MercuryDPM: oomph::TreeBasedRefineableMeshBase Class Reference
oomph::TreeBasedRefineableMeshBase Class Reference abstract
Base class for tree-based refineable meshes.
#include <refineable_mesh.h>
Public Member Functions
TreeBasedRefineableMeshBase ()
Constructor.
TreeBasedRefineableMeshBase (const TreeBasedRefineableMeshBase &dummy)=delete
Broken copy constructor.
void operator= (const TreeBasedRefineableMeshBase &)=delete
Broken assignment operator.
virtual ~TreeBasedRefineableMeshBase ()
Empty Destructor:
void adapt (const Vector< double > &elemental_error)
void p_adapt (const Vector< double > &elemental_error)
void refine_uniformly (DocInfo &doc_info)
Refine mesh uniformly and doc process.
void refine_uniformly ()
Refine mesh uniformly.
void p_refine_uniformly (DocInfo &doc_info)
p-refine mesh uniformly and doc process
void p_refine_uniformly ()
p-refine mesh uniformly
unsigned unrefine_uniformly ()
void p_unrefine_uniformly (DocInfo &doc_info)
p-unrefine mesh uniformly
virtual void setup_tree_forest ()=0
Set up the tree forest associated with the Mesh (if any)
TreeForest * forest_pt ()
Return pointer to the Forest represenation of the mesh.
void doc_adaptivity_targets (std::ostream &outfile)
Doc the targets for mesh adaptation.
unsigned & max_refinement_level ()
Access fct for max. permissible refinement level (relative to base mesh)
unsigned & min_refinement_level ()
Access fct for min. permissible refinement level (relative to base mesh)
unsigned & max_p_refinement_level ()
unsigned & min_p_refinement_level ()
virtual void adapt_mesh (DocInfo &doc_info)
virtual void adapt_mesh ()
void p_adapt_mesh (DocInfo &doc_info)
void p_adapt_mesh ()
virtual void refine_selected_elements (const Vector< unsigned > &elements_to_be_refined)
virtual void refine_selected_elements (const Vector< RefineableElement * > &elements_to_be_refined)
void p_refine_selected_elements (const Vector< unsigned > &elements_to_be_refined)
p-refine mesh by refining the elements identified by their numbers.
void p_refine_selected_elements (const Vector< PRefineableElement * > &elements_to_be_refined_pt)
p-refine mesh by refining the elements identified by their pointers.
virtual void refine_base_mesh_as_in_reference_mesh (TreeBasedRefineableMeshBase *const &ref_mesh_pt)
Refine to same degree as the reference mesh.
virtual bool refine_base_mesh_as_in_reference_mesh_minus_one (TreeBasedRefineableMeshBase *const &ref_mesh_pt)
virtual void refine_as_in_reference_mesh (TreeBasedRefineableMeshBase *const &ref_mesh_pt)
virtual void get_refinement_levels (unsigned &min_refinement_level, unsigned &max_refinement_level)
Get max/min refinement levels in mesh.
virtual void get_elements_at_refinement_level (unsigned &refinement_level, Vector< RefineableElement * > &level_elements)
virtual void get_refinement_pattern (Vector< Vector< unsigned >> &to_be_refined)
void refine_base_mesh (Vector< Vector< unsigned >> &to_be_refined)
Refine base mesh according to specified refinement pattern.
virtual void refine (std::ifstream &restart_file)
Refine mesh according to refinement pattern in restart file.
virtual void dump_refinement (std::ostream &outfile)
Dump refinement pattern to allow for rebuild.
virtual void read_refinement (std::ifstream &restart_file, Vector< Vector< unsigned >> &to_be_refined)
Read refinement pattern to allow for rebuild.
unsigned uniform_refinement_level_when_pruned () const
unsigned & uniform_refinement_level_when_pruned ()
Level to which the mesh was uniformly refined when it was pruned.
Public Member Functions inherited from oomph::RefineableMeshBase
bool adapt_flag ()
RefineableMeshBase ()
RefineableMeshBase (const RefineableMeshBase &dummy)=delete
Broken copy constructor.
void operator= (const RefineableMeshBase &)=delete
Broken assignment operator.
virtual ~RefineableMeshBase ()
Empty Destructor:
unsigned nrefined ()
Access fct for number of elements that were refined.
unsigned nunrefined ()
Access fct for number of elements that were unrefined.
unsigned & nrefinement_overruled ()
unsigned & max_keep_unrefined ()
ErrorEstimator *& spatial_error_estimator_pt ()
Access to spatial error estimator.
ErrorEstimator * spatial_error_estimator_pt () const
Access to spatial error estimator (const version.
double & min_permitted_error ()
double & max_permitted_error ()
double & min_error ()
double & max_error ()
DocInfo *& doc_info_pt ()
Access fct for pointer to DocInfo.
void enable_adaptation ()
Enable adaptation.
void disable_adaptation ()
Disable adaptation.
void enable_p_adaptation ()
Enable adaptation.
void disable_p_adaptation ()
Disable adaptation.
void enable_additional_synchronisation_of_hanging_nodes ()
Enable additional synchronisation of hanging nodes.
void disable_additional_synchronisation_of_hanging_nodes ()
Disable additional synchronisation of hanging nodes.
bool is_adaptation_enabled () const
Return whether the mesh is to be adapted.
bool is_p_adaptation_enabled () const
Return whether the mesh is to be adapted.
bool is_additional_synchronisation_of_hanging_nodes_disabled () const
Return whether additional synchronisation is enabled.
DocInfo doc_info ()
Access fct for DocInfo.
void p_unrefine_uniformly (DocInfo &doc_info)
p-unrefine mesh uniformly
Public Member Functions inherited from oomph::Mesh
Mesh ()
Default constructor.
Mesh (const Vector< Mesh * > &sub_mesh_pt)
void merge_meshes (const Vector< Mesh * > &sub_mesh_pt)
virtual void setup_boundary_element_info ()
virtual void setup_boundary_element_info (std::ostream &outfile)
virtual void reset_boundary_element_info (Vector< unsigned > &ntmp_boundary_elements, Vector< Vector< unsigned >> &ntmp_boundary_elements_in_region, Vector< FiniteElement * > &deleted_elements)
Virtual function to perform the reset boundary elements info rutines.
template<class BULK_ELEMENT >
void doc_boundary_coordinates (const unsigned &b, std::ofstream &the_file)
virtual void scale_mesh (const double &factor)
Mesh (const Mesh &dummy)=delete
Broken copy constructor.
void operator= (const Mesh &)=delete
Broken assignment operator.
virtual ~Mesh ()
Virtual Destructor to clean up all memory.
void flush_element_and_node_storage ()
void flush_element_storage ()
void flush_node_storage ()
Node *& node_pt (const unsigned long &n)
Return pointer to global node n.
Node * node_pt (const unsigned long &n) const
Return pointer to global node n (const version)
GeneralisedElement *& element_pt (const unsigned long &e)
Return pointer to element e.
GeneralisedElement * element_pt (const unsigned long &e) const
Return pointer to element e (const version)
const Vector< GeneralisedElement * > & element_pt () const
Return reference to the Vector of elements.
Vector< GeneralisedElement * > & element_pt ()
Return reference to the Vector of elements.
FiniteElement * finite_element_pt (const unsigned &e) const
Node *& boundary_node_pt (const unsigned &b, const unsigned &n)
Return pointer to node n on boundary b.
Node * boundary_node_pt (const unsigned &b, const unsigned &n) const
Return pointer to node n on boundary b.
void set_nboundary (const unsigned &nbound)
Set the number of boundaries in the mesh.
void remove_boundary_nodes ()
Clear all pointers to boundary nodes.
void remove_boundary_nodes (const unsigned &b)
void remove_boundary_node (const unsigned &b, Node *const &node_pt)
Remove a node from the boundary b.
void add_boundary_node (const unsigned &b, Node *const &node_pt)
Add a (pointer to) a node to the b-th boundary.
void copy_boundary_node_data_from_nodes ()
bool boundary_coordinate_exists (const unsigned &i) const
Indicate whether the i-th boundary has an intrinsic coordinate.
unsigned long nelement () const
Return number of elements in the mesh.
unsigned long nnode () const
Return number of nodes in the mesh.
unsigned ndof_types () const
Return number of dof types in mesh.
unsigned elemental_dimension () const
Return number of elemental dimension in mesh.
unsigned nodal_dimension () const
Return number of nodal dimension in mesh.
void add_node_pt (Node *const &node_pt)
Add a (pointer to a) node to the mesh.
void add_element_pt (GeneralisedElement *const &element_pt)
Add a (pointer to) an element to the mesh.
virtual void node_update (const bool &update_all_solid_nodes=false)
virtual void reorder_nodes (const bool &use_old_ordering=true)
virtual void get_node_reordering (Vector< Node * > &reordering, const bool &use_old_ordering=true) const
template<class BULK_ELEMENT , template< class > class FACE_ELEMENT>
void build_face_mesh (const unsigned &b, Mesh *const &face_mesh_pt)
unsigned self_test ()
Self-test: Check elements and nodes. Return 0 for OK.
void max_and_min_element_size (double &max_size, double &min_size)
double total_size ()
void check_inverted_elements (bool &mesh_has_inverted_elements, std::ofstream &inverted_element_file)
void check_inverted_elements (bool &mesh_has_inverted_elements)
unsigned check_for_repeated_nodes (const double &epsilon=1.0e-12)
Vector< Node * > prune_dead_nodes ()
unsigned nboundary () const
Return number of boundaries.
unsigned long nboundary_node (const unsigned &ibound) const
Return number of nodes on a particular boundary.
FiniteElement * boundary_element_pt (const unsigned &b, const unsigned &e) const
Return pointer to e-th finite element on boundary b.
Node * get_some_non_boundary_node () const
unsigned nboundary_element (const unsigned &b) const
Return number of finite elements that are adjacent to boundary b.
int face_index_at_boundary (const unsigned &b, const unsigned &e) const
virtual void dump (std::ofstream &dump_file, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
void dump (const std::string &dump_file_name, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
virtual void read (std::ifstream &restart_file)
Read solution from restart file.
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
void output (std::ostream &outfile)
Output for all elements.
void output (std::ostream &outfile, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output (FILE *file_pt)
Output for all elements (C-style output)
void output (FILE *file_pt, const unsigned &nplot)
Output at f(n_plot) points in each element (C-style output)
void output (const std::string &output_filename)
Output for all elements.
void output (const std::string &output_filename, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt)
Output a given Vector function at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt)
void output_boundaries (std::ostream &outfile)
Output the nodes on the boundaries (into separate tecplot zones)
void output_boundaries (const std::string &output_filename)
void assign_initial_values_impulsive ()
Assign initial values for an impulsive start.
void shift_time_values ()
void calculate_predictions ()
void set_nodal_and_elemental_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
virtual void set_mesh_level_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void set_consistent_pinned_values_for_continuation (ContinuationStorageScheme *const &continuation_stepper_pt)
Set consistent values for pinned data in continuation.
bool does_pointer_correspond_to_mesh_data (double *const &parameter_pt)
Does the double pointer correspond to any mesh data.
void set_nodal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
Set the timestepper associated with the nodal data in the mesh.
void set_elemental_internal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
virtual void compute_norm (double &norm)
virtual void compute_norm (Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Returns the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
bool is_mesh_distributed () const
Boolean to indicate if Mesh has been distributed.
OomphCommunicator * communicator_pt () const
void delete_all_external_storage ()
Wipe the storage for all externally-based elements.
Protected Member Functions
virtual void split_elements_if_required ()=0
virtual void p_refine_elements_if_required ()=0
void complete_hanging_nodes (const int &ncont_interpolated_values)
Complete the hanging node scheme recursively.
void complete_hanging_nodes_recursively (Node *&nod_pt, Vector< Node * > &master_nodes, Vector< double > &hang_weights, const int &ival)
Auxiliary routine for recursive hanging node completion.
Protected Member Functions inherited from oomph::Mesh
unsigned long assign_global_eqn_numbers (Vector< double * > &Dof_pt)
Assign (global) equation numbers to the nodes.
void describe_dofs (std::ostream &out, const std::string &current_string) const
void describe_local_dofs (std::ostream &out, const std::string &current_string) const
void assign_local_eqn_numbers (const bool &store_local_dof_pt)
Assign local equation numbers in all elements.
void convert_to_boundary_node (Node *&node_pt, const Vector< FiniteElement * > &finite_element_pt)
void convert_to_boundary_node (Node *&node_pt)
Protected Attributes
unsigned Uniform_refinement_level_when_pruned
Level to which the mesh was uniformly refined when it was pruned.
unsigned Max_refinement_level
Max. permissible refinement level (relative to base mesh)
unsigned Min_refinement_level
Min. permissible refinement level (relative to base mesh)
unsigned Max_p_refinement_level
Max. permissible p-refinement level (relative to base mesh)
unsigned Min_p_refinement_level
Min. permissible p-refinement level (relative to base mesh)
TreeForest * Forest_pt
Forest representation of the mesh.
Protected Attributes inherited from oomph::RefineableMeshBase
ErrorEstimator * Spatial_error_estimator_pt
Pointer to spatial error estimator.
double Max_permitted_error
Max. error (i.e. split elements if their error is larger)
double Min_permitted_error
Min. error (i.e. (try to) merge elements if their error is smaller)
double Min_error
Min.actual error.
double Max_error
Max. actual error.
unsigned Nrefined
Stats: Number of elements that were refined.
unsigned Nunrefined
Stats: Number of elements that were unrefined.
bool Adapt_flag
Flag that requests adaptation.
bool P_adapt_flag
Flag that requests p-adaptation.
bool Additional_synchronisation_of_hanging_nodes_not_required
Flag that disables additional synchronisation of hanging nodes.
DocInfo * Doc_info_pt
Pointer to DocInfo.
unsigned Max_keep_unrefined
unsigned Nrefinement_overruled
Protected Attributes inherited from oomph::Mesh
Vector< Vector< Node * > > Boundary_node_pt
bool Lookup_for_elements_next_boundary_is_setup
Vector< Vector< FiniteElement * > > Boundary_element_pt
Vector< Vector< int > > Face_index_at_boundary
Vector< Node * > Node_pt
Vector of pointers to nodes.
Vector< GeneralisedElement * > Element_pt
Vector of pointers to generalised elements.
std::vector< bool > Boundary_coordinate_exists
Additional Inherited Members
Public Types inherited from oomph::Mesh
typedef void(FiniteElement::* SteadyExactSolutionFctPt) (const Vector< double > &x, Vector< double > &soln)
typedef void(FiniteElement::* UnsteadyExactSolutionFctPt) (const double &time, const Vector< double > &x, Vector< double > &soln)
Static Public Attributes inherited from oomph::Mesh
static Steady< 0 > Default_TimeStepper
The Steady Timestepper.
static bool Suppress_warning_about_empty_mesh_level_time_stepper_function
Static boolean flag to control warning about mesh level timesteppers.
Detailed Description
Base class for tree-based refineable meshes.
///////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////
Constructor & Destructor Documentation
TreeBasedRefineableMeshBase() [1/2]
oomph::TreeBasedRefineableMeshBase::TreeBasedRefineableMeshBase () inline
Constructor.
     {
       // Max/min refinement levels
       Max_refinement_level = 5;
       Min_refinement_level = 0;
       // Max/min p-refinement levels
       Max_p_refinement_level = 7;
       Min_p_refinement_level = 2;
       // Stats
       Nrefined = 0;
       Nunrefined = 0;
       // Where do I write the documatation of the refinement process?
       Doc_info_pt = 0;
       // Initialise the forest pointer to NULL
       Forest_pt = 0;
       // Mesh hasn't been pruned yet
       Uniform_refinement_level_when_pruned = 0;
     }
References oomph::RefineableMeshBase::Doc_info_pt, Forest_pt, Max_p_refinement_level, Max_refinement_level, Min_p_refinement_level, Min_refinement_level, oomph::RefineableMeshBase::Nrefined, oomph::RefineableMeshBase::Nunrefined, and Uniform_refinement_level_when_pruned.
TreeBasedRefineableMeshBase() [2/2]
oomph::TreeBasedRefineableMeshBase::TreeBasedRefineableMeshBase (const TreeBasedRefineableMeshBase & dummy) delete
Broken copy constructor.
~TreeBasedRefineableMeshBase()
virtual oomph::TreeBasedRefineableMeshBase::~TreeBasedRefineableMeshBase () inline virtual
Empty Destructor:
     {
       // Kill the forest if there is one
       if (Forest_pt != 0)
       {
         delete Forest_pt;
         Forest_pt = 0;
       }
     }
References Forest_pt.
Member Function Documentation
adapt()
void oomph::TreeBasedRefineableMeshBase::adapt (const Vector< double > & elemental_error) virtual
Adapt mesh: Refine elements whose error is lager than err_max and (try to) unrefine those whose error is smaller than err_min
Do adaptive refinement for mesh.
Pass Vector of error estimates for all elements.
Refine those whose errors exceeds the threshold
(Try to) unrefine those whose errors is less than threshold (only possible if the three brothers also want to be unrefined, of course.)
Update the nodal positions in the whole lot
Store # of refined/unrefined elements.
Doc refinement process (if required)
Implements oomph::RefineableMeshBase.
Reimplemented in oomph::RefineableQuadFromTriangleMesh< ELEMENT >.
   {
     // Set the refinement tolerance to be the max permissible error
     double refine_tol = max_permitted_error();
     // Set the unrefinement tolerance to be the min permissible error
     double unrefine_tol = min_permitted_error();
     // Setup doc info
     DocInfo local_doc_info;
     if (doc_info_pt() == 0)
     {
       local_doc_info.disable_doc();
     }
     else
     {
       local_doc_info = doc_info();
     }
     // Check that the errors make sense
     if (refine_tol <= unrefine_tol)
     {
       std::ostringstream error_stream;
       error_stream << "Refinement tolerance <= Unrefinement tolerance"
                    << refine_tol << " " << unrefine_tol << std::endl
                    << "doesn't make sense and will almost certainly crash"
                    << std::endl
                    << "this beautiful code!" << std::endl;
       throw OomphLibError(
         error_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
     // Select elements for refinement and unrefinement
     //================================================
     // Reset counter for number of elements that would like to be
     // refined further but can't
     nrefinement_overruled() = 0;
     // Note: Yes, this needs to be a map because we'll have to check
     // the refinement wishes of brothers (who we only access via pointers)
     std::map<RefineableElement*, bool> wants_to_be_unrefined;
     // Initialise a variable to store the number of elements for refinment
     unsigned n_refine = 0;
     // Loop over all elements and mark them according to the error criterion
     unsigned long Nelement = this->nelement();
     for (unsigned long e = 0; e < Nelement; e++)
     {
       // (Cast) pointer to the element
       RefineableElement* el_pt =
         dynamic_cast<RefineableElement*>(this->element_pt(e));
       // Initially element is not to be refined
       el_pt->deselect_for_refinement();
       // If the element error exceeds the threshold ...
       if (elemental_error[e] > refine_tol)
       {
         // ... and its refinement level is less than the maximum desired level
         // mark is to be refined
         if ((el_pt->refinement_is_enabled()) &&
             (el_pt->refinement_level() < max_refinement_level()))
         {
           el_pt->select_for_refinement();
           n_refine++;
         }
         // ... otherwise mark it as having been over-ruled
         else
         {
           nrefinement_overruled() += 1;
         }
       }
       // Now worry about unrefinement (first pass):
       // Is my error too small AND do I have a father?
       if ((elemental_error[e] < unrefine_tol) &&
           (el_pt->tree_pt()->father_pt() != 0))
       {
         // Flag to indicate whether to unrefine
         bool unrefine = true;
         unsigned n_sons = el_pt->tree_pt()->father_pt()->nsons();
         // Are all brothers leaf nodes?
         for (unsigned ison = 0; ison < n_sons; ison++)
         {
           // (At least) one brother is not a leaf: end of story; we're not doing
           // it (= the unrefinement)
           if (!(el_pt->tree_pt()->father_pt()->son_pt(ison)->is_leaf()))
           {
             unrefine = false;
           }
         }
         // Don't allow unrefinement of elements that would become larger
         // than the minimum legal refinement level
         if (el_pt->refinement_level() - 1 < min_refinement_level())
         {
           unrefine = false;
         }
         // So, all things considered, is the element eligbible for refinement?
         if (unrefine)
         {
           wants_to_be_unrefined[el_pt] = true;
         }
         else
         {
           wants_to_be_unrefined[el_pt] = false;
         }
       }
     }
     oomph_info << " \n Number of elements to be refined: " << n_refine
                << std::endl;
     oomph_info << " \n Number of elements whose refinement was overruled: "
                << nrefinement_overruled() << std::endl;
     // Second pass for unrefinement --- an element cannot be unrefined unless
     // all brothers want to be unrefined.
     // Loop over all elements again and let the first set of sons check if their
     // brothers also want to be unrefined
     unsigned n_unrefine = 0;
     for (unsigned long e = 0; e < Nelement; e++)
     {
       //(Cast) pointer to the element
       RefineableElement* el_pt =
         dynamic_cast<RefineableElement*>(this->element_pt(e));
       // hierher: This is a bit naughty... We want to put the
       // first son in charge -- the statement below assumes (correctly) that the
       // enumeration of all (!) trees starts with son types.
       // This is correct for oc and quadtrees but will bite us if we
       // ever introduce other trees if/when we accidentally break this
       // tacit assumption. Not sure what to do about it for
       // now other than leaving it hierher-ed...
       if (el_pt->tree_pt()->son_type() == OcTreeNames::LDB)
       {
         // Do all sons want to be unrefined?
         bool unrefine = true;
         unsigned n_sons = el_pt->tree_pt()->father_pt()->nsons();
         for (unsigned ison = 0; ison < n_sons; ison++)
         {
           if (!(wants_to_be_unrefined[dynamic_cast<RefineableElement*>(
                 el_pt->tree_pt()->father_pt()->son_pt(ison)->object_pt())]))
           {
             // One guy isn't cooperating and spoils the party.
             unrefine = false;
           }
         }
         // Tell father that his sons need to be merged
         if (unrefine)
         {
           el_pt->tree_pt()
             ->father_pt()
             ->object_pt()
             ->select_sons_for_unrefinement();
           n_unrefine += n_sons;
         }
         // Otherwise mark the sons as not to be touched
         else
         {
           el_pt->tree_pt()
             ->father_pt()
             ->object_pt()
             ->deselect_sons_for_unrefinement();
         }
       }
     }
     oomph_info << " \n Number of elements to be merged : " << n_unrefine
                << std::endl
                << std::endl;
     // Now do the actual mesh adaptation
     //---------------------------------
     // Check whether its worth our while
     // Either some elements want to be refined,
     // or the number that want to be unrefined are greater than the
     // specified tolerance
     // In a parallel job, it is possible that one process may not have
     // any elements to refine, BUT a neighbouring process may refine an
     // element which changes the hanging status of a node that is on
     // both processes (i.e. a halo(ed) node).  To get around this issue,
     // ALL processes need to call adapt_mesh if ANY refinement is to
     // take place anywhere.
     unsigned total_n_refine = 0;
 #ifdef OOMPH_HAS_MPI
     // Sum n_refine across all processors
     if (this->is_mesh_distributed())
     {
       MPI_Allreduce(&n_refine,
                     &total_n_refine,
                     1,
                     MPI_UNSIGNED,
                     MPI_SUM,
                     Comm_pt->mpi_comm());
     }
     else
     {
       total_n_refine = n_refine;
     }
 #else
     total_n_refine = n_refine;
 #endif
     // There may be some issues with unrefinement too, but I have not
     // been able to come up with an example (either in my head or in a
     // particular problem) where anything has arisen. I can see that
     // there may be an issue if n_unrefine differs across processes so
     // that (total_n_unrefine > max_keep_unrefined()) on some but not
     // all processes. I haven't seen any examples of this yet so the
     // following code may or may not work!  (Andy, 06/03/08)
     unsigned total_n_unrefine = 0;
 #ifdef OOMPH_HAS_MPI
     // Sum n_unrefine across all processors
     if (this->is_mesh_distributed())
     {
       MPI_Allreduce(&n_unrefine,
                     &total_n_unrefine,
                     1,
                     MPI_UNSIGNED,
                     MPI_SUM,
                     Comm_pt->mpi_comm());
     }
     else
     {
       total_n_unrefine = n_unrefine;
     }
 #else
     total_n_unrefine = n_unrefine;
 #endif
     oomph_info << "---> " << total_n_refine << " elements to be refined, and "
                << total_n_unrefine << " to be unrefined, in total.\n"
                << std::endl;
     if ((total_n_refine > 0) || (total_n_unrefine > max_keep_unrefined()))
     {
 #ifdef PARANOID
 #ifdef OOMPH_HAS_MPI
       // Sanity check: Each processor checks if the enforced unrefinement of
       // its haloed element is matched by enforced unrefinement of the
       // corresponding halo elements on the other processors.
       if (this->is_mesh_distributed())
       {
         // Store number of processors and current process
         MPI_Status status;
         int n_proc = Comm_pt->nproc();
         int my_rank = Comm_pt->my_rank();
         // Loop over processes: Each processor sends unrefinement pattern
         // for halo elements with processor d to processor d where it's
         // compared against the unrefinement pattern for the corresponding
         // haloed elements
         for (int d = 0; d < n_proc; d++)
         {
           // No halo with self: Send unrefinement info to proc d
           if (d != my_rank)
           {
             // Get the vector of halo elements whose non-halo counterpart
             // are on processor d
             Vector<GeneralisedElement*> halo_elem_pt(this->halo_element_pt(d));
             // Create vector containing (0)1 to indicate that
             // halo element is (not) to be unrefined
             unsigned nhalo = halo_elem_pt.size();
             Vector<int> halo_to_be_unrefined(nhalo, 0);
             for (unsigned e = 0; e < nhalo; e++)
             {
               if (dynamic_cast<RefineableElement*>(halo_elem_pt[e])
                     ->sons_to_be_unrefined())
               {
                 halo_to_be_unrefined[e] = 1;
               }
             }
             // Trap the case when there are no halo elements
             // so that we don't get a segfault in the MPI send
             if (nhalo > 0)
             {
               // Send it across to proc d
               MPI_Send(&halo_to_be_unrefined[0],
                        nhalo,
                        MPI_INT,
                        d,
                        0,
                        Comm_pt->mpi_comm());
             }
           }
           // else (d=my_rank): Receive unrefinement pattern from all
           // other processors (dd)
           else
           {
             // Loop over other processors
             for (int dd = 0; dd < n_proc; dd++)
             {
               // No halo with yourself
               if (dd != d)
               {
                 // Get the vector of haloed elements on current processor
                 // with processor dd
                 Vector<GeneralisedElement*> haloed_elem_pt(
                   this->haloed_element_pt(dd));
                 // Ask processor dd to send vector containing (0)1 for
                 // halo element with current processor to be (not)unrefined
                 unsigned nhaloed = haloed_elem_pt.size();
                 Vector<int> halo_to_be_unrefined(nhaloed);
                 // Trap to catch the case that there are no haloed elements
                 if (nhaloed > 0)
                 {
                   // Receive unrefinement pattern of haloes from proc dd
                   MPI_Recv(&halo_to_be_unrefined[0],
                            nhaloed,
                            MPI_INT,
                            dd,
                            0,
                            Comm_pt->mpi_comm(),
                            &status);
                 }
                 // Check it
                 for (unsigned e = 0; e < nhaloed; e++)
                 {
                   if (((halo_to_be_unrefined[e] == 0) &&
                        (dynamic_cast<RefineableElement*>(haloed_elem_pt[e])
                           ->sons_to_be_unrefined())) ||
                       ((halo_to_be_unrefined[e] == 1) &&
                        (!dynamic_cast<RefineableElement*>(haloed_elem_pt[e])
                            ->sons_to_be_unrefined())))
                   {
                     std::ostringstream error_message;
                     error_message
                       << "Error in unrefinement: \n"
                       << "Haloed element: " << e << " on proc " << my_rank
                       << " \n"
                       << "wants to be unrefined whereas its halo counterpart "
                          "on\n"
                       << "proc " << dd << " doesn't (or vice versa)...\n"
                       << "This is most likely because the error estimator\n"
                       << "has not assigned the same errors to halo and haloed\n"
                       << "elements -- it ought to!\n";
                     throw OomphLibError(error_message.str(),
                                         OOMPH_CURRENT_FUNCTION,
                                         OOMPH_EXCEPTION_LOCATION);
                   }
                 }
               }
             }
           }
         }
         // Loop over processes: Each processor sends refinement pattern
         // for halo elements with processor d to processor d where it's
         // compared against the refinement pattern for the corresponding
         // haloed elements
         for (int d = 0; d < n_proc; d++)
         {
           // No halo with self: Send refinement info to proc d
           if (d != my_rank)
           {
             // Get the vector of halo elements whose non-halo counterpart
             // are on processor d
             Vector<GeneralisedElement*> halo_elem_pt(this->halo_element_pt(d));
             // Create vector containing (0)1 to indicate that
             // halo element is (not) to be refined
             unsigned nhalo = halo_elem_pt.size();
             Vector<int> halo_to_be_refined(nhalo, 0);
             for (unsigned e = 0; e < nhalo; e++)
             {
               if (dynamic_cast<RefineableElement*>(halo_elem_pt[e])
                     ->to_be_refined())
               {
                 halo_to_be_refined[e] = 1;
               }
             }
             // Trap the case when there are no halo elements
             // so that we don't get a segfault in the MPI send
             if (nhalo > 0)
             {
               // Send it across to proc d
               MPI_Send(&halo_to_be_refined[0],
                        nhalo,
                        MPI_INT,
                        d,
                        0,
                        Comm_pt->mpi_comm());
             }
           }
           // else (d=my_rank): Receive refinement pattern from all
           // other processors (dd)
           else
           {
             // Loop over other processors
             for (int dd = 0; dd < n_proc; dd++)
             {
               // No halo with yourself
               if (dd != d)
               {
                 // Get the vector of haloed elements on current processor
                 // with processor dd
                 Vector<GeneralisedElement*> haloed_elem_pt(
                   this->haloed_element_pt(dd));
                 // Ask processor dd to send vector containing (0)1 for
                 // halo element with current processor to be (not)refined
                 unsigned nhaloed = haloed_elem_pt.size();
                 Vector<int> halo_to_be_refined(nhaloed);
                 // Trap to catch the case that there are no haloed elements
                 if (nhaloed > 0)
                 {
                   // Receive unrefinement pattern of haloes from proc dd
                   MPI_Recv(&halo_to_be_refined[0],
                            nhaloed,
                            MPI_INT,
                            dd,
                            0,
                            Comm_pt->mpi_comm(),
                            &status);
                 }
                 // Check it
                 for (unsigned e = 0; e < nhaloed; e++)
                 {
                   if (((halo_to_be_refined[e] == 0) &&
                        (dynamic_cast<RefineableElement*>(haloed_elem_pt[e])
                           ->to_be_refined())) ||
                       ((halo_to_be_refined[e] == 1) &&
                        (!dynamic_cast<RefineableElement*>(haloed_elem_pt[e])
                            ->to_be_refined())))
                   {
                     std::ostringstream error_message;
                     error_message
                       << "Error in refinement: \n"
                       << "Haloed element: " << e << " on proc " << my_rank
                       << " \n"
                       << "wants to be refined whereas its halo counterpart on\n"
                       << "proc " << dd << " doesn't (or vice versa)...\n"
                       << "This is most likely because the error estimator\n"
                       << "has not assigned the same errors to halo and haloed\n"
                       << "elements -- it ought to!\n";
                     throw OomphLibError(error_message.str(),
                                         OOMPH_CURRENT_FUNCTION,
                                         OOMPH_EXCEPTION_LOCATION);
                   }
                 }
               }
             }
           }
         }
       }
 #endif
 #endif
       // Perform the actual adaptation
       adapt_mesh(local_doc_info);
       // The number of refineable elements is still local to each process
       Nunrefined = n_unrefine;
       Nrefined = n_refine;
     }
     // If not worthwhile, say so but still reorder nodes and kill
     // external storage for consistency in parallel computations
     else
     {
 #ifdef OOMPH_HAS_MPI
       // Delete any external element storage - any interaction will still
       // be set up on the fly again, so we need to get rid of old information.
       // This particularly causes problems in multi-domain examples where
       // we decide not to refine one of the meshes
       this->delete_all_external_storage();
 #endif
       // Reorder the nodes within the mesh's node vector
       // to establish a standard ordering regardless of the sequence
       // of mesh refinements -- this is required to allow dump/restart
       // on refined meshes
       this->reorder_nodes();
 #ifdef OOMPH_HAS_MPI
       // Now (re-)classify halo and haloed nodes and synchronise hanging
       // nodes
       // This is required in cases where delete_all_external_storage()
       // made dependent nodes to external halo nodes nonhanging.
       if (this->is_mesh_distributed())
       {
         DocInfo doc_info;
         doc_info.disable_doc();
         classify_halo_and_haloed_nodes(doc_info, doc_info.is_doc_enabled());
       }
 #endif
       if (n_refine == 0)
       {
         oomph_info << " Not enough benefit in adapting mesh." << std::endl
                    << std::endl;
       }
       Nunrefined = 0;
       Nrefined = 0;
     }
   }
References adapt_mesh(), oomph::Mesh::delete_all_external_storage(), oomph::RefineableElement::deselect_for_refinement(), oomph::RefineableElement::deselect_sons_for_unrefinement(), oomph::DocInfo::disable_doc(), oomph::RefineableMeshBase::doc_info(), oomph::RefineableMeshBase::doc_info_pt(), e(), oomph::Mesh::element_pt(), oomph::Tree::father_pt(), oomph::DocInfo::is_doc_enabled(), oomph::Tree::is_leaf(), oomph::Mesh::is_mesh_distributed(), oomph::OcTreeNames::LDB, oomph::RefineableMeshBase::max_keep_unrefined(), oomph::RefineableMeshBase::max_permitted_error(), max_refinement_level(), oomph::RefineableMeshBase::min_permitted_error(), min_refinement_level(), oomph::Mesh::nelement(), oomph::RefineableMeshBase::Nrefined, oomph::RefineableMeshBase::nrefinement_overruled(), oomph::Tree::nsons(), oomph::RefineableMeshBase::Nunrefined, oomph::Tree::object_pt(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::oomph_info, oomph::RefineableElement::refinement_is_enabled(), oomph::RefineableElement::refinement_level(), oomph::Mesh::reorder_nodes(), oomph::RefineableElement::select_for_refinement(), oomph::RefineableElement::select_sons_for_unrefinement(), oomph::Tree::son_pt(), oomph::Tree::son_type(), and oomph::RefineableElement::tree_pt().
Referenced by unrefine_uniformly().
adapt_mesh() [1/2]
virtual void oomph::TreeBasedRefineableMeshBase::adapt_mesh () inline virtual
Perform the actual tree-based mesh adaptation. A simple wrapper to call the function without documentation.
     {
       // Create a dummy doc_info object
       DocInfo doc_info;
       doc_info.directory() = "";
       doc_info.disable_doc();
       // Call the other adapt mesh
       adapt_mesh(doc_info);
     }
References oomph::DocInfo::directory(), oomph::DocInfo::disable_doc(), and oomph::RefineableMeshBase::doc_info().
Referenced by adapt(), refine_base_mesh(), refine_selected_elements(), and refine_uniformly().
adapt_mesh() [2/2]
void oomph::TreeBasedRefineableMeshBase::adapt_mesh (DocInfo & doc_info) virtual
Perform the actual tree-based mesh adaptation, documenting the progress in the directory specified in DocInfo object.
Adapt mesh, which exists in two representations, namely as:
a FE mesh
a forest of Oc or QuadTrees
Refinement/derefinement process is documented (in tecplot-able form) if requested.
Procedure:
Loop over all elements and do the refinement for those who want to be refined. Note: Refinement/splitting only allocates elements but doesn't build them.
Build the new elements (i.e. give them nodes (create new ones where necessary), assign boundary conditions, and add nodes to mesh and mesh boundaries.
For all nodes that were hanging on the previous mesh (and are still marked as such), fill in their nodal values (consistent with the current hanging node scheme) to make sure they are fully functional, should they have become non-hanging during the mesh-adaptation. Then mark the nodes as non-hanging.
Unrefine selected elements (which may cause nodes to be re-built).
Add the new elements to the mesh (by completely overwriting the old Vector of elements).
Delete any nodes that have become obsolete.
Mark up hanging nodes and setup hanging node scheme (incl. recursive cleanup for hanging nodes that depend on other hanging nodes).
Adjust position of hanging nodes to make sure their position is consistent with the FE-based represenetation of their larger neighbours.
run a quick self-test on the neighbour finding scheme and check the integrity of the elements (if PARANOID)
doc hanging node status, boundary conditions, neighbour scheme if requested.
After adaptation, all nodes (whether new or old) have up-to-date current and previous values.
If refinement process is being documented, the following information is documented:
The files
"neighbours.dat"
"all_nodes.dat"
"new_nodes.dat"
"hang_nodes_*.dat" where the * denotes a direction (n,s,e,w) in 2D or (r,l,u,d,f,b) in 3D
can be viewed with
QHangingNodes.mcr
The file
"hangnodes_withmasters.dat"
can be viewed with
QHangingNodesWithMasters.mcr
to check the hanging node status.
The neighbour status of the elements is documented in
"neighbours.dat"
and can be viewed with
QuadTreeNeighbours.mcr
Update the boundary element info – this can be a costly procedure and for this reason the mesh writer might have decided not to set up this scheme. If so, we won't change this and suppress its creation...
   {
 #ifdef OOMPH_HAS_MPI
     // Delete any external element storage before performing the adaptation
     // (in particular, external halo nodes that are on mesh boundaries)
     this->delete_all_external_storage();
 #endif
     // Only perform the adapt step if the mesh has any elements.  This is
     // relevant in a distributed problem with multiple meshes, where a
     // particular process may not have any elements on a particular submesh.
     if (this->nelement() > 0)
     {
       // Pointer to mesh needs to be passed to some functions
       Mesh* mesh_pt = this;
       double t_start = 0.0;
       if (Global_timings::Doc_comprehensive_timings)
       {
         t_start = TimingHelpers::timer();
       }
       // Do refinement(=splitting) of elements that have been selected
       // This function encapsulates the template parameter
       this->split_elements_if_required();
       if (Global_timings::Doc_comprehensive_timings)
       {
         double t_end = TimingHelpers::timer();
         oomph_info << "Time for split_elements_if_required: " << t_end - t_start
                    << std::endl;
         t_start = TimingHelpers::timer();
       }
       // Now elements have been created -- build all the leaves
       //-------------------------------------------------------
       // Firstly put all the elements into a vector
       Vector<Tree*> leaf_nodes_pt;
       Forest_pt->stick_leaves_into_vector(leaf_nodes_pt);
       if (Global_timings::Doc_comprehensive_timings)
       {
         double t_end = TimingHelpers::timer();
         oomph_info << "Time for stick_leaves_into_vector: " << t_end - t_start
                    << std::endl;
         t_start = TimingHelpers::timer();
       }
       // If we are documenting the output, create the filename
       std::ostringstream fullname;
       std::ofstream new_nodes_file;
       if (doc_info.is_doc_enabled())
       {
         fullname << doc_info.directory() << "/new_nodes" << doc_info.number()
                  << ".dat";
         new_nodes_file.open(fullname.str().c_str());
       }
       // Build all elements and store vector of pointers to new nodes
       // (Note: build() checks if the element has been built
       // already, i.e. if it's not a new element).
       Vector<Node*> new_node_pt;
       bool was_already_built;
       unsigned long num_tree_nodes = leaf_nodes_pt.size();
       for (unsigned long e = 0; e < num_tree_nodes; e++)
       {
         // Pre-build must be performed before any elements are built
         leaf_nodes_pt[e]->object_pt()->pre_build(mesh_pt, new_node_pt);
       }
       for (unsigned long e = 0; e < num_tree_nodes; e++)
       {
         // Now do the actual build of the new elements
         leaf_nodes_pt[e]->object_pt()->build(
           mesh_pt, new_node_pt, was_already_built, new_nodes_file);
       }
       double t_end = 0.0;
       if (Global_timings::Doc_comprehensive_timings)
       {
         t_end = TimingHelpers::timer();
         oomph_info << "Time for building " << num_tree_nodes
                    << " new elements: " << t_end - t_start << std::endl;
         t_start = TimingHelpers::timer();
       }
       // Close the new nodes files, if it was opened
       if (doc_info.is_doc_enabled())
       {
         new_nodes_file.close();
       }
       // Loop over all nodes in mesh and free the dofs of those that were
       //-----------------------------------------------------------------
       // pinned only because they were hanging nodes. Also update their
       //-----------------------------------------------------------------
       // nodal values so that they contain data that is consistent
       //----------------------------------------------------------
       // with the hanging node representation
       //-------------------------------------
       // (Even if the nodal data isn't actually accessed because the node
       // is still hanging -- we don't know this yet, and this step makes
       // sure that all nodes are fully functional and up-to-date, should
       // they become non-hanging below).
       //
       //
       // However, if we have a fixed mesh and hanging nodes on the boundary
       // become non-hanging they will not necessarily respect the curvilinear
       // boundaries. This can only happen in 3D of course because it is not
       // possible to have hanging nodes on boundaries in 2D.
       // The solution is to store those nodes on the boundaries that are
       // currently hanging and then check to see whether they have changed
       // status at the end of the refinement procedure.
       // If it has changed, then we need to adjust their positions.
       const unsigned n_boundary = this->nboundary();
       const unsigned mesh_dim = this->finite_element_pt(0)->dim();
       Vector<std::set<Node*>> hanging_nodes_on_boundary_pt(n_boundary);
       unsigned long n_node = this->nnode();
       for (unsigned long n = 0; n < n_node; n++)
       {
         // Get the pointer to the node
         Node* nod_pt = this->node_pt(n);
         // Get the number of values in the node
         unsigned n_value = nod_pt->nvalue();
         // We need to find if any of the values are hanging
         bool is_hanging = nod_pt->is_hanging();
         // Loop over the values and find out whether any are hanging
         for (unsigned n = 0; n < n_value; n++)
         {
           is_hanging |= nod_pt->is_hanging(n);
         }
         // If the node is hanging then ...
         if (is_hanging)
         {
           // Unless they are turned into hanging nodes again below
           // (this might or might not happen), fill in all the necessary
           // data to make them 'proper' nodes again.
           // Reconstruct the nodal values/position from the node's
           // hanging node representation
           unsigned nt = nod_pt->ntstorage();
           Vector<double> values(n_value);
           unsigned n_dim = nod_pt->ndim();
           Vector<double> position(n_dim);
           // Loop over all history values
           for (unsigned t = 0; t < nt; t++)
           {
             nod_pt->value(t, values);
             for (unsigned i = 0; i < n_value; i++)
             {
               nod_pt->set_value(t, i, values[i]);
             }
             nod_pt->position(t, position);
             for (unsigned i = 0; i < n_dim; i++)
             {
               nod_pt->x(t, i) = position[i];
             }
           }
           // If it's an algebraic node: Update its previous nodal positions too
           AlgebraicNode* alg_node_pt = dynamic_cast<AlgebraicNode*>(nod_pt);
           if (alg_node_pt != 0)
           {
             bool update_all_time_levels = true;
             alg_node_pt->node_update(update_all_time_levels);
           }
           // If it's a Solid node, update Lagrangian coordinates
           // from its hanging node representation
           SolidNode* solid_node_pt = dynamic_cast<SolidNode*>(nod_pt);
           if (solid_node_pt != 0)
           {
             unsigned n_lagrangian = solid_node_pt->nlagrangian();
             for (unsigned i = 0; i < n_lagrangian; i++)
             {
               solid_node_pt->xi(i) = solid_node_pt->lagrangian_position(i);
             }
           }
           // Now store geometrically hanging nodes on boundaries that
           // may need updating after refinement.
           // There will only be a problem if we have 3 spatial dimensions
           if ((mesh_dim > 2) && (nod_pt->is_hanging()))
           {
             // If the node is on a boundary then add a pointer to the node
             // to our lookup scheme
             if (nod_pt->is_on_boundary())
             {
               // Storage for the boundaries on which the Node is located
               std::set<unsigned>* boundaries_pt;
               nod_pt->get_boundaries_pt(boundaries_pt);
               if (boundaries_pt != 0)
               {
                 // Loop over the boundaries and add a pointer to the node
                 // to the appropriate storage scheme
                 for (std::set<unsigned>::iterator it = boundaries_pt->begin();
                      it != boundaries_pt->end();
                      ++it)
                 {
                   hanging_nodes_on_boundary_pt[*it].insert(nod_pt);
                 }
               }
             }
           }
         } // End of is_hanging
         // Initially mark all nodes as 'non-hanging' and `obsolete'
         nod_pt->set_nonhanging();
         nod_pt->set_obsolete();
       }
       if (Global_timings::Doc_comprehensive_timings)
       {
         t_end = TimingHelpers::timer();
         oomph_info << "Time for sorting out initial hanging status: "
                    << t_end - t_start << std::endl;
         t_start = TimingHelpers::timer();
       }
       // Unrefine all the selected elements: This needs to be
       //-----------------------------------------------------
       // all elements, because the father elements are not actually leaves.
       //-------------------------------------------------------------------
       // Unrefine
       for (unsigned long e = 0; e < Forest_pt->ntree(); e++)
       {
         Forest_pt->tree_pt(e)->traverse_all(&Tree::merge_sons_if_required,
                                             mesh_pt);
       }
       if (Global_timings::Doc_comprehensive_timings)
       {
         t_end = TimingHelpers::timer();
         oomph_info << "Time for unrefinement: " << t_end - t_start << std::endl;
         t_start = TimingHelpers::timer();
       }
       // Add the newly created elements to mesh
       //---------------------------------------
       // Stick all elements into a new vector
       //(note the leaves may have changed, so this is not duplicated work)
       Vector<Tree*> tree_nodes_pt;
       Forest_pt->stick_leaves_into_vector(tree_nodes_pt);
       // Copy the elements into the mesh Vector
       num_tree_nodes = tree_nodes_pt.size();
       Element_pt.resize(num_tree_nodes);
       for (unsigned long e = 0; e < num_tree_nodes; e++)
       {
         Element_pt[e] = tree_nodes_pt[e]->object_pt();
         // Now loop over all nodes in element and mark them as non-obsolete
         // Logic: Initially all nodes in the unrefined mesh were labeled
         // as deleteable. Then we create new elements (whose newly created
         // nodes are obviously non-obsolete), and killed some other elements (by
         // by deleting them and marking the nodes that were not shared by
         // their father as obsolete. Now we loop over all the remaining
         // elements and (re-)label all their nodes as non-obsolete. This
         // saves some nodes that were regarded as obsolete by deleted
         // elements but are still required in some surviving ones
         // from a tragic early death...
         FiniteElement* this_el_pt = this->finite_element_pt(e);
         unsigned n_node = this_el_pt->nnode(); // caching pre-loop
         for (unsigned n = 0; n < n_node; n++)
         {
           this_el_pt->node_pt(n)->set_non_obsolete();
         }
       }
       if (Global_timings::Doc_comprehensive_timings)
       {
         t_end = TimingHelpers::timer();
         oomph_info << "Time for adding elements to mesh: " << t_end - t_start
                    << std::endl;
         t_start = TimingHelpers::timer();
       }
       // Cannot delete nodes that are still marked as obsolete
       // because they may still be required to assemble the hanging schemes
       //-------------------------------------------------------------------
       // Mark up hanging nodes
       //----------------------
       // Output streams for the hanging nodes
       Vector<std::ofstream*> hanging_output_files;
       // Setup the output files for hanging nodes, this must be called
       // precisely once for the forest. Note that the files will only
       // actually be opened if doc_info.is_doc_enabled() is true
       Forest_pt->open_hanging_node_files(doc_info, hanging_output_files);
       for (unsigned long e = 0; e < num_tree_nodes; e++)
       {
         // Generic setup
         tree_nodes_pt[e]->object_pt()->setup_hanging_nodes(
           hanging_output_files);
         // Element specific setup
         tree_nodes_pt[e]->object_pt()->further_setup_hanging_nodes();
       }
       // Close the hanging node files and delete the memory allocated
       // for the streams
       Forest_pt->close_hanging_node_files(doc_info, hanging_output_files);
       if (Global_timings::Doc_comprehensive_timings)
       {
         t_end = TimingHelpers::timer();
         oomph_info << "Time for setup_hanging_nodes() and "
                       "further_setup_hanging_nodes() for "
                    << num_tree_nodes << " elements: " << t_end - t_start
                    << std::endl;
         t_start = TimingHelpers::timer();
       }
       // Read out the number of continously interpolated values
       // from one of the elements (assuming it's the same in all elements)
       unsigned ncont_interpolated_values =
         tree_nodes_pt[0]->object_pt()->ncont_interpolated_values();
       // Complete the hanging nodes schemes by dealing with the
       // recursively hanging nodes
       complete_hanging_nodes(ncont_interpolated_values);
       if (Global_timings::Doc_comprehensive_timings)
       {
         t_end = TimingHelpers::timer();
         oomph_info << "Time for complete_hanging_nodes: " << t_end - t_start
                    << std::endl;
         t_start = TimingHelpers::timer();
       }
       if (Lookup_for_elements_next_boundary_is_setup)
       {
         this->setup_boundary_element_info();
       }
       if (Global_timings::Doc_comprehensive_timings)
       {
         t_end = TimingHelpers::timer();
         oomph_info << "Time for boundary element info: " << t_end - t_start
                    << std::endl;
         t_start = TimingHelpers::timer();
       }
 #ifdef PARANOID
       // Doc/check the neighbours
       //-------------------------
       Vector<Tree*> all_tree_nodes_pt;
       Forest_pt->stick_all_tree_nodes_into_vector(all_tree_nodes_pt);
       // Check the neighbours
       Forest_pt->check_all_neighbours(doc_info);
       // Check the integrity of the elements
       // -----------------------------------
       // Loop over elements and get the elemental integrity
       double max_error = 0.0;
       for (unsigned long e = 0; e < num_tree_nodes; e++)
       {
         double max_el_error;
         tree_nodes_pt[e]->object_pt()->check_integrity(max_el_error);
         // If the elemental error is greater than our maximum error
         // reset the maximum
         if (max_el_error > max_error)
         {
           max_error = max_el_error;
         }
       }
       if (max_error > RefineableElement::max_integrity_tolerance())
       {
         std::ostringstream error_stream;
         error_stream << "Mesh refined: Max. error in integrity check: "
                      << max_error << " is too big\n";
         error_stream
           << "i.e. bigger than RefineableElement::max_integrity_tolerance()="
           << RefineableElement::max_integrity_tolerance() << "\n"
           << std::endl;
         std::ofstream some_file;
         some_file.open("ProblemMesh.dat");
         for (unsigned long n = 0; n < n_node; n++)
         {
           // Get the pointer to the node
           Node* nod_pt = this->node_pt(n);
           // Get the dimension
           unsigned n_dim = nod_pt->ndim();
           // Output the coordinates
           for (unsigned i = 0; i < n_dim; i++)
           {
             some_file << this->node_pt(n)->x(i) << " ";
           }
           some_file << std::endl;
         }
         some_file.close();
         error_stream << "Doced problem mesh in ProblemMesh.dat" << std::endl;
         throw OomphLibError(
           error_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
       }
       else
       {
         oomph_info << "Mesh refined: Max. error in integrity check: "
                    << max_error << " is OK" << std::endl;
         oomph_info
           << "i.e. less than RefineableElement::max_integrity_tolerance()="
           << RefineableElement::max_integrity_tolerance() << "\n"
           << std::endl;
       }
       if (Global_timings::Doc_comprehensive_timings)
       {
         t_end = TimingHelpers::timer();
         oomph_info << "Time for (paranoid only) checking of integrity: "
                    << t_end - t_start << std::endl;
         t_start = TimingHelpers::timer();
       }
 #endif
       // Loop over all elements other than the final level and deactivate the
       // objects, essentially set the pointer that point to nodes that are
       // about to be deleted to NULL. This must take place here because nodes
       // addressed by elements that are dead but still living in the tree might
       // have been made obsolete in the last round of refinement
       for (unsigned long e = 0; e < Forest_pt->ntree(); e++)
       {
         Forest_pt->tree_pt(e)->traverse_all_but_leaves(
           &Tree::deactivate_object);
       }
       // Now we can prune the dead nodes from the mesh.
       Vector<Node*> deleted_node_pt = this->prune_dead_nodes();
       if (Global_timings::Doc_comprehensive_timings)
       {
         t_end = TimingHelpers::timer();
         oomph_info << "Time for deactivating objects and pruning nodes: "
                    << t_end - t_start << std::endl;
         t_start = TimingHelpers::timer();
       }
       // Finally: Reorder the nodes within the mesh's node vector
       // to establish a standard ordering regardless of the sequence
       // of mesh refinements -- this is required to allow dump/restart
       // on refined meshes
       this->reorder_nodes();
       if (Global_timings::Doc_comprehensive_timings)
       {
         t_end = TimingHelpers::timer();
         oomph_info << "Time for reordering " << nnode()
                    << " nodes: " << t_end - t_start << std::endl;
         t_start = TimingHelpers::timer();
       }
       // Now we can correct the nodes on boundaries that were hanging that
       // are no longer hanging
       // Only bother if we have more than two dimensions
       if (mesh_dim > 2)
       {
         // Loop over the boundaries
         for (unsigned b = 0; b < n_boundary; b++)
         {
           // Remove deleted nodes from the set
           unsigned n_del = deleted_node_pt.size();
           for (unsigned j = 0; j < n_del; j++)
           {
             hanging_nodes_on_boundary_pt[b].erase(deleted_node_pt[j]);
           }
           // If the nodes that were hanging are still hanging then remove them
           // from the set (note increment is not in for command for efficiencty)
           for (std::set<Node*>::iterator it =
                  hanging_nodes_on_boundary_pt[b].begin();
                it != hanging_nodes_on_boundary_pt[b].end();)
           {
             if ((*it)->is_hanging())
             {
               hanging_nodes_on_boundary_pt[b].erase(it++);
             }
             else
             {
               ++it;
             }
           }
           // Are there any nodes that have changed geometric hanging status
           // on the boundary
           // The slightly painful part is that we must adjust the position
           // via the macro-elements which are only available through the
           // elements and not the nodes.
           if (hanging_nodes_on_boundary_pt[b].size() > 0)
           {
             // If so we loop over all elements adjacent to the boundary
             unsigned n_boundary_element = this->nboundary_element(b);
             for (unsigned e = 0; e < n_boundary_element; ++e)
             {
               // Get a pointer to the element
               FiniteElement* el_pt = this->boundary_element_pt(b, e);
               // Do we have a solid element
               SolidFiniteElement* solid_el_pt =
                 dynamic_cast<SolidFiniteElement*>(el_pt);
               // Determine whether there is a macro element
               bool macro_present = (el_pt->macro_elem_pt() != 0);
               // Or a solid macro element
               if (solid_el_pt != 0)
               {
                 macro_present |= (solid_el_pt->undeformed_macro_elem_pt() != 0);
               }
               // Only bother to do anything if there is a macro element
               // or undeformed macro element in a SolidElement
               if (macro_present)
               {
                 // Loop over the nodes
                 // ALH: (could optimise to only loop over
                 // node associated with the boundary with more effort)
                 unsigned n_el_node = el_pt->nnode();
                 for (unsigned n = 0; n < n_el_node; n++)
                 {
                   // Cache pointer to the node
                   Node* nod_pt = el_pt->node_pt(n);
                   if (nod_pt->is_on_boundary(b))
                   {
                     // Is the Node in our set
                     std::set<Node*>::iterator it =
                       hanging_nodes_on_boundary_pt[b].find(nod_pt);
                     // If we have found the Node then update the position
                     // to be consistent with the macro-element representation
                     if (it != hanging_nodes_on_boundary_pt[b].end())
                     {
                       // Specialise local and global coordinates to 3D
                       // because there is only a problem in 3D.
                       Vector<double> s(3), x(3);
                       // Find the local coordinate of the ndoe
                       el_pt->local_coordinate_of_node(n, s);
                       // Find the number of time history values
                       const unsigned ntstorage = nod_pt->ntstorage();
                       // Do we have a solid node
                       SolidNode* solid_node_pt =
                         dynamic_cast<SolidNode*>(nod_pt);
                       if (solid_node_pt)
                       {
                         // Assign Lagrangian coordinates from undeformed
                         // macro element (if it has one -- get_x_and_xi()
                         // does "the right thing" anyway. Leave actual
                         // nodal positions alone -- we're doing a solid
                         // mechanics problem and once we're going
                         // the nodal positions are always computed, never
                         // (automatically) reset to macro-element based
                         // positions; not even on pinned boundaries
                         // because the user may have other ideas about where
                         // these should go -- pinning means "don't touch the
                         // value", not "leave where the macro-element thinks
                         // it should be"
                         Vector<double> x_fe(3), xi(3), xi_fe(3);
                         solid_el_pt->get_x_and_xi(s, x_fe, x, xi_fe, xi);
                         for (unsigned i = 0; i < 3; i++)
{
                           solid_node_pt->xi(i) = xi[i];
                         }
                       }
                       else
                       {
                         // Set position and history values from the
                         // macro-element representation
                         for (unsigned t = 0; t < ntstorage; t++)
{
                           // Get the history value from the macro element
                           el_pt->get_x(t, s, x);
                           // Set the coordinate to that of the macroelement
                           // representation
                           for (unsigned i = 0; i < 3; i++)
{
                             nod_pt->x(t, i) = x[i];
                           }
                         }
                       } // End of non-solid node case
                       // Now remove the node from the list
                       hanging_nodes_on_boundary_pt[b].erase(it);
                       // If there are no Nodes left then exit the loops
                       if (hanging_nodes_on_boundary_pt[b].size() == 0)
                       {
                         e = n_boundary_element;
                         break;
                       }
                     }
                   }
                 }
               } // End of macro element case
             }
           }
         }
       } // End of case when we have fixed nodal positions
       // Final doc
       //-----------
       if (doc_info.is_doc_enabled())
       {
         // Doc the boundary conditions ('0' for non-existent, '1' for free,
         //----------------------------------------------------------------
         // '2' for pinned -- ideal for tecplot scatter sizing.
         //----------------------------------------------------
         // num_tree_nodes=tree_nodes_pt.size();
         // Determine maximum number of values at any node in this type of
         // element
         RefineableElement* el_pt = tree_nodes_pt[0]->object_pt();
         // Initalise max_nval
         unsigned max_nval = 0;
         for (unsigned n = 0; n < el_pt->nnode(); n++)
         {
           if (el_pt->node_pt(n)->nvalue() > max_nval)
           {
             max_nval = el_pt->node_pt(n)->nvalue();
           }
         }
         // Open the output file
         std::ofstream bcs_file;
         fullname.str("");
         fullname << doc_info.directory() << "/bcs" << doc_info.number()
                  << ".dat";
         bcs_file.open(fullname.str().c_str());
         // Loop over elements
         for (unsigned long e = 0; e < num_tree_nodes; e++)
         {
           el_pt = tree_nodes_pt[e]->object_pt();
           // Loop over nodes in element
           unsigned n_nod = el_pt->nnode();
           for (unsigned n = 0; n < n_nod; n++)
           {
             // Get pointer to the node
             Node* nod_pt = el_pt->node_pt(n);
             // Find the dimension of the node
             unsigned n_dim = nod_pt->ndim();
             // Write the nodal coordinates to the file
             for (unsigned i = 0; i < n_dim; i++)
             {
               bcs_file << nod_pt->x(i) << " ";
             }
             // Loop over all values in this element
             for (unsigned i = 0; i < max_nval; i++)
             {
               // Value exists at this node:
               if (i < nod_pt->nvalue())
               {
                 bcs_file << " " << 1 + nod_pt->is_pinned(i);
               }
               // ...if not just dump out a zero
               else
               {
                 bcs_file << " 0 ";
               }
             }
             bcs_file << std::endl;
           }
         }
         bcs_file.close();
         // Doc all nodes
         //---------------
         std::ofstream all_nodes_file;
         fullname.str("");
         fullname << doc_info.directory() << "/all_nodes" << doc_info.number()
                  << ".dat";
         all_nodes_file.open(fullname.str().c_str());
         all_nodes_file << "ZONE \n";
         // Need to recompute the number of nodes since it may have
         // changed during mesh refinement/unrefinement
         n_node = this->nnode();
         for (unsigned long n = 0; n < n_node; n++)
         {
           Node* nod_pt = this->node_pt(n);
           unsigned n_dim = nod_pt->ndim();
           for (unsigned i = 0; i < n_dim; i++)
           {
             all_nodes_file << this->node_pt(n)->x(i) << " ";
           }
           all_nodes_file << std::endl;
         }
         all_nodes_file.close();
         // Doc all hanging nodes:
         //-----------------------
         std::ofstream some_file;
         fullname.str("");
         fullname << doc_info.directory() << "/all_hangnodes"
                  << doc_info.number() << ".dat";
         some_file.open(fullname.str().c_str());
         for (unsigned long n = 0; n < n_node; n++)
         {
           Node* nod_pt = this->node_pt(n);
           if (nod_pt->is_hanging())
           {
             unsigned n_dim = nod_pt->ndim();
             for (unsigned i = 0; i < n_dim; i++)
             {
               some_file << nod_pt->x(i) << " ";
             }
             // ALH: Added this to stop Solid problems seg-faulting
             if (this->node_pt(n)->nvalue() > 0)
             {
               some_file << " " << nod_pt->raw_value(0);
             }
             some_file << std::endl;
           }
         }
         some_file.close();
         // Doc all hanging nodes and their masters
         // View with QHangingNodesWithMasters.mcr
         fullname.str("");
         fullname << doc_info.directory() << "/geometric_hangnodes_withmasters"
                  << doc_info.number() << ".dat";
         some_file.open(fullname.str().c_str());
         for (unsigned long n = 0; n < n_node; n++)
         {
           Node* nod_pt = this->node_pt(n);
           if (nod_pt->is_hanging())
           {
             unsigned n_dim = nod_pt->ndim();
             unsigned nmaster = nod_pt->hanging_pt()->nmaster();
             some_file << "ZONE I=" << nmaster + 1 << std::endl;
             for (unsigned i = 0; i < n_dim; i++)
             {
               some_file << nod_pt->x(i) << " ";
             }
             some_file << " 2 " << std::endl;
             for (unsigned imaster = 0; imaster < nmaster; imaster++)
             {
               Node* master_nod_pt =
                 nod_pt->hanging_pt()->master_node_pt(imaster);
               unsigned n_dim = master_nod_pt->ndim();
               for (unsigned i = 0; i < n_dim; i++)
               {
                 some_file << master_nod_pt->x(i) << " ";
               }
               some_file << " 1 " << std::endl;
             }
           }
         }
         some_file.close();
         // Doc all hanging nodes and their masters
         // View with QHangingNodesWithMasters.mcr
         for (unsigned i = 0; i < ncont_interpolated_values; i++)
         {
           fullname.str("");
           fullname << doc_info.directory()
                    << "/nonstandard_hangnodes_withmasters" << i << "_"
                    << doc_info.number() << ".dat";
           some_file.open(fullname.str().c_str());
           unsigned n_nod = this->nnode();
           for (unsigned long n = 0; n < n_nod; n++)
           {
             Node* nod_pt = this->node_pt(n);
             if (nod_pt->is_hanging(i))
             {
               if (nod_pt->hanging_pt(i) != nod_pt->hanging_pt())
               {
                 unsigned nmaster = nod_pt->hanging_pt(i)->nmaster();
                 some_file << "ZONE I=" << nmaster + 1 << std::endl;
                 unsigned n_dim = nod_pt->ndim();
                 for (unsigned j = 0; j < n_dim; j++)
                 {
                   some_file << nod_pt->x(j) << " ";
                 }
                 some_file << " 2 " << std::endl;
                 for (unsigned imaster = 0; imaster < nmaster; imaster++)
                 {
                   Node* master_nod_pt =
                     nod_pt->hanging_pt(i)->master_node_pt(imaster);
                   unsigned n_dim = master_nod_pt->ndim();
                   for (unsigned j = 0; j < n_dim; j++)
                   {
                     //               some_file << master_nod_pt->x(i) << " ";
                   }
                   some_file << " 1 " << std::endl;
                 }
               }
             }
           }
           some_file.close();
         }
       } // End of documentation
     } // End if (this->nelement()>0)
 #ifdef OOMPH_HAS_MPI
     // Now (re-)classify halo and haloed nodes and synchronise hanging
     // nodes
     if (this->is_mesh_distributed())
     {
       classify_halo_and_haloed_nodes(doc_info, doc_info.is_doc_enabled());
     }
 #endif
   }
References b, oomph::Mesh::boundary_element_pt(), oomph::TreeForest::check_all_neighbours(), oomph::TreeForest::close_hanging_node_files(), complete_hanging_nodes(), oomph::Tree::deactivate_object(), oomph::Mesh::delete_all_external_storage(), oomph::FiniteElement::dim(), oomph::DocInfo::directory(), oomph::Global_timings::Doc_comprehensive_timings, oomph::RefineableMeshBase::doc_info(), e(), oomph::Mesh::Element_pt, Eigen::placeholders::end, oomph::Mesh::finite_element_pt(), Forest_pt, oomph::Node::get_boundaries_pt(), oomph::FiniteElement::get_x(), oomph::SolidFiniteElement::get_x_and_xi(), oomph::Node::hanging_pt(), i, oomph::DocInfo::is_doc_enabled(), oomph::Node::is_hanging(), oomph::Mesh::is_mesh_distributed(), oomph::Node::is_on_boundary(), oomph::Data::is_pinned(), j, oomph::SolidNode::lagrangian_position(), oomph::FiniteElement::local_coordinate_of_node(), oomph::Mesh::Lookup_for_elements_next_boundary_is_setup, oomph::FiniteElement::macro_elem_pt(), oomph::HangInfo::master_node_pt(), oomph::RefineableMeshBase::max_error(), oomph::RefineableElement::max_integrity_tolerance(), oomph::Tree::merge_sons_if_required(), n, oomph::Mesh::nboundary(), oomph::Mesh::nboundary_element(), oomph::Node::ndim(), oomph::Mesh::nelement(), oomph::SolidNode::nlagrangian(), oomph::HangInfo::nmaster(), oomph::FiniteElement::nnode(), oomph::Mesh::nnode(), oomph::FiniteElement::node_pt(), oomph::Mesh::node_pt(), oomph::AlgebraicNode::node_update(), oomph::TreeForest::ntree(), oomph::Data::ntstorage(), oomph::DocInfo::number(), oomph::Data::nvalue(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::oomph_info, oomph::TreeForest::open_hanging_node_files(), oomph::Node::position(), oomph::Mesh::prune_dead_nodes(), oomph::Node::raw_value(), oomph::Mesh::reorder_nodes(), s, oomph::Node::set_non_obsolete(), oomph::Node::set_nonhanging(), oomph::Node::set_obsolete(), oomph::Data::set_value(), oomph::Mesh::setup_boundary_element_info(), size, split_elements_if_required(), oomph::TreeForest::stick_all_tree_nodes_into_vector(), oomph::TreeForest::stick_leaves_into_vector(), plotPSD::t, oomph::TimingHelpers::timer(), oomph::Tree::traverse_all(), oomph::Tree::traverse_all_but_leaves(), oomph::TreeForest::tree_pt(), oomph::SolidFiniteElement::undeformed_macro_elem_pt(), oomph::Node::value(), plotDoE::x, oomph::Node::x(), and oomph::SolidNode::xi().
complete_hanging_nodes()
void oomph::TreeBasedRefineableMeshBase::complete_hanging_nodes (const int & ncont_interpolated_values) protected
Complete the hanging node scheme recursively.
Complete the hanging node scheme recursively. After the initial markup scheme, hanging nodes can depend on other hanging nodes —> AAAAAAAAARGH! Need to translate this into a scheme where all hanging nodes only depend on non-hanging nodes...
   {
     // Number of nodes in mesh
     unsigned long n_node = this->nnode();
     double min_weight = 1.0e-8; // RefineableBrickElement::min_weight_value();
     // Loop over the nodes in the mesh
     for (unsigned long n = 0; n < n_node; n++)
     {
       // Assign a local pointer to the node
       Node* nod_pt = this->node_pt(n);
       // Loop over the values,
       // N.B. geometric hanging data is stored at the index -1
       for (int i = -1; i < ncont_interpolated_values; i++)
       {
         // Is the node hanging?
         if (nod_pt->is_hanging(i))
         {
           // If it is geometric OR has hanging node data that differs
           // from the geometric data, we must do some work
           if ((i == -1) || (nod_pt->hanging_pt(i) != nod_pt->hanging_pt()))
           {
             // Find out the ultimate map of dependencies: Master nodes
             // and associated weights
             Vector<Node*> master_nodes;
             Vector<double> hanging_weights;
             complete_hanging_nodes_recursively(
               nod_pt, master_nodes, hanging_weights, i);
             // put them into a map to merge all the occurences of the same node
             // (add the weights)
             std::map<Node*, double> hang_weights;
             unsigned n_master = master_nodes.size();
             for (unsigned k = 0; k < n_master; k++)
             {
               if (std::fabs(hanging_weights[k]) > min_weight)
                 hang_weights[master_nodes[k]] += hanging_weights[k];
             }
             // Create new hanging data (we know how many data there are)
             HangInfo* hang_pt = new HangInfo(hang_weights.size());
             unsigned hang_weights_index = 0;
             // Copy the map into the HangInfo object
             typedef std::map<Node*, double>::iterator IT;
             for (IT it = hang_weights.begin(); it != hang_weights.end(); ++it)
             {
               hang_pt->set_master_node_pt(
                 hang_weights_index, it->first, it->second);
               ++hang_weights_index;
             }
             // Assign the new hanging pointer to the appropriate value
             nod_pt->set_hanging_pt(hang_pt, i);
           }
         }
       }
     }
 #ifdef PARANOID
     // Check hanging node scheme: The weights need to add up to one
     //-------------------------------------------------------------
     // Loop over all values indices
     for (int i = -1; i < ncont_interpolated_values; i++)
     {
       // Loop over all nodes in mesh
       for (unsigned long n = 0; n < n_node; n++)
       {
         // Set a local pointer to the node
         Node* nod_pt = this->node_pt(n);
         // Is it hanging?
         if (nod_pt->is_hanging(i))
         {
           unsigned nmaster = nod_pt->hanging_pt(i)->nmaster();
           double sum = 0.0;
           for (unsigned imaster = 0; imaster < nmaster; imaster++)
           {
             sum += nod_pt->hanging_pt(i)->master_weight(imaster);
           }
           if (std::fabs(sum - 1.0) > 1.0e-7)
           {
             oomph_info << "WARNING: Sum of master node weights fabs(sum-1.0) "
                        << std::fabs(sum - 1.0) << " for node number " << n
                        << " at value " << i << std::endl;
           }
         }
       }
     }
 #endif
   }
References complete_hanging_nodes_recursively(), boost::multiprecision::fabs(), oomph::Node::hanging_pt(), i, oomph::Node::is_hanging(), k, oomph::HangInfo::master_weight(), n, oomph::HangInfo::nmaster(), oomph::Mesh::nnode(), oomph::Mesh::node_pt(), oomph::oomph_info, oomph::Node::set_hanging_pt(), and oomph::HangInfo::set_master_node_pt().
Referenced by adapt_mesh(), and p_adapt_mesh().
complete_hanging_nodes_recursively()
void oomph::TreeBasedRefineableMeshBase::complete_hanging_nodes_recursively (Node *& nod_pt, Vector< Node * > & master_nodes, Vector< double > & hang_weights, const int & i) protected
Auxiliary routine for recursive hanging node completion.
Given a node, return a vector of pointers to master nodes and a vector of the associated weights. This is done recursively, so if a node is not hanging, the node is regarded as its own master node which has weight 1.0.
   {
     // Is the node hanging in the variable i
     if (nod_pt->is_hanging(i))
     {
       // Loop over all master nodes
       HangInfo* const hang_pt = nod_pt->hanging_pt(i);
       unsigned nmaster = hang_pt->nmaster();
       for (unsigned m = 0; m < nmaster; m++)
       {
         // Get the master node
         Node* master_nod_pt = hang_pt->master_node_pt(m);
         // Keep in memory the size of the list before adding the nodes this
         // master node depends on. This is required so that the recursion is
         // only performed on these particular master nodes. A master node
         // could contain contributions from two separate pseudo-masters.
         // These contributions must be summed, not multiplied.
         int first_new_node = master_nodes.size();
         // Now check which master nodes this master node depends on
         complete_hanging_nodes_recursively(
           master_nod_pt, master_nodes, hang_weights, i);
         // Multiply old weight by new weight for all the nodes this master
         // node depends on
         unsigned n_new_master_node = master_nodes.size();
         double mtr_weight = hang_pt->master_weight(m);
         for (unsigned k = first_new_node; k < n_new_master_node; k++)
         {
           hang_weights[k] = mtr_weight * hang_weights[k];
         }
       }
     }
     else
     // Node isn't hanging so it enters itself with the full weight
     {
       master_nodes.push_back(nod_pt);
       hang_weights.push_back(1.0);
     }
   }
References oomph::Node::hanging_pt(), i, oomph::Node::is_hanging(), k, m, oomph::HangInfo::master_node_pt(), oomph::HangInfo::master_weight(), and oomph::HangInfo::nmaster().
Referenced by complete_hanging_nodes().
doc_adaptivity_targets()
void oomph::TreeBasedRefineableMeshBase::doc_adaptivity_targets (std::ostream & outfile) inline virtual
Doc the targets for mesh adaptation.
Reimplemented from oomph::RefineableMeshBase.
     {
       outfile << std::endl;
       outfile << "Targets for mesh adaptation: " << std::endl;
       outfile << "---------------------------- " << std::endl;
       outfile << "Target for max. error: " << Max_permitted_error << std::endl;
       outfile << "Target for min. error: " << Min_permitted_error << std::endl;
       outfile << "Min. refinement level: " << Min_refinement_level << std::endl;
       outfile << "Max. refinement level: " << Max_refinement_level << std::endl;
       outfile << "Min. p-refinement level: " << Min_p_refinement_level
               << std::endl;
       outfile << "Max. p-refinement level: " << Max_p_refinement_level
               << std::endl;
       outfile << "Don't unrefine if less than " << Max_keep_unrefined
               << " elements need unrefinement." << std::endl;
       outfile << std::endl;
     }
References oomph::RefineableMeshBase::Max_keep_unrefined, Max_p_refinement_level, oomph::RefineableMeshBase::Max_permitted_error, Max_refinement_level, Min_p_refinement_level, oomph::RefineableMeshBase::Min_permitted_error, and Min_refinement_level.
Referenced by FSIRingProblem::dynamic_run().
dump_refinement()
void oomph::TreeBasedRefineableMeshBase::dump_refinement (std::ostream & outfile) virtual
Dump refinement pattern to allow for rebuild.
Dump refinement pattern to allow for rebuild
   {
     // Assign storage for refinement pattern
     Vector<Vector<unsigned>> to_be_refined;
     // Get refinement pattern of reference mesh:
     get_refinement_pattern(to_be_refined);
     // Dump max refinement level:
     unsigned max_level = to_be_refined.size();
     outfile << max_level << " # max. refinement level " << std::endl;
     // Doc the numbers of the elements that need to be refined at this level
     for (unsigned l = 0; l < max_level; l++)
     {
       // Loop over elements that need to be refined at this level
       unsigned n_to_be_refined = to_be_refined[l].size();
       outfile << n_to_be_refined << " # number of elements to be refined. "
               << "What follows are the numbers of the elements. " << std::endl;
       // Select relevant elements to be refined
       for (unsigned i = 0; i < n_to_be_refined; i++)
       {
         outfile << to_be_refined[l][i] << std::endl;
       }
     }
   }
References get_refinement_pattern(), and i.
forest_pt()
TreeForest* oomph::TreeBasedRefineableMeshBase::forest_pt () inline
Return pointer to the Forest represenation of the mesh.
     {
       return Forest_pt;
     }
References Forest_pt.
Referenced by get_elements_at_refinement_level(), get_refinement_pattern(), p_adapt_mesh(), and refine_as_in_reference_mesh().
get_elements_at_refinement_level()
void oomph::TreeBasedRefineableMeshBase::get_elements_at_refinement_level (unsigned & refinement_level, Vector< RefineableElement * > & level_elements) virtual
Extract the elements at a particular refinement level in the refinement pattern - used in Mesh::redistribute or whatever it's going to be called (RefineableMeshBase::reduce_halo_layers or something)
Extract the elements at a particular refinement level in the refinement pattern (used in Mesh::redistribute or whatever it's going to be called (RefineableMeshBase::reduce_halo_layers or something)
   {
     // Extract *all* elements from current (fully refined) mesh.
     Vector<Tree*> all_tree_nodes_pt;
     forest_pt()->stick_all_tree_nodes_into_vector(all_tree_nodes_pt);
     // Add the element to the vector if its level matches refinement_level
     unsigned nnodes = all_tree_nodes_pt.size();
     for (unsigned e = 0; e < nnodes; e++)
     {
       unsigned level = all_tree_nodes_pt[e]->level();
       if (level == refinement_level)
       {
         level_elements.push_back(
           dynamic_cast<RefineableElement*>(all_tree_nodes_pt[e]->object_pt()));
       }
     }
   }
References e(), forest_pt(), and oomph::TreeForest::stick_all_tree_nodes_into_vector().
get_refinement_levels()
void oomph::TreeBasedRefineableMeshBase::get_refinement_levels (unsigned & min_refinement_level, unsigned & max_refinement_level) virtual
Get max/min refinement levels in mesh.
Get max/min refinement level.
   {
     // Initialise
     min_refinement_level = UINT_MAX;
     max_refinement_level = 0;
     // Loop over all elements
     unsigned long n_element = this->nelement();
     if (n_element == 0)
     {
       min_refinement_level = 0;
       max_refinement_level = 0;
     }
     else
     {
       for (unsigned long e = 0; e < n_element; e++)
       {
         // Get the refinement level of the element
         unsigned level = dynamic_cast<RefineableElement*>(this->element_pt(e))
                            ->refinement_level();
         if (level > max_refinement_level) max_refinement_level = level;
         if (level < min_refinement_level) min_refinement_level = level;
       }
     }
   }
References e(), oomph::Mesh::element_pt(), max_refinement_level(), min_refinement_level(), and oomph::Mesh::nelement().
Referenced by oomph::Problem::read(), refine_as_in_reference_mesh(), refine_base_mesh(), oomph::RefineableBrickMesh< ELEMENT >::setup_octree_forest(), and oomph::RefineableQuadMesh< ELEMENT >::setup_quadtree_forest().
get_refinement_pattern()
void oomph::TreeBasedRefineableMeshBase::get_refinement_pattern (Vector< Vector< unsigned >> & to_be_refined) virtual
Extract refinement pattern: Consider the hypothetical mesh obtained by truncating the refinement of the current mesh to a given level (where level=0 is the un-refined base mesh). To advance to the next refinement level, we need to refine (split) the to_be_refined[level].size() elements identified by the element numbers contained in vector to_be_refined[level][...]
Get refinement pattern of mesh: Consider the hypothetical mesh obtained by truncating the refinement of the current mesh to a given level (where level=0 is the un-refined base mesh). To advance to the next refinement level, we need to refine (split) the to_be_refined[level].size() elements identified by the element numbers contained in vector to_be_refined[level][...]
   {
     // Extract *all* elements from current (fully refined) mesh.
     Vector<Tree*> all_tree_nodes_pt;
     forest_pt()->stick_all_tree_nodes_into_vector(all_tree_nodes_pt);
     // Find out maximum refinement level
     unsigned max_level = 0;
     unsigned nnodes = all_tree_nodes_pt.size();
     for (unsigned e = 0; e < nnodes; e++)
     {
       unsigned level = all_tree_nodes_pt[e]->level();
       if (level > max_level) max_level = level;
     }
     // Assign storage for refinement pattern
     to_be_refined.clear();
     to_be_refined.resize(max_level);
     Vector<unsigned> el_count(max_level);
     // Initialise count of elements that exist in mesh when refinement
     // has proceeded to this level
     for (unsigned l = 0; l < max_level; l++)
     {
       el_count[l] = 0;
     }
     // Loop over all levels and extract all elements that exist
     // in reference mesh when refinement has proceeded to this level
     for (unsigned l = 0; l < max_level; l++)
     {
       // Loop over all elements (tree nodes)
       for (unsigned e = 0; e < nnodes; e++)
       {
         // What level does this element exist on?
         unsigned level = all_tree_nodes_pt[e]->level();
         // Element is part of the mesh at this refinement level
         // if it exists at this level OR if it exists at a lower level
         // and is a leaf
         if ((level == l) || ((level < l) && (all_tree_nodes_pt[e]->is_leaf())))
         {
           // If element exsts at this level and is not a leaf it will
           // be refined when we move to the next level:
           if ((level == l) && (!all_tree_nodes_pt[e]->is_leaf()))
           {
             // Add element number (in mesh at current refinement level)
             // to the list of elements that need to be refined
             to_be_refined[l].push_back(el_count[l]);
           }
           // Element exists in this mesh: Add to counter
           el_count[l]++;
         }
       }
     }
   }
References e(), forest_pt(), and oomph::TreeForest::stick_all_tree_nodes_into_vector().
Referenced by dump_refinement(), refine_base_mesh_as_in_reference_mesh(), and refine_base_mesh_as_in_reference_mesh_minus_one().
max_p_refinement_level()
unsigned& oomph::TreeBasedRefineableMeshBase::max_p_refinement_level () inline
Access fct for max. permissible p-refinement level (relative to base mesh)
     {
       return Max_p_refinement_level;
     }
References Max_p_refinement_level.
Referenced by p_adapt().
max_refinement_level()
unsigned& oomph::TreeBasedRefineableMeshBase::max_refinement_level () inline
Access fct for max. permissible refinement level (relative to base mesh)
     {
       return Max_refinement_level;
     }
References Max_refinement_level.
Referenced by adapt(), FSIRingProblem::dynamic_run(), and get_refinement_levels().
min_p_refinement_level()
unsigned& oomph::TreeBasedRefineableMeshBase::min_p_refinement_level () inline
Access fct for min. permissible p-refinement level (relative to base mesh)
     {
       return Min_p_refinement_level;
     }
References Min_p_refinement_level.
min_refinement_level()
unsigned& oomph::TreeBasedRefineableMeshBase::min_refinement_level () inline
Access fct for min. permissible refinement level (relative to base mesh)
     {
       return Min_refinement_level;
     }
References Min_refinement_level.
Referenced by adapt(), FSIRingProblem::dynamic_run(), and get_refinement_levels().
operator=()
void oomph::TreeBasedRefineableMeshBase::operator= (const TreeBasedRefineableMeshBase &) delete
Broken assignment operator.
p_adapt()
void oomph::TreeBasedRefineableMeshBase::p_adapt (const Vector< double > & elemental_error) virtual
p-adapt mesh: Refine elements whose error is lager than err_max and (try to) unrefine those whose error is smaller than err_min
///////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////// Do adaptive p-refinement for mesh.
Pass Vector of error estimates for all elements.
p-refine those whose errors exceeds the threshold
p-unrefine those whose errors is less than threshold.
/ ... otherwise mark it as having been over-ruled
Reimplemented from oomph::RefineableMeshBase.
   {
     // Set the refinement tolerance to be the max permissible error
     double refine_tol = this->max_permitted_error();
     // Set the unrefinement tolerance to be the min permissible error
     double unrefine_tol = this->min_permitted_error();
     // Setup doc info
     DocInfo local_doc_info;
     if (doc_info_pt() == 0)
     {
       local_doc_info.disable_doc();
     }
     else
     {
       local_doc_info = this->doc_info();
     }
     // Check that the errors make sense
     if (refine_tol <= unrefine_tol)
     {
       std::ostringstream error_stream;
       error_stream << "Refinement tolerance <= Unrefinement tolerance"
                    << refine_tol << " " << unrefine_tol << std::endl
                    << "doesn't make sense and will almost certainly crash"
                    << std::endl
                    << "this beautiful code!" << std::endl;
       throw OomphLibError(
         error_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
     // Select elements for refinement and unrefinement
     //==============================================
     // Reset counter for number of elements that would like to be
     // refined further but can't
     this->nrefinement_overruled() = 0;
     unsigned n_refine = 0;
     unsigned n_unrefine = 0;
     // Loop over all elements and mark them according to the error criterion
     unsigned long Nelement = this->nelement();
     for (unsigned long e = 0; e < Nelement; e++)
     {
       //(Cast) pointer to the element
       PRefineableElement* el_pt =
         dynamic_cast<PRefineableElement*>(this->element_pt(e));
       // Check that we can p-refine the element
       if (el_pt != 0)
       {
         // Initially element is not to be refined
         el_pt->deselect_for_p_refinement();
         el_pt->deselect_for_p_unrefinement();
         // If the element error exceeds the threshold ...
         if (elemental_error[e] > refine_tol)
         {
           // ... and its refinement level is less than the maximum desired level
           // mark is to be refined
           if ((el_pt->p_refinement_is_enabled()) &&
               (el_pt->p_order() < this->max_p_refinement_level()))
           {
             el_pt->select_for_p_refinement();
             n_refine++;
           }
           // ... otherwise mark it as having been over-ruled
           else
           {
             this->nrefinement_overruled() += 1;
           }
         }
         if (elemental_error[e] < unrefine_tol)
         {
           // ... and its refinement level is more than the minimum desired level
           // mark is to be refined
           //(Also check that we don't unrefine past the initial refinement
           // level)
           if ((el_pt->p_refinement_is_enabled()) &&
               (el_pt->p_order() > this->min_p_refinement_level()) &&
               (el_pt->p_order() > el_pt->initial_p_order()))
           {
             el_pt->select_for_p_unrefinement();
             n_unrefine++;
           }
           // Don't mark as overruled - it's misleading
           // else
           // {
           //  this->nrefinement_overruled()+=1;
           // }
         }
       } // End of check for p-refineability of element
       else
       {
         oomph_info << "p-refinement is not possible for these elements"
                    << std::endl;
         // Don't try to p-refine any more elements
         break;
       }
     }
     oomph_info << " \n Number of elements to be refined: " << n_refine
                << std::endl;
     oomph_info << " \n Number of elements whose refinement was overruled: "
                << this->nrefinement_overruled() << std::endl;
     oomph_info << " \n Number of elements to be unrefined : " << n_unrefine
                << std::endl
                << std::endl;
     // Now do the actual mesh adaptation
     //---------------------------------
     // Check whether its worth our while
     // Either some elements want to be refined,
     // or the number that want to be unrefined are greater than the
     // specified tolerance
     // In a parallel job, it is possible that one process may not have
     // any elements to refine, BUT a neighbouring process may refine an
     // element which changes the hanging status of a node that is on
     // both processes (i.e. a halo(ed) node).  To get around this issue,
     // ALL processes need to call adapt_mesh if ANY refinement is to
     // take place anywhere.
     unsigned total_n_refine = 0;
 #ifdef OOMPH_HAS_MPI
     // Sum n_refine across all processors
     if (this->is_mesh_distributed())
     {
       MPI_Allreduce(
         &n_refine, &total_n_refine, 1, MPI_INT, MPI_SUM, Comm_pt->mpi_comm());
     }
     else
     {
       total_n_refine = n_refine;
     }
 #else
     total_n_refine = n_refine;
 #endif
     // There may be some issues with unrefinement too, but I have not
     // been able to come up with an example (either in my head or in a
     // particular problem) where anything has arisen.  I can see that
     // there may be an issue if n_unrefine differs across processes so
     // that (total_n_unrefine > max_keep_unrefined()) on some but not
     // all processes. I haven't seen any examples of this yet so the
     // following code may or may not work!  (Andy, 06/03/08)
     unsigned total_n_unrefine = 0;
 #ifdef OOMPH_HAS_MPI
     // Sum n_unrefine across all processors
     if (this->is_mesh_distributed())
     {
       MPI_Allreduce(&n_unrefine,
                     &total_n_unrefine,
                     1,
                     MPI_INT,
                     MPI_SUM,
                     Comm_pt->mpi_comm());
     }
     else
     {
       total_n_unrefine = n_unrefine;
     }
 #else
     total_n_unrefine = n_unrefine;
 #endif
     oomph_info << "---> " << total_n_refine << " elements to be refined, and "
                << total_n_unrefine << " to be unrefined, in total."
                << std::endl;
     if ((total_n_refine > 0) || (total_n_unrefine > this->max_keep_unrefined()))
     {
 #ifdef PARANOID
 #ifdef OOMPH_HAS_MPI
       // Sanity check: Each processor checks if the enforced unrefinement of
       // its haloed element is matched by enforced unrefinement of the
       // corresponding halo elements on the other processors.
       if (this->is_mesh_distributed())
       {
         // Store number of processors and current process
         MPI_Status status;
         int n_proc = Comm_pt->nproc();
         int my_rank = Comm_pt->my_rank();
         // Loop over all other domains/processors
         for (int d = 0; d < n_proc; d++)
         {
           // Don't talk to yourself
           if (d != my_rank)
           {
             {
               // Get the vector of halo elements whose non-halo counterpart
               // are on processor d
               Vector<GeneralisedElement*> halo_elem_pt(
                 this->halo_element_pt(d));
               // Create vector containing (0)1 to indicate that
               // halo element is (not) to be unrefined
               unsigned nhalo = halo_elem_pt.size();
               Vector<int> halo_to_be_unrefined(nhalo, 0);
               for (unsigned e = 0; e < nhalo; e++)
               {
                 if (dynamic_cast<PRefineableElement*>(halo_elem_pt[e])
                       ->to_be_p_unrefined())
                 {
                   halo_to_be_unrefined[e] = 1;
                 }
               }
               // Trap the case when there are no halo elements
               // so that we don't get a segfault in the MPI send
               if (nhalo > 0)
               {
                 // Send it across
                 MPI_Send(&halo_to_be_unrefined[0],
                          nhalo,
                          MPI_INT,
                          d,
                          0,
                          Comm_pt->mpi_comm());
               }
             }
             {
               // Get the vector of haloed elements on current processor
               Vector<GeneralisedElement*> haloed_elem_pt(
                 this->haloed_element_pt(d));
               // Ask processor d to send vector containing (0)1 for
               // halo element with current processor to be (not)unrefined
               unsigned nhaloed = haloed_elem_pt.size();
               Vector<int> halo_to_be_unrefined(nhaloed);
               // Trap to catch the case that there are no haloed elements
               if (nhaloed > 0)
               {
                 MPI_Recv(&halo_to_be_unrefined[0],
                          nhaloed,
                          MPI_INT,
                          d,
                          0,
                          Comm_pt->mpi_comm(),
                          &status);
               }
               // Check it
               for (unsigned e = 0; e < nhaloed; e++)
               {
                 if (((halo_to_be_unrefined[e] == 0) &&
                      (dynamic_cast<PRefineableElement*>(haloed_elem_pt[e])
                         ->to_be_p_unrefined())) ||
                     ((halo_to_be_unrefined[e] == 1) &&
                      (!dynamic_cast<PRefineableElement*>(haloed_elem_pt[e])
                          ->to_be_p_unrefined())))
                 {
                   std::ostringstream error_message;
                   error_message
                     << "Error in refinement: \n"
                     << "Haloed element: " << e << " on proc " << my_rank
                     << " \n"
                     << "wants to be unrefined whereas its halo counterpart on\n"
                     << "proc " << d << " doesn't (or vice versa)...\n"
                     << "This is most likely because the error estimator\n"
                     << "has not assigned the same errors to halo and haloed\n"
                     << "elements -- it ought to!\n";
                   throw OomphLibError(error_message.str(),
                                       OOMPH_CURRENT_FUNCTION,
                                       OOMPH_EXCEPTION_LOCATION);
                 }
               }
             }
           }
         }
         // Loop over all other domains/processors
         for (int d = 0; d < n_proc; d++)
         {
           // Don't talk to yourself
           if (d != my_rank)
           {
             {
               // Get the vector of halo elements whose non-halo counterpart
               // are on processor d
               Vector<GeneralisedElement*> halo_elem_pt(
                 this->halo_element_pt(d));
               // Create vector containing (0)1 to indicate that
               // halo element is (not) to be refined
               unsigned nhalo = halo_elem_pt.size();
               Vector<int> halo_to_be_refined(nhalo, 0);
               for (unsigned e = 0; e < nhalo; e++)
               {
                 if (dynamic_cast<PRefineableElement*>(halo_elem_pt[e])
                       ->to_be_p_refined())
                 {
                   halo_to_be_refined[e] = 1;
                 }
               }
               // Send it across
               if (nhalo > 0)
               {
                 MPI_Send(&halo_to_be_refined[0],
                          nhalo,
                          MPI_INT,
                          d,
                          0,
                          Comm_pt->mpi_comm());
               }
             }
             {
               // Get the vector of haloed elements on current processor
               Vector<GeneralisedElement*> haloed_elem_pt(
                 this->haloed_element_pt(d));
               // Ask processor d to send vector containing (0)1 for
               // halo element with current processor to be (not)refined
               unsigned nhaloed = haloed_elem_pt.size();
               Vector<int> halo_to_be_refined(nhaloed);
               if (nhaloed > 0)
               {
                 MPI_Recv(&halo_to_be_refined[0],
                          nhaloed,
                          MPI_INT,
                          d,
                          0,
                          Comm_pt->mpi_comm(),
                          &status);
               }
               // Check it
               for (unsigned e = 0; e < nhaloed; e++)
               {
                 if (((halo_to_be_refined[e] == 0) &&
                      (dynamic_cast<PRefineableElement*>(haloed_elem_pt[e])
                         ->to_be_p_refined())) ||
                     ((halo_to_be_refined[e] == 1) &&
                      (!dynamic_cast<PRefineableElement*>(haloed_elem_pt[e])
                          ->to_be_p_refined())))
                 {
                   std::ostringstream error_message;
                   error_message
                     << "Error in refinement: \n"
                     << "Haloed element: " << e << " on proc " << my_rank
                     << " \n"
                     << "wants to be refined whereas its halo counterpart on\n"
                     << "proc " << d << " doesn't (or vice versa)...\n"
                     << "This is most likely because the error estimator\n"
                     << "has not assigned the same errors to halo and haloed\n"
                     << "elements -- it ought to!\n";
                   throw OomphLibError(error_message.str(),
                                       OOMPH_CURRENT_FUNCTION,
                                       OOMPH_EXCEPTION_LOCATION);
                 }
               }
             }
           }
         }
       }
 #endif
 #endif
       // Perform the actual adaptation
       p_adapt_mesh(local_doc_info);
       // The number of refineable elements is still local to each process
       this->Nunrefined = n_unrefine;
       this->Nrefined = n_refine;
     }
     // If not worthwhile, say so but still reorder nodes and kill external
     // storage for consistency in parallel computations
     else
     {
 #ifdef OOMPH_HAS_MPI
       // Delete any external element storage - any interaction will still
       // be set up on the fly again, so we need to get rid of old information.
       // This particularly causes problems in multi-domain examples where
       // we decide not to refine one of the meshes
       this->delete_all_external_storage();
 #endif
       // Reorder the nodes within the mesh's node vector
       // to establish a standard ordering regardless of the sequence
       // of mesh refinements -- this is required to allow dump/restart
       // on refined meshes
       this->reorder_nodes();
 #ifdef OOMPH_HAS_MPI
       // Now (re-)classify halo and haloed nodes and synchronise hanging
       // nodes
       // This is required in cases where delete_all_external_storage()
       // made dependent nodes to external halo nodes nonhanging.
       if (this->is_mesh_distributed())
       {
         DocInfo doc_info;
         doc_info.disable_doc();
         classify_halo_and_haloed_nodes(doc_info, doc_info.is_doc_enabled());
       }
 #endif
       if (n_refine == 0)
       {
         oomph_info << "\n Not enough benefit in adapting mesh. " << std::endl
                    << std::endl;
       }
       this->Nunrefined = 0;
       this->Nrefined = 0;
     }
   }
References oomph::Mesh::delete_all_external_storage(), oomph::PRefineableElement::deselect_for_p_refinement(), oomph::PRefineableElement::deselect_for_p_unrefinement(), oomph::DocInfo::disable_doc(), oomph::RefineableMeshBase::doc_info(), oomph::RefineableMeshBase::doc_info_pt(), e(), oomph::Mesh::element_pt(), oomph::PRefineableElement::initial_p_order(), oomph::DocInfo::is_doc_enabled(), oomph::Mesh::is_mesh_distributed(), oomph::RefineableMeshBase::max_keep_unrefined(), max_p_refinement_level(), oomph::RefineableMeshBase::max_permitted_error(), oomph::RefineableMeshBase::min_permitted_error(), oomph::Mesh::nelement(), oomph::RefineableMeshBase::Nrefined, oomph::RefineableMeshBase::nrefinement_overruled(), oomph::RefineableMeshBase::Nunrefined, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::oomph_info, p_adapt_mesh(), oomph::PRefineableElement::p_order(), oomph::PRefineableElement::p_refinement_is_enabled(), oomph::Mesh::reorder_nodes(), oomph::PRefineableElement::select_for_p_refinement(), and oomph::PRefineableElement::select_for_p_unrefinement().
p_adapt_mesh() [1/2]
void oomph::TreeBasedRefineableMeshBase::p_adapt_mesh () inline
Perform the actual tree-based mesh p-adaptation. A simple wrapper to call the function without documentation.
     {
       // Create a dummy doc_info object
       DocInfo doc_info;
       doc_info.directory() = "";
       doc_info.disable_doc();
       // Call the other adapt mesh
       p_adapt_mesh(doc_info);
     }
References oomph::DocInfo::directory(), oomph::DocInfo::disable_doc(), and oomph::RefineableMeshBase::doc_info().
Referenced by p_adapt(), p_refine_selected_elements(), p_refine_uniformly(), and p_unrefine_uniformly().
p_adapt_mesh() [2/2]
void oomph::TreeBasedRefineableMeshBase::p_adapt_mesh (DocInfo & doc_info)
Perform the actual tree-based mesh p-adaptation, documenting the progress in the directory specified in DocInfo object.
p-adapt mesh, which exists in two representations, namely as:
a FE mesh
a forest of Oc or QuadTrees
p-refinement/derefinement process is documented (in tecplot-able form) if requested.
Procedure:
Loop over all elements and do the p-refinement/unrefinement for those who want to be refined. Note: p-refinement builds fully- functional elements.
For all nodes that were hanging on the previous mesh (and are still marked as such), fill in their nodal values (consistent with the current hanging node scheme) to make sure they are fully functional, should they have become non-hanging during the mesh-adaptation. Then mark the nodes as non-hanging.
Delete any nodes that have become obsolete.
Mark up hanging nodes and setup hanging node scheme (incl. recursive cleanup for hanging nodes that depend on other hanging nodes).
run a quick self-test on the neighbour finding scheme and check the integrity of the elements (if PARANOID)
doc hanging node status, boundary conditions, neighbour scheme if requested.
After adaptation, all nodes (whether new or old) have up-to-date current and previous values.
If refinement process is being documented, the following information is documented:
The files
"neighbours.dat"
"all_nodes.dat"
"new_nodes.dat"
"hang_nodes_*.dat" where the * denotes a direction (n,s,e,w) in 2D or (r,l,u,d,f,b) in 3D
can be viewed with
QHangingNodes.mcr
The file
"hangnodes_withmasters.dat"
can be viewed with
QHangingNodesWithMasters.mcr
to check the hanging node status.
The neighbour status of the elements is documented in
"neighbours.dat"
and can be viewed with
QuadTreeNeighbours.mcr
Update the boundary element info – this can be a costly procedure and for this reason the mesh writer might have decided not to set up this scheme. If so, we won't change this and suppress its creation...
/BENFLAG: Check that all the nodes belong to their update elements
   {
 #ifdef OOMPH_HAS_MPI
     // Delete any external element storage before performing the adaptation
     // (in particular, external halo nodes that are on mesh boundaries)
     this->delete_all_external_storage();
 #endif
     // Only perform the adapt step if the mesh has any elements.  This is
     // relevant in a distributed problem with multiple meshes, where a
     // particular process may not have any elements on a particular submesh.
     if (this->nelement() > 0)
     {
       double t_start = 0.0;
       if (Global_timings::Doc_comprehensive_timings)
       {
         t_start = TimingHelpers::timer();
       }
       // Do refinement/unrefinement if required
       this->p_refine_elements_if_required();
       if (Global_timings::Doc_comprehensive_timings)
       {
         double t_end = TimingHelpers::timer();
         oomph_info << "Time for p-refinement/unrefinement: " << t_end - t_start
                    << std::endl;
         t_start = TimingHelpers::timer();
       }
       // Loop over all nodes in mesh and free the dofs of those that were
       //-----------------------------------------------------------------
       // pinned only because they were hanging nodes. Also update their
       //-----------------------------------------------------------------
       // nodal values so that they contain data that is consistent
       //----------------------------------------------------------
       // with the hanging node representation
       //-------------------------------------
       // (Even if the nodal data isn't actually accessed because the node
       // is still hanging -- we don't know this yet, and this step makes
       // sure that all nodes are fully functional and up-to-date, should
       // they become non-hanging below).
       //
       //
       // However, if we have a fixed mesh and hanging nodes on the boundary
       // become non-hanging they will not necessarily respect the curvilinear
       // boundaries. This can only happen in 3D of course because it is not
       // possible to have hanging nodes on boundaries in 2D.
       // The solution is to store those nodes on the boundaries that are
       // currently hanging and then check to see whether they have changed
       // status at the end of the refinement procedure.
       // If it has changed, then we need to adjust their positions.
       const unsigned n_boundary = this->nboundary();
       const unsigned mesh_dim = this->finite_element_pt(0)->dim();
       Vector<std::set<Node*>> hanging_nodes_on_boundary_pt(n_boundary);
       unsigned long n_node = this->nnode();
       for (unsigned long n = 0; n < n_node; n++)
       {
         // Get the pointer to the node
         Node* nod_pt = this->node_pt(n);
         // Get the number of values in the node
         unsigned n_value = nod_pt->nvalue();
         // We need to find if any of the values are hanging
         bool is_hanging = nod_pt->is_hanging();
         // Loop over the values and find out whether any are hanging
         for (unsigned n = 0; n < n_value; n++)
         {
           is_hanging |= nod_pt->is_hanging(n);
         }
         // If the node is hanging then ...
         if (is_hanging)
         {
           // Unless they are turned into hanging nodes again below
           // (this might or might not happen), fill in all the necessary
           // data to make them 'proper' nodes again.
           // Reconstruct the nodal values/position from the node's
           // hanging node representation
           unsigned nt = nod_pt->ntstorage();
           Vector<double> values(n_value);
           unsigned n_dim = nod_pt->ndim();
           Vector<double> position(n_dim);
           // Loop over all history values
           for (unsigned t = 0; t < nt; t++)
           {
             nod_pt->value(t, values);
             for (unsigned i = 0; i < n_value; i++)
             {
               nod_pt->set_value(t, i, values[i]);
             }
             nod_pt->position(t, position);
             for (unsigned i = 0; i < n_dim; i++)
             {
               nod_pt->x(t, i) = position[i];
             }
           }
           // If it's an algebraic node: Update its previous nodal positions too
           AlgebraicNode* alg_node_pt = dynamic_cast<AlgebraicNode*>(nod_pt);
           if (alg_node_pt != 0)
           {
             bool update_all_time_levels = true;
             alg_node_pt->node_update(update_all_time_levels);
           }
           // If it's a Solid node, update Lagrangian coordinates
           // from its hanging node representation
           SolidNode* solid_node_pt = dynamic_cast<SolidNode*>(nod_pt);
           if (solid_node_pt != 0)
           {
             unsigned n_lagrangian = solid_node_pt->nlagrangian();
             for (unsigned i = 0; i < n_lagrangian; i++)
             {
               solid_node_pt->xi(i) = solid_node_pt->lagrangian_position(i);
             }
           }
           // Now store geometrically hanging nodes on boundaries that
           // may need updating after refinement.
           // There will only be a problem if we have 3 spatial dimensions
           if ((mesh_dim > 2) && (nod_pt->is_hanging()))
           {
             // If the node is on a boundary then add a pointer to the node
             // to our lookup scheme
             if (nod_pt->is_on_boundary())
             {
               // Storage for the boundaries on which the Node is located
               std::set<unsigned>* boundaries_pt;
               nod_pt->get_boundaries_pt(boundaries_pt);
               if (boundaries_pt != 0)
               {
                 // Loop over the boundaries and add a pointer to the node
                 // to the appropriate storage scheme
                 for (std::set<unsigned>::iterator it = boundaries_pt->begin();
                      it != boundaries_pt->end();
                      ++it)
                 {
                   hanging_nodes_on_boundary_pt[*it].insert(nod_pt);
                 }
               }
             }
           }
         } // End of is_hanging
         // Initially mark all nodes as 'non-hanging' and `obsolete'
         nod_pt->set_nonhanging();
         nod_pt->set_obsolete();
       }
       double t_end = 0.0;
       if (Global_timings::Doc_comprehensive_timings)
       {
         t_end = TimingHelpers::timer();
         oomph_info << "Time for sorting out initial hanging status: "
                    << t_end - t_start << std::endl;
         t_start = TimingHelpers::timer();
       }
       // Stick all elements into a vector
       Vector<Tree*> tree_nodes_pt;
       this->forest_pt()->stick_leaves_into_vector(tree_nodes_pt);
       // Copy the elements into the mesh Vector
       unsigned long num_tree_nodes = tree_nodes_pt.size();
       this->element_pt().resize(num_tree_nodes);
       for (unsigned long e = 0; e < num_tree_nodes; e++)
       {
         this->element_pt(e) = tree_nodes_pt[e]->object_pt();
         // Now loop over all nodes in element and mark them as non-obsolete
         FiniteElement* this_el_pt = this->finite_element_pt(e);
         unsigned n_node = this_el_pt->nnode(); // caching pre-loop
         for (unsigned n = 0; n < n_node; n++)
         {
           this_el_pt->node_pt(n)->set_non_obsolete();
         }
         // Mark up so that repeated refinements do not occur
         // (Required because refined element is the same element as the
         // original)
         PRefineableElement* cast_el_pt =
           dynamic_cast<PRefineableElement*>(this->element_pt(e));
         cast_el_pt->deselect_for_p_refinement();
         cast_el_pt->deselect_for_p_unrefinement();
       }
       // Cannot delete nodes that are still marked as obsolete
       // because they may still be required to assemble the hanging schemes
       //-------------------------------------------------------------------
       // Mark up hanging nodes
       //----------------------
       // Output streams for the hanging nodes
       Vector<std::ofstream*> hanging_output_files;
       // Setup the output files for hanging nodes, this must be called
       // precisely once for the forest. Note that the files will only
       // actually be opened if doc_info.Doc_flag is true
       this->forest_pt()->open_hanging_node_files(doc_info,
                                                  hanging_output_files);
       for (unsigned long e = 0; e < num_tree_nodes; e++)
       {
         // Generic setup
         tree_nodes_pt[e]->object_pt()->setup_hanging_nodes(
           hanging_output_files);
         // Element specific setup
         tree_nodes_pt[e]->object_pt()->further_setup_hanging_nodes();
       }
       // Close the hanging node files and delete the memory allocated
       // for the streams
       this->forest_pt()->close_hanging_node_files(doc_info,
                                                   hanging_output_files);
       if (Global_timings::Doc_comprehensive_timings)
       {
         t_end = TimingHelpers::timer();
         oomph_info << "Time for setup_hanging_nodes() and "
                       "further_setup_hanging_nodes() for "
                    << num_tree_nodes << " elements: " << t_end - t_start
                    << std::endl;
         t_start = TimingHelpers::timer();
       }
       // Read out the number of continously interpolated values
       // from one of the elements (assuming it's the same in all elements)
       unsigned ncont_interpolated_values =
         tree_nodes_pt[0]->object_pt()->ncont_interpolated_values();
       // Complete the hanging nodes schemes by dealing with the
       // recursively hanging nodes
       this->complete_hanging_nodes(ncont_interpolated_values);
       if (Global_timings::Doc_comprehensive_timings)
       {
         t_end = TimingHelpers::timer();
         oomph_info << "Time for complete_hanging_nodes: " << t_end - t_start
                    << std::endl;
         t_start = TimingHelpers::timer();
       }
       if (Lookup_for_elements_next_boundary_is_setup)
       {
         this->setup_boundary_element_info();
       }
       if (Global_timings::Doc_comprehensive_timings)
       {
         t_end = TimingHelpers::timer();
         oomph_info << "Time for boundary element info: " << t_end - t_start
                    << std::endl;
         t_start = TimingHelpers::timer();
       }
       // BENFLAG: Reset all the node update elements.
       //         This is necessary to prevent the following case: A node N is
       //         shared between two elements, A and B. The update element for
       //         the node is set to A, say. Element A is p-refined and now
       //         nolonger has N as a node. However the node update element for N
       //         is still A but the node doesn't exist in A.
       MacroElementNodeUpdateElementBase* first_macro_el_pt =
         dynamic_cast<MacroElementNodeUpdateElementBase*>(this->element_pt(0));
       if (first_macro_el_pt != 0)
       {
         // Now set the node update info elementwise
         for (unsigned e = 0; e < this->nelement(); e++)
         {
           // Cast to macro element
           MacroElementNodeUpdateElementBase* macro_el_pt =
             dynamic_cast<MacroElementNodeUpdateElementBase*>(
               this->element_pt(e));
           if (macro_el_pt != 0)
           {
             // Get vector of geometric objects from element (construct vector
             // via copy operation)
             Vector<GeomObject*> geom_object_pt(macro_el_pt->geom_object_pt());
             // (Re)set node update info for all the nodes in the element
             macro_el_pt->set_node_update_info(geom_object_pt);
           }
         }
       }
 #ifdef PARANOID
       // Doc/check the neighbours
       //-------------------------
       Vector<Tree*> all_tree_nodes_pt;
       this->forest_pt()->stick_all_tree_nodes_into_vector(all_tree_nodes_pt);
       // Check the neighbours
       this->forest_pt()->check_all_neighbours(doc_info);
       // Check the integrity of the elements
       // -----------------------------------
       // Loop over elements and get the elemental integrity
       double max_error = 0.0;
       for (unsigned long e = 0; e < num_tree_nodes; e++)
       {
         double max_el_error;
         tree_nodes_pt[e]->object_pt()->check_integrity(max_el_error);
         // If the elemental error is greater than our maximum error
         // reset the maximum
         if (max_el_error > max_error)
         {
           max_error = max_el_error;
         }
       }
       if (max_error > RefineableElement::max_integrity_tolerance())
       {
         std::ostringstream error_stream;
         error_stream << "Mesh refined: Max. error in integrity check: "
                      << max_error << " is too big"
                      << "\ni.e. bigger than RefineableElement::"
                      << "max_integrity_tolerance()="
                      << RefineableElement::max_integrity_tolerance()
                      << std::endl;
         std::ofstream some_file;
         some_file.open("ProblemMesh.dat");
         for (unsigned long n = 0; n < n_node; n++)
         {
           // Get the pointer to the node
           Node* nod_pt = this->node_pt(n);
           // Get the dimension
           unsigned n_dim = nod_pt->ndim();
           // Output the coordinates
           for (unsigned i = 0; i < n_dim; i++)
           {
             some_file << this->node_pt(n)->x(i) << " ";
           }
           some_file << std::endl;
         }
         some_file.close();
         error_stream << "Documented problem mesh in ProblemMesh.dat"
                      << std::endl;
         throw OomphLibError(
           error_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
       }
       else
       {
         oomph_info << "Mesh refined: Max. error in integrity check: "
                    << max_error << " is OK" << std::endl;
         oomph_info
           << "i.e. less than RefineableElement::max_integrity_tolerance()="
           << RefineableElement::max_integrity_tolerance() << "\n"
           << std::endl;
       }
       if (Global_timings::Doc_comprehensive_timings)
       {
         t_end = TimingHelpers::timer();
         oomph_info << "Time for (paranoid only) checking of integrity: "
                    << t_end - t_start << std::endl;
         t_start = TimingHelpers::timer();
       }
 #endif
       // Loop over all elements other than the final level and deactivate the
       // objects, essentially set the pointer that point to nodes that are
       // about to be deleted to NULL. This must take place here because nodes
       // addressed by elements that are dead but still living in the tree might
       // have been made obsolete in the last round of refinement
       //(Not strictly required, as tree structure has not changed, but does no
       // harm)
       for (unsigned long e = 0; e < this->forest_pt()->ntree(); e++)
       {
         this->forest_pt()->tree_pt(e)->traverse_all(&Tree::deactivate_object);
       }
       // Now we can prune the dead nodes from the mesh.
       Vector<Node*> deleted_node_pt = this->prune_dead_nodes();
       if (Global_timings::Doc_comprehensive_timings)
       {
         t_end = TimingHelpers::timer();
         oomph_info << "Time for deactivating objects and pruning nodes: "
                    << t_end - t_start << std::endl;
         t_start = TimingHelpers::timer();
       }
       // Finally: Reorder the nodes within the mesh's node vector
       // to establish a standard ordering regardless of the sequence
       // of mesh refinements -- this is required to allow dump/restart
       // on refined meshes
       this->reorder_nodes();
       if (Global_timings::Doc_comprehensive_timings)
       {
         t_end = TimingHelpers::timer();
         oomph_info << "Time for reordering " << nnode()
                    << " nodes: " << t_end - t_start << std::endl;
         t_start = TimingHelpers::timer();
       }
       // Now we can correct the nodes on boundaries that were hanging that
       // are no longer hanging
       // Only bother if we have more than two dimensions
       if (mesh_dim > 2)
       {
         // Loop over the boundaries
         for (unsigned b = 0; b < n_boundary; b++)
         {
           // Remove deleted nodes from the set
           unsigned n_del = deleted_node_pt.size();
           for (unsigned j = 0; j < n_del; j++)
           {
             hanging_nodes_on_boundary_pt[b].erase(deleted_node_pt[j]);
           }
           // If the nodes that were hanging are still hanging then remove them
           // from the set (note increment is not in for command for efficiencty)
           for (std::set<Node*>::iterator it =
                  hanging_nodes_on_boundary_pt[b].begin();
                it != hanging_nodes_on_boundary_pt[b].end();)
           {
             if ((*it)->is_hanging())
             {
               hanging_nodes_on_boundary_pt[b].erase(it++);
             }
             else
             {
               ++it;
             }
           }
           // Are there any nodes that have changed geometric hanging status
           // on the boundary
           // The slightly painful part is that we must adjust the position
           // via the macro-elements which are only available through the
           // elements and not the nodes.
           if (hanging_nodes_on_boundary_pt[b].size() > 0)
           {
             // If so we loop over all elements adjacent to the boundary
             unsigned n_boundary_element = this->nboundary_element(b);
             for (unsigned e = 0; e < n_boundary_element; ++e)
             {
               // Get a pointer to the element
               FiniteElement* el_pt = this->boundary_element_pt(b, e);
               // Do we have a solid element
               SolidFiniteElement* solid_el_pt =
                 dynamic_cast<SolidFiniteElement*>(el_pt);
               // Determine whether there is a macro element
               bool macro_present = (el_pt->macro_elem_pt() != 0);
               // Or a solid macro element
               if (solid_el_pt != 0)
               {
                 macro_present |= (solid_el_pt->undeformed_macro_elem_pt() != 0);
               }
               // Only bother to do anything if there is a macro element
               // or undeformed macro element in a SolidElement
               if (macro_present)
               {
                 // Loop over the nodes
                 // ALH: (could optimise to only loop over
                 // node associated with the boundary with more effort)
                 unsigned n_el_node = el_pt->nnode();
                 for (unsigned n = 0; n < n_el_node; n++)
                 {
                   // Cache pointer to the node
                   Node* nod_pt = el_pt->node_pt(n);
                   if (nod_pt->is_on_boundary(b))
                   {
                     // Is the Node in our set
                     std::set<Node*>::iterator it =
                       hanging_nodes_on_boundary_pt[b].find(nod_pt);
                     // If we have found the Node then update the position
                     // to be consistent with the macro-element representation
                     if (it != hanging_nodes_on_boundary_pt[b].end())
                     {
                       // Specialise local and global coordinates to 3D
                       // because there is only a problem in 3D.
                       Vector<double> s(3), x(3);
                       // Find the local coordinate of the ndoe
                       el_pt->local_coordinate_of_node(n, s);
                       // Find the number of time history values
                       const unsigned ntstorage = nod_pt->ntstorage();
                       // Do we have a solid node
                       SolidNode* solid_node_pt =
                         dynamic_cast<SolidNode*>(nod_pt);
                       if (solid_node_pt)
                       {
                         // Assign Lagrangian coordinates from undeformed
                         // macro element (if it has one -- get_x_and_xi()
                         // does "the right thing" anyway. Leave actual
                         // nodal positions alone -- we're doing a solid
                         // mechanics problem and once we're going
                         // the nodal positions are always computed, never
                         // (automatically) reset to macro-element based
                         // positions; not even on pinned boundaries
                         // because the user may have other ideas about where
                         // these should go -- pinning means "don't touch the
                         // value", not "leave where the macro-element thinks
                         // it should be"
                         Vector<double> x_fe(3), xi(3), xi_fe(3);
                         solid_el_pt->get_x_and_xi(s, x_fe, x, xi_fe, xi);
                         for (unsigned i = 0; i < 3; i++)
{
                           solid_node_pt->xi(i) = xi[i];
                         }
                       }
                       else
                       {
                         // Set position and history values from the
                         // macro-element representation
                         for (unsigned t = 0; t < ntstorage; t++)
{
                           // Get the history value from the macro element
                           el_pt->get_x(t, s, x);
                           // Set the coordinate to that of the macroelement
                           // representation
                           for (unsigned i = 0; i < 3; i++)
{
                             nod_pt->x(t, i) = x[i];
                           }
                         }
                       } // End of non-solid node case
                       // Now remove the node from the list
                       hanging_nodes_on_boundary_pt[b].erase(it);
                       // If there are no Nodes left then exit the loops
                       if (hanging_nodes_on_boundary_pt[b].size() == 0)
                       {
                         e = n_boundary_element;
                         break;
                       }
                     }
                   }
                 }
               } // End of macro element case
             }
           }
         }
       } // End of case when we have fixed nodal positions
       // Final doc
       //-----------
       if (doc_info.is_doc_enabled())
       {
         // Doc the boundary conditions ('0' for non-existent, '1' for free,
         //----------------------------------------------------------------
         // '2' for pinned -- ideal for tecplot scatter sizing.
         //----------------------------------------------------
         // num_tree_nodes=tree_nodes_pt.size();
         // Determine maximum number of values at any node in this type of
         // element
         RefineableElement* el_pt = tree_nodes_pt[0]->object_pt();
         // Initalise max_nval
         unsigned max_nval = 0;
         for (unsigned n = 0; n < el_pt->nnode(); n++)
         {
           if (el_pt->node_pt(n)->nvalue() > max_nval)
           {
             max_nval = el_pt->node_pt(n)->nvalue();
           }
         }
         // Open the output file
         std::ostringstream fullname;
         std::ofstream bcs_file;
         fullname.str("");
         fullname << doc_info.directory() << "/bcs" << doc_info.number()
                  << ".dat";
         bcs_file.open(fullname.str().c_str());
         // Loop over elements
         for (unsigned long e = 0; e < num_tree_nodes; e++)
         {
           el_pt = tree_nodes_pt[e]->object_pt();
           // Loop over nodes in element
           unsigned n_nod = el_pt->nnode();
           for (unsigned n = 0; n < n_nod; n++)
           {
             // Get pointer to the node
             Node* nod_pt = el_pt->node_pt(n);
             // Find the dimension of the node
             unsigned n_dim = nod_pt->ndim();
             // Write the nodal coordinates to the file
             for (unsigned i = 0; i < n_dim; i++)
             {
               bcs_file << nod_pt->x(i) << " ";
             }
             // Loop over all values in this element
             for (unsigned i = 0; i < max_nval; i++)
             {
               // Value exists at this node:
               if (i < nod_pt->nvalue())
               {
                 bcs_file << " " << 1 + nod_pt->is_pinned(i);
               }
               // ...if not just dump out a zero
               else
               {
                 bcs_file << " 0 ";
               }
             }
             bcs_file << std::endl;
           }
         }
         bcs_file.close();
         // Doc all nodes
         //---------------
         std::ofstream all_nodes_file;
         fullname.str("");
         fullname << doc_info.directory() << "/all_nodes" << doc_info.number()
                  << ".dat";
         all_nodes_file.open(fullname.str().c_str());
         all_nodes_file << "ZONE \n";
         // Need to recompute the number of nodes since it may have
         // changed during mesh refinement/unrefinement
         n_node = this->nnode();
         for (unsigned long n = 0; n < n_node; n++)
         {
           Node* nod_pt = this->node_pt(n);
           unsigned n_dim = nod_pt->ndim();
           for (unsigned i = 0; i < n_dim; i++)
           {
             all_nodes_file << this->node_pt(n)->x(i) << " ";
           }
           all_nodes_file << std::endl;
         }
         all_nodes_file.close();
         // Doc all hanging nodes:
         //-----------------------
         std::ofstream some_file;
         fullname.str("");
         fullname << doc_info.directory() << "/all_hangnodes"
                  << doc_info.number() << ".dat";
         some_file.open(fullname.str().c_str());
         for (unsigned long n = 0; n < n_node; n++)
         {
           Node* nod_pt = this->node_pt(n);
           if (nod_pt->is_hanging())
           {
             unsigned n_dim = nod_pt->ndim();
             for (unsigned i = 0; i < n_dim; i++)
             {
               some_file << nod_pt->x(i) << " ";
             }
             // ALH: Added this to stop Solid problems seg-faulting
             if (this->node_pt(n)->nvalue() > 0)
             {
               some_file << " " << nod_pt->raw_value(0);
             }
             some_file << std::endl;
           }
         }
         some_file.close();
         // Doc all hanging nodes and their masters
         // View with QHangingNodesWithMasters.mcr
         fullname.str("");
         fullname << doc_info.directory() << "/geometric_hangnodes_withmasters"
                  << doc_info.number() << ".dat";
         some_file.open(fullname.str().c_str());
         for (unsigned long n = 0; n < n_node; n++)
         {
           Node* nod_pt = this->node_pt(n);
           if (nod_pt->is_hanging())
           {
             unsigned n_dim = nod_pt->ndim();
             unsigned nmaster = nod_pt->hanging_pt()->nmaster();
             some_file << "ZONE I=" << nmaster + 1 << std::endl;
             for (unsigned i = 0; i < n_dim; i++)
             {
               some_file << nod_pt->x(i) << " ";
             }
             some_file << " 2 " << std::endl;
             for (unsigned imaster = 0; imaster < nmaster; imaster++)
             {
               Node* master_nod_pt =
                 nod_pt->hanging_pt()->master_node_pt(imaster);
               unsigned n_dim = master_nod_pt->ndim();
               for (unsigned i = 0; i < n_dim; i++)
               {
                 some_file << master_nod_pt->x(i) << " ";
               }
               some_file << " 1 " << std::endl;
             }
           }
         }
         some_file.close();
         // Doc all hanging nodes and their masters
         // View with QHangingNodesWithMasters.mcr
         for (unsigned i = 0; i < ncont_interpolated_values; i++)
         {
           fullname.str("");
           fullname << doc_info.directory()
                    << "/nonstandard_hangnodes_withmasters" << i << "_"
                    << doc_info.number() << ".dat";
           some_file.open(fullname.str().c_str());
           unsigned n_nod = this->nnode();
           for (unsigned long n = 0; n < n_nod; n++)
           {
             Node* nod_pt = this->node_pt(n);
             if (nod_pt->is_hanging(i))
             {
               if (nod_pt->hanging_pt(i) != nod_pt->hanging_pt())
               {
                 unsigned nmaster = nod_pt->hanging_pt(i)->nmaster();
                 some_file << "ZONE I=" << nmaster + 1 << std::endl;
                 unsigned n_dim = nod_pt->ndim();
                 for (unsigned j = 0; j < n_dim; j++)
                 {
                   some_file << nod_pt->x(j) << " ";
                 }
                 some_file << " 2 " << std::endl;
                 for (unsigned imaster = 0; imaster < nmaster; imaster++)
                 {
                   Node* master_nod_pt =
                     nod_pt->hanging_pt(i)->master_node_pt(imaster);
                   unsigned n_dim = master_nod_pt->ndim();
                   for (unsigned j = 0; j < n_dim; j++)
                   {
                     //               some_file << master_nod_pt->x(i) << " ";
                   }
                   some_file << " 1 " << std::endl;
                 }
               }
             }
           }
           some_file.close();
         }
       } // End of documentation
     } // End if (this->nelement()>0)
     // std::cout << "p_adapt_mesh(): Checking stuff works!" << std::endl;
     // for(unsigned j=0; j<this->nnode(); j++)
     // {
     //  MacroElementNodeUpdateNode* macro_nod_pt =
     //  dynamic_cast<MacroElementNodeUpdateNode*>(this->node_pt(j));
     //  if(macro_nod_pt!=0)
     //   {
     //    bool big_problem = true;
     //    std::cout << "Node " << macro_nod_pt << " at [ " << macro_nod_pt->x(0)
     //    << ", " << macro_nod_pt->x(1) << " ]" << std::endl; FiniteElement*
     //    up_el_pt =
     //    dynamic_cast<FiniteElement*>(macro_nod_pt->node_update_element_pt());
     //    for(unsigned l=0; l<up_el_pt->nnode(); l++)
     //     {
     //      if(up_el_pt->node_pt(l)==macro_nod_pt)
     //       {
     //        big_problem = false;
     //        break;
     //       }
     //     }
     //    if(big_problem)
     //     {
     //      std::cout << "  This node doesn't exist in it's update element!" <<
     //      std::endl;
     //     }
     //   }
     // }
 #ifdef OOMPH_HAS_MPI
     // Now (re-)classify halo and haloed nodes and synchronise hanging
     // nodes
     if (this->is_mesh_distributed())
     {
       classify_halo_and_haloed_nodes(doc_info, doc_info.is_doc_enabled());
     }
 #endif
   }
References b, oomph::Mesh::boundary_element_pt(), oomph::TreeForest::check_all_neighbours(), oomph::TreeForest::close_hanging_node_files(), complete_hanging_nodes(), oomph::Tree::deactivate_object(), oomph::Mesh::delete_all_external_storage(), oomph::PRefineableElement::deselect_for_p_refinement(), oomph::PRefineableElement::deselect_for_p_unrefinement(), oomph::FiniteElement::dim(), oomph::DocInfo::directory(), oomph::Global_timings::Doc_comprehensive_timings, oomph::RefineableMeshBase::doc_info(), e(), oomph::Mesh::element_pt(), Eigen::placeholders::end, oomph::Mesh::finite_element_pt(), forest_pt(), oomph::MacroElementNodeUpdateElementBase::geom_object_pt(), oomph::Node::get_boundaries_pt(), oomph::FiniteElement::get_x(), oomph::SolidFiniteElement::get_x_and_xi(), oomph::Node::hanging_pt(), i, oomph::DocInfo::is_doc_enabled(), oomph::Node::is_hanging(), oomph::Mesh::is_mesh_distributed(), oomph::Node::is_on_boundary(), oomph::Data::is_pinned(), j, oomph::SolidNode::lagrangian_position(), oomph::FiniteElement::local_coordinate_of_node(), oomph::Mesh::Lookup_for_elements_next_boundary_is_setup, oomph::FiniteElement::macro_elem_pt(), oomph::HangInfo::master_node_pt(), oomph::RefineableMeshBase::max_error(), oomph::RefineableElement::max_integrity_tolerance(), n, oomph::Mesh::nboundary(), oomph::Mesh::nboundary_element(), oomph::Node::ndim(), oomph::Mesh::nelement(), oomph::SolidNode::nlagrangian(), oomph::HangInfo::nmaster(), oomph::FiniteElement::nnode(), oomph::Mesh::nnode(), oomph::FiniteElement::node_pt(), oomph::Mesh::node_pt(), oomph::AlgebraicNode::node_update(), oomph::TreeForest::ntree(), oomph::Data::ntstorage(), oomph::DocInfo::number(), oomph::Data::nvalue(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::oomph_info, oomph::TreeForest::open_hanging_node_files(), p_refine_elements_if_required(), oomph::Node::position(), oomph::Mesh::prune_dead_nodes(), oomph::Node::raw_value(), oomph::Mesh::reorder_nodes(), s, oomph::MacroElementNodeUpdateElementBase::set_node_update_info(), oomph::Node::set_non_obsolete(), oomph::Node::set_nonhanging(), oomph::Node::set_obsolete(), oomph::Data::set_value(), oomph::Mesh::setup_boundary_element_info(), size, oomph::TreeForest::stick_all_tree_nodes_into_vector(), oomph::TreeForest::stick_leaves_into_vector(), plotPSD::t, oomph::TimingHelpers::timer(), oomph::Tree::traverse_all(), oomph::TreeForest::tree_pt(), oomph::SolidFiniteElement::undeformed_macro_elem_pt(), oomph::Node::value(), plotDoE::x, oomph::Node::x(), and oomph::SolidNode::xi().
p_refine_elements_if_required()
virtual void oomph::TreeBasedRefineableMeshBase::p_refine_elements_if_required () protected pure virtual
p-refine all the elements in the mesh if required. This template free interface will be overloaded in RefineableMesh<ELEMENT> so that any temporary copies of the element that are created will be of the correct type.
Implemented in oomph::TreeBasedRefineableMesh< ELEMENT >.
Referenced by p_adapt_mesh().
p_refine_selected_elements() [1/2]
void oomph::TreeBasedRefineableMeshBase::p_refine_selected_elements (const Vector< PRefineableElement * > & elements_to_be_refined_pt)
p-refine mesh by refining the elements identified by their pointers.
p-refine mesh by refining the elements identified by their pointers.
   {
 #ifdef OOMPH_HAS_MPI
     if (this->is_mesh_distributed())
     {
       std::ostringstream warn_stream;
       warn_stream << "You are attempting to refine selected elements of a "
                   << std::endl
                   << "distributed mesh. This may have undesired effects."
                   << std::endl;
       OomphLibWarning(warn_stream.str(),
                       "TreeBasedRefineableMeshBase::refine_selected_elements()",
                       OOMPH_EXCEPTION_LOCATION);
     }
 #endif
     // Select elements for refinement
     unsigned long nref = elements_to_be_refined_pt.size();
     for (unsigned long e = 0; e < nref; e++)
     {
       elements_to_be_refined_pt[e]->select_for_p_refinement();
     }
     // Do the actual mesh adaptation
     p_adapt_mesh();
   }
References e(), oomph::Mesh::is_mesh_distributed(), OOMPH_EXCEPTION_LOCATION, and p_adapt_mesh().
p_refine_selected_elements() [2/2]
void oomph::TreeBasedRefineableMeshBase::p_refine_selected_elements (const Vector< unsigned > & elements_to_be_refined)
p-refine mesh by refining the elements identified by their numbers.
p-refine mesh by refining the elements identified by their numbers.
   {
 #ifdef OOMPH_HAS_MPI
     if (this->is_mesh_distributed())
     {
       std::ostringstream warn_stream;
       warn_stream << "You are attempting to refine selected elements of a "
                   << std::endl
                   << "distributed mesh. This may have undesired effects."
                   << std::endl;
       OomphLibWarning(warn_stream.str(),
                       "TreeBasedRefineableMeshBase::refine_selected_elements()",
                       OOMPH_EXCEPTION_LOCATION);
     }
 #endif
     // Select elements for refinement
     unsigned long nref = elements_to_be_refined.size();
     for (unsigned long e = 0; e < nref; e++)
     {
       // Get pointer to p-refineable element
       PRefineableElement* el_pt = dynamic_cast<PRefineableElement*>(
         this->element_pt(elements_to_be_refined[e]));
       // Mark for p-refinement if possible. If not then p_adapt_mesh() will
       // report the error.
       if (el_pt != 0)
       {
         el_pt->select_for_p_refinement();
       }
     }
     // Do the actual mesh adaptation
     p_adapt_mesh();
   }
References e(), oomph::Mesh::element_pt(), oomph::Mesh::is_mesh_distributed(), OOMPH_EXCEPTION_LOCATION, p_adapt_mesh(), and oomph::PRefineableElement::select_for_p_refinement().
p_refine_uniformly() [1/2]
void oomph::TreeBasedRefineableMeshBase::p_refine_uniformly () inline virtual
p-refine mesh uniformly
Reimplemented from oomph::RefineableMeshBase.
     {
       RefineableMeshBase::p_refine_uniformly();
     }
References oomph::RefineableMeshBase::p_refine_uniformly().
p_refine_uniformly() [2/2]
void oomph::TreeBasedRefineableMeshBase::p_refine_uniformly (DocInfo & doc_info) virtual
p-refine mesh uniformly and doc process
p-refine mesh uniformly
Reimplemented from oomph::RefineableMeshBase.
   {
     // Select all elements for refinement
     unsigned long Nelement = this->nelement();
     for (unsigned long e = 0; e < Nelement; e++)
     {
       // Get pointer to p-refineable element
       PRefineableElement* el_pt =
         dynamic_cast<PRefineableElement*>(this->element_pt(e));
       // Mark for p-refinement if possible. If not then p_adapt_mesh() will
       // report the error.
       if (el_pt != 0)
       {
         el_pt->select_for_p_refinement();
       }
     }
     // Do the actual mesh adaptation
     p_adapt_mesh(doc_info);
   }
References oomph::RefineableMeshBase::doc_info(), e(), oomph::Mesh::element_pt(), oomph::Mesh::nelement(), p_adapt_mesh(), and oomph::PRefineableElement::select_for_p_refinement().
p_unrefine_uniformly()
void oomph::TreeBasedRefineableMeshBase::p_unrefine_uniformly (DocInfo & doc_info)
p-unrefine mesh uniformly
p-unrefine mesh uniformly Unlike in h-refinement, we can simply p-unrefine each element in the mesh
   {
     // Select all elements for unrefinement
     unsigned long Nelement = this->nelement();
     for (unsigned long e = 0; e < Nelement; e++)
     {
       // Get pointer to p-refineable element
       PRefineableElement* el_pt =
         dynamic_cast<PRefineableElement*>(this->element_pt(e));
       // Mark for p-refinement if possible. If not then p_adapt_mesh() will
       // report the error.
       if (el_pt != 0)
       {
         el_pt->select_for_p_unrefinement();
       }
     }
     // Do the actual mesh adaptation
     p_adapt_mesh(doc_info);
   }
References oomph::RefineableMeshBase::doc_info(), e(), oomph::Mesh::element_pt(), oomph::Mesh::nelement(), p_adapt_mesh(), and oomph::PRefineableElement::select_for_p_unrefinement().
read_refinement()
void oomph::TreeBasedRefineableMeshBase::read_refinement (std::ifstream & restart_file, Vector< Vector< unsigned >> & to_be_refined) virtual
Read refinement pattern to allow for rebuild.
Read refinement pattern to allow for rebuild
   {
     std::string input_string;
     // Read max refinement level:
     // Read line up to termination sign
     getline(restart_file, input_string, '#');
     // Ignore rest of line
     restart_file.ignore(80, '\n');
     // Convert
     unsigned max_level = std::atoi(input_string.c_str());
     // Assign storage for refinement pattern
     to_be_refined.resize(max_level);
     // Read the number of the elements that need to be refined at different
     // levels
     for (unsigned l = 0; l < max_level; l++)
     {
       // Read line up to termination sign
       getline(restart_file, input_string, '#');
       // Ignore rest of line
       restart_file.ignore(80, '\n');
       // Convert
       unsigned n_to_be_refined = atoi(input_string.c_str());
       ;
       // Assign storage
       to_be_refined[l].resize(n_to_be_refined);
       // Read numbers of the elements that need to be refined
       for (unsigned i = 0; i < n_to_be_refined; i++)
       {
         restart_file >> to_be_refined[l][i];
       }
     }
   }
References i, and oomph::Global_string_for_annotation::string().
Referenced by refine().
refine()
void oomph::TreeBasedRefineableMeshBase::refine (std::ifstream & restart_file) virtual
Refine mesh according to refinement pattern in restart file.
Refine base mesh according to refinement pattern in restart file.
   {
     // Assign storage for refinement pattern
     Vector<Vector<unsigned>> to_be_refined;
     // Read refinement pattern
     read_refinement(restart_file, to_be_refined);
     // Refine
     refine_base_mesh(to_be_refined);
   }
References read_refinement(), and refine_base_mesh().
refine_as_in_reference_mesh()
void oomph::TreeBasedRefineableMeshBase::refine_as_in_reference_mesh (TreeBasedRefineableMeshBase *const & ref_mesh_pt) virtual
Refine mesh once so that its topology etc becomes that of the (finer!) reference mesh – if possible! Useful for meshes in multigrid hierarchies. If the meshes are too different and the conversion cannot be performed, the code dies (provided PARANOID is enabled).
   {
     oomph_info << "WARNING : This has not been checked comprehensively yet"
                << std::endl
                << "Check it and remove this break " << std::endl;
     pause("Yes really pause");
 #ifdef PARANOID
     // The max. refinement levels of the two meshes need to differ
     // by one, otherwise what we're doing here doesn't make sense.
     unsigned my_min, my_max;
     get_refinement_levels(my_min, my_max);
     unsigned ref_min, ref_max;
     ref_mesh_pt->get_refinement_levels(ref_min, ref_max);
     if (ref_max != my_max + 1)
     {
       std::ostringstream error_stream;
       error_stream
         << "Meshes definitely don't differ by one refinement level \n"
         << "max. refinement levels: " << ref_max << " " << my_max << std::endl;
       throw OomphLibError(
         error_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
 #endif
     // Vector storing the elements of the uniformly unrefined mesh
     Vector<Tree*> coarse_elements_pt;
     // Map storing which father elements have already been added to coarse mesh
     // (Default return is 0).
     std::map<Tree*, unsigned> father_element_included;
     // Extract active elements (=leaf nodes in the quadtree) from reference
     // mesh.
     Vector<Tree*> leaf_nodes_pt;
     ref_mesh_pt->forest_pt()->stick_leaves_into_vector(leaf_nodes_pt);
     // Loop over all elements (in their quadtree impersonation) and
     // check if their fathers's sons are all leaves too:
     unsigned nelem = leaf_nodes_pt.size();
     for (unsigned e = 0; e < nelem; e++)
     {
       // Pointer to leaf node
       Tree* leaf_pt = leaf_nodes_pt[e];
       // Get pointer to father:
       Tree* father_pt = leaf_pt->father_pt();
       // If we don't have a father we're at the root level in which
       // case this element can't be unrefined.
       if (0 == father_pt)
       {
         coarse_elements_pt.push_back(leaf_pt);
       }
       else
       {
         // Loop over the father's sons to check if they're
         // all non-leafs, i.e. if they can be unrefined
         bool can_unrefine = true;
         unsigned n_sons = father_pt->nsons();
         for (unsigned i = 0; i < n_sons; i++)
         {
           // If (at least) one of the sons is not a leaf, we can't unrefine
           if (!father_pt->son_pt(i)->is_leaf()) can_unrefine = false;
         }
         // If we can unrefine, the father element will be
         // an element in the coarse mesh, the sons won't
         if (can_unrefine)
         {
           if (father_element_included[father_pt] == 0)
           {
             coarse_elements_pt.push_back(father_pt);
             father_element_included[father_pt] = 1;
           }
         }
         // Son will still be there on the coarse mesh
         else
         {
           coarse_elements_pt.push_back(leaf_pt);
         }
       }
     }
     // Number of elements in ref mesh if it was unrefined uniformly:
     unsigned nel_coarse = coarse_elements_pt.size();
 #ifdef PARANOID
     bool stop_it = false;
     // The numbers had better match otherwise we might as well stop now...
     if (nel_coarse != this->nelement())
     {
       oomph_info << "Number of elements in uniformly unrefined reference mesh: "
                  << nel_coarse << std::endl;
       oomph_info << "Number of elements in 'this' mesh: " << nel_coarse
                  << std::endl;
       oomph_info << "don't match" << std::endl;
       stop_it = true;
     }
 #endif
     // Now loop over all elements in uniformly coarsened reference mesh
     // and check if add the number of any element that was created
     // by having had its sons merged to the vector of elements that
     // need to get refined if we go the other way
     Vector<unsigned> elements_to_be_refined;
     for (unsigned i = 0; i < nel_coarse; i++)
     {
       if (father_element_included[coarse_elements_pt[i]] == 1)
       {
         elements_to_be_refined.push_back(i);
       }
     }
 #ifdef PARANOID
     // Doc troublesome meshes:
     if (stop_it)
     {
       std::ofstream some_file;
       some_file.open("orig_mesh.dat");
       this->output(some_file);
       some_file.close();
       oomph_info << "Documented original ('this')mesh in orig_mesh.dat"
                  << std::endl;
     }
 #endif
     // Now refine precisely these elements in "this" mesh.
     refine_selected_elements(elements_to_be_refined);
 #ifdef PARANOID
     // Check if the nodal positions of all element's nodes agree
     // in the two fine meshes:
     double tol = 1.0e-5;
     for (unsigned e = 0; e < nelem; e++)
     {
       // Get elements
       FiniteElement* ref_el_pt = ref_mesh_pt->finite_element_pt(e);
       FiniteElement* el_pt = this->finite_element_pt(e);
       // Loop over nodes
       unsigned nnod = ref_el_pt->nnode();
       for (unsigned j = 0; j < nnod; j++)
       {
         // Get nodes
         Node* ref_node_pt = ref_el_pt->node_pt(j);
         Node* node_pt = el_pt->node_pt(j);
         // Check error in position
         double error = 0.0;
         unsigned ndim = node_pt->ndim();
         for (unsigned i = 0; i < ndim; i++)
         {
           error += pow(node_pt->x(i) - ref_node_pt->x(i), 2);
         }
         error = sqrt(error);
         if (error > tol)
         {
           oomph_info << "Error in nodal position of node " << j << ": " << error
                      << "           [tol=" << tol << "]" << std::endl;
           stop_it = true;
         }
       }
     }
     // Do we have a death wish?
     if (stop_it)
     {
       // Doc troublesome meshes:
       std::ofstream some_file;
       some_file.open("refined_mesh.dat");
       this->output(some_file);
       some_file.close();
       some_file.open("finer_mesh.dat");
       ref_mesh_pt->output(some_file);
       some_file.close();
       throw OomphLibError(
         "Bailing out. Doced refined_mesh.dat finer_mesh.dat\n",
         OOMPH_CURRENT_FUNCTION,
         OOMPH_EXCEPTION_LOCATION);
     }
 #endif
   }
References e(), calibrate::error, oomph::Tree::father_pt(), oomph::Mesh::finite_element_pt(), forest_pt(), get_refinement_levels(), i, oomph::Tree::is_leaf(), j, oomph::Node::ndim(), oomph::Mesh::nelement(), oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::Mesh::node_pt(), oomph::Tree::nsons(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::oomph_info, oomph::Mesh::output(), oomph::pause(), Eigen::bfloat16_impl::pow(), refine_selected_elements(), oomph::Tree::son_pt(), sqrt(), oomph::TreeForest::stick_leaves_into_vector(), and oomph::Node::x().
refine_base_mesh()
void oomph::TreeBasedRefineableMeshBase::refine_base_mesh (Vector< Vector< unsigned >> & to_be_refined)
Refine base mesh according to specified refinement pattern.
Refine original, unrefined mesh according to specified refinement pattern (relative to original, unrefined mesh).
   {
     // Get mesh back to unrefined state
     unsigned my_max, my_min;
     get_refinement_levels(my_min, my_max);
     // Max refinement level:
     unsigned my_max_level = to_be_refined.size();
     unsigned global_max = 0;
     unsigned global_max_level = 0;
     Vector<unsigned> data(2, 0);
     data[0] = my_max;
     data[1] = my_max_level;
     Vector<unsigned> global_data(2, 0);
 #ifdef OOMPH_HAS_MPI
     if (this->is_mesh_distributed())
     {
       MPI_Allreduce(&data[0],
                     &global_data[0],
                     2,
                     MPI_UNSIGNED,
                     MPI_MAX,
                     Comm_pt->mpi_comm());
       global_max = global_data[0];
       global_max_level = global_data[1];
     }
     else
 #endif
     {
       global_max = my_max;
       global_max_level = my_max_level;
     }
     for (unsigned i = 0; i < global_max; i++)
     {
       unrefine_uniformly();
     }
     // Do refinement steps in current mesh
     for (unsigned l = 0; l < global_max_level; l++)
     {
       // Loop over elements that need to be refined at this level
       unsigned n_to_be_refined = 0;
       if (l < my_max_level) n_to_be_refined = to_be_refined[l].size();
       // Select relevant elements to be refined
       for (unsigned i = 0; i < n_to_be_refined; i++)
       {
         dynamic_cast<RefineableElement*>(this->element_pt(to_be_refined[l][i]))
           ->select_for_refinement();
       }
       // Now do the actual mesh refinement
       adapt_mesh();
     }
   }
References adapt_mesh(), data, oomph::Mesh::element_pt(), get_refinement_levels(), i, oomph::Mesh::is_mesh_distributed(), and unrefine_uniformly().
Referenced by PolarNSProblem< ELEMENT >::output_streamfunction(), refine(), refine_base_mesh_as_in_reference_mesh(), and refine_base_mesh_as_in_reference_mesh_minus_one().
refine_base_mesh_as_in_reference_mesh()
void oomph::TreeBasedRefineableMeshBase::refine_base_mesh_as_in_reference_mesh (TreeBasedRefineableMeshBase *const & ref_mesh_pt) virtual
Refine to same degree as the reference mesh.
Refine base mesh to same degree as reference mesh (relative to original unrefined mesh).
   {
     // Assign storage for refinement pattern
     Vector<Vector<unsigned>> to_be_refined;
     // Get refinement pattern of reference mesh:
     ref_mesh_pt->get_refinement_pattern(to_be_refined);
     // Refine mesh according to given refinement pattern
     refine_base_mesh(to_be_refined);
   }
References get_refinement_pattern(), and refine_base_mesh().
refine_base_mesh_as_in_reference_mesh_minus_one()
bool oomph::TreeBasedRefineableMeshBase::refine_base_mesh_as_in_reference_mesh_minus_one (TreeBasedRefineableMeshBase *const & ref_mesh_pt) virtual
Refine base mesh to same degree as reference mesh minus one level of refinement (relative to original unrefined mesh). Useful function for multigrid solvers; allows the easy copy of a mesh to the level of refinement just below the current one
Refine to same degree as the reference mesh minus one. Useful function for multigrid solvers; allows the easy copy of a mesh to the level of refinement just below the current one. Returns a boolean variable which indicates if the reference mesh has not been refined at all
   {
     // Assign storage for refinement pattern
     Vector<Vector<unsigned>> to_be_refined;
     // Get refinement pattern of reference mesh:
     ref_mesh_pt->get_refinement_pattern(to_be_refined);
     // Find the length of the vector
     unsigned nrefinement_levels = to_be_refined.size();
     // If the reference mesh has not been refined a single time then
     // we cannot create an unrefined copy so stop here
     if (nrefinement_levels == 0)
     {
       return false;
     }
     // If the reference mesh has been refined at least once
     else
     {
       // Remove the last entry of the vector to make sure we refine to
       // the same level minus one
       to_be_refined.resize(nrefinement_levels - 1);
       // Refine mesh according to given refinement pattern
       refine_base_mesh(to_be_refined);
       // Indicate that it was possible to create an unrefined copy
       return true;
     }
   }
References get_refinement_pattern(), and refine_base_mesh().
Referenced by oomph::MGSolver< DIM >::setup_mg_hierarchy(), and oomph::HelmholtzMGPreconditioner< DIM >::setup_mg_hierarchy().
refine_selected_elements() [1/2]
void oomph::TreeBasedRefineableMeshBase::refine_selected_elements (const Vector< RefineableElement * > & elements_to_be_refined_pt) virtual
Refine mesh by splitting the elements identified by their pointers.
Refine mesh by splitting the elements identified by their pointers
   {
 #ifdef OOMPH_HAS_MPI
     if (this->is_mesh_distributed())
     {
       std::ostringstream warn_stream;
       warn_stream << "You are attempting to refine selected elements of a "
                   << std::endl
                   << "distributed mesh. This may have undesired effects."
                   << std::endl;
       OomphLibWarning(warn_stream.str(),
                       "TreeBasedRefineableMeshBase::refine_selected_elements()",
                       OOMPH_EXCEPTION_LOCATION);
     }
 #endif
     // Select elements for refinement
     unsigned long nref = elements_to_be_refined_pt.size();
     for (unsigned long e = 0; e < nref; e++)
     {
       elements_to_be_refined_pt[e]->select_for_refinement();
     }
     // Do the actual mesh adaptation
     adapt_mesh();
   }
References adapt_mesh(), e(), oomph::Mesh::is_mesh_distributed(), and OOMPH_EXCEPTION_LOCATION.
refine_selected_elements() [2/2]
void oomph::TreeBasedRefineableMeshBase::refine_selected_elements (const Vector< unsigned > & elements_to_be_refined) virtual
Refine mesh by splitting the elements identified by their numbers.
   {
 #ifdef OOMPH_HAS_MPI
     if (this->is_mesh_distributed())
     {
       std::ostringstream warn_stream;
       warn_stream << "You are attempting to refine selected elements of a "
                   << std::endl
                   << "distributed mesh. This may have undesired effects."
                   << std::endl;
       OomphLibWarning(warn_stream.str(),
                       "TreeBasedRefineableMeshBase::refine_selected_elements()",
                       OOMPH_EXCEPTION_LOCATION);
     }
 #endif
     // Select elements for refinement
     unsigned long nref = elements_to_be_refined.size();
     for (unsigned long e = 0; e < nref; e++)
     {
       dynamic_cast<RefineableElement*>(
         this->element_pt(elements_to_be_refined[e]))
         ->select_for_refinement();
     }
     // Do the actual mesh adaptation
     adapt_mesh();
   }
References adapt_mesh(), e(), oomph::Mesh::element_pt(), oomph::Mesh::is_mesh_distributed(), and OOMPH_EXCEPTION_LOCATION.
Referenced by FSIRingProblem::FSIRingProblem(), and refine_as_in_reference_mesh().
refine_uniformly() [1/2]
void oomph::TreeBasedRefineableMeshBase::refine_uniformly () inline virtual
Refine mesh uniformly.
Reimplemented from oomph::RefineableMeshBase.
Reimplemented in oomph::RefineableQuadFromTriangleMesh< ELEMENT >.
     {
       RefineableMeshBase::refine_uniformly();
     }
References oomph::RefineableMeshBase::refine_uniformly().
refine_uniformly() [2/2]
void oomph::TreeBasedRefineableMeshBase::refine_uniformly (DocInfo & doc_info) virtual
Refine mesh uniformly and doc process.
Refine mesh uniformly.
Implements oomph::RefineableMeshBase.
Reimplemented in oomph::RefineableQuadFromTriangleMesh< ELEMENT >.
   {
     // Select all elements for refinement
     unsigned long Nelement = this->nelement();
     for (unsigned long e = 0; e < Nelement; e++)
     {
       dynamic_cast<RefineableElement*>(this->element_pt(e))
         ->select_for_refinement();
     }
     // Do the actual mesh adaptation
     adapt_mesh(doc_info);
   }
References adapt_mesh(), oomph::RefineableMeshBase::doc_info(), e(), oomph::Mesh::element_pt(), and oomph::Mesh::nelement().
Referenced by ExtrudedMovingCylinderProblem< TWO_D_ELEMENT, THREE_D_ELEMENT >::create_extruded_mesh(), run_navier_stokes_outflow(), and TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::TurekProblem().
setup_tree_forest()
virtual void oomph::TreeBasedRefineableMeshBase::setup_tree_forest () pure virtual
Set up the tree forest associated with the Mesh (if any)
Implemented in oomph::RefineableQuadMesh< ELEMENT >, oomph::RefineableQuadMesh< NST_ELEMENT >, oomph::RefineableQuadMesh< AD_ELEMENT >, oomph::RefineableLineMesh< ELEMENT >, and oomph::RefineableBrickMesh< ELEMENT >.
split_elements_if_required()
virtual void oomph::TreeBasedRefineableMeshBase::split_elements_if_required () protected pure virtual
Split all the elements in the mesh if required. This template free interface will be overloaded in RefineableMesh<ELEMENT> so that any new elements that are created will be of the correct type.
Implemented in oomph::TreeBasedRefineableMesh< ELEMENT >.
Referenced by adapt_mesh().
uniform_refinement_level_when_pruned() [1/2]
unsigned& oomph::TreeBasedRefineableMeshBase::uniform_refinement_level_when_pruned () inline
Level to which the mesh was uniformly refined when it was pruned.
     {
       return Uniform_refinement_level_when_pruned;
     }
References Uniform_refinement_level_when_pruned.
uniform_refinement_level_when_pruned() [2/2]
unsigned oomph::TreeBasedRefineableMeshBase::uniform_refinement_level_when_pruned () const inline
Level to which the mesh was uniformly refined when it was pruned (const version)
     {
       return Uniform_refinement_level_when_pruned;
     }
References Uniform_refinement_level_when_pruned.
unrefine_uniformly()
unsigned oomph::TreeBasedRefineableMeshBase::unrefine_uniformly () virtual
Unrefine mesh uniformly: Return 0 for success, 1 for failure (if unrefinement has reached the coarsest permitted level)
Unrefine mesh uniformly. Return 0 for success, 1 for failure (if unrefinement has reached the coarsest permitted level)
Implements oomph::RefineableMeshBase.
   {
     // We can't just select all elements for unrefinement
     // because they need to merge with their brothers.
     // --> Rather than repeating the convoluted logic of
     // RefineableQuadMesh<ELEMENT>::adapt(Vector<double>& elemental_error)
     // here (code duplication!) hack it by filling the error
     // vector with values that ensure unrefinement for all
     // elements where this is possible
     // Create dummy vector for elemental errors
     unsigned long Nelement = this->nelement();
     Vector<double> elemental_error(Nelement);
     // In order to force unrefinement, set the min permitted error to
     // be the default and then set the actual error to be below this.
     // This avoids problems when the actual min error is zero (or small)
     // For sanity's sake, also set the max permitted error back to the default
     // so that we have a max error bigger than a min error
     const double current_min_error = this->min_permitted_error();
     const double current_max_error = this->max_permitted_error();
     this->min_permitted_error() = 1.0e-5;
     this->max_permitted_error() = 1.0e-3;
     double error = min_permitted_error() / 100.0;
     for (unsigned long e = 0; e < Nelement; e++)
     {
       elemental_error[e] = error;
     }
     // Temporarily lift any restrictions on the minimum number of
     // elements that need to be unrefined to make it worthwhile
     unsigned backup = max_keep_unrefined();
     max_keep_unrefined() = 0;
     // Do the actual mesh adaptation with fake error vector
     adapt(elemental_error);
     // Reset the minimum number of elements that need to be unrefined
     // to make it worthwhile
     max_keep_unrefined() = backup;
     // Now restore the error tolerances
     this->min_permitted_error() = current_min_error;
     this->max_permitted_error() = current_max_error;
     // Has the unrefinement actually changed anything?
     if (Nelement == this->nelement())
     {
       return 1;
     }
     else
     {
       return 0;
     }
   }
References adapt(), e(), calibrate::error, oomph::RefineableMeshBase::max_keep_unrefined(), oomph::RefineableMeshBase::max_permitted_error(), oomph::RefineableMeshBase::min_permitted_error(), and oomph::Mesh::nelement().
Referenced by refine_base_mesh().
Member Data Documentation
Forest_pt
TreeForest* oomph::TreeBasedRefineableMeshBase::Forest_pt protected
Forest representation of the mesh.
Referenced by adapt_mesh(), oomph::ElasticRefineableQuarterPipeMesh< ELEMENT >::ElasticRefineableQuarterPipeMesh(), forest_pt(), oomph::TreeBasedRefineableMesh< ELEMENT >::p_refine_elements_if_required(), oomph::RefineableEighthSphereMesh< ELEMENT >::RefineableEighthSphereMesh(), oomph::RefineableFullCircleMesh< ELEMENT >::RefineableFullCircleMesh(), oomph::RefineableQuarterPipeMesh< ELEMENT >::RefineableQuarterPipeMesh(), oomph::RefineableQuarterTubeMesh< ELEMENT >::RefineableQuarterTubeMesh(), oomph::RefineableTubeMesh< ELEMENT >::RefineableTubeMesh(), oomph::RefineableLineMesh< ELEMENT >::setup_binary_tree_forest(), oomph::RefineableBrickMesh< ELEMENT >::setup_octree_forest(), oomph::RefineableQuadMesh< ELEMENT >::setup_quadtree_forest(), oomph::TreeBasedRefineableMesh< ELEMENT >::split_elements_if_required(), TreeBasedRefineableMeshBase(), oomph::RefineableQuarterPipeMesh< ELEMENT >::~RefineableQuarterPipeMesh(), and ~TreeBasedRefineableMeshBase().
Max_p_refinement_level
unsigned oomph::TreeBasedRefineableMeshBase::Max_p_refinement_level protected
Max. permissible p-refinement level (relative to base mesh)
Referenced by doc_adaptivity_targets(), max_p_refinement_level(), and TreeBasedRefineableMeshBase().
Max_refinement_level
unsigned oomph::TreeBasedRefineableMeshBase::Max_refinement_level protected
Max. permissible refinement level (relative to base mesh)
Referenced by doc_adaptivity_targets(), max_refinement_level(), and TreeBasedRefineableMeshBase().
Min_p_refinement_level
unsigned oomph::TreeBasedRefineableMeshBase::Min_p_refinement_level protected
Min. permissible p-refinement level (relative to base mesh)
Referenced by doc_adaptivity_targets(), min_p_refinement_level(), and TreeBasedRefineableMeshBase().
Min_refinement_level
unsigned oomph::TreeBasedRefineableMeshBase::Min_refinement_level protected
Min. permissible refinement level (relative to base mesh)
Referenced by doc_adaptivity_targets(), min_refinement_level(), and TreeBasedRefineableMeshBase().
Uniform_refinement_level_when_pruned
unsigned oomph::TreeBasedRefineableMeshBase::Uniform_refinement_level_when_pruned protected
Level to which the mesh was uniformly refined when it was pruned.
Referenced by TreeBasedRefineableMeshBase(), and uniform_refinement_level_when_pruned().
The documentation for this class was generated from the following files:
refineable_mesh.h
refineable_mesh.cc