MercuryDPM: HessenbergDecomposition_matrixH.cpp File Reference
HessenbergDecomposition_matrixH.cpp File Reference
Functions
cout<< "Here is a random 4x4 matrix:"<< endl<< A<< endl;HessenbergDecomposition< MatrixXf > hessOfA (A)
Variables
Matrix4f A = MatrixXf::Random(4, 4)
MatrixXf H = hessOfA.matrixH()
Function Documentation
hessOfA()
cout<< "Here is a random 4x4 matrix:" << endl << A << endl;HessenbergDecomposition<MatrixXf> hessOfA (A)
Variable Documentation
A
Matrix4f A = MatrixXf::Random(4, 4)
H
MatrixXf H = hessOfA.matrixH()
Referenced by AirwayReopeningProblem< ELEMENT >::actions_after_change_in_global_parameter(), ChutePeriodic::add_flow_particles(), SilbertPeriodic::add_flow_particles(), oomph::HomogenisedLinearElasticityEquations< DIM >::calculate_effective_modulus(), WearableNurbsWall::computeWear(), WearableTriangulatedWall::computeWear(), oomph::TriangleMesh< ELEMENT >::convex_hull(), UndeformedWall::d2position(), SinusoidalWall::d2position(), SpikedLine::d2position(), AirwayReopeningProblem< ELEMENT >::dump(), FSIRingProblem::dynamic_run(), Eigen::internal::gmres(), hessenberg(), Flag_definition::lower_tip(), main(), AirwayReopeningProblem< ELEMENT >::parameter_study(), Flag_definition::TopOfFlag::position(), Flag_definition::BottomOfFlag::position(), Flag_definition::TipOfFlag::position(), OscillatingWall::position(), UndeformedWall::position(), SinusoidalWall::position(), SpikedLine::position(), oomph::GMRESBlockPreconditioner::preconditioner_solve(), AirwayReopeningProblem< ELEMENT >::read(), ChutePeriodic::set_H(), Global_Physical_Variables::set_params(), oomph::GMRES< MATRIX >::solve_helper(), oomph::AugmentedProblemGMRES::solve_helper(), oomph::AnnularSpineMesh< ELEMENT >::spine_node_update(), oomph::MyHorizontalSingleLayerSpineMesh< ELEMENT >::spine_node_update(), SpineInclinedPlaneMesh< ELEMENT >::spine_node_update(), MyCanyonMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update(), CombCanSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update(), CombTipSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update(), STSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update(), MyTipMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update(), AxialSpineQuarterTubeMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update(), oomph::HorizontalSingleLayerSpineMesh< ELEMENT >::spine_node_update(), oomph::SingleLayerCubicSpineMesh< ELEMENT >::spine_node_update(), oomph::SingleLayerSpineMesh< ELEMENT >::spine_node_update(), oomph::TwoLayerSpineMesh< ELEMENT >::spine_node_update_lower(), oomph::TwoLayerSpineMesh< ELEMENT >::spine_node_update_upper(), Global_Physical_Variables::spring_load(), Global_Physical_Variables::spring_load_lower(), TwoLayerInterfaceProblem< ELEMENT >::TwoLayerInterfaceProblem(), UndeformedWall::UndeformedWall(), oomph::GMRESBlockPreconditioner::update(), oomph::GMRES< MATRIX >::update(), oomph::AugmentedProblemGMRES::update(), and Flag_definition::upper_tip().