MercuryDPM: Tutorial10MPI_LoadingDataRestart.cpp File Reference
Tutorial10MPI_LoadingDataRestart.cpp File Reference
#include <Mercury3D.h>
#include <Math/Helpers.h>
Classes
class DPM
In this file a cubic packing of 5^3 particles in a tri-axial box is created and allowed to settle under small gravity. After that Z statistics are calculated.
Functions
int main (int argc, char *argv[])
[T10:main]
Function Documentation
main()
int main (int argc , char * argv[])
[T10:main]
 {
     //writeToFile is used here to create a restart and a data file, which will be loaded below.
     helpers::writeToFile("Tutorial10MPI.ini.restart",
         "restart_version 1.0 name Tutorial10MPI\n"
         "dataFile fileType ONE_FILE saveCount 10 counter 0 nextSavedTimeStep 0\n"
         "fStatFile fileType NO_FILE saveCount 10 counter 0 nextSavedTimeStep 0\n"
         "eneFile fileType ONE_FILE saveCount 10 counter 0 nextSavedTimeStep 0\n"
         "restartFile fileType ONE_FILE saveCount 10 counter 0 nextSavedTimeStep 0\n"
         "statFile fileType ONE_FILE saveCount 10 counter 0 nextSavedTimeStep 0\n"
         "xMin 0 xMax 2 yMin 0 yMax 2 zMin 0 zMax 2\n"
         "timeStep 1e-03 time 0 ntimeSteps 0 timeMax 10\n"
         "systemDimensions 3 particleDimensions 3 gravity 0 0 -1\n"
         "Species 1\n"
         "LinearViscoelasticSpecies id 0 density 1.9098593 stiffness 2000 dissipation 1\n"
         "Walls 1\n"
         "InfiniteWall id 0 indSpecies 0 position 0 0 0 orientation 0 0 0 1 velocity 0 0 0 angularVelocity 0 0 0 0 force 0 0 0 torque 0 0 0 normal 0 0 -1 factor 1\n"
         "Boundaries 0\n"
         "Particles 0\n"
         "Interactions 0\n"
     );
     helpers::writeToFile("Tutorial10MPI.ini.data",
         "1 0 0 0 0 2 2 2\n"
         "1 1 1.5  0 0 0  0.5  0 0 0  0 0 0  0\n"
         //"1 1 0.5  0 0 0  0.5  0 0 0  0 0 0  0\n"
     );
     DPM Tutorial10;
     Tutorial10.setNumberOfDomains({1,1,2});
     //use readRestartFile to load information from a restart file
     Tutorial10.readRestartFile("Tutorial10MPI.ini.restart");
     Tutorial10.setRestarted(false);
     //now start the calculations
     Tutorial10.solve();
     return 0;
 }
References DPMBase::readRestartFile(), DPMBase::setNumberOfDomains(), DPMBase::setRestarted(), DPMBase::solve(), and helpers::writeToFile().