MercuryDPM: Eigen::MatrixSquareRootReturnValue< Derived > Class Template Reference
Eigen::MatrixSquareRootReturnValue< Derived > Class Template Reference
Proxy for the matrix square root of some matrix (expression).
#include <MatrixSquareRoot.h>
Public Member Functions
MatrixSquareRootReturnValue (const Derived &src)
Constructor.
template<typename ResultType >
void evalTo (ResultType &result) const
Compute the matrix square root.
Index rows () const
Index cols () const
Public Member Functions inherited from Eigen::ReturnByValue< MatrixSquareRootReturnValue< Derived > >
EIGEN_DEVICE_FUNC void evalTo (Dest &dst) const
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index rows () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index cols () const EIGEN_NOEXCEPT
const Unusable & coeff (Index) const
const Unusable & coeff (Index, Index) const
Unusable & coeffRef (Index)
Unusable & coeffRef (Index, Index)
Protected Types
typedef internal::ref_selector< Derived >::type DerivedNested
Protected Attributes
const DerivedNested m_src
Additional Inherited Members
Public Types inherited from Eigen::ReturnByValue< MatrixSquareRootReturnValue< Derived > >
typedef internal::traits< MatrixSquareRootReturnValue< Derived > >::ReturnType ReturnType
typedef internal::dense_xpr_base< ReturnByValue >::type Base
Detailed Description
template<typename Derived>
class Eigen::MatrixSquareRootReturnValue< Derived >
Proxy for the matrix square root of some matrix (expression).
Template Parameters
Derived Type of the argument to the matrix square root.
This class holds the argument to the matrix square root until it is assigned or evaluated for some other reason (so the argument should not be changed in the meantime). It is the return type of MatrixBase::sqrt() and most of the time this is the only way it is used.
Member Typedef Documentation
DerivedNested
template<typename Derived > typedef internal::ref_selector<Derived>::type Eigen::MatrixSquareRootReturnValue< Derived >::DerivedNested protected
Constructor & Destructor Documentation
MatrixSquareRootReturnValue()
template<typename Derived > Eigen::MatrixSquareRootReturnValue< Derived >::MatrixSquareRootReturnValue (const Derived & src) inline explicit
Constructor.
Parameters
[in] src Matrix (expression) forming the argument of the matrix square root.
 : m_src(src) {}
Member Function Documentation
cols()
template<typename Derived > Index Eigen::MatrixSquareRootReturnValue< Derived >::cols () const inline
 { return m_src.cols(); }
References Eigen::MatrixSquareRootReturnValue< Derived >::m_src.
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
evalTo()
template<typename Derived > template<typename ResultType > void Eigen::MatrixSquareRootReturnValue< Derived >::evalTo (ResultType & result) const inline
Compute the matrix square root.
Parameters
[out] result the matrix square root of src in the constructor.
{
     typedef typename internal::nested_eval<Derived, 10>::type DerivedEvalType;
     typedef internal::remove_all_t<DerivedEvalType> DerivedEvalTypeClean;
     DerivedEvalType tmp(m_src);
     internal::matrix_sqrt_compute<DerivedEvalTypeClean>::run(tmp, result);
   }
References Eigen::MatrixSquareRootReturnValue< Derived >::m_src, Eigen::internal::matrix_sqrt_compute< MatrixType, IsComplex >::run(), and tmp.
rows()
template<typename Derived > Index Eigen::MatrixSquareRootReturnValue< Derived >::rows () const inline
 { return m_src.rows(); }
References Eigen::MatrixSquareRootReturnValue< Derived >::m_src.
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
Member Data Documentation
m_src
template<typename Derived > const DerivedNested Eigen::MatrixSquareRootReturnValue< Derived >::m_src protected
Referenced by Eigen::MatrixSquareRootReturnValue< Derived >::cols(), Eigen::MatrixSquareRootReturnValue< Derived >::evalTo(), and Eigen::MatrixSquareRootReturnValue< Derived >::rows().
The documentation for this class was generated from the following files:
ForwardDeclarations.h
MatrixSquareRoot.h