MercuryDPM: circular_boulder_melt.cc File Reference
circular_boulder_melt.cc File Reference
#include <fenv.h>
#include "generic.h"
#include "unsteady_heat.h"
#include "solid.h"
#include "contact_elements.h"
#include "heat_transfer_and_melt_elements.h"
#include "meshes/triangle_mesh.h"
Classes
class MeltContactProblem< ELEMENT >
Problem class.
Namespaces
ProblemParameters
Namespace for exact solution and problem parameters.
ExactSolution
Namespace for exact solution.
Macros
#define ADAPTIVE
Functions
void ExactSolution::get_exact_u_for_unsteady_heat_validation (const double &t, const Vector< double > &x, Vector< double > &u)
Exact solution as a Vector.
void ExactSolution::get_exact_u_for_unsteady_heat_validation (const double &t, const Vector< double > &x, double &u)
Exact solution as a scalar.
void ExactSolution::get_source_for_unsteady_heat_validation (const double &t, const Vector< double > &x, double &source)
Source function to make it an exact solution.
double ExactSolution::melting_surface_height (const double &t, const double &x)
Height of melting surface.
void ExactSolution::analytical_outer_unit_normal (const double &t, const Vector< double > &x, double &nx, double &ny)
Analytical outer unit normal.
void ExactSolution::flux_into_bulk (const double &t, const Vector< double > &x, const Vector< double > &n, const double &u, double &flux)
void ExactSolution::prescribed_flux_for_unsteady_heat_validation (const double &t, const Vector< double > &x, const Vector< double > &n, const double &u, double &flux)
int main (int argc, char *argv[])
Driver code.
Variables
double ProblemParameters::Melt_temperature =0.0
Melt-temperature.
ConstitutiveLaw * ProblemParameters::Constitutive_law_pt =0
Pointer to constitutive law.
double ProblemParameters::Radius =0.2
Radius of penetrator.
double ProblemParameters::Y_c_initial =1.05
Initial y position of centre of penetrator.
Vector< double > ProblemParameters::Centre
Position of centre of penetrator.
Penetrator * ProblemParameters::Penetrator_pt =0
Penetrator.
double ExactSolution::U0 =0.0
Constant/initial temperature.
double ExactSolution::Growth_rate =1.0
Growth rate for interface.
bool ExactSolution::Use_analytical_outer_unit_normal =true
Use analytical outer unit normal when computing fluxes?
double ExactSolution::Omega_cos =0.0
Macro Definition Documentation
ADAPTIVE
#define ADAPTIVE
Function Documentation
main()
int main (int argc , char * argv[])
Driver code.
///////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////
 {
  Global_unsigned::Number=0;
  // hierher
 // FiniteElement::Accept_negative_jacobian=true;
 // FiniteElement::Tolerance_for_singular_jacobian=0.0;
  // Store command line arguments
  CommandLineArgs::setup(argc,argv);
  // Define possible command line arguments and parse the ones that
  // were actually specified
  // Suppress adaptation
  CommandLineArgs::specify_command_line_flag("--no_adapt");
  // Parse command line
  CommandLineArgs::parse_and_assign();
  // Doc what has actually been specified on the command line
  CommandLineArgs::doc_specified_flags();
  // Create generalised Hookean constitutive equations
  ProblemParameters::Constitutive_law_pt =
   new GeneralisedHookean(&ProblemParameters::Nu);
  // Define centre of penetrator
  ProblemParameters::Centre.resize(2);
  ProblemParameters::Centre[0]=0.5;
  ProblemParameters::Centre[1]=ProblemParameters::Y_c_initial;
  // Create penetrator
  ProblemParameters::Penetrator_pt =
   new CircularPenetrator(&ProblemParameters::Centre,
                          ProblemParameters::Radius);
 #ifdef ADAPTIVE
  // Build problem
  MeltContactProblem<ProjectableUnsteadyHeatElement<
   PseudoSolidNodeUpdateElement<TUnsteadyHeatElement<2,3>,TPVDElement<2,3> > > >
                     problem;
   //ProjectablePVDElement<TPVDElement<2,3> > > problem;
 #else
  // Build problem
  MeltContactProblem<TPVDElement<2,3> > problem;
 #endif
   //Output initial condition
  problem.doc_solution();
  unsigned max_adapt=1;
  if (CommandLineArgs::command_line_flag_has_been_set("--no_adapt"))
   {
    max_adapt=0;
   }
  // // Set number of steps
  // unsigned nstep = 100;
  // if (CommandLineArgs::command_line_flag_has_been_set("--validate"))
  //  {
  //   nstep=5;
  //  }
  // Number of parameter increments per period
  unsigned nstep_for_period=100;
  // Parameter variation
  unsigned nperiod=3;
  // Initial timestep
  double dt=1.0/double(nstep_for_period);
  // Initialise timestep -- also sets the weights for all timesteppers
  // in the problem.
  problem.initialise_dt(dt);
  // Set impulsive IC
  problem.assign_initial_values_impulsive(dt);
  while (problem.time_pt()->time()<double(nperiod))
   {
 #ifdef ADAPTIVE
    // Dummy double adaptivity (timestep is always accepted because
    // tolerance is set to huge value; mainly used to automatically
    // re-solve with smaller timestep increment after non-convergence
    double epsilon_t=DBL_MAX;
    bool first=false;
    unsigned suppress_resolve_after_spatial_adapt_flag=0;
    double next_dt=
     problem.doubly_adaptive_unsteady_newton_solve(
      dt,
      epsilon_t,
      max_adapt,
      suppress_resolve_after_spatial_adapt_flag,
      first);
    dt = next_dt;
 #else
    // hierher
    abort();
    // Solve
    problem.newton_solve();
 #endif
    //Output solution
    problem.doc_solution();
   }
 } // end of main
References ProblemParameters::Centre, oomph::CommandLineArgs::command_line_flag_has_been_set(), ProblemParameters::Constitutive_law_pt, oomph::CommandLineArgs::doc_specified_flags(), ProblemParameters::Nu, oomph::Global_unsigned::Number, oomph::CommandLineArgs::parse_and_assign(), ProblemParameters::Penetrator_pt, problem, ProblemParameters::Radius, Flag_definition::setup(), oomph::CommandLineArgs::specify_command_line_flag(), and ProblemParameters::Y_c_initial.