MercuryDPM: cxx11_tensor_io.cpp File Reference
cxx11_tensor_io.cpp File Reference
#include "main.h"
#include <sstream>
#include <Eigen/CXX11/Tensor>
Classes
struct test_tensor_ostream_impl< Scalar, rank, Layout >
struct test_tensor_ostream_impl< Scalar, 0, Layout >
struct test_tensor_ostream_impl< Scalar, 1, Layout >
struct test_tensor_ostream_impl< Scalar, 2, Layout >
struct test_tensor_ostream_impl< Scalar, 3, Layout >
struct test_tensor_ostream_impl< bool, 2, Layout >
struct test_tensor_ostream_impl< std::complex< Scalar >, 2, Layout >
Functions
template<typename Scalar , int rank, int Layout>
void test_tensor_ostream ()
void test_const_tensor_ostream ()
EIGEN_DECLARE_TEST (cxx11_tensor_io)
Function Documentation
EIGEN_DECLARE_TEST()
EIGEN_DECLARE_TEST (cxx11_tensor_io)
{
   CALL_SUBTEST((test_tensor_ostream<float, 0, Eigen::ColMajor>()));
   CALL_SUBTEST((test_tensor_ostream<float, 1, Eigen::ColMajor>()));
   CALL_SUBTEST((test_tensor_ostream<float, 2, Eigen::ColMajor>()));
   CALL_SUBTEST((test_tensor_ostream<float, 3, Eigen::ColMajor>()));
   CALL_SUBTEST((test_tensor_ostream<double, 0, Eigen::ColMajor>()));
   CALL_SUBTEST((test_tensor_ostream<double, 1, Eigen::ColMajor>()));
   CALL_SUBTEST((test_tensor_ostream<double, 2, Eigen::ColMajor>()));
   CALL_SUBTEST((test_tensor_ostream<double, 3, Eigen::ColMajor>()));
   CALL_SUBTEST((test_tensor_ostream<int, 0, Eigen::ColMajor>()));
   CALL_SUBTEST((test_tensor_ostream<int, 1, Eigen::ColMajor>()));
   CALL_SUBTEST((test_tensor_ostream<int, 2, Eigen::ColMajor>()));
   CALL_SUBTEST((test_tensor_ostream<int, 3, Eigen::ColMajor>()));
   CALL_SUBTEST((test_tensor_ostream<float, 0, Eigen::RowMajor>()));
   CALL_SUBTEST((test_tensor_ostream<float, 1, Eigen::RowMajor>()));
   CALL_SUBTEST((test_tensor_ostream<float, 2, Eigen::RowMajor>()));
   CALL_SUBTEST((test_tensor_ostream<float, 3, Eigen::RowMajor>()));
   CALL_SUBTEST((test_tensor_ostream<double, 0, Eigen::RowMajor>()));
   CALL_SUBTEST((test_tensor_ostream<double, 1, Eigen::RowMajor>()));
   CALL_SUBTEST((test_tensor_ostream<double, 2, Eigen::RowMajor>()));
   CALL_SUBTEST((test_tensor_ostream<double, 3, Eigen::RowMajor>()));
   CALL_SUBTEST((test_tensor_ostream<int, 0, Eigen::RowMajor>()));
   CALL_SUBTEST((test_tensor_ostream<int, 1, Eigen::RowMajor>()));
   CALL_SUBTEST((test_tensor_ostream<int, 2, Eigen::RowMajor>()));
   CALL_SUBTEST((test_tensor_ostream<int, 3, Eigen::RowMajor>()));
   CALL_SUBTEST((test_tensor_ostream<bool, 2, Eigen::ColMajor>()));
   CALL_SUBTEST((test_tensor_ostream<bool, 2, Eigen::RowMajor>()));
   CALL_SUBTEST((test_tensor_ostream<std::complex<double>, 2, Eigen::ColMajor>()));
   CALL_SUBTEST((test_tensor_ostream<std::complex<float>, 2, Eigen::ColMajor>()));
   // Test printing TensorMap with const elements.
   CALL_SUBTEST((test_const_tensor_ostream()));
 }
References CALL_SUBTEST, Eigen::ColMajor, test_const_tensor_ostream(), and test_tensor_ostream().
test_const_tensor_ostream()
void test_const_tensor_ostream ()
{
   Eigen::Tensor<float, 0> t;
   t.setValues(1);
   const Eigen::TensorMap<Eigen::Tensor<const float, 0, Eigen::RowMajor>, Eigen::Unaligned> t_const(
       t.data(), Eigen::DSizes<Eigen::DenseIndex, 0>{});
   std::ostringstream os;
   os << t_const.format(Eigen::TensorIOFormat::Plain());
   VERIFY(os.str() == "1");
 }
References Eigen::TensorIOFormat::Plain(), plotPSD::t, Eigen::Unaligned, and VERIFY.
Referenced by EIGEN_DECLARE_TEST().
test_tensor_ostream()
template<typename Scalar , int rank, int Layout> void test_tensor_ostream ()
{
   test_tensor_ostream_impl<Scalar, rank, Layout>::run();
 }
References run().
Referenced by EIGEN_DECLARE_TEST().