MercuryDPM: Eigen::internal::std_fallback Namespace Reference
Eigen::internal::std_fallback Namespace Reference
Functions
template<typename Scalar >
EIGEN_DEVICE_FUNC Scalar expm1 (const Scalar &x)
template<typename Scalar >
EIGEN_DEVICE_FUNC Scalar log1p (const Scalar &x)
Function Documentation
expm1()
template<typename Scalar > EIGEN_DEVICE_FUNC Scalar Eigen::internal::std_fallback::expm1 (const Scalar & x) inline
{
   EIGEN_STATIC_ASSERT_NON_INTEGER(Scalar)
   typedef typename NumTraits<Scalar>::Real RealScalar;
   EIGEN_USING_STD(exp);
   Scalar u = exp(x);
   if (numext::equal_strict(u, Scalar(1))) {
     return x;
   }
   Scalar um1 = u - RealScalar(1);
   if (numext::equal_strict(um1, Scalar(-1))) {
     return RealScalar(-1);
   }
   EIGEN_USING_STD(log);
   Scalar logu = log(u);
   return numext::equal_strict(u, logu) ? u : (u - RealScalar(1)) * x / logu;
 }
References EIGEN_STATIC_ASSERT_NON_INTEGER, EIGEN_USING_STD, Eigen::numext::equal_strict(), Eigen::numext::exp(), Eigen::numext::log(), and plotDoE::x.
Referenced by Eigen::numext::EIGEN_MATHFUNC_RETVAL(), and Eigen::internal::expm1_impl< Scalar >::run().
log1p()
template<typename Scalar > EIGEN_DEVICE_FUNC Scalar Eigen::internal::std_fallback::log1p (const Scalar & x) inline
{
   EIGEN_STATIC_ASSERT_NON_INTEGER(Scalar)
   typedef typename NumTraits<Scalar>::Real RealScalar;
   EIGEN_USING_STD(log);
   Scalar x1p = RealScalar(1) + x;
   Scalar log_1p = log_impl<Scalar>::run(x1p);
   const bool is_small = numext::equal_strict(x1p, Scalar(1));
   const bool is_inf = numext::equal_strict(x1p, log_1p);
   return (is_small || is_inf) ? x : x * (log_1p / (x1p - RealScalar(1)));
 }
References EIGEN_STATIC_ASSERT_NON_INTEGER, EIGEN_USING_STD, Eigen::numext::equal_strict(), Eigen::numext::log(), Eigen::internal::log_impl< Scalar >::run(), and plotDoE::x.
Referenced by Eigen::internal::log1p_impl< Scalar >::run(), and Eigen::internal::log1p_impl< std::complex< RealScalar > >::run().