MercuryDPM: ConvectionProblem< NST_ELEMENT, AD_ELEMENT > Class Template Reference
ConvectionProblem< NST_ELEMENT, AD_ELEMENT > Class Template Reference
Public Member Functions
ConvectionProblem ()
Constructor.
~ConvectionProblem ()
Destructor. Empty.
void actions_before_newton_solve ()
Update the problem specs before solve (empty)
void actions_after_newton_solve ()
Update the problem after solve (empty)
void actions_before_adapt ()
Actions before adapt:(empty)
void actions_after_distribute ()
Actions after distribute: re-setup multi-domain interaction.
void actions_before_implicit_timestep ()
void fix_pressure (const unsigned &e, const unsigned &pdof, const double &pvalue)
Fix pressure in element e at pressure dof pdof and set to pvalue.
void doc_solution ()
Doc the solution.
void set_boundary_conditions (const double &time)
Set the boundary conditions.
RectangularQuadMesh< NST_ELEMENT > * nst_mesh_pt ()
Access function to the Navier-Stokes mesh.
RectangularQuadMesh< AD_ELEMENT > * adv_diff_mesh_pt ()
Access function to the Advection-Diffusion mesh.
ConvectionProblem ()
Constructor.
~ConvectionProblem ()
Destructor. Empty.
void actions_before_newton_solve ()
Update the problem specs before solve (empty)
void actions_after_newton_solve ()
Update the problem after solve (empty)
void actions_before_adapt ()
Actions before adapt:(empty)
void actions_before_implicit_timestep ()
void fix_pressure (const unsigned &e, const unsigned &pdof, const double &pvalue)
Fix pressure in element e at pressure dof pdof and set to pvalue.
void doc_solution ()
Doc the solution.
void set_boundary_conditions (const double &time)
Set the boundary conditions.
RectangularQuadMesh< ELEMENT > * mesh_pt ()
ConvectionProblem ()
Constructor.
~ConvectionProblem ()
Destructor. Empty.
void actions_before_newton_solve ()
Update the problem specs before solve (empty)
void actions_after_newton_solve ()
Update the problem after solve (empty)
void actions_before_adapt ()
Actions before adapt:(empty)
void actions_before_implicit_timestep ()
void fix_pressure (const unsigned &e, const unsigned &pdof, const double &pvalue)
Fix pressure in element e at pressure dof pdof and set to pvalue.
void doc_solution ()
Doc the solution.
void set_boundary_conditions (const double &time)
Set the boundary conditions.
RectangularQuadMesh< NST_ELEMENT > * nst_mesh_pt ()
Access function to the Navier-Stokes mesh.
RectangularQuadMesh< AD_ELEMENT > * adv_diff_mesh_pt ()
Access function to the Advection-Diffusion mesh.
ConvectionProblem ()
Constructor.
~ConvectionProblem ()
Destructor. Empty.
void actions_before_newton_solve ()
Update the problem specs before solve (empty)
void actions_after_newton_solve ()
Update the problem after solve (empty)
void actions_before_adapt ()
Actions before adapt:(empty)
void actions_before_implicit_timestep ()
void fix_pressure (const unsigned &e, const unsigned &pdof, const double &pvalue)
Fix pressure in element e at pressure dof pdof and set to pvalue.
void doc_solution ()
Doc the solution.
void set_boundary_conditions (const double &time)
Set the boundary conditions.
RectangularQuadMesh< ELEMENT > * mesh_pt ()
void get_kinetic_energy (double &E, double &Edot)
Get kinetic energy and kinetic energy flux.
ConvectionProblem (const bool &pin=true)
Constructor. The boolean indicates whether the free surface.
~ConvectionProblem ()
Destructor. Empty.
void unpin_surface ()
Release the free surface so that it can move.
void actions_before_newton_solve ()
Update the problem specs before solve (empty)
void actions_after_newton_solve ()
Update the problem after solve (empty)
void actions_before_newton_convergence_check ()
Remember to update the nodes if the surface is not pinned.
void actions_before_implicit_timestep ()
void fix_pressure (const unsigned &e, const unsigned &pdof, const double &pvalue)
Fix pressure in element e at pressure dof pdof and set to pvalue.
void unfix_pressure (const unsigned &e, const unsigned &pdof)
UnFix pressure in element e at pressure dof pdof and set to pvalue.
void doc_solution (std::ofstream &trace)
Doc the solution.
void set_boundary_conditions (const double &time)
Set the boundary conditions.
ConvectionProblem (const bool &pin=true)
Constructor. The boolean indicates whether the free surface.
~ConvectionProblem ()
Destructor. Empty.
void unpin_surface ()
Release the free surface so that it can move.
void actions_before_newton_solve ()
Update the problem specs before solve (empty)
void actions_after_newton_solve ()
Update the problem after solve (empty)
void actions_before_newton_convergence_check ()
Remember to update the nodes if the surface is not pinned.
void actions_before_implicit_timestep ()
void fix_pressure (const unsigned &e, const unsigned &pdof, const double &pvalue)
Fix pressure in element e at pressure dof pdof and set to pvalue.
void unfix_pressure (const unsigned &e, const unsigned &pdof)
UnFix pressure in element e at pressure dof pdof and set to pvalue.
void doc_solution ()
Doc the solution.
void set_boundary_conditions (const double &time)
Set the boundary conditions.
ConvectionProblem ()
Constructor.
~ConvectionProblem ()
Destructor. Empty.
void switch_boundary_conditions ()
Unpin things for timestepping.
void actions_before_newton_solve ()
Update the problem specs before solve (empty)
void actions_after_newton_solve ()
Update the problem after solve (empty)
void actions_before_newton_convergence_check ()
Remember to update the nodes!
void actions_before_adapt ()
Actions before adapt:(empty)
void actions_before_implicit_timestep ()
void fix_pressure (const unsigned &e, const unsigned &pdof, const double &pvalue)
Fix pressure in element e at pressure dof pdof and set to pvalue.
void unfix_pressure (const unsigned &e, const unsigned &pdof)
UnFix pressure in element e at pressure dof pdof and set to pvalue.
void doc_solution ()
Doc the solution.
void set_boundary_conditions (const double &time)
Set the boundary conditions.
ConvectionProblem (const bool &pin=true)
Constructor. The boolean indicates whether the free surface.
~ConvectionProblem ()
Destructor. Empty.
void unpin_surface ()
Release the free surface so that it can move.
void actions_before_newton_solve ()
Update the problem specs before solve (empty)
void actions_after_newton_solve ()
Update the problem after solve (empty)
void actions_before_newton_convergence_check ()
Remember to update the nodes if the surface is not pinned.
void actions_before_implicit_timestep ()
void fix_pressure (const unsigned &e, const unsigned &pdof, const double &pvalue)
Fix pressure in element e at pressure dof pdof and set to pvalue.
void unfix_pressure (const unsigned &e, const unsigned &pdof)
UnFix pressure in element e at pressure dof pdof and set to pvalue.
void doc_solution (std::ofstream &trace)
Doc the solution.
void set_boundary_conditions (const double &time)
Set the boundary conditions.
Public Member Functions inherited from oomph::Problem
virtual void debug_hook_fct (const unsigned &i)
void set_analytic_dparameter (double *const &parameter_pt)
void unset_analytic_dparameter (double *const &parameter_pt)
bool is_dparameter_calculated_analytically (double *const &parameter_pt)
void set_analytic_hessian_products ()
void unset_analytic_hessian_products ()
bool are_hessian_products_calculated_analytically ()
void set_pinned_values_to_zero ()
bool distributed () const
virtual void actions_after_adapt ()
Actions that are to be performed after a mesh adaptation.
OomphCommunicator * communicator_pt ()
access function to the oomph-lib communicator
const OomphCommunicator * communicator_pt () const
access function to the oomph-lib communicator, const version
Problem ()
Problem (const Problem &dummy)=delete
Broken copy constructor.
void operator= (const Problem &)=delete
Broken assignment operator.
virtual ~Problem ()
Virtual destructor to clean up memory.
Mesh *& mesh_pt ()
Return a pointer to the global mesh.
Mesh *const & mesh_pt () const
Return a pointer to the global mesh (const version)
Mesh *& mesh_pt (const unsigned &imesh)
Mesh *const & mesh_pt (const unsigned &imesh) const
Return a pointer to the i-th submesh (const version)
unsigned nsub_mesh () const
Return number of submeshes.
unsigned add_sub_mesh (Mesh *const &mesh_pt)
void flush_sub_meshes ()
void build_global_mesh ()
void rebuild_global_mesh ()
LinearSolver *& linear_solver_pt ()
Return a pointer to the linear solver object.
LinearSolver *const & linear_solver_pt () const
Return a pointer to the linear solver object (const version)
LinearSolver *& mass_matrix_solver_for_explicit_timestepper_pt ()
LinearSolver * mass_matrix_solver_for_explicit_timestepper_pt () const
EigenSolver *& eigen_solver_pt ()
Return a pointer to the eigen solver object.
EigenSolver *const & eigen_solver_pt () const
Return a pointer to the eigen solver object (const version)
Time *& time_pt ()
Return a pointer to the global time object.
Time * time_pt () const
Return a pointer to the global time object (const version).
double & time ()
Return the current value of continuous time.
double time () const
Return the current value of continuous time (const version)
TimeStepper *& time_stepper_pt ()
const TimeStepper * time_stepper_pt () const
TimeStepper *& time_stepper_pt (const unsigned &i)
Return a pointer to the i-th timestepper.
ExplicitTimeStepper *& explicit_time_stepper_pt ()
Return a pointer to the explicit timestepper.
unsigned long set_timestepper_for_all_data (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data=false)
virtual void shift_time_values ()
Shift all values along to prepare for next timestep.
AssemblyHandler *& assembly_handler_pt ()
Return a pointer to the assembly handler object.
AssemblyHandler *const & assembly_handler_pt () const
Return a pointer to the assembly handler object (const version)
double & minimum_dt ()
Access function to min timestep in adaptive timestepping.
double & maximum_dt ()
Access function to max timestep in adaptive timestepping.
unsigned & max_newton_iterations ()
Access function to max Newton iterations before giving up.
void problem_is_nonlinear (const bool &prob_lin)
Access function to Problem_is_nonlinear.
double & max_residuals ()
bool & time_adaptive_newton_crash_on_solve_fail ()
Access function for Time_adaptive_newton_crash_on_solve_fail.
double & newton_solver_tolerance ()
void add_time_stepper_pt (TimeStepper *const &time_stepper_pt)
void set_explicit_time_stepper_pt (ExplicitTimeStepper *const &explicit_time_stepper_pt)
void initialise_dt (const double &dt)
void initialise_dt (const Vector< double > &dt)
Data *& global_data_pt (const unsigned &i)
Return a pointer to the the i-th global data object.
void add_global_data (Data *const &global_data_pt)
void flush_global_data ()
LinearAlgebraDistribution *const & dof_distribution_pt () const
Return the pointer to the dof distribution (read-only)
unsigned long ndof () const
Return the number of dofs.
unsigned ntime_stepper () const
Return the number of time steppers.
unsigned nglobal_data () const
Return the number of global data values.
unsigned self_test ()
Self-test: Check meshes and global data. Return 0 for OK.
void enable_store_local_dof_pt_in_elements ()
void disable_store_local_dof_pt_in_elements ()
unsigned long assign_eqn_numbers (const bool &assign_local_eqn_numbers=true)
void describe_dofs (std::ostream &out= *(oomph_info.stream_pt())) const
void enable_discontinuous_formulation ()
void disable_discontinuous_formulation ()
void get_dofs (DoubleVector &dofs) const
void get_dofs (const unsigned &t, DoubleVector &dofs) const
Return vector of the t'th history value of all dofs.
void set_dofs (const DoubleVector &dofs)
Set the values of the dofs.
void set_dofs (const unsigned &t, DoubleVector &dofs)
Set the history values of the dofs.
void set_dofs (const unsigned &t, Vector< double * > &dof_pt)
void add_to_dofs (const double &lambda, const DoubleVector &increment_dofs)
Add lambda x incremenet_dofs[l] to the l-th dof.
double * global_dof_pt (const unsigned &i)
double & dof (const unsigned &i)
i-th dof in the problem
double dof (const unsigned &i) const
i-th dof in the problem (const version)
double *& dof_pt (const unsigned &i)
Pointer to i-th dof in the problem.
double * dof_pt (const unsigned &i) const
Pointer to i-th dof in the problem (const version)
virtual void get_inverse_mass_matrix_times_residuals (DoubleVector &Mres)
virtual void get_dvaluesdt (DoubleVector &f)
virtual void get_residuals (DoubleVector &residuals)
Get the total residuals Vector for the problem.
virtual void get_jacobian (DoubleVector &residuals, DenseDoubleMatrix &jacobian)
virtual void get_jacobian (DoubleVector &residuals, CRDoubleMatrix &jacobian)
virtual void get_jacobian (DoubleVector &residuals, CCDoubleMatrix &jacobian)
virtual void get_jacobian (DoubleVector &residuals, SumOfMatrices &jacobian)
void get_fd_jacobian (DoubleVector &residuals, DenseMatrix< double > &jacobian)
Get the full Jacobian by finite differencing.
void get_derivative_wrt_global_parameter (double *const &parameter_pt, DoubleVector &result)
void get_hessian_vector_products (DoubleVectorWithHaloEntries const &Y, Vector< DoubleVectorWithHaloEntries > const &C, Vector< DoubleVectorWithHaloEntries > &product)
void solve_eigenproblem (const unsigned &n_eval, Vector< std::complex< double >> &eigenvalue, Vector< DoubleVector > &eigenvector, const bool &steady=true)
Solve the eigenproblem.
void solve_eigenproblem (const unsigned &n_eval, Vector< std::complex< double >> &eigenvalue, const bool &steady=true)
virtual void get_eigenproblem_matrices (CRDoubleMatrix &mass_matrix, CRDoubleMatrix &main_matrix, const double &shift=0.0)
void assign_eigenvector_to_dofs (DoubleVector &eigenvector)
Assign the eigenvector passed to the function to the dofs.
void add_eigenvector_to_dofs (const double &epsilon, const DoubleVector &eigenvector)
void store_current_dof_values ()
Store the current values of the degrees of freedom.
void restore_dof_values ()
Restore the stored values of the degrees of freedom.
void enable_jacobian_reuse ()
void disable_jacobian_reuse ()
Disable recycling of Jacobian in Newton iteration.
bool jacobian_reuse_is_enabled ()
Is recycling of Jacobian in Newton iteration enabled?
bool & use_predictor_values_as_initial_guess ()
void newton_solve ()
Use Newton method to solve the problem.
void enable_globally_convergent_newton_method ()
enable globally convergent Newton method
void disable_globally_convergent_newton_method ()
disable globally convergent Newton method
void newton_solve (unsigned const &max_adapt)
void steady_newton_solve (unsigned const &max_adapt=0)
void copy (Problem *orig_problem_pt)
virtual Problem * make_copy ()
virtual void read (std::ifstream &restart_file, bool &unsteady_restart)
virtual void read (std::ifstream &restart_file)
virtual void dump (std::ofstream &dump_file) const
void dump (const std::string &dump_file_name) const
void delete_all_external_storage ()
virtual void symmetrise_eigenfunction_for_adaptive_pitchfork_tracking ()
double * bifurcation_parameter_pt () const
void get_bifurcation_eigenfunction (Vector< DoubleVector > &eigenfunction)
void activate_fold_tracking (double *const &parameter_pt, const bool &block_solve=true)
void activate_bifurcation_tracking (double *const &parameter_pt, const DoubleVector &eigenvector, const bool &block_solve=true)
void activate_bifurcation_tracking (double *const &parameter_pt, const DoubleVector &eigenvector, const DoubleVector &normalisation, const bool &block_solve=true)
void activate_pitchfork_tracking (double *const &parameter_pt, const DoubleVector &symmetry_vector, const bool &block_solve=true)
void activate_hopf_tracking (double *const &parameter_pt, const bool &block_solve=true)
void activate_hopf_tracking (double *const &parameter_pt, const double &omega, const DoubleVector &null_real, const DoubleVector &null_imag, const bool &block_solve=true)
void deactivate_bifurcation_tracking ()
void reset_assembly_handler_to_default ()
Reset the system to the standard non-augemented state.
double arc_length_step_solve (double *const &parameter_pt, const double &ds, const unsigned &max_adapt=0)
double arc_length_step_solve (Data *const &data_pt, const unsigned &data_index, const double &ds, const unsigned &max_adapt=0)
void reset_arc_length_parameters ()
int & sign_of_jacobian ()
void explicit_timestep (const double &dt, const bool &shift_values=true)
Take an explicit timestep of size dt.
void unsteady_newton_solve (const double &dt)
void unsteady_newton_solve (const double &dt, const bool &shift_values)
void unsteady_newton_solve (const double &dt, const unsigned &max_adapt, const bool &first, const bool &shift=true)
double doubly_adaptive_unsteady_newton_solve (const double &dt, const double &epsilon, const unsigned &max_adapt, const bool &first, const bool &shift=true)
double doubly_adaptive_unsteady_newton_solve (const double &dt, const double &epsilon, const unsigned &max_adapt, const unsigned &suppress_resolve_after_spatial_adapt_flag, const bool &first, const bool &shift=true)
double adaptive_unsteady_newton_solve (const double &dt_desired, const double &epsilon)
double adaptive_unsteady_newton_solve (const double &dt_desired, const double &epsilon, const bool &shift_values)
void assign_initial_values_impulsive ()
void assign_initial_values_impulsive (const double &dt)
void calculate_predictions ()
Calculate predictions.
void enable_mass_matrix_reuse ()
void disable_mass_matrix_reuse ()
bool mass_matrix_reuse_is_enabled ()
Return whether the mass matrix is being reused.
void refine_uniformly (const Vector< unsigned > &nrefine_for_mesh)
void refine_uniformly (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh)
void refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void refine_uniformly (DocInfo &doc_info)
void refine_uniformly_and_prune (DocInfo &doc_info)
void refine_uniformly ()
void refine_uniformly (const unsigned &i_mesh, DocInfo &doc_info)
Do uniform refinement for submesh i_mesh with documentation.
void refine_uniformly (const unsigned &i_mesh)
Do uniform refinement for submesh i_mesh without documentation.
void p_refine_uniformly (const Vector< unsigned > &nrefine_for_mesh)
void p_refine_uniformly (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void p_refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh)
void p_refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void p_refine_uniformly (DocInfo &doc_info)
void p_refine_uniformly_and_prune (DocInfo &doc_info)
void p_refine_uniformly ()
void p_refine_uniformly (const unsigned &i_mesh, DocInfo &doc_info)
Do uniform p-refinement for submesh i_mesh with documentation.
void p_refine_uniformly (const unsigned &i_mesh)
Do uniform p-refinement for submesh i_mesh without documentation.
void refine_selected_elements (const Vector< unsigned > &elements_to_be_refined)
void refine_selected_elements (const Vector< RefineableElement * > &elements_to_be_refined_pt)
void refine_selected_elements (const unsigned &i_mesh, const Vector< unsigned > &elements_to_be_refined)
void refine_selected_elements (const unsigned &i_mesh, const Vector< RefineableElement * > &elements_to_be_refined_pt)
void refine_selected_elements (const Vector< Vector< unsigned >> &elements_to_be_refined)
void refine_selected_elements (const Vector< Vector< RefineableElement * >> &elements_to_be_refined_pt)
void p_refine_selected_elements (const Vector< unsigned > &elements_to_be_refined)
void p_refine_selected_elements (const Vector< PRefineableElement * > &elements_to_be_refined_pt)
void p_refine_selected_elements (const unsigned &i_mesh, const Vector< unsigned > &elements_to_be_refined)
void p_refine_selected_elements (const unsigned &i_mesh, const Vector< PRefineableElement * > &elements_to_be_refined_pt)
void p_refine_selected_elements (const Vector< Vector< unsigned >> &elements_to_be_refined)
void p_refine_selected_elements (const Vector< Vector< PRefineableElement * >> &elements_to_be_refined_pt)
unsigned unrefine_uniformly ()
unsigned unrefine_uniformly (const unsigned &i_mesh)
void p_unrefine_uniformly (DocInfo &doc_info)
void p_unrefine_uniformly (const unsigned &i_mesh, DocInfo &doc_info)
Do uniform p-unrefinement for submesh i_mesh without documentation.
void adapt (unsigned &n_refined, unsigned &n_unrefined)
void adapt ()
void p_adapt (unsigned &n_refined, unsigned &n_unrefined)
void p_adapt ()
void adapt_based_on_error_estimates (unsigned &n_refined, unsigned &n_unrefined, Vector< Vector< double >> &elemental_error)
void adapt_based_on_error_estimates (Vector< Vector< double >> &elemental_error)
void get_all_error_estimates (Vector< Vector< double >> &elemental_error)
void doc_errors (DocInfo &doc_info)
Get max and min error for all elements in submeshes.
void doc_errors ()
Get max and min error for all elements in submeshes.
void enable_info_in_newton_solve ()
void disable_info_in_newton_solve ()
Disable the output of information when in the newton solver.
Public Member Functions inherited from oomph::ExplicitTimeSteppableObject
ExplicitTimeSteppableObject ()
Empty constructor.
ExplicitTimeSteppableObject (const ExplicitTimeSteppableObject &)=delete
Broken copy constructor.
void operator= (const ExplicitTimeSteppableObject &)=delete
Broken assignment operator.
virtual ~ExplicitTimeSteppableObject ()
Empty destructor.
virtual void actions_before_explicit_stage ()
virtual void actions_after_explicit_stage ()
Public Attributes
SingleLayerSpineMesh< ELEMENT > * Bulk_mesh_pt
Mesh for the bulk fluid elements.
Mesh * Surface_mesh_pt
The mesh for the interface elements.
Mesh * Point_mesh_pt
The mesh for the element at the contact points.
Public Attributes inherited from oomph::Problem
bool Shut_up_in_newton_solve
Protected Attributes
RectangularQuadMesh< NST_ELEMENT > * Nst_mesh_pt
Mesh of Navier Stokes elements.
RectangularQuadMesh< AD_ELEMENT > * Adv_diff_mesh_pt
Mesh of advection diffusion elements.
Protected Attributes inherited from oomph::Problem
Vector< Problem * > Copy_of_problem_pt
std::map< double *, bool > Calculate_dparameter_analytic
bool Calculate_hessian_products_analytic
LinearAlgebraDistribution * Dof_distribution_pt
Vector< double * > Dof_pt
Vector of pointers to dofs.
DoubleVectorWithHaloEntries Element_count_per_dof
double Relaxation_factor
double Newton_solver_tolerance
unsigned Max_newton_iterations
Maximum number of Newton iterations.
unsigned Nnewton_iter_taken
Vector< double > Max_res
Maximum residuals at start and after each newton iteration.
double Max_residuals
bool Time_adaptive_newton_crash_on_solve_fail
bool Jacobian_reuse_is_enabled
Is re-use of Jacobian in Newton iteration enabled? Default: false.
bool Jacobian_has_been_computed
bool Problem_is_nonlinear
bool Pause_at_end_of_sparse_assembly
bool Doc_time_in_distribute
unsigned Sparse_assembly_method
unsigned Sparse_assemble_with_arrays_initial_allocation
unsigned Sparse_assemble_with_arrays_allocation_increment
Vector< Vector< unsigned > > Sparse_assemble_with_arrays_previous_allocation
double Numerical_zero_for_sparse_assembly
double FD_step_used_in_get_hessian_vector_products
bool Mass_matrix_reuse_is_enabled
bool Mass_matrix_has_been_computed
bool Discontinuous_element_formulation
double Minimum_dt
Minimum desired dt: if dt falls below this value, exit.
double Maximum_dt
Maximum desired dt.
double DTSF_max_increase
double DTSF_min_decrease
double Minimum_dt_but_still_proceed
bool Scale_arc_length
Boolean to control whether arc-length should be scaled.
double Desired_proportion_of_arc_length
Proportion of the arc-length to taken by the parameter.
double Theta_squared
int Sign_of_jacobian
Storage for the sign of the global Jacobian.
double Continuation_direction
double Parameter_derivative
Storage for the derivative of the global parameter wrt arc-length.
double Parameter_current
Storage for the present value of the global parameter.
bool Use_continuation_timestepper
Boolean to control original or new storage of dof stuff.
unsigned Dof_derivative_offset
unsigned Dof_current_offset
Vector< double > Dof_derivative
Storage for the derivative of the problem variables wrt arc-length.
Vector< double > Dof_current
Storage for the present values of the variables.
double Ds_current
Storage for the current step value.
unsigned Desired_newton_iterations_ds
double Minimum_ds
Minimum desired value of arc-length.
bool Bifurcation_detection
Boolean to control bifurcation detection via determinant of Jacobian.
bool Bisect_to_find_bifurcation
Boolean to control wheter bisection is used to located bifurcation.
bool First_jacobian_sign_change
Boolean to indicate whether a sign change has occured in the Jacobian.
bool Arc_length_step_taken
Boolean to indicate whether an arc-length step has been taken.
bool Use_finite_differences_for_continuation_derivatives
OomphCommunicator * Communicator_pt
The communicator for this problem.
bool Always_take_one_newton_step
double Timestep_reduction_factor_after_nonconvergence
bool Keep_temporal_error_below_tolerance
Private Attributes
DocInfo Doc_info
DocInfo object.
bool Surface_pinned
Boolean to indicate whether the surface is pinned.
Data * External_pressure_data_pt
Pointer to the external data point.
Additional Inherited Members
Public Types inherited from oomph::Problem
typedef void(* SpatialErrorEstimatorFctPt) (Mesh *&mesh_pt, Vector< double > &elemental_error)
Function pointer for spatial error estimator.
typedef void(* SpatialErrorEstimatorWithDocFctPt) (Mesh *&mesh_pt, Vector< double > &elemental_error, DocInfo &doc_info)
Function pointer for spatial error estimator with doc.
Static Public Attributes inherited from oomph::Problem
static bool Suppress_warning_about_actions_before_read_unstructured_meshes
Protected Types inherited from oomph::Problem
enum Assembly_method {
Perform_assembly_using_vectors_of_pairs , Perform_assembly_using_two_vectors , Perform_assembly_using_maps , Perform_assembly_using_lists ,
Perform_assembly_using_two_arrays
}
Enumerated flags to determine which sparse assembly method is used.
Protected Member Functions inherited from oomph::Problem
unsigned setup_element_count_per_dof ()
virtual void sparse_assemble_row_or_column_compressed (Vector< int * > &column_or_row_index, Vector< int * > &row_or_column_start, Vector< double * > &value, Vector< unsigned > &nnz, Vector< double * > &residual, bool compressed_row_flag)
virtual void actions_before_newton_step ()
virtual void actions_after_newton_step ()
virtual void actions_after_implicit_timestep ()
virtual void actions_after_implicit_timestep_and_error_estimation ()
virtual void actions_before_explicit_timestep ()
Actions that should be performed before each explicit time step.
virtual void actions_after_explicit_timestep ()
Actions that should be performed after each explicit time step.
virtual void actions_before_read_unstructured_meshes ()
virtual void actions_after_read_unstructured_meshes ()
virtual void actions_after_change_in_global_parameter (double *const &parameter_pt)
virtual void actions_after_change_in_bifurcation_parameter ()
virtual void actions_after_parameter_increase (double *const &parameter_pt)
double & dof_derivative (const unsigned &i)
double & dof_current (const unsigned &i)
virtual void set_initial_condition ()
virtual double global_temporal_error_norm ()
unsigned newton_solve_continuation (double *const &parameter_pt)
unsigned newton_solve_continuation (double *const &parameter_pt, DoubleVector &z)
void calculate_continuation_derivatives (double *const &parameter_pt)
void calculate_continuation_derivatives (const DoubleVector &z)
void calculate_continuation_derivatives_fd (double *const &parameter_pt)
bool does_pointer_correspond_to_problem_data (double *const &parameter_pt)
void set_consistent_pinned_values_for_continuation ()
Static Protected Attributes inherited from oomph::Problem
static ContinuationStorageScheme Continuation_time_stepper
Storage for the single static continuation timestorage object.
Detailed Description
template<class NST_ELEMENT, class AD_ELEMENT>
class ConvectionProblem< NST_ELEMENT, AD_ELEMENT >
/////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////// 2D Convection problem on two rectangular domains, discretised with Navier-Stokes and Advection-Diffusion elements. The specific type of elements is specified via the template parameters.
/////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////// 2D Convection problem on rectangular domain, discretised with refineable elements. The specific type of element is specified via the template parameter.
/////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////// 2D Convection problem on rectangular domain. The specific type of element is specified via the template parameter.
Constructor & Destructor Documentation
ConvectionProblem() [1/8]
template<class ELEMENT , class INTERFACE_ELEMENT > ConvectionProblem< ELEMENT, INTERFACE_ELEMENT >::ConvectionProblem
Constructor.
Constructor for convection problem.
 {
  //Allocate a timestepper
  add_time_stepper_pt(new BDF<2>);
  // Set output directory
 #ifdef USE_FD_JACOBIAN_NST_IN_MULTI_DOMAIN_BOUSSINESQ
  Doc_info.set_directory("RESLT_FD");
 #else
  Doc_info.set_directory("RESLT");
 #endif
  // # of elements in x-direction
  unsigned n_x=8;
  // # of elements in y-direction
  unsigned n_y=8;
  // Domain length in x-direction
  double l_x=3.0;
  // Domain length in y-direction
  double l_y=1.0;
  // Build two standard rectangular quadmesh
  Nst_mesh_pt =
   new RectangularQuadMesh<NST_ELEMENT>(n_x,n_y,l_x,l_y,time_stepper_pt());
  Adv_diff_mesh_pt =
   new RectangularQuadMesh<AD_ELEMENT>(n_x,n_y,l_x,l_y,time_stepper_pt());
  // Set the boundary conditions for this problem: All nodes are
  // free by default -- only need to pin the ones that have Dirichlet
  // conditions here
  //Loop over the boundaries
  unsigned num_bound = nst_mesh_pt()->nboundary();
  for(unsigned ibound=0;ibound<num_bound;ibound++)
   {
    //Set the maximum index to be pinned (all values by default)
    unsigned val_max;//=3; (fine for combined element... !)
    //Loop over the number of nodes on the boundry
    unsigned num_nod= nst_mesh_pt()->nboundary_node(ibound);
    for (unsigned inod=0;inod<num_nod;inod++)
     {
      //If we are on the side-walls, the v-velocity and temperature
      //satisfy natural boundary conditions, so we only pin the
      //first value
      if ((ibound==1) || (ibound==3))
       {
        val_max=1;
       }
      else // pin all values
       {
        val_max=nst_mesh_pt()->boundary_node_pt(ibound,inod)->nvalue();
       }
      //Loop over the desired values stored at the nodes and pin
      for(unsigned j=0;j<val_max;j++)
       {
        nst_mesh_pt()->boundary_node_pt(ibound,inod)->pin(j);
       }
     }
   }
  //Pin the zero-th pressure dof in element 0 and set its value to
  //zero:
  fix_pressure(0,0,0.0);
  //Loop over the boundaries of the AD mesh
  num_bound = adv_diff_mesh_pt()->nboundary();
  for(unsigned ibound=0;ibound<num_bound;ibound++)
   {
    //Set the maximum index to be pinned (all values by default)
    unsigned val_max=0;
    //Loop over the number of nodes on the boundry
    unsigned num_nod= adv_diff_mesh_pt()->nboundary_node(ibound);
    for (unsigned inod=0;inod<num_nod;inod++)
     {
      //If we are on the side-walls, the v-velocity and temperature
      //satisfy natural boundary conditions, so we don't pin anything
      // in this mesh
      if ((ibound==1) || (ibound==3))
       {
        val_max=0;
       }
      else // pin all values
       {
        val_max=adv_diff_mesh_pt()->boundary_node_pt(ibound,inod)->nvalue();
        //Loop over the desired values stored at the nodes and pin
        for(unsigned j=0;j<val_max;j++)
         {
          adv_diff_mesh_pt()->boundary_node_pt(ibound,inod)->pin(j);
         }
       }
     }
   }
  // Complete the build of all elements so they are fully functional
  // Loop over the elements to set up element-specific
  // things that cannot be handled by the (argument-free!) ELEMENT
  // constructors.
  unsigned n_nst_element = nst_mesh_pt()->nelement();
  for(unsigned i=0;i<n_nst_element;i++)
   {
    // Upcast from GeneralsedElement to the present element
    NST_ELEMENT *el_pt = dynamic_cast<NST_ELEMENT*>
     (nst_mesh_pt()->element_pt(i));
    // Set the Reynolds number (1/Pr in our non-dimensionalisation)
    el_pt->re_pt() = &Global_Physical_Variables::Inverse_Prandtl;
    // Set ReSt (also 1/Pr in our non-dimensionalisation)
    el_pt->re_st_pt() = &Global_Physical_Variables::Inverse_Prandtl;
    // Set the Rayleigh number
    el_pt->ra_pt() = &Global_Physical_Variables::Rayleigh;
    //Set Gravity vector
    el_pt->g_pt() = &Global_Physical_Variables::Direction_of_gravity;
    // We can ignore the external geometric data in the "external"
    // advection diffusion element when computing the Jacobian matrix
    // because the interaction does not involve spatial gradients of
    // the temperature (and also because the mesh isn't moving!)
    el_pt->ignore_external_geometric_data();
    //The mesh is fixed, so we can disable ALE
    el_pt->disable_ALE();
   }
  unsigned n_ad_element = adv_diff_mesh_pt()->nelement();
  for(unsigned i=0;i<n_ad_element;i++)
   {
    // Upcast from GeneralsedElement to the present element
    AD_ELEMENT *el_pt = dynamic_cast<AD_ELEMENT*>
     (adv_diff_mesh_pt()->element_pt(i));
    // Set the Peclet number
    el_pt->pe_pt() = &Global_Physical_Variables::Peclet;
    // Set the Peclet number multiplied by the Strouhal number
    el_pt->pe_st_pt() =&Global_Physical_Variables::Peclet;
    //The mesh is fixed, so we can disable ALE
    el_pt->disable_ALE();
    // We can ignore the external geometric data in the "external"
    // advection diffusion element when computing the Jacobian matrix
    // because the interaction does not involve spatial gradients of
    // the temperature (and also because the mesh isn't moving!)
    el_pt->ignore_external_geometric_data();
   }
  // combine the submeshes
  add_sub_mesh(Nst_mesh_pt);
  add_sub_mesh(Adv_diff_mesh_pt);
  build_global_mesh();
  // Setup multi-domain interaction
  Multi_domain_functions::
   setup_multi_domain_interactions<NST_ELEMENT,AD_ELEMENT>
   (this,nst_mesh_pt(),adv_diff_mesh_pt());
  // Setup equation numbering scheme
  cout <<"Number of equations: " << assign_eqn_numbers() << endl;
 } // end of constructor
References oomph::Global_Physical_Variables::Direction_of_gravity, GlobalParameters::Doc_info, i, Global_Physical_Variables::Inverse_Prandtl, j, Global_Physical_Variables::Peclet, Global_Physical_Variables::Rayleigh, and oomph::DocInfo::set_directory().
~ConvectionProblem() [1/8]
template<class NST_ELEMENT , class AD_ELEMENT > ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::~ConvectionProblem () inline
Destructor. Empty.
 {}
ConvectionProblem() [2/8]
template<class NST_ELEMENT , class AD_ELEMENT > ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::ConvectionProblem ()
Constructor.
~ConvectionProblem() [2/8]
template<class NST_ELEMENT , class AD_ELEMENT > ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::~ConvectionProblem () inline
Destructor. Empty.
 {}
ConvectionProblem() [3/8]
template<class NST_ELEMENT , class AD_ELEMENT > ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::ConvectionProblem ()
Constructor.
~ConvectionProblem() [3/8]
template<class NST_ELEMENT , class AD_ELEMENT > ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::~ConvectionProblem () inline
Destructor. Empty.
 {}
ConvectionProblem() [4/8]
template<class NST_ELEMENT , class AD_ELEMENT > ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::ConvectionProblem ()
Constructor.
~ConvectionProblem() [4/8]
template<class NST_ELEMENT , class AD_ELEMENT > ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::~ConvectionProblem () inline
Destructor. Empty.
 {}
ConvectionProblem() [5/8]
template<class ELEMENT , class INTERFACE_ELEMENT > ConvectionProblem< ELEMENT, INTERFACE_ELEMENT >::ConvectionProblem (const bool & pin = true)
Constructor. The boolean indicates whether the free surface.
Constructor for convection problem.
                                    : Surface_pinned(pin)
 {
  //Allocate a timestepper
  add_time_stepper_pt(new BDF<2>);
  // Set output directory
  Doc_info.set_directory("RESLT");
  // # of elements in x-direction
  unsigned n_x=8;
  // # of elements in y-direction
  unsigned n_y=8;
  // Domain length in x-direction
  double l_x=3.0;
  // Domain length in y-direction
  double l_y=1.0;
  // Build a standard rectangular quadmesh
  Bulk_mesh_pt =
   new SingleLayerSpineMesh<ELEMENT>(n_x,n_y,l_x,l_y,time_stepper_pt());
  //Create the surface mesh that will contain the interface elements
  //First create storage, but with no elements or nodes
  Surface_mesh_pt = new Mesh;
  //Loop over the horizontal elements
  for(unsigned i=0;i<n_x;i++)
   {
    //Construct a new 1D line element on the face on which the local
    //coordinate 1 is fixed at its max. value (1) --- This is face 2
    FiniteElement *interface_element_pt =
     new INTERFACE_ELEMENT(
      Bulk_mesh_pt->finite_element_pt(n_x*(n_y-1)+i),2);
    //Push it back onto the stack
    this->Surface_mesh_pt->add_element_pt(interface_element_pt);
   }
  // Add the two sub-meshes to the problem
  add_sub_mesh(Bulk_mesh_pt);
  add_sub_mesh(Surface_mesh_pt);
  // Combine all sub-meshes into a single mesh
  build_global_mesh();
  //Pin the heights of all the spines if the surface is pinned
  if(Surface_pinned)
   {
    unsigned n_spine = Bulk_mesh_pt->nspine();
    for(unsigned n=0;n<n_spine;n++)
     {
      Bulk_mesh_pt->spine_pt(n)->spine_height_pt()->pin(0);
     }
   }
  // Set the boundary conditions for this problem: All nodes are
  // free by default -- only need to pin the ones that have Dirichlet
  // conditions here
  //Loop over the boundaries
  unsigned num_bound = Bulk_mesh_pt->nboundary();
  for(unsigned ibound=0;ibound<num_bound;ibound++)
   {
    //Set the minimum index to be pinned (all values by default)
    unsigned val_min=0;
    //Set the maximum index to be pinned (all values by default)
    unsigned val_max=3;
    //If we are on the side-walls, the v-velocity and temperature
    //satisfy natural boundary conditions, so we only pin the
    //first value
    if((ibound==1) || (ibound==3)) {val_max=1;}
    //If we on the top wall, v velocity is pinned
    if(ibound==2)
     {
      //If the surface is pinned, pin the v velocity
      if(Surface_pinned) {val_min=1; val_max=2;}
      //Otherwise pin nothing
      else {val_min=0; val_max=0;}
     }
    //Loop over the number of nodes on the boundary
    unsigned num_nod= Bulk_mesh_pt->nboundary_node(ibound);
    for (unsigned inod=0;inod<num_nod;inod++)
     {
      //Loop over the desired values stored at the nodes and pin
      for(unsigned j=val_min;j<val_max;j++)
       {
        Bulk_mesh_pt->boundary_node_pt(ibound,inod)->pin(j);
       }
     }
   }
  //Pin the zero-th pressure dof in element 0 and set its value to
  //zero:
  if(Surface_pinned) {fix_pressure(0,0,0.0);}
  // Complete the build of all elements so they are fully functional
  // Loop over the elements to set up element-specific
  // things that cannot be handled by the (argument-free!) ELEMENT
  // constructor.
  unsigned n_element = Bulk_mesh_pt->nelement();
  for(unsigned i=0;i<n_element;i++)
   {
    // Upcast from GeneralsedElement to the present element
    ELEMENT *el_pt = dynamic_cast<ELEMENT*>(Bulk_mesh_pt->element_pt(i));
    // Set the Peclet number
    el_pt->pe_pt() = &Global_Physical_Variables::Peclet;
    // Set the Peclet number multiplied by the Strouhal number
    el_pt->pe_st_pt() =&Global_Physical_Variables::Peclet;
    // Set the Reynolds number (1/Pr in our non-dimensionalisation)
    el_pt->re_pt() = &Global_Physical_Variables::Inverse_Prandtl;
    // Set ReSt (also 1/Pr in our non-dimensionalisation)
    el_pt->re_st_pt() = &Global_Physical_Variables::Inverse_Prandtl;
    // Set the Re/Fr equal to Bo/Ca, the scaled Bond number
    el_pt->re_invfr_pt() = &Global_Physical_Variables::Scaled_Bond;
    // Set the Rayleigh number
    el_pt->ra_pt() = &Global_Physical_Variables::Rayleigh;
    //Set Gravity vector
    el_pt->g_pt() = &Global_Physical_Variables::Direction_of_gravity;
    //If the mesh is fixed, we can disable ALE
    if(Surface_pinned) {el_pt->disable_ALE();}
   }
   // Loop over the interface elements to set up element-specific
  // things that cannot be handled by the (argument-free!) ELEMENT
  // constructor.
  unsigned n_interface  = Surface_mesh_pt->nelement();
  for(unsigned i=0;i<n_interface;i++)
   {
    // Upcast from GeneralsedElement to the present element
    INTERFACE_ELEMENT *el_pt = dynamic_cast<INTERFACE_ELEMENT*>(
     Surface_mesh_pt->element_pt(i));
    // Set the Biot number
    el_pt->bi_pt() = &Global_Physical_Variables::Biot;
    // Set the Marangoni number
    el_pt->ma_pt() =&Global_Physical_Variables::Marangoni;
    // Set the Capillary number
    el_pt->ca_pt() = &Global_Physical_Variables::Capillary;
    // Set the surface elasticity number
    el_pt->beta_pt() = &Global_Physical_Variables::Beta;
    // Set the surface peclect number
    el_pt->peclet_s_pt() = &Global_Physical_Variables::Peclet_S;
    // Set the surface peclect number multiplied by strouhal number
    el_pt->peclet_strouhal_s_pt() = &Global_Physical_Variables::Peclet_St_S;
   }
  // Setup equation numbering scheme
  cout <<"Number of equations: " << assign_eqn_numbers() << endl;
 } // end of constructor
References oomph::Mesh::add_element_pt(), oomph::Problem::add_sub_mesh(), oomph::Problem::add_time_stepper_pt(), oomph::Problem::assign_eqn_numbers(), Global_Physical_Variables::Beta, Global_Physical_Variables::Biot, oomph::Problem::build_global_mesh(), ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::Bulk_mesh_pt, Global_Physical_Variables::Capillary, Global_Physical_Variables::Direction_of_gravity, ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::Doc_info, oomph::Mesh::element_pt(), ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::fix_pressure(), i, Global_Physical_Variables::Inverse_Prandtl, j, Global_Physical_Variables::Marangoni, n, oomph::Mesh::nelement(), Global_Physical_Variables::Peclet, Global_Physical_Variables::Peclet_S, Global_Physical_Variables::Peclet_St_S, Global_Physical_Variables::Rayleigh, Global_Physical_Variables::Scaled_Bond, oomph::DocInfo::set_directory(), ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::Surface_mesh_pt, ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::Surface_pinned, and oomph::Problem::time_stepper_pt().
~ConvectionProblem() [5/8]
template<class NST_ELEMENT , class AD_ELEMENT > ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::~ConvectionProblem () inline
Destructor. Empty.
 {}
ConvectionProblem() [6/8]
template<class NST_ELEMENT , class AD_ELEMENT > ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::ConvectionProblem (const bool & pin = true)
Constructor. The boolean indicates whether the free surface.
~ConvectionProblem() [6/8]
template<class NST_ELEMENT , class AD_ELEMENT > ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::~ConvectionProblem () inline
Destructor. Empty.
 {}
ConvectionProblem() [7/8]
template<class NST_ELEMENT , class AD_ELEMENT > ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::ConvectionProblem ()
Constructor.
~ConvectionProblem() [7/8]
template<class NST_ELEMENT , class AD_ELEMENT > ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::~ConvectionProblem () inline
Destructor. Empty.
 {}
ConvectionProblem() [8/8]
template<class NST_ELEMENT , class AD_ELEMENT > ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::ConvectionProblem (const bool & pin = true)
Constructor. The boolean indicates whether the free surface.
~ConvectionProblem() [8/8]
template<class NST_ELEMENT , class AD_ELEMENT > ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::~ConvectionProblem () inline
Destructor. Empty.
 {}
Member Function Documentation
actions_after_distribute()
template<class NST_ELEMENT , class AD_ELEMENT > void ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::actions_after_distribute () inline
Actions after distribute: re-setup multi-domain interaction.
   {
    // Re-setup multi-domain interaction
    Multi_domain_functions::setup_multi_domain_interactions
     <NST_ELEMENT,AD_ELEMENT>(this,nst_mesh_pt(),adv_diff_mesh_pt());
   }
References oomph::Multi_domain_functions::setup_multi_domain_interactions().
actions_after_newton_solve() [1/8]
template<class NST_ELEMENT , class AD_ELEMENT > void ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::actions_after_newton_solve () inline virtual
Update the problem after solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_after_newton_solve() [2/8]
template<class NST_ELEMENT , class AD_ELEMENT > void ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::actions_after_newton_solve () inline virtual
Update the problem after solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_after_newton_solve() [3/8]
template<class NST_ELEMENT , class AD_ELEMENT > void ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::actions_after_newton_solve () inline virtual
Update the problem after solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_after_newton_solve() [4/8]
template<class NST_ELEMENT , class AD_ELEMENT > void ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::actions_after_newton_solve () inline virtual
Update the problem after solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_after_newton_solve() [5/8]
template<class NST_ELEMENT , class AD_ELEMENT > void ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::actions_after_newton_solve () inline virtual
Update the problem after solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_after_newton_solve() [6/8]
template<class NST_ELEMENT , class AD_ELEMENT > void ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::actions_after_newton_solve () inline virtual
Update the problem after solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_after_newton_solve() [7/8]
template<class NST_ELEMENT , class AD_ELEMENT > void ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::actions_after_newton_solve () inline virtual
Update the problem after solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_after_newton_solve() [8/8]
template<class NST_ELEMENT , class AD_ELEMENT > void ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::actions_after_newton_solve () inline virtual
Update the problem after solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_before_adapt() [1/5]
template<class NST_ELEMENT , class AD_ELEMENT > void ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::actions_before_adapt () inline virtual
Actions before adapt:(empty)
Reimplemented from oomph::Problem.
 {}
actions_before_adapt() [2/5]
template<class NST_ELEMENT , class AD_ELEMENT > void ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::actions_before_adapt () inline virtual
Actions before adapt:(empty)
Reimplemented from oomph::Problem.
 {}
actions_before_adapt() [3/5]
template<class NST_ELEMENT , class AD_ELEMENT > void ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::actions_before_adapt () inline virtual
Actions before adapt:(empty)
Reimplemented from oomph::Problem.
 {}
actions_before_adapt() [4/5]
template<class NST_ELEMENT , class AD_ELEMENT > void ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::actions_before_adapt () inline virtual
Actions before adapt:(empty)
Reimplemented from oomph::Problem.
 {}
actions_before_adapt() [5/5]
template<class NST_ELEMENT , class AD_ELEMENT > void ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::actions_before_adapt () inline virtual
Actions before adapt:(empty)
Reimplemented from oomph::Problem.
 {}
actions_before_implicit_timestep() [1/8]
template<class NST_ELEMENT , class AD_ELEMENT > void ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::actions_before_implicit_timestep () inline virtual
Actions before the timestep (update the the time-dependent boundary conditions)
Reimplemented from oomph::Problem.
   {
    set_boundary_conditions(time_pt()->time());
   }
actions_before_implicit_timestep() [2/8]
template<class NST_ELEMENT , class AD_ELEMENT > void ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::actions_before_implicit_timestep () inline virtual
Actions before the timestep (update the the time-dependent boundary conditions)
Reimplemented from oomph::Problem.
   {
    set_boundary_conditions(time_pt()->time());
   }
actions_before_implicit_timestep() [3/8]
template<class NST_ELEMENT , class AD_ELEMENT > void ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::actions_before_implicit_timestep () inline virtual
Actions before the timestep (update the the time-dependent boundary conditions)
Reimplemented from oomph::Problem.
   {
    set_boundary_conditions(time_pt()->time());
   }
actions_before_implicit_timestep() [4/8]
template<class NST_ELEMENT , class AD_ELEMENT > void ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::actions_before_implicit_timestep () inline virtual
Actions before the timestep (update the the time-dependent boundary conditions)
Reimplemented from oomph::Problem.
   {
    set_boundary_conditions(time_pt()->time());
   }
actions_before_implicit_timestep() [5/8]
template<class NST_ELEMENT , class AD_ELEMENT > void ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::actions_before_implicit_timestep () inline virtual
Actions before the timestep (update the the time-dependent boundary conditions)
Reimplemented from oomph::Problem.
   {set_boundary_conditions(time_pt()->time());}
actions_before_implicit_timestep() [6/8]
template<class NST_ELEMENT , class AD_ELEMENT > void ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::actions_before_implicit_timestep () inline virtual
Actions before the timestep (update the the time-dependent boundary conditions)
Reimplemented from oomph::Problem.
   {set_boundary_conditions(time_pt()->time());}
actions_before_implicit_timestep() [7/8]
template<class NST_ELEMENT , class AD_ELEMENT > void ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::actions_before_implicit_timestep () inline virtual
Actions before the timestep (update the the time-dependent boundary conditions)
Reimplemented from oomph::Problem.
   {
    set_boundary_conditions(time_pt()->time());
   }
actions_before_implicit_timestep() [8/8]
template<class NST_ELEMENT , class AD_ELEMENT > void ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::actions_before_implicit_timestep () inline virtual
Actions before the timestep (update the the time-dependent boundary conditions)
Reimplemented from oomph::Problem.
   {set_boundary_conditions(time_pt()->time());}
actions_before_newton_convergence_check() [1/4]
template<class NST_ELEMENT , class AD_ELEMENT > void ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::actions_before_newton_convergence_check () inline virtual
Remember to update the nodes if the surface is not pinned.
Reimplemented from oomph::Problem.
   {if(!Surface_pinned) {Bulk_mesh_pt->node_update();}}
actions_before_newton_convergence_check() [2/4]
template<class NST_ELEMENT , class AD_ELEMENT > void ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::actions_before_newton_convergence_check () inline virtual
Remember to update the nodes if the surface is not pinned.
Reimplemented from oomph::Problem.
   {
    if(!Surface_pinned) {Bulk_mesh_pt->node_update();}
    // This driver code cannot be allowed to use the analytical form of
    // get_dresidual_dnodal_coordinates(...) that is implemented in the
    // NavierStokesEquations class, since the elemental residuals have
    // contributions from external data which is not taken into account
    // by that routine. We therefore force the bulk elements to use the
    // fully-finite differenced version.
    const unsigned n_element = Bulk_mesh_pt->nelement();
    for(unsigned e=0;e<n_element;e++)
     {
      ElementWithMovingNodes* el_pt =
       dynamic_cast<ElementWithMovingNodes*>(Bulk_mesh_pt->element_pt(e));
      el_pt->evaluate_shape_derivs_by_direct_fd();
     }
   }
References e(), and oomph::ElementWithMovingNodes::evaluate_shape_derivs_by_direct_fd().
actions_before_newton_convergence_check() [3/4]
template<class NST_ELEMENT , class AD_ELEMENT > void ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::actions_before_newton_convergence_check () inline virtual
Remember to update the nodes!
Reimplemented from oomph::Problem.
   {
    Bulk_mesh_pt->node_update();
    // This driver code cannot be allowed to use the analytical form of
    // get_dresidual_dnodal_coordinates(...) that is implemented in the
    // NavierStokesEquations class, since the elemental residuals have
    // contributions from external data which is not taken into account
    // by that routine. We therefore force the bulk elements to use the
    // fully-finite differenced version.
    const unsigned n_element = Bulk_mesh_pt->nelement();
    for(unsigned e=0;e<n_element;e++)
     {
      ElementWithMovingNodes* el_pt =
       dynamic_cast<ElementWithMovingNodes*>(Bulk_mesh_pt->element_pt(e));
      el_pt->evaluate_shape_derivs_by_direct_fd();
     }
   }
References e(), and oomph::ElementWithMovingNodes::evaluate_shape_derivs_by_direct_fd().
actions_before_newton_convergence_check() [4/4]
template<class NST_ELEMENT , class AD_ELEMENT > void ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::actions_before_newton_convergence_check () inline virtual
Remember to update the nodes if the surface is not pinned.
Reimplemented from oomph::Problem.
   {if(!Surface_pinned) {Bulk_mesh_pt->node_update();}}
actions_before_newton_solve() [1/8]
template<class NST_ELEMENT , class AD_ELEMENT > void ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::actions_before_newton_solve () inline virtual
Update the problem specs before solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_before_newton_solve() [2/8]
template<class NST_ELEMENT , class AD_ELEMENT > void ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::actions_before_newton_solve () inline virtual
Update the problem specs before solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_before_newton_solve() [3/8]
template<class NST_ELEMENT , class AD_ELEMENT > void ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::actions_before_newton_solve () inline virtual
Update the problem specs before solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_before_newton_solve() [4/8]
template<class NST_ELEMENT , class AD_ELEMENT > void ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::actions_before_newton_solve () inline virtual
Update the problem specs before solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_before_newton_solve() [5/8]
template<class NST_ELEMENT , class AD_ELEMENT > void ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::actions_before_newton_solve () inline virtual
Update the problem specs before solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_before_newton_solve() [6/8]
template<class NST_ELEMENT , class AD_ELEMENT > void ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::actions_before_newton_solve () inline virtual
Update the problem specs before solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_before_newton_solve() [7/8]
template<class NST_ELEMENT , class AD_ELEMENT > void ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::actions_before_newton_solve () inline virtual
Update the problem specs before solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_before_newton_solve() [8/8]
template<class NST_ELEMENT , class AD_ELEMENT > void ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::actions_before_newton_solve () inline virtual
Update the problem specs before solve (empty)
Reimplemented from oomph::Problem.
 {}
adv_diff_mesh_pt() [1/2]
template<class NST_ELEMENT , class AD_ELEMENT > RectangularQuadMesh<AD_ELEMENT>* ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::adv_diff_mesh_pt () inline
Access function to the Advection-Diffusion mesh.
   {
    return dynamic_cast<RectangularQuadMesh<AD_ELEMENT>*>(Adv_diff_mesh_pt);
   }
adv_diff_mesh_pt() [2/2]
template<class NST_ELEMENT , class AD_ELEMENT > RectangularQuadMesh<AD_ELEMENT>* ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::adv_diff_mesh_pt () inline
Access function to the Advection-Diffusion mesh.
   {
    return dynamic_cast<RectangularQuadMesh<AD_ELEMENT>*>(Adv_diff_mesh_pt);
   }
doc_solution() [1/8]
template<class ELEMENT , class INTERFACE_ELEMENT > void ConvectionProblem< ELEMENT, INTERFACE_ELEMENT >::doc_solution
Doc the solution.
 {
  //Declare an output stream and filename
  ofstream some_file;
  char filename[100];
  // Number of plot points: npts x npts
  unsigned npts=5;
  // Output Navier-Stokes solution
  sprintf(filename,"%s/fluid_soln%i_on_proc%i.dat",
          Doc_info.directory().c_str(),
          Doc_info.number(),
          this->communicator_pt()->my_rank());
  some_file.open(filename);
  nst_mesh_pt()->output(some_file,npts);
  some_file.close();
  // Output advection diffusion solution
  sprintf(filename,"%s/temperature_soln%i_on_proc%i.dat",
          Doc_info.directory().c_str(),
          Doc_info.number(),
          this->communicator_pt()->my_rank());
  some_file.open(filename);
  adv_diff_mesh_pt()->output(some_file,npts);
  some_file.close();
  Doc_info.number()++;
 } // end of doc
References oomph::DocInfo::directory(), GlobalParameters::Doc_info, MergeRestartFiles::filename, and oomph::DocInfo::number().
doc_solution() [2/8]
template<class NST_ELEMENT , class AD_ELEMENT > void ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::doc_solution ()
Doc the solution.
doc_solution() [3/8]
template<class NST_ELEMENT , class AD_ELEMENT > void ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::doc_solution ()
Doc the solution.
doc_solution() [4/8]
template<class NST_ELEMENT , class AD_ELEMENT > void ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::doc_solution ()
Doc the solution.
doc_solution() [5/8]
template<class NST_ELEMENT , class AD_ELEMENT > void ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::doc_solution ()
Doc the solution.
doc_solution() [6/8]
template<class NST_ELEMENT , class AD_ELEMENT > void ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::doc_solution ()
Doc the solution.
doc_solution() [7/8]
template<class ELEMENT , class INTERFACE_ELEMENT > void ConvectionProblem< ELEMENT, INTERFACE_ELEMENT >::doc_solution (std::ofstream & trace)
Doc the solution.
 {
  //Declare an output stream and filename
  ofstream some_file;
  char filename[100];
  // Number of plot points: npts x npts
  unsigned npts=5;
  // Output solution
  //-----------------
  sprintf(filename,"%s/soln%i.dat",Doc_info.directory().c_str(),
          Doc_info.number());
  some_file.open(filename);
  unsigned n_element = Bulk_mesh_pt->nelement();
  for(unsigned e=0;e<n_element;e++)
   {
    Bulk_mesh_pt->finite_element_pt(e)->output(some_file,npts);
   }
  some_file.close();
  //Output the interface
  sprintf(filename,"%s/int%i.dat",Doc_info.directory().c_str(),
          Doc_info.number());
  some_file.open(filename);
  unsigned n_interface  = Surface_mesh_pt->nelement();
  for(unsigned i=0;i<n_interface;i++)
   {
    Surface_mesh_pt->finite_element_pt(i)->output(some_file,npts);
   }
  some_file.close();
  trace << time_pt()->time() << " "
        << Bulk_mesh_pt->boundary_node_pt(2,8)->value(2) << " "
        << Bulk_mesh_pt->boundary_node_pt(2,8)->value(3) << std::endl;
  Doc_info.number()++;
 } // end of doc
References oomph::DocInfo::directory(), GlobalParameters::Doc_info, e(), MergeRestartFiles::filename, i, and oomph::DocInfo::number().
doc_solution() [8/8]
template<class NST_ELEMENT , class AD_ELEMENT > void ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::doc_solution (std::ofstream & trace)
Doc the solution.
fix_pressure() [1/8]
template<class NST_ELEMENT , class AD_ELEMENT > void ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::fix_pressure (const unsigned & e, const unsigned & pdof, const double & pvalue) inline
Fix pressure in element e at pressure dof pdof and set to pvalue.
   {
    //Cast to specific element and fix pressure
    dynamic_cast<NST_ELEMENT*>(nst_mesh_pt()->element_pt(e))->
     fix_pressure(pdof,pvalue);
   } // end_of_fix_pressure
References e().
Referenced by ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::ConvectionProblem().
fix_pressure() [2/8]
template<class NST_ELEMENT , class AD_ELEMENT > void ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::fix_pressure (const unsigned & e, const unsigned & pdof, const double & pvalue) inline
Fix pressure in element e at pressure dof pdof and set to pvalue.
   {
    //Cast to specific element and fix pressure
    dynamic_cast<ELEMENT*>(mesh_pt()->element_pt(e))->
     fix_pressure(pdof,pvalue);
   } // end_of_fix_pressure
References e().
fix_pressure() [3/8]
template<class NST_ELEMENT , class AD_ELEMENT > void ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::fix_pressure (const unsigned & e, const unsigned & pdof, const double & pvalue) inline
Fix pressure in element e at pressure dof pdof and set to pvalue.
   {
    //Cast to specific element and fix pressure
    dynamic_cast<NST_ELEMENT*>(nst_mesh_pt()->element_pt(e))->
     fix_pressure(pdof,pvalue);
   } // end_of_fix_pressure
References e().
fix_pressure() [4/8]
template<class NST_ELEMENT , class AD_ELEMENT > void ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::fix_pressure (const unsigned & e, const unsigned & pdof, const double & pvalue) inline
Fix pressure in element e at pressure dof pdof and set to pvalue.
   {
    //Cast to specific element and fix pressure
    dynamic_cast<ELEMENT*>(mesh_pt()->element_pt(e))->
     fix_pressure(pdof,pvalue);
   } // end_of_fix_pressure
References e().
fix_pressure() [5/8]
template<class NST_ELEMENT , class AD_ELEMENT > void ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::fix_pressure (const unsigned & e, const unsigned & pdof, const double & pvalue) inline
Fix pressure in element e at pressure dof pdof and set to pvalue.
   {
    //Cast to specific element and fix pressure
    dynamic_cast<ELEMENT*>(Bulk_mesh_pt->element_pt(e))->
     fix_pressure(pdof,pvalue);
   } // end_of_fix_pressure
References e().
fix_pressure() [6/8]
template<class NST_ELEMENT , class AD_ELEMENT > void ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::fix_pressure (const unsigned & e, const unsigned & pdof, const double & pvalue) inline
Fix pressure in element e at pressure dof pdof and set to pvalue.
   {
    //Cast to specific element and fix pressure
    dynamic_cast<ELEMENT*>(Bulk_mesh_pt->element_pt(e))->
     fix_pressure(pdof,pvalue);
   } // end_of_fix_pressure
References e().
fix_pressure() [7/8]
template<class NST_ELEMENT , class AD_ELEMENT > void ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::fix_pressure (const unsigned & e, const unsigned & pdof, const double & pvalue) inline
Fix pressure in element e at pressure dof pdof and set to pvalue.
   {
    //Cast to specific element and fix pressure
    dynamic_cast<ELEMENT*>(Bulk_mesh_pt->element_pt(e))->
     fix_pressure(pdof,pvalue);
   } // end_of_fix_pressure
References e().
fix_pressure() [8/8]
template<class NST_ELEMENT , class AD_ELEMENT > void ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::fix_pressure (const unsigned & e, const unsigned & pdof, const double & pvalue) inline
Fix pressure in element e at pressure dof pdof and set to pvalue.
   {
    //Cast to specific element and fix pressure
    dynamic_cast<ELEMENT*>(Bulk_mesh_pt->element_pt(e))->
     fix_pressure(pdof,pvalue);
   } // end_of_fix_pressure
References e().
get_kinetic_energy()
template<class ELEMENT > void ConvectionProblem< ELEMENT >::get_kinetic_energy (double & E, double & Edot)
Get kinetic energy and kinetic energy flux.
 {
  //Reset values to zero
  E = 0.0; Edot=0.0;
  //Loop over the elements
  unsigned n_element = mesh_pt()->nelement();
  for(unsigned e=0;e<n_element;e++)
   {
    ELEMENT* elem_pt = dynamic_cast<ELEMENT*>(mesh_pt()->element_pt(e));
    E += elem_pt->kin_energy();
    Edot += elem_pt->d_kin_energy_dt();
   }
 }
References Global_Physical_Variables::E, and e().
mesh_pt() [1/2]
template<class NST_ELEMENT , class AD_ELEMENT > RectangularQuadMesh<ELEMENT>* ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::mesh_pt () inline
Overloaded version of the problem's access function to the mesh. Recasts the pointer to the base Mesh object to the actual mesh type.
   {
    return dynamic_cast<RectangularQuadMesh<ELEMENT>*>(
     Problem::mesh_pt());
   }
References oomph::Problem::mesh_pt().
mesh_pt() [2/2]
template<class NST_ELEMENT , class AD_ELEMENT > RectangularQuadMesh<ELEMENT>* ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::mesh_pt () inline
Overloaded version of the problem's access function to the mesh. Recasts the pointer to the base Mesh object to the actual mesh type.
   {
    return dynamic_cast<RectangularQuadMesh<ELEMENT>*>(
     Problem::mesh_pt());
   }
References oomph::Problem::mesh_pt().
nst_mesh_pt() [1/2]
template<class NST_ELEMENT , class AD_ELEMENT > RectangularQuadMesh<NST_ELEMENT>* ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::nst_mesh_pt () inline
Access function to the Navier-Stokes mesh.
   {
    return dynamic_cast<RectangularQuadMesh<NST_ELEMENT>*>(Nst_mesh_pt);
   }
nst_mesh_pt() [2/2]
template<class NST_ELEMENT , class AD_ELEMENT > RectangularQuadMesh<NST_ELEMENT>* ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::nst_mesh_pt () inline
Access function to the Navier-Stokes mesh.
   {
    return dynamic_cast<RectangularQuadMesh<NST_ELEMENT>*>(Nst_mesh_pt);
   }
set_boundary_conditions() [1/8]
template<class ELEMENT , class INTERFACE_ELEMENT > void ConvectionProblem< ELEMENT, INTERFACE_ELEMENT >::set_boundary_conditions (const double & time)
Set the boundary conditions.
Set the boundary conditions as a function of continuous time
 {
  // Loop over all the boundaries on the NST mesh
  unsigned num_bound=nst_mesh_pt()->nboundary();
  for(unsigned ibound=0;ibound<num_bound;ibound++)
   {
    // Loop over the nodes on boundary
    unsigned num_nod=nst_mesh_pt()->nboundary_node(ibound);
    for(unsigned inod=0;inod<num_nod;inod++)
     {
      // Get pointer to node
      Node* nod_pt=nst_mesh_pt()->boundary_node_pt(ibound,inod);
      //Set the number of velocity components
      unsigned vel_max=2;
      //If we are on the side walls we only set the x-velocity.
      if((ibound==1) || (ibound==3)) {vel_max = 1;}
      //Set the pinned velocities to zero on NST mesh
      for(unsigned j=0;j<vel_max;j++) {nod_pt->set_value(j,0.0);}
      //If we are on the top boundary
      if(ibound==2)
       {
        //Add small velocity imperfection if desired
        double epsilon = 0.01;
        //Read out the x position
        double x = nod_pt->x(0);
        //Set a sinusoidal perturbation in the vertical velocity
        //This perturbation is mass conserving
        double value = sin(2.0*MathematicalConstants::Pi*x/3.0)*
         epsilon*time*exp(-time);
        nod_pt->set_value(1,value);
       }
     }
   }
  // Loop over all the boundaries on the AD mesh
  num_bound=adv_diff_mesh_pt()->nboundary();
  for(unsigned ibound=0;ibound<num_bound;ibound++)
   {
    // Loop over the nodes on boundary
    unsigned num_nod=adv_diff_mesh_pt()->nboundary_node(ibound);
    for(unsigned inod=0;inod<num_nod;inod++)
     {
      // Get pointer to node
      Node* nod_pt=adv_diff_mesh_pt()->boundary_node_pt(ibound,inod);
      //If we are on the top boundary, set the temperature
      //to -0.5 (cooled)
      if(ibound==2) {nod_pt->set_value(0,-0.5);}
      //If we are on the bottom boundary, set the temperature
      //to 0.5 (heated)
      if(ibound==0) {nod_pt->set_value(0,0.5);}
     }
   }
 } // end_of_set_boundary_conditions
References oomph::SarahBL::epsilon, Eigen::bfloat16_impl::exp(), j, oomph::MathematicalConstants::Pi, oomph::Data::set_value(), sin(), Eigen::value, plotDoE::x, and oomph::Node::x().
set_boundary_conditions() [2/8]
template<class NST_ELEMENT , class AD_ELEMENT > void ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::set_boundary_conditions (const double & time)
Set the boundary conditions.
set_boundary_conditions() [3/8]
template<class NST_ELEMENT , class AD_ELEMENT > void ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::set_boundary_conditions (const double & time)
Set the boundary conditions.
set_boundary_conditions() [4/8]
template<class NST_ELEMENT , class AD_ELEMENT > void ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::set_boundary_conditions (const double & time)
Set the boundary conditions.
set_boundary_conditions() [5/8]
template<class NST_ELEMENT , class AD_ELEMENT > void ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::set_boundary_conditions (const double & time)
Set the boundary conditions.
set_boundary_conditions() [6/8]
template<class NST_ELEMENT , class AD_ELEMENT > void ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::set_boundary_conditions (const double & time)
Set the boundary conditions.
set_boundary_conditions() [7/8]
template<class NST_ELEMENT , class AD_ELEMENT > void ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::set_boundary_conditions (const double & time)
Set the boundary conditions.
set_boundary_conditions() [8/8]
template<class NST_ELEMENT , class AD_ELEMENT > void ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::set_boundary_conditions (const double & time)
Set the boundary conditions.
switch_boundary_conditions()
template<class NST_ELEMENT , class AD_ELEMENT > void ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::switch_boundary_conditions () inline
Unpin things for timestepping.
   {
    //Pin the external pressure
    External_pressure_data_pt->pin(0);
    //Release the internal pressure
    unfix_pressure(0,0);
    //Set the new number of unknowns
    std::cout << "Preparing to timestep: "
              << assign_eqn_numbers() << "\n";
   }
unfix_pressure() [1/4]
template<class NST_ELEMENT , class AD_ELEMENT > void ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::unfix_pressure (const unsigned & e, const unsigned & pdof) inline
UnFix pressure in element e at pressure dof pdof and set to pvalue.
   {
    //Cast to specific element and fix pressure
    dynamic_cast<ELEMENT*>(Bulk_mesh_pt->element_pt(e))->
     unfix_pressure(pdof);
   } // end_of_unfix_pressure
References e().
unfix_pressure() [2/4]
template<class NST_ELEMENT , class AD_ELEMENT > void ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::unfix_pressure (const unsigned & e, const unsigned & pdof) inline
UnFix pressure in element e at pressure dof pdof and set to pvalue.
   {
    //Cast to specific element and fix pressure
    dynamic_cast<ELEMENT*>(Bulk_mesh_pt->element_pt(e))->
     unfix_pressure(pdof);
   } // end_of_unfix_pressure
References e().
unfix_pressure() [3/4]
template<class NST_ELEMENT , class AD_ELEMENT > void ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::unfix_pressure (const unsigned & e, const unsigned & pdof) inline
UnFix pressure in element e at pressure dof pdof and set to pvalue.
   {
    //Cast to specific element and fix pressure
    dynamic_cast<ELEMENT*>(Bulk_mesh_pt->element_pt(e))->
     unfix_pressure(pdof);
   } // end_of_unfix_pressure
References e().
unfix_pressure() [4/4]
template<class NST_ELEMENT , class AD_ELEMENT > void ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::unfix_pressure (const unsigned & e, const unsigned & pdof) inline
UnFix pressure in element e at pressure dof pdof and set to pvalue.
   {
    //Cast to specific element and fix pressure
    dynamic_cast<ELEMENT*>(Bulk_mesh_pt->element_pt(e))->
     unfix_pressure(pdof);
   } // end_of_unfix_pressure
References e().
unpin_surface() [1/3]
template<class NST_ELEMENT , class AD_ELEMENT > void ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::unpin_surface () inline
Release the free surface so that it can move.
   {
    //Only bother if the surface is pinned
    if(Surface_pinned)
     {
      Surface_pinned = false;
      //Unpin the heights of all the spines in the middle
      unsigned n_spine = Bulk_mesh_pt->nspine();
      for(unsigned n=0;n<n_spine;n++)
       {
        Bulk_mesh_pt->spine_pt(n)->spine_height_pt()->unpin(0);
       }
      //If we on the top wall, v velocity is no longer pinned
      unsigned ibound=2;
      //Loop over the number of nodes on the boundary
      unsigned num_nod= Bulk_mesh_pt->nboundary_node(ibound);
      for (unsigned inod=0;inod<num_nod;inod++)
       {
        //Loop over the desired values stored at the nodes and unpin
        Bulk_mesh_pt->boundary_node_pt(ibound,inod)->unpin(1);
       }
      //Unfix the pressure
      unfix_pressure(0,0);
      // Loop over the elements to set up element-specific
      // and re-enable ALE
      unsigned n_element = Bulk_mesh_pt->nelement();
      for(unsigned i=0;i<n_element;i++)
       {
        // Upcast from GeneralsedElement to the present element
        ELEMENT *el_pt = dynamic_cast<ELEMENT*>(Bulk_mesh_pt->element_pt(i));
        el_pt->enable_ALE();
       }
      //Reassign the equation number
      std::cout << "Surface unpinned to give "
                << assign_eqn_numbers() << " equation numbers\n";
     }
   }
References i, and n.
unpin_surface() [2/3]
template<class NST_ELEMENT , class AD_ELEMENT > void ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::unpin_surface () inline
Release the free surface so that it can move.
   {
    //Only bother if the surface is pinned
    if(Surface_pinned)
     {
      Surface_pinned = false;
      //Unpin the heights of all the spines in the middle
      unsigned n_spine = Bulk_mesh_pt->nspine();
      for(unsigned n=0;n<n_spine;n++)
       {
        Bulk_mesh_pt->spine_pt(n)->spine_height_pt()->unpin(0);
       }
      //If we on the top wall, v velocity is no longer pinned
      unsigned ibound=2;
      //Loop over the number of nodes on the boundary
      unsigned num_nod= Bulk_mesh_pt->nboundary_node(ibound);
      for (unsigned inod=0;inod<num_nod;inod++)
       {
        //Loop over the desired values stored at the nodes and unpin
        Bulk_mesh_pt->boundary_node_pt(ibound,inod)->unpin(1);
       }
      //Unfix the pressure
      unfix_pressure(0,0);
      // Loop over the elements to set up element-specific
      // and re-enable ALE
      unsigned n_element = Bulk_mesh_pt->nelement();
      for(unsigned i=0;i<n_element;i++)
       {
        // Upcast from GeneralsedElement to the present element
        ELEMENT *el_pt = dynamic_cast<ELEMENT*>(Bulk_mesh_pt->element_pt(i));
        el_pt->enable_ALE();
       }
      //Reassign the equation number
      std::cout << "Surface unpinned to give "
                << assign_eqn_numbers() << " equation numbers\n";
     }
   }
References i, and n.
unpin_surface() [3/3]
template<class NST_ELEMENT , class AD_ELEMENT > void ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::unpin_surface () inline
Release the free surface so that it can move.
   {
    //Only bother if the surface is pinned
    if(Surface_pinned)
     {
      Surface_pinned = false;
      //Unpin the heights of all the spines in the middle
      unsigned n_spine = Bulk_mesh_pt->nspine();
      for(unsigned n=0;n<n_spine;n++)
       {
        Bulk_mesh_pt->spine_pt(n)->spine_height_pt()->unpin(0);
       }
      //If we on the top wall, v velocity is no longer pinned
      unsigned ibound=2;
      //Loop over the number of nodes on the boundary
      unsigned num_nod= Bulk_mesh_pt->nboundary_node(ibound);
      for (unsigned inod=0;inod<num_nod;inod++)
       {
        //Loop over the desired values stored at the nodes and unpin
        Bulk_mesh_pt->boundary_node_pt(ibound,inod)->unpin(1);
       }
      //Unfix the pressure
      unfix_pressure(0,0);
      // Loop over the elements to set up element-specific
      // and re-enable ALE
      unsigned n_element = Bulk_mesh_pt->nelement();
      for(unsigned i=0;i<n_element;i++)
       {
        // Upcast from GeneralsedElement to the present element
        ELEMENT *el_pt = dynamic_cast<ELEMENT*>(Bulk_mesh_pt->element_pt(i));
        el_pt->enable_ALE();
       }
      //Reassign the equation number
      std::cout << "Surface unpinned to give "
                << assign_eqn_numbers() << " equation numbers\n";
     }
   }
References i, and n.
Member Data Documentation
Adv_diff_mesh_pt
template<class NST_ELEMENT , class AD_ELEMENT > RectangularQuadMesh< AD_ELEMENT > * ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::Adv_diff_mesh_pt protected
Mesh of advection diffusion elements.
Bulk_mesh_pt
template<class NST_ELEMENT , class AD_ELEMENT > SingleLayerSpineMesh< ELEMENT > * ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::Bulk_mesh_pt
Mesh for the bulk fluid elements.
Overloaded version of the problem's access function to the mesh. Recasts the pointer to the base Mesh object to the actual mesh type.
Referenced by ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::ConvectionProblem().
Doc_info
template<class NST_ELEMENT , class AD_ELEMENT > DocInfo ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::Doc_info private
DocInfo object.
Referenced by ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::ConvectionProblem().
External_pressure_data_pt
template<class NST_ELEMENT , class AD_ELEMENT > Data* ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::External_pressure_data_pt private
Pointer to the external data point.
Nst_mesh_pt
template<class NST_ELEMENT , class AD_ELEMENT > RectangularQuadMesh< NST_ELEMENT > * ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::Nst_mesh_pt protected
Mesh of Navier Stokes elements.
Point_mesh_pt
template<class NST_ELEMENT , class AD_ELEMENT > Mesh* ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::Point_mesh_pt
The mesh for the element at the contact points.
Surface_mesh_pt
template<class NST_ELEMENT , class AD_ELEMENT > Mesh * ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::Surface_mesh_pt
The mesh for the interface elements.
Referenced by ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::ConvectionProblem().
Surface_pinned
template<class NST_ELEMENT , class AD_ELEMENT > bool ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::Surface_pinned private
Boolean to indicate whether the surface is pinned.
Referenced by ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::ConvectionProblem().
The documentation for this class was generated from the following files:
mpi/multi_domain/boussinesq_convection/multi_domain_boussinesq_convection.cc
boussinesq_convection.cc
dd_convection.cc
surfactant.cc
marangoni_convection.cc
marangoni_convection_box.cc
soluble_surfactant.cc