MercuryDPM: ProtectiveWall.cpp File Reference
ProtectiveWall.cpp File Reference
#include <Mercury3D.h>
#include "Species/LinearViscoelasticSpecies.h"
#include "Walls/InfiniteWall.h"
#include "Walls/IntersectionOfWalls.h"
#include "Boundaries/CubeInsertionBoundary.h"
#include "Boundaries/CubeDeletionBoundary.h"
Classes
class protectiveWall
[AT_PW:headers]
Functions
int main (int argc, char *argv[])
[AT_PW:MainClass]
Function Documentation
main()
int main (int argc , char * argv[])
[AT_PW:MainClass]
[AT_PW:Mainfunction]
[AT_PW:setUp]
[AT_PW:setUp]
 {
     //Helper
     logger(INFO,
            "Write in the terminal after the compilation'./ProtectiveWall -Np 500 -r 0.01 -h 0.1 -w 0.25 -l 1.0 -s 15.0 -t "
            "20.0' to run the program");
     int Nump = helpers::readFromCommandLine(argc, argv, "-Np", 50); //50 particles
     Mdouble pRadius = helpers::readFromCommandLine(argc, argv, "-r", 0.01); //0.01 [m]
     Mdouble height = helpers::readFromCommandLine(argc, argv, "-h", 0.1); //0.1 [m]
     Mdouble width = helpers::readFromCommandLine(argc, argv, "-w", 0.25);  //0.25 [m]
     Mdouble length = helpers::readFromCommandLine(argc, argv, "-l", 1.0); //1.0 [m]
     Mdouble slopeAngle = helpers::readFromCommandLine(argc, argv, "-s", 15.0); //15 grades
     protectiveWall problem(Nump, pRadius, height, width, length, slopeAngle); //Object
     Mdouble simTime = helpers::readFromCommandLine(argc, argv, "-t", 5.0); // 5.0 [s]
     problem.setTimeMax(simTime);
     std::string simName = helpers::readFromCommandLine(argc,argv,"-name",std::string("protectiveWall"));
     problem.setName(simName);
     problem.setSaveCount(400);
     problem.setTimeStep(0.005 / 50.0); // (collision time)/50.0
     problem.removeOldFiles();
     problem.solve();
     return 0;
 }
References Global_Physical_Variables::height(), INFO, logger, problem, helpers::readFromCommandLine(), and oomph::Global_string_for_annotation::string().