MercuryDPM: unit_cube_poisson.cc File Reference
unit_cube_poisson.cc File Reference
#include "generic.h"
#include "poisson.h"
#include "meshes/simple_cubic_mesh.h"
Classes
class UnitCubePoissonMGProblem< ELEMENT, MESH >
Namespaces
Smoother_Factory_Function_Helper
Returns a pointer to a smoother of the appropriate type.
TanhSolnForPoisson
Namespace for exact solution for Poisson equation with "sharp step".
Functions
Smoother * Smoother_Factory_Function_Helper::set_smoother ()
void TanhSolnForPoisson::get_exact_u (const Vector< double > &x, Vector< double > &u)
Exact solution as a Vector.
void TanhSolnForPoisson::get_exact_u (const Vector< double > &x, double &u)
Exact solution as a scalar.
void TanhSolnForPoisson::get_source (const Vector< double > &x, double &source)
Source function to make it an exact solution.
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc , char * argv[])
///////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////// Driver for 3D Poisson problem in a unit cube. Solution has a sharp step.
 {
  //------------------------------------
  // Sort out documentation information:
  //------------------------------------
  // Create a DocInfo object to document the solution
  DocInfo doc_info;
  // Set output directory
  doc_info.set_directory("RESLT");
  // Step number
  doc_info.number()=0;
  //--------------------
  // Set up the problem
  //--------------------
  // Using linear interpolation
  typedef RefineableQPoissonElement<3,3> ELEMENT;
  // Typedef the mesh and template it by the chosen element type
  typedef RefineableSimpleCubicMesh<ELEMENT> MESH;
  // Set the problem
  UnitCubePoissonMGProblem<ELEMENT,MESH> problem(&TanhSolnForPoisson::get_source);
  //-------------------
  // Solve the problem:
  //-------------------
  // Set the number of times to initially refine the problem. Must be at
  // least 1 otherwise the multigrid solver uses SuperLU to solve the problem
  unsigned n_refine=2;
  // Keep refining until the minimum refinement level is reached
  for (unsigned i=0;i<n_refine;i++)
  {
   // Indicate the problem is about to be refined
   oomph_info << "\n===================="
          << "Initial Refinement"
          << "====================\n"
          << std::endl;
   // Refine the problem
   problem.refine_uniformly();
  }
  // Solve the problem
  problem.newton_solve();
  // Document the solution
  problem.doc_solution(doc_info);
 } // End of main
References TanhSolnForPoisson::get_source(), i, oomph::DocInfo::number(), oomph::oomph_info, problem, and oomph::DocInfo::set_directory().