MercuryDPM: oomph::HerschelBulkleyBerEngRegConstitutiveEquation< DIM > Class Template Reference
oomph::HerschelBulkleyBerEngRegConstitutiveEquation< DIM > Class Template Reference
#include <generalised_newtonian_constitutive_models.h>
Public Member Functions
HerschelBulkleyBerEngRegConstitutiveEquation (double *yield_stress_pt, double *flow_index_pt, double *regularisation_parameter_pt)
double viscosity (const double &second_invariant_of_rate_of_strain_tensor)
double dviscosity_dinvariant (const double &second_invariant_of_rate_of_strain_tensor)
Public Member Functions inherited from oomph::GeneralisedNewtonianConstitutiveEquation< DIM >
GeneralisedNewtonianConstitutiveEquation ()
Empty constructor.
virtual ~GeneralisedNewtonianConstitutiveEquation ()
Empty virtual destructor.
Private Attributes
double * Yield_stress_pt
yield stress tau_y
double * Flow_index_pt
power law index n
double * Regularisation_parameter_pt
regularisation parameter e << 1
Detailed Description
template<unsigned DIM>
class oomph::HerschelBulkleyBerEngRegConstitutiveEquation< DIM >
A GeneralisedNewtonianConstitutiveEquation class defining a Herschel-Bulkley fluid using Bercovier and Engelman's (1980) regularisation
Constructor & Destructor Documentation
HerschelBulkleyBerEngRegConstitutiveEquation()
template<unsigned DIM> oomph::HerschelBulkleyBerEngRegConstitutiveEquation< DIM >::HerschelBulkleyBerEngRegConstitutiveEquation (double * yield_stress_pt, double * flow_index_pt, double * regularisation_parameter_pt) inline
       : GeneralisedNewtonianConstitutiveEquation<DIM>(),
         Yield_stress_pt(yield_stress_pt),
         Flow_index_pt(flow_index_pt),
         Regularisation_parameter_pt(regularisation_parameter_pt)
     {
     }
Member Function Documentation
dviscosity_dinvariant()
template<unsigned DIM> double oomph::HerschelBulkleyBerEngRegConstitutiveEquation< DIM >::dviscosity_dinvariant (const double & second_invariant_of_rate_of_strain_tensor) inline virtual
Function returning the derivative of the viscosity w.r.t. the second invariant of the rate of strain tensor For Newtonian behaviour this returns 0.0
Implements oomph::GeneralisedNewtonianConstitutiveEquation< DIM >.
     {
       // Pre-multiply the second invariant with +/-1 depending on whether it's
       // positive or not
       double sign = -1.0;
       if (second_invariant_of_rate_of_strain_tensor >= 0.0)
       {
         sign = 1.0;
       }
       // std::ostringstream error_stream;
       // error_stream << "This has not been implemented yet!";
       // throw OomphLibError(
       //  error_stream.str(),
       //  OOMPH_CURRENT_FUNCTION,
       //  OOMPH_EXCEPTION_LOCATION);
       return sign * pow(2.0, (*Flow_index_pt) - 2.0) *
                ((*Flow_index_pt) - 1.0) *
                pow(sign * second_invariant_of_rate_of_strain_tensor +
                      (*Regularisation_parameter_pt),
                    ((*Flow_index_pt) - 1.0) / 2.0 - 1.0) -
              sign * (*Yield_stress_pt) /
                (4.0 * pow(sign * second_invariant_of_rate_of_strain_tensor +
                             (*Regularisation_parameter_pt),
                           3.0 / 2.0));
     }
References oomph::HerschelBulkleyBerEngRegConstitutiveEquation< DIM >::Flow_index_pt, Eigen::bfloat16_impl::pow(), oomph::HerschelBulkleyBerEngRegConstitutiveEquation< DIM >::Regularisation_parameter_pt, and SYCL::sign().
viscosity()
template<unsigned DIM> double oomph::HerschelBulkleyBerEngRegConstitutiveEquation< DIM >::viscosity (const double & second_invariant_of_rate_of_strain_tensor) inline virtual
Function implementing the constitutive model Input: second invariant of the rate of strain Output: the viscosity For Newtonian behaviour this returns 1
Implements oomph::GeneralisedNewtonianConstitutiveEquation< DIM >.
     {
       // Pre-multiply the second invariant with +/-1 depending on whether it's
       // positive or not
       double sign = -1.0;
       if (second_invariant_of_rate_of_strain_tensor >= 0.0)
       {
         sign = 1.0;
       }
       // Calculate the square root of the absolute value of the
       // second invariant of the rate of strain tensor
       double measure_of_rate_of_strain =
         sqrt(sign * second_invariant_of_rate_of_strain_tensor +
              (*Regularisation_parameter_pt));
       return (*Yield_stress_pt) / (2.0 * measure_of_rate_of_strain) +
              pow(2.0 * measure_of_rate_of_strain, *Flow_index_pt - 1.0);
     }
References oomph::HerschelBulkleyBerEngRegConstitutiveEquation< DIM >::Flow_index_pt, Eigen::bfloat16_impl::pow(), oomph::HerschelBulkleyBerEngRegConstitutiveEquation< DIM >::Regularisation_parameter_pt, SYCL::sign(), sqrt(), and oomph::HerschelBulkleyBerEngRegConstitutiveEquation< DIM >::Yield_stress_pt.
Member Data Documentation
Flow_index_pt
template<unsigned DIM> double* oomph::HerschelBulkleyBerEngRegConstitutiveEquation< DIM >::Flow_index_pt private
power law index n
Referenced by oomph::HerschelBulkleyBerEngRegConstitutiveEquation< DIM >::dviscosity_dinvariant(), and oomph::HerschelBulkleyBerEngRegConstitutiveEquation< DIM >::viscosity().
Regularisation_parameter_pt
template<unsigned DIM> double* oomph::HerschelBulkleyBerEngRegConstitutiveEquation< DIM >::Regularisation_parameter_pt private
regularisation parameter e << 1
Referenced by oomph::HerschelBulkleyBerEngRegConstitutiveEquation< DIM >::dviscosity_dinvariant(), and oomph::HerschelBulkleyBerEngRegConstitutiveEquation< DIM >::viscosity().
Yield_stress_pt
template<unsigned DIM> double* oomph::HerschelBulkleyBerEngRegConstitutiveEquation< DIM >::Yield_stress_pt private
yield stress tau_y
Referenced by oomph::HerschelBulkleyBerEngRegConstitutiveEquation< DIM >::viscosity().
The documentation for this class was generated from the following file:
generalised_newtonian_constitutive_models.h