MercuryDPM: NewtonsCradleSelfTest.cpp File Reference
NewtonsCradleSelfTest.cpp File Reference
#include "Mercury3D.h"
#include "StatisticsVector.h"
#include "Walls/InfiniteWall.h"
#include <array>
#include <Species/LinearViscoelasticSpecies.h>
#include <CG/TimeAveragedCG.h>
Classes
class NewtonsCradleSelfTest
Functions
int main (int argc UNUSED, char *argv[] UNUSED)
Function Documentation
main()
int main (int argc UNUSED, char *argv[] UNUSED)
Todo:
TW the output of the old and new stat doesn't compare perfectly, check.
 {
     logger(INFO,"Simulating a stack of particles under gravity on a wall until it is relaxed");
     NewtonsCradleSelfTest problem;
     problem.setName("NewtonsCradleSelfTest");
     auto species=problem.speciesHandler.copyAndAddObject(LinearViscoelasticSpecies());
     problem.N=5;    //set the number of particles
     problem.removeOldFiles();
     problem.setSystemDimensions(3);
     problem.setParticleDimensions(3);
     species->setDensity(6./pi);
     problem.setGravity(Vec3D(0.,0.,-1.));
     species->setCollisionTimeAndRestitutionCoefficient(.01,.1,1.);
     problem.setTimeStep(0.0001);
     problem.setTimeMax(8.0);
     problem.setSaveCount(1000);
     problem.solve();
     Mdouble w=0.46/3.;
     logger(INFO,"\nTesting CGHandler::restartAndEvaluateDataFiles");
     Mercury3D cg;
     auto c0 = cg.cgHandler.copyAndAddObject(TimeAveragedCG<CGCoordinates::Z,CGFunctions::Gauss>());
     c0->setNZ(400);
     c0->setWidth(w);
     c0->setTimeMin(8+1e-12);
     c0->statFile.setName(problem.getName()+".fromData.stat");
     cg.cgHandler.restartAndEvaluateDataFiles("NewtonsCradleSelfTest");
     logger(INFO,"\nTesting CGHandler::restartAndEvaluateRestartFiles");
     c0->statFile.setName(problem.getName()+".fromRestart.stat");
     cg.cgHandler.restartAndEvaluateRestartFiles("NewtonsCradleSelfTest");
     helpers::writeToFile("NewtonsCradleSelfTest.gnu",
                          "p 'NewtonsCradleSelfTest.0.stat' u 2:22 w lp, 'NewtonsCradleSelfTest.stat' u 3:41 w l");
     StatisticsVector<Z> stats1("NewtonsCradleSelfTest");
     stats1.setNZ(400);
     stats1.setCGWidth(w);
     stats1.setSuperExact(false);
     stats1.setCGShape("Gaussian");
     stats1.setCGTimeMin(problem.getTimeMax()*1.00000999999);
     stats1.setTimeMaxStat(1e20);
     //stats1.statFile.setName("NewtonsCradleSelfTest.old.stat");
     logger(INFO,"Creating %",stats1.statFile.getName());
     stats1.statistics_from_fstat_and_data();
     logger(INFO,"Test StatisticsVector for different CG functions (Gauss, Heaviside, Lucy)");
     int i=0;
     std::array<std::string,3> str = {"Gaussian","HeavisideSphere","Lucy"};
     for (int i=0; i<3; i++) {
         double w=0.125;
         if (i==1) w*=2;
         if (i==2) w*=2*sqrt(3);
         StatisticsVector<Z> stats0("NewtonsCradleSelfTest");
         stats0.setZMinStat(-0.5);
         stats0.statFile.setName(stats0.getName() + "_" + str[i] + "Z.stat");
         stats0.set_h(0.02);
         stats0.verbose();
         stats0.setCGWidth(w);
         stats0.setSuperExact(true);
         stats0.setCGShape(str[i].c_str());
         stats0.setCGTimeMin(problem.getTimeMax()*.999999);
         stats0.setTimeMaxStat(1e20);
         logger(INFO,"Creating %",stats0.statFile.getName());
         stats0.statistics_from_fstat_and_data();
         StatisticsVector<XYZ> stats2("NewtonsCradleSelfTest");
         stats2.setZMinStat(-0.5);
         stats2.statFile.setName(stats2.getName() + "_" + str[i] + "XYZ.stat");
         stats2.set_h(0.02);
         stats2.setNY(1);
         stats2.setCGWidth(w);
         stats2.setSuperExact(true);
         stats2.setCGShape(str[i].c_str());
         stats2.setCGTimeMin(problem.getTimeMax()*.999999);
         stats2.setTimeMaxStat(1e20);
         logger(INFO,"Creating %",stats2.statFile.getName());
         stats2.statistics_from_fstat_and_data();
     }
     return(0);
 }
References DPMBase::cgHandler, BaseHandler< T >::copyAndAddObject(), e(), DPMBase::getName(), File::getName(), i, INFO, logger, constants::pi, problem, CGHandler::restartAndEvaluateDataFiles(), CGHandler::restartAndEvaluateRestartFiles(), StatisticsVector< T >::set_h(), StatisticsVector< T >::setCGShape(), StatisticsVector< T >::setCGTimeMin(), StatisticsVector< T >::setCGWidth(), File::setName(), StatisticsVector< T >::setNY(), StatisticsVector< T >::setNZ(), StatisticsVector< T >::setSuperExact(), StatisticsVector< T >::setTimeMaxStat(), StatisticsVector< T >::setZMinStat(), sqrt(), DPMBase::statFile, StatisticsVector< T >::statistics_from_fstat_and_data(), compute_granudrum_aor::str, StatisticsVector< T >::verbose(), w, and helpers::writeToFile().