MercuryDPM: Funnel Class Reference
Funnel Class Reference
#include <Funnel.h>
Public Member Functions
Funnel ()
This is the default constructor. All it does is set sensible defaults.
void write (std::ostream &os, bool writeAllParticles=false) const override
This function prints all funnel data in human readable format.
void read (std::istream &is, ReadOptions opt=ReadOptions::ReadAll) override
This function reads all funnel data.
void constructor ()
This is the actual constructor.
void cleanChute ()
Here we define the outflow.
void set_funnz (double funnz_)
Set funnel number of particles along the funnel heigth:
double get_funnz () const
Get the funnel number of particles along the funnel heigth:
void set_funfr (double funfr_)
Set the filling ratio.
double get_funfr () const
Get the filling ratio.
double get_funr ()
Get funnel radius:
void set_funO (double x, double y)
Set funnel origin of the funnel:
void set_funO (double *x)
const double * get_funO () const
Get funnel origin of the funnel:
double get_funOx () const
double get_funOy () const
double get_fundiag () const
double get_funrmax () const
void set_funa (double funa_)
Set funnel angle:
double get_funa () const
Get funnel angle:
double get_funH () const
Get funnel Heigth:
void set_funHf (double funHf_)
Set falling heigth:
double get_funHf () const
Get falling heigth:
void set_funD (double funD_)
Set minimum funnel diameter:
double get_funD () const
Get minimum funnel diameter:
void setName_ ()
Public Member Functions inherited from Chute
Chute ()
This is the default constructor. All it does is set sensible defaults.
Chute (const DPMBase &other)
Copy constructor, converts an existing DPMBase problem into a Chute problem.
Chute (const MercuryBase &other)
Copy constructor, converts an existing MercuryBase problem into a Chute problem.
Chute (const Mercury3D &other)
Copy constructor, converts an existing Mercury3D problem into a Chute problem.
Chute (const Chute &other)
Default copy constructor.
void constructor ()
This is the actual constructor METHOD; it is called by all constructors above (except the default copy constructor).
bool readNextArgument (int &i, int argc, char *argv[]) override
This method can be used for reading object properties from a string.
void setupSideWalls ()
Creates chute side walls (either solid or periodic)
void makeChutePeriodic ()
This makes the chute periodic in Y.
bool getIsPeriodic () const
Returns whether the chute is periodic in Y.
void setupInitialConditions () override
Creates bottom, side walls and a particle insertion boundary.
void read (std::istream &is, ReadOptions opt=ReadOptions::ReadAll) override
Reads all chute properties from an istream.
void write (std::ostream &os, bool writeAllParticles=true) const override
This function writes the Chute properties to an ostream, and adds the properties of ALL chute particles as well.
void setFixedParticleRadius (Mdouble fixedParticleRadius)
Sets the particle radius of the fixed particles which constitute the (rough) chute bottom.
Mdouble getFixedParticleRadius () const
Returns the particle radius of the fixed particles which constitute the (rough) chute bottom.
void setFixedParticleSpacing (Mdouble fixedParticleSpacing)
Sets the spacing of the fixed particles which constitute the (rough) chute bottom; used in triangular packing only.
Mdouble getFixedParticleSpacing () const
Returns the particle radius of the fixed particles which constitute the (rough) chute bottom; used in triangular packing only.
void setRoughBottomType (RoughBottomType roughBottomType)
Sets the type of rough bottom of the chute.
void setRoughBottomType (std::string roughBottomTypeString)
Sets the type of rough bottom of the chute, using a string with the EXACT enum type as input.
RoughBottomType getRoughBottomType () const
Returns the type of (rough) bottom of the chute.
void setChuteAngle (Mdouble chuteAngle)
Sets gravity vector according to chute angle (in degrees)
void setChuteAngleAndMagnitudeOfGravity (Mdouble chuteAngle, Mdouble gravity)
Sets gravity vector according to chute angle (in degrees)
Mdouble getChuteAngle () const
Returns the chute angle (in radians)
Mdouble getChuteAngleDegrees () const
Returns the chute angle (in degrees)
void setMaxFailed (unsigned int maxFailed)
Sets the number of times a particle will be tried to be added to the insertion boundary.
unsigned int getMaxFailed () const
Returns the number of times a particle will be tried to be added to the insertion boundary.
void setInflowParticleRadius (Mdouble inflowParticleRadius)
Sets the radius of the inflow particles to a single one (i.e. ensures a monodisperse inflow).
void setInflowParticleRadius (Mdouble minInflowParticleRadius, Mdouble maxInflowParticleRadius)
Sets the minimum and maximum radius of the inflow particles.
void setMinInflowParticleRadius (Mdouble minInflowParticleRadius)
sets the minimum radius of inflow particles
void setMaxInflowParticleRadius (Mdouble maxInflowParticleRadius)
Sets the maximum radius of inflow particles.
Mdouble getInflowParticleRadius () const
Returns the average radius of inflow particles.
Mdouble getMinInflowParticleRadius () const
returns the minimum radius of inflow particles
Mdouble getMaxInflowParticleRadius () const
Returns the maximum radius of inflow particles.
void setInflowHeight (Mdouble inflowHeight)
Sets maximum inflow height (Z-direction)
Mdouble getInflowHeight () const
Returns the maximum inflow height (Z-direction)
void setInflowVelocity (Mdouble inflowVelocity)
Sets the average inflow velocity.
Mdouble getInflowVelocity () const
Returns the average inflow velocity.
void setInflowVelocityVariance (Mdouble inflowVelocityVariance)
Sets the inflow velocity variance.
Mdouble getInflowVelocityVariance () const
Returns the inflow velocity variance.
void setChuteWidth (Mdouble chuteWidth)
Sets the chute width (Y-direction)
Mdouble getChuteWidth () const
Returns the chute width (Y-direction)
virtual void setChuteLength (Mdouble chuteLength)
Sets the chute length (X-direction)
Mdouble getChuteLength () const
Returns the chute length (X-direction)
void setInsertionBoundary (InsertionBoundary *insertionBoundary)
Sets the chute insertion boundary.
Public Member Functions inherited from Mercury3D
Mercury3D ()
This is the default constructor. All it does is set sensible defaults.
Mercury3D (const DPMBase &other)
Copy-constructor for creates an Mercury3D problem from an existing MD problem.
Mercury3D (const Mercury3D &other)
Copy-constructor.
void constructor ()
Function that sets the SystemDimension and ParticleDimension to 3.
std::vector< BaseParticle * > hGridFindParticleContacts (const BaseParticle *obj) override
Returns all particles that have a contact with a given particle.
Public Member Functions inherited from MercuryBase
MercuryBase ()
This is the default constructor. It sets sensible defaults.
~MercuryBase () override
This is the default destructor.
MercuryBase (const MercuryBase &mercuryBase)
Copy-constructor.
void constructor ()
This is the actual constructor, it is called do both constructors above.
void hGridActionsBeforeTimeLoop () override
This sets up the broad phase information, has to be done at this stage because it requires the particle size.
void hGridActionsBeforeTimeStep () override
Performs all necessary actions before a time-step, like updating the particles and resetting all the bucket information, etc.
void read (std::istream &is, ReadOptions opt=ReadOptions::ReadAll) override
Reads the MercuryBase from an input stream, for example a restart file.
void write (std::ostream &os, bool writeAllParticles=true) const override
Writes all data into a restart file.
Mdouble getHGridCurrentMaxRelativeDisplacement () const
Returns hGridCurrentMaxRelativeDisplacement_.
Mdouble getHGridTotalCurrentMaxRelativeDisplacement () const
Returns hGridTotalCurrentMaxRelativeDisplacement_.
void setHGridUpdateEachTimeStep (bool updateEachTimeStep)
Sets whether or not the HGrid must be updated every time step.
bool getHGridUpdateEachTimeStep () const final
Gets whether or not the HGrid is updated every time step.
void setHGridMaxLevels (unsigned int HGridMaxLevels)
Sets the maximum number of levels of the HGrid in this MercuryBase.
unsigned int getHGridMaxLevels () const
Gets the maximum number of levels of the HGrid in this MercuryBase.
HGridMethod getHGridMethod () const
Gets whether the HGrid in this MercuryBase is BOTTOMUP or TOPDOWN.
void setHGridMethod (HGridMethod hGridMethod)
Sets the HGridMethod to either BOTTOMUP or TOPDOWN.
HGridDistribution getHGridDistribution () const
Gets how the sizes of the cells of different levels are distributed.
void setHGridDistribution (HGridDistribution hGridDistribution)
Sets how the sizes of the cells of different levels are distributed.
Mdouble getHGridCellOverSizeRatio () const
Gets the ratio of the smallest cell over the smallest particle.
void setHGridCellOverSizeRatio (Mdouble cellOverSizeRatio)
Sets the ratio of the smallest cell over the smallest particle.
bool hGridNeedsRebuilding ()
Gets if the HGrid needs rebuilding before anything else happens.
virtual unsigned int getHGridTargetNumberOfBuckets () const
Gets the desired number of buckets, which is the maximum of the number of particles and 10.
virtual Mdouble getHGridTargetMinInteractionRadius () const
Gets the desired size of the smallest cells of the HGrid.
virtual Mdouble getHGridTargetMaxInteractionRadius () const
Gets the desired size of the largest cells of the HGrid.
bool checkParticleForInteraction (const BaseParticle &P) final
Checks if given BaseParticle has an interaction with a BaseWall or other BaseParticle.
bool checkParticleForInteractionLocal (const BaseParticle &P) final
Checks if the given BaseParticle has an interaction with a BaseWall or other BaseParticles in a local domain.
virtual Mdouble userHGridCellSize (unsigned int level)
Virtual function that enables inheriting classes to implement a function to let the user set the cell size of the HGrid.
void hGridInfo (std::ostream &os=std::cout) const
Writes the info of the HGrid to the screen in a nice format.
Public Member Functions inherited from DPMBase
void constructor ()
A function which initialises the member variables to default values, so that the problem can be solved off the shelf; sets up a basic two dimensional problem which can be solved off the shelf. It is called in the constructor DPMBase().
DPMBase ()
Constructor that calls the "void constructor()".
DPMBase (const DPMBase &other)
Copy constructor type-2.
virtual ~DPMBase ()
virtual destructor
void autoNumber ()
The autoNumber() function calls three functions: setRunNumber(), readRunNumberFromFile() and incrementRunNumberInFile().
std::vector< int > get1DParametersFromRunNumber (int size_x) const
This turns a counter into 1 index, which is a useful feature for performing 1D parameter study. The index run from 1:size_x, while the study number starts at 0 (initially the counter=1 in COUNTER_DONOTDEL)
std::vector< int > get2DParametersFromRunNumber (int size_x, int size_y) const
This turns a counter into 2 indices which is a very useful feature for performing a 2D study. The indices run from 1:size_x and 1:size_y, while the study number starts at 0 (initially the counter=1 in COUNTER_DONOTDEL)
std::vector< int > get3DParametersFromRunNumber (int size_x, int size_y, int size_z) const
This turns a counter into 3 indices, which is a useful feature for performing a 3D parameter study. The indices run from 1:size_x, 1:size_y and 1:size_z, while the study number starts at 0 (initially the counter=1 in COUNTER_DONOTDEL)
int launchNewRun (const char *name, bool quick=false)
This launches a code from within this code. Please pass the name of the code to run.
void setRunNumber (int runNumber)
This sets the counter/Run number, overriding the defaults.
int getRunNumber () const
This returns the current value of the counter (runNumber_)
virtual void decompose ()
Sends particles from processorId to the root processor.
void solve ()
The work horse of the code.
void initialiseSolve ()
Beginning of the solve routine, before time stepping.
void finaliseSolve ()
End of the solve routine, after time stepping.
virtual void computeOneTimeStep ()
Performs everything needed for one time step, used in the time-loop of solve().
void checkSettings ()
Checks if the essentials are set properly to go ahead with solving the problem.
void forceWriteOutputFiles ()
Writes output files immediately, even if the current time step was not meant to be written. Also resets the last saved time step.
virtual void writeOutputFiles ()
Writes simulation data to all the main Mercury files: .data, .ene, .fstat, .xballs and .restart (see the Mercury website for more details regarding these files).
void solve (int argc, char *argv[])
The work horse of the code. Can handle flags from the command line.
virtual void writeXBallsScript () const
This writes a script which can be used to load the xballs problem to display the data just generated.
virtual Mdouble getInfo (const BaseParticle &P) const
A virtual function that returns some user-specified information about a particle.
ParticleVtkWriter * getVtkWriter () const
virtual void writeRestartFile ()
Stores all the particle data for current save time step to a "restart" file, which is a file simply intended to store all the information necessary to "restart" a simulation from a given time step (see also MercuryDPM.org for more information on restart files).
void writeDataFile ()
void writeEneFile ()
void writeFStatFile ()
void fillDomainWithParticles (unsigned N=50)
bool readRestartFile (ReadOptions opt=ReadOptions::ReadAll)
Reads all the particle data corresponding to a given, existing . restart file (for more details regarding restart files, refer to the training materials on the MercuryDPM website).Returns true if it is successful, false otherwise.
int readRestartFile (std::string fileName, ReadOptions opt=ReadOptions::ReadAll)
The same as readRestartFile(bool), but also reads all the particle data corresponding to the current saved time step.
virtual BaseWall * readUserDefinedWall (const std::string &type) const
Allows you to read in a wall defined in a Driver directory; see USER/Luca/ScrewFiller.
virtual void readOld (std::istream &is)
Reads all data from a restart file, e.g. domain data and particle data; old version.
bool readDataFile (std::string fileName="", unsigned int format=0)
This allows particle data to be reloaded from data files.
bool readParAndIniFiles (std::string fileName)
Allows the user to read par.ini files (useful to read files produced by the MDCLR simulation code - external to MercuryDPM)
bool readNextDataFile (unsigned int format=0)
Reads the next data file with default format=0. However, one can modify the format based on whether the particle data corresponds to 3D or 2D data- see Visualising data in xballs.
void readNextFStatFile ()
Reads the next fstat file.
bool findNextExistingDataFile (Mdouble tMin, bool verbose=true)
Finds and opens the next data file, if such a file exists.
bool readArguments (int argc, char *argv[])
Can interpret main function input arguments that are passed by the driver codes.
bool checkParticleForInteractionLocalPeriodic (const BaseParticle &P)
void readSpeciesFromDataFile (bool read=true)
void importParticlesAs (ParticleHandler &particleHandler, InteractionHandler &interactionHandler, const ParticleSpecies *species)
Copies particles, interactions assigning species from a local simulation to a global one. Useful for the creation of a cluster.
MERCURYDPM_DEPRECATED File & getDataFile ()
The non const version. Allows one to edit the File::dataFile.
MERCURYDPM_DEPRECATED File & getEneFile ()
The non const version. Allows to edit the File::eneFile.
MERCURYDPM_DEPRECATED File & getFStatFile ()
The non const version. Allows to edit the File::fStatFile.
MERCURYDPM_DEPRECATED File & getRestartFile ()
The non const version. Allows to edit the File::restartFile.
MERCURYDPM_DEPRECATED File & getStatFile ()
The non const version. Allows to edit the File::statFile.
File & getInteractionFile ()
Return a reference to the file InteractionsFile.
MERCURYDPM_DEPRECATED const File & getDataFile () const
The const version. Does not allow for any editing of the File::dataFile.
MERCURYDPM_DEPRECATED const File & getEneFile () const
The const version. Does not allow for any editing of the File::eneFile.
MERCURYDPM_DEPRECATED const File & getFStatFile () const
The const version. Does not allow for any editing of the File::fStatFile.
MERCURYDPM_DEPRECATED const File & getRestartFile () const
The const version. Does not allow for any editing of the File::restartFile.
MERCURYDPM_DEPRECATED const File & getStatFile () const
The const version. Does not allow for any editing of the File::statFile.
const File & getInteractionFile () const
Returns a constant reference to an Interactions file.
const std::string & getName () const
Returns the name of the file. Does not allow to change it though.
void setName (const std::string &name)
Allows to set the name of all the files (ene, data, fstat, restart, stat)
void setName (const char *name)
Calls setName(std::string)
void setSaveCount (unsigned int saveCount)
Sets File::saveCount_ for all files (ene, data, fstat, restart, stat)
void setFileType (FileType fileType)
Sets File::fileType_ for all files (ene, data, fstat, restart, stat)
void setOpenMode (std::fstream::openmode openMode)
Sets File::openMode_ for all files (ene, data, fstat, restart, stat)
void resetFileCounter ()
Resets the file counter for each file i.e. for ene, data, fstat, restart, stat)
void closeFiles ()
Closes all files (ene, data, fstat, restart, stat) that were opened to read or write.
void setVTKOutputDirectory (const std::string &dir)
Sets the output directory of the VTK files.
void setLastSavedTimeStep (unsigned int nextSavedTimeStep)
Sets the next time step for all the files (ene, data, fstat, restart, stat) at which the data is to be written or saved.
Mdouble getTime () const
Returns the current simulation time.
Mdouble getNextTime () const
Returns the current simulation time.
unsigned int getNumberOfTimeSteps () const
Returns the current counter of time-steps, i.e. the number of time-steps that the simulation has undergone so far.
void setTime (Mdouble time)
Sets a new value for the current simulation time.
void setTimeMax (Mdouble newTMax)
Sets a new value for the maximum simulation duration.
Mdouble getTimeMax () const
Returns the maximum simulation duration.
void setLogarithmicSaveCount (Mdouble logarithmicSaveCountBase)
Sets File::logarithmicSaveCount_ for all files (ene, data, fstat, restart, stat)
void setNToWrite (int nToWrite)
set the number of elements to write to the screen
int getNToWrite () const
get the number of elements to write to the
void setRotation (bool rotation)
Sets whether particle rotation is enabled or disabled.
bool getRotation () const
Indicates whether particle rotation is enabled or disabled.
MERCURYDPM_DEPRECATED void setWallsWriteVTK (FileType writeWallsVTK)
Sets whether walls are written into a VTK file.
MERCURYDPM_DEPRECATED void setWallsWriteVTK (bool)
Sets whether walls are written into a VTK file.
MERCURYDPM_DEPRECATED void setInteractionsWriteVTK (bool)
Sets whether interactions are written into a VTK file.
void setParticlesWriteVTK (bool writeParticlesVTK)
Sets whether particles are written in a VTK file.
void setSuperquadricParticlesWriteVTK (bool writeSuperquadricParticlesVTK)
MERCURYDPM_DEPRECATED FileType getWallsWriteVTK () const
Returns whether walls are written in a VTK file.
bool getParticlesWriteVTK () const
Returns whether particles are written in a VTK file.
bool getSuperquadricParticlesWriteVTK () const
Mdouble getXMin () const
If the length of the problem domain in x-direction is XMax - XMin, then getXMin() returns XMin.
Mdouble getXMax () const
If the length of the problem domain in x-direction is XMax - XMin, then getXMax() returns XMax.
Mdouble getYMin () const
If the length of the problem domain in y-direction is YMax - YMin, then getYMin() returns YMin.
Mdouble getYMax () const
If the length of the problem domain in y-direction is YMax - YMin, then getYMax() returns XMax.
Mdouble getZMin () const
If the length of the problem domain in z-direction is ZMax - ZMin, then getZMin() returns ZMin.
Mdouble getZMax () const
If the length of the problem domain in z-direction is ZMax - ZMin, then getZMax() returns ZMax.
Mdouble getXCenter () const
Mdouble getYCenter () const
Mdouble getZCenter () const
Vec3D getCenter () const
get center of domain
Vec3D getMin () const
Returns the minimum coordinates of the problem domain.
Vec3D getMax () const
Returns the maximum coordinates of the problem domain.
void setXMin (Mdouble newXMin)
Sets the value of XMin, the lower bound of the problem domain in the x-direction.
void setYMin (Mdouble newYMin)
Sets the value of YMin, the lower bound of the problem domain in the y-direction.
void setZMin (Mdouble newZMin)
Sets the value of ZMin, the lower bound of the problem domain in the z-direction.
void setXMax (Mdouble newXMax)
Sets the value of XMax, the upper bound of the problem domain in the x-direction.
void setYMax (Mdouble newYMax)
Sets the value of YMax, the upper bound of the problem domain in the y-direction.
void setZMax (Mdouble newZMax)
Sets the value of ZMax, the upper bound of the problem domain in the z-direction.
void setMax (const Vec3D &max)
Sets the maximum coordinates of the problem domain.
void setMax (Mdouble, Mdouble, Mdouble)
Sets the maximum coordinates of the problem domain.
void setDomain (const Vec3D &min, const Vec3D &max)
Sets the minimum coordinates of the problem domain.
void setMin (const Vec3D &min)
Sets the minimum coordinates of the problem domain.
void setMin (Mdouble, Mdouble, Mdouble)
Sets the minimum coordinates of the problem domain.
void setTimeStep (Mdouble newDt)
Sets a new value for the simulation time step.
Mdouble getTimeStep () const
Returns the simulation time step.
void setNumberOfOMPThreads (int numberOfOMPThreads)
Sets the number of omp threads.
int getNumberOfOMPThreads () const
Returns the number of omp threads.
void setXBallsColourMode (int newCMode)
Set the xballs output mode.
int getXBallsColourMode () const
Get the xballs colour mode (CMode).
void setXBallsVectorScale (double newVScale)
Set the scale of vectors in xballs.
double getXBallsVectorScale () const
Returns the scale of vectors used in xballs.
void setXBallsAdditionalArguments (std::string newXBArgs)
Set the additional arguments for xballs.
std::string getXBallsAdditionalArguments () const
Returns the additional arguments for xballs.
void setXBallsScale (Mdouble newScale)
Sets the scale of the view (either normal, zoom in or zoom out) to display in xballs. The default is fit to screen.
double getXBallsScale () const
Returns the scale of the view in xballs.
void setGravity (Vec3D newGravity)
Sets a new value for the gravitational acceleration.
Vec3D getGravity () const
Returns the gravitational acceleration.
void setBackgroundDrag (Mdouble backgroundDrag)
Simple access function to turn on a background drag. The force of particleVelocity*drag is applied (note, it allowed to be negative i.e. create energy)
const Mdouble getBackgroundDrag () const
Return the background drag.
void setDimension (unsigned int newDim)
Sets both the system dimensions and the particle dimensionality.
void setSystemDimensions (unsigned int newDim)
Sets the system dimensionality.
unsigned int getSystemDimensions () const
Returns the system dimensionality.
void setParticleDimensions (unsigned int particleDimensions)
Sets the particle dimensionality.
unsigned int getParticleDimensions () const
Returns the particle dimensionality.
std::string getRestartVersion () const
This is to take into account for different Mercury versions. Returns the version of the restart file.
void setRestartVersion (std::string newRV)
Sets restart_version.
bool getRestarted () const
Returns the flag denoting if the simulation was restarted or not.
void setRestarted (bool newRestartedFlag)
Allows to set the flag stating if the simulation is to be restarted or not.
bool getAppend () const
Returns whether the "append" option is on or off.
void setAppend (bool newAppendFlag)
Sets whether the "append" option is on or off.
Mdouble getElasticEnergy () const
Returns the global elastic energy within the system.
Mdouble getKineticEnergy () const
Returns the global kinetic energy stored in the system.
Mdouble getGravitationalEnergy (Vec3D origin={0, 0, 0}) const
Returns the global gravitational potential energy stored relative to a user-defined origin in the system. Note, if no origin is specified the real origin i.e. (0,0,0) is taken.
Mdouble getRotationalEnergy () const
Returns the global rotational energy stored in the system.
Mdouble getTotalEnergy () const
Mdouble getTotalMass () const
JMFT: Return the total mass of the system, excluding fixed particles.
Vec3D getCentreOfMass () const
JMFT: Return the centre of mass of the system, excluding fixed particles.
Vec3D getTotalMomentum () const
JMFT: Return the total momentum of the system, excluding fixed particles.
double getCPUTime ()
double getWallTime ()
virtual void hGridInsertParticle (BaseParticle *obj UNUSED)
virtual void hGridUpdateParticle (BaseParticle *obj UNUSED)
virtual void hGridRemoveParticle (BaseParticle *obj UNUSED)
bool mpiIsInCommunicationZone (BaseParticle *particle)
Checks if the position of the particle is in an mpi communication zone or not.
bool mpiInsertParticleCheck (BaseParticle *P)
Function that checks if the mpi particle should really be inserted by the current domain.
void insertGhostParticle (BaseParticle *P)
This function inserts a particle in the mpi communication boundaries.
void updateGhostGrid (BaseParticle *P)
Checks if the Domain/periodic interaction distance needs to be updated and updates it accordingly.
virtual void gatherContactStatistics (unsigned int index1, int index2, Vec3D Contact, Mdouble delta, Mdouble ctheta, Mdouble fdotn, Mdouble fdott, Vec3D P1_P2_normal_, Vec3D P1_P2_tangential)
//Not unsigned index because of possible wall collisions.
void setNumberOfDomains (std::vector< unsigned > direction)
Sets the number of domains in x-,y- and z-direction. Required for parallel computations.
void splitDomain (DomainSplit domainSplit)
std::vector< unsigned > getNumberOfDomains ()
returns the number of domains
Domain * getCurrentDomain ()
Function that returns a pointer to the domain corresponding to the processor.
void removeOldFiles () const
void setMeanVelocity (Vec3D V_mean_goal)
This function will help you set a fixed kinetic energy and mean velocity in your system.
void setMeanVelocityAndKineticEnergy (Vec3D V_mean_goal, Mdouble Ek_goal)
This function will help you set a fixed kinetic energy and mean velocity in your system.
Mdouble getTotalVolume () const
Get the total volume of the cuboid system.
Matrix3D getKineticStress () const
Calculate the kinetic stress tensor in the system averaged over the whole volume.
Matrix3D getStaticStress () const
Calculate the static stress tensor in the system averaged over the whole volume.
Matrix3D getTotalStress () const
Calculate the total stress tensor in the system averaged over the whole volume.
virtual void handleParticleRemoval (unsigned int id)
Handles the removal of particles from the particleHandler.
virtual void handleParticleAddition (unsigned int id, BaseParticle *p)
Handles the addition of particles to the particleHandler.
void writePythonFileForVTKVisualisation () const
writes .py file for ParaView
void setWritePythonFileForVTKVisualisation (bool forceWritePythonFileForVTKVisualisation)
bool getWritePythonFileForVTKVisualisation () const
WallVTKWriter & getWallVTKWriter ()
Protected Member Functions
void set_funH (double funH_)
Set funnel Heigth:
void set_funrmax (double funrmax_)
void set_fundiag (double fundiag_)
void set_funr (double funr_)
Set funnel radius:
virtual void setupInitialConditions () override
initialise particle position, velocity, radius
virtual void create_inflow_particle ()
Sets variable values for particles that are created at the inflow.
virtual void create_funnel ()
Create the funnel.
virtual void update_funnel ()
Updates the parameters for the funnel;.
virtual void check_funnel ()
Check the funnel parameters.
virtual void create_walls ()
Create or update the walls.
virtual bool readNextArgument (int &i, int argc, char *argv[]) override
Interprets the i^th command-line argument.
Protected Member Functions inherited from Chute
void actionsBeforeTimeStep () override
Calls Chute::cleanChute().
void cleanChute ()
Deletes all outflow particles once every 100 time steps.
virtual void createBottom ()
Creates the chute bottom, which can be either flat or one of three flavours of rough.
virtual void addFlowParticlesCompactly ()
Add initial flow particles in a dense packing.
virtual SphericalParticle createFlowParticle ()
void printTime () const override
prints time, max time and number of particles
Protected Member Functions inherited from Mercury3D
void hGridFindContactsWithinTargetCell (int x, int y, int z, unsigned int l)
Finds contacts between particles in the target cell.
void hGridFindContactsWithTargetCell (int x, int y, int z, unsigned int l, BaseParticle *obj)
Finds contacts between the BaseParticle and the target cell.
void computeWallForces (BaseWall *w) override
Compute contacts with a wall.
void hGridFindParticlesWithTargetCell (int x, int y, int z, unsigned int l, BaseParticle *obj, std::vector< BaseParticle * > &list)
Finds particles within target cell and stores them in a list.
void hGridGetInteractingParticleList (BaseParticle *obj, std::vector< BaseParticle * > &list) override
Obtains all neighbour particles of a given object, obtained from the hgrid.
void computeInternalForces (BaseParticle *obj) override
Finds contacts with the BaseParticle; avoids multiple checks.
bool hGridHasContactsInTargetCell (int x, int y, int z, unsigned int l, const BaseParticle *obj) const
Tests if the BaseParticle has contacts with other Particles in the target cell.
bool hGridHasParticleContacts (const BaseParticle *obj) override
Tests if a BaseParticle has any contacts in the HGrid.
void hGridRemoveParticle (BaseParticle *obj) override
Removes a BaseParticle from the HGrid.
void hGridUpdateParticle (BaseParticle *obj) override
Updates the cell (not the level) of a BaseParticle.
Protected Member Functions inherited from MercuryBase
void hGridRebuild ()
This sets up the parameters required for the contact model.
void hGridInsertParticle (BaseParticle *obj) final
Inserts a single Particle to current grid.
void hGridUpdateMove (BaseParticle *iP, Mdouble move) final
Computes the relative displacement of the given BaseParticle and updates the currentMaxRelativeDisplacement_ accordingly.
void hGridActionsBeforeIntegration () override
Resets the currentMaxRelativeDisplacement_ to 0.
void hGridActionsAfterIntegration () override
This function has to be called before integrateBeforeForceComputation.
HGrid * getHGrid ()
Gets the HGrid used by this problem.
const HGrid * getHGrid () const
Gets the HGrid used by this problem, const version.
bool readNextArgument (int &i, int argc, char *argv[]) override
Reads the next command line argument.
Protected Member Functions inherited from DPMBase
virtual void computeAllForces ()
Computes all the forces acting on the particles using the BaseInteractable::setForce() and BaseInteractable::setTorque()
virtual void computeInternalForce (BaseParticle *, BaseParticle *)
Computes the forces between two particles (internal in the sense that the sum over all these forces is zero i.e. fully modelled forces)
virtual void computeExternalForces (BaseParticle *)
Computes the external forces, such as gravity, acting on particles.
virtual void computeForcesDueToWalls (BaseParticle *, BaseWall *)
Computes the forces on the particles due to the walls (normals are outward normals)
virtual void actionsOnRestart ()
A virtual function where the users can add extra code which is executed only when the code is restarted.
virtual void actionsBeforeTimeLoop ()
A virtual function. Allows one to carry out any operations before the start of the time loop.
virtual void computeAdditionalForces ()
A virtual function which allows to define operations to be executed prior to the OMP force collect.
virtual void actionsAfterSolve ()
A virtual function which allows to define operations to be executed after the solve().
virtual void actionsAfterTimeStep ()
A virtual function which allows to define operations to be executed after time step.
void writeVTKFiles () const
virtual void outputXBallsData (std::ostream &os) const
This function writes the location of the walls and particles in a format the XBalls program can read. For more information on the XBalls program, see Visualising data in xballs.
virtual void outputXBallsDataParticle (unsigned int i, unsigned int format, std::ostream &os) const
This function writes out the particle locations into an output stream in a format the XBalls program can read. For more information on the XBalls program, see Visualising data in xballs.
virtual void writeEneHeader (std::ostream &os) const
Writes a header with a certain format for ENE file.
virtual void writeFstatHeader (std::ostream &os) const
Writes a header with a certain format for FStat file.
virtual void writeEneTimeStep (std::ostream &os) const
Write the global kinetic, potential energy, etc. in the system.
virtual void initialiseStatistics ()
virtual void outputStatistics ()
void gatherContactStatistics ()
virtual void processStatistics (bool)
virtual void finishStatistics ()
virtual void integrateBeforeForceComputation ()
Update particles' and walls' positions and velocities before force computation.
virtual void integrateAfterForceComputation ()
Update particles' and walls' positions and velocities after force computation.
virtual void checkInteractionWithBoundaries ()
There are a range of boundaries one could implement depending on ones' problem. This methods checks for interactions between particles and such range of boundaries. See BaseBoundary.h and all the boundaries in the Boundaries folder.
void setFixedParticles (unsigned int n)
Sets a number, n, of particles in the particleHandler as "fixed particles".
virtual bool continueSolve () const
A virtual function for deciding whether to continue the simulation, based on a user-specified criterion.
void outputInteractionDetails () const
Displays the interaction details corresponding to the pointer objects in the interaction handler.
bool isTimeEqualTo (Mdouble time) const
Checks whether the input variable "time" is the current time in the simulation.
void removeDuplicatePeriodicParticles ()
Removes periodic duplicate Particles.
void checkAndDuplicatePeriodicParticles ()
For simulations using periodic boundaries, checks and adds particles when necessary into the particle handler. See DPMBase.cc and PeriodicBoundary.cc for more details.
void performGhostParticleUpdate ()
When the Verlet scheme updates the positions and velocities of particles, ghost particles will need an update as wel. Their status will also be updated accordingly.
void deleteGhostParticles (std::set< BaseParticle * > &particlesToBeDeleted)
void synchroniseParticle (BaseParticle *, unsigned fromProcessor=0)
void performGhostVelocityUpdate ()
updates the final time-step velocity of the ghost particles
void disableSoftStop ()
This prevents the initialisation of the soft stop feature.
void discontinueSolve ()
This discontinues the solve loop after the current time step is finished.
Protected Attributes
SphericalParticle inflowParticle_
double funr
double funO [2]
double funa
double funH
double funHf
double funD
double funnz
double funfr
double fundiag
double funrmax
Additional Inherited Members
Public Types inherited from DPMBase
enum class ReadOptions : int { ReadAll , ReadNoInteractions , ReadNoParticlesAndInteractions }
enum class DomainSplit {
X , Y , Z , XY ,
XZ , YZ , XYZ
}
Static Public Member Functions inherited from DPMBase
static void incrementRunNumberInFile ()
Increment the run Number (counter value) stored in the file_counter (COUNTER_DONOTDEL) by 1 and store the new value in the counter file.
static int readRunNumberFromFile ()
Read the run number or the counter from the counter file (COUNTER_DONOTDEL)
static bool areInContact (const BaseParticle *pI, const BaseParticle *pJ)
Checks if two particle are in contact or is there any positive overlap.
Public Attributes inherited from DPMBase
SpeciesHandler speciesHandler
A handler to that stores the species type i.e. LinearViscoelasticSpecies, etc.
RNG random
This is a random generator, often used for setting up the initial conditions etc...
ParticleHandler particleHandler
An object of the class ParticleHandler, contains the pointers to all the particles created.
ParticleHandler paoloParticleHandler
Fake particleHandler created by Paolo needed temporary by just Paolo.
WallHandler wallHandler
An object of the class WallHandler. Contains pointers to all the walls created.
BoundaryHandler boundaryHandler
An object of the class BoundaryHandler which concerns insertion and deletion of particles into or from regions.
PeriodicBoundaryHandler periodicBoundaryHandler
Internal handler that deals with periodic boundaries, especially in a parallel build.
DomainHandler domainHandler
An object of the class DomainHandler which deals with parallel code.
InteractionHandler interactionHandler
An object of the class InteractionHandler.
CGHandler cgHandler
Object of the class cgHandler.
File dataFile
An instance of class File to handle in- and output into a .data file.
File fStatFile
An instance of class File to handle in- and output into a .fstat file.
File eneFile
An instance of class File to handle in- and output into a .ene file.
File restartFile
An instance of class File to handle in- and output into a .restart file.
File statFile
An instance of class File to handle in- and output into a .stat file.
File interactionFile
File class to handle in- and output into .interactions file. This file hold information about interactions.
Time clock_
record when the simulation started
Detailed Description
Funnel adds a funnel to the Chute class. Parameters needed are:
The number of particles along the sidewall of the funnel
The angle in which the funnel grows
The diameter at the bottom of the funnel
The origin of the funnel: (x,y) coordinates of the middlepoint of the circle
The falling height from the bottom wall
The filling ratio of the funnel, in which (0.0-1.0) range should the funnel be filled
Constructor & Destructor Documentation
Funnel()
Funnel::Funnel () inline
This is the default constructor. All it does is set sensible defaults.
 {constructor();}
References constructor().
Member Function Documentation
check_funnel()
void Funnel::check_funnel () protected virtual
Check the funnel parameters.
Checks the funnel with the boundaries (xmin,xmax, ymin or ymax)s ///.
 {
     //Call update_funnel to initiate funr
     update_funnel();
     //Check parameters and reinitialise if needed
     if ((get_funr() + get_funOx()) > getXMax())
     {
         double oldxmax = getXMax();
         setXMax(get_funr() + get_funOx());
         logger(WARN, "Funnel did not fit in boundaries, changed xmax from % to %", oldxmax, getXMax());
     }
     if ((get_funOx() - get_funr()) < getXMin())
     {
         double oldxmin = getXMin();
         setXMin(get_funOx() - get_funr());
         logger(WARN, "Funnel did not fit in boundaries, changed xmin from % to %", oldxmin, getXMin());
     }
     if ((get_funOy() + get_funr()) > getYMax())
     {
         double oldymax = getYMax();
         setYMax(get_funOy() + get_funr());
         logger(WARN, "Funnel did not fit in boundaries, changed ymax from % to %", oldymax, getYMax());
     }
     if ((get_funOy() - get_funr()) < getYMin())
     {
         double oldymin = getYMin();
         setYMin(get_funOy() - get_funr());
         logger(WARN, "Funnel did not fit in boundaries, changed ymin from % to %", oldymin, getYMin());
     }
     update_funnel();
 }
References get_funOx(), get_funOy(), get_funr(), DPMBase::getXMax(), DPMBase::getXMin(), DPMBase::getYMax(), DPMBase::getYMin(), logger, DPMBase::setXMax(), DPMBase::setXMin(), DPMBase::setYMax(), DPMBase::setYMin(), update_funnel(), and WARN.
Referenced by setupInitialConditions().
cleanChute()
void Funnel::cleanChute ()
Here we define the outflow.
Removes particles which left the x-y domain///.
 {
     //clean outflow every 100 time steps
     static int count = 0, maxcount = 100;
     if (count > maxcount)
     {
         count = 0;
         // delete all outflowing particles
         for (unsigned int i = 0; i < particleHandler.getNumberOfObjects();)
         {
             //if (Particles[i].get_Position().X>getXMax()||Particles[i].get_Position().X<getXMin()||Particles[i].get_Position().Y<getYMin()||Particles[i].get_Position().Y>getYMax()||Particles[i].get_Position().Z+Particles[i].Radius<-getZMax())
             if (particleHandler.getObject(i)->getPosition().Z + 10 * particleHandler.getObject(i)->getRadius() < getZMin())
             {
 #ifdef DEBUG_OUTPUT_FULL
                 std::cout << "erased:" << particleHandler.getObject(i) << std::endl;
 #endif
                 particleHandler.removeObject(i);
             }
             else
                 i++;
         }
     }
     else
         count++;
 }
References ParticleHandler::getNumberOfObjects(), BaseHandler< T >::getObject(), BaseInteractable::getPosition(), BaseParticle::getRadius(), DPMBase::getZMin(), i, DPMBase::particleHandler, ParticleHandler::removeObject(), and Vec3D::Z.
constructor()
void Funnel::constructor ()
This is the actual constructor.
This is the actually constructor it is called do both constructors above.
 {
     set_funH(0);
     set_funnz(0);
     set_funa(0);
     set_funfr(0.33);
 }
References set_funa(), set_funfr(), set_funH(), and set_funnz().
Referenced by Funnel().
create_funnel()
void Funnel::create_funnel () protected virtual
Create the funnel.
Creates the funnel; based on particles ///.
 {
     // Define standard fixed particle
     SphericalParticle F0;
     F0.setRadius(getFixedParticleRadius());
     F0.setPosition(Vec3D(0., 0., 0.));
     const double* funh_ = get_funO();
     double zc = Chute::getInflowHeight() - F0.getRadius();
     bool isdone;
     int layercount = 0;
     if (get_funH() <= getFixedParticleRadius())
     {
         isdone = true;
     }
     else
     {
         isdone = false;
     }
     while (!isdone)
     {
         layercount++;
 #ifdef DEBUG_OUTPUT
         cout<< "Current layer in Funnel creation = " << layercount << endl;
 #endif
         //Current radius of the funnel
         //double funr_=get_funr()-(Chute::getInflowHeight()-zc+F0.Radius)*sin(get_funa())+F0.Radius;
         double funr_ = 1.0 / 2.0 * funD + ((funnz - layercount) * sin(funa)) * 2 * getFixedParticleRadius() + getFixedParticleRadius();
         //Calculate the # of particles in current circle:
         int nc = ceil((constants::pi * funr_) / (F0.getRadius()));
         double dth = 2 * constants::pi / nc; // angle increment.
         double Xo;
         Vec3D position;
         //Loop over those particles
         for (int i = 0; i < nc; i++)
         {
             //Create particles in a circle at certain height zc:
             position.X = funh_[0] + funr_ * cos(i * dth);
             position.Y = funh_[1] + funr_ * sin(i * dth);
             position.Z = zc;
             F0.setPosition(position);
             //Apply ChuteAngle rotation:
             //1) Determine the X distance from the current particle to the origin of the funnel
             Xo = F0.getPosition().X - get_funOx();
             //2) Recalculate X: Origin  + Lifting of a particle      + Moving of the origin
             //F0.getPosition().X = get_funOx() + Xo * cos(getChuteAngle()) + (getInflowHeight()-F0.getPosition().Z)*sin(getChuteAngle());
             position.X = get_funOx() + Xo * cos(getChuteAngle()) + (getInflowHeight() - F0.getPosition().Z) * sin(getChuteAngle());
             //3) Recalculate Z: Original Z+ Lifting of a particle
             //F0.getPosition().Z = F0.getPosition().Z + Xo * sin(getChuteAngle());
             position.Z = F0.getPosition().Z + Xo * sin(getChuteAngle());
             F0.setPosition(position);
             particleHandler.copyAndAddObject(F0);
             //cc++;
         }
         if (zc < (Chute::getInflowHeight() - get_funH()) + getFixedParticleRadius())
         {
             logger(INFO, "Lst funr_ = % with zc = %", funr_, zc);
             isdone = true;
         }
         if (funr_ <= (1.0 / 2.0 * get_funD()))
         {
             logger(INFO, "Lst funr_ = %\n", Flusher::NO_FLUSH, funr_);
             funr_ = 1.0 / 2.0 * get_funD() + 2.0 * F0.getRadius();
             logger(WARN, "Warning: Funnel is closing! ");
             isdone = true;
         }
         zc -= 2 * F0.getRadius() * cos(get_funa());
     }
     //set_Nmax(particleHandler.getNumberOfObjects());
     //finally, fix particles to the floor
     for (std::vector<BaseParticle*>::iterator it = particleHandler.begin(); it != particleHandler.end(); ++it)
         (*it)->fixParticle();
 #ifdef DEBUG_OUTPUT
     //Print funnel info to console:
     logger(INFO, "Current zmax = %"
     "\nCurrent inflowheight = %"
     "\nFunnel D = %"
     "\nFunnel R = %"
     "\nFunnel A = %"
     "\nFunnel HF = %"
     "\nFunnel H = %"
     "\nFunnel rmax = %"
     "\nFunnel diag = %"
     "\nFunnel fr = %"
     "\nFunnel Oy = %"
     "\nFunnel Ox = %"
     "\nCurrent number of particles = %", getZMax(), Chute::getInflowHeight(), get_funD(), get_funr(), get_funa()
     /constants::pi*180, get_funHf(), get_funH(), get_funrmax(), get_fundiag(), get_funfr(), get_funOy(), get_funOx(),
     get_NmaxR());
 #endif
 }
References BaseHandler< T >::begin(), Eigen::bfloat16_impl::ceil(), BaseHandler< T >::copyAndAddObject(), cos(), BaseHandler< T >::end(), funa, funD, funnz, get_funa(), get_funD(), get_fundiag(), get_funfr(), get_funH(), get_funHf(), get_funO(), get_funOx(), get_funOy(), get_funr(), get_funrmax(), Chute::getChuteAngle(), Chute::getFixedParticleRadius(), Chute::getInflowHeight(), BaseInteractable::getPosition(), BaseParticle::getRadius(), DPMBase::getZMax(), i, INFO, logger, NO_FLUSH, DPMBase::particleHandler, constants::pi, BaseInteractable::setPosition(), BaseParticle::setRadius(), sin(), WARN, Vec3D::X, Vec3D::Y, and Vec3D::Z.
Referenced by setupInitialConditions().
create_inflow_particle()
void Funnel::create_inflow_particle () protected virtual
Sets variable values for particles that are created at the inflow.
Bug:
This can no longer be called. Some one should check with Ruud's thesis what the density should be
 {
     //cout <<" void Funnel::create_inflow_particle()"<<endl;
  inflowParticle_.setRadius(random.getRandomNumber(getMinInflowParticleRadius(), getMaxInflowParticleRadius()));
     //    inflowParticle_.computeMass();
     Vec3D position, velocity;
     position.Z = random.getRandomNumber(Chute::getInflowHeight() - cos(get_funa()) * get_fundiag(), Chute::getInflowHeight());
     position.Y = random.getRandomNumber(get_funOy() - get_funrmax(), get_funOy() + get_funrmax());
     //P0.getPosition().Z=random.get_RN(Chute::getInflowHeight()-cos(get_funa())*get_fundiag(),Chute::getInflowHeight()); // Generate an Z value from the lower bound up to zmax
 //  P0.getPosition().Y=random.get_RN(get_funOy()-get_funrmax(),get_funOy()+get_funrmax()); // Generate an Y value in the diameter range of the funnel.
     double funb = acos((inflowParticle_.getPosition().Y - get_funOy()) / get_funrmax()); // Determine the angle beta which the Y value makes with respect to the origin in the XY plane
     position.X = random.getRandomNumber(get_funOx() - sin(funb) * get_funrmax(), get_funOx() + sin(funb) * get_funrmax());
     //  P0.getPosition().X=random.get_RN(get_funOx()-sin(funb)*get_funrmax(),get_funOx()+sin(funb)*get_funrmax()); // Generate an X value on a distance smaller then Y from the origin.
     inflowParticle_.setPosition(position);
     //Apply ChuteAngle rotation:
     //1) Determine the X distance from the current particle to the origin of the funnel
     double Xo = inflowParticle_.getPosition().X - get_funOx();
     //2) Recalculate X: Origin  + Lifting of a particle      + Moving of the origin
     //P0.getPosition().X = get_funOx() + Xo * cos(getChuteAngle()) + (getInflowHeight()-P0.getPosition().Z)*sin(getChuteAngle());
     position.X = random.getRandomNumber(get_funOx() - sin(funb) * get_funrmax(), get_funOx() + sin(funb) * get_funrmax());
     //3) Recalculate Z: Original Z+ Lifting of a particle
     //P0.getPosition().Z = P0.getPosition().Z + Xo * sin(getChuteAngle());
     position.Z = inflowParticle_.getPosition().Z + Xo * sin(getChuteAngle());
     inflowParticle_.setPosition(position);
     velocity.X = getInflowVelocity() * random.getRandomNumber(-getInflowVelocityVariance(), getInflowVelocityVariance()) + getInflowVelocity();
     velocity.Y = getInflowVelocity() * random.getRandomNumber(-getInflowVelocityVariance(), getInflowVelocityVariance());
     velocity.Z = getInflowVelocity() * random.getRandomNumber(-getInflowVelocityVariance(), getInflowVelocityVariance());
     inflowParticle_.setVelocity(velocity);
     //P0.getVelocity().X = InflowVelocity * random.get_RN(-InflowVelocityVariance,InflowVelocityVariance) + InflowVelocity;
     //P0.getVelocity().Y = InflowVelocity * random.get_RN(-InflowVelocityVariance,InflowVelocityVariance);
     //P0.getVelocity().Z = InflowVelocity * random.get_RN(-InflowVelocityVariance,InflowVelocityVariance);
 }
References acos(), cos(), get_funa(), get_fundiag(), get_funOx(), get_funOy(), get_funrmax(), Chute::getChuteAngle(), Chute::getInflowHeight(), Chute::getInflowVelocity(), Chute::getInflowVelocityVariance(), Chute::getMaxInflowParticleRadius(), Chute::getMinInflowParticleRadius(), BaseInteractable::getPosition(), RNG::getRandomNumber(), inflowParticle_, DPMBase::random, BaseInteractable::setPosition(), BaseParticle::setRadius(), BaseInteractable::setVelocity(), sin(), Jeffery_Solution::velocity(), Vec3D::X, Vec3D::Y, and Vec3D::Z.
create_walls()
void Funnel::create_walls () protected virtual
Create or update the walls.
Creates or updates the wall according to the boundaries (xmin,xmax, ymin or ymax)s ///.
 {
     //set side walls - solid if not a periodic
     if (Chute::getIsPeriodic())
     {
         PeriodicBoundary b0;
         b0.set(Vec3D(0.0, 1.0, 0.0), getYMin(), getYMax());
         boundaryHandler.copyAndAddObject(b0);
         //set_NWallPeriodic(1);
         wallHandler.clear(); //set_NWall(0);
         //WallsPeriodic[0].set(Vec3D( 0.0, 1.0, 0.0), getYMin(), getYMax());
     }
     //SIDE WALLS: REMOVED, clean chute should be updated to clean sidewalls to (nov 28)
     else
     {
         //set_NWallPeriodic(0);
         wallHandler.clear(); //set_NWall(0);
         //wallHandler.getObject(0)->set(Vec3D( 0.0,-1.0, 0.0), -getYMin());
         //Walls[1].set(Vec3D( 0.0, 1.0, 0.0),  getYMax());
     }
 }
References DPMBase::boundaryHandler, BaseHandler< T >::clear(), BaseHandler< T >::copyAndAddObject(), Chute::getIsPeriodic(), DPMBase::getYMax(), DPMBase::getYMin(), PeriodicBoundary::set(), and DPMBase::wallHandler.
Referenced by setupInitialConditions().
get_funa()
double Funnel::get_funa () const inline
Get funnel angle:
 {return funa;}
References funa.
Referenced by create_funnel(), create_inflow_particle(), update_funnel(), and write().
get_funD()
double Funnel::get_funD () const inline
Get minimum funnel diameter:
 {return funD;}
References funD.
Referenced by create_funnel(), setName_(), and write().
get_fundiag()
double Funnel::get_fundiag () const inline
 {return fundiag;}
References fundiag.
Referenced by create_funnel(), create_inflow_particle(), and update_funnel().
get_funfr()
double Funnel::get_funfr () const inline
Get the filling ratio.
 {return funfr;}
References funfr.
Referenced by create_funnel(), update_funnel(), and write().
get_funH()
double Funnel::get_funH () const inline
Get funnel Heigth:
 {return funH;}
References funH.
Referenced by create_funnel().
get_funHf()
double Funnel::get_funHf () const inline
Get falling heigth:
 {return funHf;}
References funHf.
Referenced by create_funnel(), and write().
get_funnz()
double Funnel::get_funnz () const inline
Get the funnel number of particles along the funnel heigth:
 {return funnz;}
References funnz.
Referenced by setName_(), update_funnel(), and write().
get_funO()
const double* Funnel::get_funO () const inline
Get funnel origin of the funnel:
 {return funO;}
References funO.
Referenced by create_funnel().
get_funOx()
double Funnel::get_funOx () const inline
 {return funO[0];}
References funO.
Referenced by check_funnel(), create_funnel(), create_inflow_particle(), and write().
get_funOy()
double Funnel::get_funOy () const inline
 {return funO[1];}
References funO.
Referenced by check_funnel(), create_funnel(), create_inflow_particle(), and write().
get_funr()
double Funnel::get_funr () inline
Get funnel radius:
 {return funr;}
References funr.
Referenced by check_funnel(), create_funnel(), and update_funnel().
get_funrmax()
double Funnel::get_funrmax () const inline
 {return funrmax;}
References funrmax.
Referenced by create_funnel(), and create_inflow_particle().
read()
void Funnel::read (std::istream & is, ReadOptions opt = ReadOptions::ReadAll) override virtual
This function reads all funnel data.
Reads the restart data for the funnel ///.
Reimplemented from DPMBase.
 {
     Chute::read(is, opt);
     logger(INFO, "Funnel read: %\n", Flusher::NO_FLUSH, wallHandler.getNumberOfObjects());
     std::string dummy;
     double funOx, funOy;
     is >> dummy >> funa >> dummy >> funD >> dummy >> funHf >> dummy >> funnz >> dummy >> funOx >> dummy >> funOy >> dummy >> funfr;
     set_funO(funOx, funOy);
     //Calculate additional information
     logger(INFO, "In Funnel::read, calling update_funnel()");
     update_funnel();
 }
References funa, funD, funfr, funHf, funnz, BaseHandler< T >::getNumberOfObjects(), INFO, logger, NO_FLUSH, Chute::read(), set_funO(), oomph::Global_string_for_annotation::string(), update_funnel(), and DPMBase::wallHandler.
readNextArgument()
bool Funnel::readNextArgument (int & i, int argc, char * argv[]) override protected virtual
Interprets the i^th command-line argument.
Reads, recognises and applies all valid flags passed when starting or restarting a Mercury simulation.
For all of the N = argc (argument count) command line arguments passed when starting/restarting a code (e.g. -tmax, -tmin ...), compares them to the "known" arguments understood by Mercury (note that further recognised arguments can be added in derived classes). If a match is found, the relevant parameter is set to the corresponding value(s) following the flag and true is returned. Otherwise, false is returned.
For instance, if the flag -xmin 0 is passed, the code's second if statement will recognise the flag, convert the subsequent string in argv to a double, and then call the setXMin() function to implement the new value (0) of XMin.
For developers: note the use of strcmp here. This cannot be replaced with a simpler ==, as we are comparing c-style strings (char*), instead of std::string. Thus, == would return equality of the pointers instead of the contents of the string. strcmp returns 0 if the strings are the same, and another number if they are different. This is then implicitly cast to a bool, where 0->false and other numbers will give true. Finally, the !-operator makes sure that the expression in the if-statements are true if the strings are the same, and false otherwise.
Parameters
[in] i the position of the element that will be read, note that the count starts at 1, as element 0 is the name of the executable
[in] argc number of arguments the user has given
[in] *argv[] the command-line arguments the user has given when calling the executable
Returns
true if the argument is successfully read, and false otherwise.
-gravity_ requires three arguments
-restart or -r loads a restart file. By default, it loads <name>.restart. If an argument "arg" is given it loads the file "arg", or "arg".restart (if the ending is not given).
Reimplemented from DPMBase.
 {
     if (!strcmp(argv[i], "-funnz"))
     {
         set_funnz(atof(argv[i + 1]));
     }
     else if (!strcmp(argv[i], "-funfr"))
     {
         set_funfr(atof(argv[i + 1]));
     }
     else if (!strcmp(argv[i], "-funr"))
     {
         set_funr(atof(argv[i + 1]));
     }
     else if (!strcmp(argv[i], "-funO"))
     {
         set_funO(atof(argv[i + 1]), atof(argv[i + 2]));
         i++; //two arguments
     }
     else if (!strcmp(argv[i], "-fundiag"))
     {
         set_fundiag(atof(argv[i + 1]));
     }
     else if (!strcmp(argv[i], "-funrmax"))
     {
         set_funrmax(atof(argv[i + 1]));
     }
     else if (!strcmp(argv[i], "-funa"))
     {
         set_funa(atof(argv[i + 1]));
     }
     else if (!strcmp(argv[i], "-funH"))
     {
         set_funH(atof(argv[i + 1]));
     }
     else if (!strcmp(argv[i], "-funHf"))
     {
         set_funHf(atof(argv[i + 1]));
     }
     else if (!strcmp(argv[i], "-funD"))
     {
         set_funD(atof(argv[i + 1]));
     }
     else
     {
         //if argv[i] is not found, check the commands in Chute
         return Chute::readNextArgument(i, argc, argv);
     }
     return true; //returns true if argv[i] is found
 }
References i, Chute::readNextArgument(), set_funa(), set_funD(), set_fundiag(), set_funfr(), set_funH(), set_funHf(), set_funnz(), set_funO(), set_funr(), and set_funrmax().
set_funa()
void Funnel::set_funa (double funa_) inline
Set funnel angle:
 {funa=funa_*constants::pi/180;}
References funa, and constants::pi.
Referenced by constructor(), and readNextArgument().
set_funD()
void Funnel::set_funD (double funD_) inline
Set minimum funnel diameter:
 {funD=funD_;}
References funD.
Referenced by readNextArgument().
set_fundiag()
void Funnel::set_fundiag (double fundiag_) inline protected
 {fundiag=fundiag_;}
References fundiag.
Referenced by readNextArgument(), and update_funnel().
set_funfr()
void Funnel::set_funfr (double funfr_) inline
Set the filling ratio.
{
         if (funfr_ < 0.0 || funfr_ > 1.0)
         {
             logger(WARN, "Filling Ratio is below 0 or above 1, default value of 0.33 is used!");
         }
         else
         {
             funfr = funfr_;
         }
     }
References funfr, logger, and WARN.
Referenced by constructor(), and readNextArgument().
set_funH()
void Funnel::set_funH (double funH_) inline protected
Set funnel Heigth:
 {funH=funH_;}
References funH.
Referenced by constructor(), readNextArgument(), and update_funnel().
set_funHf()
void Funnel::set_funHf (double funHf_) inline
Set falling heigth:
 {funHf=funHf_;}
References funHf.
Referenced by readNextArgument().
set_funnz()
void Funnel::set_funnz (double funnz_) inline
Set funnel number of particles along the funnel heigth:
 {funnz=funnz_;}
References funnz.
Referenced by constructor(), and readNextArgument().
set_funO() [1/2]
void Funnel::set_funO (double * x) inline
 {funO[0]=x[0]; funO[1]=x[1];}
References funO, and plotDoE::x.
set_funO() [2/2]
void Funnel::set_funO (double x, double y) inline
Set funnel origin of the funnel:
 {funO[0]=x; funO[1]=y;}
References funO, plotDoE::x, and y.
Referenced by read(), and readNextArgument().
set_funr()
void Funnel::set_funr (double funr_) inline protected
Set funnel radius:
 {funr=funr_;}
References funr.
Referenced by readNextArgument(), and update_funnel().
set_funrmax()
void Funnel::set_funrmax (double funrmax_) inline protected
 {funrmax=funrmax_;}
References funrmax.
Referenced by readNextArgument(), and update_funnel().
setName_()
void Funnel::setName_ ()
 {
     std::stringstream name;
     name << "A" << getChuteAngleDegrees()
             << "X" << getChuteLength()
             << "Y" << getChuteWidth()
             << "L" << getFixedParticleRadius() / getInflowParticleRadius()
             << "nz" << get_funnz()
             //~ << "r" << get_funr()
             //~ << "Ox" << get_funOx()
             //~ << "Oy" << get_funOy()
             //~ << "diag" << get_fundiag()
             //~ << "rmax" << get_funrmax()
             //~ << "H" << get_funH()
             //~ << "a" << get_funa()
             //~ << "Hf" << get_funHf()
             << "D" << get_funD();
     setName(name.str().c_str());
 }
References get_funD(), get_funnz(), Chute::getChuteAngleDegrees(), Chute::getChuteLength(), Chute::getChuteWidth(), Chute::getFixedParticleRadius(), Chute::getInflowParticleRadius(), plotDoE::name, and DPMBase::setName().
setupInitialConditions()
void Funnel::setupInitialConditions () override protected virtual
initialise particle position, velocity, radius
This initially set up the particles///.
Reimplemented from DPMBase.
 {
     logger(DEBUG, " in Funnel::setupInitialConditions ");
     //check funnel
     check_funnel();
     //create walls
     create_walls();
     //creates the funnel.
     create_funnel();
     //creates the bottom of the chute
     createBottom();
     write(std::cout);
 }
References check_funnel(), create_funnel(), create_walls(), Chute::createBottom(), DEBUG, logger, and write().
update_funnel()
void Funnel::update_funnel () protected virtual
Updates the parameters for the funnel;.
Update the funnel if it did not fit into the simulation boundaries (xmin,xmax, ymin or ymax)s ///.
 {
     logger(DEBUG, " in Funnel::update_funnel() ");
     //set_funnz(get_funnz()*(1.0+get_funfr()));
     set_funH(funnz * cos(funa) * 2 * getFixedParticleRadius());
     Chute::setInflowHeight(funHf + funH);
     set_funr(1.0 / 2.0 * funD + (funnz * sin(funa)) * 2 * getFixedParticleRadius() + getFixedParticleRadius());
     //set_funH(Chute::getInflowHeight()-funHf);
     set_fundiag(get_funfr() * get_funnz() * getFixedParticleRadius()); // Length (in m) of the filling length over the cone
     set_funrmax(get_funr() - get_fundiag() * sin(get_funa()) + getFixedParticleRadius());
     //create_walls();
 }
References cos(), DEBUG, funa, funD, funH, funHf, funnz, get_funa(), get_fundiag(), get_funfr(), get_funnz(), get_funr(), Chute::getFixedParticleRadius(), logger, set_fundiag(), set_funH(), set_funr(), set_funrmax(), Chute::setInflowHeight(), and sin().
Referenced by check_funnel(), and read().
write()
void Funnel::write (std::ostream & os, bool writeAllParticles = false) const override virtual
This function prints all funnel data in human readable format.
Writes the restart data for the funnel ///.
Reimplemented from DPMBase.
         {
     Chute::write(os, writeAllParticles);
     os
     << " funa " << get_funa()
             << " funD " << get_funD()
             << " funHf " << get_funHf()
             << " funnz " << get_funnz()
             << " funOx " << get_funOx()
             << " funOy " << get_funOy()
             << " funfr " << get_funfr() << std::endl;
 }
References get_funa(), get_funD(), get_funfr(), get_funHf(), get_funnz(), get_funOx(), get_funOy(), and Chute::write().
Referenced by setupInitialConditions().
Member Data Documentation
funa
double Funnel::funa protected
Referenced by create_funnel(), get_funa(), read(), set_funa(), and update_funnel().
funD
double Funnel::funD protected
Referenced by create_funnel(), get_funD(), read(), set_funD(), and update_funnel().
fundiag
double Funnel::fundiag protected
Referenced by get_fundiag(), and set_fundiag().
funfr
double Funnel::funfr protected
Referenced by get_funfr(), read(), and set_funfr().
funH
double Funnel::funH protected
Referenced by get_funH(), set_funH(), and update_funnel().
funHf
double Funnel::funHf protected
Referenced by get_funHf(), read(), set_funHf(), and update_funnel().
funnz
double Funnel::funnz protected
Referenced by create_funnel(), get_funnz(), read(), set_funnz(), and update_funnel().
funO
double Funnel::funO[2] protected
Referenced by get_funO(), get_funOx(), get_funOy(), and set_funO().
funr
double Funnel::funr protected
Referenced by get_funr(), and set_funr().
funrmax
double Funnel::funrmax protected
Referenced by get_funrmax(), and set_funrmax().
inflowParticle_
SphericalParticle Funnel::inflowParticle_ protected
Referenced by create_inflow_particle().
The documentation for this class was generated from the following files:
Funnel.h
Funnel.cc