MercuryDPM: Eigen::BlockImpl< XprType, BlockRows, BlockCols, true, Sparse > Class Template Reference
Eigen::BlockImpl< XprType, BlockRows, BlockCols, true, Sparse > Class Template Reference
#include <SparseBlock.h>
Public Types
enum { IsRowMajor = internal::traits<BlockType>::IsRowMajor }
Public Types inherited from Eigen::SparseMatrixBase< Block< XprType, BlockRows, BlockCols, true > >
enum
typedef internal::traits< Block< XprType, BlockRows, BlockCols, true > >::Scalar Scalar
typedef Scalar value_type
typedef internal::packet_traits< Scalar >::type PacketScalar
typedef internal::traits< Block< XprType, BlockRows, BlockCols, true > >::StorageKind StorageKind
typedef internal::traits< Block< XprType, BlockRows, BlockCols, true > >::StorageIndex StorageIndex
typedef internal::add_const_on_value_type_if_arithmetic< typename internal::packet_traits< Scalar >::type >::type PacketReturnType
typedef SparseMatrixBase StorageBaseType
typedef Matrix< StorageIndex, Dynamic, 1 > IndexVector
typedef Matrix< Scalar, Dynamic, 1 > ScalarVector
typedef std::conditional_t< NumTraits< Scalar >::IsComplex, CwiseUnaryOp< internal::scalar_conjugate_op< Scalar >, Eigen::Transpose< const Block< XprType, BlockRows, BlockCols, true > > >, Transpose< const Block< XprType, BlockRows, BlockCols, true > > > AdjointReturnType
typedef Transpose< Block< XprType, BlockRows, BlockCols, true > > TransposeReturnType
typedef Transpose< const Block< XprType, BlockRows, BlockCols, true > > ConstTransposeReturnType
typedef SparseMatrix< Scalar, Flags &RowMajorBit ? RowMajor :ColMajor, StorageIndex > PlainObject
typedef NumTraits< Scalar >::Real RealScalar
typedef std::conditional_t< HasDirectAccess_, const Scalar &, Scalar > CoeffReturnType
typedef CwiseNullaryOp< internal::scalar_constant_op< Scalar >, Matrix< Scalar, Dynamic, Dynamic > > ConstantReturnType
typedef Matrix< Scalar, RowsAtCompileTime, ColsAtCompileTime > DenseMatrixType
typedef Matrix< Scalar, internal::max_size_prefer_dynamic(RowsAtCompileTime, ColsAtCompileTime), internal::max_size_prefer_dynamic(RowsAtCompileTime, ColsAtCompileTime)> SquareMatrixType
typedef EigenBase< Block< XprType, BlockRows, BlockCols, true > > Base
Public Types inherited from Eigen::EigenBase< Block< XprType, BlockRows, BlockCols, true > >
typedef Eigen::Index Index
The interface type of indices.
typedef internal::traits< Block< XprType, BlockRows, BlockCols, true > >::StorageKind StorageKind
Public Member Functions
BlockImpl (XprType &xpr, Index i)
BlockImpl (XprType &xpr, Index startRow, Index startCol, Index blockRows, Index blockCols)
EIGEN_STRONG_INLINE Index rows () const
EIGEN_STRONG_INLINE Index cols () const
Index nonZeros () const
const Scalar coeff (Index row, Index col) const
const Scalar coeff (Index index) const
const XprType & nestedExpression () const
XprType & nestedExpression ()
Index startRow () const
Index startCol () const
Index blockRows () const
Index blockCols () const
Public Member Functions inherited from Eigen::SparseMatrixBase< Block< XprType, BlockRows, BlockCols, true > >
Block< XprType, BlockRows, BlockCols, true > & operator= (const EigenBase< OtherDerived > &other)
Block< XprType, BlockRows, BlockCols, true > & operator= (const ReturnByValue< OtherDerived > &other)
Block< XprType, BlockRows, BlockCols, true > & operator= (const SparseMatrixBase< OtherDerived > &other)
Block< XprType, BlockRows, BlockCols, true > & operator= (const Block< XprType, BlockRows, BlockCols, true > &other)
const Block< XprType, BlockRows, BlockCols, true > & derived () const
Block< XprType, BlockRows, BlockCols, true > & derived ()
Block< XprType, BlockRows, BlockCols, true > & const_cast_derived () const
Index rows () const
Index cols () const
Index size () const
bool isVector () const
Index outerSize () const
Index innerSize () const
bool isRValue () const
Block< XprType, BlockRows, BlockCols, true > & markAsRValue ()
SparseMatrixBase ()
Block< XprType, BlockRows, BlockCols, true > & operator+= (const SparseMatrixBase< OtherDerived > &other)
Block< XprType, BlockRows, BlockCols, true > & operator+= (const DiagonalBase< OtherDerived > &other)
Block< XprType, BlockRows, BlockCols, true > & operator+= (const EigenBase< OtherDerived > &other)
EIGEN_STRONG_INLINE Block< XprType, BlockRows, BlockCols, true > & operator+= (const SparseMatrixBase< OtherDerived > &other)
Block< XprType, BlockRows, BlockCols, true > & operator-= (const SparseMatrixBase< OtherDerived > &other)
Block< XprType, BlockRows, BlockCols, true > & operator-= (const DiagonalBase< OtherDerived > &other)
Block< XprType, BlockRows, BlockCols, true > & operator-= (const EigenBase< OtherDerived > &other)
EIGEN_STRONG_INLINE Block< XprType, BlockRows, BlockCols, true > & operator-= (const SparseMatrixBase< OtherDerived > &other)
Block< XprType, BlockRows, BlockCols, true > & operator*= (const Scalar &other)
Block< XprType, BlockRows, BlockCols, true > & operator*= (const SparseMatrixBase< OtherDerived > &other)
Block< XprType, BlockRows, BlockCols, true > & operator/= (const Scalar &other)
EIGEN_STRONG_INLINE const CwiseProductDenseReturnType< OtherDerived >::Type cwiseProduct (const MatrixBase< OtherDerived > &other) const
EIGEN_STRONG_INLINE const SparseMatrixBase< Block< XprType, BlockRows, BlockCols, true > >::template CwiseProductDenseReturnType< OtherDerived >::Type cwiseProduct (const MatrixBase< OtherDerived > &other) const
const Product< Block< XprType, BlockRows, BlockCols, true >, OtherDerived > operator* (const DiagonalBase< OtherDerived > &other) const
const Product< Block< XprType, BlockRows, BlockCols, true >, OtherDerived, AliasFreeProduct > operator* (const SparseMatrixBase< OtherDerived > &other) const
const Product< Block< XprType, BlockRows, BlockCols, true >, OtherDerived > operator* (const MatrixBase< OtherDerived > &other) const
SparseSymmetricPermutationProduct< Block< XprType, BlockRows, BlockCols, true >, Upper|Lower > twistedBy (const PermutationMatrix< Dynamic, Dynamic, StorageIndex > &perm) const
const TriangularView< const Block< XprType, BlockRows, BlockCols, true >, Mode > triangularView () const
ConstSelfAdjointViewReturnType< UpLo >::Type selfadjointView () const
SelfAdjointViewReturnType< UpLo >::Type selfadjointView ()
SparseMatrixBase< Block< XprType, BlockRows, BlockCols, true > >::template ConstSelfAdjointViewReturnType< UpLo >::Type selfadjointView () const
SparseMatrixBase< Block< XprType, BlockRows, BlockCols, true > >::template SelfAdjointViewReturnType< UpLo >::Type selfadjointView ()
Scalar dot (const MatrixBase< OtherDerived > &other) const
Scalar dot (const SparseMatrixBase< OtherDerived > &other) const
internal::traits< Block< XprType, BlockRows, BlockCols, true > >::Scalar dot (const MatrixBase< OtherDerived > &other) const
internal::traits< Block< XprType, BlockRows, BlockCols, true > >::Scalar dot (const SparseMatrixBase< OtherDerived > &other) const
RealScalar squaredNorm () const
RealScalar norm () const
RealScalar blueNorm () const
TransposeReturnType transpose ()
const ConstTransposeReturnType transpose () const
const AdjointReturnType adjoint () const
DenseMatrixType toDense () const
bool isApprox (const SparseMatrixBase< OtherDerived > &other, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
bool isApprox (const MatrixBase< OtherDerived > &other, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
const internal::eval< Block< XprType, BlockRows, BlockCols, true > >::type eval () const
Scalar sum () const
const SparseView< Block< XprType, BlockRows, BlockCols, true > > pruned (const Scalar &reference=Scalar(0), const RealScalar &epsilon=NumTraits< Scalar >::dummy_precision()) const
Public Member Functions inherited from Eigen::EigenBase< Block< XprType, BlockRows, BlockCols, true > >
constexpr EIGEN_DEVICE_FUNC Block< XprType, BlockRows, BlockCols, true > & derived ()
constexpr EIGEN_DEVICE_FUNC const Block< XprType, BlockRows, BlockCols, true > & derived () const
EIGEN_DEVICE_FUNC Block< XprType, BlockRows, BlockCols, true > & const_cast_derived () const
EIGEN_DEVICE_FUNC const Block< XprType, BlockRows, BlockCols, true > & const_derived () const
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index rows () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index cols () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index size () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC void evalTo (Dest &dst) const
EIGEN_DEVICE_FUNC void addTo (Dest &dst) const
EIGEN_DEVICE_FUNC void subTo (Dest &dst) const
EIGEN_DEVICE_FUNC void applyThisOnTheRight (Dest &dst) const
EIGEN_DEVICE_FUNC void applyThisOnTheLeft (Dest &dst) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE DeviceWrapper< Block< XprType, BlockRows, BlockCols, true >, Device > device (Device &device)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE DeviceWrapper< const Block< XprType, BlockRows, BlockCols, true >, Device > device (Device &device) const
Protected Types
enum { OuterSize = IsRowMajor ? BlockRows : BlockCols }
typedef SparseMatrixBase< BlockType > Base
Protected Member Functions
template<typename T >
BlockImpl & operator= (const T &)
Protected Member Functions inherited from Eigen::SparseMatrixBase< Block< XprType, BlockRows, BlockCols, true > >
Block< XprType, BlockRows, BlockCols, true > & assign (const OtherDerived &other)
void assignGeneric (const OtherDerived &other)
Static Protected Member Functions
static StorageIndex convert_index (const Index idx)
Static Protected Member Functions inherited from Eigen::SparseMatrixBase< Block< XprType, BlockRows, BlockCols, true > >
static StorageIndex convert_index (const Index idx)
Protected Attributes
internal::ref_selector< XprType >::non_const_type m_matrix
Index m_outerStart
const internal::variable_if_dynamic< Index, OuterSize > m_outerSize
Protected Attributes inherited from Eigen::SparseMatrixBase< Block< XprType, BlockRows, BlockCols, true > >
bool m_isRValue
Private Types
typedef internal::remove_all_t< typename XprType::Nested > MatrixTypeNested_
typedef Block< XprType, BlockRows, BlockCols, true > BlockType
Member Typedef Documentation
Base
template<typename XprType , int BlockRows, int BlockCols> typedef SparseMatrixBase<BlockType> Eigen::BlockImpl< XprType, BlockRows, BlockCols, true, Sparse >::Base protected
BlockType
template<typename XprType , int BlockRows, int BlockCols> typedef Block<XprType, BlockRows, BlockCols, true> Eigen::BlockImpl< XprType, BlockRows, BlockCols, true, Sparse >::BlockType private
MatrixTypeNested_
template<typename XprType , int BlockRows, int BlockCols> typedef internal::remove_all_t<typename XprType::Nested> Eigen::BlockImpl< XprType, BlockRows, BlockCols, true, Sparse >::MatrixTypeNested_ private
Member Enumeration Documentation
anonymous enum
template<typename XprType , int BlockRows, int BlockCols> anonymous enum
Enumerator
IsRowMajor
 { IsRowMajor = internal::traits<BlockType>::IsRowMajor };
anonymous enum
template<typename XprType , int BlockRows, int BlockCols> anonymous enum protected
Enumerator
OuterSize
 { OuterSize = IsRowMajor ? BlockRows : BlockCols };
Constructor & Destructor Documentation
BlockImpl() [1/2]
template<typename XprType , int BlockRows, int BlockCols> Eigen::BlockImpl< XprType, BlockRows, BlockCols, true, Sparse >::BlockImpl (XprType & xpr, Index i) inline
 : m_matrix(xpr), m_outerStart(convert_index(i)), m_outerSize(OuterSize) {}
BlockImpl() [2/2]
template<typename XprType , int BlockRows, int BlockCols> Eigen::BlockImpl< XprType, BlockRows, BlockCols, true, Sparse >::BlockImpl (XprType & xpr, Index startRow, Index startCol, Index blockRows, Index blockCols) inline
       : m_matrix(xpr),
         m_outerStart(convert_index(IsRowMajor ? startRow : startCol)),
         m_outerSize(convert_index(IsRowMajor ? blockRows : blockCols)) {}
Member Function Documentation
blockCols()
template<typename XprType , int BlockRows, int BlockCols> Index Eigen::BlockImpl< XprType, BlockRows, BlockCols, true, Sparse >::blockCols () const inline
 { return IsRowMajor ? m_matrix.cols() : m_outerSize.value(); }
blockRows()
template<typename XprType , int BlockRows, int BlockCols> Index Eigen::BlockImpl< XprType, BlockRows, BlockCols, true, Sparse >::blockRows () const inline
 { return IsRowMajor ? m_outerSize.value() : m_matrix.rows(); }
coeff() [1/2]
template<typename XprType , int BlockRows, int BlockCols> const Scalar Eigen::BlockImpl< XprType, BlockRows, BlockCols, true, Sparse >::coeff (Index index) const inline
{
     return m_matrix.coeff(IsRowMajor ? m_outerStart : index, IsRowMajor ? index : m_outerStart);
   }
coeff() [2/2]
template<typename XprType , int BlockRows, int BlockCols> const Scalar Eigen::BlockImpl< XprType, BlockRows, BlockCols, true, Sparse >::coeff (Index row, Index col) const inline
{
     return m_matrix.coeff(row + (IsRowMajor ? m_outerStart : 0), col + (IsRowMajor ? 0 : m_outerStart));
   }
References col(), and row().
cols()
template<typename XprType , int BlockRows, int BlockCols> EIGEN_STRONG_INLINE Index Eigen::BlockImpl< XprType, BlockRows, BlockCols, true, Sparse >::cols () const inline
 { return IsRowMajor ? m_matrix.cols() : m_outerSize.value(); }
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
convert_index()
template<typename XprType , int BlockRows, int BlockCols> static StorageIndex Eigen::SparseMatrixBase< Derived >::convert_index inline static protected
 { return internal::convert_index<StorageIndex>(idx); }
nestedExpression() [1/2]
template<typename XprType , int BlockRows, int BlockCols> XprType& Eigen::BlockImpl< XprType, BlockRows, BlockCols, true, Sparse >::nestedExpression () inline
 { return m_matrix; }
nestedExpression() [2/2]
template<typename XprType , int BlockRows, int BlockCols> const XprType& Eigen::BlockImpl< XprType, BlockRows, BlockCols, true, Sparse >::nestedExpression () const inline
 { return m_matrix; }
nonZeros()
template<typename XprType , int BlockRows, int BlockCols> Index Eigen::BlockImpl< XprType, BlockRows, BlockCols, true, Sparse >::nonZeros () const inline
{
     typedef internal::evaluator<XprType> EvaluatorType;
     EvaluatorType matEval(m_matrix);
     Index nnz = 0;
     Index end = m_outerStart + m_outerSize.value();
     for (Index j = m_outerStart; j < end; ++j)
       for (typename EvaluatorType::InnerIterator it(matEval, j); it; ++it) ++nnz;
     return nnz;
   }
References Eigen::placeholders::end, and j.
operator=()
template<typename XprType , int BlockRows, int BlockCols> template<typename T > BlockImpl& Eigen::BlockImpl< XprType, BlockRows, BlockCols, true, Sparse >::operator= (const T &) inline protected
{
     EIGEN_STATIC_ASSERT(sizeof(T) == 0, THIS_SPARSE_BLOCK_SUBEXPRESSION_IS_READ_ONLY);
     return *this;
   }
References EIGEN_STATIC_ASSERT.
rows()
template<typename XprType , int BlockRows, int BlockCols> EIGEN_STRONG_INLINE Index Eigen::BlockImpl< XprType, BlockRows, BlockCols, true, Sparse >::rows () const inline
 { return IsRowMajor ? m_outerSize.value() : m_matrix.rows(); }
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
startCol()
template<typename XprType , int BlockRows, int BlockCols> Index Eigen::BlockImpl< XprType, BlockRows, BlockCols, true, Sparse >::startCol () const inline
 { return IsRowMajor ? 0 : m_outerStart; }
startRow()
template<typename XprType , int BlockRows, int BlockCols> Index Eigen::BlockImpl< XprType, BlockRows, BlockCols, true, Sparse >::startRow () const inline
 { return IsRowMajor ? m_outerStart : 0; }
Member Data Documentation
m_matrix
template<typename XprType , int BlockRows, int BlockCols> internal::ref_selector<XprType>::non_const_type Eigen::BlockImpl< XprType, BlockRows, BlockCols, true, Sparse >::m_matrix protected
m_outerSize
template<typename XprType , int BlockRows, int BlockCols> const internal::variable_if_dynamic<Index, OuterSize> Eigen::BlockImpl< XprType, BlockRows, BlockCols, true, Sparse >::m_outerSize protected
m_outerStart
template<typename XprType , int BlockRows, int BlockCols> Index Eigen::BlockImpl< XprType, BlockRows, BlockCols, true, Sparse >::m_outerStart protected
The documentation for this class was generated from the following file:
SparseBlock.h