MercuryDPM: Logger.cc File Reference
Logger.cc File Reference
#include "Logger.h"
#include <cstdlib>
#include <iostream>
#include <csignal>
Functions
static void printInfo (std::string module, std::string msg, Flusher doFlush)
Prints messages of loglevel INFO.
static void printWarn (std::string module, std::string msg, Flusher doFlush)
Prints messages of loglevel WARN.
static void printError (std::string module, std::string msg, Flusher doFlush)
Prints messages of loglevel ERROR.
static void printFatalError (const std::string &module, const std::string &msg, Flusher doFlush)
Prints messages of loglevel FATAL.
Variables
LL< Log::FATAL > FATAL
Definition of the different loglevels by its wrapper class LL. These are used as tags in template metaprogramming for the Logger class.
LL< Log::ERROR > ERROR
Error log level.
LL< Log::WARN > WARN
Warning log level.
LL< Log::INFO > INFO
Info log level.
LL< Log::DEFAULT > DEFAULT
Default log level.
LL< Log::VERBOSE > VERBOSE
Verbose information.
LL< Log::DEBUG > DEBUG
Debug information.
Logger< MERCURYDPM_LOGLEVEL > logger ("MercuryKernel")
Definition of different loggers with certain modules. A user can define its own custom logger here.
Logger< CG_LOGLEVEL > cgLogger ("MercuryCG")
LoggerOutput loggerOutputDefaultImpl
LoggerOutput * loggerOutput = &loggerOutputDefaultImpl
Declaration of the output functions.
Function Documentation
printError()
static void printError (std::string module, std::string msg, Flusher doFlush) static
Prints messages of loglevel ERROR.
Parameters
[in] module The module name of the current logger invocation.
[in] msg formatted message to be printed.
[in] doFlush Flusher enum class object to enable/disable flushing of the output.
 {
 #ifdef MERCURYDPM_USE_MPI
     //Check if MPI is initialised
     initialiseMPI();
     MPIContainer& communicator = MPIContainer::Instance();
     std::cout << "\033[1;33mError " << module << ":\033[0m\n" << "[Processor: " << communicator.getProcessorID() << "]" << msg << std::endl;
 #else
     std::cout << "\033[1;31mAn error has occured"
               << "\n\033[1;31mModule : " << module
               << "\n\033[1;31mMessage: " << msg << ":\033[0m\n" << std::endl;
 #endif
 #ifdef MERCURYDPM_BACKTRACE_ENABLE
     std::cerr << "\n-----------------[Stack Trace]-----------------\n";
     void* stackBuffer[64]; //This should be enough for all purposes..
     //First, we retrieve the addresses of the entire stack...
     int nStackFrames = backtrace(stackBuffer, 64);
 #ifndef MERCURYDPM_BACKTRACE_DEMANGLE
     //We don't have the demangling infra, so just use backtrace_symbols.
     char** functionNames = backtrace_symbols(stackBuffer, nStackFrames);
     for( int i = 0; i < nStackFrames; i++ )
     {
         std::cerr << '\t' << functionNames[i] << '\n';
     }
     std::cerr << "Exiting.\n" << std::endl;
     //DO NOT USE DELETE HERE. THIS SHOULD BE free()'d!
     // -- dducks
     free(functionNames);
 #else
     //We request the symbol information ourselves, in order to be able to demangle it.
     //And request the function names using dladdr.
     Dl_info infoStruct;
     for (int i = 4; i < nStackFrames; i++)
     {
         if (dladdr(stackBuffer[i], &infoStruct))
         { // We succesfully loaded the address...
             int demangleStatus;
             char* fnDemangled = abi::__cxa_demangle(infoStruct.dli_sname, NULL, NULL, &demangleStatus);
             if (infoStruct.dli_sname == nullptr)
                 continue;
             //We even succesfully demangled the symbol...
             if (demangleStatus == 0)
             {
                 std::cerr << fnDemangled << " +" << (void*) ((char*) stackBuffer[i] - (char*) infoStruct.dli_saddr) << "\t(" << infoStruct.dli_fname << ")\n";
                 free(fnDemangled);
             }
             else
             { //Well, we tried. Lets output at least our raw symbol name.
                 std::cerr << infoStruct.dli_sname << " +" << (void*) ((char*) stackBuffer[i] - (char*) infoStruct.dli_saddr) << "\t(" << infoStruct.dli_fname << ")\n";
             }
         }
         else
         { //Name lookup failed.
             std::cerr << stackBuffer[i] << ": ?????" << std::endl;
         }
     }
 #endif
 #endif
     //send a signal first, in case a debugger can catch it
     std::raise(SIGTERM);
     //call exit() for the specific loglevel
     std::exit(static_cast<int>(Log::ERROR));
 }
References ERROR, MPIContainer::getProcessorID(), i, initialiseMPI(), and MPIContainer::Instance().
printFatalError()
static void printFatalError (const std::string & module, const std::string & msg, Flusher doFlush) static
Prints messages of loglevel FATAL.
Parameters
[in] module The module name of the current logger invocation.
[in] msg formatted message to be printed.
[in] doFlush Flusher enum class object to enable/disable flushing of the output.
 {
 #ifdef MERCURYDPM_USE_MPI
     //Check if MPI is initialised
     initialiseMPI();
     MPIContainer& communicator = MPIContainer::Instance();
     std::cout << "\033[1;33mError " << module << ":\033[0m\n" << "[Processor: " << communicator.getProcessorID() << "]" << msg << std::endl;
 #else
     std::cout << "\033[1;31mA fatal error has occured"
               << "\n\033[1;31mModule : " << module
               << "\n\033[1;31mMessage: " << msg << ":\033[0m\n" << std::endl;
 #endif
 #ifdef MERCURYDPM_BACKTRACE_ENABLE
     std::cerr << "\n-----------------[Stack Trace]-----------------\n";
     void* stackBuffer[64]; //This should be enough for all purposes..
     //First, we retrieve the addresses of the entire stack...
     int nStackFrames = backtrace(stackBuffer, 64);
 #ifndef MERCURYDPM_BACKTRACE_DEMANGLE
     //We don't have the demangling infra, so just use backtrace_symbols.
     char** functionNames = backtrace_symbols(stackBuffer, nStackFrames);
     for( int i = 0; i < nStackFrames; i++ )
     {
         std::cerr << '\t' << functionNames[i] << '\n';
     }
     std::cerr << "Exiting.\n" << std::endl;
     //DO NOT USE DELETE HERE. THIS SHOULD BE free()'d!
     // -- dducks
     free(functionNames);
 #else
     //We request the symbol information ourselves, in order to be able to demangle it.
     //And request the function names using dladdr.
     Dl_info infoStruct;
     for (int i = 4; i < nStackFrames; i++)
     {
         if (dladdr(stackBuffer[i], &infoStruct))
         { // We succesfully loaded the address...
             int demangleStatus;
             char* fnDemangled = abi::__cxa_demangle(infoStruct.dli_sname, NULL, NULL, &demangleStatus);
             if (infoStruct.dli_sname == nullptr)
                 continue;
             //We even succesfully demangled the symbol...
             if (demangleStatus == 0)
             {
                 std::cerr << fnDemangled << " +" << (void*) ((char*) stackBuffer[i] - (char*) infoStruct.dli_saddr) << "\t(" << infoStruct.dli_fname << ")\n";
                 free(fnDemangled);
             }
             else
             { //Well, we tried. Lets output at least our raw symbol name.
                 std::cerr << infoStruct.dli_sname << " +" << (void*) ((char*) stackBuffer[i] - (char*) infoStruct.dli_saddr) << "\t(" << infoStruct.dli_fname << ")\n";
             }
         }
         else
         { //Name lookup failed.
             std::cerr << stackBuffer[i] << ": ?????" << std::endl;
         }
     }
 #endif
 #endif
     //send a signal first, in case a debugger can catch it
     std::raise(SIGTRAP);
     //call exit for the specific loglevel
     std::exit(static_cast<int>(Log::FATAL));
 }
References FATAL, MPIContainer::getProcessorID(), i, initialiseMPI(), and MPIContainer::Instance().
printInfo()
static void printInfo (std::string module, std::string msg, Flusher doFlush) static
Prints messages of loglevel INFO.
Parameters
[in] module The module name of the current logger invocation.
[in] msg formatted message to be printed.
[in] doFlush Flusher enum class object to enable/disable flushing of the output.
 {
 #ifdef MERCURYDPM_USE_MPI
     //Check if MPI is initialised
     initialiseMPI();
     MPIContainer& communicator = MPIContainer::Instance();
     std::cout << "[Process: " << communicator.getProcessorID() << "]: " << msg;
     if (doFlush == Flusher::FLUSH)
     {
         std::cout << std::endl;
     }
 #else
     std::cout << msg;
     if (doFlush == Flusher::FLUSH)
     {
         std::cout << std::endl;
     }
 #endif
 }
References FLUSH, MPIContainer::getProcessorID(), initialiseMPI(), and MPIContainer::Instance().
printWarn()
static void printWarn (std::string module, std::string msg, Flusher doFlush) static
Prints messages of loglevel WARN.
Parameters
[in] module The module name of the current logger invocation.
[in] msg formatted message to be printed.
[in] doFlush Flusher enum class object to enable/disable flushing of the output.
 {
 #ifdef MERCURYDPM_USE_MPI
     //Check if MPI is initialised
     initialiseMPI();
     MPIContainer& communicator = MPIContainer::Instance();
     std::cout << "\033[1;33mModule " << module << ":\033[0m\n" << "[Processor: " << communicator.getProcessorID() << "]" << msg;
     if (doFlush == Flusher::FLUSH)
     {
         std::cout << std::endl;
     }
 #else
     std::cout << "\033[1;33mMessage " << module << ":\033[0m\n" << msg;
     if (doFlush == Flusher::FLUSH)
     {
         std::cout << std::endl;
     }
 #endif
 }
References FLUSH, MPIContainer::getProcessorID(), initialiseMPI(), and MPIContainer::Instance().
Variable Documentation
cgLogger
Logger<CG_LOGLEVEL> cgLogger("MercuryCG") ("MercuryCG")
Referenced by CGHandler::computeContactPoints(), CGHandler::evaluateDataFiles(), CGHandler::evaluateRestartFiles(), and CGHandler::restart().
DEBUG
LL<Log::DEBUG> DEBUG
Debug information.
Only used for internal development. Can be very cryptic, as it is only meant for finding bugs / oddities by the internal development team.
Example: Collision found between Particle #38201 and Wall #5
Default behaviour: ignore.
DEFAULT
LL<Log::DEFAULT> DEFAULT
Default log level.
Only useful for defining the loglevel of the logger itself. Should not actually be used.
ERROR
LL<Log::ERROR> ERROR
Error log level.
Error, as in, the program has found a severe problem which it cannot resolve any further. It does not know how to recover in a sane way. The difference to FATAL is mainly that this type of failure is most often caused by human error.
Example: Negative time step, Infinite end time and no override of the continuation function.
Default behaviour: log to std::cerr, followed by std::exit().
Referenced by addObject(), CLiveStatistics< T >::CLiveStatistics(), commandLineCG(), SmallMatrix< numberOfRows, numberOfColumns >::computeWedgeStuffVector(), helpers::createDirectory(), SmallMatrix< numberOfRows, numberOfColumns >::determinant(), SolidProblem< ELEMENT_TYPE >::get_x(), BaseHandler< T >::getObjectById(), BaseHandler< T >::getObjectsById(), getPSDTypeName(), helpers::getSaveCountFromNumberOfSavesAndTimeMaxAndTimeStep(), main(), BaseVTKWriter< H >::makeVTKFileWithHeader(), Species< NormalForceSpecies, FrictionForceSpecies, AdhesiveForceSpecies >::mixAll(), helpers::more(), operator<<(), operator>>(), helpers::readArrayFromFile(), NurbsSurface::set(), CGFields::StandardFieldsBinning::setFields(), SCoupling< M, O >::solveSurfaceCouplingForgiving(), SolidProblem< ELEMENT_TYPE >::solveUnsteady(), SolidProblem< ELEMENT_TYPE >::solveUnsteadyForgiving(), Statistics(), statistics_while_running< T >::statistics_while_running(), helpers::stringFormat(), test1(), test2(), testPSD(), and SolidProblem< ELEMENT_TYPE >::writeToVTK().
FATAL
LL<Log::FATAL> FATAL
Definition of the different loglevels by its wrapper class LL. These are used as tags in template metaprogramming for the Logger class.
Fatal log level.
Referenced by compareParticles(), main(), transformMercuryToVTK(), and MortaringValidationProblem< ELEMENT, NON_MORTAR_ELEMENT >::verify_mortared_nodes_coincide().
INFO
LL<Log::INFO> INFO
Info log level.
Useful information, small oddities and statistics which should be of no real effect to the user, but still give useful information about the current state and progress of the program.
Example: Finished inserting 381 particles.
Default behaviour: log to std::cout, returns afterwards.
logger
Logger<MERCURYDPM_LOGLEVEL> logger("MercuryKernel") ("MercuryKernel")
Definition of different loggers with certain modules. A user can define its own custom logger here.
Referenced by SilbertHstop::actionAfterTimeStep(), ShearStage::actionsAfterSolve(), DPM::actionsAfterSolve(), ForceLawsMPI2Test::actionsAfterSolve(), MaserRepeatedOutInMPI2Test::actionsAfterSolve(), ParameterStudy1DDemo::actionsAfterSolve(), ParameterStudy2DDemo::actionsAfterSolve(), ParameterStudy3DDemo::actionsAfterSolve(), PSDManualInsertionSelfTest::actionsAfterSolve(), HertzianBSHPInteractionTwoParticleElasticCollision::actionsAfterSolve(), Contact::actionsAfterSolve(), SphericalSuperQuadricCollision::actionsAfterSolve(), SpeciesTest::actionsAfterSolve(), BaseCluster::actionsAfterSolve(), GranuHeap::actionsAfterTimeStep(), ShearStage::actionsAfterTimeStep(), NozzleDemo::actionsAfterTimeStep(), RotatingDrumWet::actionsAfterTimeStep(), TwoByTwoMPIDomainMPI4Test::actionsAfterTimeStep(), HourGlass::actionsAfterTimeStep(), LeesEdwardsDemo::actionsAfterTimeStep(), TimeDependentPeriodicBoundary3DSelfTest::actionsAfterTimeStep(), TimeDependentPeriodicBoundaryTest::actionsAfterTimeStep(), OneParticleHeatingSelfTest::actionsAfterTimeStep(), OneParticleCoolingSelfTest::actionsAfterTimeStep(), RotatingDrumBidisperseInitialise::actionsAfterTimeStep(), Chutebelt::actionsAfterTimeStep(), NozzleSelfTest::actionsAfterTimeStep(), PolydisperseInsertionBoundarySelfTest::actionsAfterTimeStep(), SphericalIndenter::actionsAfterTimeStep(), BouncingSuperQuadric::actionsAfterTimeStep(), GranularCollapse::actionsAfterTimeStep(), SphericalSuperQuadricCollision::actionsAfterTimeStep(), ContactDetectionNormalSpheresTest::actionsAfterTimeStep(), ContactDetectionRotatedSpheresTest::actionsAfterTimeStep(), MercuryProblem::actionsAfterTimeStep(), Tutorial11::actionsAfterTimeStep(), DrivenParticleClass::actionsAfterTimeStep(), BaseCluster::actionsAfterTimeStep(), VolumeCoupling::actionsAfterTimeStep(), BaseBoundary::actionsBeforeTimeLoop(), ParameterStudy1DDemo::actionsBeforeTimeLoop(), ParameterStudy2DDemo::actionsBeforeTimeLoop(), ParameterStudy3DDemo::actionsBeforeTimeLoop(), SphericalIndenter::actionsBeforeTimeLoop(), DropletBoundary::actionsBeforeTimeLoop(), LawinenBox::actionsBeforeTimeStep(), DPM::actionsBeforeTimeStep(), SmoothChute::actionsBeforeTimeStep(), ForceLawsMPI2Test::actionsBeforeTimeStep(), MeltableForceLaw2SelfTest::actionsBeforeTimeStep(), MeltableForceLawSelfTest::actionsBeforeTimeStep(), ThermalConductionSelfTest::actionsBeforeTimeStep(), Chutebelt::actionsBeforeTimeStep(), DrumRot::actionsBeforeTimeStep(), RotatingDrum::actionsBeforeTimeStep(), PeriodicWallsWithSlidingFrictionUnitTest::actionsBeforeTimeStep(), SaveCountUnitTest::actionsBeforeTimeStep(), AirySavageHutter::actionsOnRestart(), Chutebelt::actionsOnRestart(), DrumRot::actionsOnRestart(), BaseCluster::actionsOnRestart(), ConstantMassFlowMaserBoundary::activateMaser(), SubcriticalMaserBoundary::activateMaser(), SubcriticalMaserBoundaryTEST::activateMaser(), IntersectionOfWalls::add3PointObject(), oomph::SCoupledElement< ELEMENT >::add_external_coupling_forces_to_residuals(), ChutePeriodic::add_flow_particles(), PossibleContactList::add_PossibleContact(), SolidProblem< ELEMENT_TYPE >::addAnisotropy(), SolidProblem< ELEMENT_TYPE >::addDissipation(), ParticleHandler::addExistingObject(), Chute::addFlowParticlesCompactly(), PolydisperseInsertionBoundary::addGenerandum(), ParticleHandler::addGhostObject(), LocalExpansion::addLocalExpansionCoefficients(), Multipole::addMultipoleCoefficients(), ParticleHandler::addObject(), WallHandler::addObject(), addObject(), NautaMixer::addParticles(), NautaMixer::addParticlesAtWall(), BaseWall::addParticlesAtWall(), Domain::addParticlesToLists(), ConstantMassFlowMaserBoundary::addParticleToMaser(), SubcriticalMaserBoundary::addParticleToMaser(), IntersectionOfWalls::addPlate(), NautaMixer::addSpeciesAndSetTimeStepAndSaveCount(), Thermal< Particle >::addTemperature(), IntersectionOfWalls::addTetra(), IntersectionOfWalls::addTetraSTL(), helpers::addToFile(), MeltableNormalSpecies::analyseTimeScales(), Membrane::applyPressure(), HGridOptimiser::applyStep(), Membrane::Edge::applyStretchForce(), AxisymmetricIntersectionOfWalls::AxisymmetricIntersectionOfWalls(), BaseBoundary::BaseBoundary(), BaseCG::BaseCG(), BaseCluster::BaseCluster(), BaseClusterInsertionBoundary::BaseClusterInsertionBoundary(), BaseHandler< T >::BaseHandler(), BaseInteractable::BaseInteractable(), BaseParticle::BaseParticle(), BaseSpecies::BaseSpecies(), BaseWall::BaseWall(), BasicIntersectionOfWalls::BasicIntersectionOfWalls(), BasicUnionOfWalls::BasicUnionOfWalls(), SolidBag::bendBag(), BondedInteraction::BondedInteraction(), BoundaryHandler::BoundaryHandler(), HGridOptimiser::calcDfDx(), HGridOptimiser::calculateDiffWork(), BaseCluster::calculateTimeStep(), HGridOptimiser::calculateWork(), CFile::CFile(), ChargedBondedInteraction::ChargedBondedInteraction(), mathsFunc::chebyshev(), Funnel::check_funnel(), Beam::checkBeamDeflection(), DeletionBoundary::checkBoundaryAfterParticleMoved(), SubcriticalMaserBoundaryTEST::checkBoundaryAfterParticleMoved(), StressStrainControlBoundary::checkBoundaryAfterParticlesMove(), DropletBoundary::checkBoundaryAfterParticlesMove(), SubcriticalMaserBoundaryTEST::checkBoundaryAfterParticlesMove(), FixedClusterInsertionBoundary::checkBoundaryBeforeTimeStep(), InsertionBoundary::checkBoundaryBeforeTimeStep(), RandomClusterInsertionBoundary::checkBoundaryBeforeTimeStep(), MeshTriangle::checkInteractions(), HGridOptimiser::checkLimit(), MercuryBase::checkParticleForInteractionLocal(), BaseCoupling< M, O >::checkResidual(), DPMBase::checkSettings(), checkTemplate(), Chute::Chute(), CircularPeriodicBoundary::CircularPeriodicBoundary(), Chute::cleanChute(), BaseCG::clear(), CLiveStatistics< T >::CLiveStatistics(), ClosedCSCRestart::ClosedCSCRestart(), ClosedCSCRun::ClosedCSCRun(), ClosedCSCStats::ClosedCSCStats(), ClosedCSCWalls::ClosedCSCWalls(), ConstantMassFlowMaserBoundary::closeMaser(), ClumpParticle::ClumpParticle(), ClusterGenerator::ClusterGenerator(), Coil::Coil(), commandLineCG(), helpers::compare(), compareParticles(), ChargedBondedInteraction::computeAdhesionForce(), LiquidBridgeBagheriInteraction::computeAdhesionForce(), DPMBase::computeAllForces(), LinearPlasticViscoelasticNormalSpecies::computeBondNumberMax(), SuperQuadricParticle::computeContactPoint(), ScaleCoupling< M, O >::computeCouplingForce(), ScrewsymmetricIntersectionOfWalls::computeDeltaZ(), computeFFc(), Box::computeFlow(), FrictionInteraction::computeFrictionForce(), BaseCluster::computeInternalStructure(), ParticleHandler::computeLargestParticle(), SuperQuadricParticle::computeMass(), ScaleCoupling< M, O >::computeNodalCouplingForces(), MeltableInteraction::computeNormalForce(), SinterInteraction::computeNormalForce(), DPMBase::computeOneTimeStep(), SCoupling< M, O >::computeOneTimeStepForSCoupling(), computeSimpleFFc(), HertzianSinterInteraction::computeSinterForce(), SlidingFrictionInteraction::computeSlidingSpring(), ParticleHandler::computeSmallestParticle(), HertzianSinterNormalSpecies::computeTimeStep(), SinterNormalSpecies::computeTimeStep(), Mercury3D::computeWallForces(), SmallMatrix< numberOfRows, numberOfColumns >::computeWedgeStuffVector(), ConstantMassFlowMaserBoundary::ConstantMassFlowMaserBoundary(), DPMBase::constructor(), MercuryLogo::constructTextAsParticles(), PSD::convertCumulativeNumberDistributionToCumulative(), PSD::convertCumulativeToCumulativeNumberDistribution(), PSD::convertProbabilityDensityNumberDistributionToProbabilityDensity(), PSD::convertProbabilityDensityToProbabilityDensityNumberDistribution(), PSDContinuous::convertSubtractiveNumberToVolume(), PSDContinuous::convertSubtractiveToCumulative(), PSDContinuous::convertSubtractiveVolumeToNumber(), AngledPeriodicBoundary::copy(), PolydisperseInsertionBoundary::copy(), CFile::copy(), CFile::copy_data(), CFile::copy_fstat(), SubcriticalMaserBoundaryTEST::copyExtraParticles(), MPIInteraction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::copyFromInteraction(), MixedSpecies< NormalForceSpecies, FrictionForceSpecies, AdhesiveForceSpecies >::copyInto(), Species< NormalForceSpecies, FrictionForceSpecies, AdhesiveForceSpecies >::copyInto(), SolidProblem< ELEMENT_TYPE >::countPinned(), CoupledBeam::CoupledBeam(), CoupledProblem::CoupledProblem(), Funnel::create_funnel(), Slide::create_rough_wall(), Chute::createBottom(), CurvyChute::createBottom(), helpers::createDirectory(), DomainHandler::createMesh(), BaseInteraction::createMPIInteractionDataArray(), BoundaryHandler::createObject(), ParticleHandler::createObject(), WallHandler::createObject(), PSDContinuous::createPSDFromRadiiAndProbabilities(), CSCInit::CSCInit(), CSCRestart::CSCRestart(), CSCStats::CSCStats(), CSCWalls::CSCWalls(), CubeDeletionBoundary::CubeDeletionBoundary(), PSD::cutHighSizeRatio(), PSD::cutoffAndSqueezeCumulativeDistribution(), PSD::cutoffCumulativeDistribution(), DataFiles::DataFiles(), SubcriticalMaserBoundary::deactivateMaser(), SubcriticalMaserBoundaryTEST::deactivateMaser(), Domain::debugInformation(), DPMBase::decompose(), BaseInteraction::deleteMPIInteractionDataArray(), DeletionBoundary::DeletionBoundary(), SmallMatrix< numberOfRows, numberOfColumns >::determinant(), MPIContainer::directReceive(), MPIContainer::directSend(), CGFields::DisplacementField::DisplacementField(), DomainHandler::DomainHandler(), Box::downwardPass(), ElementAnalysis::ElementAnalysis(), CGHandler::evaluateDataFiles(), CGHandler::evaluateRestartFiles(), SubcriticalMaserBoundaryTEST::extendBottom(), NurbsUtils::extendKnotVector(), FileReader::FileReader(), DPMBase::fillDomainWithParticles(), PeriodicBoundaryHandler::findNewParticle(), DPMBase::findNextExistingDataFile(), FixedClusterInsertionBoundary::FixedClusterInsertionBoundary(), MembraneSelfTest::fixMembraneEdges(), Domain::flushParticlesFromList(), LiquidMigrationLSInteraction::form(), LiquidMigrationWilletInteraction::form(), Quaternion::fromAxisAndAngle(), InsertionBoundary::generateParticle(), PolydisperseInsertionBoundary::generateParticle(), DPMBase::get1DParametersFromRunNumber(), DPMBase::get2DParametersFromRunNumber(), DPMBase::get3DParametersFromRunNumber(), SolidProblem< ELEMENT_TYPE >::get_x(), PSD::getAreaDx(), BaseForce::getBaseSpecies(), CoupledBeam::getBeamDeflection(), SphericalIndenter::getBedHeight(), CGFields::BaseFields::getCG(), SinterNormalSpecies::getCollisionTime(), LinearPlasticViscoelasticNormalSpecies::getCollisionTime(), LinearViscoelasticNormalSpecies::getCollisionTime(), SmallMatrix< numberOfRows, numberOfColumns >::getColumn(), Vec3D::getComponent(), SuperQuadricParticle::getContactPointPlanB(), NurbsSurface::getDistance(), AxisymmetricIntersectionOfWalls::getDistanceAndNormal(), HorizontalBaseScrew::getDistanceAndNormal(), ScrewsymmetricIntersectionOfWalls::getDistanceAndNormal(), BasicIntersectionOfWalls::getDistanceAndNormal(), SimpleDrumSuperquadrics::getDistanceAndNormal(), VChute::getDistanceAndNormal(), IntersectionOfWalls::getDistanceAndNormal(), Screw::getDistanceAndNormalLabCoordinates(), BaseWall::getDistanceNormalOverlapSuperquadric(), SimpleDrumSuperquadrics::getDistanceNormalOverlapSuperquadric(), SolidProblem< ELEMENT_TYPE >::getDomainSize(), BaseInteraction::getEffectiveMass(), BaseInteraction::getEffectiveRadius(), ChargedBondedInteraction::getElasticEnergy(), SCoupling< M, O >::getElementBoundingBox(), ParticleHandler::getFastestParticle(), ParticleHandler::getFastestParticleLocal(), BaseWall::getFurthestPointSuperQuadric(), ParticleHandler::getHighestPositionComponentParticle(), ParticleHandler::getHighestPositionComponentParticleLocal(), ParticleHandler::getHighestVelocityComponentParticle(), ParticleHandler::getHighestVelocityComponentParticleLocal(), BaseInteraction::getI(), BaseInteraction::getInteractionDetails(), BaseWall::getInteractionWith(), MeshTriangle::getInteractionWith(), BaseWall::getInteractionWithSuperQuad(), HGrid::getInvCellSize(), ParticleSpecies::getLargestInverseParticleMassLocal(), ParticleHandler::getLargestParticle(), PSD::getLengthDx(), getLinearFit(), LiquidMigrationPeriodicBoundaryInteraction::getLiquidBridgeVolume(), LiquidMigrationPeriodicBoundaryInteraction::getLiquidFilmVolume(), ParticleHandler::getLowestPositionComponentParticle(), ParticleHandler::getLowestPositionComponentParticleLocal(), ParticleHandler::getLowestVelocityComponentParticle(), ParticleHandler::getLowestVelocityComponentParticleLocal(), helpers::getMaximumNumberOfOMPThreads(), Sintering::getMeanPlasticOverlap(), regimeForceUnitTest::getMeanRelativeContactRadius(), SpeciesHandler::getMixedObject(), getName(), PossibleContact::getNext(), RNG::getNormalVariate(), PSD::getNumberDx(), ParticleHandler::getNumberOfRealObjectsLocal(), BaseHandler< T >::getObject(), BasicIntersectionOfWalls::getObject(), BasicUnionOfWalls::getObject(), BaseHandler< T >::getObjectById(), BaseHandler< T >::getObjectsById(), HGridOptimiser::getOptimalDistribution(), PossibleContact::getOtherParticle(), BaseInteraction::getOverlapVolume(), BaseInteraction::getP(), ParticleHandler::getParticleAttribute(), ParticleHandler::getParticleAttributeLocal(), InsertionBoundary::getParticleToCopy(), helpers::getPath(), TimeDependentPeriodicBoundary::getPlanewiseShift(), RNG::getPoissonVariate(), PossibleContact::getPrevious(), ParticleHandler::getPSD(), getPSDTypeName(), PSDContinuous::getQuantile(), PSD::getRadiusByQuantile(), RNG::getRandomNumber(), SmallMatrix< numberOfRows, numberOfColumns >::getRow(), helpers::getSaveCountFromNumberOfSavesAndTimeMaxAndTimeStep(), SCoupling< M, O >::getSCoupledElements(), ParticleHandler::getSmallestParticle(), DropletBoundary::getSpeciesHeatCapacity(), NonSphericalParticle::getSurfaceArea(), Time2Finish::getTime2Finish(), BaseCG::getTimeStep(), ChuteWithHopper::getTimeStepRatio(), AreaVTK::getTotalsurfaceAreaFromFile(), BaseParticle::getVolume(), SuperQuadricParticle::getVolume(), PSD::getVolumeDx(), ParticleSpecies::getVolumeFromRadius(), DPMBase::getWallsWriteVTK(), Mercury3DRestart::getWallTime(), BaseCG::getWidthTime(), helpers::gnuplot(), mathsFunc::goldenSectionSearch(), HGridOptimiser::goldenSectionSearch(), GranuDrum::GranuDrum(), GranuHeap::GranuHeap(), helpers::readFromCommandLine< std::string >(), HGrid::HGrid(), Mercury3D::hGridFindContactsWithTargetCell(), Mercury2D::hGridFindContactsWithTargetCell(), Mercury2D::hGridFindParticleContacts(), Mercury3D::hGridFindParticleContacts(), Mercury3D::hGridGetInteractingParticleList(), Mercury2D::hGridHasParticleContacts(), Mercury3D::hGridHasParticleContacts(), MercuryBase::hGridNeedsRebuilding(), MercuryBase::hGridRebuild(), HGridOptimiser::histNumberParticlesPerCell(), HorizontalBaseScrew::HorizontalBaseScrew(), HorizontalScrew::HorizontalScrew(), HstopCurve(), Indenter::Indenter(), InfiniteWall::InfiniteWall(), HGrid::info(), InitialConditions< SpeciesType >::InitialConditions(), HGridOptimiser::initialise(), ScaleCoupling< M, O >::initialiseCoupledElements(), HGridOptimiser::initialisePolyFunc(), DPMBase::initialiseSolve(), MembraneDemo::initializeSpecies(), MembraneSelfTest::initializeSpecies(), InsertionBoundary::insertParticle(), BaseCluster::insertParticles(), InsertionBoundary::insertParticles(), HGrid::insertParticleToHgrid(), InteractionHandler::InteractionHandler(), IntersectionOfWalls::IntersectionOfWalls(), BaseWall::intersectVTK(), HorizontalMixer::introduceParticlesAtWall(), ContactDetectionIntersectionOfWallsTest::introduceParticlesAtWall(), HorizontalMixer::introduceParticlesInDomain(), HorizontalMixer::introduceSingleParticle(), MatrixSymmetric3D::inverse(), SmallMatrix< numberOfRows, numberOfColumns >::inverse(), ConstantMassFlowMaserBoundary::isCopying(), LaserOnLayer::LaserOnLayer(), LawinenBox::LawinenBox(), LeesEdwardsBoundary::LeesEdwardsBoundary(), LeesEdwardsDemo::LeesEdwardsDemo(), LeesEdwardsSelfTest::LeesEdwardsSelfTest(), SmallVector< numberOfRows >::length(), LevelSetWall::LevelSetWall(), LiquidMigrationLSInteraction::LiquidMigrationLSInteraction(), LiquidMigrationLSSpecies::LiquidMigrationLSSpecies(), load(), LoadClumps(), Membrane::loadFromSTL(), loadingTest(), LoadMass(), LoadPD(), LoadPebbles(), SolidProblem< ELEMENT_TYPE >::loadSolidMesh(), LoadTOI(), Membrane::loadVertexPositions(), helpers::lookAhead(), main(), ChuteBottom::makeRoughBottom(), BaseVTKWriter< H >::makeVTKFileWithHeader(), VTKData::makeVTKFileWithHeader(), Membrane::Membrane(), Mercury2D::Mercury2D(), Mercury3D::Mercury3D(), MercuryBase::MercuryBase(), LinearPlasticViscoelasticNormalSpecies::mix(), MixedSpecies< NormalForceSpecies, FrictionForceSpecies, AdhesiveForceSpecies >::mixAll(), Species< NormalForceSpecies, FrictionForceSpecies, AdhesiveForceSpecies >::mixAll(), MixedSpecies< NormalForceSpecies, FrictionForceSpecies, AdhesiveForceSpecies >::MixedSpecies(), SubcriticalMaserBoundaryTEST::modifyPeriodicComplexity(), helpers::more(), TriangleMeshWall::moveVerticesToMatchVolume(), MovingWalls::MovingWalls(), MPIContainer::MPIContainer(), normalAndTangentialLoadingTest(), Vec3D::normalise(), NurbsWall::NurbsWall(), objectivenessTest(), BaseParticle::oldRead(), BinaryReader::openFile(), NumericalVector< T >::operator()(), SmallVector< numberOfRows >::operator()(), SmallMatrix< numberOfRows, numberOfColumns >::operator()(), NumericalVector< T >::operator*(), SmallMatrix< numberOfRows, numberOfColumns >::operator*(), operator*(), NumericalVector< T >::operator+(), NumericalVector< T >::operator+=(), NumericalVector< T >::operator-(), NumericalVector< T >::operator-=(), operator<<(), BoundaryHandler::operator=(), DomainHandler::operator=(), InteractionHandler::operator=(), IntersectionOfWalls::operator=(), ParticleHandler::operator=(), PeriodicBoundaryHandler::operator=(), SpeciesHandler::operator=(), TriangulatedWall::operator=(), WearableTriangulatedWall::operator=(), operator>>(), SmallMatrix< numberOfRows, numberOfColumns >::operator[](), NumericalVector< T >::operator[](), SmallVector< numberOfRows >::operator[](), CGFields::OrientationField::OrientationField(), STLReader::output(), DPMBase::outputInteractionDetails(), DPMBase::outputXBallsData(), LiquidMigrationSelfTest::outputXBallsData(), SuperQuadricParticle::overlapFromContactPoint(), ParabolaChute::ParabolaChute(), ParhamiMcMeekingSinterInteraction::ParhamiMcMeekingSinterInteraction(), ParticleBeam::ParticleBeam(), ParticleCreation::ParticleCreation(), ParticleHandler::ParticleHandler(), ParticleInclusion::ParticleInclusion(), particleParticleTest(), SubcriticalMaserBoundaryTEST::performActionsBeforeAddingParticles(), PeriodicBoundary::PeriodicBoundary(), PeriodicBoundaryHandler::PeriodicBoundaryHandler(), SolidProblem< ELEMENT_TYPE >::pinBoundaries(), SolidProblem< ELEMENT_TYPE >::pinBoundary(), PointIsAboveCurve(), PolydisperseInsertionBoundary::PolydisperseInsertionBoundary(), PossibleContactList::PossibleContactList(), SolidProblem< ELEMENT_TYPE >::prepareForSolve(), PSD::printPSD(), DPMBase::printTime(), LawinenBox::printTime(), GranuDrum::printTime(), GranuHeap::printTime(), ShearStage::printTime(), ClosedCSCRestart::printTime(), ClosedCSCRun::printTime(), ClosedCSCStats::printTime(), ClosedCSCWalls::printTime(), CSCInit::printTime(), CSCRestart::printTime(), CSCRun::printTime(), CSCStats::printTime(), CSCWalls::printTime(), CFDDEMCoupleTest::printTime(), HorizontalMixer::printTime(), NozzleDemo::printTime(), Drum::printTime(), RotatingDrumWet::printTime(), VerticalMixer::printTime(), ForceLawsMPI2Test::printTime(), LiquidMigrationMPI2Test::printTime(), ParticleInclusion::printTime(), ParticleBeam::printTime(), SilbertPeriodic::printTime(), CLiveStatistics< T >::printTime(), statistics_while_running< T >::printTime(), vibratedBed::printTime(), InitialBed::printTime(), LaserOnLayer::printTime(), MeltableForceLaw2SelfTest::printTime(), MeltableForceLawSelfTest::printTime(), OneParticleHeatingSelfTest::printTime(), OneParticleCoolingSelfTest::printTime(), ThermalConductionSelfTest::printTime(), RotatingDrumBidisperseInitialise::printTime(), RotatingDrumBidisperse::printTime(), SingleParticleSegregation::printTime(), ConstantMassFlowMaserBoundaryMixedSpeciesSelfTest::printTime(), ConstantMassFlowMaserSelfTest::printTime(), CubeDeletionBoundarySelfTest::printTime(), DeletionBoundarySelfTest::printTime(), DistributionSelfTest::printTime(), DistributionToPSDSelfTest::printTime(), InsertionBoundarySelfTest::printTime(), MultiplePSDSelfTest::printTime(), NozzleSelfTest::printTime(), PolydisperseInsertionBoundarySelfTest::printTime(), PSDManualInsertionSelfTest::printTime(), LiquidMigrationSelfTest::printTime(), TwoParticleElasticCollisionInteraction::printTime(), InitialConditions< SpeciesType >::printTime(), SinterPair::printTime(), SphericalIndenter::printTime(), DPM::printTime(), protectiveWall::printTime(), PSDSelfTest::printTime(), EvaporationAndHeatTest::printTime(), RandomClusterInsertionBoundarySelfTest::printTime(), HeatTransferUnitTest::printTime(), viscoElasticUnitTest::printTime(), LiquidMigrationPeriodicBoundaryInteraction::printTime(), MultiParticlesInsertion::printTime(), regimeForceUnitTest::printTime(), SetDistributionPhiNormalSelfTest::printTime(), TangentialSpringEnergyConservationUnitTest::printTime(), BaseCluster::printTime(), Chute::printTime(), PrintWallTimeMixin::printTime(), PeriodicBoundaryHandler::processLocalGhostParticles(), PeriodicBoundaryHandler::processLocalInteractionData(), Domain::processReceivedBoundaryParticleData(), PeriodicBoundaryHandler::processReceivedGhostParticleData(), Domain::processReceivedInteractionData(), HGridOptimiser::radius2Cell(), RandomClusterInsertionBoundary::RandomClusterInsertionBoundary(), FileReader::read(), csvReader::read(), BaseHandler< T >::read(), InteractionHandler::read(), MeltableNormalSpecies::read(), ConstantMassFlowMaserBoundary::read(), FluxBoundary::read(), SubcriticalMaserBoundary::read(), SubcriticalMaserBoundaryTEST::read(), Domain::read(), SuperQuadricParticle::read(), Membrane::read(), DPMBase::read(), Funnel::read(), Chute::read(), BoundaryHandler::readAndAddObject(), InteractionHandler::readAndAddObject(), SpeciesHandler::readAndAddObject(), ParticleHandler::readAndCreateObject(), WallHandler::readAndCreateObject(), WallHandler::readAndCreateOldObject(), DPMBase::readArguments(), helpers::readArrayFromCommandLine(), helpers::readArrayFromFile(), DPMBase::readDataFile(), helpers::readFromCommandLine(), helpers::readFromFile(), DPMBase::readNextArgument(), SilbertPeriodic::readNextArgument(), Mercury3DRestart::readNextArgument(), DPMBase::readNextDataFile(), DPMBase::readNextFStatFile(), SpeciesHandler::readOldObject(), DPMBase::readParAndIniFiles(), DPMBase::readRestartFile(), WallHandler::readTriangleWall(), helpers::readVectorFromCommandLine(), TriangulatedWall::readVTK(), MPIContainer::receive(), regimeForceUnitTest::regimeForceUnitTest(), RegimeSinterInteraction::RegimeSinterInteraction(), PossibleContactList::remove_ParticlePosibleContacts(), ScaleCoupling< M, O >::CoupledParticle::removeCoupledElement(), ParticleHandler::removeGhostObject(), BaseInteractable::removeInteraction(), BaseHandler< T >::removeLastObject(), BaseHandler< T >::removeObject(), ParticleHandler::removeObject(), BaseHandler< T >::removeObjects(), DPMBase::removeOldFiles(), ClosedCSCRestart::restart(), CSCRestart::restart(), CGHandler::restart(), RestrictedWall::RestrictedWall(), RotatingDrumBidisperse::RotatingDrumBidisperse(), RotatingDrumBidisperseInitialise::RotatingDrumBidisperseInitialise(), Detail::round(), FlowRule::run(), statistics_while_running< T >::run(), AngleOfRepose::run(), vibratedBed::run(), LiquidMigrationLSInteraction::rupture(), LiquidMigrationWilletInteraction::rupture(), CSCInit::save(), RotatingDrumBidisperseInitialise::save(), Membrane::saveAsSTL(), SaveCountUnitTest::SaveCountUnitTest(), ParticleHandler::saveNumberPSDtoCSV(), SolidProblem< ELEMENT_TYPE >::saveSolidMesh(), ClosedCSCWalls::saveWalls(), CSCWalls::saveWalls(), ScaleCoupledBeam::ScaleCoupledBeam(), SingleParticle< SpeciesType >::scaleMass(), InitialConditions< SpeciesType >::scaleMass(), PSD::scaleParticleSizeAuto(), Screw::Screw(), ScrewsymmetricIntersectionOfWalls::ScrewsymmetricIntersectionOfWalls(), MPIContainer::send(), Domain::sendAndReceiveCount(), StressStrainControlBoundary::set(), NurbsSurface::set(), ParhamiMcMeekingSinterSpecies::set(), PeriodicBoundary::set(), InfiniteWall::set(), Funnel::set_funfr(), AxisymmetricHopper::set_FunnelInflowHeight(), Chutebelt::set_particle_numbers(), Cstatic2d::set_particle_properties(), Cstatic3D::set_particle_properties(), Chutebelt::set_radiusLarge(), AngleOfRepose::set_study(), SilbertPeriodic::set_study(), Slide::set_Walls(), MeltableNormalSpecies::setActivationEnergy(), ChargedBondedSpecies::setAdhesionForceMax(), ReversibleAdhesiveSpecies::setAdhesionForceMax(), ChargedBondedSpecies::setAdhesionStiffness(), JKRAdhesiveSpecies::setAdhesionStiffness(), ReversibleAdhesiveSpecies::setAdhesionStiffness(), ThermalSpecies< NormalForceSpecies >::setAmbientDensity(), ThermalSpecies< NormalForceSpecies >::setAmbientDynamicViscosity(), HeatFluidCoupledSpecies< NormalForceSpecies >::setAmbientEquilibriumMoistureContent(), ThermalSpecies< NormalForceSpecies >::setAmbientHeatCapacity(), HeatFluidCoupledSpecies< NormalForceSpecies >::setAmbientHumidity(), MeltableNormalSpecies::setAmbientTemperature(), ThermalSpecies< NormalForceSpecies >::setAmbientTemperature(), ThermalSpecies< NormalForceSpecies >::setAmbientThermalConductivity(), HeatFluidCoupledSpecies< NormalForceSpecies >::setAmbientVapourConcentration(), SuperQuadricParticle::setAxesAndExponents(), CurvyChute::setBasalDensity(), CurvyChute::setBasalDisorder(), CurvyChute::setBasalSizeDispersity(), SolidProblem< ELEMENT_TYPE >::setBodyForceAsGravity(), SolidifyingLiquidMigrationWilletSpecies::setBondDissipation(), BondedSpecies::setBondDissipation(), ChargedBondedSpecies::setBondDissipation(), SolidifyingLiquidMigrationWilletSpecies::setBondForceMax(), BondedSpecies::setBondForceMax(), ChargedBondedSpecies::setBondForceMax(), WallVTKWriter::setCGWidth(), ChargedBondedSpecies::setCharge(), Chute::setChuteAngle(), Chute::setChuteAngleAndMagnitudeOfGravity(), ChuteWithHopper::setChuteLength(), BaseCluster::setClusterId(), SlidingFrictionSpecies::setCollisionTimeAndNormalAndTangentialRestitutionCoefficient(), SlidingFrictionSpecies::setCollisionTimeAndNormalAndTangentialRestitutionCoefficientNoDispt(), LinearViscoelasticNormalSpecies::setCollisionTimeAndRestitutionCoefficient(), SPHNormalSpecies::setCollisionTimeAndRestitutionCoefficient(), BaseCluster::setCollisionTimeOverTimeStep(), SinterLinNormalSpecies::setComplianceZero(), SinterNormalSpecies::setComplianceZero(), Vec3D::setComponent(), SinterNormalSpecies::setConstantC1(), BaseNormalForce::setConstantRestitution(), LiquidBridgeBagheriSpecies::setContactAngle(), LiquidBridgeClassicalWilletSpecies::setContactAngle(), LiquidBridgeWilletSpecies::setContactAngle(), LiquidMigrationLSSpecies::setContactAngle(), LiquidMigrationWilletSpecies::setContactAngle(), ScaleCoupling< M, O >::CoupledParticle::setCoupledElement(), MeltableNormalSpecies::setDeltaT(), SolidProblem< ELEMENT_TYPE >::setDensity(), ParticleSpecies::setDensity(), FlowRule::setDensityVariation(), AxisymmetricIntersectionOfWalls::setDisplayedSegments(), HertzianSinterNormalSpecies::setDissipation(), LinearPlasticViscoelasticNormalSpecies::setDissipation(), LinearViscoelasticNormalSpecies::setDissipation(), MeltableNormalSpecies::setDissipation(), SinterLinNormalSpecies::setDissipation(), SinterNormalSpecies::setDissipation(), LiquidMigrationLSSpecies::setDistributionCoefficient(), LiquidMigrationWilletSpecies::setDistributionCoefficient(), PSD::setDistributionNormal(), PSD::setDistributionPhiNormal(), DPMBase::setDomain(), BaseCluster::setDomainLimits(), HertzianBSHPViscoelasticNormalSpecies::setEffectiveElasticModulusAndRestitutionCoefficient(), MindlinSpecies::setEffectiveShearModulus(), SolidProblem< ELEMENT_TYPE >::setElasticModulus(), MeltableNormalSpecies::setElasticModulus(), BaseCluster::setEnergyRatioTolerance(), HeatFluidCoupledSpecies< NormalForceSpecies >::setEvaporationCoefficientA(), HeatFluidCoupledSpecies< NormalForceSpecies >::setEvaporationCoefficientB(), SuperQuadricParticle::setExponents(), CGFields::LiquidMigrationFields::setFields(), CGFields::OrientationField::setFields(), CGFields::StandardFieldsBinning::setFields(), Chute::setFixedParticleRadius(), Chute::setFixedParticleSpacing(), SinterLinNormalSpecies::setFluidity(), PolydisperseInsertionBoundary::setGenerandum(), AxisymmetricWallSelfTest::setGeometry(), BaseCG::setH(), ThermalSpecies< NormalForceSpecies >::setHeatCapacity(), ChuteWithHopper::setHopper(), ChuteWithHopper::setHopperShift(), BaseCG::setHX(), BaseCG::setHY(), BaseCG::setHZ(), BaseParticle::setIndSpecies(), BaseWall::setIndSpecies(), Chute::setInflowParticleRadius(), Chute::setInflowVelocity(), Chute::setInflowVelocityVariance(), ChargedBondedSpecies::setInteractionDistance(), LiquidBridgeWilletSpecies::setInteractionDistance(), ReversibleAdhesiveSpecies::setInteractionDistance(), DomainHandler::setInteractionDistance(), DPMBase::setInteractionsWriteVTK(), SinterNormalSpecies::setInverseSinterViscosity(), SolidProblem< ELEMENT_TYPE >::setIsPinned(), MeltableNormalSpecies::setLatentHeat(), HeatFluidCoupledSpecies< NormalForceSpecies >::setLatentHeatVaporization(), Quaternion< float >::setLength(), LiquidBridgeBagheriSpecies::setLiquidBridgeVolume(), LiquidBridgeClassicalWilletSpecies::setLiquidBridgeVolume(), LiquidBridgeWilletSpecies::setLiquidBridgeVolume(), LiquidMigrationLSSpecies::setLiquidBridgeVolumeMax(), LiquidMigrationWilletSpecies::setLiquidBridgeVolumeMax(), LiquidMigrationLSSpecies::setLiquidBridgeVolumeMin(), LiquidMigrationWilletSpecies::setLiquidBridgeVolumeMin(), HeatFluidCoupledSpecies< NormalForceSpecies >::setLiquidDensity(), DropletBoundary::setLiquidFilmVolumeMaxFraction(), DropletBoundary::setLiquidFilmVolumeMaxFractionFromRadiusFraction(), MeltableNormalSpecies::setLiquidHeatCapacity(), File::setlogarithmicSaveCount(), BaseParticle::setMass(), MeshTriangle::setMass(), BaseParticle::setMassForP3Statistics(), HeatFluidCoupledSpecies< NormalForceSpecies >::setMassTransferCoefficient(), MeltableNormalSpecies::setMaterialAbsorptivity(), MeltableNormalSpecies::setMaterialEmissivity(), DPMBase::setMax(), Chute::setMaxInflowParticleRadius(), DPMBase::setMeanVelocityAndKineticEnergy(), MeltableNormalSpecies::setMeltingTemperature(), DPMBase::setMin(), Chute::setMinInflowParticleRadius(), File::setName(), SolidProblem< ELEMENT_TYPE >::setName(), PossibleContact::setNextPosition(), DPMBase::setNumberOfDomains(), BaseCluster::setNumberOfInternalStructurePoints(), DPMBase::setNumberOfOMPThreads(), BaseCluster::setNumberOfParticles(), RandomClusterInsertionBoundary::setNumberOfParticlesPerCluster(), StatisticsVector< T >::setNZ(), SolidProblem< ELEMENT_TYPE >::setOomphGravity(), CylinderInsertionBoundary::setOrientation(), BaseVTKWriter< H >::setOutputDirectory(), SinterNormalSpecies::setParhamiMcKeeping(), DPMBase::setParticleDimensions(), Membrane::setParticleRadius(), InsertionBoundary::setParticleToCopy(), HertzianSinterNormalSpecies::setPlasticParameters(), LinearPlasticViscoelasticNormalSpecies::setPlasticParameters(), SinterNormalSpecies::setPlasticParameters(), IntersectionOfWalls::setPointsAndLines(), SolidProblem< ELEMENT_TYPE >::setPoissonRatio(), MindlinSpecies::setPoissonRatio(), MeltableNormalSpecies::setPoissonRatio(), FlowRule::setPolydispersity(), FixedClusterInsertionBoundary::setPositionsAndRadii(), PossibleContact::setPreviousPosition(), Calibration::setPSD(), Material::setPSD(), InsertionBoundary::setPSD(), PSD::setPSDFromCSV(), PSD::setPSDFromVector(), SimpleDrumSuperquadrics::setRadius(), SuperQuadricParticle::setRadius(), SphericalWall::setRadius(), BaseCluster::setRadiusCluster(), BaseClusterInsertionBoundary::setRadiusMicroParticle(), BaseCluster::setRadiusParticle(), Domain::setRange(), MeltableNormalSpecies::setRefViscosity(), FrictionSpecies::setRollingDissipation(), MindlinRollingTorsionSpecies::setRollingDissipation(), FrictionSpecies::setRollingFrictionCoefficient(), MindlinRollingTorsionSpecies::setRollingFrictionCoefficient(), FrictionSpecies::setRollingFrictionCoefficientStatic(), MindlinRollingTorsionSpecies::setRollingFrictionCoefficientStatic(), FrictionSpecies::setRollingStiffness(), Chute::setRoughBottomType(), SinterLinNormalSpecies::setSeparationDis(), SinterNormalSpecies::setSeparationDis(), LevelSetWall::setShapeCube(), LevelSetWall::setShapeCylinder(), LevelSetWall::setShapeDiamond(), LevelSetWall::setShapeFourSided(), LevelSetWall::setShapeSphere(), SinterLinNormalSpecies::setSinterAdhesion(), SinterNormalSpecies::setSinterAdhesion(), SinterNormalSpecies::setSinterForceAndTime(), HertzianSinterNormalSpecies::setSinterRate(), SinterLinNormalSpecies::setSinterRate(), SinterNormalSpecies::setSinterRate(), SinterLinNormalSpecies::setSinterType(), SinterNormalSpecies::setSinterType(), Penetration::setSize(), BaseCluster::setSizeDispersityParticle(), MindlinSpecies::setSlidingDissipation(), SlidingFrictionSpecies::setSlidingDissipation(), MindlinSpecies::setSlidingFrictionCoefficient(), SlidingFrictionSpecies::setSlidingFrictionCoefficient(), MindlinSpecies::setSlidingFrictionCoefficientStatic(), SlidingFrictionSpecies::setSlidingFrictionCoefficientStatic(), SlidingFrictionSpecies::setSlidingStiffness(), DPMBase::setSoftStop(), SolidProblem< ELEMENT_TYPE >::setSolidCubicMesh(), SolidifyingLiquidMigrationWilletSpecies::setSolidFraction(), MeltableNormalSpecies::setSolidHeatCapacity(), BaseCluster::setSpecies(), BaseInteractable::setSpecies(), Calibration::setSpecies(), Material::setSpecies(), Membrane::setSpringConstant(), LinearViscoelasticNormalSpecies::setStiffness(), SolidBag::setSuctionAsBodyForce(), CurvyChute::setSurface(), LiquidBridgeBagheriSpecies::setSurfaceTension(), LiquidBridgeClassicalWilletSpecies::setSurfaceTension(), LiquidBridgeWilletSpecies::setSurfaceTension(), LiquidMigrationLSSpecies::setSurfaceTension(), LiquidMigrationWilletSpecies::setSurfaceTension(), MeltableNormalSpecies::setSurfaceTension(), SinterLinNormalSpecies::setSurfTension(), SinterNormalSpecies::setSurfTension(), DPMBase::setSystemDimensions(), Thermal< Particle >::setTemperature(), ThermalSpecies< NormalForceSpecies >::setThermalConductivity(), MeltableNormalSpecies::setThermalConductivityCoefficient(), MeltableNormalSpecies::setThermalConvectionCoefficient(), ChuteBottom::setThickness(), Membrane::setThickness(), Thermal< Particle >::setTimeDependentTemperature(), DPMBase::setTimeMax(), DPMBase::setTimeStep(), BaseCG::setTimeStep(), FrictionSpecies::setTorsionDissipation(), MindlinRollingTorsionSpecies::setTorsionDissipation(), FrictionSpecies::setTorsionFrictionCoefficient(), MindlinRollingTorsionSpecies::setTorsionFrictionCoefficient(), FrictionSpecies::setTorsionFrictionCoefficientStatic(), MindlinRollingTorsionSpecies::setTorsionFrictionCoefficientStatic(), FrictionSpecies::setTorsionStiffness(), ChutePeriodic::setup(), LawinenBox::setupInitialConditions(), ClosedCSCWalls::setupInitialConditions(), CSCInit::setupInitialConditions(), CSCRun::setupInitialConditions(), CSCWalls::setupInitialConditions(), AirySavageHutter::setupInitialConditions(), MercuryLogo::setupInitialConditions(), SmoothChute::setupInitialConditions(), my_problem::setupInitialConditions(), free_cooling::setupInitialConditions(), restart::setupInitialConditions(), CFDDEMCoupleTest::setupInitialConditions(), NozzleDemo::setupInitialConditions(), RotatingDrumWet::setupInitialConditions(), Funnel::setupInitialConditions(), Binary::setupInitialConditions(), ForceLawsMPI2Test::setupInitialConditions(), LiquidMigrationMPI2Test::setupInitialConditions(), CubicCell::setupInitialConditions(), FreeCooling2DinWalls::setupInitialConditions(), LeesEdwardsDemo::setupInitialConditions(), MarbleRun::setupInitialConditions(), StressStrainControl::setupInitialConditions(), TimeDependentPeriodicBoundaryTest::setupInitialConditions(), SilbertPeriodic::setupInitialConditions(), InitialBed::setupInitialConditions(), MeltableForceLaw2SelfTest::setupInitialConditions(), MeltableForceLawSelfTest::setupInitialConditions(), OneParticleHeatingSelfTest::setupInitialConditions(), OneParticleCoolingSelfTest::setupInitialConditions(), GetDistanceAndNormalForIntersectionOfWalls::setupInitialConditions(), GetDistanceAndNormalForScrew::setupInitialConditions(), GetDistanceAndNormalForTriangleWall::setupInitialConditions(), Drum::setupInitialConditions(), Penetration::setupInitialConditions(), Silo::setupInitialConditions(), SegregationPeriodic::setupInitialConditions(), Chutebelt::setupInitialConditions(), DistributionPhiNormalSelfTest::setupInitialConditions(), NozzleSelfTest::setupInitialConditions(), NewtonsCradleSelfTest::setupInitialConditions(), SquarePacking::setupInitialConditions(), ParticleCreation::setupInitialConditions(), DPM::setupInitialConditions(), TwoParticleCollisionInteraction::setupInitialConditions(), TwoParticleElasticCollisionInteraction::setupInitialConditions(), CoilSelfTest::setupInitialConditions(), GetDistanceAndNormalForTriangleWalls::setupInitialConditions(), TriangulatedScrewSelfTest::setupInitialConditions(), TriangulatedStepWallSelfTest::setupInitialConditions(), TriangulatedWallSelfTest::setupInitialConditions(), UnionOfWalls::setupInitialConditions(), DrumRot::setupInitialConditions(), RotatingDrum::setupInitialConditions(), SingleParticle< SpeciesType >::setupInitialConditions(), InitialConditions< SpeciesType >::setupInitialConditions(), SphericalIndenter::setupInitialConditions(), Wall::setupInitialConditions(), BouncingSuperQuadric::setupInitialConditions(), EllipticalSuperQuadricCollision::setupInitialConditions(), SlidingSpheresUnitTest::setupInitialConditions(), SphericalSuperQuadricCollision::setupInitialConditions(), ContactDetectionNormalSpheresTest::setupInitialConditions(), ContactDetectionRotatedSpheresTest::setupInitialConditions(), VisualisationTest::setupInitialConditions(), ArcWallUnitTest::setupInitialConditions(), PSDSelfTest::setupInitialConditions(), HertzianSinterForceUnitTest::setupInitialConditions(), MovingWalls::setupInitialConditions(), MpiPeriodicBoundaryUnitTest::setupInitialConditions(), SetDistributionPhiNormalSelfTest::setupInitialConditions(), BaseCluster::setupInitialConditions(), Chute::setupInitialConditions(), ChuteBottom::setupInitialConditions(), MembraneDemo::setUpMembrane(), MembraneSelfTest::setUpMembrane(), CoupledBeam::setupMercury(), CoupledBeam::setupOomph(), CoupledProblem::setupOomph(), ChargedBondedSpecies::setVanDerWaalsForceMax(), InsertionBoundary::setVariableVolumeFlowRate(), BaseCluster::setVelocityDampingModulus(), LiquidMigrationLSSpecies::setViscosity(), LiquidMigrationWilletViscousSpecies::setViscosity(), DPMBase::setVTKOutputDirectory(), DPMBase::setWallsWriteVTK(), BaseCG::setWidthTime(), DPMBase::setXMax(), DPMBase::setXMin(), DPMBase::setYMax(), DPMBase::setYMin(), DPMBase::setZMax(), DPMBase::setZMin(), ShearStage::ShearStage(), Siegen::Siegen(), DPMBase::signalHandler(), SimpleDrumSuperquadrics::SimpleDrumSuperquadrics(), SineWall::SineWall(), SingleParticleIndenter::SingleParticleIndenter(), SinterPair::SinterPair(), Slide::Slide(), SmallMatrix< numberOfRows, numberOfColumns >::SmallMatrix(), SmallVector< numberOfRows >::SmallVector(), SolidBag::SolidBag(), SolidifyingLiquidMigrationWilletInteraction::SolidifyingLiquidMigrationWilletInteraction(), SolidProblem< ELEMENT_TYPE >::SolidProblem(), SmallMatrix< numberOfRows, numberOfColumns >::solve(), VolumeCoupling::solveFirstHalfTimeStep(), solveQuad(), ScaleCoupling< M, O >::solveScaleCoupling(), VolumeCoupling::solveSecondHalfTimeStep(), SolidProblem< ELEMENT_TYPE >::solveSteady(), SCoupling< M, O >::solveSurfaceCoupling(), SCoupling< M, O >::solveSurfaceCouplingFixedSolid(), SCoupling< M, O >::solveSurfaceCouplingForgiving(), SolidProblem< ELEMENT_TYPE >::solveUnsteady(), SolidProblem< ELEMENT_TYPE >::solveUnsteadyForgiving(), CGCoordinates::spaceEvenly(), Species< NormalForceSpecies, FrictionForceSpecies, AdhesiveForceSpecies >::Species(), SpeciesHandler::SpeciesHandler(), SphericalIndenter::SphericalIndenter(), SphericalWall::SphericalWall(), Statistics(), statistics_while_running< T >::statistics_while_running(), StressStrainControlBoundary::StressStrainControlBoundary(), helpers::stringFormat(), SubcriticalMaserBoundary::SubcriticalMaserBoundary(), SubcriticalMaserBoundaryTESTMPI2Test::SubcriticalMaserBoundaryTESTMPI2Test(), SuperQuadricParticle::SuperQuadricParticle(), SlidingSpheresUnitTest::test(), BoundingRadiusTester::test(), ContactDetectionNormalSpheresTest::test(), ContactDetectionRotatedSpheresTest::test(), ContactDetectionTester::test(), ContactDetectionWithWallTester::test(), InertiaTensorTester::test(), ShapeGradientHessianTester::test(), VolumeTest::test(), Packing::test(), HertzContactRestitutionUnitTest::test(), RNG::test(), test1(), test2(), testCGHandler(), ShapeGradientHessianTester::testCushion(), ShapeGradientHessianTester::testEllipsoid(), ContactDetectionTester::testEllipsoidsContact(), ContactDetectionWithWallTester::testEllipsoidsContact(), testPSD(), ShapeGradientHessianTester::testRoundedBeam(), ShapeGradientHessianTester::testSphere(), ContactDetectionTester::testSpheresContact(), ContactDetectionWithWallTester::testSpheresContact(), TimeDependentPeriodicBoundary::TimeDependentPeriodicBoundary(), TimeDependentPeriodicBoundary3DSelfTest::TimeDependentPeriodicBoundary3DSelfTest(), TimeDependentPeriodicBoundaryTest::TimeDependentPeriodicBoundaryTest(), transformMercuryToVTK(), Multipole::TranslateMultipoleExpansionTo(), TriangulatedWall::TriangulatedWall(), Tutorial11::Tutorial11(), Funnel::update_funnel(), ScaleCoupling< M, O >::updateCoupledElements(), DPMBase::updateGhostGrid(), PeriodicBoundaryHandler::updateMaserParticle(), Domain::updateParticlePosition(), PeriodicBoundaryHandler::updateParticles(), Domain::updateParticles(), PeriodicBoundaryHandler::updateParticleStatus(), SCoupling< M, O >::updateTractionOnFiniteElems(), MeshTriangle::updateVertexAndNormal(), TriangleWall::updateVertexAndNormal(), Box::upwardPass(), MercuryBase::userHGridCellSize(), PSD::validateCumulativeDistribution(), PSDContinuous::validateCumulativeDistribution(), PSD::validateProbabilityDensityDistribution(), MortaringValidationProblem< ELEMENT, NON_MORTAR_ELEMENT >::verify_mortared_nodes_coincide(), viscoElasticUnitTest::viscoElasticUnitTest(), wallParticleTest(), WearableNurbsWall::WearableNurbsWall(), WearableTriangulatedWall::WearableTriangulatedWall(), DataFiles::write(), InsertionBoundary::write(), PolydisperseInsertionBoundary::write(), Domain::write(), WallVTKWriter::writeCGFields(), SuperQuadricParticle::writeDebugMessageMiddleOfLoop(), SuperQuadricParticle::writeDebugMessageStep1(), SuperQuadricParticle::writeDebugMessageStep2(), SuperQuadricParticle::writeDebugMessageStep3(), SingleParticle< SpeciesType >::writeEneTimeStep(), Mercury3DRestarter::writeOutputFiles(), Mercury3DRestart::writeOutputFiles(), CFile::writeP4C(), CFile::writeP4P(), CFile::writeP4W(), Calibration::writePSDToFile(), DPMBase::writePythonFileForVTKVisualisation(), CFile::writeRestart(), GranuDrum::writeResults(), RotatingDrumBidisperse::writeResults(), HorizontalMixer::writeScript(), DataFiles::writeTimeStep(), helpers::writeToFile(), LevelSetWall::writeToFile(), ChutePeriodic::writeToLocalFolder(), SolidProblem< ELEMENT_TYPE >::writeToVTK(), BaseWall::writeVTK(), AxisymmetricIntersectionOfWalls::~AxisymmetricIntersectionOfWalls(), BaseBoundary::~BaseBoundary(), BaseCluster::~BaseCluster(), BaseHandler< T >::~BaseHandler(), BaseInteractable::~BaseInteractable(), BaseInteraction::~BaseInteraction(), BaseParticle::~BaseParticle(), BaseSpecies::~BaseSpecies(), BaseWall::~BaseWall(), BasicIntersectionOfWalls::~BasicIntersectionOfWalls(), BasicUnionOfWalls::~BasicUnionOfWalls(), BoundaryHandler::~BoundaryHandler(), CFile::~CFile(), ClusterGenerator::~ClusterGenerator(), Coil::~Coil(), CubeDeletionBoundary::~CubeDeletionBoundary(), DeletionBoundary::~DeletionBoundary(), DomainHandler::~DomainHandler(), DropletBoundary::~DropletBoundary(), FileReader::~FileReader(), HeaterBoundary::~HeaterBoundary(), HGrid::~HGrid(), HorizontalBaseScrew::~HorizontalBaseScrew(), HorizontalScrew::~HorizontalScrew(), InfiniteWall::~InfiniteWall(), InteractionHandler::~InteractionHandler(), IntersectionOfWalls::~IntersectionOfWalls(), LevelSetWall::~LevelSetWall(), LiquidMigrationLSInteraction::~LiquidMigrationLSInteraction(), LiquidMigrationLSSpecies::~LiquidMigrationLSSpecies(), MercuryBase::~MercuryBase(), MixedSpecies< NormalForceSpecies, FrictionForceSpecies, AdhesiveForceSpecies >::~MixedSpecies(), NurbsWall::~NurbsWall(), ParabolaChute::~ParabolaChute(), ParticleHandler::~ParticleHandler(), PeriodicBoundary::~PeriodicBoundary(), PeriodicBoundaryHandler::~PeriodicBoundaryHandler(), RestrictedWall::~RestrictedWall(), Screw::~Screw(), ScrewsymmetricIntersectionOfWalls::~ScrewsymmetricIntersectionOfWalls(), SimpleDrumSuperquadrics::~SimpleDrumSuperquadrics(), SineWall::~SineWall(), Species< NormalForceSpecies, FrictionForceSpecies, AdhesiveForceSpecies >::~Species(), SpeciesHandler::~SpeciesHandler(), SphericalWall::~SphericalWall(), SubcriticalMaserBoundaryTEST::~SubcriticalMaserBoundaryTEST(), SuperQuadricParticle::~SuperQuadricParticle(), TimeDependentPeriodicBoundary::~TimeDependentPeriodicBoundary(), TriangulatedWall::~TriangulatedWall(), WearableNurbsWall::~WearableNurbsWall(), and WearableTriangulatedWall::~WearableTriangulatedWall().
loggerOutput
LoggerOutput* loggerOutput = &loggerOutputDefaultImpl
Declaration of the output functions.
If the output needs to be redirected, please swap the loggerOutput pointer to your preferred LoggerOutput instance, and make sure this exists until AFTER an std::exit() invocation. (e.g. clean up with std::atexit())
Referenced by Logger< L, ASSERTS >::if(), main(), and Logger< L, ASSERTS >::operator()().
loggerOutputDefaultImpl
LoggerOutput loggerOutputDefaultImpl
Initial value:
= {printFatalError,
                                        printError,
                                        printWarn,
                                        printInfo,
                                        printInfo,
                                        printInfo
}
VERBOSE
LL<Log::VERBOSE> VERBOSE
Verbose information.
Information which is not useful to anybody except those looking for weird behaviour. These should however still be clear in meaning.
Example: Finished creating a particle.
Default behaviour: ignore.
Referenced by oomph::SCoupledElement< ELEMENT >::add_external_coupling_forces_to_residuals(), commandLineCG(), helpers::compare(), ScaleCoupling< M, O >::computeCouplingForce(), ScaleCoupling< M, O >::computeNodalCouplingForces(), NurbsSurface::getDistance(), ScaleCoupling< M, O >::initialiseCoupledElements(), load(), LoadClumps(), main(), BaseHandler< T >::read(), ScaleCoupling< M, O >::CoupledParticle::removeCoupledElement(), ScaleCoupling< M, O >::CoupledParticle::setCoupledElement(), ScaleCoupling< M, O >::updateCoupledElements(), and SCoupling< M, O >::updateTractionOnFiniteElems().
WARN
LL<Log::WARN> WARN
Warning log level.
Warning, as in, the program has detected a problem but does know a solution. The simulation can continue with this fix, but the user should look at fixing his / her simulation so this won't occur in the future.
Example: Setting a smaller Xmax than Xmin.
Default behaviour: log to std::cerr, returns afterwards.
Referenced by commandLineCG(), helpers::compare(), computeFFc(), computeSimpleFFc(), MPIInteraction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::copyFromInteraction(), MixedSpecies< NormalForceSpecies, FrictionForceSpecies, AdhesiveForceSpecies >::copyInto(), Species< NormalForceSpecies, FrictionForceSpecies, AdhesiveForceSpecies >::copyInto(), NurbsSurface::getDistance(), helpers::getMaximumNumberOfOMPThreads(), helpers::getPath(), helpers::gnuplot(), main(), BaseVTKWriter< H >::makeVTKFileWithHeader(), SmallMatrix< numberOfRows, numberOfColumns >::operator*(), operator*(), helpers::readFromFile(), BaseHandler< T >::removeLastObject(), solveQuad(), CGCoordinates::spaceEvenly(), transformMercuryToVTK(), and helpers::writeToFile().