MercuryDPM: OneDimMesh< ELEMENT > Class Template Reference
OneDimMesh< ELEMENT > Class Template Reference
A simple one dimensional mesh: uniformly spaced nodes in the domain x=0,1.
Public Member Functions
OneDimMesh (const unsigned &n_element, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Mesh Constructor. The argument is the desired number of elements.
void output_faces (std::ostream &outfile)
Output the face element.
void neighbour_finder (FiniteElement *const &bulk_element_pt, const int &face_index, const Vector< double > &s_bulk, FaceElement *&face_element_pt, Vector< double > &s_face)
OneDimMesh (const unsigned &n_element, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Mesh Constructor. The argument is the desired number of elements.
void output_faces (std::ostream &outfile)
Output the face element.
void neighbour_finder (FiniteElement *const &bulk_element_pt, const int &face_index, const Vector< double > &s_bulk, FaceElement *&face_element_pt, Vector< double > &s_face)
OneDimMesh (const unsigned &n_element)
Mesh Constructor. The argument is the desired number of elements.
Public Member Functions inherited from oomph::DGMesh
DGMesh ()
virtual ~DGMesh ()
void setup_face_neighbour_info (const bool &add_face_data_as_external=false)
void limit_slopes (SlopeLimiter *const &slope_limiter_pt)
Public Member Functions inherited from oomph::Mesh
Mesh ()
Default constructor.
Mesh (const Vector< Mesh * > &sub_mesh_pt)
void merge_meshes (const Vector< Mesh * > &sub_mesh_pt)
virtual void setup_boundary_element_info ()
virtual void setup_boundary_element_info (std::ostream &outfile)
virtual void reset_boundary_element_info (Vector< unsigned > &ntmp_boundary_elements, Vector< Vector< unsigned >> &ntmp_boundary_elements_in_region, Vector< FiniteElement * > &deleted_elements)
Virtual function to perform the reset boundary elements info rutines.
template<class BULK_ELEMENT >
void doc_boundary_coordinates (const unsigned &b, std::ofstream &the_file)
virtual void scale_mesh (const double &factor)
Mesh (const Mesh &dummy)=delete
Broken copy constructor.
void operator= (const Mesh &)=delete
Broken assignment operator.
virtual ~Mesh ()
Virtual Destructor to clean up all memory.
void flush_element_and_node_storage ()
void flush_element_storage ()
void flush_node_storage ()
Node *& node_pt (const unsigned long &n)
Return pointer to global node n.
Node * node_pt (const unsigned long &n) const
Return pointer to global node n (const version)
GeneralisedElement *& element_pt (const unsigned long &e)
Return pointer to element e.
GeneralisedElement * element_pt (const unsigned long &e) const
Return pointer to element e (const version)
const Vector< GeneralisedElement * > & element_pt () const
Return reference to the Vector of elements.
Vector< GeneralisedElement * > & element_pt ()
Return reference to the Vector of elements.
FiniteElement * finite_element_pt (const unsigned &e) const
Node *& boundary_node_pt (const unsigned &b, const unsigned &n)
Return pointer to node n on boundary b.
Node * boundary_node_pt (const unsigned &b, const unsigned &n) const
Return pointer to node n on boundary b.
void set_nboundary (const unsigned &nbound)
Set the number of boundaries in the mesh.
void remove_boundary_nodes ()
Clear all pointers to boundary nodes.
void remove_boundary_nodes (const unsigned &b)
void remove_boundary_node (const unsigned &b, Node *const &node_pt)
Remove a node from the boundary b.
void add_boundary_node (const unsigned &b, Node *const &node_pt)
Add a (pointer to) a node to the b-th boundary.
void copy_boundary_node_data_from_nodes ()
bool boundary_coordinate_exists (const unsigned &i) const
Indicate whether the i-th boundary has an intrinsic coordinate.
unsigned long nelement () const
Return number of elements in the mesh.
unsigned long nnode () const
Return number of nodes in the mesh.
unsigned ndof_types () const
Return number of dof types in mesh.
unsigned elemental_dimension () const
Return number of elemental dimension in mesh.
unsigned nodal_dimension () const
Return number of nodal dimension in mesh.
void add_node_pt (Node *const &node_pt)
Add a (pointer to a) node to the mesh.
void add_element_pt (GeneralisedElement *const &element_pt)
Add a (pointer to) an element to the mesh.
virtual void node_update (const bool &update_all_solid_nodes=false)
virtual void reorder_nodes (const bool &use_old_ordering=true)
virtual void get_node_reordering (Vector< Node * > &reordering, const bool &use_old_ordering=true) const
template<class BULK_ELEMENT , template< class > class FACE_ELEMENT>
void build_face_mesh (const unsigned &b, Mesh *const &face_mesh_pt)
unsigned self_test ()
Self-test: Check elements and nodes. Return 0 for OK.
void max_and_min_element_size (double &max_size, double &min_size)
double total_size ()
void check_inverted_elements (bool &mesh_has_inverted_elements, std::ofstream &inverted_element_file)
void check_inverted_elements (bool &mesh_has_inverted_elements)
unsigned check_for_repeated_nodes (const double &epsilon=1.0e-12)
Vector< Node * > prune_dead_nodes ()
unsigned nboundary () const
Return number of boundaries.
unsigned long nboundary_node (const unsigned &ibound) const
Return number of nodes on a particular boundary.
FiniteElement * boundary_element_pt (const unsigned &b, const unsigned &e) const
Return pointer to e-th finite element on boundary b.
Node * get_some_non_boundary_node () const
unsigned nboundary_element (const unsigned &b) const
Return number of finite elements that are adjacent to boundary b.
int face_index_at_boundary (const unsigned &b, const unsigned &e) const
virtual void dump (std::ofstream &dump_file, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
void dump (const std::string &dump_file_name, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
virtual void read (std::ifstream &restart_file)
Read solution from restart file.
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
void output (std::ostream &outfile)
Output for all elements.
void output (std::ostream &outfile, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output (FILE *file_pt)
Output for all elements (C-style output)
void output (FILE *file_pt, const unsigned &nplot)
Output at f(n_plot) points in each element (C-style output)
void output (const std::string &output_filename)
Output for all elements.
void output (const std::string &output_filename, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt)
Output a given Vector function at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt)
void output_boundaries (std::ostream &outfile)
Output the nodes on the boundaries (into separate tecplot zones)
void output_boundaries (const std::string &output_filename)
void assign_initial_values_impulsive ()
Assign initial values for an impulsive start.
void shift_time_values ()
void calculate_predictions ()
void set_nodal_and_elemental_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
virtual void set_mesh_level_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void set_consistent_pinned_values_for_continuation (ContinuationStorageScheme *const &continuation_stepper_pt)
Set consistent values for pinned data in continuation.
bool does_pointer_correspond_to_mesh_data (double *const &parameter_pt)
Does the double pointer correspond to any mesh data.
void set_nodal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
Set the timestepper associated with the nodal data in the mesh.
void set_elemental_internal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
virtual void compute_norm (double &norm)
virtual void compute_norm (Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Returns the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
bool is_mesh_distributed () const
Boolean to indicate if Mesh has been distributed.
OomphCommunicator * communicator_pt () const
void delete_all_external_storage ()
Wipe the storage for all externally-based elements.
Additional Inherited Members
Public Types inherited from oomph::Mesh
typedef void(FiniteElement::* SteadyExactSolutionFctPt) (const Vector< double > &x, Vector< double > &soln)
typedef void(FiniteElement::* UnsteadyExactSolutionFctPt) (const double &time, const Vector< double > &x, Vector< double > &soln)
Static Public Attributes inherited from oomph::DGMesh
static double FaceTolerance = 1.0e-10
Static Public Attributes inherited from oomph::Mesh
static Steady< 0 > Default_TimeStepper
The Steady Timestepper.
static bool Suppress_warning_about_empty_mesh_level_time_stepper_function
Static boolean flag to control warning about mesh level timesteppers.
Protected Member Functions inherited from oomph::Mesh
unsigned long assign_global_eqn_numbers (Vector< double * > &Dof_pt)
Assign (global) equation numbers to the nodes.
void describe_dofs (std::ostream &out, const std::string &current_string) const
void describe_local_dofs (std::ostream &out, const std::string &current_string) const
void assign_local_eqn_numbers (const bool &store_local_dof_pt)
Assign local equation numbers in all elements.
void convert_to_boundary_node (Node *&node_pt, const Vector< FiniteElement * > &finite_element_pt)
void convert_to_boundary_node (Node *&node_pt)
Protected Attributes inherited from oomph::Mesh
Vector< Vector< Node * > > Boundary_node_pt
bool Lookup_for_elements_next_boundary_is_setup
Vector< Vector< FiniteElement * > > Boundary_element_pt
Vector< Vector< int > > Face_index_at_boundary
Vector< Node * > Node_pt
Vector of pointers to nodes.
Vector< GeneralisedElement * > Element_pt
Vector of pointers to generalised elements.
std::vector< bool > Boundary_coordinate_exists
Detailed Description
template<class ELEMENT>
class OneDimMesh< ELEMENT >
A simple one dimensional mesh: uniformly spaced nodes in the domain x=0,1.
Constructor & Destructor Documentation
OneDimMesh() [1/3]
template<class ELEMENT > OneDimMesh< ELEMENT >::OneDimMesh (const unsigned & n_element, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper) inline
Mesh Constructor. The argument is the desired number of elements.
  {
   double X_min = 0.0;
   double X_max = 1.0;
   //Resize the vector of pointers to elements: there are n_element elements
   Element_pt.resize(n_element);
   //Loop over and construct all elements
   for(unsigned e=0;e<n_element;e++)
    {
     Element_pt[e] = new ELEMENT;
    }
   //Construct nodes and faces for the elements
   {
    //First element
    std::vector<bool> boundary_info(finite_element_pt(0)->nnode(),false);
    boundary_info[0] = true;
    dynamic_cast<ELEMENT*>(element_pt(0))
     ->construct_boundary_nodes_and_faces(this,boundary_info,time_stepper_pt);
    //Construct normal nodes for middle elements
    for(unsigned e=1;e<n_element-1;e++)
     {
      dynamic_cast<ELEMENT*>(element_pt(e))->
       construct_nodes_and_faces(this,time_stepper_pt);
     }
    //Final element
    unsigned n_node = finite_element_pt(n_element-1)->nnode();
    boundary_info.resize(n_node,false);
    boundary_info[0] = false;
    boundary_info[n_node-1] = true;
    dynamic_cast<ELEMENT*>(element_pt(n_element-1))
     ->construct_boundary_nodes_and_faces(this,boundary_info,time_stepper_pt);
   }
   //We've now created all the nodes -- let's set their positions:
   //Elements are uniformly spaced
   double el_length = (X_max - X_min)/(double)n_element;
   //Storage for fractional position of node
   Vector<double> s_fraction;
   //Loop over the elements again
   for(unsigned e=0;e<n_element;e++)
    {
     //Locally cache the element
     FiniteElement* elem_pt = finite_element_pt(e);
     //Locally cache the pointer to the first node
     Node* nod_pt = elem_pt->node_pt(0);
     //Set it's position
     nod_pt->x(0) = e*el_length;
     //Add to the Mesh's list of nodes
     Node_pt.push_back(nod_pt);
     unsigned n_node = elem_pt->nnode();
     //Now we must loop over all other nodes
     for(unsigned n=1;n<n_node;n++)
      {
       //Get the pointer to the n-th node
       nod_pt = elem_pt->node_pt(n);
       //Find the fractional position of the node
       elem_pt->local_fraction_of_node(n,s_fraction);
       //Now set the position of the node
       nod_pt->x(0) = (e + s_fraction[0])*el_length;
       //Add to the list of nodes in the mesh
       Node_pt.push_back(nod_pt);
      }
    }
   //Find the total number of nodes created
   const unsigned n_node = this->nnode();
   //There are two boundaries
   set_nboundary(2);
   //Boundary 0 contains the first node in the mesh:
   add_boundary_node(0,Node_pt[0]);
   //Boundary 1 contains the final node in the mesh:
   add_boundary_node(1,Node_pt[n_node-1]);
   //Check
   std::cout << "Constructed mesh with " << this->nelement()
             << " Elements and " << this->nnode() << " Nodes" << std::endl;
  } // End of constructor
References e(), oomph::FiniteElement::local_fraction_of_node(), n, oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::Node::x(), RayParam::X_max, and RayParam::X_min.
OneDimMesh() [2/3]
template<class ELEMENT > OneDimMesh< ELEMENT >::OneDimMesh (const unsigned & n_element, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper) inline
Mesh Constructor. The argument is the desired number of elements.
  {
   double X_min = -1.0;
   double X_max = 1.0;
   //Resize the vector of pointers to elements: there are n_element elements
   Element_pt.resize(n_element);
   //Loop over and construct all elements
   for(unsigned e=0;e<n_element;e++)
    {
     Element_pt[e] = new ELEMENT;
    }
   //Construct nodes and faces for the elements
   {
    //First element
    std::vector<bool> boundary_info(finite_element_pt(0)->nnode(),false);
    boundary_info[0] = true;
    dynamic_cast<ELEMENT*>(element_pt(0))
     ->construct_boundary_nodes_and_faces(this,boundary_info,time_stepper_pt);
    //Construct normal nodes for middle elements
    for(unsigned e=1;e<n_element-1;e++)
     {
      dynamic_cast<ELEMENT*>(element_pt(e))->
       construct_nodes_and_faces(this,time_stepper_pt);
     }
    //Final element
    unsigned n_node = finite_element_pt(n_element-1)->nnode();
    boundary_info.resize(n_node,false);
    boundary_info[0] = false;
    boundary_info[n_node-1] = true;
    dynamic_cast<ELEMENT*>(element_pt(n_element-1))
     ->construct_boundary_nodes_and_faces(this,boundary_info,time_stepper_pt);
   }
   //We've now created all the nodes -- let's set their positions:
   //Elements are uniformly spaced
   double el_length = (X_max - X_min)/(double)n_element;
   //Storage for fractional position of node
   Vector<double> s_fraction;
   //Loop over the elements again
   for(unsigned e=0;e<n_element;e++)
    {
     //Locally cache the element
     FiniteElement* elem_pt = finite_element_pt(e);
     //Locally cache the pointer to the first node
     Node* nod_pt = elem_pt->node_pt(0);
     //Set it's position
     nod_pt->x(0) = X_min + e*el_length;
     //Add to the Mesh's list of nodes
     Node_pt.push_back(nod_pt);
     unsigned n_node = elem_pt->nnode();
     //Now we must loop over all other nodes
     for(unsigned n=1;n<n_node;n++)
      {
       //Get the pointer to the n-th node
       nod_pt = elem_pt->node_pt(n);
       //Find the fractional position of the node
       elem_pt->local_fraction_of_node(n,s_fraction);
       //Now set the position of the node
       nod_pt->x(0) = X_min + (e + s_fraction[0])*el_length;
       //Add to the list of nodes in the mesh
       Node_pt.push_back(nod_pt);
      }
    }
   //Find the total number of nodes created
   const unsigned n_node = this->nnode();
   //There are two boundaries
   set_nboundary(2);
   //Boundary 0 contains the first node in the mesh:
   add_boundary_node(0,Node_pt[0]);
   //Boundary 1 contains the final node in the mesh:
   add_boundary_node(1,Node_pt[n_node-1]);
   //Check
   std::cout << "Constructed mesh with " << this->nelement()
             << " Elements and " << this->nnode() << " Nodes" << std::endl;
   //Now set up the neighbour information
   this->setup_face_neighbour_info();
  } // End of constructor
References e(), oomph::FiniteElement::local_fraction_of_node(), n, oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::Node::x(), RayParam::X_max, and RayParam::X_min.
OneDimMesh() [3/3]
template<class ELEMENT > OneDimMesh< ELEMENT >::OneDimMesh (const unsigned & n_element) inline
Mesh Constructor. The argument is the desired number of elements.
  {
   //Resize the vector of pointers to elements: there are n_element elements
   Element_pt.resize(n_element);
   //Construct the first element (Note the use of the template parameter)
   Element_pt[0] = new ELEMENT;
   //Construct the first node and add it to the Mesh::Node_pt vector
   //Note: The FiniteElement::construct_boundary_node(j) function
   //builds the element's j-th local node, and provides the functionality
   //that allows it to be located on a Mesh boundary -- essentially this
   //involves allocating additional storage to the Node.
   //The function obtains the Node's
   //characteristics (e.g. its spatial dimension, the number of
   //values to be stored, etc) from various virtual FiniteElement
   //member functions, such as FiniteElement::required_nvalue().
   //FiniteElement::construct_boundary_node(...) also
   //stores a pointer to the newly created Node in the element's own
   //Node_pt vector.
   //Finally, the function returns the pointer to the
   //newly created Node, so that it can be stored in the Mesh's Node_pt
   //vector, as done here:
   Node_pt.push_back(finite_element_pt(0)->construct_boundary_node(0));
   //Find the number of nodes per element (N.B. all elements are identical
   //so we can determine this value once and for all).
   unsigned n_node = finite_element_pt(0)->nnode();
   //Loop over the remaning nodes of the first element
   for(unsigned n=1;n<n_node;n++)
    {
     //Construct the next node and add it to the Mesh::Node_pt vector
     //Note that these interior nodes need not (and should not)
     //be boundary nodes, so they are created using the construct_node
     //function, which has the same interface as
     //construct_boundary_node()
     Node_pt.push_back(finite_element_pt(0)->construct_node(n));
    }
   //Loop over the remaining elements apart from the last
   for(unsigned e=1;e<(n_element-1);e++)
    {
     //Construct the e-th element
     Element_pt[e] = new ELEMENT;
     //The first local node of the e-th element is the last local node
     //of the (e-1)-th element. We MUST NOT construct the node twice.
     //Instead, we set the pointer in the e-th element to point to the
     //previously created node in the (e-1)-th element.
     finite_element_pt(e)->node_pt(0) =
       finite_element_pt(e-1)->node_pt(n_node-1);
     //Loop over the remaining nodes of the e-th element
     for(unsigned n=1;n<n_node;n++)
      {
       //Construct the next node and add it to the Mesh::Node_pt vector
       //Note that these interior nodes need not (and should not)
       //be boundary nodes, so they are created using the construct_node
       //function, which has the same interface as
       //construct_boundary_node()
       Node_pt.push_back(finite_element_pt(e)->construct_node(n));
      }
    } //End of loop over elements
   //Construct the final element
   Element_pt[n_element-1] = new ELEMENT;
   //The first local node of the final element is the last local node
   //of the penultimate element. We MUST NOT construct the node twice.
   //Instead, we set the pointer in the final element to point to the
   //previously created node in the penultimate element.
   finite_element_pt(n_element-1)->node_pt(0) =
    finite_element_pt(n_element-2)->node_pt(n_node-1);
   //Loop over the remaining central nodes of the final element
   for(unsigned n=1;n<(n_node-1);n++)
    {
     //Construct the next node and add it to the Mesh::Node_pt vector
     //Note that these interior nodes need not (and should not)
     //be boundary nodes, so they are created using the construct_node
     //function()
     Node_pt.push_back(finite_element_pt(n_element-1)->construct_node(n));
    }
   //Construct the final node and add it to the Mesh::Node_pt vector.
   //This node will be located on a boundary, and hence we use
   //the construct_boundary_node function.
   Node_pt.push_back(finite_element_pt(n_element-1)
                     ->construct_boundary_node(n_node-1));
   //We've now created all the nodes -- let's set their positions:
   //Find the total number of nodes
   unsigned n_global_node = nnode();
   //Loop over all nodes
   for(unsigned n=0;n<n_global_node;n++)
    {
     //Set the position of the node (equally spaced through the unit interval)
     Node_pt[n]->x(0) = double(n)/double(n_global_node-1);
    }
   //Set the boundary data:
   //There are two boundaries in this mesh
   set_nboundary(2);
   //Boundary 0 contains the first node in the mesh:
   add_boundary_node(0,Node_pt[0]);
   //Boundary 1 contains the final node in the mesh:
   add_boundary_node(1,Node_pt[n_global_node-1]);
  } // End of constructor
References e(), and n.
Member Function Documentation
neighbour_finder() [1/2]
template<class ELEMENT > void OneDimMesh< ELEMENT >::neighbour_finder (FiniteElement *const & bulk_element_pt, const int & face_index, const Vector< double > & s_bulk, FaceElement *& face_element_pt, Vector< double > & s_face) inline virtual
Reimplemented from oomph::DGMesh.
   {
    //The face coordinate is always a vector of size zero
    s_face.resize(0);
    //Not efficient but will work
    const unsigned n_element = this->nelement();
    for(unsigned e=0;e<n_element;e++)
     {
      if(finite_element_pt(e)==bulk_element_pt)
       {
        //Now what's up
        switch(face_index)
         {
          //left face
         case -1:
          //If not the first
          if(e!=0)
           {
            //Right face of previous element
            face_element_pt =
             dynamic_cast<ELEMENT*>(Element_pt[e-1])->face_element_pt(1);
           }
          //Otherwie make periodic
          else
           {
            face_element_pt =
             dynamic_cast<ELEMENT*>(Element_pt[n_element-1])->face_element_pt(1);
            //dynamic_cast<ELEMENT*>(Element_pt[e])->face_element_pt(0);
           }
          break;
          //Right face
         case 1:
          //If not the last
          if(e!=n_element-1)
           {
            //Left face of next element
            face_element_pt =
             dynamic_cast<ELEMENT*>(Element_pt[e+1])->face_element_pt(0);
           }
          //Otherwie make periodic
          else
           {
            face_element_pt =
             dynamic_cast<ELEMENT*>(Element_pt[0])->face_element_pt(0);
            //dynamic_cast<ELEMENT*>(Element_pt[e])->face_element_pt(1);
           }
          break;
          //Otherwise complain
         default:
          throw OomphLibError(
           "Coordinate is not on any face",
           OOMPH_CURRENT_FUNCTION,
           OOMPH_EXCEPTION_LOCATION);
         }
        //Break out of the for loop
        break;
       }
     }
   }
References e(), OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
neighbour_finder() [2/2]
template<class ELEMENT > void OneDimMesh< ELEMENT >::neighbour_finder (FiniteElement *const & bulk_element_pt, const int & face_index, const Vector< double > & s_bulk, FaceElement *& face_element_pt, Vector< double > & s_face) inline virtual
Reimplemented from oomph::DGMesh.
   {
    //The face coordinate is always a vector of size zero
    s_face.resize(0);
    //Not efficient but will work
    const unsigned n_element = this->nelement();
    for(unsigned e=0;e<n_element;e++)
     {
      if(finite_element_pt(e)==bulk_element_pt)
       {
        //Now what's up
        switch(face_index)
         {
          //left face
         case -1:
          //If not the first
          if(e!=0)
           {
            //Right face of previous element
            face_element_pt =
             dynamic_cast<ELEMENT*>(Element_pt[e-1])->face_element_pt(1);
           }
          //Otherwie just set the face to be the face of the first element
          else
           {
            face_element_pt =
             //dynamic_cast<ELEMENT*>(Element_pt[n_element-1])->face_element_pt(1);
            dynamic_cast<ELEMENT*>(Element_pt[e])->face_element_pt(0);
           }
          break;
          //Right face
         case 1:
          //If not the last
          if(e!=n_element-1)
           {
            //Left face of next element
            face_element_pt =
             dynamic_cast<ELEMENT*>(Element_pt[e+1])->face_element_pt(0);
           }
          //Otherwie make periodic
          else
           {
            face_element_pt =
             //dynamic_cast<ELEMENT*>(Element_pt[0])->face_element_pt(0);
            dynamic_cast<ELEMENT*>(Element_pt[e])->face_element_pt(1);
           }
          break;
          //Otherwise complain
         default:
          throw OomphLibError(
           "Coordinate is not on any face",
           OOMPH_CURRENT_FUNCTION,
           OOMPH_EXCEPTION_LOCATION);
         }
        //Break out of the for loop
        break;
       }
     }
   }
References e(), OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
output_faces() [1/2]
template<class ELEMENT > void OneDimMesh< ELEMENT >::output_faces (std::ostream & outfile) inline
Output the face element.
   {
    //Loop over the elements
    unsigned n_element = this->nelement();
    for(unsigned e=0;e<n_element;e++)
     {
      dynamic_cast<ELEMENT*>(element_pt(e))->output_faces(outfile);
     }
   }
References e().
output_faces() [2/2]
template<class ELEMENT > void OneDimMesh< ELEMENT >::output_faces (std::ostream & outfile) inline
Output the face element.
   {
    //Loop over the elements
    unsigned n_element = this->nelement();
    for(unsigned e=0;e<n_element;e++)
     {
      dynamic_cast<ELEMENT*>(element_pt(e))->output_faces(outfile);
     }
   }
References e().
The documentation for this class was generated from the following files:
one_d_advection.cc
one_d_euler.cc
one_d_poisson_generic_only.cc