MercuryDPM: LiquidMigrationWilletInteraction Class Reference
LiquidMigrationWilletInteraction Class Reference
Defines the liquid bridge willet interaction between two particles or walls.
#include <LiquidMigrationWilletInteraction.h>
Public Types
typedef LiquidMigrationWilletSpecies SpeciesType
An alias name for LiquidMigrationWilletSpecies data type.
Public Member Functions
LiquidMigrationWilletInteraction (BaseInteractable *P, BaseInteractable *I, unsigned timeStamp)
Constructor.
LiquidMigrationWilletInteraction ()
LiquidMigrationWilletInteraction (const LiquidMigrationWilletInteraction &p)
Copy constructor.
~LiquidMigrationWilletInteraction () override
Destructor.
void actionsOnErase () override
If an interaction needs to do something before it gets erased, add it here. E.g. Liquid bridges rupture at the end of their lifetime, and the liquid bridge volume has to be redistributed. The reason this action is not done in the destructor is that this action should not be taken when erasing ghost interactions.
void actionsAfterTimeStep () override
test if particle needs to be ruptured
void computeAdhesionForce ()
Computes the adhesive forces for liquid bridge Willet type of interaction.
void read (std::istream &is) override
Interaction read function, which accepts an std::istream as input.
void write (std::ostream &os) const override
Interaction print function, which accepts an std::ostream as input.
Mdouble getElasticEnergy () const override
Returns the amount of Elastic energy involved in an interaction. Basically used in case you want to write the elastic energy into an output file.
const LiquidMigrationWilletSpecies * getSpecies () const
Returns a pointer to the adhesive force species LiquidMigrationWilletSpecies.
std::string getBaseName () const
Returns the name of the interaction, see Interaction.h.
Mdouble getLiquidBridgeVolume () const
void setLiquidBridgeVolumeByEvaporation (Mdouble liquidBridgeVolume)
void addLiquidBridgeVolumeByEvaporation (Mdouble liquidBridgeVolume)
virtual void setLiquidBridgeVolume (Mdouble liquidBridgeVolume)
virtual void addLiquidBridgeVolume (Mdouble liquidBridgeVolume)
bool getWasInContact () const
void setWasInContact (bool wasInContact)
virtual void rupture ()
void form ()
Mdouble getRuptureDistance ()
unsigned getNumberOfFieldsVTK () const override
std::string getTypeVTK (unsigned i) const override
std::string getNameVTK (unsigned i) const override
std::vector< Mdouble > getFieldVTK (unsigned i) const override
Public Member Functions inherited from BaseInteraction
BaseInteraction (BaseInteractable *P, BaseInteractable *I, unsigned timeStamp)
A constructor takes the BaseInteractable objects which are interacting (come into contact) and time the interaction starts.
BaseInteraction ()
BaseInteraction (const BaseInteraction &p)
Copy constructor.
~BaseInteraction () override
The destructor. It removes this interactions from the objects that were interacting, and writes the time to a file when needed.
virtual void computeForce ()
Virtual function that contains the force law between the two objects interacting.
void read (std::istream &is) override
Interaction read function, which accepts an std::istream as input.
void write (std::ostream &os) const override
Interaction print function, which accepts an std::ostream as input.
void writeToFStat (std::ostream &os, Mdouble time) const
Writes forces data to the FStat file.
std::string getName () const override
Virtual function which allows interactions to be named.
void setDistance (Mdouble distance)
Sets the interaction distance between the two interacting objects.
void setNormal (Vec3D normal)
Sets the normal vector between the two interacting objects.
void setOverlap (Mdouble overlap)
Set the overlap between the two interacting object.
void setContactPoint (Vec3D contactPoint)
Set the location of the contact point between the two interacting objects.
void setTimeStamp (unsigned timeStamp)
Updates the time step of the interacting. Note, time steps used to find completed interactions.
void setSpecies (const BaseSpecies *species)
Set the Species of the interaction; note this can either be a Species or MixedSpecies.
void setP (BaseInteractable *P)
Sets the first object involved in the interaction (normally a particle).
void setI (BaseInteractable *I)
Sets the second object involved in the interaction (often particle or wall).
void importP (BaseInteractable *P)
Sets the first object involved in the interaction (normally a particle).
void importI (BaseInteractable *I)
Sets the second object involved in the interaction (often particle or wall).
Vec3D getIP () const
Vec3D getIC () const
Vec3D getCP () const
void setLagrangeMultiplier (Mdouble multiplier)
Mdouble getLagrangeMultiplier ()
void setHandler (InteractionHandler *handler)
Sets the pointer to the interaction hander which is storing this interaction.
InteractionHandler * getHandler () const
Gets a point to the interaction handlers to which this interaction belongs.
const Vec3D & getForce () const
Gets the current force (vector) between the two interacting objects.
const Vec3D & getTorque () const
Gets the current torque (vector) between the two interacting objects.
const Vec3D & getNormal () const
Gets the normal vector between the two interacting objects.
const Vec3D & getContactPoint () const
Gets constant reference to contact point (vector).
Mdouble getOverlap () const
Returns a Mdouble with the current overlap between the two interacting objects.
Mdouble getOverlapVolume () const
Returns the overlap volume between two interacting objects.
Mdouble getContactRadius () const
Returns a Mdouble with the current contact between the two interacting objects.
void removeFromHandler ()
Removes this interaction from its interaction hander.
void copySwitchPointer (const BaseInteractable *original, BaseInteractable *ghost) const
This copies the interactions of the original particle and replaces the original with the ghost copy.
void gatherContactStatistics ()
BaseInteractable * getP ()
Returns a pointer to first object involved in the interaction (normally a particle).
BaseInteractable * getI ()
Returns a pointer to the second object involved in the interaction (often a wall or a particle).
const BaseInteractable * getP () const
Returns a constant pointer to the first object involved in the interaction.
const BaseInteractable * getI () const
Returns a constant pointer to the second object involved in the interaction.
Mdouble getTimeStamp () const
Returns an Mdouble which is the time stamp of the interaction.
virtual void integrate (Mdouble timeStep)
integrates variables of the interaction which need to be integrate e.g. the tangential overlap.
virtual Mdouble getTangentialOverlap () const
get the length of the current tangential overlap
Mdouble getDistance () const
Returns an Mdouble which is the norm (length) of distance vector.
const Vec3D & getRelativeVelocity () const
Returns a constant reference to a vector of relative velocity.
Mdouble getNormalRelativeVelocity () const
Returns a double which is the norm (length) of the relative velocity vector.
Mdouble getAbsoluteNormalForce () const
Returns the absolute value of the norm (length) of the Normal force vector.
virtual BaseInteraction * copy () const =0
Makes a copy of the interaction and returns a pointer to the copy.
void setFStatData (std::fstream &fstat, BaseParticle *P, BaseWall *I)
void setFStatData (std::fstream &fstat, BaseParticle *P, BaseParticle *I)
unsigned int getMultiContactIdentifier () const
void setMultiContactIdentifier (unsigned int multiContactIdentifier_)
virtual void rotateHistory (Matrix3D &rotationMatrix)
When periodic particles are used, some interactions need certain history properties rotated (e.g. tangential springs). This is the function for that.
void addForce (Vec3D force)
add an force increment to the total force.
void addTorque (Vec3D torque)
add a torque increment to the total torque.
void setForce (Vec3D force)
set total force (this is used by the normal force, tangential forces are added use addForce)
void setTorque (Vec3D torque)
set the total force (this is used by the normal force, tangential torques are added use addTorque)
const BaseSpecies * getBaseSpecies () const
Return a constant point to BaseSpecies of the interaction.
virtual void createMPIType ()
virtual void * createMPIInteractionDataArray (unsigned int numberOfInteractions) const
virtual void deleteMPIInteractionDataArray (void *dataArray)
virtual void getMPIInteraction (void *historyDataArray, unsigned int index) const
copies the history interactions into the data array
virtual void getInteractionDetails (void *interactionDataArray, unsigned int index, unsigned int &identificationP, unsigned int &identificationI, bool &isWallInteraction, unsigned &timeStamp)
virtual void setMPIInteraction (void *interactionDataArray, unsigned int index, bool resetPointers)
void setBasicMPIInteractionValues (int P, int I, unsigned timeStamp, Vec3D force, Vec3D torque, bool isWallInteraction, bool resetPointers)
void setIdentificationP (unsigned int identification)
void setIdentificationI (int identification)
void setWallInteraction (bool flag)
unsigned int getIdentificationP ()
int getIdentificationI ()
bool isWallInteraction ()
virtual bool isBonded () const
Public Member Functions inherited from BaseObject
BaseObject ()=default
Default constructor.
BaseObject (const BaseObject &p)=default
Copy constructor, copies all the objects BaseObject contains.
virtual ~BaseObject ()=default
virtual destructor
virtual void moveInHandler (unsigned int index)
Except that it is virtual, it does the same thing as setIndex() does.
void setIndex (unsigned int index)
Allows one to assign an index to an object in the handler/container.
void setId (unsigned long id)
Assigns a unique identifier to each object in the handler (container) which remains constant even after the object is deleted from the container/handler.
unsigned int getIndex () const
Returns the index of the object in the handler.
unsigned int getId () const
Returns the unique identifier of any particular object.
void setGroupId (unsigned groupId)
unsigned getGroupId () const
Static Public Member Functions
static Mdouble getTotalLiquidFilmVolume (ParticleHandler &)
static Mdouble getTotalLiquidBridgeVolume (InteractionHandler &)
Private Member Functions
void distributeToOtherBridges (LiquidFilmParticle *particle, Mdouble distributableVolume)
Private Attributes
bool wasInContact_
A history parameter to store if the particles were in contact or not. Useful to compute adhesive forces.
Mdouble liquidBridgeVolume_
Additional Inherited Members
Protected Member Functions inherited from BaseInteraction
virtual const Vec3D getTangentialForce () const
Mdouble getEffectiveRadius () const
Returns a Mdouble to the effective radius of the interaction. (Not corrected for the overlap)
Mdouble getEffectiveMass () const
Returns a Mdouble to the effective radius of the interaction. (Not corrected for the overlap)
void setRelativeVelocity (Vec3D relativeVelocity)
set the relative velocity of the current of the interactions.
void setNormalRelativeVelocity (Mdouble normalRelativeVelocit)
set the normal component of the relative velocity.
void setAbsoluteNormalForce (Mdouble absoluteNormalForce)
the absolute values of the norm (length) of the normal force
virtual Mdouble getElasticEnergyAtEquilibrium (Mdouble adhesiveForce) const
virtual void reverseHistory ()
When periodic particles some interaction need certain history properties reversing. This is the function for that.
void writeInteraction (std::ostream &os, bool created) const
Writes information about a interaction to the interaction file.
Detailed Description
Defines the liquid bridge willet interaction between two particles or walls.
Member Typedef Documentation
SpeciesType
typedef LiquidMigrationWilletSpecies LiquidMigrationWilletInteraction::SpeciesType
An alias name for LiquidMigrationWilletSpecies data type.
Constructor & Destructor Documentation
LiquidMigrationWilletInteraction() [1/3]
LiquidMigrationWilletInteraction::LiquidMigrationWilletInteraction (BaseInteractable * P, BaseInteractable * I, unsigned timeStamp)
Constructor.
Parameters
[in] P
[in] I
[in] timeStamp
         : BaseInteraction(P, I, timeStamp)
 {
     liquidBridgeVolume_ = 0.0;
     wasInContact_ = false;
 #ifdef DEBUG_CONSTRUCTOR
     std::cout << "LiquidMigrationWilletInteraction::LiquidMigrationWilletInteraction() finished" << std::endl;
 #endif
 }
References liquidBridgeVolume_, and wasInContact_.
LiquidMigrationWilletInteraction() [2/3]
LiquidMigrationWilletInteraction::LiquidMigrationWilletInteraction ()
         : BaseInteraction()
 {
     liquidBridgeVolume_ = 0.0;
     wasInContact_ = false;
 #ifdef DEBUG_CONSTRUCTOR
     std::cout << "LiquidMigrationWilletInteraction::LiquidMigrationWilletInteraction() finished" << std::endl;
 #endif
 }
References liquidBridgeVolume_, and wasInContact_.
LiquidMigrationWilletInteraction() [3/3]
LiquidMigrationWilletInteraction::LiquidMigrationWilletInteraction (const LiquidMigrationWilletInteraction & p)
Copy constructor.
Parameters
[in] p
         : BaseInteraction(p)
 {
     liquidBridgeVolume_ = p.liquidBridgeVolume_;
     wasInContact_ = p.wasInContact_;
 #ifdef DEBUG_CONSTRUCTOR
     std::cout << "LiquidMigrationWilletInteraction::LiquidMigrationWilletInteraction(const LiquidMigrationWilletInteraction &p finished" << std::endl;
 #endif
 }
References liquidBridgeVolume_, p, and wasInContact_.
~LiquidMigrationWilletInteraction()
LiquidMigrationWilletInteraction::~LiquidMigrationWilletInteraction () override
Destructor.
 {
 #ifdef DEBUG_DESTRUCTOR
     std::cout << "LiquidMigrationWilletInteraction::~LiquidMigrationWilletInteraction() finished" << std::endl;
 #endif
 }
Member Function Documentation
actionsAfterTimeStep()
void LiquidMigrationWilletInteraction::actionsAfterTimeStep () override virtual
test if particle needs to be ruptured
Reimplemented from BaseInteraction.
 {
     if (wasInContact_)
     {
         if (-getOverlap() >= getRuptureDistance())
         {
             rupture();
         }
     }
     else
     {
         if (getOverlap() >= 0)
         {
             form();
         }
     }
 }
References form(), BaseInteraction::getOverlap(), getRuptureDistance(), rupture(), and wasInContact_.
actionsOnErase()
void LiquidMigrationWilletInteraction::actionsOnErase () override virtual
If an interaction needs to do something before it gets erased, add it here. E.g. Liquid bridges rupture at the end of their lifetime, and the liquid bridge volume has to be redistributed. The reason this action is not done in the destructor is that this action should not be taken when erasing ghost interactions.
Reimplemented from BaseInteraction.
 {
     rupture();
 };
References rupture().
addLiquidBridgeVolume()
void LiquidMigrationWilletInteraction::addLiquidBridgeVolume (Mdouble liquidBridgeVolume) virtual
Reimplemented in SolidifyingLiquidMigrationWilletInteraction.
 {
     liquidBridgeVolume_ += liquidBridgeVolume;
 }
References liquidBridgeVolume_.
Referenced by SolidifyingLiquidMigrationWilletInteraction::addLiquidBridgeVolume().
addLiquidBridgeVolumeByEvaporation()
void LiquidMigrationWilletInteraction::addLiquidBridgeVolumeByEvaporation (Mdouble liquidBridgeVolume)
 {
     liquidBridgeVolume_ += liquidBridgeVolume;
 }
References liquidBridgeVolume_.
computeAdhesionForce()
void LiquidMigrationWilletInteraction::computeAdhesionForce ()
Computes the adhesive forces for liquid bridge Willet type of interaction.
 {
     // Adding no capillary force for liquid bridge volume = 0
     if (getLiquidBridgeVolume() == 0) return;
     if (getOverlap() >= 0)
     {
         // if particles are in contact
         const LiquidMigrationWilletSpecies* species = getSpecies();
         const Mdouble effectiveRadius = 2.0 * getEffectiveRadius();
         const Mdouble fdotn = -2.0 * constants::pi * effectiveRadius * species->getSurfaceTension()
                               * std::cos(species->getContactAngle());
         addForce(getNormal() * fdotn);
     }
     else if (wasInContact_)
     {
         // if particles are not in contact, but within their interaction distance
         const LiquidMigrationWilletSpecies* species = getSpecies();
         const Mdouble effectiveRadius = 2.0 * getEffectiveRadius();
         const Mdouble s_c = -getOverlap() * std::sqrt(effectiveRadius / getLiquidBridgeVolume());
         const Mdouble fdotn = -2.0 * constants::pi * effectiveRadius * species->getSurfaceTension()
                               * std::cos(species->getContactAngle()) / (1 + (1.05 + 2.5 * s_c) * s_c);
         addForce(getNormal() * fdotn);
     }
 }
References BaseInteraction::addForce(), cos(), LiquidMigrationWilletSpecies::getContactAngle(), BaseInteraction::getEffectiveRadius(), getLiquidBridgeVolume(), BaseInteraction::getNormal(), BaseInteraction::getOverlap(), getSpecies(), LiquidMigrationWilletSpecies::getSurfaceTension(), constants::pi, sqrt(), and wasInContact_.
Referenced by LiquidMigrationWilletViscousInteraction::computeAdhesionForce().
distributeToOtherBridges()
void LiquidMigrationWilletInteraction::distributeToOtherBridges (LiquidFilmParticle * particle, Mdouble distributableVolume) private
 {
     // Get the other valid liquid bridges that the particle has.
     std::vector<LiquidMigrationWilletInteraction*> bridges;
     for (auto i : particle->getInteractions())
     {
         auto j = dynamic_cast<LiquidMigrationWilletInteraction*>(i);
         if (j != this && j != nullptr && j->getLiquidBridgeVolume() != 0.0)
             bridges.push_back(j);
     }
     // When there are no other bridges, the particle should get all the liquid.
     if (bridges.empty())
         particle->addLiquidVolume(distributableVolume);
     else
     {
         // Calculate the particle and bridge volumes from to the distribution coefficient and the number of bridges.
         particle->addLiquidVolume(distributableVolume * (1.0 - getSpecies()->getDistributionCoefficient()));
         Mdouble bridgeVolume = distributableVolume * getSpecies()->getDistributionCoefficient() / bridges.size();
         for (auto i : bridges)
         {
             // Add liquid to the bridge, but keep within maximum. Any excess liquid is added to the particle.
             Mdouble excess = std::max(i->getLiquidBridgeVolume() + bridgeVolume - getSpecies()->getLiquidBridgeVolumeMax(), 0.0);
             i->addLiquidBridgeVolume(bridgeVolume - excess);
             particle->addLiquidVolume(excess);
         }
     }
 }
References LiquidFilm< Particle >::addLiquidVolume(), LiquidMigrationWilletSpecies::getDistributionCoefficient(), getSpecies(), i, j, and max.
Referenced by rupture().
form()
void LiquidMigrationWilletInteraction::form ()
 {
     //form a bridge
     //todo: extend to neighbours
     wasInContact_ = true;
     auto species = getSpecies();
     auto P = dynamic_cast<LiquidFilmParticle*>(getP());
     auto I = dynamic_cast<LiquidFilmParticle*>(getI());
     if (P == nullptr) //if P is a wall
     {
         logger(ERROR,"In LiquidMigrationWilletInteraction::form, P should be a particle");
     }
     else if (I == nullptr) //if I is a wall
     {
         // Don't form a bridge when the volume is below the minimum bridge volume.
         if (P->getLiquidVolume() < species->getLiquidBridgeVolumeMin())
             return;
         // Don't exceed the maximum bridge volume. Remaining liquid will be kept in the particle.
         Mdouble liquidBridgeVolume = std::min(species->getLiquidBridgeVolumeMax(), P->getLiquidVolume());
         setLiquidBridgeVolume(liquidBridgeVolume);
         P->addLiquidVolume(-liquidBridgeVolume);
     }
     else //if P and I are particles
     {
         Mdouble distributableLiquidVolume = P->getLiquidVolume() + I->getLiquidVolume();
         // Don't form a bridge when the volume is below the minimum bridge volume.
         if (distributableLiquidVolume <= species->getLiquidBridgeVolumeMin())
             return;
         // Don't exceed the maximum bridge volume. Remaining liquid will be kept in the particles.
         Mdouble pFraction = P->getLiquidVolume() / distributableLiquidVolume;
         Mdouble liquidBridgeVolume = std::min(species->getLiquidBridgeVolumeMax(), distributableLiquidVolume);
         setLiquidBridgeVolume(liquidBridgeVolume);
         P->addLiquidVolume(-pFraction * liquidBridgeVolume);
         I->addLiquidVolume(-(1.0 - pFraction) * liquidBridgeVolume);
     }
 }
References ERROR, BaseInteraction::getI(), BaseInteraction::getP(), getSpecies(), I, logger, min, Global_Physical_Variables::P, setLiquidBridgeVolume(), and wasInContact_.
Referenced by actionsAfterTimeStep().
getBaseName()
std::string LiquidMigrationWilletInteraction::getBaseName () const
Returns the name of the interaction, see Interaction.h.
Returns
std::string
 {
     return "LiquidMigrationWillet";
 }
Referenced by SolidifyingLiquidMigrationWilletInteraction::getBaseName().
getElasticEnergy()
Mdouble LiquidMigrationWilletInteraction::getElasticEnergy () const override virtual
Returns the amount of Elastic energy involved in an interaction. Basically used in case you want to write the elastic energy into an output file.
Returns
Mdouble
Todo:
TW
Reimplemented from BaseInteraction.
Reimplemented in SolidifyingLiquidMigrationWilletInteraction.
 {
     return 0.0;
 }
getFieldVTK()
std::vector< Mdouble > LiquidMigrationWilletInteraction::getFieldVTK (unsigned i) const override virtual
Reimplemented from BaseInteraction.
Reimplemented in SolidifyingLiquidMigrationWilletInteraction.
 {
     return std::vector<Mdouble>(1, cbrt(getLiquidBridgeVolume()));
 }
References Eigen::numext::cbrt(), and getLiquidBridgeVolume().
getLiquidBridgeVolume()
Mdouble LiquidMigrationWilletInteraction::getLiquidBridgeVolume () const
 {
     return liquidBridgeVolume_;
 }
References liquidBridgeVolume_.
Referenced by computeAdhesionForce(), SolidifyingLiquidMigrationWilletInteraction::computeAdhesionForce(), getFieldVTK(), SolidifyingLiquidMigrationWilletInteraction::getFieldVTK(), LiquidMigrationPeriodicBoundaryInteraction::getLiquidBridgeVolume(), getRuptureDistance(), LiquidMigrationSelfTest::printTime(), and rupture().
getNameVTK()
std::string LiquidMigrationWilletInteraction::getNameVTK (unsigned i) const override virtual
Reimplemented from BaseInteraction.
Reimplemented in SolidifyingLiquidMigrationWilletInteraction.
 {
     return "liquidBridgeRadius";
 }
getNumberOfFieldsVTK()
unsigned LiquidMigrationWilletInteraction::getNumberOfFieldsVTK () const override virtual
writes extra information to the VTK output
Reimplemented from BaseInteraction.
Reimplemented in SolidifyingLiquidMigrationWilletInteraction.
 {
     return 1;
 }
getRuptureDistance()
Mdouble LiquidMigrationWilletInteraction::getRuptureDistance ()
 {
     const LiquidMigrationWilletSpecies* species = getSpecies();
     return (1.0 + 0.5 * species->getContactAngle()) * cbrt(getLiquidBridgeVolume());
 }
References Eigen::numext::cbrt(), LiquidMigrationWilletSpecies::getContactAngle(), getLiquidBridgeVolume(), and getSpecies().
Referenced by actionsAfterTimeStep().
getSpecies()
const LiquidMigrationWilletSpecies * LiquidMigrationWilletInteraction::getSpecies () const
Returns a pointer to the adhesive force species LiquidMigrationWilletSpecies.
Returns
const LiquidMigrationWilletSpecies*
 {
     return static_cast<const LiquidMigrationWilletSpecies*>(getBaseSpecies()->getAdhesiveForce());
 }
References BaseSpecies::getAdhesiveForce(), and BaseInteraction::getBaseSpecies().
Referenced by computeAdhesionForce(), distributeToOtherBridges(), form(), and getRuptureDistance().
getTotalLiquidBridgeVolume()
Mdouble LiquidMigrationWilletInteraction::getTotalLiquidBridgeVolume (InteractionHandler & h) static
 {
     Mdouble volume = 0;
     for (auto i : h)
     {
         auto l = dynamic_cast<LiquidMigrationWilletInteraction*>(i);
         if (l)
         {
             volume += l->getLiquidBridgeVolume();
         }
     }
     return volume;
 }
References i.
getTotalLiquidFilmVolume()
Mdouble LiquidMigrationWilletInteraction::getTotalLiquidFilmVolume (ParticleHandler & h) static
 {
     Mdouble volume = 0;
     for (auto p : h)
     {
         auto l = dynamic_cast<LiquidFilmParticle*>(p);
         if (l)
         {
             volume += l->getLiquidVolume();
         }
     }
     return volume;
 }
References p.
getTypeVTK()
std::string LiquidMigrationWilletInteraction::getTypeVTK (unsigned i) const override virtual
Reimplemented from BaseInteraction.
Reimplemented in SolidifyingLiquidMigrationWilletInteraction.
 {
     return "Float32";
 }
getWasInContact()
bool LiquidMigrationWilletInteraction::getWasInContact () const
 {
     return wasInContact_;
 }
References wasInContact_.
Referenced by LiquidMigrationWilletViscousInteraction::computeAdhesionForce().
read()
void LiquidMigrationWilletInteraction::read (std::istream & is) override virtual
Interaction read function, which accepts an std::istream as input.
Parameters
[in,out] is
Implements BaseObject.
Reimplemented in SolidifyingLiquidMigrationWilletInteraction.
 {
     std::string dummy;
     is >> dummy >> wasInContact_;
     is >> dummy >> liquidBridgeVolume_;
 }
References liquidBridgeVolume_, oomph::Global_string_for_annotation::string(), and wasInContact_.
Referenced by SolidifyingLiquidMigrationWilletInteraction::read().
rupture()
void LiquidMigrationWilletInteraction::rupture () virtual
Reimplemented in SolidifyingLiquidMigrationWilletInteraction.
 {
     // remove the contact history
     wasInContact_ = false;
     //if the bridge is already empty, do nothing
     if (getLiquidBridgeVolume() == 0.0)
         return;
     //else rupture a bridge
     auto P = dynamic_cast<LiquidFilmParticle*>(getP());
     auto I = dynamic_cast<LiquidFilmParticle*>(getI());
     if (P == nullptr) //if P is a wall
     {
         logger(ERROR,"In LiquidMigrationWilletInteraction::rupture, P should be a particle");
     }
     else if (I == nullptr) //if I is a wall
     {
         distributeToOtherBridges(P, getLiquidBridgeVolume());
         setLiquidBridgeVolume(0.0);
     }
     else //if P and I are particles
     {
         distributeToOtherBridges(P, 0.5 * getLiquidBridgeVolume());
         distributeToOtherBridges(I, 0.5 * getLiquidBridgeVolume());
         setLiquidBridgeVolume(0.0);
     }
 }
References distributeToOtherBridges(), ERROR, BaseInteraction::getI(), getLiquidBridgeVolume(), BaseInteraction::getP(), I, logger, Global_Physical_Variables::P, setLiquidBridgeVolume(), and wasInContact_.
Referenced by actionsAfterTimeStep(), actionsOnErase(), and SolidifyingLiquidMigrationWilletInteraction::rupture().
setLiquidBridgeVolume()
void LiquidMigrationWilletInteraction::setLiquidBridgeVolume (Mdouble liquidBridgeVolume) virtual
Reimplemented in SolidifyingLiquidMigrationWilletInteraction.
 {
     liquidBridgeVolume_ = liquidBridgeVolume;
 }
References liquidBridgeVolume_.
Referenced by form(), rupture(), and SolidifyingLiquidMigrationWilletInteraction::setLiquidBridgeVolume().
setLiquidBridgeVolumeByEvaporation()
void LiquidMigrationWilletInteraction::setLiquidBridgeVolumeByEvaporation (Mdouble liquidBridgeVolume)
 {
     liquidBridgeVolume_ = liquidBridgeVolume;
 }
References liquidBridgeVolume_.
setWasInContact()
void LiquidMigrationWilletInteraction::setWasInContact (bool wasInContact)
 {
     wasInContact_ = wasInContact;
 }
References wasInContact_.
write()
void LiquidMigrationWilletInteraction::write (std::ostream & os) const override virtual
Interaction print function, which accepts an std::ostream as input.
Parameters
[in,out] os
Implements BaseObject.
Reimplemented in SolidifyingLiquidMigrationWilletInteraction.
 {
     os
             << " wasInContact " << wasInContact_
             << " liquidBridgeVolume " << liquidBridgeVolume_;
 }
References liquidBridgeVolume_, and wasInContact_.
Referenced by SolidifyingLiquidMigrationWilletInteraction::write().
Member Data Documentation
liquidBridgeVolume_
Mdouble LiquidMigrationWilletInteraction::liquidBridgeVolume_ private
Referenced by addLiquidBridgeVolume(), addLiquidBridgeVolumeByEvaporation(), getLiquidBridgeVolume(), LiquidMigrationWilletInteraction(), read(), setLiquidBridgeVolume(), setLiquidBridgeVolumeByEvaporation(), and write().
wasInContact_
bool LiquidMigrationWilletInteraction::wasInContact_ private
A history parameter to store if the particles were in contact or not. Useful to compute adhesive forces.
Referenced by actionsAfterTimeStep(), computeAdhesionForce(), form(), getWasInContact(), LiquidMigrationWilletInteraction(), read(), rupture(), setWasInContact(), and write().
The documentation for this class was generated from the following files:
LiquidMigrationWilletInteraction.h
LiquidMigrationWilletInteraction.cc