MercuryDPM: FreeFallHertzMindlinUnitTest.cpp File Reference
FreeFallHertzMindlinUnitTest.cpp File Reference
#include "Mercury2D.h"
#include "Walls/InfiniteWall.h"
#include <Species/HertzianViscoelasticMindlinSpecies.h>
Classes
class FreeFallHertzMindlinUnitTest
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc , char * argv[])
 {
     logger(INFO, "Single particle bouncing vertically on the bottom plate");
     //The monosized 3 mm perfect-spherical tungsten particles are simulated.
     //Poisson Ratio is 0.28,
     //bulk density is 19250 Kg/m^3,
     //Young modulus 4.11E11 Pa,
     //restitution coefficient is 0.95,
     //Hertz-Mindlin model is used to describe the contact force between neighboring particles.
     Mdouble poissonRatio = 0.28;
     Mdouble density = 10000*6.0/constants::pi;
     Mdouble elasticModulus = 4.11e11; //100 times too soft
     Mdouble restitution = 0.5;
     // Make the problem and set the name
     FreeFallHertzMindlinUnitTest dpm;
     dpm.setName("FreeFallHertzMindlinUnitTest");
     dpm.setGravity(Vec3D(0,-10,0));
     dpm.setParticleDimensions(3);
     //Set the species of the particle and wall, and its properties
     HertzianViscoelasticMindlinSpecies species;
     species.setDensity(density);
     species.setEffectiveElasticModulusAndRestitutionCoefficient(elasticModulus, restitution);
     //https://en.wikipedia.org/wiki/Shear_modulus#References
     species.setEffectiveShearModulus(0.5 * elasticModulus / (1 + poissonRatio));
     species.setSlidingFrictionCoefficient(1.0);
     dpm.speciesHandler.copyAndAddObject(species);
     //set the parameters for the solver
     dpm.setSaveCount(40);
     dpm.fStatFile.setFileType(FileType::NO_FILE);
     dpm.wallHandler.setWriteVTK(FileType::ONE_FILE);
     Mdouble relativeVelocity = 0.1;
     Mdouble tc = species.getCollisionTime(2.0*dpm.radius, species.getDensity(), relativeVelocity);
     logger(INFO,"Collision time %", tc);
     dpm.setTimeStep(0.02*tc);
     dpm.setTimeMax(0.1);
     //solve the system, the single particle will now bounce on the plate
     dpm.solve(argc, argv);
     helpers::writeToFile("FreeFallHertzMindlinUnitTest.gnu",
                          "set xlabel 't'; p 'FreeFallHertzMindlinUnitTest.ene' u 1:(sqrt($3)) t 'sqrt(E_kin)' w lp");
     logger(INFO,"type 'gnuplot FreeFallHertzMindlinUnitTest.gnu' to check energy conservation");
 }
References BaseHandler< T >::copyAndAddObject(), UniformPSDSelfTest::density, DPMBase::fStatFile, ParticleSpecies::getDensity(), INFO, logger, NO_FILE, ONE_FILE, constants::pi, FreeFallHertzMindlinUnitTest::radius, ParticleSpecies::setDensity(), File::setFileType(), DPMBase::setGravity(), DPMBase::setName(), DPMBase::setParticleDimensions(), DPMBase::setSaveCount(), DPMBase::setTimeMax(), DPMBase::setTimeStep(), WallHandler::setWriteVTK(), DPMBase::solve(), DPMBase::speciesHandler, DPMBase::wallHandler, and helpers::writeToFile().