MercuryDPM: Eigen::TensorEvaluator< const TensorGeneratorOp< Generator, ArgType >, Device > Struct Template Reference
Eigen::TensorEvaluator< const TensorGeneratorOp< Generator, ArgType >, Device > Struct Template Reference
#include <TensorGenerator.h>
Classes
struct BlockIteratorState
Public Types
enum {
IsAligned = false , PacketAccess = (PacketType<CoeffReturnType, Device>::size > 1) , BlockAccess = true , PreferBlockAccess = true ,
CoordAccess = false , RawAccess = false
}
typedef TensorGeneratorOp< Generator, ArgType > XprType
typedef XprType::Index Index
typedef TensorEvaluator< ArgType, Device >::Dimensions Dimensions
typedef XprType::Scalar Scalar
typedef XprType::CoeffReturnType CoeffReturnType
typedef PacketType< CoeffReturnType, Device >::type PacketReturnType
typedef StorageMemory< CoeffReturnType, Device > Storage
typedef Storage::Type EvaluatorPointerType
typedef internal::TensorIntDivisor< Index > IndexDivisor
typedef internal::TensorBlockDescriptor< NumDims, Index > TensorBlockDesc
typedef internal::TensorBlockScratchAllocator< Device > TensorBlockScratch
typedef internal::TensorMaterializedBlock< CoeffReturnType, NumDims, Layout, Index > TensorBlock
Public Member Functions
EIGEN_STRONG_INLINE TensorEvaluator (const XprType &op, const Device &device)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Dimensions & dimensions () const
EIGEN_STRONG_INLINE bool evalSubExprsIfNeeded (EvaluatorPointerType)
EIGEN_STRONG_INLINE void cleanup ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType coeff (Index index) const
template<int LoadMode>
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketReturnType packet (Index index) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE internal::TensorBlockResourceRequirements getResourceRequirements () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorBlock block (TensorBlockDesc &desc, TensorBlockScratch &scratch, bool=false) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorOpCost costPerCoeff (bool) const
EIGEN_DEVICE_FUNC EvaluatorPointerType data () const
Static Public Attributes
static constexpr int NumDims = internal::array_size<Dimensions>::value
static constexpr int Layout = TensorEvaluator<ArgType, Device>::Layout
Protected Member Functions
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void extract_coordinates (Index index, array< Index, NumDims > &coords) const
Protected Attributes
const Device EIGEN_DEVICE_REF m_device
Dimensions m_dimensions
array< Index, NumDims > m_strides
array< IndexDivisor, NumDims > m_fast_strides
Generator m_generator
Member Typedef Documentation
CoeffReturnType
template<typename Generator , typename ArgType , typename Device > typedef XprType::CoeffReturnType Eigen::TensorEvaluator< const TensorGeneratorOp< Generator, ArgType >, Device >::CoeffReturnType
Dimensions
template<typename Generator , typename ArgType , typename Device > typedef TensorEvaluator<ArgType, Device>::Dimensions Eigen::TensorEvaluator< const TensorGeneratorOp< Generator, ArgType >, Device >::Dimensions
EvaluatorPointerType
template<typename Generator , typename ArgType , typename Device > typedef Storage::Type Eigen::TensorEvaluator< const TensorGeneratorOp< Generator, ArgType >, Device >::EvaluatorPointerType
Index
template<typename Generator , typename ArgType , typename Device > typedef XprType::Index Eigen::TensorEvaluator< const TensorGeneratorOp< Generator, ArgType >, Device >::Index
IndexDivisor
template<typename Generator , typename ArgType , typename Device > typedef internal::TensorIntDivisor<Index> Eigen::TensorEvaluator< const TensorGeneratorOp< Generator, ArgType >, Device >::IndexDivisor
PacketReturnType
template<typename Generator , typename ArgType , typename Device > typedef PacketType<CoeffReturnType, Device>::type Eigen::TensorEvaluator< const TensorGeneratorOp< Generator, ArgType >, Device >::PacketReturnType
Scalar
template<typename Generator , typename ArgType , typename Device > typedef XprType::Scalar Eigen::TensorEvaluator< const TensorGeneratorOp< Generator, ArgType >, Device >::Scalar
Storage
template<typename Generator , typename ArgType , typename Device > typedef StorageMemory<CoeffReturnType, Device> Eigen::TensorEvaluator< const TensorGeneratorOp< Generator, ArgType >, Device >::Storage
TensorBlock
template<typename Generator , typename ArgType , typename Device > typedef internal::TensorMaterializedBlock<CoeffReturnType, NumDims, Layout, Index> Eigen::TensorEvaluator< const TensorGeneratorOp< Generator, ArgType >, Device >::TensorBlock
TensorBlockDesc
template<typename Generator , typename ArgType , typename Device > typedef internal::TensorBlockDescriptor<NumDims, Index> Eigen::TensorEvaluator< const TensorGeneratorOp< Generator, ArgType >, Device >::TensorBlockDesc
TensorBlockScratch
template<typename Generator , typename ArgType , typename Device > typedef internal::TensorBlockScratchAllocator<Device> Eigen::TensorEvaluator< const TensorGeneratorOp< Generator, ArgType >, Device >::TensorBlockScratch
XprType
template<typename Generator , typename ArgType , typename Device > typedef TensorGeneratorOp<Generator, ArgType> Eigen::TensorEvaluator< const TensorGeneratorOp< Generator, ArgType >, Device >::XprType
Member Enumeration Documentation
anonymous enum
template<typename Generator , typename ArgType , typename Device > anonymous enum
Enumerator
IsAligned
PacketAccess
BlockAccess
PreferBlockAccess
CoordAccess
RawAccess
        {
     IsAligned = false,
     PacketAccess = (PacketType<CoeffReturnType, Device>::size > 1),
     BlockAccess = true,
     PreferBlockAccess = true,
     CoordAccess = false,  // to be implemented
     RawAccess = false
   };
Constructor & Destructor Documentation
TensorEvaluator()
template<typename Generator , typename ArgType , typename Device > EIGEN_STRONG_INLINE Eigen::TensorEvaluator< const TensorGeneratorOp< Generator, ArgType >, Device >::TensorEvaluator (const XprType & op, const Device & device) inline
       : m_device(device), m_generator(op.generator()) {
     TensorEvaluator<ArgType, Device> argImpl(op.expression(), device);
     m_dimensions = argImpl.dimensions();
     if (static_cast<int>(Layout) == static_cast<int>(ColMajor)) {
       m_strides[0] = 1;
       EIGEN_UNROLL_LOOP
       for (int i = 1; i < NumDims; ++i) {
         m_strides[i] = m_strides[i - 1] * m_dimensions[i - 1];
         if (m_strides[i] != 0) m_fast_strides[i] = IndexDivisor(m_strides[i]);
       }
     } else {
       m_strides[NumDims - 1] = 1;
       EIGEN_UNROLL_LOOP
       for (int i = NumDims - 2; i >= 0; --i) {
         m_strides[i] = m_strides[i + 1] * m_dimensions[i + 1];
         if (m_strides[i] != 0) m_fast_strides[i] = IndexDivisor(m_strides[i]);
       }
     }
   }
References Eigen::ColMajor, Eigen::TensorEvaluator< Derived, Device >::dimensions(), EIGEN_UNROLL_LOOP, i, Eigen::TensorEvaluator< Derived, Device >::Layout, and op.
Member Function Documentation
block()
template<typename Generator , typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorBlock Eigen::TensorEvaluator< const TensorGeneratorOp< Generator, ArgType >, Device >::block (TensorBlockDesc & desc, TensorBlockScratch & scratch, bool = false) const inline
{
     static const bool is_col_major = static_cast<int>(Layout) == static_cast<int>(ColMajor);
     // Compute spatial coordinates for the first block element.
     array<Index, NumDims> coords;
     extract_coordinates(desc.offset(), coords);
     array<Index, NumDims> initial_coords = coords;
     // Offset in the output block buffer.
     Index offset = 0;
     // Initialize output block iterator state. Dimension in this array are
     // always in inner_most -> outer_most order (col major layout).
     array<BlockIteratorState, NumDims> it;
     for (int i = 0; i < NumDims; ++i) {
       const int dim = is_col_major ? i : NumDims - 1 - i;
       it[i].size = desc.dimension(dim);
       it[i].stride = i == 0 ? 1 : (it[i - 1].size * it[i - 1].stride);
       it[i].span = it[i].stride * (it[i].size - 1);
       it[i].count = 0;
     }
     eigen_assert(it[0].stride == 1);
     // Prepare storage for the materialized generator result.
     const typename TensorBlock::Storage block_storage = TensorBlock::prepareStorage(desc, scratch);
     CoeffReturnType* block_buffer = block_storage.data();
     static const int packet_size = PacketType<CoeffReturnType, Device>::size;
     static const int inner_dim = is_col_major ? 0 : NumDims - 1;
     const Index inner_dim_size = it[0].size;
     const Index inner_dim_vectorized = inner_dim_size - packet_size;
     while (it[NumDims - 1].count < it[NumDims - 1].size) {
       Index i = 0;
       // Generate data for the vectorized part of the inner-most dimension.
       for (; i <= inner_dim_vectorized; i += packet_size) {
         for (Index j = 0; j < packet_size; ++j) {
           array<Index, NumDims> j_coords = coords;  // Break loop dependence.
           j_coords[inner_dim] += j;
           *(block_buffer + offset + i + j) = m_generator(j_coords);
         }
         coords[inner_dim] += packet_size;
       }
       // Finalize non-vectorized part of the inner-most dimension.
       for (; i < inner_dim_size; ++i) {
         *(block_buffer + offset + i) = m_generator(coords);
         coords[inner_dim]++;
       }
       coords[inner_dim] = initial_coords[inner_dim];
       // For the 1d tensor we need to generate only one inner-most dimension.
       if (NumDims == 1) break;
       // Update offset.
       for (i = 1; i < NumDims; ++i) {
         if (++it[i].count < it[i].size) {
           offset += it[i].stride;
           coords[is_col_major ? i : NumDims - 1 - i]++;
           break;
         }
         if (i != NumDims - 1) it[i].count = 0;
         coords[is_col_major ? i : NumDims - 1 - i] = initial_coords[is_col_major ? i : NumDims - 1 - i];
         offset -= it[i].span;
       }
     }
     return block_storage.AsTensorMaterializedBlock();
   }
References Eigen::internal::TensorMaterializedBlock< Scalar, NumDims, Layout, IndexType >::Storage::AsTensorMaterializedBlock(), Eigen::ColMajor, Eigen::internal::TensorMaterializedBlock< Scalar, NumDims, Layout, IndexType >::Storage::data(), Eigen::internal::TensorBlockDescriptor< NumDims, IndexType >::dimension(), eigen_assert, i, j, Eigen::TensorEvaluator< Derived, Device >::Layout, Eigen::internal::TensorBlockDescriptor< NumDims, IndexType >::offset(), Eigen::internal::TensorMaterializedBlock< Scalar, NumDims, Layout, IndexType >::prepareStorage(), and size.
cleanup()
template<typename Generator , typename ArgType , typename Device > EIGEN_STRONG_INLINE void Eigen::TensorEvaluator< const TensorGeneratorOp< Generator, ArgType >, Device >::cleanup () inline
 {}
Referenced by framework.Frame::__init__().
coeff()
template<typename Generator , typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType Eigen::TensorEvaluator< const TensorGeneratorOp< Generator, ArgType >, Device >::coeff (Index index) const inline
{
     array<Index, NumDims> coords;
     extract_coordinates(index, coords);
     return m_generator(coords);
   }
costPerCoeff()
template<typename Generator , typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorOpCost Eigen::TensorEvaluator< const TensorGeneratorOp< Generator, ArgType >, Device >::costPerCoeff (bool) const inline
{
     // TODO(rmlarsen): This is just a placeholder. Define interface to make
     // generators return their cost.
     return TensorOpCost(0, 0, TensorOpCost::AddCost<Scalar>() + TensorOpCost::MulCost<Scalar>());
   }
data()
template<typename Generator , typename ArgType , typename Device > EIGEN_DEVICE_FUNC EvaluatorPointerType Eigen::TensorEvaluator< const TensorGeneratorOp< Generator, ArgType >, Device >::data () const inline
 { return NULL; }
Referenced by gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenQuaternionPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), gdb.printers.EigenSparseMatrixPrinter::to_string(), and gdb.printers.EigenQuaternionPrinter::to_string().
dimensions()
template<typename Generator , typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Dimensions& Eigen::TensorEvaluator< const TensorGeneratorOp< Generator, ArgType >, Device >::dimensions () const inline
 { return m_dimensions; }
evalSubExprsIfNeeded()
template<typename Generator , typename ArgType , typename Device > EIGEN_STRONG_INLINE bool Eigen::TensorEvaluator< const TensorGeneratorOp< Generator, ArgType >, Device >::evalSubExprsIfNeeded (EvaluatorPointerType) inline
 { return true; }
extract_coordinates()
template<typename Generator , typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::TensorEvaluator< const TensorGeneratorOp< Generator, ArgType >, Device >::extract_coordinates (Index index, array< Index, NumDims > & coords) const inline protected
{
     if (static_cast<int>(Layout) == static_cast<int>(ColMajor)) {
       for (int i = NumDims - 1; i > 0; --i) {
         const Index idx = index / m_fast_strides[i];
         index -= idx * m_strides[i];
         coords[i] = idx;
       }
       coords[0] = index;
     } else {
       for (int i = 0; i < NumDims - 1; ++i) {
         const Index idx = index / m_fast_strides[i];
         index -= idx * m_strides[i];
         coords[i] = idx;
       }
       coords[NumDims - 1] = index;
     }
   }
References Eigen::ColMajor, i, and Eigen::TensorEvaluator< Derived, Device >::Layout.
getResourceRequirements()
template<typename Generator , typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE internal::TensorBlockResourceRequirements Eigen::TensorEvaluator< const TensorGeneratorOp< Generator, ArgType >, Device >::getResourceRequirements () const inline
{
     const size_t target_size = m_device.firstLevelCacheSize();
     // TODO(ezhulenev): Generator should have a cost.
     return internal::TensorBlockResourceRequirements::skewed<Scalar>(target_size);
   }
References Eigen::TensorEvaluator< Derived, Device >::m_device.
packet()
template<typename Generator , typename ArgType , typename Device > template<int LoadMode> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketReturnType Eigen::TensorEvaluator< const TensorGeneratorOp< Generator, ArgType >, Device >::packet (Index index) const inline
{
     const int packetSize = PacketType<CoeffReturnType, Device>::size;
     eigen_assert(index + packetSize - 1 < dimensions().TotalSize());
     EIGEN_ALIGN_MAX std::remove_const_t<CoeffReturnType> values[packetSize];
     for (int i = 0; i < packetSize; ++i) {
       values[i] = coeff(index + i);
     }
     PacketReturnType rslt = internal::pload<PacketReturnType>(values);
     return rslt;
   }
References Eigen::TensorEvaluator< Derived, Device >::coeff(), Eigen::TensorEvaluator< Derived, Device >::dimensions(), EIGEN_ALIGN_MAX, eigen_assert, and i.
Member Data Documentation
Layout
template<typename Generator , typename ArgType , typename Device > constexpr int Eigen::TensorEvaluator< const TensorGeneratorOp< Generator, ArgType >, Device >::Layout = TensorEvaluator<ArgType, Device>::Layout static constexpr
m_device
template<typename Generator , typename ArgType , typename Device > const Device EIGEN_DEVICE_REF Eigen::TensorEvaluator< const TensorGeneratorOp< Generator, ArgType >, Device >::m_device protected
m_dimensions
template<typename Generator , typename ArgType , typename Device > Dimensions Eigen::TensorEvaluator< const TensorGeneratorOp< Generator, ArgType >, Device >::m_dimensions protected
m_fast_strides
template<typename Generator , typename ArgType , typename Device > array<IndexDivisor, NumDims> Eigen::TensorEvaluator< const TensorGeneratorOp< Generator, ArgType >, Device >::m_fast_strides protected
m_generator
template<typename Generator , typename ArgType , typename Device > Generator Eigen::TensorEvaluator< const TensorGeneratorOp< Generator, ArgType >, Device >::m_generator protected
m_strides
template<typename Generator , typename ArgType , typename Device > array<Index, NumDims> Eigen::TensorEvaluator< const TensorGeneratorOp< Generator, ArgType >, Device >::m_strides protected
NumDims
template<typename Generator , typename ArgType , typename Device > constexpr int Eigen::TensorEvaluator< const TensorGeneratorOp< Generator, ArgType >, Device >::NumDims = internal::array_size<Dimensions>::value static constexpr
The documentation for this struct was generated from the following file:
TensorGenerator.h