MercuryDPM: Eigen::internal::IndexedViewImpl< XprType, RowIndices, ColIndices, StorageKind, true > Class Template Reference
Eigen::internal::IndexedViewImpl< XprType, RowIndices, ColIndices, StorageKind, true > Class Template Reference
#include <IndexedView.h>
Public Types
using Base = internal::IndexedViewImpl< XprType, RowIndices, ColIndices, typename internal::traits< XprType >::StorageKind, false >
using Derived = IndexedView< XprType, RowIndices, ColIndices >
Public Types inherited from Eigen::internal::IndexedViewImpl< XprType, RowIndices, ColIndices, StorageKind, false >
typedef internal::generic_xpr_base< IndexedView< XprType, RowIndices, ColIndices > >::type Base
typedef internal::ref_selector< XprType >::non_const_type MatrixTypeNested
typedef internal::remove_all_t< XprType > NestedExpression
typedef XprType::Scalar Scalar
Public Member Functions
template<typename T0 , typename T1 >
IndexedViewImpl (XprType &xpr, const T0 &rowIndices, const T1 &colIndices)
Index rowIncrement () const
Index colIncrement () const
Index innerIncrement () const
Index outerIncrement () const
std::decay_t< typename XprType::Scalar > * data ()
const std::decay_t< typename XprType::Scalar > * data () const
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index innerStride () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index outerStride () const EIGEN_NOEXCEPT
Public Member Functions inherited from Eigen::internal::IndexedViewImpl< XprType, RowIndices, ColIndices, StorageKind, false >
IndexedViewImpl (XprType &xpr, const T0 &rowIndices, const T1 &colIndices)
Index rows () const
Index cols () const
const internal::remove_all_t< XprType > & nestedExpression () const
std::remove_reference_t< XprType > & nestedExpression ()
const RowIndices & rowIndices () const
const ColIndices & colIndices () const
constexpr Scalar & coeffRef (Index rowId, Index colId)
constexpr const Scalar & coeffRef (Index rowId, Index colId) const
Additional Inherited Members
Protected Attributes inherited from Eigen::internal::IndexedViewImpl< XprType, RowIndices, ColIndices, StorageKind, false >
MatrixTypeNested m_xpr
RowIndices m_rowIndices
ColIndices m_colIndices
Member Typedef Documentation
Base
template<typename XprType , typename RowIndices , typename ColIndices , typename StorageKind > using Eigen::internal::IndexedViewImpl< XprType, RowIndices, ColIndices, StorageKind, true >::Base = internal::IndexedViewImpl<XprType, RowIndices, ColIndices, typename internal::traits<XprType>::StorageKind, false>
Derived
template<typename XprType , typename RowIndices , typename ColIndices , typename StorageKind > using Eigen::internal::IndexedViewImpl< XprType, RowIndices, ColIndices, StorageKind, true >::Derived = IndexedView<XprType, RowIndices, ColIndices>
Constructor & Destructor Documentation
IndexedViewImpl()
template<typename XprType , typename RowIndices , typename ColIndices , typename StorageKind > template<typename T0 , typename T1 > Eigen::internal::IndexedViewImpl< XprType, RowIndices, ColIndices, StorageKind, true >::IndexedViewImpl (XprType & xpr, const T0 & rowIndices, const T1 & colIndices) inline
 : Base(xpr, rowIndices, colIndices) {}
Member Function Documentation
colIncrement()
template<typename XprType , typename RowIndices , typename ColIndices , typename StorageKind > Index Eigen::internal::IndexedViewImpl< XprType, RowIndices, ColIndices, StorageKind, true >::colIncrement () const inline
{
     if (traits<Derived>::ColIncr != DynamicIndex && traits<Derived>::ColIncr != Undefined) {
       return traits<Derived>::ColIncr;
     }
     return IndexedViewHelper<ColIndices>::incr(this->colIndices());
   }
References Eigen::DynamicIndex, Eigen::internal::IndexedViewHelper< Indices, EnableIf >::incr(), and Eigen::Undefined.
data() [1/2]
template<typename XprType , typename RowIndices , typename ColIndices , typename StorageKind > std::decay_t<typename XprType::Scalar>* Eigen::internal::IndexedViewImpl< XprType, RowIndices, ColIndices, StorageKind, true >::data () inline
{
     Index row_offset = this->rowIndices()[0] * this->nestedExpression().rowStride();
     Index col_offset = this->colIndices()[0] * this->nestedExpression().colStride();
     return this->nestedExpression().data() + row_offset + col_offset;
   }
Referenced by gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenQuaternionPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), gdb.printers.EigenSparseMatrixPrinter::to_string(), and gdb.printers.EigenQuaternionPrinter::to_string().
data() [2/2]
template<typename XprType , typename RowIndices , typename ColIndices , typename StorageKind > const std::decay_t<typename XprType::Scalar>* Eigen::internal::IndexedViewImpl< XprType, RowIndices, ColIndices, StorageKind, true >::data () const inline
{
     Index row_offset = this->rowIndices()[0] * this->nestedExpression().rowStride();
     Index col_offset = this->colIndices()[0] * this->nestedExpression().colStride();
     return this->nestedExpression().data() + row_offset + col_offset;
   }
Referenced by gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenQuaternionPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), gdb.printers.EigenSparseMatrixPrinter::to_string(), and gdb.printers.EigenQuaternionPrinter::to_string().
innerIncrement()
template<typename XprType , typename RowIndices , typename ColIndices , typename StorageKind > Index Eigen::internal::IndexedViewImpl< XprType, RowIndices, ColIndices, StorageKind, true >::innerIncrement () const inline
 { return traits<Derived>::IsRowMajor ? colIncrement() : rowIncrement(); }
innerStride()
template<typename XprType , typename RowIndices , typename ColIndices , typename StorageKind > EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index Eigen::internal::IndexedViewImpl< XprType, RowIndices, ColIndices, StorageKind, true >::innerStride () const inline
{
     if (traits<Derived>::InnerStrideAtCompileTime != Dynamic) {
       return traits<Derived>::InnerStrideAtCompileTime;
     }
     return innerIncrement() * this->nestedExpression().innerStride();
   }
References Eigen::Dynamic.
outerIncrement()
template<typename XprType , typename RowIndices , typename ColIndices , typename StorageKind > Index Eigen::internal::IndexedViewImpl< XprType, RowIndices, ColIndices, StorageKind, true >::outerIncrement () const inline
 { return traits<Derived>::IsRowMajor ? rowIncrement() : colIncrement(); }
outerStride()
template<typename XprType , typename RowIndices , typename ColIndices , typename StorageKind > EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index Eigen::internal::IndexedViewImpl< XprType, RowIndices, ColIndices, StorageKind, true >::outerStride () const inline
{
     if (traits<Derived>::OuterStrideAtCompileTime != Dynamic) {
       return traits<Derived>::OuterStrideAtCompileTime;
     }
     return outerIncrement() * this->nestedExpression().outerStride();
   }
References Eigen::Dynamic.
rowIncrement()
template<typename XprType , typename RowIndices , typename ColIndices , typename StorageKind > Index Eigen::internal::IndexedViewImpl< XprType, RowIndices, ColIndices, StorageKind, true >::rowIncrement () const inline
{
     if (traits<Derived>::RowIncr != DynamicIndex && traits<Derived>::RowIncr != Undefined) {
       return traits<Derived>::RowIncr;
     }
     return IndexedViewHelper<RowIndices>::incr(this->rowIndices());
   }
References Eigen::DynamicIndex, Eigen::internal::IndexedViewHelper< Indices, EnableIf >::incr(), and Eigen::Undefined.
The documentation for this class was generated from the following file:
IndexedView.h