MercuryDPM: Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, 1 > Class Template Reference
Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, 1 > Class Template Reference
#include <BlasUtil.h>
Public Types
typedef BlasLinearMapper< Scalar, Index, AlignmentType > LinearMapper
typedef blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType > SubMapper
typedef BlasVectorMapper< Scalar, Index > VectorMapper
Public Member Functions
EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE blas_data_mapper (Scalar *data, Index stride, Index incr=1)
EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE SubMapper getSubMapper (Index i, Index j) const
EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE LinearMapper getLinearMapper (Index i, Index j) const
EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE VectorMapper getVectorMapper (Index i, Index j) const
EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE void prefetch (Index i, Index j) const
EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE Scalar & operator() (Index i, Index j) const
template<typename PacketType >
EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE PacketType loadPacket (Index i, Index j) const
template<typename PacketType >
EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE PacketType loadPacketPartial (Index i, Index j, Index n, Index offset=0) const
template<typename PacketT , int AlignmentT>
EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE PacketT load (Index i, Index j) const
template<typename PacketType >
EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE void storePacket (Index i, Index j, const PacketType &p) const
template<typename PacketType >
EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE void storePacketPartial (Index i, Index j, const PacketType &p, Index n, Index offset=0) const
template<typename SubPacket >
EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE void scatterPacket (Index i, Index j, const SubPacket &p) const
template<typename SubPacket >
EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE SubPacket gatherPacket (Index i, Index j) const
EIGEN_DEVICE_FUNC const Index stride () const
EIGEN_DEVICE_FUNC const Index incr () const
constexpr EIGEN_DEVICE_FUNC const Scalar * data () const
EIGEN_DEVICE_FUNC Index firstAligned (Index size) const
template<typename SubPacket , int n>
EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE void storePacketBlock (Index i, Index j, const PacketBlock< SubPacket, n > &block) const
Protected Attributes
Scalar *EIGEN_RESTRICT m_data
const Index m_stride
Member Typedef Documentation
LinearMapper
template<typename Scalar , typename Index , int StorageOrder, int AlignmentType> typedef BlasLinearMapper<Scalar, Index, AlignmentType> Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, 1 >::LinearMapper
SubMapper
template<typename Scalar , typename Index , int StorageOrder, int AlignmentType> typedef blas_data_mapper<Scalar, Index, StorageOrder, AlignmentType> Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, 1 >::SubMapper
VectorMapper
template<typename Scalar , typename Index , int StorageOrder, int AlignmentType> typedef BlasVectorMapper<Scalar, Index> Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, 1 >::VectorMapper
Constructor & Destructor Documentation
blas_data_mapper()
template<typename Scalar , typename Index , int StorageOrder, int AlignmentType> EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, 1 >::blas_data_mapper (Scalar * data, Index stride, Index incr = 1) inline
       : m_data(data), m_stride(stride) {
     EIGEN_ONLY_USED_FOR_DEBUG(incr);
     eigen_assert(incr == 1);
   }
References eigen_assert, EIGEN_ONLY_USED_FOR_DEBUG, and Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, Incr >::incr().
Member Function Documentation
data()
template<typename Scalar , typename Index , int StorageOrder, int AlignmentType> constexpr EIGEN_DEVICE_FUNC const Scalar* Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, 1 >::data () const inline constexpr
 { return m_data; }
References Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, Incr >::m_data.
Referenced by gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenQuaternionPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), gdb.printers.EigenSparseMatrixPrinter::to_string(), and gdb.printers.EigenQuaternionPrinter::to_string().
firstAligned()
template<typename Scalar , typename Index , int StorageOrder, int AlignmentType> EIGEN_DEVICE_FUNC Index Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, 1 >::firstAligned (Index size) const inline
{
     if (std::uintptr_t(m_data) % sizeof(Scalar)) {
       return -1;
     }
     return internal::first_default_aligned(m_data, size);
   }
References Eigen::internal::first_default_aligned(), Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, Incr >::m_data, and size.
gatherPacket()
template<typename Scalar , typename Index , int StorageOrder, int AlignmentType> template<typename SubPacket > EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE SubPacket Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, 1 >::gatherPacket (Index i, Index j) const inline
{
     return pgather<Scalar, SubPacket>(&operator()(i, j), m_stride);
   }
References i, j, and Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, Incr >::m_stride.
getLinearMapper()
template<typename Scalar , typename Index , int StorageOrder, int AlignmentType> EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE LinearMapper Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, 1 >::getLinearMapper (Index i, Index j) const inline
{
     return LinearMapper(&operator()(i, j));
   }
References i, and j.
getSubMapper()
template<typename Scalar , typename Index , int StorageOrder, int AlignmentType> EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE SubMapper Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, 1 >::getSubMapper (Index i, Index j) const inline
{
     return SubMapper(&operator()(i, j), m_stride);
   }
References i, j, and Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, Incr >::m_stride.
getVectorMapper()
template<typename Scalar , typename Index , int StorageOrder, int AlignmentType> EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE VectorMapper Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, 1 >::getVectorMapper (Index i, Index j) const inline
{
     return VectorMapper(&operator()(i, j));
   }
References i, and j.
incr()
template<typename Scalar , typename Index , int StorageOrder, int AlignmentType> EIGEN_DEVICE_FUNC const Index Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, 1 >::incr () const inline
 { return 1; }
load()
template<typename Scalar , typename Index , int StorageOrder, int AlignmentType> template<typename PacketT , int AlignmentT> EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE PacketT Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, 1 >::load (Index i, Index j) const inline
{
     return ploadt<PacketT, AlignmentT>(&operator()(i, j));
   }
References i, and j.
loadPacket()
template<typename Scalar , typename Index , int StorageOrder, int AlignmentType> template<typename PacketType > EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE PacketType Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, 1 >::loadPacket (Index i, Index j) const inline
{
     return ploadt<PacketType, AlignmentType>(&operator()(i, j));
   }
References i, and j.
loadPacketPartial()
template<typename Scalar , typename Index , int StorageOrder, int AlignmentType> template<typename PacketType > EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE PacketType Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, 1 >::loadPacketPartial (Index i, Index j, Index n, Index offset = 0) const inline
{
     return ploadt_partial<PacketType, AlignmentType>(&operator()(i, j), n, offset);
   }
References i, j, and n.
operator()()
template<typename Scalar , typename Index , int StorageOrder, int AlignmentType> EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE Scalar& Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, 1 >::operator() (Index i, Index j) const inline
{
     return m_data[StorageOrder == RowMajor ? j + i * m_stride : i + j * m_stride];
   }
References i, j, Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, Incr >::m_data, Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, Incr >::m_stride, and Eigen::RowMajor.
prefetch()
template<typename Scalar , typename Index , int StorageOrder, int AlignmentType> EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE void Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, 1 >::prefetch (Index i, Index j) const inline
 { internal::prefetch(&operator()(i, j)); }
References i, j, and Eigen::internal::prefetch().
scatterPacket()
template<typename Scalar , typename Index , int StorageOrder, int AlignmentType> template<typename SubPacket > EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE void Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, 1 >::scatterPacket (Index i, Index j, const SubPacket & p) const inline
{
     pscatter<Scalar, SubPacket>(&operator()(i, j), p, m_stride);
   }
References i, j, Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, Incr >::m_stride, and p.
storePacket()
template<typename Scalar , typename Index , int StorageOrder, int AlignmentType> template<typename PacketType > EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE void Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, 1 >::storePacket (Index i, Index j, const PacketType & p) const inline
{
     pstoret<Scalar, PacketType, AlignmentType>(&operator()(i, j), p);
   }
References i, j, and p.
storePacketBlock()
template<typename Scalar , typename Index , int StorageOrder, int AlignmentType> template<typename SubPacket , int n> EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE void Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, 1 >::storePacketBlock (Index i, Index j, const PacketBlock< SubPacket, n > & block) const inline
{
     PacketBlockManagement<Index, Scalar, SubPacket, n, n - 1, StorageOrder> pbm;
     pbm.store(m_data, m_stride, i, j, block);
   }
References block(), i, j, Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, Incr >::m_data, Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, Incr >::m_stride, and n.
storePacketPartial()
template<typename Scalar , typename Index , int StorageOrder, int AlignmentType> template<typename PacketType > EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE void Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, 1 >::storePacketPartial (Index i, Index j, const PacketType & p, Index n, Index offset = 0) const inline
{
     pstoret_partial<Scalar, PacketType, AlignmentType>(&operator()(i, j), p, n, offset);
   }
References i, j, n, and p.
stride()
template<typename Scalar , typename Index , int StorageOrder, int AlignmentType> EIGEN_DEVICE_FUNC const Index Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, 1 >::stride () const inline
 { return m_stride; }
References Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, Incr >::m_stride.
Member Data Documentation
m_data
template<typename Scalar , typename Index , int StorageOrder, int AlignmentType> Scalar* EIGEN_RESTRICT Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, 1 >::m_data protected
m_stride
template<typename Scalar , typename Index , int StorageOrder, int AlignmentType> const Index Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, 1 >::m_stride protected
The documentation for this class was generated from the following file:
BlasUtil.h