MercuryDPM: oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM > Class Template Reference
oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM > Class Template Reference abstract
#include <mixed_order_petrov_galerkin_space_time_navier_stokes_elements.h>
Public Types
typedef void(* NavierStokesMixedOrderBodyForceFctPt) (const double &time, const Vector< double > &x, Vector< double > &body_force)
typedef double(* NavierStokesMixedOrderSourceFctPt) (const double &time, const Vector< double > &x)
Function pointer to source function fct(t,x) (x is a Vector!)
typedef double(* NavierStokesMixedOrderPressureAdvDiffSourceFctPt) (const Vector< double > &x)
Public Types inherited from oomph::FiniteElement
typedef void(* SteadyExactSolutionFctPt) (const Vector< double > &, Vector< double > &)
typedef void(* UnsteadyExactSolutionFctPt) (const double &, const Vector< double > &, Vector< double > &)
Public Member Functions
SpaceTimeNavierStokesMixedOrderEquations ()
void store_reynolds_strouhal_as_external_data (Data *reynolds_strouhal_data_pt)
Function that tells us whether the period is stored as external data.
bool is_reynolds_strouhal_stored_as_external_data () const
Are we storing the Strouhal number as external data?
const double & re () const
Reynolds number.
double *& re_pt ()
Pointer to Reynolds number.
const double & re_st () const
ReSt parameter (const. version)
double * re_st_pt () const
Pointer to Strouhal parameter (const. version)
double *& re_st_pt ()
Pointer to ReSt number (can only assign to private member data)
const double & viscosity_ratio () const
double *& viscosity_ratio_pt ()
Pointer to Viscosity Ratio.
const double & density_ratio () const
double *& density_ratio_pt ()
Pointer to Density ratio.
const double & re_invfr () const
Global inverse Froude number.
double *& re_invfr_pt ()
Pointer to global inverse Froude number.
const Vector< double > & g () const
Vector of gravitational components.
Vector< double > *& g_pt ()
Pointer to Vector of gravitational components.
NavierStokesMixedOrderBodyForceFctPt & body_force_fct_pt ()
Access function for the body-force pointer.
NavierStokesMixedOrderBodyForceFctPt body_force_fct_pt () const
Access function for the body-force pointer. Const version.
NavierStokesMixedOrderSourceFctPt & source_fct_pt ()
Access function for the source-function pointer.
NavierStokesMixedOrderSourceFctPt source_fct_pt () const
Access function for the source-function pointer. Const version.
NavierStokesMixedOrderPressureAdvDiffSourceFctPt & source_fct_for_pressure_adv_diff ()
NavierStokesMixedOrderPressureAdvDiffSourceFctPt source_fct_for_pressure_adv_diff () const
int & pinned_fp_pressure_eqn ()
virtual unsigned npres_nst () const =0
Function to return number of pressure degrees of freedom.
virtual void pshape_nst (const Vector< double > &s, Shape &psi) const =0
Compute the pressure shape functions at local coordinate s.
virtual void pshape_nst (const Vector< double > &s, Shape &psi, Shape &test) const =0
double u_nst (const unsigned &n, const unsigned &i) const
double u_nst (const unsigned &t, const unsigned &n, const unsigned &i) const
virtual unsigned u_index_nst (const unsigned &i) const
unsigned n_u_nst () const
double get_du_dt (const unsigned &n, const unsigned &i) const
double du_dt_nst (const unsigned &n, const unsigned &i) const
double interpolated_du_dt_nst (const Vector< double > &s, const unsigned &i) const
void disable_ALE ()
void enable_ALE ()
virtual double p_nst (const unsigned &n_p) const =0
virtual double p_nst (const unsigned &t, const unsigned &n_p) const =0
Pressure at local pressure "node" n_p at time level t.
virtual void fix_pressure (const unsigned &p_dof, const double &p_value)=0
Pin p_dof-th pressure dof and set it to value specified by p_value.
virtual int p_nodal_index_nst () const
double pressure_integral () const
Integral of pressure over element.
double dissipation () const
Return integral of dissipation over element.
double dissipation (const Vector< double > &s) const
Return dissipation at local coordinate s.
void get_vorticity (const Vector< double > &s, Vector< double > &vorticity) const
Compute the vorticity vector at local coordinate s.
void get_vorticity (const Vector< double > &s, double &vorticity) const
Compute the vorticity vector at local coordinate s.
double kin_energy () const
Get integral of kinetic energy over element.
double d_kin_energy_dt () const
Get integral of time derivative of kinetic energy over element.
void strain_rate (const Vector< double > &s, DenseMatrix< double > &strain_rate) const
Strain-rate tensor: 1/2 (du_i/dx_j+du_j/dx_i)
void get_traction (const Vector< double > &s, const Vector< double > &N, Vector< double > &traction)
void get_traction (const Vector< double > &s, const Vector< double > &N, Vector< double > &traction_p, Vector< double > &traction_visc_n, Vector< double > &traction_visc_t)
void get_load (const Vector< double > &s, const Vector< double > &N, Vector< double > &load)
void get_pressure_and_velocity_mass_matrix_diagonal (Vector< double > &press_mass_diag, Vector< double > &veloc_mass_diag, const unsigned &which_one=0)
unsigned nscalar_paraview () const
void scalar_value_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot) const
void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
std::string scalar_name_paraview (const unsigned &i) const
void output (std::ostream &outfile)
void output (std::ostream &outfile, const unsigned &n_plot)
void output (FILE *file_pt)
void output (FILE *file_pt, const unsigned &n_plot)
void full_output (std::ostream &outfile)
void full_output (std::ostream &outfile, const unsigned &n_plot)
void output_veloc (std::ostream &outfile, const unsigned &nplot, const unsigned &t)
void output_vorticity (std::ostream &outfile, const unsigned &nplot)
void output_fct (std::ostream &outfile, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
void output_fct (std::ostream &outfile, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
void compute_norm (Vector< double > &norm)
Compute the vector norm of the FEM solution.
void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Compute the element's residual Vector.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
void fill_in_contribution_to_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
void fill_in_contribution_to_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
void fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
void fill_in_pressure_advection_diffusion_residuals (Vector< double > &residuals)
void fill_in_pressure_advection_diffusion_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void pin_all_non_pressure_dofs (std::map< Data *, std::vector< int >> &eqn_number_backup)
Pin all non-pressure dofs and backup eqn numbers.
virtual void build_fp_press_adv_diff_robin_bc_element (const unsigned &face_index)=0
void output_pressure_advection_diffusion_robin_elements (std::ostream &outfile)
void delete_pressure_advection_diffusion_robin_elements ()
virtual void get_dresidual_dnodal_coordinates (RankThreeTensor< double > &dresidual_dnodal_coordinates)
void interpolated_u_nst (const Vector< double > &s, Vector< double > &velocity) const
Compute vector of FE interpolated velocity u at local coordinate s.
double interpolated_u_nst (const Vector< double > &s, const unsigned &i) const
Return FE interpolated velocity u[i] at local coordinate s.
double interpolated_u_nst (const unsigned &t, const Vector< double > &s, const unsigned &i) const
virtual void dinterpolated_u_nst_ddata (const Vector< double > &s, const unsigned &i, Vector< double > &du_ddata, Vector< unsigned > &global_eqn_number)
virtual double interpolated_p_nst (const Vector< double > &s) const
Return FE interpolated pressure at local coordinate s.
double interpolated_p_nst (const unsigned &t, const Vector< double > &s) const
Return FE interpolated pressure at local coordinate s at time level t.
void point_output_data (const Vector< double > &s, Vector< double > &data)
void get_vorticity (const Vector< double > &s, Vector< double > &vorticity) const
void get_vorticity (const Vector< double > &s, double &vorticity) const
Public Member Functions inherited from oomph::FSIFluidElement
FSIFluidElement ()
Constructor.
FSIFluidElement (const FSIFluidElement &)=delete
Broken copy constructor.
void operator= (const FSIFluidElement &)=delete
Broken assignment operator.
virtual void identify_load_data (std::set< std::pair< Data *, unsigned >> &paired_load_data)=0
virtual void identify_pressure_data (std::set< std::pair< Data *, unsigned >> &paired_pressure_data)=0
Public Member Functions inherited from oomph::FiniteElement
void set_dimension (const unsigned &dim)
void set_nodal_dimension (const unsigned &nodal_dim)
void set_nnodal_position_type (const unsigned &nposition_type)
Set the number of types required to interpolate the coordinate.
void set_n_node (const unsigned &n)
int nodal_local_eqn (const unsigned &n, const unsigned &i) const
double dJ_eulerian_at_knot (const unsigned &ipt, Shape &psi, DenseMatrix< double > &djacobian_dX) const
FiniteElement ()
Constructor.
virtual ~FiniteElement ()
FiniteElement (const FiniteElement &)=delete
Broken copy constructor.
virtual bool local_coord_is_valid (const Vector< double > &s)
Broken assignment operator.
virtual void move_local_coord_back_into_element (Vector< double > &s) const
void get_centre_of_gravity_and_max_radius_in_terms_of_zeta (Vector< double > &cog, double &max_radius) const
virtual void local_coordinate_of_node (const unsigned &j, Vector< double > &s) const
virtual void local_fraction_of_node (const unsigned &j, Vector< double > &s_fraction)
virtual double local_one_d_fraction_of_node (const unsigned &n1d, const unsigned &i)
virtual void set_macro_elem_pt (MacroElement *macro_elem_pt)
MacroElement * macro_elem_pt ()
Access function to pointer to macro element.
void get_x (const Vector< double > &s, Vector< double > &x) const
void get_x (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void get_x_from_macro_element (const Vector< double > &s, Vector< double > &x) const
virtual void get_x_from_macro_element (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void set_integration_scheme (Integral *const &integral_pt)
Set the spatial integration scheme.
Integral *const & integral_pt () const
Return the pointer to the integration scheme (const version)
virtual void shape (const Vector< double > &s, Shape &psi) const =0
virtual void shape_at_knot (const unsigned &ipt, Shape &psi) const
virtual void dshape_local (const Vector< double > &s, Shape &psi, DShape &dpsids) const
virtual void dshape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids) const
virtual void d2shape_local (const Vector< double > &s, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual void d2shape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual double J_eulerian (const Vector< double > &s) const
virtual double J_eulerian_at_knot (const unsigned &ipt) const
void check_J_eulerian_at_knots (bool &passed) const
void check_jacobian (const double &jacobian) const
double dshape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsi, DenseMatrix< double > &djacobian_dX, RankFourTensor< double > &d_dpsidx_dX) const
double d2shape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual double d2shape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual void assign_nodal_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void describe_local_dofs (std::ostream &out, const std::string &current_string) const
virtual void describe_nodal_local_dofs (std::ostream &out, const std::string &current_string) const
virtual void assign_all_generic_local_eqn_numbers (const bool &store_local_dof_pt)
Node *& node_pt (const unsigned &n)
Return a pointer to the local node n.
Node *const & node_pt (const unsigned &n) const
Return a pointer to the local node n (const version)
unsigned nnode () const
Return the number of nodes.
virtual unsigned nnode_1d () const
double raw_nodal_position (const unsigned &n, const unsigned &i) const
double raw_nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position (const unsigned &n, const unsigned &i) const
double nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double dnodal_position_dt (const unsigned &n, const unsigned &i) const
Return the i-th component of nodal velocity: dx/dt at local node n.
double dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
virtual unsigned required_nvalue (const unsigned &n) const
unsigned nnodal_position_type () const
bool has_hanging_nodes () const
unsigned nodal_dimension () const
Return the required Eulerian dimension of the nodes in this element.
virtual unsigned nvertex_node () const
virtual Node * vertex_node_pt (const unsigned &j) const
virtual Node * construct_node (const unsigned &n)
virtual Node * construct_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
virtual Node * construct_boundary_node (const unsigned &n)
virtual Node * construct_boundary_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
int get_node_number (Node *const &node_pt) const
virtual Node * get_node_at_local_coordinate (const Vector< double > &s) const
double raw_nodal_value (const unsigned &n, const unsigned &i) const
double raw_nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
unsigned dim () const
virtual ElementGeometry::ElementGeometry element_geometry () const
Return the geometry type of the element (either Q or T usually).
virtual double interpolated_x (const Vector< double > &s, const unsigned &i) const
Return FE interpolated coordinate x[i] at local coordinate s.
virtual double interpolated_x (const unsigned &t, const Vector< double > &s, const unsigned &i) const
virtual void interpolated_x (const Vector< double > &s, Vector< double > &x) const
Return FE interpolated position x[] at local coordinate s as Vector.
virtual void interpolated_x (const unsigned &t, const Vector< double > &s, Vector< double > &x) const
virtual double interpolated_dxdt (const Vector< double > &s, const unsigned &i, const unsigned &t)
virtual void interpolated_dxdt (const Vector< double > &s, const unsigned &t, Vector< double > &dxdt)
unsigned ngeom_data () const
Data * geom_data_pt (const unsigned &j)
void position (const Vector< double > &zeta, Vector< double > &r) const
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
void dposition_dt (const Vector< double > &zeta, const unsigned &t, Vector< double > &drdt)
virtual double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
void interpolated_zeta (const Vector< double > &s, Vector< double > &zeta) const
void locate_zeta (const Vector< double > &zeta, GeomObject *&geom_object_pt, Vector< double > &s, const bool &use_coordinate_as_initial_guess=false)
virtual void node_update ()
virtual void identify_field_data_for_interactions (std::set< std::pair< Data *, unsigned >> &paired_field_data)
virtual void identify_geometric_data (std::set< Data * > &geometric_data_pt)
virtual double s_min () const
Min value of local coordinate.
virtual double s_max () const
Max. value of local coordinate.
double size () const
virtual double compute_physical_size () const
void point_output (std::ostream &outfile, const Vector< double > &s)
virtual unsigned nplot_points_paraview (const unsigned &nplot) const
virtual unsigned nsub_elements_paraview (const unsigned &nplot) const
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_output_offset_information (std::ofstream &file_out, const unsigned &nplot, unsigned &counter) const
virtual void write_paraview_type (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_offsets (std::ofstream &file_out, const unsigned &nplot, unsigned &offset_sum) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
virtual void output (const unsigned &t, std::ostream &outfile, const unsigned &n_plot) const
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, const SolutionFunctorBase &exact_soln) const
Output a time-dependent exact solution over the element.
virtual void get_s_plot (const unsigned &i, const unsigned &nplot, Vector< double > &s, const bool &shifted_to_interior=false) const
virtual std::string tecplot_zone_string (const unsigned &nplot) const
virtual void write_tecplot_zone_footer (std::ostream &outfile, const unsigned &nplot) const
virtual void write_tecplot_zone_footer (FILE *file_pt, const unsigned &nplot) const
virtual unsigned nplot_points (const unsigned &nplot) const
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_abs_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error)
void integrate_fct (FiniteElement::SteadyExactSolutionFctPt integrand_fct_pt, Vector< double > &integral)
Integrate Vector-valued function over element.
void integrate_fct (FiniteElement::UnsteadyExactSolutionFctPt integrand_fct_pt, const double &time, Vector< double > &integral)
Integrate Vector-valued time-dep function over element.
virtual void build_face_element (const int &face_index, FaceElement *face_element_pt)
virtual unsigned self_test ()
virtual unsigned get_bulk_node_number (const int &face_index, const unsigned &i) const
virtual int face_outer_unit_normal_sign (const int &face_index) const
Get the sign of the outer unit normal on the face given by face_index.
virtual unsigned nnode_on_face () const
void face_node_number_error_check (const unsigned &i) const
Range check for face node numbers.
virtual CoordinateMappingFctPt face_to_bulk_coordinate_fct_pt (const int &face_index) const
virtual BulkCoordinateDerivativesFctPt bulk_coordinate_derivatives_fct_pt (const int &face_index) const
Public Member Functions inherited from oomph::GeneralisedElement
GeneralisedElement ()
Constructor: Initialise all pointers and all values to zero.
virtual ~GeneralisedElement ()
Virtual destructor to clean up any memory allocated by the object.
GeneralisedElement (const GeneralisedElement &)=delete
Broken copy constructor.
void operator= (const GeneralisedElement &)=delete
Broken assignment operator.
Data *& internal_data_pt (const unsigned &i)
Return a pointer to i-th internal data object.
Data *const & internal_data_pt (const unsigned &i) const
Return a pointer to i-th internal data object (const version)
Data *& external_data_pt (const unsigned &i)
Return a pointer to i-th external data object.
Data *const & external_data_pt (const unsigned &i) const
Return a pointer to i-th external data object (const version)
unsigned long eqn_number (const unsigned &ieqn_local) const
int local_eqn_number (const unsigned long &ieqn_global) const
unsigned add_external_data (Data *const &data_pt, const bool &fd=true)
bool external_data_fd (const unsigned &i) const
void exclude_external_data_fd (const unsigned &i)
void include_external_data_fd (const unsigned &i)
void flush_external_data ()
Flush all external data.
void flush_external_data (Data *const &data_pt)
Flush the object addressed by data_pt from the external data array.
unsigned ninternal_data () const
Return the number of internal data objects.
unsigned nexternal_data () const
Return the number of external data objects.
unsigned ndof () const
Return the number of equations/dofs in the element.
void dof_vector (const unsigned &t, Vector< double > &dof)
Return the vector of dof values at time level t.
void dof_pt_vector (Vector< double * > &dof_pt)
Return the vector of pointers to dof values.
void set_internal_data_time_stepper (const unsigned &i, TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void assign_internal_eqn_numbers (unsigned long &global_number, Vector< double * > &Dof_pt)
void describe_dofs (std::ostream &out, const std::string &current_string) const
void add_internal_value_pt_to_map (std::map< unsigned, double * > &map_of_value_pt)
virtual void assign_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void complete_setup_of_dependencies ()
virtual void get_residuals (Vector< double > &residuals)
virtual void get_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
virtual void get_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void get_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void get_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void get_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void get_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void get_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void get_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void get_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
virtual void compute_norm (double &norm)
virtual unsigned ndof_types () const
virtual void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned >> &dof_lookup_list) const
Public Member Functions inherited from oomph::GeomObject
GeomObject ()
Default constructor.
GeomObject (const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim, TimeStepper *time_stepper_pt)
GeomObject (const GeomObject &dummy)=delete
Broken copy constructor.
void operator= (const GeomObject &)=delete
Broken assignment operator.
virtual ~GeomObject ()
(Empty) destructor
unsigned nlagrangian () const
Access function to # of Lagrangian coordinates.
unsigned ndim () const
Access function to # of Eulerian coordinates.
void set_nlagrangian_and_ndim (const unsigned &n_lagrangian, const unsigned &n_dim)
Set # of Lagrangian and Eulerian coordinates.
TimeStepper *& time_stepper_pt ()
TimeStepper * time_stepper_pt () const
virtual void position (const double &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void dposition (const Vector< double > &zeta, DenseMatrix< double > &drdzeta) const
virtual void d2position (const Vector< double > &zeta, RankThreeTensor< double > &ddrdzeta) const
virtual void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
Public Member Functions inherited from oomph::TemplateFreeSpaceTimeNavierStokesMixedOrderEquationsBase
TemplateFreeSpaceTimeNavierStokesMixedOrderEquationsBase ()
Constructor (empty)
virtual ~TemplateFreeSpaceTimeNavierStokesMixedOrderEquationsBase ()
Virtual destructor (empty)
virtual int p_local_eqn (const unsigned &n) const =0
Public Member Functions inherited from oomph::NavierStokesElementWithDiagonalMassMatrices
NavierStokesElementWithDiagonalMassMatrices ()
Empty constructor.
virtual ~NavierStokesElementWithDiagonalMassMatrices ()
Virtual destructor.
NavierStokesElementWithDiagonalMassMatrices (const NavierStokesElementWithDiagonalMassMatrices &)=delete
Broken copy constructor.
void operator= (const NavierStokesElementWithDiagonalMassMatrices &)=delete
Broken assignment operator.
Static Public Attributes
static Vector< double > Gamma
Navier-Stokes equations static data.
Static Public Attributes inherited from oomph::FiniteElement
static double Tolerance_for_singular_jacobian = 1.0e-16
Tolerance below which the jacobian is considered singular.
static bool Accept_negative_jacobian = false
static bool Suppress_output_while_checking_for_inverted_elements
Static Public Attributes inherited from oomph::GeneralisedElement
static bool Suppress_warning_about_repeated_internal_data
static bool Suppress_warning_about_repeated_external_data = true
static double Default_fd_jacobian_step = 1.0e-8
Protected Member Functions
virtual double dshape_and_dtest_eulerian_nst (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const =0
virtual double dshape_and_dtest_eulerian_at_knot_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const =0
virtual double dshape_and_dtest_eulerian_at_knot_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, RankFourTensor< double > &d_dpsidx_dX, Shape &test, DShape &dtestdx, RankFourTensor< double > &d_dtestdx_dX, DenseMatrix< double > &djacobian_dX) const =0
virtual void shape_u_nst (const Vector< double > &s, Shape &psi) const =0
DRAIG: Fill in later...
virtual void dshape_local_u_nst (const Vector< double > &s, Shape &psi, DShape &dpsidx) const =0
DRAIG: Fill in later...
virtual void dtest_local_u_nst (const Vector< double > &s, Shape &test, DShape &dtestdx) const =0
DRAIG: Fill in later...
virtual double dpshape_eulerian (const Vector< double > &s, Shape &ppsi, DShape &dppsidx) const =0
virtual double dptest_eulerian (const Vector< double > &s, Shape &ptest, DShape &dptestdx) const =0
virtual double dpshape_and_dptest_eulerian_nst (const Vector< double > &s, Shape &ppsi, DShape &dppsidx, Shape &ptest, DShape &dptestdx) const =0
virtual void get_body_force_nst (const double &time, const unsigned &ipt, const Vector< double > &s, const Vector< double > &x, Vector< double > &result)
virtual void get_body_force_gradient_nst (const double &time, const unsigned &ipt, const Vector< double > &s, const Vector< double > &x, DenseMatrix< double > &d_body_force_dx)
virtual double get_source_nst (const double &time, const unsigned &ipt, const Vector< double > &x)
Calculate the source fct at a given time and Eulerian position.
virtual void get_source_gradient_nst (const double &time, const unsigned &ipt, const Vector< double > &x, Vector< double > &gradient)
virtual void fill_in_generic_residual_contribution_nst (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix, const unsigned &flag)
virtual void fill_in_generic_pressure_advection_diffusion_contribution_nst (Vector< double > &residuals, DenseMatrix< double > &jacobian, const unsigned &flag)
virtual void fill_in_generic_dresidual_contribution_nst (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam, const unsigned &flag)
void fill_in_contribution_to_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
Protected Member Functions inherited from oomph::FiniteElement
virtual void assemble_local_to_eulerian_jacobian (const DShape &dpsids, DenseMatrix< double > &jacobian) const
virtual void assemble_local_to_eulerian_jacobian2 (const DShape &d2psids, DenseMatrix< double > &jacobian2) const
virtual void assemble_eulerian_base_vectors (const DShape &dpsids, DenseMatrix< double > &interpolated_G) const
template<unsigned DIM>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double invert_jacobian_mapping (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping_diagonal (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual void dJ_eulerian_dnodal_coordinates (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<unsigned DIM>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
virtual void d_dshape_eulerian_dnodal_coordinates (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<unsigned DIM>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
virtual void transform_derivatives (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
void transform_derivatives_diagonal (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
virtual void transform_second_derivatives (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
virtual void fill_in_jacobian_from_nodal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_jacobian_from_nodal_by_fd (DenseMatrix< double > &jacobian)
virtual void update_before_nodal_fd ()
virtual void reset_after_nodal_fd ()
virtual void update_in_nodal_fd (const unsigned &i)
virtual void reset_in_nodal_fd (const unsigned &i)
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Zero-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
One-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Two-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
Protected Member Functions inherited from oomph::GeneralisedElement
unsigned add_internal_data (Data *const &data_pt, const bool &fd=true)
bool internal_data_fd (const unsigned &i) const
void exclude_internal_data_fd (const unsigned &i)
void include_internal_data_fd (const unsigned &i)
void clear_global_eqn_numbers ()
void add_global_eqn_numbers (std::deque< unsigned long > const &global_eqn_numbers, std::deque< double * > const &global_dof_pt)
virtual void assign_internal_and_external_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void assign_additional_local_eqn_numbers ()
int internal_local_eqn (const unsigned &i, const unsigned &j) const
int external_local_eqn (const unsigned &i, const unsigned &j)
void fill_in_jacobian_from_internal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_internal_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
virtual void update_before_internal_fd ()
virtual void reset_after_internal_fd ()
virtual void update_in_internal_fd (const unsigned &i)
virtual void reset_in_internal_fd (const unsigned &i)
virtual void update_before_external_fd ()
virtual void reset_after_external_fd ()
virtual void update_in_external_fd (const unsigned &i)
virtual void reset_in_external_fd (const unsigned &i)
virtual void fill_in_contribution_to_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void fill_in_contribution_to_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
Protected Attributes
double * Viscosity_Ratio_pt
double * Density_Ratio_pt
double * Re_pt
Pointer to global Reynolds number.
double * ReSt_pt
Pointer to global Reynolds number x Strouhal number (=Womersley)
bool ReynoldsStrouhal_is_stored_as_external_data
double * ReInvFr_pt
Vector< double > * G_pt
Pointer to global gravity Vector.
NavierStokesMixedOrderBodyForceFctPt Body_force_fct_pt
Pointer to body force function.
NavierStokesMixedOrderSourceFctPt Source_fct_pt
Pointer to volumetric source function.
NavierStokesMixedOrderPressureAdvDiffSourceFctPt Press_adv_diff_source_fct_pt
bool ALE_is_disabled
Vector< FpPressureAdvDiffRobinBCMixedOrderSpaceTimeElementBase * > Pressure_advection_diffusion_robin_element_pt
int Pinned_fp_pressure_eqn
Protected Attributes inherited from oomph::FiniteElement
MacroElement * Macro_elem_pt
Pointer to the element's macro element (NULL by default)
Protected Attributes inherited from oomph::GeomObject
unsigned NLagrangian
Number of Lagrangian (intrinsic) coordinates.
unsigned Ndim
Number of Eulerian coordinates.
TimeStepper * Geom_object_time_stepper_pt
Static Private Attributes
static int Pressure_not_stored_at_node
static double Default_Physical_Constant_Value = 0.0
Navier-Stokes equations static data.
static double Default_Physical_Ratio_Value = 1.0
Navier-Stokes equations static data.
static Vector< double > Default_Gravity_vector
Static default value for the gravity vector.
Additional Inherited Members
Static Protected Attributes inherited from oomph::FiniteElement
static const unsigned Default_Initial_Nvalue = 0
Default value for the number of values at a node.
static const double Node_location_tolerance = 1.0e-14
static const unsigned N2deriv [] = {0, 1, 3, 6}
Static Protected Attributes inherited from oomph::GeneralisedElement
static DenseMatrix< double > Dummy_matrix
static std::deque< double * > Dof_pt_deque
Detailed Description
template<unsigned DIM>
class oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >
//////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////// A class for elements that solve the Cartesian Navier-Stokes equations, templated by the dimension DIM. This contains the generic maths – any concrete implementation must be derived from this.
We're solving:
\({ Re \left(St \frac{\partial u_i}{\partial t}+ (u_j-u_j^{M}) \frac{\partial u_i}{\partial x_j} \right)= -\frac{\partial p}{\partial x_i} -R_\rho B_i(x_j) - \frac{Re}{Fr} G_i + \frac{\partial }{\partial x_j} \left[ R_\mu \left(\frac{\partial u_i}{\partial x_j}+ \frac{\partial u_j}{\partial x_i} \right) \right] } \)
and
\({ \frac{\partial u_i}{\partial x_i}=Q } \)
We also provide all functions required to use this element in FSI problems, by deriving it from the FSIFluidElement base class.
SPACE-TIME ELEMENTS:
The space-time extension is written ONLY for the 2D Navier-Stokes equations. The result is a 3D problem (x,y,t) to be solved on a 3D mesh. The template parameter DIM now corresponds to the dimension of the space-time problem (i.e. DIM=3 for the 2D flow).
Member Typedef Documentation
NavierStokesMixedOrderBodyForceFctPt
template<unsigned DIM> typedef void(* oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::NavierStokesMixedOrderBodyForceFctPt) (const double &time, const Vector< double > &x, Vector< double > &body_force)
Function pointer to body force function fct(t,x,f(x)) x is a Vector!
NavierStokesMixedOrderPressureAdvDiffSourceFctPt
template<unsigned DIM> typedef double(* oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::NavierStokesMixedOrderPressureAdvDiffSourceFctPt) (const Vector< double > &x)
Function pointer to source function fct(x) for the pressure advection diffusion equation (only used during validation!). x is a Vector!
NavierStokesMixedOrderSourceFctPt
template<unsigned DIM> typedef double(* oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::NavierStokesMixedOrderSourceFctPt) (const double &time, const Vector< double > &x)
Function pointer to source function fct(t,x) (x is a Vector!)
Constructor & Destructor Documentation
SpaceTimeNavierStokesMixedOrderEquations()
template<unsigned DIM> oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::SpaceTimeNavierStokesMixedOrderEquations () inline
Constructor: NULL the body force and source function and make sure the ALE terms are included by default.
       : Body_force_fct_pt(0),
         Source_fct_pt(0),
         Press_adv_diff_source_fct_pt(0),
         ALE_is_disabled(false),
         Pinned_fp_pressure_eqn(-1)
     {
       // Set all the Physical parameter pointers:
       // Set the Reynolds number to the value zero
       Re_pt = &Default_Physical_Constant_Value;
       // Set the Strouhal number to the value zero
       ReSt_pt = &Default_Physical_Constant_Value;
       // The Strouhal number (which is a proxy for the period here) is not
       // stored as external data
       ReynoldsStrouhal_is_stored_as_external_data = false;
       // Set the Reynolds / Froude value to zero
       ReInvFr_pt = &Default_Physical_Constant_Value;
       // Set the gravity vector to be the zero vector
       G_pt = &Default_Gravity_vector;
       // Set the Physical ratios:
       // Set the viscosity ratio to the value one
       Viscosity_Ratio_pt = &Default_Physical_Ratio_Value;
       // Set the density ratio to the value one
       Density_Ratio_pt = &Default_Physical_Ratio_Value;
     }
References oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::Default_Gravity_vector, oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::Default_Physical_Constant_Value, oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::Default_Physical_Ratio_Value, oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::Density_Ratio_pt, oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::G_pt, oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::Re_pt, oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::ReInvFr_pt, oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::ReSt_pt, oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::ReynoldsStrouhal_is_stored_as_external_data, and oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::Viscosity_Ratio_pt.
Member Function Documentation
body_force_fct_pt() [1/2]
template<unsigned DIM> NavierStokesMixedOrderBodyForceFctPt& oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::body_force_fct_pt () inline
Access function for the body-force pointer.
     {
       return Body_force_fct_pt;
     }
References oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::Body_force_fct_pt.
body_force_fct_pt() [2/2]
template<unsigned DIM> NavierStokesMixedOrderBodyForceFctPt oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::body_force_fct_pt () const inline
Access function for the body-force pointer. Const version.
     {
       return Body_force_fct_pt;
     }
References oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::Body_force_fct_pt.
build_fp_press_adv_diff_robin_bc_element()
template<unsigned DIM> virtual void oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::build_fp_press_adv_diff_robin_bc_element (const unsigned & face_index) pure virtual
Build FaceElements that apply the Robin boundary condition to the pressure advection diffusion problem required by Fp preconditioner
Implements oomph::TemplateFreeSpaceTimeNavierStokesMixedOrderEquationsBase.
Implemented in oomph::RefineableQTaylorHoodMixedOrderSpaceTimeElement< DIM >, oomph::QTaylorHoodMixedOrderSpaceTimeElement< DIM >, and oomph::QTaylorHoodMixedOrderSpaceTimeElement< 2 >.
compute_error() [1/5]
template<unsigned DIM> void oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double & error, double & norm) virtual
Validate against exact solution. Solution is provided via function pointer. Compute L2 error and L2 norm of velocity solution over element.
Validate against exact velocity solution Solution is provided via a function pointer. Compute L2 error and L2 norm of velocity solution over element.
Reimplemented from oomph::FiniteElement.
   {
     // Initialise the error norm value
     error = 0.0;
     // Initialise the solution norm value
     norm = 0.0;
     // Vector of local coordinates
     Vector<double> s(DIM + 1, 0.0);
     // Vector for the spatial coordinates
     Vector<double> x(DIM, 0.0);
     // Set the value of n_intpt
     unsigned n_intpt = integral_pt()->nweight();
     // Exact solution Vector (u,v,[w],p)
     Vector<double> exact_soln(DIM + 1, 0.0);
     // Loop over the integration points
     for (unsigned ipt = 0; ipt < n_intpt; ipt++)
     {
       // Assign values of s
       for (unsigned i = 0; i < DIM + 1; i++)
       {
         s[i] = integral_pt()->knot(ipt, i);
       }
       // Assign values of x
       for (unsigned i = 0; i < DIM; i++)
       {
         // Get x position as Vector
         x[i] = interpolated_x(s, i);
       }
       // Get exact solution at this point
       (*exact_soln_pt)(x, exact_soln);
       // Get the integral weight
       double w = integral_pt()->weight(ipt);
       // Get Jacobian of mapping
       double J = J_eulerian(s);
       // Premultiply the weights and the Jacobian
       double W = w * J;
       // Velocity error
       for (unsigned i = 0; i < DIM; i++)
       {
         // Update the solution norm value
         norm += exact_soln[i] * exact_soln[i] * W;
         // Update the error norm value
         error += pow(exact_soln[i] - interpolated_u_nst(s, i), 2) * W;
       }
     } // for (unsigned ipt=0;ipt<n_intpt;ipt++)
   } // End of compute_error
References DIM, calibrate::error, ProblemParameters::exact_soln(), i, J, Eigen::bfloat16_impl::pow(), s, w, oomph::QuadTreeNames::W, and plotDoE::x.
compute_error() [2/5]
template<unsigned DIM> void oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double & time, double & error, double & norm) virtual
Validate against exact solution. Solution is provided via function pointer. Compute L2 error and L2 norm of velocity solution over element.
Validate against exact velocity solution at given time. Solution is provided via function pointer. Compute L2 error and L2 norm of velocity solution over element.
Reimplemented from oomph::FiniteElement.
   {
     // Initialise the error norm value
     error = 0.0;
     // Initialise the solution norm value
     norm = 0.0;
     // Storage for the time value
     double interpolated_t = 0.0;
     // Vector of local coordinates
     Vector<double> s(DIM + 1, 0.0);
     // Vector for the spatial coordinates
     Vector<double> x(DIM, 0.0);
     // Set the value of n_intpt
     unsigned n_intpt = integral_pt()->nweight();
     // Exact solution Vector (u,v,[w],p)
     Vector<double> exact_soln(DIM + 1, 0.0);
     // Loop over the integration points
     for (unsigned ipt = 0; ipt < n_intpt; ipt++)
     {
       // Assign values of s
       for (unsigned i = 0; i < DIM + 1; i++)
       {
         s[i] = integral_pt()->knot(ipt, i);
       }
       // Assign values of x
       for (unsigned i = 0; i < DIM; i++)
       {
         // Get x position as Vector
         x[i] = interpolated_x(s, i);
       }
       // Get the time value
       interpolated_t = interpolated_x(s, DIM);
       // Get exact solution at this point
       (*exact_soln_pt)(interpolated_t, x, exact_soln);
       // Get the integral weight
       double w = integral_pt()->weight(ipt);
       // Get Jacobian of mapping
       double J = J_eulerian(s);
       // Premultiply the weights and the Jacobian
       double W = w * J;
       // Velocity error
       for (unsigned i = 0; i < DIM; i++)
       {
         // Update the solution norm value
         norm += exact_soln[i] * exact_soln[i] * W;
         // Update the error norm value
         error += pow(exact_soln[i] - interpolated_u_nst(s, i), 2) * W;
       }
     } // for (unsigned ipt=0;ipt<n_intpt;ipt++)
   } // End of compute_error
References DIM, calibrate::error, ProblemParameters::exact_soln(), i, J, Eigen::bfloat16_impl::pow(), s, w, oomph::QuadTreeNames::W, and plotDoE::x.
compute_error() [3/5]
template<unsigned DIM> void oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::compute_error (std::ostream & outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double & error, double & norm) virtual
Validate against exact solution. Solution is provided via function pointer. Plot at a given number of plot points and compute L2 error and L2 norm of velocity solution over element
Validate against exact velocity solution Solution is provided via function pointer. Plot at a given number of plot points and compute L2 error and L2 norm of velocity solution over element.
Reimplemented from oomph::FiniteElement.
   {
     // Initialise the error norm value
     error = 0.0;
     // Initialise the solution norm value
     norm = 0.0;
     // Storage for the time value
     double interpolated_t = 0.0;
     // Vector of local coordinates
     Vector<double> s(DIM + 1, 0.0);
     // Vector for the spatial coordinates
     Vector<double> x(DIM, 0.0);
     // Set the value of n_intpt
     unsigned n_intpt = integral_pt()->nweight();
     // Output the tecplot header
     outfile << "ZONE" << std::endl;
     // Exact solution Vector (u,v,[w],p)
     Vector<double> exact_soln(DIM + 1, 0.0);
     // Loop over the integration points
     for (unsigned ipt = 0; ipt < n_intpt; ipt++)
     {
       // Assign values of s
       for (unsigned i = 0; i < DIM + 1; i++)
       {
         s[i] = integral_pt()->knot(ipt, i);
       }
       // Assign values of x
       for (unsigned i = 0; i < DIM; i++)
       {
         // Get x position as Vector
         x[i] = interpolated_x(s, i);
       }
       // Get the time value
       interpolated_t = interpolated_x(s, DIM);
       // Get exact solution at this point
       (*exact_soln_pt)(x, exact_soln);
       // Get the integral weight
       double w = integral_pt()->weight(ipt);
       // Get Jacobian of mapping
       double J = J_eulerian(s);
       // Premultiply the weights and the Jacobian
       double W = w * J;
       // Velocity error
       for (unsigned i = 0; i < DIM; i++)
       {
         // Update the solution norm value
         norm += exact_soln[i] * exact_soln[i] * W;
         // Update the error norm value
         error += pow(exact_soln[i] - interpolated_u_nst(s, i), 2) * W;
       }
       // Output x,y,...,u_exact
       for (unsigned i = 0; i < DIM; i++)
       {
         // Output the i-th coordinate value
         outfile << x[i] << " ";
       }
       // Output the time value at this point
       outfile << interpolated_t << " ";
       // Output x,y,u_error,v_error
       for (unsigned i = 0; i < DIM; i++)
       {
         // Output the error in the i-th velocity component at this point
         outfile << exact_soln[i] - interpolated_u_nst(s, i) << " ";
       }
       // Finish the line off
       outfile << std::endl;
     } // for (unsigned ipt=0;ipt<n_intpt;ipt++)
   } // End of compute_error
References DIM, calibrate::error, ProblemParameters::exact_soln(), i, J, Eigen::bfloat16_impl::pow(), s, w, oomph::QuadTreeNames::W, and plotDoE::x.
compute_error() [4/5]
template<unsigned DIM> void oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::compute_error (std::ostream & outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double & time, double & error, double & norm) virtual
Validate against exact solution at given time Solution is provided via function pointer. Plot at a given number of plot points and compute L2 error and L2 norm of velocity solution over element
Validate against exact velocity solution at given time. Solution is provided via function pointer. Plot at a given number of plot points and compute L2 error and L2 norm of velocity solution over element.
Reimplemented from oomph::FiniteElement.
   {
     // Initialise the error norm value
     error = 0.0;
     // Initialise the solution norm value
     norm = 0.0;
     // Storage for the time value
     double interpolated_t = 0.0;
     // Vector of local coordinates
     Vector<double> s(DIM + 1, 0.0);
     // Vector for the spatial coordinates
     Vector<double> x(DIM, 0.0);
     // Set the value of n_intpt
     unsigned n_intpt = integral_pt()->nweight();
     // Exact solution Vector (u,v,[w],p)
     Vector<double> exact_soln(DIM + 1, 0.0);
     // Loop over the integration points
     for (unsigned ipt = 0; ipt < n_intpt; ipt++)
     {
       // Assign values of s
       for (unsigned i = 0; i < DIM + 1; i++)
       {
         s[i] = integral_pt()->knot(ipt, i);
       }
       // Assign values of x
       for (unsigned i = 0; i < DIM; i++)
       {
         // Get x position as Vector
         x[i] = interpolated_x(s, i);
       }
       // Get the time value
       interpolated_t = interpolated_x(s, DIM);
       // Get exact solution at this point
       (*exact_soln_pt)(interpolated_t, x, exact_soln);
       // Get the integral weight
       double w = integral_pt()->weight(ipt);
       // Get Jacobian of mapping
       double J = J_eulerian(s);
       // Premultiply the weights and the Jacobian
       double W = w * J;
       // Velocity error
       for (unsigned i = 0; i < DIM; i++)
       {
         // Update the solution norm value
         norm += exact_soln[i] * exact_soln[i] * W;
         // Update the error norm value
         error += pow(exact_soln[i] - interpolated_u_nst(s, i), 2) * W;
       }
       // ------ DRAIG: REMOVE ----------------------------------------
       // Update the solution norm value
       norm += pow(exact_soln[DIM], 2) * W;
       // Update the error norm value
       error += pow(exact_soln[DIM] - interpolated_p_nst(s), 2) * W;
       // ------ DRAIG: REMOVE ----------------------------------------
     } // for (unsigned ipt=0;ipt<n_intpt;ipt++)
     //------------------------------------------------
     // Output the error at the appropriate plot points
     //------------------------------------------------
     // Just output at the default number of plot points
     unsigned n_plot = 5;
     // Tecplot header info
     outfile << tecplot_zone_string(n_plot);
     // How many plot points are there in total?
     unsigned num_plot_points = nplot_points(n_plot);
     // Loop over plot points
     for (unsigned i_plot = 0; i_plot < num_plot_points; i_plot++)
     {
       // Get local coordinates of plot point
       get_s_plot(i_plot, n_plot, s);
       // Loop over the spatial coordinates
       for (unsigned i = 0; i < DIM; i++)
       {
         // Assign the i-th spatial coordinate
         x[i] = interpolated_x(s, i);
       }
       // Get the time value
       interpolated_t = interpolated_x(s, DIM);
       // Get exact solution at this point
       (*exact_soln_pt)(interpolated_t, x, exact_soln);
       // Output x,y,...
       for (unsigned i = 0; i < DIM; i++)
       {
         // Output the i-th spatial coordinate
         outfile << x[i] << " ";
       }
       // Output the time value at this point
       outfile << interpolated_t << " ";
       // Output u_error,v_error
       for (unsigned i = 0; i < DIM; i++)
       {
         // Output the error in the i-th velocity component at this point
         outfile << exact_soln[i] - interpolated_u_nst(s, i) << " ";
       }
       // Output the error in the pressure field at this point
       outfile << exact_soln[DIM] - interpolated_p_nst(s) << " ";
       // End the line
       outfile << std::endl;
     } // for (unsigned i_plot=0;i_plot<num_plot_points;i_plot++)
     // Write tecplot footer (e.g. FE connectivity lists)
     write_tecplot_zone_footer(outfile, n_plot);
   } // End of compute_error
References DIM, calibrate::error, ProblemParameters::exact_soln(), i, J, Eigen::bfloat16_impl::pow(), s, w, oomph::QuadTreeNames::W, and plotDoE::x.
compute_error() [5/5]
template<unsigned DIM> void oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::compute_error (std::ostream & outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double & time, Vector< double > & error, Vector< double > & norm) virtual
Validate against exact solution at given time Solution is provided via function pointer. Plot at a given number of plot points and compute L2 error and L2 norm of velocity solution over element
Validate against exact velocity solution at given time. Solution is provided via function pointer. Plot at a given number of plot points and compute L2 error and L2 norm of velocity solution over element.
Reimplemented from oomph::FiniteElement.
   {
     // Resize the error norm vector
     error.resize(DIM + 1, 0.0);
     // Resize the solution norm vector
     norm.resize(DIM + 1, 0.0);
     // Storage for the time value
     double interpolated_t = 0.0;
     // Vector of local coordinates
     Vector<double> s(DIM + 1, 0.0);
     // Vector for the spatial coordinates
     Vector<double> x(DIM, 0.0);
     // Set the value of n_intpt
     unsigned n_intpt = integral_pt()->nweight();
     // Exact solution Vector (u,v,[w],p)
     Vector<double> exact_soln(DIM + 1, 0.0);
     // Loop over the integration points
     for (unsigned ipt = 0; ipt < n_intpt; ipt++)
     {
       // Assign values of s
       for (unsigned i = 0; i < DIM + 1; i++)
       {
         s[i] = integral_pt()->knot(ipt, i);
       }
       // Assign values of x
       for (unsigned i = 0; i < DIM; i++)
       {
         // Get x position as Vector
         x[i] = interpolated_x(s, i);
       }
       // Get the time value
       interpolated_t = interpolated_x(s, DIM);
       // Get exact solution at this point
       (*exact_soln_pt)(interpolated_t, x, exact_soln);
       // Get the integral weight
       double w = integral_pt()->weight(ipt);
       // Get Jacobian of mapping
       double J = J_eulerian(s);
       // Premultiply the weights and the Jacobian
       double W = w * J;
       // Velocity error
       for (unsigned i = 0; i < DIM; i++)
       {
         // Update the solution norm value
         norm[i] += exact_soln[i] * exact_soln[i] * W;
         // Update the error norm value
         error[i] += pow(exact_soln[i] - interpolated_u_nst(s, i), 2) * W;
       }
       // ------ DRAIG: REMOVE ----------------------------------------
       // Update the solution norm value
       norm[DIM] += pow(exact_soln[DIM], 2) * W;
       // Update the error norm value
       error[DIM] += pow(exact_soln[DIM] - interpolated_p_nst(s), 2) * W;
       // ------ DRAIG: REMOVE ----------------------------------------
     } // for (unsigned ipt=0;ipt<n_intpt;ipt++)
     //------------------------------------------------
     // Output the error at the appropriate plot points
     //------------------------------------------------
     // Just output at the default number of plot points
     unsigned n_plot = 5;
     // Tecplot header info
     outfile << tecplot_zone_string(n_plot);
     // How many plot points are there in total?
     unsigned num_plot_points = nplot_points(n_plot);
     // Loop over plot points
     for (unsigned i_plot = 0; i_plot < num_plot_points; i_plot++)
     {
       // Get local coordinates of plot point
       get_s_plot(i_plot, n_plot, s);
       // Loop over the spatial coordinates
       for (unsigned i = 0; i < DIM; i++)
       {
         // Assign the i-th spatial coordinate
         x[i] = interpolated_x(s, i);
       }
       // Get the time value
       interpolated_t = interpolated_x(s, DIM);
       // Get exact solution at this point
       (*exact_soln_pt)(interpolated_t, x, exact_soln);
       // Output x,y,...
       for (unsigned i = 0; i < DIM; i++)
       {
         // Output the i-th spatial coordinate
         outfile << x[i] << " ";
       }
       // Output the time value at this point
       outfile << interpolated_t << " ";
       // Output u_error,v_error
       for (unsigned i = 0; i < DIM; i++)
       {
         // Output the error in the i-th velocity component at this point
         outfile << exact_soln[i] - interpolated_u_nst(s, i) << " ";
       }
       // Output the error in the pressure field at this point
       outfile << exact_soln[DIM] - interpolated_p_nst(s) << " ";
       // End the line
       outfile << std::endl;
     } // for (unsigned i_plot=0;i_plot<num_plot_points;i_plot++)
     // Write tecplot footer (e.g. FE connectivity lists)
     write_tecplot_zone_footer(outfile, n_plot);
   } // End of compute_error
References DIM, calibrate::error, ProblemParameters::exact_soln(), i, J, Eigen::bfloat16_impl::pow(), s, w, oomph::QuadTreeNames::W, and plotDoE::x.
compute_norm()
template<unsigned DIM> void oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::compute_norm (Vector< double > & norm) virtual
Compute the vector norm of the FEM solution.
Compute the vector norm of FEM solution.
Reimplemented from oomph::GeneralisedElement.
   {
     // Resize the solution norm vector
     norm.resize(DIM + 1, 0.0);
     // Vector of local coordinates
     Vector<double> s(DIM + 1, 0.0);
     // Set the value of n_intpt
     unsigned n_intpt = integral_pt()->nweight();
     // Loop over the integration points
     for (unsigned ipt = 0; ipt < n_intpt; ipt++)
     {
       // Assign values of s
       for (unsigned i = 0; i < DIM + 1; i++)
       {
         s[i] = integral_pt()->knot(ipt, i);
       }
       // Get the integral weight
       double w = integral_pt()->weight(ipt);
       // Get Jacobian of mapping
       double J = J_eulerian(s);
       // Premultiply the weights and the Jacobian
       double W = w * J;
       // Compute the velocity norm
       for (unsigned i = 0; i < DIM; i++)
       {
         // Update the solution norm value
         norm[i] += pow(interpolated_u_nst(s, i), 2) * W;
       }
       // Update the pressure norm value
       norm[DIM] += pow(interpolated_p_nst(s), 2) * W;
     } // for (unsigned ipt=0;ipt<n_intpt;ipt++)
   } // End of compute_norm
References DIM, i, J, Eigen::bfloat16_impl::pow(), s, w, and oomph::QuadTreeNames::W.
d_kin_energy_dt()
template<unsigned DIM> double oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::d_kin_energy_dt
Get integral of time derivative of kinetic energy over element.
Get integral of time derivative of kinetic energy over element:
   {
     // Initialise
     double d_kin_en_dt = 0.0;
     // Set the value of n_intpt
     const unsigned n_intpt = integral_pt()->nweight();
     // Get the number of nodes
     const unsigned n_node = this->nnode();
     // Storage for the shape function
     Shape psi(n_node);
     DShape dpsidx(n_node, DIM + 1);
     // Get the value at which the velocities are stored
     unsigned u_index[DIM];
     for (unsigned i = 0; i < DIM; i++)
     {
       u_index[i] = this->u_index_nst(i);
     }
     // Loop over the integration points
     for (unsigned ipt = 0; ipt < n_intpt; ipt++)
     {
       // Get the jacobian of the mapping
       double J = dshape_eulerian_at_knot(ipt, psi, dpsidx);
       // Get the integral weight
       double w = integral_pt()->weight(ipt);
       // Now work out the velocity and the time derivative
       Vector<double> interpolated_u(DIM, 0.0);
       Vector<double> interpolated_dudt(DIM, 0.0);
       // Loop over the shape functions
       for (unsigned l = 0; l < n_node; l++)
       {
         // Loop over the dimensions
         for (unsigned i = 0; i < DIM; i++)
         {
           interpolated_u[i] += nodal_value(l, u_index[i]) * psi(l);
           interpolated_dudt[i] += du_dt_nst(l, u_index[i]) * psi(l);
         }
       }
       // Get mesh velocity bit
       if (!ALE_is_disabled)
       {
         Vector<double> mesh_velocity(DIM, 0.0);
         DenseMatrix<double> interpolated_dudx(DIM, DIM, 0.0);
         // Loop over nodes again
         for (unsigned l = 0; l < n_node; l++)
         {
           for (unsigned i = 0; i < DIM; i++)
           {
             mesh_velocity[i] += this->dnodal_position_dt(l, i) * psi(l);
             for (unsigned j = 0; j < DIM; j++)
             {
               interpolated_dudx(i, j) +=
                 this->nodal_value(l, u_index[i]) * dpsidx(l, j);
             }
           }
         }
         // Subtract mesh velocity from du_dt
         for (unsigned i = 0; i < DIM; i++)
         {
           for (unsigned k = 0; k < DIM; k++)
           {
             interpolated_dudt[i] -= mesh_velocity[k] * interpolated_dudx(i, k);
           }
         }
       }
       // Loop over directions and add up u du/dt  terms
       double sum = 0.0;
       for (unsigned i = 0; i < DIM; i++)
       {
         sum += interpolated_u[i] * interpolated_dudt[i];
       }
       d_kin_en_dt += sum * w * J;
     }
     return d_kin_en_dt;
   } // End of d_kin_energy_dt
References oomph::ALE_is_disabled, DIM, i, J, j, k, and w.
delete_pressure_advection_diffusion_robin_elements()
template<unsigned DIM> void oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::delete_pressure_advection_diffusion_robin_elements () inline virtual
Delete the FaceElements that apply the Robin boundary condition to the pressure advection diffusion problem required by Fp preconditioner
Implements oomph::TemplateFreeSpaceTimeNavierStokesMixedOrderEquationsBase.
     {
       unsigned nel = Pressure_advection_diffusion_robin_element_pt.size();
       for (unsigned e = 0; e < nel; e++)
       {
         delete Pressure_advection_diffusion_robin_element_pt[e];
       }
       Pressure_advection_diffusion_robin_element_pt.clear();
     } // End of delete_pressure_advection_diffusion_robin_elements
References e(), and oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::Pressure_advection_diffusion_robin_element_pt.
density_ratio()
template<unsigned DIM> const double& oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::density_ratio () const inline
Density ratio for element: Element's density relative to the viscosity used in the definition of the Reynolds number
     {
       return *Density_Ratio_pt;
     }
References oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::Density_Ratio_pt.
density_ratio_pt()
template<unsigned DIM> double*& oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::density_ratio_pt () inline
Pointer to Density ratio.
     {
       return Density_Ratio_pt;
     }
References oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::Density_Ratio_pt.
dinterpolated_u_nst_ddata()
template<unsigned DIM> virtual void oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::dinterpolated_u_nst_ddata (const Vector< double > & s, const unsigned & i, Vector< double > & du_ddata, Vector< unsigned > & global_eqn_number) inline virtual
Compute the derivatives of the i-th component of velocity at point s with respect to all data that can affect its value. In addition, return the global equation numbers corresponding to the data. The function is virtual so that it can be overloaded in the refineable version
Reimplemented in oomph::RefineableSpaceTimeNavierStokesMixedOrderEquations< DIM >.
     {
       // Find the number of nodes
       unsigned n_node = nnode();
       // Local shape function
       Shape psi(n_node);
       // Find values of shape function
       shape_u_nst(s, psi);
       // Get nodal index at which i-th velocity is stored
       unsigned u_nodal_index = u_index_nst(i);
       // Find the number of dofs associated with interpolated u
       unsigned n_u_dof = 0;
       // Loop over the nodes
       for (unsigned l = 0; l < n_node; l++)
       {
         // Get the global equation number of the dof
         int global_eqn = this->node_pt(l)->eqn_number(u_nodal_index);
         // If it's positive add to the count
         if (global_eqn >= 0)
         {
           // Increment the counter
           n_u_dof++;
         }
       } // End of dinterpolated_u_nst_ddata
       // Now resize the storage schemes
       du_ddata.resize(n_u_dof, 0.0);
       global_eqn_number.resize(n_u_dof, 0);
       // Loop over th nodes again and set the derivatives
       unsigned count = 0;
       // Loop over the local nodes and sum
       for (unsigned l = 0; l < n_node; l++)
       {
         // Get the global equation number
         int global_eqn = this->node_pt(l)->eqn_number(u_nodal_index);
         if (global_eqn >= 0)
         {
           // Set the global equation number
           global_eqn_number[count] = global_eqn;
           // Set the derivative with respect to the unknown
           du_ddata[count] = psi[l];
           // Increase the counter
           ++count;
         }
       }
     } // End of dinterpolated_u_nst_ddata
References oomph::Data::eqn_number(), i, oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), s, oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::shape_u_nst(), and oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::u_index_nst().
disable_ALE()
template<unsigned DIM> void oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::disable_ALE () inline virtual
Disable ALE, i.e. assert the mesh is not moving – you do this at your own risk!
Reimplemented from oomph::FiniteElement.
     {
       ALE_is_disabled = true;
     } // End of disable_ALE
References oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::ALE_is_disabled.
dissipation() [1/2]
template<unsigned DIM> double oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::dissipation
Return integral of dissipation over element.
   {
     // Initialise the elemental dissipation value
     double diss = 0.0;
     // Set the value of n_intpt
     unsigned n_intpt = integral_pt()->nweight();
     // Set the Vector to hold local coordinates
     Vector<double> s(DIM + 1, 0.0);
     // Loop over the integration points
     for (unsigned ipt = 0; ipt < n_intpt; ipt++)
     {
       // Assign values of s
       for (unsigned i = 0; i < DIM + 1; i++)
       {
         // Calculate the i-th local coordinate value
         s[i] = integral_pt()->knot(ipt, i);
       }
       // Get the integral weight
       double w = integral_pt()->weight(ipt);
       // Get Jacobian of mapping
       double J = J_eulerian(s);
       // Storage for the strain rate matrix
       DenseMatrix<double> strainrate(DIM, DIM);
       // Get strain rate matrix
       strain_rate(s, strainrate);
       // Initialise the local dissipation
       double local_diss = 0.0;
       // Loop over the coordinate directions
       for (unsigned i = 0; i < DIM; i++)
       {
         // Loop over the coordinate directions
         for (unsigned j = 0; j < DIM; j++)
         {
           // Update the local dissipation value
           local_diss += 2.0 * strainrate(i, j) * strainrate(i, j);
         }
       } // for (unsigned i=0;i<DIM;i++)
       // Update the elemental dissipation value
       diss += local_diss * w * J;
     } // for (unsigned ipt=0;ipt<n_intpt;ipt++)
     // Return the elemental dissipation value
     return diss;
   } // End of dissipation
References DIM, i, J, j, s, and w.
dissipation() [2/2]
template<unsigned DIM> double oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::dissipation (const Vector< double > & s) const
Return dissipation at local coordinate s.
   {
     // Get strain rate matrix
     DenseMatrix<double> strainrate(DIM, DIM);
     strain_rate(s, strainrate);
     // Initialise
     double local_diss = 0.0;
     for (unsigned i = 0; i < DIM; i++)
     {
       for (unsigned j = 0; j < DIM; j++)
       {
         local_diss += 2.0 * strainrate(i, j) * strainrate(i, j);
       }
     }
     return local_diss;
   }
References DIM, i, j, and s.
dpshape_and_dptest_eulerian_nst()
template<unsigned DIM> virtual double oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::dpshape_and_dptest_eulerian_nst (const Vector< double > & s, Shape & ppsi, DShape & dppsidx, Shape & ptest, DShape & dptestdx) const protected pure virtual
Compute the pressure shape and test functions and derivatives w.r.t. global coords at local coordinate s. Return Jacobian of mapping between local and global coordinates.
Implemented in oomph::QTaylorHoodMixedOrderSpaceTimeElement< DIM >, oomph::QTaylorHoodMixedOrderSpaceTimeElement< 2 >, oomph::QTaylorHoodMixedOrderSpaceTimeElement< DIM >, and oomph::QTaylorHoodMixedOrderSpaceTimeElement< 2 >.
dpshape_eulerian()
template<unsigned DIM> virtual double oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::dpshape_eulerian (const Vector< double > & s, Shape & ppsi, DShape & dppsidx) const protected pure virtual
Pressure shape functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry). Return Jacobian of mapping between local and global coordinates.
Implemented in oomph::QTaylorHoodMixedOrderSpaceTimeElement< DIM >, oomph::QTaylorHoodMixedOrderSpaceTimeElement< 2 >, oomph::QTaylorHoodMixedOrderSpaceTimeElement< DIM >, and oomph::QTaylorHoodMixedOrderSpaceTimeElement< 2 >.
dptest_eulerian()
template<unsigned DIM> virtual double oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::dptest_eulerian (const Vector< double > & s, Shape & ptest, DShape & dptestdx) const protected pure virtual
Pressure test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry). Return Jacobian of mapping between local and global coordinates.
Implemented in oomph::QTaylorHoodMixedOrderSpaceTimeElement< DIM >, oomph::QTaylorHoodMixedOrderSpaceTimeElement< 2 >, oomph::QTaylorHoodMixedOrderSpaceTimeElement< DIM >, and oomph::QTaylorHoodMixedOrderSpaceTimeElement< 2 >.
dshape_and_dtest_eulerian_at_knot_nst() [1/2]
template<unsigned DIM> virtual double oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::dshape_and_dtest_eulerian_at_knot_nst (const unsigned & ipt, Shape & psi, DShape & dpsidx, RankFourTensor< double > & d_dpsidx_dX, Shape & test, DShape & dtestdx, RankFourTensor< double > & d_dtestdx_dX, DenseMatrix< double > & djacobian_dX) const protected pure virtual
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping (J). Also compute derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
Implemented in oomph::QTaylorHoodMixedOrderSpaceTimeElement< DIM >, oomph::QTaylorHoodMixedOrderSpaceTimeElement< 2 >, oomph::QTaylorHoodMixedOrderSpaceTimeElement< DIM >, and oomph::QTaylorHoodMixedOrderSpaceTimeElement< 2 >.
dshape_and_dtest_eulerian_at_knot_nst() [2/2]
template<unsigned DIM> virtual double oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::dshape_and_dtest_eulerian_at_knot_nst (const unsigned & ipt, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const protected pure virtual
Compute the shape functions and derivatives w.r.t. global coords at ipt-th integration point Return Jacobian of mapping between local and global coordinates.
Implemented in oomph::QTaylorHoodMixedOrderSpaceTimeElement< DIM >, and oomph::QTaylorHoodMixedOrderSpaceTimeElement< 2 >.
dshape_and_dtest_eulerian_nst()
template<unsigned DIM> virtual double oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::dshape_and_dtest_eulerian_nst (const Vector< double > & s, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const protected pure virtual
Compute the shape functions and derivatives w.r.t. global coords at local coordinate s. Return Jacobian of mapping between local and global coordinates.
Implemented in oomph::QTaylorHoodMixedOrderSpaceTimeElement< DIM >, and oomph::QTaylorHoodMixedOrderSpaceTimeElement< 2 >.
dshape_local_u_nst()
template<unsigned DIM> virtual void oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::dshape_local_u_nst (const Vector< double > & s, Shape & psi, DShape & dpsidx) const protected pure virtual
DRAIG: Fill in later...
Implemented in oomph::QTaylorHoodMixedOrderSpaceTimeElement< DIM >, oomph::QTaylorHoodMixedOrderSpaceTimeElement< 2 >, oomph::QTaylorHoodMixedOrderSpaceTimeElement< DIM >, and oomph::QTaylorHoodMixedOrderSpaceTimeElement< 2 >.
Referenced by oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::interpolated_du_dt_nst().
dtest_local_u_nst()
template<unsigned DIM> virtual void oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::dtest_local_u_nst (const Vector< double > & s, Shape & test, DShape & dtestdx) const protected pure virtual
DRAIG: Fill in later...
Implemented in oomph::QTaylorHoodMixedOrderSpaceTimeElement< DIM >, oomph::QTaylorHoodMixedOrderSpaceTimeElement< 2 >, oomph::QTaylorHoodMixedOrderSpaceTimeElement< DIM >, and oomph::QTaylorHoodMixedOrderSpaceTimeElement< 2 >.
du_dt_nst()
template<unsigned DIM> double oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::du_dt_nst (const unsigned & n, const unsigned & i) const inline
i-th component of du/dt at local node n. Uses suitably interpolated value for hanging nodes.
     {
       // Storage for the local coordinates
       Vector<double> s(DIM + 1, 0.0);
       // Get the local coordinate at the n-th node
       local_coordinate_of_node(n, s);
       // Return the interpolated du_i/dt value
       return interpolated_du_dt_nst(s, i);
     } // End of du_dt_nst
References DIM, i, oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::interpolated_du_dt_nst(), oomph::FiniteElement::local_coordinate_of_node(), n, and s.
Referenced by oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::get_du_dt().
enable_ALE()
template<unsigned DIM> void oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::enable_ALE () inline virtual
(Re-)enable ALE, i.e. take possible mesh motion into account when evaluating the time-derivative. Note: By default, ALE is enabled, at the expense of possibly creating unnecessary work in problems where the mesh is, in fact, stationary.
Reimplemented from oomph::FiniteElement.
     {
       ALE_is_disabled = false;
     } // End of enable_ALE
References oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::ALE_is_disabled.
fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter()
template<unsigned DIM> void oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter (double *const & parameter_pt, Vector< double > & dres_dparam, DenseMatrix< double > & djac_dparam, DenseMatrix< double > & dmass_matrix_dparam) inline virtual
Add the element's contribution to its residuals vector, jacobian matrix and mass matrix
Reimplemented from oomph::GeneralisedElement.
     {
       // Do we want to compute the Jacobian AND mass matrix? ANSWER: Yes!
       unsigned compute_matrices_flag = 2;
       // Call the generic routine with the appropriate flag
       fill_in_generic_dresidual_contribution_nst(parameter_pt,
                                                  dres_dparam,
                                                  djac_dparam,
                                                  dmass_matrix_dparam,
                                                  compute_matrices_flag);
     } // End of fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter
References oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::fill_in_generic_dresidual_contribution_nst().
fill_in_contribution_to_djacobian_dparameter()
template<unsigned DIM> void oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::fill_in_contribution_to_djacobian_dparameter (double *const & parameter_pt, Vector< double > & dres_dparam, DenseMatrix< double > & djac_dparam) inline virtual
Compute the element's residual Vector and the jacobian matrix Virtual function can be overloaded by hanging-node version
Reimplemented from oomph::GeneralisedElement.
     {
       // Do we want to compute the Jacobian? ANSWER: Yes!
       unsigned compute_jacobian_flag = 1;
       // Call the generic routine with the flag set to 1
       fill_in_generic_dresidual_contribution_nst(
         parameter_pt,
         dres_dparam,
         djac_dparam,
         GeneralisedElement::Dummy_matrix,
         compute_jacobian_flag);
     } // End of fill_in_contribution_to_djacobian_dparameter
References oomph::GeneralisedElement::Dummy_matrix, and oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::fill_in_generic_dresidual_contribution_nst().
fill_in_contribution_to_dresiduals_dparameter()
template<unsigned DIM> void oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::fill_in_contribution_to_dresiduals_dparameter (double *const & parameter_pt, Vector< double > & dres_dparam) inline virtual
Compute the element's residual Vector (differentiated w.r.t. a parameter)
Reimplemented from oomph::GeneralisedElement.
     {
       // Do we want to compute the Jacobian? ANSWER: No!
       unsigned compute_jacobian_flag = 0;
       // Call the generic residuals function using a dummy matrix argument
       fill_in_generic_dresidual_contribution_nst(
         parameter_pt,
         dres_dparam,
         GeneralisedElement::Dummy_matrix,
         GeneralisedElement::Dummy_matrix,
         compute_jacobian_flag);
     } // End of fill_in_contribution_to_dresiduals_dparameter
References oomph::GeneralisedElement::Dummy_matrix, and oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::fill_in_generic_dresidual_contribution_nst().
fill_in_contribution_to_hessian_vector_products()
template<unsigned DIM> void oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::fill_in_contribution_to_hessian_vector_products (Vector< double > const & Y, DenseMatrix< double > const & C, DenseMatrix< double > & product) protected virtual
Compute the hessian tensor vector products required to perform continuation of bifurcations analytically
Reimplemented from oomph::GeneralisedElement.
   {
     // Throw an error
     throw OomphLibError("Not yet implemented\n",
                         OOMPH_CURRENT_FUNCTION,
                         OOMPH_EXCEPTION_LOCATION);
   } // End of fill_in_contribution_to_hessian_vector_products
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
fill_in_contribution_to_jacobian()
template<unsigned DIM> void oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) inline virtual
Compute the element's residual Vector and the jacobian matrix Virtual function can be overloaded by hanging-node version
Reimplemented from oomph::FiniteElement.
     {
       // Do we want to compute the Jacobian? ANSWER: Yes!
       unsigned compute_jacobian_flag = 1;
       // Call the generic routine with the flag set to 1
       fill_in_generic_residual_contribution_nst(
         residuals,
         jacobian,
         GeneralisedElement::Dummy_matrix,
         compute_jacobian_flag);
     } // End of fill_in_contribution_to_residuals
References oomph::GeneralisedElement::Dummy_matrix, and oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::fill_in_generic_residual_contribution_nst().
fill_in_contribution_to_jacobian_and_mass_matrix()
template<unsigned DIM> void oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > & residuals, DenseMatrix< double > & jacobian, DenseMatrix< double > & mass_matrix) inline virtual
Add the element's contribution to its residuals vector, jacobian matrix and mass matrix
Reimplemented from oomph::GeneralisedElement.
     {
       // Do we want to compute the Jacobian AND mass matrix? ANSWER: Yes!
       unsigned compute_matrices_flag = 2;
       // Call the generic routine with the flag set to 2
       fill_in_generic_residual_contribution_nst(
         residuals, jacobian, mass_matrix, compute_matrices_flag);
     } // End of fill_in_contribution_to_jacobian_and_mass_matrix
References oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::fill_in_generic_residual_contribution_nst().
fill_in_contribution_to_residuals()
template<unsigned DIM> void oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::fill_in_contribution_to_residuals (Vector< double > & residuals) inline virtual
Compute the element's residual Vector.
Reimplemented from oomph::GeneralisedElement.
     {
       // Do we want to compute the Jacobian? ANSWER: No!
       unsigned compute_jacobian_flag = 0;
       // Call the generic residuals function using a dummy matrix argument
       fill_in_generic_residual_contribution_nst(
         residuals,
         GeneralisedElement::Dummy_matrix,
         GeneralisedElement::Dummy_matrix,
         compute_jacobian_flag);
     } // End of fill_in_contribution_to_residuals
References oomph::GeneralisedElement::Dummy_matrix, and oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::fill_in_generic_residual_contribution_nst().
fill_in_generic_dresidual_contribution_nst()
template<unsigned DIM> void oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::fill_in_generic_dresidual_contribution_nst (double *const & parameter_pt, Vector< double > & dres_dparam, DenseMatrix< double > & djac_dparam, DenseMatrix< double > & dmass_matrix_dparam, const unsigned & flag) protected virtual
Compute the derivatives of the residuals for the Navier-Stokes equations with respect to a parameter Flag=1 (or 0): do (or don't) compute the Jacobian as well. Flag=2: Fill in mass matrix too.
Compute the derivatives of the residuals for the Navier-Stokes equations with respect to a parameter; flag=2 or 1 or 0: do (or don't) compute the Jacobian and mass matrix as well
   {
     // Throw an error
     throw OomphLibError("Not yet implemented\n",
                         OOMPH_CURRENT_FUNCTION,
                         OOMPH_EXCEPTION_LOCATION);
   } // End of fill_in_generic_dresidual_contribution_nst
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
Referenced by oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::fill_in_contribution_to_djacobian_dparameter(), and oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::fill_in_contribution_to_dresiduals_dparameter().
fill_in_generic_pressure_advection_diffusion_contribution_nst()
template<unsigned DIM> void oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::fill_in_generic_pressure_advection_diffusion_contribution_nst (Vector< double > & residuals, DenseMatrix< double > & jacobian, const unsigned & flag) protected virtual
Compute the residuals for the associated pressure advection diffusion problem. Used by the Fp preconditioner. flag=1(or 0): do (or don't) compute the Jacobian as well.
Reimplemented in oomph::RefineableSpaceTimeNavierStokesMixedOrderEquations< DIM >.
   {
     // Throw an error
     throw OomphLibError("Not yet implemented\n",
                         OOMPH_CURRENT_FUNCTION,
                         OOMPH_EXCEPTION_LOCATION);
   } // End of fill_in_generic_pressure_advection_diffusion_contribution_nst
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
Referenced by oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::fill_in_pressure_advection_diffusion_jacobian(), and oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::fill_in_pressure_advection_diffusion_residuals().
fill_in_generic_residual_contribution_nst()
template<unsigned DIM> void oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::fill_in_generic_residual_contribution_nst (Vector< double > & residuals, DenseMatrix< double > & jacobian, DenseMatrix< double > & mass_matrix, const unsigned & flag) protected virtual
Compute the residuals for the Navier-Stokes equations. Flag=1 (or 0): do (or don't) compute the Jacobian as well. Flag=2: Fill in mass matrix too.
Compute the residuals for the Navier-Stokes equations; flag=1 (or 0): do (or don't) compute the Jacobian as well.
Reimplemented in oomph::RefineableSpaceTimeNavierStokesMixedOrderEquations< DIM >.
   {
     // Return immediately if there are no dofs
     if (ndof() == 0) return;
     // Find out how many nodes there are
     unsigned n_node = nnode();
     // Find out how many pressure dofs there are
     unsigned n_pres = npres_nst();
     // Allocate storage for the indices of the velocity components
     unsigned u_nodal_index[DIM];
     // Loop over the velocity components
     for (unsigned i = 0; i < DIM; i++)
     {
       // Find the index at which the i-th local velocity is stored
       u_nodal_index[i] = u_index_nst(i);
     }
     // Set up memory for the shape functions
     Shape psif(n_node);
     // Set up memory for the test functions
     Shape testf(n_node);
     // Allocate space for the derivatives of the shape functions
     DShape dpsifdx(n_node, DIM + 1);
     // Allocate space for the derivatives of the test functions
     DShape dtestfdx(n_node, DIM + 1);
     // Set up memory for pressure shape functions
     Shape psip(n_pres);
     // Set up memory for pressure test functions
     Shape testp(n_pres);
     // Number of integration points
     unsigned n_intpt = integral_pt()->nweight();
     // Set the Vector to hold local coordinates
     Vector<double> s(DIM + 1, 0.0);
     //-------------------------------------
     // Get physical variables from element:
     //-------------------------------------
     // Reynolds number must be multiplied by the density ratio
     double scaled_re = re() * density_ratio();
     // Get the scaled Strouhal value
     double scaled_re_st = re_st() * density_ratio();
     // Get the scaled Womersley number differentiated w.r.t. the Womersley
     // number
     double scaled_dre_st_dre_st = density_ratio();
     // Get the scaled Reynolds / Froude number
     double scaled_re_inv_fr = re_invfr() * density_ratio();
     // Get the viscosity ratio
     double visc_ratio = viscosity_ratio();
     // Get the gravity vector
     Vector<double> G = g();
     // Integer to store the local equation number
     int local_eqn = 0;
     // Integer to store the local unknown number
     int local_unknown = 0;
     // Loop over the integration points
     for (unsigned ipt = 0; ipt < n_intpt; ipt++)
     {
       // Assign values of s
       for (unsigned i = 0; i < DIM + 1; i++)
       {
         // Calculate the i-th local coordinate
         s[i] = integral_pt()->knot(ipt, i);
       }
       // Get the integral weight
       double w = integral_pt()->weight(ipt);
       // Call the derivatives of the shape and test functions
       double J = dshape_and_dtest_eulerian_at_knot_nst(
         ipt, psif, dpsifdx, testf, dtestfdx);
       // Call the pressure shape and test functions
       pshape_nst(s, psip, testp);
       // Pre-multiply the weights and the Jacobian
       double W = w * J;
       // Storage for the interpolated time value
       double interpolated_t = 0.0;
       // Storage for the interpolated pressure value
       double interpolated_p = 0.0;
       // Storage for the spatial coordinates
       Vector<double> interpolated_x(DIM, 0.0);
       // Storage for the interpolated velocity components
       Vector<double> interpolated_u(DIM, 0.0);
       // Storage for the interpolated time-derivative of the velocities
       Vector<double> interpolated_dudt(DIM, 0.0);
       // Storage for the mesh velocity
       Vector<double> mesh_velocity(DIM, 0.0);
       // Storage for the spatial derivatives of the velocity components
       DenseMatrix<double> interpolated_dudx(DIM, DIM, 0.0);
       // Calculate pressure
       for (unsigned l = 0; l < n_pres; l++)
       {
         // Update the current approximation to the interpolated pressure
         interpolated_p += p_nst(l) * psip[l];
       }
       //-------------------------------------------------------------------
       // Calculate velocities, derivatives, source function and body force:
       //-------------------------------------------------------------------
       // Loop over nodes
       for (unsigned l = 0; l < n_node; l++)
       {
         // Update the interpolated time value
         interpolated_t += raw_nodal_position(l, DIM) * psif(l);
         // Loop over coordinate directions
         for (unsigned i = 0; i < DIM; i++)
         {
           // Get the nodal value
           double u_value = raw_nodal_value(l, u_nodal_index[i]);
           // Update the i-th interpolated velocity component
           interpolated_u[i] += u_value * psif[l];
           // Update the i-th interpolated coordinate value
           interpolated_x[i] += raw_nodal_position(l, i) * psif[l];
           // Update the interpolated du_i/dt value
           interpolated_dudt[i] += u_value * dpsifdx(l, DIM);
           // Loop over derivative directions
           for (unsigned j = 0; j < DIM; j++)
           {
             // Update the interpolated du_i/dx_j value
             interpolated_dudx(i, j) += u_value * dpsifdx(l, j);
           }
         } // for (unsigned i=0;i<DIM;i++)
       } // for (unsigned l=0;l<n_node;l++)
       // If ALE is enabled
       if (!ALE_is_disabled)
       {
         // Loop over nodes
         for (unsigned l = 0; l < n_node; l++)
         {
           // Loop over directions
           for (unsigned i = 0; i < DIM; i++)
           {
             // Update the i-th mesh velocity component
             mesh_velocity[i] += raw_nodal_position(l, i) * dpsifdx(l, DIM);
           }
         } // for (unsigned l=0;l<n_node;l++)
       } // if (!ALE_is_disabled)
       // Allocate space for the body force
       Vector<double> body_force(DIM, 0.0);
       // Get the user-defined body force term
       get_body_force_nst(interpolated_t, ipt, s, interpolated_x, body_force);
       // Get the user-defined source function
       double source = get_source_nst(interpolated_t, ipt, interpolated_x);
       //---------------------------------
       // Assemble residuals and Jacobian:
       //---------------------------------
       //--------------------
       // Momentum equations:
       //--------------------
       // Loop over the test functions
       for (unsigned l = 0; l < n_node; l++)
       {
         // Loop over the velocity components
         for (unsigned i = 0; i < DIM; i++)
         {
           // Get the local equation number associated with this unknown and node
           local_eqn = nodal_local_eqn(l, u_nodal_index[i]);
           // If it's not a boundary condition
           if (local_eqn >= 0)
           {
             // Add the user-defined body force terms
             residuals[local_eqn] += body_force[i] * testf[l] * W;
             // Add the gravitational body force term
             residuals[local_eqn] += scaled_re_inv_fr * testf[l] * G[i] * W;
             // Add the pressure gradient term
             residuals[local_eqn] += interpolated_p * dtestfdx(l, i) * W;
             // Add in the contribution from the time derivative
             residuals[local_eqn] -=
               scaled_re_st * interpolated_dudt[i] * testf[l] * W;
             // If ALE is enabled
             if (!ALE_is_disabled)
             {
               // Loop over the coordinate directions
               for (unsigned k = 0; k < DIM; k++)
               {
                 // Add in the mesh velocity contribution
                 residuals[local_eqn] +=
                   (scaled_re_st * mesh_velocity[k] * interpolated_dudx(i, k) *
                    testf[l] * W);
               }
             } // if (!ALE_is_disabled)
             // Loop over the coordinate directions
             for (unsigned k = 0; k < DIM; k++)
             {
               // Add in the convective term contribution
               residuals[local_eqn] -= (scaled_re * interpolated_u[k] *
                                        interpolated_dudx(i, k) * testf[l] * W);
             }
             // Loop over the coordinate directions
             for (unsigned k = 0; k < DIM; k++)
             {
               // Add in the stress tensor terms:
               // NOTE: The viscosity ratio needs to go in here to ensure
               // continuity of normal stress is satisfied even in flows
               // with zero pressure gradient!
               residuals[local_eqn] -= ((interpolated_dudx(i, k) +
                                         Gamma[i] * interpolated_dudx(k, i)) *
                                        visc_ratio * dtestfdx(l, k) * W);
             }
             //------------------------
             // Calculate the Jacobian:
             //------------------------
             // If we also need to construct the Jacobian
             if (flag)
             {
               // Loop over the velocity shape functions again
               for (unsigned l2 = 0; l2 < n_node; l2++)
               {
                 // Loop over the velocity components again
                 for (unsigned i2 = 0; i2 < DIM; i2++)
                 {
                   // Get the local equation number associated with this unknown
                   local_unknown = nodal_local_eqn(l2, u_nodal_index[i2]);
                   // If we're at a proper degree of freedom
                   if (local_unknown >= 0)
                   {
                     // Add the contribution to the elemental matrix
                     jacobian(local_eqn, local_unknown) -=
                       (visc_ratio * Gamma[i] * dpsifdx(l2, i) *
                        dtestfdx(l, i2) * W);
                     // Now add in the inertial terms
                     jacobian(local_eqn, local_unknown) -=
                       (scaled_re * psif[l2] * interpolated_dudx(i, i2) *
                        testf[l] * W);
                     // Extra component if i2=i
                     if (i2 == i)
                     {
                       // If we also need to construct the mass matrix (only
                       // diagonal entries)
                       if (flag == 2)
                       {
                         // NOTE: This is positive because the mass matrix is
                         // taken to the other side of the equation when
                         // formulating the generalised eigenproblem.
                         mass_matrix(local_eqn, local_unknown) +=
                           (scaled_re_st * psif[l2] * testf[l] * W);
                       }
                       // Add in the time-derivative contribution
                       jacobian(local_eqn, local_unknown) -=
                         (scaled_re_st * dpsifdx(l2, DIM) * testf[l] * W);
                       // If ALE is enabled
                       if (!ALE_is_disabled)
                       {
                         // Loop over the velocity components
                         for (unsigned k = 0; k < DIM; k++)
{
                           // Add in the mesh velocity contribution
                           jacobian(local_eqn, local_unknown) +=
                             (scaled_re_st * mesh_velocity[k] * dpsifdx(l2, k) *
                              testf[l] * W);
                         }
                       } // if (!ALE_is_disabled)
                       // Loop over the velocity components
                       for (unsigned k = 0; k < DIM; k++)
                       {
                         // Add in the convective term contribution
                         jacobian(local_eqn, local_unknown) -=
                           (scaled_re * interpolated_u[k] * dpsifdx(l2, k) *
                            testf[l] * W);
                       }
                       // Loop over the velocity components
                       for (unsigned k = 0; k < DIM; k++)
                       {
                         // Add in the velocity gradient terms
                         jacobian(local_eqn, local_unknown) -=
                           (visc_ratio * dpsifdx(l2, k) * dtestfdx(l, k) * W);
                       }
                     } // if (i2==i)
                   } // if (local_unknown>=0)
                 } // for (unsigned i2=0;i2<DIM;i2++)
               } // for (unsigned l2=0;l2<n_node;l2++)
               // Loop over pressure shape functions
               for (unsigned l2 = 0; l2 < n_pres; l2++)
               {
                 // Get the local equation number associated with this degree of
                 // freedom
                 local_unknown = p_local_eqn(l2);
                 // If we are at a proper degree of freedom
                 if (local_unknown >= 0)
                 {
                   // Add in the pressure gradient contribution
                   jacobian(local_eqn, local_unknown) +=
                     psip[l2] * dtestfdx(l, i) * W;
                 }
               } // for (unsigned l2=0;l2<n_pres;l2++)
               //------------------------------------
               // Calculate external data information
               //------------------------------------
               // If we're storing the Strouhal number as external data then we
               // need to calculate dr/d(St) in the elemental Jacobian
               if (ReynoldsStrouhal_is_stored_as_external_data)
               {
                 // The index of the external data (there's only one!)
                 unsigned data_index = 0;
                 // The index of the unknown value stored in the external data
                 unsigned value_index = 0;
                 // Get the local equation number associated with the extra
                 // unknown
                 local_unknown =
                   this->external_local_eqn(data_index, value_index);
                 // If we're at a non-zero degree of freedom add in the entry
                 if (local_unknown >= 0)
                 {
                   // Add in the contribution from the time derivative
                   jacobian(local_eqn, local_unknown) -=
                     (scaled_dre_st_dre_st * interpolated_dudt[i] * testf[l] *
                      W);
                   // If ALE is enabled
                   if (!ALE_is_disabled)
                   {
                     // Loop over the coordinate directions
                     for (unsigned k = 0; k < DIM; k++)
                     {
                       // Add in the mesh velocity contribution
                       jacobian(local_eqn, local_unknown) +=
                         (scaled_dre_st_dre_st * mesh_velocity[k] *
                          interpolated_dudx(i, k) * testf[l] * W);
                     }
                   } // if (!ALE_is_disabled)
                 } // if (local_unknown>=0)
               } // if (Strouhal_is_stored_as_external_data)
             } // if (flag)
           } // if (local_eqn>=0)
         } // for (unsigned i=0;i<DIM;i++)
       } // for (unsigned l=0;l<n_node;l++)
       //---------------------
       // Continuity equation:
       //---------------------
       // Loop over the shape functions
       for (unsigned l = 0; l < n_pres; l++)
       {
         // Get the local equation number associated with the pressure dof
         local_eqn = p_local_eqn(l);
         // If it's not a boundary condition
         if (local_eqn >= 0)
         {
           // Add in the source term contribution
           residuals[local_eqn] -= source * testp[l] * W;
           // Loop over velocity components
           for (unsigned k = 0; k < DIM; k++)
           {
             // Add in the velocity gradient terms
             residuals[local_eqn] += interpolated_dudx(k, k) * testp[l] * W;
           }
           //------------------------
           // Calculate the Jacobian:
           //------------------------
           // If we also need to construct the Jacobian
           if (flag)
           {
             // Loop over the velocity shape functions
             for (unsigned l2 = 0; l2 < n_node; l2++)
             {
               // Loop over velocity components
               for (unsigned i2 = 0; i2 < DIM; i2++)
               {
                 // Get the local equation number associated with this node
                 local_unknown = nodal_local_eqn(l2, u_nodal_index[i2]);
                 // If we're at a proper degree of freedom
                 if (local_unknown >= 0)
                 {
                   // Add in the velocity gradient contribution
                   jacobian(local_eqn, local_unknown) +=
                     dpsifdx(l2, i2) * testp[l] * W;
                 }
               } // for (unsigned i2=0;i2<DIM;i2++)
             } // for (unsigned l2=0;l2<n_node;l2++)
           } // if (flag)
         } // if (local_eqn>=0)
       } // for (unsigned l=0;l<n_pres;l++)
     } // for (unsigned ipt=0;ipt<n_intpt;ipt++)
   } // End of fill_in_generic_residual_contribution_nst
References oomph::ALE_is_disabled, Global_Parameters::body_force(), DIM, G, GlobalPhysicalVariables::Gamma, i, J, j, k, s, TestProblem::source(), w, and oomph::QuadTreeNames::W.
Referenced by oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::fill_in_contribution_to_jacobian(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::fill_in_contribution_to_jacobian_and_mass_matrix(), and oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::fill_in_contribution_to_residuals().
fill_in_pressure_advection_diffusion_jacobian()
template<unsigned DIM> void oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::fill_in_pressure_advection_diffusion_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) inline virtual
Compute the residuals and Jacobian for the associated pressure advection diffusion problem. Used by the Fp preconditioner.
Implements oomph::TemplateFreeSpaceTimeNavierStokesMixedOrderEquationsBase.
     {
       // Do we want to compute the Jacobian? ANSWER: Yes!
       unsigned compute_jacobian_flag = 1;
       // Call the generic routine with the appropriate flag
       fill_in_generic_pressure_advection_diffusion_contribution_nst(
         residuals, jacobian, compute_jacobian_flag);
     } // End of fill_in_pressure_advection_diffusion_jacobian
References oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::fill_in_generic_pressure_advection_diffusion_contribution_nst().
fill_in_pressure_advection_diffusion_residuals()
template<unsigned DIM> void oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::fill_in_pressure_advection_diffusion_residuals (Vector< double > & residuals) inline virtual
Compute the residuals for the associated pressure advection diffusion problem. Used by the Fp preconditioner.
Implements oomph::TemplateFreeSpaceTimeNavierStokesMixedOrderEquationsBase.
     {
       // Do we want to compute the Jacobian? ANSWER: No!
       unsigned compute_jacobian_flag = 0;
       // Call the generic routine with the appropriate flag
       fill_in_generic_pressure_advection_diffusion_contribution_nst(
         residuals, GeneralisedElement::Dummy_matrix, compute_jacobian_flag);
     } // End of fill_in_pressure_advection_diffusion_residuals
References oomph::GeneralisedElement::Dummy_matrix, and oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::fill_in_generic_pressure_advection_diffusion_contribution_nst().
fix_pressure()
template<unsigned DIM> virtual void oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::fix_pressure (const unsigned & p_dof, const double & p_value) pure virtual
Pin p_dof-th pressure dof and set it to value specified by p_value.
Implemented in oomph::QTaylorHoodMixedOrderSpaceTimeElement< DIM >, and oomph::QTaylorHoodMixedOrderSpaceTimeElement< 2 >.
full_output() [1/2]
template<unsigned DIM> void oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::full_output (std::ostream & outfile) inline
Full output function: x,y,[z],u,v,[w],p,du/dt,dv/dt,[dw/dt],dissipation in tecplot format. The default number of plot points is five
     {
       // Set the number of plot points in each direction
       unsigned n_plot = 5;
       // Forward the call to the appropriate output function
       full_output(outfile, n_plot);
     } // End of full_output
full_output() [2/2]
template<unsigned DIM> void oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::full_output (std::ostream & outfile, const unsigned & n_plot)
Full output function: x,y,t,u,v,p,du/dt,dv/dt,dissipation in tecplot format. Use n_plot plot points in each coordinate direction
Full output function: x,y,t,u,v,p,du/dt,dv/dt,dissipation in tecplot format. Specified number of plot points in each coordinate direction
   {
     // Vector of local coordinates
     Vector<double> s(DIM + 1, 0.0);
     // Tecplot header info
     outfile << tecplot_zone_string(n_plot);
     // Find out how many nodes there are
     unsigned n_node = nnode();
     // Set up memory for the shape functions
     Shape psif(n_node);
     // Set up memory for the shape function derivatives
     DShape dpsifdx(n_node, DIM);
     // How many plot points in total?
     unsigned num_plot_points = nplot_points(n_plot);
     // Loop over plot points
     for (unsigned i_plot = 0; i_plot < num_plot_points; i_plot++)
     {
       // Get the local coordinates of plot point
       get_s_plot(i_plot, n_plot, s);
       // DRAIG: Fix
       throw OomphLibError("This needs to be fixed...",
                           OOMPH_CURRENT_FUNCTION,
                           OOMPH_EXCEPTION_LOCATION);
       // Call the derivatives of the shape and test functions
       dshape_eulerian(s, psif, dpsifdx);
       // Allocate storage for the mesh velocity
       Vector<double> mesh_velocity(DIM, 0.0);
       // Allocate storage for the acceleration
       Vector<double> du_dt(DIM, 0.0);
       // Allocate storage for the ALE acceleration
       Vector<double> du_dt_ALE(DIM, 0.0);
       // Allocate storage for the velocity derivatives
       DenseMatrix<double> interpolated_dudx(DIM, DIM, 0.0);
       //--------------------------------------
       // Calculate velocities and derivatives:
       //--------------------------------------
       // Loop over directions
       for (unsigned i = 0; i < DIM; i++)
       {
         // Get the index at which velocity i is stored
         unsigned u_nodal_index = u_index_nst(i);
         // Loop over nodes
         for (unsigned l = 0; l < n_node; l++)
         {
           // Get the nodal value
           double u_value = nodal_value(l, u_nodal_index);
           // Update the i-th acceleration component
           du_dt[i] += u_value * dpsifdx(l, DIM);
           // Update the i-th mesh velocity component
           mesh_velocity[i] += nodal_position(l, i) * dpsifdx(l, DIM);
           // Loop over derivative directions for velocity gradients
           for (unsigned j = 0; j < DIM; j++)
           {
             // Update the value of du_i/dx_j
             interpolated_dudx(i, j) += u_value * dpsifdx(l, j);
           }
         } // for (unsigned l=0;l<n_node;l++)
       } // for (unsigned i=0;i<DIM;i++)
       //---------------------------------------------
       // Get du/dt in ALE form (incl. mesh velocity):
       //---------------------------------------------
       // Loop over the coordinate directions
       for (unsigned i = 0; i < DIM; i++)
       {
         // Store the i-th acceleration component
         du_dt_ALE[i] = du_dt[i];
         // Loop over the coordinate directions
         for (unsigned k = 0; k < DIM; k++)
         {
           // Take the mesh velocity into account
           du_dt_ALE[i] -= mesh_velocity[k] * interpolated_dudx(i, k);
         }
       } // for (unsigned i=0;i<DIM;i++)
       // Output the coordinates
       for (unsigned i = 0; i < DIM + 1; i++)
       {
         // Output the i-th coordinate value
         outfile << interpolated_x(s, i) << " ";
       }
       // Output the velocity components
       for (unsigned i = 0; i < DIM; i++)
       {
         // Output the i-th velocity component
         outfile << interpolated_u_nst(s, i) << " ";
       }
       // Output the pressure
       outfile << interpolated_p_nst(s) << " ";
       // Output the acceleration
       for (unsigned i = 0; i < DIM; i++)
       {
         // Output the ALE acceleration term
         outfile << du_dt_ALE[i] << " ";
       }
       // Dissipation
       outfile << dissipation(s) << " ";
       // End the line
       outfile << std::endl;
     } // for (unsigned i_plot=0;i_plot<num_plot_points;i_plot++)
     // Write tecplot footer (e.g. FE connectivity lists)
     write_tecplot_zone_footer(outfile, n_plot);
   } // End of full_output
References DIM, i, j, k, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and s.
g()
template<unsigned DIM> const Vector<double>& oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::g () const inline
Vector of gravitational components.
     {
       return *G_pt;
     }
References oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::G_pt.
g_pt()
template<unsigned DIM> Vector<double>*& oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::g_pt () inline
Pointer to Vector of gravitational components.
     {
       return G_pt;
     }
References oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::G_pt.
get_body_force_gradient_nst()
template<unsigned DIM> virtual void oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::get_body_force_gradient_nst (const double & time, const unsigned & ipt, const Vector< double > & s, const Vector< double > & x, DenseMatrix< double > & d_body_force_dx) inline protected virtual
Get gradient of body force term at (Eulerian) position x. This function is virtual to allow overloading in multi-physics problems where the strength of the source function might be determined by another system of equations. Computed via function pointer (if set) or by finite differencing (default)
     {
       // Reference value
       Vector<double> body_force(DIM, 0.0);
       // Get the body force vector
       get_body_force_nst(time, ipt, s, x, body_force);
       // Get the finite-difference step size
       double eps_fd = GeneralisedElement::Default_fd_jacobian_step;
       // The body force computed at the perturbed coordinates
       Vector<double> body_force_pls(DIM, 0.0);
       // Copy the (Eulerian) coordinate vector x
       Vector<double> x_pls(x);
       // Loop over the coordinate directions
       for (unsigned i = 0; i < DIM; i++)
       {
         // Update the i-th entry
         x_pls[i] += eps_fd;
         // Get the body force at the current time
         get_body_force_nst(time, ipt, s, x_pls, body_force_pls);
         // Loop over the coordinate directions
         for (unsigned j = 0; j < DIM; j++)
         {
           // Finite-difference the body force derivative
           d_body_force_dx(j, i) = (body_force_pls[j] - body_force[j]) / eps_fd;
         }
         // Reset the i-th entry
         x_pls[i] = x[i];
       }
     } // End of get_body_force_gradient_nst
References Global_Parameters::body_force(), oomph::GeneralisedElement::Default_fd_jacobian_step, DIM, oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::get_body_force_nst(), i, j, s, and plotDoE::x.
get_body_force_nst()
template<unsigned DIM> virtual void oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::get_body_force_nst (const double & time, const unsigned & ipt, const Vector< double > & s, const Vector< double > & x, Vector< double > & result) inline protected virtual
Calculate the body force at a given time and local and/or Eulerian position. This function is virtual so that it can be overloaded in multi-physics elements where the body force might depend on another variable.
     {
       // If a function has not been provided
       if (Body_force_fct_pt == 0)
       {
         // Set the body forces to zero
         result.initialise(0.0);
       }
       // If the function pointer is non-zero
       else
       {
         // Call the function
         (*Body_force_fct_pt)(time, x, result);
       } // if (Body_force_fct_pt!=0)
     } // End of get_body_force_nst
References oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::Body_force_fct_pt, oomph::Vector< _Tp >::initialise(), and plotDoE::x.
Referenced by oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::get_body_force_gradient_nst().
get_dresidual_dnodal_coordinates()
template<unsigned DIM> void oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::get_dresidual_dnodal_coordinates (RankThreeTensor< double > & dresidual_dnodal_coordinates) virtual
Compute derivatives of elemental residual vector with respect to nodal coordinates. Overwrites default implementation in FiniteElement base class. dresidual_dnodal_coordinates(l,i,j)=d res(l) / dX_{ij}
Compute derivatives of elemental residual vector with respect to nodal coordinates. dresidual_dnodal_coordinates(l,i,j)=d res(l) / dX_{ij} Overloads the FD-based version in the FE base class. DRAIG: This needs doing carefully if the ALE nodes aren't fixed!!!
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::RefineableSpaceTimeNavierStokesMixedOrderEquations< DIM >.
   {
     // Throw a warning
     throw OomphLibError("Space-time update needs to be checked!",
                         OOMPH_CURRENT_FUNCTION,
                         OOMPH_EXCEPTION_LOCATION);
   } // End of get_dresidual_dnodal_coordinates
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
get_du_dt()
template<unsigned DIM> double oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::get_du_dt (const unsigned & n, const unsigned & i) const inline
i-th component of du/dt at local node n. Uses suitably interpolated value for hanging nodes. NOTE: This is essentially a wrapper for du_dt_nst() so it can be called externally.
     {
       // Return the value calculated by du_dt_vdp
       return du_dt_nst(n, i);
     } // End of get_du_dt
References oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::du_dt_nst(), i, and n.
get_load()
template<unsigned DIM> void oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::get_load (const Vector< double > & s, const Vector< double > & N, Vector< double > & load) inline virtual
This implements a pure virtual function defined in the FSIFluidElement class. The function computes the traction (on the viscous scale), at the element's local coordinate s, that the fluid element exerts onto an adjacent solid element. The number of arguments is imposed by the interface defined in the FSIFluidElement – only the unit normal N (pointing into the fluid!) is actually used in the computation.
Implements oomph::FSIFluidElement.
     {
       // Note: get_traction() computes the traction onto the fluid
       // if N is the outer unit normal onto the fluid; here we're
       // expecting N to point into the fluid so we're getting the
       // traction onto the adjacent wall instead!
       get_traction(s, N, load);
     }
References oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::get_traction(), load(), N, and s.
get_pressure_and_velocity_mass_matrix_diagonal()
template<unsigned DIM> void oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::get_pressure_and_velocity_mass_matrix_diagonal (Vector< double > & press_mass_diag, Vector< double > & veloc_mass_diag, const unsigned & which_one = 0) virtual
Compute the diagonal of the velocity/pressure mass matrices. If which one=0, both are computed, otherwise only the pressure (which_one=1) or the velocity mass matrix (which_one=2 – the LSC version of the preconditioner only needs that one)
Compute the diagonal of the velocity/pressure mass matrices. If which one=0, both are computed, otherwise only the pressure (which_one=1) or the velocity mass matrix (which_one=2 – the LSC version of the preconditioner only needs that one).
Implements oomph::TemplateFreeSpaceTimeNavierStokesMixedOrderEquationsBase.
Reimplemented in oomph::RefineableSpaceTimeNavierStokesMixedOrderEquations< DIM >.
   {
     // Resize and initialise
     unsigned n_dof = ndof();
     // If space needs to be assigned for the pressure mass matrix
     if ((which_one == 0) || (which_one == 1))
     {
       // Assign the appropriate amount of space
       press_mass_diag.assign(n_dof, 0.0);
     }
     // If space needs to be assigned for the velocity mass matrix
     if ((which_one == 0) || (which_one == 2))
     {
       // Assign the appropriate amount of space
       veloc_mass_diag.assign(n_dof, 0.0);
     }
     // Find out how many nodes there are
     unsigned n_node = nnode();
     // Storage for the local coordinates
     Vector<double> s(DIM + 1, 0.0);
     // Storage for the local velocity indices
     Vector<unsigned> u_nodal_index(DIM, 0.0);
     // Find the indices at which the local velocities are stored
     for (unsigned i = 0; i < DIM; i++)
     {
       // Calculate the i-th local velocity component
       u_nodal_index[i] = this->u_index_nst(i);
     }
     // Set up memory for velocity shape functions
     Shape psi(n_node);
     // Find number of pressure dofs
     unsigned n_pres = npres_nst();
     // Pressure shape function
     Shape psi_p(n_pres);
     // Number of integration points
     unsigned n_intpt = integral_pt()->nweight();
     // Integer to store the local equations no
     int local_eqn = 0;
     // Loop over the integration points
     for (unsigned ipt = 0; ipt < n_intpt; ipt++)
     {
       // Get the integral weight
       double w = integral_pt()->weight(ipt);
       // Get determinant of Jacobian of the mapping
       double J = J_eulerian_at_knot(ipt);
       // Assign values of s
       for (unsigned i = 0; i < DIM + 1; i++)
       {
         // Calculate the i-th local coordinate at the ipt-th integration point
         s[i] = integral_pt()->knot(ipt, i);
       }
       // Premultiply weights and Jacobian
       double W = w * J;
       // Do we want the velocity one?
       if ((which_one == 0) || (which_one == 2))
       {
         // Get the velocity shape functions
         shape_at_knot(ipt, psi);
         // Loop over the velocity shape functions
         for (unsigned l = 0; l < n_node; l++)
         {
           // Loop over the velocity components
           for (unsigned i = 0; i < DIM; i++)
           {
             // Get the local equation number
             local_eqn = nodal_local_eqn(l, u_nodal_index[i]);
             // If not a boundary condition
             if (local_eqn >= 0)
             {
               // Add the contribution
               veloc_mass_diag[local_eqn] += pow(psi[l], 2) * W;
             }
           } // for (unsigned i=0;i<n_dim;i++)
         } // for (unsigned l=0;l<n_node;l++)
       } // if ((which_one==0)||(which_one==2))
       // Do we want the pressure one?
       if ((which_one == 0) || (which_one == 1))
       {
         // Get the pressure shape functions
         pshape_nst(s, psi_p);
         // Loop over the veclocity shape functions
         for (unsigned l = 0; l < n_pres; l++)
         {
           // Get equation number
           local_eqn = p_local_eqn(l);
           // If not a boundary condition
           if (local_eqn >= 0)
           {
             // Add the contribution
             press_mass_diag[local_eqn] += pow(psi_p[l], 2) * W;
           }
         } // for (unsigned l=0;l<n_pres;l++)
       } // if ((which_one==0)||(which_one==1))
     } // for (unsigned ipt=0;ipt<n_intpt;ipt++)
   } // End of get_pressure_and_velocity_mass_matrix_diagonal
References DIM, i, J, Eigen::bfloat16_impl::pow(), s, w, and oomph::QuadTreeNames::W.
get_source_gradient_nst()
template<unsigned DIM> virtual void oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::get_source_gradient_nst (const double & time, const unsigned & ipt, const Vector< double > & x, Vector< double > & gradient) inline protected virtual
Get gradient of source term at (Eulerian) position x. This function is virtual to allow overloading in multi-physics problems where the strength of the source function might be determined by another system of equations. Computed via function pointer (if set) or by finite differencing (default)
     {
       // Reference value
       double source = get_source_nst(time, ipt, x);
       // Get the finite-difference step size
       double eps_fd = GeneralisedElement::Default_fd_jacobian_step;
       // The source function value computed at the perturbed coordinates
       double source_pls = 0.0;
       // Copy the (Eulerian) coordinate vector, x
       Vector<double> x_pls(x);
       // Loop over the coordinate directions
       for (unsigned i = 0; i < DIM; i++)
       {
         // Update the i-th entry
         x_pls[i] += eps_fd;
         // Get the body force at the current time
         source_pls = get_source_nst(time, ipt, x_pls);
         // Loop over the coordinate directions
         for (unsigned j = 0; j < DIM; j++)
         {
           // Finite-difference the source function gradient
           gradient[i] = (source_pls - source) / eps_fd;
         }
         // Reset the i-th entry
         x_pls[i] = x[i];
       }
     } // End of get_source_gradient_nst
References oomph::GeneralisedElement::Default_fd_jacobian_step, DIM, oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::get_source_nst(), i, j, TestProblem::source(), and plotDoE::x.
get_source_nst()
template<unsigned DIM> virtual double oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::get_source_nst (const double & time, const unsigned & ipt, const Vector< double > & x) inline protected virtual
Calculate the source fct at a given time and Eulerian position.
     {
       // If the function pointer is null
       if (Source_fct_pt == 0)
       {
         // Set the source function value to zero
         return 0;
       }
       // Otherwise call the function pointer
       else
       {
         // Return the appropriate value
         return (*Source_fct_pt)(time, x);
       }
     } // End of get_source_nst
References oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::Source_fct_pt, and plotDoE::x.
Referenced by oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::get_source_gradient_nst().
get_traction() [1/2]
template<unsigned DIM> void oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::get_traction (const Vector< double > & s, const Vector< double > & N, Vector< double > & traction)
Compute traction (on the viscous scale) exerted onto the fluid at local coordinate s. N has to be outer unit normal to the fluid.
   {
     // Allocate space for the strain rate matrix
     DenseMatrix<double> strainrate(DIM, DIM);
     // Get velocity gradients
     strain_rate(s, strainrate);
     // Get pressure
     double press = interpolated_p_nst(s);
     // Loop over traction components
     for (unsigned i = 0; i < DIM; i++)
     {
       // Add in the pressure contribution
       traction[i] = -press * N[i];
       // Loop over the strain rate entries
       for (unsigned j = 0; j < DIM; j++)
       {
         // Add in the strain rate contribution
         traction[i] += 2.0 * strainrate(i, j) * N[j];
       }
     } // for (unsigned i=0;i<DIM;i++)
   } // End of get_traction
References DIM, i, j, N, and s.
Referenced by oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::get_load().
get_traction() [2/2]
template<unsigned DIM> void oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::get_traction (const Vector< double > & s, const Vector< double > & N, Vector< double > & traction_p, Vector< double > & traction_visc_n, Vector< double > & traction_visc_t)
Compute traction (on the viscous scale) exerted onto the fluid at local coordinate s, decomposed into pressure and normal and tangential viscous components. N has to be outer unit normal to the fluid.
   {
     // Allocate space for the traction components
     Vector<double> traction_visc(DIM);
     // Allocate space for the velocity gradients
     DenseMatrix<double> strainrate(DIM, DIM);
     // Calculate the strain rate at the local coordinate s
     strain_rate(s, strainrate);
     // Get pressure
     double press = interpolated_p_nst(s);
     // Loop over traction components
     for (unsigned i = 0; i < DIM; i++)
     {
       // Get the pressure contribution
       traction_p[i] = -press * N[i];
       // Loop over the coordinate directions
       for (unsigned j = 0; j < DIM; j++)
       {
         // Add in the viscous stress contribution
         traction_visc[i] += 2.0 * strainrate(i, j) * N[j];
       }
       // Get the normal component of the viscous stress
       traction_visc_n[i] = traction_visc[i] * N[i];
       // Get the tangential component of the viscous stress
       traction_visc_t[i] = traction_visc[i] - traction_visc_n[i];
     } // for (unsigned i=0;i<DIM;i++)
   } // End of get_traction
References DIM, i, j, N, and s.
get_vorticity() [1/4]
void oomph::SpaceTimeNavierStokesMixedOrderEquations< 2 >::get_vorticity (const Vector< double > & s, double & vorticity) const
Compute 2D vorticity vector at local coordinate s (return in one and only component of vorticity vector as a double
   {
     // Create a vector to store the vorticity
     Vector<double> vort(1, 0.0);
     // Calculate the vorticity
     get_vorticity(s, vort);
     // Assign the vorticity
     vorticity = vort[0];
   } // End of get_vorticity
References s.
get_vorticity() [2/4]
template<unsigned DIM> void oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::get_vorticity (const Vector< double > & s, double & vorticity) const
Compute the vorticity vector at local coordinate s.
get_vorticity() [3/4]
void oomph::SpaceTimeNavierStokesMixedOrderEquations< 2 >::get_vorticity (const Vector< double > & s, Vector< double > & vorticity) const
Compute 2D vorticity vector at local coordinate s (return in one and only component of vorticity vector
   {
 #ifdef PARANOID
     if (vorticity.size() != 1)
     {
       // Create an output stream
       std::ostringstream error_message;
       // Create an error message
       error_message << "Computation of vorticity in 2D requires a 1D vector\n"
                     << "which contains the only non-zero component of the\n"
                     << "vorticity vector. You've passed a vector of size "
                     << vorticity.size() << std::endl;
       // Throw an error
       throw OomphLibError(
         error_message.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
 #endif
     // Specify spatial dimension
     unsigned dim = 2;
     // Velocity gradient matrix
     DenseMatrix<double> dudx(dim, dim, 0.0);
     // Find out how many nodes there are in the element
     unsigned n_node = nnode();
     // Set up memory for the shape and test functions
     Shape psi(n_node);
     // Set up memory for the shape and test function derivatives
     DShape dpsidx(n_node, dim + 1);
     // Evaluate the shape functions and shape function derivatives at this point
     dshape_eulerian(s, psi, dpsidx);
     // Initialise to zero
     dudx.initialise(0.0);
     // Loop over velocity components
     for (unsigned i = 0; i < dim; i++)
     {
       // Get the index at which the i-th velocity is stored
       unsigned u_nodal_index = u_index_nst(i);
       // Loop over derivative directions
       for (unsigned j = 0; j < dim; j++)
       {
         // Loop over nodes
         for (unsigned l = 0; l < n_node; l++)
         {
           // Update the value of du_i/dx_j
           dudx(i, j) += nodal_value(l, u_nodal_index) * dpsidx(l, j);
         }
       } // for (unsigned j=0;j<DIM;j++)
     } // for (unsigned i=0;i<DIM;i++)
     // Z-component of vorticity
     vorticity[0] = dudx(1, 0) - dudx(0, 1);
   } // End of get_vorticity
References i, oomph::DenseMatrix< T >::initialise(), j, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and s.
get_vorticity() [4/4]
template<unsigned DIM> void oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::get_vorticity (const Vector< double > & s, Vector< double > & vorticity) const
Compute the vorticity vector at local coordinate s.
interpolated_du_dt_nst()
template<unsigned DIM> double oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::interpolated_du_dt_nst (const Vector< double > & s, const unsigned & i) const inline
Return FE representation of function value du_i/dt(s) at local coordinate s
     {
       // Find number of nodes
       unsigned n_node = nnode();
       // Local shape function
       Shape psi(n_node);
       // Allocate space for the derivatives of the shape functions
       DShape dpsidx(n_node, DIM + 1);
       //------------dshape_eulerian(s,psi,dpsidx)----------------------------
       // Find the element dimension
       const unsigned el_dim = this->dim();
       // Get the values of the shape functions and their local derivatives;
       // temporarily stored in dpsi
       dshape_local_u_nst(s, psi, dpsidx);
       // Allocate memory for the inverse jacobian
       DenseMatrix<double> inverse_jacobian(el_dim);
       // Now calculate the inverse jacobian
       local_to_eulerian_mapping(dpsidx, inverse_jacobian);
       // Now set the values of the derivatives to be dpsidx
       transform_derivatives(inverse_jacobian, dpsidx);
       //------------dshape_eulerian(s,psi,dpsidx)----------------------------
       // Initialise value of du_i/dt
       double interpolated_dudt = 0.0;
       // Find the index at which the variable is stored
       unsigned u_nodal_index = u_index_nst(i);
       // Loop over the local nodes and sum
       for (unsigned l = 0; l < n_node; l++)
       {
         // Update the interpolated du_i/dt value
         interpolated_dudt += nodal_value(l, u_nodal_index) * dpsidx(l, DIM);
       }
       // Return the interpolated du_i/dt value
       return interpolated_dudt;
     } // End of interpolated_du_dt_nst
References oomph::FiniteElement::dim(), DIM, oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::dshape_local_u_nst(), el_dim, i, oomph::FiniteElement::local_to_eulerian_mapping(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), oomph::FiniteElement::transform_derivatives(), and oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::u_index_nst().
Referenced by oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::du_dt_nst().
interpolated_p_nst() [1/2]
template<unsigned DIM> double oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::interpolated_p_nst (const unsigned & t, const Vector< double > & s) const inline
Return FE interpolated pressure at local coordinate s at time level t.
     {
       // Find number of nodes
       unsigned n_pres = npres_nst();
       // Local shape function
       Shape psi(n_pres);
       // Find values of shape function
       pshape_nst(s, psi);
       // Initialise value of p
       double interpolated_p = 0.0;
       // Loop over the local nodes and sum
       for (unsigned l = 0; l < n_pres; l++)
       {
         interpolated_p += p_nst(t, l) * psi[l];
       }
       return (interpolated_p);
     }
References oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::npres_nst(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::p_nst(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::pshape_nst(), s, and plotPSD::t.
interpolated_p_nst() [2/2]
template<unsigned DIM> virtual double oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::interpolated_p_nst (const Vector< double > & s) const inline virtual
Return FE interpolated pressure at local coordinate s.
     {
       // Find number of nodes
       unsigned n_pres = npres_nst();
       // Local shape function
       Shape psi(n_pres);
       // Find values of shape function
       pshape_nst(s, psi);
       // Initialise value of p
       double interpolated_p = 0.0;
       // Loop over the local nodes and sum
       for (unsigned l = 0; l < n_pres; l++)
       {
         interpolated_p += p_nst(l) * psi[l];
       }
       return (interpolated_p);
     }
References oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::npres_nst(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::p_nst(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::pshape_nst(), and s.
Referenced by oomph::RefineableQTaylorHoodMixedOrderSpaceTimeElement< DIM >::get_interpolated_values(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::point_output_data(), and oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::scalar_value_paraview().
interpolated_u_nst() [1/3]
template<unsigned DIM> double oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::interpolated_u_nst (const unsigned & t, const Vector< double > & s, const unsigned & i) const inline
Return FE interpolated velocity u[i] at local coordinate s time level, t. Purposely broken for space-time elements.
     {
       // Create an output stream
       std::ostringstream error_message_stream;
       // Create an error message
       error_message_stream << "This interface doesn't make sense in "
                            << "space-time elements!" << std::endl;
       // Throw an error
       throw OomphLibError(error_message_stream.str(),
                           OOMPH_CURRENT_FUNCTION,
                           OOMPH_EXCEPTION_LOCATION);
     } // End of interpolated_u_nst
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
interpolated_u_nst() [2/3]
template<unsigned DIM> double oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::interpolated_u_nst (const Vector< double > & s, const unsigned & i) const inline
Return FE interpolated velocity u[i] at local coordinate s.
     {
       // Find the number of nodes
       unsigned n_node = nnode();
       // Local shape function
       Shape psi(n_node);
       // Find values of shape function
       shape_u_nst(s, psi);
       // Get nodal index at which i-th velocity is stored
       unsigned u_nodal_index = u_index_nst(i);
       // Initialise value of u
       double interpolated_u = 0.0;
       // Loop over the local nodes and sum
       for (unsigned l = 0; l < n_node; l++)
       {
         // Update the i-th velocity component approximation
         interpolated_u += nodal_value(l, u_nodal_index) * psi[l];
       }
       // Return the calculated approximation to the i-th velocity component
       return interpolated_u;
     } // End of interpolated_u_nst
References i, oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), s, oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::shape_u_nst(), and oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::u_index_nst().
interpolated_u_nst() [3/3]
template<unsigned DIM> void oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::interpolated_u_nst (const Vector< double > & s, Vector< double > & velocity) const inline
Compute vector of FE interpolated velocity u at local coordinate s.
     {
       // Find the number of nodes
       unsigned n_node = nnode();
       // Local shape function
       Shape psi(n_node);
       // Find values of shape function
       shape_u_nst(s, psi);
       // Loop over the velocity components
       for (unsigned i = 0; i < DIM; i++)
       {
         // Index at which the nodal value is stored
         unsigned u_nodal_index = u_index_nst(i);
         // Initialise the i-th value of the velocity vector
         velocity[i] = 0.0;
         // Loop over the local nodes and sum
         for (unsigned l = 0; l < n_node; l++)
         {
           // Update the i-th velocity component approximation
           velocity[i] += nodal_value(l, u_nodal_index) * psi[l];
         }
       } // for (unsigned i=0;i<DIM;i++)
     } // End of interpolated_u_nst
References DIM, i, oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), s, oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::shape_u_nst(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::u_index_nst(), and Jeffery_Solution::velocity().
Referenced by oomph::RefineableQTaylorHoodMixedOrderSpaceTimeElement< DIM >::get_interpolated_values(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::point_output_data(), and oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::scalar_value_paraview().
is_reynolds_strouhal_stored_as_external_data()
template<unsigned DIM> bool oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::is_reynolds_strouhal_stored_as_external_data () const inline
Are we storing the Strouhal number as external data?
     {
       // Return the flags value
       return ReynoldsStrouhal_is_stored_as_external_data;
     } // End of is_reynolds_strouhal_stored_as_external_data
References oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::ReynoldsStrouhal_is_stored_as_external_data.
kin_energy()
template<unsigned DIM> double oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::kin_energy
Get integral of kinetic energy over element.
Get integral of kinetic energy over element: Note that this is the "raw" kinetic energy in the sense that the density ratio has not been included. In problems with two or more fluids the user will have to remember to premultiply certain elements by the appropriate density ratio.
   {
     // Initialise the elemental kinetic energy value
     double kin_en = 0.0;
     // Set the value of n_intpt
     unsigned n_intpt = integral_pt()->nweight();
     // Set the Vector to hold local coordinates
     Vector<double> s(DIM + 1, 0.0);
     // Loop over the integration points
     for (unsigned ipt = 0; ipt < n_intpt; ipt++)
     {
       // Assign values of s
       for (unsigned i = 0; i < DIM + 1; i++)
       {
         s[i] = integral_pt()->knot(ipt, i);
       }
       // Get the integral weight
       double w = integral_pt()->weight(ipt);
       // Get Jacobian of mapping
       double J = J_eulerian(s);
       // Loop over directions
       double veloc_squared = 0.0;
       for (unsigned i = 0; i < DIM; i++)
       {
         veloc_squared += interpolated_u_nst(s, i) * interpolated_u_nst(s, i);
       }
       kin_en += 0.5 * veloc_squared * w * J;
     }
     return kin_en;
   } // End of kin_energy
References DIM, i, J, s, and w.
n_u_nst()
template<unsigned DIM> unsigned oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::n_u_nst () const inline
Return the number of velocity components (used in FluidInterfaceElements)
     {
       // Return the number of equations to solve
       return DIM;
     } // End of n_u_nst
References DIM.
npres_nst()
template<unsigned DIM> virtual unsigned oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::npres_nst () const pure virtual
Function to return number of pressure degrees of freedom.
Implemented in oomph::QTaylorHoodMixedOrderSpaceTimeElement< DIM >, and oomph::QTaylorHoodMixedOrderSpaceTimeElement< 2 >.
Referenced by oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::interpolated_p_nst().
nscalar_paraview()
template<unsigned DIM> unsigned oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::nscalar_paraview () const inline virtual
Number of scalars/fields output by this element. Reimplements broken virtual function in base class.
Reimplemented from oomph::FiniteElement.
     {
       // The number of velocity components plus the pressure field
       return DIM + 1;
     }
References DIM.
output() [1/4]
template<unsigned DIM> void oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::output (FILE * file_pt) inline virtual
C-style output function: x,y,[z],u,v,[w],p in tecplot format. The default number of plot points is five
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QTaylorHoodMixedOrderSpaceTimeElement< DIM >, and oomph::QTaylorHoodMixedOrderSpaceTimeElement< 2 >.
     {
       // Set the number of plot points in each direction
       unsigned n_plot = 5;
       // Forward the call to the appropriate output function
       output(file_pt, n_plot);
     } // End of output
References oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::output().
output() [2/4]
template<unsigned DIM> void oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::output (FILE * file_pt, const unsigned & n_plot) virtual
C-style output function: x,y,[z],u,v,[w],p in tecplot format. Use n_plot points in each coordinate direction
C-style output function: x,y,[z],u,v,[w],p in tecplot format. Specified number of plot points in each coordinate direction.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QTaylorHoodMixedOrderSpaceTimeElement< DIM >, and oomph::QTaylorHoodMixedOrderSpaceTimeElement< 2 >.
   {
     // Vector of local coordinates
     Vector<double> s(DIM + 1, 0.0);
     // Tecplot header info
     fprintf(file_pt, "%s", tecplot_zone_string(n_plot).c_str());
     // How many plot points in total?
     unsigned num_plot_points = nplot_points(n_plot);
     // Loop over plot points
     for (unsigned i_plot = 0; i_plot < num_plot_points; i_plot++)
     {
       // Get the local coordinates associated with this plot point
       get_s_plot(i_plot, n_plot, s);
       // Loop over the coordinate directions
       for (unsigned i = 0; i < DIM + 1; i++)
       {
         // Output the i-th coordinate value to file
         fprintf(file_pt, "%g ", interpolated_x(s, i));
       }
       // Loop over the velocity components
       for (unsigned i = 0; i < DIM; i++)
       {
         // Output the i-th velocity component to file
         fprintf(file_pt, "%g ", interpolated_u_nst(s, i));
       }
       // Pressure
       fprintf(file_pt, "%g \n", interpolated_p_nst(s));
     }
     // Finish the line off
     fprintf(file_pt, "\n");
     // Write tecplot footer (e.g. FE connectivity lists)
     write_tecplot_zone_footer(file_pt, n_plot);
   } // End of output
References DIM, i, and s.
output() [3/4]
template<unsigned DIM> void oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::output (std::ostream & outfile) inline virtual
Output function: x,y,t,u,v,p in tecplot format. The default number of plot points is five
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QTaylorHoodMixedOrderSpaceTimeElement< DIM >, and oomph::QTaylorHoodMixedOrderSpaceTimeElement< 2 >.
     {
       // Set the number of plot points in each direction
       unsigned n_plot = 5;
       // Forward the call to the appropriate output function
       output(outfile, n_plot);
     } // End of output
Referenced by oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::output(), and oomph::QTaylorHoodMixedOrderSpaceTimeElement< DIM >::output().
output() [4/4]
template<unsigned DIM> void oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::output (std::ostream & outfile, const unsigned & n_plot) virtual
Output function: x,y,[z],u,v,[w],p in tecplot format. Here, we use n_plot plot points in each coordinate direction
Output function: x,y,[z],u,v,[w],p in tecplot format. Specified number of plot points in each coordinate direction.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QTaylorHoodMixedOrderSpaceTimeElement< DIM >, and oomph::QTaylorHoodMixedOrderSpaceTimeElement< 2 >.
   {
     // Find number of nodes
     unsigned n_node = nnode();
     // Local shape function
     Shape psi(n_node);
     // Vectors of local coordinates
     Vector<double> s(DIM + 1, 0.0);
     // Tecplot header info
     outfile << tecplot_zone_string(n_plot);
     // How many plot points are there?
     unsigned num_plot_points = nplot_points(n_plot);
     // Loop over plot points
     for (unsigned i_plot = 0; i_plot < num_plot_points; i_plot++)
     {
       // Get the local coordinates of plot point
       get_s_plot(i_plot, n_plot, s);
       // Coordinates
       for (unsigned i = 0; i < DIM + 1; i++)
       {
         // Output the i-th spatial coordinate value
         outfile << interpolated_x(s, i) << " ";
       }
       // Velocities
       for (unsigned i = 0; i < DIM; i++)
       {
         // Output the i-th velocity component
         outfile << interpolated_u_nst(s, i) << " ";
       }
       // Pressure
       outfile << interpolated_p_nst(s) << " ";
       // End the line
       outfile << std::endl;
     } // for (unsigned i_plot=0;i_plot<num_plot_points;i_plot++)
     // Add an extra line
     outfile << std::endl;
     // Write tecplot footer (e.g. FE connectivity lists)
     write_tecplot_zone_footer(outfile, n_plot);
   } // End of output
References DIM, i, and s.
output_fct() [1/2]
template<unsigned DIM> void oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::output_fct (std::ostream & outfile, const unsigned & n_plot, const double & time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) virtual
Output exact solution specified via function pointer at a given time and at a given number of plot points. Function prints as many components as are returned in solution Vector.
Output "exact" solution at a given time Solution is provided via function pointer. Plot at a given number of plot points. Function prints as many components as are returned in solution Vector.
Reimplemented from oomph::FiniteElement.
   {
     // Storage for the time value
     double interpolated_t = 0.0;
     // Vector of local coordinates
     Vector<double> s(DIM + 1, 0.0);
     // Vector for coordinates
     Vector<double> x(DIM, 0.0);
     // Tecplot header info
     outfile << tecplot_zone_string(n_plot);
     // Exact solution Vector
     Vector<double> exact_soln;
     // How many plot points are there in total?
     unsigned num_plot_points = nplot_points(n_plot);
     // Loop over plot points
     for (unsigned i_plot = 0; i_plot < num_plot_points; i_plot++)
     {
       // Get local coordinates of plot point
       get_s_plot(i_plot, n_plot, s);
       // Loop over the spatial coordinates
       for (unsigned i = 0; i < DIM; i++)
       {
         // Assign the i-th spatial coordinate
         x[i] = interpolated_x(s, i);
       }
       // Get the time value
       interpolated_t = interpolated_x(s, DIM);
       // Get exact solution at this point
       (*exact_soln_pt)(interpolated_t, x, exact_soln);
       // Output x,y,...
       for (unsigned i = 0; i < DIM; i++)
       {
         // Output the i-th spatial coordinate value
         outfile << x[i] << " ";
       }
       // Output the time value at this point
       outfile << interpolated_t << " ";
       // Output "exact solution"
       for (unsigned i = 0; i < exact_soln.size(); i++)
       {
         // Output the i-th (exact) velocity component value
         outfile << exact_soln[i] << " ";
       }
       // End the line
       outfile << std::endl;
     } // for (unsigned i_plot=0;i_plot<num_plot_points;i_plot++)
     // Write tecplot footer (e.g. FE connectivity lists)
     write_tecplot_zone_footer(outfile, n_plot);
   } // End of output_fct
References DIM, ProblemParameters::exact_soln(), i, s, and plotDoE::x.
output_fct() [2/2]
template<unsigned DIM> void oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::output_fct (std::ostream & outfile, const unsigned & n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) virtual
Output exact solution specified via function pointer at a given number of plot points. Function prints as many components as are returned in solution Vector
Output "exact" solution Solution is provided via function pointer. Plot at a given number of plot points. Function prints as many components as are returned in solution Vector.
Reimplemented from oomph::FiniteElement.
   {
     // Storage for the time value
     double interpolated_t = 0.0;
     // Vector of local coordinates
     Vector<double> s(DIM + 1, 0.0);
     // Vector for coordinates
     Vector<double> x(DIM, 0.0);
     // Tecplot header info
     outfile << tecplot_zone_string(n_plot);
     // Exact solution Vector
     Vector<double> exact_soln;
     // How many plot points are there in total?
     unsigned num_plot_points = nplot_points(n_plot);
     // Loop over plot points
     for (unsigned i_plot = 0; i_plot < num_plot_points; i_plot++)
     {
       // Get local coordinates of plot point
       get_s_plot(i_plot, n_plot, s);
       // Loop over the spatial coordinates
       for (unsigned i = 0; i < DIM; i++)
       {
         // Assign the i-th spatial coordinate
         x[i] = interpolated_x(s, i);
       }
       // Get the time value
       interpolated_t = interpolated_x(s, DIM);
       // Get exact solution at this point
       (*exact_soln_pt)(x, exact_soln);
       // Output x,y,...
       for (unsigned i = 0; i < DIM; i++)
       {
         // Output the i-th spatial coordinate
         outfile << x[i] << " ";
       }
       // Output the time value at this point
       outfile << interpolated_t << " ";
       // Output "exact solution"
       for (unsigned i = 0; i < exact_soln.size(); i++)
       {
         // Output the i-th (exact) velocity component value
         outfile << exact_soln[i] << " ";
       }
       // End the line
       outfile << std::endl;
     } // for (unsigned i_plot=0;i_plot<num_plot_points;i_plot++)
     // Write tecplot footer (e.g. FE connectivity lists)
     write_tecplot_zone_footer(outfile, n_plot);
   } // End of output_fct
References DIM, ProblemParameters::exact_soln(), i, s, and plotDoE::x.
output_pressure_advection_diffusion_robin_elements()
template<unsigned DIM> void oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::output_pressure_advection_diffusion_robin_elements (std::ostream & outfile) inline
Output the FaceElements that apply the Robin boundary condition to the pressure advection diffusion problem required by Fp preconditioner
     {
       unsigned nel = Pressure_advection_diffusion_robin_element_pt.size();
       for (unsigned e = 0; e < nel; e++)
       {
         FaceElement* face_el_pt =
           Pressure_advection_diffusion_robin_element_pt[e];
         outfile << "ZONE" << std::endl;
         Vector<double> unit_normal(DIM);
         Vector<double> x(DIM + 1);
         Vector<double> s(DIM);
         unsigned n = face_el_pt->integral_pt()->nweight();
         for (unsigned ipt = 0; ipt < n; ipt++)
         {
           for (unsigned i = 0; i < DIM; i++)
           {
             s[i] = face_el_pt->integral_pt()->knot(ipt, i);
           }
           face_el_pt->interpolated_x(s, x);
           face_el_pt->outer_unit_normal(ipt, unit_normal);
           for (unsigned i = 0; i < DIM + 1; i++)
           {
             outfile << x[i] << " ";
           }
           for (unsigned i = 0; i < DIM; i++)
           {
             outfile << unit_normal[i] << " ";
           }
           outfile << std::endl;
         }
       }
     } // End of output_pressure_advection_diffusion_robin_elements
References DIM, e(), i, oomph::FiniteElement::integral_pt(), oomph::FaceElement::interpolated_x(), oomph::Integral::knot(), n, oomph::Integral::nweight(), oomph::FaceElement::outer_unit_normal(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::Pressure_advection_diffusion_robin_element_pt, s, and plotDoE::x.
output_veloc()
template<unsigned DIM> void oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::output_veloc (std::ostream & outfile, const unsigned & n_plot, const unsigned & t)
Output function: x,y,t,u,v in tecplot format. Use n_plot points in each coordinate direction at timestep t (t=0: present; t>0: previous timestep)
Output function: Velocities only x,y,[z],u,v,[w] in tecplot format at specified previous timestep (t=0: present; t>0: previous timestep). Specified number of plot points in each coordinate direction. DRAIG: Should be broken!
   {
     // Find number of nodes
     unsigned n_node = nnode();
     // Local shape function
     Shape psi(n_node);
     // Vectors of local coordinates
     Vector<double> s(DIM + 1, 0.0);
     // Tecplot header info
     outfile << tecplot_zone_string(n_plot);
     // How many plot points are there?
     unsigned num_plot_points = nplot_points(n_plot);
     // Loop over plot points
     for (unsigned i_plot = 0; i_plot < num_plot_points; i_plot++)
     {
       // Get the local coordinates of plot point
       get_s_plot(i_plot, n_plot, s);
       // Coordinates
       for (unsigned i = 0; i < DIM + 1; i++)
       {
         // Output the i-th spatial coordinate value
         outfile << interpolated_x(s, i) << " ";
       }
       // Velocities
       for (unsigned i = 0; i < DIM; i++)
       {
         // Output the i-th velocity component
         outfile << interpolated_u_nst(s, i) << " ";
       }
       // End the line
       outfile << std::endl;
     } // for (unsigned i_plot=0;i_plot<num_plot_points;i_plot++)
     // Write tecplot footer (e.g. FE connectivity lists)
     write_tecplot_zone_footer(outfile, n_plot);
   } // End of output_veloc
References DIM, i, and s.
output_vorticity()
template<unsigned DIM> void oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::output_vorticity (std::ostream & outfile, const unsigned & n_plot)
Output function: x,y,t,omega in tecplot format. nplot points in each coordinate direction
Output function for vorticity. x,y,[z],[omega_x,omega_y,[and/or omega_z]] in tecplot format. Specified number of plot points in each coordinate direction.
   {
     // Vector of local coordinates
     Vector<double> s(DIM + 1, 0.0);
     // Create vorticity vector of the required size
     Vector<double> vorticity;
     // If we're in 2D the vorticity field is a scalar field
     if (DIM == 2)
     {
       // Resize the vorticity vector
       vorticity.resize(1);
     }
     // If we're in 3D the vorticity field is a vector field
     else if (DIM == 3)
     {
       // Resize the vorticity vector
       vorticity.resize(3);
     }
     // If we're in 1D
     else
     {
       std::string error_message =
         "Can't output vorticity in 1D - in fact, what ";
       error_message += "do you mean\nby the 1D Navier-Stokes equations?\n";
       throw OomphLibError(
         error_message, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
     // Tecplot header info
     outfile << tecplot_zone_string(n_plot);
     // How many plot points are there in total?
     unsigned num_plot_points = nplot_points(n_plot);
     // Loop over plot points
     for (unsigned i_plot = 0; i_plot < num_plot_points; i_plot++)
     {
       // Get local coordinates of plot point
       get_s_plot(i_plot, n_plot, s);
       // Coordinates
       for (unsigned i = 0; i < DIM + 1; i++)
       {
         // Output the i-th coordinate value
         outfile << interpolated_x(s, i) << " ";
       }
       // Get vorticity
       get_vorticity(s, vorticity);
       // If we're in 2D
       if (DIM == 2)
       {
         // Output the vorticity field value
         outfile << vorticity[0];
       }
       // If we're in 3D
       else
       {
         // Output the vorticity field
         outfile << vorticity[0] << " " << vorticity[1] << " " << vorticity[2]
                 << " ";
       }
       // Finish the line off
       outfile << std::endl;
     }
     // Add in an extra line
     outfile << std::endl;
     // Write tecplot footer (e.g. FE connectivity lists)
     write_tecplot_zone_footer(outfile, n_plot);
   } // End of output_vorticity
References DIM, i, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, s, and oomph::Global_string_for_annotation::string().
p_nodal_index_nst()
template<unsigned DIM> virtual int oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::p_nodal_index_nst () const inline virtual
Return the index at which the pressure is stored if it is stored at the nodes. If not stored at the nodes this will return a negative number.
Implements oomph::TemplateFreeSpaceTimeNavierStokesMixedOrderEquationsBase.
Reimplemented in oomph::QTaylorHoodMixedOrderSpaceTimeElement< DIM >, and oomph::QTaylorHoodMixedOrderSpaceTimeElement< 2 >.
     {
       return Pressure_not_stored_at_node;
     }
References oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::Pressure_not_stored_at_node.
Referenced by oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::pin_all_non_pressure_dofs().
p_nst() [1/2]
template<unsigned DIM> virtual double oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::p_nst (const unsigned & n_p) const pure virtual
Pressure at local pressure "node" n_p Uses suitably interpolated value for hanging nodes.
Implemented in oomph::QTaylorHoodMixedOrderSpaceTimeElement< DIM >, and oomph::QTaylorHoodMixedOrderSpaceTimeElement< 2 >.
Referenced by oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::interpolated_p_nst().
p_nst() [2/2]
template<unsigned DIM> virtual double oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::p_nst (const unsigned & t, const unsigned & n_p) const pure virtual
Pressure at local pressure "node" n_p at time level t.
Implemented in oomph::QTaylorHoodMixedOrderSpaceTimeElement< DIM >, and oomph::QTaylorHoodMixedOrderSpaceTimeElement< 2 >.
pin_all_non_pressure_dofs()
template<unsigned DIM> void oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::pin_all_non_pressure_dofs (std::map< Data *, std::vector< int >> & eqn_number_backup) inline virtual
Pin all non-pressure dofs and backup eqn numbers.
Implements oomph::TemplateFreeSpaceTimeNavierStokesMixedOrderEquationsBase.
     {
       // Loop over internal data and pin the values (having established that
       // pressure dofs aren't amongst those)
       unsigned nint = this->ninternal_data();
       for (unsigned j = 0; j < nint; j++)
       {
         Data* data_pt = this->internal_data_pt(j);
         if (eqn_number_backup[data_pt].size() == 0)
         {
           unsigned nvalue = data_pt->nvalue();
           eqn_number_backup[data_pt].resize(nvalue);
           for (unsigned i = 0; i < nvalue; i++)
           {
             // Backup
             eqn_number_backup[data_pt][i] = data_pt->eqn_number(i);
             // Pin everything
             data_pt->pin(i);
           }
         }
       }
       // Now deal with nodal values
       unsigned nnod = this->nnode();
       for (unsigned j = 0; j < nnod; j++)
       {
         Node* nod_pt = this->node_pt(j);
         if (eqn_number_backup[nod_pt].size() == 0)
         {
           unsigned nvalue = nod_pt->nvalue();
           eqn_number_backup[nod_pt].resize(nvalue);
           for (unsigned i = 0; i < nvalue; i++)
           {
             // Pin everything apart from the nodal pressure
             // value
             if (int(i) != this->p_nodal_index_nst())
             {
               // Backup
               eqn_number_backup[nod_pt][i] = nod_pt->eqn_number(i);
               // Pin
               nod_pt->pin(i);
             }
             // Else it's a pressure value
             else
             {
               // Exclude non-nodal pressure based elements
               if (this->p_nodal_index_nst() >= 0)
               {
                 // Backup
                 eqn_number_backup[nod_pt][i] = nod_pt->eqn_number(i);
               }
             }
           }
           // If it's a solid node deal with its positional data too
           SolidNode* solid_nod_pt = dynamic_cast<SolidNode*>(nod_pt);
           if (solid_nod_pt != 0)
           {
             Data* solid_posn_data_pt = solid_nod_pt->variable_position_pt();
             if (eqn_number_backup[solid_posn_data_pt].size() == 0)
             {
               unsigned nvalue = solid_posn_data_pt->nvalue();
               eqn_number_backup[solid_posn_data_pt].resize(nvalue);
               for (unsigned i = 0; i < nvalue; i++)
               {
                 // Backup
                 eqn_number_backup[solid_posn_data_pt][i] =
                   solid_posn_data_pt->eqn_number(i);
                 // Pin
                 solid_posn_data_pt->pin(i);
               }
             }
           }
         }
       }
     } // End of pin_all_non_pressure_dofs
References oomph::Data::eqn_number(), i, oomph::GeneralisedElement::internal_data_pt(), j, oomph::GeneralisedElement::ninternal_data(), oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::Data::nvalue(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::p_nodal_index_nst(), oomph::Data::pin(), oomph::FiniteElement::size(), and oomph::SolidNode::variable_position_pt().
pinned_fp_pressure_eqn()
template<unsigned DIM> int& oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::pinned_fp_pressure_eqn () inline virtual
Global eqn number of pressure dof that's pinned in pressure adv diff problem
Implements oomph::TemplateFreeSpaceTimeNavierStokesMixedOrderEquationsBase.
     {
       // Return the appropriate equation number
       return Pinned_fp_pressure_eqn;
     }
References oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::Pinned_fp_pressure_eqn.
point_output_data()
template<unsigned DIM> void oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::point_output_data (const Vector< double > & s, Vector< double > & data) inline virtual
Output solution in data vector at local cordinates s: x,y,z,u,v,p
Reimplemented from oomph::FiniteElement.
     {
       // Resize data for values
       data.resize(2 * DIM + 2);
       // Write values in the vector
       for (unsigned i = 0; i < DIM + 1; i++)
       {
         // Output the i-th (Eulerian) coordinate at these local coordinates
         data[i] = interpolated_x(s, i);
       }
       // Write values in the vector
       for (unsigned i = 0; i < DIM; i++)
       {
         // Output the i-th velocity component at these local coordinates
         data[i + (DIM + 1)] = this->interpolated_u_nst(s, i);
       }
       // Output the pressure field value at these local coordinates
       data[2 * DIM + 1] = this->interpolated_p_nst(s);
     } // End of point_output_data
References data, DIM, i, oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::interpolated_p_nst(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::interpolated_u_nst(), oomph::FiniteElement::interpolated_x(), and s.
pressure_integral()
template<unsigned DIM> double oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::pressure_integral
Integral of pressure over element.
Return pressure integrated over the element.
   {
     // Initialise
     double press_int = 0;
     // Set the value of n_intpt
     unsigned n_intpt = integral_pt()->nweight();
     // Set the Vector to hold local coordinates
     Vector<double> s(DIM + 1, 0.0);
     // Loop over the integration points
     for (unsigned ipt = 0; ipt < n_intpt; ipt++)
     {
       // Assign values of s
       for (unsigned i = 0; i < DIM + 1; i++)
       {
         s[i] = integral_pt()->knot(ipt, i);
       }
       // Get the integral weight
       double w = integral_pt()->weight(ipt);
       // Get Jacobian of mapping
       double J = J_eulerian(s);
       // Premultiply the weights and the Jacobian
       double W = w * J;
       // Get pressure
       double press = interpolated_p_nst(s);
       // Add
       press_int += press * W;
     }
     return press_int;
   }
References DIM, i, J, s, w, and oomph::QuadTreeNames::W.
pshape_nst() [1/2]
template<unsigned DIM> virtual void oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::pshape_nst (const Vector< double > & s, Shape & psi) const pure virtual
Compute the pressure shape functions at local coordinate s.
Implemented in oomph::QTaylorHoodMixedOrderSpaceTimeElement< DIM >, oomph::QTaylorHoodMixedOrderSpaceTimeElement< 2 >, oomph::QTaylorHoodMixedOrderSpaceTimeElement< DIM >, and oomph::QTaylorHoodMixedOrderSpaceTimeElement< 2 >.
Referenced by oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::interpolated_p_nst().
pshape_nst() [2/2]
template<unsigned DIM> virtual void oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::pshape_nst (const Vector< double > & s, Shape & psi, Shape & test) const pure virtual
Compute the pressure shape and test functions at local coordinate s
Implemented in oomph::QTaylorHoodMixedOrderSpaceTimeElement< DIM >, and oomph::QTaylorHoodMixedOrderSpaceTimeElement< 2 >.
re()
template<unsigned DIM> const double& oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::re () const inline
Reynolds number.
     {
       // Use the Reynolds number pointer to get the Reynolds value
       return *Re_pt;
     } // End of re
References oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::Re_pt.
re_invfr()
template<unsigned DIM> const double& oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::re_invfr () const inline
Global inverse Froude number.
     {
       return *ReInvFr_pt;
     }
References oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::ReInvFr_pt.
re_invfr_pt()
template<unsigned DIM> double*& oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::re_invfr_pt () inline
Pointer to global inverse Froude number.
     {
       return ReInvFr_pt;
     }
References oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::ReInvFr_pt.
re_pt()
template<unsigned DIM> double*& oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::re_pt () inline
Pointer to Reynolds number.
     {
       // Return the Reynolds number pointer
       return Re_pt;
     } // End of re_pt
References oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::Re_pt.
re_st()
template<unsigned DIM> const double& oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::re_st () const inline
ReSt parameter (const. version)
     {
       // If the st is stored as external data
       if (ReynoldsStrouhal_is_stored_as_external_data)
       {
         // The index of the external data (which contains the st)
         unsigned data_index = 0;
         // The index of the value at which the ReynoldsStrouhal number is stored
         unsigned re_st_index = 0;
         // Return the value of the st in the external data
         return *(this->external_data_pt(data_index)->value_pt(re_st_index));
       }
       // Otherwise the st is just stored as a pointer
       else
       {
         // Return the value of St
         return *ReSt_pt;
       }
     } // End of re_st
References oomph::GeneralisedElement::external_data_pt(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::ReSt_pt, oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::ReynoldsStrouhal_is_stored_as_external_data, and oomph::Data::value_pt().
re_st_pt() [1/2]
template<unsigned DIM> double*& oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::re_st_pt () inline
Pointer to ReSt number (can only assign to private member data)
     {
       // Return the ReSt number pointer
       return ReSt_pt;
     } // End of st_pt
References oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::ReSt_pt.
re_st_pt() [2/2]
template<unsigned DIM> double* oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::re_st_pt () const inline
Pointer to Strouhal parameter (const. version)
     {
       // If the strouhal is stored as external data
       if (ReynoldsStrouhal_is_stored_as_external_data)
       {
         // The index of the external data (which contains the strouhal)
         unsigned data_index = 0;
         // The index of the value at which the ReynoldsStrouhal number is stored
         unsigned re_st_index = 0;
         // Return the value of the st in the external data
         return this->external_data_pt(data_index)->value_pt(re_st_index);
       }
       // Otherwise the strouhal is just stored as a pointer
       else
       {
         // Return the value of Strouhal
         return ReSt_pt;
       }
     } // End of re_st_pt
References oomph::GeneralisedElement::external_data_pt(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::ReSt_pt, oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::ReynoldsStrouhal_is_stored_as_external_data, and oomph::Data::value_pt().
scalar_name_paraview()
template<unsigned DIM> std::string oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::scalar_name_paraview (const unsigned & i) const inline virtual
Name of the i-th scalar field. Default implementation returns V1 for the first one, V2 for the second etc. Can (should!) be overloaded with more meaningful names in specific elements.
Reimplemented from oomph::FiniteElement.
     {
       // Velocities
       if (i < DIM)
       {
         // Return the appropriate string for the i-th velocity component
         return "Velocity " + StringConversion::to_string(i);
       }
       // Pressure
       else if (i == DIM)
       {
         // Return the name for the pressure
         return "Pressure";
       }
       // Never get here
       else
       {
         // Create an output stream
         std::stringstream error_stream;
         // Create the error message
         error_stream << "These Navier Stokes elements only store " << DIM + 1
                      << " fields,\nbut i is currently " << i << std::endl;
         // Throw the error message
         throw OomphLibError(
           error_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
         // Dummy return so the compiler doesn't complain
         return " ";
       }
     } // End of scalar_name_paraview
References DIM, i, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and oomph::StringConversion::to_string().
scalar_value_fct_paraview()
template<unsigned DIM> void oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::scalar_value_fct_paraview (std::ofstream & file_out, const unsigned & i, const unsigned & nplot, const double & time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const inline virtual
Write values of the i_field-th scalar field at the plot points. Needs to be implemented for each new specific element type.
Reimplemented from oomph::FiniteElement.
     {
 #ifdef PARANOID
       if (i > DIM)
       {
         // Create an output stream
         std::stringstream error_stream;
         // Create the error message
         error_stream << "These Navier Stokes elements only store " << DIM + 1
                      << " fields, but i is currently " << i << std::endl;
         // Throw the error message
         throw OomphLibError(
           error_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
       }
 #endif
       // Vector of local coordinates
       Vector<double> s(DIM + 1, 0.0);
       // Storage for the time value
       double interpolated_t = 0.0;
       // Storage for the spatial coordinates
       Vector<double> spatial_coordinates(DIM, 0.0);
       // How many plot points do we have in total?
       unsigned num_plot_points = nplot_points_paraview(nplot);
       // Loop over plot points
       for (unsigned iplot = 0; iplot < num_plot_points; iplot++)
       {
         // Get the local coordinates of the iplot-th plot point
         get_s_plot(iplot, nplot, s);
         // Loop over the spatial coordinates
         for (unsigned j = 0; j < DIM; j++)
         {
           // Assign the i-th spatial coordinate
           spatial_coordinates[j] = interpolated_x(s, j);
         }
         // Get the time value
         interpolated_t = interpolated_x(s, DIM);
         // ------ DRAIG: REMOVE ----------------------------------------
         // Exact solution vector (here it's simply a scalar)
         Vector<double> exact_soln(DIM + 1, 0.0);
         // DRAIG: Needs to be changed to a Vector of size DIM
         // ------ DRAIG: REMOVE ----------------------------------------
         // Get the exact solution at this point
         (*exact_soln_pt)(interpolated_t, spatial_coordinates, exact_soln);
         // Output the interpolated solution value
         file_out << exact_soln[i] << std::endl;
       } // for (unsigned iplot=0;iplot<num_plot_points;iplot++)
     } // End of scalar_value_fct_paraview
References DIM, ProblemParameters::exact_soln(), oomph::FiniteElement::get_s_plot(), i, oomph::FiniteElement::interpolated_x(), j, oomph::FiniteElement::nplot_points_paraview(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and s.
scalar_value_paraview()
template<unsigned DIM> void oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::scalar_value_paraview (std::ofstream & file_out, const unsigned & i, const unsigned & nplot) const inline virtual
Write values of the i-th scalar field at the plot points. Needs to be implemented for each new specific element type.
Reimplemented from oomph::FiniteElement.
     {
       // Vector of local coordinates
       Vector<double> s(DIM + 1, 0.0);
       // How many plot points do we have in total?
       unsigned num_plot_points = nplot_points_paraview(nplot);
       // Loop over plot points
       for (unsigned iplot = 0; iplot < num_plot_points; iplot++)
       {
         // Get the local coordinates of the iplot-th plot point
         get_s_plot(iplot, nplot, s);
         // Velocities
         if (i < DIM)
         {
           // Output the i-th velocity component
           file_out << interpolated_u_nst(s, i) << std::endl;
         }
         // Pressure
         else if (i == DIM)
         {
           // Output the pressure at this point
           file_out << interpolated_p_nst(s) << std::endl;
         }
         // Never get here
         else
         {
 #ifdef PARANOID
           // Create an output stream
           std::stringstream error_stream;
           // Create the error message
           error_stream << "These Navier Stokes elements only store " << DIM + 1
                        << " fields, "
                        << "but i is currently  " << i << std::endl;
           // Throw the error message
           throw OomphLibError(error_stream.str(),
                               OOMPH_CURRENT_FUNCTION,
                               OOMPH_EXCEPTION_LOCATION);
 #endif
         }
       } // for (unsigned iplot=0;iplot<num_plot_points;iplot++)
     } // End of scalar_value_paraview
References DIM, oomph::FiniteElement::get_s_plot(), i, oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::interpolated_p_nst(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::interpolated_u_nst(), oomph::FiniteElement::nplot_points_paraview(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and s.
shape_u_nst()
template<unsigned DIM> virtual void oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::shape_u_nst (const Vector< double > & s, Shape & psi) const protected pure virtual
DRAIG: Fill in later...
Implemented in oomph::QTaylorHoodMixedOrderSpaceTimeElement< DIM >, oomph::QTaylorHoodMixedOrderSpaceTimeElement< 2 >, oomph::QTaylorHoodMixedOrderSpaceTimeElement< DIM >, and oomph::QTaylorHoodMixedOrderSpaceTimeElement< 2 >.
Referenced by oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::dinterpolated_u_nst_ddata(), and oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::interpolated_u_nst().
source_fct_for_pressure_adv_diff() [1/2]
template<unsigned DIM> NavierStokesMixedOrderPressureAdvDiffSourceFctPt& oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::source_fct_for_pressure_adv_diff () inline
Access function for the source-function pointer for pressure advection diffusion (used for validation only).
     {
       return Press_adv_diff_source_fct_pt;
     }
References oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::Press_adv_diff_source_fct_pt.
source_fct_for_pressure_adv_diff() [2/2]
template<unsigned DIM> NavierStokesMixedOrderPressureAdvDiffSourceFctPt oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::source_fct_for_pressure_adv_diff () const inline
Access function for the source-function pointer for pressure advection diffusion (used for validation only). Const version.
     {
       return Press_adv_diff_source_fct_pt;
     }
References oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::Press_adv_diff_source_fct_pt.
source_fct_pt() [1/2]
template<unsigned DIM> NavierStokesMixedOrderSourceFctPt& oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::source_fct_pt () inline
Access function for the source-function pointer.
     {
       return Source_fct_pt;
     }
References oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::Source_fct_pt.
source_fct_pt() [2/2]
template<unsigned DIM> NavierStokesMixedOrderSourceFctPt oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::source_fct_pt () const inline
Access function for the source-function pointer. Const version.
     {
       return Source_fct_pt;
     }
References oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::Source_fct_pt.
store_reynolds_strouhal_as_external_data()
template<unsigned DIM> void oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::store_reynolds_strouhal_as_external_data (Data * reynolds_strouhal_data_pt) inline
Function that tells us whether the period is stored as external data.
     {
 #ifdef PARANOID
       // Sanity check; make sure it's not a null pointer
       if (reynolds_strouhal_data_pt == 0)
       {
         // Create an output stream
         std::ostringstream error_message_stream;
         // Create an error message
         error_message_stream
           << "User supplied the Reynolds x Strouhal number as "
           << "external data\nbut the pointer provided is a "
           << "null pointer!" << std::endl;
         // Throw an error
         throw OomphLibError(error_message_stream.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
 #endif
       // Set the Strouhal value pointer (the Strouhal number is stored as the
       // only piece of internal data in the phase condition element)
       this->add_external_data(reynolds_strouhal_data_pt);
       // Indicate that the Strouhal number is store as external data
       ReynoldsStrouhal_is_stored_as_external_data = true;
     } // End of store_strouhal_as_external_data
References oomph::GeneralisedElement::add_external_data(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::ReynoldsStrouhal_is_stored_as_external_data.
Referenced by oomph::RefineableSpaceTimeNavierStokesMixedOrderEquations< DIM >::further_build().
strain_rate()
template<unsigned DIM> void oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::strain_rate (const Vector< double > & s, DenseMatrix< double > & strain_rate) const
Strain-rate tensor: 1/2 (du_i/dx_j+du_j/dx_i)
Get strain-rate tensor: (1/2)*(du_i/dx_j+du_j/dx_i)
   {
 #ifdef PARANOID
     if ((strainrate.ncol() != DIM) || (strainrate.nrow() != DIM))
     {
       std::ostringstream error_message;
       error_message << "The strain rate has incorrect dimensions "
                     << strainrate.ncol() << " x " << strainrate.nrow()
                     << " not " << DIM << std::endl;
       throw OomphLibError(
         error_message.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
 #endif
     // Velocity gradient matrix
     DenseMatrix<double> dudx(DIM);
     // Find out how many nodes there are in the element
     unsigned n_node = nnode();
     // Set up memory for the shape and test functions
     Shape psi(n_node);
     // Set up memory for the shape and test function derivatives
     DShape dpsidx(n_node, DIM + 1);
     // Evaluate the shape functions and shape function derivatives at this point
     dshape_eulerian(s, psi, dpsidx);
     // Initialise to zero
     dudx.initialise(0.0);
     // Loop over velocity components
     for (unsigned i = 0; i < DIM; i++)
     {
       // Get the index at which the i-th velocity is stored
       unsigned u_nodal_index = u_index_nst(i);
       // Loop over derivative directions
       for (unsigned j = 0; j < DIM; j++)
       {
         // Loop over nodes
         for (unsigned l = 0; l < n_node; l++)
         {
           // Update the value of du_i/dx_j
           dudx(i, j) += nodal_value(l, u_nodal_index) * dpsidx(l, j);
         }
       } // for (unsigned j=0;j<DIM;j++)
     } // for (unsigned i=0;i<DIM;i++)
     // Loop over velocity components
     for (unsigned i = 0; i < DIM; i++)
     {
       // Loop over derivative directions
       for (unsigned j = 0; j < DIM; j++)
       {
         // Calculate the (i,j)-th strain rate entry
         strainrate(i, j) = 0.5 * (dudx(i, j) + dudx(j, i));
       }
     } // for (unsigned i=0;i<DIM;i++)
   } // End of strain_rate
References DIM, i, oomph::DenseMatrix< T >::initialise(), j, oomph::DenseMatrix< T >::ncol(), oomph::DenseMatrix< T >::nrow(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and s.
Referenced by oomph::RefineableSpaceTimeNavierStokesMixedOrderEquations< DIM >::get_Z2_flux().
u_index_nst()
template<unsigned DIM> virtual unsigned oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::u_index_nst (const unsigned & i) const inline virtual
Return the index at which the i-th unknown velocity component is stored. The default value, i, is appropriate for single-physics problems. In derived multi-physics elements, this function should be overloaded to reflect the chosen storage scheme. Note that these equations require that the unknowns are always stored at the same indices at each node.
     {
 #ifdef PARANOID
       if (i > DIM - 1)
       {
         // Create an output stream
         std::ostringstream error_message_stream;
         // Create an error message
         error_message_stream << "Input index " << i << " does not correspond "
                              << "to a velocity component when DIM=" << DIM
                              << "!" << std::endl;
         // Throw an error
         throw OomphLibError(error_message_stream.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
 #endif
       // Return the appropriate entry
       return i;
     } // End of u_index_nst
References DIM, i, OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
Referenced by oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::dinterpolated_u_nst_ddata(), oomph::RefineableSpaceTimeNavierStokesMixedOrderEquations< DIM >::dinterpolated_u_nst_ddata(), oomph::RefineableSpaceTimeNavierStokesMixedOrderEquations< DIM >::get_Z2_flux(), oomph::RefineableQTaylorHoodMixedOrderSpaceTimeElement< DIM >::identify_load_data(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::interpolated_du_dt_nst(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::interpolated_u_nst(), and oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::u_nst().
u_nst() [1/2]
template<unsigned DIM> double oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::u_nst (const unsigned & n, const unsigned & i) const inline
Velocity i at local node n. Uses suitably interpolated value for hanging nodes. The use of u_index_nst() permits the use of this element as the basis for multi-physics elements. The default is to assume that the i-th velocity component is stored at the i-th location of the node
     {
       return nodal_value(n, u_index_nst(i));
     }
References i, n, oomph::FiniteElement::nodal_value(), and oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::u_index_nst().
u_nst() [2/2]
template<unsigned DIM> double oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::u_nst (const unsigned & t, const unsigned & n, const unsigned & i) const inline
Velocity i at local node n at timestep t (t=0: present; t>0: previous). Uses suitably interpolated value for hanging nodes.
     {
 #ifdef PARANOID
       // Since we're using space-time elements, this only makes sense if t=0
       if (t != 0)
       {
         // Throw an error
         throw OomphLibError("Space-time elements cannot have history values!",
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
 #endif
       // Return the appropriate nodal value (noting that t=0 here)
       return nodal_value(t, n, u_index_nst(i));
     } // End of u_nst
References i, n, oomph::FiniteElement::nodal_value(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, plotPSD::t, and oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::u_index_nst().
viscosity_ratio()
template<unsigned DIM> const double& oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::viscosity_ratio () const inline
Viscosity ratio for element: Element's viscosity relative to the viscosity used in the definition of the Reynolds number
     {
       return *Viscosity_Ratio_pt;
     }
References oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::Viscosity_Ratio_pt.
viscosity_ratio_pt()
template<unsigned DIM> double*& oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::viscosity_ratio_pt () inline
Pointer to Viscosity Ratio.
     {
       return Viscosity_Ratio_pt;
     }
References oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::Viscosity_Ratio_pt.
Member Data Documentation
ALE_is_disabled
template<unsigned DIM> bool oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::ALE_is_disabled protected
Boolean flag to indicate if ALE formulation is disabled when time-derivatives are computed. Only set to true if you're sure that the mesh is stationary.
Referenced by oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::disable_ALE(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::enable_ALE(), and oomph::RefineableSpaceTimeNavierStokesMixedOrderEquations< DIM >::further_build().
Body_force_fct_pt
template<unsigned DIM> NavierStokesMixedOrderBodyForceFctPt oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::Body_force_fct_pt protected
Pointer to body force function.
Referenced by oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::body_force_fct_pt(), oomph::RefineableSpaceTimeNavierStokesMixedOrderEquations< DIM >::further_build(), and oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::get_body_force_nst().
Default_Gravity_vector
template<unsigned DIM> Vector< double > oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::Default_Gravity_vector static private
Static default value for the gravity vector.
Navier-Stokes equations default gravity vector.
Referenced by oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::SpaceTimeNavierStokesMixedOrderEquations().
Default_Physical_Constant_Value
template<unsigned DIM> double oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::Default_Physical_Constant_Value = 0.0 static private
Navier-Stokes equations static data.
Static default value for the physical constants (all initialised to zero)
Referenced by oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::SpaceTimeNavierStokesMixedOrderEquations().
Default_Physical_Ratio_Value
template<unsigned DIM> double oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::Default_Physical_Ratio_Value = 1.0 static private
Navier-Stokes equations static data.
Static default value for the physical ratios (all are initialised to one)
Referenced by oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::SpaceTimeNavierStokesMixedOrderEquations().
Density_Ratio_pt
template<unsigned DIM> double* oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::Density_Ratio_pt protected
Pointer to the density ratio (relative to the density used in the definition of the Reynolds number)
Referenced by oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::density_ratio(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::density_ratio_pt(), oomph::RefineableSpaceTimeNavierStokesMixedOrderEquations< DIM >::further_build(), and oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::SpaceTimeNavierStokesMixedOrderEquations().
G_pt
template<unsigned DIM> Vector<double>* oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::G_pt protected
Pointer to global gravity Vector.
Referenced by oomph::RefineableSpaceTimeNavierStokesMixedOrderEquations< DIM >::further_build(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::g(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::g_pt(), and oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::SpaceTimeNavierStokesMixedOrderEquations().
Gamma
template<unsigned DIM> Vector< double > oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::Gamma static
Navier-Stokes equations static data.
Vector to decide whether the stress-divergence form is used or not N.B. This needs to be public so that the intel compiler gets things correct somehow the access function messes things up when going to refineable Navier-Stokes
Pinned_fp_pressure_eqn
template<unsigned DIM> int oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::Pinned_fp_pressure_eqn protected
Global eqn number of pressure dof that's pinned in pressure advection diffusion problem (defaults to -1)
Referenced by oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::pinned_fp_pressure_eqn().
Press_adv_diff_source_fct_pt
template<unsigned DIM> NavierStokesMixedOrderPressureAdvDiffSourceFctPt oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::Press_adv_diff_source_fct_pt protected
Pointer to source function pressure advection diffusion equation (only to be used during validation)
Referenced by oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::source_fct_for_pressure_adv_diff().
Pressure_advection_diffusion_robin_element_pt
template<unsigned DIM> Vector<FpPressureAdvDiffRobinBCMixedOrderSpaceTimeElementBase*> oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::Pressure_advection_diffusion_robin_element_pt protected
Storage for FaceElements that apply Robin BC for pressure adv diff equation used in Fp preconditioner.
Referenced by oomph::QTaylorHoodMixedOrderSpaceTimeElement< DIM >::build_fp_press_adv_diff_robin_bc_element(), oomph::RefineableQTaylorHoodMixedOrderSpaceTimeElement< DIM >::build_fp_press_adv_diff_robin_bc_element(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::delete_pressure_advection_diffusion_robin_elements(), and oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::output_pressure_advection_diffusion_robin_elements().
Pressure_not_stored_at_node
template<unsigned DIM> int oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::Pressure_not_stored_at_node static private
Initial value:
=
      -100
Static "magic" number that indicates that the pressure is not stored at a node
"Magic" negative number that indicates that the pressure is not stored at a node. This cannot be -1 because that represents the positional hanging scheme in the hanging_pt object of nodes.
Referenced by oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::p_nodal_index_nst().
Re_pt
template<unsigned DIM> double* oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::Re_pt protected
Pointer to global Reynolds number.
Referenced by oomph::RefineableSpaceTimeNavierStokesMixedOrderEquations< DIM >::further_build(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::re(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::re_pt(), and oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::SpaceTimeNavierStokesMixedOrderEquations().
ReInvFr_pt
template<unsigned DIM> double* oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::ReInvFr_pt protected
Pointer to global Reynolds number x inverse Froude number (= Bond number / Capillary number)
Referenced by oomph::RefineableSpaceTimeNavierStokesMixedOrderEquations< DIM >::further_build(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::re_invfr(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::re_invfr_pt(), and oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::SpaceTimeNavierStokesMixedOrderEquations().
ReSt_pt
template<unsigned DIM> double* oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::ReSt_pt protected
Pointer to global Reynolds number x Strouhal number (=Womersley)
Referenced by oomph::RefineableSpaceTimeNavierStokesMixedOrderEquations< DIM >::further_build(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::re_st(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::re_st_pt(), and oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::SpaceTimeNavierStokesMixedOrderEquations().
ReynoldsStrouhal_is_stored_as_external_data
template<unsigned DIM> bool oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::ReynoldsStrouhal_is_stored_as_external_data protected
Boolean to indicate whether or not the Strouhal value is stored as external data (if it's also an unknown of the problem)
Referenced by oomph::RefineableSpaceTimeNavierStokesMixedOrderEquations< DIM >::further_build(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::is_reynolds_strouhal_stored_as_external_data(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::re_st(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::re_st_pt(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::SpaceTimeNavierStokesMixedOrderEquations(), and oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::store_reynolds_strouhal_as_external_data().
Source_fct_pt
template<unsigned DIM> NavierStokesMixedOrderSourceFctPt oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::Source_fct_pt protected
Pointer to volumetric source function.
Referenced by oomph::RefineableSpaceTimeNavierStokesMixedOrderEquations< DIM >::further_build(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::get_source_nst(), and oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::source_fct_pt().
Viscosity_Ratio_pt
template<unsigned DIM> double* oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::Viscosity_Ratio_pt protected
Pointer to the viscosity ratio (relative to the viscosity used in the definition of the Reynolds number)
Referenced by oomph::RefineableSpaceTimeNavierStokesMixedOrderEquations< DIM >::further_build(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::SpaceTimeNavierStokesMixedOrderEquations(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::viscosity_ratio(), and oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::viscosity_ratio_pt().
The documentation for this class was generated from the following files:
mixed_order_petrov_galerkin_space_time_navier_stokes_elements.h
mixed_order_petrov_galerkin_space_time_navier_stokes_elements.cc