MercuryDPM: two_d_poisson.cc File Reference
poisson/poisson_with_singularity/two_d_poisson.cc File Reference
#include "generic.h"
#include "poisson.h"
#include "meshes/simple_rectangular_quadmesh.h"
#include "poisson_elements_with_singularity.h"
Classes
class PoissonProblem< ELEMENT >
Micky mouse Poisson problem.
Namespaces
Global_parameters
Namespace.
Functions
double Global_parameters::b (const double &r)
Blending function based on the rectangular function but made smoother.
Vector< double > Global_parameters::x1 (const Vector< double > &coord)
Cartesian coordinates centered at the point (0.5,1)
Vector< double > Global_parameters::x2 (const Vector< double > &coord)
Cartesian coordinates centered at the point (1.5,1)
Vector< double > Global_parameters::polar (const Vector< double > &coord)
Polar coordinates (r,phi) centered at the point x.
Vector< double > Global_parameters::polar1 (const Vector< double > &coord)
Polar coordinates (r,phi) centered at the point (0.5,1)
Vector< double > Global_parameters::polar2 (const Vector< double > &coord)
Polar coordinates (r,phi) centered at the point (1.5,1)
double Global_parameters::f1_exact (const Vector< double > &coord)
function that contributs to u_exact
double Global_parameters::f1 (const Vector< double > &coord)
f1 function, in front of the C1 unknown
Vector< double > Global_parameters::grad_f1 (const Vector< double > &coord)
double Global_parameters::f2_exact (const Vector< double > &coord)
function that contributes to u_exact
double Global_parameters::f2 (const Vector< double > &coord)
f2 function, in front of the C2 unknown
Vector< double > Global_parameters::grad_f2 (const Vector< double > &coord)
gradient of f2 function
void Global_parameters::get_exact_u (const Vector< double > &coord, Vector< double > &u)
void Global_parameters::source_function (const Vector< double > &coord, double &source)
Source function required to make the solution above an exact solution.
int main (int argc, char **argv)
Driver code for 2D Poisson problem.
Variables
unsigned Global_parameters::Element_multiplier =1
element multiplier for convergence tess
bool Global_parameters::Blend = false
Boolean that imposes the blending or not.
double Global_parameters::R_blend = 0.5
Limit of the blending region.
unsigned Global_parameters::Direction = 1
Function Documentation
main()
int main (int argc , char ** argv)
Driver code for 2D Poisson problem.
 {
  // Store command line arguments
  CommandLineArgs::setup(argc,argv);
  // Define possible command line arguments and parse the ones that
  // were actually specified
  // Multiplier for elements
  CommandLineArgs::specify_command_line_flag(
   "--element_multiplier",
   &Global_parameters::Element_multiplier);
  // Impose blending or not
  CommandLineArgs::specify_command_line_flag("--blend");
  // radius of the blending
  CommandLineArgs::specify_command_line_flag(
   "--r_blend",&Global_parameters::R_blend);
  // Parse command line
  CommandLineArgs::parse_and_assign();
  // Doc what has actually been specified on the command line
  CommandLineArgs::doc_specified_flags();
  if (CommandLineArgs::command_line_flag_has_been_set
      ("--blend"))
   {
    Global_parameters::Blend=true;
   }
  //Set up the problem
  //------------------
  // Create the problem with 2D nine-node elements from the
  // QPoissonElement family. Pass pointer to source function.
  PoissonProblem<PoissonElementWithSingularity<
   QPoissonElement<2,3> > >
   problem(&Global_parameters::source_function);
  // Create label for output
  //------------------------
  DocInfo doc_info;
  // Set output directory
  doc_info.set_directory("RESLT");
  // Solve the problem
  problem.newton_solve();
  //Output the solution
  problem.doc_solution(doc_info);
 } //end of main
References Global_parameters::Blend, oomph::CommandLineArgs::command_line_flag_has_been_set(), oomph::CommandLineArgs::doc_specified_flags(), Global_parameters::Element_multiplier, oomph::CommandLineArgs::parse_and_assign(), problem, Global_parameters::R_blend, oomph::DocInfo::set_directory(), Flag_definition::setup(), Global_parameters::source_function(), and oomph::CommandLineArgs::specify_command_line_flag().