MercuryDPM: hstop_StudyHeightHmaxAngle_exponential.cpp File Reference
hstop_StudyHeightHmaxAngle_exponential.cpp File Reference
#include "SilbertPeriodic.h"
Classes
class SilbertHstop
Functions
bool PointIsAboveCurve (int argc, char *argv[], Mdouble h, Mdouble a, int study_num)
int HstopCurve (int argc, char *argv[], int study_num, Mdouble h, Mdouble hMax, Mdouble a)
int main (int argc, char *argv[])
Variables
std::fstream ReportFile
Function Documentation
HstopCurve()
int HstopCurve (int argc, char * argv[], int study_num, Mdouble h, Mdouble hMax, Mdouble a)
 {
     logger(INFO, "restart at study_num=%, h=%, a=%", study_num, h, a);
   std::stringstream name;
     name << "Report" << study_num;
     ReportFile.open(name.str().c_str(),std::fstream::out | std::fstream::app);
     //~ ReportFile << "height\tangle\tlambda\tmu\tabovemuBottom\tabove\n";
     bool piac = PointIsAboveCurve(argc,argv,h,a,study_num);
     ReportFile.close();
     //now increase height gradually; decrease angle if flow starts
     if (h<hMax)
     {
         //exponential
         if (piac) a -= .5;
         else
         {
             h *= pow(2., .25);
             a += .25;
         }
         //linear
         //if (piac) a-=.5;
         //else h+=2;
         //write arg file
         std::stringstream command;
         command << "echo " << study_num << " " << h << " " << hMax << " " << a << " > arg";
         logger(INFO, "%", command.str());
         return system(command.str().c_str());
     } else {
         return 0;
     }
 }
References a, INFO, logger, plotDoE::name, out(), PointIsAboveCurve(), Eigen::bfloat16_impl::pow(), and ReportFile.
Referenced by main().
main()
int main (int argc , char * argv[])
 {
     if (argc < 4)
     {
         logger(ERROR, "Please specify Study, Height, max. Height and Angle");
     }
     HstopCurve(argc, argv, atoi(argv[1]), atof(argv[2]), atof(argv[3]), atof(argv[4]));
 }
References ERROR, HstopCurve(), and logger.
PointIsAboveCurve()
bool PointIsAboveCurve (int argc, char * argv[], Mdouble h, Mdouble a, int study_num)
{
     logger(INFO, "PointIsAboveCurve(%, h=%, a=%)", study_num, h, a);
     SilbertHstop problem;
     problem.setInflowHeight(h);
     problem.setChuteAngle(a);
     problem.set_study(study_num);
     std::stringstream name;
     name << "H" << problem.getInflowHeight()
          << "A" << problem.getChuteAngleDegrees()
          << "L" << round(100. * problem.getFixedParticleRadius() * 2.) / 100.
          << "M" << problem.species->getSlidingFrictionCoefficient()
          << "B" << problem.getSlidingFrictionCoefficientBottom();
     problem.setName(name.str().c_str());
     logger(INFO, "starting %", name.str().c_str());
     problem.writeRestartFile();
     if ((argc > 5) && (!strcmp(argv[5], "-test")))
     {
         // for test runs:
         problem.solve_analytic();
     }
     else
     {
         // for real runs:
         problem.solve();
     }
     std::stringstream com;
     ReportFile << problem.getInflowHeight()
                << "\t" << problem.getChuteAngleDegrees()
          << "\t" << round(100.*problem.getFixedParticleRadius()*2.)/100.
          << "\t" << problem.species->getSlidingFrictionCoefficient()
          << "\t" << problem.getSlidingFrictionCoefficientBottom()
          << "\t" << problem.pointIsAboveCurve
              << std::endl;
     return problem.pointIsAboveCurve;
 }
References a, INFO, logger, plotDoE::name, problem, ReportFile, and Eigen::bfloat16_impl::round().
Referenced by HstopCurve().
Variable Documentation
ReportFile
std::fstream ReportFile
Referenced by HstopCurve(), and PointIsAboveCurve().