MercuryDPM: linearised_poroelastic_fsi_pulsewave.cc File Reference
linearised_poroelastic_fsi_pulsewave.cc File Reference
#include "generic.h"
#include "axisym_navier_stokes.h"
#include "axisym_poroelasticity.h"
#include "meshes/triangle_mesh.h"
Classes
class PressureWaveFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >
Problem class.
Namespaces
Global_Physical_Variables
Global variables.
Functions
std::string Global_Physical_Variables::Directory ("RESLT")
void Global_Physical_Variables::fluid_inflow_boundary_traction (const double &time, const Vector< double > &x, const Vector< double > &n, Vector< double > &result)
Inflow traction applied to the fluid mesh.
void Global_Physical_Variables::update_dependent_parameters ()
Helper function to update dependent parameters.
void Global_Physical_Variables::doc_dependent_parameters ()
Doc dependent parameters.
template<class ELEMENT >
void Global_Physical_Variables::edge_sign_setup (Mesh *mesh_pt)
Global function that completes the edge sign setup.
int main (int argc, char **argv)
Variables
double Global_Physical_Variables::Chris_p_factor =1.0
double Global_Physical_Variables::Poro_elastic_to_navier_stokes_fluid_density =1.0
double Global_Physical_Variables::Permeability =5.0
double Global_Physical_Variables::Porosity =0.18
Porosity.
double Global_Physical_Variables::Density_ratio_poro =1.0
double Global_Physical_Variables::Inverse_slip_rate_coefficient =0.0
Inverse slip rate coefficient.
double Global_Physical_Variables::Lambda_lame = 0.0
Lambda - first Lame parameter – dependent parameter; compute from nu.
double Global_Physical_Variables::Mu_lame = 0.0
mu - second Lame parameter – dependent parameter; compute from nu
double Global_Physical_Variables::Rho_f_over_rho = 0.0
double Global_Physical_Variables::Element_area_fluid =0.002
Target element area for fluid mesh.
double Global_Physical_Variables::Element_area_solid =0.002
Target element area for poro-elasticmesh.
double Global_Physical_Variables::Fluid_mesh_bl_thickness =0.01
Fluid mesh boundary layer thickness.
double Global_Physical_Variables::Solid_mesh_bl_thickness =0.01
Poro-elastic mesh boundary layer thickness.
double Global_Physical_Variables::P_inlet_initial =500.0
Constant inlet pressure (for steady Poiseuille flow)
double Global_Physical_Variables::P_inlet_step =P_inlet_initial
double Global_Physical_Variables::T_tanh =0.25
Parameter for tanh origin for pressure incrementation.
double Global_Physical_Variables::Alpha_tanh =100.0
Steepness parameter for tanh for pressure incrementation.
Function Documentation
main()
int main (int argc , char ** argv)
 {
  // Store command line arguments
  CommandLineArgs::setup(argc,argv);
  // Define possible command line arguments and parse the ones that
  // were actually specified
  // Reynolds number
  CommandLineArgs::specify_command_line_flag("--re",
                                             &Global_Physical_Variables::Re);
  // FSI parameter
  CommandLineArgs::specify_command_line_flag("--q",
                                             &Global_Physical_Variables::Q);
  // Drained Poisson's ratio
  CommandLineArgs::specify_command_line_flag("--nu",
                                             &Global_Physical_Variables::Nu);
  // Initial inlet pressure
  CommandLineArgs::specify_command_line_flag(
   "--p_inlet_initial",
   &Global_Physical_Variables::P_inlet_initial);
  // Step in inlet pressure (applied with tanh profile)
  CommandLineArgs::specify_command_line_flag(
   "--p_inlet_step",
   &Global_Physical_Variables::P_inlet_step);
  // Non-dim permeability
  CommandLineArgs::specify_command_line_flag(
   "--permeability",
   &Global_Physical_Variables::Permeability);
  // Ratio of poro-elastic fluid to Navier-Stokes fluid densities
  CommandLineArgs::specify_command_line_flag(
   "--fluid_density_ratio",
   &Global_Physical_Variables::Poro_elastic_to_navier_stokes_fluid_density);
  // Biot parameter
  CommandLineArgs::specify_command_line_flag(
   "--alpha",
   &Global_Physical_Variables::Alpha);
  // Porosity
  CommandLineArgs::specify_command_line_flag(
   "--porosity",
   &Global_Physical_Variables::Porosity);
  // Factor for reduction in inlet pressure
  CommandLineArgs::specify_command_line_flag(
   "--chris_p_factor", &Global_Physical_Variables::Chris_p_factor);
  // Outer radius
  CommandLineArgs::specify_command_line_flag(
   "--outer_radius",&Global_Physical_Variables::Outer_radius);
  // Outer radius
  CommandLineArgs::specify_command_line_flag(
   "--length",&Global_Physical_Variables::Length);
  // Pin darcy?
  CommandLineArgs::specify_command_line_flag("--pin_darcy");
  // Start from rest?
  CommandLineArgs::specify_command_line_flag("--start_from_steady_presolve");
  // Element area for fluid mesh
  CommandLineArgs::specify_command_line_flag(
   "--el_area_fluid",
   &Global_Physical_Variables::Element_area_fluid);
  // Element area for solid mesh
  CommandLineArgs::specify_command_line_flag(
   "--el_area_solid",
   &Global_Physical_Variables::Element_area_solid);
  // Output directory
  CommandLineArgs::specify_command_line_flag(
   "--dir",&Global_Physical_Variables::Directory);
  // Timestep
  double dt=0.00001;
  CommandLineArgs::specify_command_line_flag("--dt",&dt);
  // Number of timesteps to perform
  unsigned nstep=1000;
  CommandLineArgs::specify_command_line_flag("--nstep",&nstep);
  // Steepness parameter for tanh increment of pressure load
  CommandLineArgs::specify_command_line_flag(
   "--alpha_tanh",
   &Global_Physical_Variables::Alpha_tanh);
  // "Time" for tanh increment of pressure load
  CommandLineArgs::specify_command_line_flag(
   "--t_tanh",
   &Global_Physical_Variables::T_tanh);
  // Validation run?
  CommandLineArgs::specify_command_line_flag("--validation");
  // Parse command line
  CommandLineArgs::parse_and_assign();
  // Doc what has actually been specified on the command line
  CommandLineArgs::doc_specified_flags();
  // Create doc info object
  DocInfo doc_info;
  doc_info.set_directory(Global_Physical_Variables::Directory);
  // Create problem
  PressureWaveFSIProblem<AxisymmetricTTaylorHoodElement,
                          TAxisymmetricPoroelasticityElement<1> > problem;
  // Update dependent problem parameters
  Global_Physical_Variables::update_dependent_parameters();
  // Doc dependent parameters
  Global_Physical_Variables::doc_dependent_parameters();
  // Set up impulsive start from rest
  problem.assign_initial_values_impulsive(dt);
  if (CommandLineArgs::command_line_flag_has_been_set("--validation"))
   {
    // Do only 3 steps if validating
    nstep=3;
   }
  // Output current time
  oomph_info << "Output initial state.\n";
  // Output mesh and initial conditions
  problem.doc_solution(doc_info);
  if (CommandLineArgs::command_line_flag_has_been_set
      ("--start_from_steady_presolve"))
   {
    oomph_info << "Doing steady initial solve.\n";
    // Do a steady solve
    problem.steady_newton_solve();
    // Output solution
    problem.doc_solution(doc_info);
   }
  else
   {
    oomph_info << "Bypassing steady initial solve and starting from rest.\n";
   }
  // Timestep
  oomph_info << "About to do " << nstep << " timesteps with dt = "
             << dt << std::endl;
  for(unsigned n=0;n<nstep;n++)
   {
    oomph_info << "Solving at time " << problem.time_pt()->time()+dt
               << std::endl;
    //Solve the problem
    problem.unsteady_newton_solve(dt);
    // Output
    problem.doc_solution(doc_info);
   }
  return 0;
 }
References Global_Physical_Variables::Alpha, Global_Physical_Variables::Alpha_tanh, Global_Physical_Variables::Chris_p_factor, oomph::CommandLineArgs::command_line_flag_has_been_set(), Global_Physical_Variables::Directory(), Global_Physical_Variables::doc_dependent_parameters(), oomph::CommandLineArgs::doc_specified_flags(), Global_Physical_Variables::Element_area_fluid, Global_Physical_Variables::Element_area_solid, Global_Physical_Variables::Length, n, Global_Physical_Variables::Nu, oomph::oomph_info, Global_Physical_Variables::Outer_radius, Global_Physical_Variables::P_inlet_initial, Global_Physical_Variables::P_inlet_step, oomph::CommandLineArgs::parse_and_assign(), Global_Physical_Variables::Permeability, Global_Physical_Variables::Poro_elastic_to_navier_stokes_fluid_density, Global_Physical_Variables::Porosity, problem, Global_Physical_Variables::Q, Global_Physical_Variables::Re, oomph::DocInfo::set_directory(), Flag_definition::setup(), oomph::CommandLineArgs::specify_command_line_flag(), Global_Physical_Variables::T_tanh, and Global_Physical_Variables::update_dependent_parameters().