MercuryDPM: Eigen::internal::tensor_static_symgroup_do_apply< internal::type_list< first, next... > > Struct Template Reference
Eigen::internal::tensor_static_symgroup_do_apply< internal::type_list< first, next... > > Struct Template Reference
#include <StaticSymmetry.h>
Static Public Member Functions
template<typename Op , typename RV , std::size_t SGNumIndices, typename Index , std::size_t NumIndices, typename... Args>
static RV run (const std::array< Index, NumIndices > &idx, RV initial, Args &&... args)
template<typename Op , typename RV , std::size_t SGNumIndices, typename Index , typename... Args>
static RV run (const std::vector< Index > &idx, RV initial, Args &&... args)
Member Function Documentation
run() [1/2]
template<typename first , typename... next> template<typename Op , typename RV , std::size_t SGNumIndices, typename Index , std::size_t NumIndices, typename... Args> static RV Eigen::internal::tensor_static_symgroup_do_apply< internal::type_list< first, next... > >::run (const std::array< Index, NumIndices > & idx, RV initial, Args &&... args) inline static
{
     static_assert(NumIndices >= SGNumIndices,
                   "Can only apply symmetry group to objects that have at least the required amount of indices.");
     typedef typename internal::gen_numeric_list<int, NumIndices - SGNumIndices, SGNumIndices>::type remaining_indices;
     initial = Op::run(tensor_static_symgroup_index_permute(idx, typename first::indices(), remaining_indices()),
                       first::flags, initial, std::forward<Args>(args)...);
     return tensor_static_symgroup_do_apply<internal::type_list<next...>>::template run<Op, RV, SGNumIndices>(
         idx, initial, args...);
   }
References compute_granudrum_aor::args, int(), run(), Eigen::internal::tensor_static_symgroup_index_permute(), and compute_granudrum_aor::type.
run() [2/2]
template<typename first , typename... next> template<typename Op , typename RV , std::size_t SGNumIndices, typename Index , typename... Args> static RV Eigen::internal::tensor_static_symgroup_do_apply< internal::type_list< first, next... > >::run (const std::vector< Index > & idx, RV initial, Args &&... args) inline static
{
     eigen_assert(idx.size() >= SGNumIndices &&
                  "Can only apply symmetry group to objects that have at least the required amount of indices.");
     initial = Op::run(tensor_static_symgroup_index_permute(idx, typename first::indices()), first::flags, initial,
                       std::forward<Args>(args)...);
     return tensor_static_symgroup_do_apply<internal::type_list<next...>>::template run<Op, RV, SGNumIndices>(
         idx, initial, args...);
   }
References compute_granudrum_aor::args, eigen_assert, run(), and Eigen::internal::tensor_static_symgroup_index_permute().
The documentation for this struct was generated from the following file:
StaticSymmetry.h