MercuryDPM: Eigen::internal::scalar_clamp_op< Scalar > Struct Template Reference
Eigen::internal::scalar_clamp_op< Scalar > Struct Template Reference
#include <TensorFunctors.h>
Public Member Functions
EIGEN_DEVICE_FUNC scalar_clamp_op (const Scalar &_min, const Scalar &_max)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Scalar operator() (const Scalar &x) const
template<typename Packet >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Packet packetOp (const Packet &x) const
Public Attributes
const Scalar m_min
const Scalar m_max
Constructor & Destructor Documentation
scalar_clamp_op()
template<typename Scalar > EIGEN_DEVICE_FUNC Eigen::internal::scalar_clamp_op< Scalar >::scalar_clamp_op (const Scalar & _min, const Scalar & _max) inline
 : m_min(_min), m_max(_max) {}
Member Function Documentation
operator()()
template<typename Scalar > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Scalar Eigen::internal::scalar_clamp_op< Scalar >::operator() (const Scalar & x) const inline
{
     return numext::mini(numext::maxi(x, m_min), m_max);
   }
References Eigen::internal::scalar_clamp_op< Scalar >::m_max, Eigen::internal::scalar_clamp_op< Scalar >::m_min, Eigen::numext::maxi(), Eigen::numext::mini(), and plotDoE::x.
packetOp()
template<typename Scalar > template<typename Packet > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Packet Eigen::internal::scalar_clamp_op< Scalar >::packetOp (const Packet & x) const inline
{
     return internal::pmin(internal::pmax(x, pset1<Packet>(m_min)), pset1<Packet>(m_max));
   }
References Eigen::internal::scalar_clamp_op< Scalar >::m_max, Eigen::internal::scalar_clamp_op< Scalar >::m_min, Eigen::internal::pmax(), Eigen::internal::pmin(), and plotDoE::x.
Member Data Documentation
m_max
template<typename Scalar > const Scalar Eigen::internal::scalar_clamp_op< Scalar >::m_max
Referenced by Eigen::internal::scalar_clamp_op< Scalar >::operator()(), and Eigen::internal::scalar_clamp_op< Scalar >::packetOp().
m_min
template<typename Scalar > const Scalar Eigen::internal::scalar_clamp_op< Scalar >::m_min
Referenced by Eigen::internal::scalar_clamp_op< Scalar >::operator()(), and Eigen::internal::scalar_clamp_op< Scalar >::packetOp().
The documentation for this struct was generated from the following file:
TensorFunctors.h