MercuryDPM: ClosedCSCRestart.cpp File Reference
ClosedCSCRestart.cpp File Reference
#include "Mercury3D.h"
#include "Walls/InfiniteWall.h"
#include <sys/time.h>
Classes
class ClosedCSCRestart
Functions
double get_wall_time ()
int main (int argc, char *argv[])
Function Documentation
get_wall_time()
double get_wall_time ()
                       {
     struct timeval time;
     if (gettimeofday(&time,NULL)){
         //  Handle error
         return 0;
     }
     return (double)time.tv_sec + (double)time.tv_usec * .000001;
 }
Referenced by ClosedCSCRestart::ClosedCSCRestart(), and ClosedCSCRestart::writeOutputFiles().
main()
int main (int argc , char * argv[])
{
     Mdouble pressure = 30;
     ClosedCSCRestart SC(pressure);
     SC.setTimeMax(2000);
     SC.solve(argc, argv);
     if (SC.getTimeMax()<2000)
         SC.restart();
 }
References DPMBase::getTimeMax(), ClosedCSCRestart::restart(), DPMBase::setTimeMax(), and DPMBase::solve().