MercuryDPM: Eigen::SparseQRMatrixQReturnType< SparseQRType > Struct Template Reference
Eigen::SparseQRMatrixQReturnType< SparseQRType > Struct Template Reference
#include <SparseQR.h>
Public Types
enum { RowsAtCompileTime = Dynamic , ColsAtCompileTime = Dynamic }
typedef SparseQRType::Scalar Scalar
typedef Matrix< Scalar, Dynamic, Dynamic > DenseMatrix
Public Types inherited from Eigen::EigenBase< SparseQRMatrixQReturnType< SparseQRType > >
typedef Eigen::Index Index
The interface type of indices.
typedef internal::traits< SparseQRMatrixQReturnType< SparseQRType > >::StorageKind StorageKind
Public Member Functions
SparseQRMatrixQReturnType (const SparseQRType &qr)
template<typename Derived >
SparseQR_QProduct< SparseQRType, Derived > operator* (const MatrixBase< Derived > &other)
SparseQRMatrixQTransposeReturnType< SparseQRType > adjoint () const
Index rows () const
Index cols () const
SparseQRMatrixQTransposeReturnType< SparseQRType > transpose () const
Public Member Functions inherited from Eigen::EigenBase< SparseQRMatrixQReturnType< SparseQRType > >
constexpr EIGEN_DEVICE_FUNC SparseQRMatrixQReturnType< SparseQRType > & derived ()
constexpr EIGEN_DEVICE_FUNC const SparseQRMatrixQReturnType< SparseQRType > & derived () const
EIGEN_DEVICE_FUNC SparseQRMatrixQReturnType< SparseQRType > & const_cast_derived () const
EIGEN_DEVICE_FUNC const SparseQRMatrixQReturnType< SparseQRType > & const_derived () const
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index rows () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index cols () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index size () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC void evalTo (Dest &dst) const
EIGEN_DEVICE_FUNC void addTo (Dest &dst) const
EIGEN_DEVICE_FUNC void subTo (Dest &dst) const
EIGEN_DEVICE_FUNC void applyThisOnTheRight (Dest &dst) const
EIGEN_DEVICE_FUNC void applyThisOnTheLeft (Dest &dst) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE DeviceWrapper< SparseQRMatrixQReturnType< SparseQRType >, Device > device (Device &device)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE DeviceWrapper< const SparseQRMatrixQReturnType< SparseQRType >, Device > device (Device &device) const
Public Attributes
const SparseQRType & m_qr
Member Typedef Documentation
DenseMatrix
template<typename SparseQRType > typedef Matrix<Scalar, Dynamic, Dynamic> Eigen::SparseQRMatrixQReturnType< SparseQRType >::DenseMatrix
Scalar
template<typename SparseQRType > typedef SparseQRType::Scalar Eigen::SparseQRMatrixQReturnType< SparseQRType >::Scalar
Member Enumeration Documentation
anonymous enum
template<typename SparseQRType > anonymous enum
Enumerator
RowsAtCompileTime
ColsAtCompileTime
 { RowsAtCompileTime = Dynamic, ColsAtCompileTime = Dynamic };
Constructor & Destructor Documentation
SparseQRMatrixQReturnType()
template<typename SparseQRType > Eigen::SparseQRMatrixQReturnType< SparseQRType >::SparseQRMatrixQReturnType (const SparseQRType & qr) inline explicit
 : m_qr(qr) {}
Member Function Documentation
adjoint()
template<typename SparseQRType > SparseQRMatrixQTransposeReturnType<SparseQRType> Eigen::SparseQRMatrixQReturnType< SparseQRType >::adjoint () const inline
{
     return SparseQRMatrixQTransposeReturnType<SparseQRType>(m_qr);
   }
References Eigen::SparseQRMatrixQReturnType< SparseQRType >::m_qr.
cols()
template<typename SparseQRType > Index Eigen::SparseQRMatrixQReturnType< SparseQRType >::cols () const inline
 { return m_qr.rows(); }
References Eigen::SparseQRMatrixQReturnType< SparseQRType >::m_qr.
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), Eigen::internal::Assignment< DstXprType, SparseQRMatrixQReturnType< SparseQRType >, internal::assign_op< typename DstXprType::Scalar, typename DstXprType::Scalar >, Sparse2Sparse >::run(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
operator*()
template<typename SparseQRType > template<typename Derived > SparseQR_QProduct<SparseQRType, Derived> Eigen::SparseQRMatrixQReturnType< SparseQRType >::operator* (const MatrixBase< Derived > & other) inline
{
     return SparseQR_QProduct<SparseQRType, Derived>(m_qr, other.derived(), false);
   }
References Eigen::SparseQRMatrixQReturnType< SparseQRType >::m_qr.
rows()
template<typename SparseQRType > Index Eigen::SparseQRMatrixQReturnType< SparseQRType >::rows () const inline
 { return m_qr.rows(); }
References Eigen::SparseQRMatrixQReturnType< SparseQRType >::m_qr.
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), Eigen::internal::Assignment< DstXprType, SparseQRMatrixQReturnType< SparseQRType >, internal::assign_op< typename DstXprType::Scalar, typename DstXprType::Scalar >, Sparse2Sparse >::run(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
transpose()
template<typename SparseQRType > SparseQRMatrixQTransposeReturnType<SparseQRType> Eigen::SparseQRMatrixQReturnType< SparseQRType >::transpose () const inline
{
     return SparseQRMatrixQTransposeReturnType<SparseQRType>(m_qr);
   }
References Eigen::SparseQRMatrixQReturnType< SparseQRType >::m_qr.
Member Data Documentation
m_qr
template<typename SparseQRType > const SparseQRType& Eigen::SparseQRMatrixQReturnType< SparseQRType >::m_qr
Referenced by Eigen::SparseQRMatrixQReturnType< SparseQRType >::adjoint(), Eigen::SparseQRMatrixQReturnType< SparseQRType >::cols(), Eigen::SparseQRMatrixQReturnType< SparseQRType >::operator*(), Eigen::SparseQRMatrixQReturnType< SparseQRType >::rows(), Eigen::internal::Assignment< DstXprType, SparseQRMatrixQReturnType< SparseQRType >, internal::assign_op< typename DstXprType::Scalar, typename DstXprType::Scalar >, Sparse2Sparse >::run(), Eigen::internal::Assignment< DstXprType, SparseQRMatrixQReturnType< SparseQRType >, internal::assign_op< typename DstXprType::Scalar, typename DstXprType::Scalar >, Sparse2Dense >::run(), and Eigen::SparseQRMatrixQReturnType< SparseQRType >::transpose().
The documentation for this struct was generated from the following file:
SparseQR.h