MercuryDPM: oomph::QElement3FaceToBulkCoordinates Namespace Reference
oomph::QElement3FaceToBulkCoordinates Namespace Reference
Functions
void face0 (const Vector< double > &s, Vector< double > &s_bulk)
The translation scheme for the left face (s0 = -1.0)
void face1 (const Vector< double > &s, Vector< double > &s_bulk)
The translation scheme for the down face (s1 = -1.0)
void face2 (const Vector< double > &s, Vector< double > &s_bulk)
The translation scheme for the back face (s2 = -1.0)
void face3 (const Vector< double > &s, Vector< double > &s_bulk)
The translation scheme for the right face (s0 = 1.0)
void face4 (const Vector< double > &s, Vector< double > &s_bulk)
The translation scheme for the up face (s1 = 1.0)
void face5 (const Vector< double > &s, Vector< double > &s_bulk)
The translation scheme for the front face (s2 = 1.0)
Detailed Description
Namespace for the functions that translate local face coordinates to the coordinates in the bulk element
Function Documentation
face0()
void oomph::QElement3FaceToBulkCoordinates::face0 (const Vector< double > & s, Vector< double > & s_bulk)
The translation scheme for the left face (s0 = -1.0)
     {
       s_bulk[0] = -1.0;
       s_bulk[1] = s[0];
       s_bulk[2] = s[1];
     }
References s.
Referenced by oomph::QSpectralElement< 3, NNODE_1D >::build_face_element(), and oomph::QElement< 3, NNODE_1D >::face_to_bulk_coordinate_fct_pt().
face1()
void oomph::QElement3FaceToBulkCoordinates::face1 (const Vector< double > & s, Vector< double > & s_bulk)
The translation scheme for the down face (s1 = -1.0)
     {
       s_bulk[0] = s[0];
       s_bulk[1] = -1.0;
       s_bulk[2] = s[1];
     }
References s.
Referenced by oomph::QSpectralElement< 3, NNODE_1D >::build_face_element(), and oomph::QElement< 3, NNODE_1D >::face_to_bulk_coordinate_fct_pt().
face2()
void oomph::QElement3FaceToBulkCoordinates::face2 (const Vector< double > & s, Vector< double > & s_bulk)
The translation scheme for the back face (s2 = -1.0)
     {
       s_bulk[0] = s[0];
       s_bulk[1] = s[1];
       s_bulk[2] = -1.0;
     }
References s.
Referenced by oomph::QSpectralElement< 3, NNODE_1D >::build_face_element(), and oomph::QElement< 3, NNODE_1D >::face_to_bulk_coordinate_fct_pt().
face3()
void oomph::QElement3FaceToBulkCoordinates::face3 (const Vector< double > & s, Vector< double > & s_bulk)
The translation scheme for the right face (s0 = 1.0)
     {
       s_bulk[0] = 1.0;
       s_bulk[1] = s[0];
       s_bulk[2] = s[1];
     }
References s.
Referenced by oomph::QSpectralElement< 3, NNODE_1D >::build_face_element(), and oomph::QElement< 3, NNODE_1D >::face_to_bulk_coordinate_fct_pt().
face4()
void oomph::QElement3FaceToBulkCoordinates::face4 (const Vector< double > & s, Vector< double > & s_bulk)
The translation scheme for the up face (s1 = 1.0)
     {
       s_bulk[0] = s[0];
       s_bulk[1] = 1.0;
       s_bulk[2] = s[1];
     }
References s.
Referenced by oomph::QSpectralElement< 3, NNODE_1D >::build_face_element(), and oomph::QElement< 3, NNODE_1D >::face_to_bulk_coordinate_fct_pt().
face5()
void oomph::QElement3FaceToBulkCoordinates::face5 (const Vector< double > & s, Vector< double > & s_bulk)
The translation scheme for the front face (s2 = 1.0)
     {
       s_bulk[0] = s[0];
       s_bulk[1] = s[1];
       s_bulk[2] = 1.0;
     }
References s.
Referenced by oomph::QSpectralElement< 3, NNODE_1D >::build_face_element(), and oomph::QElement< 3, NNODE_1D >::face_to_bulk_coordinate_fct_pt().