MercuryDPM: VTKCollection Class Reference
VTKCollection Class Reference
#include <VTKData.h>
Public Member Functions
VTKCollection (std::string fileName)
~VTKCollection ()
operator bool () const
void append (std::string filename)
Private Member Functions
void writeHeader ()
void writeFooter ()
Private Attributes
std::ofstream outFile_
bool hasHeader_
bool hasFooter_
std::size_t recordID_
Constructor & Destructor Documentation
VTKCollection()
VTKCollection::VTKCollection (std::string fileName) inline
     : outFile_(fileName), hasHeader_(false), hasFooter_(false), recordID_(0)
   {
   }
~VTKCollection()
VTKCollection::~VTKCollection () inline
   {
     if (hasHeader_ && !hasFooter_)
       writeFooter();
   }
References hasFooter_, hasHeader_, and writeFooter().
Member Function Documentation
append()
void VTKCollection::append (std::string filename) inline
   {
     if (!hasHeader_)
       writeHeader();
     outFile_ <<
       "<DataSet group=\"\" part=\"0\" timestep=\"" << recordID_ << "\" file=\"" << filename << "\" />\n";
     recordID_++;
   }
References MergeRestartFiles::filename, hasHeader_, outFile_, recordID_, and writeHeader().
Referenced by transformMercuryToVTK().
operator bool()
VTKCollection::operator bool () const inline
   {
     return outFile_.good();
   }
References outFile_.
writeFooter()
void VTKCollection::writeFooter () inline private
  {
    outFile_ <<
      " </Collection>\n"
      "</VTKFile>\n";
    hasFooter_ = true;
  }
References hasFooter_, and outFile_.
Referenced by ~VTKCollection().
writeHeader()
void VTKCollection::writeHeader () inline private
  {
    outFile_ <<
      "<?xml version=\"1.0\"?>\n"
      "<VTKFile type=\"Collection\" version=\"0.1\" byte_order=\"LittleEndian\">\n"
      " <Collection>\n";
    hasHeader_ = true;
  }
References hasHeader_, and outFile_.
Referenced by append().
Member Data Documentation
hasFooter_
bool VTKCollection::hasFooter_ private
Referenced by writeFooter(), and ~VTKCollection().
hasHeader_
bool VTKCollection::hasHeader_ private
Referenced by append(), writeHeader(), and ~VTKCollection().
outFile_
std::ofstream VTKCollection::outFile_ private
Referenced by append(), operator bool(), writeFooter(), and writeHeader().
recordID_
std::size_t VTKCollection::recordID_ private
Referenced by append().
The documentation for this class was generated from the following file:
Tools/VTKData.h