MercuryDPM: refineable_b_convection.cc File Reference
mpi/multi_domain/boussinesq_convection/refineable_b_convection.cc File Reference
#include "generic.h"
#include "advection_diffusion.h"
#include "navier_stokes.h"
#include "multi_physics.h"
#include "meshes/rectangular_quadmesh.h"
Classes
class RefineableConvectionProblem< NST_ELEMENT, AD_ELEMENT >
Namespaces
Global_Physical_Variables
Global variables.
Functions
int main (int argc, char **argv)
Variables
Vector< double > Global_Physical_Variables::Direction_of_gravity (2)
Gravity vector.
Function Documentation
main()
int main (int argc , char ** argv)
Driver code for 2D Boussinesq convection problem with adaptivity.
 {
 #ifdef OOMPH_HAS_MPI
  MPI_Helpers::init(argc,argv);
 #endif
  // Store command line arguments
  CommandLineArgs::setup(argc,argv);
  // Set the direction of gravity
  Global_Physical_Variables::Direction_of_gravity[0] = 0.0;
  Global_Physical_Variables::Direction_of_gravity[1] = -1.0;
  // Create the problem with 2D nine-node refineable elements.
  RefineableConvectionProblem<
   RefineableBuoyantQCrouzeixRaviartElement<2> > problem;
  // Apply a perturbation to the upper boundary condition to
  // force the solution into the symmetry-broken state.
  problem.enable_imperfection();
 #ifdef OOMPH_HAS_MPI
  bool report_stats=true;
  // Are there command-line arguments?
  if (CommandLineArgs::Argc==1)
   {
    // No arguments, so distribute without reference to partition vector
    problem.distribute(report_stats);
   }
  else
   {
    // Command line argument(s), so read in partition vector from file
    unsigned n_element=problem.mesh_pt()->nelement();
    Vector<unsigned> in_element_partition(n_element);
    std::ifstream input_file;
    char filename[100];
    sprintf(filename,"refineable_b_convection_partition.dat");
    input_file.open(filename);
    std::string input_string;
    for (unsigned e=0;e<n_element;e++)
     {
      getline(input_file,input_string,'\n');
      in_element_partition[e]=atoi(input_string.c_str());
     }
    // Distribute the problem
    problem.distribute(in_element_partition,report_stats);
   }
 #endif
  //Solve the problem with (up to) two levels of adaptation
  problem.newton_solve(2);
  //Document the solution
  problem.doc_solution();
  // Make the boundary conditions perfect and solve again.
  // Now the slightly perturbed symmetry broken state computed
  // above is used as the initial condition and the Newton solver
  // converges to the symmetry broken solution, even without
  // the perturbation
  problem.disable_imperfection();
  problem.newton_solve(2);
  problem.doc_solution();
 #ifdef OOMPH_HAS_MPI
  MPI_Helpers::finalize();
 #endif
 } // end of main
References oomph::CommandLineArgs::Argc, Global_Physical_Variables::Direction_of_gravity, e(), MergeRestartFiles::filename, problem, Flag_definition::setup(), and oomph::Global_string_for_annotation::string().