MercuryDPM: Eigen::internal::product_transpose_helper< Lhs, Rhs, Option, TransposeProductEnum::MatrixPermutation > Struct Template Reference
Eigen::internal::product_transpose_helper< Lhs, Rhs, Option, TransposeProductEnum::MatrixPermutation > Struct Template Reference
#include <Product.h>
Public Types
using Derived = Product< Lhs, Rhs, Option >
using LhsScalar = typename traits< Lhs >::Scalar
using LhsTransposeType = typename DenseBase< Lhs >::ConstTransposeReturnType
using LhsConjugateTransposeType = CwiseUnaryOp< scalar_conjugate_op< LhsScalar >, LhsTransposeType >
using LhsAdjointType = std::conditional_t< NumTraits< LhsScalar >::IsComplex, LhsConjugateTransposeType, LhsTransposeType >
using RhsInverseType = typename PermutationBase< Rhs >::InverseReturnType
using TransposeType = Product< RhsInverseType, LhsTransposeType, Option >
using AdjointType = Product< RhsInverseType, LhsAdjointType, Option >
Static Public Member Functions
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TransposeType run_transpose (const Derived &derived)
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE AdjointType run_adjoint (const Derived &derived)
Member Typedef Documentation
AdjointType
template<typename Lhs , typename Rhs , int Option> using Eigen::internal::product_transpose_helper< Lhs, Rhs, Option, TransposeProductEnum::MatrixPermutation >::AdjointType = Product<RhsInverseType, LhsAdjointType, Option>
Derived
template<typename Lhs , typename Rhs , int Option> using Eigen::internal::product_transpose_helper< Lhs, Rhs, Option, TransposeProductEnum::MatrixPermutation >::Derived = Product<Lhs, Rhs, Option>
LhsAdjointType
template<typename Lhs , typename Rhs , int Option> using Eigen::internal::product_transpose_helper< Lhs, Rhs, Option, TransposeProductEnum::MatrixPermutation >::LhsAdjointType = std::conditional_t<NumTraits<LhsScalar>::IsComplex, LhsConjugateTransposeType, LhsTransposeType>
LhsConjugateTransposeType
template<typename Lhs , typename Rhs , int Option> using Eigen::internal::product_transpose_helper< Lhs, Rhs, Option, TransposeProductEnum::MatrixPermutation >::LhsConjugateTransposeType = CwiseUnaryOp<scalar_conjugate_op<LhsScalar>, LhsTransposeType>
LhsScalar
template<typename Lhs , typename Rhs , int Option> using Eigen::internal::product_transpose_helper< Lhs, Rhs, Option, TransposeProductEnum::MatrixPermutation >::LhsScalar = typename traits<Lhs>::Scalar
LhsTransposeType
template<typename Lhs , typename Rhs , int Option> using Eigen::internal::product_transpose_helper< Lhs, Rhs, Option, TransposeProductEnum::MatrixPermutation >::LhsTransposeType = typename DenseBase<Lhs>::ConstTransposeReturnType
RhsInverseType
template<typename Lhs , typename Rhs , int Option> using Eigen::internal::product_transpose_helper< Lhs, Rhs, Option, TransposeProductEnum::MatrixPermutation >::RhsInverseType = typename PermutationBase<Rhs>::InverseReturnType
TransposeType
template<typename Lhs , typename Rhs , int Option> using Eigen::internal::product_transpose_helper< Lhs, Rhs, Option, TransposeProductEnum::MatrixPermutation >::TransposeType = Product<RhsInverseType, LhsTransposeType, Option>
Member Function Documentation
run_adjoint()
template<typename Lhs , typename Rhs , int Option> static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE AdjointType Eigen::internal::product_transpose_helper< Lhs, Rhs, Option, TransposeProductEnum::MatrixPermutation >::run_adjoint (const Derived & derived) inline static
{
     return AdjointType(RhsInverseType(derived.rhs()), LhsAdjointType(LhsTransposeType(derived.lhs())));
   }
References Eigen::Product< Lhs_, Rhs_, Option >::lhs(), and Eigen::Product< Lhs_, Rhs_, Option >::rhs().
run_transpose()
template<typename Lhs , typename Rhs , int Option> static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TransposeType Eigen::internal::product_transpose_helper< Lhs, Rhs, Option, TransposeProductEnum::MatrixPermutation >::run_transpose (const Derived & derived) inline static
{
     return TransposeType(RhsInverseType(derived.rhs()), LhsTransposeType(derived.lhs()));
   }
References Eigen::Product< Lhs_, Rhs_, Option >::lhs(), and Eigen::Product< Lhs_, Rhs_, Option >::rhs().
The documentation for this struct was generated from the following file:
Product.h