MercuryDPM: Eigen::internal::DenseStorage_impl< T, Size, Rows, Cols, Options > Class Template Reference
Eigen::internal::DenseStorage_impl< T, Size, Rows, Cols, Options > Class Template Reference
#include <DenseStorage.h>
Public Member Functions
EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE DenseStorage_impl ()=default
EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE DenseStorage_impl (const DenseStorage_impl &)=default
EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE DenseStorage_impl (Index, Index, Index)
EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE DenseStorage_impl & operator= (const DenseStorage_impl &)=default
EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE void swap (DenseStorage_impl &other)
EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE void conservativeResize (Index, Index, Index)
EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE void resize (Index, Index, Index)
EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE Index rows () const
EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE Index cols () const
EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE Index size () const
EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE T * data ()
EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE const T * data () const
Private Attributes
plain_array< T, Size, Options > m_data
Constructor & Destructor Documentation
DenseStorage_impl() [1/3]
template<typename T , int Size, int Rows, int Cols, int Options> EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE Eigen::internal::DenseStorage_impl< T, Size, Rows, Cols, Options >::DenseStorage_impl () constexpr default
DenseStorage_impl() [2/3]
template<typename T , int Size, int Rows, int Cols, int Options> EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE Eigen::internal::DenseStorage_impl< T, Size, Rows, Cols, Options >::DenseStorage_impl (const DenseStorage_impl< T, Size, Rows, Cols, Options > &) constexpr default
References EIGEN_INTERNAL_DENSE_STORAGE_CTOR_PLUGIN, and size.
DenseStorage_impl() [3/3]
template<typename T , int Size, int Rows, int Cols, int Options> EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE Eigen::internal::DenseStorage_impl< T, Size, Rows, Cols, Options >::DenseStorage_impl (Index , Index , Index) inline constexpr
 {}
Member Function Documentation
cols()
template<typename T , int Size, int Rows, int Cols, int Options> EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE Index Eigen::internal::DenseStorage_impl< T, Size, Rows, Cols, Options >::cols () const inline constexpr
 { return Cols; }
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), Eigen::PlainObjectBase< Derived >::coeffRef(), Eigen::PlainObjectBase< Derived >::cols(), Eigen::internal::DenseStorage_impl< T, Dynamic, Dynamic, Cols, Options >::operator=(), Eigen::internal::DenseStorage_impl< T, Dynamic, Rows, Dynamic, Options >::operator=(), Eigen::internal::DenseStorage_impl< T, Dynamic, Dynamic, Dynamic, Options >::operator=(), Eigen::PlainObjectBase< Derived >::packet(), gdb.printers.EigenMatrixPrinter::to_string(), gdb.printers.EigenSparseMatrixPrinter::to_string(), and Eigen::PlainObjectBase< Derived >::writePacket().
conservativeResize()
template<typename T , int Size, int Rows, int Cols, int Options> EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE void Eigen::internal::DenseStorage_impl< T, Size, Rows, Cols, Options >::conservativeResize (Index , Index , Index) inline constexpr
                                                                                    {}
data() [1/2]
template<typename T , int Size, int Rows, int Cols, int Options> EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE T* Eigen::internal::DenseStorage_impl< T, Size, Rows, Cols, Options >::data () inline constexpr
 { return m_data.array; }
Referenced by Eigen::PlainObjectBase< Derived >::_init1(), Eigen::PlainObjectBase< Derived >::_init2(), Eigen::Array< Scalar_, Rows_, Cols_, Options_, MaxRows_, MaxCols_ >::Array(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenQuaternionPrinter::children(), Eigen::PlainObjectBase< Derived >::coeff(), Eigen::PlainObjectBase< Derived >::coeffRef(), Eigen::PlainObjectBase< Derived >::data(), Eigen::Matrix< Scalar_, Rows_, Cols_, Options_, MaxRows_, MaxCols_ >::Matrix(), Eigen::PlainObjectBase< Derived >::packet(), Eigen::PlainObjectBase< Derived >::PlainObjectBase(), gdb.printers.EigenMatrixPrinter::to_string(), gdb.printers.EigenSparseMatrixPrinter::to_string(), gdb.printers.EigenQuaternionPrinter::to_string(), and Eigen::PlainObjectBase< Derived >::writePacket().
data() [2/2]
template<typename T , int Size, int Rows, int Cols, int Options> EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE const T* Eigen::internal::DenseStorage_impl< T, Size, Rows, Cols, Options >::data () const inline constexpr
 { return m_data.array; }
Referenced by gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenQuaternionPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), gdb.printers.EigenSparseMatrixPrinter::to_string(), and gdb.printers.EigenQuaternionPrinter::to_string().
operator=()
template<typename T , int Size, int Rows, int Cols, int Options> EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE DenseStorage_impl& Eigen::internal::DenseStorage_impl< T, Size, Rows, Cols, Options >::operator= (const DenseStorage_impl< T, Size, Rows, Cols, Options > &) constexpr default
resize()
template<typename T , int Size, int Rows, int Cols, int Options> EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE void Eigen::internal::DenseStorage_impl< T, Size, Rows, Cols, Options >::resize (Index , Index , Index) inline constexpr
 {}
Referenced by Eigen::PlainObjectBase< Derived >::resize().
rows()
template<typename T , int Size, int Rows, int Cols, int Options> EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE Index Eigen::internal::DenseStorage_impl< T, Size, Rows, Cols, Options >::rows () const inline constexpr
 { return Rows; }
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), Eigen::PlainObjectBase< Derived >::coeffRef(), Eigen::internal::DenseStorage_impl< T, Dynamic, Dynamic, Cols, Options >::operator=(), Eigen::internal::DenseStorage_impl< T, Dynamic, Rows, Dynamic, Options >::operator=(), Eigen::internal::DenseStorage_impl< T, Dynamic, Dynamic, Dynamic, Options >::operator=(), Eigen::PlainObjectBase< Derived >::packet(), Eigen::PlainObjectBase< Derived >::rows(), gdb.printers.EigenMatrixPrinter::to_string(), gdb.printers.EigenSparseMatrixPrinter::to_string(), and Eigen::PlainObjectBase< Derived >::writePacket().
size()
template<typename T , int Size, int Rows, int Cols, int Options> EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE Index Eigen::internal::DenseStorage_impl< T, Size, Rows, Cols, Options >::size () const inline constexpr
 { return Rows * Cols; }
Referenced by Eigen::internal::DenseStorage_impl< T, Size, Dynamic, Cols, Options >::DenseStorage_impl(), Eigen::internal::DenseStorage_impl< T, Size, Rows, Dynamic, Options >::DenseStorage_impl(), Eigen::internal::DenseStorage_impl< T, Size, Dynamic, Dynamic, Options >::DenseStorage_impl(), Eigen::internal::DenseStorage_impl< T, Dynamic, Dynamic, Cols, Options >::DenseStorage_impl(), Eigen::internal::DenseStorage_impl< T, Dynamic, Rows, Dynamic, Options >::DenseStorage_impl(), Eigen::internal::DenseStorage_impl< T, Dynamic, Dynamic, Dynamic, Options >::DenseStorage_impl(), Eigen::internal::DenseStorage_impl< T, Size, Dynamic, Cols, Options >::operator=(), Eigen::internal::DenseStorage_impl< T, Size, Rows, Dynamic, Options >::operator=(), Eigen::internal::DenseStorage_impl< T, Size, Dynamic, Dynamic, Options >::operator=(), Eigen::internal::DenseStorage_impl< T, Dynamic, Dynamic, Cols, Options >::operator=(), Eigen::internal::DenseStorage_impl< T, Dynamic, Rows, Dynamic, Options >::operator=(), Eigen::internal::DenseStorage_impl< T, Dynamic, Dynamic, Dynamic, Options >::operator=(), Eigen::PlainObjectBase< Derived >::PlainObjectBase(), Eigen::internal::DenseStorage_impl< T, Size, Dynamic, Cols, Options >::swap(), Eigen::internal::DenseStorage_impl< T, Size, Rows, Dynamic, Options >::swap(), and Eigen::internal::DenseStorage_impl< T, Size, Dynamic, Dynamic, Options >::swap().
swap()
template<typename T , int Size, int Rows, int Cols, int Options> EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE void Eigen::internal::DenseStorage_impl< T, Size, Rows, Cols, Options >::swap (DenseStorage_impl< T, Size, Rows, Cols, Options > & other) inline constexpr
{
     numext::swap(m_data, other.m_data);
   }
References Eigen::internal::DenseStorage_impl< T, Size, Rows, Cols, Options >::m_data, and Eigen::numext::swap().
Referenced by Eigen::internal::matrix_swap_impl< MatrixTypeA, MatrixTypeB, true >::run().
Member Data Documentation
m_data
template<typename T , int Size, int Rows, int Cols, int Options> plain_array<T, Size, Options> Eigen::internal::DenseStorage_impl< T, Size, Rows, Cols, Options >::m_data private
Referenced by Eigen::internal::DenseStorage_impl< T, Size, Dynamic, Cols, Options >::DenseStorage_impl(), Eigen::internal::DenseStorage_impl< T, Size, Rows, Dynamic, Options >::DenseStorage_impl(), Eigen::internal::DenseStorage_impl< T, Size, Dynamic, Dynamic, Options >::DenseStorage_impl(), Eigen::internal::DenseStorage_impl< T, Dynamic, Dynamic, Cols, Options >::DenseStorage_impl(), Eigen::internal::DenseStorage_impl< T, Dynamic, Rows, Dynamic, Options >::DenseStorage_impl(), Eigen::internal::DenseStorage_impl< T, Dynamic, Dynamic, Dynamic, Options >::DenseStorage_impl(), Eigen::internal::DenseStorage_impl< T, Size, Dynamic, Cols, Options >::operator=(), Eigen::internal::DenseStorage_impl< T, Size, Rows, Dynamic, Options >::operator=(), Eigen::internal::DenseStorage_impl< T, Size, Dynamic, Dynamic, Options >::operator=(), Eigen::internal::DenseStorage_impl< T, Dynamic, Dynamic, Cols, Options >::operator=(), Eigen::internal::DenseStorage_impl< T, Dynamic, Rows, Dynamic, Options >::operator=(), Eigen::internal::DenseStorage_impl< T, Dynamic, Dynamic, Dynamic, Options >::operator=(), Eigen::internal::DenseStorage_impl< T, Size, Rows, Cols, Options >::swap(), Eigen::internal::DenseStorage_impl< T, Size, Dynamic, Cols, Options >::swap(), Eigen::internal::DenseStorage_impl< T, Size, Rows, Dynamic, Options >::swap(), and Eigen::internal::DenseStorage_impl< T, Size, Dynamic, Dynamic, Options >::swap().
The documentation for this class was generated from the following file:
DenseStorage.h