MercuryDPM: oomph::MatrixBasedLumpedPreconditioner< MATRIX > Class Template Reference
oomph::MatrixBasedLumpedPreconditioner< MATRIX > Class Template Reference
Matrix-based lumped preconditioner.
#include <general_purpose_preconditioners.h>
Public Member Functions
MatrixBasedLumpedPreconditioner ()
Constructor.
~MatrixBasedLumpedPreconditioner ()
Destructor.
MatrixBasedLumpedPreconditioner (const MatrixBasedDiagPreconditioner &)=delete
Broken copy constructor.
void operator= (const MatrixBasedLumpedPreconditioner &)=delete
Broken assignment operator.
void preconditioner_solve (const DoubleVector &r, DoubleVector &z)
Apply preconditioner to z, i.e. z=D^-1.
void setup ()
bool positive_matrix () const
double * inverse_lumped_vector_pt ()
unsigned & nrow ()
Access function to number of rows for this preconditioner.
void clean_up_memory ()
clean up memory - just delete the inverse lumped vector
void setup ()
Setup the lumped preconditioner. Specialisation for CCDoubleMatrix.
void setup ()
Setup the lumped preconditioner. Specialisation for CRDoubleMatrix.
void setup (DoubleMatrixBase *matrix_pt)
void setup (const Problem *problem_pt, DoubleMatrixBase *matrix_pt)
virtual void setup ()=0
Public Member Functions inherited from oomph::Preconditioner
Preconditioner ()
Constructor.
Preconditioner (const Preconditioner &)=delete
Broken copy constructor.
void operator= (const Preconditioner &)=delete
Broken assignment operator.
virtual ~Preconditioner ()
Destructor (empty)
virtual void preconditioner_solve_transpose (const DoubleVector &r, DoubleVector &z)
void setup (DoubleMatrixBase *matrix_pt)
void setup (const Problem *problem_pt, DoubleMatrixBase *matrix_pt)
void enable_silent_preconditioner_setup ()
Set up the block preconditioner quietly!
void disable_silent_preconditioner_setup ()
Be verbose in the block preconditioner setup.
virtual DoubleMatrixBase * matrix_pt () const
Get function for matrix pointer.
virtual void set_matrix_pt (DoubleMatrixBase *matrix_pt)
Set the matrix pointer.
virtual const OomphCommunicator * comm_pt () const
Get function for comm pointer.
virtual void set_comm_pt (const OomphCommunicator *const comm_pt)
Set the communicator pointer.
double setup_time () const
Returns the time to setup the preconditioner.
virtual void turn_into_subsidiary_block_preconditioner (BlockPreconditioner< CRDoubleMatrix > *master_block_prec_pt, const Vector< unsigned > &doftype_in_master_preconditioner_coarse)
virtual void turn_into_subsidiary_block_preconditioner (BlockPreconditioner< CRDoubleMatrix > *master_block_prec_pt, const Vector< unsigned > &doftype_in_master_preconditioner_coarse, const Vector< Vector< unsigned >> &doftype_coarsen_map_coarse)
Public Member Functions inherited from oomph::DistributableLinearAlgebraObject
DistributableLinearAlgebraObject ()
Default constructor - create a distribution.
DistributableLinearAlgebraObject (const DistributableLinearAlgebraObject &matrix)=delete
Broken copy constructor.
void operator= (const DistributableLinearAlgebraObject &)=delete
Broken assignment operator.
virtual ~DistributableLinearAlgebraObject ()
Destructor.
LinearAlgebraDistribution * distribution_pt () const
access to the LinearAlgebraDistribution
unsigned nrow () const
access function to the number of global rows.
unsigned nrow_local () const
access function for the num of local rows on this processor.
unsigned nrow_local (const unsigned &p) const
access function for the num of local rows on this processor.
unsigned first_row () const
access function for the first row on this processor
unsigned first_row (const unsigned &p) const
access function for the first row on this processor
bool distributed () const
distribution is serial or distributed
bool distribution_built () const
void build_distribution (const LinearAlgebraDistribution *const dist_pt)
void build_distribution (const LinearAlgebraDistribution &dist)
Private Attributes
double * Inv_lumped_diag_pt
Vector of inverse diagonal entries.
bool Positive_matrix
unsigned Nrow
Additional Inherited Members
Protected Member Functions inherited from oomph::DistributableLinearAlgebraObject
void clear_distribution ()
Protected Attributes inherited from oomph::Preconditioner
bool Silent_preconditioner_setup
Boolean to indicate whether or not the build should be done silently.
std::ostream * Stream_pt
Pointer to the output stream – defaults to std::cout.
Detailed Description
template<typename MATRIX>
class oomph::MatrixBasedLumpedPreconditioner< MATRIX >
Matrix-based lumped preconditioner.
Constructor & Destructor Documentation
MatrixBasedLumpedPreconditioner() [1/2]
template<typename MATRIX > oomph::MatrixBasedLumpedPreconditioner< MATRIX >::MatrixBasedLumpedPreconditioner () inline
Constructor.
     {
       // default the positive matrix boolean to false
       Positive_matrix = false;
       // set the pointers to the lumped vector to 0
       Inv_lumped_diag_pt = 0;
     };
References oomph::MatrixBasedLumpedPreconditioner< MATRIX >::Inv_lumped_diag_pt, and oomph::MatrixBasedLumpedPreconditioner< MATRIX >::Positive_matrix.
~MatrixBasedLumpedPreconditioner()
template<typename MATRIX > oomph::MatrixBasedLumpedPreconditioner< MATRIX >::~MatrixBasedLumpedPreconditioner () inline
Destructor.
     {
       this->clean_up_memory();
     }
References oomph::MatrixBasedLumpedPreconditioner< MATRIX >::clean_up_memory().
MatrixBasedLumpedPreconditioner() [2/2]
template<typename MATRIX > oomph::MatrixBasedLumpedPreconditioner< MATRIX >::MatrixBasedLumpedPreconditioner (const MatrixBasedDiagPreconditioner &) delete
Broken copy constructor.
Member Function Documentation
clean_up_memory()
template<typename MATRIX > void oomph::MatrixBasedLumpedPreconditioner< MATRIX >::clean_up_memory () inline virtual
clean up memory - just delete the inverse lumped vector
Reimplemented from oomph::Preconditioner.
     {
       delete[] Inv_lumped_diag_pt;
     }
References oomph::MatrixBasedLumpedPreconditioner< MATRIX >::Inv_lumped_diag_pt.
Referenced by oomph::MatrixBasedLumpedPreconditioner< MATRIX >::~MatrixBasedLumpedPreconditioner().
inverse_lumped_vector_pt()
template<typename MATRIX > double* oomph::MatrixBasedLumpedPreconditioner< MATRIX >::inverse_lumped_vector_pt () inline
Access function to the inverse of the lumped vector assembled in the preconditioner setup routine
paranoid check that vector has been created
     {
 #ifdef PARANOID
       if (Inv_lumped_diag_pt == 0)
       {
         throw OomphLibError("The inverse lumped vector has not been created. "
                             "Created in setup(...)",
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
 #endif
       return Inv_lumped_diag_pt;
     }
References oomph::MatrixBasedLumpedPreconditioner< MATRIX >::Inv_lumped_diag_pt, OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
nrow()
template<typename MATRIX > unsigned& oomph::MatrixBasedLumpedPreconditioner< MATRIX >::nrow () inline
Access function to number of rows for this preconditioner.
     {
       return Nrow;
     }
References oomph::MatrixBasedLumpedPreconditioner< MATRIX >::Nrow.
operator=()
template<typename MATRIX > void oomph::MatrixBasedLumpedPreconditioner< MATRIX >::operator= (const MatrixBasedLumpedPreconditioner< MATRIX > &) delete
Broken assignment operator.
positive_matrix()
template<typename MATRIX > bool oomph::MatrixBasedLumpedPreconditioner< MATRIX >::positive_matrix () const inline
Access function to the Positive_matrix which indicates whether lumped matrix was positive
paranoid check that preconditioner has been setup
     {
 #ifdef PARANOID
       if (Inv_lumped_diag_pt == 0)
       {
         throw OomphLibError("The preconditioner has not been setup.",
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
 #endif
       return Positive_matrix;
     }
References oomph::MatrixBasedLumpedPreconditioner< MATRIX >::Inv_lumped_diag_pt, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and oomph::MatrixBasedLumpedPreconditioner< MATRIX >::Positive_matrix.
preconditioner_solve()
template<typename MATRIX > void oomph::MatrixBasedLumpedPreconditioner< MATRIX >::preconditioner_solve (const DoubleVector & r, DoubleVector & z) virtual
Apply preconditioner to z, i.e. z=D^-1.
Apply preconditioner: Multiply r by the inverse of the lumped matrix.
Implements oomph::Preconditioner.
   {
 #ifdef PARANOID
     if (*r.distribution_pt() != *this->distribution_pt())
     {
       std::ostringstream error_message_stream;
       error_message_stream
         << "The r vector must have teh same distribution as the "
            "preconditioner. "
         << "(this is the same as the matrix passed to setup())";
       throw OomphLibError(error_message_stream.str(),
                           OOMPH_CURRENT_FUNCTION,
                           OOMPH_EXCEPTION_LOCATION);
     }
     if (z.built())
     {
       if (*z.distribution_pt() != *this->distribution_pt())
       {
         std::ostringstream error_message_stream;
         error_message_stream
           << "The z vector distribution has been setup; it must have the "
           << "same distribution as the r vector (and preconditioner).";
         throw OomphLibError(error_message_stream.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
     }
 #endif
     z.build(r.distribution_pt(), 0.0);
     for (unsigned i = 0; i < Nrow; i++)
     {
       z[i] = Inv_lumped_diag_pt[i] * r[i];
     }
   }
References oomph::DoubleVector::build(), oomph::DoubleVector::built(), oomph::DistributableLinearAlgebraObject::distribution_pt(), i, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and UniformPSDSelfTest::r.
setup() [1/6]
void oomph::MatrixBasedLumpedPreconditioner< CCDoubleMatrix >::setup () virtual
Setup the lumped preconditioner. Specialisation for CCDoubleMatrix.
Implements oomph::Preconditioner.
   {
     // # of rows in the matrix
     Nrow = matrix_pt()->nrow();
     // Create the vector for the inverse lumped
     if (Inv_lumped_diag_pt != 0)
     {
       delete[] this->Inv_lumped_diag_pt;
     }
     Inv_lumped_diag_pt = new double[this->Nrow];
     // zero the vector
     for (unsigned i = 0; i < Nrow; i++)
     {
       Inv_lumped_diag_pt[i] = 0.0;
     }
     // cast the Double Base Matrix to Compressed Column Double Matrix
     CCDoubleMatrix* cc_matrix_pt = dynamic_cast<CCDoubleMatrix*>(matrix_pt());
     // get the matrix
     int* m_row_index = cc_matrix_pt->row_index();
     double* m_value = cc_matrix_pt->value();
     unsigned m_nnz = cc_matrix_pt->nnz();
     // intially set positive matrix to true
     Positive_matrix = true;
     // lump the matrix
     for (unsigned i = 0; i < m_nnz; i++)
     {
       // if the matrix contains negative coefficient the matrix not positive
       if (m_value[i] < 0.0)
       {
         Positive_matrix = false;
       }
       // computed lumped matrix - temporarily stored in Inv_lumped_diag_pt
       Inv_lumped_diag_pt[m_row_index[i]] += m_value[i];
     }
     // invert the lumped matrix
     for (unsigned i = 0; i < Nrow; i++)
     {
       Inv_lumped_diag_pt[i] = 1.0 / Inv_lumped_diag_pt[i];
     }
     // create the distribution
     LinearAlgebraDistribution dist(comm_pt(), Nrow, false);
     this->build_distribution(dist);
   }
References i, oomph::SparseMatrix< T, MATRIX_TYPE >::nnz(), oomph::CCMatrix< T >::row_index(), and oomph::SparseMatrix< T, MATRIX_TYPE >::value().
setup() [2/6]
void oomph::MatrixBasedLumpedPreconditioner< CRDoubleMatrix >::setup () virtual
Setup the lumped preconditioner. Specialisation for CRDoubleMatrix.
Implements oomph::Preconditioner.
   {
     // first attempt to cast to CRDoubleMatrix
     CRDoubleMatrix* cr_matrix_pt = dynamic_cast<CRDoubleMatrix*>(matrix_pt());
     // # of rows in the matrix
     Nrow = cr_matrix_pt->nrow_local();
     // Create the vector for the inverse lumped
     if (Inv_lumped_diag_pt != 0)
     {
       delete[] this->Inv_lumped_diag_pt;
     }
     Inv_lumped_diag_pt = new double[this->Nrow];
     // zero the vector
     for (unsigned i = 0; i < Nrow; i++)
     {
       Inv_lumped_diag_pt[i] = 0.0;
     }
     // get the matrix
     int* m_row_start = cr_matrix_pt->row_start();
     double* m_value = cr_matrix_pt->value();
     // intially set positive matrix to true
     Positive_matrix = true;
     // lump and invert matrix
     for (unsigned i = 0; i < Nrow; i++)
     {
       Inv_lumped_diag_pt[i] = 0.0;
       for (int j = m_row_start[i]; j < m_row_start[i + 1]; j++)
       {
         // if the matrix contains negative coefficient the matrix not positive
         if (m_value[j] < 0.0)
         {
           Positive_matrix = false;
         }
         // computed lumped coef (i,i)- temporarily stored in Inv_lumped_diag_pt
         Inv_lumped_diag_pt[i] += m_value[j];
       }
       // invert coef (i,i)
       Inv_lumped_diag_pt[i] = 1.0 / Inv_lumped_diag_pt[i];
     }
     // store the distribution
     this->build_distribution(cr_matrix_pt->distribution_pt());
   }
References oomph::DistributableLinearAlgebraObject::distribution_pt(), i, j, oomph::DistributableLinearAlgebraObject::nrow_local(), oomph::CRDoubleMatrix::row_start(), and oomph::CRDoubleMatrix::value().
setup() [3/6]
template<typename MATRIX > void oomph::MatrixBasedLumpedPreconditioner< MATRIX >::setup () virtual
Setup the preconditioner (store diagonal) from the fully assembled matrix. Problem pointer is ignored.
Implements oomph::Preconditioner.
setup() [4/6]
template<typename MATRIX > virtual void oomph::Preconditioner::setup virtual
For some reason we need to remind the compiler that there is also a function named setup in the base class.
Implements oomph::Preconditioner.
setup() [5/6]
template<typename MATRIX > void oomph::Preconditioner::setup inline virtual
For some reason we need to remind the compiler that there is also a function named setup in the base class.
Implements oomph::Preconditioner.
     {
       ObsoleteCode::obsolete();
       setup(matrix_pt);
     }
setup() [6/6]
template<typename MATRIX > void oomph::Preconditioner::setup inline virtual
For some reason we need to remind the compiler that there is also a function named setup in the base class.
Implements oomph::Preconditioner.
     {
       // Store matrix pointer
       set_matrix_pt(matrix_pt);
       // Extract and store communicator pointer
       DistributableLinearAlgebraObject* dist_obj_pt =
         dynamic_cast<DistributableLinearAlgebraObject*>(matrix_pt);
       if (dist_obj_pt != 0)
       {
         set_comm_pt(dist_obj_pt->distribution_pt()->communicator_pt());
       }
       else
       {
         set_comm_pt(0);
       }
       double setup_time_start = TimingHelpers::timer();
       setup();
       double setup_time_finish = TimingHelpers::timer();
       Setup_time = setup_time_finish - setup_time_start;
     }
Member Data Documentation
Inv_lumped_diag_pt
template<typename MATRIX > double* oomph::MatrixBasedLumpedPreconditioner< MATRIX >::Inv_lumped_diag_pt private
Vector of inverse diagonal entries.
Referenced by oomph::MatrixBasedLumpedPreconditioner< MATRIX >::clean_up_memory(), oomph::MatrixBasedLumpedPreconditioner< MATRIX >::inverse_lumped_vector_pt(), oomph::MatrixBasedLumpedPreconditioner< MATRIX >::MatrixBasedLumpedPreconditioner(), and oomph::MatrixBasedLumpedPreconditioner< MATRIX >::positive_matrix().
Nrow
template<typename MATRIX > unsigned oomph::MatrixBasedLumpedPreconditioner< MATRIX >::Nrow private
Referenced by oomph::MatrixBasedLumpedPreconditioner< MATRIX >::nrow().
Positive_matrix
template<typename MATRIX > bool oomph::MatrixBasedLumpedPreconditioner< MATRIX >::Positive_matrix private
Referenced by oomph::MatrixBasedLumpedPreconditioner< MATRIX >::MatrixBasedLumpedPreconditioner(), and oomph::MatrixBasedLumpedPreconditioner< MATRIX >::positive_matrix().
The documentation for this class was generated from the following files:
general_purpose_preconditioners.h
general_purpose_preconditioners.cc