MercuryDPM: lmder_functor Struct Reference
lmder_functor Struct Reference
Public Member Functions
lmder_functor (void)
int operator() (const VectorXd &x, VectorXd &fvec) const
int df (const VectorXd &x, MatrixXd &fjac) const
lmder_functor (void)
int operator() (const VectorXd &x, VectorXd &fvec) const
int df (const VectorXd &x, MatrixXd &fjac) const
Public Member Functions inherited from Eigen::DenseFunctor< double >
DenseFunctor ()
DenseFunctor (int inputs, int values)
int inputs () const
int values () const
Public Member Functions inherited from Functor< double >
Functor ()
Functor (int inputs, int values)
Functor ()
Functor (int inputs_, int values_)
int inputs () const
int inputs () const
int values () const
int values () const
Additional Inherited Members
Public Types inherited from Eigen::DenseFunctor< double >
enum
typedef double Scalar
typedef Matrix< Scalar, InputsAtCompileTime, 1 > InputType
typedef Matrix< Scalar, ValuesAtCompileTime, 1 > ValueType
typedef Matrix< Scalar, ValuesAtCompileTime, InputsAtCompileTime > JacobianType
typedef ColPivHouseholderQR< JacobianType > QRSolver
Public Types inherited from Functor< double >
enum
enum
typedef double Scalar
typedef double Scalar
typedef Matrix< Scalar, InputsAtCompileTime, 1 > InputType
typedef Matrix< Scalar, InputsAtCompileTime, 1 > InputType
typedef Matrix< Scalar, ValuesAtCompileTime, 1 > ValueType
typedef Matrix< Scalar, ValuesAtCompileTime, 1 > ValueType
typedef Matrix< Scalar, ValuesAtCompileTime, InputsAtCompileTime > JacobianType
typedef Matrix< Scalar, ValuesAtCompileTime, InputsAtCompileTime > JacobianType
Public Attributes inherited from Eigen::DenseFunctor< double >
const int m_inputs
const int m_values
Public Attributes inherited from Functor< double >
const int m_inputs
int m_inputs
const int m_values
int m_values
Constructor & Destructor Documentation
lmder_functor() [1/2]
lmder_functor::lmder_functor (void) inline
 : DenseFunctor<double>(3, 15) {}
lmder_functor() [2/2]
lmder_functor::lmder_functor (void) inline
 : Functor<double>(3, 15) {}
Member Function Documentation
df() [1/2]
int lmder_functor::df (const VectorXd & x, MatrixXd & fjac) const inline
{
     double tmp1, tmp2, tmp3, tmp4;
     for (int i = 0; i < values(); i++) {
       tmp1 = i + 1;
       tmp2 = 16 - i - 1;
       tmp3 = (i >= 8) ? tmp2 : tmp1;
       tmp4 = (x[1] * tmp2 + x[2] * tmp3);
       tmp4 = tmp4 * tmp4;
       fjac(i, 0) = -1;
       fjac(i, 1) = tmp1 * tmp2 / tmp4;
       fjac(i, 2) = tmp1 * tmp3 / tmp4;
     }
     return 0;
   }
References i, Eigen::DenseFunctor< double >::values(), and plotDoE::x.
df() [2/2]
int lmder_functor::df (const VectorXd & x, MatrixXd & fjac) const inline
{
     double tmp1, tmp2, tmp3, tmp4;
     for (int i = 0; i < values(); i++) {
       tmp1 = i + 1;
       tmp2 = 16 - i - 1;
       tmp3 = (i >= 8) ? tmp2 : tmp1;
       tmp4 = (x[1] * tmp2 + x[2] * tmp3);
       tmp4 = tmp4 * tmp4;
       fjac(i, 0) = -1;
       fjac(i, 1) = tmp1 * tmp2 / tmp4;
       fjac(i, 2) = tmp1 * tmp3 / tmp4;
     }
     return 0;
   }
References i, Eigen::DenseFunctor< double >::values(), and plotDoE::x.
operator()() [1/2]
int lmder_functor::operator() (const VectorXd & x, VectorXd & fvec) const inline
{
     double tmp1, tmp2, tmp3;
     static const double y[15] = {1.4e-1, 1.8e-1, 2.2e-1, 2.5e-1, 2.9e-1, 3.2e-1, 3.5e-1, 3.9e-1,
                                  3.7e-1, 5.8e-1, 7.3e-1, 9.6e-1, 1.34,   2.1,    4.39};
     for (int i = 0; i < values(); i++) {
       tmp1 = i + 1;
       tmp2 = 16 - i - 1;
       tmp3 = (i >= 8) ? tmp2 : tmp1;
       fvec[i] = y[i] - (x[0] + tmp1 / (x[1] * tmp2 + x[2] * tmp3));
     }
     return 0;
   }
References i, Eigen::DenseFunctor< double >::values(), plotDoE::x, and y.
operator()() [2/2]
int lmder_functor::operator() (const VectorXd & x, VectorXd & fvec) const inline
{
     double tmp1, tmp2, tmp3;
     static const double y[15] = {1.4e-1, 1.8e-1, 2.2e-1, 2.5e-1, 2.9e-1, 3.2e-1, 3.5e-1, 3.9e-1,
                                  3.7e-1, 5.8e-1, 7.3e-1, 9.6e-1, 1.34,   2.1,    4.39};
     for (int i = 0; i < values(); i++) {
       tmp1 = i + 1;
       tmp2 = 16 - i - 1;
       tmp3 = (i >= 8) ? tmp2 : tmp1;
       fvec[i] = y[i] - (x[0] + tmp1 / (x[1] * tmp2 + x[2] * tmp3));
     }
     return 0;
   }
References i, Eigen::DenseFunctor< double >::values(), plotDoE::x, and y.
The documentation for this struct was generated from the following files:
levenberg_marquardt.cpp
NonLinearOptimization.cpp