MercuryDPM: Eigen::internal::CwiseUnaryViewImpl< ViewOp, MatrixType, StrideType, Dense, false > Class Template Reference
Eigen::internal::CwiseUnaryViewImpl< ViewOp, MatrixType, StrideType, Dense, false > Class Template Reference
#include <CwiseUnaryView.h>
Public Types
typedef CwiseUnaryView< ViewOp, MatrixType, StrideType > Derived
typedef dense_xpr_base< CwiseUnaryView< ViewOp, MatrixType, StrideType > >::type Base
Public Member Functions
EIGEN_DEVICE_FUNC const Scalar * data () const
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index innerStride () const
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index outerStride () const
Protected Member Functions
EIGEN_DEVICE_FUNC const Scalar & coeffRef (Index index) const
EIGEN_DEVICE_FUNC const Scalar & coeffRef (Index row, Index col) const
Member Typedef Documentation
Base
template<typename ViewOp , typename MatrixType , typename StrideType > typedef dense_xpr_base<CwiseUnaryView<ViewOp, MatrixType, StrideType> >::type Eigen::internal::CwiseUnaryViewImpl< ViewOp, MatrixType, StrideType, Dense, false >::Base
Derived
template<typename ViewOp , typename MatrixType , typename StrideType > typedef CwiseUnaryView<ViewOp, MatrixType, StrideType> Eigen::internal::CwiseUnaryViewImpl< ViewOp, MatrixType, StrideType, Dense, false >::Derived
Member Function Documentation
coeffRef() [1/2]
template<typename ViewOp , typename MatrixType , typename StrideType > EIGEN_DEVICE_FUNC const Scalar& Eigen::internal::CwiseUnaryViewImpl< ViewOp, MatrixType, StrideType, Dense, false >::coeffRef (Index index) const inline protected
{
     return internal::evaluator<Derived>(derived()).coeffRef(index);
   }
coeffRef() [2/2]
template<typename ViewOp , typename MatrixType , typename StrideType > EIGEN_DEVICE_FUNC const Scalar& Eigen::internal::CwiseUnaryViewImpl< ViewOp, MatrixType, StrideType, Dense, false >::coeffRef (Index row, Index col) const inline protected
{
     return internal::evaluator<Derived>(derived()).coeffRef(row, col);
   }
References col(), and row().
data()
template<typename ViewOp , typename MatrixType , typename StrideType > EIGEN_DEVICE_FUNC const Scalar* Eigen::internal::CwiseUnaryViewImpl< ViewOp, MatrixType, StrideType, Dense, false >::data () const inline
 { return &(this->coeffRef(0)); }
Referenced by gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenQuaternionPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), gdb.printers.EigenSparseMatrixPrinter::to_string(), and gdb.printers.EigenQuaternionPrinter::to_string().
innerStride()
template<typename ViewOp , typename MatrixType , typename StrideType > EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index Eigen::internal::CwiseUnaryViewImpl< ViewOp, MatrixType, StrideType, Dense, false >::innerStride () const inline
{
     return StrideType::InnerStrideAtCompileTime != 0 ? int(StrideType::InnerStrideAtCompileTime)
                                                      : derived().nestedExpression().innerStride() *
                                                            sizeof(typename traits<MatrixType>::Scalar) / sizeof(Scalar);
   }
References int().
outerStride()
template<typename ViewOp , typename MatrixType , typename StrideType > EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index Eigen::internal::CwiseUnaryViewImpl< ViewOp, MatrixType, StrideType, Dense, false >::outerStride () const inline
{
     return StrideType::OuterStrideAtCompileTime != 0 ? int(StrideType::OuterStrideAtCompileTime)
                                                      : derived().nestedExpression().outerStride() *
                                                            sizeof(typename traits<MatrixType>::Scalar) / sizeof(Scalar);
   }
References int().
The documentation for this class was generated from the following file:
CwiseUnaryView.h