MercuryDPM: oomph::Spine Class Reference
oomph::Spine Class Reference
#include <spines.h>
Public Member Functions
Spine ()
Spine (const double &height)
Spine (const double &height, const Vector< Data * > &geom_data_pt)
Spine (const double &height, const Vector< Data * > &geom_data_pt, const Vector< GeomObject * > &geom_object_pt)
~Spine ()
double & height ()
Access function to spine height.
Data *& spine_height_pt ()
Access function to Data object that stores the spine height.
Data * spine_height_pt () const
unsigned ngeom_data ()
void set_geom_data_pt (const Vector< Data * > &geom_data_pt)
void add_geom_data_pt (Data *geom_data_pt)
Data *& geom_data_pt (const unsigned &i)
Data * geom_data_pt (const unsigned &i) const
Vector< Data * > & vector_geom_data_pt ()
Return the vector of geometric data.
unsigned ngeom_object ()
void set_geom_object_pt (const Vector< GeomObject * > &geom_object_pt)
void add_geom_object_pt (GeomObject *geom_object_pt)
GeomObject *& geom_object_pt (const unsigned &i)
GeomObject * geom_object_pt (const unsigned &i) const
Vector< GeomObject * > & vector_geom_object_pt ()
unsigned ngeom_parameter ()
void set_geom_parameter (const Vector< double > &geom_parameter)
void add_geom_parameter (const double &geom_parameter)
double & geom_parameter (const unsigned &i)
const double & geom_parameter (const unsigned &i) const
Private Attributes
Vector< Data * > Geom_data_pt
Data that stores the spine height.
Vector< GeomObject * > Geom_object_pt
Vector< double > Geom_parameter
Vector that stores doubles that are used in the geometric updates.
Detailed Description
Spines are used for algebraic node update operations in free-surface fluid problems: They form the back-bones along which nodes in a a free-surface mesh are located. Typically, the free surface is located at the "end" of the spine; the nodes in the interior of the mesh are located at fixed fractions along the spine. The key Data member of the Spine object is its "height" – usually an unknown in the problem – which is used by the SpineNode's node update function to update the SpineNode's position.
In more complex problems (such as the case where a fluid layer is deposited on an elastic body), the node update function can depend on additional information, such as the GeomObject representation of the elastic body, and additional Data objects wich specify the position on the GeomObject from which the Spine emanates. The Spine class therefore provides storage for pointers to GeomObjects and storage for any additional geometric Data that may be required during node update operations.
Constructor & Destructor Documentation
Spine() [1/4]
oomph::Spine::Spine () inline
Default constructor: Create the Spine and initialise its height to zero.
     {
       Geom_data_pt.resize(1);
       // Create Data for height. By default it's free
       Geom_data_pt[0] = new Data(1);
     }
References Geom_data_pt.
Spine() [2/4]
oomph::Spine::Spine (const double & height) inline
Constructor: Create the Spine and initialise its height to the specified value
     {
       Geom_data_pt.resize(1);
       // Create Data for height. By default it's free
       Geom_data_pt[0] = new Data(1);
       // Set value
       Geom_data_pt[0]->set_value(0, height);
     }
References Geom_data_pt, and height().
Spine() [3/4]
oomph::Spine::Spine (const double & height, const Vector< Data * > & geom_data_pt) inline
Constructor: Create the Spine and initialise its height to the specified value. Store the vector of (pointers to) the additional geometric Data that is required during the node update operation for this Spine.
     {
       // Find the number of geometric data passed
       const unsigned n_geom_data = geom_data_pt.size();
       // Now allocate enough storage for the spine height and additional
       // geometric data
       Geom_data_pt.resize(n_geom_data + 1);
       // Create Data for height. By default it's free
       Geom_data_pt[0] = new Data(1);
       // Set value
       Geom_data_pt[0]->set_value(0, height);
       // Add the additional geometric data
       for (unsigned i = 0; i < n_geom_data; i++)
       {
         Geom_data_pt[i + 1] = geom_data_pt[i];
       }
     }
References geom_data_pt(), Geom_data_pt, height(), and i.
Spine() [4/4]
oomph::Spine::Spine (const double & height, const Vector< Data * > & geom_data_pt, const Vector< GeomObject * > & geom_object_pt) inline
Constructor: Create the Spine and initialise its height to the specified value. Store the vector of (pointers to) the additional geometric Data that is required during the node update operation; also store vector of (pointers to) GeomObjects that is required during the node update operation for this Spine
       : Geom_object_pt(geom_object_pt)
     {
       // Find the number of geometric data passed
       const unsigned n_geom_data = geom_data_pt.size();
       // Now allocate enough storage for the spine height and additional
       // geometric data
       Geom_data_pt.resize(n_geom_data + 1);
       // Create Data for height. By default it's free
       Geom_data_pt[0] = new Data(1);
       // Set value
       Geom_data_pt[0]->set_value(0, height);
       // Add the additional geometric data
       for (unsigned i = 0; i < n_geom_data; i++)
       {
         Geom_data_pt[i + 1] = geom_data_pt[i];
       }
     }
References geom_data_pt(), Geom_data_pt, height(), and i.
~Spine()
oomph::Spine::~Spine () inline
Destructor: Wipe Data object that stores the Spine height. All other objects (geometric Data and geometric objects) were created outside the Spine and must be deleted there.
     {
       // Kill spine height
       delete Geom_data_pt[0];
     }
References Geom_data_pt.
Member Function Documentation
add_geom_data_pt()
void oomph::Spine::add_geom_data_pt (Data * geom_data_pt) inline
Add (pointer to) geometric Data that is involved in the node update operations for this Spine
     {
       Geom_data_pt.push_back(geom_data_pt);
     }
References geom_data_pt(), and Geom_data_pt.
add_geom_object_pt()
void oomph::Spine::add_geom_object_pt (GeomObject * geom_object_pt) inline
Add (pointer to) geometric object that is involved in the node update operations for this Spine
     {
       Geom_object_pt.push_back(geom_object_pt);
     }
References geom_object_pt(), and Geom_object_pt.
add_geom_parameter()
void oomph::Spine::add_geom_parameter (const double & geom_parameter) inline
Add geometric parameter involved in the node update operations for this Spine
     {
       Geom_parameter.push_back(geom_parameter);
     }
References geom_parameter(), and Geom_parameter.
Referenced by oomph::AnnularSpineMesh< ELEMENT >::AnnularSpineMesh().
geom_data_pt() [1/2]
Data*& oomph::Spine::geom_data_pt (const unsigned & i) inline
Return i-th geometric Data that is involved in the node update operations for this Spine
     {
       return Geom_data_pt[i];
     }
References Geom_data_pt, and i.
Referenced by add_geom_data_pt(), oomph::SpineNode::all_geom_data_pt(), set_geom_data_pt(), and Spine().
geom_data_pt() [2/2]
Data* oomph::Spine::geom_data_pt (const unsigned & i) const inline
Return i-th geometric Data that is involved in the node update operations for this Spine. Const version
     {
       return Geom_data_pt[i];
     }
References Geom_data_pt, and i.
geom_object_pt() [1/2]
GeomObject*& oomph::Spine::geom_object_pt (const unsigned & i) inline
Return i-th geometric object that is involved in the node update operations for this Spine
     {
       return Geom_object_pt[i];
     }
References Geom_object_pt, and i.
Referenced by add_geom_object_pt(), oomph::SpineNode::all_geom_object_pt(), No_Slip::no_slip_condition_first(), No_Slip::no_slip_condition_second(), set_geom_object_pt(), SimpleSpineMesh< ELEMENT >::spine_node_update(), oomph::ChannelSpineMesh< ELEMENT >::spine_node_update(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_channel(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_film_lower(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_film_upper(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_horizontal_transition_lower(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_horizontal_transition_upper(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_vertical_transition_lower(), and oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_vertical_transition_upper().
geom_object_pt() [2/2]
GeomObject* oomph::Spine::geom_object_pt (const unsigned & i) const inline
Return i-th geometric object that is involved in the node update operations for this Spine. Const version
     {
       return Geom_object_pt[i];
     }
References Geom_object_pt, and i.
geom_parameter() [1/2]
double& oomph::Spine::geom_parameter (const unsigned & i) inline
Return i-th geometric parameter that is involved in the node update operations for this Spine
     {
       return Geom_parameter[i];
     }
References Geom_parameter, and i.
Referenced by add_geom_parameter(), CombCanSpineMesh< ELEMENT, INTERFACE_ELEMENT >::build_single_layer_mesh(), CombTipSpineMesh< ELEMENT, INTERFACE_ELEMENT >::build_single_layer_mesh(), ThreeDimBethertonProblem< ELEMENT >::multiply_aspect_ratio(), No_Slip::no_slip_condition_first(), No_Slip::no_slip_condition_second(), CombCanSpineMesh< ELEMENT, INTERFACE_ELEMENT >::rotate_90(), CombTipSpineMesh< ELEMENT, INTERFACE_ELEMENT >::rotate_90_zeq1_xeq0(), CombTipSpineMesh< ELEMENT, INTERFACE_ELEMENT >::rotate_90_zeq1_yeq0(), set_geom_parameter(), oomph::AnnularSpineMesh< ELEMENT >::spine_node_update(), SimpleSpineMesh< ELEMENT >::spine_node_update(), MyCanyonMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update(), CombCanSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update(), CombTipSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update(), STSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update(), MyTipMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update(), oomph::ChannelSpineMesh< ELEMENT >::spine_node_update(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_channel(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_film_lower(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_film_upper(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_horizontal_transition_lower(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_horizontal_transition_upper(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_vertical_transition_lower(), and oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_vertical_transition_upper().
geom_parameter() [2/2]
const double& oomph::Spine::geom_parameter (const unsigned & i) const inline
Return i-th geometric parameter that is involved in the node update operations for this Spine. Const version
     {
       return Geom_parameter[i];
     }
References Geom_parameter, and i.
height()
double& oomph::Spine::height () inline
Access function to spine height.
     {
       return *(Geom_data_pt[0]->value_pt(0));
     }
References Geom_data_pt.
Referenced by oomph::ChannelSpineMesh< ELEMENT >::build_channel_spine_mesh(), MeltSpinningProblem< ELEMENT >::deform_free_surface(), AxisymFreeSurfaceNozzleAdvDiffRobinProblem< ELEMENT >::deform_free_surface(), InterfaceProblem< ELEMENT, TIMESTEPPER >::deform_free_surface(), oomph::SpineNode::h(), oomph::BrethertonSpineMesh< ELEMENT, SpineLineFluidInterfaceElement< ELEMENT > >::initial_element_reorder(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::reposition_spines(), Spine(), SimpleSpineMesh< ELEMENT >::spine_node_update(), oomph::TwoLayerPerturbedSpineMesh< ELEMENT >::spine_node_update_lower(), oomph::TwoLayerPerturbedSpineMesh< ELEMENT >::spine_node_update_upper(), and ThreeDimBethertonProblem< ELEMENT >::ThreeDimBethertonProblem().
ngeom_data()
unsigned oomph::Spine::ngeom_data () inline
Number of geometric Data that is involved in the node update operations for this Spine
     {
       return Geom_data_pt.size();
     }
References Geom_data_pt.
Referenced by oomph::SpineNode::ngeom_data().
ngeom_object()
unsigned oomph::Spine::ngeom_object () inline
Number of geometric objects that is involved in the node update operations for this Spine
     {
       return Geom_object_pt.size();
     }
References Geom_object_pt.
Referenced by oomph::SpineNode::ngeom_object().
ngeom_parameter()
unsigned oomph::Spine::ngeom_parameter () inline
Number of geometric parameters that are involved in the node update operations for this Spine
     {
       return Geom_parameter.size();
     }
References Geom_parameter.
Referenced by oomph::AnnularSpineMesh< ELEMENT >::AnnularSpineMesh().
set_geom_data_pt()
void oomph::Spine::set_geom_data_pt (const Vector< Data * > & geom_data_pt) inline
Set vector of (pointers to) geometric Data that is involved in the node update operations for this Spine. Wipes any previously existing geometric Data.
     {
       unsigned n_geom_data = geom_data_pt.size();
       Geom_data_pt.resize(n_geom_data + 1);
       for (unsigned i = 1; i < n_geom_data; i++)
       {
         Geom_data_pt[i + 1] = geom_data_pt[i];
       }
     }
References geom_data_pt(), Geom_data_pt, and i.
set_geom_object_pt()
void oomph::Spine::set_geom_object_pt (const Vector< GeomObject * > & geom_object_pt) inline
Set vector of (pointers to) geometric objects that is involved in the node update operations for this Spine
     {
       unsigned n_geom_object = geom_object_pt.size();
       Geom_object_pt.resize(n_geom_object);
       for (unsigned i = 0; i < n_geom_object; i++)
       {
         Geom_object_pt[i] = geom_object_pt[i];
       }
     }
References geom_object_pt(), Geom_object_pt, and i.
Referenced by oomph::ChannelSpineMesh< ELEMENT >::build_channel_spine_mesh(), oomph::BrethertonSpineMesh< ELEMENT, SpineLineFluidInterfaceElement< ELEMENT > >::initial_element_reorder(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::reposition_spines(), and SimpleSpineMesh< ELEMENT >::SimpleSpineMesh().
set_geom_parameter()
void oomph::Spine::set_geom_parameter (const Vector< double > & geom_parameter) inline
Set vector of geometric parameters that are involved in the node update operations for this Spine. Wipes any previously existing geometric parameters
     {
       Geom_parameter = geom_parameter;
     }
References geom_parameter(), and Geom_parameter.
Referenced by oomph::ChannelSpineMesh< ELEMENT >::build_channel_spine_mesh(), MyCanyonMesh< ELEMENT, INTERFACE_ELEMENT >::build_single_layer_mesh(), MyTipMesh< ELEMENT, INTERFACE_ELEMENT >::build_single_layer_mesh(), oomph::BrethertonSpineMesh< ELEMENT, SpineLineFluidInterfaceElement< ELEMENT > >::initial_element_reorder(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::reposition_spines(), and SimpleSpineMesh< ELEMENT >::SimpleSpineMesh().
spine_height_pt() [1/2]
Data*& oomph::Spine::spine_height_pt () inline
Access function to Data object that stores the spine height.
     {
       return Geom_data_pt[0];
     }
References Geom_data_pt.
Referenced by oomph::ChannelSpineMesh< ELEMENT >::build_channel_spine_mesh(), oomph::SpineElement< ELEMENT >::complete_setup_of_dependencies(), oomph::SpineMesh::dump(), oomph::Hijacked< ELEMENT >::hijack_nodal_spine_value(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::pin_all_spines(), and oomph::SpineMesh::read().
spine_height_pt() [2/2]
Data* oomph::Spine::spine_height_pt () const inline
Access function to Data object that stores the spine height (const version)
     {
       return Geom_data_pt[0];
     }
References Geom_data_pt.
vector_geom_data_pt()
Vector<Data*>& oomph::Spine::vector_geom_data_pt () inline
Return the vector of geometric data.
     {
       return Geom_data_pt;
     }
References Geom_data_pt.
vector_geom_object_pt()
Vector<GeomObject*>& oomph::Spine::vector_geom_object_pt () inline
Return the vector of all geometric objects that affect this spine
     {
       return Geom_object_pt;
     }
References Geom_object_pt.
Member Data Documentation
Geom_data_pt
Vector<Data*> oomph::Spine::Geom_data_pt private
Data that stores the spine height.
Vector that stores the pointers to additional geometric Data
Referenced by add_geom_data_pt(), geom_data_pt(), height(), ngeom_data(), set_geom_data_pt(), Spine(), spine_height_pt(), vector_geom_data_pt(), and ~Spine().
Geom_object_pt
Vector<GeomObject*> oomph::Spine::Geom_object_pt private
Vector that stores the pointers to geometric objects that is involved in the node update operation
Referenced by add_geom_object_pt(), geom_object_pt(), ngeom_object(), set_geom_object_pt(), and vector_geom_object_pt().
Geom_parameter
Vector<double> oomph::Spine::Geom_parameter private
Vector that stores doubles that are used in the geometric updates.
Referenced by add_geom_parameter(), geom_parameter(), ngeom_parameter(), and set_geom_parameter().
The documentation for this class was generated from the following file:
spines.h