MercuryDPM: Interaction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction > Class Template Reference
Interaction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction > Class Template Reference
Contains information about the contact between two interactables, BaseInteraction::P_ and BaseInteraction::I_;.
#include <Interaction.h>
Public Member Functions
Interaction (BaseInteractable *P, BaseInteractable *I, unsigned timeStamp)
The default constructor.
Interaction ()
Empty constructor.
Interaction (const Interaction &p)
The default copy constructor.
virtual ~Interaction ()
The default destructor.
Interaction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction > * copy () const final
Creates a copy of this Interaction.
void computeForce () final
Computes the normal, tangential, and adhesive forces.
void computeInteraction ()
Computes the interaction parameters based on the forces and torques.
void read (std::istream &is) final
Read Interaction properties from a file.
void write (std::ostream &os) const final
Writes Interaction properties to a file.
std::string getName () const final
Returns the name of the Interaction.
Mdouble getElasticEnergy () const final
Returns the elastic energy stored in the Interaction.
void integrate (Mdouble timeStep) final
Integrates the time-dependent parameters of the contact force.
void reverseHistory () final
Reverses the parameters of the contact force.
void rotateHistory (Matrix3D &rotationMatrix) final
When periodic particles are used, some interactions need certain history properties rotated (e.g. tangential springs). This is the function for that.
void actionsAfterTimeStep ()
Mdouble getElasticEnergyAtEquilibrium (Mdouble adhesiveForce) const
returns the overlap at which the repulsive elastic force equals a given adhesive force; to be implemented in the normal force
void getMPIInteraction (void *historyDataArray, unsigned int index) const final
copies the history interactions into the data array
void setMPIInteraction (void *historyDataArray, unsigned int index, const bool resetPointers) final
void getInteractionDetails (void *interactionDataArray, unsigned int index, unsigned int &identificationP, unsigned int &identificationI, bool &isWallInteraction, unsigned &timeStamp)
void createMPIType () final
void * createMPIInteractionDataArray (unsigned int numberOfInteractions) const final
void deleteMPIInteractionDataArray (void *dataArray) final
Public Member Functions inherited from EmptyFrictionInteraction
EmptyFrictionInteraction (BaseInteractable *P, BaseInteractable *I, unsigned timeStamp)
Constructor.
EmptyFrictionInteraction ()
EmptyFrictionInteraction (const EmptyFrictionInteraction &p)
Copy constructor.
~EmptyFrictionInteraction () override
Destructor.
void computeFrictionForce ()
Computes nothing, it is an empty function.
void computeFrictionInteraction ()
const EmptyFrictionSpecies * getSpecies () const
Returns a const pointer of type EmptyFrictionSpecies*.
std::string getBaseName () const
Returns interaction name/type.
Mdouble getTangentialOverlap () const override
Returns zero overlap.
const Vec3D getTangentialForce () const override
Returns zero tangential force.
Public Member Functions inherited from BaseInteraction
BaseInteraction (BaseInteractable *P, BaseInteractable *I, unsigned timeStamp)
A constructor takes the BaseInteractable objects which are interacting (come into contact) and time the interaction starts.
BaseInteraction ()
BaseInteraction (const BaseInteraction &p)
Copy constructor.
~BaseInteraction () override
The destructor. It removes this interactions from the objects that were interacting, and writes the time to a file when needed.
virtual void actionsOnErase ()
If an interaction needs to do something before it gets erased, add it here. E.g. Liquid bridges rupture at the end of their lifetime, and the liquid bridge volume has to be redistributed. The reason this action is not done in the destructor is that this action should not be taken when erasing ghost interactions.
void writeToFStat (std::ostream &os, Mdouble time) const
Writes forces data to the FStat file.
void setDistance (Mdouble distance)
Sets the interaction distance between the two interacting objects.
void setNormal (Vec3D normal)
Sets the normal vector between the two interacting objects.
void setOverlap (Mdouble overlap)
Set the overlap between the two interacting object.
void setContactPoint (Vec3D contactPoint)
Set the location of the contact point between the two interacting objects.
void setTimeStamp (unsigned timeStamp)
Updates the time step of the interacting. Note, time steps used to find completed interactions.
void setSpecies (const BaseSpecies *species)
Set the Species of the interaction; note this can either be a Species or MixedSpecies.
void setP (BaseInteractable *P)
Sets the first object involved in the interaction (normally a particle).
void setI (BaseInteractable *I)
Sets the second object involved in the interaction (often particle or wall).
void importP (BaseInteractable *P)
Sets the first object involved in the interaction (normally a particle).
void importI (BaseInteractable *I)
Sets the second object involved in the interaction (often particle or wall).
Vec3D getIP () const
Vec3D getIC () const
Vec3D getCP () const
void setLagrangeMultiplier (Mdouble multiplier)
Mdouble getLagrangeMultiplier ()
void setHandler (InteractionHandler *handler)
Sets the pointer to the interaction hander which is storing this interaction.
InteractionHandler * getHandler () const
Gets a point to the interaction handlers to which this interaction belongs.
const Vec3D & getForce () const
Gets the current force (vector) between the two interacting objects.
const Vec3D & getTorque () const
Gets the current torque (vector) between the two interacting objects.
const Vec3D & getNormal () const
Gets the normal vector between the two interacting objects.
const Vec3D & getContactPoint () const
Gets constant reference to contact point (vector).
Mdouble getOverlap () const
Returns a Mdouble with the current overlap between the two interacting objects.
Mdouble getOverlapVolume () const
Returns the overlap volume between two interacting objects.
Mdouble getContactRadius () const
Returns a Mdouble with the current contact between the two interacting objects.
void removeFromHandler ()
Removes this interaction from its interaction hander.
void copySwitchPointer (const BaseInteractable *original, BaseInteractable *ghost) const
This copies the interactions of the original particle and replaces the original with the ghost copy.
void gatherContactStatistics ()
BaseInteractable * getP ()
Returns a pointer to first object involved in the interaction (normally a particle).
BaseInteractable * getI ()
Returns a pointer to the second object involved in the interaction (often a wall or a particle).
const BaseInteractable * getP () const
Returns a constant pointer to the first object involved in the interaction.
const BaseInteractable * getI () const
Returns a constant pointer to the second object involved in the interaction.
Mdouble getTimeStamp () const
Returns an Mdouble which is the time stamp of the interaction.
Mdouble getDistance () const
Returns an Mdouble which is the norm (length) of distance vector.
const Vec3D & getRelativeVelocity () const
Returns a constant reference to a vector of relative velocity.
Mdouble getNormalRelativeVelocity () const
Returns a double which is the norm (length) of the relative velocity vector.
Mdouble getAbsoluteNormalForce () const
Returns the absolute value of the norm (length) of the Normal force vector.
void setFStatData (std::fstream &fstat, BaseParticle *P, BaseWall *I)
void setFStatData (std::fstream &fstat, BaseParticle *P, BaseParticle *I)
unsigned int getMultiContactIdentifier () const
void setMultiContactIdentifier (unsigned int multiContactIdentifier_)
virtual unsigned getNumberOfFieldsVTK () const
virtual std::string getTypeVTK (unsigned i) const
virtual std::string getNameVTK (unsigned i) const
virtual std::vector< Mdouble > getFieldVTK (unsigned i) const
void addForce (Vec3D force)
add an force increment to the total force.
void addTorque (Vec3D torque)
add a torque increment to the total torque.
void setForce (Vec3D force)
set total force (this is used by the normal force, tangential forces are added use addForce)
void setTorque (Vec3D torque)
set the total force (this is used by the normal force, tangential torques are added use addTorque)
const BaseSpecies * getBaseSpecies () const
Return a constant point to BaseSpecies of the interaction.
void setBasicMPIInteractionValues (int P, int I, unsigned timeStamp, Vec3D force, Vec3D torque, bool isWallInteraction, bool resetPointers)
void setIdentificationP (unsigned int identification)
void setIdentificationI (int identification)
void setWallInteraction (bool flag)
unsigned int getIdentificationP ()
int getIdentificationI ()
bool isWallInteraction ()
virtual bool isBonded () const
Public Member Functions inherited from BaseObject
BaseObject ()=default
Default constructor.
BaseObject (const BaseObject &p)=default
Copy constructor, copies all the objects BaseObject contains.
virtual ~BaseObject ()=default
virtual destructor
virtual void moveInHandler (unsigned int index)
Except that it is virtual, it does the same thing as setIndex() does.
void setIndex (unsigned int index)
Allows one to assign an index to an object in the handler/container.
void setId (unsigned long id)
Assigns a unique identifier to each object in the handler (container) which remains constant even after the object is deleted from the container/handler.
unsigned int getIndex () const
Returns the index of the object in the handler.
unsigned int getId () const
Returns the unique identifier of any particular object.
void setGroupId (unsigned groupId)
unsigned getGroupId () const
Public Member Functions inherited from EmptyAdhesiveInteraction
EmptyAdhesiveInteraction (BaseInteractable *P, BaseInteractable *I, unsigned timeStamp)
Constructor.
EmptyAdhesiveInteraction ()
EmptyAdhesiveInteraction (const EmptyAdhesiveInteraction &p)
copy constructor.
~EmptyAdhesiveInteraction () override
Destructor.
void computeAdhesionForce ()
Computes nothing as it is an Empty Adhesive interaction.
void computeAdhesionInteraction ()
const EmptyAdhesiveSpecies * getSpecies () const
Returns a pointer to the adhesive force species EmptyAdhesiveSpecies.
std::string getBaseName () const
Returns the name of the interaction, see Interaction.h.
Additional Inherited Members
Public Types inherited from EmptyFrictionInteraction
typedef EmptyFrictionSpecies SpeciesType
An alias name for EmptyFrictionSpecies.
Public Types inherited from EmptyAdhesiveInteraction
typedef EmptyAdhesiveSpecies SpeciesType
An alias name for EmptyAdhesiveSpecies data type.
Protected Member Functions inherited from BaseInteraction
Mdouble getEffectiveRadius () const
Returns a Mdouble to the effective radius of the interaction. (Not corrected for the overlap)
Mdouble getEffectiveMass () const
Returns a Mdouble to the effective radius of the interaction. (Not corrected for the overlap)
void setRelativeVelocity (Vec3D relativeVelocity)
set the relative velocity of the current of the interactions.
void setNormalRelativeVelocity (Mdouble normalRelativeVelocit)
set the normal component of the relative velocity.
void setAbsoluteNormalForce (Mdouble absoluteNormalForce)
the absolute values of the norm (length) of the normal force
void writeInteraction (std::ostream &os, bool created) const
Writes information about a interaction to the interaction file.
Detailed Description
template<class NormalForceInteraction, class FrictionForceInteraction = EmptyFrictionInteraction, class AdhesiveForceInteraction = EmptyAdhesiveInteraction>
class Interaction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >
Contains information about the contact between two interactables, BaseInteraction::P_ and BaseInteraction::I_;.
An instance is created every time two BaseInteractables (particles or walls) get into contact with another, and gets deleted when the contact ends.
Next, the call process is described for this function for the case of two particles (it is very similar for a particle-wall contact.
Then, in each time step, every time that a contact is detected, DPMBase::computeInternalForces is called, which calls BaseParticle::getInteractionWith to create a new Interaction (setting the links to the interactables P_ and I_ and adds it to the InteractionHandler) or find an existing one. When a new Interaction is created, the Species determines what kind of Interaction it will be. DPMBase::computeInternalForces also sets the timeStamp_, normal_, overlap_, distance_, and contactPoint_ of the Interaction.
Then, computeForce is called, which sets the force_, which sets BaseInteraction::force_ and BaseInteraction::torque_ of the Interaction, and a few temporary values to communicate between the three different computeForce routines (see diamond inheritance below).
The force_ and torque_ is then used in DPMBase::integrateBeforeForceComputation and DPMBase::integrateAfterForceComputation to calcutate the new positions and velocities.
Todo:
MX: I do not think the above is correct. integrateBeforeForceComputation() updates the positions
As there are many types of contact forces, the class is templated to allow for different force models. This is done in a diamond inheritance structure: First, three kinds of Interactions are created:
NormalForceInteraction: Computes the normal contact force and sets the torque to zero (we currently only have spherical particles). Also sets relativeVelocity_, normalRelativeVelocity_, absoluteNormalForce_.
FrictionForceInteraction: Computes tangential contact force and torques.
AdhesiveForceInteraction: Computes the short-range normal contact force.
A full Interaction object is then derived by inheriting from all of the above:
Constructor & Destructor Documentation
Interaction() [1/3]
template<class NormalForceInteraction , class FrictionForceInteraction , class AdhesiveForceInteraction > Interaction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::Interaction (BaseInteractable * P, BaseInteractable * I, unsigned timeStamp)
The default constructor.
         : BaseInteraction(P, I, timeStamp), NormalForceInteraction(P, I, timeStamp),
           FrictionForceInteraction(P, I, timeStamp), AdhesiveForceInteraction(P, I, timeStamp)
 {
 #ifdef DEBUG_CONSTRUCTOR
     std::cout<<"Interaction::Interaction() finished"<<std::endl;
 #endif
 }
Interaction() [2/3]
template<class NormalForceInteraction , class FrictionForceInteraction , class AdhesiveForceInteraction > Interaction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::Interaction
Empty constructor.
         : BaseInteraction(), NormalForceInteraction(), FrictionForceInteraction(), AdhesiveForceInteraction()
 {
 #ifdef DEBUG_CONSTRUCTOR
     std::cout<<"Interaction::Interaction() finished"<<std::endl;
 #endif
 }
Interaction() [3/3]
template<class NormalForceInteraction , class FrictionForceInteraction , class AdhesiveForceInteraction > Interaction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::Interaction (const Interaction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction > & p)
The default copy constructor.
         : BaseInteraction(p), NormalForceInteraction(p), FrictionForceInteraction(p), AdhesiveForceInteraction(p)
 {
 #ifdef DEBUG_CONSTRUCTOR
     std::cout<<"Interaction::Interaction(const Interaction &p finished"<<std::endl;
 #endif
 }
~Interaction()
template<class NormalForceInteraction , class FrictionForceInteraction , class AdhesiveForceInteraction > Interaction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::~Interaction virtual
The default destructor.
 {
 #ifdef DEBUG_DESTRUCTOR
     std::cout<<"Interaction::~Interaction() finished"<<std::endl;
 #endif
 }
Member Function Documentation
actionsAfterTimeStep()
template<class NormalForceInteraction , class FrictionForceInteraction , class AdhesiveForceInteraction > void Interaction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::actionsAfterTimeStep virtual
Reimplemented from BaseInteraction.
 {
     NormalForceInteraction::actionsAfterTimeStep();
     FrictionForceInteraction::actionsAfterTimeStep();
     AdhesiveForceInteraction::actionsAfterTimeStep();
 }
computeForce()
template<class NormalForceInteraction , class FrictionForceInteraction , class AdhesiveForceInteraction > void Interaction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::computeForce final virtual
Computes the normal, tangential, and adhesive forces.
Computes the normal, tangential, and adhesive forces (in that order). The order is important, as the normal force computation also calculates some additional parameters required by the other force laws: relativeVelocity_, normalRelativeVelocity_, absoluteNormalForce_.
Reimplemented from BaseInteraction.
 {
     NormalForceInteraction::computeNormalForce();
     FrictionForceInteraction::computeFrictionForce();
     AdhesiveForceInteraction::computeAdhesionForce();
 }
computeInteraction()
template<class NormalForceInteraction , class FrictionForceInteraction = EmptyFrictionInteraction, class AdhesiveForceInteraction = EmptyAdhesiveInteraction> void Interaction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::computeInteraction ()
Computes the interaction parameters based on the forces and torques.
copy()
template<class NormalForceInteraction , class FrictionForceInteraction , class AdhesiveForceInteraction > Interaction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction > * Interaction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::copy final virtual
Creates a copy of this Interaction.
Useful for polymorphism as it can be called from a BaseInteraction* pointer.
Implements BaseInteraction.
 {
     return new Interaction(*this);
 }
createMPIInteractionDataArray()
template<class NormalForceInteraction , class FrictionForceInteraction , class AdhesiveForceInteraction > void * Interaction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::createMPIInteractionDataArray (unsigned int numberOfInteractions) const final virtual
Reimplemented from BaseInteraction.
 {
     MPIInteraction<NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction>* array = new MPIInteraction<NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction>[numberOfInteractions];
     void* interactionArray = static_cast<void*>(array);
     return interactionArray;
 }
createMPIType()
template<class NormalForceInteraction , class FrictionForceInteraction , class AdhesiveForceInteraction > void Interaction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::createMPIType final virtual
Reimplemented from BaseInteraction.
 {
 #ifdef MERCURYDPM_USE_MPI
     MPIContainer& communicator = MPIContainer::Instance();
     MPIInteraction<NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction> dummyHistoryInteraction;
     communicator.createMercuryMPIType(dummyHistoryInteraction, MercuryMPIType::INTERACTION);
 #endif
 }
References MPIContainer::createMercuryMPIType(), MPIContainer::Instance(), and INTERACTION.
deleteMPIInteractionDataArray()
template<class NormalForceInteraction , class FrictionForceInteraction , class AdhesiveForceInteraction > void Interaction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::deleteMPIInteractionDataArray (void * dataArray) final virtual
Reimplemented from BaseInteraction.
 {
     MPIInteraction<NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction>* array = static_cast<MPIInteraction<NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction>*>(dataArray);
     delete[] array;
 }
getElasticEnergy()
template<class NormalForceInteraction , class FrictionForceInteraction , class AdhesiveForceInteraction > Mdouble Interaction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::getElasticEnergy final virtual
Returns the elastic energy stored in the Interaction.
Returns the elastic energy stored in the Interaction, adding up contributions from the normal, frictional and adhesive interaction The elastic (=potential) energy is defined as the energy gained by separating P_ and I_.
Returns
the computed elastic energy.
Reimplemented from EmptyAdhesiveInteraction.
 {
     return NormalForceInteraction::getElasticEnergy() + FrictionForceInteraction::getElasticEnergy() +
            AdhesiveForceInteraction::getElasticEnergy();
 }
getElasticEnergyAtEquilibrium()
template<class NormalForceInteraction , class FrictionForceInteraction , class AdhesiveForceInteraction > Mdouble Interaction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::getElasticEnergyAtEquilibrium (Mdouble adhesiveForce) const virtual
returns the overlap at which the repulsive elastic force equals a given adhesive force; to be implemented in the normal force
Reimplemented from BaseInteraction.
 {
     return NormalForceInteraction::getElasticEnergyAtEquilibrium(adhesiveForce);
 };
getInteractionDetails()
template<class NormalForceInteraction , class FrictionForceInteraction , class AdhesiveForceInteraction > void Interaction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::getInteractionDetails (void * interactionDataArray, unsigned int index, unsigned int & identificationP, unsigned int & identificationI, bool & isWallInteraction, unsigned & timeStamp) virtual
Reimplemented from BaseInteraction.
 {
     MPIInteraction<NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction>* array = static_cast<MPIInteraction<NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction>*>(interactionDataArray);
     MPIInteraction<NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction> interactionData = array[index];
     identificationP = interactionData.P;
     identificationI = interactionData.I;
     isWallInteraction = interactionData.isWallInteraction;
     timeStamp = interactionData.timeStamp;
 }
References MPIInteraction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::I, MPIInteraction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::isWallInteraction, MPIInteraction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::P, and MPIInteraction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::timeStamp.
getMPIInteraction()
template<class NormalForceInteraction , class FrictionForceInteraction , class AdhesiveForceInteraction > void Interaction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::getMPIInteraction (void * historyDataArray, unsigned int index) const final virtual
copies the history interactions into the data array
Reimplemented from BaseInteraction.
 {
     MPIInteraction<NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction> interactionData;
     interactionData.copyFromInteraction(this);
     MPIInteraction<NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction>* array = static_cast<MPIInteraction<NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction>*>(interactionDataArray);
     array[index] = interactionData;
 }
References MPIInteraction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::copyFromInteraction().
getName()
template<class NormalForceInteraction , class FrictionForceInteraction , class AdhesiveForceInteraction > std::string Interaction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::getName final virtual
Returns the name of the Interaction.
Returns the name of the Interaction, which depends on the template parameters.
Returns
the string to which the name is written.
Reimplemented from BaseInteraction.
 {
     return NormalForceInteraction::getBaseName() + FrictionForceInteraction::getBaseName() +
            AdhesiveForceInteraction::getBaseName() + "Interaction";
 }
integrate()
template<class NormalForceInteraction , class FrictionForceInteraction , class AdhesiveForceInteraction > void Interaction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::integrate (Mdouble timeStep) final virtual
Integrates the time-dependent parameters of the contact force.
Called by ??? to integrate time-dependent parameters of the contact force, such as the SlidingFrictionInteraction::slidingSpring_
Parameters
[in] the time step.
Reimplemented from EmptyFrictionInteraction.
 {
     FrictionForceInteraction::integrate(timeStep);
 }
read()
template<class NormalForceInteraction , class FrictionForceInteraction , class AdhesiveForceInteraction > void Interaction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::read (std::istream & is) final virtual
Read Interaction properties from a file.
Reads Interaction properties in human-readable form from a file, typically Files::restartFile.
Parameters
[in] is the istream from which the data is read.
Reimplemented from EmptyAdhesiveInteraction.
 {
     NormalForceInteraction::read(is);
     FrictionForceInteraction::read(is);
     AdhesiveForceInteraction::read(is);
 }
References Eigen::TensorSycl::internal::read().
reverseHistory()
template<class NormalForceInteraction , class FrictionForceInteraction , class AdhesiveForceInteraction > void Interaction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::reverseHistory final virtual
Reverses the parameters of the contact force.
Called by BaseInteraction::copySwitchPointer to reverse the
parameters of the contact force in the case that the interactables P_ and I_ are switched. This is needed to deal with periodic particles.
Reimplemented from BaseInteraction.
 {
     NormalForceInteraction::reverseHistory();
     FrictionForceInteraction::reverseHistory();
     AdhesiveForceInteraction::reverseHistory();
 }
rotateHistory()
template<class NormalForceInteraction , class FrictionForceInteraction , class AdhesiveForceInteraction > void Interaction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::rotateHistory (Matrix3D & rotationMatrix) final virtual
When periodic particles are used, some interactions need certain history properties rotated (e.g. tangential springs). This is the function for that.
Todo:
some of these might be unneccesary
Reimplemented from BaseInteraction.
 {
     NormalForceInteraction::rotateHistory(rotationMatrix);
     FrictionForceInteraction::rotateHistory(rotationMatrix);
     AdhesiveForceInteraction::rotateHistory(rotationMatrix);
 }
setMPIInteraction()
template<class NormalForceInteraction , class FrictionForceInteraction , class AdhesiveForceInteraction > void Interaction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::setMPIInteraction (void * historyDataArray, unsigned int index, const bool resetPointers) final virtual
Reimplemented from BaseInteraction.
 {
     MPIInteraction<NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction>* array = static_cast<MPIInteraction<NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction>*>(interactionDataArray);
     MPIInteraction<NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction> interactionData = array[index];
     //Copy the interaction data into the interaction
     interactionData.copyToInteraction(this, resetPointers);
 }
References MPIInteraction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::copyToInteraction().
write()
template<class NormalForceInteraction , class FrictionForceInteraction , class AdhesiveForceInteraction > void Interaction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::write (std::ostream & os) const final virtual
Writes Interaction properties to a file.
Writes Interaction properties in human-readable form to a file, typically Files::restartFile.
Parameters
[out] os the ostream to which the data is written.
Reimplemented from EmptyAdhesiveInteraction.
 {
     NormalForceInteraction::write(os);
     FrictionForceInteraction::write(os);
     AdhesiveForceInteraction::write(os);
 }
References Eigen::TensorSycl::internal::write().
The documentation for this class was generated from the following file:
Interaction.h