MercuryDPM: Eigen::TensorDevice< ExpressionType, DeviceType > Class Template Reference
Eigen::TensorDevice< ExpressionType, DeviceType > Class Template Reference
Pseudo expression providing an operator = that will evaluate its argument on the specified computing 'device' (GPU, thread pool, ...)
#include <TensorDevice.h>
Public Member Functions
TensorDevice (const DeviceType &device, ExpressionType &expression)
template<typename OtherDerived >
EIGEN_STRONG_INLINE TensorDevice & operator= (const OtherDerived &other)
template<typename OtherDerived >
EIGEN_STRONG_INLINE TensorDevice & operator+= (const OtherDerived &other)
template<typename OtherDerived >
EIGEN_STRONG_INLINE TensorDevice & operator-= (const OtherDerived &other)
Protected Attributes
const DeviceType & m_device
ExpressionType & m_expression
Detailed Description
template<typename ExpressionType, typename DeviceType>
class Eigen::TensorDevice< ExpressionType, DeviceType >
Pseudo expression providing an operator = that will evaluate its argument on the specified computing 'device' (GPU, thread pool, ...)
Example: C.device(EIGEN_GPU) = A + B;
Todo: operator *= and /=.
Constructor & Destructor Documentation
TensorDevice()
template<typename ExpressionType , typename DeviceType > Eigen::TensorDevice< ExpressionType, DeviceType >::TensorDevice (const DeviceType & device, ExpressionType & expression) inline
 : m_device(device), m_expression(expression) {}
Member Function Documentation
operator+=()
template<typename ExpressionType , typename DeviceType > template<typename OtherDerived > EIGEN_STRONG_INLINE TensorDevice& Eigen::TensorDevice< ExpressionType, DeviceType >::operator+= (const OtherDerived & other) inline
{
     typedef typename OtherDerived::Scalar Scalar;
     typedef TensorCwiseBinaryOp<internal::scalar_sum_op<Scalar>, const ExpressionType, const OtherDerived> Sum;
     Sum sum(m_expression, other);
     typedef TensorAssignOp<ExpressionType, const Sum> Assign;
     Assign assign(m_expression, sum);
     internal::TensorExecutor<const Assign, DeviceType>::run(assign, m_device);
     return *this;
   }
References Eigen::TensorDevice< ExpressionType, DeviceType >::m_device, Eigen::TensorDevice< ExpressionType, DeviceType >::m_expression, and Eigen::internal::TensorExecutor< Expression, Device, Vectorizable, Tiling >::run().
operator-=()
template<typename ExpressionType , typename DeviceType > template<typename OtherDerived > EIGEN_STRONG_INLINE TensorDevice& Eigen::TensorDevice< ExpressionType, DeviceType >::operator-= (const OtherDerived & other) inline
{
     typedef typename OtherDerived::Scalar Scalar;
     typedef TensorCwiseBinaryOp<internal::scalar_difference_op<Scalar>, const ExpressionType, const OtherDerived>
         Difference;
     Difference difference(m_expression, other);
     typedef TensorAssignOp<ExpressionType, const Difference> Assign;
     Assign assign(m_expression, difference);
     internal::TensorExecutor<const Assign, DeviceType>::run(assign, m_device);
     return *this;
   }
References Eigen::TensorDevice< ExpressionType, DeviceType >::m_device, Eigen::TensorDevice< ExpressionType, DeviceType >::m_expression, and Eigen::internal::TensorExecutor< Expression, Device, Vectorizable, Tiling >::run().
operator=()
template<typename ExpressionType , typename DeviceType > template<typename OtherDerived > EIGEN_STRONG_INLINE TensorDevice& Eigen::TensorDevice< ExpressionType, DeviceType >::operator= (const OtherDerived & other) inline
{
     typedef TensorAssignOp<ExpressionType, const OtherDerived> Assign;
     Assign assign(m_expression, other);
     internal::TensorExecutor<const Assign, DeviceType>::run(assign, m_device);
     return *this;
   }
References Eigen::TensorDevice< ExpressionType, DeviceType >::m_device, Eigen::TensorDevice< ExpressionType, DeviceType >::m_expression, and Eigen::internal::TensorExecutor< Expression, Device, Vectorizable, Tiling >::run().
Member Data Documentation
m_device
template<typename ExpressionType , typename DeviceType > const DeviceType& Eigen::TensorDevice< ExpressionType, DeviceType >::m_device protected
Referenced by Eigen::TensorDevice< ExpressionType, DeviceType >::operator+=(), Eigen::TensorDevice< ExpressionType, DeviceType >::operator-=(), and Eigen::TensorDevice< ExpressionType, DeviceType >::operator=().
m_expression
template<typename ExpressionType , typename DeviceType > ExpressionType& Eigen::TensorDevice< ExpressionType, DeviceType >::m_expression protected
Referenced by Eigen::TensorDevice< ExpressionType, DeviceType >::operator+=(), Eigen::TensorDevice< ExpressionType, DeviceType >::operator-=(), and Eigen::TensorDevice< ExpressionType, DeviceType >::operator=().
The documentation for this class was generated from the following file:
TensorDevice.h