MercuryDPM: chute_periodic_autorun.cpp File Reference
chute_periodic_autorun.cpp File Reference
#include <sstream>
#include <iostream>
#include <iomanip>
#include <cmath>
#include <sys/types.h>
#include <sys/stat.h>
#include <Boundaries/PeriodicBoundary.h>
#include <Species/LinearViscoelasticFrictionSpecies.h>
#include "Chute.h"
Classes
class ChutePeriodic
Functions
int main (int argc UNUSED, char *argv[] UNUSED)
Function Documentation
main()
int main (int argc UNUSED, char *argv[] UNUSED)
 {
     ChutePeriodic problem;
     problem.setup();
     logger.assert_always(argc > 1, "Argument needed!");
     problem.setChuteAngle(atof(argv[1]));
     logger(INFO, "Chute Angle: %", problem.getChuteAngle());
     problem.setZMax(5e-3);
     problem.solve();
     problem.write(std::cout, false);
     problem.writeRestartFile();
     ChutePeriodic problem2;
     problem2.setup();
     logger.assert_always(argc > 1, "Argument needed!");
    problem2.setChuteAngle(atof(argv[1]));
     logger(INFO, "Chute Angle: %", problem2.getChuteAngle());
     problem2.setZMax(10e-3);
     problem2.solve();
     problem2.write(std::cout, false);
     problem2.writeRestartFile();
     ChutePeriodic problem3;
     problem3.setup();
     logger.assert_always(argc > 1, "Argument needed!");
      problem3.setChuteAngle(atof(argv[1]));
     logger(INFO, "Chute Angle: %", problem3.getChuteAngle());
     problem3.setZMax(15e-3);
     problem3.solve();
     problem3.write(std::cout, false);
     problem3.writeRestartFile();
     ChutePeriodic problem4;
     problem4.setup();
     logger.assert_always(argc > 1, "Argument needed!");
     problem4.setChuteAngle(atof(argv[1]));
     logger(INFO, "Chute Angle: %" , problem4.getChuteAngle());
     problem4.setZMax(20e-3);
     problem4.solve();
     problem4.write(std::cout, false);
     problem4.writeRestartFile();
     ChutePeriodic problem5;
     problem5.setup();
     logger.assert_always(argc > 1, "Argument needed!");
     problem5.setChuteAngle(atof(argv[1]));
     logger(INFO, "Chute Angle: %", problem5.getChuteAngle());
     problem5.setZMax(25e-3);
     problem5.solve();
     problem5.write(std::cout, false);
     problem5.writeRestartFile();
 }
References e(), Chute::getChuteAngle(), INFO, logger, problem, Chute::setChuteAngle(), ChutePeriodic::setup(), DPMBase::setZMax(), DPMBase::solve(), Chute::write(), and DPMBase::writeRestartFile().