MercuryDPM: Eigen::TensorEvaluator< const TensorCwiseBinaryOp< BinaryOp, LeftArgType, RightArgType >, Device > Struct Template Reference
Eigen::TensorEvaluator< const TensorCwiseBinaryOp< BinaryOp, LeftArgType, RightArgType >, Device > Struct Template Reference
#include <TensorEvaluator.h>
Public Types
enum {
IsAligned , PacketAccess , BlockAccess , PreferBlockAccess ,
CoordAccess = false , RawAccess = false
}
typedef TensorCwiseBinaryOp< BinaryOp, LeftArgType, RightArgType > XprType
typedef XprType::Index Index
typedef XprType::Scalar Scalar
typedef internal::traits< XprType >::Scalar CoeffReturnType
typedef PacketType< CoeffReturnType, Device >::type PacketReturnType
typedef TensorEvaluator< LeftArgType, Device >::Dimensions Dimensions
typedef StorageMemory< CoeffReturnType, Device > Storage
typedef Storage::Type EvaluatorPointerType
typedef internal::TensorBlockDescriptor< NumDims, Index > TensorBlockDesc
typedef internal::TensorBlockScratchAllocator< Device > TensorBlockScratch
typedef TensorEvaluator< const LeftArgType, Device >::TensorBlock LeftTensorBlock
typedef TensorEvaluator< const RightArgType, Device >::TensorBlock RightTensorBlock
typedef internal::TensorCwiseBinaryBlock< BinaryOp, LeftTensorBlock, RightTensorBlock > TensorBlock
Public Member Functions
EIGEN_DEVICE_FUNC TensorEvaluator (const XprType &op, const Device &device)
EIGEN_DEVICE_FUNC const Dimensions & dimensions () const
EIGEN_STRONG_INLINE bool evalSubExprsIfNeeded (EvaluatorPointerType)
EIGEN_STRONG_INLINE void cleanup ()
EIGEN_DEVICE_FUNC CoeffReturnType coeff (Index index) const
template<int LoadMode>
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketReturnType packet (Index index) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorOpCost costPerCoeff (bool vectorized) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE internal::TensorBlockResourceRequirements getResourceRequirements () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorBlock block (TensorBlockDesc &desc, TensorBlockScratch &scratch, bool=false) const
EIGEN_DEVICE_FUNC EvaluatorPointerType data () const
Static Public Attributes
static constexpr int Layout = TensorEvaluator<LeftArgType, Device>::Layout
static constexpr int PacketSize = PacketType<CoeffReturnType, Device>::size
static constexpr int NumDims = internal::array_size<typename TensorEvaluator<LeftArgType, Device>::Dimensions>::value
Private Attributes
const Device EIGEN_DEVICE_REF m_device
const BinaryOp m_functor
TensorEvaluator< LeftArgType, Device > m_leftImpl
TensorEvaluator< RightArgType, Device > m_rightImpl
Member Typedef Documentation
CoeffReturnType
template<typename BinaryOp , typename LeftArgType , typename RightArgType , typename Device > typedef internal::traits<XprType>::Scalar Eigen::TensorEvaluator< const TensorCwiseBinaryOp< BinaryOp, LeftArgType, RightArgType >, Device >::CoeffReturnType
Dimensions
template<typename BinaryOp , typename LeftArgType , typename RightArgType , typename Device > typedef TensorEvaluator<LeftArgType, Device>::Dimensions Eigen::TensorEvaluator< const TensorCwiseBinaryOp< BinaryOp, LeftArgType, RightArgType >, Device >::Dimensions
EvaluatorPointerType
template<typename BinaryOp , typename LeftArgType , typename RightArgType , typename Device > typedef Storage::Type Eigen::TensorEvaluator< const TensorCwiseBinaryOp< BinaryOp, LeftArgType, RightArgType >, Device >::EvaluatorPointerType
Index
template<typename BinaryOp , typename LeftArgType , typename RightArgType , typename Device > typedef XprType::Index Eigen::TensorEvaluator< const TensorCwiseBinaryOp< BinaryOp, LeftArgType, RightArgType >, Device >::Index
LeftTensorBlock
template<typename BinaryOp , typename LeftArgType , typename RightArgType , typename Device > typedef TensorEvaluator<const LeftArgType, Device>::TensorBlock Eigen::TensorEvaluator< const TensorCwiseBinaryOp< BinaryOp, LeftArgType, RightArgType >, Device >::LeftTensorBlock
PacketReturnType
template<typename BinaryOp , typename LeftArgType , typename RightArgType , typename Device > typedef PacketType<CoeffReturnType, Device>::type Eigen::TensorEvaluator< const TensorCwiseBinaryOp< BinaryOp, LeftArgType, RightArgType >, Device >::PacketReturnType
RightTensorBlock
template<typename BinaryOp , typename LeftArgType , typename RightArgType , typename Device > typedef TensorEvaluator<const RightArgType, Device>::TensorBlock Eigen::TensorEvaluator< const TensorCwiseBinaryOp< BinaryOp, LeftArgType, RightArgType >, Device >::RightTensorBlock
Scalar
template<typename BinaryOp , typename LeftArgType , typename RightArgType , typename Device > typedef XprType::Scalar Eigen::TensorEvaluator< const TensorCwiseBinaryOp< BinaryOp, LeftArgType, RightArgType >, Device >::Scalar
Storage
template<typename BinaryOp , typename LeftArgType , typename RightArgType , typename Device > typedef StorageMemory<CoeffReturnType, Device> Eigen::TensorEvaluator< const TensorCwiseBinaryOp< BinaryOp, LeftArgType, RightArgType >, Device >::Storage
TensorBlock
template<typename BinaryOp , typename LeftArgType , typename RightArgType , typename Device > typedef internal::TensorCwiseBinaryBlock<BinaryOp, LeftTensorBlock, RightTensorBlock> Eigen::TensorEvaluator< const TensorCwiseBinaryOp< BinaryOp, LeftArgType, RightArgType >, Device >::TensorBlock
TensorBlockDesc
template<typename BinaryOp , typename LeftArgType , typename RightArgType , typename Device > typedef internal::TensorBlockDescriptor<NumDims, Index> Eigen::TensorEvaluator< const TensorCwiseBinaryOp< BinaryOp, LeftArgType, RightArgType >, Device >::TensorBlockDesc
TensorBlockScratch
template<typename BinaryOp , typename LeftArgType , typename RightArgType , typename Device > typedef internal::TensorBlockScratchAllocator<Device> Eigen::TensorEvaluator< const TensorCwiseBinaryOp< BinaryOp, LeftArgType, RightArgType >, Device >::TensorBlockScratch
XprType
template<typename BinaryOp , typename LeftArgType , typename RightArgType , typename Device > typedef TensorCwiseBinaryOp<BinaryOp, LeftArgType, RightArgType> Eigen::TensorEvaluator< const TensorCwiseBinaryOp< BinaryOp, LeftArgType, RightArgType >, Device >::XprType
Member Enumeration Documentation
anonymous enum
template<typename BinaryOp , typename LeftArgType , typename RightArgType , typename Device > anonymous enum
Enumerator
IsAligned
PacketAccess
BlockAccess
PreferBlockAccess
CoordAccess
RawAccess
        {
     IsAligned =
         int(TensorEvaluator<LeftArgType, Device>::IsAligned) & int(TensorEvaluator<RightArgType, Device>::IsAligned),
     PacketAccess = int(TensorEvaluator<LeftArgType, Device>::PacketAccess) &
                    int(TensorEvaluator<RightArgType, Device>::PacketAccess) &
                    int(internal::functor_traits<BinaryOp>::PacketAccess),
     BlockAccess = int(TensorEvaluator<LeftArgType, Device>::BlockAccess) &
                   int(TensorEvaluator<RightArgType, Device>::BlockAccess),
     PreferBlockAccess = int(TensorEvaluator<LeftArgType, Device>::PreferBlockAccess) |
                         int(TensorEvaluator<RightArgType, Device>::PreferBlockAccess),
     CoordAccess = false,  // to be implemented
     RawAccess = false
   };
Constructor & Destructor Documentation
TensorEvaluator()
template<typename BinaryOp , typename LeftArgType , typename RightArgType , typename Device > EIGEN_DEVICE_FUNC Eigen::TensorEvaluator< const TensorCwiseBinaryOp< BinaryOp, LeftArgType, RightArgType >, Device >::TensorEvaluator (const XprType & op, const Device & device) inline
       : m_device(device),
         m_functor(op.functor()),
         m_leftImpl(op.lhsExpression(), device),
         m_rightImpl(op.rhsExpression(), device) {
     EIGEN_STATIC_ASSERT((static_cast<int>(TensorEvaluator<LeftArgType, Device>::Layout) ==
                              static_cast<int>(TensorEvaluator<RightArgType, Device>::Layout) ||
                          internal::traits<XprType>::NumDimensions <= 1),
                         YOU_MADE_A_PROGRAMMING_MISTAKE);
     eigen_assert(dimensions_match(m_leftImpl.dimensions(), m_rightImpl.dimensions()));
   }
References Eigen::dimensions_match(), eigen_assert, and EIGEN_STATIC_ASSERT.
Member Function Documentation
block()
template<typename BinaryOp , typename LeftArgType , typename RightArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorBlock Eigen::TensorEvaluator< const TensorCwiseBinaryOp< BinaryOp, LeftArgType, RightArgType >, Device >::block (TensorBlockDesc & desc, TensorBlockScratch & scratch, bool = false) const inline
{
     desc.DropDestinationBuffer();
     return TensorBlock(m_leftImpl.block(desc, scratch), m_rightImpl.block(desc, scratch), m_functor);
   }
References Eigen::internal::TensorBlockDescriptor< NumDims, IndexType >::DropDestinationBuffer().
cleanup()
template<typename BinaryOp , typename LeftArgType , typename RightArgType , typename Device > EIGEN_STRONG_INLINE void Eigen::TensorEvaluator< const TensorCwiseBinaryOp< BinaryOp, LeftArgType, RightArgType >, Device >::cleanup () inline
{
     m_leftImpl.cleanup();
     m_rightImpl.cleanup();
   }
Referenced by framework.Frame::__init__().
coeff()
template<typename BinaryOp , typename LeftArgType , typename RightArgType , typename Device > EIGEN_DEVICE_FUNC CoeffReturnType Eigen::TensorEvaluator< const TensorCwiseBinaryOp< BinaryOp, LeftArgType, RightArgType >, Device >::coeff (Index index) const inline
{
     return m_functor(m_leftImpl.coeff(index), m_rightImpl.coeff(index));
   }
costPerCoeff()
template<typename BinaryOp , typename LeftArgType , typename RightArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorOpCost Eigen::TensorEvaluator< const TensorCwiseBinaryOp< BinaryOp, LeftArgType, RightArgType >, Device >::costPerCoeff (bool vectorized) const inline
{
     const double functor_cost = internal::functor_traits<BinaryOp>::Cost;
     return m_leftImpl.costPerCoeff(vectorized) + m_rightImpl.costPerCoeff(vectorized) +
            TensorOpCost(0, 0, functor_cost, vectorized, PacketSize);
   }
References Eigen::TensorEvaluator< Derived, Device >::PacketSize.
data()
template<typename BinaryOp , typename LeftArgType , typename RightArgType , typename Device > EIGEN_DEVICE_FUNC EvaluatorPointerType Eigen::TensorEvaluator< const TensorCwiseBinaryOp< BinaryOp, LeftArgType, RightArgType >, Device >::data () const inline
 { return NULL; }
Referenced by gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenQuaternionPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), gdb.printers.EigenSparseMatrixPrinter::to_string(), and gdb.printers.EigenQuaternionPrinter::to_string().
dimensions()
template<typename BinaryOp , typename LeftArgType , typename RightArgType , typename Device > EIGEN_DEVICE_FUNC const Dimensions& Eigen::TensorEvaluator< const TensorCwiseBinaryOp< BinaryOp, LeftArgType, RightArgType >, Device >::dimensions () const inline
{
     // TODO: use right impl instead if right impl dimensions are known at compile time.
     return m_leftImpl.dimensions();
   }
evalSubExprsIfNeeded()
template<typename BinaryOp , typename LeftArgType , typename RightArgType , typename Device > EIGEN_STRONG_INLINE bool Eigen::TensorEvaluator< const TensorCwiseBinaryOp< BinaryOp, LeftArgType, RightArgType >, Device >::evalSubExprsIfNeeded (EvaluatorPointerType) inline
{
     m_leftImpl.evalSubExprsIfNeeded(NULL);
     m_rightImpl.evalSubExprsIfNeeded(NULL);
     return true;
   }
getResourceRequirements()
template<typename BinaryOp , typename LeftArgType , typename RightArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE internal::TensorBlockResourceRequirements Eigen::TensorEvaluator< const TensorCwiseBinaryOp< BinaryOp, LeftArgType, RightArgType >, Device >::getResourceRequirements () const inline
{
     static const double functor_cost = internal::functor_traits<BinaryOp>::Cost;
     return internal::TensorBlockResourceRequirements::merge(m_leftImpl.getResourceRequirements(),
                                                             m_rightImpl.getResourceRequirements())
         .addCostPerCoeff({0, 0, functor_cost / PacketSize});
   }
References Eigen::internal::TensorBlockResourceRequirements::addCostPerCoeff(), Eigen::internal::TensorBlockResourceRequirements::merge(), and Eigen::TensorEvaluator< Derived, Device >::PacketSize.
packet()
template<typename BinaryOp , typename LeftArgType , typename RightArgType , typename Device > template<int LoadMode> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketReturnType Eigen::TensorEvaluator< const TensorCwiseBinaryOp< BinaryOp, LeftArgType, RightArgType >, Device >::packet (Index index) const inline
{
     return m_functor.packetOp(m_leftImpl.template packet<LoadMode>(index),
                               m_rightImpl.template packet<LoadMode>(index));
   }
Member Data Documentation
Layout
template<typename BinaryOp , typename LeftArgType , typename RightArgType , typename Device > constexpr int Eigen::TensorEvaluator< const TensorCwiseBinaryOp< BinaryOp, LeftArgType, RightArgType >, Device >::Layout = TensorEvaluator<LeftArgType, Device>::Layout static constexpr
m_device
template<typename BinaryOp , typename LeftArgType , typename RightArgType , typename Device > const Device EIGEN_DEVICE_REF Eigen::TensorEvaluator< const TensorCwiseBinaryOp< BinaryOp, LeftArgType, RightArgType >, Device >::m_device private
m_functor
template<typename BinaryOp , typename LeftArgType , typename RightArgType , typename Device > const BinaryOp Eigen::TensorEvaluator< const TensorCwiseBinaryOp< BinaryOp, LeftArgType, RightArgType >, Device >::m_functor private
m_leftImpl
template<typename BinaryOp , typename LeftArgType , typename RightArgType , typename Device > TensorEvaluator<LeftArgType, Device> Eigen::TensorEvaluator< const TensorCwiseBinaryOp< BinaryOp, LeftArgType, RightArgType >, Device >::m_leftImpl private
m_rightImpl
template<typename BinaryOp , typename LeftArgType , typename RightArgType , typename Device > TensorEvaluator<RightArgType, Device> Eigen::TensorEvaluator< const TensorCwiseBinaryOp< BinaryOp, LeftArgType, RightArgType >, Device >::m_rightImpl private
NumDims
template<typename BinaryOp , typename LeftArgType , typename RightArgType , typename Device > constexpr int Eigen::TensorEvaluator< const TensorCwiseBinaryOp< BinaryOp, LeftArgType, RightArgType >, Device >::NumDims = internal::array_size<typename TensorEvaluator<LeftArgType, Device>::Dimensions>::value static constexpr
PacketSize
template<typename BinaryOp , typename LeftArgType , typename RightArgType , typename Device > constexpr int Eigen::TensorEvaluator< const TensorCwiseBinaryOp< BinaryOp, LeftArgType, RightArgType >, Device >::PacketSize = PacketType<CoeffReturnType, Device>::size static constexpr
The documentation for this struct was generated from the following file:
TensorEvaluator.h