MercuryDPM: Eigen::internal::significant_decimals_impl< Scalar > Struct Template Reference
Eigen::internal::significant_decimals_impl< Scalar > Struct Template Reference
#include <IO.h>
Static Public Member Functions
static int run ()
Member Function Documentation
run()
template<typename Scalar > static int Eigen::internal::significant_decimals_impl< Scalar >::run () inline static
 { return NumTraits<Scalar>::max_digits10(); }
Referenced by Eigen::internal::print_matrix(), Eigen::internal::TensorPrinter< Tensor, rank, Format, EnableIf >::run(), and Eigen::internal::TensorPrinter< Tensor, 0, Format >::run().
The documentation for this struct was generated from the following file:
IO.h