MercuryDPM: PIController Class Reference
PIController Class Reference
#include <PIController.h>
Public Member Functions
PIController ()=default
PIController (Mdouble pGain, Mdouble iGain)
void reset ()
Mdouble apply (Mdouble error, Mdouble timeStep)
double getErrorVariance () const
unsigned getNApplied () const
Public Member Functions inherited from PIControllerBasic
PIControllerBasic ()=default
PIControllerBasic (Mdouble pGain, Mdouble iGain)
void set (Mdouble pGain, Mdouble iGain)
void reset ()
Mdouble apply (Mdouble error, Mdouble timeStep)
double getIError () const
Private Attributes
Mdouble sumErrorSquared_ = 0.0
unsigned nApplied_ = 0
Constructor & Destructor Documentation
PIController() [1/2]
PIController::PIController () default
PIController() [2/2]
PIController::PIController (Mdouble pGain, Mdouble iGain) inline
 : PIControllerBasic(pGain, iGain) {}
Member Function Documentation
apply()
Mdouble PIController::apply (Mdouble error, Mdouble timeStep)
{
     sumErrorSquared_ += error*error;
     nApplied_++;
     return PIControllerBasic::apply (error, timeStep);
 }
References PIControllerBasic::apply(), calibrate::error, nApplied_, and sumErrorSquared_.
Referenced by StressStrainControlBoundary::computeStrainRate(), and ControllerUnitTest::RungeKutta().
getErrorVariance()
double PIController::getErrorVariance () const
{
     return sumErrorSquared_/nApplied_;
 }
References nApplied_, and sumErrorSquared_.
getNApplied()
unsigned PIController::getNApplied () const
{
     return nApplied_;
 }
References nApplied_.
reset()
void PIController::reset ()
{
     sumErrorSquared_ = 0.0;
     nApplied_ = 0;
     PIControllerBasic::reset();
 }
References nApplied_, PIControllerBasic::reset(), and sumErrorSquared_.
Referenced by StressStrainControlBoundary::set().
Member Data Documentation
nApplied_
unsigned PIController::nApplied_ = 0 private
Referenced by apply(), getErrorVariance(), getNApplied(), and reset().
sumErrorSquared_
Mdouble PIController::sumErrorSquared_ = 0.0 private
Referenced by apply(), getErrorVariance(), and reset().
The documentation for this class was generated from the following files:
PIController.h
PIController.cc