MercuryDPM: check_rsqrt_impl< std::complex< T > > Struct Template Reference
check_rsqrt_impl< std::complex< T > > Struct Template Reference
Static Public Member Functions
static void run ()
Member Function Documentation
run()
template<typename T > static void check_rsqrt_impl< std::complex< T > >::run () inline static
                     {
     typedef typename std::complex<T> ComplexT;
     const T zero = T(0);
     const T one = T(1);
     const T inf = std::numeric_limits<T>::infinity();
     const T nan = std::numeric_limits<T>::quiet_NaN();
     for (int i = 0; i < 1000; ++i) {
       const ComplexT x = internal::random<ComplexT>();
       const ComplexT invx = ComplexT(one, zero) / x;
       const ComplexT rsqrtx = numext::rsqrt(x);
       VERIFY_IS_APPROX(rsqrtx * rsqrtx, invx);
     }
 // GCC and MSVC differ in their treatment of 1/(0 + 0i)
 //   GCC/clang = (inf, nan)
 //   MSVC = (nan, nan)
 // and 1 / (x + inf i)
 //   GCC/clang = (0, 0)
 //   MSVC = (nan, nan)
 #if (EIGEN_COMP_GNUC)
     {
       const int kNumCorners = 20;
       const ComplexT corners[kNumCorners][2] = {
           // Only consistent across GCC, clang
           {ComplexT(zero, zero), ComplexT(zero, zero)},
           {ComplexT(-zero, zero), ComplexT(zero, zero)},
           {ComplexT(zero, -zero), ComplexT(zero, zero)},
           {ComplexT(-zero, -zero), ComplexT(zero, zero)},
           {ComplexT(one, inf), ComplexT(inf, inf)},
           {ComplexT(nan, inf), ComplexT(inf, inf)},
           {ComplexT(one, -inf), ComplexT(inf, -inf)},
           {ComplexT(nan, -inf), ComplexT(inf, -inf)},
           // Consistent across GCC, clang, MSVC
           {ComplexT(-inf, one), ComplexT(zero, inf)},
           {ComplexT(inf, one), ComplexT(inf, zero)},
           {ComplexT(-inf, -one), ComplexT(zero, -inf)},
           {ComplexT(inf, -one), ComplexT(inf, -zero)},
           {ComplexT(-inf, nan), ComplexT(nan, inf)},
           {ComplexT(inf, nan), ComplexT(inf, nan)},
           {ComplexT(zero, nan), ComplexT(nan, nan)},
           {ComplexT(one, nan), ComplexT(nan, nan)},
           {ComplexT(nan, zero), ComplexT(nan, nan)},
           {ComplexT(nan, one), ComplexT(nan, nan)},
           {ComplexT(nan, -one), ComplexT(nan, nan)},
           {ComplexT(nan, nan), ComplexT(nan, nan)},
       };
       for (int i = 0; i < kNumCorners; ++i) {
         const ComplexT& x = corners[i][0];
         const ComplexT rsqrtx = ComplexT(one, zero) / corners[i][1];
         VERIFY_IS_EQUAL_OR_NANS(numext::rsqrt(x), rsqrtx);
       }
     }
 #endif
   }
References corners(), i, constants::inf, Eigen::numext::rsqrt(), VERIFY_IS_APPROX, VERIFY_IS_EQUAL_OR_NANS, plotDoE::x, and zero().
The documentation for this struct was generated from the following file:
numext.cpp