MercuryDPM: Eigen::MatrixFunctionReturnValue< Derived > Class Template Reference
Eigen::MatrixFunctionReturnValue< Derived > Class Template Reference
Proxy for the matrix function of some matrix (expression).
#include <MatrixFunction.h>
Public Types
typedef Derived::Scalar Scalar
typedef internal::stem_function< Scalar >::type StemFunction
Public Types inherited from Eigen::ReturnByValue< MatrixFunctionReturnValue< Derived > >
typedef internal::traits< MatrixFunctionReturnValue< Derived > >::ReturnType ReturnType
typedef internal::dense_xpr_base< ReturnByValue >::type Base
Public Member Functions
MatrixFunctionReturnValue (const Derived &A, StemFunction f)
Constructor.
template<typename ResultType >
void evalTo (ResultType &result) const
Compute the matrix function.
Index rows () const
Index cols () const
Public Member Functions inherited from Eigen::ReturnByValue< MatrixFunctionReturnValue< Derived > >
EIGEN_DEVICE_FUNC void evalTo (Dest &dst) const
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index rows () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index cols () const EIGEN_NOEXCEPT
const Unusable & coeff (Index) const
const Unusable & coeff (Index, Index) const
Unusable & coeffRef (Index)
Unusable & coeffRef (Index, Index)
Protected Types
typedef internal::ref_selector< Derived >::type DerivedNested
Private Attributes
const DerivedNested m_A
StemFunction * m_f
Detailed Description
template<typename Derived>
class Eigen::MatrixFunctionReturnValue< Derived >
Proxy for the matrix function of some matrix (expression).
Template Parameters
Derived Type of the argument to the matrix function.
This class holds the argument to the matrix function until it is assigned or evaluated for some other reason (so the argument should not be changed in the meantime). It is the return type of matrixBase::matrixFunction() and related functions and most of the time this is the only way it is used.
Member Typedef Documentation
DerivedNested
template<typename Derived > typedef internal::ref_selector<Derived>::type Eigen::MatrixFunctionReturnValue< Derived >::DerivedNested protected
Scalar
template<typename Derived > typedef Derived::Scalar Eigen::MatrixFunctionReturnValue< Derived >::Scalar
StemFunction
template<typename Derived > typedef internal::stem_function<Scalar>::type Eigen::MatrixFunctionReturnValue< Derived >::StemFunction
Constructor & Destructor Documentation
MatrixFunctionReturnValue()
template<typename Derived > Eigen::MatrixFunctionReturnValue< Derived >::MatrixFunctionReturnValue (const Derived & A, StemFunction f) inline
Constructor.
Parameters
[in] A Matrix (expression) forming the argument of the matrix function.
[in] f Stem function for matrix function under consideration.
 : m_A(A), m_f(f) {}
Member Function Documentation
cols()
template<typename Derived > Index Eigen::MatrixFunctionReturnValue< Derived >::cols () const inline
 { return m_A.cols(); }
References Eigen::MatrixFunctionReturnValue< Derived >::m_A.
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
evalTo()
template<typename Derived > template<typename ResultType > void Eigen::MatrixFunctionReturnValue< Derived >::evalTo (ResultType & result) const inline
Compute the matrix function.
Parameters
[out] result f applied to A, where f and A are as in the constructor.
{
     typedef typename internal::nested_eval<Derived, 10>::type NestedEvalType;
     typedef internal::remove_all_t<NestedEvalType> NestedEvalTypeClean;
     typedef internal::traits<NestedEvalTypeClean> Traits;
     typedef std::complex<typename NumTraits<Scalar>::Real> ComplexScalar;
     typedef Matrix<ComplexScalar, Dynamic, Dynamic, 0, Traits::RowsAtCompileTime, Traits::ColsAtCompileTime>
         DynMatrixType;
     typedef internal::MatrixFunctionAtomic<DynMatrixType> AtomicType;
     AtomicType atomic(m_f);
     internal::matrix_function_compute<typename NestedEvalTypeClean::PlainObject>::run(m_A, atomic, result);
   }
References Eigen::MatrixFunctionReturnValue< Derived >::m_A, Eigen::MatrixFunctionReturnValue< Derived >::m_f, and Eigen::internal::matrix_function_compute< MatrixType, IsComplex >::run().
rows()
template<typename Derived > Index Eigen::MatrixFunctionReturnValue< Derived >::rows () const inline
 { return m_A.rows(); }
References Eigen::MatrixFunctionReturnValue< Derived >::m_A.
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
Member Data Documentation
m_A
template<typename Derived > const DerivedNested Eigen::MatrixFunctionReturnValue< Derived >::m_A private
Referenced by Eigen::MatrixFunctionReturnValue< Derived >::cols(), Eigen::MatrixFunctionReturnValue< Derived >::evalTo(), and Eigen::MatrixFunctionReturnValue< Derived >::rows().
m_f
template<typename Derived > StemFunction* Eigen::MatrixFunctionReturnValue< Derived >::m_f private
Referenced by Eigen::MatrixFunctionReturnValue< Derived >::evalTo().
The documentation for this class was generated from the following files:
ForwardDeclarations.h
MatrixFunction.h