MercuryDPM: Eigen::bfloat16_impl::numeric_limits_bfloat16_impl< typename > Struct Template Reference
Eigen::bfloat16_impl::numeric_limits_bfloat16_impl< typename > Struct Template Reference
#include <BFloat16.h>
Static Public Member Functions
static EIGEN_CONSTEXPR Eigen::bfloat16() min ()
static EIGEN_CONSTEXPR Eigen::bfloat16 lowest ()
static EIGEN_CONSTEXPR Eigen::bfloat16() max ()
static EIGEN_CONSTEXPR Eigen::bfloat16 epsilon ()
static EIGEN_CONSTEXPR Eigen::bfloat16 round_error ()
static EIGEN_CONSTEXPR Eigen::bfloat16 infinity ()
static EIGEN_CONSTEXPR Eigen::bfloat16 quiet_NaN ()
static EIGEN_CONSTEXPR Eigen::bfloat16 signaling_NaN ()
static EIGEN_CONSTEXPR Eigen::bfloat16 denorm_min ()
Static Public Attributes
static EIGEN_CONSTEXPR const bool is_specialized = true
static EIGEN_CONSTEXPR const bool is_signed = true
static EIGEN_CONSTEXPR const bool is_integer = false
static EIGEN_CONSTEXPR const bool is_exact = false
static EIGEN_CONSTEXPR const bool has_infinity = true
static EIGEN_CONSTEXPR const bool has_quiet_NaN = true
static EIGEN_CONSTEXPR const bool has_signaling_NaN = true
static EIGEN_DISABLE_DEPRECATED_WARNING EIGEN_CONSTEXPR const std::float_denorm_style has_denorm = std::denorm_present
static EIGEN_CONSTEXPR const bool has_denorm_loss = false
static EIGEN_CONSTEXPR const std::float_round_style round_style = std::numeric_limits<float>::round_style
static EIGEN_CONSTEXPR const bool is_iec559 = true
static EIGEN_CONSTEXPR const bool is_bounded = true
static EIGEN_CONSTEXPR const bool is_modulo = false
static EIGEN_CONSTEXPR const int digits = 8
static EIGEN_CONSTEXPR const int digits10 = 2
static EIGEN_CONSTEXPR const int max_digits10 = 4
static EIGEN_CONSTEXPR const int radix = std::numeric_limits<float>::radix
static EIGEN_CONSTEXPR const int min_exponent = std::numeric_limits<float>::min_exponent
static EIGEN_CONSTEXPR const int min_exponent10 = std::numeric_limits<float>::min_exponent10
static EIGEN_CONSTEXPR const int max_exponent = std::numeric_limits<float>::max_exponent
static EIGEN_CONSTEXPR const int max_exponent10 = std::numeric_limits<float>::max_exponent10
static EIGEN_CONSTEXPR const bool traps = std::numeric_limits<float>::traps
static EIGEN_CONSTEXPR const bool tinyness_before = std::numeric_limits<float>::tinyness_before
Member Function Documentation
denorm_min()
template<typename = void> static EIGEN_CONSTEXPR Eigen::bfloat16 Eigen::bfloat16_impl::numeric_limits_bfloat16_impl< typename >::denorm_min () inline static
 { return Eigen::bfloat16_impl::raw_uint16_to_bfloat16(0x0001); }
References Eigen::bfloat16_impl::raw_uint16_to_bfloat16().
epsilon()
template<typename = void> static EIGEN_CONSTEXPR Eigen::bfloat16 Eigen::bfloat16_impl::numeric_limits_bfloat16_impl< typename >::epsilon () inline static
 { return Eigen::bfloat16_impl::raw_uint16_to_bfloat16(0x3c00); }
References Eigen::bfloat16_impl::raw_uint16_to_bfloat16().
infinity()
template<typename = void> static EIGEN_CONSTEXPR Eigen::bfloat16 Eigen::bfloat16_impl::numeric_limits_bfloat16_impl< typename >::infinity () inline static
 { return Eigen::bfloat16_impl::raw_uint16_to_bfloat16(0x7f80); }
References Eigen::bfloat16_impl::raw_uint16_to_bfloat16().
lowest()
template<typename = void> static EIGEN_CONSTEXPR Eigen::bfloat16 Eigen::bfloat16_impl::numeric_limits_bfloat16_impl< typename >::lowest () inline static
 { return Eigen::bfloat16_impl::raw_uint16_to_bfloat16(0xff7f); }
References Eigen::bfloat16_impl::raw_uint16_to_bfloat16().
max()
template<typename = void> static EIGEN_CONSTEXPR Eigen::bfloat16() Eigen::bfloat16_impl::numeric_limits_bfloat16_impl< typename >::max () inline static
 { return Eigen::bfloat16_impl::raw_uint16_to_bfloat16(0x7f7f); }
References Eigen::bfloat16_impl::raw_uint16_to_bfloat16().
min()
template<typename = void> static EIGEN_CONSTEXPR Eigen::bfloat16() Eigen::bfloat16_impl::numeric_limits_bfloat16_impl< typename >::min () inline static
 { return Eigen::bfloat16_impl::raw_uint16_to_bfloat16(0x0080); }
References Eigen::bfloat16_impl::raw_uint16_to_bfloat16().
quiet_NaN()
template<typename = void> static EIGEN_CONSTEXPR Eigen::bfloat16 Eigen::bfloat16_impl::numeric_limits_bfloat16_impl< typename >::quiet_NaN () inline static
 { return Eigen::bfloat16_impl::raw_uint16_to_bfloat16(0x7fc0); }
References Eigen::bfloat16_impl::raw_uint16_to_bfloat16().
round_error()
template<typename = void> static EIGEN_CONSTEXPR Eigen::bfloat16 Eigen::bfloat16_impl::numeric_limits_bfloat16_impl< typename >::round_error () inline static
 { return Eigen::bfloat16_impl::raw_uint16_to_bfloat16(0x3f00); }
References Eigen::bfloat16_impl::raw_uint16_to_bfloat16().
signaling_NaN()
template<typename = void> static EIGEN_CONSTEXPR Eigen::bfloat16 Eigen::bfloat16_impl::numeric_limits_bfloat16_impl< typename >::signaling_NaN () inline static
{
     return Eigen::bfloat16_impl::raw_uint16_to_bfloat16(0x7fa0);
   }
References Eigen::bfloat16_impl::raw_uint16_to_bfloat16().
Member Data Documentation
digits
template<typename T > EIGEN_CONSTEXPR const int Eigen::bfloat16_impl::numeric_limits_bfloat16_impl< T >::digits = 8 static
digits10
template<typename T > EIGEN_CONSTEXPR const int Eigen::bfloat16_impl::numeric_limits_bfloat16_impl< T >::digits10 = 2 static
has_denorm
template<typename T > EIGEN_DISABLE_DEPRECATED_WARNING EIGEN_CONSTEXPR const std::float_denorm_style Eigen::bfloat16_impl::numeric_limits_bfloat16_impl< T >::has_denorm = std::denorm_present static
has_denorm_loss
template<typename T > EIGEN_CONSTEXPR const bool Eigen::bfloat16_impl::numeric_limits_bfloat16_impl< T >::has_denorm_loss = false static
has_infinity
template<typename T > EIGEN_CONSTEXPR const bool Eigen::bfloat16_impl::numeric_limits_bfloat16_impl< T >::has_infinity = true static
has_quiet_NaN
template<typename T > EIGEN_CONSTEXPR const bool Eigen::bfloat16_impl::numeric_limits_bfloat16_impl< T >::has_quiet_NaN = true static
has_signaling_NaN
template<typename T > EIGEN_CONSTEXPR const bool Eigen::bfloat16_impl::numeric_limits_bfloat16_impl< T >::has_signaling_NaN = true static
is_bounded
template<typename T > EIGEN_CONSTEXPR const bool Eigen::bfloat16_impl::numeric_limits_bfloat16_impl< T >::is_bounded = true static
is_exact
template<typename T > EIGEN_CONSTEXPR const bool Eigen::bfloat16_impl::numeric_limits_bfloat16_impl< T >::is_exact = false static
is_iec559
template<typename T > EIGEN_CONSTEXPR const bool Eigen::bfloat16_impl::numeric_limits_bfloat16_impl< T >::is_iec559 = true static
is_integer
template<typename T > EIGEN_CONSTEXPR const bool Eigen::bfloat16_impl::numeric_limits_bfloat16_impl< T >::is_integer = false static
is_modulo
template<typename T > EIGEN_CONSTEXPR const bool Eigen::bfloat16_impl::numeric_limits_bfloat16_impl< T >::is_modulo = false static
is_signed
template<typename T > EIGEN_CONSTEXPR const bool Eigen::bfloat16_impl::numeric_limits_bfloat16_impl< T >::is_signed = true static
is_specialized
template<typename T > EIGEN_CONSTEXPR const bool Eigen::bfloat16_impl::numeric_limits_bfloat16_impl< T >::is_specialized = true static
max_digits10
template<typename T > EIGEN_CONSTEXPR const int Eigen::bfloat16_impl::numeric_limits_bfloat16_impl< T >::max_digits10 = 4 static
max_exponent
template<typename T > EIGEN_CONSTEXPR const int Eigen::bfloat16_impl::numeric_limits_bfloat16_impl< T >::max_exponent = std::numeric_limits<float>::max_exponent static
max_exponent10
template<typename T > EIGEN_CONSTEXPR const int Eigen::bfloat16_impl::numeric_limits_bfloat16_impl< T >::max_exponent10 = std::numeric_limits<float>::max_exponent10 static
min_exponent
template<typename T > EIGEN_CONSTEXPR const int Eigen::bfloat16_impl::numeric_limits_bfloat16_impl< T >::min_exponent = std::numeric_limits<float>::min_exponent static
min_exponent10
template<typename T > EIGEN_CONSTEXPR const int Eigen::bfloat16_impl::numeric_limits_bfloat16_impl< T >::min_exponent10 = std::numeric_limits<float>::min_exponent10 static
radix
template<typename T > EIGEN_CONSTEXPR const int Eigen::bfloat16_impl::numeric_limits_bfloat16_impl< T >::radix = std::numeric_limits<float>::radix static
round_style
template<typename T > EIGEN_CONSTEXPR const std::float_round_style Eigen::bfloat16_impl::numeric_limits_bfloat16_impl< T >::round_style = std::numeric_limits<float>::round_style static
tinyness_before
template<typename T > EIGEN_CONSTEXPR const bool Eigen::bfloat16_impl::numeric_limits_bfloat16_impl< T >::tinyness_before = std::numeric_limits<float>::tinyness_before static
traps
template<typename T > EIGEN_CONSTEXPR const bool Eigen::bfloat16_impl::numeric_limits_bfloat16_impl< T >::traps = std::numeric_limits<float>::traps static
The documentation for this struct was generated from the following file:
BFloat16.h