MercuryDPM: TorsionFrictionSelfTest.cpp File Reference
TorsionFrictionSelfTest.cpp File Reference
#include <Mercury3D.h>
#include <Species/LinearViscoelasticFrictionSpecies.h>
Classes
class DPM
In this file a cubic packing of 5^3 particles in a tri-axial box is created and allowed to settle under small gravity. After that Z statistics are calculated.
Functions
int main (int argc UNUSED, char *argv[] UNUSED)
Function Documentation
main()
int main (int argc UNUSED, char *argv[] UNUSED)
 {
     DPM dpm;
     dpm.solve();
     logger(INFO,"Run gnuplot %.gnu --persist to view output; you should see that the torque is capped at torsionfriction*radius*normalForce, then oscillates and decays",dpm.getName());
     helpers::writeToFile(dpm.getName()+".gnu",
                          "set xlabel 'time'\n"
                          "set ylabel 'torque'\n"
                          "p 'TorsionFrictionSelfTest.torque' u 1:2 w l t 'torque', '' u 1:(0.1*0.5*$3) w l t 'torsionfriction*radius*normalForce'"
     );
 }
References DPMBase::getName(), INFO, logger, DPMBase::solve(), and helpers::writeToFile().