MercuryDPM: oomph::PVDEquationsBase< DIM > Class Template Reference
oomph::PVDEquationsBase< DIM > Class Template Reference abstract
#include <solid_elements.h>
Public Types
typedef void(* IsotropicGrowthFctPt) (const Vector< double > &xi, double &gamma)
typedef double(* PrestressFctPt) (const unsigned &i, const unsigned &j, const Vector< double > &xi)
typedef void(* BodyForceFctPt) (const double &t, const Vector< double > &xi, Vector< double > &b)
Public Types inherited from oomph::SolidFiniteElement
typedef double(* MultiplierFctPt) (const Vector< double > &xi)
Public Types inherited from oomph::FiniteElement
typedef void(* SteadyExactSolutionFctPt) (const Vector< double > &, Vector< double > &)
typedef void(* UnsteadyExactSolutionFctPt) (const double &, const Vector< double > &, Vector< double > &)
Public Member Functions
PVDEquationsBase ()
ConstitutiveLaw *& constitutive_law_pt ()
Return the constitutive law pointer.
const double & lambda_sq () const
Access function for timescale ratio (nondim density)
double *& lambda_sq_pt ()
Access function for pointer to timescale ratio (nondim density)
IsotropicGrowthFctPt & isotropic_growth_fct_pt ()
Access function: Pointer to isotropic growth function.
PrestressFctPt & prestress_fct_pt ()
Access function: Pointer to pre-stress function.
IsotropicGrowthFctPt isotropic_growth_fct_pt () const
Access function: Pointer to isotropic growth function (const version)
BodyForceFctPt & body_force_fct_pt ()
Access function: Pointer to body force function.
BodyForceFctPt body_force_fct_pt () const
Access function: Pointer to body force function (const version)
void enable_inertia ()
Switch on solid inertia.
void disable_inertia ()
Switch off solid inertia.
bool is_inertia_enabled () const
Access function to flag that switches inertia on/off (const version)
virtual unsigned npres_solid () const
virtual int solid_p_local_eqn (const unsigned &i) const
virtual int solid_p_nodal_index () const
virtual void unpin_elemental_solid_pressure_dofs ()=0
Unpin all solid pressure dofs in the element.
virtual void pin_elemental_redundant_nodal_solid_pressures ()
Pin the element's redundant solid pressures (needed for refinement)
virtual void get_stress (const Vector< double > &s, DenseMatrix< double > &sigma)=0
void get_strain (const Vector< double > &s, DenseMatrix< double > &strain) const
Return the strain tensor.
void get_energy (double &pot_en, double &kin_en)
Get potential (strain) and kinetic energy.
void get_deformed_covariant_basis_vectors (const Vector< double > &s, DenseMatrix< double > &def_covariant_basis)
void get_principal_stress (const Vector< double > &s, DenseMatrix< double > &principal_stress_vector, Vector< double > &principal_stress)
virtual void get_isotropic_growth (const unsigned &ipt, const Vector< double > &s, const Vector< double > &xi, double &gamma) const
void body_force (const Vector< double > &xi, Vector< double > &b) const
unsigned ndof_types () const
returns the number of DOF types associated with this element.
void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned >> &dof_lookup_list) const
void enable_evaluate_jacobian_by_fd ()
Set Jacobian to be evaluated by FD? Else: Analytically.
void disable_evaluate_jacobian_by_fd ()
Set Jacobian to be evaluated analytically Else: by FD.
bool is_jacobian_evaluated_by_fd () const
Return the flag indicating whether the jacobian is evaluated by fd.
double prestress (const unsigned &i, const unsigned &j, const Vector< double > xi)
Public Member Functions inherited from oomph::SolidFiniteElement
void set_lagrangian_dimension (const unsigned &lagrangian_dimension)
virtual bool has_internal_solid_data ()
SolidFiniteElement ()
Constructor: Set defaults.
virtual ~SolidFiniteElement ()
Destructor to clean up any allocated memory.
SolidFiniteElement (const SolidFiniteElement &)=delete
Broken copy constructor.
unsigned ngeom_data () const
Broken assignment operator.
Data * geom_data_pt (const unsigned &j)
void identify_geometric_data (std::set< Data * > &geometric_data_pt)
double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
virtual void get_x_and_xi (const Vector< double > &s, Vector< double > &x_fe, Vector< double > &x, Vector< double > &xi_fe, Vector< double > &xi) const
virtual void set_macro_elem_pt (MacroElement *macro_elem_pt)
virtual void set_macro_elem_pt (MacroElement *macro_elem_pt, MacroElement *undeformed_macro_elem_pt)
void set_undeformed_macro_elem_pt (MacroElement *undeformed_macro_elem_pt)
MacroElement * undeformed_macro_elem_pt ()
Access function to pointer to "undeformed" macro element.
double dshape_lagrangian (const Vector< double > &s, Shape &psi, DShape &dpsidxi) const
virtual double dshape_lagrangian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidxi) const
double d2shape_lagrangian (const Vector< double > &s, Shape &psi, DShape &dpsidxi, DShape &d2psidxi) const
virtual double d2shape_lagrangian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidxi, DShape &d2psidxi) const
unsigned lagrangian_dimension () const
unsigned nnodal_lagrangian_type () const
Node * construct_node (const unsigned &n)
Construct the local node n and return a pointer to it.
Node * construct_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
Node * construct_boundary_node (const unsigned &n)
Node * construct_boundary_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
virtual void assign_all_generic_local_eqn_numbers (const bool &store_local_dof_pt)
void describe_local_dofs (std::ostream &out, const std::string &current_string) const
double raw_lagrangian_position (const unsigned &n, const unsigned &i) const
double raw_lagrangian_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double lagrangian_position (const unsigned &n, const unsigned &i) const
Return i-th Lagrangian coordinate at local node n.
double lagrangian_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
virtual double interpolated_xi (const Vector< double > &s, const unsigned &i) const
virtual void interpolated_xi (const Vector< double > &s, Vector< double > &xi) const
virtual void interpolated_dxids (const Vector< double > &s, DenseMatrix< double > &dxids) const
virtual void J_lagrangian (const Vector< double > &s) const
virtual double J_lagrangian_at_knot (const unsigned &ipt) const
SolidInitialCondition *& solid_ic_pt ()
Pointer to object that describes the initial condition.
void enable_solve_for_consistent_newmark_accel ()
void disable_solve_for_consistent_newmark_accel ()
Set to reset the problem being solved to be the standard problem.
MultiplierFctPt & multiplier_fct_pt ()
MultiplierFctPt multiplier_fct_pt () const
virtual void get_residuals_for_solid_ic (Vector< double > &residuals)
void fill_in_residuals_for_solid_ic (Vector< double > &residuals)
void fill_in_jacobian_for_solid_ic (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_jacobian_for_newmark_accel (DenseMatrix< double > &jacobian)
void compute_norm (double &el_norm)
int position_local_eqn (const unsigned &n, const unsigned &k, const unsigned &j) const
Public Member Functions inherited from oomph::FiniteElement
void set_dimension (const unsigned &dim)
void set_nodal_dimension (const unsigned &nodal_dim)
void set_nnodal_position_type (const unsigned &nposition_type)
Set the number of types required to interpolate the coordinate.
void set_n_node (const unsigned &n)
int nodal_local_eqn (const unsigned &n, const unsigned &i) const
double dJ_eulerian_at_knot (const unsigned &ipt, Shape &psi, DenseMatrix< double > &djacobian_dX) const
FiniteElement ()
Constructor.
virtual ~FiniteElement ()
FiniteElement (const FiniteElement &)=delete
Broken copy constructor.
virtual bool local_coord_is_valid (const Vector< double > &s)
Broken assignment operator.
virtual void move_local_coord_back_into_element (Vector< double > &s) const
void get_centre_of_gravity_and_max_radius_in_terms_of_zeta (Vector< double > &cog, double &max_radius) const
virtual void local_coordinate_of_node (const unsigned &j, Vector< double > &s) const
virtual void local_fraction_of_node (const unsigned &j, Vector< double > &s_fraction)
virtual double local_one_d_fraction_of_node (const unsigned &n1d, const unsigned &i)
MacroElement * macro_elem_pt ()
Access function to pointer to macro element.
void get_x (const Vector< double > &s, Vector< double > &x) const
void get_x (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void get_x_from_macro_element (const Vector< double > &s, Vector< double > &x) const
virtual void get_x_from_macro_element (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void set_integration_scheme (Integral *const &integral_pt)
Set the spatial integration scheme.
Integral *const & integral_pt () const
Return the pointer to the integration scheme (const version)
virtual void shape (const Vector< double > &s, Shape &psi) const =0
virtual void shape_at_knot (const unsigned &ipt, Shape &psi) const
virtual void dshape_local (const Vector< double > &s, Shape &psi, DShape &dpsids) const
virtual void dshape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids) const
virtual void d2shape_local (const Vector< double > &s, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual void d2shape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual double J_eulerian (const Vector< double > &s) const
virtual double J_eulerian_at_knot (const unsigned &ipt) const
void check_J_eulerian_at_knots (bool &passed) const
void check_jacobian (const double &jacobian) const
double dshape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsi, DenseMatrix< double > &djacobian_dX, RankFourTensor< double > &d_dpsidx_dX) const
double d2shape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual double d2shape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual void assign_nodal_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void describe_nodal_local_dofs (std::ostream &out, const std::string &current_string) const
Node *& node_pt (const unsigned &n)
Return a pointer to the local node n.
Node *const & node_pt (const unsigned &n) const
Return a pointer to the local node n (const version)
unsigned nnode () const
Return the number of nodes.
virtual unsigned nnode_1d () const
double raw_nodal_position (const unsigned &n, const unsigned &i) const
double raw_nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position (const unsigned &n, const unsigned &i) const
double nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double dnodal_position_dt (const unsigned &n, const unsigned &i) const
Return the i-th component of nodal velocity: dx/dt at local node n.
double dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
virtual void get_dresidual_dnodal_coordinates (RankThreeTensor< double > &dresidual_dnodal_coordinates)
virtual void disable_ALE ()
virtual void enable_ALE ()
virtual unsigned required_nvalue (const unsigned &n) const
unsigned nnodal_position_type () const
bool has_hanging_nodes () const
unsigned nodal_dimension () const
Return the required Eulerian dimension of the nodes in this element.
virtual unsigned nvertex_node () const
virtual Node * vertex_node_pt (const unsigned &j) const
int get_node_number (Node *const &node_pt) const
virtual Node * get_node_at_local_coordinate (const Vector< double > &s) const
double raw_nodal_value (const unsigned &n, const unsigned &i) const
double raw_nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
unsigned dim () const
virtual ElementGeometry::ElementGeometry element_geometry () const
Return the geometry type of the element (either Q or T usually).
virtual double interpolated_x (const Vector< double > &s, const unsigned &i) const
Return FE interpolated coordinate x[i] at local coordinate s.
virtual double interpolated_x (const unsigned &t, const Vector< double > &s, const unsigned &i) const
virtual void interpolated_x (const Vector< double > &s, Vector< double > &x) const
Return FE interpolated position x[] at local coordinate s as Vector.
virtual void interpolated_x (const unsigned &t, const Vector< double > &s, Vector< double > &x) const
virtual double interpolated_dxdt (const Vector< double > &s, const unsigned &i, const unsigned &t)
virtual void interpolated_dxdt (const Vector< double > &s, const unsigned &t, Vector< double > &dxdt)
void position (const Vector< double > &zeta, Vector< double > &r) const
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
void dposition_dt (const Vector< double > &zeta, const unsigned &t, Vector< double > &drdt)
void interpolated_zeta (const Vector< double > &s, Vector< double > &zeta) const
void locate_zeta (const Vector< double > &zeta, GeomObject *&geom_object_pt, Vector< double > &s, const bool &use_coordinate_as_initial_guess=false)
virtual void node_update ()
virtual void identify_field_data_for_interactions (std::set< std::pair< Data *, unsigned >> &paired_field_data)
virtual double s_min () const
Min value of local coordinate.
virtual double s_max () const
Max. value of local coordinate.
double size () const
virtual double compute_physical_size () const
virtual void point_output_data (const Vector< double > &s, Vector< double > &data)
void point_output (std::ostream &outfile, const Vector< double > &s)
virtual unsigned nplot_points_paraview (const unsigned &nplot) const
virtual unsigned nsub_elements_paraview (const unsigned &nplot) const
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_output_offset_information (std::ofstream &file_out, const unsigned &nplot, unsigned &counter) const
virtual void write_paraview_type (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_offsets (std::ofstream &file_out, const unsigned &nplot, unsigned &offset_sum) const
virtual unsigned nscalar_paraview () const
virtual void scalar_value_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
virtual std::string scalar_name_paraview (const unsigned &i) const
virtual void output (std::ostream &outfile)
virtual void output (std::ostream &outfile, const unsigned &n_plot)
virtual void output (const unsigned &t, std::ostream &outfile, const unsigned &n_plot) const
virtual void output (FILE *file_pt)
virtual void output (FILE *file_pt, const unsigned &n_plot)
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output an exact solution over the element.
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output a time-dependent exact solution over the element.
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, const SolutionFunctorBase &exact_soln) const
Output a time-dependent exact solution over the element.
virtual void get_s_plot (const unsigned &i, const unsigned &nplot, Vector< double > &s, const bool &shifted_to_interior=false) const
virtual std::string tecplot_zone_string (const unsigned &nplot) const
virtual void write_tecplot_zone_footer (std::ostream &outfile, const unsigned &nplot) const
virtual void write_tecplot_zone_footer (FILE *file_pt, const unsigned &nplot) const
virtual unsigned nplot_points (const unsigned &nplot) const
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_abs_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error)
void integrate_fct (FiniteElement::SteadyExactSolutionFctPt integrand_fct_pt, Vector< double > &integral)
Integrate Vector-valued function over element.
void integrate_fct (FiniteElement::UnsteadyExactSolutionFctPt integrand_fct_pt, const double &time, Vector< double > &integral)
Integrate Vector-valued time-dep function over element.
virtual void build_face_element (const int &face_index, FaceElement *face_element_pt)
virtual unsigned self_test ()
virtual unsigned get_bulk_node_number (const int &face_index, const unsigned &i) const
virtual int face_outer_unit_normal_sign (const int &face_index) const
Get the sign of the outer unit normal on the face given by face_index.
virtual unsigned nnode_on_face () const
void face_node_number_error_check (const unsigned &i) const
Range check for face node numbers.
virtual CoordinateMappingFctPt face_to_bulk_coordinate_fct_pt (const int &face_index) const
virtual BulkCoordinateDerivativesFctPt bulk_coordinate_derivatives_fct_pt (const int &face_index) const
Public Member Functions inherited from oomph::GeneralisedElement
GeneralisedElement ()
Constructor: Initialise all pointers and all values to zero.
virtual ~GeneralisedElement ()
Virtual destructor to clean up any memory allocated by the object.
GeneralisedElement (const GeneralisedElement &)=delete
Broken copy constructor.
void operator= (const GeneralisedElement &)=delete
Broken assignment operator.
Data *& internal_data_pt (const unsigned &i)
Return a pointer to i-th internal data object.
Data *const & internal_data_pt (const unsigned &i) const
Return a pointer to i-th internal data object (const version)
Data *& external_data_pt (const unsigned &i)
Return a pointer to i-th external data object.
Data *const & external_data_pt (const unsigned &i) const
Return a pointer to i-th external data object (const version)
unsigned long eqn_number (const unsigned &ieqn_local) const
int local_eqn_number (const unsigned long &ieqn_global) const
unsigned add_external_data (Data *const &data_pt, const bool &fd=true)
bool external_data_fd (const unsigned &i) const
void exclude_external_data_fd (const unsigned &i)
void include_external_data_fd (const unsigned &i)
void flush_external_data ()
Flush all external data.
void flush_external_data (Data *const &data_pt)
Flush the object addressed by data_pt from the external data array.
unsigned ninternal_data () const
Return the number of internal data objects.
unsigned nexternal_data () const
Return the number of external data objects.
unsigned ndof () const
Return the number of equations/dofs in the element.
void dof_vector (const unsigned &t, Vector< double > &dof)
Return the vector of dof values at time level t.
void dof_pt_vector (Vector< double * > &dof_pt)
Return the vector of pointers to dof values.
void set_internal_data_time_stepper (const unsigned &i, TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void assign_internal_eqn_numbers (unsigned long &global_number, Vector< double * > &Dof_pt)
void describe_dofs (std::ostream &out, const std::string &current_string) const
void add_internal_value_pt_to_map (std::map< unsigned, double * > &map_of_value_pt)
virtual void assign_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void complete_setup_of_dependencies ()
virtual void get_residuals (Vector< double > &residuals)
virtual void get_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
virtual void get_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void get_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void get_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void get_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void get_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void get_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void get_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void get_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
virtual void compute_norm (Vector< double > &norm)
Public Member Functions inherited from oomph::GeomObject
GeomObject ()
Default constructor.
GeomObject (const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim, TimeStepper *time_stepper_pt)
GeomObject (const GeomObject &dummy)=delete
Broken copy constructor.
void operator= (const GeomObject &)=delete
Broken assignment operator.
virtual ~GeomObject ()
(Empty) destructor
unsigned nlagrangian () const
Access function to # of Lagrangian coordinates.
unsigned ndim () const
Access function to # of Eulerian coordinates.
void set_nlagrangian_and_ndim (const unsigned &n_lagrangian, const unsigned &n_dim)
Set # of Lagrangian and Eulerian coordinates.
TimeStepper *& time_stepper_pt ()
TimeStepper * time_stepper_pt () const
virtual void position (const double &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void dposition (const Vector< double > &zeta, DenseMatrix< double > &drdzeta) const
virtual void d2position (const Vector< double > &zeta, RankThreeTensor< double > &ddrdzeta) const
virtual void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
Static Public Member Functions
static void pin_redundant_nodal_solid_pressures (const Vector< GeneralisedElement * > &element_pt)
static void unpin_all_solid_pressure_dofs (const Vector< GeneralisedElement * > &element_pt)
Unpin all pressure dofs in elements listed in vector.
Protected Attributes
IsotropicGrowthFctPt Isotropic_growth_fct_pt
Pointer to isotropic growth function.
PrestressFctPt Prestress_fct_pt
Pointer to prestress function.
ConstitutiveLaw * Constitutive_law_pt
Pointer to the constitutive law.
double * Lambda_sq_pt
Timescale ratio (non-dim. density)
bool Unsteady
Flag that switches inertia on/off.
BodyForceFctPt Body_force_fct_pt
Pointer to body force function.
bool Evaluate_jacobian_by_fd
Use FD to evaluate Jacobian.
Protected Attributes inherited from oomph::SolidFiniteElement
MacroElement * Undeformed_macro_elem_pt
Pointer to the element's "undeformed" macro element (NULL by default)
SolidInitialCondition * Solid_ic_pt
Pointer to object that specifies the initial condition.
bool Solve_for_consistent_newmark_accel_flag
Protected Attributes inherited from oomph::FiniteElement
MacroElement * Macro_elem_pt
Pointer to the element's macro element (NULL by default)
Protected Attributes inherited from oomph::GeomObject
unsigned NLagrangian
Number of Lagrangian (intrinsic) coordinates.
unsigned Ndim
Number of Eulerian coordinates.
TimeStepper * Geom_object_time_stepper_pt
Static Protected Attributes
static double Default_lambda_sq_value = 1.0
Static default value for timescale ratio (1.0 – for natural scaling)
Static Protected Attributes inherited from oomph::FiniteElement
static const unsigned Default_Initial_Nvalue = 0
Default value for the number of values at a node.
static const double Node_location_tolerance = 1.0e-14
static const unsigned N2deriv [] = {0, 1, 3, 6}
Static Protected Attributes inherited from oomph::GeneralisedElement
static DenseMatrix< double > Dummy_matrix
static std::deque< double * > Dof_pt_deque
Static Private Attributes
static int Solid_pressure_not_stored_at_node = -100
Additional Inherited Members
Static Public Attributes inherited from oomph::FiniteElement
static double Tolerance_for_singular_jacobian = 1.0e-16
Tolerance below which the jacobian is considered singular.
static bool Accept_negative_jacobian = false
static bool Suppress_output_while_checking_for_inverted_elements
Static Public Attributes inherited from oomph::GeneralisedElement
static bool Suppress_warning_about_repeated_internal_data
static bool Suppress_warning_about_repeated_external_data = true
static double Default_fd_jacobian_step = 1.0e-8
Protected Member Functions inherited from oomph::SolidFiniteElement
void fill_in_generic_jacobian_for_solid_ic (Vector< double > &residuals, DenseMatrix< double > &jacobian, const unsigned &flag)
void set_nnodal_lagrangian_type (const unsigned &nlagrangian_type)
virtual double local_to_lagrangian_mapping (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
double local_to_lagrangian_mapping (const DShape &dpsids, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_lagrangian_mapping_diagonal (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual void assign_solid_local_eqn_numbers (const bool &store_local_dof)
Assign local equation numbers for the solid equations in the element.
void describe_solid_local_dofs (std::ostream &out, const std::string &current_string) const
Classifies dofs locally for solid specific aspects.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
virtual void fill_in_jacobian_from_solid_position_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_jacobian_from_solid_position_by_fd (DenseMatrix< double > &jacobian)
virtual void update_before_solid_position_fd ()
virtual void reset_after_solid_position_fd ()
virtual void update_in_solid_position_fd (const unsigned &i)
virtual void reset_in_solid_position_fd (const unsigned &i)
Protected Member Functions inherited from oomph::FiniteElement
virtual void assemble_local_to_eulerian_jacobian (const DShape &dpsids, DenseMatrix< double > &jacobian) const
virtual void assemble_local_to_eulerian_jacobian2 (const DShape &d2psids, DenseMatrix< double > &jacobian2) const
virtual void assemble_eulerian_base_vectors (const DShape &dpsids, DenseMatrix< double > &interpolated_G) const
template<unsigned DIM>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double invert_jacobian_mapping (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping_diagonal (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual void dJ_eulerian_dnodal_coordinates (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<unsigned DIM>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
virtual void d_dshape_eulerian_dnodal_coordinates (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<unsigned DIM>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
virtual void transform_derivatives (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
void transform_derivatives_diagonal (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
virtual void transform_second_derivatives (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
virtual void fill_in_jacobian_from_nodal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_jacobian_from_nodal_by_fd (DenseMatrix< double > &jacobian)
virtual void update_before_nodal_fd ()
virtual void reset_after_nodal_fd ()
virtual void update_in_nodal_fd (const unsigned &i)
virtual void reset_in_nodal_fd (const unsigned &i)
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Zero-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
One-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Two-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
Protected Member Functions inherited from oomph::GeneralisedElement
unsigned add_internal_data (Data *const &data_pt, const bool &fd=true)
bool internal_data_fd (const unsigned &i) const
void exclude_internal_data_fd (const unsigned &i)
void include_internal_data_fd (const unsigned &i)
void clear_global_eqn_numbers ()
void add_global_eqn_numbers (std::deque< unsigned long > const &global_eqn_numbers, std::deque< double * > const &global_dof_pt)
virtual void assign_internal_and_external_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void assign_additional_local_eqn_numbers ()
int internal_local_eqn (const unsigned &i, const unsigned &j) const
int external_local_eqn (const unsigned &i, const unsigned &j)
virtual void fill_in_contribution_to_residuals (Vector< double > &residuals)
void fill_in_jacobian_from_internal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_internal_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
virtual void update_before_internal_fd ()
virtual void reset_after_internal_fd ()
virtual void update_in_internal_fd (const unsigned &i)
virtual void reset_in_internal_fd (const unsigned &i)
virtual void update_before_external_fd ()
virtual void reset_after_external_fd ()
virtual void update_in_external_fd (const unsigned &i)
virtual void reset_in_external_fd (const unsigned &i)
virtual void fill_in_contribution_to_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void fill_in_contribution_to_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void fill_in_contribution_to_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void fill_in_contribution_to_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void fill_in_contribution_to_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
Detailed Description
template<unsigned DIM>
class oomph::PVDEquationsBase< DIM >
A base class for elements that solve the equations of solid mechanics, based on the principle of virtual displacements in Cartesian coordinates. Combines a few generic functions that are shared by PVDEquations and PVDEquationsWithPressure.
Member Typedef Documentation
BodyForceFctPt
template<unsigned DIM> typedef void(* oomph::PVDEquationsBase< DIM >::BodyForceFctPt) (const double &t, const Vector< double > &xi, Vector< double > &b)
Function pointer to function that specifies the body force as a function of the Lagrangian coordinates and time FCT(t,xi,b) – xi and b are Vectors!
IsotropicGrowthFctPt
template<unsigned DIM> typedef void(* oomph::PVDEquationsBase< DIM >::IsotropicGrowthFctPt) (const Vector< double > &xi, double &gamma)
Function pointer to function that specifies the isotropic growth as a function of the Lagrangian coordinates FCT(xi,gamma(xi)) – xi is a Vector!
PrestressFctPt
template<unsigned DIM> typedef double(* oomph::PVDEquationsBase< DIM >::PrestressFctPt) (const unsigned &i, const unsigned &j, const Vector< double > &xi)
Function pointer to function that specifies the pre-stress sigma_0(i,j) as a function of the Lagrangian coordinates FCT(i,j,xi) – xi is a Vector!
Constructor & Destructor Documentation
PVDEquationsBase()
template<unsigned DIM> oomph::PVDEquationsBase< DIM >::PVDEquationsBase () inline
Constructor: Set null pointers for constitutive law and for isotropic growth function. Set physical parameter values to default values, enable inertia and set body force to zero. Default evaluation of Jacobian: analytically rather than by FD.
       : Isotropic_growth_fct_pt(0),
         Prestress_fct_pt(0),
         Constitutive_law_pt(0),
         Lambda_sq_pt(&Default_lambda_sq_value),
         Unsteady(true),
         Body_force_fct_pt(0),
         Evaluate_jacobian_by_fd(false)
     {
     }
Member Function Documentation
body_force()
template<unsigned DIM> void oomph::PVDEquationsBase< DIM >::body_force (const Vector< double > & xi, Vector< double > & b) const inline
Evaluate body force at Lagrangian coordinate xi at present time (returns zero vector if no body force function pointer has been set)
     {
       // If no function has been set, return zero vector
       if (Body_force_fct_pt == 0)
       {
         // Get spatial dimension of element
         unsigned n = dim();
         for (unsigned i = 0; i < n; i++)
         {
           b[i] = 0.0;
         }
       }
       else
       {
         // Get time from timestepper of first node (note that this must
         // work -- body force only makes sense for elements that can be
         // deformed and given that the deformation of solid finite elements
         // is controlled by their nodes, nodes must exist!)
         double time = node_pt(0)->time_stepper_pt()->time_pt()->time();
         // Now evaluate the body force
         (*Body_force_fct_pt)(time, xi, b);
       }
     }
References b, oomph::PVDEquationsBase< DIM >::Body_force_fct_pt, oomph::FiniteElement::dim(), i, n, oomph::FiniteElement::node_pt(), oomph::Time::time(), oomph::TimeStepper::time_pt(), and oomph::Data::time_stepper_pt().
Referenced by oomph::RefineableQDPVDElement< DIM, NNODE_1D >::fill_in_generic_contribution_to_residuals_pvd().
body_force_fct_pt() [1/2]
template<unsigned DIM> BodyForceFctPt& oomph::PVDEquationsBase< DIM >::body_force_fct_pt () inline
Access function: Pointer to body force function.
     {
       return Body_force_fct_pt;
     }
References oomph::PVDEquationsBase< DIM >::Body_force_fct_pt.
Referenced by oomph::RefineablePVDEquations< DIM >::further_build(), and oomph::RefineablePVDEquationsWithPressure< DIM >::further_build().
body_force_fct_pt() [2/2]
template<unsigned DIM> BodyForceFctPt oomph::PVDEquationsBase< DIM >::body_force_fct_pt () const inline
Access function: Pointer to body force function (const version)
     {
       return Body_force_fct_pt;
     }
References oomph::PVDEquationsBase< DIM >::Body_force_fct_pt.
constitutive_law_pt()
template<unsigned DIM> ConstitutiveLaw*& oomph::PVDEquationsBase< DIM >::constitutive_law_pt () inline
Return the constitutive law pointer.
     {
       return Constitutive_law_pt;
     }
References oomph::PVDEquationsBase< DIM >::Constitutive_law_pt.
Referenced by oomph::RefineablePVDEquations< DIM >::further_build(), and oomph::RefineablePVDEquationsWithPressure< DIM >::further_build().
disable_evaluate_jacobian_by_fd()
template<unsigned DIM> void oomph::PVDEquationsBase< DIM >::disable_evaluate_jacobian_by_fd () inline
Set Jacobian to be evaluated analytically Else: by FD.
     {
       Evaluate_jacobian_by_fd = false;
     }
References oomph::PVDEquationsBase< DIM >::Evaluate_jacobian_by_fd.
disable_inertia()
template<unsigned DIM> void oomph::PVDEquationsBase< DIM >::disable_inertia () inline
Switch off solid inertia.
     {
       Unsteady = false;
     }
References oomph::PVDEquationsBase< DIM >::Unsteady.
enable_evaluate_jacobian_by_fd()
template<unsigned DIM> void oomph::PVDEquationsBase< DIM >::enable_evaluate_jacobian_by_fd () inline
Set Jacobian to be evaluated by FD? Else: Analytically.
     {
       Evaluate_jacobian_by_fd = true;
     }
References oomph::PVDEquationsBase< DIM >::Evaluate_jacobian_by_fd.
enable_inertia()
template<unsigned DIM> void oomph::PVDEquationsBase< DIM >::enable_inertia () inline
Switch on solid inertia.
     {
       Unsteady = true;
     }
References oomph::PVDEquationsBase< DIM >::Unsteady.
get_deformed_covariant_basis_vectors()
template<unsigned DIM> void oomph::PVDEquationsBase< DIM >::get_deformed_covariant_basis_vectors (const Vector< double > & s, DenseMatrix< double > & def_covariant_basis)
Return the deformed covariant basis vectors at specified local coordinate: def_covariant_basis(i,j) is the j-th component of the i-th basis vector.
   {
     // Find out how many nodes there are
     unsigned n_node = nnode();
     // Find out how many positional dofs there are
     unsigned n_position_type = this->nnodal_position_type();
     // Set up memory for the shape functions
     Shape psi(n_node, n_position_type);
     DShape dpsidxi(n_node, n_position_type, DIM);
     // Call the derivatives of the shape functions (ignore Jacobian)
     (void)dshape_lagrangian(s, psi, dpsidxi);
     // Initialise to zero
     for (unsigned i = 0; i < DIM; i++)
     {
       for (unsigned j = 0; j < DIM; j++)
       {
         def_covariant_basis(i, j) = 0.0;
       }
     }
     // Calculate displacements and derivatives
     for (unsigned l = 0; l < n_node; l++)
     {
       // Loop over positional dofs
       for (unsigned k = 0; k < n_position_type; k++)
       {
         // Loop over displacement components (deformed position)
         for (unsigned i = 0; i < DIM; i++)
         {
           // Loop over derivative directions (i.e. base vectors)
           for (unsigned j = 0; j < DIM; j++)
           {
             def_covariant_basis(j, i) +=
               nodal_position_gen(l, k, i) * dpsidxi(l, k, j);
           }
         }
       }
     }
   }
References DIM, i, j, k, and s.
get_dof_numbers_for_unknowns()
template<unsigned DIM> void oomph::PVDEquationsBase< DIM >::get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned >> & dof_lookup_list) const inline virtual
Create a list of pairs for all unknowns in this element, so that the first entry in each pair contains the global equation number of the unknown, while the second one contains the number of the "DOF" that this unknown is associated with. (Function can obviously only be called if the equation numbering scheme has been set up.) E.g. in a 3D problem there are 3 types of DOF: 0 - x displacement 1 - y displacement 2 - z displacement
Reimplemented from oomph::GeneralisedElement.
Reimplemented in oomph::PVDEquationsWithPressure< DIM >, oomph::PseudoSolidNodeUpdateElement< TCrouzeixRaviartElement< 2 >, TPVDBubbleEnrichedElement< 2, 3 > >, oomph::PseudoSolidNodeUpdateElement< TTaylorHoodElement< 2 >, TPVDElement< 2, 3 > >, oomph::PseudoSolidNodeUpdateElement< GeneralisedNewtonianAxisymmetricTTaylorHoodElement, TPVDElement< 2, 3 > >, oomph::PseudoSolidNodeUpdateElement< AxisymmetricTTaylorHoodElement, TPVDElement< 2, 3 > >, and oomph::PseudoSolidNodeUpdateElement< GeneralisedNewtonianTTaylorHoodElement< 2 >, TPVDElement< 2, 3 > >.
     {
       // temporary pair (used to store dof lookup prior to being added to list
       std::pair<unsigned, unsigned> dof_lookup;
       // number of nodes
       const unsigned n_node = this->nnode();
       // Get the number of position dofs and dimensions at the node
       const unsigned n_position_type = nnodal_position_type();
       const unsigned nodal_dim = nodal_dimension();
       // Integer storage for local unknown
       int local_unknown = 0;
       // Loop over the nodes
       for (unsigned n = 0; n < n_node; n++)
       {
         // Loop over position dofs
         for (unsigned k = 0; k < n_position_type; k++)
         {
           // Loop over dimension
           for (unsigned i = 0; i < nodal_dim; i++)
           {
             // If the variable is free
             local_unknown = position_local_eqn(n, k, i);
             // ignore pinned values
             if (local_unknown >= 0)
             {
               // store dof lookup in temporary pair: First entry in pair
               // is global equation number; second entry is dof type
               dof_lookup.first = this->eqn_number(local_unknown);
               dof_lookup.second = i;
               // add to list
               dof_lookup_list.push_front(dof_lookup);
             }
           }
         }
       }
     }
References oomph::GeneralisedElement::eqn_number(), i, k, n, oomph::FiniteElement::nnodal_position_type(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_dimension(), and oomph::SolidFiniteElement::position_local_eqn().
get_energy()
template<unsigned DIM> void oomph::PVDEquationsBase< DIM >::get_energy (double & pot_en, double & kin_en)
Get potential (strain) and kinetic energy.
   {
     // Initialise
     pot_en = 0;
     kin_en = 0;
     // Set the value of n_intpt
     unsigned n_intpt = this->integral_pt()->nweight();
     // Set the Vector to hold local coordinates
     Vector<double> s(DIM);
     // Find out how many nodes there are
     const unsigned n_node = this->nnode();
     // Find out how many positional dofs there are
     const unsigned n_position_type = this->nnodal_position_type();
     // Set up memory for the shape functions
     Shape psi(n_node, n_position_type);
     DShape dpsidxi(n_node, n_position_type, DIM);
     // Timescale ratio (non-dim density)
     double lambda_sq = this->lambda_sq();
     // Loop over the integration points
     for (unsigned ipt = 0; ipt < n_intpt; ipt++)
     {
       // Assign values of s
       for (unsigned i = 0; i < DIM; i++)
       {
         s[i] = this->integral_pt()->knot(ipt, i);
       }
       // Get the integral weight
       double w = this->integral_pt()->weight(ipt);
       // Call the derivatives of the shape functions and get Jacobian
       double J = this->dshape_lagrangian_at_knot(ipt, psi, dpsidxi);
       // Storage for Lagrangian coordinates and velocity (initialised to zero)
       Vector<double> interpolated_xi(DIM, 0.0);
       Vector<double> veloc(DIM, 0.0);
       // Calculate lagrangian coordinates
       for (unsigned l = 0; l < n_node; l++)
       {
         // Loop over positional dofs
         for (unsigned k = 0; k < n_position_type; k++)
         {
           // Loop over displacement components (deformed position)
           for (unsigned i = 0; i < DIM; i++)
           {
             // Calculate the Lagrangian coordinates
             interpolated_xi[i] +=
               this->lagrangian_position_gen(l, k, i) * psi(l, k);
             // Calculate the velocity components (if unsteady solve)
             if (this->Unsteady)
             {
               veloc[i] += this->dnodal_position_gen_dt(l, k, i) * psi(l, k);
             }
           }
         }
       }
       // Get isotropic growth factor
       double gamma = 1.0;
       this->get_isotropic_growth(ipt, s, interpolated_xi, gamma);
       // Premultiply the undeformed volume ratio (from the isotropic
       // growth), the weights and the Jacobian
       double W = gamma * w * J;
       DenseMatrix<double> sigma(DIM, DIM);
       DenseMatrix<double> strain(DIM, DIM);
       // Now calculate the stress tensor from the constitutive law
       this->get_stress(s, sigma);
       // Add pre-stress
       for (unsigned i = 0; i < DIM; i++)
       {
         for (unsigned j = 0; j < DIM; j++)
         {
           sigma(i, j) += prestress(i, j, interpolated_xi);
         }
       }
       // get the strain
       this->get_strain(s, strain);
       // Initialise
       double local_pot_en = 0;
       double veloc_sq = 0;
       // Compute integrals
       for (unsigned i = 0; i < DIM; i++)
       {
         for (unsigned j = 0; j < DIM; j++)
         {
           local_pot_en += sigma(i, j) * strain(i, j);
         }
         veloc_sq += veloc[i] * veloc[i];
       }
       pot_en += 0.5 * local_pot_en * W;
       kin_en += lambda_sq * 0.5 * veloc_sq * W;
     }
   }
References DIM, mathsFunc::gamma(), i, J, j, k, s, calibrate::sigma, w, and oomph::QuadTreeNames::W.
get_isotropic_growth()
template<unsigned DIM> virtual void oomph::PVDEquationsBase< DIM >::get_isotropic_growth (const unsigned & ipt, const Vector< double > & s, const Vector< double > & xi, double & gamma) const inline virtual
Evaluate isotropic growth function at Lagrangian coordinate xi and/or local coordinate s. (returns 1, i.e. no growth, if no function pointer has been set) This function is virtual to allow overloading in multi-physics problems where the growth function might be determined by another system of equations
Reimplemented in QThermalPVDElement< DIM >.
     {
       // If no function has been set, return 1
       if (Isotropic_growth_fct_pt == 0)
       {
         gamma = 1.0;
       }
       else
       {
         // Get isotropic growth
         (*Isotropic_growth_fct_pt)(xi, gamma);
       }
     }
References mathsFunc::gamma(), and oomph::PVDEquationsBase< DIM >::Isotropic_growth_fct_pt.
Referenced by oomph::RefineableQDPVDElement< DIM, NNODE_1D >::fill_in_generic_contribution_to_residuals_pvd().
get_principal_stress()
template<unsigned DIM> void oomph::PVDEquationsBase< DIM >::get_principal_stress (const Vector< double > & s, DenseMatrix< double > & principal_stress_vector, Vector< double > & principal_stress)
Compute principal stress vectors and (scalar) principal stresses at specified local coordinate. principal_stress_vector(i,j) is the j-th component of the i-th principal stress vector.
/////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////// Compute principal stress vectors and (scalar) principal stresses at specified local coordinate: principal_stress_vector(i,j) is the j-th component of the i-th principal stress vector.
   {
     // Compute contravariant ("upper") 2nd Piola Kirchhoff stress
     DenseDoubleMatrix sigma(DIM, DIM);
     get_stress(s, sigma);
     // Lagrangian coordinates
     Vector<double> xi(DIM);
     this->interpolated_xi(s, xi);
     // Add pre-stress
     for (unsigned i = 0; i < DIM; i++)
     {
       for (unsigned j = 0; j < DIM; j++)
       {
         sigma(i, j) += this->prestress(i, j, xi);
       }
     }
     // Get covariant base vectors in deformed configuration
     DenseMatrix<double> lower_deformed_basis(DIM);
     get_deformed_covariant_basis_vectors(s, lower_deformed_basis);
     // Work out covariant ("lower") metric tensor
     DenseDoubleMatrix lower_metric(DIM);
     for (unsigned i = 0; i < DIM; i++)
     {
       for (unsigned j = 0; j < DIM; j++)
       {
         lower_metric(i, j) = 0.0;
         for (unsigned k = 0; k < DIM; k++)
         {
           lower_metric(i, j) +=
             lower_deformed_basis(i, k) * lower_deformed_basis(j, k);
         }
       }
     }
     // Work out cartesian components of contravariant ("upper") basis vectors
     DenseMatrix<double> upper_deformed_basis(DIM);
     // Loop over RHSs
     Vector<double> rhs(DIM);
     Vector<double> aux(DIM);
     for (unsigned k = 0; k < DIM; k++)
     {
       for (unsigned l = 0; l < DIM; l++)
       {
         rhs[l] = lower_deformed_basis(l, k);
       }
       lower_metric.solve(rhs, aux);
       for (unsigned l = 0; l < DIM; l++)
       {
         upper_deformed_basis(l, k) = aux[l];
       }
     }
     // Eigenvalues (=principal stresses) and eigenvectors
     DenseMatrix<double> ev(DIM);
     // Get eigenvectors of contravariant 2nd Piola Kirchoff stress
     sigma.eigenvalues_by_jacobi(principal_stress, ev);
     // ev(j,i) is the i-th component of the j-th eigenvector
     // relative to the deformed "lower variance" basis!
     // Work out cartesian components of eigenvectors by multiplying
     // the "lower variance components" by these "upper variance" basis
     // vectors
     // Loop over cartesian compnents
     for (unsigned i = 0; i < DIM; i++)
     {
       // Initialise the row
       for (unsigned j = 0; j < DIM; j++)
       {
         principal_stress_vector(j, i) = 0.0;
       }
       // Loop over basis vectors
       for (unsigned j = 0; j < DIM; j++)
       {
         for (unsigned k = 0; k < DIM; k++)
         {
           principal_stress_vector(j, i) +=
             upper_deformed_basis(k, i) * ev(j, k);
         }
       }
     }
     // Scaling factor to turn these vectors into unit vectors
     Vector<double> norm(DIM);
     for (unsigned i = 0; i < DIM; i++)
     {
       norm[i] = 0.0;
       for (unsigned j = 0; j < DIM; j++)
       {
         norm[i] += pow(principal_stress_vector(i, j), 2);
       }
       norm[i] = sqrt(norm[i]);
     }
     // Scaling and then multiplying by eigenvalue gives the principal stress
     // vectors
     for (unsigned i = 0; i < DIM; i++)
     {
       for (unsigned j = 0; j < DIM; j++)
       {
         principal_stress_vector(j, i) =
           ev(j, i) / norm[j] * principal_stress[j];
       }
     }
   }
References DIM, i, j, k, Eigen::bfloat16_impl::pow(), s, calibrate::sigma, oomph::DoubleMatrixBase::solve(), and sqrt().
get_strain()
template<unsigned DIM> void oomph::PVDEquationsBase< DIM >::get_strain (const Vector< double > & s, DenseMatrix< double > & strain) const
Return the strain tensor.
Compute the strain tensor at local coordinate s.
/////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////
   {
 #ifdef PARANOID
     if ((strain.ncol() != DIM) || (strain.nrow() != DIM))
     {
       std::ostringstream error_message;
       error_message << "Strain matrix is " << strain.ncol() << " x "
                     << strain.nrow() << ", but dimension of the equations is "
                     << DIM << std::endl;
       throw OomphLibError(
         error_message.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
 #endif
     // Find out how many nodes there are in the element
     const unsigned n_node = nnode();
     // Find out how many position types there are
     const unsigned n_position_type = this->nnodal_position_type();
     // Set up memory for the shape and test functions
     Shape psi(n_node, n_position_type);
     DShape dpsidxi(n_node, n_position_type, DIM);
     // Call the derivatives of the shape functions
     (void)dshape_lagrangian(s, psi, dpsidxi);
     // Calculate interpolated values of the derivative of global position
     DenseMatrix<double> interpolated_G(DIM);
     // Initialise to zero
     for (unsigned i = 0; i < DIM; i++)
     {
       for (unsigned j = 0; j < DIM; j++)
       {
         interpolated_G(i, j) = 0.0;
       }
     }
     // Storage for Lagrangian coordinates (initialised to zero)
     Vector<double> interpolated_xi(DIM, 0.0);
     // Loop over nodes
     for (unsigned l = 0; l < n_node; l++)
     {
       // Loop over the positional dofs
       for (unsigned k = 0; k < n_position_type; k++)
       {
         // Loop over velocity components
         for (unsigned i = 0; i < DIM; i++)
         {
           // Calculate the Lagrangian coordinates
           interpolated_xi[i] +=
             this->lagrangian_position_gen(l, k, i) * psi(l, k);
           // Loop over derivative directions
           for (unsigned j = 0; j < DIM; j++)
           {
             interpolated_G(j, i) +=
               this->nodal_position_gen(l, k, i) * dpsidxi(l, k, j);
           }
         }
       }
     }
     // Get isotropic growth factor
     double gamma = 1.0;
     // Dummy integration point
     unsigned ipt = 0;
     get_isotropic_growth(ipt, s, interpolated_xi, gamma);
     // We use Cartesian coordinates as the reference coordinate
     // system. In this case the undeformed metric tensor is always
     // the identity matrix -- stretched by the isotropic growth
     double diag_entry = pow(gamma, 2.0 / double(DIM));
     DenseMatrix<double> g(DIM);
     for (unsigned i = 0; i < DIM; i++)
     {
       for (unsigned j = 0; j < DIM; j++)
       {
         if (i == j)
         {
           g(i, j) = diag_entry;
         }
         else
         {
           g(i, j) = 0.0;
         }
       }
     }
     // Declare and calculate the deformed metric tensor
     DenseMatrix<double> G(DIM);
     // Assign values of G
     for (unsigned i = 0; i < DIM; i++)
     {
       // Do upper half of matrix
       for (unsigned j = i; j < DIM; j++)
       {
         // Initialise G(i,j) to zero
         G(i, j) = 0.0;
         // Now calculate the dot product
         for (unsigned k = 0; k < DIM; k++)
         {
           G(i, j) += interpolated_G(i, k) * interpolated_G(j, k);
         }
       }
       // Matrix is symmetric so just copy lower half
       for (unsigned j = 0; j < i; j++)
       {
         G(i, j) = G(j, i);
       }
     }
     // Fill in the strain tensor
     for (unsigned i = 0; i < DIM; i++)
     {
       for (unsigned j = 0; j < DIM; j++)
       {
         strain(i, j) = 0.5 * (G(i, j) - g(i, j));
       }
     }
   }
References DIM, G, mathsFunc::gamma(), i, j, k, oomph::DenseMatrix< T >::ncol(), oomph::DenseMatrix< T >::nrow(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, Eigen::bfloat16_impl::pow(), and s.
Referenced by oomph::RefineablePVDEquations< DIM >::get_Z2_flux(), oomph::RefineablePVDEquationsWithPressure< DIM >::get_Z2_flux(), oomph::TPVDElement< DIM, NNODE_1D >::get_Z2_flux(), oomph::TPVDBubbleEnrichedElement< DIM, NNODE_1D >::get_Z2_flux(), and oomph::TPVDElementWithContinuousPressure< DIM >::get_Z2_flux().
get_stress()
template<unsigned DIM> virtual void oomph::PVDEquationsBase< DIM >::get_stress (const Vector< double > & s, DenseMatrix< double > & sigma) pure virtual
Return the 2nd Piola Kirchoff stress tensor, as calculated from the constitutive law at specified local coordinate (needed by get_principal_stress(...), so I'm afraid I will have to insist that you implement it...
Implemented in oomph::PVDEquationsWithPressure< DIM >, and oomph::PVDEquations< DIM >.
is_inertia_enabled()
template<unsigned DIM> bool oomph::PVDEquationsBase< DIM >::is_inertia_enabled () const inline
Access function to flag that switches inertia on/off (const version)
     {
       return Unsteady;
     }
References oomph::PVDEquationsBase< DIM >::Unsteady.
Referenced by oomph::RefineablePVDEquations< DIM >::further_build(), and oomph::RefineablePVDEquationsWithPressure< DIM >::further_build().
is_jacobian_evaluated_by_fd()
template<unsigned DIM> bool oomph::PVDEquationsBase< DIM >::is_jacobian_evaluated_by_fd () const inline
Return the flag indicating whether the jacobian is evaluated by fd.
     {
       return Evaluate_jacobian_by_fd;
     }
References oomph::PVDEquationsBase< DIM >::Evaluate_jacobian_by_fd.
Referenced by oomph::RefineablePVDEquations< DIM >::further_build(), and oomph::RefineablePVDEquationsWithPressure< DIM >::further_build().
isotropic_growth_fct_pt() [1/2]
template<unsigned DIM> IsotropicGrowthFctPt& oomph::PVDEquationsBase< DIM >::isotropic_growth_fct_pt () inline
Access function: Pointer to isotropic growth function.
     {
       return Isotropic_growth_fct_pt;
     }
References oomph::PVDEquationsBase< DIM >::Isotropic_growth_fct_pt.
Referenced by oomph::RefineablePVDEquations< DIM >::further_build(), and oomph::RefineablePVDEquationsWithPressure< DIM >::further_build().
isotropic_growth_fct_pt() [2/2]
template<unsigned DIM> IsotropicGrowthFctPt oomph::PVDEquationsBase< DIM >::isotropic_growth_fct_pt () const inline
Access function: Pointer to isotropic growth function (const version)
     {
       return Isotropic_growth_fct_pt;
     }
References oomph::PVDEquationsBase< DIM >::Isotropic_growth_fct_pt.
lambda_sq()
template<unsigned DIM> const double& oomph::PVDEquationsBase< DIM >::lambda_sq () const inline
Access function for timescale ratio (nondim density)
     {
       return *Lambda_sq_pt;
     }
References oomph::PVDEquationsBase< DIM >::Lambda_sq_pt.
Referenced by oomph::RefineableQDPVDElement< DIM, NNODE_1D >::fill_in_generic_contribution_to_residuals_pvd().
lambda_sq_pt()
template<unsigned DIM> double*& oomph::PVDEquationsBase< DIM >::lambda_sq_pt () inline
Access function for pointer to timescale ratio (nondim density)
     {
       return Lambda_sq_pt;
     }
References oomph::PVDEquationsBase< DIM >::Lambda_sq_pt.
Referenced by oomph::RefineablePVDEquations< DIM >::further_build(), and oomph::RefineablePVDEquationsWithPressure< DIM >::further_build().
ndof_types()
template<unsigned DIM> unsigned oomph::PVDEquationsBase< DIM >::ndof_types () const inline virtual
returns the number of DOF types associated with this element.
Reimplemented from oomph::GeneralisedElement.
Reimplemented in oomph::PVDEquationsWithPressure< DIM >, oomph::PseudoSolidNodeUpdateElement< TCrouzeixRaviartElement< 2 >, TPVDBubbleEnrichedElement< 2, 3 > >, oomph::PseudoSolidNodeUpdateElement< TTaylorHoodElement< 2 >, TPVDElement< 2, 3 > >, oomph::PseudoSolidNodeUpdateElement< GeneralisedNewtonianAxisymmetricTTaylorHoodElement, TPVDElement< 2, 3 > >, oomph::PseudoSolidNodeUpdateElement< AxisymmetricTTaylorHoodElement, TPVDElement< 2, 3 > >, and oomph::PseudoSolidNodeUpdateElement< GeneralisedNewtonianTTaylorHoodElement< 2 >, TPVDElement< 2, 3 > >.
     {
       return DIM;
     }
References DIM.
npres_solid()
template<unsigned DIM> virtual unsigned oomph::PVDEquationsBase< DIM >::npres_solid () const inline virtual
Return the number of solid pressure degrees of freedom Default is that there are no solid pressures
Reimplemented in oomph::TPVDElementWithContinuousPressure< DIM >, oomph::TPVDElementWithContinuousPressure< DIM >, oomph::TPVDElementWithContinuousPressure< DIM >, oomph::QPVDElementWithContinuousPressure< DIM >, and oomph::QPVDElementWithPressure< DIM >.
     {
       return 0;
     }
Referenced by oomph::PVDEquationsWithPressure< DIM >::get_dof_numbers_for_unknowns(), and oomph::PVDEquationsWithPressure< DIM >::interpolated_solid_p().
pin_elemental_redundant_nodal_solid_pressures()
template<unsigned DIM> virtual void oomph::PVDEquationsBase< DIM >::pin_elemental_redundant_nodal_solid_pressures () inline virtual
Pin the element's redundant solid pressures (needed for refinement)
Reimplemented in oomph::RefineableQPVDElementWithContinuousPressure< DIM >.
 {}
Referenced by oomph::PVDEquationsBase< DIM >::pin_redundant_nodal_solid_pressures().
pin_redundant_nodal_solid_pressures()
template<unsigned DIM> static void oomph::PVDEquationsBase< DIM >::pin_redundant_nodal_solid_pressures (const Vector< GeneralisedElement * > & element_pt) inline static
Loop over all elements in Vector (which typically contains all the elements in a refineable solid mesh) and pin the nodal solid pressure degrees of freedom that are not being used. Function uses the member function
PVDEquationsBase<DIM>:: pin_elemental_redundant_nodal_pressure_dofs()
which is empty by default and should be implemented for elements with nodal solid pressure degrees of freedom (e.g. solid elements with continuous pressure interpolation.)
     {
       // Loop over all elements
       unsigned n_element = element_pt.size();
       for (unsigned e = 0; e < n_element; e++)
       {
         dynamic_cast<PVDEquationsBase<DIM>*>(element_pt[e])
           ->pin_elemental_redundant_nodal_solid_pressures();
       }
     }
References e(), and oomph::PVDEquationsBase< DIM >::pin_elemental_redundant_nodal_solid_pressures().
Referenced by SolidProblem< ELEMENT_TYPE >::prepareForSolve().
prestress()
template<unsigned DIM> double oomph::PVDEquationsBase< DIM >::prestress (const unsigned & i, const unsigned & j, const Vector< double > xi) inline
Return (i,j)-th component of second Piola Kirchhoff membrane prestress at Lagrangian coordinate xi
     {
       if (Prestress_fct_pt == 0)
       {
         return 0.0;
       }
       else
       {
         return (*Prestress_fct_pt)(i, j, xi);
       }
     }
References i, j, and oomph::PVDEquationsBase< DIM >::Prestress_fct_pt.
Referenced by oomph::RefineableQDPVDElement< DIM, NNODE_1D >::fill_in_generic_contribution_to_residuals_pvd().
prestress_fct_pt()
template<unsigned DIM> PrestressFctPt& oomph::PVDEquationsBase< DIM >::prestress_fct_pt () inline
Access function: Pointer to pre-stress function.
     {
       return Prestress_fct_pt;
     }
References oomph::PVDEquationsBase< DIM >::Prestress_fct_pt.
solid_p_local_eqn()
template<unsigned DIM> virtual int oomph::PVDEquationsBase< DIM >::solid_p_local_eqn (const unsigned & i) const inline virtual
Return the local degree of freedom associated with the i-th solid pressure. Default is that there are none.
Reimplemented in oomph::TPVDElementWithContinuousPressure< DIM >, oomph::QPVDElementWithContinuousPressure< DIM >, and oomph::QPVDElementWithPressure< DIM >.
     {
       return -1;
     }
Referenced by oomph::PVDEquationsWithPressure< DIM >::get_dof_numbers_for_unknowns().
solid_p_nodal_index()
template<unsigned DIM> virtual int oomph::PVDEquationsBase< DIM >::solid_p_nodal_index () const inline virtual
Return the index at which the solid pressure is stored if it is stored at the nodes. If not stored at the nodes this will return a negative number.
Reimplemented in oomph::TPVDElementWithContinuousPressure< DIM >, oomph::QPVDElementWithContinuousPressure< DIM >, oomph::PseudoSolidNodeUpdateElement< TCrouzeixRaviartElement< 2 >, TPVDBubbleEnrichedElement< 2, 3 > >, oomph::PseudoSolidNodeUpdateElement< TTaylorHoodElement< 2 >, TPVDElement< 2, 3 > >, oomph::PseudoSolidNodeUpdateElement< GeneralisedNewtonianAxisymmetricTTaylorHoodElement, TPVDElement< 2, 3 > >, oomph::PseudoSolidNodeUpdateElement< AxisymmetricTTaylorHoodElement, TPVDElement< 2, 3 > >, and oomph::PseudoSolidNodeUpdateElement< GeneralisedNewtonianTTaylorHoodElement< 2 >, TPVDElement< 2, 3 > >.
     {
       return Solid_pressure_not_stored_at_node;
     }
References oomph::PVDEquationsBase< DIM >::Solid_pressure_not_stored_at_node.
unpin_all_solid_pressure_dofs()
template<unsigned DIM> static void oomph::PVDEquationsBase< DIM >::unpin_all_solid_pressure_dofs (const Vector< GeneralisedElement * > & element_pt) inline static
Unpin all pressure dofs in elements listed in vector.
     {
       // Loop over all elements
       unsigned n_element = element_pt.size();
       for (unsigned e = 0; e < n_element; e++)
       {
         dynamic_cast<PVDEquationsBase<DIM>*>(element_pt[e])
           ->unpin_elemental_solid_pressure_dofs();
       }
     }
References e(), and oomph::PVDEquationsBase< DIM >::unpin_elemental_solid_pressure_dofs().
unpin_elemental_solid_pressure_dofs()
template<unsigned DIM> virtual void oomph::PVDEquationsBase< DIM >::unpin_elemental_solid_pressure_dofs () pure virtual
Unpin all solid pressure dofs in the element.
Implemented in oomph::TPVDElementWithContinuousPressure< DIM >, oomph::QPVDElementWithContinuousPressure< DIM >, oomph::QPVDElementWithPressure< DIM >, oomph::PVDEquations< DIM >, oomph::RefineableQPVDElementWithContinuousPressure< DIM >, and oomph::RefineableQPVDElementWithPressure< DIM >.
Referenced by oomph::PVDEquationsBase< DIM >::unpin_all_solid_pressure_dofs().
Member Data Documentation
Body_force_fct_pt
template<unsigned DIM> BodyForceFctPt oomph::PVDEquationsBase< DIM >::Body_force_fct_pt protected
Pointer to body force function.
Referenced by oomph::PVDEquationsBase< DIM >::body_force(), oomph::PVDEquationsBase< DIM >::body_force_fct_pt(), oomph::RefineablePVDEquations< DIM >::further_build(), and oomph::RefineablePVDEquationsWithPressure< DIM >::further_build().
Constitutive_law_pt
template<unsigned DIM> ConstitutiveLaw* oomph::PVDEquationsBase< DIM >::Constitutive_law_pt protected
Pointer to the constitutive law.
Referenced by oomph::PVDEquationsBase< DIM >::constitutive_law_pt(), oomph::RefineableQDPVDElement< DIM, NNODE_1D >::fill_in_generic_contribution_to_residuals_pvd(), oomph::RefineablePVDEquations< DIM >::further_build(), oomph::RefineablePVDEquationsWithPressure< DIM >::further_build(), oomph::PVDEquationsWithPressure< DIM >::get_d_stress_dG_upper(), oomph::PVDEquations< DIM >::get_d_stress_dG_upper(), oomph::PVDEquations< DIM >::get_stress(), and oomph::PVDEquationsWithPressure< DIM >::get_stress().
Default_lambda_sq_value
template<unsigned DIM> double oomph::PVDEquationsBase< DIM >::Default_lambda_sq_value = 1.0 static protected
Static default value for timescale ratio (1.0 – for natural scaling)
Evaluate_jacobian_by_fd
template<unsigned DIM> bool oomph::PVDEquationsBase< DIM >::Evaluate_jacobian_by_fd protected
Use FD to evaluate Jacobian.
Referenced by oomph::PVDEquationsBase< DIM >::disable_evaluate_jacobian_by_fd(), oomph::PVDEquationsBase< DIM >::enable_evaluate_jacobian_by_fd(), oomph::PVDEquations< DIM >::fill_in_contribution_to_jacobian(), oomph::PVDEquationsWithPressure< DIM >::fill_in_contribution_to_jacobian(), oomph::PVDEquationsWithPressure< DIM >::fill_in_contribution_to_jacobian_and_mass_matrix(), oomph::RefineablePVDEquations< DIM >::further_build(), oomph::RefineablePVDEquationsWithPressure< DIM >::further_build(), and oomph::PVDEquationsBase< DIM >::is_jacobian_evaluated_by_fd().
Isotropic_growth_fct_pt
template<unsigned DIM> IsotropicGrowthFctPt oomph::PVDEquationsBase< DIM >::Isotropic_growth_fct_pt protected
Pointer to isotropic growth function.
Referenced by oomph::RefineablePVDEquations< DIM >::further_build(), oomph::RefineablePVDEquationsWithPressure< DIM >::further_build(), oomph::PVDEquationsBase< DIM >::get_isotropic_growth(), and oomph::PVDEquationsBase< DIM >::isotropic_growth_fct_pt().
Lambda_sq_pt
template<unsigned DIM> double* oomph::PVDEquationsBase< DIM >::Lambda_sq_pt protected
Timescale ratio (non-dim. density)
Referenced by oomph::RefineablePVDEquations< DIM >::further_build(), oomph::RefineablePVDEquationsWithPressure< DIM >::further_build(), oomph::PVDEquationsBase< DIM >::lambda_sq(), and oomph::PVDEquationsBase< DIM >::lambda_sq_pt().
Prestress_fct_pt
template<unsigned DIM> PrestressFctPt oomph::PVDEquationsBase< DIM >::Prestress_fct_pt protected
Pointer to prestress function.
Referenced by oomph::PVDEquationsBase< DIM >::prestress(), and oomph::PVDEquationsBase< DIM >::prestress_fct_pt().
Solid_pressure_not_stored_at_node
template<unsigned DIM> int oomph::PVDEquationsBase< DIM >::Solid_pressure_not_stored_at_node = -100 static private
Static "magic" number that indicates that the solid pressure is not stored at a node
/////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////// "Magic" number that indicates that the solid pressure is not stored at a node. It is a negative number that cannot be -1 because that is used to represent the positional hanging scheme in Hanging_pt objects
Referenced by oomph::PVDEquationsBase< DIM >::solid_p_nodal_index().
Unsteady
template<unsigned DIM> bool oomph::PVDEquationsBase< DIM >::Unsteady protected
Flag that switches inertia on/off.
Referenced by oomph::PVDEquationsBase< DIM >::disable_inertia(), oomph::PVDEquationsBase< DIM >::enable_inertia(), oomph::RefineableQDPVDElement< DIM, NNODE_1D >::fill_in_generic_contribution_to_residuals_pvd(), oomph::RefineablePVDEquations< DIM >::further_build(), oomph::RefineablePVDEquationsWithPressure< DIM >::further_build(), and oomph::PVDEquationsBase< DIM >::is_inertia_enabled().
The documentation for this class was generated from the following files:
solid_elements.h
solid_elements.cc