MercuryDPM: Eigen::TensorReductionEvaluatorBase< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device > Struct Template Reference
Eigen::TensorReductionEvaluatorBase< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device > Struct Template Reference
#include <TensorReduction.h>
Classes
struct BlockIteratorState
Public Types
enum {
IsAligned = false , PacketAccess = Self::InputPacketAccess && ReducerTraits::PacketAccess , BlockAccess = false , PreferBlockAccess = true ,
CoordAccess = false , RawAccess = false
}
typedef internal::reducer_traits< Op, Device > ReducerTraits
typedef Dims ReducedDims
typedef TensorReductionOp< Op, Dims, ArgType, MakePointer_ > XprType
typedef XprType::Index Index
typedef ArgType ChildType
typedef TensorEvaluator< ArgType, Device >::Dimensions InputDimensions
typedef std::conditional_t< NumOutputDims==0, Sizes<>, DSizes< Index, NumOutputDims > > Dimensions
typedef XprType::Scalar Scalar
typedef TensorReductionEvaluatorBase< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device > Self
typedef internal::ReductionReturnType< Op, typename XprType::CoeffReturnType >::type CoeffReturnType
typedef PacketType< CoeffReturnType, Device >::type PacketReturnType
typedef Eigen::internal::traits< XprType >::PointerType TensorPointerType
typedef StorageMemory< CoeffReturnType, Device > Storage
typedef Storage::Type EvaluatorPointerType
typedef std::remove_const_t< Scalar > ScalarNoConst
typedef internal::TensorBlockNotImplemented TensorBlock
Public Member Functions
EIGEN_STRONG_INLINE TensorReductionEvaluatorBase (const XprType &op, const Device &device)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Dimensions & dimensions () const
EIGEN_STRONG_INLINE bool evalSubExprsIfNeededCommon (EvaluatorPointerType data)
EIGEN_STRONG_INLINE bool evalSubExprsIfNeeded (EvaluatorPointerType data)
EIGEN_STRONG_INLINE void cleanup ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType coeff (Index index) const
template<int LoadMode>
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketReturnType packet (Index index) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorOpCost costPerCoeff (bool vectorized) const
EIGEN_DEVICE_FUNC EvaluatorPointerType data () const
EIGEN_DEVICE_FUNC const TensorEvaluator< ArgType, Device > & impl () const
EIGEN_DEVICE_FUNC const Device & device () const
Static Public Attributes
static constexpr int NumInputDims = internal::array_size<InputDimensions>::value
static constexpr int NumReducedDims = internal::array_size<Dims>::value
static constexpr int NumOutputDims = NumInputDims - NumReducedDims
static constexpr bool InputPacketAccess = TensorEvaluator<ArgType, Device>::PacketAccess
static constexpr Index PacketSize = PacketType<CoeffReturnType, Device>::size
static constexpr int NumPreservedStrides = max_n_1<NumOutputDims>::size
static constexpr bool RunningOnGPU = false
static constexpr bool RunningOnSycl = false
static constexpr int Layout = TensorEvaluator<ArgType, Device>::Layout
static constexpr bool ReducingInnerMostDims = internal::are_inner_most_dims<Dims, NumInputDims, Layout>::value
static constexpr bool PreservingInnerMostDims = internal::preserve_inner_most_dims<Dims, NumInputDims, Layout>::value
static constexpr bool RunningFullReduction = (NumOutputDims == 0)
Private Member Functions
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index firstInput (Index index) const
Private Attributes
array< bool, NumInputDims > m_reduced
Dimensions m_dimensions
array< Index,(std::max)(NumOutputDims, 1)> m_outputStrides
array< internal::TensorIntDivisor< Index >,(std::max)(NumOutputDims, 1)> m_fastOutputStrides
array< Index,(std::max)(NumPreservedStrides, 1)> m_preservedStrides
array< Index,(std::max)(NumOutputDims, 1)> m_output_to_input_dim_map
Index m_numValuesToReduce
array< Index, NumReducedDims > m_reducedStrides
array< Index, NumReducedDims > m_reducedDims
TensorEvaluator< ArgType, Device > m_impl
Op m_reducer
EvaluatorPointerType m_result
const Device EIGEN_DEVICE_REF m_device
Friends
template<int , typename , typename >
struct internal::GenericDimReducer
template<typename , typename , bool , bool >
struct internal::InnerMostDimReducer
template<int , typename , typename , bool >
struct internal::InnerMostDimPreserver
template<typename S , typename O , typename D , bool V>
struct internal::FullReducer
template<typename S , typename O , typename D >
struct internal::InnerReducer
Member Typedef Documentation
ChildType
template<typename Op , typename Dims , typename ArgType , template< class > class MakePointer_, typename Device > typedef ArgType Eigen::TensorReductionEvaluatorBase< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device >::ChildType
CoeffReturnType
template<typename Op , typename Dims , typename ArgType , template< class > class MakePointer_, typename Device > typedef internal::ReductionReturnType<Op, typename XprType::CoeffReturnType>::type Eigen::TensorReductionEvaluatorBase< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device >::CoeffReturnType
Dimensions
template<typename Op , typename Dims , typename ArgType , template< class > class MakePointer_, typename Device > typedef std::conditional_t<NumOutputDims == 0, Sizes<>, DSizes<Index, NumOutputDims> > Eigen::TensorReductionEvaluatorBase< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device >::Dimensions
EvaluatorPointerType
template<typename Op , typename Dims , typename ArgType , template< class > class MakePointer_, typename Device > typedef Storage::Type Eigen::TensorReductionEvaluatorBase< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device >::EvaluatorPointerType
Index
template<typename Op , typename Dims , typename ArgType , template< class > class MakePointer_, typename Device > typedef XprType::Index Eigen::TensorReductionEvaluatorBase< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device >::Index
InputDimensions
template<typename Op , typename Dims , typename ArgType , template< class > class MakePointer_, typename Device > typedef TensorEvaluator<ArgType, Device>::Dimensions Eigen::TensorReductionEvaluatorBase< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device >::InputDimensions
PacketReturnType
template<typename Op , typename Dims , typename ArgType , template< class > class MakePointer_, typename Device > typedef PacketType<CoeffReturnType, Device>::type Eigen::TensorReductionEvaluatorBase< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device >::PacketReturnType
ReducedDims
template<typename Op , typename Dims , typename ArgType , template< class > class MakePointer_, typename Device > typedef Dims Eigen::TensorReductionEvaluatorBase< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device >::ReducedDims
ReducerTraits
template<typename Op , typename Dims , typename ArgType , template< class > class MakePointer_, typename Device > typedef internal::reducer_traits<Op, Device> Eigen::TensorReductionEvaluatorBase< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device >::ReducerTraits
Scalar
template<typename Op , typename Dims , typename ArgType , template< class > class MakePointer_, typename Device > typedef XprType::Scalar Eigen::TensorReductionEvaluatorBase< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device >::Scalar
ScalarNoConst
template<typename Op , typename Dims , typename ArgType , template< class > class MakePointer_, typename Device > typedef std::remove_const_t<Scalar> Eigen::TensorReductionEvaluatorBase< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device >::ScalarNoConst
Self
template<typename Op , typename Dims , typename ArgType , template< class > class MakePointer_, typename Device > typedef TensorReductionEvaluatorBase<const TensorReductionOp<Op, Dims, ArgType, MakePointer_>, Device> Eigen::TensorReductionEvaluatorBase< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device >::Self
Storage
template<typename Op , typename Dims , typename ArgType , template< class > class MakePointer_, typename Device > typedef StorageMemory<CoeffReturnType, Device> Eigen::TensorReductionEvaluatorBase< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device >::Storage
TensorBlock
template<typename Op , typename Dims , typename ArgType , template< class > class MakePointer_, typename Device > typedef internal::TensorBlockNotImplemented Eigen::TensorReductionEvaluatorBase< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device >::TensorBlock
TensorPointerType
template<typename Op , typename Dims , typename ArgType , template< class > class MakePointer_, typename Device > typedef Eigen::internal::traits<XprType>::PointerType Eigen::TensorReductionEvaluatorBase< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device >::TensorPointerType
XprType
template<typename Op , typename Dims , typename ArgType , template< class > class MakePointer_, typename Device > typedef TensorReductionOp<Op, Dims, ArgType, MakePointer_> Eigen::TensorReductionEvaluatorBase< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device >::XprType
Member Enumeration Documentation
anonymous enum
template<typename Op , typename Dims , typename ArgType , template< class > class MakePointer_, typename Device > anonymous enum
Enumerator
IsAligned
PacketAccess
BlockAccess
PreferBlockAccess
CoordAccess
RawAccess
        {
     IsAligned = false,
     PacketAccess = Self::InputPacketAccess && ReducerTraits::PacketAccess,
     BlockAccess = false,
     PreferBlockAccess = true,
     CoordAccess = false,  // to be implemented
     RawAccess = false
   };
Constructor & Destructor Documentation
TensorReductionEvaluatorBase()
template<typename Op , typename Dims , typename ArgType , template< class > class MakePointer_, typename Device > EIGEN_STRONG_INLINE Eigen::TensorReductionEvaluatorBase< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device >::TensorReductionEvaluatorBase (const XprType & op, const Device & device) inline
       : m_impl(op.expression(), device), m_reducer(op.reducer()), m_result(NULL), m_device(device) {
     EIGEN_STATIC_ASSERT((NumInputDims >= NumReducedDims), YOU_MADE_A_PROGRAMMING_MISTAKE);
     EIGEN_STATIC_ASSERT((!ReducingInnerMostDims | !PreservingInnerMostDims | (NumReducedDims == NumInputDims)),
                         YOU_MADE_A_PROGRAMMING_MISTAKE);
     // Build the bitmap indicating if an input dimension is reduced or not.
     for (int i = 0; i < NumInputDims; ++i) {
       m_reduced[i] = false;
     }
     for (int i = 0; i < NumReducedDims; ++i) {
       eigen_assert(op.dims()[i] >= 0);
       eigen_assert(op.dims()[i] < NumInputDims);
       m_reduced[op.dims()[i]] = true;
     }
     const typename TensorEvaluator<ArgType, Device>::Dimensions& input_dims = m_impl.dimensions();
     internal::DimInitializer<Dimensions>::run(input_dims, m_reduced, &m_dimensions, &m_reducedDims);
     // Precompute output strides.
     if (NumOutputDims > 0) {
       if (static_cast<int>(Layout) == static_cast<int>(ColMajor)) {
         m_outputStrides[0] = 1;
         for (int i = 1; i < NumOutputDims; ++i) {
           m_outputStrides[i] = m_outputStrides[i - 1] * m_dimensions[i - 1];
           m_fastOutputStrides[i] = internal::TensorIntDivisor<Index>(m_outputStrides[i]);
         }
       } else {
         m_outputStrides[static_cast<size_t>(NumOutputDims - 1)] = 1;
         for (int i = NumOutputDims - 2; i >= 0; --i) {
           m_outputStrides[i] = m_outputStrides[i + 1] * m_dimensions[i + 1];
           m_fastOutputStrides[i] = internal::TensorIntDivisor<Index>(m_outputStrides[i]);
         }
       }
     }
     // Precompute input strides.
     if (NumInputDims > 0) {
       array<Index, NumInputDims> input_strides;
       if (static_cast<int>(Layout) == static_cast<int>(ColMajor)) {
         input_strides[0] = 1;
         for (int i = 1; i < NumInputDims; ++i) {
           input_strides[i] = input_strides[i - 1] * input_dims[i - 1];
         }
       } else {
         input_strides.back() = 1;
         for (int i = NumInputDims - 2; i >= 0; --i) {
           input_strides[i] = input_strides[i + 1] * input_dims[i + 1];
         }
       }
       int outputIndex = 0;
       int reduceIndex = 0;
       for (int i = 0; i < NumInputDims; ++i) {
         if (m_reduced[i]) {
           m_reducedStrides[reduceIndex] = input_strides[i];
           ++reduceIndex;
         } else {
           m_preservedStrides[outputIndex] = input_strides[i];
           m_output_to_input_dim_map[outputIndex] = i;
           ++outputIndex;
         }
       }
     }
     // Special case for full reductions
     if (NumOutputDims == 0) {
       m_preservedStrides[0] = internal::array_prod(input_dims);
     }
     m_numValuesToReduce = NumOutputDims == 0 ? internal::array_prod(input_dims)
                           : (static_cast<int>(Layout) == static_cast<int>(ColMajor))
                               ? m_preservedStrides[0]
                               : m_preservedStrides[static_cast<size_t>(NumOutputDims - 1)];
   }
References Eigen::internal::array_prod(), Eigen::ColMajor, Eigen::TensorEvaluator< Derived, Device >::dimensions(), eigen_assert, EIGEN_STATIC_ASSERT, i, op, and Eigen::internal::DimInitializer< OutputDims >::run().
Member Function Documentation
cleanup()
template<typename Op , typename Dims , typename ArgType , template< class > class MakePointer_, typename Device > EIGEN_STRONG_INLINE void Eigen::TensorReductionEvaluatorBase< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device >::cleanup () inline
{
     m_impl.cleanup();
     if (m_result) {
       m_device.deallocate_temp(m_result);
       m_result = NULL;
     }
   }
Referenced by framework.Frame::__init__().
coeff()
template<typename Op , typename Dims , typename ArgType , template< class > class MakePointer_, typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType Eigen::TensorReductionEvaluatorBase< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device >::coeff (Index index) const inline
{
     if ((RunningFullReduction || RunningOnGPU) && m_result) {
       return *(m_result + index);
     }
     Op reducer(m_reducer);
     if (ReducingInnerMostDims || RunningFullReduction) {
       const Index num_values_to_reduce = (static_cast<int>(Layout) == static_cast<int>(ColMajor))
                                              ? m_preservedStrides[0]
                                              : m_preservedStrides[NumPreservedStrides - 1];
       return internal::InnerMostDimReducer<Self, Op>::reduce(*this, firstInput(index), num_values_to_reduce, reducer);
     } else {
       typename Self::CoeffReturnType accum = reducer.initialize();
       internal::GenericDimReducer<NumReducedDims - 1, Self, Op>::reduce(*this, firstInput(index), reducer, &accum);
       return reducer.finalize(accum);
     }
   }
References Eigen::ColMajor, Eigen::internal::GenericDimReducer< DimIndex, Self, Op >::reduce(), and Eigen::internal::InnerMostDimReducer< Self, Op, Vectorizable, UseTreeReduction >::reduce().
costPerCoeff()
template<typename Op , typename Dims , typename ArgType , template< class > class MakePointer_, typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorOpCost Eigen::TensorReductionEvaluatorBase< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device >::costPerCoeff (bool vectorized) const inline
{
     if (RunningFullReduction && m_result) {
       return TensorOpCost(sizeof(CoeffReturnType), 0, 0, vectorized, PacketSize);
     } else {
       const Index num_values_to_reduce = internal::array_prod(m_reducedDims);
       const double compute_cost = num_values_to_reduce * internal::functor_traits<Op>::Cost;
       return m_impl.costPerCoeff(vectorized) * num_values_to_reduce +
              TensorOpCost(0, 0, compute_cost, vectorized, PacketSize);
     }
   }
References Eigen::internal::array_prod().
data()
template<typename Op , typename Dims , typename ArgType , template< class > class MakePointer_, typename Device > EIGEN_DEVICE_FUNC EvaluatorPointerType Eigen::TensorReductionEvaluatorBase< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device >::data () const inline
 { return m_result; }
Referenced by gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenQuaternionPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), gdb.printers.EigenSparseMatrixPrinter::to_string(), and gdb.printers.EigenQuaternionPrinter::to_string().
device()
template<typename Op , typename Dims , typename ArgType , template< class > class MakePointer_, typename Device > EIGEN_DEVICE_FUNC const Device& Eigen::TensorReductionEvaluatorBase< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device >::device () const inline
 { return m_device; }
dimensions()
template<typename Op , typename Dims , typename ArgType , template< class > class MakePointer_, typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Dimensions& Eigen::TensorReductionEvaluatorBase< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device >::dimensions () const inline
 { return m_dimensions; }
evalSubExprsIfNeeded()
template<typename Op , typename Dims , typename ArgType , template< class > class MakePointer_, typename Device > EIGEN_STRONG_INLINE bool Eigen::TensorReductionEvaluatorBase< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device >::evalSubExprsIfNeeded (EvaluatorPointerType data) inline
{
     m_impl.evalSubExprsIfNeeded(NULL);
     return evalSubExprsIfNeededCommon(data);
   }
References data.
evalSubExprsIfNeededCommon()
template<typename Op , typename Dims , typename ArgType , template< class > class MakePointer_, typename Device > EIGEN_STRONG_INLINE bool Eigen::TensorReductionEvaluatorBase< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device >::evalSubExprsIfNeededCommon (EvaluatorPointerType data) inline
{
     // Use the FullReducer if possible.
     if ((RunningFullReduction && RunningOnSycl) ||
         (RunningFullReduction && internal::FullReducer<Self, Op, Device>::HasOptimizedImplementation &&
          ((RunningOnGPU && (m_device.majorDeviceVersion() >= 3)) || !RunningOnGPU))) {
       bool need_assign = false;
       if (!data) {
         m_result = static_cast<EvaluatorPointerType>(
             m_device.get((CoeffReturnType*)m_device.allocate_temp(sizeof(CoeffReturnType))));
         data = m_result;
         need_assign = true;
       }
       Op reducer(m_reducer);
       internal::FullReducer<Self, Op, Device>::run(*this, reducer, m_device, data);
       return need_assign;
     }
     // Attempt to use an optimized reduction.
     else if ((RunningOnGPU && (m_device.majorDeviceVersion() >= 3)) || (RunningOnSycl)) {
       bool reducing_inner_dims = true;
       for (int i = 0; i < NumReducedDims; ++i) {
         if (static_cast<int>(Layout) == static_cast<int>(ColMajor)) {
           reducing_inner_dims &= m_reduced[i];
         } else {
           reducing_inner_dims &= m_reduced[NumInputDims - 1 - i];
         }
       }
       if (internal::InnerReducer<Self, Op, Device>::HasOptimizedImplementation &&
           (reducing_inner_dims || ReducingInnerMostDims)) {
         const Index num_values_to_reduce = internal::array_prod(m_reducedDims);
         const Index num_coeffs_to_preserve = internal::array_prod(m_dimensions);
         if (!data) {
           if ((num_coeffs_to_preserve < 1024 && num_values_to_reduce > num_coeffs_to_preserve &&
                num_values_to_reduce > 128) ||
               (RunningOnSycl)) {
             data = static_cast<EvaluatorPointerType>(m_device.get(
                 (CoeffReturnType*)m_device.allocate_temp(sizeof(CoeffReturnType) * num_coeffs_to_preserve)));
             m_result = data;
           } else {
             return true;
           }
         }
         Op reducer(m_reducer);
         // For SYCL this if always return false
         if (internal::InnerReducer<Self, Op, Device>::run(*this, reducer, m_device, data, num_values_to_reduce,
                                                           num_coeffs_to_preserve)) {
           if (m_result) {
             m_device.deallocate_temp(m_result);
             m_result = NULL;
           }
           return true;
         } else {
           return (m_result != NULL);
         }
       }
       bool preserving_inner_dims = true;
       for (int i = 0; i < NumReducedDims; ++i) {
         if (static_cast<int>(Layout) == static_cast<int>(ColMajor)) {
           preserving_inner_dims &= m_reduced[NumInputDims - 1 - i];
         } else {
           preserving_inner_dims &= m_reduced[i];
         }
       }
       if (internal::OuterReducer<Self, Op, Device>::HasOptimizedImplementation && preserving_inner_dims) {
         const Index num_values_to_reduce = internal::array_prod(m_reducedDims);
         const Index num_coeffs_to_preserve = internal::array_prod(m_dimensions);
         if (!data) {
           if ((num_coeffs_to_preserve < 1024 && num_values_to_reduce > num_coeffs_to_preserve &&
                num_values_to_reduce > 32) ||
               (RunningOnSycl)) {
             data = static_cast<EvaluatorPointerType>(m_device.get(
                 (CoeffReturnType*)m_device.allocate_temp(sizeof(CoeffReturnType) * num_coeffs_to_preserve)));
             m_result = data;
           } else {
             return true;
           }
         }
         Op reducer(m_reducer);
         // For SYCL this if always return false
         if (internal::OuterReducer<Self, Op, Device>::run(*this, reducer, m_device, data, num_values_to_reduce,
                                                           num_coeffs_to_preserve)) {
           if (m_result) {
             m_device.deallocate_temp(m_result);
             m_result = NULL;
           }
           return true;
         } else {
           return (m_result != NULL);
         }
       }
 #if defined(EIGEN_USE_SYCL)
       // If there is no Optimised version for SYCL, the reduction expression
       // must break into two subexpression and use the SYCL generic Reducer on the device.
       if (RunningOnSycl) {
         const Index num_values_to_reduce = internal::array_prod(m_reducedDims);
         const Index num_coeffs_to_preserve = internal::array_prod(m_dimensions);
         if (!data) {
           data = static_cast<EvaluatorPointerType>(
               m_device.get((CoeffReturnType*)m_device.allocate_temp(sizeof(CoeffReturnType) * num_coeffs_to_preserve)));
           m_result = data;
         }
         Op reducer(m_reducer);
         internal::GenericReducer<Self, Op, Device>::run(*this, reducer, m_device, data, num_values_to_reduce,
                                                         num_coeffs_to_preserve);
         return (m_result != NULL);
       }
 #endif
     }
     return true;
   }
References Eigen::internal::array_prod(), Eigen::ColMajor, data, i, Eigen::internal::FullReducer< Self, Op, Device, Vectorizable >::run(), and run().
firstInput()
template<typename Op , typename Dims , typename ArgType , template< class > class MakePointer_, typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index Eigen::TensorReductionEvaluatorBase< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device >::firstInput (Index index) const inline private
{
     if (ReducingInnerMostDims) {
       if (static_cast<int>(Layout) == static_cast<int>(ColMajor)) {
         return index * m_preservedStrides[0];
       } else {
         return index * m_preservedStrides[NumPreservedStrides - 1];
       }
     }
     // TBD: optimize the case where we preserve the innermost dimensions.
     Index startInput = 0;
     if (static_cast<int>(Layout) == static_cast<int>(ColMajor)) {
       for (int i = NumOutputDims - 1; i > 0; --i) {
         // This is index_i in the output tensor.
         const Index idx = index / m_outputStrides[i];
         startInput += idx * m_preservedStrides[i];
         index -= idx * m_outputStrides[i];
       }
       if (PreservingInnerMostDims) {
         eigen_assert(m_preservedStrides[0] == 1);
         startInput += index;
       } else {
         startInput += index * m_preservedStrides[0];
       }
     } else {
       for (int i = 0; i < NumOutputDims - 1; ++i) {
         // This is index_i in the output tensor.
         const Index idx = index / m_outputStrides[i];
         startInput += idx * m_preservedStrides[i];
         index -= idx * m_outputStrides[i];
       }
       if (PreservingInnerMostDims) {
         eigen_assert(m_preservedStrides[NumPreservedStrides - 1] == 1);
         startInput += index;
       } else {
         startInput += index * m_preservedStrides[NumPreservedStrides - 1];
       }
     }
     return startInput;
   }
References Eigen::ColMajor, eigen_assert, and i.
impl()
template<typename Op , typename Dims , typename ArgType , template< class > class MakePointer_, typename Device > EIGEN_DEVICE_FUNC const TensorEvaluator<ArgType, Device>& Eigen::TensorReductionEvaluatorBase< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device >::impl () const inline
 { return m_impl; }
packet()
template<typename Op , typename Dims , typename ArgType , template< class > class MakePointer_, typename Device > template<int LoadMode> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketReturnType Eigen::TensorReductionEvaluatorBase< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device >::packet (Index index) const inline
{
     eigen_assert(index + PacketSize - 1 < Index(internal::array_prod(dimensions())));
     if (RunningOnGPU && m_result) {
       return internal::pload<PacketReturnType>(m_result + index);
     }
     EIGEN_ALIGN_MAX std::remove_const_t<CoeffReturnType> values[PacketSize];
     if (ReducingInnerMostDims) {
       const Index num_values_to_reduce = (static_cast<int>(Layout) == static_cast<int>(ColMajor))
                                              ? m_preservedStrides[0]
                                              : m_preservedStrides[NumPreservedStrides - 1];
       const Index firstIndex = firstInput(index);
       for (Index i = 0; i < PacketSize; ++i) {
         Op reducer(m_reducer);
         values[i] = internal::InnerMostDimReducer<Self, Op>::reduce(*this, firstIndex + i * num_values_to_reduce,
                                                                     num_values_to_reduce, reducer);
       }
     } else if (PreservingInnerMostDims) {
       const Index firstIndex = firstInput(index);
       const int innermost_dim = (static_cast<int>(Layout) == static_cast<int>(ColMajor)) ? 0 : NumOutputDims - 1;
       // TBD: extend this the the n innermost dimensions that we preserve.
       if (((firstIndex % m_dimensions[innermost_dim]) + PacketSize - 1) < m_dimensions[innermost_dim]) {
         Op reducer(m_reducer);
         typename Self::PacketReturnType accum = reducer.template initializePacket<typename Self::PacketReturnType>();
         internal::InnerMostDimPreserver<NumReducedDims - 1, Self, Op>::reduce(*this, firstIndex, reducer, &accum);
         return reducer.finalizePacket(accum);
       } else {
         for (int i = 0; i < PacketSize; ++i) {
           values[i] = coeff(index + i);
         }
       }
     } else {
       for (int i = 0; i < PacketSize; ++i) {
         values[i] = coeff(index + i);
       }
     }
     PacketReturnType rslt = internal::pload<PacketReturnType>(values);
     return rslt;
   }
References Eigen::internal::array_prod(), Eigen::ColMajor, EIGEN_ALIGN_MAX, eigen_assert, i, Eigen::internal::InnerMostDimPreserver< DimIndex, Self, Op, vectorizable >::reduce(), and Eigen::internal::InnerMostDimReducer< Self, Op, Vectorizable, UseTreeReduction >::reduce().
Friends And Related Function Documentation
internal::FullReducer
template<typename Op , typename Dims , typename ArgType , template< class > class MakePointer_, typename Device > template<typename S , typename O , typename D , bool V> friend struct internal::FullReducer friend
internal::GenericDimReducer
template<typename Op , typename Dims , typename ArgType , template< class > class MakePointer_, typename Device > template<int , typename , typename > friend struct internal::GenericDimReducer friend
internal::InnerMostDimPreserver
template<typename Op , typename Dims , typename ArgType , template< class > class MakePointer_, typename Device > template<int , typename , typename , bool > friend struct internal::InnerMostDimPreserver friend
internal::InnerMostDimReducer
template<typename Op , typename Dims , typename ArgType , template< class > class MakePointer_, typename Device > template<typename , typename , bool , bool > friend struct internal::InnerMostDimReducer friend
internal::InnerReducer
template<typename Op , typename Dims , typename ArgType , template< class > class MakePointer_, typename Device > template<typename S , typename O , typename D > friend struct internal::InnerReducer friend
Member Data Documentation
InputPacketAccess
template<typename Op , typename Dims , typename ArgType , template< class > class MakePointer_, typename Device > constexpr bool Eigen::TensorReductionEvaluatorBase< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device >::InputPacketAccess = TensorEvaluator<ArgType, Device>::PacketAccess static constexpr
Layout
template<typename Op , typename Dims , typename ArgType , template< class > class MakePointer_, typename Device > constexpr int Eigen::TensorReductionEvaluatorBase< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device >::Layout = TensorEvaluator<ArgType, Device>::Layout static constexpr
m_device
template<typename Op , typename Dims , typename ArgType , template< class > class MakePointer_, typename Device > const Device EIGEN_DEVICE_REF Eigen::TensorReductionEvaluatorBase< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device >::m_device private
m_dimensions
template<typename Op , typename Dims , typename ArgType , template< class > class MakePointer_, typename Device > Dimensions Eigen::TensorReductionEvaluatorBase< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device >::m_dimensions private
m_fastOutputStrides
template<typename Op , typename Dims , typename ArgType , template< class > class MakePointer_, typename Device > array<internal::TensorIntDivisor<Index>, (std::max)(NumOutputDims, 1)> Eigen::TensorReductionEvaluatorBase< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device >::m_fastOutputStrides private
m_impl
template<typename Op , typename Dims , typename ArgType , template< class > class MakePointer_, typename Device > TensorEvaluator<ArgType, Device> Eigen::TensorReductionEvaluatorBase< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device >::m_impl private
m_numValuesToReduce
template<typename Op , typename Dims , typename ArgType , template< class > class MakePointer_, typename Device > Index Eigen::TensorReductionEvaluatorBase< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device >::m_numValuesToReduce private
m_output_to_input_dim_map
template<typename Op , typename Dims , typename ArgType , template< class > class MakePointer_, typename Device > array<Index, (std::max)(NumOutputDims, 1)> Eigen::TensorReductionEvaluatorBase< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device >::m_output_to_input_dim_map private
m_outputStrides
template<typename Op , typename Dims , typename ArgType , template< class > class MakePointer_, typename Device > array<Index, (std::max)(NumOutputDims, 1)> Eigen::TensorReductionEvaluatorBase< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device >::m_outputStrides private
m_preservedStrides
template<typename Op , typename Dims , typename ArgType , template< class > class MakePointer_, typename Device > array<Index, (std::max)(NumPreservedStrides, 1)> Eigen::TensorReductionEvaluatorBase< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device >::m_preservedStrides private
m_reduced
template<typename Op , typename Dims , typename ArgType , template< class > class MakePointer_, typename Device > array<bool, NumInputDims> Eigen::TensorReductionEvaluatorBase< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device >::m_reduced private
m_reducedDims
template<typename Op , typename Dims , typename ArgType , template< class > class MakePointer_, typename Device > array<Index, NumReducedDims> Eigen::TensorReductionEvaluatorBase< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device >::m_reducedDims private
m_reducedStrides
template<typename Op , typename Dims , typename ArgType , template< class > class MakePointer_, typename Device > array<Index, NumReducedDims> Eigen::TensorReductionEvaluatorBase< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device >::m_reducedStrides private
m_reducer
template<typename Op , typename Dims , typename ArgType , template< class > class MakePointer_, typename Device > Op Eigen::TensorReductionEvaluatorBase< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device >::m_reducer private
m_result
template<typename Op , typename Dims , typename ArgType , template< class > class MakePointer_, typename Device > EvaluatorPointerType Eigen::TensorReductionEvaluatorBase< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device >::m_result private
NumInputDims
template<typename Op , typename Dims , typename ArgType , template< class > class MakePointer_, typename Device > constexpr int Eigen::TensorReductionEvaluatorBase< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device >::NumInputDims = internal::array_size<InputDimensions>::value static constexpr
NumOutputDims
template<typename Op , typename Dims , typename ArgType , template< class > class MakePointer_, typename Device > constexpr int Eigen::TensorReductionEvaluatorBase< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device >::NumOutputDims = NumInputDims - NumReducedDims static constexpr
NumPreservedStrides
template<typename Op , typename Dims , typename ArgType , template< class > class MakePointer_, typename Device > constexpr int Eigen::TensorReductionEvaluatorBase< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device >::NumPreservedStrides = max_n_1<NumOutputDims>::size static constexpr
NumReducedDims
template<typename Op , typename Dims , typename ArgType , template< class > class MakePointer_, typename Device > constexpr int Eigen::TensorReductionEvaluatorBase< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device >::NumReducedDims = internal::array_size<Dims>::value static constexpr
PacketSize
template<typename Op , typename Dims , typename ArgType , template< class > class MakePointer_, typename Device > constexpr Index Eigen::TensorReductionEvaluatorBase< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device >::PacketSize = PacketType<CoeffReturnType, Device>::size static constexpr
PreservingInnerMostDims
template<typename Op , typename Dims , typename ArgType , template< class > class MakePointer_, typename Device > constexpr bool Eigen::TensorReductionEvaluatorBase< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device >::PreservingInnerMostDims = internal::preserve_inner_most_dims<Dims, NumInputDims, Layout>::value static constexpr
ReducingInnerMostDims
template<typename Op , typename Dims , typename ArgType , template< class > class MakePointer_, typename Device > constexpr bool Eigen::TensorReductionEvaluatorBase< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device >::ReducingInnerMostDims = internal::are_inner_most_dims<Dims, NumInputDims, Layout>::value static constexpr
RunningFullReduction
template<typename Op , typename Dims , typename ArgType , template< class > class MakePointer_, typename Device > constexpr bool Eigen::TensorReductionEvaluatorBase< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device >::RunningFullReduction = (NumOutputDims == 0) static constexpr
RunningOnGPU
template<typename Op , typename Dims , typename ArgType , template< class > class MakePointer_, typename Device > constexpr bool Eigen::TensorReductionEvaluatorBase< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device >::RunningOnGPU = false static constexpr
RunningOnSycl
template<typename Op , typename Dims , typename ArgType , template< class > class MakePointer_, typename Device > constexpr bool Eigen::TensorReductionEvaluatorBase< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device >::RunningOnSycl = false static constexpr
The documentation for this struct was generated from the following file:
TensorReduction.h