MercuryDPM: packetmath_pcast_ops_runner< Scalar, Packet, EnableIf > Struct Template Reference
packetmath_pcast_ops_runner< Scalar, Packet, EnableIf > Struct Template Reference
Static Public Member Functions
static void run ()
Member Function Documentation
run()
template<typename Scalar , typename Packet , typename EnableIf = void> static void packetmath_pcast_ops_runner< Scalar, Packet, EnableIf >::run () inline static
                     {
     test_cast_runner<Packet, float>::run();
     test_cast_runner<Packet, double>::run();
     test_cast_runner<Packet, int8_t>::run();
     test_cast_runner<Packet, uint8_t>::run();
     test_cast_runner<Packet, int16_t>::run();
     test_cast_runner<Packet, uint16_t>::run();
     test_cast_runner<Packet, int32_t>::run();
     test_cast_runner<Packet, uint32_t>::run();
     test_cast_runner<Packet, int64_t>::run();
     test_cast_runner<Packet, uint64_t>::run();
     test_cast_runner<Packet, bool>::run();
     test_cast_runner<Packet, std::complex<float>>::run();
     test_cast_runner<Packet, std::complex<double>>::run();
     test_cast_runner<Packet, half>::run();
     test_cast_runner<Packet, bfloat16>::run();
   }
References test_cast_runner< Scalar, EnableIf >::run().
Referenced by packetmath(), and packetmath_pcast_ops_runner< Scalar, Packet, std::enable_if_t< NumTraits< Scalar >::IsComplex > >::run().
The documentation for this struct was generated from the following file:
packetmath.cpp