MercuryDPM: Eigen::NumTraits< Eigen::half > Struct Reference
Eigen::NumTraits< Eigen::half > Struct Reference
#include <Half.h>
Public Types
enum { IsSigned = true , IsInteger = false , IsComplex = false , RequireInitialization = false }
Public Types inherited from Eigen::GenericNumTraits< Eigen::half >
enum
typedef Eigen::half Real
Static Public Member Functions
EIGEN_DEVICE_FUNC static EIGEN_CONSTEXPR EIGEN_STRONG_INLINE Eigen::half epsilon ()
EIGEN_DEVICE_FUNC static EIGEN_CONSTEXPR EIGEN_STRONG_INLINE Eigen::half dummy_precision ()
EIGEN_DEVICE_FUNC static EIGEN_CONSTEXPR EIGEN_STRONG_INLINE Eigen::half highest ()
EIGEN_DEVICE_FUNC static EIGEN_CONSTEXPR EIGEN_STRONG_INLINE Eigen::half lowest ()
EIGEN_DEVICE_FUNC static EIGEN_CONSTEXPR EIGEN_STRONG_INLINE Eigen::half infinity ()
EIGEN_DEVICE_FUNC static EIGEN_CONSTEXPR EIGEN_STRONG_INLINE Eigen::half quiet_NaN ()
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
IsSigned
IsInteger
IsComplex
RequireInitialization
 { IsSigned = true, IsInteger = false, IsComplex = false, RequireInitialization = false };
Member Function Documentation
dummy_precision()
EIGEN_DEVICE_FUNC static EIGEN_CONSTEXPR EIGEN_STRONG_INLINE Eigen::half Eigen::NumTraits< Eigen::half >::dummy_precision () inline static
{
     return half_impl::raw_uint16_to_half(0x211f);  //  Eigen::half(1e-2f);
   }
References Eigen::half_impl::raw_uint16_to_half().
epsilon()
EIGEN_DEVICE_FUNC static EIGEN_CONSTEXPR EIGEN_STRONG_INLINE Eigen::half Eigen::NumTraits< Eigen::half >::epsilon () inline static
{
     return half_impl::raw_uint16_to_half(0x0800);
   }
References Eigen::half_impl::raw_uint16_to_half().
highest()
EIGEN_DEVICE_FUNC static EIGEN_CONSTEXPR EIGEN_STRONG_INLINE Eigen::half Eigen::NumTraits< Eigen::half >::highest () inline static
{
     return half_impl::raw_uint16_to_half(0x7bff);
   }
References Eigen::half_impl::raw_uint16_to_half().
infinity()
EIGEN_DEVICE_FUNC static EIGEN_CONSTEXPR EIGEN_STRONG_INLINE Eigen::half Eigen::NumTraits< Eigen::half >::infinity () inline static
{
     return half_impl::raw_uint16_to_half(0x7c00);
   }
References Eigen::half_impl::raw_uint16_to_half().
lowest()
EIGEN_DEVICE_FUNC static EIGEN_CONSTEXPR EIGEN_STRONG_INLINE Eigen::half Eigen::NumTraits< Eigen::half >::lowest () inline static
{
     return half_impl::raw_uint16_to_half(0xfbff);
   }
References Eigen::half_impl::raw_uint16_to_half().
quiet_NaN()
EIGEN_DEVICE_FUNC static EIGEN_CONSTEXPR EIGEN_STRONG_INLINE Eigen::half Eigen::NumTraits< Eigen::half >::quiet_NaN () inline static
{
     return half_impl::raw_uint16_to_half(0x7e00);
   }
References Eigen::half_impl::raw_uint16_to_half().
The documentation for this struct was generated from the following file:
Half.h