MercuryDPM: Eigen::internal::MatrixLogarithmAtomic< MatrixType > Class Template Reference
Eigen::internal::MatrixLogarithmAtomic< MatrixType > Class Template Reference
Helper class for computing matrix logarithm of atomic matrices.
#include <MatrixLogarithm.h>
Public Member Functions
MatrixType compute (const MatrixType &A)
Compute matrix logarithm of atomic matrix.
Detailed Description
template<typename MatrixType>
class Eigen::internal::MatrixLogarithmAtomic< MatrixType >
Helper class for computing matrix logarithm of atomic matrices.
Here, an atomic matrix is a triangular matrix whose diagonal entries are close to each other.
See also
class MatrixFunctionAtomic, MatrixBase::log()
Member Function Documentation
compute()
template<typename MatrixType > MatrixType Eigen::internal::MatrixLogarithmAtomic< MatrixType >::compute (const MatrixType & A)
Compute matrix logarithm of atomic matrix.
Parameters
[in] A argument of matrix logarithm, should be upper triangular and atomic
Returns
The logarithm of A.
{
   using std::log;
   MatrixType result(A.rows(), A.rows());
   if (A.rows() == 1)
     result(0, 0) = log(A(0, 0));
   else if (A.rows() == 2)
     matrix_log_compute_2x2(A, result);
   else
     matrix_log_compute_big(A, result);
   return result;
 }
References Eigen::bfloat16_impl::log(), Eigen::internal::matrix_log_compute_2x2(), Eigen::internal::matrix_log_compute_big(), and Eigen::PlainObjectBase< Derived >::rows().
The documentation for this class was generated from the following file:
MatrixLogarithm.h