MercuryDPM: Eigen::internal::unary_evaluator< CoherentPadOp< ArgType, SizeAtCompileTime > > Struct Template Reference
Eigen::internal::unary_evaluator< CoherentPadOp< ArgType, SizeAtCompileTime > > Struct Template Reference
#include <CoherentPadOp.h>
Public Types
enum { CoeffReadCost = evaluator<ArgTypeNestedCleaned>::CoeffReadCost , LinearAccessMask = XprType::IsVectorAtCompileTime ? LinearAccessBit : 0 , Flags = evaluator<ArgTypeNestedCleaned>::Flags & (HereditaryBits | LinearAccessMask | RowMajorBit) , Alignment = evaluator<ArgTypeNestedCleaned>::Alignment }
typedef CoherentPadOp< ArgType, SizeAtCompileTime > XprType
typedef internal::remove_all_t< typename XprType::CoeffReturnType > CoeffReturnType
typedef internal::nested_eval< ArgType, 1 >::type ArgTypeNested
typedef internal::remove_all_t< ArgTypeNested > ArgTypeNestedCleaned
Public Types inherited from Eigen::internal::evaluator_base< CoherentPadOp< ArgType, SizeAtCompileTime > >
enum
typedef traits< CoherentPadOp< ArgType, SizeAtCompileTime > > ExpressionTraits
Public Member Functions
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE unary_evaluator (const XprType &pad)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType coeff (Index row, Index col) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType coeff (Index index) const
template<int LoadMode, typename PacketType >
EIGEN_STRONG_INLINE PacketType packet (Index row, Index col) const
template<int LoadMode, typename PacketType >
EIGEN_STRONG_INLINE PacketType packet (Index index) const
Public Member Functions inherited from Eigen::internal::evaluator_base< CoherentPadOp< ArgType, SizeAtCompileTime > >
EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE evaluator_base ()=default
Protected Attributes
const ArgTypeNested m_arg
evaluator< ArgTypeNestedCleaned > m_argImpl
const variable_if_dynamic< Index, ArgTypeNestedCleaned::SizeAtCompileTime > m_size
Member Typedef Documentation
ArgTypeNested
template<typename ArgType , int SizeAtCompileTime> typedef internal::nested_eval<ArgType, 1>::type Eigen::internal::unary_evaluator< CoherentPadOp< ArgType, SizeAtCompileTime > >::ArgTypeNested
ArgTypeNestedCleaned
template<typename ArgType , int SizeAtCompileTime> typedef internal::remove_all_t<ArgTypeNested> Eigen::internal::unary_evaluator< CoherentPadOp< ArgType, SizeAtCompileTime > >::ArgTypeNestedCleaned
CoeffReturnType
template<typename ArgType , int SizeAtCompileTime> typedef internal::remove_all_t<typename XprType::CoeffReturnType> Eigen::internal::unary_evaluator< CoherentPadOp< ArgType, SizeAtCompileTime > >::CoeffReturnType
XprType
template<typename ArgType , int SizeAtCompileTime> typedef CoherentPadOp<ArgType, SizeAtCompileTime> Eigen::internal::unary_evaluator< CoherentPadOp< ArgType, SizeAtCompileTime > >::XprType
Member Enumeration Documentation
anonymous enum
template<typename ArgType , int SizeAtCompileTime> anonymous enum
Enumerator
CoeffReadCost
LinearAccessMask
Flags
Alignment
        {
     CoeffReadCost = evaluator<ArgTypeNestedCleaned>::CoeffReadCost,
     LinearAccessMask = XprType::IsVectorAtCompileTime ? LinearAccessBit : 0,
     Flags = evaluator<ArgTypeNestedCleaned>::Flags & (HereditaryBits | LinearAccessMask | RowMajorBit),
     Alignment = evaluator<ArgTypeNestedCleaned>::Alignment
   };
Constructor & Destructor Documentation
unary_evaluator()
template<typename ArgType , int SizeAtCompileTime> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Eigen::internal::unary_evaluator< CoherentPadOp< ArgType, SizeAtCompileTime > >::unary_evaluator (const XprType & pad) inline explicit
       : m_arg(pad.nestedExpression()), m_argImpl(m_arg), m_size(pad.nestedExpression().size()) {}
Member Function Documentation
coeff() [1/2]
template<typename ArgType , int SizeAtCompileTime> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType Eigen::internal::unary_evaluator< CoherentPadOp< ArgType, SizeAtCompileTime > >::coeff (Index index) const inline
{
     if (index < m_size.value()) {
       return m_argImpl.coeff(index);
     }
     return CoeffReturnType(0);
   }
coeff() [2/2]
template<typename ArgType , int SizeAtCompileTime> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType Eigen::internal::unary_evaluator< CoherentPadOp< ArgType, SizeAtCompileTime > >::coeff (Index row, Index col) const inline
{
     EIGEN_IF_CONSTEXPR(XprType::IsRowMajor) {
       if (col < m_size.value()) {
         return m_argImpl.coeff(1, col);
       }
     }
     else {
       if (row < m_size.value()) {
         return m_argImpl.coeff(row, 1);
       }
     }
     return CoeffReturnType(0);
   }
References col(), EIGEN_IF_CONSTEXPR, and row().
packet() [1/2]
template<typename ArgType , int SizeAtCompileTime> template<int LoadMode, typename PacketType > EIGEN_STRONG_INLINE PacketType Eigen::internal::unary_evaluator< CoherentPadOp< ArgType, SizeAtCompileTime > >::packet (Index index) const inline
{
     constexpr int kPacketSize = unpacket_traits<PacketType>::size;
     if (index + kPacketSize <= m_size.value()) {
       return m_argImpl.template packet<LoadMode, PacketType>(index);
     } else if (index < m_size.value()) {
       // Partial packet.
       EIGEN_ALIGN_MAX std::remove_const_t<CoeffReturnType> values[kPacketSize];
       const int partial = m_size.value() - index;
       for (int i = 0; i < partial && i < kPacketSize; ++i) {
         values[i] = m_argImpl.coeff(index + i);
       }
       for (int i = partial; i < kPacketSize; ++i) {
         values[i] = CoeffReturnType(0);
       }
       return pload<PacketType>(values);
     }
     return pset1<PacketType>(CoeffReturnType(0));
   }
References EIGEN_ALIGN_MAX, and i.
packet() [2/2]
template<typename ArgType , int SizeAtCompileTime> template<int LoadMode, typename PacketType > EIGEN_STRONG_INLINE PacketType Eigen::internal::unary_evaluator< CoherentPadOp< ArgType, SizeAtCompileTime > >::packet (Index row, Index col) const inline
{
     // AutoDiff scalar's derivative must be a vector, which is enforced by static assert.
     // Defer to linear access for simplicity.
     EIGEN_IF_CONSTEXPR(XprType::IsRowMajor) { return packet(col); }
     return packet(row);
   }
References col(), EIGEN_IF_CONSTEXPR, and row().
Member Data Documentation
m_arg
template<typename ArgType , int SizeAtCompileTime> const ArgTypeNested Eigen::internal::unary_evaluator< CoherentPadOp< ArgType, SizeAtCompileTime > >::m_arg protected
m_argImpl
template<typename ArgType , int SizeAtCompileTime> evaluator<ArgTypeNestedCleaned> Eigen::internal::unary_evaluator< CoherentPadOp< ArgType, SizeAtCompileTime > >::m_argImpl protected
m_size
template<typename ArgType , int SizeAtCompileTime> const variable_if_dynamic<Index, ArgTypeNestedCleaned::SizeAtCompileTime> Eigen::internal::unary_evaluator< CoherentPadOp< ArgType, SizeAtCompileTime > >::m_size protected
The documentation for this struct was generated from the following file:
CoherentPadOp.h