MercuryDPM: Chain.cpp File Reference
Chain.cpp File Reference
#include <Walls/InfiniteWall.h>
#include "Mercury3D.h"
#include "CG/CG.h"
#include "Species/LinearViscoelasticSpecies.h"
Classes
class Chain
Functions
int main ()
Function Documentation
main()
int main ()
 {
     Chain chain;
     chain.setName("Chain");
     chain.setTimeStep(1e-4);
     chain.setTimeMax(1);
     chain.setSaveCount(250);
     //chain.restartFile.setName("ChainRenamed.restart");
     //define coarse-graining resolved in z
     CG<CGCoordinates::Z> cgZ;
     cgZ.setN(20);
     cgZ.setWidth(0.5);
     chain.cgHandler.copyAndAddObject(cgZ);
     chain.solve();
     logger(INFO,"Execute 'source Chain.sh' to get coarse-grained statistics of the last time step");
     helpers::writeToFile("Chain.sh","../MercuryCG/fstatistics Chain -stattype XZ -w 0.1 -h 0.05 -tmin 1 -tmax 30 -o Chain.XZ.stat\n"
             "../MercuryCG/MercuryCG Chain -stattype Z -w 0.1 -h 0.05 -tmin 1 -tmax 30 -o Chain.Z.stat\n"
             "../MercuryCG/MercuryCG Chain -stattype O -w 0.1 -h 0.05 -tmin 1 -tmax 30 -o Chain.O.stat\n");
     logger(INFO,"Run 'Chain.m' in MATLAB/octave to visualise the statistical output");
     helpers::writeToFile("Chain.m","addpath('../MercuryCG/')\n"
             "data = loadstatistics('Chain.XZ.stat');\n"
             "colormap(1-gray)\n"
             "contourf(data.x,data.z,data.Density,20,'EdgeColor','none')\n"
             "c = colorbar\n"
             "c.Label.String = '\\rho';\n"
             "title('Density')\n"
             "xlabel('x')\n"
             "ylabel('z');\n"
             "axis equal\n"
             "%%\n"
             "particles=importdata('Chain.data',' ',12);\n"
             "z=particles.data(:,3);\n"
             "r=particles.data(:,7);\n"
             "a=linspace(0,2*pi,40);\n"
             "xCircle = sin(a);\n"
             "zCircle = cos(a);\n"
             "hold on;\n"
             "for i=1:length(x)\n"
             "  plot(x(i)+r(i)*xCircle,z(i)+r(i)*zCircle,'Color',.8*[1 1 1])\n"
             "end\n"
             "hold off");
     return 0;
 }
References DPMBase::cgHandler, BaseHandler< T >::copyAndAddObject(), e(), INFO, logger, BaseCG::setN(), DPMBase::setName(), DPMBase::setSaveCount(), DPMBase::setTimeMax(), DPMBase::setTimeStep(), CG< Coordinates, BaseFunction, Fields >::setWidth(), DPMBase::solve(), and helpers::writeToFile().