MercuryDPM: SingleParticleConstantTemperatureSelfTest.cpp File Reference
SingleParticleConstantTemperatureSelfTest.cpp File Reference
#include "Mercury3D.h"
#include "Species/SinterFrictionReversibleAdhesiveSpecies.h"
#include "Species/SinterSpecies.h"
#include "Species/HertzianSinterSpecies.h"
#include "Walls/InfiniteWall.h"
#include "Boundaries/PeriodicBoundary.h"
Classes
class SingleParticle< SpeciesType >
One particle, sintering slowly to a wall.
Functions
int main (int argc UNUSED, char *argv[] UNUSED)
Function Documentation
main()
int main (int argc UNUSED, char *argv[] UNUSED)
 {
     SingleParticle<SinterSpecies> sp;
     sp.scaleMass(1e12);
     //set species properties
     Mdouble kMax=20000;
     sp.species->setPlasticParameters(0.1*kMax, kMax, 0.1*kMax, 0.16);
     Mdouble radius = sp.particleHandler.getSmallestInteractionRadius();
     Mdouble mass = sp.species->getSmallestParticleMass();
     sp.species->setStiffnessAndRestitutionCoefficient(sp.species->getLoadingStiffness(),0.8,mass);
     //flip between volume and surface sintering
     if (true)
     {
         sp.species->setSinterType(SINTERTYPE::CONSTANT_RATE);
         sp.species->setSinterRate(std::pow(0.3,2.0));
     } else {
         sp.species->setSinterType(SINTERTYPE::PARHAMI_MCKEEPING);
         sp.species->setSinterRate(std::pow(0.3,6.0));
     }
     sp.setTimeMax(1);
     sp.setSaveCount(10);
     sp.species->setSinterAdhesion(1200e-9/radius);
     sp.solve();
     logger(INFO,"Execute 'gnuplot %.gnu' to view output",sp.getName());
 }
References CONSTANT_RATE, e(), DPMBase::getName(), ParticleHandler::getSmallestInteractionRadius(), INFO, logger, PARHAMI_MCKEEPING, DPMBase::particleHandler, Eigen::bfloat16_impl::pow(), UniformPSDSelfTest::radius, SingleParticle< SpeciesType >::scaleMass(), DPMBase::setSaveCount(), DPMBase::setTimeMax(), DPMBase::solve(), and SingleParticle< SpeciesType >::species.