MercuryDPM: PlasticForceUnitTest.cpp File Reference
PlasticForceUnitTest.cpp File Reference
#include "DPMBase.h"
#include <iostream>
#include <vector>
#include <Species/LinearPlasticViscoelasticSpecies.h>
#include <Logger.h>
Classes
class PlasticForceUnitTest
[T11:contactModel]
Functions
int main (int argc UNUSED, char *argv[] UNUSED)
Function Documentation
main()
int main (int argc UNUSED, char *argv[] UNUSED)
 {
     PlasticForceUnitTest PlasticForceUnitTestProblem;
     double k1=100.0;
     PlasticForceUnitTestProblem.species->setPlasticParameters(k1, 5.0*k1, k1, 0.05);
     PlasticForceUnitTestProblem.species->setDissipation(0);
     PlasticForceUnitTestProblem.setParticleDimensions(3);
     PlasticForceUnitTestProblem.setSystemDimensions(3);
     logger(INFO,"Testing particle particles collision for elastic plastic forces. \n"
         "This will be done for serveral values of scaled relative velocity chi");
     //PlasticForceUnitTestProblem.restartFile.getFstream().precision(20);
     //Set up constant data that will be used
     const std::vector<double> chi = {0.34, 0.69, 1.1, 1.37};
     const std::vector<Vec3D> leftFinalVecloity = {
         Vec3D(-0.032721738352012,0.0,0.0),
         Vec3D(-0.0138683231953154,0.0,0.0),
         Vec3D(-0.0204655358555405,0.0,0.0),
         Vec3D(-0.163049415300304,0.0,0.0)};
     const std::vector<Vec3D> leftFinalPosition = {
         Vec3D(0.995546292935715,1.0,1.0),
         Vec3D(1.00695193269955,1.0,1.0),
         Vec3D(1.00840467123501,1.0,1.0),
         Vec3D(0.969386085767181,1.0,1.0)};
     //Loop over all test cases
     for (int i=0; i<4; i++)
     {
         logger(INFO, "Running for chi=%",chi[i]);
         PlasticForceUnitTestProblem.set_chi(chi[i]);
         std::stringstream ss("");
         ss << "PlasticForceUnitTest" << PlasticForceUnitTestProblem.get_chi();
         PlasticForceUnitTestProblem.setName(ss.str().c_str());
         PlasticForceUnitTestProblem.solve();
         //PlasticForceUnitTestProblem.writeRestartFile();
         //Now check the particles are in the right place for each of the 4 cases
         auto pIt = PlasticForceUnitTestProblem.particleHandler.begin();
         if (!(*pIt)->getPosition().isEqualTo(leftFinalPosition[i], 1e-10))
             logger(FATAL, "Left particle is in the wrong position. It is at % and should be %", (*pIt)->getPosition(),
                    leftFinalPosition[i]);
         if (!(*pIt)->getVelocity().isEqualTo(leftFinalVecloity[i], 1e-10))
             logger(FATAL, "Left particle has the wrong velocity. It is at % and should be %", (*pIt)->getVelocity(),
                    leftFinalVecloity[i]);
     }
     logger(INFO, "Execute 'gnuplot PlasticForceUnitTest.gnu' to view output");
     helpers::writeToFile("PlasticForceUnitTest.gnu",
                          "set xlabel 'displacement [{/Symbol d}]'\n"
                          "set ylabel 'force [f^n]'\n"
                          "set grid\n"
                          "plot 'PlasticForceUnitTest0.34.fstat' u 7:9 w lp\n"
     );
 }
References BaseHandler< T >::begin(), e(), FATAL, PlasticForceUnitTest::get_chi(), i, INFO, logger, DPMBase::particleHandler, PlasticForceUnitTest::set_chi(), DPMBase::setName(), DPMBase::setParticleDimensions(), DPMBase::setSystemDimensions(), DPMBase::solve(), PlasticForceUnitTest::species, and helpers::writeToFile().