MercuryDPM: CGLiquidsUnitTest.cpp File Reference
CGLiquidsUnitTest.cpp File Reference
#include <Walls/InfiniteWall.h>
#include <Species/LinearViscoelasticFrictionLiquidMigrationWilletSpecies.h>
#include <Particles/LiquidFilmParticle.h>
#include <CG/Fields/LiquidMigrationFields.h>
#include "Mercury3D.h"
#include "CG/CG.h"
Classes
class TwoParticles
Functions
int main ()
Function Documentation
main()
int main ()
 {
     logger(INFO," Simulates a particle-particle collision.\n"
                 " Checks cg \n"
                 "   - at one instant in time\n"
                 "   - standard fields (density and stress)\n"
                 "   - for O, Z, and XYZ coordinates\n"
                 "   - for both Gauss and Lucy kernel functions\n");
     TwoParticles dpm;
     dpm.setTimeMax(0);
     auto o = dpm.cgHandler.copyAndAddObject(CG<CGCoordinates::O,CGFunctions::Gauss,CGFields::LiquidMigrationFields>());
     auto z = dpm.cgHandler.copyAndAddObject(CG<CGCoordinates::Z,CGFunctions::Gauss,CGFields::LiquidMigrationFields>());
     z->setWidth(0.16);
     z->setN(100);
     auto xz = dpm.cgHandler.copyAndAddObject(CG<CGCoordinates::XZ,CGFunctions::Gauss,CGFields::LiquidMigrationFields>());
     xz->setWidth(0.16);
     xz->setN(100);
     dpm.solve();
     //A few checks
     logger(INFO,"Checking a few cg parameters");
     //Checks density for unresolved cg, rho = M/V = 2/16 = 0.125
     helpers::check(o->getPoint(0).getLiquidFilmVolume(),1,1e-15, "Average liquidFilmVolume");
     helpers::check(o->getPoint(0).getLiquidBridgeVolume(),1,1e-15, "Average liquidBridgeVolume");
     helpers::check(z->evaluateAverage().getLiquidFilmVolume(),1,3e-2, "Average liquidFilmVolume for z-resolved stats");
     helpers::check(z->evaluateAverage().getLiquidBridgeVolume(),1,1e-2, "Average liquidBridgeVolume for z-resolved stats");
     helpers::check(xz->evaluateAverage().getLiquidFilmVolume(),1,3e-2, "Average liquidFilmVolume for xz-resolved stats");
     helpers::check(xz->evaluateAverage().getLiquidBridgeVolume(),1,1e-2, "Average liquidBridgeVolume for xz-resolved stats");
     return 0;
 }
References DPMBase::cgHandler, helpers::check(), BaseHandler< T >::copyAndAddObject(), e(), INFO, logger, DPMBase::setTimeMax(), and DPMBase::solve().