MercuryDPM: Eigen::TensorOpCost Class Reference
Eigen::TensorOpCost Class Reference
#include <TensorCostModel.h>
Public Member Functions
EIGEN_DEVICE_FUNC TensorOpCost ()
EIGEN_DEVICE_FUNC TensorOpCost (double bytes_loaded, double bytes_stored, double compute_cycles)
EIGEN_DEVICE_FUNC TensorOpCost (double bytes_loaded, double bytes_stored, double compute_cycles, bool vectorized, double packet_size)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE double bytes_loaded () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE double bytes_stored () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE double compute_cycles () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE double total_cost (double load_cost, double store_cost, double compute_cost) const
EIGEN_DEVICE_FUNC void dropMemoryCost ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorOpCost cwiseMin (const TensorOpCost &rhs) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorOpCost cwiseMax (const TensorOpCost &rhs) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorOpCost & operator+= (const TensorOpCost &rhs)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorOpCost & operator*= (double rhs)
Static Public Member Functions
template<typename ArgType >
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE int MulCost ()
template<typename ArgType >
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE int AddCost ()
template<typename ArgType >
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE int DivCost ()
template<typename ArgType >
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE int ModCost ()
template<typename SrcType , typename TargetType >
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE int CastCost ()
Private Attributes
double bytes_loaded_
double bytes_stored_
double compute_cycles_
Friends
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE friend TensorOpCost operator+ (TensorOpCost lhs, const TensorOpCost &rhs)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE friend TensorOpCost operator* (TensorOpCost lhs, double rhs)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE friend TensorOpCost operator* (double lhs, TensorOpCost rhs)
std::ostream & operator<< (std::ostream &os, const TensorOpCost &tc)
Constructor & Destructor Documentation
TensorOpCost() [1/3]
EIGEN_DEVICE_FUNC Eigen::TensorOpCost::TensorOpCost () inline
 : bytes_loaded_(0), bytes_stored_(0), compute_cycles_(0) {}
Referenced by cwiseMax(), and cwiseMin().
TensorOpCost() [2/3]
EIGEN_DEVICE_FUNC Eigen::TensorOpCost::TensorOpCost (double bytes_loaded, double bytes_stored, double compute_cycles) inline
       : bytes_loaded_(bytes_loaded), bytes_stored_(bytes_stored), compute_cycles_(compute_cycles) {}
TensorOpCost() [3/3]
EIGEN_DEVICE_FUNC Eigen::TensorOpCost::TensorOpCost (double bytes_loaded, double bytes_stored, double compute_cycles, bool vectorized, double packet_size) inline
       : bytes_loaded_(bytes_loaded),
         bytes_stored_(bytes_stored),
         compute_cycles_(vectorized ? compute_cycles / packet_size : compute_cycles) {
     eigen_assert(bytes_loaded >= 0 && (numext::isfinite)(bytes_loaded));
     eigen_assert(bytes_stored >= 0 && (numext::isfinite)(bytes_stored));
     eigen_assert(compute_cycles >= 0 && (numext::isfinite)(compute_cycles));
   }
References bytes_loaded(), bytes_stored(), compute_cycles(), eigen_assert, and Eigen::numext::isfinite().
Member Function Documentation
AddCost()
template<typename ArgType > static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE int Eigen::TensorOpCost::AddCost () inline static
{
     return internal::functor_traits<internal::scalar_sum_op<ArgType> >::Cost;
   }
bytes_loaded()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE double Eigen::TensorOpCost::bytes_loaded () const inline
 { return bytes_loaded_; }
References bytes_loaded_.
Referenced by Eigen::TensorEvaluator< const TensorAssignOp< LeftArgType, RightArgType >, Device >::costPerCoeff(), cwiseMax(), cwiseMin(), operator+=(), and TensorOpCost().
bytes_stored()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE double Eigen::TensorOpCost::bytes_stored () const inline
 { return bytes_stored_; }
References bytes_stored_.
Referenced by Eigen::TensorEvaluator< const TensorAssignOp< LeftArgType, RightArgType >, Device >::costPerCoeff(), cwiseMax(), cwiseMin(), operator+=(), and TensorOpCost().
CastCost()
template<typename SrcType , typename TargetType > static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE int Eigen::TensorOpCost::CastCost () inline static
{
     return internal::functor_traits<internal::scalar_cast_op<SrcType, TargetType> >::Cost;
   }
compute_cycles()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE double Eigen::TensorOpCost::compute_cycles () const inline
 { return compute_cycles_; }
References compute_cycles_.
Referenced by Eigen::TensorEvaluator< const TensorAssignOp< LeftArgType, RightArgType >, Device >::costPerCoeff(), cwiseMax(), cwiseMin(), operator+=(), and TensorOpCost().
cwiseMax()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorOpCost Eigen::TensorOpCost::cwiseMax (const TensorOpCost & rhs) const inline
{
     double bytes_loaded = numext::maxi(bytes_loaded_, rhs.bytes_loaded());
     double bytes_stored = numext::maxi(bytes_stored_, rhs.bytes_stored());
     double compute_cycles = numext::maxi(compute_cycles_, rhs.compute_cycles());
     return TensorOpCost(bytes_loaded, bytes_stored, compute_cycles);
   }
References bytes_loaded(), bytes_loaded_, bytes_stored(), bytes_stored_, compute_cycles(), compute_cycles_, Eigen::numext::maxi(), and TensorOpCost().
Referenced by Eigen::TensorEvaluator< const TensorSelectOp< IfArgType, ThenArgType, ElseArgType >, Device >::costPerCoeff().
cwiseMin()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorOpCost Eigen::TensorOpCost::cwiseMin (const TensorOpCost & rhs) const inline
{
     double bytes_loaded = numext::mini(bytes_loaded_, rhs.bytes_loaded());
     double bytes_stored = numext::mini(bytes_stored_, rhs.bytes_stored());
     double compute_cycles = numext::mini(compute_cycles_, rhs.compute_cycles());
     return TensorOpCost(bytes_loaded, bytes_stored, compute_cycles);
   }
References bytes_loaded(), bytes_loaded_, bytes_stored(), bytes_stored_, compute_cycles(), compute_cycles_, Eigen::numext::mini(), and TensorOpCost().
DivCost()
template<typename ArgType > static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE int Eigen::TensorOpCost::DivCost () inline static
{
     return internal::functor_traits<internal::scalar_quotient_op<ArgType, ArgType> >::Cost;
   }
dropMemoryCost()
EIGEN_DEVICE_FUNC void Eigen::TensorOpCost::dropMemoryCost () inline
{
     bytes_loaded_ = 0;
     bytes_stored_ = 0;
   }
References bytes_loaded_, and bytes_stored_.
ModCost()
template<typename ArgType > static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE int Eigen::TensorOpCost::ModCost () inline static
{
     return internal::functor_traits<internal::scalar_mod_op<ArgType> >::Cost;
   }
MulCost()
template<typename ArgType > static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE int Eigen::TensorOpCost::MulCost () inline static
{
     return internal::functor_traits<internal::scalar_product_op<ArgType, ArgType> >::Cost;
   }
operator*=()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorOpCost& Eigen::TensorOpCost::operator*= (double rhs) inline
{
     bytes_loaded_ *= rhs;
     bytes_stored_ *= rhs;
     compute_cycles_ *= rhs;
     return *this;
   }
References bytes_loaded_, bytes_stored_, and compute_cycles_.
operator+=()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorOpCost& Eigen::TensorOpCost::operator+= (const TensorOpCost & rhs) inline
{
     bytes_loaded_ += rhs.bytes_loaded();
     bytes_stored_ += rhs.bytes_stored();
     compute_cycles_ += rhs.compute_cycles();
     return *this;
   }
References bytes_loaded(), bytes_loaded_, bytes_stored(), bytes_stored_, compute_cycles(), and compute_cycles_.
total_cost()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE double Eigen::TensorOpCost::total_cost (double load_cost, double store_cost, double compute_cost) const inline
{
     return load_cost * bytes_loaded_ + store_cost * bytes_stored_ + compute_cost * compute_cycles_;
   }
References bytes_loaded_, bytes_stored_, and compute_cycles_.
Referenced by Eigen::TensorCostModel< Device >::totalCost().
Friends And Related Function Documentation
operator* [1/2]
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE friend TensorOpCost operator* (double lhs, TensorOpCost rhs) friend
{
     rhs *= lhs;
     return rhs;
   }
operator* [2/2]
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE friend TensorOpCost operator* (TensorOpCost lhs, double rhs) friend
{
     lhs *= rhs;
     return lhs;
   }
operator+
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE friend TensorOpCost operator+ (TensorOpCost lhs, const TensorOpCost & rhs) friend
{
     lhs += rhs;
     return lhs;
   }
operator<<
std::ostream& operator<< (std::ostream & os, const TensorOpCost & tc) friend
{
     return os << "[bytes_loaded = " << tc.bytes_loaded() << ", bytes_stored = " << tc.bytes_stored()
               << ", compute_cycles = " << tc.compute_cycles() << "]";
   }
Member Data Documentation
bytes_loaded_
double Eigen::TensorOpCost::bytes_loaded_ private
Referenced by bytes_loaded(), cwiseMax(), cwiseMin(), dropMemoryCost(), operator*=(), operator+=(), and total_cost().
bytes_stored_
double Eigen::TensorOpCost::bytes_stored_ private
Referenced by bytes_stored(), cwiseMax(), cwiseMin(), dropMemoryCost(), operator*=(), operator+=(), and total_cost().
compute_cycles_
double Eigen::TensorOpCost::compute_cycles_ private
Referenced by compute_cycles(), cwiseMax(), cwiseMin(), operator*=(), operator+=(), and total_cost().
The documentation for this class was generated from the following file:
TensorCostModel.h