MercuryDPM: oomph::SpineNode Class Reference
oomph::SpineNode Class Reference
#include <spines.h>
Public Member Functions
SpineNode (const unsigned &n_dim, const unsigned &n_position_type, const unsigned &initial_nvalue)
Steady Constructor, initialise pointers to zero.
SpineNode (TimeStepper *const &time_stepper_pt, const unsigned &n_dim, const unsigned &n_position_type, const unsigned &initial_nvalue)
Unsteady Constructor, initialise pointers to zero.
Spine *& spine_pt ()
Access function to spine.
double & fraction ()
Set reference to fraction along spine.
unsigned & node_update_fct_id ()
Access function to ID of node update function (within specific mesh)
SpineMesh *& spine_mesh_pt ()
double & h ()
Access function to spine height.
void node_update (const bool &update_all_time_levels_for_new_node=false)
Update function, call the update function in the Node's SpineMesh.
unsigned ngeom_data () const
Return the number of geometric data, zero if no spine.
unsigned ngeom_object () const
Return the number of geometric objects, zero if no spine.
Data ** all_geom_data_pt ()
Return the vector of all geometric data.
GeomObject ** all_geom_object_pt ()
Return the vector of all geometric objects.
Public Member Functions inherited from oomph::Node
Node ()
Default constructor.
Node (const unsigned &n_dim, const unsigned &n_position_type, const unsigned &initial_n_value, const bool &allocate_x_position=true)
Node (TimeStepper *const &time_stepper_pt, const unsigned &n_dim, const unsigned &n_position_type, const unsigned &initial_n_value, const bool &allocate_x_position=true)
virtual ~Node ()
Destructor: Clean up the memory allocated for nodal position.
Node (const Node &node)=delete
Broken copy constructor.
void operator= (const Node &)=delete
Broken assignment operator.
unsigned nposition_type () const
TimeStepper *& position_time_stepper_pt ()
Return a pointer to the position timestepper.
TimeStepper *const & position_time_stepper_pt () const
Return a pointer to the position timestepper (const version).
virtual void set_position_time_stepper (TimeStepper *const &position_time_stepper_pt, const bool &preserve_existing_data)
virtual bool does_pointer_correspond_to_position_data (double *const &parameter_pt)
virtual void assign_eqn_numbers (unsigned long &global_ndof, Vector< double * > &dof_pt)
unsigned ndim () const
Return (Eulerian) spatial dimension of the node.
double & x (const unsigned &i)
Return the i-th nodal coordinate.
const double & x (const unsigned &i) const
Return the i-th nodal coordinate (const version).
double & x (const unsigned &t, const unsigned &i)
const double & x (const unsigned &t, const unsigned &i) const
double dx_dt (const unsigned &i) const
Return the i-th component of nodal velocity: dx/dt.
double dx_dt (const unsigned &j, const unsigned &i) const
virtual Node * copied_node_pt () const
virtual bool position_is_a_copy () const
Return whether any position coordinate has been copied (always false)
virtual bool position_is_a_copy (const unsigned &i) const
Return whether the position coordinate i has been copied (always false)
double & x_gen (const unsigned &k, const unsigned &i)
const double & x_gen (const unsigned &k, const unsigned &i) const
double & x_gen (const unsigned &t, const unsigned &k, const unsigned &i)
const double & x_gen (const unsigned &t, const unsigned &k, const unsigned &i) const
double dx_gen_dt (const unsigned &k, const unsigned &i) const
double dx_gen_dt (const unsigned &j, const unsigned &k, const unsigned &i) const
double * x_pt (const unsigned &t, const unsigned &i)
void copy (Node *orig_node_pt)
Copy all nodal data from specified Node object.
virtual void dump (std::ostream &dump_file) const
Dump nodal position and associated data to file for restart.
void read (std::ifstream &restart_file)
Read nodal position and associated data from file for restart.
virtual void pin_all ()
virtual void unpin_all ()
unsigned hang_code ()
HangInfo *const & hanging_pt () const
HangInfo *const & hanging_pt (const int &i) const
Return pointer to hanging node data for value i (const version)
bool is_hanging () const
Test whether the node is geometrically hanging.
bool is_hanging (const int &i) const
Test whether the i-th value is hanging.
void set_hanging_pt (HangInfo *const &hang_pt, const int &i)
Set the hanging data for the i-th value. (hang_pt=0 to make non-hanging)
void set_nonhanging ()
Label node as non-hanging node by removing all hanging node data.
void resize (const unsigned &n_value)
Resize the number of equations.
virtual void constrain_positions ()
virtual void unconstrain_positions ()
virtual void make_periodic (Node *const &node_pt)
virtual void make_periodic_nodes (const Vector< Node * > &periodic_nodes_pt)
virtual void get_boundaries_pt (std::set< unsigned > *&boundaries_pt)
virtual bool is_on_boundary () const
virtual bool is_on_boundary (const unsigned &b) const
virtual void add_to_boundary (const unsigned &b)
virtual void remove_from_boundary (const unsigned &b)
virtual unsigned ncoordinates_on_boundary (const unsigned &b)
virtual bool boundary_coordinates_have_been_set_up ()
virtual void get_coordinates_on_boundary (const unsigned &b, const unsigned &k, Vector< double > &boundary_zeta)
virtual void set_coordinates_on_boundary (const unsigned &b, const unsigned &k, const Vector< double > &boundary_zeta)
virtual void get_coordinates_on_boundary (const unsigned &b, Vector< double > &boundary_zeta)
virtual void set_coordinates_on_boundary (const unsigned &b, const Vector< double > &boundary_zeta)
void set_obsolete ()
Mark node as obsolete.
void set_non_obsolete ()
Mark node as non-obsolete.
bool is_obsolete ()
Test whether node is obsolete.
double raw_value (const unsigned &i) const
double raw_value (const unsigned &t, const unsigned &i) const
double value (const unsigned &i) const
double value (const unsigned &t, const unsigned &i) const
void value (Vector< double > &values) const
Vector< double > value () const
Return vector of values calculated using value(vector).
void value (const unsigned &t, Vector< double > &values) const
void position (Vector< double > &pos) const
Vector< double > position () const
Return vector of position of node at current time.
void position (const unsigned &t, Vector< double > &pos) const
double position (const unsigned &i) const
double position (const unsigned &t, const unsigned &i) const
double position_gen (const unsigned &k, const unsigned &i) const
double position_gen (const unsigned &t, const unsigned &k, const unsigned &i) const
double dposition_dt (const unsigned &i) const
double dposition_dt (const unsigned &j, const unsigned &i) const
double dposition_gen_dt (const unsigned &k, const unsigned &i) const
double dposition_gen_dt (const unsigned &j, const unsigned &k, const unsigned &i) const
void set_auxiliary_node_update_fct_pt (AuxNodeUpdateFctPt aux_node_update_fct_pt)
bool has_auxiliary_node_update_fct_pt ()
void perform_auxiliary_node_update_fct ()
void output (std::ostream &outfile)
Output nodal position.
Public Member Functions inherited from oomph::Data
virtual void clear_copied_pointers ()
Data ()
Default constructor.
Data (const unsigned &initial_n_value)
Data (TimeStepper *const &time_stepper_pt, const unsigned &initial_n_value, const bool &allocate_storage=true)
Data (const Data &data)=delete
Broken copy constructor.
void operator= (const Data &)=delete
Broken assignment operator.
virtual ~Data ()
Destructor, deallocates memory assigned for data.
void set_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
TimeStepper *& time_stepper_pt ()
Return the pointer to the timestepper.
TimeStepper *const & time_stepper_pt () const
Return the pointer to the timestepper (const version).
virtual bool is_a_copy () const
virtual bool is_a_copy (const unsigned &i) const
void set_value (const unsigned &i, const double &value_)
void set_value (const unsigned &t, const unsigned &i, const double &value_)
double value (const unsigned &i) const
double value (const unsigned &t, const unsigned &i) const
void value (Vector< double > &values) const
Compute Vector of values for the Data value.
void value (const unsigned &t, Vector< double > &values) const
double * value_pt (const unsigned &i) const
double * value_pt (const unsigned &t, const unsigned &i) const
bool does_pointer_correspond_to_value (double *const &parameter_pt)
Check whether the pointer parameter_pt addresses internal data values.
void copy (Data *orig_data_pt)
Copy Data values from specified Data object.
void dump (std::ostream &dump_file) const
Dump the data object to a file.
void read (std::ifstream &restart_file)
Read data object from a file.
long * eqn_number_pt (const unsigned &i)
Return the pointer to the equation number of the i-th stored variable.
long & eqn_number (const unsigned &i)
Return the equation number of the i-th stored variable.
long eqn_number (const unsigned &i) const
Return the equation number of the i-th stored variable.
void pin (const unsigned &i)
Pin the i-th stored variable.
void unpin (const unsigned &i)
Unpin the i-th stored variable.
void pin_all ()
Pin all the stored variables.
void unpin_all ()
Unpin all the stored variables.
bool is_pinned (const unsigned &i) const
Test whether the i-th variable is pinned (1: true; 0: false).
bool is_segregated_solve_pinned (const unsigned &i)
void constrain (const unsigned &i)
void unconstrain (const unsigned &i)
void constrain_all ()
Constrain all the stored variables when the data is made hanging.
void unconstrain_all ()
Unconstrain all the stored variables when the data is made nonhanging.
bool is_constrained (const unsigned &i)
unsigned self_test ()
unsigned nvalue () const
Return number of values stored in data object (incl pinned ones).
unsigned ntstorage () const
virtual void describe_dofs (std::ostream &out, const std::string &current_string) const
virtual void add_value_pt_to_map (std::map< unsigned, double * > &map_of_value_pt)
Private Attributes
Spine * Spine_pt
Private internal data pointer to a spine.
double Fraction
Private double that represents the fixed fraction along the spine.
SpineMesh * Spine_mesh_pt
unsigned Node_update_fct_id
Additional Inherited Members
Public Types inherited from oomph::Node
typedef void(* AuxNodeUpdateFctPt) (Node *)
Function pointer to auxiliary node update function.
Static Public Attributes inherited from oomph::Node
static unsigned No_independent_position = 10
Static Public Attributes inherited from oomph::Data
static long Is_pinned = -1
Static "Magic number" to indicate pinned values.
static long Is_segregated_solve_pinned = -3
static long Is_unclassified = -10
static long Is_constrained = -2
Protected Member Functions inherited from oomph::Node
void x_gen_range_check (const unsigned &t, const unsigned &k, const unsigned &i) const
double * x_position_pt (const unsigned &i)
Direct access to the pointer to the i-th stored coordinate data.
Protected Member Functions inherited from oomph::Data
virtual void reset_copied_pointers ()
Protected Attributes inherited from oomph::Node
double ** X_position
TimeStepper * Position_time_stepper_pt
Pointer to the timestepper associated with the position data.
HangInfo ** Hanging_pt
unsigned Ndim
Eulerian dimension of the node.
unsigned Nposition_type
bool Obsolete
AuxNodeUpdateFctPt Aux_node_update_fct_pt
Protected Attributes inherited from oomph::Data
Data ** Copy_of_data_pt
unsigned Ncopies
Static Protected Attributes inherited from oomph::Data
static TimeStepper * Default_static_time_stepper_pt = new Steady<0>()
Default (static) timestepper used in steady problems.
Detailed Description
Class for nodes that live on spines. The assumption is that each Node lies at a fixed fraction on a single spine (although more complex behaviour could be included by adding more variables to the spine). In general, more complex node updating should be handled by the classes implemented for algebraic node updates.
Constructor & Destructor Documentation
SpineNode() [1/2]
oomph::SpineNode::SpineNode (const unsigned & n_dim, const unsigned & n_position_type, const unsigned & initial_nvalue) inline
Steady Constructor, initialise pointers to zero.
       : Node(n_dim, n_position_type, initial_nvalue),
         Spine_pt(0),
         Fraction(0),
         Spine_mesh_pt(0),
         Node_update_fct_id(0)
     {
     }
SpineNode() [2/2]
oomph::SpineNode::SpineNode (TimeStepper *const & time_stepper_pt, const unsigned & n_dim, const unsigned & n_position_type, const unsigned & initial_nvalue) inline
Unsteady Constructor, initialise pointers to zero.
       : Node(time_stepper_pt, n_dim, n_position_type, initial_nvalue),
         Spine_pt(0),
         Fraction(0),
         Spine_mesh_pt(0),
         Node_update_fct_id(0)
     {
     }
Member Function Documentation
all_geom_data_pt()
Data** oomph::SpineNode::all_geom_data_pt () inline virtual
Return the vector of all geometric data.
Reimplemented from oomph::Node.
     {
       return &(Spine_pt->geom_data_pt(0));
     }
References oomph::Spine::geom_data_pt(), and Spine_pt.
all_geom_object_pt()
GeomObject** oomph::SpineNode::all_geom_object_pt () inline virtual
Return the vector of all geometric objects.
Reimplemented from oomph::Node.
     {
       return &(Spine_pt->geom_object_pt(0));
     }
References oomph::Spine::geom_object_pt(), and Spine_pt.
fraction()
double& oomph::SpineNode::fraction () inline
Set reference to fraction along spine.
     {
       return Fraction;
     }
References Fraction.
Referenced by AxialSpineQuarterTubeMesh< ELEMENT, INTERFACE_ELEMENT >::AxialSpineQuarterTubeMesh(), oomph::ChannelSpineMesh< ELEMENT >::build_channel_spine_mesh(), oomph::HorizontalSingleLayerSpineMesh< ELEMENT >::build_horizontal_single_layer_mesh(), MyCanyonMesh< ELEMENT, INTERFACE_ELEMENT >::build_single_layer_mesh(), MyTipMesh< ELEMENT, INTERFACE_ELEMENT >::build_single_layer_mesh(), oomph::SingleLayerCubicSpineMesh< ELEMENT >::build_single_layer_mesh(), oomph::SingleLayerSpineMesh< ELEMENT >::build_single_layer_mesh(), oomph::TwoLayerSpineMesh< BASE_ELEMENT >::build_two_layer_mesh(), SimpleSpineMesh< ELEMENT >::SimpleSpineMesh(), oomph::AnnularSpineMesh< ELEMENT >::spine_node_update(), oomph::MyHorizontalSingleLayerSpineMesh< ELEMENT >::spine_node_update(), SpineInclinedPlaneMesh< ELEMENT >::spine_node_update(), SimpleSpineMesh< ELEMENT >::spine_node_update(), MyCanyonMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update(), CombCanSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update(), CombTipSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update(), STSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update(), MyTipMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update(), AxialSpineQuarterTubeMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update(), oomph::ChannelSpineMesh< ELEMENT >::spine_node_update(), oomph::HorizontalSingleLayerSpineMesh< ELEMENT >::spine_node_update(), oomph::SingleLayerCubicSpineMesh< ELEMENT >::spine_node_update(), oomph::SingleLayerSpineMesh< ELEMENT >::spine_node_update(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_channel(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_film_lower(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_film_upper(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_horizontal_transition_lower(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_horizontal_transition_upper(), oomph::TwoLayerSpineMesh< ELEMENT >::spine_node_update_lower(), oomph::TwoLayerSpineMesh< ELEMENT >::spine_node_update_upper(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_vertical_transition_lower(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_vertical_transition_upper(), and SpineInclinedPlaneMesh< ELEMENT >::SpineInclinedPlaneMesh().
h()
double& oomph::SpineNode::h () inline
Access function to spine height.
     {
       return Spine_pt->height();
     }
References oomph::Spine::height(), and Spine_pt.
Referenced by oomph::AnnularSpineMesh< ELEMENT >::AnnularSpineMesh(), CombCanSpineMesh< ELEMENT, INTERFACE_ELEMENT >::build_single_layer_mesh(), CombTipSpineMesh< ELEMENT, INTERFACE_ELEMENT >::build_single_layer_mesh(), ThreeDimBethertonProblem< ELEMENT >::multiply_aspect_ratio(), oomph::AnnularSpineMesh< ELEMENT >::spine_node_update(), oomph::MyHorizontalSingleLayerSpineMesh< ELEMENT >::spine_node_update(), SpineInclinedPlaneMesh< ELEMENT >::spine_node_update(), MyCanyonMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update(), CombCanSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update(), CombTipSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update(), STSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update(), MyTipMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update(), AxialSpineQuarterTubeMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update(), oomph::HorizontalSingleLayerSpineMesh< ELEMENT >::spine_node_update(), oomph::SingleLayerCubicSpineMesh< ELEMENT >::spine_node_update(), oomph::SingleLayerSpineMesh< ELEMENT >::spine_node_update(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_film_lower(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_film_upper(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_horizontal_transition_lower(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_horizontal_transition_upper(), oomph::TwoLayerSpineMesh< ELEMENT >::spine_node_update_lower(), oomph::TwoLayerSpineMesh< ELEMENT >::spine_node_update_upper(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_vertical_transition_lower(), and oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_vertical_transition_upper().
ngeom_data()
unsigned oomph::SpineNode::ngeom_data () const inline virtual
Return the number of geometric data, zero if no spine.
Reimplemented from oomph::Node.
     {
       if (Spine_pt)
       {
         return Spine_pt->ngeom_data();
       }
       else
       {
         return 0;
       }
     }
References oomph::Spine::ngeom_data(), and Spine_pt.
ngeom_object()
unsigned oomph::SpineNode::ngeom_object () const inline virtual
Return the number of geometric objects, zero if no spine.
Reimplemented from oomph::Node.
     {
       if (Spine_pt)
       {
         return Spine_pt->ngeom_object();
       }
       else
       {
         return 0;
       }
     }
References oomph::Spine::ngeom_object(), and Spine_pt.
node_update()
void oomph::SpineNode::node_update (const bool & update_all_time_levels_for_new_node = false) virtual
Update function, call the update function in the Node's SpineMesh.
Overload thet node update function, call the update function in the Node's SpineMesh
//////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////
Reimplemented from oomph::Node.
   {
     Spine_mesh_pt->spine_node_update(this);
     // Perform any auxiliary updates (i.e. reseting boundary conditions)
     if (Aux_node_update_fct_pt != 0)
     {
       Aux_node_update_fct_pt(this);
     }
   }
References oomph::Node::Aux_node_update_fct_pt, Spine_mesh_pt, and oomph::SpineMesh::spine_node_update().
Referenced by doc_sparse_node_update().
node_update_fct_id()
unsigned& oomph::SpineNode::node_update_fct_id () inline
Access function to ID of node update function (within specific mesh)
     {
       return Node_update_fct_id;
     }
References Node_update_fct_id.
Referenced by STSpineMesh< ELEMENT, INTERFACE_ELEMENT >::add_mesh(), AirwayReopeningProblem< ELEMENT >::AirwayReopeningProblem(), oomph::ChannelSpineMesh< ELEMENT >::build_channel_spine_mesh(), CombCanSpineMesh< ELEMENT, INTERFACE_ELEMENT >::build_single_layer_mesh(), CombTipSpineMesh< ELEMENT, INTERFACE_ELEMENT >::build_single_layer_mesh(), STSpineMesh< ELEMENT, INTERFACE_ELEMENT >::build_single_layer_mesh(), oomph::TwoLayerSpineMesh< BASE_ELEMENT >::build_two_layer_mesh(), doc_sparse_node_update(), oomph::BrethertonSpineMesh< ELEMENT, SpineLineFluidInterfaceElement< ELEMENT > >::initial_element_reorder(), SimpleSpineMesh< ELEMENT >::SimpleSpineMesh(), STSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update(), and oomph::TwoLayerSpineMesh< ELEMENT >::spine_node_update().
spine_mesh_pt()
SpineMesh*& oomph::SpineNode::spine_mesh_pt () inline
Access function to Pointer to SpineMesh that this node is a part of and which implements the node update function(s)
     {
       return Spine_mesh_pt;
     }
References Spine_mesh_pt.
Referenced by STSpineMesh< ELEMENT, INTERFACE_ELEMENT >::add_mesh(), AxialSpineQuarterTubeMesh< ELEMENT, INTERFACE_ELEMENT >::AxialSpineQuarterTubeMesh(), oomph::ChannelSpineMesh< ELEMENT >::build_channel_spine_mesh(), oomph::HorizontalSingleLayerSpineMesh< ELEMENT >::build_horizontal_single_layer_mesh(), MyCanyonMesh< ELEMENT, INTERFACE_ELEMENT >::build_single_layer_mesh(), CombCanSpineMesh< ELEMENT, INTERFACE_ELEMENT >::build_single_layer_mesh(), CombTipSpineMesh< ELEMENT, INTERFACE_ELEMENT >::build_single_layer_mesh(), STSpineMesh< ELEMENT, INTERFACE_ELEMENT >::build_single_layer_mesh(), MyTipMesh< ELEMENT, INTERFACE_ELEMENT >::build_single_layer_mesh(), oomph::SingleLayerCubicSpineMesh< ELEMENT >::build_single_layer_mesh(), oomph::SingleLayerSpineMesh< ELEMENT >::build_single_layer_mesh(), oomph::TwoLayerSpineMesh< BASE_ELEMENT >::build_two_layer_mesh(), SimpleSpineMesh< ELEMENT >::SimpleSpineMesh(), and SpineInclinedPlaneMesh< ELEMENT >::SpineInclinedPlaneMesh().
spine_pt()
Spine*& oomph::SpineNode::spine_pt () inline
Access function to spine.
     {
       return Spine_pt;
     }
References Spine_pt.
Referenced by oomph::AnnularSpineMesh< ELEMENT >::AnnularSpineMesh(), AxialSpineQuarterTubeMesh< ELEMENT, INTERFACE_ELEMENT >::AxialSpineQuarterTubeMesh(), oomph::ChannelSpineMesh< ELEMENT >::build_channel_spine_mesh(), oomph::HorizontalSingleLayerSpineMesh< ELEMENT >::build_horizontal_single_layer_mesh(), MyCanyonMesh< ELEMENT, INTERFACE_ELEMENT >::build_single_layer_mesh(), CombCanSpineMesh< ELEMENT, INTERFACE_ELEMENT >::build_single_layer_mesh(), CombTipSpineMesh< ELEMENT, INTERFACE_ELEMENT >::build_single_layer_mesh(), MyTipMesh< ELEMENT, INTERFACE_ELEMENT >::build_single_layer_mesh(), oomph::SingleLayerCubicSpineMesh< ELEMENT >::build_single_layer_mesh(), oomph::SingleLayerSpineMesh< ELEMENT >::build_single_layer_mesh(), oomph::TwoLayerSpineMesh< BASE_ELEMENT >::build_two_layer_mesh(), oomph::Hijacked< ELEMENT >::hijack_nodal_spine_value(), oomph::BrethertonSpineMesh< ELEMENT, SpineLineFluidInterfaceElement< ELEMENT > >::initial_element_reorder(), oomph::MeshHelper::merge_spine_meshes(), ThreeDimBethertonProblem< ELEMENT >::multiply_aspect_ratio(), No_Slip::no_slip_condition_first(), No_Slip::no_slip_condition_second(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::reposition_spines(), SimpleSpineMesh< ELEMENT >::SimpleSpineMesh(), oomph::AnnularSpineMesh< ELEMENT >::spine_node_update(), SimpleSpineMesh< ELEMENT >::spine_node_update(), MyCanyonMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update(), CombCanSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update(), CombTipSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update(), STSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update(), MyTipMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update(), oomph::ChannelSpineMesh< ELEMENT >::spine_node_update(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_channel(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_film_lower(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_film_upper(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_horizontal_transition_lower(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_horizontal_transition_upper(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_vertical_transition_lower(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_vertical_transition_upper(), SpineInclinedPlaneMesh< ELEMENT >::SpineInclinedPlaneMesh(), and ThreeDimBethertonProblem< ELEMENT >::ThreeDimBethertonProblem().
Member Data Documentation
Fraction
double oomph::SpineNode::Fraction private
Private double that represents the fixed fraction along the spine.
Referenced by fraction().
Node_update_fct_id
unsigned oomph::SpineNode::Node_update_fct_id private
ID of node update function (within specific mesh – useful if there are multiple node update functions, e.g. in two-layer problems.
Referenced by node_update_fct_id().
Spine_mesh_pt
SpineMesh* oomph::SpineNode::Spine_mesh_pt private
Pointer to SpineMesh that this node is a part of. (The mesh implements the node update function(s))
Referenced by node_update(), and spine_mesh_pt().
Spine_pt
Spine* oomph::SpineNode::Spine_pt private
Private internal data pointer to a spine.
Referenced by all_geom_data_pt(), all_geom_object_pt(), h(), ngeom_data(), ngeom_object(), and spine_pt().
The documentation for this class was generated from the following files:
spines.h
spines.cc