MercuryDPM: oomph::AlgebraicFSIDrivenCavityMesh< ELEMENT > Class Template Reference
oomph::AlgebraicFSIDrivenCavityMesh< ELEMENT > Class Template Reference
#include <fsi_driven_cavity_mesh.template.h>
Public Member Functions
AlgebraicFSIDrivenCavityMesh (const unsigned &nx, const unsigned &ny, const double &lx, const double &ly, const double &gap_fraction, GeomObject *wall_pt, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
virtual ~AlgebraicFSIDrivenCavityMesh ()
Destructor: empty.
void algebraic_node_update (const unsigned &t, AlgebraicNode *&node_pt)
void update_node_update (AlgebraicNode *&node_pt)
Public Member Functions inherited from oomph::FSIDrivenCavityMesh< ELEMENT >
FSIDrivenCavityMesh (const unsigned &nx, const unsigned &ny, const double &lx, const double &ly, const double &gap_fraction, GeomObject *wall_pt, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Public Member Functions inherited from oomph::SimpleRectangularQuadMesh< ELEMENT >
SimpleRectangularQuadMesh (const unsigned &Nx, const unsigned &Ny, const double &Lx, const double &Ly, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
const unsigned & nx () const
Access function for number of elements in x directions.
const unsigned & ny () const
Access function for number of elements in y directions.
Public Member Functions inherited from oomph::QuadMeshBase
QuadMeshBase ()
Constructor (empty)
QuadMeshBase (const QuadMeshBase &node)=delete
Broken copy constructor.
void operator= (const QuadMeshBase &)=delete
Broken assignment operator.
virtual ~QuadMeshBase ()
Destructor (empty)
void setup_boundary_element_info ()
void setup_boundary_element_info (std::ostream &outfile)
Public Member Functions inherited from oomph::Mesh
Mesh ()
Default constructor.
Mesh (const Vector< Mesh * > &sub_mesh_pt)
void merge_meshes (const Vector< Mesh * > &sub_mesh_pt)
virtual void reset_boundary_element_info (Vector< unsigned > &ntmp_boundary_elements, Vector< Vector< unsigned >> &ntmp_boundary_elements_in_region, Vector< FiniteElement * > &deleted_elements)
Virtual function to perform the reset boundary elements info rutines.
template<class BULK_ELEMENT >
void doc_boundary_coordinates (const unsigned &b, std::ofstream &the_file)
virtual void scale_mesh (const double &factor)
Mesh (const Mesh &dummy)=delete
Broken copy constructor.
void operator= (const Mesh &)=delete
Broken assignment operator.
virtual ~Mesh ()
Virtual Destructor to clean up all memory.
void flush_element_and_node_storage ()
void flush_element_storage ()
void flush_node_storage ()
Node *& node_pt (const unsigned long &n)
Return pointer to global node n.
Node * node_pt (const unsigned long &n) const
Return pointer to global node n (const version)
GeneralisedElement *& element_pt (const unsigned long &e)
Return pointer to element e.
GeneralisedElement * element_pt (const unsigned long &e) const
Return pointer to element e (const version)
const Vector< GeneralisedElement * > & element_pt () const
Return reference to the Vector of elements.
Vector< GeneralisedElement * > & element_pt ()
Return reference to the Vector of elements.
FiniteElement * finite_element_pt (const unsigned &e) const
Node *& boundary_node_pt (const unsigned &b, const unsigned &n)
Return pointer to node n on boundary b.
Node * boundary_node_pt (const unsigned &b, const unsigned &n) const
Return pointer to node n on boundary b.
void set_nboundary (const unsigned &nbound)
Set the number of boundaries in the mesh.
void remove_boundary_nodes ()
Clear all pointers to boundary nodes.
void remove_boundary_nodes (const unsigned &b)
void remove_boundary_node (const unsigned &b, Node *const &node_pt)
Remove a node from the boundary b.
void add_boundary_node (const unsigned &b, Node *const &node_pt)
Add a (pointer to) a node to the b-th boundary.
void copy_boundary_node_data_from_nodes ()
bool boundary_coordinate_exists (const unsigned &i) const
Indicate whether the i-th boundary has an intrinsic coordinate.
unsigned long nelement () const
Return number of elements in the mesh.
unsigned long nnode () const
Return number of nodes in the mesh.
unsigned ndof_types () const
Return number of dof types in mesh.
unsigned elemental_dimension () const
Return number of elemental dimension in mesh.
unsigned nodal_dimension () const
Return number of nodal dimension in mesh.
void add_node_pt (Node *const &node_pt)
Add a (pointer to a) node to the mesh.
void add_element_pt (GeneralisedElement *const &element_pt)
Add a (pointer to) an element to the mesh.
virtual void reorder_nodes (const bool &use_old_ordering=true)
virtual void get_node_reordering (Vector< Node * > &reordering, const bool &use_old_ordering=true) const
template<class BULK_ELEMENT , template< class > class FACE_ELEMENT>
void build_face_mesh (const unsigned &b, Mesh *const &face_mesh_pt)
unsigned self_test ()
Self-test: Check elements and nodes. Return 0 for OK.
void max_and_min_element_size (double &max_size, double &min_size)
double total_size ()
void check_inverted_elements (bool &mesh_has_inverted_elements, std::ofstream &inverted_element_file)
void check_inverted_elements (bool &mesh_has_inverted_elements)
unsigned check_for_repeated_nodes (const double &epsilon=1.0e-12)
Vector< Node * > prune_dead_nodes ()
unsigned nboundary () const
Return number of boundaries.
unsigned long nboundary_node (const unsigned &ibound) const
Return number of nodes on a particular boundary.
FiniteElement * boundary_element_pt (const unsigned &b, const unsigned &e) const
Return pointer to e-th finite element on boundary b.
Node * get_some_non_boundary_node () const
unsigned nboundary_element (const unsigned &b) const
Return number of finite elements that are adjacent to boundary b.
int face_index_at_boundary (const unsigned &b, const unsigned &e) const
virtual void dump (std::ofstream &dump_file, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
void dump (const std::string &dump_file_name, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
virtual void read (std::ifstream &restart_file)
Read solution from restart file.
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
void output (std::ostream &outfile)
Output for all elements.
void output (std::ostream &outfile, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output (FILE *file_pt)
Output for all elements (C-style output)
void output (FILE *file_pt, const unsigned &nplot)
Output at f(n_plot) points in each element (C-style output)
void output (const std::string &output_filename)
Output for all elements.
void output (const std::string &output_filename, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt)
Output a given Vector function at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt)
void output_boundaries (std::ostream &outfile)
Output the nodes on the boundaries (into separate tecplot zones)
void output_boundaries (const std::string &output_filename)
void assign_initial_values_impulsive ()
Assign initial values for an impulsive start.
void shift_time_values ()
void calculate_predictions ()
void set_nodal_and_elemental_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
virtual void set_mesh_level_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void set_consistent_pinned_values_for_continuation (ContinuationStorageScheme *const &continuation_stepper_pt)
Set consistent values for pinned data in continuation.
bool does_pointer_correspond_to_mesh_data (double *const &parameter_pt)
Does the double pointer correspond to any mesh data.
void set_nodal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
Set the timestepper associated with the nodal data in the mesh.
void set_elemental_internal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
virtual void compute_norm (double &norm)
virtual void compute_norm (Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Returns the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
bool is_mesh_distributed () const
Boolean to indicate if Mesh has been distributed.
OomphCommunicator * communicator_pt () const
void delete_all_external_storage ()
Wipe the storage for all externally-based elements.
Public Member Functions inherited from oomph::AlgebraicMesh
AlgebraicMesh ()
AlgebraicMesh (const AlgebraicMesh &)=delete
Broken copy constructor.
~AlgebraicMesh ()
Broken assignment operator.
AlgebraicNode * node_pt (const unsigned long &n)
Return a pointer to the n-th global AlgebraicNode.
void node_update (const bool &update_all_solid_nodes=false)
unsigned self_test ()
Self test: check consistentency of multiple node updates.
void add_geom_object_list_pt (GeomObject *geom_object_pt)
unsigned ngeom_object_list_pt ()
Return number of geometric objects associated with AlgebraicMesh.
GeomObject * geom_object_list_pt (const unsigned &i)
Access function to the ith GeomObject.
Protected Member Functions
void setup_algebraic_node_update ()
Function to setup the algebraic node update.
Protected Member Functions inherited from oomph::Mesh
unsigned long assign_global_eqn_numbers (Vector< double * > &Dof_pt)
Assign (global) equation numbers to the nodes.
void describe_dofs (std::ostream &out, const std::string &current_string) const
void describe_local_dofs (std::ostream &out, const std::string &current_string) const
void assign_local_eqn_numbers (const bool &store_local_dof_pt)
Assign local equation numbers in all elements.
void convert_to_boundary_node (Node *&node_pt, const Vector< FiniteElement * > &finite_element_pt)
void convert_to_boundary_node (Node *&node_pt)
Additional Inherited Members
Public Types inherited from oomph::Mesh
typedef void(FiniteElement::* SteadyExactSolutionFctPt) (const Vector< double > &x, Vector< double > &soln)
typedef void(FiniteElement::* UnsteadyExactSolutionFctPt) (const double &time, const Vector< double > &x, Vector< double > &soln)
Static Public Attributes inherited from oomph::Mesh
static Steady< 0 > Default_TimeStepper
The Steady Timestepper.
static bool Suppress_warning_about_empty_mesh_level_time_stepper_function
Static boolean flag to control warning about mesh level timesteppers.
Protected Attributes inherited from oomph::FSIDrivenCavityMesh< ELEMENT >
unsigned Nx
Number of elements in x direction.
unsigned Ny
Number of elements in y direction.
double Gap_fraction
GeomObject * Wall_pt
Pointer to geometric object that represents the moving wall.
Protected Attributes inherited from oomph::Mesh
Vector< Vector< Node * > > Boundary_node_pt
bool Lookup_for_elements_next_boundary_is_setup
Vector< Vector< FiniteElement * > > Boundary_element_pt
Vector< Vector< int > > Face_index_at_boundary
Vector< Node * > Node_pt
Vector of pointers to nodes.
Vector< GeneralisedElement * > Element_pt
Vector of pointers to generalised elements.
std::vector< bool > Boundary_coordinate_exists
Detailed Description
template<class ELEMENT>
class oomph::AlgebraicFSIDrivenCavityMesh< ELEMENT >
/ Alebraic node update version of FSIDrivenCavityMesh
Boundary 0 is the moving lid.
Boundary 1 is the gap above the moving lid on the right wall
Boundary 2 is the rigid part of the right wall
Boundary 3 is the moving (elastic) wall
Boundary 4 is the rigid part of the left wall
Boundary 5 is the gap above the moving lid on the left wall
Constructor & Destructor Documentation
AlgebraicFSIDrivenCavityMesh()
template<class ELEMENT > oomph::AlgebraicFSIDrivenCavityMesh< ELEMENT >::AlgebraicFSIDrivenCavityMesh (const unsigned & nx, const unsigned & ny, const double & lx, const double & ly, const double & gap_fraction, GeomObject * wall_pt, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper) inline
Constructor: Pass number of elements, lengths, pointer to GeomObject that defines the collapsible segment and pointer to TimeStepper (defaults to the default timestepper, Steady).
       : FSIDrivenCavityMesh<ELEMENT>(
           nx, ny, lx, ly, gap_fraction, wall_pt, time_stepper_pt)
     {
       // Add the geometric object to the list associated with this AlgebraicMesh
       AlgebraicMesh::add_geom_object_list_pt(wall_pt);
       // Setup algebraic node update operations
       setup_algebraic_node_update();
     }
References oomph::AlgebraicMesh::add_geom_object_list_pt(), and oomph::AlgebraicFSIDrivenCavityMesh< ELEMENT >::setup_algebraic_node_update().
~AlgebraicFSIDrivenCavityMesh()
template<class ELEMENT > virtual oomph::AlgebraicFSIDrivenCavityMesh< ELEMENT >::~AlgebraicFSIDrivenCavityMesh () inline virtual
Destructor: empty.
 {}
Member Function Documentation
algebraic_node_update()
template<class ELEMENT > void oomph::AlgebraicFSIDrivenCavityMesh< ELEMENT >::algebraic_node_update (const unsigned & t, AlgebraicNode *& node_pt) virtual
Update nodal position at time level t (t=0: present; t>0: previous)
//////////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////////// Perform algebraic mesh update at time level t (t=0: present; t>0: previous)
Implements oomph::AlgebraicMesh.
   {
 #ifdef PARANOID
     // We're updating the nodal positions (!) at time level t
     // and determine them by evaluating the wall GeomObject's
     // position at that gime level. I believe this only makes sense
     // if the t-th history value in the positional timestepper
     // actually represents previous values (rather than some
     // generalised quantity). Hence if this function is called with
     // t>nprev_values(), we issue a warning and terminate the execution.
     // It *might* be possible that the code still works correctly
     // even if this condition is violated (e.g. if the GeomObject's
     // position() function returns the appropriate "generalised"
     // position value that is required by the timestepping scheme but it's
     // probably worth flagging this up and forcing the user to manually switch
     // off this warning if he/she is 100% sure that this is kosher.
     if (t > node_pt->position_time_stepper_pt()->nprev_values())
     {
       std::string error_message =
         "Trying to update the nodal position at a time level";
       error_message += "beyond the number of previous values in the nodes'";
       error_message += "position timestepper. This seems highly suspect!";
       error_message += "If you're sure the code behaves correctly";
       error_message += "in your application, remove this warning ";
       error_message += "or recompile with PARNOID switched off.";
       std::string function_name = "AlgebraicFSIDrivenCavityMesh::";
       function_name += "algebraic_node_update()";
       throw OomphLibError(
         error_message, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
 #endif
     // Extract references for update by copy construction
     Vector<double> ref_value(node_pt->vector_ref_value());
     // First reference value: Original x-position. Used as the start point
     // for the lines connecting the nodes in the vertical direction
     double x_bottom = ref_value[0];
     // Second reference value: Fractional position along
     // straight line from the bottom (at the original x position)
     // to the reference point on the upper wall
     double fract = ref_value[1];
     // Third reference value:  Reference local coordinate
     // in GeomObject that represents the upper wall (local coordinate
     // in finite element if the wall GeomObject is a finite element mesh)
     Vector<double> s(1);
     s[0] = ref_value[2];
     // Fourth reference value: zeta coordinate on the upper wall
     // If the wall is a simple GeomObject, zeta[0]=s[0]
     // but if it's a compound GeomObject (e.g. a finite element mesh)
     // zeta scales during mesh refinement, whereas s[0] and the
     // pointer to the geom object have to be re-computed.
     // double zeta=ref_value[3]; // not needed here
     // Extract geometric objects for update by copy construction
     Vector<GeomObject*> geom_object_pt(node_pt->vector_geom_object_pt());
     // Pointer to actual wall geom object (either the same as the wall object
     // or the pointer to the actual finite element)
     GeomObject* geom_obj_pt = geom_object_pt[0];
     // Get position vector to wall at previous timestep t!
     Vector<double> r_wall(2);
     geom_obj_pt->position(t, s, r_wall);
     // Assign new nodal coordinate
     node_pt->x(t, 0) = x_bottom + fract * (r_wall[0] - x_bottom);
     node_pt->x(t, 1) = fract * r_wall[1];
   }
References oomph::TimeStepper::nprev_values(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::GeomObject::position(), oomph::Node::position_time_stepper_pt(), s, oomph::Global_string_for_annotation::string(), plotPSD::t, oomph::AlgebraicNode::vector_geom_object_pt(), oomph::AlgebraicNode::vector_ref_value(), and oomph::Node::x().
setup_algebraic_node_update()
template<class ELEMENT > void oomph::AlgebraicFSIDrivenCavityMesh< ELEMENT >::setup_algebraic_node_update protected
Function to setup the algebraic node update.
Setup algebraic mesh update – assumes that mesh has initially been set up with a flush upper wall.
   {
     // Loop over all nodes in mesh
     unsigned nnod = this->nnode();
     for (unsigned j = 0; j < nnod; j++)
     {
       // Get pointer to node -- recall that that Mesh::node_pt(...) has been
       // overloaded in the AlgebraicMesh class to return a pointer to
       // an AlgebraicNode.
       AlgebraicNode* nod_pt = node_pt(j);
       // Get coordinates
       double x = nod_pt->x(0);
       double y = nod_pt->x(1);
       // Get zeta coordinate on the undeformed wall
       Vector<double> zeta(1);
       zeta[0] = x;
       // Get pointer to geometric (sub-)object and Lagrangian coordinate
       // on that sub-object. For a wall that is represented by
       // a single geom object, this simply returns the input.
       // If the geom object consists of sub-objects (e.g.
       // if it is a finite element mesh representing a wall,
       // then we'll obtain the pointer to the finite element
       // (in its incarnation as a GeomObject) and the
       // local coordinate in that element.
       GeomObject* geom_obj_pt;
       Vector<double> s(1);
       this->Wall_pt->locate_zeta(zeta, geom_obj_pt, s);
       // Get position vector to wall:
       Vector<double> r_wall(2);
       geom_obj_pt->position(s, r_wall);
       // Sanity check: Confirm that the wall is in its undeformed position
 #ifdef PARANOID
       if ((std::fabs(r_wall[0] - x) > 1.0e-15) &&
           (std::fabs(r_wall[1] - y) > 1.0e-15))
       {
         std::ostringstream error_stream;
         error_stream << "Wall must be in its undeformed position when\n"
                      << "algebraic node update information is set up!\n "
                      << "x-discrepancy: " << std::fabs(r_wall[0] - x)
                      << std::endl
                      << "y-discrepancy: " << std::fabs(r_wall[1] - y)
                      << std::endl;
         throw OomphLibError(
           error_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
       }
 #endif
       // One geometric object is involved in update operation
       Vector<GeomObject*> geom_object_pt(1);
       // The actual geometric object (If the wall is simple GeomObject
       // this is the same as Wall_pt; if it's a compound GeomObject
       // this points to the sub-object)
       geom_object_pt[0] = geom_obj_pt;
       // The update function requires four  parameters:
       Vector<double> ref_value(4);
       // First reference value: Original x-position
       ref_value[0] = r_wall[0];
       // Second  reference value: fractional position along
       // straight line from the bottom (at the original x position)
       // to the point on the wall)
       ref_value[1] = y / r_wall[1];
       // Third reference value: Reference local coordinate
       // in wall element (local coordinate in FE if we're dealing
       // with a wall mesh)
       ref_value[2] = s[0];
       // Fourth reference value: zeta coordinate on wall
       // If the wall is a simple GeomObject, zeta[0]=s[0]
       // but if it's a compound GeomObject (e.g. a finite element mesh)
       // zeta scales during mesh refinement, whereas s[0] and the
       // pointer to the geom object have to be re-computed.
       ref_value[3] = zeta[0];
       // Setup algebraic update for node: Pass update information
       nod_pt->add_node_update_info(this, // mesh
                                    geom_object_pt, // vector of geom objects
                                    ref_value); // vector of  ref. values
     }
   } // end of setup_algebraic_node_update
References oomph::AlgebraicNode::add_node_update_info(), boost::multiprecision::fabs(), j, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::GeomObject::position(), s, plotDoE::x, oomph::Node::x(), y, and Eigen::zeta().
Referenced by oomph::AlgebraicFSIDrivenCavityMesh< ELEMENT >::AlgebraicFSIDrivenCavityMesh().
update_node_update()
template<class ELEMENT > void oomph::AlgebraicFSIDrivenCavityMesh< ELEMENT >::update_node_update (AlgebraicNode *& node_pt) inline virtual
Update the node-udate data after mesh adaptation. Empty – no update of node update required as this is non-refineable mesh.
Implements oomph::AlgebraicMesh.
Reimplemented in oomph::RefineableAlgebraicFSIDrivenCavityMesh< ELEMENT >.
 {}
The documentation for this class was generated from the following files:
fsi_driven_cavity_mesh.template.h
fsi_driven_cavity_mesh.template.cc