MercuryDPM: Eigen::internal::direct_selfadjoint_eigenvalues< SolverType, 2, false > Struct Template Reference
Eigen::internal::direct_selfadjoint_eigenvalues< SolverType, 2, false > Struct Template Reference
#include <SelfAdjointEigenSolver.h>
Public Types
typedef SolverType::MatrixType MatrixType
typedef SolverType::RealVectorType VectorType
typedef SolverType::Scalar Scalar
typedef SolverType::EigenvectorsType EigenvectorsType
Static Public Member Functions
static EIGEN_DEVICE_FUNC void computeRoots (const MatrixType &m, VectorType &roots)
static EIGEN_DEVICE_FUNC void run (SolverType &solver, const MatrixType &mat, int options)
Member Typedef Documentation
EigenvectorsType
template<typename SolverType > typedef SolverType::EigenvectorsType Eigen::internal::direct_selfadjoint_eigenvalues< SolverType, 2, false >::EigenvectorsType
MatrixType
template<typename SolverType > typedef SolverType::MatrixType Eigen::internal::direct_selfadjoint_eigenvalues< SolverType, 2, false >::MatrixType
Scalar
template<typename SolverType > typedef SolverType::Scalar Eigen::internal::direct_selfadjoint_eigenvalues< SolverType, 2, false >::Scalar
VectorType
template<typename SolverType > typedef SolverType::RealVectorType Eigen::internal::direct_selfadjoint_eigenvalues< SolverType, 2, false >::VectorType
Member Function Documentation
computeRoots()
template<typename SolverType > static EIGEN_DEVICE_FUNC void Eigen::internal::direct_selfadjoint_eigenvalues< SolverType, 2, false >::computeRoots (const MatrixType & m, VectorType & roots) inline static
{
     EIGEN_USING_STD(sqrt);
     const Scalar t0 = Scalar(0.5) * sqrt(numext::abs2(m(0, 0) - m(1, 1)) + Scalar(4) * numext::abs2(m(1, 0)));
     const Scalar t1 = Scalar(0.5) * (m(0, 0) + m(1, 1));
     roots(0) = t1 - t0;
     roots(1) = t1 + t0;
   }
References Eigen::numext::abs2(), EIGEN_USING_STD, m, and sqrt().
run()
template<typename SolverType > static EIGEN_DEVICE_FUNC void Eigen::internal::direct_selfadjoint_eigenvalues< SolverType, 2, false >::run (SolverType & solver, const MatrixType & mat, int options) inline static
{
     EIGEN_USING_STD(sqrt);
     EIGEN_USING_STD(abs);
     eigen_assert(mat.cols() == 2 && mat.cols() == mat.rows());
     eigen_assert((options & ~(EigVecMask | GenEigMask)) == 0 && (options & EigVecMask) != EigVecMask &&
                  "invalid option parameter");
     bool computeEigenvectors = (options & ComputeEigenvectors) == ComputeEigenvectors;
     EigenvectorsType& eivecs = solver.m_eivec;
     VectorType& eivals = solver.m_eivalues;
     // Shift the matrix to the mean eigenvalue and map the matrix coefficients to [-1:1] to avoid over- and underflow.
     Scalar shift = mat.trace() / Scalar(2);
     MatrixType scaledMat = mat;
     scaledMat.coeffRef(0, 1) = mat.coeff(1, 0);
     scaledMat.diagonal().array() -= shift;
     Scalar scale = scaledMat.cwiseAbs().maxCoeff();
     if (scale > Scalar(0)) scaledMat /= scale;
     // Compute the eigenvalues
     computeRoots(scaledMat, eivals);
     // compute the eigen vectors
     if (computeEigenvectors) {
       if ((eivals(1) - eivals(0)) <= abs(eivals(1)) * Eigen::NumTraits<Scalar>::epsilon()) {
         eivecs.setIdentity();
       } else {
         scaledMat.diagonal().array() -= eivals(1);
         Scalar a2 = numext::abs2(scaledMat(0, 0));
         Scalar c2 = numext::abs2(scaledMat(1, 1));
         Scalar b2 = numext::abs2(scaledMat(1, 0));
         if (a2 > c2) {
           eivecs.col(1) << -scaledMat(1, 0), scaledMat(0, 0);
           eivecs.col(1) /= sqrt(a2 + b2);
         } else {
           eivecs.col(1) << -scaledMat(1, 1), scaledMat(1, 0);
           eivecs.col(1) /= sqrt(c2 + b2);
         }
         eivecs.col(0) << eivecs.col(1).unitOrthogonal();
       }
     }
     // Rescale back to the original size.
     eivals *= scale;
     eivals.array() += shift;
     solver.m_info = Success;
     solver.m_isInitialized = true;
     solver.m_eigenvectorsOk = computeEigenvectors;
   }
References abs(), Eigen::numext::abs2(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::coeff(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::coeffRef(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::cols(), Eigen::ComputeEigenvectors, computeRoots(), eigen_assert, EIGEN_USING_STD, Eigen::EigVecMask, eivals, Eigen::GenEigMask, Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::rows(), solver, sqrt(), and Eigen::Success.
The documentation for this struct was generated from the following file:
SelfAdjointEigenSolver.h