MercuryDPM: oomph::Integral Class Reference
oomph::Integral Class Reference abstract
#include <integral.h>
Public Member Functions
Integral ()
Default constructor (empty)
Integral (const Integral &dummy)=delete
Broken copy constructor.
void operator= (const Integral &)=delete
Broken assignment operator.
virtual ~Integral ()
Virtual destructor (empty)
virtual unsigned nweight () const =0
Return the number of integration points of the scheme.
virtual double knot (const unsigned &i, const unsigned &j) const =0
Return local coordinate s[j] of i-th integration point.
virtual Vector< double > knot (const unsigned &i) const
Return local coordinates of i-th intergration point. Broken virtual.
virtual double weight (const unsigned &i) const =0
Return weight of i-th integration point.
Detailed Description
Generic class for numerical integration schemes:
\[ \int f(x_0,x_1...)\ dx_0 \ dx_1... = \sum_{i_{int}=0}^{\mbox{\tt nweight()} } f(x_j=\mbox{\tt knot($i_{int}$,j)}) \ \ \ \mbox{\tt weight($i_{int}$)} \]
Constructor & Destructor Documentation
Integral() [1/2]
oomph::Integral::Integral () inline
Default constructor (empty)
 {};
Integral() [2/2]
oomph::Integral::Integral (const Integral & dummy) delete
Broken copy constructor.
~Integral()
virtual oomph::Integral::~Integral () inline virtual
Virtual destructor (empty)
 {};
Member Function Documentation
knot() [1/2]
virtual Vector<double> oomph::Integral::knot (const unsigned & i) const inline virtual
Return local coordinates of i-th intergration point. Broken virtual.
     {
       throw OomphLibError("Not implemented for this integration scheme (yet?).",
                           OOMPH_CURRENT_FUNCTION,
                           OOMPH_EXCEPTION_LOCATION);
     }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
knot() [2/2]
virtual double oomph::Integral::knot (const unsigned & i, const unsigned & j) const pure virtual
Return local coordinate s[j] of i-th integration point.
Implemented in oomph::GaussLegendre< 3, NPTS_1D >, oomph::GaussLegendre< 2, NPTS_1D >, oomph::GaussLegendre< 1, NPTS_1D >, oomph::GaussLobattoLegendre< 3, NPTS_1D >, oomph::GaussLobattoLegendre< 2, NPTS_1D >, oomph::GaussLobattoLegendre< 1, NPTS_1D >, oomph::TGauss< 3, 5 >, oomph::TGauss< 3, 3 >, oomph::TGauss< 3, 2 >, oomph::TGauss< 2, 5 >, oomph::TGauss< 2, 16 >, oomph::TGauss< 2, 9 >, oomph::TGauss< 2, 13 >, oomph::TGauss< 2, 4 >, oomph::TGauss< 2, 3 >, oomph::TGauss< 2, 2 >, oomph::TGauss< 1, 5 >, oomph::TGauss< 1, 4 >, oomph::TGauss< 1, 3 >, oomph::TGauss< 1, 2 >, oomph::Gauss< 3, 4 >, oomph::Gauss< 3, 3 >, oomph::Gauss< 3, 2 >, oomph::Gauss< 2, 4 >, oomph::Gauss< 2, 3 >, oomph::Gauss< 2, 2 >, oomph::Gauss< 1, 4 >, oomph::Gauss< 1, 3 >, oomph::Gauss< 1, 2 >, oomph::PointIntegral, MyIntegral, MyIntegral, and MortaringHelpers::PointIntegralScheme.
Referenced by oomph::NavierStokesImpedanceTractionElement< BULK_NAVIER_STOKES_ELEMENT, WOMERSLEY_ELEMENT, DIM >::add_element_contribution_to_aux_integral(), oomph::Multi_domain_functions::aux_setup_multi_domain_interaction(), FourierDecomposedHelmholtzProblem< ELEMENT >::check_gamma(), oomph::Mesh::check_inverted_elements(), oomph::HelmholtzBCElementBase< ELEMENT >::compute_contribution_to_fourier_components(), oomph::AxisymAdvectionDiffusionEquations::compute_error(), oomph::AxisymFoepplvonKarmanEquations::compute_error(), oomph::AxisymmetricLinearElasticityEquations::compute_error(), oomph::BiharmonicEquations< DIM >::compute_error(), oomph::DisplacementBasedFoepplvonKarmanEquations::compute_error(), oomph::FoepplvonKarmanEquations::compute_error(), oomph::FourierDecomposedHelmholtzEquations::compute_error(), oomph::PMLFourierDecomposedHelmholtzEquations::compute_error(), oomph::SphericalAdvectionDiffusionEquations::compute_error(), oomph::SteadyAxisymAdvectionDiffusionEquations::compute_error(), oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations::compute_error(), oomph::YoungLaplaceEquations::compute_error(), oomph::AxisymmetricPoroelasticityEquations::compute_error(), oomph::AxisymmetricNavierStokesEquations::compute_error(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::compute_error(), oomph::PolarNavierStokesEquations::compute_error(), oomph::SphericalNavierStokesEquations::compute_error(), oomph::SphericalNavierStokesEquations::compute_error_e(), oomph::SolidFiniteElement::compute_norm(), oomph::FourierDecomposedHelmholtzEquations::compute_norm(), oomph::PMLFourierDecomposedHelmholtzEquations::compute_norm(), oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations::compute_norm(), oomph::AxisymmetricNavierStokesEquations::compute_physical_size(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::compute_physical_size(), AirwayReopeningProblem< ELEMENT >::connect_walls(), oomph::FaceElement::continuous_tangent_and_outer_unit_normal(), oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::contribution_to_enclosed_volume(), oomph::LineVolumeConstraintBoundingElement::contribution_to_enclosed_volume(), oomph::AxisymmetricVolumeConstraintBoundingElement::contribution_to_enclosed_volume(), oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::contribution_to_total_porous_flux(), oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::contribution_to_total_porous_flux(), oomph::AxisymmetricVolumeConstraintBoundingElement::contribution_to_volume_flux(), oomph::FiniteElement::d2shape_local_at_knot(), oomph::AxisymmetricNavierStokesEquations::dissipation(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::dissipation(), oomph::PolarNavierStokesEquations::dissipation(), oomph::SphericalNavierStokesEquations::dissipation(), oomph::LinearisedAxisymmetricNavierStokesEquations::dkin_energy_dt(), oomph::FSI_functions::doc_fsi(), ContactProblem< ELEMENT >::doc_solution(), StefanBoltzmannProblem< ELEMENT >::doc_solution(), oomph::NavierStokesSurfacePowerElement< ELEMENT >::drag_force(), oomph::FiniteElement::dshape_local_at_knot(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::extrapolated_strain_rate(), oomph::GeneralisedNewtonianNavierStokesEquations< DIM >::extrapolated_strain_rate(), oomph::AxisymmetricNavierStokesEquations::fill_in_contribution_to_hessian_vector_products(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_contribution_to_hessian_vector_products(), oomph::ClampedHermiteShellBoundaryConditionElement::fill_in_contribution_to_residuals(), oomph::AxisymmetricLinearElasticityEquations::fill_in_generic_contribution_to_residuals_axisymmetric_linear_elasticity(), oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations::fill_in_generic_contribution_to_residuals_fourier_decomp_time_harmonic_linear_elasticity(), oomph::RefineableQDPVDElement< DIM, NNODE_1D >::fill_in_generic_contribution_to_residuals_pvd(), oomph::AxisymmetricNavierStokesEquations::fill_in_generic_dresidual_contribution_axi_nst(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_generic_dresidual_contribution_axi_nst(), oomph::SolidFiniteElement::fill_in_generic_jacobian_for_solid_ic(), oomph::AxisymmetricPoroelasticityEquations::fill_in_generic_residual_contribution(), oomph::PolarNavierStokesEquations::fill_in_generic_residual_contribution(), oomph::RefineablePolarNavierStokesEquations::fill_in_generic_residual_contribution(), oomph::SteadyAxisymAdvectionDiffusionEquations::fill_in_generic_residual_contribution_adv_diff(), oomph::AxisymAdvectionDiffusionEquations::fill_in_generic_residual_contribution_axi_adv_diff(), oomph::RefineableAxisymAdvectionDiffusionEquations::fill_in_generic_residual_contribution_axi_adv_diff(), oomph::AxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), oomph::RefineableAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), oomph::RefineableGeneralisedAxisymAdvectionDiffusionEquations::fill_in_generic_residual_contribution_cons_axisym_adv_diff(), oomph::FourierDecomposedHelmholtzDtNBoundaryElement< ELEMENT >::fill_in_generic_residual_contribution_fourier_decomposed_helmholtz_DtN_bc(), oomph::HelmholtzAbsorbingBCElement< ELEMENT >::fill_in_generic_residual_contribution_helmholtz_abc(), oomph::HelmholtzDtNBoundaryElement< ELEMENT >::fill_in_generic_residual_contribution_helmholtz_DtN_bc(), oomph::FluidInterfaceElement::fill_in_generic_residual_contribution_interface(), oomph::LineFluidInterfaceBoundingElement::fill_in_generic_residual_contribution_interface_boundary(), oomph::LinearisedAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_lin_axi_nst(), oomph::LinearisedAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_linearised_axi_nst(), oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_linearised_axi_nst(), oomph::LinearisedNavierStokesEquations::fill_in_generic_residual_contribution_linearised_nst(), oomph::RefineableLinearisedNavierStokesEquations::fill_in_generic_residual_contribution_linearised_nst(), oomph::RefineableSphericalAdvectionDiffusionEquations::fill_in_generic_residual_contribution_spherical_adv_diff(), oomph::SphericalAdvectionDiffusionEquations::fill_in_generic_residual_contribution_spherical_adv_diff(), oomph::RefineableSphericalNavierStokesEquations::fill_in_generic_residual_contribution_spherical_nst(), oomph::SphericalNavierStokesEquations::fill_in_generic_residual_contribution_spherical_nst(), oomph::LineVolumeConstraintBoundingElement::fill_in_generic_residual_contribution_volume_constraint(), oomph::AxisymmetricVolumeConstraintBoundingElement::fill_in_generic_residual_contribution_volume_constraint(), oomph::SurfaceVolumeConstraintBoundingElement::fill_in_generic_residual_contribution_volume_constraint(), oomph::SolidFiniteElement::fill_in_jacobian_for_newmark_accel(), oomph::NavierStokesSurfaceDragTorqueElement< ELEMENT >::get_drag_and_torque(), oomph::AxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates(), oomph::RefineableAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates(), oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates(), oomph::Z2ErrorEstimator::get_element_errors(), oomph::NavierStokesSurfacePowerElement< ELEMENT >::get_kinetic_energy_flux(), oomph::NavierStokesSurfacePowerElement< ELEMENT >::get_rate_of_traction_work(), oomph::NavierStokesSurfacePowerElement< ELEMENT >::get_rate_of_traction_work_components(), oomph::Z2ErrorEstimator::get_recovered_flux_in_patch(), oomph::VorticitySmoother< ELEMENT >::get_recovered_vorticity_in_patch(), oomph::FSILinearisedAxisymPoroelasticTractionElement< POROELASTICITY_BULK_ELEMENT, NAVIER_STOKES_BULK_ELEMENT >::get_traction(), oomph::NavierStokesImpedanceTractionElement< BULK_NAVIER_STOKES_ELEMENT, WOMERSLEY_ELEMENT, DIM >::get_volume_flux(), oomph::NavierStokesSurfacePowerElement< ELEMENT >::get_volume_flux(), oomph::PMLHelmholtzPowerElement< ELEMENT >::global_flux_contribution(), oomph::TimeHarmonicLinElastLoadedByPMLHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::global_flux_contribution_from_helmholtz(), oomph::TimeHarmonicLinElastLoadedByPMLHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::global_flux_contribution_from_solid(), oomph::FourierDecomposedHelmholtzBCElementBase< ELEMENT >::global_power_contribution(), oomph::HelmholtzBCElementBase< ELEMENT >::global_power_contribution(), oomph::PMLFourierDecomposedHelmholtzPowerMonitorElement< ELEMENT >::global_power_contribution(), oomph::PMLHelmholtzPowerElement< ELEMENT >::global_power_contribution(), oomph::SurfactantTransportInterfaceElement::integrate_c(), oomph::FiniteElement::integrate_fct(), oomph::SolubleSurfactantTransportInterfaceElement::integrated_C(), oomph::AxisymmetricNavierStokesEquations::kin_energy(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::kin_energy(), oomph::PolarNavierStokesEquations::kin_energy(), oomph::SphericalNavierStokesEquations::kin_energy(), oomph::SolubleSurfactantTransportInterfaceElement::l2_norm_of_height(), oomph::KirchhoffLoveShellEquations::load_rate_of_work(), oomph::Multi_domain_functions::locate_zeta_for_local_coordinates(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::max_and_min_invariant_and_viscosity(), oomph::FaceElement::outer_unit_normal(), oomph::UnsteadyHeatBaseFaceElement< ELEMENT >::output(), oomph::FSIAxisymmetricLinearElasticityTractionElement< ELASTICITY_BULK_ELEMENT, NAVIER_STOKES_BULK_ELEMENT >::output(), oomph::LinearisedFSIAxisymmetricNStNoSlipBCElementElement< FLUID_BULK_ELEMENT, SOLID_BULK_ELEMENT >::output(), oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::output(), oomph::FSILinearisedAxisymPoroelasticTractionElement< POROELASTICITY_BULK_ELEMENT, NAVIER_STOKES_BULK_ELEMENT >::output(), oomph::FourierDecomposedTimeHarmonicLinElastLoadedByHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::output(), oomph::FourierDecomposedHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::output(), oomph::TimeHarmonicLinElastLoadedByHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::output(), oomph::HelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::output(), oomph::TimeHarmonicLinElastLoadedByPMLHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::output(), oomph::PMLHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::output(), oomph::ClampedHermiteShellBoundaryConditionElement::output(), oomph::FSISolidTractionElement< ELEMENT, DIM >::output(), oomph::SolarRadiationBase::output_atmospheric_radiation(), oomph::SolarRadiationBase::output_diffuse_radiation_cone(), oomph::SolarRadiationBase::output_diffuse_radiation_cone_max_angle(), oomph::SolarRadiationBase::output_diffuse_radiation_cone_min_angle(), oomph::ElementWithExternalElement::output_external_elements(), oomph::FSIAxisymFoepplvonKarmanElement< NNODE_1D, FLUID_ELEMENT >::output_integration_points(), oomph::SolarRadiationBase::output_limiting_angles(), oomph::SurfaceMeltElement< ELEMENT >::output_melt(), oomph::NavierStokesEquations< DIM >::output_pressure_advection_diffusion_robin_elements(), oomph::SpaceTimeNavierStokesEquations< DIM >::output_pressure_advection_diffusion_robin_elements(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::output_pressure_advection_diffusion_robin_elements(), oomph::StefanBoltzmannUnsteadyHeatFluxElement< ELEMENT >::output_stefan_boltzmann_radiation(), oomph::StefanBoltzmannRadiationBase::output_stefan_boltzmann_radiation_rays(), oomph::AxisymmetricNavierStokesEquations::pressure_integral(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::pressure_integral(), oomph::PolarNavierStokesEquations::pressure_integral(), oomph::SphericalNavierStokesEquations::pressure_integral(), oomph::DGFaceElement::report_info(), oomph::ProjectableAxisymmetricPoroelasticityElement< AXISYMMETRIC_POROELASTICITY_ELEMENT >::residual_for_projection(), oomph::ProjectableDarcyElement< DARCY_ELEMENT >::residual_for_projection(), oomph::ProjectableElement< ELEMENT >::residual_for_projection(), oomph::FiniteElement::self_test(), oomph::FourierDecomposedHelmholtzDtNMesh< ELEMENT >::setup_gamma(), oomph::HelmholtzDtNMesh< ELEMENT >::setup_gamma(), oomph::DGFaceElement::setup_neighbour_info(), oomph::StefanBoltzmannHelper::setup_stefan_boltzmann_visibility(), oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >::shape_and_test_at_knot(), oomph::NavierStokesMixedOrderSpaceTimeTractionElement< ELEMENT >::shape_and_test_at_knot(), oomph::FiniteElement::shape_at_knot(), oomph::TAxisymmetricPoroelasticityElement< ORDER >::shape_basis_test_local_at_knot(), oomph::TPoroelasticityElement< ORDER >::shape_basis_test_local_at_knot(), oomph::TRaviartThomasDarcyElement< ORDER >::shape_basis_test_local_at_knot(), oomph::AxisymmetricPVDEquationsWithPressure::solid_pshape_at_knot(), oomph::PVDEquationsWithPressure< DIM >::solid_pshape_at_knot(), oomph::MyTaylorHoodElement< DIM >::square_of_l2_norm(), and oomph::SolarRadiationBase::update_limiting_angles().
nweight()
virtual unsigned oomph::Integral::nweight () const pure virtual
Return the number of integration points of the scheme.
Implemented in oomph::GaussLegendre< 3, NPTS_1D >, oomph::GaussLegendre< 2, NPTS_1D >, oomph::GaussLegendre< 1, NPTS_1D >, oomph::GaussLobattoLegendre< 3, NPTS_1D >, oomph::GaussLobattoLegendre< 2, NPTS_1D >, oomph::GaussLobattoLegendre< 1, NPTS_1D >, oomph::TGauss< 3, 5 >, oomph::TGauss< 3, 3 >, oomph::TGauss< 3, 2 >, oomph::TGauss< 2, 5 >, oomph::TGauss< 2, 16 >, oomph::TGauss< 2, 9 >, oomph::TGauss< 2, 13 >, oomph::TGauss< 2, 4 >, oomph::TGauss< 2, 3 >, oomph::TGauss< 2, 2 >, oomph::TGauss< 1, 5 >, oomph::TGauss< 1, 4 >, oomph::TGauss< 1, 3 >, oomph::TGauss< 1, 2 >, oomph::Gauss< 3, 4 >, oomph::Gauss< 3, 3 >, oomph::Gauss< 3, 2 >, oomph::Gauss< 2, 4 >, oomph::Gauss< 2, 3 >, oomph::Gauss< 2, 2 >, oomph::Gauss< 1, 4 >, oomph::Gauss< 1, 3 >, oomph::Gauss< 1, 2 >, oomph::PointIntegral, MyIntegral, MyIntegral, and MortaringHelpers::PointIntegralScheme.
Referenced by oomph::NavierStokesImpedanceTractionElement< BULK_NAVIER_STOKES_ELEMENT, WOMERSLEY_ELEMENT, DIM >::add_element_contribution_to_aux_integral(), oomph::DGFaceElement::add_flux_contributions(), oomph::ElementWithExternalElement::assign_external_interaction_data_local_eqn_numbers(), oomph::Multi_domain_functions::aux_setup_multi_domain_interaction(), FourierDecomposedHelmholtzProblem< ELEMENT >::check_gamma(), oomph::Mesh::check_inverted_elements(), oomph::FiniteElement::check_J_eulerian_at_knots(), oomph::FaceElement::check_J_eulerian_at_knots(), oomph::HelmholtzBCElementBase< ELEMENT >::compute_contribution_to_fourier_components(), oomph::AxisymAdvectionDiffusionEquations::compute_error(), oomph::AxisymFoepplvonKarmanEquations::compute_error(), oomph::AxisymmetricLinearElasticityEquations::compute_error(), oomph::BiharmonicEquations< DIM >::compute_error(), oomph::DisplacementBasedFoepplvonKarmanEquations::compute_error(), oomph::FoepplvonKarmanEquations::compute_error(), oomph::FourierDecomposedHelmholtzEquations::compute_error(), oomph::PMLFourierDecomposedHelmholtzEquations::compute_error(), oomph::SphericalAdvectionDiffusionEquations::compute_error(), oomph::SteadyAxisymAdvectionDiffusionEquations::compute_error(), oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations::compute_error(), oomph::YoungLaplaceEquations::compute_error(), oomph::AxisymmetricPoroelasticityEquations::compute_error(), oomph::AxisymmetricNavierStokesEquations::compute_error(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::compute_error(), oomph::PolarNavierStokesEquations::compute_error(), oomph::SphericalNavierStokesEquations::compute_error(), oomph::EulerEquations< DIM >::compute_error(), oomph::ScalarAdvectionEquations< DIM >::compute_error(), oomph::SphericalNavierStokesEquations::compute_error_e(), oomph::SolidFiniteElement::compute_norm(), oomph::FourierDecomposedHelmholtzEquations::compute_norm(), oomph::PMLFourierDecomposedHelmholtzEquations::compute_norm(), oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations::compute_norm(), oomph::AxisymmetricNavierStokesEquations::compute_physical_size(), oomph::AxisymmetricPVDEquations::compute_physical_size(), oomph::AxisymmetricPVDEquationsWithPressure::compute_physical_size(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::compute_physical_size(), AirwayReopeningProblem< ELEMENT >::connect_walls(), oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::contribution_to_enclosed_volume(), oomph::LineVolumeConstraintBoundingElement::contribution_to_enclosed_volume(), oomph::AxisymmetricVolumeConstraintBoundingElement::contribution_to_enclosed_volume(), oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::contribution_to_total_porous_flux(), oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::contribution_to_total_porous_flux(), oomph::AxisymmetricVolumeConstraintBoundingElement::contribution_to_volume_flux(), oomph::SphericalNavierStokesEquations::d_kin_energy_dt(), oomph::AxisymmetricNavierStokesEquations::dissipation(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::dissipation(), oomph::PolarNavierStokesEquations::dissipation(), oomph::SphericalNavierStokesEquations::dissipation(), oomph::LinearisedAxisymmetricNavierStokesEquations::dkin_energy_dt(), oomph::FSI_functions::doc_fsi(), ContactProblem< ELEMENT >::doc_solution(), StefanBoltzmannProblem< ELEMENT >::doc_solution(), oomph::NavierStokesSurfacePowerElement< ELEMENT >::drag_force(), oomph::AxisymmetricNavierStokesEquations::fill_in_contribution_to_hessian_vector_products(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_contribution_to_hessian_vector_products(), oomph::AxisymFoepplvonKarmanEquations::fill_in_contribution_to_residuals(), oomph::DisplacementBasedFoepplvonKarmanEquations::fill_in_contribution_to_residuals(), oomph::FoepplvonKarmanEquations::fill_in_contribution_to_residuals(), oomph::ClampedHermiteShellBoundaryConditionElement::fill_in_contribution_to_residuals(), oomph::RefineableYoungLaplaceEquations::fill_in_contribution_to_residuals(), oomph::YoungLaplaceEquations::fill_in_contribution_to_residuals(), oomph::AxisymmetricPVDEquations::fill_in_contribution_to_residuals_axisym_pvd(), oomph::KirchhoffLoveBeamEquations::fill_in_contribution_to_residuals_beam(), oomph::KirchhoffLoveShellEquations::fill_in_contribution_to_residuals_shell(), oomph::AxisymmetricLinearElasticityEquations::fill_in_generic_contribution_to_residuals_axisymmetric_linear_elasticity(), oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::fill_in_generic_contribution_to_residuals_displ_lagr_multiplier(), oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations::fill_in_generic_contribution_to_residuals_fourier_decomp_time_harmonic_linear_elasticity(), oomph::FSIImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::fill_in_generic_contribution_to_residuals_fsi_displ_lagr_multiplier(), oomph::ImposeImpenetrabilityElement< ELEMENT >::fill_in_generic_contribution_to_residuals_parall_lagr_multiplier(), oomph::ImposeParallelOutflowElement< ELEMENT >::fill_in_generic_contribution_to_residuals_parall_lagr_multiplier(), oomph::RefineableQDPVDElement< DIM, NNODE_1D >::fill_in_generic_contribution_to_residuals_pvd(), oomph::AxisymmetricNavierStokesEquations::fill_in_generic_dresidual_contribution_axi_nst(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_generic_dresidual_contribution_axi_nst(), oomph::SolidFiniteElement::fill_in_generic_jacobian_for_solid_ic(), oomph::AxisymmetricPoroelasticityEquations::fill_in_generic_residual_contribution(), oomph::PolarNavierStokesEquations::fill_in_generic_residual_contribution(), oomph::RefineablePolarNavierStokesEquations::fill_in_generic_residual_contribution(), oomph::RefineablePolarStreamfunctionEquations::fill_in_generic_residual_contribution(), oomph::PolarStreamfunctionEquations::fill_in_generic_residual_contribution(), oomph::SteadyAxisymAdvectionDiffusionEquations::fill_in_generic_residual_contribution_adv_diff(), oomph::AxisymAdvectionDiffusionEquations::fill_in_generic_residual_contribution_axi_adv_diff(), oomph::RefineableAxisymAdvectionDiffusionEquations::fill_in_generic_residual_contribution_axi_adv_diff(), oomph::AxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), oomph::RefineableAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), oomph::AxisymmetricPVDEquationsWithPressure::fill_in_generic_residual_contribution_axisym_pvd_with_pressure(), oomph::RefineableGeneralisedAxisymAdvectionDiffusionEquations::fill_in_generic_residual_contribution_cons_axisym_adv_diff(), oomph::NavierStokesFluxControlElement< ELEMENT >::fill_in_generic_residual_contribution_fluid_traction(), oomph::FourierDecomposedHelmholtzEquations::fill_in_generic_residual_contribution_fourier_decomposed_helmholtz(), oomph::FourierDecomposedHelmholtzDtNBoundaryElement< ELEMENT >::fill_in_generic_residual_contribution_fourier_decomposed_helmholtz_DtN_bc(), oomph::HelmholtzAbsorbingBCElement< ELEMENT >::fill_in_generic_residual_contribution_helmholtz_abc(), oomph::HelmholtzDtNBoundaryElement< ELEMENT >::fill_in_generic_residual_contribution_helmholtz_DtN_bc(), oomph::FluidInterfaceElement::fill_in_generic_residual_contribution_interface(), oomph::LineFluidInterfaceBoundingElement::fill_in_generic_residual_contribution_interface_boundary(), oomph::LinearisedAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_lin_axi_nst(), oomph::LinearisedAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_linearised_axi_nst(), oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_linearised_axi_nst(), oomph::LinearisedNavierStokesEquations::fill_in_generic_residual_contribution_linearised_nst(), oomph::RefineableLinearisedNavierStokesEquations::fill_in_generic_residual_contribution_linearised_nst(), oomph::PeriodicOrbitEquations::fill_in_generic_residual_contribution_orbit(), oomph::PMLFourierDecomposedHelmholtzEquations::fill_in_generic_residual_contribution_pml_fourier_decomposed_helmholtz(), oomph::RefineableSphericalAdvectionDiffusionEquations::fill_in_generic_residual_contribution_spherical_adv_diff(), oomph::SphericalAdvectionDiffusionEquations::fill_in_generic_residual_contribution_spherical_adv_diff(), oomph::RefineableSphericalNavierStokesEquations::fill_in_generic_residual_contribution_spherical_nst(), oomph::SphericalNavierStokesEquations::fill_in_generic_residual_contribution_spherical_nst(), oomph::LineVolumeConstraintBoundingElement::fill_in_generic_residual_contribution_volume_constraint(), oomph::AxisymmetricVolumeConstraintBoundingElement::fill_in_generic_residual_contribution_volume_constraint(), oomph::SurfaceVolumeConstraintBoundingElement::fill_in_generic_residual_contribution_volume_constraint(), oomph::SolidFiniteElement::fill_in_jacobian_for_newmark_accel(), oomph::RefineableNavierStokesBoussinesqElement< NST_ELEMENT, AD_ELEMENT >::fill_in_off_diagonal_block_analytic(), oomph::RefineableAdvectionDiffusionBoussinesqElement< AD_ELEMENT, NST_ELEMENT >::fill_in_off_diagonal_block_analytic(), oomph::NavierStokesBoussinesqElement< NST_ELEMENT, AD_ELEMENT >::fill_in_off_diagonal_block_analytic(), oomph::AdvectionDiffusionBoussinesqElement< AD_ELEMENT, NST_ELEMENT >::fill_in_off_diagonal_block_analytic(), oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::fill_in_off_diagonal_jacobian_blocks_analytic(), oomph::RefineableBuoyantQSphericalCrouzeixRaviartElement::fill_in_off_diagonal_jacobian_blocks_analytic(), oomph::BuoyantQCrouzeixRaviartElement< DIM >::fill_in_off_diagonal_jacobian_blocks_analytic(), oomph::RefineableBuoyantQCrouzeixRaviartElement< DIM >::fill_in_off_diagonal_jacobian_blocks_analytic(), oomph::FoepplvonKarmanEquations::get_bounded_volume(), oomph::NavierStokesSurfaceDragTorqueElement< ELEMENT >::get_drag_and_torque(), oomph::AxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates(), oomph::RefineableAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates(), oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates(), oomph::Z2ErrorEstimator::get_element_errors(), oomph::KirchhoffLoveShellEquations::get_energy(), oomph::KirchhoffLoveBeamEquations::get_energy(), oomph::NavierStokesSurfacePowerElement< ELEMENT >::get_kinetic_energy_flux(), oomph::AxisymmetricNavierStokesEquations::get_pressure_and_velocity_mass_matrix_diagonal(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::get_pressure_and_velocity_mass_matrix_diagonal(), oomph::SphericalNavierStokesEquations::get_pressure_and_velocity_mass_matrix_diagonal(), oomph::NavierStokesSurfacePowerElement< ELEMENT >::get_rate_of_traction_work(), oomph::NavierStokesSurfacePowerElement< ELEMENT >::get_rate_of_traction_work_components(), oomph::Z2ErrorEstimator::get_recovered_flux_in_patch(), oomph::VorticitySmoother< ELEMENT >::get_recovered_vorticity_in_patch(), oomph::NavierStokesImpedanceTractionElement< BULK_NAVIER_STOKES_ELEMENT, WOMERSLEY_ELEMENT, DIM >::get_volume_flux(), oomph::NavierStokesSurfacePowerElement< ELEMENT >::get_volume_flux(), oomph::PMLHelmholtzPowerElement< ELEMENT >::global_flux_contribution(), oomph::TimeHarmonicLinElastLoadedByPMLHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::global_flux_contribution_from_helmholtz(), oomph::TimeHarmonicLinElastLoadedByPMLHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::global_flux_contribution_from_solid(), oomph::FourierDecomposedHelmholtzBCElementBase< ELEMENT >::global_power_contribution(), oomph::HelmholtzBCElementBase< ELEMENT >::global_power_contribution(), oomph::PMLFourierDecomposedHelmholtzPowerMonitorElement< ELEMENT >::global_power_contribution(), oomph::PMLHelmholtzPowerElement< ELEMENT >::global_power_contribution(), oomph::ElementWithExternalElement::initialise_external_element_storage(), oomph::SurfactantTransportInterfaceElement::integrate_c(), oomph::FiniteElement::integrate_fct(), oomph::SolubleSurfactantTransportInterfaceElement::integrated_C(), oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::integrated_C_and_M(), oomph::RefineableDoubleBuoyantQCrouzeixRaviartElement< DIM >::integrated_C_and_M(), oomph::AxisymmetricNavierStokesEquations::kin_energy(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::kin_energy(), oomph::PolarNavierStokesEquations::kin_energy(), oomph::SphericalNavierStokesEquations::kin_energy(), oomph::SolubleSurfactantTransportInterfaceElement::l2_norm_of_height(), oomph::KirchhoffLoveShellEquations::load_rate_of_work(), oomph::Multi_domain_functions::locate_zeta_for_local_coordinates(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::max_and_min_invariant_and_viscosity(), oomph::FSIAxisymFoepplvonKarmanElement< NNODE_1D, FLUID_ELEMENT >::node_update_adjacent_fluid_elements(), oomph::FSIWallElement::node_update_adjacent_fluid_elements(), oomph::UnsteadyHeatBaseFaceElement< ELEMENT >::output(), oomph::FSIAxisymmetricLinearElasticityTractionElement< ELASTICITY_BULK_ELEMENT, NAVIER_STOKES_BULK_ELEMENT >::output(), oomph::LinearisedFSIAxisymmetricNStNoSlipBCElementElement< FLUID_BULK_ELEMENT, SOLID_BULK_ELEMENT >::output(), oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::output(), oomph::FSILinearisedAxisymPoroelasticTractionElement< POROELASTICITY_BULK_ELEMENT, NAVIER_STOKES_BULK_ELEMENT >::output(), oomph::FourierDecomposedTimeHarmonicLinElastLoadedByHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::output(), oomph::FourierDecomposedHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::output(), oomph::TimeHarmonicLinElastLoadedByHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::output(), oomph::HelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::output(), oomph::TimeHarmonicLinElastLoadedByPMLHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::output(), oomph::PMLHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::output(), oomph::ClampedHermiteShellBoundaryConditionElement::output(), oomph::FSISolidTractionElement< ELEMENT, DIM >::output(), oomph::FSIAxisymFoepplvonKarmanElement< NNODE_1D, FLUID_ELEMENT >::output_adjacent_fluid_elements(), oomph::SolarRadiationBase::output_atmospheric_radiation(), oomph::SolarRadiationBase::output_diffuse_radiation_cone(), oomph::SolarRadiationBase::output_diffuse_radiation_cone_max_angle(), oomph::SolarRadiationBase::output_diffuse_radiation_cone_min_angle(), oomph::ElementWithExternalElement::output_external_elements(), oomph::FSIAxisymFoepplvonKarmanElement< NNODE_1D, FLUID_ELEMENT >::output_integration_points(), oomph::SolarRadiationBase::output_limiting_angles(), oomph::SurfaceMeltElement< ELEMENT >::output_melt(), oomph::NavierStokesEquations< DIM >::output_pressure_advection_diffusion_robin_elements(), oomph::SpaceTimeNavierStokesEquations< DIM >::output_pressure_advection_diffusion_robin_elements(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::output_pressure_advection_diffusion_robin_elements(), oomph::StefanBoltzmannUnsteadyHeatFluxElement< ELEMENT >::output_stefan_boltzmann_radiation(), oomph::StefanBoltzmannRadiationBase::output_stefan_boltzmann_radiation_rays(), oomph::StorableShapeElementBase::pre_compute_d2shape_eulerian_at_knots(), oomph::StorableShapeSolidElementBase::pre_compute_d2shape_lagrangian_at_knots(), oomph::StorableShapeElementBase::pre_compute_d2shape_local_at_knots(), oomph::StorableShapeElementBase::pre_compute_dshape_eulerian_at_knots(), oomph::StorableShapeSolidElementBase::pre_compute_dshape_lagrangian_at_knots(), oomph::StorableShapeElementBase::pre_compute_dshape_local_at_knots(), oomph::InterpolateFromIntegralPointsBase::pre_compute_ipt_to_node_mapping(), oomph::StorableShapeElementBase::pre_compute_J_eulerian_at_knots(), oomph::StorableShapeElementBase::pre_compute_shape_at_knots(), oomph::AxisymmetricNavierStokesEquations::pressure_integral(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::pressure_integral(), oomph::PolarNavierStokesEquations::pressure_integral(), oomph::SphericalNavierStokesEquations::pressure_integral(), oomph::RefineableImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::refineable_fill_in_generic_contribution_to_residuals_displ_lagr_multiplier(), oomph::RefineableFSIImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::refineable_fill_in_generic_contribution_to_residuals_fsi_displ_lagr_multiplier(), oomph::RefineableNavierStokesFluxControlElement< ELEMENT >::refineable_fill_in_generic_residual_contribution_fluid_traction(), oomph::DGFaceElement::report_info(), oomph::ProjectableAxisymmetricPoroelasticityElement< AXISYMMETRIC_POROELASTICITY_ELEMENT >::residual_for_projection(), oomph::ProjectableDarcyElement< DARCY_ELEMENT >::residual_for_projection(), oomph::ProjectableElement< ELEMENT >::residual_for_projection(), oomph::FiniteElement::self_test(), oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::set_boundary_shape_geom_object_pt(), oomph::StefanBoltzmannUnsteadyHeatFluxElement< ELEMENT >::set_integration_scheme(), oomph::FourierDecomposedHelmholtzDtNMesh< ELEMENT >::setup_gamma(), oomph::HelmholtzDtNMesh< ELEMENT >::setup_gamma(), oomph::DGFaceElement::setup_neighbour_info(), oomph::StefanBoltzmannHelper::setup_stefan_boltzmann_visibility(), oomph::FiniteElement::size(), oomph::SolarRadiationBase::SolarRadiationBase(), oomph::MyTaylorHoodElement< DIM >::square_of_l2_norm(), oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::square_of_l2_norm_of_error(), oomph::StefanBoltzmannRadiationBase::StefanBoltzmannRadiationBase(), and oomph::SolarRadiationBase::update_limiting_angles().
operator=()
void oomph::Integral::operator= (const Integral &) delete
Broken assignment operator.
weight()
virtual double oomph::Integral::weight (const unsigned & i) const pure virtual
Return weight of i-th integration point.
Implemented in oomph::GaussLegendre< 3, NPTS_1D >, oomph::GaussLegendre< 2, NPTS_1D >, oomph::GaussLegendre< 1, NPTS_1D >, oomph::GaussLobattoLegendre< 3, NPTS_1D >, oomph::GaussLobattoLegendre< 2, NPTS_1D >, oomph::GaussLobattoLegendre< 1, NPTS_1D >, oomph::TGauss< 3, 5 >, oomph::TGauss< 3, 3 >, oomph::TGauss< 3, 2 >, oomph::TGauss< 2, 5 >, oomph::TGauss< 2, 16 >, oomph::TGauss< 2, 9 >, oomph::TGauss< 2, 13 >, oomph::TGauss< 2, 4 >, oomph::TGauss< 2, 3 >, oomph::TGauss< 2, 2 >, oomph::TGauss< 1, 5 >, oomph::TGauss< 1, 4 >, oomph::TGauss< 1, 3 >, oomph::TGauss< 1, 2 >, oomph::Gauss< 3, 4 >, oomph::Gauss< 3, 3 >, oomph::Gauss< 3, 2 >, oomph::Gauss< 2, 4 >, oomph::Gauss< 2, 3 >, oomph::Gauss< 2, 2 >, oomph::Gauss< 1, 4 >, oomph::Gauss< 1, 3 >, oomph::Gauss< 1, 2 >, oomph::PointIntegral, MyIntegral, MyIntegral, and MortaringHelpers::PointIntegralScheme.
Referenced by oomph::NavierStokesImpedanceTractionElement< BULK_NAVIER_STOKES_ELEMENT, WOMERSLEY_ELEMENT, DIM >::add_element_contribution_to_aux_integral(), oomph::DGFaceElement::add_flux_contributions(), oomph::HelmholtzBCElementBase< ELEMENT >::compute_contribution_to_fourier_components(), oomph::AxisymAdvectionDiffusionEquations::compute_error(), oomph::AxisymFoepplvonKarmanEquations::compute_error(), oomph::AxisymmetricLinearElasticityEquations::compute_error(), oomph::BiharmonicEquations< DIM >::compute_error(), oomph::DisplacementBasedFoepplvonKarmanEquations::compute_error(), oomph::FoepplvonKarmanEquations::compute_error(), oomph::FourierDecomposedHelmholtzEquations::compute_error(), oomph::PMLFourierDecomposedHelmholtzEquations::compute_error(), oomph::SphericalAdvectionDiffusionEquations::compute_error(), oomph::SteadyAxisymAdvectionDiffusionEquations::compute_error(), oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations::compute_error(), oomph::YoungLaplaceEquations::compute_error(), oomph::AxisymmetricPoroelasticityEquations::compute_error(), oomph::AxisymmetricNavierStokesEquations::compute_error(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::compute_error(), oomph::PolarNavierStokesEquations::compute_error(), oomph::SphericalNavierStokesEquations::compute_error(), oomph::EulerEquations< DIM >::compute_error(), oomph::ScalarAdvectionEquations< DIM >::compute_error(), oomph::SphericalNavierStokesEquations::compute_error_e(), oomph::SolidFiniteElement::compute_norm(), oomph::FourierDecomposedHelmholtzEquations::compute_norm(), oomph::PMLFourierDecomposedHelmholtzEquations::compute_norm(), oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations::compute_norm(), oomph::AxisymmetricNavierStokesEquations::compute_physical_size(), oomph::AxisymmetricPVDEquations::compute_physical_size(), oomph::AxisymmetricPVDEquationsWithPressure::compute_physical_size(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::compute_physical_size(), oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::contribution_to_enclosed_volume(), oomph::LineVolumeConstraintBoundingElement::contribution_to_enclosed_volume(), oomph::AxisymmetricVolumeConstraintBoundingElement::contribution_to_enclosed_volume(), oomph::StefanBoltzmannRadiationBase::contribution_to_stefan_boltzmann_radiation(), oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::contribution_to_total_porous_flux(), oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::contribution_to_total_porous_flux(), oomph::AxisymmetricVolumeConstraintBoundingElement::contribution_to_volume_flux(), oomph::SphericalNavierStokesEquations::d_kin_energy_dt(), oomph::AxisymmetricNavierStokesEquations::dissipation(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::dissipation(), oomph::PolarNavierStokesEquations::dissipation(), oomph::SphericalNavierStokesEquations::dissipation(), oomph::LinearisedAxisymmetricNavierStokesEquations::dkin_energy_dt(), oomph::NavierStokesSurfacePowerElement< ELEMENT >::drag_force(), oomph::SphericalNavierStokesEquations::extract_velocity(), oomph::AxisymmetricNavierStokesEquations::fill_in_contribution_to_hessian_vector_products(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_contribution_to_hessian_vector_products(), oomph::AxisymFoepplvonKarmanEquations::fill_in_contribution_to_residuals(), oomph::DisplacementBasedFoepplvonKarmanEquations::fill_in_contribution_to_residuals(), oomph::FoepplvonKarmanEquations::fill_in_contribution_to_residuals(), oomph::ClampedHermiteShellBoundaryConditionElement::fill_in_contribution_to_residuals(), oomph::RefineableYoungLaplaceEquations::fill_in_contribution_to_residuals(), oomph::YoungLaplaceEquations::fill_in_contribution_to_residuals(), oomph::AxisymmetricPVDEquations::fill_in_contribution_to_residuals_axisym_pvd(), oomph::KirchhoffLoveBeamEquations::fill_in_contribution_to_residuals_beam(), oomph::KirchhoffLoveShellEquations::fill_in_contribution_to_residuals_shell(), oomph::AxisymmetricLinearElasticityEquations::fill_in_generic_contribution_to_residuals_axisymmetric_linear_elasticity(), oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::fill_in_generic_contribution_to_residuals_displ_lagr_multiplier(), oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations::fill_in_generic_contribution_to_residuals_fourier_decomp_time_harmonic_linear_elasticity(), oomph::FSIImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::fill_in_generic_contribution_to_residuals_fsi_displ_lagr_multiplier(), oomph::ImposeImpenetrabilityElement< ELEMENT >::fill_in_generic_contribution_to_residuals_parall_lagr_multiplier(), oomph::ImposeParallelOutflowElement< ELEMENT >::fill_in_generic_contribution_to_residuals_parall_lagr_multiplier(), oomph::RefineableQDPVDElement< DIM, NNODE_1D >::fill_in_generic_contribution_to_residuals_pvd(), oomph::AxisymmetricNavierStokesEquations::fill_in_generic_dresidual_contribution_axi_nst(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_generic_dresidual_contribution_axi_nst(), oomph::SolidFiniteElement::fill_in_generic_jacobian_for_solid_ic(), oomph::AxisymmetricPoroelasticityEquations::fill_in_generic_residual_contribution(), oomph::PolarNavierStokesEquations::fill_in_generic_residual_contribution(), oomph::RefineablePolarNavierStokesEquations::fill_in_generic_residual_contribution(), oomph::RefineablePolarStreamfunctionEquations::fill_in_generic_residual_contribution(), oomph::PolarStreamfunctionEquations::fill_in_generic_residual_contribution(), oomph::SteadyAxisymAdvectionDiffusionEquations::fill_in_generic_residual_contribution_adv_diff(), oomph::AxisymAdvectionDiffusionEquations::fill_in_generic_residual_contribution_axi_adv_diff(), oomph::RefineableAxisymAdvectionDiffusionEquations::fill_in_generic_residual_contribution_axi_adv_diff(), oomph::AxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), oomph::RefineableAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), oomph::AxisymmetricPVDEquationsWithPressure::fill_in_generic_residual_contribution_axisym_pvd_with_pressure(), oomph::RefineableGeneralisedAxisymAdvectionDiffusionEquations::fill_in_generic_residual_contribution_cons_axisym_adv_diff(), oomph::NavierStokesFluxControlElement< ELEMENT >::fill_in_generic_residual_contribution_fluid_traction(), oomph::FourierDecomposedHelmholtzEquations::fill_in_generic_residual_contribution_fourier_decomposed_helmholtz(), oomph::FourierDecomposedHelmholtzDtNBoundaryElement< ELEMENT >::fill_in_generic_residual_contribution_fourier_decomposed_helmholtz_DtN_bc(), oomph::HelmholtzAbsorbingBCElement< ELEMENT >::fill_in_generic_residual_contribution_helmholtz_abc(), oomph::HelmholtzDtNBoundaryElement< ELEMENT >::fill_in_generic_residual_contribution_helmholtz_DtN_bc(), oomph::FluidInterfaceElement::fill_in_generic_residual_contribution_interface(), oomph::LineFluidInterfaceBoundingElement::fill_in_generic_residual_contribution_interface_boundary(), oomph::LinearisedAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_lin_axi_nst(), oomph::LinearisedAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_linearised_axi_nst(), oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_linearised_axi_nst(), oomph::LinearisedNavierStokesEquations::fill_in_generic_residual_contribution_linearised_nst(), oomph::RefineableLinearisedNavierStokesEquations::fill_in_generic_residual_contribution_linearised_nst(), oomph::PeriodicOrbitEquations::fill_in_generic_residual_contribution_orbit(), oomph::PMLFourierDecomposedHelmholtzEquations::fill_in_generic_residual_contribution_pml_fourier_decomposed_helmholtz(), oomph::RefineableSphericalAdvectionDiffusionEquations::fill_in_generic_residual_contribution_spherical_adv_diff(), oomph::SphericalAdvectionDiffusionEquations::fill_in_generic_residual_contribution_spherical_adv_diff(), oomph::RefineableSphericalNavierStokesEquations::fill_in_generic_residual_contribution_spherical_nst(), oomph::SphericalNavierStokesEquations::fill_in_generic_residual_contribution_spherical_nst(), oomph::LineVolumeConstraintBoundingElement::fill_in_generic_residual_contribution_volume_constraint(), oomph::AxisymmetricVolumeConstraintBoundingElement::fill_in_generic_residual_contribution_volume_constraint(), oomph::SurfaceVolumeConstraintBoundingElement::fill_in_generic_residual_contribution_volume_constraint(), oomph::SolidFiniteElement::fill_in_jacobian_for_newmark_accel(), oomph::RefineableNavierStokesBoussinesqElement< NST_ELEMENT, AD_ELEMENT >::fill_in_off_diagonal_block_analytic(), oomph::RefineableAdvectionDiffusionBoussinesqElement< AD_ELEMENT, NST_ELEMENT >::fill_in_off_diagonal_block_analytic(), oomph::NavierStokesBoussinesqElement< NST_ELEMENT, AD_ELEMENT >::fill_in_off_diagonal_block_analytic(), oomph::AdvectionDiffusionBoussinesqElement< AD_ELEMENT, NST_ELEMENT >::fill_in_off_diagonal_block_analytic(), oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::fill_in_off_diagonal_jacobian_blocks_analytic(), oomph::RefineableBuoyantQSphericalCrouzeixRaviartElement::fill_in_off_diagonal_jacobian_blocks_analytic(), oomph::BuoyantQCrouzeixRaviartElement< DIM >::fill_in_off_diagonal_jacobian_blocks_analytic(), oomph::RefineableBuoyantQCrouzeixRaviartElement< DIM >::fill_in_off_diagonal_jacobian_blocks_analytic(), oomph::FoepplvonKarmanEquations::get_bounded_volume(), oomph::NavierStokesSurfaceDragTorqueElement< ELEMENT >::get_drag_and_torque(), oomph::AxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates(), oomph::RefineableAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates(), oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates(), oomph::Z2ErrorEstimator::get_element_errors(), oomph::KirchhoffLoveShellEquations::get_energy(), oomph::KirchhoffLoveBeamEquations::get_energy(), oomph::NavierStokesSurfacePowerElement< ELEMENT >::get_kinetic_energy_flux(), oomph::AxisymmetricNavierStokesEquations::get_pressure_and_velocity_mass_matrix_diagonal(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::get_pressure_and_velocity_mass_matrix_diagonal(), oomph::SphericalNavierStokesEquations::get_pressure_and_velocity_mass_matrix_diagonal(), oomph::NavierStokesSurfacePowerElement< ELEMENT >::get_rate_of_traction_work(), oomph::NavierStokesSurfacePowerElement< ELEMENT >::get_rate_of_traction_work_components(), oomph::Z2ErrorEstimator::get_recovered_flux_in_patch(), oomph::VorticitySmoother< ELEMENT >::get_recovered_vorticity_in_patch(), oomph::NavierStokesImpedanceTractionElement< BULK_NAVIER_STOKES_ELEMENT, WOMERSLEY_ELEMENT, DIM >::get_volume_flux(), oomph::NavierStokesSurfacePowerElement< ELEMENT >::get_volume_flux(), oomph::PMLHelmholtzPowerElement< ELEMENT >::global_flux_contribution(), oomph::TimeHarmonicLinElastLoadedByPMLHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::global_flux_contribution_from_helmholtz(), oomph::TimeHarmonicLinElastLoadedByPMLHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::global_flux_contribution_from_solid(), oomph::FourierDecomposedHelmholtzBCElementBase< ELEMENT >::global_power_contribution(), oomph::HelmholtzBCElementBase< ELEMENT >::global_power_contribution(), oomph::PMLFourierDecomposedHelmholtzPowerMonitorElement< ELEMENT >::global_power_contribution(), oomph::PMLHelmholtzPowerElement< ELEMENT >::global_power_contribution(), oomph::SurfactantTransportInterfaceElement::integrate_c(), oomph::FiniteElement::integrate_fct(), oomph::SolubleSurfactantTransportInterfaceElement::integrated_C(), oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::integrated_C_and_M(), oomph::RefineableDoubleBuoyantQCrouzeixRaviartElement< DIM >::integrated_C_and_M(), oomph::AxisymmetricNavierStokesEquations::kin_energy(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::kin_energy(), oomph::PolarNavierStokesEquations::kin_energy(), oomph::SphericalNavierStokesEquations::kin_energy(), oomph::SolubleSurfactantTransportInterfaceElement::l2_norm_of_height(), oomph::KirchhoffLoveShellEquations::load_rate_of_work(), oomph::AxisymmetricNavierStokesEquations::pressure_integral(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::pressure_integral(), oomph::PolarNavierStokesEquations::pressure_integral(), oomph::SphericalNavierStokesEquations::pressure_integral(), oomph::RefineableImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::refineable_fill_in_generic_contribution_to_residuals_displ_lagr_multiplier(), oomph::RefineableFSIImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::refineable_fill_in_generic_contribution_to_residuals_fsi_displ_lagr_multiplier(), oomph::RefineableNavierStokesFluxControlElement< ELEMENT >::refineable_fill_in_generic_residual_contribution_fluid_traction(), oomph::ProjectableAxisymmetricPoroelasticityElement< AXISYMMETRIC_POROELASTICITY_ELEMENT >::residual_for_projection(), oomph::ProjectableDarcyElement< DARCY_ELEMENT >::residual_for_projection(), oomph::ProjectableElement< ELEMENT >::residual_for_projection(), oomph::FiniteElement::size(), oomph::MyTaylorHoodElement< DIM >::square_of_l2_norm(), and oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::square_of_l2_norm_of_error().
The documentation for this class was generated from the following file:
integral.h