MercuryDPM: CylindricalCoordinatesUnitTest.cpp File Reference
CylindricalCoordinatesUnitTest.cpp File Reference
#include <Math/Vector.h>
#include <cstdio>
#include <Logger.h>
#include <Math/Matrix.h>
Functions
int main (int argc UNUSED, char *argv[] UNUSED)
Function Documentation
main()
int main (int argc UNUSED, char *argv[] UNUSED)
 {
     Vec3D position(1,.5,0);
     Vec3D velocity;
     Matrix3D stress;
     //just to check that the magnitude of position does not matter
     position *=2;
     //check velocity in radial direction
     velocity = Vec3D(1,.5,0);
     logger(INFO,"radial\tpos % \tvel %  \tvel-cyl %",position,velocity,velocity.getCylindricalTensorField(position));
     //check velocity in angular direction
     velocity = Vec3D(-.5,1,0);
     logger(INFO,"angular\tpos % \tvel %  \tvel-cyl %",position,velocity,velocity.getCylindricalTensorField(position));
     //check velocity in z direction
     velocity = Vec3D(0,0,1);
     logger(INFO,"z      \tpos % \tvel %    \tvel-cyl %",position,velocity,velocity.getCylindricalTensorField(position));
     //check stress in radial direction
     velocity = Vec3D(1,.5,0);
     stress = Matrix3D::dyadic(velocity,velocity);
     logger(INFO,"radial\tpos % \tstress %   \tstress-cyl %",position,stress,stress.getCylindricalTensorField(position));
     //check stress in angular direction
     velocity = Vec3D(-.5,1,0);
     stress = Matrix3D::dyadic(velocity,velocity);
     logger(INFO,"angular\tpos % \tstress %\tstress-cyl %",position,stress,stress.getCylindricalTensorField(position));
     //check stress in z direction
     velocity = Vec3D(0,0,1);
     stress = Matrix3D::dyadic(velocity,velocity);
     logger(INFO,"z      \tpos % \tstress %         \tstress-cyl %",position,stress,stress.getCylindricalTensorField(position));
 }
References Matrix3D::dyadic(), Matrix3D::getCylindricalTensorField(), INFO, logger, and Jeffery_Solution::velocity().