MercuryDPM: tools Namespace Reference
tools Namespace Reference
Functions
def initParamsTable (keys, maxs, mins, num=100, threads=4, tableName='smcTable.txt')
def writeToTable (tableName, table, dim, num, thread, keys)
def getKeysAndData (fileName)
def resampledParamsTable (keys, smcSamples, proposal, num=100, thread=4, maxNumComponents=10, priorWeight=1e3, tableName='smcTableNew.txt', verbose=False)
def getGMMFromPosterior (smcSamples, posterior, priorWeight)
def get_pool (mpi=False, threads=1)
Function Documentation
get_pool()
def tools.get_pool (mpi = False, threads = 1)
 def get_pool(mpi=False,threads=1):
    if mpi: # using MPI
       from mpipool import MPIPool
       pool = MPIPool()
       pool.start()
       if not pool.is_master():
          sys.exit(0)
    elif threads>1: # using multiprocessing
       from multiprocessing import Pool
       pool = Pool(processes=threads,maxtasksperchild=10)
    else:
       raise RuntimeError ("Wrong arguments: either mpi=True or threads>1.")
    return pool
Referenced by smc.smc.initialize().
getGMMFromPosterior()
def tools.getGMMFromPosterior (smcSamples, posterior, priorWeight)
 def getGMMFromPosterior(smcSamples,posterior,priorWeight):
     # resample parameters from a proposal PDF
     ResampleIndices = residual_resample(posterior)
     smcNewSamples = smcSamples[ResampleIndices]
     n_components = int(self._numSamples/5)
     gmm = mixture.BayesianGaussianMixture(n_components=n_components,weight_concentration_prior=priorWeight,covariance_type='full',tol = 1e-5,max_iter=int(1e5),n_init=100)
     gmm.fit(smcNewSamples)
     return gmm
References int(), and resample.residual_resample().
Referenced by smc.smc.trainGMMinTime().
getKeysAndData()
def tools.getKeysAndData (fileName)
 def getKeysAndData(fileName):
     data = np.genfromtxt(fileName)
     fopen = open(fileName,'r')
     keys = (fopen.read().splitlines()[0]).split('\t\t')
     if '#' in keys: keys.remove('#')
     keysAndData = {}
     for key in keys: keysAndData[key] = data[:,keys.index(key)]
     return keysAndData
References oomph::DoubleVectorHelpers.split().
Referenced by smc.smc.getDPMData(), and smc.smc.getObsDataFromFile().
initParamsTable()
def tools.initParamsTable (keys, maxs, mins, num = 100, threads = 4, tableName = 'smcTable.txt')
:param dim: type integer, number of parameters
:param num: type integer, number of sampling points for Monte Carlo Simulation
:param threads: type integer, number of thread for each parallel simulation
:param maxs: type tuples, maximums ranges of parameters
:param mins: type tuples, minimums ranges of parameters
:param keys: type strings, names of parameters
 def initParamsTable(keys,maxs,mins,num=100,threads=4,tableName='smcTable.txt'):
     """
    :param dim: type integer, number of parameters
    :param num: type integer, number of sampling points for Monte Carlo Simulation
    :param threads: type integer, number of thread for each parallel simulation
    :param maxs: type tuples, maximums ranges of parameters
    :param mins: type tuples, minimums ranges of parameters
    :param keys: type strings, names of parameters
     """
     dim = len(keys)
     sequencer = ghalton.Halton(dim)
     table = sequencer.get(num)
     for i in range(dim):
         for j in range(num):
             mean = .5*(maxs[i]+mins[i])
             std  = .5*(maxs[i]-mins[i])
             table[j][i] = mean+(table[j][i]-.5)*2*std
     # write parameters in the format for Yade batch mode
     writeToTable(tableName,table,dim,num,threads,keys)
     return table, tableName
References writeToTable().
Referenced by smc.smc.getInitParams().
resampledParamsTable()
def tools.resampledParamsTable (keys, smcSamples, proposal, num = 100, thread = 4, maxNumComponents = 10, priorWeight = 1e3, tableName = 'smcTableNew.txt', verbose = False)
 def resampledParamsTable(keys,smcSamples,proposal,num=100,thread=4,maxNumComponents=10,priorWeight=1e3,tableName='smcTableNew.txt',verbose=False):
     if (verbose):
         print("Called resampledParamsTable(keys=%s, smcSamples=%s, proposal=%s, num=%s, thread=%s, maxNumComponents=%s, priorWeight=%s, tableName=%s)"
               % (keys,smcSamples,proposal,num,thread,maxNumComponents,priorWeight,tableName))
     dim = len(keys)
     # resample parameters from a proposal PDF
     ResampleIndices = unWeighted_resample(proposal,10*num)
     smcNewSamples = smcSamples[ResampleIndices]
     # normalize parameter samples
     sampleMaxs = np.zeros(smcSamples.shape[1])
     for i in range(sampleMaxs.shape[0]):
         sampleMaxs[i] = max(smcNewSamples[:, i])
         smcNewSamples[:, i] /= sampleMaxs[i]
     # regenerate new SMC samples from Bayesian gaussian mixture model
     # details on http://scikit-learn.org/stable/modules/generated/sklearn.mixture.BayesianGaussianMixture.html
     gmm = mixture.BayesianGaussianMixture(n_components=maxNumComponents,weight_concentration_prior=priorWeight,covariance_type='full',tol = 1e-5,max_iter=int(1e5),n_init=100)
     gmm.fit(smcNewSamples)
     smcNewSamples, _ = gmm.sample(num)
     # print("BayesianGaussianMixture fit: means %s, weights %s, covs %s"
     #     % (gmm.means_*sampleMaxs, gmm.weights_, gmm.covariances_))
     if verbose:
         print("Fitting smcNewSamples=%s with %s" % (smcNewSamples, gmm))
     # scale resampled parameters back to their right units
     for i in range(sampleMaxs.shape[0]): smcNewSamples[:, i] *= sampleMaxs[i]
     # write parameters in the format for Yade batch mode
     writeToTable(tableName,smcNewSamples,dim,num,thread,keys)
     return smcNewSamples, tableName, gmm, maxNumComponents
References int(), max, Eigen::internal.print(), resample.unWeighted_resample(), and writeToTable().
Referenced by smc.smc.resampleParams().
writeToTable()
def tools.writeToTable (tableName, table, dim, num, thread, keys)
 def writeToTable(tableName,table,dim,num,thread,keys):
     #print("Writing %s" % tableName)
     # output parameter table with thread number for each Yade simulation session
     fout = open(tableName,'w')
     fout.write(' '.join(['!OMP_NUM_THREADS','key']+keys+['\n']))
     for j in range(num):
         fout.write(' '.join(['%2i'%thread,'%9i'%j]+['%15.5e'%table[j][i] for i in range(dim)]+['\n']))
     fout.close()
Referenced by initParamsTable(), and resampledParamsTable().