MercuryDPM: melt.cc File Reference
melt.cc File Reference
#include <fenv.h>
#include "generic.h"
#include "unsteady_heat.h"
#include "solid.h"
#include "meshes/triangle_mesh.h"
#include "heat_transfer_and_melt_elements.h"
Classes
class UnsteadyHeatMeltProblem< ELEMENT >
UnsteadyHeat problem.
Namespaces
ProblemParameters
Namespace for exact solution and problem parameters.
ExactSolution
Namespace for exact solution.
Functions
void ExactSolution::get_exact_u_for_unsteady_heat_validation (const double &t, const Vector< double > &x, Vector< double > &u)
Exact solution as a Vector.
void ExactSolution::get_exact_u_for_unsteady_heat_validation (const double &t, const Vector< double > &x, double &u)
Exact solution as a scalar.
void ExactSolution::get_source_for_unsteady_heat_validation (const double &t, const Vector< double > &x, double &source)
Source function to make it an exact solution.
void ExactSolution::prescribed_flux_for_unsteady_heat_validation (const double &t, const Vector< double > &x, const Vector< double > &n, const double &u, double &flux)
double ExactSolution::melting_surface_height (const double &t, const double &x)
Height of melting surface.
int main (int argc, char *argv[])
Driver code for unsteady heat equation.
Function Documentation
main()
int main (int argc , char * argv[])
Driver code for unsteady heat equation.
///////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////
 {
  FiniteElement::Accept_negative_jacobian=true;
  // Store command line arguments
  CommandLineArgs::setup(argc,argv);
  // Define possible command line arguments and parse the ones that
  // were actually specified
  // Suppress adaptation
  CommandLineArgs::specify_command_line_flag("--no_adapt");
  // Suppress melting?
  CommandLineArgs::specify_command_line_flag("--disable_melting");
  // Suppress melt flux?
  CommandLineArgs::specify_command_line_flag("--disable_melt_flux");
  // Non-default initial temperature
  CommandLineArgs::specify_command_line_flag("--theta_init",
                                             &ExactSolution::U0);
  //  Frequency of co-sinusoidal oscillation of incoming heat flux
  // (to assess suppression of re-freezing).
  CommandLineArgs::specify_command_line_flag("--omega_cos",
                                             &ExactSolution::Omega_cos);
  // Validation
  CommandLineArgs::specify_command_line_flag("--validate");
  // Parse command line
  CommandLineArgs::parse_and_assign();
  // Doc what has actually been specified on the command line
  CommandLineArgs::doc_specified_flags();
  // Create generalised Hookean constitutive equations
  ProblemParameters::Constitutive_law_pt =
   new GeneralisedHookean(&ProblemParameters::Nu);
  // Build problem
  UnsteadyHeatMeltProblem<
   ProjectableUnsteadyHeatElement<
   PseudoSolidNodeUpdateElement<TUnsteadyHeatElement<2,3>,TPVDElement<2,3> > > >
  problem;
  // Choose simulation interval and timestep
  double t_max=0.5;
  double dt=0.01;
  // Initialise timestep -- also sets the weights for all timesteppers
  // in the problem.
  problem.initialise_dt(dt);
  // Set impulsive IC
  problem.assign_initial_values_impulsive(dt);
  //Output initial condition
  problem.doc_solution();
  unsigned max_adapt=1;
  bool first=false;
  if (CommandLineArgs::command_line_flag_has_been_set("--no_adapt"))
   {
    max_adapt=0;
   }
  // Find number of steps
  unsigned nstep = unsigned(t_max/dt);
  // Validation?
  if (CommandLineArgs::command_line_flag_has_been_set("--validate"))
   {
    nstep=5;
   }
  // Timestepping loop
  for (unsigned istep=0;istep<nstep;istep++)
   {
    cout << " Timestep " << istep << std::endl;
    // Dummy double adaptivity (timestep is always accepted because
    // tolerance is set to huge value; mainly used to automatically
    // re-solve with smaller timestep increment after non-convergence
    double epsilon_t=DBL_MAX;
    unsigned suppress_resolve_after_spatial_adapt_flag=0;
    double next_dt=
     problem.doubly_adaptive_unsteady_newton_solve(
      dt,
      epsilon_t,
      max_adapt,
      suppress_resolve_after_spatial_adapt_flag,
      first);
    oomph_info << "Suggested next dt: " << next_dt << std::endl;
    dt = next_dt;
    //Output solution
    problem.doc_solution();
   }
 } // end of main
References oomph::CommandLineArgs::command_line_flag_has_been_set(), ProblemParameters::Constitutive_law_pt, oomph::CommandLineArgs::doc_specified_flags(), ProblemParameters::Nu, ExactSolution::Omega_cos, oomph::oomph_info, oomph::CommandLineArgs::parse_and_assign(), problem, Flag_definition::setup(), oomph::CommandLineArgs::specify_command_line_flag(), and ExactSolution::U0.