MercuryDPM: Eigen::SparseLU< MatrixType_, OrderingType_ > Class Template Reference
Eigen::SparseLU< MatrixType_, OrderingType_ > Class Template Reference
Sparse linear algebra » Reference » SparseLU_Module
Sparse supernodal LU factorization for general matrices.
#include <SparseLU.h>
Public Types
enum { ColsAtCompileTime = MatrixType::ColsAtCompileTime , MaxColsAtCompileTime = MatrixType::MaxColsAtCompileTime }
typedef MatrixType_ MatrixType
typedef OrderingType_ OrderingType
typedef MatrixType::Scalar Scalar
typedef MatrixType::RealScalar RealScalar
typedef MatrixType::StorageIndex StorageIndex
typedef SparseMatrix< Scalar, ColMajor, StorageIndex > NCMatrix
typedef internal::MappedSuperNodalMatrix< Scalar, StorageIndex > SCMatrix
typedef Matrix< Scalar, Dynamic, 1 > ScalarVector
typedef Matrix< StorageIndex, Dynamic, 1 > IndexVector
typedef PermutationMatrix< Dynamic, Dynamic, StorageIndex > PermutationType
typedef internal::SparseLUImpl< Scalar, StorageIndex > Base
Public Types inherited from Eigen::internal::SparseLUImpl< MatrixType_::Scalar, MatrixType_::StorageIndex >
typedef Matrix< MatrixType_::Scalar, Dynamic, 1 > ScalarVector
typedef Matrix< MatrixType_::StorageIndex, Dynamic, 1 > IndexVector
typedef Matrix< MatrixType_::Scalar, Dynamic, Dynamic, ColMajor > ScalarMatrix
typedef Map< ScalarMatrix, 0, OuterStride<> > MappedMatrixBlock
typedef ScalarVector::RealScalar RealScalar
typedef Ref< Matrix< MatrixType_::Scalar, Dynamic, 1 > > BlockScalarVector
typedef Ref< Matrix< MatrixType_::StorageIndex, Dynamic, 1 > > BlockIndexVector
typedef LU_GlobalLU_t< IndexVector, ScalarVector > GlobalLU_t
typedef SparseMatrix< MatrixType_::Scalar, ColMajor, MatrixType_::StorageIndex > MatrixType
Public Member Functions
SparseLU ()
Basic constructor of the solver.
SparseLU (const MatrixType &matrix)
Constructor of the solver already based on a specific matrix.
~SparseLU ()
void analyzePattern (const MatrixType &matrix)
Compute the column permutation.
void factorize (const MatrixType &matrix)
Factorize the matrix to get the solver ready.
void simplicialfactorize (const MatrixType &matrix)
void compute (const MatrixType &matrix)
Analyze and factorize the matrix so the solver is ready to solve.
const SparseLUTransposeView< false, SparseLU< MatrixType_, OrderingType_ > > transpose ()
Return a solver for the transposed matrix.
const SparseLUTransposeView< true, SparseLU< MatrixType_, OrderingType_ > > adjoint ()
Return a solver for the adjointed matrix.
Index rows () const
Give the number of rows.
Index cols () const
Give the number of columns.
void isSymmetric (bool sym)
Let you set that the pattern of the input matrix is symmetric.
SparseLUMatrixLReturnType< SCMatrix > matrixL () const
Give the matrixL.
SparseLUMatrixUReturnType< SCMatrix, Map< SparseMatrix< Scalar, ColMajor, StorageIndex > > > matrixU () const
Give the MatrixU.
const PermutationType & rowsPermutation () const
Give the row matrix permutation.
const PermutationType & colsPermutation () const
Give the column matrix permutation.
void setPivotThreshold (const RealScalar &thresh)
ComputationInfo info () const
Reports whether previous computation was successful.
std::string lastErrorMessage () const
Give a human readable error.
template<typename Rhs , typename Dest >
bool _solve_impl (const MatrixBase< Rhs > &B, MatrixBase< Dest > &X_base) const
Scalar absDeterminant ()
Give the absolute value of the determinant.
Scalar logAbsDeterminant () const
Give the natural log of the absolute determinant.
Scalar signDeterminant ()
Give the sign of the determinant.
Scalar determinant ()
Give the determinant.
Index nnzL () const
Give the number of non zero in matrix L.
Index nnzU () const
Give the number of non zero in matrix U.
Public Member Functions inherited from Eigen::SparseSolverBase< SparseLU< MatrixType_, OrderingType_ > >
SparseSolverBase ()
SparseSolverBase (SparseSolverBase &&other)
~SparseSolverBase ()
SparseLU< MatrixType_, OrderingType_ > & derived ()
const SparseLU< MatrixType_, OrderingType_ > & derived () const
const Solve< SparseLU< MatrixType_, OrderingType_ >, Rhs > solve (const MatrixBase< Rhs > &b) const
const Solve< SparseLU< MatrixType_, OrderingType_ >, Rhs > solve (const SparseMatrixBase< Rhs > &b) const
void _solve_impl (const SparseMatrixBase< Rhs > &b, SparseMatrixBase< Dest > &dest) const
Protected Types
typedef SparseSolverBase< SparseLU< MatrixType_, OrderingType_ > > APIBase
Protected Member Functions
void initperfvalues ()
Protected Member Functions inherited from Eigen::internal::SparseLUImpl< MatrixType_::Scalar, MatrixType_::StorageIndex >
Index expand (VectorType &vec, Index &length, Index nbElts, Index keep_prev, Index &num_expansions)
Index memInit (Index m, Index n, Index annz, Index lwork, Index fillratio, Index panel_size, GlobalLU_t &glu)
Allocate various working space for the numerical factorization phase.
Index memXpand (VectorType &vec, Index &maxlen, Index nbElts, MemType memtype, Index &num_expansions)
Expand the existing storage.
void heap_relax_snode (const Index n, IndexVector &et, const Index relax_columns, IndexVector &descendants, IndexVector &relax_end)
Identify the initial relaxed supernodes.
void relax_snode (const Index n, IndexVector &et, const Index relax_columns, IndexVector &descendants, IndexVector &relax_end)
Identify the initial relaxed supernodes.
Index snode_dfs (const Index jcol, const Index kcol, const MatrixType &mat, IndexVector &xprune, IndexVector &marker, GlobalLU_t &glu)
Index snode_bmod (const Index jcol, const Index fsupc, ScalarVector &dense, GlobalLU_t &glu)
Index pivotL (const Index jcol, const RealScalar &diagpivotthresh, IndexVector &perm_r, IndexVector &iperm_c, Index &pivrow, GlobalLU_t &glu)
Performs the numerical pivoting on the current column of L, and the CDIV operation.
void dfs_kernel (const MatrixType_::StorageIndex jj, IndexVector &perm_r, Index &nseg, IndexVector &panel_lsub, IndexVector &segrep, Ref< IndexVector > repfnz_col, IndexVector &xprune, Ref< IndexVector > marker, IndexVector &parent, IndexVector &xplore, GlobalLU_t &glu, Index &nextl_col, Index krow, Traits &traits)
void panel_dfs (const Index m, const Index w, const Index jcol, MatrixType &A, IndexVector &perm_r, Index &nseg, ScalarVector &dense, IndexVector &panel_lsub, IndexVector &segrep, IndexVector &repfnz, IndexVector &xprune, IndexVector &marker, IndexVector &parent, IndexVector &xplore, GlobalLU_t &glu)
Performs a symbolic factorization on a panel of columns [jcol, jcol+w)
void panel_bmod (const Index m, const Index w, const Index jcol, const Index nseg, ScalarVector &dense, ScalarVector &tempv, IndexVector &segrep, IndexVector &repfnz, GlobalLU_t &glu)
Performs numeric block updates (sup-panel) in topological order.
Index column_dfs (const Index m, const Index jcol, IndexVector &perm_r, Index maxsuper, Index &nseg, BlockIndexVector lsub_col, IndexVector &segrep, BlockIndexVector repfnz, IndexVector &xprune, IndexVector &marker, IndexVector &parent, IndexVector &xplore, GlobalLU_t &glu)
Performs a symbolic factorization on column jcol and decide the supernode boundary.
Index column_bmod (const Index jcol, const Index nseg, BlockScalarVector dense, ScalarVector &tempv, BlockIndexVector segrep, BlockIndexVector repfnz, Index fpanelc, GlobalLU_t &glu)
Performs numeric block updates (sup-col) in topological order.
Index copy_to_ucol (const Index jcol, const Index nseg, IndexVector &segrep, BlockIndexVector repfnz, IndexVector &perm_r, BlockScalarVector dense, GlobalLU_t &glu)
Performs numeric block updates (sup-col) in topological order.
void pruneL (const Index jcol, const IndexVector &perm_r, const Index pivrow, const Index nseg, const IndexVector &segrep, BlockIndexVector repfnz, IndexVector &xprune, GlobalLU_t &glu)
Prunes the L-structure.
void countnz (const Index n, Index &nnzL, Index &nnzU, GlobalLU_t &glu)
Count Nonzero elements in the factors.
void fixupL (const Index n, const IndexVector &perm_r, GlobalLU_t &glu)
Fix up the data storage lsub for L-subscripts.
Protected Attributes
ComputationInfo m_info
bool m_factorizationIsOk
bool m_analysisIsOk
std::string m_lastError
NCMatrix m_mat
SCMatrix m_Lstore
Map< SparseMatrix< Scalar, ColMajor, StorageIndex > > m_Ustore
PermutationType m_perm_c
PermutationType m_perm_r
IndexVector m_etree
Base::GlobalLU_t m_glu
bool m_symmetricmode
internal::perfvalues m_perfv
RealScalar m_diagpivotthresh
Index m_nnzL
Index m_nnzU
Index m_detPermR
Index m_detPermC
Protected Attributes inherited from Eigen::SparseSolverBase< SparseLU< MatrixType_, OrderingType_ > >
bool m_isInitialized
Private Member Functions
SparseLU (const SparseLU &)
Detailed Description
template<typename MatrixType_, typename OrderingType_>
class Eigen::SparseLU< MatrixType_, OrderingType_ >
Sparse supernodal LU factorization for general matrices.
This class implements the supernodal LU factorization for general matrices. It uses the main techniques from the sequential SuperLU package (http://crd-legacy.lbl.gov/~xiaoye/SuperLU/). It handles transparently real and complex arithmetic with single and double precision, depending on the scalar type of your input matrix. The code has been optimized to provide BLAS-3 operations during supernode-panel updates. It benefits directly from the built-in high-performant Eigen BLAS routines. Moreover, when the size of a supernode is very small, the BLAS calls are avoided to enable a better optimization from the compiler. For best performance, you should compile it with NDEBUG flag to avoid the numerous bounds checking on vectors.
An important parameter of this class is the ordering method. It is used to reorder the columns (and eventually the rows) of the matrix to reduce the number of new elements that are created during numerical factorization. The cheapest method available is COLAMD. See the OrderingMethods module for the list of built-in and external ordering methods.
Simple example with key steps
VectorXd x(n), b(n);
SparseMatrix<double> A;
SparseLU<SparseMatrix<double>, COLAMDOrdering<int> > solver;
// Fill A and b.
// Compute the ordering permutation vector from the structural pattern of A.
solver.analyzePattern(A);
// Compute the numerical factorization.
solver.factorize(A);
// Use the factors to solve the linear system.
x = solver.solve(b);
We can directly call compute() instead of analyzePattern() and factorize()
VectorXd x(n), b(n);
SparseMatrix<double> A;
SparseLU<SparseMatrix<double>, COLAMDOrdering<int> > solver;
// Fill A and b.
solver.compute(A);
// Use the factors to solve the linear system.
x = solver.solve(b);
Or give the matrix to the constructor SparseLU(const MatrixType& matrix)
VectorXd x(n), b(n);
SparseMatrix<double> A;
// Fill A and b.
SparseLU<SparseMatrix<double>, COLAMDOrdering<int> > solver(A);
// Use the factors to solve the linear system.
x = solver.solve(b);
Warning
The input matrix A should be in a compressed and column-major form. Otherwise an expensive copy will be made. You can call the inexpensive makeCompressed() to get a compressed matrix.
Note
Unlike the initial SuperLU implementation, there is no step to equilibrate the matrix. For badly scaled matrices, this step can be useful to reduce the pivoting during factorization. If this is the case for your matrices, you can try the basic scaling method at "unsupported/Eigen/src/IterativeSolvers/Scaling.h"
Template Parameters
MatrixType_ The type of the sparse matrix. It must be a column-major SparseMatrix<>
OrderingType_ The ordering method to use, either AMD, COLAMD or METIS. Default is COLMAD
\implsparsesolverconcept
See also
Sparse solver concept
OrderingMethods_Module
Member Typedef Documentation
APIBase
template<typename MatrixType_ , typename OrderingType_ > typedef SparseSolverBase<SparseLU<MatrixType_, OrderingType_> > Eigen::SparseLU< MatrixType_, OrderingType_ >::APIBase protected
Base
template<typename MatrixType_ , typename OrderingType_ > typedef internal::SparseLUImpl<Scalar, StorageIndex> Eigen::SparseLU< MatrixType_, OrderingType_ >::Base
IndexVector
template<typename MatrixType_ , typename OrderingType_ > typedef Matrix<StorageIndex, Dynamic, 1> Eigen::SparseLU< MatrixType_, OrderingType_ >::IndexVector
MatrixType
template<typename MatrixType_ , typename OrderingType_ > typedef MatrixType_ Eigen::SparseLU< MatrixType_, OrderingType_ >::MatrixType
NCMatrix
template<typename MatrixType_ , typename OrderingType_ > typedef SparseMatrix<Scalar, ColMajor, StorageIndex> Eigen::SparseLU< MatrixType_, OrderingType_ >::NCMatrix
OrderingType
template<typename MatrixType_ , typename OrderingType_ > typedef OrderingType_ Eigen::SparseLU< MatrixType_, OrderingType_ >::OrderingType
PermutationType
template<typename MatrixType_ , typename OrderingType_ > typedef PermutationMatrix<Dynamic, Dynamic, StorageIndex> Eigen::SparseLU< MatrixType_, OrderingType_ >::PermutationType
RealScalar
template<typename MatrixType_ , typename OrderingType_ > typedef MatrixType::RealScalar Eigen::SparseLU< MatrixType_, OrderingType_ >::RealScalar
Scalar
template<typename MatrixType_ , typename OrderingType_ > typedef MatrixType::Scalar Eigen::SparseLU< MatrixType_, OrderingType_ >::Scalar
ScalarVector
template<typename MatrixType_ , typename OrderingType_ > typedef Matrix<Scalar, Dynamic, 1> Eigen::SparseLU< MatrixType_, OrderingType_ >::ScalarVector
SCMatrix
template<typename MatrixType_ , typename OrderingType_ > typedef internal::MappedSuperNodalMatrix<Scalar, StorageIndex> Eigen::SparseLU< MatrixType_, OrderingType_ >::SCMatrix
StorageIndex
template<typename MatrixType_ , typename OrderingType_ > typedef MatrixType::StorageIndex Eigen::SparseLU< MatrixType_, OrderingType_ >::StorageIndex
Member Enumeration Documentation
anonymous enum
template<typename MatrixType_ , typename OrderingType_ > anonymous enum
Enumerator
ColsAtCompileTime
MaxColsAtCompileTime
 { ColsAtCompileTime = MatrixType::ColsAtCompileTime, MaxColsAtCompileTime = MatrixType::MaxColsAtCompileTime };
Constructor & Destructor Documentation
SparseLU() [1/3]
template<typename MatrixType_ , typename OrderingType_ > Eigen::SparseLU< MatrixType_, OrderingType_ >::SparseLU () inline
Basic constructor of the solver.
Construct a SparseLU. As no matrix is given as argument, compute() should be called afterward with a matrix.
       : m_lastError(""), m_Ustore(0, 0, 0, 0, 0, 0), m_symmetricmode(false), m_diagpivotthresh(1.0), m_detPermR(1) {
     initperfvalues();
   }
References Eigen::SparseLU< MatrixType_, OrderingType_ >::initperfvalues().
SparseLU() [2/3]
template<typename MatrixType_ , typename OrderingType_ > Eigen::SparseLU< MatrixType_, OrderingType_ >::SparseLU (const MatrixType & matrix) inline explicit
Constructor of the solver already based on a specific matrix.
Construct a SparseLU. compute() is already called with the given matrix.
       : m_lastError(""), m_Ustore(0, 0, 0, 0, 0, 0), m_symmetricmode(false), m_diagpivotthresh(1.0), m_detPermR(1) {
     initperfvalues();
     compute(matrix);
   }
References Eigen::SparseLU< MatrixType_, OrderingType_ >::compute(), Eigen::SparseLU< MatrixType_, OrderingType_ >::initperfvalues(), and matrix().
~SparseLU()
template<typename MatrixType_ , typename OrderingType_ > Eigen::SparseLU< MatrixType_, OrderingType_ >::~SparseLU () inline
               {
     // Free all explicit dynamic pointers
   }
SparseLU() [3/3]
template<typename MatrixType_ , typename OrderingType_ > Eigen::SparseLU< MatrixType_, OrderingType_ >::SparseLU (const SparseLU< MatrixType_, OrderingType_ > &) private
Member Function Documentation
_solve_impl()
template<typename MatrixType_ , typename OrderingType_ > template<typename Rhs , typename Dest > bool Eigen::SparseLU< MatrixType_, OrderingType_ >::_solve_impl (const MatrixBase< Rhs > & B, MatrixBase< Dest > & X_base) const inline
{
     Dest& X(X_base.derived());
     eigen_assert(m_factorizationIsOk && "The matrix should be factorized first");
     EIGEN_STATIC_ASSERT((Dest::Flags & RowMajorBit) == 0, THIS_METHOD_IS_ONLY_FOR_COLUMN_MAJOR_MATRICES);
     // Permute the right hand side to form X = Pr*B
     // on return, X is overwritten by the computed solution
     X.resize(B.rows(), B.cols());
     // this ugly const_cast_derived() helps to detect aliasing when applying the permutations
     for (Index j = 0; j < B.cols(); ++j) X.col(j) = rowsPermutation() * B.const_cast_derived().col(j);
     // Forward substitution with L
     this->matrixL().solveInPlace(X);
     this->matrixU().solveInPlace(X);
     // Permute back the solution
     for (Index j = 0; j < B.cols(); ++j) X.col(j) = colsPermutation().inverse() * X.col(j);
     return true;
   }
References Eigen::SparseLU< MatrixType_, OrderingType_ >::colsPermutation(), eigen_assert, EIGEN_STATIC_ASSERT, Eigen::PermutationBase< Derived >::inverse(), j, Eigen::SparseLU< MatrixType_, OrderingType_ >::m_factorizationIsOk, Eigen::SparseLU< MatrixType_, OrderingType_ >::matrixL(), Eigen::SparseLU< MatrixType_, OrderingType_ >::matrixU(), Eigen::RowMajorBit, Eigen::SparseLU< MatrixType_, OrderingType_ >::rowsPermutation(), and X.
absDeterminant()
template<typename MatrixType_ , typename OrderingType_ > Scalar Eigen::SparseLU< MatrixType_, OrderingType_ >::absDeterminant () inline
Give the absolute value of the determinant.
Returns
the absolute value of the determinant of the matrix of which *this is the QR decomposition.
Warning
a determinant can be very big or small, so for matrices of large enough dimension, there is a risk of overflow/underflow. One way to work around that is to use logAbsDeterminant() instead.
See also
logAbsDeterminant(), signDeterminant()
{
     using std::abs;
     eigen_assert(m_factorizationIsOk && "The matrix should be factorized first.");
     // Initialize with the determinant of the row matrix
     Scalar det = Scalar(1.);
     // Note that the diagonal blocks of U are stored in supernodes,
     // which are available in the  L part :)
     for (Index j = 0; j < this->cols(); ++j) {
       for (typename SCMatrix::InnerIterator it(m_Lstore, j); it; ++it) {
         if (it.index() == j) {
           det *= abs(it.value());
           break;
         }
       }
     }
     return det;
   }
References abs(), Eigen::SparseLU< MatrixType_, OrderingType_ >::cols(), eigen_assert, j, Eigen::SparseLU< MatrixType_, OrderingType_ >::m_factorizationIsOk, and Eigen::SparseLU< MatrixType_, OrderingType_ >::m_Lstore.
adjoint()
template<typename MatrixType_ , typename OrderingType_ > const SparseLUTransposeView<true, SparseLU<MatrixType_, OrderingType_> > Eigen::SparseLU< MatrixType_, OrderingType_ >::adjoint () inline
Return a solver for the adjointed matrix.
Returns
an expression of the adjoint of the factored matrix
A typical usage is to solve for the adjoint problem A' x = b:
solver.compute(A);
x = solver.adjoint().solve(b);
For real scalar types, this function is equivalent to transpose().
See also
transpose(), solve()
{
     SparseLUTransposeView<true, SparseLU<MatrixType_, OrderingType_>> adjointView;
     adjointView.setSparseLU(this);
     adjointView.setIsInitialized(this->m_isInitialized);
     return adjointView;
   }
References Eigen::SparseSolverBase< SparseLU< MatrixType_, OrderingType_ > >::m_isInitialized, Eigen::SparseLUTransposeView< Conjugate, SparseLUType >::setIsInitialized(), and Eigen::SparseLUTransposeView< Conjugate, SparseLUType >::setSparseLU().
analyzePattern()
template<typename MatrixType , typename OrderingType > void Eigen::SparseLU< MatrixType, OrderingType >::analyzePattern (const MatrixType & mat)
Compute the column permutation.
Compute the column permutation to minimize the fill-in
Apply this permutation to the input matrix -
Compute the column elimination tree on the permuted matrix
Postorder the elimination tree and the column permutation
It is possible to call compute() instead of analyzePattern() + factorize().
If the matrix is row-major this function will do an heavy copy.
See also
factorize(), compute()
{
   // TODO  It is possible as in SuperLU to compute row and columns scaling vectors to equilibrate the matrix mat.
   // Firstly, copy the whole input matrix.
   m_mat = mat;
   // Compute fill-in ordering
   OrderingType ord;
   ord(m_mat, m_perm_c);
   // Apply the permutation to the column of the input  matrix
   if (m_perm_c.size()) {
     m_mat.uncompress();  // NOTE: The effect of this command is only to create the InnerNonzeros pointers. FIXME : This
                          // vector is filled but not subsequently used.
     // Then, permute only the column pointers
     ei_declare_aligned_stack_constructed_variable(
         StorageIndex, outerIndexPtr, mat.cols() + 1,
         mat.isCompressed() ? const_cast<StorageIndex*>(mat.outerIndexPtr()) : 0);
     // If the input matrix 'mat' is uncompressed, then the outer-indices do not match the ones of m_mat, and a copy is
     // thus needed.
     if (!mat.isCompressed())
       IndexVector::Map(outerIndexPtr, mat.cols() + 1) = IndexVector::Map(m_mat.outerIndexPtr(), mat.cols() + 1);
     // Apply the permutation and compute the nnz per column.
     for (Index i = 0; i < mat.cols(); i++) {
       m_mat.outerIndexPtr()[m_perm_c.indices()(i)] = outerIndexPtr[i];
       m_mat.innerNonZeroPtr()[m_perm_c.indices()(i)] = outerIndexPtr[i + 1] - outerIndexPtr[i];
     }
   }
   // Compute the column elimination tree of the permuted matrix
   IndexVector firstRowElt;
   internal::coletree(m_mat, m_etree, firstRowElt);
   // In symmetric mode, do not do postorder here
   if (!m_symmetricmode) {
     IndexVector post, iwork;
     // Post order etree
     internal::treePostorder(StorageIndex(m_mat.cols()), m_etree, post);
     // Renumber etree in postorder
     Index m = m_mat.cols();
     iwork.resize(m + 1);
     for (Index i = 0; i < m; ++i) iwork(post(i)) = post(m_etree(i));
     m_etree = iwork;
     // Postmultiply A*Pc by post, i.e reorder the matrix according to the postorder of the etree
     PermutationType post_perm(m);
     for (Index i = 0; i < m; i++) post_perm.indices()(i) = post(i);
     // Combine the two permutations : postorder the permutation for future use
     if (m_perm_c.size()) {
       m_perm_c = post_perm * m_perm_c;
     }
   }  // end postordering
   m_analysisIsOk = true;
 }
References Eigen::internal::coletree(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::cols(), ei_declare_aligned_stack_constructed_variable, i, Eigen::PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, StorageIndex_ >::indices(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::isCompressed(), m, Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::outerIndexPtr(), Eigen::PlainObjectBase< Derived >::resize(), and Eigen::internal::treePostorder().
Referenced by Eigen::SparseLU< MatrixType_, OrderingType_ >::compute().
cols()
template<typename MatrixType_ , typename OrderingType_ > Index Eigen::SparseLU< MatrixType_, OrderingType_ >::cols () const inline
Give the number of columns.
 { return m_mat.cols(); }
References Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::cols(), and Eigen::SparseLU< MatrixType_, OrderingType_ >::m_mat.
Referenced by gdb.printers._MatrixEntryIterator::__next__(), Eigen::SparseLU< MatrixType_, OrderingType_ >::absDeterminant(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), Eigen::SparseLU< MatrixType_, OrderingType_ >::determinant(), Eigen::SparseLU< MatrixType_, OrderingType_ >::logAbsDeterminant(), Eigen::SparseLU< MatrixType_, OrderingType_ >::signDeterminant(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
colsPermutation()
template<typename MatrixType_ , typename OrderingType_ > const PermutationType& Eigen::SparseLU< MatrixType_, OrderingType_ >::colsPermutation () const inline
Give the column matrix permutation.
Returns
a reference to the column matrix permutation \(P_c^T \) such that \(P_r A P_c^T = L U\)
See also
rowsPermutation()
 { return m_perm_c; }
References Eigen::SparseLU< MatrixType_, OrderingType_ >::m_perm_c.
Referenced by Eigen::SparseLU< MatrixType_, OrderingType_ >::_solve_impl(), and Eigen::SparseInverse< Scalar >::computeInverse().
compute()
template<typename MatrixType_ , typename OrderingType_ > void Eigen::SparseLU< MatrixType_, OrderingType_ >::compute (const MatrixType & matrix) inline
Analyze and factorize the matrix so the solver is ready to solve.
Compute the symbolic and numeric factorization of the input sparse matrix. The input matrix should be in column-major storage, otherwise analyzePattern() will do a heavy copy.
Call analyzePattern() followed by factorize()
See also
analyzePattern(), factorize()
{
     // Analyze
     analyzePattern(matrix);
     // Factorize
     factorize(matrix);
   }
References Eigen::SparseLU< MatrixType_, OrderingType_ >::analyzePattern(), Eigen::SparseLU< MatrixType_, OrderingType_ >::factorize(), and matrix().
Referenced by check_sparse_inverse(), Eigen::SparseInverse< Scalar >::compute(), and Eigen::SparseLU< MatrixType_, OrderingType_ >::SparseLU().
determinant()
template<typename MatrixType_ , typename OrderingType_ > Scalar Eigen::SparseLU< MatrixType_, OrderingType_ >::determinant () inline
Give the determinant.
Returns
The determinant of the matrix.
See also
absDeterminant(), logAbsDeterminant()
{
     eigen_assert(m_factorizationIsOk && "The matrix should be factorized first.");
     // Initialize with the determinant of the row matrix
     Scalar det = Scalar(1.);
     // Note that the diagonal blocks of U are stored in supernodes,
     // which are available in the  L part :)
     for (Index j = 0; j < this->cols(); ++j) {
       for (typename SCMatrix::InnerIterator it(m_Lstore, j); it; ++it) {
         if (it.index() == j) {
           det *= it.value();
           break;
         }
       }
     }
     return (m_detPermR * m_detPermC) > 0 ? det : -det;
   }
References Eigen::SparseLU< MatrixType_, OrderingType_ >::cols(), eigen_assert, j, Eigen::SparseLU< MatrixType_, OrderingType_ >::m_detPermC, Eigen::SparseLU< MatrixType_, OrderingType_ >::m_detPermR, Eigen::SparseLU< MatrixType_, OrderingType_ >::m_factorizationIsOk, and Eigen::SparseLU< MatrixType_, OrderingType_ >::m_Lstore.
factorize()
template<typename MatrixType , typename OrderingType > void Eigen::SparseLU< MatrixType, OrderingType >::factorize (const MatrixType & matrix)
Factorize the matrix to get the solver ready.
Numerical factorization
Interleaved with the symbolic factorization
To get error of this function you should check info(), you can get more info of errors with lastErrorMessage().
In the past (before 2012 (git history is not older)), this function was returning an integer. This exit was 0 if successful factorization.
0 if info = i, and i is been completed, but the factor U is exactly singular,
and division by zero will occur if it is used to solve a system of equation.
A->ncol: number of bytes allocated when memory allocation failure occurred, plus A->ncol.
If lwork = -1, it is the estimated amount of space needed, plus A->ncol.
It seems that A was the name of the matrix in the past.
See also
analyzePattern(), compute(), SparseLU(), info(), lastErrorMessage()
{
   using internal::emptyIdxLU;
   eigen_assert(m_analysisIsOk && "analyzePattern() should be called first");
   eigen_assert((matrix.rows() == matrix.cols()) && "Only for squared matrices");
   m_isInitialized = true;
   // Apply the column permutation computed in analyzepattern()
   //   m_mat = matrix * m_perm_c.inverse();
   m_mat = matrix;
   if (m_perm_c.size()) {
     m_mat.uncompress();  // NOTE: The effect of this command is only to create the InnerNonzeros pointers.
     // Then, permute only the column pointers
     const StorageIndex* outerIndexPtr;
     if (matrix.isCompressed())
       outerIndexPtr = matrix.outerIndexPtr();
     else {
       StorageIndex* outerIndexPtr_t = new StorageIndex[matrix.cols() + 1];
       for (Index i = 0; i <= matrix.cols(); i++) outerIndexPtr_t[i] = m_mat.outerIndexPtr()[i];
       outerIndexPtr = outerIndexPtr_t;
     }
     for (Index i = 0; i < matrix.cols(); i++) {
       m_mat.outerIndexPtr()[m_perm_c.indices()(i)] = outerIndexPtr[i];
       m_mat.innerNonZeroPtr()[m_perm_c.indices()(i)] = outerIndexPtr[i + 1] - outerIndexPtr[i];
     }
     if (!matrix.isCompressed()) delete[] outerIndexPtr;
   } else {  // FIXME This should not be needed if the empty permutation is handled transparently
     m_perm_c.resize(matrix.cols());
     for (StorageIndex i = 0; i < matrix.cols(); ++i) m_perm_c.indices()(i) = i;
   }
   Index m = m_mat.rows();
   Index n = m_mat.cols();
   Index nnz = m_mat.nonZeros();
   Index maxpanel = m_perfv.panel_size * m;
   // Allocate working storage common to the factor routines
   Index lwork = 0;
   // Return the size of actually allocated memory when allocation failed,
   // and 0 on success.
   Index info = Base::memInit(m, n, nnz, lwork, m_perfv.fillfactor, m_perfv.panel_size, m_glu);
   if (info) {
     m_lastError = "UNABLE TO ALLOCATE WORKING MEMORY\n\n";
     m_factorizationIsOk = false;
     return;
   }
   // Set up pointers for integer working arrays
   IndexVector segrep(m);
   segrep.setZero();
   IndexVector parent(m);
   parent.setZero();
   IndexVector xplore(m);
   xplore.setZero();
   IndexVector repfnz(maxpanel);
   IndexVector panel_lsub(maxpanel);
   IndexVector xprune(n);
   xprune.setZero();
   IndexVector marker(m * internal::LUNoMarker);
   marker.setZero();
   repfnz.setConstant(-1);
   panel_lsub.setConstant(-1);
   // Set up pointers for scalar working arrays
   ScalarVector dense;
   dense.setZero(maxpanel);
   ScalarVector tempv;
   tempv.setZero(internal::LUnumTempV(m, m_perfv.panel_size, m_perfv.maxsuper, /*m_perfv.rowblk*/ m));
   // Compute the inverse of perm_c
   PermutationType iperm_c(m_perm_c.inverse());
   // Identify initial relaxed snodes
   IndexVector relax_end(n);
   if (m_symmetricmode == true)
     Base::heap_relax_snode(n, m_etree, m_perfv.relax, marker, relax_end);
   else
     Base::relax_snode(n, m_etree, m_perfv.relax, marker, relax_end);
   m_perm_r.resize(m);
   m_perm_r.indices().setConstant(-1);
   marker.setConstant(-1);
   m_detPermR = 1;  // Record the determinant of the row permutation
   m_glu.supno(0) = emptyIdxLU;
   m_glu.xsup.setConstant(0);
   m_glu.xsup(0) = m_glu.xlsub(0) = m_glu.xusub(0) = m_glu.xlusup(0) = Index(0);
   // Work on one 'panel' at a time. A panel is one of the following :
   //  (a) a relaxed supernode at the bottom of the etree, or
   //  (b) panel_size contiguous columns, <panel_size> defined by the user
   Index jcol;
   Index pivrow;  // Pivotal row number in the original row matrix
   Index nseg1;   // Number of segments in U-column above panel row jcol
   Index nseg;    // Number of segments in each U-column
   Index irep;
   Index i, k, jj;
   for (jcol = 0; jcol < n;) {
     // Adjust panel size so that a panel won't overlap with the next relaxed snode.
     Index panel_size = m_perfv.panel_size;  // upper bound on panel width
     for (k = jcol + 1; k < (std::min)(jcol + panel_size, n); k++) {
       if (relax_end(k) != emptyIdxLU) {
         panel_size = k - jcol;
         break;
       }
     }
     if (k == n) panel_size = n - jcol;
     // Symbolic outer factorization on a panel of columns
     Base::panel_dfs(m, panel_size, jcol, m_mat, m_perm_r.indices(), nseg1, dense, panel_lsub, segrep, repfnz, xprune,
                     marker, parent, xplore, m_glu);
     // Numeric sup-panel updates in topological order
     Base::panel_bmod(m, panel_size, jcol, nseg1, dense, tempv, segrep, repfnz, m_glu);
     // Sparse LU within the panel, and below the panel diagonal
     for (jj = jcol; jj < jcol + panel_size; jj++) {
       k = (jj - jcol) * m;  // Column index for w-wide arrays
       nseg = nseg1;  // begin after all the panel segments
       // Depth-first-search for the current column
       VectorBlock<IndexVector> panel_lsubk(panel_lsub, k, m);
       VectorBlock<IndexVector> repfnz_k(repfnz, k, m);
       // Return 0 on success and > 0 number of bytes allocated when run out of space.
       info = Base::column_dfs(m, jj, m_perm_r.indices(), m_perfv.maxsuper, nseg, panel_lsubk, segrep, repfnz_k, xprune,
                               marker, parent, xplore, m_glu);
       if (info) {
         m_lastError = "UNABLE TO EXPAND MEMORY IN COLUMN_DFS() ";
         m_info = NumericalIssue;
         m_factorizationIsOk = false;
         return;
       }
       // Numeric updates to this column
       VectorBlock<ScalarVector> dense_k(dense, k, m);
       VectorBlock<IndexVector> segrep_k(segrep, nseg1, m - nseg1);
       // Return 0 on success and > 0 number of bytes allocated when run out of space.
       info = Base::column_bmod(jj, (nseg - nseg1), dense_k, tempv, segrep_k, repfnz_k, jcol, m_glu);
       if (info) {
         m_lastError = "UNABLE TO EXPAND MEMORY IN COLUMN_BMOD() ";
         m_info = NumericalIssue;
         m_factorizationIsOk = false;
         return;
       }
       // Copy the U-segments to ucol(*)
       // Return 0 on success and > 0 number of bytes allocated when run out of space.
       info = Base::copy_to_ucol(jj, nseg, segrep, repfnz_k, m_perm_r.indices(), dense_k, m_glu);
       if (info) {
         m_lastError = "UNABLE TO EXPAND MEMORY IN COPY_TO_UCOL() ";
         m_info = NumericalIssue;
         m_factorizationIsOk = false;
         return;
       }
       // Form the L-segment
       // Return O if success, i > 0 if U(i, i) is exactly zero.
       info = Base::pivotL(jj, m_diagpivotthresh, m_perm_r.indices(), iperm_c.indices(), pivrow, m_glu);
       if (info) {
         m_lastError = "THE MATRIX IS STRUCTURALLY SINGULAR";
 #ifndef EIGEN_NO_IO
         std::ostringstream returnInfo;
         returnInfo << " ... ZERO COLUMN AT ";
         returnInfo << info;
         m_lastError += returnInfo.str();
 #endif
         m_info = NumericalIssue;
         m_factorizationIsOk = false;
         return;
       }
       // Update the determinant of the row permutation matrix
       // FIXME: the following test is not correct, we should probably take iperm_c into account and pivrow is not
       // directly the row pivot.
       if (pivrow != jj) m_detPermR = -m_detPermR;
       // Prune columns (0:jj-1) using column jj
       Base::pruneL(jj, m_perm_r.indices(), pivrow, nseg, segrep, repfnz_k, xprune, m_glu);
       // Reset repfnz for this column
       for (i = 0; i < nseg; i++) {
         irep = segrep(i);
         repfnz_k(irep) = emptyIdxLU;
       }
     }                    // end SparseLU within the panel
     jcol += panel_size;  // Move to the next panel
   }                      // end for -- end elimination
   m_detPermR = m_perm_r.determinant();
   m_detPermC = m_perm_c.determinant();
   // Count the number of nonzeros in factors
   Base::countnz(n, m_nnzL, m_nnzU, m_glu);
   // Apply permutation  to the L subscripts
   Base::fixupL(n, m_perm_r.indices(), m_glu);
   // Create supernode matrix L
   m_Lstore.setInfos(m, n, m_glu.lusup, m_glu.xlusup, m_glu.lsub, m_glu.xlsub, m_glu.supno, m_glu.xsup);
   // Create the column major upper sparse matrix  U;
   new (&m_Ustore) Map<SparseMatrix<Scalar, ColMajor, StorageIndex>>(m, n, m_nnzU, m_glu.xusub.data(), m_glu.usub.data(),
                                                                     m_glu.ucol.data());
   m_info = Success;
   m_factorizationIsOk = true;
 }
References countnz(), eigen_assert, Eigen::internal::emptyIdxLU, fixupL(), heap_relax_snode(), i, Eigen::PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, StorageIndex_ >::indices(), info, k, Eigen::internal::LUNoMarker, Eigen::internal::LUnumTempV(), m, matrix(), min, n, Eigen::NumericalIssue, relax_snode(), Eigen::PlainObjectBase< Derived >::setConstant(), Eigen::PlainObjectBase< Derived >::setZero(), and Eigen::Success.
Referenced by Eigen::SparseLU< MatrixType_, OrderingType_ >::compute().
info()
template<typename MatrixType_ , typename OrderingType_ > ComputationInfo Eigen::SparseLU< MatrixType_, OrderingType_ >::info () const inline
Reports whether previous computation was successful.
Returns
Success if computation was successful, NumericalIssue if the LU factorization reports a problem, zero diagonal for instance InvalidInput if the input matrix is invalid
You can get a readable error message with lastErrorMessage().
See also
lastErrorMessage()
{
     eigen_assert(m_isInitialized && "Decomposition is not initialized.");
     return m_info;
   }
References eigen_assert, Eigen::SparseLU< MatrixType_, OrderingType_ >::m_info, and Eigen::SparseSolverBase< SparseLU< MatrixType_, OrderingType_ > >::m_isInitialized.
Referenced by Eigen::SparseInverse< Scalar >::computeInverse().
initperfvalues()
template<typename MatrixType_ , typename OrderingType_ > void Eigen::SparseLU< MatrixType_, OrderingType_ >::initperfvalues () inline protected
{
     m_perfv.panel_size = 16;
     m_perfv.relax = 1;
     m_perfv.maxsuper = 128;
     m_perfv.rowblk = 16;
     m_perfv.colblk = 8;
     m_perfv.fillfactor = 20;
   }
References Eigen::internal::perfvalues::colblk, Eigen::internal::perfvalues::fillfactor, Eigen::SparseLU< MatrixType_, OrderingType_ >::m_perfv, Eigen::internal::perfvalues::maxsuper, Eigen::internal::perfvalues::panel_size, Eigen::internal::perfvalues::relax, and Eigen::internal::perfvalues::rowblk.
Referenced by Eigen::SparseLU< MatrixType_, OrderingType_ >::SparseLU().
isSymmetric()
template<typename MatrixType_ , typename OrderingType_ > void Eigen::SparseLU< MatrixType_, OrderingType_ >::isSymmetric (bool sym) inline
Let you set that the pattern of the input matrix is symmetric.
 { m_symmetricmode = sym; }
References Eigen::SparseLU< MatrixType_, OrderingType_ >::m_symmetricmode.
lastErrorMessage()
template<typename MatrixType_ , typename OrderingType_ > std::string Eigen::SparseLU< MatrixType_, OrderingType_ >::lastErrorMessage () const inline
Give a human readable error.
Returns
A string describing the type of error
 { return m_lastError; }
References Eigen::SparseLU< MatrixType_, OrderingType_ >::m_lastError.
logAbsDeterminant()
template<typename MatrixType_ , typename OrderingType_ > Scalar Eigen::SparseLU< MatrixType_, OrderingType_ >::logAbsDeterminant () const inline
Give the natural log of the absolute determinant.
Returns
the natural log of the absolute value of the determinant of the matrix of which **this is the QR decomposition
Note
This method is useful to work around the risk of overflow/underflow that's inherent to the determinant computation.
See also
absDeterminant(), signDeterminant()
{
     using std::abs;
     using std::log;
     eigen_assert(m_factorizationIsOk && "The matrix should be factorized first.");
     Scalar det = Scalar(0.);
     for (Index j = 0; j < this->cols(); ++j) {
       for (typename SCMatrix::InnerIterator it(m_Lstore, j); it; ++it) {
         if (it.row() < j) continue;
         if (it.row() == j) {
           det += log(abs(it.value()));
           break;
         }
       }
     }
     return det;
   }
References abs(), Eigen::SparseLU< MatrixType_, OrderingType_ >::cols(), eigen_assert, j, Eigen::bfloat16_impl::log(), Eigen::SparseLU< MatrixType_, OrderingType_ >::m_factorizationIsOk, and Eigen::SparseLU< MatrixType_, OrderingType_ >::m_Lstore.
matrixL()
template<typename MatrixType_ , typename OrderingType_ > SparseLUMatrixLReturnType<SCMatrix> Eigen::SparseLU< MatrixType_, OrderingType_ >::matrixL () const inline
Give the matrixL.
Returns
an expression of the matrix L, internally stored as supernodes The only operation available with this expression is the triangular solve
y = b; matrixL().solveInPlace(y);
 { return SparseLUMatrixLReturnType<SCMatrix>(m_Lstore); }
References Eigen::SparseLU< MatrixType_, OrderingType_ >::m_Lstore.
Referenced by Eigen::SparseLU< MatrixType_, OrderingType_ >::_solve_impl(), and Eigen::SparseInverse< Scalar >::computeInverse().
matrixU()
template<typename MatrixType_ , typename OrderingType_ > SparseLUMatrixUReturnType<SCMatrix, Map<SparseMatrix<Scalar, ColMajor, StorageIndex> > > Eigen::SparseLU< MatrixType_, OrderingType_ >::matrixU () const inline
Give the MatrixU.
Returns
an expression of the matrix U, The only operation available with this expression is the triangular solve
y = b; matrixU().solveInPlace(y);
{
     return SparseLUMatrixUReturnType<SCMatrix, Map<SparseMatrix<Scalar, ColMajor, StorageIndex>>>(m_Lstore, m_Ustore);
   }
References Eigen::SparseLU< MatrixType_, OrderingType_ >::m_Lstore, and Eigen::SparseLU< MatrixType_, OrderingType_ >::m_Ustore.
Referenced by Eigen::SparseLU< MatrixType_, OrderingType_ >::_solve_impl(), and Eigen::SparseInverse< Scalar >::computeInverse().
nnzL()
template<typename MatrixType_ , typename OrderingType_ > Index Eigen::SparseLU< MatrixType_, OrderingType_ >::nnzL () const inline
Give the number of non zero in matrix L.
 { return m_nnzL; }
References Eigen::SparseLU< MatrixType_, OrderingType_ >::m_nnzL.
nnzU()
template<typename MatrixType_ , typename OrderingType_ > Index Eigen::SparseLU< MatrixType_, OrderingType_ >::nnzU () const inline
Give the number of non zero in matrix U.
 { return m_nnzU; }
References Eigen::SparseLU< MatrixType_, OrderingType_ >::m_nnzU.
rows()
template<typename MatrixType_ , typename OrderingType_ > Index Eigen::SparseLU< MatrixType_, OrderingType_ >::rows () const inline
Give the number of rows.
 { return m_mat.rows(); }
References Eigen::SparseLU< MatrixType_, OrderingType_ >::m_mat, and Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::rows().
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
rowsPermutation()
template<typename MatrixType_ , typename OrderingType_ > const PermutationType& Eigen::SparseLU< MatrixType_, OrderingType_ >::rowsPermutation () const inline
Give the row matrix permutation.
Returns
a reference to the row matrix permutation \(P_r \) such that \(P_r A P_c^T = L U\)
See also
colsPermutation()
 { return m_perm_r; }
References Eigen::SparseLU< MatrixType_, OrderingType_ >::m_perm_r.
Referenced by Eigen::SparseLU< MatrixType_, OrderingType_ >::_solve_impl(), and Eigen::SparseInverse< Scalar >::computeInverse().
setPivotThreshold()
template<typename MatrixType_ , typename OrderingType_ > void Eigen::SparseLU< MatrixType_, OrderingType_ >::setPivotThreshold (const RealScalar & thresh) inline
Set the threshold used for a diagonal entry to be an acceptable pivot.
 { m_diagpivotthresh = thresh; }
References Eigen::SparseLU< MatrixType_, OrderingType_ >::m_diagpivotthresh.
signDeterminant()
template<typename MatrixType_ , typename OrderingType_ > Scalar Eigen::SparseLU< MatrixType_, OrderingType_ >::signDeterminant () inline
Give the sign of the determinant.
Returns
A number representing the sign of the determinant
See also
absDeterminant(), logAbsDeterminant()
{
     eigen_assert(m_factorizationIsOk && "The matrix should be factorized first.");
     // Initialize with the determinant of the row matrix
     Index det = 1;
     // Note that the diagonal blocks of U are stored in supernodes,
     // which are available in the  L part :)
     for (Index j = 0; j < this->cols(); ++j) {
       for (typename SCMatrix::InnerIterator it(m_Lstore, j); it; ++it) {
         if (it.index() == j) {
           if (it.value() < 0)
             det = -det;
           else if (it.value() == 0)
             return 0;
           break;
         }
       }
     }
     return det * m_detPermR * m_detPermC;
   }
References Eigen::SparseLU< MatrixType_, OrderingType_ >::cols(), eigen_assert, j, Eigen::SparseLU< MatrixType_, OrderingType_ >::m_detPermC, Eigen::SparseLU< MatrixType_, OrderingType_ >::m_detPermR, Eigen::SparseLU< MatrixType_, OrderingType_ >::m_factorizationIsOk, and Eigen::SparseLU< MatrixType_, OrderingType_ >::m_Lstore.
simplicialfactorize()
template<typename MatrixType_ , typename OrderingType_ > void Eigen::SparseLU< MatrixType_, OrderingType_ >::simplicialfactorize (const MatrixType & matrix)
transpose()
template<typename MatrixType_ , typename OrderingType_ > const SparseLUTransposeView<false, SparseLU<MatrixType_, OrderingType_> > Eigen::SparseLU< MatrixType_, OrderingType_ >::transpose () inline
Return a solver for the transposed matrix.
Returns
an expression of the transposed of the factored matrix.
A typical usage is to solve for the transposed problem A^T x = b:
solver.compute(A);
x = solver.transpose().solve(b);
See also
adjoint(), solve()
{
     SparseLUTransposeView<false, SparseLU<MatrixType_, OrderingType_>> transposeView;
     transposeView.setSparseLU(this);
     transposeView.setIsInitialized(this->m_isInitialized);
     return transposeView;
   }
References Eigen::SparseSolverBase< SparseLU< MatrixType_, OrderingType_ > >::m_isInitialized, Eigen::SparseLUTransposeView< Conjugate, SparseLUType >::setIsInitialized(), and Eigen::SparseLUTransposeView< Conjugate, SparseLUType >::setSparseLU().
Member Data Documentation
m_analysisIsOk
template<typename MatrixType_ , typename OrderingType_ > bool Eigen::SparseLU< MatrixType_, OrderingType_ >::m_analysisIsOk protected
m_detPermC
template<typename MatrixType_ , typename OrderingType_ > Index Eigen::SparseLU< MatrixType_, OrderingType_ >::m_detPermC protected
Referenced by Eigen::SparseLU< MatrixType_, OrderingType_ >::determinant(), and Eigen::SparseLU< MatrixType_, OrderingType_ >::signDeterminant().
m_detPermR
template<typename MatrixType_ , typename OrderingType_ > Index Eigen::SparseLU< MatrixType_, OrderingType_ >::m_detPermR protected
Referenced by Eigen::SparseLU< MatrixType_, OrderingType_ >::determinant(), and Eigen::SparseLU< MatrixType_, OrderingType_ >::signDeterminant().
m_diagpivotthresh
template<typename MatrixType_ , typename OrderingType_ > RealScalar Eigen::SparseLU< MatrixType_, OrderingType_ >::m_diagpivotthresh protected
Referenced by Eigen::SparseLU< MatrixType_, OrderingType_ >::setPivotThreshold().
m_etree
template<typename MatrixType_ , typename OrderingType_ > IndexVector Eigen::SparseLU< MatrixType_, OrderingType_ >::m_etree protected
m_factorizationIsOk
template<typename MatrixType_ , typename OrderingType_ > bool Eigen::SparseLU< MatrixType_, OrderingType_ >::m_factorizationIsOk protected
Referenced by Eigen::SparseLU< MatrixType_, OrderingType_ >::_solve_impl(), Eigen::SparseLU< MatrixType_, OrderingType_ >::absDeterminant(), Eigen::SparseLU< MatrixType_, OrderingType_ >::determinant(), Eigen::SparseLU< MatrixType_, OrderingType_ >::logAbsDeterminant(), and Eigen::SparseLU< MatrixType_, OrderingType_ >::signDeterminant().
m_glu
template<typename MatrixType_ , typename OrderingType_ > Base::GlobalLU_t Eigen::SparseLU< MatrixType_, OrderingType_ >::m_glu protected
m_info
template<typename MatrixType_ , typename OrderingType_ > ComputationInfo Eigen::SparseLU< MatrixType_, OrderingType_ >::m_info mutable protected
Referenced by Eigen::SparseLU< MatrixType_, OrderingType_ >::info().
m_lastError
template<typename MatrixType_ , typename OrderingType_ > std::string Eigen::SparseLU< MatrixType_, OrderingType_ >::m_lastError protected
Referenced by Eigen::SparseLU< MatrixType_, OrderingType_ >::lastErrorMessage().
m_Lstore
template<typename MatrixType_ , typename OrderingType_ > SCMatrix Eigen::SparseLU< MatrixType_, OrderingType_ >::m_Lstore protected
Referenced by Eigen::SparseLU< MatrixType_, OrderingType_ >::absDeterminant(), Eigen::SparseLU< MatrixType_, OrderingType_ >::determinant(), Eigen::SparseLU< MatrixType_, OrderingType_ >::logAbsDeterminant(), Eigen::SparseLU< MatrixType_, OrderingType_ >::matrixL(), Eigen::SparseLU< MatrixType_, OrderingType_ >::matrixU(), and Eigen::SparseLU< MatrixType_, OrderingType_ >::signDeterminant().
m_mat
template<typename MatrixType_ , typename OrderingType_ > NCMatrix Eigen::SparseLU< MatrixType_, OrderingType_ >::m_mat protected
Referenced by Eigen::SparseLU< MatrixType_, OrderingType_ >::cols(), and Eigen::SparseLU< MatrixType_, OrderingType_ >::rows().
m_nnzL
template<typename MatrixType_ , typename OrderingType_ > Index Eigen::SparseLU< MatrixType_, OrderingType_ >::m_nnzL protected
Referenced by Eigen::SparseLU< MatrixType_, OrderingType_ >::nnzL().
m_nnzU
template<typename MatrixType_ , typename OrderingType_ > Index Eigen::SparseLU< MatrixType_, OrderingType_ >::m_nnzU protected
Referenced by Eigen::SparseLU< MatrixType_, OrderingType_ >::nnzU().
m_perfv
template<typename MatrixType_ , typename OrderingType_ > internal::perfvalues Eigen::SparseLU< MatrixType_, OrderingType_ >::m_perfv protected
Referenced by Eigen::SparseLU< MatrixType_, OrderingType_ >::initperfvalues().
m_perm_c
template<typename MatrixType_ , typename OrderingType_ > PermutationType Eigen::SparseLU< MatrixType_, OrderingType_ >::m_perm_c protected
Referenced by Eigen::SparseLU< MatrixType_, OrderingType_ >::colsPermutation().
m_perm_r
template<typename MatrixType_ , typename OrderingType_ > PermutationType Eigen::SparseLU< MatrixType_, OrderingType_ >::m_perm_r protected
Referenced by Eigen::SparseLU< MatrixType_, OrderingType_ >::rowsPermutation().
m_symmetricmode
template<typename MatrixType_ , typename OrderingType_ > bool Eigen::SparseLU< MatrixType_, OrderingType_ >::m_symmetricmode protected
Referenced by Eigen::SparseLU< MatrixType_, OrderingType_ >::isSymmetric().
m_Ustore
template<typename MatrixType_ , typename OrderingType_ > Map<SparseMatrix<Scalar, ColMajor, StorageIndex> > Eigen::SparseLU< MatrixType_, OrderingType_ >::m_Ustore protected
Referenced by Eigen::SparseLU< MatrixType_, OrderingType_ >::matrixU().
The documentation for this class was generated from the following file:
SparseLU.h