MercuryDPM: FixedClusterInsertionBoundary Class Reference
FixedClusterInsertionBoundary Class Reference
#include <FixedClusterInsertionBoundary.h>
Public Member Functions
FixedClusterInsertionBoundary ()
Constructor: inherits from BaseClusterInsertionBoundary constructor.
FixedClusterInsertionBoundary (const FixedClusterInsertionBoundary &other)
Copy constructor with deep copy.
~FixedClusterInsertionBoundary () override
Destructor: default destructor.
FixedClusterInsertionBoundary * copy () const override
Creates a copy on the heap and returns a pointer.
void set (std::vector< BaseParticle * > particleToCopy, std::vector< Vec3D > positions, std::vector< Mdouble > radii, Vec3D velMin, Vec3D velMax, Mdouble rMicroParticle)
Sets the properties of the ClusterInsertionBoundary.
void set (BaseParticle *particleToCopy, std::vector< Vec3D > positions, std::vector< Mdouble > radii, Vec3D velMin, Vec3D velMax, Mdouble rMicroParticle)
Sets the properties of the ClusterInsertionBoundary.
void setPositionsAndRadii (std::vector< Vec3D > clusterPositions, std::vector< Mdouble > clusterRadii)
this sets positions and radii of the desired clusters.
void checkBoundaryBeforeTimeStep (DPMBase *md) final
inserts cluster: differently from RandomClusterInsertionBoundary, here no check for interaction is computed.
void placeParticle (BaseParticle *p, RNG &random) final
Places particles according to vector clusterPositions_ and sets a random velocity, if required.
BaseParticle * generateParticle (RNG &random) final
Sets cluster radii according to vector clusterRadii_.
Public Member Functions inherited from BaseClusterInsertionBoundary
BaseClusterInsertionBoundary ()
Constructor; sets everything to 0.
BaseClusterInsertionBoundary (const BaseClusterInsertionBoundary &other)
Copy constructor with deep copy.
~BaseClusterInsertionBoundary () override
Destructor: default destructor.
void setRandomised (bool randomised)
this turns off the randomise(): created for UnitTests.
bool getRandomised ()
this returns a bool which indicates if the process is randomised (true) or not (false).
unsigned int getNumberOfClusterInserted ()
this returns the number of cluster inserted.
void setRadiusMicroParticle (Mdouble rMP)
this sets the radius of the micro particle composing the cluster.
void setGeometry (Vec3D posMin, Vec3D posMax)
Sets the geometry (position and velocity distribution) of the ClusterInsertionBoundary.
void setVelocityRange (Vec3D velMin, Vec3D velMax)
Sets the velocity range of the ClusterInsertionBoundary.
void setAdditionalClusterProperties (Mdouble collisionTimeOverTimeStep, Mdouble velocityDampingModulus, Mdouble energyRatioTolerance)
sets additional cluster properties as:
void setOutputClusterProperties (bool doCdatOutput, bool doOverlOutput, bool doAmatOutput, bool doIntStrucOutput, bool doVtkOutput, bool doRestartOutput, bool doFStatOutput, bool doEneOutput)
sets cluster whether or not cluster output files will be created, for example:
void read (std::istream &is) override
reads boundary properties from istream
void write (std::ostream &os) const override
writes boundary properties to ostream
Public Member Functions inherited from InsertionBoundary
InsertionBoundary ()
InsertionBoundary (const InsertionBoundary &other)
Copy constructor (with deep copy)
~InsertionBoundary () override
Destructor: delete the particle that has to be copied at every insertion.
virtual void shiftBoundary (Vec3D shift)
virtual function that shifts the boundary.
virtual void rotateBoundary (Vec3D angle)
virtual function that rotates the boundary.
void checkBoundaryBeforeTimeStep (DPMBase *md) override
Fills the boundary with particles.
void insertParticles (DPMBase *md)
Fill a certain domain with particles.
unsigned int getNumberOfParticlesInserted () const
Gets the number of particles inserted by the boundary.
Mdouble getMassOfParticlesInserted () const
Gets the mass of particles inserted by the boundary.
Mdouble getVolumeOfParticlesInserted () const
Gets the volume of particles inserted by the boundary.
void reset ()
resets particle property counter variables.
void activate ()
Turns on the InsertionBoundary.
void deactivate ()
Turns off the InsertionBoundary.
bool isActivated ()
Returns whether the InsertionBoundary is activated.
unsigned int getMaxFailed () const
Gets the number of times that the boundary may fail to insert a particle.
void setParticleToCopy (std::vector< BaseParticle * > particleToCopy)
Sets multiple different particles that will be inserted through the insertion boundary.
void setParticleToCopy (BaseParticle *particleToCopy)
Sets the particle that will be inserted through the insertion boundary.
std::vector< BaseParticle * > getParticleToCopy ()
Gets the particles that will be inserted through the insertion boundary.
void read (std::istream &is) override
Reads the boundary's id_ and maxFailed_.
void write (std::ostream &os) const override
Writes the boundary's id_ and maxFailed_.
Mdouble getVolumeFlowRate () const
Gets the volume flow rate of the insertion routine.
void setVolumeFlowRate (Mdouble volumeFlowRate)
Sets the volume flow rate of the insertion routine.
Mdouble getInitialVolume () const
Gets the initialVolume() .
void setInitialVolume (Mdouble initialVolume)
Gets the Volume which should be inserted by the insertion routine.
void setPSD (const PSD psd)
Sets the range of particle radii that may be generated from a user defined PSD.
void setPSD (std::vector< PSD > psd, std::vector< Mdouble > probability)
Sets the ranges of particle radii that may be generated from user defined PSDs.
std::vector< PSD > getPSD ()
Gets the particle size distributions set by the user.
void setVariableVolumeFlowRate (const std::vector< Mdouble > &variableCumulativeVolumeFlowRate, Mdouble samplingInterval)
Sets a variable volume flow rate.
bool insertParticle (Mdouble time)
Checks the inserted total volume and returns if a particle is still allowed to be inserted.
bool getCheckParticleForInteraction () const
Gets the variable that checks if a particle has an interaction.
void setCheckParticleForInteraction (bool checkParticleForInteraction)
Sets the variable that checks if a particle has an interaction.
void setManualInsertion (bool manualInsertion)
Set the flag for a manual PSD insertion routine.
Public Member Functions inherited from BaseBoundary
BaseBoundary ()
default constructor.
BaseBoundary (const BaseBoundary &b)
copy constructor
~BaseBoundary () override
destructor
virtual void createPeriodicParticle (BaseParticle *p UNUSED, ParticleHandler &pH UNUSED)
Creates a periodic particle in case of periodic boundaries in serial build.
virtual void createPeriodicParticles (ParticleHandler &pH UNUSED)
Creates periodic copies of given particle in case of periodic boundaries.
virtual void checkBoundaryAfterParticlesMove (ParticleHandler &pH)
Virtual function that does things to particles, each time step after particles have moved.
virtual void actionsBeforeTimeLoop ()
Virtual function that does something after DPMBase::setupInitialConditions but before the first time step.
virtual void modifyGhostAfterCreation (BaseParticle *particle, int i)
virtual void writeVTK (std::fstream &file)
void setHandler (BoundaryHandler *handler)
Sets the boundary's BoundaryHandler.
BoundaryHandler * getHandler () const
Returns the boundary's BoundaryHandler.
Public Member Functions inherited from BaseObject
BaseObject ()=default
Default constructor.
BaseObject (const BaseObject &p)=default
Copy constructor, copies all the objects BaseObject contains.
virtual ~BaseObject ()=default
virtual destructor
virtual void moveInHandler (unsigned int index)
Except that it is virtual, it does the same thing as setIndex() does.
void setIndex (unsigned int index)
Allows one to assign an index to an object in the handler/container.
void setId (unsigned long id)
Assigns a unique identifier to each object in the handler (container) which remains constant even after the object is deleted from the container/handler.
unsigned int getIndex () const
Returns the index of the object in the handler.
unsigned int getId () const
Returns the unique identifier of any particular object.
void setGroupId (unsigned groupId)
unsigned getGroupId () const
Private Member Functions
std::string getName () const override
Returns the name of the object.
Additional Inherited Members
Public Attributes inherited from InsertionBoundary
std::vector< BaseParticle * > particleToCopy_
read Distribution class from file. ‍/ friend std::istream& operator>>(std::istream& is, InsertionBoundary::Distribution& type);
unsigned int maxFailed_
Number of times that the wall may fail to insert a particle.
unsigned int numberOfParticlesInserted_
Number of particles that are already inserted.
Mdouble massInserted_
Total mass of particles inserted.
Mdouble volumeInserted_
Total volume of particles inserted.
bool isActivated_
The InsertionBoundary is activated by default. If the InsertionBoundary is deactivated, then it introduces no particles (useful for trying to maintain a certain insertion rate).
Mdouble volumeFlowRate_
Mdouble initialVolume_
std::vector< Mdouble > variableCumulativeVolumeFlowRate_
Mdouble samplingInterval_
bool checkParticleForInteraction_
Checks if a particle has an interaction with a wall or other particles.
std::vector< PSD > particleSizeDistributionVector_
Defines a particle size distribution as an object of the PSD class; if particleSizeDistributionVector_ is empty, distribution_ is used instead.
Vec3D velMin_
Minimum and maximum velocity of the particles to be inserted.
Vec3D velMax_
bool isManuallyInserting_
A flag to enable a top-down class-by-class manual insertion of a PSD; default is FALSE.
std::vector< Mdouble > probability_
vector of probabilities in range [0,1] which determine the mixing ratio of partice size distributions.
int chosenSpecies_
stores the chosen species for each timestep.
BaseParticle * p0 = nullptr
pointer to the next particle that should be inserted (needs to be stored across time steps).
Protected Attributes inherited from BaseClusterInsertionBoundary
unsigned int nClusterInserted_
Mdouble radiusParticle_
int nParticles_
LinearPlasticViscoelasticFrictionSpecies * clusterSpecies_
bool isCdatOutputOn_
bool isOverlOutputOn_
bool isAmatOutputOn_
bool isIntStrucOutputOn_
bool isVtkOutputOn_
bool isRestartOutputOn_
bool isFStatOutputOn_
bool isEneOutputOn_
Mdouble sizeDispersityParticle_
Mdouble velocityDampingModulus_
int nInternalStructurePoints_
Mdouble energyRatioTolerance_
Mdouble collisionTimeOverTimeStep_
Vec3D posMin_
Vec3D posMax_
Vec3D velMin_
Vec3D velMax_
bool setRadiusParticleAndNotNumberOfParticles_
std::vector< Vec3D > clusterPositions_
std::vector< Mdouble > clusterRadii_
bool randomised_
Detailed Description
RandomClusterInsertionBoundary This class works exactly like CubeInsertionBoundary class but inserts clusters instead of particles, and the insertion process is not random, but determined by radii and positions specified by the user. MPI: It does not work with MPI. One of the reasons is the need to adapt function DPMBase::importParticlesAs(). In particular particles and interaction should be imported as MPIParticle and MPIInteraction. In addition to this, the same should be done inside BaseCluster::actionsAfterSolve() when particles are centred around the desired position.
Constructor & Destructor Documentation
FixedClusterInsertionBoundary() [1/2]
FixedClusterInsertionBoundary::FixedClusterInsertionBoundary ()
Constructor: inherits from BaseClusterInsertionBoundary constructor.
Default constructor: inherits from BaseClusterInsertionBoundary constructor.
                                                              : BaseClusterInsertionBoundary()
 {
     logger(DEBUG, "RandomClusterInsertionBoundary::RandomClusterInsertionBoundary() finished");
 }
References DEBUG, and logger.
Referenced by copy().
FixedClusterInsertionBoundary() [2/2]
FixedClusterInsertionBoundary::FixedClusterInsertionBoundary (const FixedClusterInsertionBoundary & other)
Copy constructor with deep copy.
Copy constructor
         : BaseClusterInsertionBoundary(other) {
     logger(DEBUG, "RandomClusterInsertionBoundary::RandomClusterInsertionBoundary() finished");
 }
References DEBUG, and logger.
~FixedClusterInsertionBoundary()
FixedClusterInsertionBoundary::~FixedClusterInsertionBoundary () override default
Destructor: default destructor.
Default Destructor.
Member Function Documentation
checkBoundaryBeforeTimeStep()
void FixedClusterInsertionBoundary::checkBoundaryBeforeTimeStep (DPMBase * md) final virtual
inserts cluster: differently from RandomClusterInsertionBoundary, here no check for interaction is computed.
Here the insertion process takes place. Differently from RandomClusterInsertionBoundary, this is basically just a for loop.
Reimplemented from BaseClusterInsertionBoundary.
 {
     logger(VERBOSE, "In FixedClusterInsertionBoundary::checkBoundaryBeforeTimeStep\n");
     if (!isActivated_)
         return;
     /* Each time step, the InsertionBoundary attempts to fill up a region with
      * clusters.
      *
      * It first calls generateParticle() to get a randomised particle, subject
      * to a specified distribution over sizes and species. (The basic class
      * supports size dispersity only but PolydisperseInsertionBoundary will
      * support species dispersity.)
      * Then it repeatedly calls placeParticle(), which gives the cluster a
      * random location (and possibly velocity) in a specified,
      * geometry-dependent bound. Each time, it checks whether the new cluster
      * would have an interaction with another cluster or a wall.
      *
      * If it manages to do that within maxFailed_ tries, then:
      *   * the new cluster is created and inserted,
      *   * the failure counter is reset, and
      * the processes is repeated with a new generateParticle().
      *
      * Otherwise, the processes terminates for this time step.
      * */
     for (std::vector<Mdouble>::const_iterator i = clusterRadii_.begin(); i != clusterRadii_.end(); ++i) {
         auto p0 = generateParticle(md->random);
         placeParticle(p0, md->random);
         BaseCluster cluster;
         if(getRandomised())
             cluster.random.randomise();
         cluster.setCollisionTimeOverTimeStep(collisionTimeOverTimeStep_);
         cluster.setVelocityDampingModulus(velocityDampingModulus_);
         cluster.setNumberOfInternalStructurePoints(nInternalStructurePoints_);
         cluster.setEnergyRatioTolerance(energyRatioTolerance_);
         cluster.setSizeDispersityParticle(sizeDispersityParticle_);
         cluster.doCdatOutput(isCdatOutputOn_);
         cluster.doOverlOutput(isOverlOutputOn_);
         cluster.doAmatOutput(isAmatOutputOn_);
         cluster.doIntStrucOutput(isIntStrucOutputOn_);
         cluster.doVtkOutput(isVtkOutputOn_);
         cluster.doRestartOutput(isRestartOutputOn_);
         cluster.doFStatOutput(isFStatOutputOn_);
         cluster.doEneOutput(isEneOutputOn_);
         cluster.setClusterId(md->particleHandler.getNextGroupId());
         //Here, differently from RandomClusterInsertionBoundary the only possibility is to set radiusCluster and
         // radiusParticle.
         if (setRadiusParticleAndNotNumberOfParticles_)
             cluster.setRadiusParticle(radiusParticle_);
         cluster.setRadiusCluster(p0->getRadius());
         cluster.setPosition(p0->getPosition());
         cluster.setVelocity(p0->getVelocity());
         cluster.setParticleSpecies(
                 dynamic_cast<LinearPlasticViscoelasticFrictionSpecies*>(
                         md->speciesHandler.getObject(p0->getIndSpecies())));
         cluster.solve();
         md->importParticlesAs( cluster.particleHandler, cluster.interactionHandler, p0->getSpecies() );
         // Number of cluster inserted
         ++nClusterInserted_;
         // Total number of particles inserted
         numberOfParticlesInserted_ += cluster.particleHandler.getSize();
         // This is the total mass composed by every single particle (not cluster!) inserted
         massInserted_ += cluster.particleHandler.getMass();
         // This is the total volume composed by every single particle (not cluster!) inserted
         volumeInserted_ += cluster.particleHandler.getVolume();
         logger(VERBOSE, "Successfully inserted cluster %/%.", nClusterInserted_, clusterRadii_.size());
         delete p0;
     }
 }
References BaseClusterInsertionBoundary::clusterRadii_, BaseClusterInsertionBoundary::collisionTimeOverTimeStep_, BaseCluster::doAmatOutput(), BaseCluster::doCdatOutput(), BaseCluster::doEneOutput(), BaseCluster::doFStatOutput(), BaseCluster::doIntStrucOutput(), BaseCluster::doOverlOutput(), BaseCluster::doRestartOutput(), BaseCluster::doVtkOutput(), BaseClusterInsertionBoundary::energyRatioTolerance_, generateParticle(), BaseInteractable::getIndSpecies(), ParticleHandler::getMass(), BaseInteractable::getPosition(), BaseParticle::getRadius(), BaseClusterInsertionBoundary::getRandomised(), BaseHandler< T >::getSize(), BaseInteractable::getSpecies(), BaseInteractable::getVelocity(), ParticleHandler::getVolume(), i, DPMBase::interactionHandler, InsertionBoundary::isActivated_, BaseClusterInsertionBoundary::isAmatOutputOn_, BaseClusterInsertionBoundary::isCdatOutputOn_, BaseClusterInsertionBoundary::isEneOutputOn_, BaseClusterInsertionBoundary::isFStatOutputOn_, BaseClusterInsertionBoundary::isIntStrucOutputOn_, BaseClusterInsertionBoundary::isOverlOutputOn_, BaseClusterInsertionBoundary::isRestartOutputOn_, BaseClusterInsertionBoundary::isVtkOutputOn_, logger, InsertionBoundary::massInserted_, md, BaseClusterInsertionBoundary::nClusterInserted_, BaseClusterInsertionBoundary::nInternalStructurePoints_, InsertionBoundary::numberOfParticlesInserted_, InsertionBoundary::p0, DPMBase::particleHandler, placeParticle(), BaseClusterInsertionBoundary::radiusParticle_, DPMBase::random, RNG::randomise(), BaseCluster::setClusterId(), BaseCluster::setCollisionTimeOverTimeStep(), BaseCluster::setEnergyRatioTolerance(), BaseCluster::setNumberOfInternalStructurePoints(), BaseCluster::setParticleSpecies(), BaseCluster::setPosition(), BaseCluster::setRadiusCluster(), BaseCluster::setRadiusParticle(), BaseClusterInsertionBoundary::setRadiusParticleAndNotNumberOfParticles_, BaseCluster::setSizeDispersityParticle(), BaseCluster::setVelocity(), BaseCluster::setVelocityDampingModulus(), BaseClusterInsertionBoundary::sizeDispersityParticle_, DPMBase::solve(), BaseClusterInsertionBoundary::velocityDampingModulus_, VERBOSE, and InsertionBoundary::volumeInserted_.
Referenced by RandomClusterInsertionBoundarySelfTest::setupInitialConditions().
copy()
FixedClusterInsertionBoundary * FixedClusterInsertionBoundary::copy () const override virtual
Creates a copy on the heap and returns a pointer.
Copy method; creates a copy on the heap and returns its pointer.
Returns
pointer to the copy on the heap
Reimplemented from BaseClusterInsertionBoundary.
 {
 #ifdef DEBUG_CONSTRUCTOR
     std::cout << "BaseClusterInsertionBoundary::copy() const finished" << std::endl;
 #endif
     return new FixedClusterInsertionBoundary(*this);
 }
References FixedClusterInsertionBoundary().
generateParticle()
BaseParticle * FixedClusterInsertionBoundary::generateParticle (RNG & random) final virtual
Sets cluster radii according to vector clusterRadii_.
Reimplemented from InsertionBoundary.
 {
     BaseParticle* P = particleToCopy_[0]->copy();
     P->setRadius(clusterRadii_[nClusterInserted_]);
     return P;
 }
References BaseClusterInsertionBoundary::clusterRadii_, BaseClusterInsertionBoundary::nClusterInserted_, Global_Physical_Variables::P, and InsertionBoundary::particleToCopy_.
Referenced by checkBoundaryBeforeTimeStep().
getName()
std::string FixedClusterInsertionBoundary::getName () const override private virtual
Returns the name of the object.
Returns the name of the object class
Returns
the object's class' name, i.e. 'ClusterInsertionBoundary'
Reimplemented from BaseClusterInsertionBoundary.
 {
     return "FixedClusterInsertionBoundary";
 }
placeParticle()
void FixedClusterInsertionBoundary::placeParticle (BaseParticle * p, RNG & random) final virtual
Places particles according to vector clusterPositions_ and sets a random velocity, if required.
Reimplemented from BaseClusterInsertionBoundary.
 {
     if(getRandomised())
         random.randomise();
     Vec3D pos, vel;
     pos = clusterPositions_[nClusterInserted_];
     vel.X = random.getRandomNumber(velMin_.X, velMax_.X);
     vel.Y = random.getRandomNumber(velMin_.Y, velMax_.Y);
     vel.Z = random.getRandomNumber(velMin_.Z, velMax_.Z);
     p->setPosition(pos);
     p->setVelocity(vel);
 }
References BaseClusterInsertionBoundary::clusterPositions_, BaseClusterInsertionBoundary::getRandomised(), RNG::getRandomNumber(), BaseClusterInsertionBoundary::nClusterInserted_, p, RNG::randomise(), BaseClusterInsertionBoundary::velMax_, BaseClusterInsertionBoundary::velMin_, Vec3D::X, Vec3D::Y, and Vec3D::Z.
Referenced by checkBoundaryBeforeTimeStep().
set() [1/2]
void FixedClusterInsertionBoundary::set (BaseParticle * particleToCopy, std::vector< Vec3D > positions, std::vector< Mdouble > radii, Vec3D velMin, Vec3D velMax, Mdouble rMicroParticle)
Sets the properties of the ClusterInsertionBoundary.
Sets all the properties of the cuboidal insertion boundary.
Parameters
[in] particleToCopy Pointer to the BaseParticle which is used as a basis for clusters to be inserted
[in] positions Vector containing all clusters positions
[in] radii Vector containing all clusters radii
[in] velMin Minimum velocity of inserted particles
[in] velMax Maximum velocity of inserted particles
[in] rMicroParticle Radius of the single particle composing the cluster.
 {
     setParticleToCopy(particleToCopy);
     setPositionsAndRadii(positions, radii);
     setVelocityRange(velMin, velMax);
     setRadiusMicroParticle(rMicroParticle);
 }
References InsertionBoundary::setParticleToCopy(), setPositionsAndRadii(), BaseClusterInsertionBoundary::setRadiusMicroParticle(), and BaseClusterInsertionBoundary::setVelocityRange().
set() [2/2]
void FixedClusterInsertionBoundary::set (std::vector< BaseParticle * > particleToCopy, std::vector< Vec3D > positions, std::vector< Mdouble > radii, Vec3D velMin, Vec3D velMax, Mdouble rMicroParticle)
Sets the properties of the ClusterInsertionBoundary.
Sets all the properties of the cuboidal insertion boundary.
Parameters
[in] particleToCopy Vector of pointers to the BaseParticles which are used as a basis for clusters to be inserted
[in] positions Vector containing all clusters positions
[in] radii Vector containing all clusters radii
[in] velMin Minimum velocity of inserted particles
[in] velMax Maximum velocity of inserted particles
[in] rMicroParticle Radius of the single particle composing the cluster.
 {
     setParticleToCopy(particleToCopy);
     setPositionsAndRadii(positions, radii);
     setVelocityRange(velMin, velMax);
     setRadiusMicroParticle(rMicroParticle);
 }
References InsertionBoundary::setParticleToCopy(), setPositionsAndRadii(), BaseClusterInsertionBoundary::setRadiusMicroParticle(), and BaseClusterInsertionBoundary::setVelocityRange().
Referenced by RandomClusterInsertionBoundarySelfTest::setupInitialConditions().
setPositionsAndRadii()
void FixedClusterInsertionBoundary::setPositionsAndRadii (std::vector< Vec3D > clusterPositions, std::vector< Mdouble > clusterRadii)
this sets positions and radii of the desired clusters.
After a few checks, this sets positions and radii of the desired clusters.
 {
     if (clusterPositions.size() != clusterRadii.size())
         logger(ERROR, "clusterPositions and clusterRadii have different size."
                       " clusterPositions.size() = %, clusterRadii.size() = %.",
                clusterPositions.size(), clusterRadii.size());
     else if (clusterPositions.empty())
         logger(ERROR, "clusterPositions is empty."
                       " clusterPositions.size() = %.", clusterPositions.size() );
     else if (clusterRadii.empty())
         logger(ERROR, "clusterRadii is empty."
                       " clusterRadii.size() = %.", clusterRadii.size());
     else
     {
         clusterPositions_ = clusterPositions;
         clusterRadii_ = clusterRadii;
     }
 }
References BaseClusterInsertionBoundary::clusterPositions_, BaseClusterInsertionBoundary::clusterRadii_, ERROR, and logger.
Referenced by set().
The documentation for this class was generated from the following files:
FixedClusterInsertionBoundary.h
FixedClusterInsertionBoundary.cc