MercuryDPM: Eigen::internal::etor_product_packet_impl< ColMajor, 1, Lhs, Rhs, Packet, LoadMode > Struct Template Reference
Eigen::internal::etor_product_packet_impl< ColMajor, 1, Lhs, Rhs, Packet, LoadMode > Struct Template Reference
#include <ProductEvaluators.h>
Static Public Member Functions
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void run (Index row, Index col, const Lhs &lhs, const Rhs &rhs, Index, Packet &res)
Member Function Documentation
run()
template<typename Lhs , typename Rhs , typename Packet , int LoadMode> static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::internal::etor_product_packet_impl< ColMajor, 1, Lhs, Rhs, Packet, LoadMode >::run (Index row, Index col, const Lhs & lhs, const Rhs & rhs, Index , Packet & res) inline static
{
     res = pmul(lhs.template packet<LoadMode, Packet>(row, Index(0)), pset1<Packet>(rhs.coeff(Index(0), col)));
   }
References col(), Eigen::internal::pmul(), res, and row().
The documentation for this struct was generated from the following file:
ProductEvaluators.h