MercuryDPM: idrstabl.cpp File Reference
idrstabl.cpp File Reference
#include "../../test/sparse_solver.h"
#include <unsupported/Eigen/IterativeSolvers>
Functions
template<typename T >
void test_idrstabl_T ()
EIGEN_DECLARE_TEST (idrstabl)
Function Documentation
EIGEN_DECLARE_TEST()
EIGEN_DECLARE_TEST (idrstabl)
{
   CALL_SUBTEST_1((test_idrstabl_T<double>()));
   CALL_SUBTEST_2((test_idrstabl_T<std::complex<double> >()));
 }
References CALL_SUBTEST_1, CALL_SUBTEST_2, and test_idrstabl_T().
test_idrstabl_T()
template<typename T > void test_idrstabl_T ()
{
   IDRSTABL<SparseMatrix<T>, DiagonalPreconditioner<T> > idrstabl_colmajor_diag;
   IDRSTABL<SparseMatrix<T>, IncompleteLUT<T> > idrstabl_colmajor_ilut;
   idrstabl_colmajor_diag.setTolerance(NumTraits<T>::epsilon() * 4);
   idrstabl_colmajor_ilut.setTolerance(NumTraits<T>::epsilon() * 4);
   CALL_SUBTEST(check_sparse_square_solving(idrstabl_colmajor_diag));
   CALL_SUBTEST(check_sparse_square_solving(idrstabl_colmajor_ilut));
 }
References CALL_SUBTEST, check_sparse_square_solving(), and Eigen::IterativeSolverBase< Derived >::setTolerance().
Referenced by EIGEN_DECLARE_TEST().