MercuryDPM: Eigen::TensorEvaluator< const TensorScanOp< Op, ArgType >, Device > Struct Template Reference
Eigen::TensorEvaluator< const TensorScanOp< Op, ArgType >, Device > Struct Template Reference
#include <TensorScan.h>
Public Types
enum {
IsAligned = false , PacketAccess = (PacketType<CoeffReturnType, Device>::size > 1) , BlockAccess = false , PreferBlockAccess = false ,
CoordAccess = false , RawAccess = true
}
typedef TensorScanOp< Op, ArgType > XprType
typedef XprType::Index Index
typedef const ArgType ChildTypeNoConst
typedef const ArgType ChildType
typedef DSizes< Index, NumDims > Dimensions
typedef std::remove_const_t< typename XprType::Scalar > Scalar
typedef XprType::CoeffReturnType CoeffReturnType
typedef PacketType< CoeffReturnType, Device >::type PacketReturnType
typedef TensorEvaluator< const TensorScanOp< Op, ArgType >, Device > Self
typedef StorageMemory< Scalar, Device > Storage
typedef Storage::Type EvaluatorPointerType
typedef internal::TensorBlockNotImplemented TensorBlock
Public Member Functions
EIGEN_STRONG_INLINE TensorEvaluator (const XprType &op, const Device &device)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Dimensions & dimensions () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Index & stride () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Index & consume_dim () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Index & size () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Op & accumulator () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE bool exclusive () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorEvaluator< ArgType, Device > & inner () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Device & device () const
EIGEN_STRONG_INLINE bool evalSubExprsIfNeeded (EvaluatorPointerType data)
template<int LoadMode>
EIGEN_DEVICE_FUNC PacketReturnType packet (Index index) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE EvaluatorPointerType data () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType coeff (Index index) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorOpCost costPerCoeff (bool) const
EIGEN_STRONG_INLINE void cleanup ()
Static Public Attributes
static constexpr int NumDims = internal::array_size<typename TensorEvaluator<ArgType, Device>::Dimensions>::value
static constexpr int Layout = TensorEvaluator<ArgType, Device>::Layout
Protected Attributes
TensorEvaluator< ArgType, Device > m_impl
const Device EIGEN_DEVICE_REF m_device
const bool m_exclusive
Op m_accumulator
const Index m_size
Index m_stride
Index m_consume_dim
EvaluatorPointerType m_output
Member Typedef Documentation
ChildType
template<typename Op , typename ArgType , typename Device > typedef const ArgType Eigen::TensorEvaluator< const TensorScanOp< Op, ArgType >, Device >::ChildType
ChildTypeNoConst
template<typename Op , typename ArgType , typename Device > typedef const ArgType Eigen::TensorEvaluator< const TensorScanOp< Op, ArgType >, Device >::ChildTypeNoConst
CoeffReturnType
template<typename Op , typename ArgType , typename Device > typedef XprType::CoeffReturnType Eigen::TensorEvaluator< const TensorScanOp< Op, ArgType >, Device >::CoeffReturnType
Dimensions
template<typename Op , typename ArgType , typename Device > typedef DSizes<Index, NumDims> Eigen::TensorEvaluator< const TensorScanOp< Op, ArgType >, Device >::Dimensions
EvaluatorPointerType
template<typename Op , typename ArgType , typename Device > typedef Storage::Type Eigen::TensorEvaluator< const TensorScanOp< Op, ArgType >, Device >::EvaluatorPointerType
Index
template<typename Op , typename ArgType , typename Device > typedef XprType::Index Eigen::TensorEvaluator< const TensorScanOp< Op, ArgType >, Device >::Index
PacketReturnType
template<typename Op , typename ArgType , typename Device > typedef PacketType<CoeffReturnType, Device>::type Eigen::TensorEvaluator< const TensorScanOp< Op, ArgType >, Device >::PacketReturnType
Scalar
template<typename Op , typename ArgType , typename Device > typedef std::remove_const_t<typename XprType::Scalar> Eigen::TensorEvaluator< const TensorScanOp< Op, ArgType >, Device >::Scalar
Self
template<typename Op , typename ArgType , typename Device > typedef TensorEvaluator<const TensorScanOp<Op, ArgType>, Device> Eigen::TensorEvaluator< const TensorScanOp< Op, ArgType >, Device >::Self
Storage
template<typename Op , typename ArgType , typename Device > typedef StorageMemory<Scalar, Device> Eigen::TensorEvaluator< const TensorScanOp< Op, ArgType >, Device >::Storage
TensorBlock
template<typename Op , typename ArgType , typename Device > typedef internal::TensorBlockNotImplemented Eigen::TensorEvaluator< const TensorScanOp< Op, ArgType >, Device >::TensorBlock
XprType
template<typename Op , typename ArgType , typename Device > typedef TensorScanOp<Op, ArgType> Eigen::TensorEvaluator< const TensorScanOp< Op, ArgType >, Device >::XprType
Member Enumeration Documentation
anonymous enum
template<typename Op , typename ArgType , typename Device > anonymous enum
Enumerator
IsAligned
PacketAccess
BlockAccess
PreferBlockAccess
CoordAccess
RawAccess
        {
     IsAligned = false,
     PacketAccess = (PacketType<CoeffReturnType, Device>::size > 1),
     BlockAccess = false,
     PreferBlockAccess = false,
     CoordAccess = false,
     RawAccess = true
   };
Constructor & Destructor Documentation
TensorEvaluator()
template<typename Op , typename ArgType , typename Device > EIGEN_STRONG_INLINE Eigen::TensorEvaluator< const TensorScanOp< Op, ArgType >, Device >::TensorEvaluator (const XprType & op, const Device & device) inline
       : m_impl(op.expression(), device),
         m_device(device),
         m_exclusive(op.exclusive()),
         m_accumulator(op.accumulator()),
         m_size(m_impl.dimensions()[op.axis()]),
         m_stride(1),
         m_consume_dim(op.axis()),
         m_output(NULL) {
     // Accumulating a scalar isn't supported.
     EIGEN_STATIC_ASSERT((NumDims > 0), YOU_MADE_A_PROGRAMMING_MISTAKE);
     eigen_assert(op.axis() >= 0 && op.axis() < NumDims);
     // Compute stride of scan axis
     const Dimensions& dims = m_impl.dimensions();
     if (static_cast<int>(Layout) == static_cast<int>(ColMajor)) {
       for (int i = 0; i < op.axis(); ++i) {
         m_stride = m_stride * dims[i];
       }
     } else {
       // dims can only be indexed through unsigned integers,
       // so let's use an unsigned type to let the compiler knows.
       // This prevents stupid warnings: ""'*((void*)(& evaluator)+64)[18446744073709551615]' may be used uninitialized
       // in this function"
       unsigned int axis = internal::convert_index<unsigned int>(op.axis());
       for (unsigned int i = NumDims - 1; i > axis; --i) {
         m_stride = m_stride * dims[i];
       }
     }
   }
References Eigen::ColMajor, eigen_assert, EIGEN_STATIC_ASSERT, i, Eigen::TensorEvaluator< Derived, Device >::Layout, and op.
Member Function Documentation
accumulator()
template<typename Op , typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Op& Eigen::TensorEvaluator< const TensorScanOp< Op, ArgType >, Device >::accumulator () const inline
 { return m_accumulator; }
cleanup()
template<typename Op , typename ArgType , typename Device > EIGEN_STRONG_INLINE void Eigen::TensorEvaluator< const TensorScanOp< Op, ArgType >, Device >::cleanup () inline
{
     if (m_output) {
       m_device.deallocate_temp(m_output);
       m_output = NULL;
     }
     m_impl.cleanup();
   }
References Eigen::TensorEvaluator< Derived, Device >::m_device.
Referenced by framework.Frame::__init__().
coeff()
template<typename Op , typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType Eigen::TensorEvaluator< const TensorScanOp< Op, ArgType >, Device >::coeff (Index index) const inline
 { return m_output[index]; }
consume_dim()
template<typename Op , typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Index& Eigen::TensorEvaluator< const TensorScanOp< Op, ArgType >, Device >::consume_dim () const inline
 { return m_consume_dim; }
costPerCoeff()
template<typename Op , typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorOpCost Eigen::TensorEvaluator< const TensorScanOp< Op, ArgType >, Device >::costPerCoeff (bool) const inline
{
     return TensorOpCost(sizeof(CoeffReturnType), 0, 0);
   }
data()
template<typename Op , typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE EvaluatorPointerType Eigen::TensorEvaluator< const TensorScanOp< Op, ArgType >, Device >::data () const inline
 { return m_output; }
Referenced by gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenQuaternionPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), gdb.printers.EigenSparseMatrixPrinter::to_string(), and gdb.printers.EigenQuaternionPrinter::to_string().
device()
template<typename Op , typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Device& Eigen::TensorEvaluator< const TensorScanOp< Op, ArgType >, Device >::device () const inline
 { return m_device; }
References Eigen::TensorEvaluator< Derived, Device >::m_device.
dimensions()
template<typename Op , typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Dimensions& Eigen::TensorEvaluator< const TensorScanOp< Op, ArgType >, Device >::dimensions () const inline
 { return m_impl.dimensions(); }
evalSubExprsIfNeeded()
template<typename Op , typename ArgType , typename Device > EIGEN_STRONG_INLINE bool Eigen::TensorEvaluator< const TensorScanOp< Op, ArgType >, Device >::evalSubExprsIfNeeded (EvaluatorPointerType data) inline
{
     m_impl.evalSubExprsIfNeeded(NULL);
     internal::ScanLauncher<Self, Op, Device> launcher;
     if (data) {
       launcher(*this, data);
       return false;
     }
     const Index total_size = internal::array_prod(dimensions());
     m_output =
         static_cast<EvaluatorPointerType>(m_device.get((Scalar*)m_device.allocate_temp(total_size * sizeof(Scalar))));
     launcher(*this, m_output);
     return true;
   }
References Eigen::internal::array_prod(), Eigen::TensorEvaluator< Derived, Device >::data(), Eigen::TensorEvaluator< Derived, Device >::dimensions(), and Eigen::TensorEvaluator< Derived, Device >::m_device.
exclusive()
template<typename Op , typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE bool Eigen::TensorEvaluator< const TensorScanOp< Op, ArgType >, Device >::exclusive () const inline
 { return m_exclusive; }
inner()
template<typename Op , typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorEvaluator<ArgType, Device>& Eigen::TensorEvaluator< const TensorScanOp< Op, ArgType >, Device >::inner () const inline
 { return m_impl; }
packet()
template<typename Op , typename ArgType , typename Device > template<int LoadMode> EIGEN_DEVICE_FUNC PacketReturnType Eigen::TensorEvaluator< const TensorScanOp< Op, ArgType >, Device >::packet (Index index) const inline
{
     return internal::ploadt<PacketReturnType, LoadMode>(m_output + index);
   }
size()
template<typename Op , typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Index& Eigen::TensorEvaluator< const TensorScanOp< Op, ArgType >, Device >::size () const inline
 { return m_size; }
stride()
template<typename Op , typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Index& Eigen::TensorEvaluator< const TensorScanOp< Op, ArgType >, Device >::stride () const inline
 { return m_stride; }
Member Data Documentation
Layout
template<typename Op , typename ArgType , typename Device > constexpr int Eigen::TensorEvaluator< const TensorScanOp< Op, ArgType >, Device >::Layout = TensorEvaluator<ArgType, Device>::Layout static constexpr
m_accumulator
template<typename Op , typename ArgType , typename Device > Op Eigen::TensorEvaluator< const TensorScanOp< Op, ArgType >, Device >::m_accumulator protected
m_consume_dim
template<typename Op , typename ArgType , typename Device > Index Eigen::TensorEvaluator< const TensorScanOp< Op, ArgType >, Device >::m_consume_dim protected
m_device
template<typename Op , typename ArgType , typename Device > const Device EIGEN_DEVICE_REF Eigen::TensorEvaluator< const TensorScanOp< Op, ArgType >, Device >::m_device protected
m_exclusive
template<typename Op , typename ArgType , typename Device > const bool Eigen::TensorEvaluator< const TensorScanOp< Op, ArgType >, Device >::m_exclusive protected
m_impl
template<typename Op , typename ArgType , typename Device > TensorEvaluator<ArgType, Device> Eigen::TensorEvaluator< const TensorScanOp< Op, ArgType >, Device >::m_impl protected
m_output
template<typename Op , typename ArgType , typename Device > EvaluatorPointerType Eigen::TensorEvaluator< const TensorScanOp< Op, ArgType >, Device >::m_output protected
m_size
template<typename Op , typename ArgType , typename Device > const Index Eigen::TensorEvaluator< const TensorScanOp< Op, ArgType >, Device >::m_size protected
m_stride
template<typename Op , typename ArgType , typename Device > Index Eigen::TensorEvaluator< const TensorScanOp< Op, ArgType >, Device >::m_stride protected
NumDims
template<typename Op , typename ArgType , typename Device > constexpr int Eigen::TensorEvaluator< const TensorScanOp< Op, ArgType >, Device >::NumDims = internal::array_size<typename TensorEvaluator<ArgType, Device>::Dimensions>::value static constexpr
The documentation for this struct was generated from the following file:
TensorScan.h