MercuryDPM: SmallMatrix_impl.h File Reference
SmallMatrix_impl.h File Reference
#include "SmallMatrix.h"
Functions
void dgemv_ (const char *trans, int *m, int *n, double *alpha, double *A, int *LDA, double *x, int *incx, double *beta, double *y, int *incy)
This does matrix times vector and is from blas level 2.
int dgemm_ (const char *transA, const char *transB, int *M, int *N, int *k, double *alpha, double *A, int *LDA, double *B, int *LDB, double *beta, double *C, int *LDC)
This is the gernal matrix multiplication from blas level 3.
int daxpy_ (int *N, double *DA, double *DX, int *INCX, double *DY, int *INCY)
This is the gerneral scalar times vector + vector from blas, hence from blas level 1. Here we also use on a matrix by treating as a vector.
void dgetrf_ (int *M, int *N, double *A, int *lda, int *IPIV, int *INFO)
This is LU factorisation of the matrix A. This has been taken from LAPACK.
void dgetri_ (int *N, double *A, int *lda, int *IPIV, double *WORK, int *lwork, int *INFO)
This is the inverse calulation also from LAPACK. Calculates inverse if you pass it the LU factorisation.
void dgesv_ (int *N, int *NRHS, double *A, int *lda, int *IPIV, double *B, int *LDB, int *INFO)
This is used for solve Ax=B for x. Again this is from LAPACK.
template<unsigned int numberOfRows, unsigned int numberOfColumns>
SmallVector< numberOfColumns > operator* (SmallVector< numberOfRows > &vec, SmallMatrix< numberOfRows, numberOfColumns > &mat)
Multiplies a matrix with a vector.
Function Documentation
daxpy_()
int daxpy_ (int * N, double * DA, double * DX, int * INCX, double * DY, int * INCY)
This is the gerneral scalar times vector + vector from blas, hence from blas level 1. Here we also use on a matrix by treating as a vector.
dgemm_()
int dgemm_ (const char * transA, const char * transB, int * M, int * N, int * k, double * alpha, double * A, int * LDA, double * B, int * LDB, double * beta, double * C, int * LDC)
This is the gernal matrix multiplication from blas level 3.
Referenced by SmallMatrix< numberOfRows, numberOfColumns >::operator*().
dgemv_()
void dgemv_ (const char * trans, int * m, int * n, double * alpha, double * A, int * LDA, double * x, int * incx, double * beta, double * y, int * incy)
This does matrix times vector and is from blas level 2.
Referenced by SmallMatrix< numberOfRows, numberOfColumns >::operator*(), and operator*().
dgesv_()
void dgesv_ (int * N, int * NRHS, double * A, int * lda, int * IPIV, double * B, int * LDB, int * INFO)
This is used for solve Ax=B for x. Again this is from LAPACK.
Referenced by SmallMatrix< numberOfRows, numberOfColumns >::solve().
dgetrf_()
void dgetrf_ (int * M, int * N, double * A, int * lda, int * IPIV, int * INFO)
This is LU factorisation of the matrix A. This has been taken from LAPACK.
Referenced by SmallMatrix< numberOfRows, numberOfColumns >::inverse(), and SmallMatrix< numberOfRows, numberOfColumns >::LUfactorisation().
dgetri_()
void dgetri_ (int * N, double * A, int * lda, int * IPIV, double * WORK, int * lwork, int * INFO)
This is the inverse calulation also from LAPACK. Calculates inverse if you pass it the LU factorisation.
Referenced by SmallMatrix< numberOfRows, numberOfColumns >::inverse().
operator*()
template<unsigned int numberOfRows, unsigned int numberOfColumns> SmallVector<numberOfColumns> operator* (SmallVector< numberOfRows > & vec, SmallMatrix< numberOfRows, numberOfColumns > & mat)
Multiplies a matrix with a vector.
 {
     if (numberOfColumns == 0)
     {
         logger(WARN, "Trying to multiply a vector with a matrix without any columns.");
         return SmallVector<numberOfColumns>();
     }
     int nr = numberOfRows;
     int nc = numberOfColumns;
     int i_one = 1;
     double d_one = 1.0;
     double d_zero = 0.0;
     SmallVector<numberOfColumns> result;
     logger(DEBUG, "Matrix size: % x % \n Vector size: %", nr, nc, vec.size());
     dgemv_("T", &nr, &nc, &d_one, mat.data(), &nr, vec.data(), &i_one, &d_zero, result.data(), &i_one);
     return result;
 }
References Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::data(), SmallVector< numberOfRows >::data(), DEBUG, dgemv_(), logger, SmallVector< numberOfRows >::size(), and WARN.