MercuryDPM: Eigen::internal::product_transpose_helper< Lhs, Rhs, Option, TransposeProductEnum::PermutationMatrix > Struct Template Reference
Eigen::internal::product_transpose_helper< Lhs, Rhs, Option, TransposeProductEnum::PermutationMatrix > Struct Template Reference
#include <Product.h>
Public Types
using Derived = Product< Lhs, Rhs, Option >
using LhsInverseType = typename PermutationBase< Lhs >::InverseReturnType
using RhsScalar = typename traits< Rhs >::Scalar
using RhsTransposeType = typename DenseBase< Rhs >::ConstTransposeReturnType
using RhsConjugateTransposeType = CwiseUnaryOp< scalar_conjugate_op< RhsScalar >, RhsTransposeType >
using RhsAdjointType = std::conditional_t< NumTraits< RhsScalar >::IsComplex, RhsConjugateTransposeType, RhsTransposeType >
using TransposeType = Product< RhsTransposeType, LhsInverseType, Option >
using AdjointType = Product< RhsAdjointType, LhsInverseType, Option >
Static Public Member Functions
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TransposeType run_transpose (const Derived &derived)
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE AdjointType run_adjoint (const Derived &derived)
Member Typedef Documentation
AdjointType
template<typename Lhs , typename Rhs , int Option> using Eigen::internal::product_transpose_helper< Lhs, Rhs, Option, TransposeProductEnum::PermutationMatrix >::AdjointType = Product<RhsAdjointType, LhsInverseType, Option>
Derived
template<typename Lhs , typename Rhs , int Option> using Eigen::internal::product_transpose_helper< Lhs, Rhs, Option, TransposeProductEnum::PermutationMatrix >::Derived = Product<Lhs, Rhs, Option>
LhsInverseType
template<typename Lhs , typename Rhs , int Option> using Eigen::internal::product_transpose_helper< Lhs, Rhs, Option, TransposeProductEnum::PermutationMatrix >::LhsInverseType = typename PermutationBase<Lhs>::InverseReturnType
RhsAdjointType
template<typename Lhs , typename Rhs , int Option> using Eigen::internal::product_transpose_helper< Lhs, Rhs, Option, TransposeProductEnum::PermutationMatrix >::RhsAdjointType = std::conditional_t<NumTraits<RhsScalar>::IsComplex, RhsConjugateTransposeType, RhsTransposeType>
RhsConjugateTransposeType
template<typename Lhs , typename Rhs , int Option> using Eigen::internal::product_transpose_helper< Lhs, Rhs, Option, TransposeProductEnum::PermutationMatrix >::RhsConjugateTransposeType = CwiseUnaryOp<scalar_conjugate_op<RhsScalar>, RhsTransposeType>
RhsScalar
template<typename Lhs , typename Rhs , int Option> using Eigen::internal::product_transpose_helper< Lhs, Rhs, Option, TransposeProductEnum::PermutationMatrix >::RhsScalar = typename traits<Rhs>::Scalar
RhsTransposeType
template<typename Lhs , typename Rhs , int Option> using Eigen::internal::product_transpose_helper< Lhs, Rhs, Option, TransposeProductEnum::PermutationMatrix >::RhsTransposeType = typename DenseBase<Rhs>::ConstTransposeReturnType
TransposeType
template<typename Lhs , typename Rhs , int Option> using Eigen::internal::product_transpose_helper< Lhs, Rhs, Option, TransposeProductEnum::PermutationMatrix >::TransposeType = Product<RhsTransposeType, LhsInverseType, Option>
Member Function Documentation
run_adjoint()
template<typename Lhs , typename Rhs , int Option> static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE AdjointType Eigen::internal::product_transpose_helper< Lhs, Rhs, Option, TransposeProductEnum::PermutationMatrix >::run_adjoint (const Derived & derived) inline static
{
     return AdjointType(RhsAdjointType(RhsTransposeType(derived.rhs())), LhsInverseType(derived.lhs()));
   }
References Eigen::Product< Lhs_, Rhs_, Option >::lhs(), and Eigen::Product< Lhs_, Rhs_, Option >::rhs().
run_transpose()
template<typename Lhs , typename Rhs , int Option> static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TransposeType Eigen::internal::product_transpose_helper< Lhs, Rhs, Option, TransposeProductEnum::PermutationMatrix >::run_transpose (const Derived & derived) inline static
{
     return TransposeType(RhsTransposeType(derived.rhs()), LhsInverseType(derived.lhs()));
   }
References Eigen::Product< Lhs_, Rhs_, Option >::lhs(), and Eigen::Product< Lhs_, Rhs_, Option >::rhs().
The documentation for this struct was generated from the following file:
Product.h