MercuryDPM: FluxBoundary Class Reference
FluxBoundary Class Reference
Used for measuring flow rates through a given plane; acts like a pair of scales Inherits from BaseBoundary. Can measure forward, backward and net fluxes.
#include <FluxBoundary.h>
Public Member Functions
FluxBoundary ()
default constructor
~FluxBoundary () override
destructor
FluxBoundary * copy () const override
Copy method; creates copy on the heap and returns a pointer to it.
void set (const Vec3D &normal, Mdouble distance)
Sets boundary position based on a normal and distance.
void reset ()
Resets the counts to zero.
void move (Mdouble position)
Sets the boundary's distance property to the given one.
Mdouble getDistance (const Mdouble &distanceFromOrigin, const Vec3D &position) const
Returns the shortest distance between the boundary at a given separation from the origin and given position.
Mdouble getDistance (const Vec3D &position) const
Returns the shortest distance between the boundary and given position.
Mdouble getPreviousDistance (const Vec3D &position) const
Returns the shortest distance between the boundary and given position as it was in the previous timestep.
void checkBoundaryAfterParticlesMove (ParticleHandler &pH) override
Runs at the end of each time step.
bool checkBoundaryAfterParticleMoved (BaseParticle *p, ParticleHandler &pH)
Checks if particle has crossed the boundary and updates the scales if so.
unsigned int getNumberOfParticlesCrossedForw () const
Gets the number of particles that have crossed the boundary.
unsigned int getNumberOfParticlesCrossedBack () const
unsigned int getNumberOfParticlesCrossedNet () const
double getMassOfParticlesCrossedForw () const
double getMassOfParticlesCrossedBack () const
double getMassOfParticlesCrossedNet () const
double getVolumeOfParticlesCrossedForw () const
double getVolumeOfParticlesCrossedBack () const
double getVolumeOfParticlesCrossedNet () const
void read (std::istream &is) override
Reads some boundary properties from an std::istream.
MERCURYDPM_DEPRECATED void oldRead (std::istream &is)
Deprecated read method. use FluxBoundary::read() instead.
void write (std::ostream &os) const override
Writes the boundary properties to an std::ostream.
std::string getName () const override
Returns the name of the object.
void setPrescribedDistance (std::function< Mdouble(double)> prescribedDistance)
Sets the prescribed distance function.
Public Member Functions inherited from BaseBoundary
BaseBoundary ()
default constructor.
BaseBoundary (const BaseBoundary &b)
copy constructor
~BaseBoundary () override
destructor
virtual void createPeriodicParticle (BaseParticle *p UNUSED, ParticleHandler &pH UNUSED)
Creates a periodic particle in case of periodic boundaries in serial build.
virtual void createPeriodicParticles (ParticleHandler &pH UNUSED)
Creates periodic copies of given particle in case of periodic boundaries.
virtual void checkBoundaryBeforeTimeStep (DPMBase *md)
Virtual function that does things before each time step.
virtual void actionsBeforeTimeLoop ()
Virtual function that does something after DPMBase::setupInitialConditions but before the first time step.
virtual void modifyGhostAfterCreation (BaseParticle *particle, int i)
virtual void writeVTK (std::fstream &file)
void setHandler (BoundaryHandler *handler)
Sets the boundary's BoundaryHandler.
BoundaryHandler * getHandler () const
Returns the boundary's BoundaryHandler.
Public Member Functions inherited from BaseObject
BaseObject ()=default
Default constructor.
BaseObject (const BaseObject &p)=default
Copy constructor, copies all the objects BaseObject contains.
virtual ~BaseObject ()=default
virtual destructor
virtual void moveInHandler (unsigned int index)
Except that it is virtual, it does the same thing as setIndex() does.
void setIndex (unsigned int index)
Allows one to assign an index to an object in the handler/container.
void setId (unsigned long id)
Assigns a unique identifier to each object in the handler (container) which remains constant even after the object is deleted from the container/handler.
unsigned int getIndex () const
Returns the index of the object in the handler.
unsigned int getId () const
Returns the unique identifier of any particular object.
void setGroupId (unsigned groupId)
unsigned getGroupId () const
Private Attributes
Vec3D normal_
outward unit normal vector
Mdouble scaleFactor_
This is the factor to rescale the given normal vector to a unit vectors.
Mdouble distance_
The boundary's distance from the origin.
Mdouble previousDistance_
The boundary's distance from the origin in the previous timestep).
unsigned int numberOfParticlesCrossedForw_
Number of particles that have been deleted by this boundary.
unsigned int numberOfParticlesCrossedBack_
double massCrossedForw_
double massCrossedBack_
double volumeCrossedForw_
double volumeCrossedBack_
std::function< Mdouble(double)> prescribedDistance_
A function which sets the distance of the boundary from the origin.
Detailed Description
Used for measuring flow rates through a given plane; acts like a pair of scales Inherits from BaseBoundary. Can measure forward, backward and net fluxes.
Constructor & Destructor Documentation
FluxBoundary()
FluxBoundary::FluxBoundary ()
default constructor
Default constructor (calls the parent-constructor of BaseBoundary as well)
         : BaseBoundary()
 {
     distance_ = std::numeric_limits<double>::quiet_NaN();
     previousDistance_  = std::numeric_limits<double>::quiet_NaN();
     scaleFactor_ = std::numeric_limits<double>::quiet_NaN();
     numberOfParticlesCrossedForw_ = 0;
     numberOfParticlesCrossedBack_ = 0;
     massCrossedForw_ = 0;
     massCrossedBack_ = 0;
     volumeCrossedForw_ = 0;
     volumeCrossedBack_ = 0;
     prescribedDistance_ = nullptr;
 #ifdef DEBUG_CONSTRUCTOR
     std::cout<<"FluxBoundary::FluxBoundary() finished"<<std::endl;
 #endif
 }
References distance_, massCrossedBack_, massCrossedForw_, numberOfParticlesCrossedBack_, numberOfParticlesCrossedForw_, prescribedDistance_, previousDistance_, scaleFactor_, volumeCrossedBack_, and volumeCrossedForw_.
Referenced by copy().
~FluxBoundary()
FluxBoundary::~FluxBoundary () override
destructor
Destructor
 {
 #ifdef DEBUG_DESTRUCTOR
     std::cout<<"FluxBoundary::~FluxBoundary() finished"<<std::endl;
 #endif
 }
Member Function Documentation
checkBoundaryAfterParticleMoved()
bool FluxBoundary::checkBoundaryAfterParticleMoved (BaseParticle * p, ParticleHandler & pH)
Checks if particle has crossed the boundary and updates the scales if so.
Checks if particle has passed the boundary, and if so, counts it.
Parameters
[in] p pointer to the particle which is to be checked
[out] pH the particle's ParticleHandler
Returns
FALSE, since the particle is not deleted by this boundary
 {
     if (getPreviousDistance(p->getPreviousPosition()) >= 0 && getDistance(p->getPosition()) < 0)
     {
         numberOfParticlesCrossedForw_++;
         massCrossedForw_ += p->getMass();
         volumeCrossedForw_ += p->getVolume();
     }
     else if (getPreviousDistance(p->getPreviousPosition()) < 0 && getDistance(p->getPosition()) >= 0)
     {
         numberOfParticlesCrossedBack_++;
         massCrossedBack_ += p->getMass();
         volumeCrossedBack_ += p->getVolume();
     }
     return false;
 }
References getDistance(), getPreviousDistance(), massCrossedBack_, massCrossedForw_, numberOfParticlesCrossedBack_, numberOfParticlesCrossedForw_, p, volumeCrossedBack_, and volumeCrossedForw_.
Referenced by checkBoundaryAfterParticlesMove().
checkBoundaryAfterParticlesMove()
void FluxBoundary::checkBoundaryAfterParticlesMove (ParticleHandler & pH) override virtual
Runs at the end of each time step.
Reimplemented from BaseBoundary.
 {
     if (prescribedDistance_)
     {
         distance_ = prescribedDistance_(getHandler()->getDPMBase()->getTime());
     }
     for (auto p = pH.begin(); p != pH.end(); ++p)
         checkBoundaryAfterParticleMoved(*p, pH);
     // Set the current distance as previous distance for the next timestep
     previousDistance_ = distance_;
 }
References BaseHandler< T >::begin(), checkBoundaryAfterParticleMoved(), distance_, BaseHandler< T >::end(), BaseBoundary::getHandler(), p, prescribedDistance_, and previousDistance_.
copy()
FluxBoundary * FluxBoundary::copy () const override virtual
Copy method; creates copy on the heap and returns a pointer to it.
Copy function, which creates a copy and returns a pointer to that copy (on the heap)
Returns
pointer to the copy
Implements BaseBoundary.
 {
     return new FluxBoundary(*this);
 }
References FluxBoundary().
getDistance() [1/2]
Mdouble FluxBoundary::getDistance (const Mdouble & distanceFromOrigin, const Vec3D & position) const
Returns the shortest distance between the boundary at a given separation from the origin and given position.
 {
     return distanceFromOrigin - Vec3D::dot(position, normal_);
 }
References Vec3D::dot(), and normal_.
Referenced by checkBoundaryAfterParticleMoved(), getDistance(), and getPreviousDistance().
getDistance() [2/2]
Mdouble FluxBoundary::getDistance (const Vec3D & position) const inline
Returns the shortest distance between the boundary and given position.
Parameters
[in] position the position of which the distance should be calculated.
     {
         return getDistance(distance_, position);
     }
References distance_, and getDistance().
getMassOfParticlesCrossedBack()
double FluxBoundary::getMassOfParticlesCrossedBack () const
 {
     return massCrossedBack_;
 }
References massCrossedBack_.
Referenced by FluxAndPeriodicBoundarySelfTest::actionsAfterTimeStep(), FluxBoundarySelfTest::actionsAfterTimeStep(), and main().
getMassOfParticlesCrossedForw()
double FluxBoundary::getMassOfParticlesCrossedForw () const
 {
     return massCrossedForw_;
 }
References massCrossedForw_.
Referenced by FluxAndPeriodicBoundarySelfTest::actionsAfterTimeStep(), FluxBoundarySelfTest::actionsAfterTimeStep(), and main().
getMassOfParticlesCrossedNet()
double FluxBoundary::getMassOfParticlesCrossedNet () const
 {
     return (massCrossedForw_ - massCrossedBack_);
 }
References massCrossedBack_, and massCrossedForw_.
Referenced by BoundariesSelfTest::actionsAfterTimeStep(), and main().
getName()
std::string FluxBoundary::getName () const override virtual
Returns the name of the object.
Returns the object's class name (i.e. 'FluxBoundary').
Returns
the object's class name
Implements BaseObject.
 {
     return "FluxBoundary";
 }
getNumberOfParticlesCrossedBack()
unsigned int FluxBoundary::getNumberOfParticlesCrossedBack () const
 {
     return numberOfParticlesCrossedBack_;
 }
References numberOfParticlesCrossedBack_.
Referenced by FluxAndPeriodicBoundarySelfTest::actionsAfterTimeStep(), FluxBoundarySelfTest::actionsAfterTimeStep(), and main().
getNumberOfParticlesCrossedForw()
unsigned int FluxBoundary::getNumberOfParticlesCrossedForw () const
Gets the number of particles that have crossed the boundary.
Returns the number of particles that have crossed in either direction.
 {
     return numberOfParticlesCrossedForw_;
 }
References numberOfParticlesCrossedForw_.
Referenced by FluxAndPeriodicBoundarySelfTest::actionsAfterTimeStep(), FluxBoundarySelfTest::actionsAfterTimeStep(), and main().
getNumberOfParticlesCrossedNet()
unsigned int FluxBoundary::getNumberOfParticlesCrossedNet () const
 {
     return (numberOfParticlesCrossedForw_ - numberOfParticlesCrossedBack_);
 }
References numberOfParticlesCrossedBack_, and numberOfParticlesCrossedForw_.
Referenced by BoundariesSelfTest::actionsAfterTimeStep(), and main().
getPreviousDistance()
Mdouble FluxBoundary::getPreviousDistance (const Vec3D & position) const inline
Returns the shortest distance between the boundary and given position as it was in the previous timestep.
Parameters
[in] position the position of which the distance should be calculated.
     {
         return getDistance(previousDistance_, position);
     }
References getDistance(), and previousDistance_.
Referenced by checkBoundaryAfterParticleMoved().
getVolumeOfParticlesCrossedBack()
double FluxBoundary::getVolumeOfParticlesCrossedBack () const
 {
     return volumeCrossedBack_;
 }
References volumeCrossedBack_.
Referenced by FluxAndPeriodicBoundarySelfTest::actionsAfterTimeStep(), FluxBoundarySelfTest::actionsAfterTimeStep(), and main().
getVolumeOfParticlesCrossedForw()
double FluxBoundary::getVolumeOfParticlesCrossedForw () const
 {
     return volumeCrossedForw_;
 }
References volumeCrossedForw_.
Referenced by FluxAndPeriodicBoundarySelfTest::actionsAfterTimeStep(), FluxBoundarySelfTest::actionsAfterTimeStep(), and main().
getVolumeOfParticlesCrossedNet()
double FluxBoundary::getVolumeOfParticlesCrossedNet () const
 {
     return (volumeCrossedForw_ - volumeCrossedBack_);
 }
References volumeCrossedBack_, and volumeCrossedForw_.
Referenced by BoundariesSelfTest::actionsAfterTimeStep(), and main().
move()
void FluxBoundary::move (Mdouble distance)
Sets the boundary's distance property to the given one.
Resets the boundary's 'distance' from the origin to be the one given.
Parameters
[in] distance the new 'distance' between boundary and origin. see also comments of FluxBoundary::set().
 {
     distance_ = distance * scaleFactor_;
 }
References distance_, and scaleFactor_.
oldRead()
void FluxBoundary::oldRead (std::istream & is)
Deprecated read method. use FluxBoundary::read() instead.
the deprecated version of the read-method. Should not be used by new users!
Deprecated:
Should be gone by Mercury 2.0. Use FluxBoundary::read() instead.
 {
     std::string dummy;
     is >> dummy >> normal_ >> dummy >> scaleFactor_ >> dummy >> distance_;
 }
References distance_, normal_, scaleFactor_, and oomph::Global_string_for_annotation::string().
read()
void FluxBoundary::read (std::istream & is) override virtual
Reads some boundary properties from an std::istream.
Reads a number of boundary properties from the given std::istream.
Parameters
[in,out] is the istream
Implements BaseBoundary.
 {
     BaseBoundary::read(is);
     std::string dummy;
     bool hadPrescribedDistance;
     is >> dummy >> normal_
        >> dummy >> scaleFactor_
        >> dummy >> distance_
        >> dummy >> previousDistance_
        >> dummy >> hadPrescribedDistance;
     if (hadPrescribedDistance)
         logger(WARN, "FluxBoundary had described distance. The function can not be read from the restart file. Make sure you set it again.");
 }
References distance_, logger, normal_, previousDistance_, BaseBoundary::read(), scaleFactor_, oomph::Global_string_for_annotation::string(), and WARN.
reset()
void FluxBoundary::reset ()
Resets the counts to zero.
Resets the various counts to zero.
 {
     numberOfParticlesCrossedForw_ = 0;
     numberOfParticlesCrossedBack_ = 0;
     massCrossedForw_ = 0;
     massCrossedBack_ = 0;
     volumeCrossedForw_ = 0;
     volumeCrossedBack_ = 0;
 }
References massCrossedBack_, massCrossedForw_, numberOfParticlesCrossedBack_, numberOfParticlesCrossedForw_, volumeCrossedBack_, and volumeCrossedForw_.
set()
void FluxBoundary::set (const Vec3D & normal, Mdouble distance)
Sets boundary position based on a normal and distance.
Defines the placing of the (2D) boundary based on the given normal and distance.
Parameters
[in] normal boundary normal vector
[in] distance 'distance' between the origin and the boundary, such that the following relation is satisfied:
\[ \mathbf{r} \cdot \mathbf{\hat{n}} = d \]
in which \(\mathbf{\hat{n}} \) and \(d \) are the given normal vector and distance, respectively. NB: If the distance is the ACTUAL distance from the origin, the normal vector must be of UNIT LENGTH for the placing of the boundary to be done correctly.
 {
     scaleFactor_ = 1. / std::sqrt(Vec3D::dot(normal, normal));
     normal_ = normal * scaleFactor_;
     distance_ = distance * scaleFactor_;
     previousDistance_ = distance_;
 }
References distance_, Vec3D::dot(), WallFunction::normal(), normal_, previousDistance_, scaleFactor_, and sqrt().
Referenced by BoundariesSelfTest::BoundariesSelfTest(), FluxAndPeriodicBoundarySelfTest::FluxAndPeriodicBoundarySelfTest(), FluxBoundarySelfTest::FluxBoundarySelfTest(), FluxBoundaryPrescribedDistanceUnitTest::setupInitialConditions(), and FluxBoundaryUnitTest::setupInitialConditions().
setPrescribedDistance()
void FluxBoundary::setPrescribedDistance (std::function< Mdouble(double)> prescribedDistance)
Sets the prescribed distance function.
 {
     prescribedDistance_ = prescribedDistance;
 }
References prescribedDistance_.
Referenced by FluxBoundaryPrescribedDistanceUnitTest::setupInitialConditions().
write()
void FluxBoundary::write (std::ostream & os) const override virtual
Writes the boundary properties to an std::ostream.
Writes the boundary properties to an std::ostream.
Parameters
[out] os the ostream the properties are to be written to.
Implements BaseBoundary.
 {
     BaseBoundary::write(os);
     os << " normal " << normal_
        << " scaleFactor " << scaleFactor_
        << " distance " << distance_
        << " previousDistance " << previousDistance_;
     os << " prescribedDistance ";
     if (prescribedDistance_)
         os << true;
     else
         os << false;
 }
References distance_, normal_, prescribedDistance_, previousDistance_, scaleFactor_, and BaseBoundary::write().
Member Data Documentation
distance_
Mdouble FluxBoundary::distance_ private
The boundary's distance from the origin.
Referenced by checkBoundaryAfterParticlesMove(), FluxBoundary(), getDistance(), move(), oldRead(), read(), set(), and write().
massCrossedBack_
double FluxBoundary::massCrossedBack_ private
Referenced by checkBoundaryAfterParticleMoved(), FluxBoundary(), getMassOfParticlesCrossedBack(), getMassOfParticlesCrossedNet(), and reset().
massCrossedForw_
double FluxBoundary::massCrossedForw_ private
Referenced by checkBoundaryAfterParticleMoved(), FluxBoundary(), getMassOfParticlesCrossedForw(), getMassOfParticlesCrossedNet(), and reset().
normal_
Vec3D FluxBoundary::normal_ private
outward unit normal vector
Referenced by getDistance(), oldRead(), read(), set(), and write().
numberOfParticlesCrossedBack_
unsigned int FluxBoundary::numberOfParticlesCrossedBack_ private
Referenced by checkBoundaryAfterParticleMoved(), FluxBoundary(), getNumberOfParticlesCrossedBack(), getNumberOfParticlesCrossedNet(), and reset().
numberOfParticlesCrossedForw_
unsigned int FluxBoundary::numberOfParticlesCrossedForw_ private
Number of particles that have been deleted by this boundary.
Referenced by checkBoundaryAfterParticleMoved(), FluxBoundary(), getNumberOfParticlesCrossedForw(), getNumberOfParticlesCrossedNet(), and reset().
prescribedDistance_
std::function<Mdouble(double)> FluxBoundary::prescribedDistance_ private
A function which sets the distance of the boundary from the origin.
Referenced by checkBoundaryAfterParticlesMove(), FluxBoundary(), setPrescribedDistance(), and write().
previousDistance_
Mdouble FluxBoundary::previousDistance_ private
The boundary's distance from the origin in the previous timestep).
This is necessary to catch transitions from particles, if the Boundary is moving
Referenced by checkBoundaryAfterParticlesMove(), FluxBoundary(), getPreviousDistance(), read(), set(), and write().
scaleFactor_
Mdouble FluxBoundary::scaleFactor_ private
This is the factor to rescale the given normal vector to a unit vectors.
NB: Not only the normal vector is rescaled by this factor, also the 'distance' from the origin of the boundary is scaled by this factor! Also, once the boundary position is set with FluxBoundary::set(), the arguments of any reset of the distance_ property (i.e. usage of FluxBoundary::move()) will be rescaled by the same factor!
Referenced by FluxBoundary(), move(), oldRead(), read(), set(), and write().
volumeCrossedBack_
double FluxBoundary::volumeCrossedBack_ private
Referenced by checkBoundaryAfterParticleMoved(), FluxBoundary(), getVolumeOfParticlesCrossedBack(), getVolumeOfParticlesCrossedNet(), and reset().
volumeCrossedForw_
double FluxBoundary::volumeCrossedForw_ private
Referenced by checkBoundaryAfterParticleMoved(), FluxBoundary(), getVolumeOfParticlesCrossedForw(), getVolumeOfParticlesCrossedNet(), and reset().
The documentation for this class was generated from the following files:
FluxBoundary.h
FluxBoundary.cc