MercuryDPM: MyIntegral Class Reference
MyIntegral Class Reference
Public Member Functions
MyIntegral (const unsigned &n_knot)
MyIntegral (const MyIntegral &dummy)
Broken copy constructor.
unsigned nweight () const
Number of integration points of the scheme.
double knot (const unsigned &i, const unsigned &j) const
Return coordinate s[j] (j=0) of integration point i –.
double weight (const unsigned &i) const
Return weight of integration point i.
MyIntegral (const unsigned &n_knot)
MyIntegral (const MyIntegral &dummy)
Broken copy constructor.
void operator= (const MyIntegral &)
Broken assignment operator.
unsigned nweight () const
Number of integration points of the scheme.
double knot (const unsigned &i, const unsigned &j) const
Return coordinate s[j] (j=0) of integration point i –.
double weight (const unsigned &i) const
Return weight of integration point i.
Public Member Functions inherited from oomph::Integral
Integral ()
Default constructor (empty)
Integral (const Integral &dummy)=delete
Broken copy constructor.
void operator= (const Integral &)=delete
Broken assignment operator.
virtual ~Integral ()
Virtual destructor (empty)
virtual Vector< double > knot (const unsigned &i) const
Return local coordinates of i-th intergration point. Broken virtual.
Private Attributes
unsigned N_knot
Number of integration points.
Detailed Description
////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////// One-dimensional integration scheme that locates integration points uniformly along boundary (if elements are equal sized, that is...)
Constructor & Destructor Documentation
MyIntegral() [1/4]
MyIntegral::MyIntegral (const unsigned & n_knot) inline
Constructor: Specify number of uniformly spaced sample points in unit interval
 {N_knot=n_knot;}
MyIntegral() [2/4]
MyIntegral::MyIntegral (const MyIntegral & dummy) inline
Broken copy constructor.
   {
    BrokenCopy::broken_copy("MyIntegral");
   }
References oomph::BrokenCopy::broken_copy().
MyIntegral() [3/4]
MyIntegral::MyIntegral (const unsigned & n_knot) inline
Constructor: Specify number of uniformly spaced sample points in unit interval
 {N_knot=n_knot;}
MyIntegral() [4/4]
MyIntegral::MyIntegral (const MyIntegral & dummy) inline
Broken copy constructor.
   {
    BrokenCopy::broken_copy("MyIntegral");
   }
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
knot() [1/2]
double MyIntegral::knot (const unsigned & i, const unsigned & j) const inline virtual
Return coordinate s[j] (j=0) of integration point i –.
Implements oomph::Integral.
   {
    double dx=1.0/double(N_knot);
    return ((0.5+double(i)))*dx;
   }
References i.
knot() [2/2]
double MyIntegral::knot (const unsigned & i, const unsigned & j) const inline virtual
Return coordinate s[j] (j=0) of integration point i –.
Implements oomph::Integral.
   {
    double dx=1.0/double(N_knot);
    return ((0.5+double(i)))*dx;
   }
References i.
nweight() [1/2]
unsigned MyIntegral::nweight () const inline virtual
Number of integration points of the scheme.
Implements oomph::Integral.
 {return N_knot;}
nweight() [2/2]
unsigned MyIntegral::nweight () const inline virtual
Number of integration points of the scheme.
Implements oomph::Integral.
 {return N_knot;}
operator=()
void MyIntegral::operator= (const MyIntegral &) inline
Broken assignment operator.
   {
    BrokenCopy::broken_assign("MyIntegral");
   }
References oomph::BrokenCopy::broken_assign().
weight() [1/2]
double MyIntegral::weight (const unsigned & i) const inline virtual
Return weight of integration point i.
Implements oomph::Integral.
   {
    //return 2.0/double(N_knot);
    return 1.0/double(N_knot);
   }
weight() [2/2]
double MyIntegral::weight (const unsigned & i) const inline virtual
Return weight of integration point i.
Implements oomph::Integral.
   {
    //return 2.0/double(N_knot);
    return 1.0/double(N_knot);
   }
Member Data Documentation
N_knot
unsigned MyIntegral::N_knot private
Number of integration points.
The documentation for this class was generated from the following files:
stefan_boltzmann.cc
stefan_boltzmann_melt.cc