MercuryDPM: fsi_collapsible_channel.cc File Reference
fsi_collapsible_channel.cc File Reference
#include <iostream>
#include "generic.h"
#include "navier_stokes.h"
#include "beam.h"
#include "meshes/one_d_lagrangian_mesh.h"
#include "meshes/collapsible_channel_mesh.h"
Classes
class UndeformedWall
class FSICollapsibleChannelProblem< ELEMENT >
Problem class.
Namespaces
BL_Squash
Global_Physical_Variables
Global variables.
Functions
double BL_Squash::squash_fct (const double &s)
void Global_Physical_Variables::prescribed_traction (const double &t, const Vector< double > &x, const Vector< double > &n, Vector< double > &traction)
Traction applied on the fluid at the left (inflow) boundary.
void Global_Physical_Variables::load (const Vector< double > &xi, const Vector< double > &x, const Vector< double > &N, Vector< double > &load)
Load function: Apply a constant external pressure to the beam.
int main (int argc, char *argv[])
Variables
double Global_Physical_Variables::P_up =0.0
Default pressure on the left boundary.
Function Documentation
main()
int main (int argc , char * argv[])
Driver code for a collapsible channel problem with FSI. Presence of command line arguments indicates validation run with coarse resolution and small number of timesteps.
 {
  // Store command line arguments
  CommandLineArgs::setup(argc,argv);
  // Reduction in resolution for validation run?
  unsigned coarsening_factor=1;
  if (CommandLineArgs::Argc>1)
   {
    coarsening_factor=4;
   }
  // Number of elements in the domain
  unsigned nup=20/coarsening_factor;
  unsigned ncollapsible=40/coarsening_factor;
  unsigned ndown=40/coarsening_factor;
  unsigned ny=16/coarsening_factor;
  // Length of the domain
  double lup=5.0;
  double lcollapsible=10.0;
  double ldown=10.0;
  double ly=1.0;
  // Set external pressure (on the wall stiffness scale).
  Global_Physical_Variables::P_ext = 1.0e-1;
  // Pressure on the left boundary: This is consistent with steady
  // Poiseuille flow
  Global_Physical_Variables::P_up=12.0*(lup+lcollapsible+ldown);
 #ifdef MACRO_ELEMENT_NODE_UPDATE
 #ifdef TAYLOR_HOOD
  // Build the problem with QTaylorHoodElements
  FSICollapsibleChannelProblem
   <MacroElementNodeUpdateElement<QTaylorHoodElement<2> > >
   problem(nup, ncollapsible, ndown, ny,
           lup, lcollapsible, ldown, ly);
 #else
  // Build the problem with QCrouzeixRaviartElements
  FSICollapsibleChannelProblem
   <MacroElementNodeUpdateElement<QCrouzeixRaviartElement<2> > >
   problem(nup, ncollapsible, ndown, ny,
           lup, lcollapsible, ldown, ly);
 #endif
 #else
 #ifdef TAYLOR_HOOD
  // Build the problem with QCrouzeixRaviartElements
  FSICollapsibleChannelProblem
   <AlgebraicElement<QTaylorHoodElement<2> > >
   problem(nup, ncollapsible, ndown, ny,
           lup, lcollapsible, ldown, ly);
 #else
  // Build the problem with QCrouzeixRaviartElements
  FSICollapsibleChannelProblem
   <AlgebraicElement<QCrouzeixRaviartElement<2> > >
   problem(nup, ncollapsible, ndown, ny,
           lup, lcollapsible, ldown, ly);
 #endif
 #endif
  // Timestep. Note: Preliminary runs indicate that the period of
  // the oscillation is about 1 so this gives us 40 steps per period.
  double dt=1.0/40.0;
  // Initial time for the simulation
  double t_min=0.0;
  // Maximum time for simulation
  double t_max=3.5;
  // Initialise timestep
  problem.time_pt()->time()=t_min;
  problem.initialise_dt(dt);
  // Apply initial condition
  problem.set_initial_condition();
  //Set output directory
  DocInfo doc_info;
  doc_info.set_directory("RESLT");
  // Open a trace file
  ofstream trace_file;
  char filename[100];
  sprintf(filename,"%s/trace.dat",doc_info.directory().c_str());
  trace_file.open(filename);
  // Output the initial solution
  problem.doc_solution(doc_info, trace_file);
  // Increment step number
  doc_info.number()++;
  // Find number of timesteps (reduced for validation)
  unsigned nstep = unsigned((t_max-t_min)/dt);
  if (CommandLineArgs::Argc>1)
   {
    nstep=3;
   }
  // Timestepping loop
  for (unsigned istep=0;istep<nstep;istep++)
   {
    // Solve the problem
    problem.unsteady_newton_solve(dt);
    // Outpt the solution
    problem.doc_solution(doc_info, trace_file);
    // Step number
    doc_info.number()++;
   }
  // Close trace file.
  trace_file.close();
 }//end of main
References oomph::CommandLineArgs::Argc, oomph::DocInfo::directory(), MergeRestartFiles::filename, Mesh_Parameters::ly, oomph::DocInfo::number(), Mesh_Parameters::ny, Global_Physical_Variables::P_ext, Global_Physical_Variables::P_up, problem, oomph::DocInfo::set_directory(), and Flag_definition::setup().