MercuryDPM: RectangleWithHoleDomain Class Reference
RectangleWithHoleDomain Class Reference
Rectangular domain with circular whole.
Public Member Functions
double centre_x ()
double centre_y ()
RectangleWithHoleDomain (GeomObject *cylinder_pt, const double &length, const double &height)
~RectangleWithHoleDomain ()
Destructor: Empty; cleanup done in base class.
void linear_interpolate (Vector< double > left, Vector< double > right, const double &s, Vector< double > &f)
void macro_element_boundary (const unsigned &time, const unsigned &m, const unsigned &direction, const Vector< double > &s, Vector< double > &f)
double centre_x ()
double centre_y ()
RectangleWithHoleDomain (GeomObject *cylinder_pt, const double &length, const double &height)
~RectangleWithHoleDomain ()
Destructor: Empty; cleanup done in base class.
void linear_interpolate (Vector< double > left, Vector< double > right, const double &s, Vector< double > &f)
void macro_element_boundary (const unsigned &time, const unsigned &m, const unsigned &direction, const Vector< double > &s, Vector< double > &f)
GeomObject *const & cylinder_pt ()
RectangleWithHoleDomain (GeomObject *cylinder_pt, const double &length, const double &height)
~RectangleWithHoleDomain ()
Destructor: Empty; cleanup done in base class.
void linear_interpolate (Vector< double > left, Vector< double > right, const double &s, Vector< double > &f)
void macro_element_boundary (const unsigned &time, const unsigned &m, const unsigned &direction, const Vector< double > &s, Vector< double > &f)
Public Member Functions inherited from oomph::Domain
Domain ()
Constructor.
Domain (const Domain &)=delete
Broken copy constructor.
void operator= (const Domain &)=delete
Broken assignment operator.
virtual ~Domain ()
MacroElement * macro_element_pt (const unsigned &i)
Access to i-th macro element.
unsigned nmacro_element ()
Number of macro elements in domain.
void output (const std::string &filename, const unsigned &nplot)
Output macro elements.
void output (std::ostream &outfile, const unsigned &nplot)
Output macro elements.
virtual void macro_element_boundary (const double &t, const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
void macro_element_boundary (const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
void output_macro_element_boundaries (const std::string &filename, const unsigned &nplot)
Output all macro element boundaries as tecplot zones.
void output_macro_element_boundaries (std::ostream &outfile, const unsigned &nplot)
Output all macro element boundaries as tecplot zones.
virtual void dmacro_element_boundary (const unsigned &t, const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
virtual void dmacro_element_boundary (const double &t, const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
void dmacro_element_boundary (const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
virtual void d2macro_element_boundary (const unsigned &t, const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
virtual void d2macro_element_boundary (const double &t, const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
void d2macro_element_boundary (const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
Private Attributes
Vector< double > Lower_left
Lower left corner of rectangle.
Vector< double > Lower_right
Lower right corner of rectangle.
Vector< double > Lower_mid_left
Where the "radial" line from circle meets lower boundary on left.
Vector< double > Lower_mid_right
Where the "radial" line from circle meets lower boundary on right.
Vector< double > Upper_left
Upper left corner of rectangle.
Vector< double > Upper_right
Upper right corner of rectangle.
Vector< double > Upper_mid_left
Where the "radial" line from circle meets upper boundary on left.
Vector< double > Upper_mid_right
Where the "radial" line from circle meets upper boundary on right.
Vector< double > Upper_1
Coordinate of internal point in the boundaries of the domain.
Vector< double > Upper_2
Coordinate of internal point in the boundaries of the domain.
Vector< double > Upper_3
Coordinate of internal point in the boundaries of the domain.
Vector< double > Lower_1
Coordinate of internal point in the boundaries of the domain.
Vector< double > Lower_2
Coordinate of internal point in the boundaries of the domain.
Vector< double > Lower_3
Coordinate of internal point in the boundaries of the domain.
double Centre_x
x-coordinate of circle centre
double Centre_y
y-coordinate of circle centre
GeomObject * Cylinder_pt
Pointer to geometric object that represents the central cylinder.
Additional Inherited Members
Protected Attributes inherited from oomph::Domain
Vector< MacroElement * > Macro_element_pt
Vector of pointers to macro elements.
Detailed Description
Rectangular domain with circular whole.
///////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////
Constructor & Destructor Documentation
RectangleWithHoleDomain() [1/3]
RectangleWithHoleDomain::RectangleWithHoleDomain (GeomObject * cylinder_pt, const double & length, const double & height) inline
Constructor, Pass pointer to geometric object that represents the cylinder, the length and height of the domain. The GeomObject must be parametrised such that \(\zeta \in [0,2\pi]\) sweeps around the circumference in anticlockwise direction.
                                                                      :
   Cylinder_pt(cylinder_pt)
   {
    Centre_x = static_cast<GeneralEllipse*>(cylinder_pt)->centre_x();
    Centre_y = static_cast<GeneralEllipse*>(cylinder_pt)->centre_y();
    double lower_wall = -0.5*height;
    double upper_wall = 0.5*height;
    //Vertices of rectangle
    Lower_left.resize(2);
    Lower_left[0] = 0.0;
    Lower_left[1] = lower_wall;
    Upper_left.resize(2);
    Upper_left[0] = 0.0;
    Upper_left[1] = upper_wall;
    Lower_right.resize(2);
    Lower_right[0] = length;
    Lower_right[1] = lower_wall;
    Upper_right.resize(2);
    Upper_right[0] = length;
    Upper_right[1] = upper_wall;
    double left_cylinder_split = 3.5;
    double right_cylinder_split = 5.5;
    // Coordinates of points where the "radial" lines from central
    // cylinder meet the upper and lower boundaries
    Lower_mid_left.resize(2);
    Lower_mid_left[0] = left_cylinder_split;
    Lower_mid_left[1] = lower_wall;
    Upper_mid_left.resize(2);
    Upper_mid_left[0] = left_cylinder_split;
    Upper_mid_left[1] = upper_wall;
    Lower_mid_right.resize(2);
    Lower_mid_right[0] = right_cylinder_split;
    Lower_mid_right[1] = lower_wall;
    Upper_mid_right.resize(2);
    Upper_mid_right[0] = right_cylinder_split;
    Upper_mid_right[1] = upper_wall;
    // Coordinates of internal points for creation of macro elements
    double help = (length - right_cylinder_split)/4.;
    Upper_1.resize(2);
    Upper_1[0] = right_cylinder_split + help;
    Upper_1[1] = upper_wall;
    Upper_2.resize(2);
    Upper_2[0] = right_cylinder_split + 2.*help;
    Upper_2[1] = upper_wall;
    Upper_3.resize(2);
    Upper_3[0] = right_cylinder_split + 3.*help;
    Upper_3[1] = upper_wall;
    Lower_1.resize(2);
    Lower_1[0] = right_cylinder_split + help;
    Lower_1[1] = lower_wall;
    Lower_2.resize(2);
    Lower_2[0] = right_cylinder_split + 2.*help;
    Lower_2[1] = lower_wall;
    Lower_3.resize(2);
    Lower_3[0] = right_cylinder_split + 3.*help;
    Lower_3[1] = lower_wall;
    //There are nine macro elements
    Macro_element_pt.resize(9);
    // Build the 2D macro elements
    for (unsigned i=0;i<9;i++)
     {Macro_element_pt[i]= new QMacroElement<2>(this,i);}
   }
References Global_Parameters::Centre_x, Global_Parameters::Centre_y, Global_Physical_Variables::height(), compute_granudrum_aor::help, and i.
~RectangleWithHoleDomain() [1/3]
RectangleWithHoleDomain::~RectangleWithHoleDomain () inline
Destructor: Empty; cleanup done in base class.
 {}
RectangleWithHoleDomain() [2/3]
RectangleWithHoleDomain::RectangleWithHoleDomain (GeomObject * cylinder_pt, const double & length, const double & height) inline
Constructor, Pass pointer to geometric object that represents the cylinder, the length and height of the domain. The GeomObject must be parametrised such that \(\zeta \in [0,2\pi]\) sweeps around the circumference in anticlockwise direction.
                                                                      :
   Cylinder_pt(cylinder_pt)
   {
    Centre_x = static_cast<GeneralEllipse*>(cylinder_pt)->centre_x();
    Centre_y = static_cast<GeneralEllipse*>(cylinder_pt)->centre_y();
    double lower_wall = -0.5*height;
    double upper_wall = 0.5*height;
    //Vertices of rectangle
    Lower_left.resize(2);
    Lower_left[0] = 0.0;
    Lower_left[1] = lower_wall;
    Upper_left.resize(2);
    Upper_left[0] = 0.0;
    Upper_left[1] = upper_wall;
    Lower_right.resize(2);
    Lower_right[0] = length;
    Lower_right[1] = lower_wall;
    Upper_right.resize(2);
    Upper_right[0] = length;
    Upper_right[1] = upper_wall;
    double left_cylinder_split = 3.5;
    double right_cylinder_split = 5.5;
    // Coordinates of points where the "radial" lines from central
    // cylinder meet the upper and lower boundaries
    Lower_mid_left.resize(2);
    Lower_mid_left[0] = left_cylinder_split;
    Lower_mid_left[1] = lower_wall;
    Upper_mid_left.resize(2);
    Upper_mid_left[0] = left_cylinder_split;
    Upper_mid_left[1] = upper_wall;
    Lower_mid_right.resize(2);
    Lower_mid_right[0] = right_cylinder_split;
    Lower_mid_right[1] = lower_wall;
    Upper_mid_right.resize(2);
    Upper_mid_right[0] = right_cylinder_split;
    Upper_mid_right[1] = upper_wall;
    // Coordinates of internal points for creation of macro elements
    double help = (length - right_cylinder_split)/4.;
    Upper_1.resize(2);
    Upper_1[0] = right_cylinder_split + help;
    Upper_1[1] = upper_wall;
    Upper_2.resize(2);
    Upper_2[0] = right_cylinder_split + 2.*help;
    Upper_2[1] = upper_wall;
    Upper_3.resize(2);
    Upper_3[0] = right_cylinder_split + 3.*help;
    Upper_3[1] = upper_wall;
    Lower_1.resize(2);
    Lower_1[0] = right_cylinder_split + help;
    Lower_1[1] = lower_wall;
    Lower_2.resize(2);
    Lower_2[0] = right_cylinder_split + 2.*help;
    Lower_2[1] = lower_wall;
    Lower_3.resize(2);
    Lower_3[0] = right_cylinder_split + 3.*help;
    Lower_3[1] = lower_wall;
    //There are nine macro elements
    Macro_element_pt.resize(9);
    // Build the 2D macro elements
    for (unsigned i=0;i<9;i++)
     {Macro_element_pt[i]= new QMacroElement<2>(this,i);}
   }
References Global_Parameters::Centre_x, Global_Parameters::Centre_y, Global_Physical_Variables::height(), compute_granudrum_aor::help, and i.
~RectangleWithHoleDomain() [2/3]
RectangleWithHoleDomain::~RectangleWithHoleDomain () inline
Destructor: Empty; cleanup done in base class.
 {}
RectangleWithHoleDomain() [3/3]
RectangleWithHoleDomain::RectangleWithHoleDomain (GeomObject * cylinder_pt, const double & length, const double & height) inline
Constructor, Pass pointer to geometric object that represents the cylinder, the length and height of the domain. The GeomObject must be parametrised such that \(\zeta \in [0,2\pi]\) sweeps around the circumference in anticlockwise direction.
                                                                      :
   Cylinder_pt(cylinder_pt)
   {
    //Vertices of rectangle
    Lower_left.resize(2);
    Lower_left[0] = 0.0;
    Lower_left[1] = 0.0;
    Upper_left.resize(2);
    Upper_left[0] = 0.0;
    Upper_left[1] = height;
    Lower_right.resize(2);
    Lower_right[0] = length;
    Lower_right[1] = 0.0;
    Upper_right.resize(2);
    Upper_right[0] = length;
    Upper_right[1] = height;
    // Coordinates of points where the "radial" lines from central
    // cylinder meet the upper and lower boundaries
    Lower_mid_left.resize(2);
    Lower_mid_left[0] = 0.0;
    Lower_mid_left[1] = 0.0;
    Upper_mid_left.resize(2);
    Upper_mid_left[0] = 0.0;
    Upper_mid_left[1] = height;
    Lower_mid_right.resize(2);
    Lower_mid_right[0] = height;
    Lower_mid_right[1] = 0.0;
    Upper_mid_right.resize(2);
    Upper_mid_right[0] = height;
    Upper_mid_right[1] = height;
    // Coordinates of internal points for creation of macro elements
    double help = (length - height)/4.;
    Upper_1.resize(2);
    Upper_1[0] = height + help;
    Upper_1[1] = height;
    Upper_2.resize(2);
    Upper_2[0] = height + 2.*help;
    Upper_2[1] = height;
    Upper_3.resize(2);
    Upper_3[0] = height + 3.*help;
    Upper_3[1] = height;
    Lower_1.resize(2);
    Lower_1[0] = height + help;
    Lower_1[1] = 0.;
    Lower_2.resize(2);
    Lower_2[0] = height + 2.*help;
    Lower_2[1] = 0.;
    Lower_3.resize(2);
    Lower_3[0] = height + 3.*help;
    Lower_3[1] = 0.;
    //There are eight macro elements
    Macro_element_pt.resize(8);
    // Build the 2D macro elements
    for (unsigned i=0;i<8;i++)
     {Macro_element_pt[i]= new QMacroElement<2>(this,i);}
   }
References Global_Physical_Variables::height(), compute_granudrum_aor::help, and i.
~RectangleWithHoleDomain() [3/3]
RectangleWithHoleDomain::~RectangleWithHoleDomain () inline
Destructor: Empty; cleanup done in base class.
 {}
Member Function Documentation
centre_x() [1/2]
double RectangleWithHoleDomain::centre_x () inline
 {return Centre_x;}
References Global_Parameters::Centre_x.
centre_x() [2/2]
double RectangleWithHoleDomain::centre_x () inline
 {return Centre_x;}
References Global_Parameters::Centre_x.
centre_y() [1/2]
double RectangleWithHoleDomain::centre_y () inline
 {return Centre_y;}
References Global_Parameters::Centre_y.
centre_y() [2/2]
double RectangleWithHoleDomain::centre_y () inline
 {return Centre_y;}
References Global_Parameters::Centre_y.
cylinder_pt()
GeomObject* const& RectangleWithHoleDomain::cylinder_pt () inline
 {return Cylinder_pt;}
References GlobalParameters::Cylinder_pt.
linear_interpolate() [1/3]
void RectangleWithHoleDomain::linear_interpolate (Vector< double > left, Vector< double > right, const double & s, Vector< double > & f) inline
Helper function to interpolate linearly between the "right" and "left" points; \(s \in [-1,1] \)
   {
    for(unsigned i=0;i<2;i++)
     {
      f[i] = left[i] + (right[i] - left[i])*0.5*(s+1.0);
     }
   }
References f(), i, and s.
linear_interpolate() [2/3]
void RectangleWithHoleDomain::linear_interpolate (Vector< double > left, Vector< double > right, const double & s, Vector< double > & f) inline
Helper function to interpolate linearly between the "right" and "left" points; \(s \in [-1,1] \)
   {
    for(unsigned i=0;i<2;i++)
     {
      f[i] = left[i] + (right[i] - left[i])*0.5*(s+1.0);
     }
   }
References f(), i, and s.
linear_interpolate() [3/3]
void RectangleWithHoleDomain::linear_interpolate (Vector< double > left, Vector< double > right, const double & s, Vector< double > & f) inline
Helper function to interpolate linearly between the "right" and "left" points; \(s \in [-1,1] \)
   {
    for(unsigned i=0;i<2;i++)
     {
      f[i] = left[i] + (right[i] - left[i])*0.5*(s+1.0);
     }
   }
References f(), i, and s.
macro_element_boundary() [1/3]
void RectangleWithHoleDomain::macro_element_boundary (const unsigned & time, const unsigned & m, const unsigned & direction, const Vector< double > & s, Vector< double > & f) inline virtual
Parametrisation of macro element boundaries: f(s) is the position vector to macro-element m's boundary in the specified direction [N/S/E/W] at the specfied discrete time level (time=0: present; time>0: previous)
Implements oomph::Domain.
  {
 #ifdef WARN_ABOUT_SUBTLY_CHANGED_OOMPH_INTERFACES
    // Warn about time argument being moved to the front
    OomphLibWarning(
     "Order of function arguments has changed between versions 0.8 and 0.85",
     "RectangleWithHoleDomain::macro_element_boundary(...)",
     OOMPH_EXCEPTION_LOCATION);
 #endif
   // Lagrangian coordinate along surface of cylinder
   Vector<double> xi(1);
   // Point on circle
   Vector<double> point_on_circle(2);
   //Switch on the macro element
   switch(m)
    {
     //Macro element 0, is is immediately left of the cylinder
    case 0:
     switch(direction)
      {
      case N:
       xi[0] = 3.0*atan(1.0);
       Cylinder_pt->position(time,xi,point_on_circle);
       linear_interpolate(Upper_mid_left,point_on_circle,s[0],f);
       break;
      case S:
       xi[0] = -3.0*atan(1.0);
       Cylinder_pt->position(time,xi,point_on_circle);
       linear_interpolate(Lower_mid_left,point_on_circle,s[0],f);
       break;
      case W:
        linear_interpolate(Lower_mid_left,Upper_mid_left,s[0],f);
       break;
      case E:
       xi[0] = 5.0*atan(1.0) - 2.0*atan(1.0)*0.5*(1.0+s[0]);
       Cylinder_pt->position(time,xi,f);
       break;
      default:
       std::ostringstream error_stream;
       error_stream << "Direction is incorrect:  " << direction << std::endl;
       throw OomphLibError(error_stream.str(),
                           OOMPH_CURRENT_FUNCTION,
                           OOMPH_EXCEPTION_LOCATION);
      }
     break;
    //Macro element 1, is immediately above the cylinder
    case 1:
     switch(direction)
      {
      case N:
        linear_interpolate(Upper_mid_left,Upper_mid_right,s[0],f);
       break;
      case S:
       xi[0] = 3.0*atan(1.0) - 2.0*atan(1.0)*0.5*(1.0+s[0]);
       Cylinder_pt->position(time,xi,f);
       break;
      case W:
       xi[0] = 3.0*atan(1.0);
       Cylinder_pt->position(time,xi,point_on_circle);
       linear_interpolate(point_on_circle,Upper_mid_left,s[0],f);
       break;
      case E:
       xi[0] = 1.0*atan(1.0);
       Cylinder_pt->position(time,xi,point_on_circle);
       linear_interpolate(point_on_circle,Upper_mid_right,s[0],f);
       break;
      default:
       std::ostringstream error_stream;
       error_stream << "Direction is incorrect:  " << direction << std::endl;
       throw OomphLibError(error_stream.str(),
                           OOMPH_CURRENT_FUNCTION,
                           OOMPH_EXCEPTION_LOCATION);
      }
     break;
     //Macro element 2, is immediately right of the cylinder
    case 2:
     switch(direction)
      {
      case N:
       xi[0] = 1.0*atan(1.0);
       Cylinder_pt->position(time,xi,point_on_circle);
       linear_interpolate(point_on_circle,Upper_mid_right,s[0],f);
       break;
      case S:
       xi[0] = -1.0*atan(1.0);
       Cylinder_pt->position(time,xi,point_on_circle);
       linear_interpolate(point_on_circle,Lower_mid_right,s[0],f);
       break;
      case W:
       xi[0] = -atan(1.0) + 2.0*atan(1.0)*0.5*(1.0+s[0]);
       Cylinder_pt->position(time,xi,f);
       break;
      case E:
        linear_interpolate(Lower_mid_right,Upper_mid_right,s[0],f);
       break;
      default:
       std::ostringstream error_stream;
       error_stream << "Direction is incorrect:  " << direction << std::endl;
       throw OomphLibError(error_stream.str(),
                           OOMPH_CURRENT_FUNCTION,
                           OOMPH_EXCEPTION_LOCATION);
      }
     break;
     //Macro element 3, is immediately below cylinder
    case 3:
     switch(direction)
      {
      case N:
       xi[0] = -3.0*atan(1.0) + 2.0*atan(1.0)*0.5*(1.0+s[0]);
       Cylinder_pt->position(time,xi,f);
       break;
      case S:
        linear_interpolate(Lower_mid_left,Lower_mid_right,s[0],f);
       break;
      case W:
       xi[0] = -3.0*atan(1.0);
       Cylinder_pt->position(time,xi,point_on_circle);
       linear_interpolate(Lower_mid_left,point_on_circle,s[0],f);
       break;
      case E:
       xi[0] = -1.0*atan(1.0);
       Cylinder_pt->position(time,xi,point_on_circle);
       linear_interpolate(Lower_mid_right,point_on_circle,s[0],f);
       break;
      default:
       std::ostringstream error_stream;
       error_stream << "Direction is incorrect:  " << direction << std::endl;
       throw OomphLibError(error_stream.str(),
                           OOMPH_CURRENT_FUNCTION,
                           OOMPH_EXCEPTION_LOCATION);
      }
     break;
     //Macro element 4, is right hand block 1
    case 4:
     switch(direction)
      {
      case N:
        linear_interpolate(Upper_mid_right,Upper_1,s[0],f);
       break;
      case S:
        linear_interpolate(Lower_mid_right,Lower_1,s[0],f);
       break;
      case W:
        linear_interpolate(Lower_mid_right,Upper_mid_right,s[0],f);
       break;
      case E:
        linear_interpolate(Lower_1,Upper_1,s[0],f);
       break;
      default:
       std::ostringstream error_stream;
       error_stream << "Direction is incorrect:  " << direction << std::endl;
       throw OomphLibError(error_stream.str(),
                           OOMPH_CURRENT_FUNCTION,
                           OOMPH_EXCEPTION_LOCATION);
      }
     break;
     //Macro element 5, is right hand block 2
    case 5:
     switch(direction)
      {
      case N:
        linear_interpolate(Upper_1,Upper_2,s[0],f);
       break;
      case S:
        linear_interpolate(Lower_1,Lower_2,s[0],f);
       break;
      case W:
        linear_interpolate(Lower_1,Upper_1,s[0],f);
       break;
      case E:
        linear_interpolate(Lower_2,Upper_2,s[0],f);
       break;
      default:
       std::ostringstream error_stream;
       error_stream << "Direction is incorrect:  " << direction << std::endl;
       throw OomphLibError(error_stream.str(),
                           OOMPH_CURRENT_FUNCTION,
                           OOMPH_EXCEPTION_LOCATION);
      }
     break;
     //Macro element 6, is right hand block 3
    case 6:
     switch(direction)
      {
      case N:
        linear_interpolate(Upper_2,Upper_3,s[0],f);
       break;
      case S:
        linear_interpolate(Lower_2,Lower_3,s[0],f);
       break;
      case W:
        linear_interpolate(Lower_2,Upper_2,s[0],f);
       break;
      case E:
        linear_interpolate(Lower_3,Upper_3,s[0],f);
       break;
      default:
       std::ostringstream error_stream;
       error_stream << "Direction is incorrect:  " << direction << std::endl;
       throw OomphLibError(error_stream.str(),
                           OOMPH_CURRENT_FUNCTION,
                           OOMPH_EXCEPTION_LOCATION);
      }
     break;
     //Macro element 7, is right hand block 4
    case 7:
     switch(direction)
      {
      case N:
        linear_interpolate(Upper_3,Upper_right,s[0],f);
       break;
      case S:
        linear_interpolate(Lower_3,Lower_right,s[0],f);
       break;
      case W:
        linear_interpolate(Lower_3,Upper_3,s[0],f);
       break;
      case E:
        linear_interpolate(Lower_right,Upper_right,s[0],f);
       break;
      default:
       std::ostringstream error_stream;
       error_stream << "Direction is incorrect:  " << direction << std::endl;
       throw OomphLibError(error_stream.str(),
                           OOMPH_CURRENT_FUNCTION,
                           OOMPH_EXCEPTION_LOCATION);
      }
     break;
     //Macro element 8, is inlet region
    case 8:
     switch(direction)
      {
      case N:
       linear_interpolate(Upper_left,Upper_mid_left,s[0],f);
       break;
      case S:
       linear_interpolate(Lower_left,Lower_mid_left,s[0],f);
       break;
      case W:
       linear_interpolate(Lower_left,Upper_left,s[0],f);
       break;
      case E:
       linear_interpolate(Lower_mid_left,Upper_mid_left,s[0],f);
       break;
      default:
       std::ostringstream error_stream;
       error_stream << "Direction is incorrect:  " << direction << std::endl;
       throw OomphLibError(error_stream.str(),
                           OOMPH_CURRENT_FUNCTION,
                           OOMPH_EXCEPTION_LOCATION);
      }
     break;
    default:
     std::ostringstream error_stream;
     error_stream << "Wrong macro element number" << m << std::endl;
     throw OomphLibError(error_stream.str(),
                         OOMPH_CURRENT_FUNCTION,
                         OOMPH_EXCEPTION_LOCATION);
    }
  }
References Eigen::bfloat16_impl::atan(), GlobalParameters::Cylinder_pt, oomph::QuadTreeNames::E, f(), m, oomph::QuadTreeNames::N, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, OscillatingCylinder::position(), s, oomph::QuadTreeNames::S, and oomph::QuadTreeNames::W.
macro_element_boundary() [2/3]
void RectangleWithHoleDomain::macro_element_boundary (const unsigned & time, const unsigned & m, const unsigned & direction, const Vector< double > & s, Vector< double > & f) inline virtual
Parametrisation of macro element boundaries: f(s) is the position vector to macro-element m's boundary in the specified direction [N/S/E/W] at the specfied discrete time level (time=0: present; time>0: previous)
Implements oomph::Domain.
  {
 #ifdef WARN_ABOUT_SUBTLY_CHANGED_OOMPH_INTERFACES
    // Warn about time argument being moved to the front
    OomphLibWarning(
     "Order of function arguments has changed between versions 0.8 and 0.85",
     "RectangleWithHoleDomain::macro_element_boundary(...)",
     OOMPH_EXCEPTION_LOCATION);
 #endif
   // Lagrangian coordinate along surface of cylinder
   Vector<double> xi(1);
   // Point on circle
   Vector<double> point_on_circle(2);
   //Switch on the macro element
   switch(m)
    {
     //Macro element 0, is is immediately left of the cylinder
    case 0:
     switch(direction)
      {
      case N:
       xi[0] = 3.0*atan(1.0);
       Cylinder_pt->position(time,xi,point_on_circle);
       linear_interpolate(Upper_mid_left,point_on_circle,s[0],f);
       break;
      case S:
       xi[0] = -3.0*atan(1.0);
       Cylinder_pt->position(time,xi,point_on_circle);
       linear_interpolate(Lower_mid_left,point_on_circle,s[0],f);
       break;
      case W:
        linear_interpolate(Lower_mid_left,Upper_mid_left,s[0],f);
       break;
      case E:
       xi[0] = 5.0*atan(1.0) - 2.0*atan(1.0)*0.5*(1.0+s[0]);
       Cylinder_pt->position(time,xi,f);
       break;
      default:
       std::ostringstream error_stream;
       error_stream << "Direction is incorrect:  " << direction << std::endl;
       throw OomphLibError(error_stream.str(),
                           OOMPH_CURRENT_FUNCTION,
                           OOMPH_EXCEPTION_LOCATION);
      }
     break;
    //Macro element 1, is immediately above the cylinder
    case 1:
     switch(direction)
      {
      case N:
        linear_interpolate(Upper_mid_left,Upper_mid_right,s[0],f);
       break;
      case S:
       xi[0] = 3.0*atan(1.0) - 2.0*atan(1.0)*0.5*(1.0+s[0]);
       Cylinder_pt->position(time,xi,f);
       break;
      case W:
       xi[0] = 3.0*atan(1.0);
       Cylinder_pt->position(time,xi,point_on_circle);
       linear_interpolate(point_on_circle,Upper_mid_left,s[0],f);
       break;
      case E:
       xi[0] = 1.0*atan(1.0);
       Cylinder_pt->position(time,xi,point_on_circle);
       linear_interpolate(point_on_circle,Upper_mid_right,s[0],f);
       break;
      default:
       std::ostringstream error_stream;
       error_stream << "Direction is incorrect:  " << direction << std::endl;
       throw OomphLibError(error_stream.str(),
                           OOMPH_CURRENT_FUNCTION,
                           OOMPH_EXCEPTION_LOCATION);
      }
     break;
     //Macro element 2, is immediately right of the cylinder
    case 2:
     switch(direction)
      {
      case N:
       xi[0] = 1.0*atan(1.0);
       Cylinder_pt->position(time,xi,point_on_circle);
       linear_interpolate(point_on_circle,Upper_mid_right,s[0],f);
       break;
      case S:
       xi[0] = -1.0*atan(1.0);
       Cylinder_pt->position(time,xi,point_on_circle);
       linear_interpolate(point_on_circle,Lower_mid_right,s[0],f);
       break;
      case W:
       xi[0] = -atan(1.0) + 2.0*atan(1.0)*0.5*(1.0+s[0]);
       Cylinder_pt->position(time,xi,f);
       break;
      case E:
        linear_interpolate(Lower_mid_right,Upper_mid_right,s[0],f);
       break;
      default:
       std::ostringstream error_stream;
       error_stream << "Direction is incorrect:  " << direction << std::endl;
       throw OomphLibError(error_stream.str(),
                           OOMPH_CURRENT_FUNCTION,
                           OOMPH_EXCEPTION_LOCATION);
      }
     break;
     //Macro element 3, is immediately below cylinder
    case 3:
     switch(direction)
      {
      case N:
       xi[0] = -3.0*atan(1.0) + 2.0*atan(1.0)*0.5*(1.0+s[0]);
       Cylinder_pt->position(time,xi,f);
       break;
      case S:
        linear_interpolate(Lower_mid_left,Lower_mid_right,s[0],f);
       break;
      case W:
       xi[0] = -3.0*atan(1.0);
       Cylinder_pt->position(time,xi,point_on_circle);
       linear_interpolate(Lower_mid_left,point_on_circle,s[0],f);
       break;
      case E:
       xi[0] = -1.0*atan(1.0);
       Cylinder_pt->position(time,xi,point_on_circle);
       linear_interpolate(Lower_mid_right,point_on_circle,s[0],f);
       break;
      default:
       std::ostringstream error_stream;
       error_stream << "Direction is incorrect:  " << direction << std::endl;
       throw OomphLibError(error_stream.str(),
                           OOMPH_CURRENT_FUNCTION,
                           OOMPH_EXCEPTION_LOCATION);
      }
     break;
     //Macro element 4, is right hand block 1
    case 4:
     switch(direction)
      {
      case N:
        linear_interpolate(Upper_mid_right,Upper_1,s[0],f);
       break;
      case S:
        linear_interpolate(Lower_mid_right,Lower_1,s[0],f);
       break;
      case W:
        linear_interpolate(Lower_mid_right,Upper_mid_right,s[0],f);
       break;
      case E:
        linear_interpolate(Lower_1,Upper_1,s[0],f);
       break;
      default:
       std::ostringstream error_stream;
       error_stream << "Direction is incorrect:  " << direction << std::endl;
       throw OomphLibError(error_stream.str(),
                           OOMPH_CURRENT_FUNCTION,
                           OOMPH_EXCEPTION_LOCATION);
      }
     break;
     //Macro element 5, is right hand block 2
    case 5:
     switch(direction)
      {
      case N:
        linear_interpolate(Upper_1,Upper_2,s[0],f);
       break;
      case S:
        linear_interpolate(Lower_1,Lower_2,s[0],f);
       break;
      case W:
        linear_interpolate(Lower_1,Upper_1,s[0],f);
       break;
      case E:
        linear_interpolate(Lower_2,Upper_2,s[0],f);
       break;
      default:
       std::ostringstream error_stream;
       error_stream << "Direction is incorrect:  " << direction << std::endl;
       throw OomphLibError(error_stream.str(),
                           OOMPH_CURRENT_FUNCTION,
                           OOMPH_EXCEPTION_LOCATION);
      }
     break;
     //Macro element 6, is right hand block 3
    case 6:
     switch(direction)
      {
      case N:
        linear_interpolate(Upper_2,Upper_3,s[0],f);
       break;
      case S:
        linear_interpolate(Lower_2,Lower_3,s[0],f);
       break;
      case W:
        linear_interpolate(Lower_2,Upper_2,s[0],f);
       break;
      case E:
        linear_interpolate(Lower_3,Upper_3,s[0],f);
       break;
      default:
       std::ostringstream error_stream;
       error_stream << "Direction is incorrect:  " << direction << std::endl;
       throw OomphLibError(error_stream.str(),
                           OOMPH_CURRENT_FUNCTION,
                           OOMPH_EXCEPTION_LOCATION);
      }
     break;
     //Macro element 7, is right hand block 4
    case 7:
     switch(direction)
      {
      case N:
        linear_interpolate(Upper_3,Upper_right,s[0],f);
       break;
      case S:
        linear_interpolate(Lower_3,Lower_right,s[0],f);
       break;
      case W:
        linear_interpolate(Lower_3,Upper_3,s[0],f);
       break;
      case E:
        linear_interpolate(Lower_right,Upper_right,s[0],f);
       break;
      default:
       std::ostringstream error_stream;
       error_stream << "Direction is incorrect:  " << direction << std::endl;
       throw OomphLibError(error_stream.str(),
                           OOMPH_CURRENT_FUNCTION,
                           OOMPH_EXCEPTION_LOCATION);
      }
     break;
     //Macro element 8, is inlet region
    case 8:
     switch(direction)
      {
      case N:
       linear_interpolate(Upper_left,Upper_mid_left,s[0],f);
       break;
      case S:
       linear_interpolate(Lower_left,Lower_mid_left,s[0],f);
       break;
      case W:
       linear_interpolate(Lower_left,Upper_left,s[0],f);
       break;
      case E:
       linear_interpolate(Lower_mid_left,Upper_mid_left,s[0],f);
       break;
      default:
       std::ostringstream error_stream;
       error_stream << "Direction is incorrect:  " << direction << std::endl;
       throw OomphLibError(error_stream.str(),
                           OOMPH_CURRENT_FUNCTION,
                           OOMPH_EXCEPTION_LOCATION);
      }
     break;
    default:
     std::ostringstream error_stream;
     error_stream << "Wrong macro element number" << m << std::endl;
     throw OomphLibError(error_stream.str(),
                         OOMPH_CURRENT_FUNCTION,
                         OOMPH_EXCEPTION_LOCATION);
    }
  }
References Eigen::bfloat16_impl::atan(), GlobalParameters::Cylinder_pt, oomph::QuadTreeNames::E, f(), m, oomph::QuadTreeNames::N, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, OscillatingCylinder::position(), s, oomph::QuadTreeNames::S, and oomph::QuadTreeNames::W.
macro_element_boundary() [3/3]
void RectangleWithHoleDomain::macro_element_boundary (const unsigned & time, const unsigned & m, const unsigned & direction, const Vector< double > & s, Vector< double > & f) inline virtual
Parametrisation of macro element boundaries: f(s) is the position vector to macro-element m's boundary in the specified direction [N/S/E/W] at the specfied discrete time level (time=0: present; time>0: previous)
Implements oomph::Domain.
  {
 #ifdef WARN_ABOUT_SUBTLY_CHANGED_OOMPH_INTERFACES
    // Warn about time argument being moved to the front
    OomphLibWarning(
     "Order of function arguments has changed between versions 0.8 and 0.85",
     "RectangleWithHoleDomain::macro_element_boundary(...)",
     OOMPH_EXCEPTION_LOCATION);
 #endif
   // Lagrangian coordinate along surface of cylinder
   Vector<double> xi(1);
   // Point on circle
   Vector<double> point_on_circle(2);
   //Switch on the macro element
   switch(m)
    {
     //Macro element 0, is is immediately left of the cylinder
    case 0:
     switch(direction)
      {
      case N:
       xi[0] = 3.0*atan(1.0);
       Cylinder_pt->position(time,xi,point_on_circle);
       linear_interpolate(Upper_mid_left,point_on_circle,s[0],f);
       break;
      case S:
       xi[0] = -3.0*atan(1.0);
       Cylinder_pt->position(time,xi,point_on_circle);
       linear_interpolate(Lower_mid_left,point_on_circle,s[0],f);
       break;
      case W:
        linear_interpolate(Lower_mid_left,Upper_mid_left,s[0],f);
       break;
      case E:
       xi[0] = 5.0*atan(1.0) - 2.0*atan(1.0)*0.5*(1.0+s[0]);
       Cylinder_pt->position(time,xi,f);
       break;
      default:
       std::ostringstream error_stream;
       error_stream << "Direction is incorrect:  " << direction << std::endl;
       throw OomphLibError(error_stream.str(),
                           OOMPH_CURRENT_FUNCTION,
                           OOMPH_EXCEPTION_LOCATION);
      }
     break;
    //Macro element 1, is immediately above the cylinder
    case 1:
     switch(direction)
      {
      case N:
        linear_interpolate(Upper_mid_left,Upper_mid_right,s[0],f);
       break;
      case S:
       xi[0] = 3.0*atan(1.0) - 2.0*atan(1.0)*0.5*(1.0+s[0]);
       Cylinder_pt->position(time,xi,f);
       break;
      case W:
       xi[0] = 3.0*atan(1.0);
       Cylinder_pt->position(time,xi,point_on_circle);
       linear_interpolate(point_on_circle,Upper_mid_left,s[0],f);
       break;
      case E:
       xi[0] = 1.0*atan(1.0);
       Cylinder_pt->position(time,xi,point_on_circle);
       linear_interpolate(point_on_circle,Upper_mid_right,s[0],f);
       break;
      default:
       std::ostringstream error_stream;
       error_stream << "Direction is incorrect:  " << direction << std::endl;
       throw OomphLibError(error_stream.str(),
                           OOMPH_CURRENT_FUNCTION,
                           OOMPH_EXCEPTION_LOCATION);
      }
     break;
     //Macro element 2, is immediately right of the cylinder
    case 2:
     switch(direction)
      {
      case N:
       xi[0] = 1.0*atan(1.0);
       Cylinder_pt->position(time,xi,point_on_circle);
       linear_interpolate(point_on_circle,Upper_mid_right,s[0],f);
       break;
      case S:
       xi[0] = -1.0*atan(1.0);
       Cylinder_pt->position(time,xi,point_on_circle);
       linear_interpolate(point_on_circle,Lower_mid_right,s[0],f);
       break;
      case W:
       xi[0] = -atan(1.0) + 2.0*atan(1.0)*0.5*(1.0+s[0]);
       Cylinder_pt->position(time,xi,f);
       break;
      case E:
        linear_interpolate(Lower_mid_right,Upper_mid_right,s[0],f);
       break;
      default:
       std::ostringstream error_stream;
       error_stream << "Direction is incorrect:  " << direction << std::endl;
       throw OomphLibError(error_stream.str(),
                           OOMPH_CURRENT_FUNCTION,
                           OOMPH_EXCEPTION_LOCATION);
      }
     break;
     //Macro element 3, is immediately below cylinder
    case 3:
     switch(direction)
      {
      case N:
       xi[0] = -3.0*atan(1.0) + 2.0*atan(1.0)*0.5*(1.0+s[0]);
       Cylinder_pt->position(time,xi,f);
       break;
      case S:
        linear_interpolate(Lower_mid_left,Lower_mid_right,s[0],f);
       break;
      case W:
       xi[0] = -3.0*atan(1.0);
       Cylinder_pt->position(time,xi,point_on_circle);
       linear_interpolate(Lower_mid_left,point_on_circle,s[0],f);
       break;
      case E:
       xi[0] = -1.0*atan(1.0);
       Cylinder_pt->position(time,xi,point_on_circle);
       linear_interpolate(Lower_mid_right,point_on_circle,s[0],f);
       break;
      default:
       std::ostringstream error_stream;
       error_stream << "Direction is incorrect:  " << direction << std::endl;
       throw OomphLibError(error_stream.str(),
                           OOMPH_CURRENT_FUNCTION,
                           OOMPH_EXCEPTION_LOCATION);
      }
     break;
     //Macro element 4, is right hand block 1
    case 4:
     switch(direction)
      {
      case N:
        linear_interpolate(Upper_mid_right,Upper_1,s[0],f);
       break;
      case S:
        linear_interpolate(Lower_mid_right,Lower_1,s[0],f);
       break;
      case W:
        linear_interpolate(Lower_mid_right,Upper_mid_right,s[0],f);
       break;
      case E:
        linear_interpolate(Lower_1,Upper_1,s[0],f);
       break;
      default:
       std::ostringstream error_stream;
       error_stream << "Direction is incorrect:  " << direction << std::endl;
       throw OomphLibError(error_stream.str(),
                           OOMPH_CURRENT_FUNCTION,
                           OOMPH_EXCEPTION_LOCATION);
      }
     break;
     //Macro element 5, is right hand block 2
    case 5:
     switch(direction)
      {
      case N:
        linear_interpolate(Upper_1,Upper_2,s[0],f);
       break;
      case S:
        linear_interpolate(Lower_1,Lower_2,s[0],f);
       break;
      case W:
        linear_interpolate(Lower_1,Upper_1,s[0],f);
       break;
      case E:
        linear_interpolate(Lower_2,Upper_2,s[0],f);
       break;
      default:
       std::ostringstream error_stream;
       error_stream << "Direction is incorrect:  " << direction << std::endl;
       throw OomphLibError(error_stream.str(),
                           OOMPH_CURRENT_FUNCTION,
                           OOMPH_EXCEPTION_LOCATION);
      }
     break;
     //Macro element 6, is right hand block 3
    case 6:
     switch(direction)
      {
      case N:
        linear_interpolate(Upper_2,Upper_3,s[0],f);
       break;
      case S:
        linear_interpolate(Lower_2,Lower_3,s[0],f);
       break;
      case W:
        linear_interpolate(Lower_2,Upper_2,s[0],f);
       break;
      case E:
        linear_interpolate(Lower_3,Upper_3,s[0],f);
       break;
      default:
       std::ostringstream error_stream;
       error_stream << "Direction is incorrect:  " << direction << std::endl;
       throw OomphLibError(error_stream.str(),
                           OOMPH_CURRENT_FUNCTION,
                           OOMPH_EXCEPTION_LOCATION);
      }
     break;
     //Macro element 7, is right hand block 4
    case 7:
     switch(direction)
      {
      case N:
        linear_interpolate(Upper_3,Upper_right,s[0],f);
       break;
      case S:
        linear_interpolate(Lower_3,Lower_right,s[0],f);
       break;
      case W:
        linear_interpolate(Lower_3,Upper_3,s[0],f);
       break;
      case E:
        linear_interpolate(Lower_right,Upper_right,s[0],f);
       break;
      default:
       std::ostringstream error_stream;
       error_stream << "Direction is incorrect:  " << direction << std::endl;
       throw OomphLibError(error_stream.str(),
                           OOMPH_CURRENT_FUNCTION,
                           OOMPH_EXCEPTION_LOCATION);
      }
     break;
    default:
     std::ostringstream error_stream;
     error_stream << "Wrong macro element number" << m << std::endl;
     throw OomphLibError(error_stream.str(),
                         OOMPH_CURRENT_FUNCTION,
                         OOMPH_EXCEPTION_LOCATION);
    }
  }
References Eigen::bfloat16_impl::atan(), GlobalParameters::Cylinder_pt, Global_Physical_Variables::E, f(), m, N, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, OscillatingCylinder::position(), s, oomph::QuadTreeNames::S, and oomph::QuadTreeNames::W.
Member Data Documentation
Centre_x
double RectangleWithHoleDomain::Centre_x private
x-coordinate of circle centre
Centre_y
double RectangleWithHoleDomain::Centre_y private
y-coordinate of circle centre
Cylinder_pt
GeomObject* RectangleWithHoleDomain::Cylinder_pt private
Pointer to geometric object that represents the central cylinder.
Lower_1
Vector< double > RectangleWithHoleDomain::Lower_1 private
Coordinate of internal point in the boundaries of the domain.
Lower_2
Vector< double > RectangleWithHoleDomain::Lower_2 private
Coordinate of internal point in the boundaries of the domain.
Lower_3
Vector< double > RectangleWithHoleDomain::Lower_3 private
Coordinate of internal point in the boundaries of the domain.
Lower_left
Vector<double> RectangleWithHoleDomain::Lower_left private
Lower left corner of rectangle.
Lower_mid_left
Vector<double> RectangleWithHoleDomain::Lower_mid_left private
Where the "radial" line from circle meets lower boundary on left.
Lower_mid_right
Vector<double> RectangleWithHoleDomain::Lower_mid_right private
Where the "radial" line from circle meets lower boundary on right.
Lower_right
Vector<double> RectangleWithHoleDomain::Lower_right private
Lower right corner of rectangle.
Upper_1
Vector< double > RectangleWithHoleDomain::Upper_1 private
Coordinate of internal point in the boundaries of the domain.
Upper_2
Vector< double > RectangleWithHoleDomain::Upper_2 private
Coordinate of internal point in the boundaries of the domain.
Upper_3
Vector< double > RectangleWithHoleDomain::Upper_3 private
Coordinate of internal point in the boundaries of the domain.
Upper_left
Vector<double> RectangleWithHoleDomain::Upper_left private
Upper left corner of rectangle.
Upper_mid_left
Vector<double> RectangleWithHoleDomain::Upper_mid_left private
Where the "radial" line from circle meets upper boundary on left.
Upper_mid_right
Vector<double> RectangleWithHoleDomain::Upper_mid_right private
Where the "radial" line from circle meets upper boundary on right.
Upper_right
Vector<double> RectangleWithHoleDomain::Upper_right private
Upper right corner of rectangle.
The documentation for this class was generated from the following files:
adaptive_hopf.cc
adaptive_hopf_with_separate_meshes.cc
flow_past_cylinder.cc