MercuryDPM: UnsteadyHeatProblem< ELEMENT > Class Template Reference
UnsteadyHeatProblem< ELEMENT > Class Template Reference
UnsteadyHeat problem.
Public Member Functions
UnsteadyHeatProblem ()
Constructor.
~UnsteadyHeatProblem ()
Destructor (empty)
void actions_after_newton_solve ()
Update the problem specs after solve (empty)
void actions_before_newton_solve ()
Update the problem specs before solve (empty)
void actions_before_adapt ()
Actions before adapt: wipe flux elements.
void actions_after_adapt ()
void doc_solution (DocInfo &doc_info)
Doc the solution.
UnsteadyHeatProblem (UnsteadyHeatEquations< 2 >::UnsteadyHeatSourceFctPt source_fct_pt)
Constructor.
~UnsteadyHeatProblem ()
Destructor (empty)
void actions_after_newton_solve ()
Update the problem specs after solve (empty)
void actions_before_newton_solve ()
Update the problem specs before solve (empty)
void actions_after_implicit_timestep ()
Update the problem specs after solve (empty)
void actions_before_implicit_timestep ()
void set_initial_condition ()
void doc_solution (DocInfo &doc_info, ofstream &trace_file)
Doc the solution.
void create_flux_elements ()
Create flux elements.
UnsteadyHeatProblem (UnsteadyHeatEquations< 2 >::UnsteadyHeatSourceFctPt source_fct_pt)
Constructor.
~UnsteadyHeatProblem ()
Destructor (empty)
void actions_after_newton_solve ()
Update the problem specs after solve (empty)
void actions_before_newton_solve ()
Update the problem specs before solve (empty)
void actions_after_implicit_timestep ()
Update the problem specs after solve (empty)
void actions_before_implicit_timestep ()
void set_initial_condition ()
void doc_solution (DocInfo &doc_info, ofstream &trace_file)
Doc the solution.
void disable_ALE ()
Switch off ALE terms.
UnsteadyHeatProblem (const SpaceTimeFunctionPt &source_fct_pt)
Constructor.
~UnsteadyHeatProblem ()
Destructor (empty)
void actions_before_newton_solve ()
Update the problem specs before solve (empty)
void actions_after_newton_solve ()
Update the problem specs after solve (empty)
void actions_before_adapt ()
Update the problem specs before solve (empty)
void actions_after_adapt ()
Update the problem specs after solve.
void create_spacetime_mesh ()
void apply_boundary_conditions ()
Assign the Dirichlet and maybe time-periodic BCs.
void enforce_time_periodic_boundary_conditions ()
void set_neighbour_periodic_and_up_right_equivalents (FiniteElement *el0_pt, FiniteElement *el1_pt, const int &direction0)
void complete_problem_setup ()
void doc_solution (const bool &doc_error=false)
Doc the solution.
UnsteadyHeatProblem (const SpaceTimeFunctionPt &source_fct_pt)
Constructor.
~UnsteadyHeatProblem ()
Destructor (empty)
void actions_before_newton_solve ()
Update the problem specs before solve (empty)
void actions_after_newton_solve ()
Update the problem specs after solve (empty)
void actions_before_adapt ()
Update the problem specs before solve (empty)
void actions_after_adapt ()
Update the problem specs after solve.
void refine_uniformly ()
void adapt ()
void create_spacetime_mesh ()
void apply_boundary_conditions ()
Assign the Dirichlet and maybe time-periodic BCs.
void enforce_time_periodic_boundary_conditions ()
void set_neighbour_periodic_and_up_right_equivalents (FiniteElement *el0_pt, FiniteElement *el1_pt, const int &direction0)
void assign_time_slab_id ()
Helper function when space-time block preconditioning is being used.
void update_block_preconditioner_after_refinement ()
void complete_problem_setup ()
void set_up_spacetime_solver ()
Assign the chosen solver (and preconditioner if so desired)
void doc_solution (const bool &doc_error=false)
Doc the solution.
UnsteadyHeatProblem (const SpaceTimeFunctionPt &source_fct_pt)
Constructor.
~UnsteadyHeatProblem ()
Destructor (empty)
void actions_before_newton_solve ()
Update the problem specs before solve (empty)
void actions_after_newton_solve ()
Update the problem specs after solve (empty)
void actions_before_adapt ()
Update the problem specs before solve (empty)
void actions_after_adapt ()
Update the problem specs after solve.
void refine_uniformly ()
void adapt ()
void unpin_all_dofs ()
Unpin all of the dofs in the mesh.
void create_spacetime_mesh ()
void pin_redundant_temporal_nodes ()
void apply_boundary_conditions ()
Assign the Dirichlet and maybe time-periodic BCs.
void enforce_time_periodic_boundary_conditions ()
void set_neighbour_periodic_and_up_right_equivalents (FiniteElement *el0_pt, FiniteElement *el1_pt, const int &direction0)
void assign_time_slab_id ()
Helper function when space-time block preconditioning is being used.
void complete_problem_setup ()
void set_up_spacetime_solver ()
Assign the chosen solver (and preconditioner if so desired)
void update_block_preconditioner_after_refinement ()
void doc_solution (const bool &doc_error=false)
Doc the solution.
UnsteadyHeatProblem (UnsteadyHeatEquations< 2 >::UnsteadyHeatSourceFctPt source_fct_pt)
Constructor.
~UnsteadyHeatProblem ()
Destructor (empty)
void actions_after_newton_solve ()
Update the problem specs after solve (empty)
void actions_before_newton_solve ()
Update the problem specs before solve (empty)
void actions_after_implicit_timestep ()
Update the problem specs after solve (empty)
void actions_before_implicit_timestep ()
void set_initial_condition ()
void doc_solution (DocInfo &doc_info, ofstream &trace_file)
Doc the solution.
UnsteadyHeatProblem (UnsteadyHeatEquations< 2 >::UnsteadyHeatSourceFctPt source_fct_pt)
Constructor.
~UnsteadyHeatProblem ()
Destructor (empty)
void actions_after_newton_solve ()
Update the problem specs after solve (empty)
void actions_before_newton_solve ()
Update the problem specs before solve (empty)
void actions_after_implicit_timestep ()
Update the problem specs after solve (empty)
void actions_before_implicit_timestep ()
void set_initial_condition ()
void doc_solution (DocInfo &doc_info, ofstream &trace_file)
Doc the solution.
void dump_it (ofstream &dump_file)
Dump problem to disk to allow for restart.
void restart (ifstream &restart_file)
Read problem for restart from specified restart file.
UnsteadyHeatProblem (UnsteadyHeatEquations< 2 >::UnsteadyHeatSourceFctPt source_fct_pt)
Constructor.
~UnsteadyHeatProblem ()
Destructor (empty)
void actions_after_newton_solve ()
Update the problem specs after solve (empty)
void actions_before_newton_solve ()
Update the problem specs before solve (empty)
void actions_after_implicit_timestep ()
Update the problem specs after solve (empty)
void actions_before_implicit_timestep ()
void set_initial_condition ()
void doc_solution (DocInfo &doc_info, ofstream &trace_file)
Doc the solution.
void dump_it (ofstream &dump_file)
Dump problem to disk to allow for restart.
void restart (ifstream &restart_file)
Read problem for restart from specified restart file.
double global_temporal_error_norm ()
Global error norm for adaptive time-stepping.
Public Member Functions inherited from oomph::Problem
virtual void debug_hook_fct (const unsigned &i)
void set_analytic_dparameter (double *const &parameter_pt)
void unset_analytic_dparameter (double *const &parameter_pt)
bool is_dparameter_calculated_analytically (double *const &parameter_pt)
void set_analytic_hessian_products ()
void unset_analytic_hessian_products ()
bool are_hessian_products_calculated_analytically ()
void set_pinned_values_to_zero ()
bool distributed () const
OomphCommunicator * communicator_pt ()
access function to the oomph-lib communicator
const OomphCommunicator * communicator_pt () const
access function to the oomph-lib communicator, const version
Problem ()
Problem (const Problem &dummy)=delete
Broken copy constructor.
void operator= (const Problem &)=delete
Broken assignment operator.
virtual ~Problem ()
Virtual destructor to clean up memory.
Mesh *& mesh_pt ()
Return a pointer to the global mesh.
Mesh *const & mesh_pt () const
Return a pointer to the global mesh (const version)
Mesh *& mesh_pt (const unsigned &imesh)
Mesh *const & mesh_pt (const unsigned &imesh) const
Return a pointer to the i-th submesh (const version)
unsigned nsub_mesh () const
Return number of submeshes.
unsigned add_sub_mesh (Mesh *const &mesh_pt)
void flush_sub_meshes ()
void build_global_mesh ()
void rebuild_global_mesh ()
LinearSolver *& linear_solver_pt ()
Return a pointer to the linear solver object.
LinearSolver *const & linear_solver_pt () const
Return a pointer to the linear solver object (const version)
LinearSolver *& mass_matrix_solver_for_explicit_timestepper_pt ()
LinearSolver * mass_matrix_solver_for_explicit_timestepper_pt () const
EigenSolver *& eigen_solver_pt ()
Return a pointer to the eigen solver object.
EigenSolver *const & eigen_solver_pt () const
Return a pointer to the eigen solver object (const version)
Time *& time_pt ()
Return a pointer to the global time object.
Time * time_pt () const
Return a pointer to the global time object (const version).
double & time ()
Return the current value of continuous time.
double time () const
Return the current value of continuous time (const version)
TimeStepper *& time_stepper_pt ()
const TimeStepper * time_stepper_pt () const
TimeStepper *& time_stepper_pt (const unsigned &i)
Return a pointer to the i-th timestepper.
ExplicitTimeStepper *& explicit_time_stepper_pt ()
Return a pointer to the explicit timestepper.
unsigned long set_timestepper_for_all_data (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data=false)
virtual void shift_time_values ()
Shift all values along to prepare for next timestep.
AssemblyHandler *& assembly_handler_pt ()
Return a pointer to the assembly handler object.
AssemblyHandler *const & assembly_handler_pt () const
Return a pointer to the assembly handler object (const version)
double & minimum_dt ()
Access function to min timestep in adaptive timestepping.
double & maximum_dt ()
Access function to max timestep in adaptive timestepping.
unsigned & max_newton_iterations ()
Access function to max Newton iterations before giving up.
void problem_is_nonlinear (const bool &prob_lin)
Access function to Problem_is_nonlinear.
double & max_residuals ()
bool & time_adaptive_newton_crash_on_solve_fail ()
Access function for Time_adaptive_newton_crash_on_solve_fail.
double & newton_solver_tolerance ()
void add_time_stepper_pt (TimeStepper *const &time_stepper_pt)
void set_explicit_time_stepper_pt (ExplicitTimeStepper *const &explicit_time_stepper_pt)
void initialise_dt (const double &dt)
void initialise_dt (const Vector< double > &dt)
Data *& global_data_pt (const unsigned &i)
Return a pointer to the the i-th global data object.
void add_global_data (Data *const &global_data_pt)
void flush_global_data ()
LinearAlgebraDistribution *const & dof_distribution_pt () const
Return the pointer to the dof distribution (read-only)
unsigned long ndof () const
Return the number of dofs.
unsigned ntime_stepper () const
Return the number of time steppers.
unsigned nglobal_data () const
Return the number of global data values.
unsigned self_test ()
Self-test: Check meshes and global data. Return 0 for OK.
void enable_store_local_dof_pt_in_elements ()
void disable_store_local_dof_pt_in_elements ()
unsigned long assign_eqn_numbers (const bool &assign_local_eqn_numbers=true)
void describe_dofs (std::ostream &out= *(oomph_info.stream_pt())) const
void enable_discontinuous_formulation ()
void disable_discontinuous_formulation ()
void get_dofs (DoubleVector &dofs) const
void get_dofs (const unsigned &t, DoubleVector &dofs) const
Return vector of the t'th history value of all dofs.
void set_dofs (const DoubleVector &dofs)
Set the values of the dofs.
void set_dofs (const unsigned &t, DoubleVector &dofs)
Set the history values of the dofs.
void set_dofs (const unsigned &t, Vector< double * > &dof_pt)
void add_to_dofs (const double &lambda, const DoubleVector &increment_dofs)
Add lambda x incremenet_dofs[l] to the l-th dof.
double * global_dof_pt (const unsigned &i)
double & dof (const unsigned &i)
i-th dof in the problem
double dof (const unsigned &i) const
i-th dof in the problem (const version)
double *& dof_pt (const unsigned &i)
Pointer to i-th dof in the problem.
double * dof_pt (const unsigned &i) const
Pointer to i-th dof in the problem (const version)
virtual void get_inverse_mass_matrix_times_residuals (DoubleVector &Mres)
virtual void get_dvaluesdt (DoubleVector &f)
virtual void get_residuals (DoubleVector &residuals)
Get the total residuals Vector for the problem.
virtual void get_jacobian (DoubleVector &residuals, DenseDoubleMatrix &jacobian)
virtual void get_jacobian (DoubleVector &residuals, CRDoubleMatrix &jacobian)
virtual void get_jacobian (DoubleVector &residuals, CCDoubleMatrix &jacobian)
virtual void get_jacobian (DoubleVector &residuals, SumOfMatrices &jacobian)
void get_fd_jacobian (DoubleVector &residuals, DenseMatrix< double > &jacobian)
Get the full Jacobian by finite differencing.
void get_derivative_wrt_global_parameter (double *const &parameter_pt, DoubleVector &result)
void get_hessian_vector_products (DoubleVectorWithHaloEntries const &Y, Vector< DoubleVectorWithHaloEntries > const &C, Vector< DoubleVectorWithHaloEntries > &product)
void solve_eigenproblem (const unsigned &n_eval, Vector< std::complex< double >> &eigenvalue, Vector< DoubleVector > &eigenvector, const bool &steady=true)
Solve the eigenproblem.
void solve_eigenproblem (const unsigned &n_eval, Vector< std::complex< double >> &eigenvalue, const bool &steady=true)
virtual void get_eigenproblem_matrices (CRDoubleMatrix &mass_matrix, CRDoubleMatrix &main_matrix, const double &shift=0.0)
void assign_eigenvector_to_dofs (DoubleVector &eigenvector)
Assign the eigenvector passed to the function to the dofs.
void add_eigenvector_to_dofs (const double &epsilon, const DoubleVector &eigenvector)
void store_current_dof_values ()
Store the current values of the degrees of freedom.
void restore_dof_values ()
Restore the stored values of the degrees of freedom.
void enable_jacobian_reuse ()
void disable_jacobian_reuse ()
Disable recycling of Jacobian in Newton iteration.
bool jacobian_reuse_is_enabled ()
Is recycling of Jacobian in Newton iteration enabled?
bool & use_predictor_values_as_initial_guess ()
void newton_solve ()
Use Newton method to solve the problem.
void enable_globally_convergent_newton_method ()
enable globally convergent Newton method
void disable_globally_convergent_newton_method ()
disable globally convergent Newton method
void newton_solve (unsigned const &max_adapt)
void steady_newton_solve (unsigned const &max_adapt=0)
void copy (Problem *orig_problem_pt)
virtual Problem * make_copy ()
virtual void read (std::ifstream &restart_file, bool &unsteady_restart)
virtual void read (std::ifstream &restart_file)
virtual void dump (std::ofstream &dump_file) const
void dump (const std::string &dump_file_name) const
void delete_all_external_storage ()
virtual void symmetrise_eigenfunction_for_adaptive_pitchfork_tracking ()
double * bifurcation_parameter_pt () const
void get_bifurcation_eigenfunction (Vector< DoubleVector > &eigenfunction)
void activate_fold_tracking (double *const &parameter_pt, const bool &block_solve=true)
void activate_bifurcation_tracking (double *const &parameter_pt, const DoubleVector &eigenvector, const bool &block_solve=true)
void activate_bifurcation_tracking (double *const &parameter_pt, const DoubleVector &eigenvector, const DoubleVector &normalisation, const bool &block_solve=true)
void activate_pitchfork_tracking (double *const &parameter_pt, const DoubleVector &symmetry_vector, const bool &block_solve=true)
void activate_hopf_tracking (double *const &parameter_pt, const bool &block_solve=true)
void activate_hopf_tracking (double *const &parameter_pt, const double &omega, const DoubleVector &null_real, const DoubleVector &null_imag, const bool &block_solve=true)
void deactivate_bifurcation_tracking ()
void reset_assembly_handler_to_default ()
Reset the system to the standard non-augemented state.
double arc_length_step_solve (double *const &parameter_pt, const double &ds, const unsigned &max_adapt=0)
double arc_length_step_solve (Data *const &data_pt, const unsigned &data_index, const double &ds, const unsigned &max_adapt=0)
void reset_arc_length_parameters ()
int & sign_of_jacobian ()
void explicit_timestep (const double &dt, const bool &shift_values=true)
Take an explicit timestep of size dt.
void unsteady_newton_solve (const double &dt)
void unsteady_newton_solve (const double &dt, const bool &shift_values)
void unsteady_newton_solve (const double &dt, const unsigned &max_adapt, const bool &first, const bool &shift=true)
double doubly_adaptive_unsteady_newton_solve (const double &dt, const double &epsilon, const unsigned &max_adapt, const bool &first, const bool &shift=true)
double doubly_adaptive_unsteady_newton_solve (const double &dt, const double &epsilon, const unsigned &max_adapt, const unsigned &suppress_resolve_after_spatial_adapt_flag, const bool &first, const bool &shift=true)
double adaptive_unsteady_newton_solve (const double &dt_desired, const double &epsilon)
double adaptive_unsteady_newton_solve (const double &dt_desired, const double &epsilon, const bool &shift_values)
void assign_initial_values_impulsive ()
void assign_initial_values_impulsive (const double &dt)
void calculate_predictions ()
Calculate predictions.
void enable_mass_matrix_reuse ()
void disable_mass_matrix_reuse ()
bool mass_matrix_reuse_is_enabled ()
Return whether the mass matrix is being reused.
void refine_uniformly (const Vector< unsigned > &nrefine_for_mesh)
void refine_uniformly (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh)
void refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void refine_uniformly (DocInfo &doc_info)
void refine_uniformly_and_prune (DocInfo &doc_info)
void refine_uniformly ()
void refine_uniformly (const unsigned &i_mesh, DocInfo &doc_info)
Do uniform refinement for submesh i_mesh with documentation.
void refine_uniformly (const unsigned &i_mesh)
Do uniform refinement for submesh i_mesh without documentation.
void p_refine_uniformly (const Vector< unsigned > &nrefine_for_mesh)
void p_refine_uniformly (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void p_refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh)
void p_refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void p_refine_uniformly (DocInfo &doc_info)
void p_refine_uniformly_and_prune (DocInfo &doc_info)
void p_refine_uniformly ()
void p_refine_uniformly (const unsigned &i_mesh, DocInfo &doc_info)
Do uniform p-refinement for submesh i_mesh with documentation.
void p_refine_uniformly (const unsigned &i_mesh)
Do uniform p-refinement for submesh i_mesh without documentation.
void refine_selected_elements (const Vector< unsigned > &elements_to_be_refined)
void refine_selected_elements (const Vector< RefineableElement * > &elements_to_be_refined_pt)
void refine_selected_elements (const unsigned &i_mesh, const Vector< unsigned > &elements_to_be_refined)
void refine_selected_elements (const unsigned &i_mesh, const Vector< RefineableElement * > &elements_to_be_refined_pt)
void refine_selected_elements (const Vector< Vector< unsigned >> &elements_to_be_refined)
void refine_selected_elements (const Vector< Vector< RefineableElement * >> &elements_to_be_refined_pt)
void p_refine_selected_elements (const Vector< unsigned > &elements_to_be_refined)
void p_refine_selected_elements (const Vector< PRefineableElement * > &elements_to_be_refined_pt)
void p_refine_selected_elements (const unsigned &i_mesh, const Vector< unsigned > &elements_to_be_refined)
void p_refine_selected_elements (const unsigned &i_mesh, const Vector< PRefineableElement * > &elements_to_be_refined_pt)
void p_refine_selected_elements (const Vector< Vector< unsigned >> &elements_to_be_refined)
void p_refine_selected_elements (const Vector< Vector< PRefineableElement * >> &elements_to_be_refined_pt)
unsigned unrefine_uniformly ()
unsigned unrefine_uniformly (const unsigned &i_mesh)
void p_unrefine_uniformly (DocInfo &doc_info)
void p_unrefine_uniformly (const unsigned &i_mesh, DocInfo &doc_info)
Do uniform p-unrefinement for submesh i_mesh without documentation.
void adapt (unsigned &n_refined, unsigned &n_unrefined)
void adapt ()
void p_adapt (unsigned &n_refined, unsigned &n_unrefined)
void p_adapt ()
void adapt_based_on_error_estimates (unsigned &n_refined, unsigned &n_unrefined, Vector< Vector< double >> &elemental_error)
void adapt_based_on_error_estimates (Vector< Vector< double >> &elemental_error)
void get_all_error_estimates (Vector< Vector< double >> &elemental_error)
void doc_errors (DocInfo &doc_info)
Get max and min error for all elements in submeshes.
void doc_errors ()
Get max and min error for all elements in submeshes.
void enable_info_in_newton_solve ()
void disable_info_in_newton_solve ()
Disable the output of information when in the newton solver.
Public Member Functions inherited from oomph::ExplicitTimeSteppableObject
ExplicitTimeSteppableObject ()
Empty constructor.
ExplicitTimeSteppableObject (const ExplicitTimeSteppableObject &)=delete
Broken copy constructor.
void operator= (const ExplicitTimeSteppableObject &)=delete
Broken assignment operator.
virtual ~ExplicitTimeSteppableObject ()
Empty destructor.
virtual void actions_before_explicit_stage ()
virtual void actions_after_explicit_stage ()
Private Types
enum {
Initial_time_boundary_id =0 , Lower_spatial_boundary_id =1 , Right_spatial_boundary_id =2 , Upper_spatial_boundary_id =3 ,
Left_spatial_boundary_id =4 , Final_time_boundary_id =5
}
enum { Diagonal_preconditioner =0 , Lower_triangular_preconditioner =1 }
enum {
Initial_time_boundary_id =0 , Lower_spatial_boundary_id =1 , Right_spatial_boundary_id =2 , Upper_spatial_boundary_id =3 ,
Left_spatial_boundary_id =4 , Final_time_boundary_id =5
}
enum { Diagonal_preconditioner =0 , Lower_triangular_preconditioner =1 }
enum {
Initial_time_boundary_id =0 , Lower_spatial_boundary_id =1 , Right_spatial_boundary_id =2 , Upper_spatial_boundary_id =3 ,
Left_spatial_boundary_id =4 , Final_time_boundary_id =5
}
typedef SpaceTimeUnsteadyHeatEquations< 2 >::SpaceTimeUnsteadyHeatSourceFctPt SpaceTimeFunctionPt
typedef SpaceTimeUnsteadyHeatEquations< 2 >::SpaceTimeUnsteadyHeatSourceFctPt SpaceTimeFunctionPt
typedef SpaceTimeUnsteadyHeatMixedOrderEquations< 2 >::SpaceTimeUnsteadyHeatSourceFctPt SpaceTimeFunctionPt
Private Member Functions
void create_flux_elements ()
Create flux elements.
void delete_flux_elements ()
Delete flux elements.
void complete_problem_setup ()
Complete problem setup: pass pointers to physical variables.
Private Attributes
RefineableTriangleMesh< ELEMENT > * Bulk_mesh_pt
Pointers to specific mesh.
Mesh * Surface_melt_mesh_pt
Pointer to the "surface" mesh.
Mesh * Surface_mesh_pt
Pointer to the "surface" mesh.
unsigned Flux_boundary_id
ID of flux boundary.
unsigned Melt_boundary_id
ID of melt boundary.
ofstream Trace_file
Trace file.
UnsteadyHeatEquations< 2 >::UnsteadyHeatSourceFctPt Source_fct_pt
Pointer to source function.
Mesh * Bulk_mesh_pt
Pointer to the "bulk" mesh.
Node * Control_node_pt
Pointer to control node at which the solution is documented.
RefineableSimpleCubicMesh< ELEMENT > * Bulk_mesh_pt
Pointer to the mesh.
SpaceTimeFunctionPt Source_fct_pt
Pointer to source function.
bool Periodicity_has_been_enforced
IterativeLinearSolver * Solver_pt
Oomph-lib iterative linear solver.
Preconditioner * Prec_pt
Preconditioner.
unsigned N_space_time_slab
Additional Inherited Members
Public Types inherited from oomph::Problem
typedef void(* SpatialErrorEstimatorFctPt) (Mesh *&mesh_pt, Vector< double > &elemental_error)
Function pointer for spatial error estimator.
typedef void(* SpatialErrorEstimatorWithDocFctPt) (Mesh *&mesh_pt, Vector< double > &elemental_error, DocInfo &doc_info)
Function pointer for spatial error estimator with doc.
Public Attributes inherited from oomph::Problem
bool Shut_up_in_newton_solve
Static Public Attributes inherited from oomph::Problem
static bool Suppress_warning_about_actions_before_read_unstructured_meshes
Protected Types inherited from oomph::Problem
enum Assembly_method {
Perform_assembly_using_vectors_of_pairs , Perform_assembly_using_two_vectors , Perform_assembly_using_maps , Perform_assembly_using_lists ,
Perform_assembly_using_two_arrays
}
Enumerated flags to determine which sparse assembly method is used.
Protected Member Functions inherited from oomph::Problem
unsigned setup_element_count_per_dof ()
virtual void sparse_assemble_row_or_column_compressed (Vector< int * > &column_or_row_index, Vector< int * > &row_or_column_start, Vector< double * > &value, Vector< unsigned > &nnz, Vector< double * > &residual, bool compressed_row_flag)
virtual void actions_before_newton_convergence_check ()
virtual void actions_before_newton_step ()
virtual void actions_after_newton_step ()
virtual void actions_after_implicit_timestep_and_error_estimation ()
virtual void actions_before_explicit_timestep ()
Actions that should be performed before each explicit time step.
virtual void actions_after_explicit_timestep ()
Actions that should be performed after each explicit time step.
virtual void actions_before_read_unstructured_meshes ()
virtual void actions_after_read_unstructured_meshes ()
virtual void actions_after_change_in_global_parameter (double *const &parameter_pt)
virtual void actions_after_change_in_bifurcation_parameter ()
virtual void actions_after_parameter_increase (double *const &parameter_pt)
double & dof_derivative (const unsigned &i)
double & dof_current (const unsigned &i)
unsigned newton_solve_continuation (double *const &parameter_pt)
unsigned newton_solve_continuation (double *const &parameter_pt, DoubleVector &z)
void calculate_continuation_derivatives (double *const &parameter_pt)
void calculate_continuation_derivatives (const DoubleVector &z)
void calculate_continuation_derivatives_fd (double *const &parameter_pt)
bool does_pointer_correspond_to_problem_data (double *const &parameter_pt)
void set_consistent_pinned_values_for_continuation ()
Protected Attributes inherited from oomph::Problem
Vector< Problem * > Copy_of_problem_pt
std::map< double *, bool > Calculate_dparameter_analytic
bool Calculate_hessian_products_analytic
LinearAlgebraDistribution * Dof_distribution_pt
Vector< double * > Dof_pt
Vector of pointers to dofs.
DoubleVectorWithHaloEntries Element_count_per_dof
double Relaxation_factor
double Newton_solver_tolerance
unsigned Max_newton_iterations
Maximum number of Newton iterations.
unsigned Nnewton_iter_taken
Vector< double > Max_res
Maximum residuals at start and after each newton iteration.
double Max_residuals
bool Time_adaptive_newton_crash_on_solve_fail
bool Jacobian_reuse_is_enabled
Is re-use of Jacobian in Newton iteration enabled? Default: false.
bool Jacobian_has_been_computed
bool Problem_is_nonlinear
bool Pause_at_end_of_sparse_assembly
bool Doc_time_in_distribute
unsigned Sparse_assembly_method
unsigned Sparse_assemble_with_arrays_initial_allocation
unsigned Sparse_assemble_with_arrays_allocation_increment
Vector< Vector< unsigned > > Sparse_assemble_with_arrays_previous_allocation
double Numerical_zero_for_sparse_assembly
double FD_step_used_in_get_hessian_vector_products
bool Mass_matrix_reuse_is_enabled
bool Mass_matrix_has_been_computed
bool Discontinuous_element_formulation
double Minimum_dt
Minimum desired dt: if dt falls below this value, exit.
double Maximum_dt
Maximum desired dt.
double DTSF_max_increase
double DTSF_min_decrease
double Minimum_dt_but_still_proceed
bool Scale_arc_length
Boolean to control whether arc-length should be scaled.
double Desired_proportion_of_arc_length
Proportion of the arc-length to taken by the parameter.
double Theta_squared
int Sign_of_jacobian
Storage for the sign of the global Jacobian.
double Continuation_direction
double Parameter_derivative
Storage for the derivative of the global parameter wrt arc-length.
double Parameter_current
Storage for the present value of the global parameter.
bool Use_continuation_timestepper
Boolean to control original or new storage of dof stuff.
unsigned Dof_derivative_offset
unsigned Dof_current_offset
Vector< double > Dof_derivative
Storage for the derivative of the problem variables wrt arc-length.
Vector< double > Dof_current
Storage for the present values of the variables.
double Ds_current
Storage for the current step value.
unsigned Desired_newton_iterations_ds
double Minimum_ds
Minimum desired value of arc-length.
bool Bifurcation_detection
Boolean to control bifurcation detection via determinant of Jacobian.
bool Bisect_to_find_bifurcation
Boolean to control wheter bisection is used to located bifurcation.
bool First_jacobian_sign_change
Boolean to indicate whether a sign change has occured in the Jacobian.
bool Arc_length_step_taken
Boolean to indicate whether an arc-length step has been taken.
bool Use_finite_differences_for_continuation_derivatives
OomphCommunicator * Communicator_pt
The communicator for this problem.
bool Always_take_one_newton_step
double Timestep_reduction_factor_after_nonconvergence
bool Keep_temporal_error_below_tolerance
Static Protected Attributes inherited from oomph::Problem
static ContinuationStorageScheme Continuation_time_stepper
Storage for the single static continuation timestorage object.
Detailed Description
template<class ELEMENT>
class UnsteadyHeatProblem< ELEMENT >
UnsteadyHeat problem.
///////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////
Member Typedef Documentation
SpaceTimeFunctionPt [1/3]
template<class ELEMENT > typedef SpaceTimeUnsteadyHeatEquations<2>:: SpaceTimeUnsteadyHeatSourceFctPt UnsteadyHeatProblem< ELEMENT >::SpaceTimeFunctionPt private
SpaceTimeFunctionPt [2/3]
template<class ELEMENT > typedef SpaceTimeUnsteadyHeatEquations<2>:: SpaceTimeUnsteadyHeatSourceFctPt UnsteadyHeatProblem< ELEMENT >::SpaceTimeFunctionPt private
SpaceTimeFunctionPt [3/3]
template<class ELEMENT > typedef SpaceTimeUnsteadyHeatMixedOrderEquations<2>:: SpaceTimeUnsteadyHeatSourceFctPt UnsteadyHeatProblem< ELEMENT >::SpaceTimeFunctionPt private
Member Enumeration Documentation
anonymous enum
template<class ELEMENT > anonymous enum private
Enumerator
Initial_time_boundary_id
Lower_spatial_boundary_id
Right_spatial_boundary_id
Upper_spatial_boundary_id
Left_spatial_boundary_id
Final_time_boundary_id
   {
     Initial_time_boundary_id=0,
     Lower_spatial_boundary_id=1,
     Right_spatial_boundary_id=2,
     Upper_spatial_boundary_id=3,
     Left_spatial_boundary_id=4,
     Final_time_boundary_id=5
   };
anonymous enum
template<class ELEMENT > anonymous enum private
Enumerator
Diagonal_preconditioner
Lower_triangular_preconditioner
   {
     Diagonal_preconditioner=0,
     Lower_triangular_preconditioner=1
   };
anonymous enum
template<class ELEMENT > anonymous enum private
Enumerator
Initial_time_boundary_id
Lower_spatial_boundary_id
Right_spatial_boundary_id
Upper_spatial_boundary_id
Left_spatial_boundary_id
Final_time_boundary_id
   {
     Initial_time_boundary_id=0,
     Lower_spatial_boundary_id=1,
     Right_spatial_boundary_id=2,
     Upper_spatial_boundary_id=3,
     Left_spatial_boundary_id=4,
     Final_time_boundary_id=5
   };
anonymous enum
template<class ELEMENT > anonymous enum private
Enumerator
Diagonal_preconditioner
Lower_triangular_preconditioner
   {
     Diagonal_preconditioner=0,
     Lower_triangular_preconditioner=1
   };
anonymous enum
template<class ELEMENT > anonymous enum private
Enumerator
Initial_time_boundary_id
Lower_spatial_boundary_id
Right_spatial_boundary_id
Upper_spatial_boundary_id
Left_spatial_boundary_id
Final_time_boundary_id
   {
     Initial_time_boundary_id=0,
     Lower_spatial_boundary_id=1,
     Right_spatial_boundary_id=2,
     Upper_spatial_boundary_id=3,
     Left_spatial_boundary_id=4,
     Final_time_boundary_id=5
   };
Constructor & Destructor Documentation
UnsteadyHeatProblem() [1/9]
template<class ELEMENT > UnsteadyHeatProblem< ELEMENT >::UnsteadyHeatProblem
Constructor.
Constructor for UnsteadyHeat problem in square domain.
 {
  // Open trace file
  Trace_file.open("RESLT/trace.dat");
  // Allow for crap initial guess
  Problem::Max_residuals=10000.0;
  Problem::Max_newton_iterations=10000;
  // Allocate the timestepper -- this constructs the Problem's
  // time object with a sufficient amount of storage to store the
  // previous timsteps.
  add_time_stepper_pt(new BDF<2>);
  // Pointer to the closed curve that defines the outer boundary
  TriangleMeshClosedCurve* closed_curve_pt=0;
  // Build outer boundary as Polygon
  // The boundary is bounded by three distinct boundaries, each
  // represented by its own polyline
  Vector<TriangleMeshCurveSection*> boundary_polyline_pt(3);
  // Vertex coordinates on boundary
  Vector<Vector<double> > bound_coords(4);
  // First part of the boundary
  //---------------------------
  bound_coords[0].resize(2);
  bound_coords[0][0]=0.0;
  bound_coords[0][1]=0.0;
  bound_coords[1].resize(2);
  bound_coords[1][0]=1.0;
  bound_coords[1][1]=0.0;
  bound_coords[2].resize(2);
  bound_coords[2][0]=1.0;
  bound_coords[2][1]=1.0;
  bound_coords[3].resize(2);
  bound_coords[3][0]=0.0;
  bound_coords[3][1]=1.0;
  // Build the 1st boundary polyline
  unsigned boundary_id=0;
  boundary_polyline_pt[0]=new TriangleMeshPolyLine(bound_coords,boundary_id);
  // Second part of the boundary
  //----------------------------
  bound_coords.resize(2);
  bound_coords[0].resize(2);
  bound_coords[0][0]=0.0;
  bound_coords[0][1]=1.0;
  bound_coords[1].resize(2);
  bound_coords[1][0]=0.0;
  bound_coords[1][1]=0.5;
  // Flux boundary
  Flux_boundary_id=1;
  // Build the 2nd boundary polyline
  boundary_polyline_pt[1]=new TriangleMeshPolyLine(bound_coords,
                                                   Flux_boundary_id);
  // Third part of the boundary
  //----------------------------
  bound_coords.resize(2);
  bound_coords[0].resize(2);
  bound_coords[0][0]=0.0;
  bound_coords[0][1]=0.5;
  bound_coords[1].resize(2);
  bound_coords[1][0]=0.0;
  bound_coords[1][1]=0.0;
  // Flux boundary
  Melt_boundary_id=2;
  // Build the 3rd boundary polyline
  boundary_polyline_pt[2]=new TriangleMeshPolyLine(bound_coords,
                                                   Melt_boundary_id);
  // Create the triangle mesh polygon for outer boundary
  //----------------------------------------------------
  TriangleMeshPolygon *outer_polygon =
   new TriangleMeshPolygon(boundary_polyline_pt);
  // Set the pointer
  closed_curve_pt = outer_polygon;
  // Now build the mesh
  //===================
  // Use the TriangleMeshParameters object for helping on the manage of the
  // TriangleMesh parameters
  TriangleMeshParameters triangle_mesh_parameters(closed_curve_pt);
  // Specify the maximum area element
  double uniform_element_area=0.002;
  triangle_mesh_parameters.element_area() = uniform_element_area;
  // Create the mesh
  Bulk_mesh_pt=new RefineableTriangleMesh<ELEMENT>(triangle_mesh_parameters,
                                                   time_stepper_pt());
  // Set error estimator for bulk mesh
  Z2ErrorEstimator* error_estimator_pt=new Z2ErrorEstimator;
  Bulk_mesh_pt->spatial_error_estimator_pt()=error_estimator_pt;
  // Set element size limits
  Bulk_mesh_pt->max_element_size()=0.2;
  Bulk_mesh_pt->min_element_size()=0.000002;
  // Create the surface mesh as an empty mesh
  Surface_melt_mesh_pt=new Mesh;
  Surface_mesh_pt=new Mesh;
  // Build 'em
  create_flux_elements();
  // Set boundary condition and complete the build of all elements
  complete_problem_setup();
  // Add the two sub meshes to the problem
  add_sub_mesh(Bulk_mesh_pt);
  add_sub_mesh(Surface_melt_mesh_pt);
  add_sub_mesh(Surface_mesh_pt);
  // Combine all submeshes into a single global Mesh
  build_global_mesh();
  // Set the initial conditions
  unsigned nnod = Bulk_mesh_pt->nnode();
  for(unsigned j=0;j<nnod;j++)
   {
    Bulk_mesh_pt->node_pt(j)->set_value(0,-0.5);
   }
  // Do equation numbering
  cout <<"Number of equations: " << assign_eqn_numbers() << std::endl;
 } // end of constructor
References oomph::TriangleMeshParameters::element_area(), MeshRefinement::error_estimator_pt, j, oomph::Locate_zeta_helpers::Max_newton_iterations, and oomph::Problem_Parameter::Trace_file.
~UnsteadyHeatProblem() [1/9]
template<class ELEMENT > UnsteadyHeatProblem< ELEMENT >::~UnsteadyHeatProblem inline
Destructor (empty)
Destructor for UnsteadyHeat problem in cubic domain.
 {}
UnsteadyHeatProblem() [2/9]
template<class ELEMENT > UnsteadyHeatProblem< ELEMENT >::UnsteadyHeatProblem (UnsteadyHeatEquations< 2 >::UnsteadyHeatSourceFctPt source_fct_pt)
Constructor.
Constructor for UnsteadyHeat problem in square domain.
                                                                 :
  Source_fct_pt(source_fct_pt)
 {
  // Allocate the timestepper -- this constructs the Problem's
  // time object with a sufficient amount of storage to store the
  // previous timsteps.
  add_time_stepper_pt(new BDF<2>);
  // Setup parameters for exact solution
  // -----------------------------------
  // Decay parameter
  ExactSolnForUnsteadyHeat::K=5.0;
  // Setup mesh
  //-----------
  // Number of elements in x and y directions
  unsigned nx=5;
  unsigned ny=5;
  // Lengths in x and y directions
  double lx=1.0;
  double ly=1.0;
  // Build mesh
  Bulk_mesh_pt = new RectangularQuadMesh<ELEMENT>(nx,ny,lx,ly,time_stepper_pt());
  // Create the surface mesh as an empty mesh
  Surface_mesh_pt=new Mesh;
  // Create prescribed-flux elements
  create_flux_elements();
  // Add meshes and build global mesh
  add_sub_mesh(Bulk_mesh_pt);
  add_sub_mesh(Surface_mesh_pt);
  build_global_mesh();
  // Choose a control node at which the solution is documented
  //----------------------------------------------------------
  // Total number of elements
  unsigned n_el=Bulk_mesh_pt->nelement();
  // Choose an element in the middle
  unsigned control_el=unsigned(n_el/2);
  // Choose its first node as the control node
  Control_node_pt=Bulk_mesh_pt->finite_element_pt(control_el)->node_pt(0);
  cout << "Recording trace of the solution at: "
       << Control_node_pt->x(0) << " "
       << Control_node_pt->x(1) << std::endl;
  // Set the boundary conditions for this problem:
  // ---------------------------------------------
  // All nodes are free by default -- just pin the ones that have
  // Dirichlet conditions here.
  unsigned n_bound = Bulk_mesh_pt->nboundary();
  // Skip boundary 0 where we apply flux boundary conditions
  for(unsigned b=1;b<n_bound;b++)
   {
    unsigned n_node = Bulk_mesh_pt->nboundary_node(b);
    for (unsigned n=0;n<n_node;n++)
     {
      Bulk_mesh_pt->boundary_node_pt(b,n)->pin(0);
     }
   } // end of set boundary conditions
  // Complete the build of all elements so they are fully functional
  //----------------------------------------------------------------
  // Find number of elements in mesh
  unsigned n_element = Bulk_mesh_pt->nelement();
  // Loop over the elements to set up element-specific
  // things that cannot be handled by constructor
  for(unsigned i=0;i<n_element;i++)
   {
    // Upcast from FiniteElement to the present element
    ELEMENT *el_pt = dynamic_cast<ELEMENT*>(Bulk_mesh_pt->element_pt(i));
    //Set the source function pointer
    el_pt->source_fct_pt() = Source_fct_pt;
   }
  // Do equation numbering
  cout <<"Number of equations: " << assign_eqn_numbers() << std::endl;
 } // end of constructor
References oomph::Problem::add_sub_mesh(), oomph::Problem::add_time_stepper_pt(), oomph::Problem::assign_eqn_numbers(), b, oomph::Problem::build_global_mesh(), UnsteadyHeatProblem< ELEMENT >::Bulk_mesh_pt, UnsteadyHeatProblem< ELEMENT >::Control_node_pt, UnsteadyHeatProblem< ELEMENT >::create_flux_elements(), i, ExactSolnForUnsteadyHeat::K, Mesh_Parameters::lx, Mesh_Parameters::ly, n, Mesh_Parameters::nx, Mesh_Parameters::ny, UnsteadyHeatProblem< ELEMENT >::Source_fct_pt, UnsteadyHeatProblem< ELEMENT >::Surface_mesh_pt, oomph::Problem::time_stepper_pt(), and oomph::Node::x().
~UnsteadyHeatProblem() [2/9]
template<class ELEMENT > UnsteadyHeatProblem< ELEMENT >::~UnsteadyHeatProblem () inline
Destructor (empty)
 {}
UnsteadyHeatProblem() [3/9]
template<class ELEMENT > UnsteadyHeatProblem< ELEMENT >::UnsteadyHeatProblem (UnsteadyHeatEquations< 2 >::UnsteadyHeatSourceFctPt source_fct_pt)
Constructor.
~UnsteadyHeatProblem() [3/9]
template<class ELEMENT > UnsteadyHeatProblem< ELEMENT >::~UnsteadyHeatProblem () inline
Destructor (empty)
 {}
UnsteadyHeatProblem() [4/9]
template<class ELEMENT > UnsteadyHeatProblem< ELEMENT >::UnsteadyHeatProblem (const SpaceTimeFunctionPt & source_fct_pt)
Constructor.
Constructor for UnsteadyHeat problem in cubic domain.
                                             :
   Bulk_mesh_pt(0),
   Source_fct_pt(source_fct_pt),
   Periodicity_has_been_enforced(false)
 {
   // Generate the space-time mesh (stored as Bulk_mesh_pt)
   create_spacetime_mesh();
   // Assign the appropriate boundary conditions
   apply_boundary_conditions();
   // Complete the setup of the elements
   complete_problem_setup();
   // Do equation numbering
   oomph_info << "\nNumber of equations: " << assign_eqn_numbers() << std::endl;
 } // End of UnsteadyHeatProblem
References UnsteadyHeatProblem< ELEMENT >::apply_boundary_conditions(), oomph::Problem::assign_eqn_numbers(), UnsteadyHeatProblem< ELEMENT >::complete_problem_setup(), UnsteadyHeatProblem< ELEMENT >::create_spacetime_mesh(), and oomph::oomph_info.
~UnsteadyHeatProblem() [4/9]
template<class ELEMENT > UnsteadyHeatProblem< ELEMENT >::~UnsteadyHeatProblem ()
Destructor (empty)
UnsteadyHeatProblem() [5/9]
template<class ELEMENT > UnsteadyHeatProblem< ELEMENT >::UnsteadyHeatProblem (const SpaceTimeFunctionPt & source_fct_pt)
Constructor.
~UnsteadyHeatProblem() [5/9]
template<class ELEMENT > UnsteadyHeatProblem< ELEMENT >::~UnsteadyHeatProblem ()
Destructor (empty)
UnsteadyHeatProblem() [6/9]
template<class ELEMENT > UnsteadyHeatProblem< ELEMENT >::UnsteadyHeatProblem (const SpaceTimeFunctionPt & source_fct_pt)
Constructor.
~UnsteadyHeatProblem() [6/9]
template<class ELEMENT > UnsteadyHeatProblem< ELEMENT >::~UnsteadyHeatProblem ()
Destructor (empty)
UnsteadyHeatProblem() [7/9]
template<class ELEMENT > UnsteadyHeatProblem< ELEMENT >::UnsteadyHeatProblem (UnsteadyHeatEquations< 2 >::UnsteadyHeatSourceFctPt source_fct_pt)
Constructor.
~UnsteadyHeatProblem() [7/9]
template<class ELEMENT > UnsteadyHeatProblem< ELEMENT >::~UnsteadyHeatProblem () inline
Destructor (empty)
 {}
UnsteadyHeatProblem() [8/9]
template<class ELEMENT > UnsteadyHeatProblem< ELEMENT >::UnsteadyHeatProblem (UnsteadyHeatEquations< 2 >::UnsteadyHeatSourceFctPt source_fct_pt)
Constructor.
~UnsteadyHeatProblem() [8/9]
template<class ELEMENT > UnsteadyHeatProblem< ELEMENT >::~UnsteadyHeatProblem () inline
Destructor (empty)
 {}
UnsteadyHeatProblem() [9/9]
template<class ELEMENT > UnsteadyHeatProblem< ELEMENT >::UnsteadyHeatProblem (UnsteadyHeatEquations< 2 >::UnsteadyHeatSourceFctPt source_fct_pt)
Constructor.
~UnsteadyHeatProblem() [9/9]
template<class ELEMENT > UnsteadyHeatProblem< ELEMENT >::~UnsteadyHeatProblem () inline
Destructor (empty)
 {}
Member Function Documentation
actions_after_adapt() [1/4]
template<class ELEMENT > void UnsteadyHeatProblem< ELEMENT >::actions_after_adapt () inline virtual
Actions after adapt: Setup the problem again – remember that the mesh has been completely rebuilt and its element's don't have any pointers to source fcts etc. yet
Reimplemented from oomph::Problem.
   {
    // Create flux elements
    create_flux_elements();
    // Rebuild the Problem's global mesh from its various sub-meshes
    rebuild_global_mesh();
    // Rebuild elements
    complete_problem_setup();
   }
actions_after_adapt() [2/4]
template<class ELEMENT > void UnsteadyHeatProblem< ELEMENT >::actions_after_adapt () inline virtual
Update the problem specs after solve.
Reimplemented from oomph::Problem.
   {
     // Assign the appropriate boundary conditions
     apply_boundary_conditions();
     // Complete the setup of the elements
     complete_problem_setup();
   } // End of actions_after_adapt
actions_after_adapt() [3/4]
template<class ELEMENT > void UnsteadyHeatProblem< ELEMENT >::actions_after_adapt () inline virtual
Update the problem specs after solve.
Reimplemented from oomph::Problem.
   {
     // Assign the appropriate boundary conditions
     apply_boundary_conditions();
     // Re-assign time-slab IDs and wipe the old solver/preconditioner and
     // create a new one based on the (possibly) updated dof-to-block map
     update_block_preconditioner_after_refinement();
     // Complete the setup of the elements
     complete_problem_setup();
   } // End of actions_after_adapt
actions_after_adapt() [4/4]
template<class ELEMENT > void UnsteadyHeatProblem< ELEMENT >::actions_after_adapt () inline virtual
Update the problem specs after solve.
Reimplemented from oomph::Problem.
   {
     // Unpin all of the dofs; don't worry, the boundary dofs will be pinned
     // again in apply_boundary_conditions(...) and the appropriate nodes in
     // each element will be pinned in pin_redundant_temporal_nodes(...)
     unpin_all_dofs();
     // Assign the appropriate boundary conditions
     apply_boundary_conditions();
     // Pin the redundant temporal nodes that should not be proper dofs
     // (because of the time discretisation we're using)
     pin_redundant_temporal_nodes();
     // Re-assign time-slab IDs and wipe the old solver/preconditioner and
     // create a new one based on the (possibly) updated dof-to-block map
     update_block_preconditioner_after_refinement();
     // Complete the setup of the elements
     complete_problem_setup();
   } // End of actions_after_adapt
actions_after_implicit_timestep() [1/5]
template<class ELEMENT > void UnsteadyHeatProblem< ELEMENT >::actions_after_implicit_timestep () inline virtual
Update the problem specs after solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_after_implicit_timestep() [2/5]
template<class ELEMENT > void UnsteadyHeatProblem< ELEMENT >::actions_after_implicit_timestep () inline virtual
Update the problem specs after solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_after_implicit_timestep() [3/5]
template<class ELEMENT > void UnsteadyHeatProblem< ELEMENT >::actions_after_implicit_timestep () inline virtual
Update the problem specs after solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_after_implicit_timestep() [4/5]
template<class ELEMENT > void UnsteadyHeatProblem< ELEMENT >::actions_after_implicit_timestep () inline virtual
Update the problem specs after solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_after_implicit_timestep() [5/5]
template<class ELEMENT > void UnsteadyHeatProblem< ELEMENT >::actions_after_implicit_timestep () inline virtual
Update the problem specs after solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_after_newton_solve() [1/9]
template<class ELEMENT > void UnsteadyHeatProblem< ELEMENT >::actions_after_newton_solve () inline virtual
Update the problem specs after solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_after_newton_solve() [2/9]
template<class ELEMENT > void UnsteadyHeatProblem< ELEMENT >::actions_after_newton_solve () inline virtual
Update the problem specs after solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_after_newton_solve() [3/9]
template<class ELEMENT > void UnsteadyHeatProblem< ELEMENT >::actions_after_newton_solve () inline virtual
Update the problem specs after solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_after_newton_solve() [4/9]
template<class ELEMENT > void UnsteadyHeatProblem< ELEMENT >::actions_after_newton_solve () inline virtual
Update the problem specs after solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_after_newton_solve() [5/9]
template<class ELEMENT > void UnsteadyHeatProblem< ELEMENT >::actions_after_newton_solve () inline virtual
Update the problem specs after solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_after_newton_solve() [6/9]
template<class ELEMENT > void UnsteadyHeatProblem< ELEMENT >::actions_after_newton_solve () inline virtual
Update the problem specs after solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_after_newton_solve() [7/9]
template<class ELEMENT > void UnsteadyHeatProblem< ELEMENT >::actions_after_newton_solve () inline virtual
Update the problem specs after solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_after_newton_solve() [8/9]
template<class ELEMENT > void UnsteadyHeatProblem< ELEMENT >::actions_after_newton_solve () inline virtual
Update the problem specs after solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_after_newton_solve() [9/9]
template<class ELEMENT > void UnsteadyHeatProblem< ELEMENT >::actions_after_newton_solve () inline virtual
Update the problem specs after solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_before_adapt() [1/4]
template<class ELEMENT > void UnsteadyHeatProblem< ELEMENT >::actions_before_adapt () inline virtual
Actions before adapt: wipe flux elements.
Reimplemented from oomph::Problem.
   {
    // Kill the  elements and wipe surface mesh
    delete_flux_elements();
    // Rebuild the Problem's global mesh from its various sub-meshes
    rebuild_global_mesh();
   }
actions_before_adapt() [2/4]
template<class ELEMENT > void UnsteadyHeatProblem< ELEMENT >::actions_before_adapt () inline virtual
Update the problem specs before solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_before_adapt() [3/4]
template<class ELEMENT > void UnsteadyHeatProblem< ELEMENT >::actions_before_adapt () inline virtual
Update the problem specs before solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_before_adapt() [4/4]
template<class ELEMENT > void UnsteadyHeatProblem< ELEMENT >::actions_before_adapt () inline virtual
Update the problem specs before solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_before_implicit_timestep() [1/5]
template<class ELEMENT > void UnsteadyHeatProblem< ELEMENT >::actions_before_implicit_timestep virtual
Update the problem specs before next timestep: Set Dirchlet boundary conditions from exact solution.
Actions before timestep: update the domain, then reset the boundary conditions for the current time.
Reimplemented from oomph::Problem.
 {
  // Get current time
  double time=time_pt()->time();
  //Loop over the boundaries
  unsigned num_bound = Bulk_mesh_pt->nboundary();
  for(unsigned ibound=0;ibound<num_bound;ibound++)
   {
    // Loop over the nodes on boundary
    unsigned num_nod=Bulk_mesh_pt->nboundary_node(ibound);
    for (unsigned inod=0;inod<num_nod;inod++)
     {
      Node* nod_pt=Bulk_mesh_pt->boundary_node_pt(ibound,inod);
      double u;
      Vector<double> x(2);
      x[0]=nod_pt->x(0);
      x[1]=nod_pt->x(1);
      // Get current values of the boundary conditions from the
      // exact solution
      ExactSolnForUnsteadyHeat::get_exact_u(time,x,u);
      nod_pt->set_value(0,u);
     }
   }
 } // end of actions_before_implicit_timestep
References ExactSolnForUnsteadyHeat::get_exact_u(), oomph::Data::set_value(), plotDoE::x, and oomph::Node::x().
actions_before_implicit_timestep() [2/5]
template<class ELEMENT > void UnsteadyHeatProblem< ELEMENT >::actions_before_implicit_timestep () virtual
Update the problem specs before next timestep: Set Dirchlet boundary conditions from exact solution.
Reimplemented from oomph::Problem.
actions_before_implicit_timestep() [3/5]
template<class ELEMENT > void UnsteadyHeatProblem< ELEMENT >::actions_before_implicit_timestep () virtual
Update the problem specs before next timestep: Set Dirchlet boundary conditions from exact solution.
Reimplemented from oomph::Problem.
actions_before_implicit_timestep() [4/5]
template<class ELEMENT > void UnsteadyHeatProblem< ELEMENT >::actions_before_implicit_timestep () virtual
Update the problem specs before next timestep: Set Dirchlet boundary conditions from exact solution.
Reimplemented from oomph::Problem.
actions_before_implicit_timestep() [5/5]
template<class ELEMENT > void UnsteadyHeatProblem< ELEMENT >::actions_before_implicit_timestep () virtual
Update the problem specs before next timestep: Set Dirchlet boundary conditions from exact solution.
Reimplemented from oomph::Problem.
actions_before_newton_solve() [1/9]
template<class ELEMENT > void UnsteadyHeatProblem< ELEMENT >::actions_before_newton_solve () inline virtual
Update the problem specs before solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_before_newton_solve() [2/9]
template<class ELEMENT > void UnsteadyHeatProblem< ELEMENT >::actions_before_newton_solve () inline virtual
Update the problem specs before solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_before_newton_solve() [3/9]
template<class ELEMENT > void UnsteadyHeatProblem< ELEMENT >::actions_before_newton_solve () inline virtual
Update the problem specs before solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_before_newton_solve() [4/9]
template<class ELEMENT > void UnsteadyHeatProblem< ELEMENT >::actions_before_newton_solve () inline virtual
Update the problem specs before solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_before_newton_solve() [5/9]
template<class ELEMENT > void UnsteadyHeatProblem< ELEMENT >::actions_before_newton_solve () inline virtual
Update the problem specs before solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_before_newton_solve() [6/9]
template<class ELEMENT > void UnsteadyHeatProblem< ELEMENT >::actions_before_newton_solve () inline virtual
Update the problem specs before solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_before_newton_solve() [7/9]
template<class ELEMENT > void UnsteadyHeatProblem< ELEMENT >::actions_before_newton_solve () inline virtual
Update the problem specs before solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_before_newton_solve() [8/9]
template<class ELEMENT > void UnsteadyHeatProblem< ELEMENT >::actions_before_newton_solve () inline virtual
Update the problem specs before solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_before_newton_solve() [9/9]
template<class ELEMENT > void UnsteadyHeatProblem< ELEMENT >::actions_before_newton_solve () inline virtual
Update the problem specs before solve (empty)
Reimplemented from oomph::Problem.
 {}
adapt() [1/2]
template<class ELEMENT > void UnsteadyHeatProblem< ELEMENT >::adapt () inline
A wrapper around the Problem's adapt(...) function; issue a warning that adaptation doesn't work for these elements
   {
     // Create an output stream
     std::ostringstream warning_message_stream;
     // Create an error message
     warning_message_stream << "Hey, adaptation doesn't work properly with "
                            << "Petrov-Galerkin elements!\nI'm not going to "
                            << "stop the simulation because you may already "
                            << "know this\nbut if you didn't, consider "
                            << "yourself warned!" << std::endl;
     // Throw an error
     OomphLibWarning(warning_message_stream.str(),
                     OOMPH_CURRENT_FUNCTION,
                     OOMPH_EXCEPTION_LOCATION);
     // Call the Problem's implementation of refine_uniformly(...)
     Problem::adapt();
   } // End of adapt
References oomph::Problem::adapt(), OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
adapt() [2/2]
template<class ELEMENT > void UnsteadyHeatProblem< ELEMENT >::adapt () inline
A wrapper around the Problem's adapt(...) function; issue a warning that adaptation doesn't work for these elements
   {
     // Create an output stream
     std::ostringstream warning_message_stream;
     // Create an error message
     warning_message_stream << "Hey, adaptation doesn't work properly with "
                            << "Petrov-Galerkin elements!\nI'm not going to "
                            << "stop the simulation because you may already "
                            << "know this\nbut if you didn't, consider "
                            << "yourself warned!" << std::endl;
     // Throw an error
     OomphLibWarning(warning_message_stream.str(),
                     OOMPH_CURRENT_FUNCTION,
                     OOMPH_EXCEPTION_LOCATION);
     // Call the Problem's implementation of refine_uniformly(...)
     Problem::adapt();
   } // End of adapt
References oomph::Problem::adapt(), OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
apply_boundary_conditions() [1/3]
template<class ELEMENT > void UnsteadyHeatProblem< ELEMENT >::apply_boundary_conditions
Assign the Dirichlet and maybe time-periodic BCs.
Apply the Dirichlet conditions on the spatial boundaries and the initial time boundary, if specified, otherwise apply time-periodic boundary conditions on the time boundaries. More explicitly: Boundary 0 (t=0) – Dirichlet or time-periodic BCs Boundary 1 (y=0) – Dirichlet Boundary 2 (x=1) – Dirichlet Boundary 3 (y=1) – Dirichlet Boundary 4 (x=0) – Dirichlet Boundary 5 (t=1) – Do nothing!
 {
   // Number of spatial dimensions
   unsigned n_dim=2;
   // Storage for the time
   double time=0.0;
   // Storage for the spatial coordinates
   Vector<double> spatial_coordinates(n_dim,0.0);
   // Storage for the solution
   double u_exact=0.0;
   // Get the number of boundaries in the mesh
   unsigned n_bound=Bulk_mesh_pt->nboundary();
   // Loop over the boundaries
   for (unsigned b=0; b<n_bound; b++)
   {
     // Get the number of nodes on the b-th boundary
     unsigned n_node=Bulk_mesh_pt->nboundary_node(b);
     // Don't do anything on the final time boundary
     if (b!=Final_time_boundary_id)
     {
       // If we're applying time-periodic boundary conditions and we're
       if ((GlobalParameters::Apply_time_periodic_boundary_conditions)&&
           (b==Initial_time_boundary_id))
       {
         // We need to apply time-periodic BCs
         enforce_time_periodic_boundary_conditions();
       }
       // Otherwise apply Dirichlet boundary conditions
       else
       {
         // Loop over the nodes on the b-th boundary
         for (unsigned n=0; n<n_node; n++)
         {
           // Get a pointer to the n-th node on the b-th boundary
           Node* node_pt=Bulk_mesh_pt->boundary_node_pt(b,n);
           // Pin the (one and only) dof at this node!
           node_pt->pin(0);
           // Loop over the coordinates
           for (unsigned i=0; i<n_dim; i++)
           {
             // Get the i-th coordinate of the node
             spatial_coordinates[i]=node_pt->x(i);
           }
           // Get the current time
           time=node_pt->x(n_dim);
           // Get the exact solution at this node
           SinSolution::get_exact_u(time,spatial_coordinates,u_exact);
           // Set the value of the solution
           node_pt->set_value(0,u_exact);
         }
       } // if ((GlobalParameters::Apply_time_periodic_boundary_conditions)&&
     } // if (b!=Final_time_boundary_id)
   } // for (unsigned b=0;b<n_bound;b++)
 } // End of apply_boundary_conditions
References GlobalParameters::Apply_time_periodic_boundary_conditions, b, SinSolution::get_exact_u(), i, n, oomph::Data::pin(), oomph::Data::set_value(), and oomph::Node::x().
Referenced by UnsteadyHeatProblem< ELEMENT >::UnsteadyHeatProblem().
apply_boundary_conditions() [2/3]
template<class ELEMENT > void UnsteadyHeatProblem< ELEMENT >::apply_boundary_conditions ()
Assign the Dirichlet and maybe time-periodic BCs.
apply_boundary_conditions() [3/3]
template<class ELEMENT > void UnsteadyHeatProblem< ELEMENT >::apply_boundary_conditions ()
Assign the Dirichlet and maybe time-periodic BCs.
assign_time_slab_id() [1/2]
template<class ELEMENT > void UnsteadyHeatProblem< ELEMENT >::assign_time_slab_id
Helper function when space-time block preconditioning is being used.
Assign the time slice IDs to each BlockPreconditionable element.
 {
   // Number of dimensions
   const unsigned n_dim=3;
   // The ID of the coordinate we want, i.e. the ID of the time-direction
   const unsigned t_index=n_dim-1;
   // Space for the local coordinates (at the center of the element)
   Vector<double> s(n_dim,0.0);
   // Space for the (Eulerian) coordinates
   double t=0.0;
   // Get the number of elements in the mesh
   const unsigned n_element=Bulk_mesh_pt->nelement();
   // Loop over the elements
   for (unsigned i=0; i<n_element; i++)
   {
     // Upcast the element
     ELEMENT* const el_pt=dynamic_cast<ELEMENT*>(Bulk_mesh_pt->element_pt(i));
     // Get the interpolated time value at the center of the element
     t=el_pt->interpolated_x(s,t_index);
     // The idea is to group all dofs in each space-time slab together, by
     // making sure that elements in the same space-time slab have the same ID
     // To ensure this is done correctly, we provide an offset. Note, however
     unsigned id=std::floor((double(N_space_time_slab)*t)/
                            GlobalParameters::L_t);
     // Upcast and assign the time slice ID
     el_pt->set_time_slab_id(id);
     // We're grouping dofs in each space-time slab together and there are only
     // "N_space_time_slab" space-time slabs
     GlobalParameters::N_dof_type=N_space_time_slab;
     // Finally, tell it how many dof types there are in the mesh
     el_pt->set_ndof_types(GlobalParameters::N_dof_type);
   } // for (unsigned i=0;i<n_element;i++)
 } // End of assign_time_slab_id
References Eigen::bfloat16_impl::floor(), i, GlobalParameters::L_t, GlobalParameters::N_dof_type, s, and plotPSD::t.
assign_time_slab_id() [2/2]
template<class ELEMENT > void UnsteadyHeatProblem< ELEMENT >::assign_time_slab_id ()
Helper function when space-time block preconditioning is being used.
complete_problem_setup() [1/4]
template<class ELEMENT > void UnsteadyHeatProblem< ELEMENT >::complete_problem_setup inline private
Complete problem setup: pass pointers to physical variables.
Helper function to (re-)set boundary condition and complete the build of all elements
   {
    // Loop over the flux elements to pass pointer to prescribed flux function
    unsigned n_element=Surface_melt_mesh_pt->nelement();
    for(unsigned e=0;e<n_element;e++)
     {
      // Upcast from GeneralisedElement to UnsteadyHeat flux element
      UnsteadyHeatFluxPseudoMeltElement<ELEMENT> *el_pt =
       dynamic_cast<UnsteadyHeatFluxPseudoMeltElement<ELEMENT>*>(
        Surface_melt_mesh_pt->element_pt(e));
      // Set the pointer to the prescribed flux function
      el_pt->flux_fct_pt() = &ProblemParameters::flux;
      // Set melt temperature
      el_pt->melt_temperature_pt()=&ProblemParameters::Melt_temperature;
      // Suppress melting?
      if (CommandLineArgs::command_line_flag_has_been_set("--disable_melting"))
       {
        el_pt->disable_melting();
       }
     }
    // Loop over the flux elements to pass pointer to prescribed flux function
    n_element=Surface_mesh_pt->nelement();
    for(unsigned e=0;e<n_element;e++)
     {
      if (CommandLineArgs::command_line_flag_has_been_set("--melt_everywhere"))
       {
        // Upcast from GeneralisedElement to UnsteadyHeat flux element
        UnsteadyHeatFluxPseudoMeltElement<ELEMENT> *el_pt =
         dynamic_cast<UnsteadyHeatFluxPseudoMeltElement<ELEMENT>*>(
          Surface_mesh_pt->element_pt(e));
        // Set the pointer to the prescribed flux function
        el_pt->flux_fct_pt() = &ProblemParameters::flux;
        // Set melt temperature
        el_pt->melt_temperature_pt()=&ProblemParameters::Melt_temperature;
        // Suppress melting?
        if (CommandLineArgs::command_line_flag_has_been_set("--disable_melting"))
         {
          el_pt->disable_melting();
         }
       }
      else
       {
        // Upcast from GeneralisedElement to UnsteadyHeat flux element
        UnsteadyHeatFluxElement<ELEMENT> *el_pt =
         dynamic_cast<UnsteadyHeatFluxElement<ELEMENT>*>(
          Surface_mesh_pt->element_pt(e));
        // Set the pointer to the prescribed flux function
        el_pt->flux_fct_pt() = &ProblemParameters::flux;
       }
     }
   }
References oomph::CommandLineArgs::command_line_flag_has_been_set(), oomph::UnsteadyHeatFluxPseudoMeltElement< ELEMENT >::disable_melting(), e(), ProblemParameters::flux(), oomph::UnsteadyHeatFluxPseudoMeltElement< ELEMENT >::flux_fct_pt(), oomph::UnsteadyHeatFluxElement< ELEMENT >::flux_fct_pt(), ProblemParameters::Melt_temperature, and oomph::UnsteadyHeatFluxPseudoMeltElement< ELEMENT >::melt_temperature_pt().
Referenced by UnsteadyHeatProblem< ELEMENT >::UnsteadyHeatProblem().
complete_problem_setup() [2/4]
template<class ELEMENT > void UnsteadyHeatProblem< ELEMENT >::complete_problem_setup ()
Complete problem setup; make all the elements fully functional by passing pointers to all physical parameters
complete_problem_setup() [3/4]
template<class ELEMENT > void UnsteadyHeatProblem< ELEMENT >::complete_problem_setup ()
Complete problem setup; make all the elements fully functional by passing pointers to all physical parameters
complete_problem_setup() [4/4]
template<class ELEMENT > void UnsteadyHeatProblem< ELEMENT >::complete_problem_setup ()
Complete problem setup; make all the elements fully functional by passing pointers to all physical parameters
create_flux_elements() [1/2]
template<class ELEMENT > void UnsteadyHeatProblem< ELEMENT >::create_flux_elements inline private
Create flux elements.
   {
    // How many bulk elements are adjacent to boundary b?
    unsigned b=Melt_boundary_id;
    unsigned n_element = Bulk_mesh_pt->nboundary_element(b);
    // Loop over the bulk elements adjacent to boundary b?
    for(unsigned e=0;e<n_element;e++)
     {
      // Get pointer to the bulk element that is adjacent to boundary b
      ELEMENT* bulk_elem_pt = dynamic_cast<ELEMENT*>(
       Bulk_mesh_pt->boundary_element_pt(b,e));
      //What is the face index of element e along boundary b
      int face_index = Bulk_mesh_pt->face_index_at_boundary(b,e);
      // Build the corresponding prescribed-flux element
      UnsteadyHeatFluxPseudoMeltElement<ELEMENT>* flux_element_pt = new
       UnsteadyHeatFluxPseudoMeltElement<ELEMENT>(bulk_elem_pt,face_index);
      //Add the prescribed-flux element to the surface mesh
      Surface_melt_mesh_pt->add_element_pt(flux_element_pt);
     } //end of loop over bulk elements adjacent to boundary b
    // How many bulk elements are adjacent to boundary b?
    b=Flux_boundary_id;
    n_element = Bulk_mesh_pt->nboundary_element(b);
    // Loop over the bulk elements adjacent to boundary b?
    for(unsigned e=0;e<n_element;e++)
     {
      // Get pointer to the bulk element that is adjacent to boundary b
      ELEMENT* bulk_elem_pt = dynamic_cast<ELEMENT*>(
       Bulk_mesh_pt->boundary_element_pt(b,e));
      //What is the face index of element e along boundary b
      int face_index = Bulk_mesh_pt->face_index_at_boundary(b,e);
      if (CommandLineArgs::command_line_flag_has_been_set("--melt_everywhere"))
       {
        // Build the corresponding prescribed-flux element
        UnsteadyHeatFluxPseudoMeltElement<ELEMENT>* flux_element_pt = new
         UnsteadyHeatFluxPseudoMeltElement<ELEMENT>(bulk_elem_pt,face_index);
        //Add the prescribed-flux element to the surface mesh
        Surface_mesh_pt->add_element_pt(flux_element_pt);
       }
      else
       {
        // Build the corresponding prescribed-flux element
        UnsteadyHeatFluxElement<ELEMENT>* flux_element_pt = new
         UnsteadyHeatFluxElement<ELEMENT>(bulk_elem_pt,face_index);
        //Add the prescribed-flux element to the surface mesh
        Surface_mesh_pt->add_element_pt(flux_element_pt);
       }
     } //end of loop over bulk elements adjacent to boundary b
   }
References b, oomph::CommandLineArgs::command_line_flag_has_been_set(), and e().
Referenced by UnsteadyHeatProblem< ELEMENT >::UnsteadyHeatProblem().
create_flux_elements() [2/2]
template<class ELEMENT > void UnsteadyHeatProblem< ELEMENT >::create_flux_elements ()
Create flux elements.
create_spacetime_mesh() [1/3]
template<class ELEMENT > void UnsteadyHeatProblem< ELEMENT >::create_spacetime_mesh
Create the space-time mesh with the chosen number of elements in the time direction and the chosen spatial resolution
Helper function to create the space-time mesh (to be assigned to Bulk_mesh_pt) with the chosen number of elements in the time direction and an appropriate spatial resolution (to capture the time-periodic solution properly).
 {
   // Build the refineable mesh
   Bulk_mesh_pt=new RefineableSimpleCubicMesh<ELEMENT>
   (GlobalParameters::N_x,GlobalParameters::N_y,GlobalParameters::N_t,
    GlobalParameters::L_x,GlobalParameters::L_y,GlobalParameters::L_t);
   // Assign the mesh pointer
   mesh_pt()=Bulk_mesh_pt;
   // Add an error estimator
   Bulk_mesh_pt->spatial_error_estimator_pt()=new Z2ErrorEstimator;
   // Maximum permitted errors
   Bulk_mesh_pt->max_permitted_error()=1.0e-03;
   // Minimum permitted errors
   Bulk_mesh_pt->min_permitted_error()=1.0e-04;
 } // End of create_spacetime_mesh
References GlobalParameters::L_t, GlobalParameters::L_x, GlobalParameters::L_y, GlobalParameters::N_t, GlobalParameters::N_x, and GlobalParameters::N_y.
Referenced by UnsteadyHeatProblem< ELEMENT >::UnsteadyHeatProblem().
create_spacetime_mesh() [2/3]
template<class ELEMENT > void UnsteadyHeatProblem< ELEMENT >::create_spacetime_mesh ()
Create the space-time mesh with the chosen number of elements in the time direction and the chosen spatial resolution
create_spacetime_mesh() [3/3]
template<class ELEMENT > void UnsteadyHeatProblem< ELEMENT >::create_spacetime_mesh ()
Create the space-time mesh with the chosen number of elements in the time direction and the chosen spatial resolution
delete_flux_elements()
template<class ELEMENT > void UnsteadyHeatProblem< ELEMENT >::delete_flux_elements () inline private
Delete flux elements.
   {
    // How many surface elements are in the surface mesh
    unsigned n_element = Surface_melt_mesh_pt->nelement();
    // Loop over the surface elements
    for(unsigned e=0;e<n_element;e++)
     {
      // Kill surface element
      delete Surface_melt_mesh_pt->element_pt(e);
     }
    // Wipe the mesh
    Surface_melt_mesh_pt->flush_element_and_node_storage();
    // How many surface elements are in the surface mesh
    n_element = Surface_mesh_pt->nelement();
    // Loop over the surface elements
    for(unsigned e=0;e<n_element;e++)
     {
      // Kill surface element
      delete Surface_mesh_pt->element_pt(e);
     }
    // Wipe the mesh
    Surface_mesh_pt->flush_element_and_node_storage();
   }
References e().
disable_ALE()
template<class ELEMENT > void UnsteadyHeatProblem< ELEMENT >::disable_ALE () inline
Switch off ALE terms.
   {
    std::cout << "Disabling ALE " << std::endl;
    // Loop over the elements
    unsigned n_element = mesh_pt()->nelement();
    for(unsigned i=0;i<n_element;i++)
     {
      // Upcast from FiniteElement to the present element
      ELEMENT *el_pt = dynamic_cast<ELEMENT*>(mesh_pt()->element_pt(i));
      //Set the source function pointer
      el_pt->disable_ALE();
     }
   }
References i.
doc_solution() [1/9]
template<class ELEMENT > void UnsteadyHeatProblem< ELEMENT >::doc_solution (const bool & doc_error = false)
Doc the solution.
Document the solution.
 {
   // Make an ofstream object to output the solution
   ofstream some_file;
   // Storage for the filename
   char filename[100];
   // The number of plot points
   unsigned n_plot_point=2;
   // The filename suffix added depending on the BCs we're using
   std::string filename_suffix="";
   // If we're solving the time-periodic problem
   if (GlobalParameters::Apply_time_periodic_boundary_conditions)
   {
     // Set the suffix
     filename_suffix="_pbc";
   }
   // If we're solving the initial-value problem
   else
   {
     // Set the suffix
     filename_suffix="_ic";
   }
   //----------------
   // Output solution
   //----------------
   // If we're solving the time-periodic problem
   if (GlobalParameters::Apply_time_periodic_boundary_conditions)
   {
     // Output the (numerically) approximated solution
     sprintf(filename,"%s/soln%s%i.dat",
             GlobalParameters::Doc_info.directory().c_str(),
             filename_suffix.c_str(),
             GlobalParameters::Doc_info.number());
   }
   // If we're solving the initial-value problem
   else
   {
     // Output the (numerically) approximated solution
     sprintf(filename,"%s/soln_ic%i.dat",
             GlobalParameters::Doc_info.directory().c_str(),
             GlobalParameters::Doc_info.number());
   }
   // Open the file
   some_file.open(filename);
   // Output the solution
   Bulk_mesh_pt->output(some_file,n_plot_point);
   // Now close the file
   some_file.close();
   //----------------------
   // Output exact solution
   //----------------------
   // Output the exact solution
   sprintf(filename,"%s/exact_soln%i.dat",
           GlobalParameters::Doc_info.directory().c_str(),
           GlobalParameters::Doc_info.number());
   // Open the file
   some_file.open(filename);
   // Dummy time value
   double dummy_time=0.0;
   // Output the exact solution
   Bulk_mesh_pt->output_fct(some_file,
                            n_plot_point,
                            dummy_time,
                            SinSolution::get_exact_u);
   // Now close the file
   some_file.close();
   //-------------------
   // Document the error
   //-------------------
   // Storage for the norm and the solution and the error
   double norm=0.0, error=0.0;
   // Output the error
   sprintf(filename,"%s/error%s%i.dat",
           GlobalParameters::Doc_info.directory().c_str(),
           filename_suffix.c_str(),
           GlobalParameters::Doc_info.number());
   // Open the file
   some_file.open(filename);
   // Compute the error in the solution
   Bulk_mesh_pt->compute_error(some_file,
                               SinSolution::get_exact_u,
                               dummy_time,
                               error,norm);
   // Now close the file
   some_file.close();
   //------------------------
   // Doc. solution and error
   //------------------------
   // Calculate the norm value we want
   norm=std::sqrt(norm);
   // Square root the error value
   error=std::sqrt(error);
   // Output the solution norm and error values
   oomph_info << "Solution norm : " << norm << std::endl;
   oomph_info << "Absolute error: " << error << std::endl;
   oomph_info << "Relative error: " << error/norm << std::endl;
   // Increment counter for solutions
   GlobalParameters::Doc_info.number()++;
 } // End of doc_solution
References GlobalParameters::Apply_time_periodic_boundary_conditions, GlobalParameters::Doc_info, calibrate::error, MergeRestartFiles::filename, SinSolution::get_exact_u(), oomph::DocInfo::number(), oomph::oomph_info, sqrt(), and oomph::Global_string_for_annotation::string().
doc_solution() [2/9]
template<class ELEMENT > void UnsteadyHeatProblem< ELEMENT >::doc_solution (const bool & doc_error = false)
Doc the solution.
doc_solution() [3/9]
template<class ELEMENT > void UnsteadyHeatProblem< ELEMENT >::doc_solution (const bool & doc_error = false)
Doc the solution.
doc_solution() [4/9]
template<class ELEMENT > void UnsteadyHeatProblem< ELEMENT >::doc_solution (DocInfo & doc_info)
Doc the solution.
 {
  ofstream some_file;
  char filename[100];
  // Number of plot points
  unsigned npts;
  npts=5;
  cout << std::endl;
  cout << "=================================================" << std::endl;
  cout << "Docing solution for t=" << time_pt()->time() << std::endl;
  cout << "=================================================" << std::endl;
  // Output solution
  sprintf(filename,"%s/soln%i.dat",doc_info.directory().c_str(),
          doc_info.number());
  some_file.open(filename);
  Bulk_mesh_pt->output(some_file,npts);
  some_file.close();
  // Output solution coarsely (only element vertices for easier
  // mesh visualisation)
  sprintf(filename,"%s/coarse_soln%i.dat",doc_info.directory().c_str(),
          doc_info.number());
  some_file.open(filename);
  Bulk_mesh_pt->output(some_file,2);
  some_file.close();
  // Output flux with melt
  sprintf(filename,"%s/flux_with_melt%i.dat",doc_info.directory().c_str(),
          doc_info.number());
  some_file.open(filename);
  unsigned nnod=dynamic_cast<UnsteadyHeatFluxPseudoMeltElement<ELEMENT>*>(
   Surface_melt_mesh_pt->element_pt(0))->nnode();
  Surface_melt_mesh_pt->output(some_file,nnod);
  if (CommandLineArgs::command_line_flag_has_been_set("--melt_everywhere"))
   {
    Surface_mesh_pt->output(some_file,nnod);
   }
  some_file.close();
  // Output Number of Newton iterations in form that can be visualised
  // as vector in paraview
  sprintf(filename,"%s/newton_iter%i.dat",doc_info.directory().c_str(),
          doc_info.number());
  some_file.open(filename);
  some_file << "0 0 0 " << Nnewton_iter_taken << std::endl;
  some_file.close();
  // Write norm of solution to trace file
  double norm=0.0;
  Bulk_mesh_pt->compute_norm(norm);
  Trace_file  << norm << std::endl;
 } // end of doc_solution
References oomph::CommandLineArgs::command_line_flag_has_been_set(), oomph::DocInfo::directory(), MergeRestartFiles::filename, oomph::DocInfo::number(), and oomph::Problem_Parameter::Trace_file.
doc_solution() [5/9]
template<class ELEMENT > void UnsteadyHeatProblem< ELEMENT >::doc_solution (DocInfo & doc_info, ofstream & trace_file)
Doc the solution.
 {
  ofstream some_file;
  char filename[100];
  // Number of plot points
  unsigned npts;
  npts=5;
  cout << std::endl;
  cout << "=================================================" << std::endl;
  cout << "Docing solution for t=" << time_pt()->time() << std::endl;
  cout << "=================================================" << std::endl;
  // Output solution
  //-----------------
  sprintf(filename,"%s/soln%i.dat",doc_info.directory().c_str(),
          doc_info.number());
  some_file.open(filename);
  Bulk_mesh_pt->output(some_file,npts);
  // Write file as a tecplot text object
  some_file << "TEXT X=2.5,Y=93.6,F=HELV,HU=POINT,C=BLUE,H=26,T=\"time = "
            << time_pt()->time() << "\"";
  // ...and draw a horizontal line whose length is proportional
  // to the elapsed time
  some_file << "GEOMETRY X=2.5,Y=98,T=LINE,C=BLUE,LT=0.4" << std::endl;
  some_file << "1" << std::endl;
  some_file << "2" << std::endl;
  some_file << " 0 0" << std::endl;
  some_file << time_pt()->time()*20.0 << " 0" << std::endl;
  some_file.close();
  // Output exact solution
  //----------------------
  sprintf(filename,"%s/exact_soln%i.dat",doc_info.directory().c_str(),
          doc_info.number());
  some_file.open(filename);
  Bulk_mesh_pt->output_fct(some_file,npts,time_pt()->time(),
                        ExactSolnForUnsteadyHeat::get_exact_u);
  some_file.close();
  // Doc error
  //----------
  double error,norm;
  sprintf(filename,"%s/error%i.dat",doc_info.directory().c_str(),
          doc_info.number());
  some_file.open(filename);
  Bulk_mesh_pt->compute_error(some_file,
                           ExactSolnForUnsteadyHeat::get_exact_u,
                           time_pt()->time(),
                           error,norm);
  some_file.close();
  // Doc solution and error
  //-----------------------
  cout << "error: " << error << std::endl;
  cout << "norm : " << norm << std::endl << std::endl;
  // Get exact solution at control node
  Vector<double> x_ctrl(2);
  x_ctrl[0]=Control_node_pt->x(0);
  x_ctrl[1]=Control_node_pt->x(1);
  double u_exact;
  ExactSolnForUnsteadyHeat::get_exact_u(time_pt()->time(),x_ctrl,u_exact);
  trace_file << time_pt()->time() << " "
             << Control_node_pt->value(0) << " "
             << u_exact << " "
             << error   << " "
             << norm    << std::endl;
 } // end of doc_solution
References oomph::DocInfo::directory(), calibrate::error, MergeRestartFiles::filename, ExactSolnForUnsteadyHeat::get_exact_u(), and oomph::DocInfo::number().
doc_solution() [6/9]
template<class ELEMENT > void UnsteadyHeatProblem< ELEMENT >::doc_solution (DocInfo & doc_info, ofstream & trace_file)
Doc the solution.
doc_solution() [7/9]
template<class ELEMENT > void UnsteadyHeatProblem< ELEMENT >::doc_solution (DocInfo & doc_info, ofstream & trace_file)
Doc the solution.
doc_solution() [8/9]
template<class ELEMENT > void UnsteadyHeatProblem< ELEMENT >::doc_solution (DocInfo & doc_info, ofstream & trace_file)
Doc the solution.
doc_solution() [9/9]
template<class ELEMENT > void UnsteadyHeatProblem< ELEMENT >::doc_solution (DocInfo & doc_info, ofstream & trace_file)
Doc the solution.
dump_it() [1/2]
template<class ELEMENT > void UnsteadyHeatProblem< ELEMENT >::dump_it (ofstream & dump_file)
Dump problem to disk to allow for restart.
Dump the solution to disk to allow for restart.
 {
  // Call generic dump()
  Problem::dump(dump_file);
 } // end of dump_it
dump_it() [2/2]
template<class ELEMENT > void UnsteadyHeatProblem< ELEMENT >::dump_it (ofstream & dump_file)
Dump problem to disk to allow for restart.
enforce_time_periodic_boundary_conditions() [1/3]
template<class ELEMENT > void UnsteadyHeatProblem< ELEMENT >::enforce_time_periodic_boundary_conditions
Assign the appropriate boundary conditions and enforce periodicity in the time direction
Assign the appropriate boundary conditions, i.e. periodicity in the t-direction. In the x and y-direction apply Dirichlet boundary conditions. In summary: Boundary 0 (t=0) – Periodic in time (w.r.t. boundary 5) Boundary 1 (y=0) – Dirichlet Boundary 2 (x=1) – Dirichlet Boundary 3 (y=1) – Dirichlet Boundary 4 (x=0) – Dirichlet Boundary 5 (t=1) – Periodic in time (w.r.t. boundary 0)
 {
   // If we need to set up periodicity
   if (!Periodicity_has_been_enforced)
   {
     // Number of dimensions
     unsigned n_dim=3;
     // Index of the t=0 boundary
     unsigned boundary0_index=0;
     // Index of the t=1 boundary
     unsigned boundary1_index=5;
     // Number of nodes on t=0 boundary
     unsigned n_boundary0_node=Bulk_mesh_pt->nboundary_node(boundary0_index);
     // Number of nodes on t=1 boundary
     unsigned n_boundary1_node=Bulk_mesh_pt->nboundary_node(boundary1_index);
     //----------------------------
     // Establish nodal periodicity
     //----------------------------
     // Make sure there are as many nodes on boundary 0 as there are on
     // boundary (n_boundary-1)
     if (n_boundary0_node!=n_boundary1_node)
     {
       // Create an output stream
       std::ofstream output_file;
       // Open a file
       output_file.open("RESLT/nodes_b0.csv");
       // Loop over the nodes on the t=0 boundary
       for (unsigned i=0; i<n_boundary0_node; i++)
       {
         // Output the coordinates of the i-th node on the t=0 boundary
         Bulk_mesh_pt->boundary_node_pt(boundary0_index,i)->output(output_file);
       }
       // Close the file
       output_file.close();
       // Open a file
       output_file.open("RESLT/nodes_b1.csv");
       // Loop over the nodes on the t=0 boundary
       for (unsigned i=0; i<n_boundary1_node; i++)
       {
         // Output the coordinates of the i-th node on the t=1 boundary
         Bulk_mesh_pt->boundary_node_pt(boundary1_index,i)->output(output_file);
       }
       // Close the file
       output_file.close();
       // Create an output stream
       std::ostringstream error_message_stream;
       // Create an error message
       error_message_stream << "Different number of nodes on t=0 and t=1 "
                            << "boundary!\nThere are " << n_boundary0_node
                            << " nodes on boundary " << boundary0_index
                            << " and " << n_boundary1_node
                            << " nodes on boundary " << boundary1_index
                            << "!" << std::endl;
       // Throw an error
       throw OomphLibError(error_message_stream.str(),
                           OOMPH_CURRENT_FUNCTION,
                           OOMPH_EXCEPTION_LOCATION);
     }
     // Loop over the nodes on the t=0 boundary
     for (unsigned i=0; i<n_boundary0_node; i++)
     {
       // Get the pointer to the associated node
       Node* node0_pt=Bulk_mesh_pt->boundary_node_pt(boundary0_index,i);
       // Boolean to indicate whether or not the neighbour has been found
       bool has_neighbour_node_been_found=false;
       // Loop over the nodes on the t=1 boundary
       for (unsigned j=0; i<n_boundary1_node; j++)
       {
         // Get the pointer to the associated node
         Node* node1_pt=Bulk_mesh_pt->boundary_node_pt(boundary1_index,j);
         // Distance value
         double distance=0.0;
         // Loop over the entries of x
         for (unsigned k=0; k<n_dim-1; k++)
         {
           // Update the distance (2 norm)
           distance+=pow(((node0_pt->x(k))-(node1_pt->x(k))),2.0);
         }
         // Square root it
         distance=std::sqrt(distance);
         // Check if it matches to within a reasonable tolerance
         if (std::fabs(distance)<Tree::max_neighbour_finding_tolerance())
         {
           // Make the nodes periodic; the node on the t=1 boundary now points
           // to the node on the t=0 boundary.
           //node1_pt->make_periodic(node0_pt);
           // DRAIG: NEW ORDER!!!
           node0_pt->make_periodic(node1_pt);
           // We've found the neighbouring node
           has_neighbour_node_been_found=true;
           // We're done; break out!
           break;
         }
       } // for (unsigned i=0;i<n_boundary0_node;i++)
       // If we get here and we haven't found the neighbouring node, something's
       // wrong so throw an error
       if (!has_neighbour_node_been_found)
       {
         // Throw an error
         throw OomphLibError("Couldn't find neighbouring node!",
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
     } // for (unsigned i=0;i<n_boundary0_node;i++)
     //--------------------------------
     // Establish elemental periodicity
     //--------------------------------
     // Number of elements on t=0 boundary
     unsigned n_boundary0_element=
       Bulk_mesh_pt->nboundary_element(boundary0_index);
     // Number of elements on t=1 boundary
     unsigned n_boundary1_element=
       Bulk_mesh_pt->nboundary_element(boundary1_index);
     // Make sure there are as many nodes on boundary 0 as there are on
     // boundary (n_boundary-1)
     if (n_boundary0_element!=n_boundary1_element)
     {
       // Throw an error
       throw OomphLibError("Different number of elements on time boundaries!",
                           OOMPH_CURRENT_FUNCTION,
                           OOMPH_EXCEPTION_LOCATION);
     }
     // Storage for the local coordinates of the centre of the face of the
     // element on the t=0 boundary
     Vector<double> s_back(n_dim,0.0);
     // Storage for the local coordinates of the centre of the face of the
     // element on the t=1 boundary
     Vector<double> s_front(n_dim,0.0);
     // The t=0 boundary corresponds to the s[n_dim-1]=-1 (in the
     // appropriate element)
     s_back[n_dim-1]=-1.0;
     // The t=1 boundary corresponds to the s[n_dim-1]=1 (in the
     // appropriate element)
     s_front[n_dim-1]=1.0;
     // Loop over the elements on t=0 boundary
     for (unsigned i=0; i<n_boundary0_element; i++)
     {
       // Get a pointer to the associated element
       FiniteElement* el0_pt=Bulk_mesh_pt->boundary_element_pt(boundary0_index,i);
       // Boolean to indicate whether or not the neighbour has been found
       bool has_neighbour_element_been_found=false;
       // Loop over the elements on t=1 boundary
       for (unsigned j=0; j<n_boundary1_element; j++)
       {
         // Get a pointer to the associated element
         FiniteElement* el1_pt=Bulk_mesh_pt->boundary_element_pt(boundary1_index,j);
         // Distance value
         double distance=0.0;
         // Loop over the entries of x
         for (unsigned k=0; k<n_dim-1; k++)
         {
           // Update the distance (2 norm)
           distance+=pow((el0_pt->interpolated_x(s_back,k))-
                         (el1_pt->interpolated_x(s_front,k)),2.0);
         }
         // Square root it
         distance=std::sqrt(distance);
         // Check if it matches to within a reasonable tolerance
         if (std::fabs(distance)<Tree::max_neighbour_finding_tolerance())
         {
           //-----------------------------------------------------------
           //                   ...FACE NEIGHBOURS...
           //-----------------------------------------------------------
           //-----------------------------------------------------------
           // First task: Set the periodicity in the face direction
           // and assign the neighbour pointers.
           //-----------------------------------------------------------
           // Variable to hold the face direction of the neighbouring element
           // from the perspective of the current element (t=1 boundary element)
           int direction1=OcTreeNames::F;
           // Set the periodicity between the neighbouring OcTree objects and
           // set the up/right equivalents of the elements (it is assumed that
           // the elements are both oriented in the same way -- seems reasonable
           // for an extruded mesh)
           set_neighbour_periodic_and_up_right_equivalents(el1_pt,el0_pt,
               direction1);
           //-----------------------------------------------------------
           //                   ...EDGE NEIGHBOURS...
           //-----------------------------------------------------------
           //-----------------------------------------------------------
           // First task: Find an element on the t=0 boundary and its
           // corresponding element on the t=1 boundary in a given edge
           // direction. We already have a pointer to the element on the
           // back face (t=0 boundary) pointed to by el0_pt so we don't
           // need to calculate that. To get the edge neighbours (on the
           // t=1 boundary) we can simply use the OcTree data structure.
           //-----------------------------------------------------------
           // Pointer to the tree root associated with the element on
           // the t=0 boundary
           OcTreeRoot* octree0_pt=
             dynamic_cast<OcTreeRoot*>
             (dynamic_cast<ELEMENT*>(el0_pt)->tree_pt()->root_pt());
           // First edge direction
           direction1=OcTreeNames::LF;
           // If there's an face neighbour in the given direction
           if (octree0_pt->neighbour_pt(OcTreeNames::L)!=0)
           {
             // Get a pointer to the LF edge neighbour of the t=1 boundary element
             el0_pt=octree0_pt->neighbour_pt(OcTreeNames::L)->object_pt();
             // Set the periodicity between the neighbouring OcTree objects and
             // set the up/right equivalents of the elements (it is assumed that
             // the elements are both oriented in the same way -- seems reasonable
             // for an extruded mesh)
             set_neighbour_periodic_and_up_right_equivalents(
               el1_pt,el0_pt,direction1);
           }
           // Second edge direction
           direction1=OcTreeNames::RF;
           // If there's an face neighbour in the given direction
           if (octree0_pt->neighbour_pt(OcTreeNames::R)!=0)
           {
             // Get a pointer to the RF edge neighbour of the t=1 boundary element
             el0_pt=octree0_pt->neighbour_pt(OcTreeNames::R)->object_pt();
             // Set the periodicity between the neighbouring OcTree objects and
             // set the up/right equivalents of the elements
             set_neighbour_periodic_and_up_right_equivalents(
               el1_pt,el0_pt,direction1);
           }
           // Third edge direction
           direction1=OcTreeNames::DF;
           // If there's an face neighbour in the given direction
           if (octree0_pt->neighbour_pt(OcTreeNames::D)!=0)
           {
             // Get a pointer to the DF edge neighbour of the t=1 boundary element
             el0_pt=octree0_pt->neighbour_pt(OcTreeNames::D)->object_pt();
             // Set the periodicity between the neighbouring OcTree objects and
             // set the up/right equivalents of the elements
             set_neighbour_periodic_and_up_right_equivalents(
               el1_pt,el0_pt,direction1);
           }
           // Fourth edge direction
           direction1=OcTreeNames::UF;
           // If there's an face neighbour in the given direction
           if (octree0_pt->neighbour_pt(OcTreeNames::U)!=0)
           {
             // Get a pointer to the UF edge neighbour of the t=1 boundary element
             el0_pt=octree0_pt->neighbour_pt(OcTreeNames::U)->object_pt();
             // Set the periodicity between the neighbouring OcTree objects and
             // set the up/right equivalents of the elements
             set_neighbour_periodic_and_up_right_equivalents(
               el1_pt,el0_pt,direction1);
           }
           // We've found the neighbouring node
           has_neighbour_element_been_found=true;
           // We're done; break out!
           break;
         }
       } // for (unsigned j=0;j<n_boundary1_element;j++)
       // If we get here and we haven't found the neighbouring element,
       // something's wrong
       if (!has_neighbour_element_been_found)
       {
         // Throw an error
         throw OomphLibError("Couldn't find neighbouring element!",
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
     } // for (unsigned i=0;i<n_boundary0_element;i++)
     // Notify user
     oomph_info << "\nFinished enforcing periodicity!" << std::endl;
     // If we've got here then the periodicity has been set up
     Periodicity_has_been_enforced=true;
   } // if (!Periodicity_has_been_enforced)
 } // End of enforce_time_periodic_boundary_conditions
References D, oomph::OcTreeNames::DF, oomph::OcTreeNames::F, boost::multiprecision::fabs(), i, oomph::FiniteElement::interpolated_x(), j, k, L, oomph::OcTreeNames::LF, oomph::Node::make_periodic(), oomph::TreeRoot::neighbour_pt(), oomph::Tree::object_pt(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::oomph_info, Eigen::ArrayBase< Derived >::pow(), R, oomph::OcTreeNames::RF, sqrt(), RachelsAdvectionDiffusion::U, oomph::OcTreeNames::UF, and oomph::Node::x().
enforce_time_periodic_boundary_conditions() [2/3]
template<class ELEMENT > void UnsteadyHeatProblem< ELEMENT >::enforce_time_periodic_boundary_conditions ()
Assign the appropriate boundary conditions and enforce periodicity in the time direction
enforce_time_periodic_boundary_conditions() [3/3]
template<class ELEMENT > void UnsteadyHeatProblem< ELEMENT >::enforce_time_periodic_boundary_conditions ()
Assign the appropriate boundary conditions and enforce periodicity in the time direction
global_temporal_error_norm()
template<class ELEMENT > double UnsteadyHeatProblem< ELEMENT >::global_temporal_error_norm virtual
Global error norm for adaptive time-stepping.
Global error norm for adaptive timestepping: RMS error, based on difference between predicted and actual value at all nodes.
Reimplemented from oomph::Problem.
 {
  double global_error = 0.0;
  //Find out how many nodes there are in the problem
  unsigned n_node = mesh_pt()->nnode();
  //Loop over the nodes and calculate the estimated error in the values
  for(unsigned i=0;i<n_node;i++)
   {
    // Get error in solution: Difference between predicted and actual
    // value for nodal value 0
    double error = mesh_pt()->node_pt(i)->time_stepper_pt()->
     temporal_error_in_value(mesh_pt()->node_pt(i),0);
    //Add the square of the individual error to the global error
    global_error += error*error;
   }
  // Divide by the number of nodes
  global_error /= double(n_node);
  // Return square root...
  return sqrt(global_error);
 } // end of global_temporal_error_norm
References calibrate::error, i, and sqrt().
pin_redundant_temporal_nodes()
template<class ELEMENT > void UnsteadyHeatProblem< ELEMENT >::pin_redundant_temporal_nodes
The mixed order elements use linear interpolation in time so the only nodes which contribute to the unknowns in the system are those that lie on the temporal boundaries of the elements. Thus, all nodes that do not lie on these boundaries need to be pinned (otherwise we'd get zero rows in the system matrix making it singular...).
 {
   // Number of nodes in each direction
   unsigned n_node_1d=Bulk_mesh_pt->finite_element_pt(0)->nnode_1d();
   // Number of nodes in a space-time element
   unsigned n_el_node=Bulk_mesh_pt->finite_element_pt(0)->nnode();
   // Get the number of elements in the mesh
   unsigned n_element=Bulk_mesh_pt->nelement();
   unsigned i_nod_s=n_node_1d*n_node_1d;
   unsigned i_nod_e=n_el_node-n_node_1d*n_node_1d;
   // Loop over the elements
   for (unsigned i=0; i<n_element; i++)
   {
     // Loop over the nodes
     for (unsigned j=i_nod_s; j<i_nod_e; j++)
     {
       // Get a pointer to the j-th node in the i-th element
       Node* node_pt=Bulk_mesh_pt->finite_element_pt(i)->node_pt(j);
       // Pin the (only) unknown at this node
       node_pt->pin(0);
     }
   } // for (unsigned i=0;i<n_element;i++)
 } // End of pin_redundant_temporal_nodes
References i, j, and oomph::Data::pin().
refine_uniformly() [1/2]
template<class ELEMENT > void UnsteadyHeatProblem< ELEMENT >::refine_uniformly () inline
A wrapper around the Problem's refine_uniformly(...) function; update the number of space-time slabs after a uniform refinement so that the preconditioner solve the system more efficiently. NOTE: We don't implement this for
   {
     // The number of space-time slabs will double after this refinement
     N_space_time_slab*=2;
     // Call the Problem's implementation of refine_uniformly(...)
     Problem::refine_uniformly();
   } // End of refine_uniformly
References oomph::Problem::refine_uniformly().
refine_uniformly() [2/2]
template<class ELEMENT > void UnsteadyHeatProblem< ELEMENT >::refine_uniformly () inline
A wrapper around the Problem's refine_uniformly(...) function; update the number of space-time slabs after a uniform refinement so that the preconditioner solve the system more efficiently.
   {
     // The number of space-time slabs will double after this refinement
     N_space_time_slab*=2;
     // Call the Problem's implementation of refine_uniformly(...)
     Problem::refine_uniformly();
   } // End of refine_uniformly
References oomph::Problem::refine_uniformly().
restart() [1/2]
template<class ELEMENT > void UnsteadyHeatProblem< ELEMENT >::restart (ifstream & restart_file)
Read problem for restart from specified restart file.
Read solution from disk for restart.
 {
  // Read the generic problem data from restart file
  Problem::read(restart_file);
 } // end of restart
References Eigen::TensorSycl::internal::read().
restart() [2/2]
template<class ELEMENT > void UnsteadyHeatProblem< ELEMENT >::restart (ifstream & restart_file)
Read problem for restart from specified restart file.
set_initial_condition() [1/5]
template<class ELEMENT > void UnsteadyHeatProblem< ELEMENT >::set_initial_condition virtual
Set initial condition (incl previous timesteps) according to specified function.
Set initial condition: Assign previous and current values from exact solution.
Set initial condition: Assign previous and current values from exact solution or from restart file.
Reimplemented from oomph::Problem.
 {
  // Backup time in global Time object
  double backed_up_time=time_pt()->time();
  // Past history needs to be established for t=time0-deltat, ...
  // Then provide current values (at t=time0) which will also form
  // the initial guess for the first solve at t=time0+deltat
  // Vector of exact solution value
  Vector<double> soln(1);
  Vector<double> x(2);
  //Find number of nodes in mesh
  unsigned num_nod = Bulk_mesh_pt->nnode();
  // Set continuous times at previous timesteps:
  // How many previous timesteps does the timestepper use?
  int nprev_steps=time_stepper_pt()->nprev_values();
  Vector<double> prev_time(nprev_steps+1);
  for (int t=nprev_steps;t>=0;t--)
   {
    prev_time[t]=time_pt()->time(unsigned(t));
   }
  // Loop over current & previous timesteps
  for (int t=nprev_steps;t>=0;t--)
   {
    // Continuous time
    double time=prev_time[t];
    cout << "setting IC at time =" << time << std::endl;
    // Loop over the nodes to set initial guess everywhere
    for (unsigned n=0;n<num_nod;n++)
     {
      // Get nodal coordinates
      x[0]=Bulk_mesh_pt->node_pt(n)->x(0);
      x[1]=Bulk_mesh_pt->node_pt(n)->x(1);
      // Get exact solution at previous time
      ExactSolnForUnsteadyHeat::get_exact_u(time,x,soln);
      // Assign solution
      Bulk_mesh_pt->node_pt(n)->set_value(t,0,soln[0]);
      // Loop over coordinate directions: Mesh doesn't move, so
      // previous position = present position
      for (unsigned i=0;i<2;i++)
       {
        Bulk_mesh_pt->node_pt(n)->x(t,i)=x[i];
       }
     }
   }
  // Reset backed up time for global timestepper
  time_pt()->time()=backed_up_time;
 } // end of set_initial_condition
References ExactSolnForUnsteadyHeat::get_exact_u(), i, n, plotPSD::t, and plotDoE::x.
set_initial_condition() [2/5]
template<class ELEMENT > void UnsteadyHeatProblem< ELEMENT >::set_initial_condition () virtual
Set initial condition (incl previous timesteps) according to specified function.
Reimplemented from oomph::Problem.
set_initial_condition() [3/5]
template<class ELEMENT > void UnsteadyHeatProblem< ELEMENT >::set_initial_condition () virtual
Set initial condition (incl previous timesteps) according to specified function.
Reimplemented from oomph::Problem.
set_initial_condition() [4/5]
template<class ELEMENT > void UnsteadyHeatProblem< ELEMENT >::set_initial_condition () virtual
Set initial condition (incl previous timesteps) according to specified function.
Reimplemented from oomph::Problem.
set_initial_condition() [5/5]
template<class ELEMENT > void UnsteadyHeatProblem< ELEMENT >::set_initial_condition () virtual
Set initial condition (incl previous timesteps) according to specified function.
Reimplemented from oomph::Problem.
set_neighbour_periodic_and_up_right_equivalents() [1/3]
template<class ELEMENT > void UnsteadyHeatProblem< ELEMENT >::set_neighbour_periodic_and_up_right_equivalents (FiniteElement * el0_pt, FiniteElement * el1_pt, const int & direction0)
Function to set the periodicity between two octrees and assign the up and right equivalents to both elements
Function to set the periodicity between two octrees and assign the up and right equivalents to both elements. The arguments are the current element, the (i,j,k) coordinates of the neighbouring element and the direction to the neighbouring element.
 {
   // The direction from the element on the other face/edge
   int direction1=0;
   // If we're on a face
   if ((direction0>=OcTreeNames::L)&&(direction0<=OcTreeNames::F))
   {
     // Calculate the reflected face direction
     direction1=OcTree::Reflect_face[direction0];
   }
   // If we're on a edge
   else if ((direction0>=OcTreeNames::LB)&&(direction0<=OcTreeNames::UF))
   {
     // Calculate the reflected edge direction
     direction1=OcTree::Reflect_edge[direction0];
   }
   // We should never reach here
   else
   {
     // Throw an error
     throw OomphLibError("Not looking for a face or edge, something's wrong!",
                         OOMPH_CURRENT_FUNCTION,
                         OOMPH_EXCEPTION_LOCATION);
   }
   // Get the tree root of the second element
   OcTreeRoot* octree0_pt=dynamic_cast<OcTreeRoot*>
                          (dynamic_cast<ELEMENT*>(el0_pt)->tree_pt()->root_pt());
   // Get the tree root of the second element
   OcTreeRoot* octree1_pt=dynamic_cast<OcTreeRoot*>
                          (dynamic_cast<ELEMENT*>(el1_pt)->tree_pt()->root_pt());
   //--------------------------------------------------------------------
   // Set the periodicity between the neighbouring OcTree objects and
   // set the up/right equivalents of the elements (it is assumed that
   // the elements are both oriented in the same way -- seems reasonable
   // for a uniform cube mesh)
   //--------------------------------------------------------------------
   // The first element (at t=0) will be periodic in the direction direction0
   octree0_pt->set_neighbour_periodic(direction0);
   // The second element (at t=1) will be periodic in the direction direction1
   octree1_pt->set_neighbour_periodic(direction1);
   // If we're on a face
   if ((direction0>=OcTreeNames::L)&&(direction0<=OcTreeNames::F))
   {
     // Pass the tree root of the neighbouring element
     octree0_pt->neighbour_pt(direction0)=octree1_pt;
     // Pass the tree root of the neighbouring element
     octree1_pt->neighbour_pt(direction1)=octree0_pt;
   }
   // If we're on an edge
   else if ((direction0>=OcTreeNames::LB)&&(direction0<=OcTreeNames::UF))
   {
     // Pass the tree root of the neighbouring element
     octree0_pt->add_edge_neighbour_pt(octree1_pt,direction0);
     // Pass the tree root of the neighbouring element
     octree1_pt->add_edge_neighbour_pt(octree0_pt,direction1);
   }
   //----------------------------------------------------------------
   // Now the appropriate OcTree objects are aware of each other,
   // they need to know their relative orientations. Specifically,
   // they need to know their up and right direction relative to each
   // other. This is painful to do by calling the function
   //               construct_up_right_equivalents()
   // from the Forest pointer of the mesh so just hardcode it (hacky,
   // I know...).
   //----------------------------------------------------------------
   // Set the up equivalent
   octree0_pt->set_up_equivalent(octree1_pt,OcTreeNames::U);
   // Set the up equivalent
   octree1_pt->set_up_equivalent(octree0_pt,OcTreeNames::U);
   // Set the right equivalent
   octree0_pt->set_right_equivalent(octree1_pt,OcTreeNames::R);
   // Set the right equivalent
   octree1_pt->set_right_equivalent(octree0_pt,OcTreeNames::R);
 } // End of set_neighbour_periodic_and_up_right_equivalents
References oomph::OcTreeRoot::add_edge_neighbour_pt(), oomph::OcTreeNames::F, L, oomph::OcTreeNames::LB, oomph::TreeRoot::neighbour_pt(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, R, oomph::TreeRoot::set_neighbour_periodic(), oomph::OcTreeRoot::set_right_equivalent(), oomph::OcTreeRoot::set_up_equivalent(), RachelsAdvectionDiffusion::U, and oomph::OcTreeNames::UF.
set_neighbour_periodic_and_up_right_equivalents() [2/3]
template<class ELEMENT > void UnsteadyHeatProblem< ELEMENT >::set_neighbour_periodic_and_up_right_equivalents (FiniteElement * el0_pt, FiniteElement * el1_pt, const int & direction0)
Function to set the periodicity between two octrees and assign the up and right equivalents to both elements
set_neighbour_periodic_and_up_right_equivalents() [3/3]
template<class ELEMENT > void UnsteadyHeatProblem< ELEMENT >::set_neighbour_periodic_and_up_right_equivalents (FiniteElement * el0_pt, FiniteElement * el1_pt, const int & direction0)
Function to set the periodicity between two octrees and assign the up and right equivalents to both elements
set_up_spacetime_solver() [1/2]
template<class ELEMENT > void UnsteadyHeatProblem< ELEMENT >::set_up_spacetime_solver
Assign the chosen solver (and preconditioner if so desired)
Set up the solver for this Problem object.
 {
   // Create oomph-lib iterative linear solver
   Solver_pt=new GMRES<CRDoubleMatrix>;
   // Use LHS preconditioning
   dynamic_cast<GMRES<CRDoubleMatrix>*>(Solver_pt)->set_preconditioner_RHS();
   // Set the tolerance
   Solver_pt->tolerance()=1.0e-12;
   // Maximum number of iterations
   Solver_pt->max_iter()=200;
   // Set linear solver
   linear_solver_pt()=Solver_pt;
   //-----------------------------------------
   // Create the master-level preconditioners:
   //-----------------------------------------
   // Solve the diagonal blocks associated with each time-slice separately
   if (GlobalParameters::Preconditioner==Diagonal_preconditioner)
   {
     // Create a new instance of the space-time preconditioner
     Prec_pt=new BlockDiagonalPreconditioner<CRDoubleMatrix>;
   }
   // Solve the block lower-triangular part of the system matrix
   else if (GlobalParameters::Preconditioner==Lower_triangular_preconditioner)
   {
     // Create a new instance of the space-time preconditioner
     Prec_pt=new BandedBlockTriangularPreconditioner<CRDoubleMatrix>;
     // Create a new instance of the space-time preconditioner
     BandedBlockTriangularPreconditioner<CRDoubleMatrix>* st_block_prec_pt=
       dynamic_cast<BandedBlockTriangularPreconditioner<CRDoubleMatrix>*>(
         Prec_pt);
     // Indicate that we're using a block lower triangular solve
     st_block_prec_pt->lower_triangular();
     // The block bandwidth for the preconditioner; because we group dofs by
     // their space-time-slab, the bandwidth will be one (we only have diagonal
     // blocks and subdiagonal blocks in the block-organised system matrix for
     // the backwards-looking mixed order discretisation).
     // NOTE: Don't delete this as this drastically reduces the time taken to
     // to extract blocks during the preconditioner setup.
     bool bandwidth=1;
     // Provide the bandwidth; only subdiagonal block entries
     st_block_prec_pt->set_block_bandwidth(bandwidth);
     // Do we want to document the memory usage?
     bool document_memory_usage=true;
     // If we want to document the memory usage
     if (document_memory_usage)
     {
       // Tell the block preconditioner that we want it to doc. the memory usage
       st_block_prec_pt->enable_doc_memory_usage();
     }
   }
   // If the user provided an invalid input
   else
   {
     // Throw an error
     throw OomphLibError("Invalid choice of preconditioner.",
                         OOMPH_CURRENT_FUNCTION,
                         OOMPH_EXCEPTION_LOCATION);
   } // if (GlobalParameters::Preconditioner==Diagonal_preconditioner)
   // Allocate space for the DOF to block map; this tells the master block
   // preconditioner which DOF types to aggregate
   Vector<unsigned> dof_to_block_map;
   // Call the auxiliary function which sets up the mapping
   GlobalParameters::set_up_dof_to_block_mapping(dof_to_block_map);
   // Create an upcasted pointer to the master preconditioner
   GeneralPurposeBlockPreconditioner<CRDoubleMatrix>* upcasted_master_prec_pt=
     dynamic_cast<GeneralPurposeBlockPreconditioner<CRDoubleMatrix>*>(Prec_pt);
   // Build silently!
   upcasted_master_prec_pt->enable_silent_preconditioner_setup();
   // Pass the DOF-to-block map to the preconditioner
   upcasted_master_prec_pt->set_dof_to_block_map(dof_to_block_map);
   // Pass a pointer to the (space-time) mesh
   upcasted_master_prec_pt->add_mesh(Bulk_mesh_pt);
   // Now assign the preconditioner to the linear solver
   Solver_pt->preconditioner_pt()=Prec_pt;
 } // End of set_up_spacetime_solver
References oomph::GeneralPurposeBlockPreconditioner< MATRIX >::add_mesh(), oomph::BandedBlockTriangularPreconditioner< MATRIX >::enable_doc_memory_usage(), oomph::Preconditioner::enable_silent_preconditioner_setup(), oomph::BandedBlockTriangularPreconditioner< MATRIX >::lower_triangular(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, GlobalParameters::Preconditioner, oomph::BandedBlockTriangularPreconditioner< MATRIX >::set_block_bandwidth(), oomph::GeneralPurposeBlockPreconditioner< MATRIX >::set_dof_to_block_map(), and GlobalParameters::set_up_dof_to_block_mapping().
set_up_spacetime_solver() [2/2]
template<class ELEMENT > void UnsteadyHeatProblem< ELEMENT >::set_up_spacetime_solver ()
Assign the chosen solver (and preconditioner if so desired)
unpin_all_dofs()
template<class ELEMENT > void UnsteadyHeatProblem< ELEMENT >::unpin_all_dofs () inline
Unpin all of the dofs in the mesh.
   {
     // The number of nodes in the mesh
     unsigned n_node=Bulk_mesh_pt->nnode();
     // Unpin all dofs
     for (unsigned n=0; n<n_node; n++)
     {
       // Unpin the only dof at the n-th node
       Bulk_mesh_pt->node_pt(n)->unpin(0);
     }
   } // End of unpin_all_dofs
References n.
update_block_preconditioner_after_refinement() [1/2]
template<class ELEMENT > void UnsteadyHeatProblem< ELEMENT >::update_block_preconditioner_after_refinement
Helper function to update the block preconditioner after, what seems like, a uniform refinement
 {
   // Make sure we're even using the preconditioner
   if (Prec_pt!=0)
   {
     // Set the time-slab id
     assign_time_slab_id();
     // Don't waste time, just kill the old solver
     // and set up a new one. God knows why it's
     // struggling with me trying to replace the
     // current dof-to-block map...
     // Kill the preconditioner
     delete Prec_pt;
     // Kill the solver
     delete Solver_pt;
     // Make the reference to the preconditioner a null pointer
     Prec_pt=0;
     // Make the reference to the solver a null pointer
     Solver_pt=0;
     // Set up a new solver and preconditioner
     set_up_spacetime_solver();
   }
 } // End of update_block_preconditioner_after_refinement
update_block_preconditioner_after_refinement() [2/2]
template<class ELEMENT > void UnsteadyHeatProblem< ELEMENT >::update_block_preconditioner_after_refinement ()
Helper function to update the block preconditioner after, what seems like, a uniform refinement
Member Data Documentation
Bulk_mesh_pt [1/3]
template<class ELEMENT > RefineableSimpleCubicMesh< ELEMENT > * UnsteadyHeatProblem< ELEMENT >::Bulk_mesh_pt private
Pointers to specific mesh.
Pointer to the mesh.
Referenced by UnsteadyHeatProblem< ELEMENT >::UnsteadyHeatProblem().
Bulk_mesh_pt [2/3]
template<class ELEMENT > Mesh* UnsteadyHeatProblem< ELEMENT >::Bulk_mesh_pt private
Pointer to the "bulk" mesh.
Bulk_mesh_pt [3/3]
template<class ELEMENT > RefineableSimpleCubicMesh<ELEMENT>* UnsteadyHeatProblem< ELEMENT >::Bulk_mesh_pt private
Pointer to the mesh.
Control_node_pt
template<class ELEMENT > Node * UnsteadyHeatProblem< ELEMENT >::Control_node_pt private
Pointer to control node at which the solution is documented.
Referenced by UnsteadyHeatProblem< ELEMENT >::UnsteadyHeatProblem().
Flux_boundary_id
template<class ELEMENT > unsigned UnsteadyHeatProblem< ELEMENT >::Flux_boundary_id private
ID of flux boundary.
Melt_boundary_id
template<class ELEMENT > unsigned UnsteadyHeatProblem< ELEMENT >::Melt_boundary_id private
ID of melt boundary.
N_space_time_slab
template<class ELEMENT > unsigned UnsteadyHeatProblem< ELEMENT >::N_space_time_slab private
The number of space-time slabs in the mesh; this is essentially a copy of N_t in the GlobalParameters namespace but will be updated when we complete a uniform refinement
Periodicity_has_been_enforced
template<class ELEMENT > bool UnsteadyHeatProblem< ELEMENT >::Periodicity_has_been_enforced private
Prec_pt
template<class ELEMENT > Preconditioner * UnsteadyHeatProblem< ELEMENT >::Prec_pt private
Preconditioner.
Solver_pt
template<class ELEMENT > IterativeLinearSolver * UnsteadyHeatProblem< ELEMENT >::Solver_pt private
Oomph-lib iterative linear solver.
Source_fct_pt [1/2]
template<class ELEMENT > UnsteadyHeatEquations< 2 >::UnsteadyHeatSourceFctPt UnsteadyHeatProblem< ELEMENT >::Source_fct_pt private
Pointer to source function.
Referenced by UnsteadyHeatProblem< ELEMENT >::UnsteadyHeatProblem().
Source_fct_pt [2/2]
template<class ELEMENT > SpaceTimeFunctionPt UnsteadyHeatProblem< ELEMENT >::Source_fct_pt private
Pointer to source function.
Surface_melt_mesh_pt
template<class ELEMENT > Mesh* UnsteadyHeatProblem< ELEMENT >::Surface_melt_mesh_pt private
Pointer to the "surface" mesh.
Surface_mesh_pt
template<class ELEMENT > Mesh * UnsteadyHeatProblem< ELEMENT >::Surface_mesh_pt private
Pointer to the "surface" mesh.
Referenced by UnsteadyHeatProblem< ELEMENT >::UnsteadyHeatProblem().
Trace_file
template<class ELEMENT > ofstream UnsteadyHeatProblem< ELEMENT >::Trace_file private
Trace file.
The documentation for this class was generated from the following files:
pretend_melt.cc
test_equal_order_galerkin.cc
test_equal_order_galerkin_petrov.cc
test_mixed_order_galerkin_petrov.cc
heat_transfer_and_melting/two_d_unsteady_heat_melt/two_d_unsteady_heat.cc
two_d_unsteady_heat_restarted.cc
two_d_unsteady_heat_t_adapt.cc