MercuryDPM: oomph::TFace Class Reference
oomph::TFace Class Reference
Triangular Face class.
#include <Telements.h>
Public Member Functions
TFace (Node *node1_pt, Node *node2_pt, Node *node3_pt)
Constructor: Pass in the three vertex nodes.
Node * node1_pt () const
Access to the first vertex node.
Node * node2_pt () const
Access to the second vertex node.
Node * node3_pt () const
Access to the third vertex node.
bool operator== (const TFace &other) const
Comparison operator.
bool operator< (const TFace &other) const
Less-than operator.
bool is_on_boundary () const
bool is_boundary_face () const
void get_boundaries_pt (std::set< unsigned > *&boundaries_pt)
Private Attributes
Node * Node1_pt
First vertex node.
Node * Node2_pt
Second vertex node.
Node * Node3_pt
Third vertex node.
Detailed Description
Triangular Face class.
//////////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////////
Constructor & Destructor Documentation
TFace()
oomph::TFace::TFace (Node * node1_pt, Node * node2_pt, Node * node3_pt) inline
Constructor: Pass in the three vertex nodes.
     {
       if ((node1_pt == node2_pt) || (node2_pt == node3_pt) ||
           (node1_pt == node3_pt))
       {
 #ifdef PARANOID
         std::ostringstream error_stream;
         error_stream << "TFace cannot have two identical vertex nodes\n";
         throw OomphLibError(
           error_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
 #endif
       }
       // Sort lexicographically based on pointer address of nodes
       std::set<Node*> nodes;
       nodes.insert(node1_pt);
       nodes.insert(node2_pt);
       nodes.insert(node3_pt);
       std::set<Node*>::iterator it = nodes.begin();
       Node1_pt = (*it);
       it++;
       Node2_pt = (*it);
       it++;
       Node3_pt = (*it);
       it++;
     }
References node1_pt(), Node1_pt, node2_pt(), Node2_pt, node3_pt(), Node3_pt, OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
Member Function Documentation
get_boundaries_pt()
void oomph::TFace::get_boundaries_pt (std::set< unsigned > *& boundaries_pt) inline
Access to pointer to set of mesh boundaries that this face occupies; NULL if the node is not on any boundary. Construct via set intersection of the boundary sets for the associated vertex nodes
     {
       std::set<unsigned> set1;
       std::set<unsigned>* set1_pt = &set1;
       Node1_pt->get_boundaries_pt(set1_pt);
       std::set<unsigned> set2;
       std::set<unsigned>* set2_pt = &set2;
       Node2_pt->get_boundaries_pt(set2_pt);
       std::set<unsigned> set3;
       std::set<unsigned>* set3_pt = &set3;
       Node3_pt->get_boundaries_pt(set3_pt);
       std::set<unsigned> aux_set;
       set_intersection((*set1_pt).begin(),
                        (*set1_pt).end(),
                        (*set2_pt).begin(),
                        (*set2_pt).end(),
                        inserter(aux_set, aux_set.begin()));
       set_intersection(aux_set.begin(),
                        aux_set.end(),
                        (*set3_pt).begin(),
                        (*set3_pt).end(),
                        inserter((*boundaries_pt), (*boundaries_pt).begin()));
     }
References oomph::Node::get_boundaries_pt(), Node1_pt, Node2_pt, and Node3_pt.
Referenced by oomph::BrickFromTetMesh< ELEMENT >::build_mesh().
is_boundary_face()
bool oomph::TFace::is_boundary_face () const inline
Test whether the face is a boundary face, i.e. does it connnect three boundary nodes?
     {
       return ((dynamic_cast<BoundaryNodeBase*>(Node1_pt) != 0) &&
               (dynamic_cast<BoundaryNodeBase*>(Node2_pt) != 0) &&
               (dynamic_cast<BoundaryNodeBase*>(Node3_pt) != 0));
     }
References Node1_pt, Node2_pt, and Node3_pt.
Referenced by oomph::BrickFromTetMesh< ELEMENT >::build_mesh().
is_on_boundary()
bool oomph::TFace::is_on_boundary () const inline
Test whether the face lies on a boundary. Relatively simple test, based on all vertices lying on (some) boundary.
     {
       return (Node1_pt->is_on_boundary() && Node2_pt->is_on_boundary() &&
               Node3_pt->is_on_boundary());
     }
References oomph::Node::is_on_boundary(), Node1_pt, Node2_pt, and Node3_pt.
node1_pt()
Node* oomph::TFace::node1_pt () const inline
Access to the first vertex node.
     {
       return Node1_pt;
     }
References Node1_pt.
Referenced by operator<(), operator==(), and TFace().
node2_pt()
Node* oomph::TFace::node2_pt () const inline
Access to the second vertex node.
     {
       return Node2_pt;
     }
References Node2_pt.
Referenced by operator<(), operator==(), and TFace().
node3_pt()
Node* oomph::TFace::node3_pt () const inline
Access to the third vertex node.
     {
       return Node3_pt;
     }
References Node3_pt.
Referenced by operator<(), operator==(), and TFace().
operator<()
bool oomph::TFace::operator< (const TFace & other) const inline
Less-than operator.
     {
       if (Node1_pt < other.node1_pt())
       {
         return true;
       }
       else if (Node1_pt == other.node1_pt())
       {
         if (Node2_pt < other.node2_pt())
         {
           return true;
         }
         else if (Node2_pt == other.node2_pt())
         {
           if (Node3_pt < other.node3_pt())
           {
             return true;
           }
           else
           {
             return false;
           }
         }
         else
         {
           return false;
         }
       }
       else
       {
         return false;
       }
     }
References node1_pt(), Node1_pt, node2_pt(), Node2_pt, node3_pt(), and Node3_pt.
operator==()
bool oomph::TFace::operator== (const TFace & other) const inline
Comparison operator.
     {
       if ((Node1_pt == other.node1_pt()) && (Node2_pt == other.node2_pt()) &&
           (Node3_pt == other.node3_pt()))
       {
         return true;
       }
       else
       {
         return false;
       }
     }
References node1_pt(), Node1_pt, node2_pt(), Node2_pt, node3_pt(), and Node3_pt.
Member Data Documentation
Node1_pt
Node* oomph::TFace::Node1_pt private
First vertex node.
Referenced by get_boundaries_pt(), is_boundary_face(), is_on_boundary(), node1_pt(), operator<(), operator==(), and TFace().
Node2_pt
Node* oomph::TFace::Node2_pt private
Second vertex node.
Referenced by get_boundaries_pt(), is_boundary_face(), is_on_boundary(), node2_pt(), operator<(), operator==(), and TFace().
Node3_pt
Node* oomph::TFace::Node3_pt private
Third vertex node.
Referenced by get_boundaries_pt(), is_boundary_face(), is_on_boundary(), node3_pt(), operator<(), operator==(), and TFace().
The documentation for this class was generated from the following file:
Telements.h