MercuryDPM: PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT > Class Template Reference
PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT > Class Template Reference
Public Member Functions
PerturbedStateProblem (const unsigned &n_r, const unsigned &n_z, const double &domain_height, Mesh *external_mesh_pt)
Constructor.
~PerturbedStateProblem ()
Destructor (empty)
void actions_before_newton_solve ()
Update before solve (empty)
void actions_after_newton_solve ()
Update after solve (empty)
void actions_before_implicit_timestep ()
Actions before timestep (empty)
void actions_after_implicit_timestep ()
Update the problem specs after solve (empty)
void set_initial_condition ()
Set the initial conditions to a "Poiseuille-style" profile.
void set_boundary_conditions ()
Set up the (homogeneous) boundary conditions.
RectangularQuadMesh< PERTURBED_ELEMENT > * mesh_pt ()
Access function for the specific mesh.
RectangularQuadMesh< BASE_ELEMENT > * base_state_mesh_pt ()
Access function for the base state mesh.
void doc_solution (DocInfo &doc_info)
Doc the solution.
PerturbedStateProblem (const unsigned &n_r, const unsigned &n_z, const double &domain_height, Mesh *external_mesh_pt)
Constructor.
~PerturbedStateProblem ()
Destructor (empty)
void actions_before_newton_solve ()
Update before solve (empty)
void actions_after_newton_solve ()
Update after solve (empty)
void actions_before_implicit_timestep ()
Actions before timestep (empty)
void actions_after_implicit_timestep ()
Update the problem specs after solve (empty)
void actions_after_adapt ()
void set_initial_condition ()
void set_boundary_conditions ()
Set up the (homogeneous) boundary conditions.
RefineableRectangularQuadMesh< PERTURBED_ELEMENT > * mesh_pt ()
Access function for the specific mesh.
RefineableRectangularQuadMesh< BASE_ELEMENT > * base_state_mesh_pt ()
Access function for the base state mesh.
void doc_solution (DocInfo &doc_info)
Doc the solution.
PerturbedStateProblem (const unsigned &n_r, const unsigned &n_z, const double &domain_height, Mesh *external_mesh_pt)
Constructor.
~PerturbedStateProblem ()
Destructor (empty)
void actions_before_newton_solve ()
Update before solve (empty)
void actions_after_newton_solve ()
Update after solve (empty)
void actions_before_implicit_timestep ()
Actions before timestep (empty)
void actions_after_implicit_timestep ()
Update the problem specs after solve (empty)
void set_initial_condition ()
Set initial conditions to a "Poiseuille-style" profile.
void set_boundary_conditions ()
Set up the (homogeneous) boundary conditions.
RectangularQuadMesh< PERTURBED_ELEMENT > * mesh_pt ()
Access function for the specific mesh.
RectangularQuadMesh< BASE_ELEMENT > * base_state_mesh_pt ()
Access function for the base state mesh.
SelfStartingBDF2 * time_stepper_pt ()
Access function for the specific timestepper.
void doc_solution (DocInfo &doc_info, const bool &output_soln=true)
Doc the solution.
void create_trace_file (DocInfo &doc_info)
Create a trace file.
void initialise_trace_file ()
Initialise trace file (print column headings)
void close_trace_file ()
Clear and close trace file.
ofstream & trace_file ()
Access function for trace file.
void pass_updated_nondim_parameters_to_elements ()
PerturbedStateProblem (const unsigned &n_r, const unsigned &n_z, const double &domain_height, Mesh *external_mesh_pt)
Constructor.
~PerturbedStateProblem ()
Destructor (empty)
void actions_before_newton_solve ()
Update before solve (empty)
void actions_after_newton_solve ()
Update after solve (empty)
void actions_before_implicit_timestep ()
Actions before timestep (empty)
void actions_after_implicit_timestep ()
Update the problem specs after solve (empty)
void actions_after_adapt ()
void set_initial_condition ()
Set initial conditions to a "Poiseuille-style" profile.
void set_boundary_conditions ()
Set up the (homogeneous) boundary conditions.
RefineableRectangularQuadMesh< PERTURBED_ELEMENT > * mesh_pt ()
Access function for the specific mesh.
RefineableRectangularQuadMesh< BASE_ELEMENT > * base_state_mesh_pt ()
Access function for the base state mesh.
SelfStartingBDF2 * time_stepper_pt ()
Access function for the specific timestepper.
void doc_solution (DocInfo &doc_info, const bool &output_soln=true)
Doc the solution.
void create_trace_file (DocInfo &doc_info)
Create a trace file.
void initialise_trace_file ()
Initialise trace file (print column headings)
void close_trace_file ()
Clear and close trace file.
ofstream & trace_file ()
Access function for trace file.
void pass_updated_nondim_parameters_to_elements ()
PerturbedStateProblem (const unsigned &n_r, const unsigned &n_z, const double &radius_inner_cylinder, const double &radius_outer_cylinder, const double &l_z, Mesh *external_mesh_pt)
Constructor.
~PerturbedStateProblem ()
Destructor (empty)
void actions_before_newton_solve ()
Update before solve (empty)
void actions_after_newton_solve ()
Update after solve (empty)
void actions_before_implicit_timestep ()
Actions before timestep (empty)
void actions_after_implicit_timestep ()
Update the problem specs after solve (empty)
void set_initial_condition ()
Set initial conditions to a "Poiseuille-style" profile.
void set_boundary_conditions ()
Set up the (homogeneous) boundary conditions.
RectangularQuadMesh< PERTURBED_ELEMENT > * mesh_pt ()
Access function for the specific mesh.
RectangularQuadMesh< BASE_ELEMENT > * base_state_mesh_pt ()
Access function for the base state mesh.
SelfStartingBDF2 * time_stepper_pt ()
Access function for the specific timestepper.
void doc_solution (DocInfo &doc_info, const bool &output_soln=true)
Doc the solution.
void create_trace_file (DocInfo &doc_info)
Create a trace file.
void initialise_trace_file ()
Initialise trace file (print column headings)
void close_trace_file ()
Clear and close trace file.
ofstream & trace_file ()
Access function for trace file.
PerturbedStateProblem (const unsigned &n_r, const unsigned &n_z1, const unsigned &n_z2, const double &h1, const double &h2, SpineMesh *external_bulk_mesh_pt, int azimuthal_mode_number)
~PerturbedStateProblem ()
Destructor (empty)
void set_initial_condition ()
Set initial conditions (velocities given random values in range [0,1])
void set_boundary_conditions ()
Set up the (homogeneous) boundary conditions.
TwoLayerSpineMesh< BASE_ELEMENT > * base_state_bulk_mesh_pt ()
Access function for the base state mesh.
TIMESTEPPER * time_stepper_pt ()
Access function for the specific timestepper.
void doc_solution (DocInfo *&doc_info_pt, const bool &output_soln=true)
Doc the solution.
void create_trace_file (DocInfo *&doc_info_pt)
Create and initialise a trace file.
void close_trace_file ()
Clear and close trace file.
ofstream & trace_file ()
Access function for trace file.
void create_interface_elements ()
Create interface elements at boundary between upper and lower layers.
TwoLayerPerturbedSpineMesh< PERTURBED_ELEMENT > * bulk_mesh_pt ()
Access function for bulk mesh.
Mesh * surface_mesh_pt ()
Access function for surface mesh.
Public Member Functions inherited from oomph::Problem
virtual void debug_hook_fct (const unsigned &i)
void set_analytic_dparameter (double *const &parameter_pt)
void unset_analytic_dparameter (double *const &parameter_pt)
bool is_dparameter_calculated_analytically (double *const &parameter_pt)
void set_analytic_hessian_products ()
void unset_analytic_hessian_products ()
bool are_hessian_products_calculated_analytically ()
void set_pinned_values_to_zero ()
bool distributed () const
virtual void actions_before_adapt ()
OomphCommunicator * communicator_pt ()
access function to the oomph-lib communicator
const OomphCommunicator * communicator_pt () const
access function to the oomph-lib communicator, const version
Problem ()
Problem (const Problem &dummy)=delete
Broken copy constructor.
void operator= (const Problem &)=delete
Broken assignment operator.
virtual ~Problem ()
Virtual destructor to clean up memory.
Mesh *& mesh_pt ()
Return a pointer to the global mesh.
Mesh *const & mesh_pt () const
Return a pointer to the global mesh (const version)
Mesh *& mesh_pt (const unsigned &imesh)
Mesh *const & mesh_pt (const unsigned &imesh) const
Return a pointer to the i-th submesh (const version)
unsigned nsub_mesh () const
Return number of submeshes.
unsigned add_sub_mesh (Mesh *const &mesh_pt)
void flush_sub_meshes ()
void build_global_mesh ()
void rebuild_global_mesh ()
LinearSolver *& linear_solver_pt ()
Return a pointer to the linear solver object.
LinearSolver *const & linear_solver_pt () const
Return a pointer to the linear solver object (const version)
LinearSolver *& mass_matrix_solver_for_explicit_timestepper_pt ()
LinearSolver * mass_matrix_solver_for_explicit_timestepper_pt () const
EigenSolver *& eigen_solver_pt ()
Return a pointer to the eigen solver object.
EigenSolver *const & eigen_solver_pt () const
Return a pointer to the eigen solver object (const version)
Time *& time_pt ()
Return a pointer to the global time object.
Time * time_pt () const
Return a pointer to the global time object (const version).
double & time ()
Return the current value of continuous time.
double time () const
Return the current value of continuous time (const version)
TimeStepper *& time_stepper_pt ()
const TimeStepper * time_stepper_pt () const
TimeStepper *& time_stepper_pt (const unsigned &i)
Return a pointer to the i-th timestepper.
ExplicitTimeStepper *& explicit_time_stepper_pt ()
Return a pointer to the explicit timestepper.
unsigned long set_timestepper_for_all_data (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data=false)
virtual void shift_time_values ()
Shift all values along to prepare for next timestep.
AssemblyHandler *& assembly_handler_pt ()
Return a pointer to the assembly handler object.
AssemblyHandler *const & assembly_handler_pt () const
Return a pointer to the assembly handler object (const version)
double & minimum_dt ()
Access function to min timestep in adaptive timestepping.
double & maximum_dt ()
Access function to max timestep in adaptive timestepping.
unsigned & max_newton_iterations ()
Access function to max Newton iterations before giving up.
void problem_is_nonlinear (const bool &prob_lin)
Access function to Problem_is_nonlinear.
double & max_residuals ()
bool & time_adaptive_newton_crash_on_solve_fail ()
Access function for Time_adaptive_newton_crash_on_solve_fail.
double & newton_solver_tolerance ()
void add_time_stepper_pt (TimeStepper *const &time_stepper_pt)
void set_explicit_time_stepper_pt (ExplicitTimeStepper *const &explicit_time_stepper_pt)
void initialise_dt (const double &dt)
void initialise_dt (const Vector< double > &dt)
Data *& global_data_pt (const unsigned &i)
Return a pointer to the the i-th global data object.
void add_global_data (Data *const &global_data_pt)
void flush_global_data ()
LinearAlgebraDistribution *const & dof_distribution_pt () const
Return the pointer to the dof distribution (read-only)
unsigned long ndof () const
Return the number of dofs.
unsigned ntime_stepper () const
Return the number of time steppers.
unsigned nglobal_data () const
Return the number of global data values.
unsigned self_test ()
Self-test: Check meshes and global data. Return 0 for OK.
void enable_store_local_dof_pt_in_elements ()
void disable_store_local_dof_pt_in_elements ()
unsigned long assign_eqn_numbers (const bool &assign_local_eqn_numbers=true)
void describe_dofs (std::ostream &out= *(oomph_info.stream_pt())) const
void enable_discontinuous_formulation ()
void disable_discontinuous_formulation ()
void get_dofs (DoubleVector &dofs) const
void get_dofs (const unsigned &t, DoubleVector &dofs) const
Return vector of the t'th history value of all dofs.
void set_dofs (const DoubleVector &dofs)
Set the values of the dofs.
void set_dofs (const unsigned &t, DoubleVector &dofs)
Set the history values of the dofs.
void set_dofs (const unsigned &t, Vector< double * > &dof_pt)
void add_to_dofs (const double &lambda, const DoubleVector &increment_dofs)
Add lambda x incremenet_dofs[l] to the l-th dof.
double * global_dof_pt (const unsigned &i)
double & dof (const unsigned &i)
i-th dof in the problem
double dof (const unsigned &i) const
i-th dof in the problem (const version)
double *& dof_pt (const unsigned &i)
Pointer to i-th dof in the problem.
double * dof_pt (const unsigned &i) const
Pointer to i-th dof in the problem (const version)
virtual void get_inverse_mass_matrix_times_residuals (DoubleVector &Mres)
virtual void get_dvaluesdt (DoubleVector &f)
virtual void get_residuals (DoubleVector &residuals)
Get the total residuals Vector for the problem.
virtual void get_jacobian (DoubleVector &residuals, DenseDoubleMatrix &jacobian)
virtual void get_jacobian (DoubleVector &residuals, CRDoubleMatrix &jacobian)
virtual void get_jacobian (DoubleVector &residuals, CCDoubleMatrix &jacobian)
virtual void get_jacobian (DoubleVector &residuals, SumOfMatrices &jacobian)
void get_fd_jacobian (DoubleVector &residuals, DenseMatrix< double > &jacobian)
Get the full Jacobian by finite differencing.
void get_derivative_wrt_global_parameter (double *const &parameter_pt, DoubleVector &result)
void get_hessian_vector_products (DoubleVectorWithHaloEntries const &Y, Vector< DoubleVectorWithHaloEntries > const &C, Vector< DoubleVectorWithHaloEntries > &product)
void solve_eigenproblem (const unsigned &n_eval, Vector< std::complex< double >> &eigenvalue, Vector< DoubleVector > &eigenvector, const bool &steady=true)
Solve the eigenproblem.
void solve_eigenproblem (const unsigned &n_eval, Vector< std::complex< double >> &eigenvalue, const bool &steady=true)
virtual void get_eigenproblem_matrices (CRDoubleMatrix &mass_matrix, CRDoubleMatrix &main_matrix, const double &shift=0.0)
void assign_eigenvector_to_dofs (DoubleVector &eigenvector)
Assign the eigenvector passed to the function to the dofs.
void add_eigenvector_to_dofs (const double &epsilon, const DoubleVector &eigenvector)
void store_current_dof_values ()
Store the current values of the degrees of freedom.
void restore_dof_values ()
Restore the stored values of the degrees of freedom.
void enable_jacobian_reuse ()
void disable_jacobian_reuse ()
Disable recycling of Jacobian in Newton iteration.
bool jacobian_reuse_is_enabled ()
Is recycling of Jacobian in Newton iteration enabled?
bool & use_predictor_values_as_initial_guess ()
void newton_solve ()
Use Newton method to solve the problem.
void enable_globally_convergent_newton_method ()
enable globally convergent Newton method
void disable_globally_convergent_newton_method ()
disable globally convergent Newton method
void newton_solve (unsigned const &max_adapt)
void steady_newton_solve (unsigned const &max_adapt=0)
void copy (Problem *orig_problem_pt)
virtual Problem * make_copy ()
virtual void read (std::ifstream &restart_file, bool &unsteady_restart)
virtual void read (std::ifstream &restart_file)
virtual void dump (std::ofstream &dump_file) const
void dump (const std::string &dump_file_name) const
void delete_all_external_storage ()
virtual void symmetrise_eigenfunction_for_adaptive_pitchfork_tracking ()
double * bifurcation_parameter_pt () const
void get_bifurcation_eigenfunction (Vector< DoubleVector > &eigenfunction)
void activate_fold_tracking (double *const &parameter_pt, const bool &block_solve=true)
void activate_bifurcation_tracking (double *const &parameter_pt, const DoubleVector &eigenvector, const bool &block_solve=true)
void activate_bifurcation_tracking (double *const &parameter_pt, const DoubleVector &eigenvector, const DoubleVector &normalisation, const bool &block_solve=true)
void activate_pitchfork_tracking (double *const &parameter_pt, const DoubleVector &symmetry_vector, const bool &block_solve=true)
void activate_hopf_tracking (double *const &parameter_pt, const bool &block_solve=true)
void activate_hopf_tracking (double *const &parameter_pt, const double &omega, const DoubleVector &null_real, const DoubleVector &null_imag, const bool &block_solve=true)
void deactivate_bifurcation_tracking ()
void reset_assembly_handler_to_default ()
Reset the system to the standard non-augemented state.
double arc_length_step_solve (double *const &parameter_pt, const double &ds, const unsigned &max_adapt=0)
double arc_length_step_solve (Data *const &data_pt, const unsigned &data_index, const double &ds, const unsigned &max_adapt=0)
void reset_arc_length_parameters ()
int & sign_of_jacobian ()
void explicit_timestep (const double &dt, const bool &shift_values=true)
Take an explicit timestep of size dt.
void unsteady_newton_solve (const double &dt)
void unsteady_newton_solve (const double &dt, const bool &shift_values)
void unsteady_newton_solve (const double &dt, const unsigned &max_adapt, const bool &first, const bool &shift=true)
double doubly_adaptive_unsteady_newton_solve (const double &dt, const double &epsilon, const unsigned &max_adapt, const bool &first, const bool &shift=true)
double doubly_adaptive_unsteady_newton_solve (const double &dt, const double &epsilon, const unsigned &max_adapt, const unsigned &suppress_resolve_after_spatial_adapt_flag, const bool &first, const bool &shift=true)
double adaptive_unsteady_newton_solve (const double &dt_desired, const double &epsilon)
double adaptive_unsteady_newton_solve (const double &dt_desired, const double &epsilon, const bool &shift_values)
void assign_initial_values_impulsive ()
void assign_initial_values_impulsive (const double &dt)
void calculate_predictions ()
Calculate predictions.
void enable_mass_matrix_reuse ()
void disable_mass_matrix_reuse ()
bool mass_matrix_reuse_is_enabled ()
Return whether the mass matrix is being reused.
void refine_uniformly (const Vector< unsigned > &nrefine_for_mesh)
void refine_uniformly (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh)
void refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void refine_uniformly (DocInfo &doc_info)
void refine_uniformly_and_prune (DocInfo &doc_info)
void refine_uniformly ()
void refine_uniformly (const unsigned &i_mesh, DocInfo &doc_info)
Do uniform refinement for submesh i_mesh with documentation.
void refine_uniformly (const unsigned &i_mesh)
Do uniform refinement for submesh i_mesh without documentation.
void p_refine_uniformly (const Vector< unsigned > &nrefine_for_mesh)
void p_refine_uniformly (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void p_refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh)
void p_refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void p_refine_uniformly (DocInfo &doc_info)
void p_refine_uniformly_and_prune (DocInfo &doc_info)
void p_refine_uniformly ()
void p_refine_uniformly (const unsigned &i_mesh, DocInfo &doc_info)
Do uniform p-refinement for submesh i_mesh with documentation.
void p_refine_uniformly (const unsigned &i_mesh)
Do uniform p-refinement for submesh i_mesh without documentation.
void refine_selected_elements (const Vector< unsigned > &elements_to_be_refined)
void refine_selected_elements (const Vector< RefineableElement * > &elements_to_be_refined_pt)
void refine_selected_elements (const unsigned &i_mesh, const Vector< unsigned > &elements_to_be_refined)
void refine_selected_elements (const unsigned &i_mesh, const Vector< RefineableElement * > &elements_to_be_refined_pt)
void refine_selected_elements (const Vector< Vector< unsigned >> &elements_to_be_refined)
void refine_selected_elements (const Vector< Vector< RefineableElement * >> &elements_to_be_refined_pt)
void p_refine_selected_elements (const Vector< unsigned > &elements_to_be_refined)
void p_refine_selected_elements (const Vector< PRefineableElement * > &elements_to_be_refined_pt)
void p_refine_selected_elements (const unsigned &i_mesh, const Vector< unsigned > &elements_to_be_refined)
void p_refine_selected_elements (const unsigned &i_mesh, const Vector< PRefineableElement * > &elements_to_be_refined_pt)
void p_refine_selected_elements (const Vector< Vector< unsigned >> &elements_to_be_refined)
void p_refine_selected_elements (const Vector< Vector< PRefineableElement * >> &elements_to_be_refined_pt)
unsigned unrefine_uniformly ()
unsigned unrefine_uniformly (const unsigned &i_mesh)
void p_unrefine_uniformly (DocInfo &doc_info)
void p_unrefine_uniformly (const unsigned &i_mesh, DocInfo &doc_info)
Do uniform p-unrefinement for submesh i_mesh without documentation.
void adapt (unsigned &n_refined, unsigned &n_unrefined)
void adapt ()
void p_adapt (unsigned &n_refined, unsigned &n_unrefined)
void p_adapt ()
void adapt_based_on_error_estimates (unsigned &n_refined, unsigned &n_unrefined, Vector< Vector< double >> &elemental_error)
void adapt_based_on_error_estimates (Vector< Vector< double >> &elemental_error)
void get_all_error_estimates (Vector< Vector< double >> &elemental_error)
void doc_errors (DocInfo &doc_info)
Get max and min error for all elements in submeshes.
void doc_errors ()
Get max and min error for all elements in submeshes.
void enable_info_in_newton_solve ()
void disable_info_in_newton_solve ()
Disable the output of information when in the newton solver.
Public Member Functions inherited from oomph::ExplicitTimeSteppableObject
ExplicitTimeSteppableObject ()
Empty constructor.
ExplicitTimeSteppableObject (const ExplicitTimeSteppableObject &)=delete
Broken copy constructor.
void operator= (const ExplicitTimeSteppableObject &)=delete
Broken assignment operator.
virtual ~ExplicitTimeSteppableObject ()
Empty destructor.
virtual void actions_before_explicit_stage ()
virtual void actions_after_explicit_stage ()
Private Member Functions
void fix_pressure (const unsigned &e, const unsigned &pdof, const double &pvalue)
Fix pressure in element e at pressure dof pdof and set to pvalue.
void fix_pressure (const unsigned &e, const unsigned &pdof, const double &pvalue)
Fix pressure in element e at pressure dof pdof and set to pvalue.
void fix_pressure (const unsigned &e, const unsigned &pdof, const double &pvalue)
Fix pressure in element e at pressure dof pdof and set to pvalue.
void fix_pressure (const unsigned &e, const unsigned &pdof, const double &pvalue)
Fix pressure in element e at pressure dof pdof and set to pvalue.
void fix_pressure (const unsigned &e, const unsigned &pdof, const double &pvalue)
Fix pressure in element e at pressure dof pdof and set to pvalue.
void actions_before_newton_convergence_check ()
void actions_before_newton_solve ()
Update before solve (empty)
void actions_after_newton_solve ()
Update after solve (empty)
void actions_before_implicit_timestep ()
Actions before timestep (empty)
void actions_after_implicit_timestep ()
Update the problem specs after solve (empty)
void fix_pressure (const unsigned &e, const unsigned &pdof, const double &pvalue)
Fix pressure in element e at pressure dof pdof and set to pvalue.
Private Attributes
Mesh * Base_state_mesh_pt
Pointer to the base state mesh.
double Domain_height
Height of domain.
ofstream Trace_file
Trace file.
double Inner_cylinder_radius
Inner and outer cylinder radii.
double Outer_cylinder_radius
SpineMesh * Base_state_bulk_mesh_pt
Pointer to the base state mesh.
TwoLayerPerturbedSpineMesh< PERTURBED_ELEMENT > * Bulk_mesh_pt
Pointer to the (specific) "bulk" mesh.
Mesh * Surface_mesh_pt
Pointer to the "surface" mesh.
int Azimuthal_mode_number
Azimuthal mode number.
Vector< unsigned > U_nodal_index
Index at which the i-th velocity component is stored.
Vector< unsigned > Xhat_nodal_index
Additional Inherited Members
Public Types inherited from oomph::Problem
typedef void(* SpatialErrorEstimatorFctPt) (Mesh *&mesh_pt, Vector< double > &elemental_error)
Function pointer for spatial error estimator.
typedef void(* SpatialErrorEstimatorWithDocFctPt) (Mesh *&mesh_pt, Vector< double > &elemental_error, DocInfo &doc_info)
Function pointer for spatial error estimator with doc.
Public Attributes inherited from oomph::Problem
bool Shut_up_in_newton_solve
Static Public Attributes inherited from oomph::Problem
static bool Suppress_warning_about_actions_before_read_unstructured_meshes
Protected Types inherited from oomph::Problem
enum Assembly_method {
Perform_assembly_using_vectors_of_pairs , Perform_assembly_using_two_vectors , Perform_assembly_using_maps , Perform_assembly_using_lists ,
Perform_assembly_using_two_arrays
}
Enumerated flags to determine which sparse assembly method is used.
Protected Member Functions inherited from oomph::Problem
unsigned setup_element_count_per_dof ()
virtual void sparse_assemble_row_or_column_compressed (Vector< int * > &column_or_row_index, Vector< int * > &row_or_column_start, Vector< double * > &value, Vector< unsigned > &nnz, Vector< double * > &residual, bool compressed_row_flag)
virtual void actions_before_newton_step ()
virtual void actions_after_newton_step ()
virtual void actions_after_implicit_timestep_and_error_estimation ()
virtual void actions_before_explicit_timestep ()
Actions that should be performed before each explicit time step.
virtual void actions_after_explicit_timestep ()
Actions that should be performed after each explicit time step.
virtual void actions_before_read_unstructured_meshes ()
virtual void actions_after_read_unstructured_meshes ()
virtual void actions_after_change_in_global_parameter (double *const &parameter_pt)
virtual void actions_after_change_in_bifurcation_parameter ()
virtual void actions_after_parameter_increase (double *const &parameter_pt)
double & dof_derivative (const unsigned &i)
double & dof_current (const unsigned &i)
virtual double global_temporal_error_norm ()
unsigned newton_solve_continuation (double *const &parameter_pt)
unsigned newton_solve_continuation (double *const &parameter_pt, DoubleVector &z)
void calculate_continuation_derivatives (double *const &parameter_pt)
void calculate_continuation_derivatives (const DoubleVector &z)
void calculate_continuation_derivatives_fd (double *const &parameter_pt)
bool does_pointer_correspond_to_problem_data (double *const &parameter_pt)
void set_consistent_pinned_values_for_continuation ()
Protected Attributes inherited from oomph::Problem
Vector< Problem * > Copy_of_problem_pt
std::map< double *, bool > Calculate_dparameter_analytic
bool Calculate_hessian_products_analytic
LinearAlgebraDistribution * Dof_distribution_pt
Vector< double * > Dof_pt
Vector of pointers to dofs.
DoubleVectorWithHaloEntries Element_count_per_dof
double Relaxation_factor
double Newton_solver_tolerance
unsigned Max_newton_iterations
Maximum number of Newton iterations.
unsigned Nnewton_iter_taken
Vector< double > Max_res
Maximum residuals at start and after each newton iteration.
double Max_residuals
bool Time_adaptive_newton_crash_on_solve_fail
bool Jacobian_reuse_is_enabled
Is re-use of Jacobian in Newton iteration enabled? Default: false.
bool Jacobian_has_been_computed
bool Problem_is_nonlinear
bool Pause_at_end_of_sparse_assembly
bool Doc_time_in_distribute
unsigned Sparse_assembly_method
unsigned Sparse_assemble_with_arrays_initial_allocation
unsigned Sparse_assemble_with_arrays_allocation_increment
Vector< Vector< unsigned > > Sparse_assemble_with_arrays_previous_allocation
double Numerical_zero_for_sparse_assembly
double FD_step_used_in_get_hessian_vector_products
bool Mass_matrix_reuse_is_enabled
bool Mass_matrix_has_been_computed
bool Discontinuous_element_formulation
double Minimum_dt
Minimum desired dt: if dt falls below this value, exit.
double Maximum_dt
Maximum desired dt.
double DTSF_max_increase
double DTSF_min_decrease
double Minimum_dt_but_still_proceed
bool Scale_arc_length
Boolean to control whether arc-length should be scaled.
double Desired_proportion_of_arc_length
Proportion of the arc-length to taken by the parameter.
double Theta_squared
int Sign_of_jacobian
Storage for the sign of the global Jacobian.
double Continuation_direction
double Parameter_derivative
Storage for the derivative of the global parameter wrt arc-length.
double Parameter_current
Storage for the present value of the global parameter.
bool Use_continuation_timestepper
Boolean to control original or new storage of dof stuff.
unsigned Dof_derivative_offset
unsigned Dof_current_offset
Vector< double > Dof_derivative
Storage for the derivative of the problem variables wrt arc-length.
Vector< double > Dof_current
Storage for the present values of the variables.
double Ds_current
Storage for the current step value.
unsigned Desired_newton_iterations_ds
double Minimum_ds
Minimum desired value of arc-length.
bool Bifurcation_detection
Boolean to control bifurcation detection via determinant of Jacobian.
bool Bisect_to_find_bifurcation
Boolean to control wheter bisection is used to located bifurcation.
bool First_jacobian_sign_change
Boolean to indicate whether a sign change has occured in the Jacobian.
bool Arc_length_step_taken
Boolean to indicate whether an arc-length step has been taken.
bool Use_finite_differences_for_continuation_derivatives
OomphCommunicator * Communicator_pt
The communicator for this problem.
bool Always_take_one_newton_step
double Timestep_reduction_factor_after_nonconvergence
bool Keep_temporal_error_below_tolerance
Static Protected Attributes inherited from oomph::Problem
static ContinuationStorageScheme Continuation_time_stepper
Storage for the single static continuation timestorage object.
Detailed Description
template<class BASE_ELEMENT, class PERTURBED_ELEMENT>
class PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >
////////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////// Perturbed state problem class for Tuckerman counter-rotating lids problem
////////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////// Perturbed state problem class for the time-periodic Taylor–Couette problem
Constructor & Destructor Documentation
PerturbedStateProblem() [1/6]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::PerturbedStateProblem (const unsigned & n_r, const unsigned & n_z, const double & domain_height, Mesh * external_mesh_pt)
Constructor.
Constructor for perturbed state Tuckerman counter-rotating lids problem
  : Base_state_mesh_pt(external_mesh_pt),
    Domain_height(domain_height)
 {
  // Be less verbose during newton solve
  this->disable_info_in_newton_solve();
  // Be less verbose about linear solve timings
  linear_solver_pt()->disable_doc_time();
  // Tell problem that it is linear (avoid doing unnecessary checks)
  Problem::Problem_is_nonlinear = false;
  // Allocate the timestepper (this constructs the time object as well)
  add_time_stepper_pt(new BDF<1>);
  // Build and assign mesh
  Problem::mesh_pt() =
   new RectangularQuadMesh<PERTURBED_ELEMENT>(n_r,n_z,0.0,1.0,0.0,domain_height,
                                              time_stepper_pt());
  // --------------------------------------------
  // Set the boundary conditions for this problem
  // --------------------------------------------
  // All nodes are free by default -- just pin the ones that have
  // Dirichlet conditions here
  // Determine number of mesh boundaries
  const unsigned n_boundary = mesh_pt()->nboundary();
  // Loop over mesh boundaries
  for(unsigned b=0;b<n_boundary;b++)
   {
    // Determine number of nodes on boundary b
    const unsigned n_node = mesh_pt()->nboundary_node(b);
    // Loop over nodes on boundary b
    for(unsigned n=0;n<n_node;n++)
     {
      // Set up pointer to node
      Node* nod_pt = mesh_pt()->boundary_node_pt(b,n);
      // On all solid boundaries, pin all velocity components
      if(b!=3)
       {
        nod_pt->pin(0); // Radial (real)
        nod_pt->pin(1); // Radial (imaginary)
        nod_pt->pin(2); // Axial (real)
        nod_pt->pin(3); // Axial (imaginary)
        nod_pt->pin(4); // Azimuthal (real)
        nod_pt->pin(5); // Azimuthal (imaginary)
       }
      // On symmetry boundary, pin only radial and azimuthal velocity
      // components, unless we are looking at the k=1 azimuthal mode.
      // In this case, do not pin any velocity components on this boundary
      else
       {
        if(GlobalPhysicalVariables::k!=1)
         {
          nod_pt->pin(0); // Radial (real)
          nod_pt->pin(1); // Radial (imaginary)
          nod_pt->pin(4); // Azimuthal (real)
          nod_pt->pin(5); // Azimuthal (imaginary)
         }
       }
     } // End of loop over nodes on boundary b
   } // End of loop over mesh boundaries
  // ----------------------------------------------------------------
  // Complete the problem setup to make the elements fully functional
  // ----------------------------------------------------------------
  // Determine number of elements in mesh
  const unsigned n_element = mesh_pt()->nelement();
  // Loop over the elements
  for(unsigned e=0;e<n_element;e++)
   {
    // Upcast from GeneralisedElement to the present element
    PERTURBED_ELEMENT* el_pt
     = dynamic_cast<PERTURBED_ELEMENT*>(mesh_pt()->element_pt(e));
    // Set the Reynolds number
    el_pt->re_pt() = &GlobalPhysicalVariables::Re;
    // Set the Womersley number
    el_pt->re_st_pt() = &GlobalPhysicalVariables::ReSt;
    // The mesh remains fixed
    el_pt->disable_ALE();
    // Set the azimuthal wavenumber
    el_pt->azimuthal_mode_number_pt() = &GlobalPhysicalVariables::k;
   } // End of loop over elements
  // Fix pressure ONLY when looking for axisymmetric modes
  if(GlobalPhysicalVariables::k==0) { fix_pressure(0,0,0.0); }
  // ------------------------------------------------------------
  // Set up interaction between base and perturbed state problems
  // ------------------------------------------------------------
  // First interaction (base state velocities)
  Multi_domain_functions::
   setup_multi_domain_interaction<BASE_ELEMENT>
   (this,mesh_pt(),Base_state_mesh_pt,0);
  // Second interaction (base state velocity derivatives w.r.t. space)
  Multi_domain_functions::
    setup_multi_domain_interaction<BASE_ELEMENT>
   (this,mesh_pt(),Base_state_mesh_pt,1);
  // Set up equation numbering scheme
  std::cout << "Number of equations: " << assign_eqn_numbers() << std::endl;
 } // End of perturbed state constructor
References oomph::Problem::add_time_stepper_pt(), oomph::Problem::assign_eqn_numbers(), b, PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Base_state_mesh_pt, oomph::LinearSolver::disable_doc_time(), oomph::Problem::disable_info_in_newton_solve(), e(), PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::fix_pressure(), GlobalPhysicalVariables::k, oomph::Problem::linear_solver_pt(), PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::mesh_pt(), n, oomph::Data::pin(), GlobalPhysicalVariables::Re, GlobalPhysicalVariables::ReSt, and PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::time_stepper_pt().
~PerturbedStateProblem() [1/6]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::~PerturbedStateProblem () inline
Destructor (empty)
 {}
PerturbedStateProblem() [2/6]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::PerturbedStateProblem (const unsigned & n_r, const unsigned & n_z, const double & domain_height, Mesh * external_mesh_pt)
Constructor.
~PerturbedStateProblem() [2/6]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::~PerturbedStateProblem () inline
Destructor (empty)
 {}
PerturbedStateProblem() [3/6]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::PerturbedStateProblem (const unsigned & n_r, const unsigned & n_z, const double & domain_height, Mesh * external_mesh_pt)
Constructor.
~PerturbedStateProblem() [3/6]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::~PerturbedStateProblem () inline
Destructor (empty)
 {}
PerturbedStateProblem() [4/6]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::PerturbedStateProblem (const unsigned & n_r, const unsigned & n_z, const double & domain_height, Mesh * external_mesh_pt)
Constructor.
~PerturbedStateProblem() [4/6]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::~PerturbedStateProblem () inline
Destructor (empty)
 {}
PerturbedStateProblem() [5/6]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::PerturbedStateProblem (const unsigned & n_r, const unsigned & n_z, const double & radius_inner_cylinder, const double & radius_outer_cylinder, const double & l_z, Mesh * external_mesh_pt)
Constructor.
Constructor for perturbed state time-periodic Taylor–Couette problem.
  : Base_state_mesh_pt(external_mesh_pt),
    Inner_cylinder_radius(radius_inner_cylinder),
    Outer_cylinder_radius(radius_outer_cylinder),
    Domain_height(l_z)
 {
  // Be less verbose during newton solve
  Problem::disable_info_in_newton_solve();
  // Be less verbose about linear solve timings
  linear_solver_pt()->disable_doc_time();
  // Allocate the timestepper (this constructs the time object as well)
  add_time_stepper_pt(new SelfStartingBDF2);
  // Build and assign mesh
  Problem::mesh_pt() =
   new RectangularQuadMesh<PERTURBED_ELEMENT>(n_r,n_z,radius_inner_cylinder,
                                              radius_outer_cylinder,0.0,l_z,
                                              time_stepper_pt());
  // --------------------------------------------
  // Set the boundary conditions for this problem
  // --------------------------------------------
  // All nodes are free by default -- just pin the ones that have
  // Dirichlet conditions here
  // Determine number of mesh boundaries
  const unsigned n_boundary = mesh_pt()->nboundary();
  // Loop over mesh boundaries
  for(unsigned b=0;b<n_boundary;b++)
   {
    // Determine number of nodes on boundary b
    const unsigned n_node = mesh_pt()->nboundary_node(b);
    // Loop over nodes on boundary b
    for(unsigned n=0;n<n_node;n++)
     {
      // Pin values for axial velocity components on all boundaries
      mesh_pt()->boundary_node_pt(b,n)->pin(2); // Axial (real)
      mesh_pt()->boundary_node_pt(b,n)->pin(3); // Axial (imaginary)
      // Pin values for radial and azimuthal velocity components on
      // all solid boundaries
      if(b==1 || b==3)
       {
        mesh_pt()->boundary_node_pt(b,n)->pin(0); // Radial (real)
        mesh_pt()->boundary_node_pt(b,n)->pin(1); // Radial (imaginary)
        mesh_pt()->boundary_node_pt(b,n)->pin(4); // Azimuthal (real)
        mesh_pt()->boundary_node_pt(b,n)->pin(5); // Azimuthal (imaginary)
       }
     } // End of loop over nodes on boundary b
   } // End of loop over mesh boundaries
  // ----------------------------------------------------------------
  // Complete the problem setup to make the elements fully functional
  // ----------------------------------------------------------------
  // Determine number of elements in mesh
  const unsigned n_element = mesh_pt()->nelement();
  // Loop over the elements
  for(unsigned e=0;e<n_element;e++)
   {
    // Upcast from GeneralisedElement to the present element
    PERTURBED_ELEMENT* el_pt
     = dynamic_cast<PERTURBED_ELEMENT*>(mesh_pt()->element_pt(e));
    // Set the Reynolds number
    el_pt->re_pt() = &GlobalPhysicalVariables::Re;
    // Set the Womersley number
    el_pt->re_st_pt() = &GlobalPhysicalVariables::ReSt;
    // The mesh remains fixed
    el_pt->disable_ALE();
    // Set the azimuthal wavenumber
    el_pt->azimuthal_mode_number_pt() = &GlobalPhysicalVariables::k;
   } // End of loop over elements
  // Set the pressure in first element at 'node' 0 to 0.0
  fix_pressure(0,0,0.0);
  // ------------------------------------------------------------
  // Set up interaction between base and perturbed state problems
  // ------------------------------------------------------------
  // First interaction (base state velocities)
  Multi_domain_functions::
   setup_multi_domain_interaction<BASE_ELEMENT>
   (this,mesh_pt(),Base_state_mesh_pt,0);
  // Second interaction (base state velocity derivatives w.r.t. space)
  Multi_domain_functions::
    setup_multi_domain_interaction<BASE_ELEMENT>
   (this,mesh_pt(),Base_state_mesh_pt,1);
  // Set up equation numbering scheme
  std::cout << "Number of equations: " << assign_eqn_numbers() << std::endl;
 } // End of perturbed state constructor
References oomph::Problem::add_time_stepper_pt(), oomph::Problem::assign_eqn_numbers(), b, PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Base_state_mesh_pt, oomph::LinearSolver::disable_doc_time(), e(), PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::fix_pressure(), GlobalPhysicalVariables::k, oomph::Problem::linear_solver_pt(), PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::mesh_pt(), n, GlobalPhysicalVariables::Re, GlobalPhysicalVariables::ReSt, and PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::time_stepper_pt().
~PerturbedStateProblem() [5/6]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::~PerturbedStateProblem () inline
Destructor (empty)
 {}
PerturbedStateProblem() [6/6]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT , class TIMESTEPPER > PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT, TIMESTEPPER >::PerturbedStateProblem (const unsigned & n_r, const unsigned & n_z1, const unsigned & n_z2, const double & h1, const double & h2, SpineMesh * external_bulk_mesh_pt, int azimuthal_mode_number)
Constructor: Pass the width of the domain in the r direction, and the heights of both bottom (fluid 1) and top (fluid 2) layers. Also pass the number of elements in both horizontal regions in the r direction and the number of elements in all three vertical regions in the z direction, along with the fractions which determine the spacings of those regions. Also pass a pointer to the base state mesh.
Constructor for perturbed state Tuckerman counter-rotating lids problem
  : Base_state_bulk_mesh_pt(external_bulk_mesh_pt),
    Azimuthal_mode_number(azimuthal_mode_number)
 {
  // Always take one newton step even if the initial residuals are
  // below the required tolerance
  Problem::Always_take_one_newton_step = true;
  // Allocate the timestepper (this constructs the time object as well)
  add_time_stepper_pt(new TIMESTEPPER);
  // Build and assign mesh
  Bulk_mesh_pt = new TwoLayerPerturbedSpineMesh<PERTURBED_ELEMENT>
   (n_r,n_z1,n_z2,1.0,h1,h2,Base_state_bulk_mesh_pt,time_stepper_pt());
  // Create "surface mesh" that will contain only the interface elements.
  // The constructor just creates the mesh without giving it any elements,
  // nodes, etc.
  Surface_mesh_pt = new Mesh;
  // Add the two sub meshes to the problem
  add_sub_mesh(Bulk_mesh_pt);
  add_sub_mesh(Surface_mesh_pt);
  // Combine all submeshes into a single Mesh
  build_global_mesh();
  // -------------------------------------------------------------------
  // Get information from elements about the order of nodal data storage
  // -------------------------------------------------------------------
  // Get a pointer to the first element in the mesh -- note that we
  // are assuming that the indices will be the same in each element
  PERTURBED_ELEMENT* el_pt = dynamic_cast<PERTURBED_ELEMENT*>
   (Bulk_mesh_pt->element_pt(0));
  // Determine indices at which the perturbations to the nodal positions
  // are stored
  this->Xhat_nodal_index.resize(4);
  for(unsigned i=0;i<4;i++)
   {
    Xhat_nodal_index[i] = el_pt->xhat_index_lin_axi_nst(i);
   }
  // Determine indices at which velocities are stored
  this->U_nodal_index.resize(6);
  for(unsigned i=0;i<6;i++)
   {
    U_nodal_index[i] = el_pt->u_index_lin_axi_nst(i);
   }
  // Pass nodal indices of cosine (i=2) and sine (i=3) components of the
  // perturbation to the nodal z-position to the bulk mesh. This
  // information is used in the node_update function
  Bulk_mesh_pt->set_perturbation_to_nodal_positions_indices
   (Xhat_nodal_index[2],Xhat_nodal_index[3]);
  // --------------------------------------------
  // Set the boundary conditions for this problem
  // --------------------------------------------
  // All nodes are free by default -- just pin the ones that have
  // Dirichlet conditions here
  // Determine number of mesh boundaries
  const unsigned n_boundary = mesh_pt()->nboundary();
  // Loop over mesh boundaries
  for(unsigned b=0;b<n_boundary;b++)
   {
    // Determine number of nodes on boundary b
    const unsigned n_node = mesh_pt()->nboundary_node(b);
    // Loop over nodes on boundary b
    for(unsigned n=0;n<n_node;n++)
     {
      // On top and bottom solid boundaries, pin all velocity components
      if(b==0 || b==2)
       {
        mesh_pt()->boundary_node_pt(b,n)->pin(U_nodal_index[0]);
        mesh_pt()->boundary_node_pt(b,n)->pin(U_nodal_index[1]);
        mesh_pt()->boundary_node_pt(b,n)->pin(U_nodal_index[2]);
        mesh_pt()->boundary_node_pt(b,n)->pin(U_nodal_index[3]);
        mesh_pt()->boundary_node_pt(b,n)->pin(U_nodal_index[4]);
        mesh_pt()->boundary_node_pt(b,n)->pin(U_nodal_index[5]);
       }
      // On outer wall, pin only radial and azimuthal velocities
      // (slippery outer wall)
      else if(b==1)
       {
        mesh_pt()->boundary_node_pt(b,n)->pin(U_nodal_index[0]);
        mesh_pt()->boundary_node_pt(b,n)->pin(U_nodal_index[1]);
        mesh_pt()->boundary_node_pt(b,n)->pin(U_nodal_index[4]);
        mesh_pt()->boundary_node_pt(b,n)->pin(U_nodal_index[5]);
       }
      // On symmetry boundary, boundary conditions differ depending on
      // the azimuthal mode number
      else if(b==3)
       {
        // If k=0, pin only radial and azimuthal velocity components
        if(Azimuthal_mode_number==0)
         {
          mesh_pt()->boundary_node_pt(b,n)->pin(U_nodal_index[0]);
          mesh_pt()->boundary_node_pt(b,n)->pin(U_nodal_index[1]);
          mesh_pt()->boundary_node_pt(b,n)->pin(U_nodal_index[4]);
          mesh_pt()->boundary_node_pt(b,n)->pin(U_nodal_index[5]);
         }
        // If k is ODD, pin axial velocity only
        else if(Azimuthal_mode_number%2)
         {
          mesh_pt()->boundary_node_pt(b,n)->pin(U_nodal_index[2]);
          mesh_pt()->boundary_node_pt(b,n)->pin(U_nodal_index[3]);
         }
        // If k is EVEN (and non-zero), pin all velocity components
        else
         {
          mesh_pt()->boundary_node_pt(b,n)->pin(U_nodal_index[0]);
          mesh_pt()->boundary_node_pt(b,n)->pin(U_nodal_index[1]);
          mesh_pt()->boundary_node_pt(b,n)->pin(U_nodal_index[2]);
          mesh_pt()->boundary_node_pt(b,n)->pin(U_nodal_index[3]);
          mesh_pt()->boundary_node_pt(b,n)->pin(U_nodal_index[4]);
          mesh_pt()->boundary_node_pt(b,n)->pin(U_nodal_index[5]);
         }
       }
     } // End of loop over nodes on boundary b
   } // End of loop over mesh boundaries
  // Pin all perturbations to the nodal positions (since these are
  // dependent variables and therefore not dofs)
  const unsigned n_node = Bulk_mesh_pt->nnode();
  for(unsigned n=0;n<n_node;n++)
   {
    for(unsigned i=0;i<4;i++)
     {
      Bulk_mesh_pt->node_pt(n)->pin(Xhat_nodal_index[i]);
     }
   }
  // ---------------------------------------------------
  // If k==0, pin all dofs corresponding to "sine parts"
  // ---------------------------------------------------
  if(Azimuthal_mode_number==0)
   {
    // Pin all the sine components of the velocity values
    for(unsigned n=0;n<n_node;n++)
     {
      Bulk_mesh_pt->node_pt(n)->pin(U_nodal_index[1]);
      Bulk_mesh_pt->node_pt(n)->pin(U_nodal_index[3]);
      Bulk_mesh_pt->node_pt(n)->pin(U_nodal_index[5]);
     }
    // Pin all the sine components of the pressure dofs
    const unsigned n_element = Bulk_mesh_pt->nelement();
    for(unsigned e=0;e<n_element;e++)
     {
      // Loop over the three pressure dofs (sine parts)
      for(unsigned i=0;i<3;i++)
       {
        // Pin the values and set them equal to zero
        dynamic_cast<PERTURBED_ELEMENT*>(mesh_pt()->element_pt(e))->
         fix_sine_component_of_pressure(i,0.0);
       }
     }
    // Pin all the sine components of the perturbed spine heights and set
    // them to zero
    const unsigned n_perturbed_spine = Bulk_mesh_pt->nspine();
    for(unsigned i=0;i<n_perturbed_spine;i++)
     {
      Bulk_mesh_pt->perturbed_spine_pt(i)->height_pt()->pin(1);
      Bulk_mesh_pt->perturbed_spine_pt(i)->height(1) = 0.0;
     }
   } // End of if k==0
  // -------------------------------------------------------------------
  // If k>0, pin interface height on the symmetry axis (both components)
  // -------------------------------------------------------------------
  if(Azimuthal_mode_number>0)
   {
    Bulk_mesh_pt->perturbed_spine_pt(0)->height_pt()->pin(0);
    Bulk_mesh_pt->perturbed_spine_pt(0)->height_pt()->pin(1);
    Bulk_mesh_pt->perturbed_spine_pt(0)->height(0) = 0.0;
    Bulk_mesh_pt->perturbed_spine_pt(0)->height(1) = 0.0;
   }
  // ----------------------------------------------------------------
  // Complete the problem setup to make the elements fully functional
  // ----------------------------------------------------------------
  // Determine number of bulk elements in lower and upper fluid
  const unsigned n_lower = Bulk_mesh_pt->nlower();
  const unsigned n_upper = Bulk_mesh_pt->nupper();
  // Loop over bulk elements in lower fluid
  for(unsigned e=0;e<n_lower;e++)
   {
    // Upcast from GeneralisedElement to the present element
    PERTURBED_ELEMENT* el_pt = dynamic_cast<PERTURBED_ELEMENT*>
     (Bulk_mesh_pt->lower_layer_element_pt(e));
    // Set the Reynolds number
    el_pt->re_pt() = &GlobalPhysicalVariables::Re;
    // Set the Womersley number
    el_pt->re_st_pt() = &GlobalPhysicalVariables::ReSt;
    // Set the product of the Reynolds number and inverse Froude number
    el_pt->re_invfr_pt() = &GlobalPhysicalVariables::ReInvFr;
    // Set the direction of gravity
    el_pt->g_pt() = &GlobalPhysicalVariables::G;
    // Set the azimuthal mode number
    el_pt->azimuthal_mode_number_pt() = &Azimuthal_mode_number;
    // These terms in the Jacobian matrix are provided analytically, so
    // by filling them in from geometric data we would be "double counting"
    el_pt->enable_bypass_fill_in_jacobian_from_geometric_data();
   } // End of loop over bulk elements in lower fluid
  // Loop over bulk elements in upper fluid
  for(unsigned e=0;e<n_upper;e++)
   {
    // Upcast from GeneralisedElement to the present element
    PERTURBED_ELEMENT* el_pt = dynamic_cast<PERTURBED_ELEMENT*>
     (Bulk_mesh_pt->upper_layer_element_pt(e));
    // Set the Reynolds number
    el_pt->re_pt() = &GlobalPhysicalVariables::Re;
    // Set the Womersley number
    el_pt->re_st_pt() = &GlobalPhysicalVariables::ReSt;
    // Set the product of the Reynolds number and inverse Froude number
    el_pt->re_invfr_pt() = &GlobalPhysicalVariables::ReInvFr;
    // Set the direction of gravity
    el_pt->g_pt() = &GlobalPhysicalVariables::G;
    // Set the viscosity ratio
    el_pt->viscosity_ratio_pt() = &GlobalPhysicalVariables::Viscosity_Ratio;
    // Set the density ratio
    el_pt->density_ratio_pt() = &GlobalPhysicalVariables::Density_Ratio;
    // Set the azimuthal mode number
    el_pt->azimuthal_mode_number_pt() = &Azimuthal_mode_number;
    // These terms in the Jacobian matrix are provided analytically, so
    // by filling them in from geometric data we would be "double counting"
    el_pt->enable_bypass_fill_in_jacobian_from_geometric_data();
   } // End of loop over bulk elements in upper fluid
  // Fix pressure ONLY when looking for axisymmetric modes
  if(Azimuthal_mode_number==0) { fix_pressure(0,0,0.0); }
  // ------------------------------------------------------------
  // Set up interaction between base and perturbed state problems
  // ------------------------------------------------------------
  // First interaction (base state velocities)
  Multi_domain_functions::setup_multi_domain_interaction<BASE_ELEMENT>
   (this,mesh_pt(),external_bulk_mesh_pt,0);
  // Second interaction (base state velocity derivatives w.r.t.
  // global spatial coordinates)
  Multi_domain_functions::setup_multi_domain_interaction<BASE_ELEMENT>
   (this,mesh_pt(),external_bulk_mesh_pt,1);
  // Third interaction (base state pressure)
  Multi_domain_functions::setup_multi_domain_interaction<BASE_ELEMENT>
   (this,mesh_pt(),external_bulk_mesh_pt,2);
  // Fourth interaction (base state velocity derivatives w.r.t. time)
  Multi_domain_functions::setup_multi_domain_interaction<BASE_ELEMENT>
   (this,mesh_pt(),external_bulk_mesh_pt,3);
  // Fourth interaction (base state velocity derivatives w.r.t. time)
  Multi_domain_functions::setup_multi_domain_interaction<BASE_ELEMENT>
   (this,mesh_pt(),external_bulk_mesh_pt,3);
  // Fifth interaction (base state velocity derivatives w.r.t.
  // local spatial coordinates)
  Multi_domain_functions::setup_multi_domain_interaction<BASE_ELEMENT>
   (this,mesh_pt(),external_bulk_mesh_pt,4);
  // Set up equation numbering scheme
  std::cout << "Number of equations: " << assign_eqn_numbers() << std::endl;
 } // End of perturbed state constructor
References oomph::Problem::add_sub_mesh(), oomph::Problem::add_time_stepper_pt(), oomph::Problem::assign_eqn_numbers(), PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Azimuthal_mode_number, b, PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Base_state_bulk_mesh_pt, oomph::Problem::build_global_mesh(), PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Bulk_mesh_pt, GlobalPhysicalVariables::Density_Ratio, e(), oomph::Mesh::element_pt(), PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::fix_pressure(), GlobalPhysicalVariables::G, oomph::PerturbedSpine::height(), oomph::PerturbedSpine::height_pt(), i, oomph::TwoLayerPerturbedSpineMesh< ELEMENT >::lower_layer_element_pt(), PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::mesh_pt(), n, oomph::Mesh::nelement(), oomph::TwoLayerPerturbedSpineMesh< ELEMENT >::nlower(), oomph::Mesh::nnode(), oomph::PerturbedSpineMesh::node_pt(), oomph::PerturbedSpineMesh::nspine(), oomph::TwoLayerPerturbedSpineMesh< ELEMENT >::nupper(), oomph::PerturbedSpineMesh::perturbed_spine_pt(), oomph::Data::pin(), GlobalPhysicalVariables::Re, GlobalPhysicalVariables::ReInvFr, GlobalPhysicalVariables::ReSt, oomph::TwoLayerPerturbedSpineMesh< ELEMENT >::set_perturbation_to_nodal_positions_indices(), PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Surface_mesh_pt, PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::time_stepper_pt(), PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::U_nodal_index, oomph::TwoLayerPerturbedSpineMesh< ELEMENT >::upper_layer_element_pt(), GlobalPhysicalVariables::Viscosity_Ratio, and PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Xhat_nodal_index.
~PerturbedStateProblem() [6/6]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::~PerturbedStateProblem () inline
Destructor (empty)
 {}
Member Function Documentation
actions_after_adapt() [1/2]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::actions_after_adapt () inline virtual
After adaptation: Pin pressure again (the previously pinned value might have disappeared) and pin redudant pressure dofs
Reimplemented from oomph::Problem.
   {
    // Unpin all pressure dofs
    RefineableLinearisedAxisymmetricNavierStokesEquations::
     unpin_all_pressure_dofs(mesh_pt()->element_pt());
    // Pin redudant pressure dofs
    RefineableLinearisedAxisymmetricNavierStokesEquations::
     pin_redundant_nodal_pressures(mesh_pt()->element_pt());
    // Fix pressure ONLY when looking for axisymmetric modes
    if(GlobalPhysicalVariables::k==0) { fix_pressure(0,0,0.0); }
    // Set external elements for the multi-domain solution
    // First interaction (base state velocities)
    Multi_domain_functions::
     setup_multi_domain_interaction<BASE_ELEMENT>
     (this,mesh_pt(),Base_state_mesh_pt,0);
    // Second interaction (base state velocity derivatives w.r.t. space)
    Multi_domain_functions::
     setup_multi_domain_interaction<BASE_ELEMENT>
     (this,mesh_pt(),Base_state_mesh_pt,1);
   } // End of actions_after_adapt
References GlobalPhysicalVariables::k.
actions_after_adapt() [2/2]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::actions_after_adapt () inline virtual
After adaptation: Pin pressure again (the previously pinned value might have disappeared) and pin redudant pressure dofs
Reimplemented from oomph::Problem.
   {
    // Unpin all pressure dofs
    RefineableLinearisedAxisymmetricNavierStokesEquations::
     unpin_all_pressure_dofs(mesh_pt()->element_pt());
    // Pin redudant pressure dofs
    RefineableLinearisedAxisymmetricNavierStokesEquations::
     pin_redundant_nodal_pressures(mesh_pt()->element_pt());
    // Fix pressure ONLY when looking for axisymmetric modes
    if(GlobalPhysicalVariables::k==0) { fix_pressure(0,0,0.0); }
    // Set external elements for the multi-domain solution
    // First interaction (base state velocities)
    Multi_domain_functions::
     setup_multi_domain_interaction<BASE_ELEMENT>
     (this,mesh_pt(),Base_state_mesh_pt,0);
    // Second interaction (base state velocity derivatives w.r.t. space)
    Multi_domain_functions::
     setup_multi_domain_interaction<BASE_ELEMENT>
     (this,mesh_pt(),Base_state_mesh_pt,1);
   } // End of actions_after_adapt
References GlobalPhysicalVariables::k.
actions_after_implicit_timestep() [1/6]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::actions_after_implicit_timestep () inline virtual
Update the problem specs after solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_after_implicit_timestep() [2/6]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::actions_after_implicit_timestep () inline virtual
Update the problem specs after solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_after_implicit_timestep() [3/6]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::actions_after_implicit_timestep () inline virtual
Update the problem specs after solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_after_implicit_timestep() [4/6]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::actions_after_implicit_timestep () inline virtual
Update the problem specs after solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_after_implicit_timestep() [5/6]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::actions_after_implicit_timestep () inline virtual
Update the problem specs after solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_after_implicit_timestep() [6/6]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::actions_after_implicit_timestep () inline private virtual
Update the problem specs after solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_after_newton_solve() [1/6]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::actions_after_newton_solve () inline virtual
Update after solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_after_newton_solve() [2/6]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::actions_after_newton_solve () inline virtual
Update after solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_after_newton_solve() [3/6]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::actions_after_newton_solve () inline virtual
Update after solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_after_newton_solve() [4/6]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::actions_after_newton_solve () inline virtual
Update after solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_after_newton_solve() [5/6]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::actions_after_newton_solve () inline virtual
Update after solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_after_newton_solve() [6/6]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::actions_after_newton_solve () inline private virtual
Update after solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_before_implicit_timestep() [1/6]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::actions_before_implicit_timestep () inline virtual
Actions before timestep (empty)
Reimplemented from oomph::Problem.
 {}
actions_before_implicit_timestep() [2/6]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::actions_before_implicit_timestep () inline virtual
Actions before timestep (empty)
Reimplemented from oomph::Problem.
 {}
actions_before_implicit_timestep() [3/6]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::actions_before_implicit_timestep () inline virtual
Actions before timestep (empty)
Reimplemented from oomph::Problem.
 {}
actions_before_implicit_timestep() [4/6]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::actions_before_implicit_timestep () inline virtual
Actions before timestep (empty)
Reimplemented from oomph::Problem.
 {}
actions_before_implicit_timestep() [5/6]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::actions_before_implicit_timestep () inline virtual
Actions before timestep (empty)
Reimplemented from oomph::Problem.
 {}
actions_before_implicit_timestep() [6/6]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::actions_before_implicit_timestep () inline private virtual
Actions before timestep (empty)
Reimplemented from oomph::Problem.
   {
    // Shift perturbed spine height history values
    // -------------------------------------------
    const unsigned n_perturbed_spine = Bulk_mesh_pt->nspine();
    for(unsigned i=0;i<n_perturbed_spine;i++)
     {
      Bulk_mesh_pt->perturbed_spine_pt(i)->height_pt()->time_stepper_pt()->
       shift_time_values(Bulk_mesh_pt->perturbed_spine_pt(i)->height_pt());
     }
   }
References i.
actions_before_newton_convergence_check()
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::actions_before_newton_convergence_check () inline private virtual
Update mesh to have nodal positions equal to that of the base state mesh
Reimplemented from oomph::Problem.
   {
    Bulk_mesh_pt->node_update();
   }
actions_before_newton_solve() [1/6]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::actions_before_newton_solve () inline virtual
Update before solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_before_newton_solve() [2/6]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::actions_before_newton_solve () inline virtual
Update before solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_before_newton_solve() [3/6]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::actions_before_newton_solve () inline virtual
Update before solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_before_newton_solve() [4/6]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::actions_before_newton_solve () inline virtual
Update before solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_before_newton_solve() [5/6]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::actions_before_newton_solve () inline virtual
Update before solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_before_newton_solve() [6/6]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::actions_before_newton_solve () inline private virtual
Update before solve (empty)
Reimplemented from oomph::Problem.
 {}
base_state_bulk_mesh_pt()
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > TwoLayerSpineMesh<BASE_ELEMENT>* PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::base_state_bulk_mesh_pt () inline
Access function for the base state mesh.
   {
    return dynamic_cast<TwoLayerSpineMesh<BASE_ELEMENT>*>
     (Base_state_bulk_mesh_pt);
   }
base_state_mesh_pt() [1/5]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > RectangularQuadMesh<BASE_ELEMENT>* PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::base_state_mesh_pt () inline
Access function for the base state mesh.
   {
    return dynamic_cast<RectangularQuadMesh<BASE_ELEMENT>*>
     (Base_state_mesh_pt);
   }
base_state_mesh_pt() [2/5]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > RefineableRectangularQuadMesh<BASE_ELEMENT>* PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::base_state_mesh_pt () inline
Access function for the base state mesh.
   {
    return dynamic_cast<RefineableRectangularQuadMesh<BASE_ELEMENT>*>
     (Base_state_mesh_pt);
   }
base_state_mesh_pt() [3/5]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > RectangularQuadMesh<BASE_ELEMENT>* PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::base_state_mesh_pt () inline
Access function for the base state mesh.
   {
    return dynamic_cast<RectangularQuadMesh<BASE_ELEMENT>*>
     (Base_state_mesh_pt);
   }
base_state_mesh_pt() [4/5]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > RefineableRectangularQuadMesh<BASE_ELEMENT>* PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::base_state_mesh_pt () inline
Access function for the base state mesh.
   {
    return dynamic_cast<RefineableRectangularQuadMesh<BASE_ELEMENT>*>
     (Base_state_mesh_pt);
   }
base_state_mesh_pt() [5/5]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > RectangularQuadMesh<BASE_ELEMENT>* PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::base_state_mesh_pt () inline
Access function for the base state mesh.
   {
    return dynamic_cast<RectangularQuadMesh<BASE_ELEMENT>*>
     (Base_state_mesh_pt);
   }
bulk_mesh_pt()
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > TwoLayerPerturbedSpineMesh<PERTURBED_ELEMENT>* PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::bulk_mesh_pt () inline
Access function for bulk mesh.
   {
    return Bulk_mesh_pt;
   }
close_trace_file() [1/4]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::close_trace_file () inline
Clear and close trace file.
 { Trace_file.clear(); Trace_file.close(); }
References oomph::Problem_Parameter::Trace_file.
close_trace_file() [2/4]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::close_trace_file () inline
Clear and close trace file.
 { Trace_file.clear(); Trace_file.close(); }
References oomph::Problem_Parameter::Trace_file.
close_trace_file() [3/4]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::close_trace_file () inline
Clear and close trace file.
   {
    Trace_file.clear();
    Trace_file.close();
   }
References oomph::Problem_Parameter::Trace_file.
close_trace_file() [4/4]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::close_trace_file () inline
Clear and close trace file.
 { Trace_file.clear(); Trace_file.close(); }
References oomph::Problem_Parameter::Trace_file.
create_interface_elements()
template<class BASE_ELEMENT , class PERTURBED_ELEMENT , class TIMESTEPPER > void PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT, TIMESTEPPER >::create_interface_elements
Create interface elements at boundary between upper and lower layers.
Create Interface Elements at the free surface between the two fluids in the mesh pointed to by bulk_mesh_pt and add the elements to the Mesh object pointeed to by surface_mesh_pt.
 {
  // Determine the number of horizontal elements
  const unsigned n_r = this->Bulk_mesh_pt->nx();
  // Determine number of bulk elements in the lower layer
  const unsigned n_z1 = this->Bulk_mesh_pt->ny1();
  // Loop over the horizontal elements
  for(unsigned e=0;e<n_r;e++)
   {
    // Construct a new 1D line element on the face on which the local
    // coordinate 1 is fixed at its max. value (1) -- Face 2
    FiniteElement* interface_element_element_pt =
     new PerturbedSpineLinearisedAxisymmetricFluidInterfaceElement
     <PERTURBED_ELEMENT>
     (this->Bulk_mesh_pt->finite_element_pt(n_r*(n_z1-1)+e),2);
    // Add the interface element to the surface mesh
    this->Surface_mesh_pt->add_element_pt(interface_element_element_pt);
   }
  // ----------------------------------------------------------------
  // Complete the problem setup to make the elements fully functional
  // ----------------------------------------------------------------
  // Determine number of 1D interface elements in mesh
  const unsigned n_interface_element = this->Surface_mesh_pt->nelement();
  // Loop over interface elements
  for(unsigned e=0;e<n_interface_element;e++)
   {
    // Upcast from GeneralisedElement to the present element
    PerturbedSpineLinearisedAxisymmetricFluidInterfaceElement
     <PERTURBED_ELEMENT>* el_pt =
     dynamic_cast<PerturbedSpineLinearisedAxisymmetricFluidInterfaceElement
     <PERTURBED_ELEMENT>*>(this->Surface_mesh_pt->element_pt(e));
    // Set the Strouhal number
    el_pt->st_pt() = &GlobalPhysicalVariables::St;
    // Set the Capillary number
    el_pt->ca_pt() = &GlobalPhysicalVariables::Ca;
    // Set the azimuthal mode number
    el_pt->azimuthal_mode_number_pt() = &Azimuthal_mode_number;
    // These terms in the Jacobian matrix are provided analytically, so
    // by filling them in from geometric data we would be "double counting"
    el_pt->enable_bypass_fill_in_jacobian_from_geometric_data();
   }
 } // End of create_interface_elements
References GlobalPhysicalVariables::Ca, e(), GlobalPhysicalVariables::St, and oomph::LinearisedAxisymmetricFluidInterfaceElement::st_pt().
create_trace_file() [1/4]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::create_trace_file (DocInfo & doc_info) inline
Create a trace file.
   {
    // Open trace file
    char filename[256];
    sprintf(filename,"%s/perturbed_trace_k%i_Re%4.2f.dat",
            doc_info.directory().c_str(),
            GlobalPhysicalVariables::k,
            GlobalPhysicalVariables::Re_current);
    Trace_file.open(filename);
   }
References oomph::DocInfo::directory(), MergeRestartFiles::filename, GlobalPhysicalVariables::k, GlobalPhysicalVariables::Re_current, and oomph::Problem_Parameter::Trace_file.
create_trace_file() [2/4]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::create_trace_file (DocInfo & doc_info) inline
Create a trace file.
   {
    // Open trace file
    char filename[256];
    sprintf(filename,"%s/perturbed_trace_k%i_Re%4.2f.dat",
            doc_info.directory().c_str(),
            GlobalPhysicalVariables::k,
            GlobalPhysicalVariables::Re_current);
    Trace_file.open(filename);
   }
References oomph::DocInfo::directory(), MergeRestartFiles::filename, GlobalPhysicalVariables::k, GlobalPhysicalVariables::Re_current, and oomph::Problem_Parameter::Trace_file.
create_trace_file() [3/4]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::create_trace_file (DocInfo & doc_info) inline
Create a trace file.
   {
    // Open trace file
    char filename[256];
    sprintf(filename,"%s/perturbed_trace_epsilon%2.1f_Re%4.2f.dat",
            doc_info.directory().c_str(),
            GlobalPhysicalVariables::Epsilon,
            GlobalPhysicalVariables::MMC_Re_current);
    Trace_file.open(filename);
   }
References oomph::DocInfo::directory(), GlobalPhysicalVariables::Epsilon, MergeRestartFiles::filename, GlobalPhysicalVariables::MMC_Re_current, and oomph::Problem_Parameter::Trace_file.
create_trace_file() [4/4]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::create_trace_file (DocInfo *& doc_info_pt) inline
Create and initialise a trace file.
   {
    // Open trace file
    char filename[256];
    sprintf(filename,"%s/perturbed_trace_k%i.dat",
            doc_info_pt->directory().c_str(),
            Azimuthal_mode_number);
    Trace_file.open(filename);
    // Initialise
    Trace_file << "time, height (cosine), height (sine), growth_rate, d_kinetic_energy_dt, kinetic_energy"
               << std::endl;
   }
References oomph::DocInfo::directory(), MergeRestartFiles::filename, and oomph::Problem_Parameter::Trace_file.
doc_solution() [1/6]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::doc_solution (DocInfo & doc_info)
Doc the solution.
Document the perturbed state solution.
 {
  ofstream some_file;
  char filename[256];
  // Set number of plot points (in each coordinate direction)
  const unsigned npts = 5;
  // Open solution output file
  sprintf(filename,"%s/perturbed_soln%i.dat",
          doc_info.directory().c_str(),
          doc_info.number());
  some_file.open(filename);
  // Output solution to file
  mesh_pt()->output(some_file,npts);
  // Close solution output file
  some_file.close();
 } // End of doc_solution for perturbed state
References oomph::DocInfo::directory(), MergeRestartFiles::filename, and oomph::DocInfo::number().
doc_solution() [2/6]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::doc_solution (DocInfo & doc_info)
Doc the solution.
doc_solution() [3/6]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::doc_solution (DocInfo & doc_info, const bool & output_soln = true)
Doc the solution.
Document the perturbed state solution.
 {
  // Create vector of dofs
  DoubleVector dofs;
  // Get dofs
  this->get_dofs(dofs);
  // Get L2 norm of dof vector
  const double dof_norm = dofs.norm();
  // Document in trace file
  Trace_file << time_pt()->time() << " " << dof_norm << std::endl;
  // If desired, output solution to file
  if(output_soln)
   {
    ofstream some_file;
    char filename[256];
    // Set number of plot points (in each coordinate direction)
    const unsigned npts = 5;
    // Open solution output file
    sprintf(filename,"%s/perturbed_soln_k%i_Re%4.2f_soln%i.dat",
            doc_info.directory().c_str(),
            GlobalPhysicalVariables::k,
            GlobalPhysicalVariables::Re_current,
            doc_info.number());
    some_file.open(filename);
    // Output solution to file
    mesh_pt()->output(some_file,npts);
    // Close solution output file
    some_file.close();
   }
 } // End of doc_solution for perturbed state
References oomph::DocInfo::directory(), MergeRestartFiles::filename, GlobalPhysicalVariables::k, oomph::DoubleVector::norm(), oomph::DocInfo::number(), GlobalPhysicalVariables::Re_current, and oomph::Problem_Parameter::Trace_file.
doc_solution() [4/6]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::doc_solution (DocInfo & doc_info, const bool & output_soln = true)
Doc the solution.
doc_solution() [5/6]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::doc_solution (DocInfo & doc_info, const bool & output_soln = true)
Doc the solution.
doc_solution() [6/6]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT , class TIMESTEPPER > void PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT, TIMESTEPPER >::doc_solution (DocInfo *& doc_info_pt, const bool & output_soln = true)
Doc the solution.
Document the perturbed state solution.
 {
  // Decide which spine to use for documenting heights in trace file
  // ---------------------------------------------------------------
  // Initialise "trace spine"
  unsigned trace_spine = 0;
  // Determine the number of spines in the mesh
  const unsigned n_spine = Bulk_mesh_pt->nspine();
  // Make decision based on azimuthal mode number
  if(Azimuthal_mode_number==0) { trace_spine = 0; }
  else { trace_spine = (n_spine-1)/2; }
  // Compute kinetic energy of perturbation
  // --------------------------------------
  // Initialise kinetic energy and its derivative w.r.t. time
  double kinetic_energy = 0.0;
  double d_kinetic_energy_dt = 0.0;
  // Loop over bulk elements in lower layer
  const unsigned n_lower = Bulk_mesh_pt->nlower();
  for(unsigned e=0;e<n_lower;e++)
   {
    // Upcast from GeneralisedElement to the present element
    PERTURBED_ELEMENT *el_pt = dynamic_cast<PERTURBED_ELEMENT*>
     (Bulk_mesh_pt->lower_layer_element_pt(e));
    // Initialise element's contributions to kinetic energy and its deriv
    double el_kinetic_energy = 0.0;
    double el_d_kinetic_energy_dt = 0.0;
    // Compute element's contributions to kinetic energy and its deriv
    el_pt->dkin_energy_dt(d_kinetic_energy_dt,el_kinetic_energy);
    // Add contribution to "global" kinetic energy and its deriv
    // (Don't forget to multiply through by the element's density ratio
    // in both cases)
    kinetic_energy += (el_pt->density_ratio())*el_kinetic_energy;
    d_kinetic_energy_dt += (el_pt->density_ratio())*el_d_kinetic_energy_dt;
   }
  // Loop over bulk elements in upper layer
  const unsigned n_upper = Bulk_mesh_pt->nupper();
  for(unsigned e=0;e<n_upper;e++)
   {
    // Upcast from GeneralisedElement to the present element
    PERTURBED_ELEMENT *el_pt = dynamic_cast<PERTURBED_ELEMENT*>
     (Bulk_mesh_pt->upper_layer_element_pt(e));
    // Initialise element's contributions to kinetic energy and its deriv
    double el_kinetic_energy = 0.0;
    double el_d_kinetic_energy_dt = 0.0;
    // Compute element's contributions to kinetic energy and its deriv
    el_pt->dkin_energy_dt(d_kinetic_energy_dt,el_kinetic_energy);
    // Add contribution to "global" kinetic energy and its deriv
    // (Don't forget to multiply through by the element's density ratio
    // in both cases)
    kinetic_energy += (el_pt->density_ratio())*el_kinetic_energy;
    d_kinetic_energy_dt += (el_pt->density_ratio())*el_d_kinetic_energy_dt;
   }
  // Compute growth rate by considering relative growth
  // (see A. Hazel and R. Hewitt's torus linear stab paper 2011, page 21)
  double growth_rate = 0.0;
  if(kinetic_energy!=0.0)
   {
    growth_rate = (0.5*d_kinetic_energy_dt)/kinetic_energy;
   }
  // Document in trace file
  Trace_file << time_pt()->time() << " "
             << Bulk_mesh_pt->perturbed_spine_pt(trace_spine)->height(0)
             << " "
             << Bulk_mesh_pt->perturbed_spine_pt(trace_spine)->height(1)
             << " "
             << growth_rate << " "
             << d_kinetic_energy_dt << " "
             << kinetic_energy << std::endl;
  // If desired, output solution to file
  if(output_soln)
   {
    ofstream some_file;
    char filename[256];
    // Set number of plot points (in each coordinate direction)
    const unsigned npts_bulk = 5;
    const unsigned npts_surface = 5;
    // Open solution output file
    sprintf(filename,"%s/perturbed_k%i_soln%i.dat",
            doc_info_pt->directory().c_str(),
            Azimuthal_mode_number,
            doc_info_pt->number());
    some_file.open(filename);
    // Output solution to file
    Bulk_mesh_pt->output(some_file,npts_bulk);
    // Close solution output file
    some_file.close();
    // Open interface solution output file
    sprintf(filename,
            "%s/perturbation_to_interface_k%i_soln%i.dat",
            doc_info_pt->directory().c_str(),
            Azimuthal_mode_number,
            doc_info_pt->number());
    some_file.open(filename);
    // Output solution to file
    const unsigned n_interface_element = Surface_mesh_pt->nelement();
    for(unsigned e=0;e<n_interface_element;e++)
     {
      // Upcast from GeneralisedElement to the present element
      PerturbedSpineLinearisedAxisymmetricFluidInterfaceElement
       <PERTURBED_ELEMENT>* el_pt =
       dynamic_cast<PerturbedSpineLinearisedAxisymmetricFluidInterfaceElement
       <PERTURBED_ELEMENT>*>(Surface_mesh_pt->element_pt(e));
      // Output solution to file
      el_pt->output_perturbation_to_interface(some_file,npts_surface);
     }
    // Close solution output file
    some_file.close();
    // Open interface solution output file
    sprintf(filename,
            "%s/combined_interface_position_k%i_soln%i.dat",
            doc_info_pt->directory().c_str(),
            Azimuthal_mode_number,
            doc_info_pt->number());
    some_file.open(filename);
    // Output solution to file
    for(unsigned e=0;e<n_interface_element;e++)
     {
      // Upcast from GeneralisedElement to the present element
      PerturbedSpineLinearisedAxisymmetricFluidInterfaceElement
       <PERTURBED_ELEMENT>* el_pt =
       dynamic_cast<PerturbedSpineLinearisedAxisymmetricFluidInterfaceElement
       <PERTURBED_ELEMENT>*>(Surface_mesh_pt->element_pt(e));
      // Output solution to file
      el_pt->output_interface_position(some_file,npts_surface);
     }
    // Close solution output file
    some_file.close();
   }
 } // End of doc_solution for perturbed state
References oomph::DocInfo::directory(), e(), MergeRestartFiles::filename, oomph::DocInfo::number(), oomph::PerturbedSpineLinearisedAxisymmetricFluidInterfaceElement< ELEMENT >::output_interface_position(), oomph::PerturbedSpineLinearisedAxisymmetricFluidInterfaceElement< ELEMENT >::output_perturbation_to_interface(), and oomph::Problem_Parameter::Trace_file.
fix_pressure() [1/6]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::fix_pressure (const unsigned & e, const unsigned & pdof, const double & pvalue) inline private
Fix pressure in element e at pressure dof pdof and set to pvalue.
   {
    dynamic_cast<PERTURBED_ELEMENT*>(mesh_pt()->element_pt(e))
     ->fix_pressure(pdof,pvalue);
   }
References e().
Referenced by PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::PerturbedStateProblem().
fix_pressure() [2/6]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::fix_pressure (const unsigned & e, const unsigned & pdof, const double & pvalue) inline private
Fix pressure in element e at pressure dof pdof and set to pvalue.
   {
    dynamic_cast<PERTURBED_ELEMENT*>(mesh_pt()->element_pt(e))
     ->fix_pressure(pdof,pvalue);
   }
References e().
fix_pressure() [3/6]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::fix_pressure (const unsigned & e, const unsigned & pdof, const double & pvalue) inline private
Fix pressure in element e at pressure dof pdof and set to pvalue.
   {
    dynamic_cast<PERTURBED_ELEMENT*>(mesh_pt()->element_pt(e))
     ->fix_pressure(pdof,pvalue);
   }
References e().
fix_pressure() [4/6]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::fix_pressure (const unsigned & e, const unsigned & pdof, const double & pvalue) inline private
Fix pressure in element e at pressure dof pdof and set to pvalue.
   {
    dynamic_cast<PERTURBED_ELEMENT*>(mesh_pt()->element_pt(e))
     ->fix_pressure(pdof,pvalue);
   }
References e().
fix_pressure() [5/6]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::fix_pressure (const unsigned & e, const unsigned & pdof, const double & pvalue) inline private
Fix pressure in element e at pressure dof pdof and set to pvalue.
   {
    dynamic_cast<PERTURBED_ELEMENT*>(mesh_pt()->element_pt(e))
     ->fix_pressure(pdof,pvalue);
   }
References e().
fix_pressure() [6/6]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::fix_pressure (const unsigned & e, const unsigned & pdof, const double & pvalue) inline private
Fix pressure in element e at pressure dof pdof and set to pvalue.
   {
    dynamic_cast<PERTURBED_ELEMENT*>(mesh_pt()->element_pt(e))
     ->fix_pressure(pdof,pvalue);
   }
References e().
initialise_trace_file() [1/3]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::initialise_trace_file () inline
Initialise trace file (print column headings)
   {
    Trace_file << "time, norm_of_dof_vector" << std::endl;
   }
References oomph::Problem_Parameter::Trace_file.
initialise_trace_file() [2/3]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::initialise_trace_file () inline
Initialise trace file (print column headings)
   {
    Trace_file << "time, norm_of_dof_vector" << std::endl;
   }
References oomph::Problem_Parameter::Trace_file.
initialise_trace_file() [3/3]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::initialise_trace_file () inline
Initialise trace file (print column headings)
   {
    Trace_file << "time, norm_of_dof_vector" << std::endl;
   }
References oomph::Problem_Parameter::Trace_file.
mesh_pt() [1/5]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > RectangularQuadMesh<PERTURBED_ELEMENT>* PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::mesh_pt () inline
Access function for the specific mesh.
   {
    return dynamic_cast<RectangularQuadMesh<PERTURBED_ELEMENT>*>
     (Problem::mesh_pt());
   }
Referenced by PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::PerturbedStateProblem().
mesh_pt() [2/5]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > RefineableRectangularQuadMesh<PERTURBED_ELEMENT>* PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::mesh_pt () inline
Access function for the specific mesh.
   {
    return dynamic_cast<RefineableRectangularQuadMesh<PERTURBED_ELEMENT>*>
     (Problem::mesh_pt());
   }
mesh_pt() [3/5]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > RectangularQuadMesh<PERTURBED_ELEMENT>* PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::mesh_pt () inline
Access function for the specific mesh.
   {
    return dynamic_cast<RectangularQuadMesh<PERTURBED_ELEMENT>*>
     (Problem::mesh_pt());
   }
mesh_pt() [4/5]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > RefineableRectangularQuadMesh<PERTURBED_ELEMENT>* PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::mesh_pt () inline
Access function for the specific mesh.
   {
    return dynamic_cast<RefineableRectangularQuadMesh<PERTURBED_ELEMENT>*>
     (Problem::mesh_pt());
   }
mesh_pt() [5/5]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > RectangularQuadMesh<PERTURBED_ELEMENT>* PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::mesh_pt () inline
Access function for the specific mesh.
   {
    return dynamic_cast<RectangularQuadMesh<PERTURBED_ELEMENT>*>
     (Problem::mesh_pt());
   }
pass_updated_nondim_parameters_to_elements() [1/2]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::pass_updated_nondim_parameters_to_elements () inline
   {
    // Determine number of elements in mesh
    const unsigned n_element = this->mesh_pt()->nelement();
    // Loop over the elements
    for(unsigned e=0;e<n_element;e++)
     {
      // Upcast from GeneralisedElement to the present element
      PERTURBED_ELEMENT* el_pt
       = dynamic_cast<PERTURBED_ELEMENT*>(mesh_pt()->element_pt(e));
      // Set the Reynolds number
      el_pt->re_pt() = &GlobalPhysicalVariables::Re_current;
      // Set the Womersley number
      el_pt->re_st_pt() = &GlobalPhysicalVariables::ReSt_current;
     }
   }
References e(), GlobalPhysicalVariables::Re_current, and GlobalPhysicalVariables::ReSt_current.
pass_updated_nondim_parameters_to_elements() [2/2]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::pass_updated_nondim_parameters_to_elements () inline
   {
    // Determine number of elements in mesh
    const unsigned n_element = this->mesh_pt()->nelement();
    // Loop over the elements
    for(unsigned e=0;e<n_element;e++)
     {
      // Upcast from GeneralisedElement to the present element
      PERTURBED_ELEMENT* el_pt
       = dynamic_cast<PERTURBED_ELEMENT*>(mesh_pt()->element_pt(e));
      // Set the Reynolds number
      el_pt->re_pt() = &GlobalPhysicalVariables::Re_current;
      // Set the Womersley number
      el_pt->re_st_pt() = &GlobalPhysicalVariables::ReSt_current;
     }
   }
References e(), GlobalPhysicalVariables::Re_current, and GlobalPhysicalVariables::ReSt_current.
set_boundary_conditions() [1/6]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT , class TIMESTEPPER > void PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT, TIMESTEPPER >::set_boundary_conditions
Set up the (homogeneous) boundary conditions.
Set the (homogeneous) boundary conditions for the perturbed state.
 {
  // Determine number of mesh boundaries
  const unsigned n_boundary = mesh_pt()->nboundary();
  // Loop over mesh boundaries
  for(unsigned b=0;b<n_boundary;b++)
   {
    // Determine number of nodes on boundary b
    const unsigned n_node = mesh_pt()->nboundary_node(b);
    // Loop over nodes on boundary b
    for(unsigned n=0;n<n_node;n++)
     {
      // Set up pointer to node
      Node* nod_pt = mesh_pt()->boundary_node_pt(b,n);
      // For the solid boundaries set all components to zero
      if(b!=3)
       {
        nod_pt->set_value(0,0,0.0); // Radial
        nod_pt->set_value(0,1,0.0); // Radial
        nod_pt->set_value(0,2,0.0); // Axial
        nod_pt->set_value(0,3,0.0); // Axial
        nod_pt->set_value(0,4,0.0); // Azimuthal
        nod_pt->set_value(0,5,0.0); // Azimuthal
       }
      // On symmetry boundary, set only radial and azimuthal components to
      // zero, unless we are looking at the k=1 azimuthal mode. In this
      // case, do not set the value of any of the velocity components
      else
       {
        if(GlobalPhysicalVariables::k!=1)
         {
          nod_pt->set_value(0,0,0.0); // Radial
          nod_pt->set_value(0,1,0.0); // Radial
          nod_pt->set_value(0,4,0.0); // Azimuthal
          nod_pt->set_value(0,5,0.0); // Azimuthal
         }
       }
     } // End of loop over nodes on boundary b
   } // End of loop over mesh boundaries
 } // End of set_boundary_conditions for perturbed state
References b, GlobalPhysicalVariables::k, n, and oomph::Data::set_value().
set_boundary_conditions() [2/6]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::set_boundary_conditions ()
Set up the (homogeneous) boundary conditions.
set_boundary_conditions() [3/6]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::set_boundary_conditions ()
Set up the (homogeneous) boundary conditions.
set_boundary_conditions() [4/6]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::set_boundary_conditions ()
Set up the (homogeneous) boundary conditions.
set_boundary_conditions() [5/6]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::set_boundary_conditions ()
Set up the (homogeneous) boundary conditions.
set_boundary_conditions() [6/6]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::set_boundary_conditions ()
Set up the (homogeneous) boundary conditions.
set_initial_condition() [1/6]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT , class TIMESTEPPER > void PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT, TIMESTEPPER >::set_initial_condition virtual
Set the initial conditions to a "Poiseuille-style" profile.
Perturb the interface.
Set the three velocity components to a smoothly varying, non-zero profile
Set the three velocity components to a smoothly-varying, non-zero profile
Reimplemented from oomph::Problem.
 {
  // Determine number of nodes in mesh
  const unsigned n_node = mesh_pt()->nnode();
  // Loop over all nodes in mesh
  for(unsigned n=0;n<n_node;n++)
   {
    // Loop over the six velocity components
    for(unsigned i=0;i<6;i++)
     {
      // Get x and y position of node
      const double x = mesh_pt()->node_pt(n)->x(0);
      const double y = mesh_pt()->node_pt(n)->x(1);
      // Assign "Poiseuille-style" initial conditions
      const double value = 4.0*x*(x-1.0)*y*(y-Domain_height);
      mesh_pt()->node_pt(n)->set_value(i,value);
     }
   } // End of loop over nodes in mesh
  // Note that we do not need to set any history values as we are
  // using a self-starting timestepper (BDF<1>)
  // Set the boundary conditions
  set_boundary_conditions();
 } // End of set_initial_condition for perturbed state
References i, n, Eigen::value, plotDoE::x, and y.
set_initial_condition() [2/6]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::set_initial_condition () virtual
Set the three velocity components to a smoothly varying, non-zero profile
Reimplemented from oomph::Problem.
set_initial_condition() [3/6]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::set_initial_condition () virtual
Set initial conditions to a "Poiseuille-style" profile.
Reimplemented from oomph::Problem.
set_initial_condition() [4/6]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::set_initial_condition () virtual
Set initial conditions to a "Poiseuille-style" profile.
Reimplemented from oomph::Problem.
set_initial_condition() [5/6]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::set_initial_condition () virtual
Set initial conditions to a "Poiseuille-style" profile.
Reimplemented from oomph::Problem.
set_initial_condition() [6/6]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::set_initial_condition () virtual
Set initial conditions (velocities given random values in range [0,1])
Reimplemented from oomph::Problem.
surface_mesh_pt()
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > Mesh* PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::surface_mesh_pt () inline
Access function for surface mesh.
   {
    return Surface_mesh_pt;
   }
time_stepper_pt() [1/4]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > SelfStartingBDF2* PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::time_stepper_pt () inline
Access function for the specific timestepper.
   {
    return dynamic_cast<SelfStartingBDF2*>(Problem::time_stepper_pt());
   }
Referenced by PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::PerturbedStateProblem().
time_stepper_pt() [2/4]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > SelfStartingBDF2* PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::time_stepper_pt () inline
Access function for the specific timestepper.
   {
    return dynamic_cast<SelfStartingBDF2*>(Problem::time_stepper_pt());
   }
time_stepper_pt() [3/4]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > SelfStartingBDF2* PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::time_stepper_pt () inline
Access function for the specific timestepper.
   {
    return dynamic_cast<SelfStartingBDF2*>(Problem::time_stepper_pt());
   }
time_stepper_pt() [4/4]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > TIMESTEPPER* PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::time_stepper_pt () inline
Access function for the specific timestepper.
   {
    return dynamic_cast<TIMESTEPPER*>(Problem::time_stepper_pt());
   }
trace_file() [1/4]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > ofstream& PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::trace_file () inline
Access function for trace file.
 { return Trace_file; }
References oomph::Problem_Parameter::Trace_file.
trace_file() [2/4]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > ofstream& PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::trace_file () inline
Access function for trace file.
 { return Trace_file; }
References oomph::Problem_Parameter::Trace_file.
trace_file() [3/4]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > ofstream& PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::trace_file () inline
Access function for trace file.
 { return Trace_file; }
References oomph::Problem_Parameter::Trace_file.
trace_file() [4/4]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > ofstream& PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::trace_file () inline
Access function for trace file.
 { return Trace_file; }
References oomph::Problem_Parameter::Trace_file.
Member Data Documentation
Azimuthal_mode_number
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > int PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Azimuthal_mode_number private
Azimuthal mode number.
Referenced by PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::PerturbedStateProblem().
Base_state_bulk_mesh_pt
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > SpineMesh* PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Base_state_bulk_mesh_pt private
Pointer to the base state mesh.
Referenced by PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::PerturbedStateProblem().
Base_state_mesh_pt
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > Mesh * PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Base_state_mesh_pt private
Pointer to the base state mesh.
Referenced by PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::PerturbedStateProblem().
Bulk_mesh_pt
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > TwoLayerPerturbedSpineMesh<PERTURBED_ELEMENT>* PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Bulk_mesh_pt private
Pointer to the (specific) "bulk" mesh.
Referenced by PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::PerturbedStateProblem().
Domain_height
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > double PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Domain_height private
Height of domain.
Inner_cylinder_radius
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > double PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Inner_cylinder_radius private
Inner and outer cylinder radii.
Outer_cylinder_radius
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > double PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Outer_cylinder_radius private
Surface_mesh_pt
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > Mesh* PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Surface_mesh_pt private
Pointer to the "surface" mesh.
Referenced by PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::PerturbedStateProblem().
Trace_file
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > ofstream PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Trace_file private
Trace file.
U_nodal_index
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > Vector<unsigned> PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::U_nodal_index private
Index at which the i-th velocity component is stored.
Referenced by PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::PerturbedStateProblem().
Xhat_nodal_index
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > Vector<unsigned> PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Xhat_nodal_index private
Index at which the i-th component of the perturbation to the nodal coordinate is stored.
Referenced by PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::PerturbedStateProblem().
The documentation for this class was generated from the following files:
axisym_navier_stokes/counter_rotating_disks/counter_rotating_disks.cc
axisym_navier_stokes/counter_rotating_disks/counter_rotating_disks_ref.cc
time_periodic_taylor_couette.cc
two_layer_interface_nonaxisym_perturbations.cc