MercuryDPM: denseLM.cpp File Reference
denseLM.cpp File Reference
#include <iostream>
#include <fstream>
#include <iomanip>
#include "main.h"
#include <Eigen/LevenbergMarquardt>
Classes
struct DenseLM< Scalar >
Functions
template<typename FunctorType , typename VectorType >
int test_minimizeLM (FunctorType &functor, VectorType &uv)
template<typename FunctorType , typename VectorType >
int test_lmder (FunctorType &functor, VectorType &uv)
template<typename FunctorType , typename VectorType >
int test_minimizeSteps (FunctorType &functor, VectorType &uv)
template<typename T >
void test_denseLM_T ()
EIGEN_DECLARE_TEST (denseLM)
Function Documentation
EIGEN_DECLARE_TEST()
EIGEN_DECLARE_TEST (denseLM)
{
   CALL_SUBTEST_2(test_denseLM_T<double>());
   // CALL_SUBTEST_2(test_sparseLM_T<std::complex<double>());
 }
References CALL_SUBTEST_2.
test_denseLM_T()
template<typename T > void test_denseLM_T ()
                       {
   typedef Matrix<T, Dynamic, 1> VectorType;
   int inputs = 10;
   int values = 1000;
   DenseLM<T> dense_gaussian(inputs, values);
   VectorType uv(inputs), uv_ref(inputs);
   VectorType x(values);
   // Generate the reference solution
   uv_ref << -2, 1, 4, 8, 6, 1.8, 1.2, 1.1, 1.9, 3;
   // Generate the reference data points
   x.setRandom();
   x = 10 * x;
   x.array() += 10;
   dense_gaussian.initPoints(uv_ref, x);
   // Generate the initial parameters
   VectorBlock<VectorType> u(uv, 0, inputs / 2);
   VectorBlock<VectorType> v(uv, inputs / 2, inputs / 2);
   // Solve the optimization problem
   // Solve in one go
   u.setOnes();
   v.setOnes();
   test_minimizeLM(dense_gaussian, uv);
   // Solve until the machine precision
   u.setOnes();
   v.setOnes();
   test_lmder(dense_gaussian, uv);
   // Solve step by step
   v.setOnes();
   u.setOnes();
   test_minimizeSteps(dense_gaussian, uv);
 }
References DenseLM< Scalar >::initPoints(), test_lmder(), test_minimizeLM(), test_minimizeSteps(), v, and plotDoE::x.
test_lmder()
template<typename FunctorType , typename VectorType > int test_lmder (FunctorType & functor, VectorType & uv)
{
   typedef typename VectorType::Scalar Scalar;
   LevenbergMarquardtSpace::Status info;
   LevenbergMarquardt<FunctorType> lm(functor);
   info = lm.lmder1(uv);
   VERIFY_IS_EQUAL(info, 1);
   // FIXME Check other parameters
   return info;
 }
References info, Eigen::LevenbergMarquardt< FunctorType_ >::lmder1(), and VERIFY_IS_EQUAL.
Referenced by test_denseLM_T().
test_minimizeLM()
template<typename FunctorType , typename VectorType > int test_minimizeLM (FunctorType & functor, VectorType & uv)
{
   LevenbergMarquardt<FunctorType> lm(functor);
   LevenbergMarquardtSpace::Status info;
   info = lm.minimize(uv);
   VERIFY_IS_EQUAL(info, 1);
   // FIXME Check other parameters
   return info;
 }
References info, Eigen::LevenbergMarquardt< FunctorType_ >::minimize(), and VERIFY_IS_EQUAL.
Referenced by test_denseLM_T().
test_minimizeSteps()
template<typename FunctorType , typename VectorType > int test_minimizeSteps (FunctorType & functor, VectorType & uv)
{
   LevenbergMarquardtSpace::Status info;
   LevenbergMarquardt<FunctorType> lm(functor);
   info = lm.minimizeInit(uv);
   if (info == LevenbergMarquardtSpace::ImproperInputParameters) return info;
   do {
     info = lm.minimizeOneStep(uv);
   } while (info == LevenbergMarquardtSpace::Running);
   VERIFY_IS_EQUAL(info, 1);
   // FIXME Check other parameters
   return info;
 }
References Eigen::LevenbergMarquardtSpace::ImproperInputParameters, info, Eigen::LevenbergMarquardt< FunctorType_ >::minimizeInit(), Eigen::LevenbergMarquardt< FunctorType_ >::minimizeOneStep(), Eigen::LevenbergMarquardtSpace::Running, and VERIFY_IS_EQUAL.
Referenced by test_denseLM_T().