MercuryDPM: oomph::RefineablePoissonEquations< DIM > Class Template Reference
oomph::RefineablePoissonEquations< DIM > Class Template Reference
#include <refineable_poisson_elements.h>
Public Member Functions
RefineablePoissonEquations ()
Constructor, simply call other constructors.
RefineablePoissonEquations (const RefineablePoissonEquations< DIM > &dummy)=delete
Broken copy constructor.
void operator= (const RefineablePoissonEquations< DIM > &)=delete
Broken assignment operator.
unsigned num_Z2_flux_terms ()
Number of 'flux' terms for Z2 error estimation.
void get_Z2_flux (const Vector< double > &s, Vector< double > &flux)
Get 'flux' for Z2 error recovery: Standard flux.from Poisson equations.
void compute_exact_Z2_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_flux_pt, double &error, double &norm)
Get error against and norm of exact flux.
void get_interpolated_values (const Vector< double > &s, Vector< double > &values)
void get_interpolated_values (const unsigned &t, const Vector< double > &s, Vector< double > &values)
void further_build ()
Further build: Copy source function pointer from father element.
Public Member Functions inherited from oomph::PoissonEquations< DIM >
PoissonEquations ()
Constructor (must initialise the Source_fct_pt to null)
PoissonEquations (const PoissonEquations &dummy)=delete
Broken copy constructor.
void operator= (const PoissonEquations &)=delete
Broken assignment operator.
virtual unsigned u_index_poisson () const
void point_output_data (const Vector< double > &s, Vector< double > &data)
unsigned nscalar_paraview () const
void scalar_value_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot) const
std::string scalar_name_paraview (const unsigned &i) const
void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
void output (std::ostream &outfile)
Output with default number of plot points.
void output (std::ostream &outfile, const unsigned &n_plot)
void output (FILE *file_pt)
C_style output with default number of plot points.
void output (FILE *file_pt, const unsigned &n_plot)
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
void compute_norm (double &norm)
Compute norm of solution: square of the L2 norm.
void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Get error against and norm of exact solution.
void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Dummy, time dependent error checker.
PoissonSourceFctPt & source_fct_pt ()
Access function: Pointer to source function.
PoissonSourceFctPt source_fct_pt () const
Access function: Pointer to source function. Const version.
PoissonSourceFctGradientPt & source_fct_gradient_pt ()
Access function: Pointer to gradient of source function.
PoissonSourceFctGradientPt source_fct_gradient_pt () const
Access function: Pointer to gradient source function. Const version.
virtual void get_source_poisson (const unsigned &ipt, const Vector< double > &x, double &source) const
virtual void get_source_gradient_poisson (const unsigned &ipt, const Vector< double > &x, Vector< double > &gradient) const
void get_flux (const Vector< double > &s, Vector< double > &flux) const
Get flux: flux[i] = du/dx_i.
void get_dflux_dnodal_u (const Vector< double > &s, Vector< Vector< double >> &dflux_dnodal_u) const
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Add the element's contribution to its residual vector (wrapper)
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
virtual double interpolated_u_poisson (const Vector< double > &s) const
unsigned self_test ()
Self-test: Return 0 for OK.
Public Member Functions inherited from oomph::FiniteElement
void set_dimension (const unsigned &dim)
void set_nodal_dimension (const unsigned &nodal_dim)
void set_nnodal_position_type (const unsigned &nposition_type)
Set the number of types required to interpolate the coordinate.
void set_n_node (const unsigned &n)
int nodal_local_eqn (const unsigned &n, const unsigned &i) const
double dJ_eulerian_at_knot (const unsigned &ipt, Shape &psi, DenseMatrix< double > &djacobian_dX) const
FiniteElement ()
Constructor.
virtual ~FiniteElement ()
FiniteElement (const FiniteElement &)=delete
Broken copy constructor.
virtual bool local_coord_is_valid (const Vector< double > &s)
Broken assignment operator.
virtual void move_local_coord_back_into_element (Vector< double > &s) const
void get_centre_of_gravity_and_max_radius_in_terms_of_zeta (Vector< double > &cog, double &max_radius) const
virtual void local_coordinate_of_node (const unsigned &j, Vector< double > &s) const
virtual void local_fraction_of_node (const unsigned &j, Vector< double > &s_fraction)
virtual double local_one_d_fraction_of_node (const unsigned &n1d, const unsigned &i)
virtual void set_macro_elem_pt (MacroElement *macro_elem_pt)
MacroElement * macro_elem_pt ()
Access function to pointer to macro element.
void get_x (const Vector< double > &s, Vector< double > &x) const
void get_x (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void get_x_from_macro_element (const Vector< double > &s, Vector< double > &x) const
virtual void get_x_from_macro_element (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void set_integration_scheme (Integral *const &integral_pt)
Set the spatial integration scheme.
Integral *const & integral_pt () const
Return the pointer to the integration scheme (const version)
virtual void shape (const Vector< double > &s, Shape &psi) const =0
virtual void shape_at_knot (const unsigned &ipt, Shape &psi) const
virtual void dshape_local (const Vector< double > &s, Shape &psi, DShape &dpsids) const
virtual void dshape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids) const
virtual void d2shape_local (const Vector< double > &s, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual void d2shape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual double J_eulerian (const Vector< double > &s) const
virtual double J_eulerian_at_knot (const unsigned &ipt) const
void check_J_eulerian_at_knots (bool &passed) const
void check_jacobian (const double &jacobian) const
double dshape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsi, DenseMatrix< double > &djacobian_dX, RankFourTensor< double > &d_dpsidx_dX) const
double d2shape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual double d2shape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual void describe_local_dofs (std::ostream &out, const std::string &current_string) const
virtual void describe_nodal_local_dofs (std::ostream &out, const std::string &current_string) const
virtual void assign_all_generic_local_eqn_numbers (const bool &store_local_dof_pt)
Node *& node_pt (const unsigned &n)
Return a pointer to the local node n.
Node *const & node_pt (const unsigned &n) const
Return a pointer to the local node n (const version)
unsigned nnode () const
Return the number of nodes.
virtual unsigned nnode_1d () const
double raw_nodal_position (const unsigned &n, const unsigned &i) const
double raw_nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position (const unsigned &n, const unsigned &i) const
double nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double dnodal_position_dt (const unsigned &n, const unsigned &i) const
Return the i-th component of nodal velocity: dx/dt at local node n.
double dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
virtual void disable_ALE ()
virtual void enable_ALE ()
virtual unsigned required_nvalue (const unsigned &n) const
unsigned nnodal_position_type () const
bool has_hanging_nodes () const
unsigned nodal_dimension () const
Return the required Eulerian dimension of the nodes in this element.
virtual Node * construct_node (const unsigned &n)
virtual Node * construct_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
virtual Node * construct_boundary_node (const unsigned &n)
virtual Node * construct_boundary_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
int get_node_number (Node *const &node_pt) const
virtual Node * get_node_at_local_coordinate (const Vector< double > &s) const
double raw_nodal_value (const unsigned &n, const unsigned &i) const
double raw_nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
unsigned dim () const
virtual ElementGeometry::ElementGeometry element_geometry () const
Return the geometry type of the element (either Q or T usually).
virtual double interpolated_x (const Vector< double > &s, const unsigned &i) const
Return FE interpolated coordinate x[i] at local coordinate s.
virtual double interpolated_x (const unsigned &t, const Vector< double > &s, const unsigned &i) const
virtual void interpolated_x (const Vector< double > &s, Vector< double > &x) const
Return FE interpolated position x[] at local coordinate s as Vector.
virtual void interpolated_x (const unsigned &t, const Vector< double > &s, Vector< double > &x) const
virtual double interpolated_dxdt (const Vector< double > &s, const unsigned &i, const unsigned &t)
virtual void interpolated_dxdt (const Vector< double > &s, const unsigned &t, Vector< double > &dxdt)
unsigned ngeom_data () const
Data * geom_data_pt (const unsigned &j)
void position (const Vector< double > &zeta, Vector< double > &r) const
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
void dposition_dt (const Vector< double > &zeta, const unsigned &t, Vector< double > &drdt)
virtual double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
void interpolated_zeta (const Vector< double > &s, Vector< double > &zeta) const
void locate_zeta (const Vector< double > &zeta, GeomObject *&geom_object_pt, Vector< double > &s, const bool &use_coordinate_as_initial_guess=false)
virtual void node_update ()
virtual void identify_geometric_data (std::set< Data * > &geometric_data_pt)
virtual double s_min () const
Min value of local coordinate.
virtual double s_max () const
Max. value of local coordinate.
double size () const
virtual double compute_physical_size () const
void point_output (std::ostream &outfile, const Vector< double > &s)
virtual unsigned nplot_points_paraview (const unsigned &nplot) const
virtual unsigned nsub_elements_paraview (const unsigned &nplot) const
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_output_offset_information (std::ofstream &file_out, const unsigned &nplot, unsigned &counter) const
virtual void write_paraview_type (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_offsets (std::ofstream &file_out, const unsigned &nplot, unsigned &offset_sum) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
virtual void output (const unsigned &t, std::ostream &outfile, const unsigned &n_plot) const
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, const SolutionFunctorBase &exact_soln) const
Output a time-dependent exact solution over the element.
virtual void get_s_plot (const unsigned &i, const unsigned &nplot, Vector< double > &s, const bool &shifted_to_interior=false) const
virtual std::string tecplot_zone_string (const unsigned &nplot) const
virtual void write_tecplot_zone_footer (std::ostream &outfile, const unsigned &nplot) const
virtual void write_tecplot_zone_footer (FILE *file_pt, const unsigned &nplot) const
virtual unsigned nplot_points (const unsigned &nplot) const
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_abs_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error)
void integrate_fct (FiniteElement::SteadyExactSolutionFctPt integrand_fct_pt, Vector< double > &integral)
Integrate Vector-valued function over element.
void integrate_fct (FiniteElement::UnsteadyExactSolutionFctPt integrand_fct_pt, const double &time, Vector< double > &integral)
Integrate Vector-valued time-dep function over element.
virtual void build_face_element (const int &face_index, FaceElement *face_element_pt)
virtual unsigned get_bulk_node_number (const int &face_index, const unsigned &i) const
virtual int face_outer_unit_normal_sign (const int &face_index) const
Get the sign of the outer unit normal on the face given by face_index.
virtual unsigned nnode_on_face () const
void face_node_number_error_check (const unsigned &i) const
Range check for face node numbers.
virtual CoordinateMappingFctPt face_to_bulk_coordinate_fct_pt (const int &face_index) const
virtual BulkCoordinateDerivativesFctPt bulk_coordinate_derivatives_fct_pt (const int &face_index) const
Public Member Functions inherited from oomph::GeneralisedElement
GeneralisedElement ()
Constructor: Initialise all pointers and all values to zero.
virtual ~GeneralisedElement ()
Virtual destructor to clean up any memory allocated by the object.
GeneralisedElement (const GeneralisedElement &)=delete
Broken copy constructor.
void operator= (const GeneralisedElement &)=delete
Broken assignment operator.
Data *& internal_data_pt (const unsigned &i)
Return a pointer to i-th internal data object.
Data *const & internal_data_pt (const unsigned &i) const
Return a pointer to i-th internal data object (const version)
Data *& external_data_pt (const unsigned &i)
Return a pointer to i-th external data object.
Data *const & external_data_pt (const unsigned &i) const
Return a pointer to i-th external data object (const version)
unsigned long eqn_number (const unsigned &ieqn_local) const
int local_eqn_number (const unsigned long &ieqn_global) const
unsigned add_external_data (Data *const &data_pt, const bool &fd=true)
bool external_data_fd (const unsigned &i) const
void exclude_external_data_fd (const unsigned &i)
void include_external_data_fd (const unsigned &i)
void flush_external_data ()
Flush all external data.
void flush_external_data (Data *const &data_pt)
Flush the object addressed by data_pt from the external data array.
unsigned ninternal_data () const
Return the number of internal data objects.
unsigned nexternal_data () const
Return the number of external data objects.
unsigned ndof () const
Return the number of equations/dofs in the element.
void dof_vector (const unsigned &t, Vector< double > &dof)
Return the vector of dof values at time level t.
void dof_pt_vector (Vector< double * > &dof_pt)
Return the vector of pointers to dof values.
void set_internal_data_time_stepper (const unsigned &i, TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void assign_internal_eqn_numbers (unsigned long &global_number, Vector< double * > &Dof_pt)
void describe_dofs (std::ostream &out, const std::string &current_string) const
void add_internal_value_pt_to_map (std::map< unsigned, double * > &map_of_value_pt)
virtual void assign_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void complete_setup_of_dependencies ()
virtual void get_residuals (Vector< double > &residuals)
virtual void get_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
virtual void get_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void get_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void get_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void get_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void get_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void get_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void get_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void get_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
virtual void compute_norm (Vector< double > &norm)
virtual unsigned ndof_types () const
virtual void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned >> &dof_lookup_list) const
Public Member Functions inherited from oomph::GeomObject
GeomObject ()
Default constructor.
GeomObject (const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim, TimeStepper *time_stepper_pt)
GeomObject (const GeomObject &dummy)=delete
Broken copy constructor.
void operator= (const GeomObject &)=delete
Broken assignment operator.
virtual ~GeomObject ()
(Empty) destructor
unsigned nlagrangian () const
Access function to # of Lagrangian coordinates.
unsigned ndim () const
Access function to # of Eulerian coordinates.
void set_nlagrangian_and_ndim (const unsigned &n_lagrangian, const unsigned &n_dim)
Set # of Lagrangian and Eulerian coordinates.
TimeStepper *& time_stepper_pt ()
TimeStepper * time_stepper_pt () const
virtual void position (const double &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void dposition (const Vector< double > &zeta, DenseMatrix< double > &drdzeta) const
virtual void d2position (const Vector< double > &zeta, RankThreeTensor< double > &ddrdzeta) const
virtual void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
Public Member Functions inherited from oomph::RefineableElement
RefineableElement ()
virtual ~RefineableElement ()
Destructor, delete the allocated storage for the hanging equations.
RefineableElement (const RefineableElement &)=delete
Broken copy constructor.
void operator= (const RefineableElement &)=delete
Broken assignment operator.
Tree * tree_pt ()
Access function: Pointer to quadtree representation of this element.
void set_tree_pt (Tree *my_tree_pt)
Set pointer to quadtree representation of this element.
virtual unsigned required_nsons () const
bool refinement_is_enabled ()
Flag to indicate suppression of any refinement.
void disable_refinement ()
Suppress of any refinement for this element.
void enable_refinement ()
Emnable refinement for this element.
template<class ELEMENT >
void split (Vector< ELEMENT * > &son_pt) const
int local_hang_eqn (Node *const &node_pt, const unsigned &i)
virtual void build (Mesh *&mesh_pt, Vector< Node * > &new_node_pt, bool &was_already_built, std::ofstream &new_nodes_file)=0
void set_refinement_level (const int &refine_level)
Set the refinement level.
unsigned refinement_level () const
Return the Refinement level.
void select_for_refinement ()
Select the element for refinement.
void deselect_for_refinement ()
Deselect the element for refinement.
void select_sons_for_unrefinement ()
Unrefinement will be performed by merging the four sons of this element.
void deselect_sons_for_unrefinement ()
bool to_be_refined ()
Has the element been selected for refinement?
bool sons_to_be_unrefined ()
Has the element been selected for unrefinement?
virtual void rebuild_from_sons (Mesh *&mesh_pt)=0
virtual void unbuild ()
virtual void deactivate_element ()
virtual bool nodes_built ()
Return true if all the nodes have been built, false if not.
long number () const
Element number (for debugging/plotting)
void set_number (const long &mynumber)
Set element number (for debugging/plotting)
virtual unsigned ncont_interpolated_values () const =0
virtual Node * interpolating_node_pt (const unsigned &n, const int &value_id)
virtual double local_one_d_fraction_of_interpolating_node (const unsigned &n1d, const unsigned &i, const int &value_id)
virtual Node * get_interpolating_node_at_local_coordinate (const Vector< double > &s, const int &value_id)
virtual unsigned ninterpolating_node (const int &value_id)
virtual unsigned ninterpolating_node_1d (const int &value_id)
virtual void interpolating_basis (const Vector< double > &s, Shape &psi, const int &value_id) const
virtual void check_integrity (double &max_error)=0
void identify_field_data_for_interactions (std::set< std::pair< Data *, unsigned >> &paired_field_data)
void assign_nodal_local_eqn_numbers (const bool &store_local_dof_pt)
virtual RefineableElement * root_element_pt ()
virtual RefineableElement * father_element_pt () const
Return a pointer to the father element.
void get_father_at_refinement_level (unsigned &refinement_level, RefineableElement *&father_at_reflevel_pt)
virtual void initial_setup (Tree *const &adopted_father_pt=0, const unsigned &initial_p_order=0)
virtual void pre_build (Mesh *&mesh_pt, Vector< Node * > &new_node_pt)
Pre-build the element.
virtual void setup_hanging_nodes (Vector< std::ofstream * > &output_stream)
virtual void further_setup_hanging_nodes ()
unsigned nshape_controlling_nodes ()
std::map< Node *, unsigned > shape_controlling_node_lookup ()
Public Member Functions inherited from oomph::ElementWithZ2ErrorEstimator
ElementWithZ2ErrorEstimator ()
Default empty constructor.
ElementWithZ2ErrorEstimator (const ElementWithZ2ErrorEstimator &)=delete
Broken copy constructor.
void operator= (const ElementWithZ2ErrorEstimator &)=delete
Broken assignment operator.
virtual unsigned ncompound_fluxes ()
virtual void get_Z2_compound_flux_indices (Vector< unsigned > &flux_index)
virtual unsigned nvertex_node () const =0
Number of vertex nodes in the element.
virtual Node * vertex_node_pt (const unsigned &j) const =0
virtual unsigned nrecovery_order ()=0
Order of recovery shape functions.
virtual double geometric_jacobian (const Vector< double > &x)
Private Member Functions
void fill_in_generic_residual_contribution_poisson (Vector< double > &residuals, DenseMatrix< double > &jacobian, const unsigned &flag)
virtual void get_dresidual_dnodal_coordinates (RankThreeTensor< double > &dresidual_dnodal_coordinates)
Additional Inherited Members
Public Types inherited from oomph::PoissonEquations< DIM >
typedef void(* PoissonSourceFctPt) (const Vector< double > &x, double &f)
typedef void(* PoissonSourceFctGradientPt) (const Vector< double > &x, Vector< double > &gradient)
Public Types inherited from oomph::FiniteElement
typedef void(* SteadyExactSolutionFctPt) (const Vector< double > &, Vector< double > &)
typedef void(* UnsteadyExactSolutionFctPt) (const double &, const Vector< double > &, Vector< double > &)
Static Public Member Functions inherited from oomph::RefineableElement
static double & max_integrity_tolerance ()
Max. allowed discrepancy in element integrity check.
Static Public Attributes inherited from oomph::FiniteElement
static double Tolerance_for_singular_jacobian = 1.0e-16
Tolerance below which the jacobian is considered singular.
static bool Accept_negative_jacobian = false
static bool Suppress_output_while_checking_for_inverted_elements
Static Public Attributes inherited from oomph::GeneralisedElement
static bool Suppress_warning_about_repeated_internal_data
static bool Suppress_warning_about_repeated_external_data = true
static double Default_fd_jacobian_step = 1.0e-8
Protected Member Functions inherited from oomph::PoissonEquations< DIM >
virtual double dshape_and_dtest_eulerian_poisson (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const =0
virtual double dshape_and_dtest_eulerian_at_knot_poisson (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const =0
virtual double dshape_and_dtest_eulerian_at_knot_poisson (const unsigned &ipt, Shape &psi, DShape &dpsidx, RankFourTensor< double > &d_dpsidx_dX, Shape &test, DShape &dtestdx, RankFourTensor< double > &d_dtestdx_dX, DenseMatrix< double > &djacobian_dX) const =0
Protected Member Functions inherited from oomph::FiniteElement
template<unsigned DIM>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double invert_jacobian_mapping (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &inverse_jacobian) const
virtual void dJ_eulerian_dnodal_coordinates (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<unsigned DIM>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
virtual void d_dshape_eulerian_dnodal_coordinates (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<unsigned DIM>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
virtual void transform_derivatives (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
void transform_derivatives_diagonal (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
virtual void transform_second_derivatives (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
void fill_in_jacobian_from_nodal_by_fd (DenseMatrix< double > &jacobian)
virtual void update_before_nodal_fd ()
virtual void reset_after_nodal_fd ()
virtual void update_in_nodal_fd (const unsigned &i)
virtual void reset_in_nodal_fd (const unsigned &i)
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Zero-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
One-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Two-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
Protected Member Functions inherited from oomph::GeneralisedElement
unsigned add_internal_data (Data *const &data_pt, const bool &fd=true)
bool internal_data_fd (const unsigned &i) const
void exclude_internal_data_fd (const unsigned &i)
void include_internal_data_fd (const unsigned &i)
void clear_global_eqn_numbers ()
void add_global_eqn_numbers (std::deque< unsigned long > const &global_eqn_numbers, std::deque< double * > const &global_dof_pt)
virtual void assign_internal_and_external_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void assign_additional_local_eqn_numbers ()
int internal_local_eqn (const unsigned &i, const unsigned &j) const
int external_local_eqn (const unsigned &i, const unsigned &j)
void fill_in_jacobian_from_internal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_internal_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
virtual void update_before_internal_fd ()
virtual void reset_after_internal_fd ()
virtual void update_in_internal_fd (const unsigned &i)
virtual void reset_in_internal_fd (const unsigned &i)
virtual void update_before_external_fd ()
virtual void reset_after_external_fd ()
virtual void update_in_external_fd (const unsigned &i)
virtual void reset_in_external_fd (const unsigned &i)
virtual void fill_in_contribution_to_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void fill_in_contribution_to_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void fill_in_contribution_to_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void fill_in_contribution_to_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void fill_in_contribution_to_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
Protected Member Functions inherited from oomph::RefineableElement
void assemble_local_to_eulerian_jacobian (const DShape &dpsids, DenseMatrix< double > &jacobian) const
void assemble_local_to_eulerian_jacobian2 (const DShape &d2psids, DenseMatrix< double > &jacobian2) const
void assemble_eulerian_base_vectors (const DShape &dpsids, DenseMatrix< double > &interpolated_G) const
double local_to_eulerian_mapping_diagonal (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
void assign_hanging_local_eqn_numbers (const bool &store_local_dof_pt)
Assign the local equation numbers for hanging node variables.
virtual void fill_in_jacobian_from_nodal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Static Protected Member Functions inherited from oomph::RefineableElement
static void check_value_id (const int &n_continuously_interpolated_values, const int &value_id)
Protected Attributes inherited from oomph::PoissonEquations< DIM >
PoissonSourceFctPt Source_fct_pt
Pointer to source function:
PoissonSourceFctGradientPt Source_fct_gradient_pt
Pointer to gradient of source function.
Protected Attributes inherited from oomph::FiniteElement
MacroElement * Macro_elem_pt
Pointer to the element's macro element (NULL by default)
Protected Attributes inherited from oomph::GeomObject
unsigned NLagrangian
Number of Lagrangian (intrinsic) coordinates.
unsigned Ndim
Number of Eulerian coordinates.
TimeStepper * Geom_object_time_stepper_pt
Protected Attributes inherited from oomph::RefineableElement
Tree * Tree_pt
A pointer to a general tree object.
unsigned Refine_level
Refinement level.
bool To_be_refined
Flag for refinement.
bool Refinement_is_enabled
Flag to indicate suppression of any refinement.
bool Sons_to_be_unrefined
Flag for unrefinement.
long Number
Global element number – for plotting/validation purposes.
Static Protected Attributes inherited from oomph::FiniteElement
static const unsigned Default_Initial_Nvalue = 0
Default value for the number of values at a node.
static const double Node_location_tolerance = 1.0e-14
static const unsigned N2deriv [] = {0, 1, 3, 6}
Static Protected Attributes inherited from oomph::GeneralisedElement
static DenseMatrix< double > Dummy_matrix
static std::deque< double * > Dof_pt_deque
Static Protected Attributes inherited from oomph::RefineableElement
static double Max_integrity_tolerance = 1.0e-8
Max. allowed discrepancy in element integrity check.
Detailed Description
template<unsigned DIM>
class oomph::RefineablePoissonEquations< DIM >
//////////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////////// Refineable version of Poisson equations
Constructor & Destructor Documentation
RefineablePoissonEquations() [1/2]
template<unsigned DIM> oomph::RefineablePoissonEquations< DIM >::RefineablePoissonEquations () inline
Constructor, simply call other constructors.
       : PoissonEquations<DIM>(),
         RefineableElement(),
         ElementWithZ2ErrorEstimator()
     {
     }
RefineablePoissonEquations() [2/2]
template<unsigned DIM> oomph::RefineablePoissonEquations< DIM >::RefineablePoissonEquations (const RefineablePoissonEquations< DIM > & dummy) delete
Broken copy constructor.
Member Function Documentation
compute_exact_Z2_error()
template<unsigned DIM> void oomph::RefineablePoissonEquations< DIM >::compute_exact_Z2_error (std::ostream & outfile, FiniteElement::SteadyExactSolutionFctPt exact_flux_pt, double & error, double & norm) virtual
Get error against and norm of exact flux.
Validate against exact flux. Flux is provided via function pointer. Plot error at a given number of plot points.
Reimplemented from oomph::ElementWithZ2ErrorEstimator.
   {
     // Initialise
     error = 0.0;
     norm = 0.0;
     // Vector of local coordinates
     Vector<double> s(DIM);
     // Vector of global coordinates
     Vector<double> x(DIM);
     // Find out how many nodes there are in the element
     const unsigned n_node = nnode();
     // Allocate storage for shape functions
     Shape psi(n_node);
     // Set the value of n_intpt
     const unsigned n_intpt = integral_pt()->nweight();
     // Tecplot
     outfile << "ZONE" << std::endl;
     // Exact flux Vector (size is DIM)
     Vector<double> exact_flux(DIM);
     // Loop over the integration points
     for (unsigned ipt = 0; ipt < n_intpt; ipt++)
     {
       // Assign values of s
       for (unsigned i = 0; i < DIM; i++)
       {
         s[i] = integral_pt()->knot(ipt, i);
       }
       // Get the integral weight
       double w = integral_pt()->weight(ipt);
       // Get jacobian of mapping
       double J = J_eulerian(s);
       // Premultiply the weights and the Jacobian
       double W = w * J;
       // Get x position as Vector
       interpolated_x(s, x);
       // Allocate storage for FE flux Vector
       Vector<double> fe_flux(DIM);
       // Get FE flux as Vector
       get_Z2_flux(s, fe_flux);
       // Get exact flux at this point
       (*exact_flux_pt)(x, exact_flux);
       // Output x,y,...
       for (unsigned i = 0; i < DIM; i++)
       {
         outfile << x[i] << " ";
       }
       // Output exact flux
       for (unsigned i = 0; i < DIM; i++)
       {
         outfile << exact_flux[i] << " ";
       }
       // Output error
       for (unsigned i = 0; i < DIM; i++)
       {
         outfile << exact_flux[i] - fe_flux[i] << " ";
       }
       outfile << std::endl;
       // Add to RMS error:
       double sum = 0.0;
       double sum2 = 0.0;
       for (unsigned i = 0; i < DIM; i++)
       {
         sum += (fe_flux[i] - exact_flux[i]) * (fe_flux[i] - exact_flux[i]);
         sum2 += exact_flux[i] * exact_flux[i];
       }
       error += sum * W;
       norm += sum2 * W;
     } // End of loop over the integration points
   }
References DIM, calibrate::error, get_Z2_flux(), i, J, s, w, oomph::QuadTreeNames::W, and plotDoE::x.
fill_in_generic_residual_contribution_poisson()
template<unsigned DIM> void oomph::RefineablePoissonEquations< DIM >::fill_in_generic_residual_contribution_poisson (Vector< double > & residuals, DenseMatrix< double > & jacobian, const unsigned & flag) private virtual
Add element's contribution to elemental residual vector and/or Jacobian matrix flag=1: compute both flag=0: compute only residual vector
Add element's contribution to the elemental residual vector and/or Jacobian matrix. flag=1: compute both flag=0: compute only residual vector
Reimplemented from oomph::PoissonEquations< DIM >.
   {
     // Find out how many nodes there are in the element
     unsigned n_node = nnode();
     // Set up memory for the shape and test functions
     Shape psi(n_node), test(n_node);
     DShape dpsidx(n_node, DIM), dtestdx(n_node, DIM);
     // Set the value of n_intpt
     unsigned n_intpt = integral_pt()->nweight();
     // The local index at which the poisson variable is stored
     unsigned u_nodal_index = this->u_index_poisson();
     // Integers to store the local equation and unknown numbers
     int local_eqn = 0, local_unknown = 0;
     // Local storage for pointers to hang_info objects
     HangInfo *hang_info_pt = 0, *hang_info2_pt = 0;
     // Loop over the integration points
     for (unsigned ipt = 0; ipt < n_intpt; ipt++)
     {
       // Get the integral weight
       double w = integral_pt()->weight(ipt);
       // Call the derivatives of the shape and test functions
       double J = this->dshape_and_dtest_eulerian_at_knot_poisson(
         ipt, psi, dpsidx, test, dtestdx);
       // Premultiply the weights and the Jacobian
       double W = w * J;
       // Position and gradient
       Vector<double> interpolated_x(DIM, 0.0);
       Vector<double> interpolated_dudx(DIM, 0.0);
       // Calculate function value and derivatives:
       //-----------------------------------------
       // Loop over nodes
       for (unsigned l = 0; l < n_node; l++)
       {
         // Get the poisson value from the node
         //(hanging-ness will be taken into account
         double u_value = this->nodal_value(l, u_nodal_index);
         // Loop over directions
         for (unsigned j = 0; j < DIM; j++)
         {
           interpolated_x[j] += nodal_position(l, j) * psi(l);
           interpolated_dudx[j] += u_value * dpsidx(l, j);
         }
       }
       // Get body force
       double source;
       this->get_source_poisson(ipt, interpolated_x, source);
       // Assemble residuals and Jacobian
       // Loop over the nodes for the test functions
       for (unsigned l = 0; l < n_node; l++)
       {
         // Local variables used to store the number of master nodes and the
         // weight associated with the shape function if the node is hanging
         unsigned n_master = 1;
         double hang_weight = 1.0;
         // Local bool (is the node hanging)
         bool is_node_hanging = this->node_pt(l)->is_hanging();
         // If the node is hanging, get the number of master nodes
         if (is_node_hanging)
         {
           hang_info_pt = this->node_pt(l)->hanging_pt();
           n_master = hang_info_pt->nmaster();
         }
         // Otherwise there is just one master node, the node itself
         else
         {
           n_master = 1;
         }
         // Loop over the master nodes
         for (unsigned m = 0; m < n_master; m++)
         {
           // Get the local equation number and hang_weight
           // If the node is hanging
           if (is_node_hanging)
           {
             // Read out the local equation number from the m-th master node
             local_eqn = this->local_hang_eqn(hang_info_pt->master_node_pt(m),
                                              u_nodal_index);
             // Read out the weight from the master node
             hang_weight = hang_info_pt->master_weight(m);
           }
           // If the node is not hanging
           else
           {
             // The local equation number comes from the node itself
             local_eqn = this->nodal_local_eqn(l, u_nodal_index);
             // The hang weight is one
             hang_weight = 1.0;
           }
           // If the nodal equation is not a boundary condition
           if (local_eqn >= 0)
           {
             // Add body force/source term here
             residuals[local_eqn] += source * test(l) * W * hang_weight;
             // The Poisson bit itself
             for (unsigned k = 0; k < DIM; k++)
             {
               residuals[local_eqn] +=
                 interpolated_dudx[k] * dtestdx(l, k) * W * hang_weight;
             }
             // Calculate the Jacobian
             if (flag)
             {
               // Local variables to store the number of master nodes
               // and the weights associated with each hanging node
               unsigned n_master2 = 1;
               double hang_weight2 = 1.0;
               // Loop over the nodes for the variables
               for (unsigned l2 = 0; l2 < n_node; l2++)
               {
                 // Local bool (is the node hanging)
                 bool is_node2_hanging = this->node_pt(l2)->is_hanging();
                 // If the node is hanging, get the number of master nodes
                 if (is_node2_hanging)
                 {
                   hang_info2_pt = this->node_pt(l2)->hanging_pt();
                   n_master2 = hang_info2_pt->nmaster();
                 }
                 // Otherwise there is one master node, the node itself
                 else
                 {
                   n_master2 = 1;
                 }
                 // Loop over the master nodes
                 for (unsigned m2 = 0; m2 < n_master2; m2++)
                 {
                   // Get the local unknown and weight
                   // If the node is hanging
                   if (is_node2_hanging)
                   {
                     // Read out the local unknown from the master node
                     local_unknown = this->local_hang_eqn(
                       hang_info2_pt->master_node_pt(m2), u_nodal_index);
                     // Read out the hanging weight from the master node
                     hang_weight2 = hang_info2_pt->master_weight(m2);
                   }
                   // If the node is not hanging
                   else
                   {
                     // The local unknown number comes from the node
                     local_unknown = this->nodal_local_eqn(l2, u_nodal_index);
                     // The hang weight is one
                     hang_weight2 = 1.0;
                   }
                   // If the unknown is not pinned
                   if (local_unknown >= 0)
                   {
                     // Add contribution to Elemental Matrix
                     for (unsigned i = 0; i < DIM; i++)
                     {
                       jacobian(local_eqn, local_unknown) +=
                         dpsidx(l2, i) * dtestdx(l, i) * W * hang_weight *
                         hang_weight2;
                     }
                   }
                 } // End of loop over master nodes
               } // End of loop over nodes
             } // End of Jacobian calculation
           } // End of case when residual equation is not pinned
         } // End of loop over master nodes for residual
       } // End of loop over nodes
     } // End of loop over integration points
   }
References DIM, i, J, j, k, m, m2(), oomph::HangInfo::master_node_pt(), oomph::HangInfo::master_weight(), oomph::HangInfo::nmaster(), TestProblem::source(), Eigen::test, w, and oomph::QuadTreeNames::W.
further_build()
template<unsigned DIM> void oomph::RefineablePoissonEquations< DIM >::further_build () inline virtual
Further build: Copy source function pointer from father element.
Reimplemented from oomph::RefineableElement.
Reimplemented in oomph::PRefineableQPoissonElement< DIM >.
     {
       this->Source_fct_pt = dynamic_cast<RefineablePoissonEquations<DIM>*>(
                               this->father_element_pt())
                               ->source_fct_pt();
     }
References oomph::RefineableElement::father_element_pt(), oomph::PoissonEquations< DIM >::source_fct_pt(), and oomph::PoissonEquations< DIM >::Source_fct_pt.
Referenced by oomph::PRefineableQPoissonElement< DIM >::further_build().
get_dresidual_dnodal_coordinates()
template<unsigned DIM> void oomph::RefineablePoissonEquations< DIM >::get_dresidual_dnodal_coordinates (RankThreeTensor< double > & dresidual_dnodal_coordinates) private virtual
Compute derivatives of elemental residual vector with respect to nodal coordinates. Overwrites default implementation in FiniteElement base class. dresidual_dnodal_coordinates(l,i,j) = d res(l) / dX_{ij}
Compute derivatives of elemental residual vector with respect to nodal coordinates (fully analytical). dresidual_dnodal_coordinates(l,i,j) = d res(l) / dX_{ij} Overloads the FD-based version in the FE base class.
Reimplemented from oomph::RefineableElement.
   {
     // Determine number of nodes in element
     const unsigned n_node = nnode();
     // Set up memory for the shape and test functions
     Shape psi(n_node), test(n_node);
     DShape dpsidx(n_node, DIM), dtestdx(n_node, DIM);
     // Get number of shape controlling nodes
     const unsigned n_shape_controlling_node = nshape_controlling_nodes();
     // Deriatives of shape fct derivatives w.r.t. nodal coords
     RankFourTensor<double> d_dpsidx_dX(
       DIM, n_shape_controlling_node, n_node, DIM);
     RankFourTensor<double> d_dtestdx_dX(
       DIM, n_shape_controlling_node, n_node, DIM);
     // Derivative of Jacobian of mapping w.r.t. to nodal coords
     DenseMatrix<double> dJ_dX(DIM, n_shape_controlling_node);
     // Derivatives of derivative of u w.r.t. nodal coords
     RankThreeTensor<double> d_dudx_dX(DIM, n_shape_controlling_node, DIM);
     // Source function and its gradient
     double source;
     Vector<double> d_source_dx(DIM);
     // Index at which the poisson unknown is stored
     const unsigned u_nodal_index = this->u_index_poisson();
     // Determine the number of integration points
     const unsigned n_intpt = integral_pt()->nweight();
     // Integer to store the local equation number
     int local_eqn = 0;
     // Local storage for pointers to hang_info object
     HangInfo* hang_info_pt = 0;
     // Loop over the integration points
     for (unsigned ipt = 0; ipt < n_intpt; ipt++)
     {
       // Get the integral weight
       double w = integral_pt()->weight(ipt);
       // Call the derivatives of the shape/test functions, as well as the
       // derivatives of these w.r.t. nodal coordinates and the derivative
       // of the jacobian of the mapping w.r.t. nodal coordinates
       const double J = this->dshape_and_dtest_eulerian_at_knot_poisson(
         ipt, psi, dpsidx, d_dpsidx_dX, test, dtestdx, d_dtestdx_dX, dJ_dX);
       // Calculate local values
       // Allocate and initialise to zero
       Vector<double> interpolated_x(DIM, 0.0);
       Vector<double> interpolated_dudx(DIM, 0.0);
       // Calculate function value and derivatives:
       // -----------------------------------------
       // Loop over nodes
       for (unsigned l = 0; l < n_node; l++)
       {
         // Get the nodal value of the Poisson unknown
         double u_value = nodal_value(l, u_nodal_index);
         // Loop over directions
         for (unsigned i = 0; i < DIM; i++)
         {
           interpolated_x[i] += nodal_position(l, i) * psi(l);
           interpolated_dudx[i] += u_value * dpsidx(l, i);
         }
       }
       // Calculate derivative of du/dx_i w.r.t. nodal positions X_{pq}
       // Loop over shape controlling nodes
       for (unsigned q = 0; q < n_shape_controlling_node; q++)
       {
         // Loop over coordinate directions
         for (unsigned p = 0; p < DIM; p++)
         {
           for (unsigned i = 0; i < DIM; i++)
           {
             double aux = 0.0;
             for (unsigned j = 0; j < n_node; j++)
             {
               aux += nodal_value(j, u_nodal_index) * d_dpsidx_dX(p, q, j, i);
             }
             d_dudx_dX(p, q, i) = aux;
           }
         }
       }
       // Get source function
       this->get_source_poisson(ipt, interpolated_x, source);
       // Get gradient of source function
       this->get_source_gradient_poisson(ipt, interpolated_x, d_source_dx);
       //   std::map<Node*,unsigned>
       //   local_shape_controlling_node_lookup=shape_controlling_node_lookup();
       // Assemble d res_{local_eqn} / d X_{pq}
       // -------------------------------------
       // Loop over the nodes for the test functions
       for (unsigned l = 0; l < n_node; l++)
       {
         // Local variables used to store the number of master nodes and the
         // weight associated with the shape function if the node is hanging
         unsigned n_master = 1;
         double hang_weight = 1.0;
         // Local bool (is the node hanging)
         bool is_node_hanging = this->node_pt(l)->is_hanging();
         // If the node is hanging, get the number of master nodes
         if (is_node_hanging)
         {
           hang_info_pt = this->node_pt(l)->hanging_pt();
           n_master = hang_info_pt->nmaster();
         }
         // Otherwise there is just one master node, the node itself
         else
         {
           n_master = 1;
         }
         // Loop over the master nodes
         for (unsigned m = 0; m < n_master; m++)
         {
           // Get the local equation number and hang_weight
           // If the node is hanging
           if (is_node_hanging)
           {
             // Read out the local equation number from the m-th master node
             local_eqn = this->local_hang_eqn(hang_info_pt->master_node_pt(m),
                                              u_nodal_index);
             // Read out the weight from the master node
             hang_weight = hang_info_pt->master_weight(m);
           }
           // If the node is not hanging
           else
           {
             // The local equation number comes from the node itself
             local_eqn = this->nodal_local_eqn(l, u_nodal_index);
             // The hang weight is one
             hang_weight = 1.0;
           }
           // If the nodal equation is not a boundary condition
           if (local_eqn >= 0)
           {
             // Loop over coordinate directions
             for (unsigned p = 0; p < DIM; p++)
             {
               // Loop over shape controlling nodes
               for (unsigned q = 0; q < n_shape_controlling_node; q++)
               {
                 double sum = source * test(l) * dJ_dX(p, q) +
                              d_source_dx[p] * test(l) * psi(q) * J;
                 for (unsigned i = 0; i < DIM; i++)
                 {
                   sum += interpolated_dudx[i] * (dtestdx(l, i) * dJ_dX(p, q) +
                                                  d_dtestdx_dX(p, q, l, i) * J) +
                          d_dudx_dX(p, q, i) * dtestdx(l, i) * J;
                 }
                 // Multiply through by integration weight
                 dresidual_dnodal_coordinates(local_eqn, p, q) +=
                   sum * w * hang_weight;
               }
             }
           }
         }
       }
     } // End of loop over integration points
   }
References DIM, i, J, j, m, oomph::HangInfo::master_node_pt(), oomph::HangInfo::master_weight(), oomph::HangInfo::nmaster(), p, Eigen::numext::q, TestProblem::source(), Eigen::test, and w.
get_interpolated_values() [1/2]
template<unsigned DIM> void oomph::RefineablePoissonEquations< DIM >::get_interpolated_values (const unsigned & t, const Vector< double > & s, Vector< double > & values) inline virtual
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
Implements oomph::RefineableElement.
     {
       if (t != 0)
       {
         std::string error_message =
           "Time-dependent version of get_interpolated_values() ";
         error_message += "not implemented for this element \n";
         throw OomphLibError(
           error_message,
           "RefineablePoissonEquations::get_interpolated_values()",
           OOMPH_EXCEPTION_LOCATION);
       }
       else
       {
         // Make sure that we call this particular object's steady
         // get_interpolated_values (it could get overloaded lower down)
         RefineablePoissonEquations<DIM>::get_interpolated_values(s, values);
       }
     }
References oomph::RefineablePoissonEquations< DIM >::get_interpolated_values(), OOMPH_EXCEPTION_LOCATION, s, oomph::Global_string_for_annotation::string(), and plotPSD::t.
get_interpolated_values() [2/2]
template<unsigned DIM> void oomph::RefineablePoissonEquations< DIM >::get_interpolated_values (const Vector< double > & s, Vector< double > & values) inline virtual
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
Reimplemented from oomph::RefineableElement.
     {
       // Set size of Vector: u
       values.resize(1);
       // Find number of nodes
       unsigned n_node = nnode();
       // Local shape function
       Shape psi(n_node);
       // Find values of shape function
       shape(s, psi);
       // Initialise value of u
       values[0] = 0.0;
       // Find the index at which the poisson unknown is stored
       unsigned u_nodal_index = this->u_index_poisson();
       // Loop over the local nodes and sum up the values
       for (unsigned l = 0; l < n_node; l++)
       {
         values[0] += this->nodal_value(l, u_nodal_index) * psi[l];
       }
     }
References oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), s, oomph::FiniteElement::shape(), and oomph::PoissonEquations< DIM >::u_index_poisson().
Referenced by oomph::RefineablePoissonEquations< DIM >::get_interpolated_values().
get_Z2_flux()
template<unsigned DIM> void oomph::RefineablePoissonEquations< DIM >::get_Z2_flux (const Vector< double > & s, Vector< double > & flux) inline virtual
Get 'flux' for Z2 error recovery: Standard flux.from Poisson equations.
Implements oomph::ElementWithZ2ErrorEstimator.
     {
       this->get_flux(s, flux);
     }
References ProblemParameters::flux(), and oomph::PoissonEquations< DIM >::get_flux().
num_Z2_flux_terms()
template<unsigned DIM> unsigned oomph::RefineablePoissonEquations< DIM >::num_Z2_flux_terms () inline virtual
Number of 'flux' terms for Z2 error estimation.
Implements oomph::ElementWithZ2ErrorEstimator.
     {
       return DIM;
     }
References DIM.
operator=()
template<unsigned DIM> void oomph::RefineablePoissonEquations< DIM >::operator= (const RefineablePoissonEquations< DIM > &) delete
Broken assignment operator.
The documentation for this class was generated from the following files:
refineable_poisson_elements.h
refineable_poisson_elements.cc