MercuryDPM: oomph::Global_string_for_annotation Namespace Reference
oomph::Global_string_for_annotation Namespace Reference
Functions
std::string string (const unsigned &i)
Variables
std::vector< std::string > String
Detailed Description
///////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////// Namespace containing a vector of strings that can be used to to store global output modifiers. This is global data and you use it at your own risk!
Function Documentation
string()
std::string oomph::Global_string_for_annotation::string (const unsigned & i)
Return the i-th string or "" if the relevant string hasn't been defined
     {
       if (i < String.size())
       {
         return String[i];
       }
       else
       {
         return "";
       }
     }
References i, and String.
Referenced by oomph::IMRByBDF::actions_after_timestep(), oomph::MyProblem::actions_before_newton_step(), oomph::IMRByBDF::actions_before_timestep(), oomph::TR::actions_before_timestep(), ParameterStudy1DDemo::actionsBeforeTimeLoop(), ParameterStudy2DDemo::actionsBeforeTimeLoop(), ParameterStudy3DDemo::actionsBeforeTimeLoop(), oomph::RefineableGmshTetMesh< ELEMENT >::adapt(), oomph::Problem::adaptive_unsteady_newton_solve(), oomph::SumOfMatrices::add_matrix(), addObject(), oomph::AdvectionDiffusionFluxElement< ELEMENT >::AdvectionDiffusionFluxElement(), oomph::AlgebraicChannelWithLeafletMesh< ELEMENT >::algebraic_node_update(), oomph::AlgebraicCollapsibleChannelMesh< ELEMENT >::algebraic_node_update(), oomph::AlgebraicFishMesh< ELEMENT >::algebraic_node_update(), oomph::AlgebraicFSIDrivenCavityMesh< ELEMENT >::algebraic_node_update(), oomph::AlgebraicRefineableQuarterCircleSectorMesh< ELEMENT >::algebraic_node_update(), oomph::AlgebraicRefineableQuarterTubeMesh< ELEMENT >::algebraic_node_update(), oomph::AlgebraicRefineableQuarterCircleSectorMesh< ELEMENT >::AlgebraicRefineableQuarterCircleSectorMesh(), oomph::AlgebraicRefineableQuarterTubeMesh< ELEMENT >::AlgebraicRefineableQuarterTubeMesh(), oomph::Problem::arc_length_step_solve_helper(), oomph::IMRBase::assign_initial_positions_impulsive(), oomph::IMRBase::assign_initial_values_impulsive(), oomph::AlgebraicCollapsibleChannelMesh< ELEMENT >::axial_spacing_fct_pt(), oomph::AlgebraicRefineableQuarterTubeMesh< ELEMENT >::axial_spacing_fct_pt(), oomph::SolidICProblem::backup_original_state(), oomph::BinaryTreeRoot::BinaryTreeRoot(), oomph::MyAlgebraicCollapsibleChannelMesh< ELEMENT >::bl_squash_fct_pt(), oomph::AlgebraicCollapsibleChannelMesh< ELEMENT >::bl_squash_fct_pt(), oomph::BrokenCopy::broken_assign(), oomph::BrokenCopy::broken_copy(), oomph::AddedMainNumberingLookup::build(), oomph::RefineableQElement< 3 >::build(), oomph::RefineableQElement< 1 >::build(), oomph::RefineableQElement< 2 >::build(), oomph::MyProblem::build(), oomph::GeompackQuadMesh< ELEMENT >::build_from_scaffold(), oomph::Problem::build_global_mesh(), oomph::FiniteElement::bulk_coordinate_derivatives_fct_pt(), oomph::QElement< 1, NNODE_1D >::bulk_coordinate_derivatives_fct_pt(), oomph::QElement< 2, NNODE_1D >::bulk_coordinate_derivatives_fct_pt(), oomph::QElement< 3, NNODE_1D >::bulk_coordinate_derivatives_fct_pt(), oomph::RefineableSolidCubicMesh< ELEMENT >::calculate_boundary_coordinate_of_node(), oomph::ConstitutiveLaw::calculate_contravariant(), oomph::ConstitutiveLaw::calculate_d_contravariant_dG(), oomph::IMRBase::calculate_predicted_positions(), oomph::Problem::calculate_predictions(), oomph::IsotropicStrainEnergyFunctionConstitutiveLaw::calculate_second_piola_kirchhoff_stress(), Calibration::Calibration(), CFile::CFile(), oomph::OneDMesh< ELEMENT >::check_1d(), check_locate_zeta(), check_marketio(), check_marketio_dense(), check_marketio_vector(), oomph::MyProblem::check_norm_limits(), check_sparse_spd_solving(), check_sparse_square_solving(), DeletionBoundary::checkBoundaryAfterParticleMoved(), oomph::CommandLineArgs::command_line_flag_has_been_set(), commandLineCG(), helpers::compare(), oomph::ComplexDampedJacobi< MATRIX >::complex_solve_helper(), oomph::FiniteElement::compute_abs_error(), oomph::FiniteElement::compute_error(), oomph::ElementWithZ2ErrorEstimator::compute_exact_Z2_error(), oomph::GeneralisedElement::compute_norm(), oomph::FluidInterfaceBoundingElement::contact_angle(), CFile::copy(), CFile::copy_data(), CFile::copy_fstat(), oomph::GmshTetScaffoldMesh::create_mesh_from_msh_file(), DomainHandler::createMesh(), DataFiles::DataFiles(), oomph::DebugHelpers::debug_string(), demo_smoothing_with_linear_elasticity(), demo_smoothing_with_nonlinear_elasticity(), demo_smoothing_with_poisson(), oomph::SolutionFunctor::derivative(), oomph::TR::derivative_index(), oomph::GeneralisedElement::describe_dofs(), oomph::Mesh::describe_dofs(), oomph::SolidNode::describe_dofs(), oomph::Problem::describe_dofs(), oomph::ElementWithExternalElement::describe_local_dofs(), oomph::ElementWithMovingNodes::describe_local_dofs(), oomph::GeneralisedElement::describe_local_dofs(), oomph::FSIWallElement::describe_local_dofs(), oomph::Mesh::describe_local_dofs(), oomph::SpectralElement::describe_local_dofs(), oomph::FiniteElement::describe_nodal_local_dofs(), oomph::SolidFiniteElement::describe_solid_local_dofs(), oomph::SpineMesh::describe_spine_dofs(), oomph::CommandLineArgs::doc_all_flags(), oomph::CommandLineArgs::doc_available_flags(), UnsteadyHeatProblem< ELEMENT >::doc_solution(), NavierStokesProblem< ELEMENT >::doc_solution(), oomph::MyProblem::doc_solution(), oomph::CommandLineArgs::doc_specified_flags(), oomph::Problem::dump(), oomph::Mesh::dump(), EIGEN_DECLARE_TEST(), oomph::FiniteElement::element_geometry(), oomph::CRMatrix< T >::entry(), oomph::CCMatrix< T >::entry(), oomph::ConstitutiveLaw::error_checking_in_input(), oomph::MyProblem::exact_solution(), ExecCommand(), oomph::FiniteElement::face_node_number_error_check(), oomph::FiniteElement::face_outer_unit_normal_sign(), oomph::QElement< 1, NNODE_1D >::face_outer_unit_normal_sign(), oomph::QElement< 2, NNODE_1D >::face_outer_unit_normal_sign(), oomph::QElement< 3, NNODE_1D >::face_outer_unit_normal_sign(), oomph::FiniteElement::face_to_bulk_coordinate_fct_pt(), oomph::QElement< 1, NNODE_1D >::face_to_bulk_coordinate_fct_pt(), oomph::QElement< 2, NNODE_1D >::face_to_bulk_coordinate_fct_pt(), oomph::QElement< 3, NNODE_1D >::face_to_bulk_coordinate_fct_pt(), oomph::GeneralisedElement::fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter(), oomph::GeneralisedElement::fill_in_contribution_to_djacobian_dparameter(), oomph::GeneralisedElement::fill_in_contribution_to_dresiduals_dparameter(), oomph::GeneralisedElement::fill_in_contribution_to_hessian_vector_products(), oomph::GeneralisedElement::fill_in_contribution_to_inner_product_vectors(), oomph::GeneralisedElement::fill_in_contribution_to_inner_products(), oomph::PVDEquationsWithPressure< DIM >::fill_in_contribution_to_jacobian(), oomph::GeneralisedElement::fill_in_contribution_to_jacobian_and_mass_matrix(), oomph::PVDEquationsWithPressure< DIM >::fill_in_contribution_to_jacobian_and_mass_matrix(), oomph::GeneralisedElement::fill_in_contribution_to_mass_matrix(), oomph::GeneralisedElement::fill_in_contribution_to_residuals(), oomph::GeneralPurposeBlockPreconditioner< MATRIX >::fill_in_subsidiary_preconditioners(), oomph::BlockDiagonalPreconditioner< MATRIX >::fill_in_subsidiary_preconditioners(), format(), oomph::FourierDecomposedHelmholtzBCElementBase< ELEMENT >::FourierDecomposedHelmholtzBCElementBase(), oomph::FourierDecomposedHelmholtzFluxElement< ELEMENT >::FourierDecomposedHelmholtzFluxElement(), oomph::FourierDecomposedHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::FourierDecomposedHelmholtzFluxFromNormalDisplacementBCElement(), oomph::MGSolver< DIM >::full_setup(), oomph::HelmholtzMGPreconditioner< DIM >::full_setup(), oomph::FullCircleMesh< ELEMENT >::FullCircleMesh(), oomph::FiniteElement::get_bulk_node_number(), oomph::QElement< 1, NNODE_1D >::get_bulk_node_number(), oomph::QElement< 2, NNODE_1D >::get_bulk_node_number(), oomph::QElement< 3, NNODE_1D >::get_bulk_node_number(), oomph::PVDEquationsWithPressure< DIM >::get_d_stress_dG_upper(), oomph::PVDEquations< DIM >::get_d_stress_dG_upper(), oomph::RefineableAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates(), oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates(), oomph::KirchhoffLoveShellEquations::get_energy(), oomph::CRDoubleMatrix::get_index_of_diagonal_entries(), RefineableModalPoissonEquations< DIM >::get_interpolated_values(), oomph::RefineablePolarStreamfunctionEquations::get_interpolated_values(), oomph::RefineableAxisymAdvectionDiffusionEquations::get_interpolated_values(), oomph::RefineableHelmholtzEquations< DIM >::get_interpolated_values(), oomph::RefineablePMLHelmholtzEquations< DIM >::get_interpolated_values(), oomph::RefineablePoissonEquations< DIM >::get_interpolated_values(), oomph::RefineableSphericalAdvectionDiffusionEquations::get_interpolated_values(), NodeReordering::get_node_reordering(), oomph::Mesh::get_node_reordering(), RefineableModalPoissonEquations< DIM >::get_source_gradient(), oomph::AxisymmetricPVDEquations::get_stress(), oomph::PVDEquations< DIM >::get_stress(), oomph::AxisymmetricPVDEquationsWithPressure::get_stress(), oomph::PVDEquationsWithPressure< DIM >::get_stress(), oomph::NavierStokesEquations< 2 >::get_traction(), oomph::TypeNames::get_type_name(), BaseVTKWriter< H >::getFileName(), helpers::getLineFromStringStream(), Eigen::getMarketHeader(), getName(), Eigen::MatrixMarketIterator< Scalar >::Getnextvalidmatrix(), helpers::getPath(), GetTestTempFilename(), AreaVTK::getTotalsurfaceAreaFromFile(), oomph::Problem::global_temporal_error_norm(), oomph::GmshTetScaffoldMesh::GmshTetScaffoldMesh(), oomph::HeatedPenetratorFluxElement< ELEMENT >::HeatedPenetratorFluxElement(), oomph::HelmholtzBCElementBase< ELEMENT >::HelmholtzBCElementBase(), oomph::HelmholtzFluxElement< ELEMENT >::HelmholtzFluxElement(), oomph::HelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::HelmholtzFluxFromNormalDisplacementBCElement(), oomph::Hijacked< ELEMENT >::hijack_nodal_position_value(), oomph::Hijacked< ELEMENT >::hijack_nodal_spine_value(), oomph::MyProblem::initial_doc(), oomph::BlockPreconditioner< MATRIX >::internal_get_block(), oomph::MGSolver< DIM >::interpolation_matrix_set(), oomph::HelmholtzMGPreconditioner< DIM >::interpolation_matrix_set(), oomph::MGSolver< DIM >::interpolation_self_test(), MercuryDataFile::isMercuryDataFile(), helpers::isNext(), oomph::SolutionFunctorBase::jacobian(), oomph::LinearWaveFluxElement< ELEMENT >::LinearWaveFluxElement(), load(), MarbleRun::loadBigSeesaw(), LoadFinalOrient(), Membrane::loadFromSTL(), LoadInitOrient(), LoadIProfiles(), Eigen::loadMarketDense(), LoadMass(), LoadPD(), LoadPebbles(), MarbleRun::loadSmallSeesaw(), LoadTOI(), Membrane::loadVertexPositions(), oomph::FiniteElement::local_one_d_fraction_of_node(), helpers::lookAhead(), oomph::RectangleWithHoleAndAnnularRegionDomain::macro_element_boundary(), oomph::MacroElementNodeUpdateChannelWithLeafletMesh< ELEMENT >::MacroElementNodeUpdateChannelWithLeafletMesh(), oomph::MacroElementNodeUpdateCollapsibleChannelMesh< ELEMENT >::MacroElementNodeUpdateCollapsibleChannelMesh(), oomph::MacroElementNodeUpdateRefineableFishMesh< ELEMENT >::MacroElementNodeUpdateRefineableFishMesh(), oomph::MacroElementNodeUpdateRefineableQuarterCircleSectorMesh< ELEMENT >::MacroElementNodeUpdateRefineableQuarterCircleSectorMesh(), oomph::MacroElementNodeUpdateRefineableQuarterTubeMesh< ELEMENT >::MacroElementNodeUpdateRefineableQuarterTubeMesh(), main(), main_gemm(), main_gemv(), oomph::AddedMainNumberingLookup::main_to_added(), BaseCluster::makeGnuplotFile(), BaseVTKWriter< H >::makeVTKFileWithHeader(), Eigen::MatrixMarketIterator< Scalar >::matrix(), helpers::more(), oomph::MyProblem::my_set_initial_condition(), oomph::DGMesh::neighbour_finder(), oomph::FiniteElement::nnode_on_face(), oomph::RefineableQElement< 1 >::node_created_by_neighbour(), oomph::NodeOrdering::node_global_position_comparison(), oomph::PerturbedSpineMesh::node_update(), oomph::AlgebraicMesh::node_update(), oomph::MacroElementNodeUpdateMesh::node_update(), oomph::SpineMesh::node_update(), oomph::MacroElementNodeUpdateRefineableFishMesh< ELEMENT >::node_update(), oomph::AlgebraicFishMesh< ELEMENT >::node_update(), oomph::MacroElementNodeUpdateRefineableQuarterCircleSectorMesh< ELEMENT >::node_update(), oomph::AlgebraicRefineableQuarterCircleSectorMesh< ELEMENT >::node_update(), oomph::MacroElementNodeUpdateRefineableQuarterTubeMesh< ELEMENT >::node_update(), oomph::AlgebraicRefineableQuarterTubeMesh< ELEMENT >::node_update(), oomph::AlgebraicRefineableQuarterTubeMesh< ELEMENT >::node_update_central_region(), oomph::AlgebraicRefineableQuarterCircleSectorMesh< ELEMENT >::node_update_in_central_box(), oomph::AlgebraicRefineableQuarterCircleSectorMesh< ELEMENT >::node_update_in_lower_right_box(), oomph::AlgebraicRefineableQuarterCircleSectorMesh< ELEMENT >::node_update_in_upper_left_box(), oomph::AlgebraicRefineableQuarterTubeMesh< ELEMENT >::node_update_lower_right_region(), oomph::AlgebraicRefineableQuarterTubeMesh< ELEMENT >::node_update_upper_left_region(), oomph::Z2ErrorEstimator::nrecovery_terms(), oomph::FiniteElement::nvertex_node(), oomph::ObsoleteCode::obsolete(), oomph::OcTreeRoot::OcTreeRoot(), AngledPeriodicBoundary::oldRead(), CircularPeriodicBoundary::oldRead(), DeletionBoundary::oldRead(), FluxBoundary::oldRead(), PeriodicBoundary::oldRead(), Coil::oldRead(), CylindricalWall::oldRead(), InfiniteWall::oldRead(), InfiniteWallWithHole::oldRead(), Screw::oldRead(), oomph::OomphLibException::OomphLibException(), openglsupport_test_loop(), oomph::SolutionFunctor::operator()(), MercuryTimeStepIterator< NDIMS >::operator++(), operator>>(), oomph::Newmark< NSTEPS >::order(), oomph::BlockPreconditioner< MATRIX >::output_blocks_to_files(), oomph::SparseMatrix< T, MATRIX_TYPE >::output_bottom_right_zero_helper(), oomph::GeneralisedNewtonianNavierStokesEquations< DIM >::output_vorticity(), oomph::SpaceTimeNavierStokesEquations< DIM >::output_vorticity(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::output_vorticity(), oomph::PRefineableQElement< 1, INITIAL_NNODE_1D >::p_refine(), oomph::PRefineableQElement< 2, INITIAL_NNODE_1D >::p_refine(), oomph::PRefineableQElement< 3, INITIAL_NNODE_1D >::p_refine(), oomph::Tree::p_refine_if_required(), parallel_test(), GlobalParameters::parameter_to_string(), oomph::CommandLineArgs::parse_and_assign(), oomph::pause(), oomph::PMLFourierDecomposedHelmholtzFluxElement< ELEMENT >::PMLFourierDecomposedHelmholtzFluxElement(), oomph::PMLFourierDecomposedHelmholtzPowerMonitorElement< ELEMENT >::PMLFourierDecomposedHelmholtzPowerMonitorElement(), oomph::PMLHelmholtzFluxElement< ELEMENT >::PMLHelmholtzFluxElement(), oomph::PMLHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::PMLHelmholtzFluxFromNormalDisplacementBCElement(), oomph::PMLHelmholtzPowerElement< ELEMENT >::PMLHelmholtzPowerElement(), oomph::PoissonFluxElement< ELEMENT >::PoissonFluxElement(), oomph::PRefineableQElement< 2, INITIAL_NNODE_1D >::pre_build(), oomph::PRefineableQElement< 3, INITIAL_NNODE_1D >::pre_build(), oomph::StorableShapeElementBase::pre_compute_d2shape_local_at_knots(), oomph::StorableShapeElementBase::pre_compute_dshape_local_at_knots(), oomph::StorableShapeElementBase::pre_compute_shape_at_knots(), oomph::GS< CRDoubleMatrix >::preconditioner_setup_time(), oomph::TimeStepper::predictor_storage_index(), oomph::QExtrudedMacroElement< 3 >::QExtrudedMacroElement(), oomph::QuadTreeRoot::QuadTreeRoot(), FileReader::read(), csvReader::read(), oomph::PerturbedSpineMesh::read(), oomph::MyProblem::read(), oomph::Mesh::read(), oomph::Data::read(), oomph::Node::read(), oomph::SolidNode::read(), oomph::SpineMesh::read(), oomph::Problem::read(), BaseHandler< T >::read(), File::read(), InteractionHandler::read(), RNG::read(), BondedSpecies::read(), ChargedBondedSpecies::read(), JKRAdhesiveSpecies::read(), LiquidBridgeBagheriSpecies::read(), LiquidBridgeClassicalWilletSpecies::read(), LiquidBridgeWilletSpecies::read(), LiquidMigrationLSSpecies::read(), LiquidMigrationWilletSpecies::read(), LiquidMigrationWilletViscousSpecies::read(), ReversibleAdhesiveSpecies::read(), SolidifyingLiquidMigrationWilletSpecies::read(), FrictionSpecies::read(), MindlinRollingTorsionSpecies::read(), MindlinSpecies::read(), SlidingFrictionSpecies::read(), HeatFluidCoupledSpecies< NormalForceSpecies >::read(), HertzianSinterNormalSpecies::read(), HertzianViscoelasticNormalSpecies::read(), LinearPlasticViscoelasticNormalSpecies::read(), LinearViscoelasticNormalSpecies::read(), MeltableNormalSpecies::read(), SinterLinNormalSpecies::read(), SinterNormalSpecies::read(), SPHNormalSpecies::read(), ThermalSpecies< NormalForceSpecies >::read(), MixedSpecies< NormalForceSpecies, FrictionForceSpecies, AdhesiveForceSpecies >::read(), BaseInteractable::read(), AngledPeriodicBoundary::read(), BaseClusterInsertionBoundary::read(), BidisperseCubeInsertionBoundary::read(), ChuteInsertionBoundary::read(), CircularPeriodicBoundary::read(), ConstantMassFlowMaserBoundary::read(), CubeDeletionBoundary::read(), CubeInsertionBoundary::read(), CylinderInsertionBoundary::read(), DeletionBoundary::read(), DropletBoundary::read(), FluxBoundary::read(), HeaterBoundary::read(), HopperInsertionBoundary::read(), InsertionBoundary::read(), LeesEdwardsBoundary::read(), PeriodicBoundary::read(), ShearBoxBoundary::read(), SphereInsertionBoundary::read(), StressStrainControlBoundary::read(), SubcriticalMaserBoundary::read(), SubcriticalMaserBoundaryTEST::read(), TimeDependentPeriodicBoundary::read(), BondedInteraction::read(), ChargedBondedInteraction::read(), IrreversibleAdhesiveInteraction::read(), LiquidBridgeBagheriInteraction::read(), LiquidBridgeClassicalWilletInteraction::read(), LiquidBridgeWilletInteraction::read(), LiquidMigrationLSInteraction::read(), LiquidMigrationWilletInteraction::read(), SolidifyingLiquidMigrationWilletInteraction::read(), BaseInteraction::read(), FrictionInteraction::read(), MindlinInteraction::read(), MindlinRollingTorsionInteraction::read(), SlidingFrictionInteraction::read(), HertzianSinterInteraction::read(), LinearPlasticViscoelasticInteraction::read(), MeltableInteraction::read(), SinterInteraction::read(), SinterLinInteraction::read(), BaseParticle::read(), ClumpParticle::read(), LiquidFilm< Particle >::read(), SuperQuadricParticle::read(), Thermal< Particle >::read(), ParticleSpecies::read(), ArcWall::read(), BaseWall::read(), BasicIntersectionOfWalls::read(), BasicUnionOfWalls::read(), Coil::read(), Combtooth::read(), CylindricalWall::read(), HorizontalScrew::read(), InfiniteWallWithHole::read(), IntersectionOfWalls::read(), LevelSetWall::read(), Membrane::read(), MeshTriangle::read(), NurbsWall::read(), Screw::read(), SineWall::read(), SphericalWall::read(), TriangleMeshWall::read(), TriangleWall::read(), VChute::read(), WearableNurbsWall::read(), WearableTriangleMeshWall::read(), BaseObject::read(), MembraneDemo::read(), MembraneSelfTest::read(), DPMBase::read(), Funnel::read(), BaseCluster::read(), Chute::read(), MercuryBase::read(), oomph::TreeBasedRefineableMeshBase::read_refinement(), BoundaryHandler::readAndAddObject(), InteractionHandler::readAndAddObject(), SpeciesHandler::readAndAddObject(), ParticleHandler::readAndCreateObject(), WallHandler::readAndCreateObject(), WallHandler::readAndCreateOldObject(), DPMBase::readDataFile(), helpers::readFromFile(), DPMBase::readNextArgument(), Chute::readNextArgument(), DPMBase::readNextDataFile(), DPMBase::readNextFStatFile(), DPMBase::readOld(), BoundaryHandler::readOldObject(), SpeciesHandler::readOldObject(), helpers::readOptionalVariable(), DPMBase::readRestartFile(), BinaryReader::readString(), WallHandler::readTriangleWall(), TriangulatedWall::readVTK(), oomph::real_date_time(), oomph::PRefineableQElement< 1, INITIAL_NNODE_1D >::rebuild_from_sons(), oomph::PRefineableQElement< 2, INITIAL_NNODE_1D >::rebuild_from_sons(), oomph::PRefineableQElement< 3, INITIAL_NNODE_1D >::rebuild_from_sons(), oomph::RefineableQSpectralElement< 3 >::rebuild_from_sons(), oomph::RefineableQSpectralElement< 1 >::rebuild_from_sons(), oomph::RefineableQSpectralElement< 2 >::rebuild_from_sons(), oomph::RefineableGmshTetMesh< ELEMENT >::refine_uniformly(), oomph::RefineableSolidQElement< 1 >::RefineableSolidQElement(), Eigen::MatrixMarketIterator< Scalar >::refX(), DPMBase::removeOldFiles(), SolidProblem< ELEMENT_TYPE >::removeOldFiles(), VTKData::reservePoints(), oomph::SolidICProblem::reset_original_state(), oomph::MGSolver< DIM >::restriction_self_test(), Eigen::MatrixMarketIterator< Scalar >::rhs(), RotatingDrumBidisperse::RotatingDrumBidisperse(), RotatingDrumBidisperseInitialise::RotatingDrumBidisperseInitialise(), statistics_while_running< T >::run(), Eigen::internal::TensorPrinter< Tensor, rank, Format, EnableIf >::run(), oomph::MemoryUsage::run_continous_top(), NavierStokesProblem< ELEMENT >::run_natural_continuation(), Eigen::saveMarket(), SolidProblem< ELEMENT_TYPE >::saveSolidMesh(), oomph::MGSolver< DIM >::self_test(), oomph::DocInfo::set_directory(), oomph::StorableShapeElementBase::set_shape_local_stored_from_element(), oomph::SpineVolumeConstraintPointElement< ELEMENT >::set_traded_pressure_data(), oomph::FixedVolumeSpineLineMarangoniFluidInterfaceElement< ELEMENT >::set_traded_pressure_data(), oomph::MyProblem::set_up_impulsive_initial_condition(), DPMBase::setName(), LevelSetWall::setShapeFourSided(), Calibration::setSpecies(), oomph::SpaceTimeNavierStokesSubsidiaryPreconditioner::setup(), oomph::AlgebraicRefineableQuarterCircleSectorMesh< ELEMENT >::setup_algebraic_node_update(), oomph::AlgebraicRefineableQuarterTubeMesh< ELEMENT >::setup_algebraic_node_update(), oomph::UnstructuredTwoDMeshGeometryBase::setup_boundary_coordinates(), oomph::LineMeshBase::setup_boundary_element_info(), oomph::HermiteQuadMesh< ELEMENT >::setup_boundary_element_info(), oomph::LineVisualiser::setup_from_file(), oomph::MacroElementNodeUpdateRefineableQuarterCircleSectorMesh< ELEMENT >::setup_macro_element_node_update(), oomph::MacroElementNodeUpdateRefineableQuarterTubeMesh< ELEMENT >::setup_macro_element_node_update(), oomph::MGSolver< DIM >::setup_mg_structures(), oomph::HelmholtzMGPreconditioner< DIM >::setup_mg_structures(), oomph::SolidICProblem::setup_problem(), oomph::MGSolver< DIM >::setup_smoothers(), oomph::HelmholtzMGPreconditioner< DIM >::setup_smoothers(), ClosedCSCStats::setupInitialConditions(), CSCStats::setupInitialConditions(), CFDDEMCoupleTest::setupInitialConditions(), Drum::setupInitialConditions(), Penetration::setupInitialConditions(), Silo::setupInitialConditions(), SheetGlueProblem< ELEMENT >::SheetGlueProblem(), SinterPair::SinterPair(), oomph::TetMeshBase::snap_to_quadratic_surface(), oomph::ComplexGMRES< MATRIX >::solve(), oomph::CG< MATRIX >::solve_helper(), oomph::BiCGStab< MATRIX >::solve_helper(), oomph::GS< MATRIX >::solve_helper(), oomph::GS< CRDoubleMatrix >::solve_helper(), oomph::DampedJacobi< MATRIX >::solve_helper(), oomph::GMRES< MATRIX >::solve_helper(), oomph::AugmentedProblemGMRES::solve_helper(), oomph::HelmholtzGMRESMG< MATRIX >::solve_helper(), oomph::HelmholtzFGMRESMG< MATRIX >::solve_helper(), InclinedPlaneProblem< ELEMENT, INTERFACE_ELEMENT >::solve_steady(), solve_with_fully_automatic_adaptation(), solve_with_incremental_adaptation(), solve_with_selected_refinement_pattern(), oomph::SparseMatrix< T, MATRIX_TYPE >::sparse_indexed_output_helper(), oomph::SphericalAdvectionDiffusionFluxElement< ELEMENT >::SphericalAdvectionDiffusionFluxElement(), oomph::Tree::split_if_required(), oomph::StringConversion::split_string(), statistics_while_running< T >::statistics_while_running(), oomph::SteadyAxisymAdvectionDiffusionFluxElement< ELEMENT >::SteadyAxisymAdvectionDiffusionFluxElement(), StefanBoltzmannProblem< ELEMENT >::StefanBoltzmannProblem(), oomph::StefanBoltzmannUnsteadyHeatFluxElement< ELEMENT >::StefanBoltzmannUnsteadyHeatFluxElement(), oomph::MemoryUsage::stop_continous_top(), helpers::stringFormat(), oomph::SurfaceMeltElement< ELEMENT >::SurfaceMeltElement(), oomph::TElement< 1, NNODE_1D >::TElement(), oomph::TElement< 2, NNODE_1D >::TElement(), oomph::TElement< 3, NNODE_1D >::TElement(), oomph::IMRBase::temporal_error_in_position(), oomph::IMRBase::temporal_error_in_value(), test_additions(), test_assign(), test_initialization(), oomph::TetgenScaffoldMesh::TetgenScaffoldMesh(), oomph::TimeStepper::time(), oomph::Time::time(), oomph::TimeStepper::time_pt(), oomph::Factories::time_stepper_factory(), InclinedPlaneProblem< ELEMENT, INTERFACE_ELEMENT >::timestep(), oomph::EBDF3::timestep(), oomph::StringConversion::to_lower(), oomph::StringConversion::to_upper(), transformMercuryToVTK(), oomph::TriangleScaffoldMesh::TriangleScaffoldMesh(), oomph::RefineableGmshTetMesh< ELEMENT >::unrefine_uniformly(), oomph::UnsteadyHeatBaseFaceElement< ELEMENT >::UnsteadyHeatBaseFaceElement(), oomph::UnsteadyHeatFluxElement< ELEMENT >::UnsteadyHeatFluxElement(), oomph::UnsteadyHeatFluxPseudoMeltElement< ELEMENT >::UnsteadyHeatFluxPseudoMeltElement(), oomph::SolarRadiationBase::update_limiting_angles(), oomph::AlgebraicRefineableQuarterCircleSectorMesh< ELEMENT >::update_node_update(), variable_identifier(), oomph::MyTaylorHoodElement< DIM >::variable_identifier(), oomph::MyCrouzeixRaviartElement::variable_identifier(), oomph::FiniteElement::vertex_node_pt(), oomph::StrainEnergyFunction::W(), oomph::GmshTetScaffoldMesh::write_geo_file(), CFile::writeP4C(), CFile::writeP4P(), CFile::writeP4W(), VTKData::writePointData(), DPMBase::writePythonFileForVTKVisualisation(), DataFiles::writeTimeStep(), ChutePeriodic::writeToLocalFolder(), SolidProblem< ELEMENT_TYPE >::writeToVTK(), and oomph::XdaTetMesh< ELEMENT >::XdaTetMesh().
Variable Documentation
String
std::vector< std::string > oomph::Global_string_for_annotation::String
Storage for strings that may be used for global annotations. This is global data and you use it at your own risk!
Referenced by string().