MercuryDPM: oomph::BermudezPMLMapping Class Reference
oomph::BermudezPMLMapping Class Reference
#include <pml_mapping_functions.h>
Public Member Functions
BermudezPMLMapping ()
Default constructor (empty)
std::complex< double > gamma (const double &nu_i, const double &pml_width_i, const double &wavenumber_squared, const double &alpha_shift=0.0)
Public Member Functions inherited from oomph::PMLMapping
PMLMapping ()
Default constructor (empty)
Detailed Description
A mapping function propsed by Bermudez et al, appears to be the best for the Helmholtz equations and so this will be the default mapping (see definition of PmlHelmholtzEquations)
Constructor & Destructor Documentation
BermudezPMLMapping()
oomph::BermudezPMLMapping::BermudezPMLMapping () inline
Default constructor (empty)
 {};
Member Function Documentation
gamma()
std::complex<double> oomph::BermudezPMLMapping::gamma (const double & nu_i, const double & pml_width_i, const double & wavenumber_squared, const double & alpha_shift = 0.0) inline virtual
Overwrite the pure Pml mapping coefficient function to return the coeffcients proposed by Bermudez et al
return \(\gamma=1 + (1/k)(i/|outer_boundary - x|)\)
Implements oomph::PMLMapping.
     {
       return 1.0 + MathematicalConstants::I / sqrt(wavenumber_squared) *
                      (1.0 / std::fabs(pml_width_i - nu_i));
     }
References boost::multiprecision::fabs(), oomph::MathematicalConstants::I(), and sqrt().
The documentation for this class was generated from the following file:
pml_mapping_functions.h