MercuryDPM: BoundaryVTKWriter Class Reference
BoundaryVTKWriter Class Reference final
#include <BoundaryVTKWriter.h>
Public Member Functions
BoundaryVTKWriter (BoundaryHandler &boundaryHandler)
Non-default constructor; sets the handler and fileCounter.
BoundaryVTKWriter (const BoundaryVTKWriter &)=default
Default copy constructor.
void writeVTK () const override
writes a vtk file
std::string getName () const
the name of the class in the restart file
Public Member Functions inherited from BaseVTKWriter< BoundaryHandler >
BaseVTKWriter (BoundaryHandler &handler)
BaseVTKWriter (const BaseVTKWriter &other)
unsigned getFileCounter () const
void setFileCounter (unsigned fileCounter)
void setOutputDirectory (const std::string &dir)
const std::string & getOutputDirectory () const
std::string getFileName () const
Protected Member Functions
void writeVTKPoints (std::fstream &file) const
writes the point data to the vtu file (i.e. the vertices of the mesh displayed in paraview)
void writeVTKPointData (std::fstream &file) const
writes the point data to the vtu file (i.e. options how to color the boundarys displayed in paraview)
Protected Member Functions inherited from BaseVTKWriter< BoundaryHandler >
std::fstream makeVTKFileWithHeader () const
void writeVTKFooterAndClose (std::fstream &file) const
Additional Inherited Members
Protected Attributes inherited from BaseVTKWriter< BoundaryHandler >
BoundaryHandler & handler_
particle handler from which the particles should be written
unsigned int fileCounter
std::string outputDirectory_
Constructor & Destructor Documentation
BoundaryVTKWriter() [1/2]
BoundaryVTKWriter::BoundaryVTKWriter (BoundaryHandler & boundaryHandler) inline explicit
Non-default constructor; sets the handler and fileCounter.
                                                                  : BaseVTKWriter(boundaryHandler)
     {}
BoundaryVTKWriter() [2/2]
BoundaryVTKWriter::BoundaryVTKWriter (const BoundaryVTKWriter &) default
Default copy constructor.
Member Function Documentation
getName()
std::string BoundaryVTKWriter::getName () const inline
the name of the class in the restart file
     {
         return "BoundaryVTKWriter";
     }
writeVTK()
void BoundaryVTKWriter::writeVTK () const override virtual
writes a vtk file
Implements BaseVTKWriter< BoundaryHandler >.
 {
     std::fstream file = makeVTKFileWithHeader();
 //    file << "<Piece NumberOfPoints=\"" << handler_.getNumberOfObjects() << "\" NumberOfCells=\"" << 0 << "\">\n";
     for (auto p: handler_) {
         p->writeVTK(file);
     }
     writeVTKFooterAndClose(file);
 }
References BaseVTKWriter< BoundaryHandler >::handler_, BaseVTKWriter< BoundaryHandler >::makeVTKFileWithHeader(), p, and BaseVTKWriter< BoundaryHandler >::writeVTKFooterAndClose().
Referenced by DPMBase::writeVTKFiles().
writeVTKPointData()
void BoundaryVTKWriter::writeVTKPointData (std::fstream & file) const protected
writes the point data to the vtu file (i.e. options how to color the boundarys displayed in paraview)
writeVTKPoints()
void BoundaryVTKWriter::writeVTKPoints (std::fstream & file) const protected
writes the point data to the vtu file (i.e. the vertices of the mesh displayed in paraview)
The documentation for this class was generated from the following files:
BoundaryVTKWriter.h
BoundaryVTKWriter.cc