MercuryDPM: Eigen::internal::ReshapedImpl_dense< XprType, Rows, Cols, Order, false > Class Template Reference
Eigen::internal::ReshapedImpl_dense< XprType, Rows, Cols, Order, false > Class Template Reference
#include <Reshaped.h>
Public Types
typedef internal::dense_xpr_base< ReshapedType >::type Base
typedef internal::ref_selector< XprType >::non_const_type MatrixTypeNested
typedef internal::remove_all_t< XprType > NestedExpression
Public Member Functions
EIGEN_DEVICE_FUNC ReshapedImpl_dense (XprType &xpr)
EIGEN_DEVICE_FUNC ReshapedImpl_dense (XprType &xpr, Index nRows, Index nCols)
EIGEN_DEVICE_FUNC Index rows () const
EIGEN_DEVICE_FUNC Index cols () const
EIGEN_DEVICE_FUNC const internal::remove_all_t< XprType > & nestedExpression () const
EIGEN_DEVICE_FUNC std::remove_reference_t< XprType > & nestedExpression ()
Protected Attributes
MatrixTypeNested m_xpr
const internal::variable_if_dynamic< Index, Rows > m_rows
const internal::variable_if_dynamic< Index, Cols > m_cols
Private Types
typedef Reshaped< XprType, Rows, Cols, Order > ReshapedType
Detailed Description
template<typename XprType, int Rows, int Cols, int Order>
class Eigen::internal::ReshapedImpl_dense< XprType, Rows, Cols, Order, false >
Internal implementation of dense Reshaped in the general case.
Member Typedef Documentation
Base
template<typename XprType , int Rows, int Cols, int Order> typedef internal::dense_xpr_base<ReshapedType>::type Eigen::internal::ReshapedImpl_dense< XprType, Rows, Cols, Order, false >::Base
MatrixTypeNested
template<typename XprType , int Rows, int Cols, int Order> typedef internal::ref_selector<XprType>::non_const_type Eigen::internal::ReshapedImpl_dense< XprType, Rows, Cols, Order, false >::MatrixTypeNested
NestedExpression
template<typename XprType , int Rows, int Cols, int Order> typedef internal::remove_all_t<XprType> Eigen::internal::ReshapedImpl_dense< XprType, Rows, Cols, Order, false >::NestedExpression
ReshapedType
template<typename XprType , int Rows, int Cols, int Order> typedef Reshaped<XprType, Rows, Cols, Order> Eigen::internal::ReshapedImpl_dense< XprType, Rows, Cols, Order, false >::ReshapedType private
Constructor & Destructor Documentation
ReshapedImpl_dense() [1/2]
template<typename XprType , int Rows, int Cols, int Order> EIGEN_DEVICE_FUNC Eigen::internal::ReshapedImpl_dense< XprType, Rows, Cols, Order, false >::ReshapedImpl_dense (XprType & xpr) inline
Fixed-size constructor
 : m_xpr(xpr), m_rows(Rows), m_cols(Cols) {}
ReshapedImpl_dense() [2/2]
template<typename XprType , int Rows, int Cols, int Order> EIGEN_DEVICE_FUNC Eigen::internal::ReshapedImpl_dense< XprType, Rows, Cols, Order, false >::ReshapedImpl_dense (XprType & xpr, Index nRows, Index nCols) inline
Dynamic-size constructor
       : m_xpr(xpr), m_rows(nRows), m_cols(nCols) {}
Member Function Documentation
cols()
template<typename XprType , int Rows, int Cols, int Order> EIGEN_DEVICE_FUNC Index Eigen::internal::ReshapedImpl_dense< XprType, Rows, Cols, Order, false >::cols () const inline
 { return m_cols; }
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
nestedExpression() [1/2]
template<typename XprType , int Rows, int Cols, int Order> EIGEN_DEVICE_FUNC std::remove_reference_t<XprType>& Eigen::internal::ReshapedImpl_dense< XprType, Rows, Cols, Order, false >::nestedExpression () inline
Returns
the nested expression
 { return m_xpr; }
nestedExpression() [2/2]
template<typename XprType , int Rows, int Cols, int Order> EIGEN_DEVICE_FUNC const internal::remove_all_t<XprType>& Eigen::internal::ReshapedImpl_dense< XprType, Rows, Cols, Order, false >::nestedExpression () const inline
Returns
the nested expression
 { return m_xpr; }
rows()
template<typename XprType , int Rows, int Cols, int Order> EIGEN_DEVICE_FUNC Index Eigen::internal::ReshapedImpl_dense< XprType, Rows, Cols, Order, false >::rows () const inline
 { return m_rows; }
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
Member Data Documentation
m_cols
template<typename XprType , int Rows, int Cols, int Order> const internal::variable_if_dynamic<Index, Cols> Eigen::internal::ReshapedImpl_dense< XprType, Rows, Cols, Order, false >::m_cols protected
m_rows
template<typename XprType , int Rows, int Cols, int Order> const internal::variable_if_dynamic<Index, Rows> Eigen::internal::ReshapedImpl_dense< XprType, Rows, Cols, Order, false >::m_rows protected
m_xpr
template<typename XprType , int Rows, int Cols, int Order> MatrixTypeNested Eigen::internal::ReshapedImpl_dense< XprType, Rows, Cols, Order, false >::m_xpr protected
The documentation for this class was generated from the following file:
Reshaped.h