MercuryDPM: oomph::TerminateHelper Namespace Reference
oomph::TerminateHelper Namespace Reference
Functions
void setup ()
Setup terminate helper.
void suppress_exception_error_messages ()
Suppress error messages (e.g. because error has been caught)
void spawn_errors_from_uncaught_errors ()
Function to spawn messages from uncaught errors.
void clean_up_memory ()
Variables
std::ostream * Error_message_stream_pt = &std::cerr
Stream to output error messages.
std::stringstream * Exception_stringstream_pt = 0
String stream that records the error message.
Detailed Description
////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////// Helper namespace for set_terminate function – used to spawn
messages from uncaught errors
////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////// Helper namespace for set_terminate function – used to spawn
messages from uncaught errors (their destructor may not be called)
Function Documentation
clean_up_memory()
void oomph::TerminateHelper::clean_up_memory ()
Clean up function that deletes anything dynamically allocated in this namespace
     {
       // If it's a null pointer
       if (Exception_stringstream_pt != 0)
       {
         // Delete it
         delete Exception_stringstream_pt;
         // Make it a null pointer
         Exception_stringstream_pt = 0;
       }
     } // End of clean_up_memory
References Exception_stringstream_pt.
Referenced by oomph::MGSolver< DIM >::full_setup(), oomph::HelmholtzMGPreconditioner< DIM >::full_setup(), BoussinesqPreconditioner::setup(), oomph::BlockDiagonalPreconditioner< MATRIX >::setup(), oomph::BlockTriangularPreconditioner< MATRIX >::setup(), oomph::NavierStokesSchurComplementPreconditioner::setup(), oomph::ExactDGPBlockPreconditioner< MATRIX >::setup(), oomph::BandedBlockTriangularPreconditioner< MATRIX >::setup(), oomph::CG< MATRIX >::solve(), oomph::BiCGStab< MATRIX >::solve(), oomph::GS< MATRIX >::solve(), oomph::DampedJacobi< MATRIX >::solve(), oomph::GMRES< MATRIX >::solve(), BoussinesqPreconditioner::~BoussinesqPreconditioner(), SimpleLSCPreconditioner::~NavierStokesSchurComplementPreconditioner(), and oomph::Problem::~Problem().
setup()
void oomph::TerminateHelper::setup ()
Setup terminate helper.
     {
       if (Exception_stringstream_pt != 0) delete Exception_stringstream_pt;
       Exception_stringstream_pt = new std::stringstream;
       std::set_terminate(spawn_errors_from_uncaught_errors);
     }
References Exception_stringstream_pt, and spawn_errors_from_uncaught_errors().
Referenced by oomph::Problem::Problem().
spawn_errors_from_uncaught_errors()
void oomph::TerminateHelper::spawn_errors_from_uncaught_errors ()
Function to spawn messages from uncaught errors.
     {
       (*Error_message_stream_pt) << (*Exception_stringstream_pt).str();
     }
Referenced by setup().
suppress_exception_error_messages()
void oomph::TerminateHelper::suppress_exception_error_messages ()
Suppress error messages (e.g. because error has been caught)
Flush string stream of error messages (call when error has been caught)
     {
       delete Exception_stringstream_pt;
       Exception_stringstream_pt = new std::stringstream;
     }
References Exception_stringstream_pt.
Referenced by oomph::OomphLibException::disable_error_message().
Variable Documentation
Error_message_stream_pt
std::ostream * oomph::TerminateHelper::Error_message_stream_pt = &std::cerr
Stream to output error messages.
Exception_stringstream_pt
std::stringstream * oomph::TerminateHelper::Exception_stringstream_pt = 0
String stream that records the error message.
Referenced by clean_up_memory(), setup(), and suppress_exception_error_messages().