MercuryDPM: cxx11_tensor_roundings.cpp File Reference
cxx11_tensor_roundings.cpp File Reference
#include "main.h"
#include <Eigen/CXX11/Tensor>
Functions
static void test_float_rounding ()
static void test_float_flooring ()
static void test_float_ceiling ()
EIGEN_DECLARE_TEST (cxx11_tensor_roundings)
Function Documentation
EIGEN_DECLARE_TEST()
EIGEN_DECLARE_TEST (cxx11_tensor_roundings)
{
   CALL_SUBTEST(test_float_rounding());
   CALL_SUBTEST(test_float_ceiling());
   CALL_SUBTEST(test_float_flooring());
 }
References CALL_SUBTEST, test_float_ceiling(), test_float_flooring(), and test_float_rounding().
test_float_ceiling()
static void test_float_ceiling () static
{
   Tensor<float, 2> ftensor(20, 30);
   ftensor = ftensor.random() * 100.f;
   Tensor<float, 2> result = ftensor.ceil();
   for (int i = 0; i < 20; ++i) {
     for (int j = 0; j < 30; ++j) {
       VERIFY_IS_EQUAL(result(i, j), numext::ceil(ftensor(i, j)));
     }
   }
 }
References Eigen::bfloat16_impl::ceil(), i, j, and VERIFY_IS_EQUAL.
Referenced by EIGEN_DECLARE_TEST().
test_float_flooring()
static void test_float_flooring () static
{
   Tensor<float, 2> ftensor(20, 30);
   ftensor = ftensor.random() * 100.f;
   Tensor<float, 2> result = ftensor.floor();
   for (int i = 0; i < 20; ++i) {
     for (int j = 0; j < 30; ++j) {
       VERIFY_IS_EQUAL(result(i, j), numext::floor(ftensor(i, j)));
     }
   }
 }
References Eigen::bfloat16_impl::floor(), i, j, and VERIFY_IS_EQUAL.
Referenced by EIGEN_DECLARE_TEST().
test_float_rounding()
static void test_float_rounding () static
{
   Tensor<float, 2> ftensor(20, 30);
   ftensor = ftensor.random() * 100.f;
   Tensor<float, 2> result = ftensor.round();
   for (int i = 0; i < 20; ++i) {
     for (int j = 0; j < 30; ++j) {
       VERIFY_IS_EQUAL(result(i, j), numext::round(ftensor(i, j)));
     }
   }
 }
References i, j, Eigen::bfloat16_impl::round(), and VERIFY_IS_EQUAL.
Referenced by EIGEN_DECLARE_TEST().