MercuryDPM: RectangularWomersleyImpedanceTube< ELEMENT > Class Template Reference
RectangularWomersleyImpedanceTube< ELEMENT > Class Template Reference
Specific Womersley impedance tube for a rectangular cross-section.
Public Member Functions
RectangularWomersleyImpedanceTube (const double &length, typename WomersleyImpedanceTubeBase< ELEMENT, 2 >::PrescribedVolumeFluxFctPt prescribed_volume_flux_fct_pt)
Mesh * build_mesh_and_apply_boundary_conditions (TimeStepper *time_stepper_pt)
Public Member Functions inherited from oomph::WomersleyImpedanceTubeBase< ELEMENT, 2 >
WomersleyImpedanceTubeBase (const double &length, PrescribedVolumeFluxFctPt prescribed_volume_flux_fct_pt)
WomersleyImpedanceTubeBase (const double &length, Mesh *navier_stokes_outflow_mesh_pt)
double & p_out ()
Access fct to outlet pressure.
void setup ()
void setup (double *re_st_pt, const double &dt, const double &q_initial, TimeStepper *time_stepper_pt=0)
WomersleyProblem< ELEMENT, DIM > * womersley_problem_pt ()
Access to underlying Womersley problem.
void shift_time_values (const double &dt)
double total_volume_flux_into_impedance_tube ()
void get_response (double &p_in, double &dp_in_dq)
Public Member Functions inherited from oomph::TemplateFreeWomersleyImpedanceTubeBase
TemplateFreeWomersleyImpedanceTubeBase ()
Empty constructor.
virtual ~TemplateFreeWomersleyImpedanceTubeBase ()
Empty virtual destructor.
Additional Inherited Members
Public Types inherited from oomph::WomersleyImpedanceTubeBase< ELEMENT, 2 >
typedef double(* PrescribedVolumeFluxFctPt) (const double &time)
Static Public Attributes inherited from oomph::TemplateFreeWomersleyImpedanceTubeBase
static double Zero = 0.0
Zero!
Protected Member Functions inherited from oomph::WomersleyImpedanceTubeBase< ELEMENT, 2 >
void precompute_aux_integrals ()
Protected Attributes inherited from oomph::WomersleyImpedanceTubeBase< ELEMENT, 2 >
double Length
Length of the tube.
double Dp_in_dq
double * Current_volume_flux_pt
WomersleyProblem< ELEMENT, DIM > * Womersley_problem_pt
double P_out
Outlet pressure.
PrescribedVolumeFluxFctPt Prescribed_volume_flux_fct_pt
Pointer to function that specifies the prescribed volume flux.
Mesh * Navier_stokes_outflow_mesh_pt
std::map< unsigned, double > * Aux_integral_pt
Detailed Description
template<class ELEMENT>
class RectangularWomersleyImpedanceTube< ELEMENT >
Specific Womersley impedance tube for a rectangular cross-section.
////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////
Constructor & Destructor Documentation
RectangularWomersleyImpedanceTube()
template<class ELEMENT > RectangularWomersleyImpedanceTube< ELEMENT >::RectangularWomersleyImpedanceTube (const double & length, typename WomersleyImpedanceTubeBase< ELEMENT, 2 >::PrescribedVolumeFluxFctPt prescribed_volume_flux_fct_pt) inline
Constructor: Pass length and function that prescribes the volume flux to constructor of underlying base class
                                  :
   WomersleyImpedanceTubeBase<ELEMENT,2>(length, prescribed_volume_flux_fct_pt)
   {}
Member Function Documentation
build_mesh_and_apply_boundary_conditions()
template<class ELEMENT > Mesh* RectangularWomersleyImpedanceTube< ELEMENT >::build_mesh_and_apply_boundary_conditions (TimeStepper * time_stepper_pt) inline virtual
Implement pure virtual fct (defined in the base class WomersleyImpedanceTubeBase) that builds the mesh of Womersley elements (of the type specified by the template argument), using the specified timestepper. Also applies the boundary condition.
Implements oomph::WomersleyImpedanceTubeBase< ELEMENT, 2 >.
   {
    // Setup mesh
    // Number of elements in x and y directions
    unsigned nx=5;
    unsigned ny=5;
    // Lengths in x and y directions
    double lx=1.0;
    double ly=1.0;
    // Build mesh
    Mesh* my_mesh_pt =
     new RectangularQuadMesh<ELEMENT >(nx,ny,lx,ly,time_stepper_pt);
    // Set the boundary conditions for this problem:
    // All nodes are free by default -- just pin the ones that have
    // Dirichlet conditions here.
    unsigned n_bound = my_mesh_pt->nboundary();
    for(unsigned b=0;b<n_bound;b++)
     {
      unsigned n_node = my_mesh_pt->nboundary_node(b);
      for (unsigned n=0;n<n_node;n++)
       {
        my_mesh_pt->boundary_node_pt(b,n)->pin(0);
       }
     } // end of set boundary conditions
    return my_mesh_pt;
   }
References b, oomph::Mesh::boundary_node_pt(), Mesh_Parameters::lx, Mesh_Parameters::ly, n, oomph::Mesh::nboundary(), oomph::Mesh::nboundary_node(), Mesh_Parameters::nx, Mesh_Parameters::ny, and oomph::Data::pin().
The documentation for this class was generated from the following file:
two_d_womersley.cc