MercuryDPM: ChuteWithPeriodicInflow Class Reference
ChuteWithPeriodicInflow Class Reference
Particles of a single Species.
#include <ChuteWithPeriodicInflow.h>
Public Member Functions
ChuteWithPeriodicInflow (std::string restart_file)
ChuteWithPeriodicInflow (std::string restart_file, int numRepetitions)
ChuteWithPeriodicInflow (std::string restart_file, int numRepetitions, int numRepetitionsInWidth)
double getInfo (const BaseParticle &P) const override
A virtual function that returns some user-specified information about a particle.
void loadPeriodicBox (std::string const restart_file)
loads periodic chute data from restart file
void AddContinuingBottom (int numRepetitions)
void ExtendInWidth (int numRepetitionsInWidth)
void actionsBeforeTimeStep () override
Do not add, only remove particles.
void cleanChute ()
Remove particles if they fall below a certain height (allows them to become supercritical)
void setupInitialConditions () override
Do not add bottom.
void integrateBeforeForceComputation ()
Update particles' and walls' positions and velocities before force computation.
void printTime () const override
add some particular output
void computeInternalForces (BaseParticle *P1, BaseParticle *P2)
int Check_and_Duplicate_Periodic_Particle (BaseParticle *i, int nWallPeriodic)
void writeXBallsScript () const
This writes a script which can be used to load the xballs problem to display the data just generated.
void outputXBallsDataParticlee (const unsigned int i, const unsigned int format, std::ostream &os) const
double get_PeriodicBoxLength ()
void set_PeriodicBoxLength (double new_)
int get_PeriodicBoxNSpecies ()
void set_PeriodicBoxNSpecies (int new_)
bool InPeriodicBox (BaseParticle *P)
Public Member Functions inherited from Chute
Chute ()
This is the default constructor. All it does is set sensible defaults.
Chute (const DPMBase &other)
Copy constructor, converts an existing DPMBase problem into a Chute problem.
Chute (const MercuryBase &other)
Copy constructor, converts an existing MercuryBase problem into a Chute problem.
Chute (const Mercury3D &other)
Copy constructor, converts an existing Mercury3D problem into a Chute problem.
Chute (const Chute &other)
Default copy constructor.
void constructor ()
This is the actual constructor METHOD; it is called by all constructors above (except the default copy constructor).
bool readNextArgument (int &i, int argc, char *argv[]) override
This method can be used for reading object properties from a string.
void setupSideWalls ()
Creates chute side walls (either solid or periodic)
void makeChutePeriodic ()
This makes the chute periodic in Y.
bool getIsPeriodic () const
Returns whether the chute is periodic in Y.
void setupInitialConditions () override
Creates bottom, side walls and a particle insertion boundary.
void read (std::istream &is, ReadOptions opt=ReadOptions::ReadAll) override
Reads all chute properties from an istream.
void write (std::ostream &os, bool writeAllParticles=true) const override
This function writes the Chute properties to an ostream, and adds the properties of ALL chute particles as well.
void setFixedParticleRadius (Mdouble fixedParticleRadius)
Sets the particle radius of the fixed particles which constitute the (rough) chute bottom.
Mdouble getFixedParticleRadius () const
Returns the particle radius of the fixed particles which constitute the (rough) chute bottom.
void setFixedParticleSpacing (Mdouble fixedParticleSpacing)
Sets the spacing of the fixed particles which constitute the (rough) chute bottom; used in triangular packing only.
Mdouble getFixedParticleSpacing () const
Returns the particle radius of the fixed particles which constitute the (rough) chute bottom; used in triangular packing only.
void setRoughBottomType (RoughBottomType roughBottomType)
Sets the type of rough bottom of the chute.
void setRoughBottomType (std::string roughBottomTypeString)
Sets the type of rough bottom of the chute, using a string with the EXACT enum type as input.
RoughBottomType getRoughBottomType () const
Returns the type of (rough) bottom of the chute.
void setChuteAngle (Mdouble chuteAngle)
Sets gravity vector according to chute angle (in degrees)
void setChuteAngleAndMagnitudeOfGravity (Mdouble chuteAngle, Mdouble gravity)
Sets gravity vector according to chute angle (in degrees)
Mdouble getChuteAngle () const
Returns the chute angle (in radians)
Mdouble getChuteAngleDegrees () const
Returns the chute angle (in degrees)
void setMaxFailed (unsigned int maxFailed)
Sets the number of times a particle will be tried to be added to the insertion boundary.
unsigned int getMaxFailed () const
Returns the number of times a particle will be tried to be added to the insertion boundary.
void setInflowParticleRadius (Mdouble inflowParticleRadius)
Sets the radius of the inflow particles to a single one (i.e. ensures a monodisperse inflow).
void setInflowParticleRadius (Mdouble minInflowParticleRadius, Mdouble maxInflowParticleRadius)
Sets the minimum and maximum radius of the inflow particles.
void setMinInflowParticleRadius (Mdouble minInflowParticleRadius)
sets the minimum radius of inflow particles
void setMaxInflowParticleRadius (Mdouble maxInflowParticleRadius)
Sets the maximum radius of inflow particles.
Mdouble getInflowParticleRadius () const
Returns the average radius of inflow particles.
Mdouble getMinInflowParticleRadius () const
returns the minimum radius of inflow particles
Mdouble getMaxInflowParticleRadius () const
Returns the maximum radius of inflow particles.
void setInflowHeight (Mdouble inflowHeight)
Sets maximum inflow height (Z-direction)
Mdouble getInflowHeight () const
Returns the maximum inflow height (Z-direction)
void setInflowVelocity (Mdouble inflowVelocity)
Sets the average inflow velocity.
Mdouble getInflowVelocity () const
Returns the average inflow velocity.
void setInflowVelocityVariance (Mdouble inflowVelocityVariance)
Sets the inflow velocity variance.
Mdouble getInflowVelocityVariance () const
Returns the inflow velocity variance.
void setChuteWidth (Mdouble chuteWidth)
Sets the chute width (Y-direction)
Mdouble getChuteWidth () const
Returns the chute width (Y-direction)
virtual void setChuteLength (Mdouble chuteLength)
Sets the chute length (X-direction)
Mdouble getChuteLength () const
Returns the chute length (X-direction)
void setInsertionBoundary (InsertionBoundary *insertionBoundary)
Sets the chute insertion boundary.
Public Member Functions inherited from Mercury3D
Mercury3D ()
This is the default constructor. All it does is set sensible defaults.
Mercury3D (const DPMBase &other)
Copy-constructor for creates an Mercury3D problem from an existing MD problem.
Mercury3D (const Mercury3D &other)
Copy-constructor.
void constructor ()
Function that sets the SystemDimension and ParticleDimension to 3.
std::vector< BaseParticle * > hGridFindParticleContacts (const BaseParticle *obj) override
Returns all particles that have a contact with a given particle.
Public Member Functions inherited from MercuryBase
MercuryBase ()
This is the default constructor. It sets sensible defaults.
~MercuryBase () override
This is the default destructor.
MercuryBase (const MercuryBase &mercuryBase)
Copy-constructor.
void constructor ()
This is the actual constructor, it is called do both constructors above.
void hGridActionsBeforeTimeLoop () override
This sets up the broad phase information, has to be done at this stage because it requires the particle size.
void hGridActionsBeforeTimeStep () override
Performs all necessary actions before a time-step, like updating the particles and resetting all the bucket information, etc.
void read (std::istream &is, ReadOptions opt=ReadOptions::ReadAll) override
Reads the MercuryBase from an input stream, for example a restart file.
void write (std::ostream &os, bool writeAllParticles=true) const override
Writes all data into a restart file.
Mdouble getHGridCurrentMaxRelativeDisplacement () const
Returns hGridCurrentMaxRelativeDisplacement_.
Mdouble getHGridTotalCurrentMaxRelativeDisplacement () const
Returns hGridTotalCurrentMaxRelativeDisplacement_.
void setHGridUpdateEachTimeStep (bool updateEachTimeStep)
Sets whether or not the HGrid must be updated every time step.
bool getHGridUpdateEachTimeStep () const final
Gets whether or not the HGrid is updated every time step.
void setHGridMaxLevels (unsigned int HGridMaxLevels)
Sets the maximum number of levels of the HGrid in this MercuryBase.
unsigned int getHGridMaxLevels () const
Gets the maximum number of levels of the HGrid in this MercuryBase.
HGridMethod getHGridMethod () const
Gets whether the HGrid in this MercuryBase is BOTTOMUP or TOPDOWN.
void setHGridMethod (HGridMethod hGridMethod)
Sets the HGridMethod to either BOTTOMUP or TOPDOWN.
HGridDistribution getHGridDistribution () const
Gets how the sizes of the cells of different levels are distributed.
void setHGridDistribution (HGridDistribution hGridDistribution)
Sets how the sizes of the cells of different levels are distributed.
Mdouble getHGridCellOverSizeRatio () const
Gets the ratio of the smallest cell over the smallest particle.
void setHGridCellOverSizeRatio (Mdouble cellOverSizeRatio)
Sets the ratio of the smallest cell over the smallest particle.
bool hGridNeedsRebuilding ()
Gets if the HGrid needs rebuilding before anything else happens.
virtual unsigned int getHGridTargetNumberOfBuckets () const
Gets the desired number of buckets, which is the maximum of the number of particles and 10.
virtual Mdouble getHGridTargetMinInteractionRadius () const
Gets the desired size of the smallest cells of the HGrid.
virtual Mdouble getHGridTargetMaxInteractionRadius () const
Gets the desired size of the largest cells of the HGrid.
bool checkParticleForInteraction (const BaseParticle &P) final
Checks if given BaseParticle has an interaction with a BaseWall or other BaseParticle.
bool checkParticleForInteractionLocal (const BaseParticle &P) final
Checks if the given BaseParticle has an interaction with a BaseWall or other BaseParticles in a local domain.
virtual Mdouble userHGridCellSize (unsigned int level)
Virtual function that enables inheriting classes to implement a function to let the user set the cell size of the HGrid.
void hGridInfo (std::ostream &os=std::cout) const
Writes the info of the HGrid to the screen in a nice format.
Public Member Functions inherited from DPMBase
void constructor ()
A function which initialises the member variables to default values, so that the problem can be solved off the shelf; sets up a basic two dimensional problem which can be solved off the shelf. It is called in the constructor DPMBase().
DPMBase ()
Constructor that calls the "void constructor()".
DPMBase (const DPMBase &other)
Copy constructor type-2.
virtual ~DPMBase ()
virtual destructor
void autoNumber ()
The autoNumber() function calls three functions: setRunNumber(), readRunNumberFromFile() and incrementRunNumberInFile().
std::vector< int > get1DParametersFromRunNumber (int size_x) const
This turns a counter into 1 index, which is a useful feature for performing 1D parameter study. The index run from 1:size_x, while the study number starts at 0 (initially the counter=1 in COUNTER_DONOTDEL)
std::vector< int > get2DParametersFromRunNumber (int size_x, int size_y) const
This turns a counter into 2 indices which is a very useful feature for performing a 2D study. The indices run from 1:size_x and 1:size_y, while the study number starts at 0 (initially the counter=1 in COUNTER_DONOTDEL)
std::vector< int > get3DParametersFromRunNumber (int size_x, int size_y, int size_z) const
This turns a counter into 3 indices, which is a useful feature for performing a 3D parameter study. The indices run from 1:size_x, 1:size_y and 1:size_z, while the study number starts at 0 (initially the counter=1 in COUNTER_DONOTDEL)
int launchNewRun (const char *name, bool quick=false)
This launches a code from within this code. Please pass the name of the code to run.
void setRunNumber (int runNumber)
This sets the counter/Run number, overriding the defaults.
int getRunNumber () const
This returns the current value of the counter (runNumber_)
virtual void decompose ()
Sends particles from processorId to the root processor.
void solve ()
The work horse of the code.
void initialiseSolve ()
Beginning of the solve routine, before time stepping.
void finaliseSolve ()
End of the solve routine, after time stepping.
virtual void computeOneTimeStep ()
Performs everything needed for one time step, used in the time-loop of solve().
void checkSettings ()
Checks if the essentials are set properly to go ahead with solving the problem.
void forceWriteOutputFiles ()
Writes output files immediately, even if the current time step was not meant to be written. Also resets the last saved time step.
virtual void writeOutputFiles ()
Writes simulation data to all the main Mercury files: .data, .ene, .fstat, .xballs and .restart (see the Mercury website for more details regarding these files).
void solve (int argc, char *argv[])
The work horse of the code. Can handle flags from the command line.
ParticleVtkWriter * getVtkWriter () const
virtual void writeRestartFile ()
Stores all the particle data for current save time step to a "restart" file, which is a file simply intended to store all the information necessary to "restart" a simulation from a given time step (see also MercuryDPM.org for more information on restart files).
void writeDataFile ()
void writeEneFile ()
void writeFStatFile ()
void fillDomainWithParticles (unsigned N=50)
bool readRestartFile (ReadOptions opt=ReadOptions::ReadAll)
Reads all the particle data corresponding to a given, existing . restart file (for more details regarding restart files, refer to the training materials on the MercuryDPM website).Returns true if it is successful, false otherwise.
int readRestartFile (std::string fileName, ReadOptions opt=ReadOptions::ReadAll)
The same as readRestartFile(bool), but also reads all the particle data corresponding to the current saved time step.
virtual BaseWall * readUserDefinedWall (const std::string &type) const
Allows you to read in a wall defined in a Driver directory; see USER/Luca/ScrewFiller.
virtual void readOld (std::istream &is)
Reads all data from a restart file, e.g. domain data and particle data; old version.
bool readDataFile (std::string fileName="", unsigned int format=0)
This allows particle data to be reloaded from data files.
bool readParAndIniFiles (std::string fileName)
Allows the user to read par.ini files (useful to read files produced by the MDCLR simulation code - external to MercuryDPM)
bool readNextDataFile (unsigned int format=0)
Reads the next data file with default format=0. However, one can modify the format based on whether the particle data corresponds to 3D or 2D data- see Visualising data in xballs.
void readNextFStatFile ()
Reads the next fstat file.
bool findNextExistingDataFile (Mdouble tMin, bool verbose=true)
Finds and opens the next data file, if such a file exists.
bool readArguments (int argc, char *argv[])
Can interpret main function input arguments that are passed by the driver codes.
bool checkParticleForInteractionLocalPeriodic (const BaseParticle &P)
void readSpeciesFromDataFile (bool read=true)
void importParticlesAs (ParticleHandler &particleHandler, InteractionHandler &interactionHandler, const ParticleSpecies *species)
Copies particles, interactions assigning species from a local simulation to a global one. Useful for the creation of a cluster.
MERCURYDPM_DEPRECATED File & getDataFile ()
The non const version. Allows one to edit the File::dataFile.
MERCURYDPM_DEPRECATED File & getEneFile ()
The non const version. Allows to edit the File::eneFile.
MERCURYDPM_DEPRECATED File & getFStatFile ()
The non const version. Allows to edit the File::fStatFile.
MERCURYDPM_DEPRECATED File & getRestartFile ()
The non const version. Allows to edit the File::restartFile.
MERCURYDPM_DEPRECATED File & getStatFile ()
The non const version. Allows to edit the File::statFile.
File & getInteractionFile ()
Return a reference to the file InteractionsFile.
MERCURYDPM_DEPRECATED const File & getDataFile () const
The const version. Does not allow for any editing of the File::dataFile.
MERCURYDPM_DEPRECATED const File & getEneFile () const
The const version. Does not allow for any editing of the File::eneFile.
MERCURYDPM_DEPRECATED const File & getFStatFile () const
The const version. Does not allow for any editing of the File::fStatFile.
MERCURYDPM_DEPRECATED const File & getRestartFile () const
The const version. Does not allow for any editing of the File::restartFile.
MERCURYDPM_DEPRECATED const File & getStatFile () const
The const version. Does not allow for any editing of the File::statFile.
const File & getInteractionFile () const
Returns a constant reference to an Interactions file.
const std::string & getName () const
Returns the name of the file. Does not allow to change it though.
void setName (const std::string &name)
Allows to set the name of all the files (ene, data, fstat, restart, stat)
void setName (const char *name)
Calls setName(std::string)
void setSaveCount (unsigned int saveCount)
Sets File::saveCount_ for all files (ene, data, fstat, restart, stat)
void setFileType (FileType fileType)
Sets File::fileType_ for all files (ene, data, fstat, restart, stat)
void setOpenMode (std::fstream::openmode openMode)
Sets File::openMode_ for all files (ene, data, fstat, restart, stat)
void resetFileCounter ()
Resets the file counter for each file i.e. for ene, data, fstat, restart, stat)
void closeFiles ()
Closes all files (ene, data, fstat, restart, stat) that were opened to read or write.
void setVTKOutputDirectory (const std::string &dir)
Sets the output directory of the VTK files.
void setLastSavedTimeStep (unsigned int nextSavedTimeStep)
Sets the next time step for all the files (ene, data, fstat, restart, stat) at which the data is to be written or saved.
Mdouble getTime () const
Returns the current simulation time.
Mdouble getNextTime () const
Returns the current simulation time.
unsigned int getNumberOfTimeSteps () const
Returns the current counter of time-steps, i.e. the number of time-steps that the simulation has undergone so far.
void setTime (Mdouble time)
Sets a new value for the current simulation time.
void setTimeMax (Mdouble newTMax)
Sets a new value for the maximum simulation duration.
Mdouble getTimeMax () const
Returns the maximum simulation duration.
void setLogarithmicSaveCount (Mdouble logarithmicSaveCountBase)
Sets File::logarithmicSaveCount_ for all files (ene, data, fstat, restart, stat)
void setNToWrite (int nToWrite)
set the number of elements to write to the screen
int getNToWrite () const
get the number of elements to write to the
void setRotation (bool rotation)
Sets whether particle rotation is enabled or disabled.
bool getRotation () const
Indicates whether particle rotation is enabled or disabled.
MERCURYDPM_DEPRECATED void setWallsWriteVTK (FileType writeWallsVTK)
Sets whether walls are written into a VTK file.
MERCURYDPM_DEPRECATED void setWallsWriteVTK (bool)
Sets whether walls are written into a VTK file.
MERCURYDPM_DEPRECATED void setInteractionsWriteVTK (bool)
Sets whether interactions are written into a VTK file.
void setParticlesWriteVTK (bool writeParticlesVTK)
Sets whether particles are written in a VTK file.
void setSuperquadricParticlesWriteVTK (bool writeSuperquadricParticlesVTK)
MERCURYDPM_DEPRECATED FileType getWallsWriteVTK () const
Returns whether walls are written in a VTK file.
bool getParticlesWriteVTK () const
Returns whether particles are written in a VTK file.
bool getSuperquadricParticlesWriteVTK () const
Mdouble getXMin () const
If the length of the problem domain in x-direction is XMax - XMin, then getXMin() returns XMin.
Mdouble getXMax () const
If the length of the problem domain in x-direction is XMax - XMin, then getXMax() returns XMax.
Mdouble getYMin () const
If the length of the problem domain in y-direction is YMax - YMin, then getYMin() returns YMin.
Mdouble getYMax () const
If the length of the problem domain in y-direction is YMax - YMin, then getYMax() returns XMax.
Mdouble getZMin () const
If the length of the problem domain in z-direction is ZMax - ZMin, then getZMin() returns ZMin.
Mdouble getZMax () const
If the length of the problem domain in z-direction is ZMax - ZMin, then getZMax() returns ZMax.
Mdouble getXCenter () const
Mdouble getYCenter () const
Mdouble getZCenter () const
Vec3D getCenter () const
get center of domain
Vec3D getMin () const
Returns the minimum coordinates of the problem domain.
Vec3D getMax () const
Returns the maximum coordinates of the problem domain.
void setXMin (Mdouble newXMin)
Sets the value of XMin, the lower bound of the problem domain in the x-direction.
void setYMin (Mdouble newYMin)
Sets the value of YMin, the lower bound of the problem domain in the y-direction.
void setZMin (Mdouble newZMin)
Sets the value of ZMin, the lower bound of the problem domain in the z-direction.
void setXMax (Mdouble newXMax)
Sets the value of XMax, the upper bound of the problem domain in the x-direction.
void setYMax (Mdouble newYMax)
Sets the value of YMax, the upper bound of the problem domain in the y-direction.
void setZMax (Mdouble newZMax)
Sets the value of ZMax, the upper bound of the problem domain in the z-direction.
void setMax (const Vec3D &max)
Sets the maximum coordinates of the problem domain.
void setMax (Mdouble, Mdouble, Mdouble)
Sets the maximum coordinates of the problem domain.
void setDomain (const Vec3D &min, const Vec3D &max)
Sets the minimum coordinates of the problem domain.
void setMin (const Vec3D &min)
Sets the minimum coordinates of the problem domain.
void setMin (Mdouble, Mdouble, Mdouble)
Sets the minimum coordinates of the problem domain.
void setTimeStep (Mdouble newDt)
Sets a new value for the simulation time step.
Mdouble getTimeStep () const
Returns the simulation time step.
void setNumberOfOMPThreads (int numberOfOMPThreads)
Sets the number of omp threads.
int getNumberOfOMPThreads () const
Returns the number of omp threads.
void setXBallsColourMode (int newCMode)
Set the xballs output mode.
int getXBallsColourMode () const
Get the xballs colour mode (CMode).
void setXBallsVectorScale (double newVScale)
Set the scale of vectors in xballs.
double getXBallsVectorScale () const
Returns the scale of vectors used in xballs.
void setXBallsAdditionalArguments (std::string newXBArgs)
Set the additional arguments for xballs.
std::string getXBallsAdditionalArguments () const
Returns the additional arguments for xballs.
void setXBallsScale (Mdouble newScale)
Sets the scale of the view (either normal, zoom in or zoom out) to display in xballs. The default is fit to screen.
double getXBallsScale () const
Returns the scale of the view in xballs.
void setGravity (Vec3D newGravity)
Sets a new value for the gravitational acceleration.
Vec3D getGravity () const
Returns the gravitational acceleration.
void setBackgroundDrag (Mdouble backgroundDrag)
Simple access function to turn on a background drag. The force of particleVelocity*drag is applied (note, it allowed to be negative i.e. create energy)
const Mdouble getBackgroundDrag () const
Return the background drag.
void setDimension (unsigned int newDim)
Sets both the system dimensions and the particle dimensionality.
void setSystemDimensions (unsigned int newDim)
Sets the system dimensionality.
unsigned int getSystemDimensions () const
Returns the system dimensionality.
void setParticleDimensions (unsigned int particleDimensions)
Sets the particle dimensionality.
unsigned int getParticleDimensions () const
Returns the particle dimensionality.
std::string getRestartVersion () const
This is to take into account for different Mercury versions. Returns the version of the restart file.
void setRestartVersion (std::string newRV)
Sets restart_version.
bool getRestarted () const
Returns the flag denoting if the simulation was restarted or not.
void setRestarted (bool newRestartedFlag)
Allows to set the flag stating if the simulation is to be restarted or not.
bool getAppend () const
Returns whether the "append" option is on or off.
void setAppend (bool newAppendFlag)
Sets whether the "append" option is on or off.
Mdouble getElasticEnergy () const
Returns the global elastic energy within the system.
Mdouble getKineticEnergy () const
Returns the global kinetic energy stored in the system.
Mdouble getGravitationalEnergy (Vec3D origin={0, 0, 0}) const
Returns the global gravitational potential energy stored relative to a user-defined origin in the system. Note, if no origin is specified the real origin i.e. (0,0,0) is taken.
Mdouble getRotationalEnergy () const
Returns the global rotational energy stored in the system.
Mdouble getTotalEnergy () const
Mdouble getTotalMass () const
JMFT: Return the total mass of the system, excluding fixed particles.
Vec3D getCentreOfMass () const
JMFT: Return the centre of mass of the system, excluding fixed particles.
Vec3D getTotalMomentum () const
JMFT: Return the total momentum of the system, excluding fixed particles.
double getCPUTime ()
double getWallTime ()
virtual void hGridInsertParticle (BaseParticle *obj UNUSED)
virtual void hGridUpdateParticle (BaseParticle *obj UNUSED)
virtual void hGridRemoveParticle (BaseParticle *obj UNUSED)
bool mpiIsInCommunicationZone (BaseParticle *particle)
Checks if the position of the particle is in an mpi communication zone or not.
bool mpiInsertParticleCheck (BaseParticle *P)
Function that checks if the mpi particle should really be inserted by the current domain.
void insertGhostParticle (BaseParticle *P)
This function inserts a particle in the mpi communication boundaries.
void updateGhostGrid (BaseParticle *P)
Checks if the Domain/periodic interaction distance needs to be updated and updates it accordingly.
virtual void gatherContactStatistics (unsigned int index1, int index2, Vec3D Contact, Mdouble delta, Mdouble ctheta, Mdouble fdotn, Mdouble fdott, Vec3D P1_P2_normal_, Vec3D P1_P2_tangential)
//Not unsigned index because of possible wall collisions.
void setNumberOfDomains (std::vector< unsigned > direction)
Sets the number of domains in x-,y- and z-direction. Required for parallel computations.
void splitDomain (DomainSplit domainSplit)
std::vector< unsigned > getNumberOfDomains ()
returns the number of domains
Domain * getCurrentDomain ()
Function that returns a pointer to the domain corresponding to the processor.
void removeOldFiles () const
void setMeanVelocity (Vec3D V_mean_goal)
This function will help you set a fixed kinetic energy and mean velocity in your system.
void setMeanVelocityAndKineticEnergy (Vec3D V_mean_goal, Mdouble Ek_goal)
This function will help you set a fixed kinetic energy and mean velocity in your system.
Mdouble getTotalVolume () const
Get the total volume of the cuboid system.
Matrix3D getKineticStress () const
Calculate the kinetic stress tensor in the system averaged over the whole volume.
Matrix3D getStaticStress () const
Calculate the static stress tensor in the system averaged over the whole volume.
Matrix3D getTotalStress () const
Calculate the total stress tensor in the system averaged over the whole volume.
virtual void handleParticleRemoval (unsigned int id)
Handles the removal of particles from the particleHandler.
virtual void handleParticleAddition (unsigned int id, BaseParticle *p)
Handles the addition of particles to the particleHandler.
void writePythonFileForVTKVisualisation () const
writes .py file for ParaView
void setWritePythonFileForVTKVisualisation (bool forceWritePythonFileForVTKVisualisation)
bool getWritePythonFileForVTKVisualisation () const
WallVTKWriter & getWallVTKWriter ()
Public Attributes
SphericalParticle inflowParticle_
Public Attributes inherited from DPMBase
SpeciesHandler speciesHandler
A handler to that stores the species type i.e. LinearViscoelasticSpecies, etc.
RNG random
This is a random generator, often used for setting up the initial conditions etc...
ParticleHandler particleHandler
An object of the class ParticleHandler, contains the pointers to all the particles created.
ParticleHandler paoloParticleHandler
Fake particleHandler created by Paolo needed temporary by just Paolo.
WallHandler wallHandler
An object of the class WallHandler. Contains pointers to all the walls created.
BoundaryHandler boundaryHandler
An object of the class BoundaryHandler which concerns insertion and deletion of particles into or from regions.
PeriodicBoundaryHandler periodicBoundaryHandler
Internal handler that deals with periodic boundaries, especially in a parallel build.
DomainHandler domainHandler
An object of the class DomainHandler which deals with parallel code.
InteractionHandler interactionHandler
An object of the class InteractionHandler.
CGHandler cgHandler
Object of the class cgHandler.
File dataFile
An instance of class File to handle in- and output into a .data file.
File fStatFile
An instance of class File to handle in- and output into a .fstat file.
File eneFile
An instance of class File to handle in- and output into a .ene file.
File restartFile
An instance of class File to handle in- and output into a .restart file.
File statFile
An instance of class File to handle in- and output into a .stat file.
File interactionFile
File class to handle in- and output into .interactions file. This file hold information about interactions.
Time clock_
record when the simulation started
Private Attributes
double PeriodicBoxLength
stores the length of the periodic box
int PeriodicBoxNSpecies
stores the number of species in the periodic box
bool FillChute
Additional Inherited Members
Public Types inherited from DPMBase
enum class ReadOptions : int { ReadAll , ReadNoInteractions , ReadNoParticlesAndInteractions }
enum class DomainSplit {
X , Y , Z , XY ,
XZ , YZ , XYZ
}
Static Public Member Functions inherited from DPMBase
static void incrementRunNumberInFile ()
Increment the run Number (counter value) stored in the file_counter (COUNTER_DONOTDEL) by 1 and store the new value in the counter file.
static int readRunNumberFromFile ()
Read the run number or the counter from the counter file (COUNTER_DONOTDEL)
static bool areInContact (const BaseParticle *pI, const BaseParticle *pJ)
Checks if two particle are in contact or is there any positive overlap.
Protected Member Functions inherited from Chute
void actionsBeforeTimeStep () override
Calls Chute::cleanChute().
void cleanChute ()
Deletes all outflow particles once every 100 time steps.
virtual void createBottom ()
Creates the chute bottom, which can be either flat or one of three flavours of rough.
virtual void addFlowParticlesCompactly ()
Add initial flow particles in a dense packing.
virtual SphericalParticle createFlowParticle ()
void printTime () const override
prints time, max time and number of particles
Protected Member Functions inherited from Mercury3D
void hGridFindContactsWithinTargetCell (int x, int y, int z, unsigned int l)
Finds contacts between particles in the target cell.
void hGridFindContactsWithTargetCell (int x, int y, int z, unsigned int l, BaseParticle *obj)
Finds contacts between the BaseParticle and the target cell.
void computeWallForces (BaseWall *w) override
Compute contacts with a wall.
void hGridFindParticlesWithTargetCell (int x, int y, int z, unsigned int l, BaseParticle *obj, std::vector< BaseParticle * > &list)
Finds particles within target cell and stores them in a list.
void hGridGetInteractingParticleList (BaseParticle *obj, std::vector< BaseParticle * > &list) override
Obtains all neighbour particles of a given object, obtained from the hgrid.
void computeInternalForces (BaseParticle *obj) override
Finds contacts with the BaseParticle; avoids multiple checks.
bool hGridHasContactsInTargetCell (int x, int y, int z, unsigned int l, const BaseParticle *obj) const
Tests if the BaseParticle has contacts with other Particles in the target cell.
bool hGridHasParticleContacts (const BaseParticle *obj) override
Tests if a BaseParticle has any contacts in the HGrid.
void hGridRemoveParticle (BaseParticle *obj) override
Removes a BaseParticle from the HGrid.
void hGridUpdateParticle (BaseParticle *obj) override
Updates the cell (not the level) of a BaseParticle.
Protected Member Functions inherited from MercuryBase
void hGridRebuild ()
This sets up the parameters required for the contact model.
void hGridInsertParticle (BaseParticle *obj) final
Inserts a single Particle to current grid.
void hGridUpdateMove (BaseParticle *iP, Mdouble move) final
Computes the relative displacement of the given BaseParticle and updates the currentMaxRelativeDisplacement_ accordingly.
void hGridActionsBeforeIntegration () override
Resets the currentMaxRelativeDisplacement_ to 0.
void hGridActionsAfterIntegration () override
This function has to be called before integrateBeforeForceComputation.
HGrid * getHGrid ()
Gets the HGrid used by this problem.
const HGrid * getHGrid () const
Gets the HGrid used by this problem, const version.
bool readNextArgument (int &i, int argc, char *argv[]) override
Reads the next command line argument.
Protected Member Functions inherited from DPMBase
virtual void computeAllForces ()
Computes all the forces acting on the particles using the BaseInteractable::setForce() and BaseInteractable::setTorque()
virtual void computeInternalForce (BaseParticle *, BaseParticle *)
Computes the forces between two particles (internal in the sense that the sum over all these forces is zero i.e. fully modelled forces)
virtual void computeExternalForces (BaseParticle *)
Computes the external forces, such as gravity, acting on particles.
virtual void computeForcesDueToWalls (BaseParticle *, BaseWall *)
Computes the forces on the particles due to the walls (normals are outward normals)
virtual void actionsOnRestart ()
A virtual function where the users can add extra code which is executed only when the code is restarted.
virtual void actionsBeforeTimeLoop ()
A virtual function. Allows one to carry out any operations before the start of the time loop.
virtual void computeAdditionalForces ()
A virtual function which allows to define operations to be executed prior to the OMP force collect.
virtual void actionsAfterSolve ()
A virtual function which allows to define operations to be executed after the solve().
virtual void actionsAfterTimeStep ()
A virtual function which allows to define operations to be executed after time step.
void writeVTKFiles () const
virtual void outputXBallsData (std::ostream &os) const
This function writes the location of the walls and particles in a format the XBalls program can read. For more information on the XBalls program, see Visualising data in xballs.
virtual void outputXBallsDataParticle (unsigned int i, unsigned int format, std::ostream &os) const
This function writes out the particle locations into an output stream in a format the XBalls program can read. For more information on the XBalls program, see Visualising data in xballs.
virtual void writeEneHeader (std::ostream &os) const
Writes a header with a certain format for ENE file.
virtual void writeFstatHeader (std::ostream &os) const
Writes a header with a certain format for FStat file.
virtual void writeEneTimeStep (std::ostream &os) const
Write the global kinetic, potential energy, etc. in the system.
virtual void initialiseStatistics ()
virtual void outputStatistics ()
void gatherContactStatistics ()
virtual void processStatistics (bool)
virtual void finishStatistics ()
virtual void integrateAfterForceComputation ()
Update particles' and walls' positions and velocities after force computation.
virtual void checkInteractionWithBoundaries ()
There are a range of boundaries one could implement depending on ones' problem. This methods checks for interactions between particles and such range of boundaries. See BaseBoundary.h and all the boundaries in the Boundaries folder.
void setFixedParticles (unsigned int n)
Sets a number, n, of particles in the particleHandler as "fixed particles".
virtual bool continueSolve () const
A virtual function for deciding whether to continue the simulation, based on a user-specified criterion.
void outputInteractionDetails () const
Displays the interaction details corresponding to the pointer objects in the interaction handler.
bool isTimeEqualTo (Mdouble time) const
Checks whether the input variable "time" is the current time in the simulation.
void removeDuplicatePeriodicParticles ()
Removes periodic duplicate Particles.
void checkAndDuplicatePeriodicParticles ()
For simulations using periodic boundaries, checks and adds particles when necessary into the particle handler. See DPMBase.cc and PeriodicBoundary.cc for more details.
void performGhostParticleUpdate ()
When the Verlet scheme updates the positions and velocities of particles, ghost particles will need an update as wel. Their status will also be updated accordingly.
void deleteGhostParticles (std::set< BaseParticle * > &particlesToBeDeleted)
void synchroniseParticle (BaseParticle *, unsigned fromProcessor=0)
void performGhostVelocityUpdate ()
updates the final time-step velocity of the ghost particles
void disableSoftStop ()
This prevents the initialisation of the soft stop feature.
void discontinueSolve ()
This discontinues the solve loop after the current time step is finished.
Detailed Description
Particles of a single Species.
Constructor & Destructor Documentation
ChuteWithPeriodicInflow() [1/3]
ChuteWithPeriodicInflow::ChuteWithPeriodicInflow (std::string restart_file) inline
     {
         loadPeriodicBox(restart_file);
     }
References loadPeriodicBox().
ChuteWithPeriodicInflow() [2/3]
ChuteWithPeriodicInflow::ChuteWithPeriodicInflow (std::string restart_file, int numRepetitions) inline
     {
         loadPeriodicBox(restart_file);
         AddContinuingBottom(numRepetitions);
     }
References AddContinuingBottom(), and loadPeriodicBox().
ChuteWithPeriodicInflow() [3/3]
ChuteWithPeriodicInflow::ChuteWithPeriodicInflow (std::string restart_file, int numRepetitions, int numRepetitionsInWidth) inline
     {
         loadPeriodicBox(restart_file);
         AddContinuingBottom(numRepetitions);
         ExtendInWidth(numRepetitionsInWidth);
     }
References AddContinuingBottom(), ExtendInWidth(), and loadPeriodicBox().
Member Function Documentation
actionsBeforeTimeStep()
void ChuteWithPeriodicInflow::actionsBeforeTimeStep () inline override virtual
Do not add, only remove particles.
Reimplemented from DPMBase.
     {
         cleanChute();
     }
References cleanChute().
AddContinuingBottom()
void ChuteWithPeriodicInflow::AddContinuingBottom (int numRepetitions) inline
     {
         // creates bottom outside periodic chute of species 1
         double lengthPeriodicChute = getXMax();
         int N = particleHandler.getNumberOfObjects();
         particleHandler.setStorageCapacity(N * (2. + numRepetitions));
         //allows for a gap between the infow and flow regimes
         double Gap = 0.;
         for (int j = 1; j < numRepetitions; j++)
         {
             for (int i = 0; i < N; i++)
             {
                 if (particleHandler.getObject(i)->isFixed() | FillChute)
                 {
                     particleHandler.addObject(particleHandler.getObject(i)->copy());
                     particleHandler.getLastObject()->setSpecies(speciesHandler.getObject(1));
                     particleHandler.getLastObject()->move(Vec3D(Gap + lengthPeriodicChute * j, 0., 0.));
                 }
             }
         }
         setXMax(numRepetitions * lengthPeriodicChute);
         //setHGridNumberOfBucketsToPower(particleHandler.getStorageCapacity());
     }
References ParticleHandler::addObject(), BaseParticle::copy(), FillChute, BaseHandler< T >::getLastObject(), ParticleHandler::getNumberOfObjects(), BaseHandler< T >::getObject(), DPMBase::getXMax(), i, BaseParticle::isFixed(), j, BaseInteractable::move(), N, DPMBase::particleHandler, BaseParticle::setSpecies(), BaseHandler< T >::setStorageCapacity(), DPMBase::setXMax(), and DPMBase::speciesHandler.
Referenced by ChuteWithPeriodicInflow().
Check_and_Duplicate_Periodic_Particle()
int ChuteWithPeriodicInflow::Check_and_Duplicate_Periodic_Particle (BaseParticle * i, int nWallPeriodic) inline
assumes first periodic wall is in x direction
     {
         int C = 0; //Number of particles created
         for (int k = nWallPeriodic; k < getIsPeriodic(); k++)
         { //Loop over all still posible walls
             PeriodicBoundary* perw = static_cast<PeriodicBoundary*>(boundaryHandler.getObject(k));
             if ((k ? true : InPeriodicBox(i)) && (perw->getDistance(*i) < i->getRadius() + getMaxInflowParticleRadius()))
             {
                 SphericalParticle F0 = *i;
                 perw->shiftPosition(i);
                 //If Particle is Mdouble shifted, get correct original particle
                 BaseParticle* From = i;
                 while (From->getPeriodicFromParticle() != NULL)
                     From = From->getPeriodicFromParticle();
                 F0.setPeriodicFromParticle(From);
                 particleHandler.copyAndAddObject(F0);
                 C++;
                 //Check for Mdouble shifted particles
                 C += Check_and_Duplicate_Periodic_Particle(particleHandler.getLastObject(), k + 1);
             }
         }
         return (C);
     }
References DPMBase::boundaryHandler, BaseHandler< T >::copyAndAddObject(), PeriodicBoundary::getDistance(), Chute::getIsPeriodic(), BaseHandler< T >::getLastObject(), Chute::getMaxInflowParticleRadius(), BaseHandler< T >::getObject(), BaseParticle::getPeriodicFromParticle(), i, InPeriodicBox(), k, DPMBase::particleHandler, BaseParticle::setPeriodicFromParticle(), and PeriodicBoundary::shiftPosition().
cleanChute()
void ChuteWithPeriodicInflow::cleanChute () inline
Remove particles if they fall below a certain height (allows them to become supercritical)
     {
         //clean outflow every 100 time steps
         static int count = 0, maxcount = 100;
         if (count > maxcount)
         {
             count = 0;
             // delete all outflowing particles
             for (unsigned int i = 0; i < particleHandler.getNumberOfObjects();)
             {
                 //~ if (particleHandler.getObject(i)->getPosition().Z<getZMin()-10*getInflowParticleRadius()){
                 if (particleHandler.getObject(i)->getPosition().X > getXMax())
                 {
                     //~ cout << "Remove particle" << endl;
                     particleHandler.removeObject(i);
                 }
                 else
                     i++;
             }
         }
         else
             count++;
     }
References ParticleHandler::getNumberOfObjects(), BaseHandler< T >::getObject(), BaseInteractable::getPosition(), DPMBase::getXMax(), i, DPMBase::particleHandler, ParticleHandler::removeObject(), and Vec3D::X.
Referenced by actionsBeforeTimeStep().
computeInternalForces()
void ChuteWithPeriodicInflow::computeInternalForces (BaseParticle * P1, BaseParticle * P2) inline
Tangential spring information is always store in the real particle with highest index When a Periodic contact is encountered it is always encoutered twice (for normal periodic walls), but the force is only applied to the real particle The tangential spring information for periodic particles is stored in the normal particle (and thus twice for normal periodic interactions) When a Particle is removed the tangential spring information has to be moved
Both options are up to first order the same (the first one is nicer becaus it always keeps the spring tangential, whereas the second one is in a nicer intergration form)
Todo:
{The spring should be cut back such that fdott=mu*fdotn. This is simple for getSlidingDissipation()=0; we have to think about what happens in the sliding case with tang. dissipation; same for walls; Update Dec-2-2011: fixed}
Todo:
TW: the following 13 lines concern only the sliding spring and could be moved into the if statement above
Todo:
Define the center this way or are radii involved? Or maybe just use middle of overlap region? Thomas: Yes, we should correct that for polydispersed problems; however, then we also have to correct it in StatisticsVector::gatherContactStatistics.
The second particle (i.e. the particle the force acts on) is always a flow particle
Todo:
{Is it the first particle the force acts on?}
     {
 <<<<<<< .mine
         // For particles of the same species, set species vector to Species(PI);
         // for particles of different species, set species vector to MixedSpecies(PI,PJ)
         BaseSpecies* pSpecies = (PI->getIndSpecies() == PJ->getIndSpecies()) ? &Species[PI->getIndSpecies()] : speciesHandler.getMixedObject(PI->getIndSpecies(), PJ->getIndSpecies());
 =======
         //this is because the rough bottom allows overlapping fixed particles
         if (P1->isFixed() && P2->isFixed())
             return;
 >>>>>>> .r824
         //Dificult cases for tangential springs in comination with periodic walls are:
         //
         // A new contact over a periodic wall:
         // Starting situation: There are no tangential springs stored at all
         // Creating periodic particles: There are no tangential springs so nothing happens
         // Contact detection: There are two contacts detected, one (CA) for P1 with P2per and one (CB) for P2 with P1per
         // Switch to the 4 cases:
         //   CA: PI=P1, PJ=P2per PJreal=P2
         //   CB: PI=P2, PJ=P1per PJreal=P1
         // Reconnecting springs:
         //   CA: PI=P1 and PJ=P2per do not have a spring, so a new spring is created in either PI or PJ (could be in periodic particle)
         //   CB: PI=P2 and PJ=P1Per do not have a spring, so a new spring is created in either PI or PJ (could be in periodic particle)
         // Removing periodic particles: One of the springs will be stored in a periodic particle and thus removed, the other spring is kept and used (this is the real particle with the kighest index)
         // Reconnect to a contact over a periodic wall:
         // Starting situation: There is a tangential spring stored in the particle with the highest index, lets assume this is P1
         // Creating periodic particles: P1 has a tangential spring, so P1per has a reversed copy of this spring
         // Contact detection: There are two contacts detected, one (CA) for P1 with P2per and one (CB) for P2 with P1per
         // Switch to the 4 cases:
         //   CA: PI=P1, PJ=P2per PJreal=P2
         //   CB: PI=P2, PJ=P1per PJreal=P1
         // Reconnecting springs:
         //   CA: PI=P1 and PJ=P2per have a spring in P1, so we reconnect to this spring in the normal way and integrate it.
         //   CB: PI=P2 and PJ=P1Per have a spring in P1per, however this spring has to be a reversed spring since it is in PJ.
         // Removing periodic particles: The spring in P1per is removed
         //Cases (start from P1 and P2 and go to PI and PJ
         //1 Normal-Normal       ->PI=max(P1,P2), PJ=min(P1,P2)
         //2 Periodic-Normal     ->(PI=P2 PJ=real(P1))
         //3 Normal-Periodic     ->(PI=P1 PJ=real(P2))
         //4 Periodic-Periodic   ->do nothing
         //Just some statements to handle the 4 cases
         BaseParticle *PI, *PJ, *PJreal;
         bool isPeriodic;
         BaseParticle *P1Per = P1->getPeriodicFromParticle();
         BaseParticle *P2Per = P2->getPeriodicFromParticle();
         if (P1Per == NULL)
         {
             if (P2Per == NULL) //N-N
                 if (P1->getIndex() < P2->getIndex())
                 {
                     PI = P2;
                     PJ = P1;
                     PJreal = P1;
                     isPeriodic = false;
                 }
                 else
                 {
                     PI = P1;
                     PJ = P2;
                     PJreal = P2;
                     isPeriodic = false;
                 }
             else //N-P
             {
                 PI = P1;
                 PJ = P2;
                 PJreal = P2Per;
                 isPeriodic = true;
             }
         }
         else
         {
             if (P2Per == NULL) //P-N
             {
                 PI = P2;
                 PJ = P1;
                 PJreal = P1Per;
                 isPeriodic = true;
             }
             else
                 return;
         }
 #ifdef DEBUG_OUTPUT
         std::cerr << "In computing internal forces between particle "<<PI->getPosition()<<" and "<<PJ->getPosition()<<std::endl;
 #endif
         //Get the square of the distance between particle i and particle j
         Mdouble dist_squared = Vec3D::getDistanceSquared(PI->getPosition(), PJ->getPosition());
         Mdouble interactionRadii_sum = PI->getInteractionRadius() + PJ->getInteractionRadius();
 #ifdef DEBUG_OUTPUT_FULL
         std::cerr << "Square of distance between " << dist_squared << " square sum of radii " << radii_sum*radii_sum <<std::endl;
 #endif
         // True if the particles are in contact
         if (dist_squared < (interactionRadii_sum * interactionRadii_sum))
         {
             // For particles of the same species, set species vector to Species(PI);
             // for particles of different species, set species vector to MixedSpecies(PI,PJ)
             CSpecies* pSpecies = (PI->getIndSpecies() == PJ->getIndSpecies()) ? &Species[PI->getIndSpecies()] : getMixedSpecies(PI->getIndSpecies(), PJ->getIndSpecies());
             // Calculate distance between the particles
             Mdouble dist = sqrt(dist_squared);
             // Compute normal vector
             Vec3D normal = (PI->getPosition() - PJ->getPosition()) / dist;
             // Compute the overlap between the particles
             Mdouble radii_sum = PI->getRadius() + PJ->getRadius();
             Mdouble deltan = std::max(0.0, radii_sum - dist);
             Vec3D force = Vec3D(0, 0, 0);
             ;
             Vec3D forcet;
             forcet.setZero();
             Vec3D forcerolling;
             forcerolling.setZero();
             Vec3D forcetorsion;
             forcetorsion.setZero();
             Mdouble fdotn = 0;
             CTangentialSpring* TangentialSpring = NULL;
             //evaluate shortrange non-contact forces
             if (pSpecies->getAdhesionForceType() != AdhesionForceType::NONE)
                 fdotn += computeShortRangeForceWithParticle(PI, PJ, PJreal, pSpecies, dist);
             if (deltan > 0) //if contact forces
             {
                 // Compute the relative velocity vector v_ij
                 Vec3D vrel;
                 if (!pSpecies->getSlidingFrictionCoefficient())
                 {
                     vrel = (PI->getVelocity() - PJ->getVelocity());
                 }
                 else
                 {
                     vrel = (PI->getVelocity() - PJ->getVelocity()) + Vec3D::cross(normal, PI->getAngularVelocity() * (PI->getRadius() - .5 * deltan) + PJ->getAngularVelocity() * (PJ->getRadius() - .5 * deltan));
                 }
                 // Compute the projection of vrel onto the normal (can be negative)
                 Mdouble vdotn = -Vec3D::dot(vrel, normal);
                 //update restitution coeff
                 if (pSpecies->getIsRestitutionCoefficientConstant())
                     pSpecies->updateDissipation(PI->getMass(), PJ->getMass());
                 Mdouble a = 0, R = 0;
                 // Compute normal force on particle i due to contact
                 if (pSpecies->getForceType() == ForceType::HERTZ_MINDLIN || pSpecies->getForceType() == ForceType::HERTZ_MINDLIN_DERESIEWICZ)
                 {
                     //R is twice the effective radius
                     R = 2.0 * PI->getRadius() * PJ->getRadius() / (PI->getRadius() + PJ->getRadius());
                     a = sqrt(R * deltan);
                     //pSpecies->getStiffness() stores the elastic modulus
                     Mdouble kn = 4. / 3. * pSpecies->getStiffness() * a;
                     fdotn += kn * deltan + pSpecies->getDissipation() * vdotn;
                 }
                 else
                 {
                     fdotn += pSpecies->getStiffness() * deltan + pSpecies->getDissipation() * vdotn;
                 }
                 force += normal * fdotn;
                 //If tangential forces are present
                 if (pSpecies->getSlidingFrictionCoefficient() || pSpecies->getRollingFrictionCoefficient() || pSpecies->getTorsionFrictionCoefficient())
                 {
                     //call tangential spring
                     if (pSpecies->getSlidingStiffness() || pSpecies->getRollingStiffness() || pSpecies->getTorsionStiffness())
                         TangentialSpring = getTangentialSpring(PI, PJ, PJreal);
                     //Compute norm of normal force
                     Mdouble norm_fn = fabs(fdotn);
                     //calculate sliding friction
                     if (pSpecies->getSlidingFrictionCoefficient())
                     {
                         //Compute the tangential component of vrel
                         Vec3D vrelt = vrel + normal * vdotn;
                         //Compute norm of vrelt
                         Mdouble vdott = vrelt.getLength();
                         if (pSpecies->getSlidingStiffness())
{
                             Vec3D* delta = &(TangentialSpring->delta);
                             //Integrate the spring
                             //(*delta) += vrelt * dt - Vec3D::Dot(*delta,normal)*normal;
                             Vec3D ddelta = (vrelt - Vec3D::dot(*delta, PI->getVelocity() - PJ->getVelocity()) * normal / dist) * getTimeStep();
                             (*delta) += ddelta;
                             //Calculate test force including viscous force
                             if (pSpecies->getForceType() == ForceType::HERTZ_MINDLIN)
{
                                 //pSpecies->getSlidingStiffness() stores the elastic shear modulus
                                 Mdouble kt = 8. * pSpecies->getSlidingStiffness() * a;
                                 TangentialSpring->SlidingForce += -kt * ddelta;
                                 forcet = TangentialSpring->SlidingForce - pSpecies->getSlidingDissipation() * vrelt;
                             }
                             else if (pSpecies->getForceType() == ForceType::HERTZ_MINDLIN_DERESIEWICZ)
{
                                 //pSpecies->getSlidingStiffness() stores the elastic shear modulus
                                 forcet = TangentialSpring->SlidingForce - pSpecies->getSlidingDissipation() * vrelt;
                                 Mdouble kt = 8. * pSpecies->getSlidingStiffness() * a * std::pow(1 - Vec3D::getLength(forcet) / pSpecies->getSlidingFrictionCoefficient() / fdotn, 0.33);
                                 TangentialSpring->SlidingForce += -kt * ddelta;
                                 forcet = TangentialSpring->SlidingForce - pSpecies->getSlidingDissipation() * vrelt;
                             }
                             else
{
                                 forcet = (-pSpecies->getSlidingDissipation()) * vrelt - pSpecies->getSlidingStiffness() * (*delta);
                             }
                             Mdouble forcet2 = forcet.getLengthSquared();
                             //tangential forces are modelled by a spring-damper of elastisity kt and viscosity getSlidingDissipation() (sticking),
                             //but the force is limited by Coulomb friction (sliding):
                             //f_t = -getSlidingDissipation()*vrelt, if getSlidingDissipation()*vrelt<=mu_s*fdotn, f_t=mu+s*fdotn*t, else
                             double muact = (TangentialSpring->sliding) ? (pSpecies->getSlidingFrictionCoefficient()) : (pSpecies->getSlidingFrictionCoefficientStatic()); // select mu from previous sliding mode
                             if (forcet2 <= mathsFunc::square(muact * norm_fn))
{
                                 //sticking++;
                                 TangentialSpring->sliding = false;
                             }
                             else
{
                                 //sliding++;
                                 TangentialSpring->sliding = true;
                                 Mdouble norm_forcet = sqrt(forcet2);
                                 forcet *= pSpecies->getSlidingFrictionCoefficient() * norm_fn / norm_forcet;
                                 TangentialSpring->SlidingForce = forcet + pSpecies->getSlidingDissipation() * vrelt;
                                 (*delta) = TangentialSpring->SlidingForce / (-pSpecies->getSlidingStiffness());
                             }
                             //Add tangential force to total force
                             force += forcet;
                         }
                         else
                         { //if no tangential spring
                           //tangential forces are modelled by a damper of viscosity getSlidingDissipation() (sticking),
                           //but the force is limited by Coulomb friction (sliding):
                           //f_t = -getSlidingDissipation()*vrelt, if getSlidingDissipation()*vrelt<=mu_s*fdotn, f_t=mu+s*fdotn*t, else
                             if (vdott * pSpecies->getSlidingDissipation() <= pSpecies->getSlidingFrictionCoefficientStatic() * norm_fn)
                             { //sticking++;
                                 forcet = -pSpecies->getSlidingDissipation() * vrelt;
                             }
                             else
                             { //sliding++;
                               //set force to Coulomb limit
                                 forcet = -(pSpecies->getSlidingFrictionCoefficient() * norm_fn / vdott) * vrelt;
                             }
                             //Add tangential force to total force
                             force += forcet;
                         }
                     }
                     //calculate rolling friction
                     if (pSpecies->getRollingFrictionCoefficient())
                     {
                         //From Luding2008, objective rolling velocity (eq 15) w/o 2.0!
                         Mdouble reducedRadiusI = PI->getRadius() - .5 * deltan;
                         Mdouble reducedRadiusJ = PJ->getRadius() - .5 * deltan;
                         Mdouble reducedRadiusIJ = 2.0 * reducedRadiusI * reducedRadiusJ / (reducedRadiusI + reducedRadiusJ);
                         Vec3D vrolling = -reducedRadiusIJ * Vec3D::cross(normal, PI->getAngularVelocity() - PJ->getAngularVelocity());
                         if (pSpecies->getRollingStiffness())
{
                             Vec3D* RollingSpring = &(TangentialSpring->RollingSpring);
                             //Integrate the spring
                             (*RollingSpring) += vrolling * getTimeStep(); // - Vec3D::Dot(*RollingSpring,normal)*normal;
                                     //Calculate test force including viscous force
                             forcerolling = (-pSpecies->getRollingDissipation()) * vrolling - pSpecies->getRollingStiffness() * (*RollingSpring);
                             Mdouble forcerolling2 = forcerolling.getLengthSquared();
                             //tangential forces are modelled by a spring-damper of elastisity kt and viscosity getSlidingDissipation() (sticking),
                             //but the force is limited by Coulomb friction (sliding):
                             //f_t = -getSlidingDissipation()*vrelt, if getSlidingDissipation()*vrelt<=mu_s*fdotn, f_t=mu+s*fdotn*t, else
                             double muact = (TangentialSpring->slidingRolling) ? (pSpecies->getRollingFrictionCoefficient()) : (pSpecies->getRollingFrictionCoefficientStatic()); // select mu from previous sliding mode
                             if (forcerolling2 <= mathsFunc::square(muact * norm_fn))
{
                                 //sticking++;
                                 TangentialSpring->slidingRolling = false;
                             }
                             else
{
                                 //sliding++;
                                 TangentialSpring->slidingRolling = true;
                                 forcerolling *= pSpecies->getRollingFrictionCoefficient() * norm_fn / sqrt(forcerolling2);
                                 (*RollingSpring) = (forcerolling + pSpecies->getRollingDissipation() * vrolling) / (-pSpecies->getRollingStiffness());
                             }
                             //Add tangential force to torque
                             Vec3D Torque = reducedRadiusIJ * Vec3D::cross(normal, forcerolling);
                             PI->addTorque(Torque);
                             PJreal->addTorque(-Torque);
                         }
                     }
                     //calculate torsive friction
                     if (pSpecies->getTorsionFrictionCoefficient())
                     {
                         //From Luding2008, spin velocity (eq 16) w/o 2.0!
                         Mdouble RadiusIJ = 2.0 * PI->getRadius() * PJ->getRadius() / (PI->getRadius() + PJ->getRadius());
                         Vec3D vtorsion = RadiusIJ * Vec3D::dot(normal, PI->getAngularVelocity() - PJ->getAngularVelocity()) * normal;
                         if (pSpecies->getTorsionStiffness())
{
                             //~ std::cout << "Error; not yet implemented" << std::endl;
                             //~ exit(-1);
                             Vec3D* TorsionSpring = &(TangentialSpring->TorsionSpring);
                             //Integrate the spring
                             (*TorsionSpring) = Vec3D::dot((*TorsionSpring) + vtorsion * getTimeStep(), normal) * normal;
                             //Calculate test force including viscous force
                             forcetorsion = (-pSpecies->getTorsionDissipation()) * vtorsion - pSpecies->getTorsionStiffness() * (*TorsionSpring);
                             Mdouble forcetorsion2 = forcetorsion.getLengthSquared();
                             //tangential forces are modelled by a spring-damper of elastisity kt and viscosity getSlidingDissipation() (sticking),
                             //but the force is limited by Coulomb friction (sliding):
                             //f_t = -getSlidingDissipation()*vrelt, if getSlidingDissipation()*vrelt<=mu_s*fdotn, f_t=mu+s*fdotn*t, else
                             double muact = (TangentialSpring->slidingTorsion) ? (pSpecies->getTorsionFrictionCoefficient()) : (pSpecies->getTorsionFrictionCoefficientStatic()); // select mu from previous sliding mode
                             if (forcetorsion2 <= mathsFunc::square(muact * norm_fn))
{
                                 //sticking++;
                                 TangentialSpring->slidingTorsion = false;
                             }
                             else
{
                                 //sliding++;
                                 TangentialSpring->slidingTorsion = true;
                                 //~ std::cout << "sliding " << std::endl;
                                 forcetorsion *= pSpecies->getTorsionFrictionCoefficient() * norm_fn / sqrt(forcetorsion2);
                                 (*TorsionSpring) = (forcetorsion + pSpecies->getTorsionDissipation() * vtorsion) / (-pSpecies->getTorsionStiffness());
                             }
                             //Add tangential force to torque
                             Vec3D torque = RadiusIJ * forcetorsion;
                             PI->addTorque(torque);
                             PJreal->addTorque(-torque);
                         }
                     }
                 } //end if tangential forces
                 //Make force Hertzian (note: deltan is normalized by the normal distanct of two particles in contact, as in Silbert)
                 if (pSpecies->getForceType() == ForceType::HERTZ)
                     force *= sqrt(deltan / (PI->getRadius() + PJ->getRadius()));
             }
             else
             { //end if contact forces
                 force += fdotn * normal;
             }
             //Add forces to total force
             //PI->addForce(force);
             //if (!isPeriodic)
             //    PJreal->addForce(-force);
             // Add torque due to tangential forces: t = Vec3D::Cross(l,f), l=dist*Wall.normal
             //if (pSpecies->getSlidingFrictionCoefficient())
             //{
             //    Vec3D Vec3D::Cross = Vec3D::Cross(normal, force);
             //    PI->addTorque(-Vec3D::Cross * (PI->getRadius() - .5 * deltan));
             //    if (!isPeriodic)
             //        PJreal->addTorque(-Vec3D::Cross * (PJ->getRadius() - .5 * deltan));
             //}
             //BEGIN: CHANGE
             if (InPeriodicBox(PI) != InPeriodicBox(PJreal))
             {
                 if (InPeriodicBox(PI))
                 {
                     if (PI->getPosition().X > get_PeriodicBoxLength() - 4.0 * particleHandler.getLargestParticle()->getRadius())
                     {
                         //~ if (PJreal->isFixed()) cout << "PJreal" << endl;
                         PJreal->addForce(-force);
                     }
                 }
                 else
                 {
                     if (PJreal->getPosition().X > get_PeriodicBoxLength() - 4.0 * particleHandler.getLargestParticle()->getRadius())
                     {
                         //~ if (Particles[PI].isFixed()) cout << "PI" << endl;
                         PI->addForce(force);
                     }
                 }
             }
             else
             {
                 PI->addForce(force);
                 PJreal->addForce(-force);
             }
             //END: CHANGE
             // Add torque due to tangential forces: t = Vec3D::Cross(l,f), l=dist*Wall.normal
             //if (pSpecies->getSlidingFrictionCoefficient()) {
             //  Vec3D Vec3D::Cross = Vec3D::Cross(normal, force);
             //  PI    ->add_Torque(-Vec3D::Cross * (PI->getRadius() - .5 * deltan));
             //  PJreal->add_Torque(-Vec3D::Cross * (PJ->getRadius() - .5 * deltan));
             //}
             //BEGIN: CHANGE
             if (pSpecies->getSlidingFrictionCoefficient())
             {
                 Vec3D cross = Vec3D::cross(normal, force);
                 if (InPeriodicBox(PI) != InPeriodicBox(PJreal))
                 {
                     if (InPeriodicBox(PI))
                     {
                         if (PI->getPosition().X > get_PeriodicBoxLength() - 4.0 * particleHandler.getLargestParticle()->getRadius())
{
                             PJreal->addTorque(-cross * (PJreal->getRadius() - .5 * deltan));
                         }
                     }
                     else
                     {
                         if (PJreal->getPosition().X > get_PeriodicBoxLength() - 4.0 * particleHandler.getLargestParticle()->getRadius())
{
                             PI->addTorque(-cross * (PI->getRadius() - .5 * deltan));
                         }
                     }
                 }
                 else
                 {
                     PI->addTorque(-cross * (PI->getRadius() - .5 * deltan));
                     PJreal->addTorque(-cross * (PJreal->getRadius() - .5 * deltan));
                 }
             }
             //END:CHANGE
             // output for ene and stat files:
             if (eneFile.getSaveCurrentTimeStep())
             {
                 if (!isPeriodic)
                     addElasticEnergy(0.5 * (pSpecies->getStiffness() * mathsFunc::square(deltan) + (TangentialSpring ? (pSpecies->getSlidingStiffness() * TangentialSpring->delta.getLengthSquared() + pSpecies->getRollingStiffness() * TangentialSpring->RollingSpring.getLengthSquared() + pSpecies->getTorsionStiffness() * TangentialSpring->TorsionSpring.getLengthSquared()) : 0.0)));
                 else
                     addElasticEnergy(0.25 * (pSpecies->getStiffness() * mathsFunc::square(deltan) + (TangentialSpring ? (pSpecies->getSlidingStiffness() * TangentialSpring->delta.getLengthSquared() + pSpecies->getRollingStiffness() * TangentialSpring->RollingSpring.getLengthSquared() + pSpecies->getTorsionStiffness() * TangentialSpring->TorsionSpring.getLengthSquared()) : 0.0)));
             }
             if (fStatFile.getSaveCurrentTimeStep() || statFile.getSaveCurrentTimeStep() || getDoCGAlways())
             {
                 Mdouble fdott = forcet.getLength();
                 Mdouble deltat_norm = TangentialSpring ? (-TangentialSpring->delta.getLength()) : 0.0;
                 Vec3D centre = 0.5 * (PI->getPosition() + PJ->getPosition());
                 if (!PI->isFixed())
                 {
                     if (statFile.getSaveCurrentTimeStep() || getDoCGAlways())
                         gatherContactStatistics(PJreal->getIndex(), PI->getIndex(), centre, deltan, deltat_norm, fdotn, fdott, -normal, -(fdott ? forcet / fdott : forcet));
                     if (fStatFile.getSaveCurrentTimeStep())
                         fStatFile.getFstream() << getTime() << " " << PJreal->getIndex() << " " << PI->getIndex() << " " << centre << " " << radii_sum - dist << " " << deltat_norm << " " << fdotn << " " << fdott << " " << -normal << " " << -(fdott ? forcet / fdott : forcet) << std::endl;
                 }
                 if (!PJreal->isFixed() && !isPeriodic)
                 {
                     if (statFile.getSaveCurrentTimeStep() || getDoCGAlways())
                         gatherContactStatistics(PI->getIndex(), PJreal->getIndex(), centre, deltan, deltat_norm, fdotn, fdott, normal, (fdott ? forcet / fdott : forcet));
                     if (fStatFile.getSaveCurrentTimeStep())
                         fStatFile.getFstream() << getTime() << " " << PI->getIndex() << " " << PJreal->getIndex() << " " << centre << " " << radii_sum - dist << " " << deltat_norm << " " << fdotn << " " << fdott << " " << normal << " " << (fdott ? forcet / fdott : forcet) << std::endl;
                 }
             }
         } // end if particle i and j are overlapping
     }
References a, BaseInteractable::addForce(), BaseInteractable::addTorque(), Vec3D::cross(), oomph::VectorHelpers::cross(), MultiOpt::delta, Vec3D::dot(), DPMBase::eneFile, boost::multiprecision::fabs(), DPMBase::fStatFile, DPMBase::gatherContactStatistics(), get_PeriodicBoxLength(), BaseInteractable::getAngularVelocity(), Vec3D::getDistanceSquared(), File::getFstream(), BaseObject::getIndex(), BaseInteractable::getIndSpecies(), ParticleHandler::getLargestParticle(), Vec3D::getLength(), Vec3D::getLengthSquared(), BaseParticle::getMass(), SpeciesHandler::getMixedObject(), BaseParticle::getPeriodicFromParticle(), BaseInteractable::getPosition(), BaseParticle::getRadius(), DPMBase::getTime(), DPMBase::getTimeStep(), BaseInteractable::getVelocity(), InPeriodicBox(), BaseParticle::isFixed(), max, WallFunction::normal(), DPMBase::particleHandler, Eigen::bfloat16_impl::pow(), R, Vec3D::setZero(), DPMBase::speciesHandler, sqrt(), mathsFunc::square(), DPMBase::statFile, and Vec3D::X.
ExtendInWidth()
void ChuteWithPeriodicInflow::ExtendInWidth (int numRepetitionsInWidth) inline
     {
         PeriodicBoundary* perw = static_cast<PeriodicBoundary*>(boundaryHandler.getLastObject());
         // creates bottom outside periodic chute of species 1
         double widthPeriodicChute = getYMax();
         int N = particleHandler.getNumberOfObjects();
         particleHandler.setStorageCapacity(N * numRepetitionsInWidth);
         for (int j = 1; j < numRepetitionsInWidth; j++)
         {
             for (int i = 0; i < N; i++)
             {
                 //if (particleHandler.getObject(i)->isFixed()) {
                 particleHandler.addObject(particleHandler.getObject(i)->copy());
                 //Particles.back()->get_IndSpecies()=1;
                 particleHandler.getLastObject()->move(Vec3D(0.0, widthPeriodicChute * j, 0.0));
                 //}
             }
         }
         setYMax(numRepetitionsInWidth * widthPeriodicChute);
         perw->set(Vec3D(0, 1, 0), getYMin(), getYMax());
         //setHGridNumberOfBucketsToPower(particleHandler.getNumberOfObjects());
     }
References ParticleHandler::addObject(), DPMBase::boundaryHandler, BaseParticle::copy(), BaseHandler< T >::getLastObject(), ParticleHandler::getNumberOfObjects(), BaseHandler< T >::getObject(), DPMBase::getYMax(), DPMBase::getYMin(), i, j, BaseInteractable::move(), N, DPMBase::particleHandler, PeriodicBoundary::set(), BaseHandler< T >::setStorageCapacity(), and DPMBase::setYMax().
Referenced by ChuteWithPeriodicInflow().
get_PeriodicBoxLength()
double ChuteWithPeriodicInflow::get_PeriodicBoxLength () inline
     {
         return PeriodicBoxLength;
     }
References PeriodicBoxLength.
Referenced by computeInternalForces().
get_PeriodicBoxNSpecies()
int ChuteWithPeriodicInflow::get_PeriodicBoxNSpecies () inline
     {
         return PeriodicBoxNSpecies;
     }
References PeriodicBoxNSpecies.
Referenced by integrateBeforeForceComputation(), and loadPeriodicBox().
getInfo()
double ChuteWithPeriodicInflow::getInfo (const BaseParticle & p) const inline override virtual
A virtual function that returns some user-specified information about a particle.
Returns
double
Reimplemented from DPMBase.
             {
         return P.getIndSpecies();
     }
References Global_Physical_Variables::P.
InPeriodicBox()
bool ChuteWithPeriodicInflow::InPeriodicBox (BaseParticle * P) inline
     {
         return P->getIndSpecies() < PeriodicBoxNSpecies;
     }
References Global_Physical_Variables::P, and PeriodicBoxNSpecies.
Referenced by Check_and_Duplicate_Periodic_Particle(), and computeInternalForces().
integrateBeforeForceComputation()
void ChuteWithPeriodicInflow::integrateBeforeForceComputation () inline virtual
Update particles' and walls' positions and velocities before force computation.
This is where the integration is done, at the moment it is velocity Verlet integration and is done before the forces are computed. See http://en.wikipedia.org/wiki/Verlet_integration#Velocity_Verlet
Performs integration - i.e. updating particle's positions, velocities and accelerations - for all particles and walls within the system (i.e. in the particleHandler and wallHandler). Integration is performed using the BaseParticle::integrateBeforeForceComputation() function.
The velocity Verlet algorithm requires us to integrate twice each time step: both before and after the force computation. This method is therefore used in conjunction with DPMBase::integrateAfterForceComputation(). See http://en.wikipedia.org/wiki/Verlet_integration#Velocity_Verlet for details.
Reimplemented from DPMBase.
     {
         for (std::vector<BaseParticle*>::iterator it = particleHandler.begin(); it != particleHandler.end(); ++it)
         {
             (*it)->integrateBeforeForceComputation(getTimeStep());
             // This shifts particles that moved through periodic walls
             PeriodicBoundary* perw = static_cast<PeriodicBoundary*>(boundaryHandler.getObject(0));
             PeriodicBoundary* perw1 = static_cast<PeriodicBoundary*>(boundaryHandler.getObject(1));
             if ((*it)->getIndSpecies() == 0 && perw->getDistance(**it) < 0)
             {
                 //if (iP->getIndSpecies()==0 && static_cast<PeriodicWall*>(boundaryHandler.getObject(0))->getDistance(*iP)<0) {
                 if (!perw->isClosestToLeftBoundary())
                 {
                     if (particleHandler.getStorageCapacity() <= particleHandler.getNumberOfObjects())
                         particleHandler.setStorageCapacity(particleHandler.getStorageCapacity() + 10000);
                     particleHandler.addObject((*it)->copy());
                     const ParticleSpecies* species = speciesHandler.getObject(particleHandler.getLastObject()->getIndSpecies() + get_PeriodicBoxNSpecies());
                     particleHandler.getLastObject()->setSpecies(species);
                     perw->shiftPosition((*it));
                     if (!getHGridUpdateEachTimeStep())
                     {
                         hGridRemoveParticle((*it));
                         hGridUpdateParticle((*it));
                     }
                 }
                 else
                 {
                     static int count = -1;
                     count++;
                     if (!(count % dataFile.getSaveCount()))
                         std::cout << "Warning: Particle " << (*it)->getIndex() << " is left of xmin: x="
                                 << (*it)->getPosition().X << ", v_x=" << (*it)->getVelocity().X << std::endl;
                 }
             }
             if (getIsPeriodic() > 1 && perw1->getDistance(**it) < 0)
             {
                 perw1->shiftPosition(*it);
                 if (!getHGridUpdateEachTimeStep())
                 {
                     hGridRemoveParticle(*it);
                     hGridUpdateParticle(*it);
                 }
             }
         }
     }
References ParticleHandler::addObject(), BaseHandler< T >::begin(), DPMBase::boundaryHandler, DPMBase::dataFile, BaseHandler< T >::end(), get_PeriodicBoxNSpecies(), PeriodicBoundary::getDistance(), MercuryBase::getHGridUpdateEachTimeStep(), BaseInteractable::getIndSpecies(), Chute::getIsPeriodic(), BaseHandler< T >::getLastObject(), ParticleHandler::getNumberOfObjects(), BaseHandler< T >::getObject(), File::getSaveCount(), BaseHandler< T >::getStorageCapacity(), DPMBase::getTimeStep(), Mercury3D::hGridRemoveParticle(), Mercury3D::hGridUpdateParticle(), PeriodicBoundary::isClosestToLeftBoundary(), DPMBase::particleHandler, BaseParticle::setSpecies(), BaseHandler< T >::setStorageCapacity(), PeriodicBoundary::shiftPosition(), and DPMBase::speciesHandler.
loadPeriodicBox()
void ChuteWithPeriodicInflow::loadPeriodicBox (std::string const restart_file) inline
loads periodic chute data from restart file
     {
         FillChute = false;
         std::cout << "constructor" << std::endl;
         //load particles and chute setup into periodic chute
         setName(restart_file.c_str());
         readRestartFile();
         set_PeriodicBoxLength(getXMax());
         set_PeriodicBoxNSpecies(speciesHandler.getNumberOfObjects());
         //we don't want to treat the data as restarted, i.e. we start the program at time=0 and create new output files
         setRestarted(false);
         //keep file name but create files in the local directory, i.e. remove folder
         size_t found = restart_file.find_last_of("/\\");
         setName(restart_file.substr(found + 1).c_str());
         // adds new species for the flow particles (0 for the periodic inflow particles)
         for (int i = 0; i < get_PeriodicBoxNSpecies(); i++)
             addSpecies(Species[i]);
         setName("ChuteWithPeriodicInflow");
     }
References FillChute, MergeRestartFiles::found, get_PeriodicBoxNSpecies(), BaseHandler< T >::getNumberOfObjects(), DPMBase::getXMax(), i, DPMBase::readRestartFile(), set_PeriodicBoxLength(), set_PeriodicBoxNSpecies(), DPMBase::setName(), DPMBase::setRestarted(), and DPMBase::speciesHandler.
Referenced by ChuteWithPeriodicInflow().
outputXBallsDataParticlee()
void ChuteWithPeriodicInflow::outputXBallsDataParticlee (const unsigned int i, const unsigned int format, std::ostream & os) const inline
             {
         os
         << particleHandler.getObject(i)->getPosition().X << " "
                 << particleHandler.getObject(i)->getPosition().Y << " "
                 << particleHandler.getObject(i)->getPosition().Z << " "
                 << particleHandler.getObject(i)->getVelocity().X << " "
                 << particleHandler.getObject(i)->getVelocity().Y << " "
                 << particleHandler.getObject(i)->getVelocity().Z << " "
                 //~ << (particleHandler.getObject(i)->isFixed()?0.0:particleHandler.getObject(i)->Force.X) << " "
                 //~ << (particleHandler.getObject(i)->isFixed()?0.0:particleHandler.getObject(i)->Force.Y) << " "
                 //~ << (particleHandler.getObject(i)->isFixed()?0.0:particleHandler.getObject(i)->Force.Z) << " "
                 << particleHandler.getObject(i)->getRadius() << " "
                 << particleHandler.getObject(i)->getIndSpecies() << " "
                 << particleHandler.getObject(i)->getOrientation().Y << " "
                 << particleHandler.getObject(i)->getOrientation().Z << " "
                 << particleHandler.getObject(i)->getAngularVelocity().X << " "
                 << particleHandler.getObject(i)->getAngularVelocity().Y << " "
                 << particleHandler.getObject(i)->getAngularVelocity().Z << " "
                 << particleHandler.getObject(i)->getIndSpecies() << std::endl;
     }
References BaseInteractable::getAngularVelocity(), BaseInteractable::getIndSpecies(), BaseHandler< T >::getObject(), BaseInteractable::getOrientation(), BaseInteractable::getPosition(), BaseParticle::getRadius(), BaseInteractable::getVelocity(), i, DPMBase::particleHandler, Vec3D::X, Vec3D::Y, and Vec3D::Z.
printTime()
void ChuteWithPeriodicInflow::printTime () const inline override virtual
add some particular output
Reimplemented from DPMBase.
     {
         int counter = 0;
         double speed1 = 0;
         double speed0 = 0;
         double n1 = 0;
         double n0 = 0;
         for (int i = 0; i < particleHandler.getNumberOfObjects(); i++)
         {
             if (particleHandler.getObject(i)->getIndSpecies() == 0)
                 counter++;
             if (!particleHandler.getObject(i)->isFixed())
             {
                 if (particleHandler.getObject(i)->getIndSpecies() == 0)
                 {
                     speed0 += particleHandler.getObject(i)->getVelocity().X;
                     n0++;
                 }
                 else
                 {
                     speed1 += particleHandler.getObject(i)->getVelocity().X;
                     n1++;
                 }
             }
         }
         speed0 /= n0;
         speed1 /= n1;
         std::cout << "t=" << std::setprecision(5) << std::left << std::setw(6) << getTime()
                 << ", n=" << n1 << "(inflow:" << n0 << ")"
                 << ", speed= " << speed1 << "(" << speed0 << ")"
                 << std::endl;
         //~ cout
         //~ << " A " << PeriodicBoxLength
         //~ << " A " << PeriodicBoxNSpecies
         //~ << " A " << FillChute << endl;
     }
References BaseInteractable::getIndSpecies(), ParticleHandler::getNumberOfObjects(), BaseHandler< T >::getObject(), DPMBase::getTime(), BaseInteractable::getVelocity(), i, BaseParticle::isFixed(), DPMBase::particleHandler, and Vec3D::X.
set_PeriodicBoxLength()
void ChuteWithPeriodicInflow::set_PeriodicBoxLength (double new_) inline
     {
         PeriodicBoxLength = new_;
     }
References PeriodicBoxLength.
Referenced by loadPeriodicBox().
set_PeriodicBoxNSpecies()
void ChuteWithPeriodicInflow::set_PeriodicBoxNSpecies (int new_) inline
     {
         PeriodicBoxNSpecies = new_;
     }
References PeriodicBoxNSpecies.
Referenced by loadPeriodicBox().
setupInitialConditions()
void ChuteWithPeriodicInflow::setupInitialConditions () inline override virtual
Do not add bottom.
Reimplemented from DPMBase.
     {
     }
writeXBallsScript()
void ChuteWithPeriodicInflow::writeXBallsScript () const inline virtual
This writes a script which can be used to load the xballs problem to display the data just generated.
Todo:
Implement or make pure virtual
First put in all the script lines. All these lines do is move you to the correct directory from any location
Reimplemented from DPMBase.
     {
         std::stringstream file_name;
         std::ofstream script_file;
         file_name << getName() << ".disp";
         script_file.open((file_name.str()).c_str());
         script_file << "#!/bin/bash" << std::endl;
         script_file << "x=$(echo $0 | cut -c2-)" << std::endl;
         script_file << "file=$PWD$x" << std::endl;
         script_file << "dirname=`dirname \"$file\"`" << std::endl;
         script_file << "cd $dirname" << std::endl;
         double scale;
         int format;
         int width = 1570, height = 860;
         double ratio = getSystemDimensions() < 3 ? (getXMax() - getXMin()) / (getYMax() - getYMin()) : (getXMax() - getXMin()) / (getZMax() - getZMin());
         if (ratio > width / height)
             height = width / ratio;
         else
             width = height * ratio;
         //~ cout << ratio << "r" << endl;
         if (getSystemDimensions() < 3)
         { // dim = 1 or 2
             format = 8;
             if (getXBallsScale() < 0)
             {
                 scale = 1.0 / std::max(getYMax() - getYMin(), getXMax() - getXMin());
             }
             else
             {
                 scale = getXBallsScale();
             }
         }
         else
         { //dim==3
             format = 14;
             if (getXBallsScale() < 0)
             {
                 scale = width / 480 / (getXMax() - getXMin());
             }
             else
             {
                 scale = getXBallsScale();
             }
         }
         script_file << "../xballs -format " << format
                 << " -f " << dataFile.getFullName()
                 << " -s " << scale
                 << " -w " << width + 140
                 << " -h " << height + 140
                 << " -cmode " << getXBallsColourMode()
                 << " -cmax -scala 4 -sort -oh 50 "
                 << getXBallsAdditionalArguments()
                 << " $*";
         if (getXBallsVectorScale() > -1)
         {
             script_file << " -vscale " << getXBallsVectorScale();
         }
         script_file.close();
         //This line changes the file permision and gives the owner (i.e. you) read, write and execute permission to the file
 #ifdef UNIX
         chmod((file_name.str().c_str()),S_IRWXU);
 #endif
     }
References DPMBase::dataFile, Particles2023AnalysisHung::file_name, format(), File::getFullName(), DPMBase::getName(), DPMBase::getSystemDimensions(), DPMBase::getXBallsAdditionalArguments(), DPMBase::getXBallsColourMode(), DPMBase::getXBallsScale(), DPMBase::getXBallsVectorScale(), DPMBase::getXMax(), DPMBase::getXMin(), DPMBase::getYMax(), DPMBase::getYMin(), DPMBase::getZMax(), DPMBase::getZMin(), Global_Physical_Variables::height(), and max.
Member Data Documentation
FillChute
bool ChuteWithPeriodicInflow::FillChute private
Referenced by AddContinuingBottom(), and loadPeriodicBox().
inflowParticle_
SphericalParticle ChuteWithPeriodicInflow::inflowParticle_
Referenced by ChuteWithPeriodicInflowAndContinuingBottom::ChuteWithPeriodicInflowAndContinuingBottom(), ChuteWithPeriodicInflowAndContraction::ChuteWithPeriodicInflowAndContraction(), and ChuteWithPeriodicInflowAndVariableBottom::ChuteWithPeriodicInflowAndVariableBottom().
PeriodicBoxLength
double ChuteWithPeriodicInflow::PeriodicBoxLength private
stores the length of the periodic box
Referenced by get_PeriodicBoxLength(), and set_PeriodicBoxLength().
PeriodicBoxNSpecies
int ChuteWithPeriodicInflow::PeriodicBoxNSpecies private
stores the number of species in the periodic box
Referenced by get_PeriodicBoxNSpecies(), InPeriodicBox(), and set_PeriodicBoxNSpecies().
The documentation for this class was generated from the following file:
ChuteWithPeriodicInflow.h