MercuryDPM: Eigen::internal::Assignment< DstXprType, Product< Lhs, Rhs, Options >, internal::assign_op< Scalar, Scalar >, Dense2Dense, std::enable_if_t<(Options==DefaultProduct||Options==AliasFreeProduct)> > Struct Template Reference
Eigen::internal::Assignment< DstXprType, Product< Lhs, Rhs, Options >, internal::assign_op< Scalar, Scalar >, Dense2Dense, std::enable_if_t<(Options==DefaultProduct||Options==AliasFreeProduct)> > Struct Template Reference
#include <ProductEvaluators.h>
Public Types
typedef Product< Lhs, Rhs, Options > SrcXprType
Static Public Member Functions
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void run (DstXprType &dst, const SrcXprType &src, const internal::assign_op< Scalar, Scalar > &)
Member Typedef Documentation
SrcXprType
template<typename DstXprType , typename Lhs , typename Rhs , int Options, typename Scalar > typedef Product<Lhs, Rhs, Options> Eigen::internal::Assignment< DstXprType, Product< Lhs, Rhs, Options >, internal::assign_op< Scalar, Scalar >, Dense2Dense, std::enable_if_t<(Options==DefaultProduct||Options==AliasFreeProduct)> >::SrcXprType
Member Function Documentation
run()
template<typename DstXprType , typename Lhs , typename Rhs , int Options, typename Scalar > static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::internal::Assignment< DstXprType, Product< Lhs, Rhs, Options >, internal::assign_op< Scalar, Scalar >, Dense2Dense, std::enable_if_t<(Options==DefaultProduct||Options==AliasFreeProduct)> >::run (DstXprType & dst, const SrcXprType & src, const internal::assign_op< Scalar, Scalar > &) inline static
{
     Index dstRows = src.rows();
     Index dstCols = src.cols();
     if ((dst.rows() != dstRows) || (dst.cols() != dstCols)) dst.resize(dstRows, dstCols);
     // FIXME shall we handle nested_eval here?
     generic_product_impl<Lhs, Rhs>::evalTo(dst, src.lhs(), src.rhs());
   }
References Eigen::Product< Lhs_, Rhs_, Option >::cols(), Eigen::Product< Lhs_, Rhs_, Option >::lhs(), Eigen::Product< Lhs_, Rhs_, Option >::rhs(), and Eigen::Product< Lhs_, Rhs_, Option >::rows().
The documentation for this struct was generated from the following file:
ProductEvaluators.h