MercuryDPM: DPMBase Class Reference
DPMBase Class Reference
The DPMBase header includes quite a few header files, defining all the handlers, which are essential. Moreover, it defines and solves a DPM problem. It is inherited from FilesAndRunNumber (public).
#include <DPMBase.h>
Public Types
enum class ReadOptions : int { ReadAll , ReadNoInteractions , ReadNoParticlesAndInteractions }
enum class DomainSplit {
X , Y , Z , XY ,
XZ , YZ , XYZ
}
Public Member Functions
void constructor ()
A function which initialises the member variables to default values, so that the problem can be solved off the shelf; sets up a basic two dimensional problem which can be solved off the shelf. It is called in the constructor DPMBase().
DPMBase ()
Constructor that calls the "void constructor()".
DPMBase (const DPMBase &other)
Copy constructor type-2.
virtual ~DPMBase ()
virtual destructor
void autoNumber ()
The autoNumber() function calls three functions: setRunNumber(), readRunNumberFromFile() and incrementRunNumberInFile().
std::vector< int > get1DParametersFromRunNumber (int size_x) const
This turns a counter into 1 index, which is a useful feature for performing 1D parameter study. The index run from 1:size_x, while the study number starts at 0 (initially the counter=1 in COUNTER_DONOTDEL)
std::vector< int > get2DParametersFromRunNumber (int size_x, int size_y) const
This turns a counter into 2 indices which is a very useful feature for performing a 2D study. The indices run from 1:size_x and 1:size_y, while the study number starts at 0 (initially the counter=1 in COUNTER_DONOTDEL)
std::vector< int > get3DParametersFromRunNumber (int size_x, int size_y, int size_z) const
This turns a counter into 3 indices, which is a useful feature for performing a 3D parameter study. The indices run from 1:size_x, 1:size_y and 1:size_z, while the study number starts at 0 (initially the counter=1 in COUNTER_DONOTDEL)
int launchNewRun (const char *name, bool quick=false)
This launches a code from within this code. Please pass the name of the code to run.
void setRunNumber (int runNumber)
This sets the counter/Run number, overriding the defaults.
int getRunNumber () const
This returns the current value of the counter (runNumber_)
virtual void decompose ()
Sends particles from processorId to the root processor.
void solve ()
The work horse of the code.
void initialiseSolve ()
Beginning of the solve routine, before time stepping.
void finaliseSolve ()
End of the solve routine, after time stepping.
virtual void computeOneTimeStep ()
Performs everything needed for one time step, used in the time-loop of solve().
void checkSettings ()
Checks if the essentials are set properly to go ahead with solving the problem.
void forceWriteOutputFiles ()
Writes output files immediately, even if the current time step was not meant to be written. Also resets the last saved time step.
virtual void writeOutputFiles ()
Writes simulation data to all the main Mercury files: .data, .ene, .fstat, .xballs and .restart (see the Mercury website for more details regarding these files).
void solve (int argc, char *argv[])
The work horse of the code. Can handle flags from the command line.
virtual void setupInitialConditions ()
This function allows to set the initial conditions for our problem to be solved, by default particle locations are randomly set. Remember particle properties must also be defined here.
virtual void writeXBallsScript () const
This writes a script which can be used to load the xballs problem to display the data just generated.
virtual Mdouble getInfo (const BaseParticle &P) const
A virtual function that returns some user-specified information about a particle.
ParticleVtkWriter * getVtkWriter () const
virtual void writeRestartFile ()
Stores all the particle data for current save time step to a "restart" file, which is a file simply intended to store all the information necessary to "restart" a simulation from a given time step (see also MercuryDPM.org for more information on restart files).
void writeDataFile ()
void writeEneFile ()
void writeFStatFile ()
void fillDomainWithParticles (unsigned N=50)
bool readRestartFile (ReadOptions opt=ReadOptions::ReadAll)
Reads all the particle data corresponding to a given, existing . restart file (for more details regarding restart files, refer to the training materials on the MercuryDPM website).Returns true if it is successful, false otherwise.
int readRestartFile (std::string fileName, ReadOptions opt=ReadOptions::ReadAll)
The same as readRestartFile(bool), but also reads all the particle data corresponding to the current saved time step.
virtual void write (std::ostream &os, bool writeAllParticles=true) const
virtual void read (std::istream &is, ReadOptions opt=ReadOptions::ReadAll)
Reads all data from a restart file, e.g. domain data and particle data.
virtual BaseWall * readUserDefinedWall (const std::string &type) const
Allows you to read in a wall defined in a Driver directory; see USER/Luca/ScrewFiller.
virtual void readOld (std::istream &is)
Reads all data from a restart file, e.g. domain data and particle data; old version.
bool readDataFile (std::string fileName="", unsigned int format=0)
This allows particle data to be reloaded from data files.
bool readParAndIniFiles (std::string fileName)
Allows the user to read par.ini files (useful to read files produced by the MDCLR simulation code - external to MercuryDPM)
bool readNextDataFile (unsigned int format=0)
Reads the next data file with default format=0. However, one can modify the format based on whether the particle data corresponds to 3D or 2D data- see Visualising data in xballs.
void readNextFStatFile ()
Reads the next fstat file.
bool findNextExistingDataFile (Mdouble tMin, bool verbose=true)
Finds and opens the next data file, if such a file exists.
bool readArguments (int argc, char *argv[])
Can interpret main function input arguments that are passed by the driver codes.
virtual bool readNextArgument (int &i, int argc, char *argv[])
Interprets the i^th command-line argument.
virtual bool checkParticleForInteraction (const BaseParticle &P)
Checks whether a particle P has any interaction with walls or other particles.
virtual bool checkParticleForInteractionLocal (const BaseParticle &P)
Checks if a particle P has any interaction with walls or other particles in the local domain.
bool checkParticleForInteractionLocalPeriodic (const BaseParticle &P)
void readSpeciesFromDataFile (bool read=true)
void importParticlesAs (ParticleHandler &particleHandler, InteractionHandler &interactionHandler, const ParticleSpecies *species)
Copies particles, interactions assigning species from a local simulation to a global one. Useful for the creation of a cluster.
MERCURYDPM_DEPRECATED File & getDataFile ()
The non const version. Allows one to edit the File::dataFile.
MERCURYDPM_DEPRECATED File & getEneFile ()
The non const version. Allows to edit the File::eneFile.
MERCURYDPM_DEPRECATED File & getFStatFile ()
The non const version. Allows to edit the File::fStatFile.
MERCURYDPM_DEPRECATED File & getRestartFile ()
The non const version. Allows to edit the File::restartFile.
MERCURYDPM_DEPRECATED File & getStatFile ()
The non const version. Allows to edit the File::statFile.
File & getInteractionFile ()
Return a reference to the file InteractionsFile.
MERCURYDPM_DEPRECATED const File & getDataFile () const
The const version. Does not allow for any editing of the File::dataFile.
MERCURYDPM_DEPRECATED const File & getEneFile () const
The const version. Does not allow for any editing of the File::eneFile.
MERCURYDPM_DEPRECATED const File & getFStatFile () const
The const version. Does not allow for any editing of the File::fStatFile.
MERCURYDPM_DEPRECATED const File & getRestartFile () const
The const version. Does not allow for any editing of the File::restartFile.
MERCURYDPM_DEPRECATED const File & getStatFile () const
The const version. Does not allow for any editing of the File::statFile.
const File & getInteractionFile () const
Returns a constant reference to an Interactions file.
const std::string & getName () const
Returns the name of the file. Does not allow to change it though.
void setName (const std::string &name)
Allows to set the name of all the files (ene, data, fstat, restart, stat)
void setName (const char *name)
Calls setName(std::string)
void setSaveCount (unsigned int saveCount)
Sets File::saveCount_ for all files (ene, data, fstat, restart, stat)
void setFileType (FileType fileType)
Sets File::fileType_ for all files (ene, data, fstat, restart, stat)
void setOpenMode (std::fstream::openmode openMode)
Sets File::openMode_ for all files (ene, data, fstat, restart, stat)
void resetFileCounter ()
Resets the file counter for each file i.e. for ene, data, fstat, restart, stat)
void closeFiles ()
Closes all files (ene, data, fstat, restart, stat) that were opened to read or write.
void setVTKOutputDirectory (const std::string &dir)
Sets the output directory of the VTK files.
void setLastSavedTimeStep (unsigned int nextSavedTimeStep)
Sets the next time step for all the files (ene, data, fstat, restart, stat) at which the data is to be written or saved.
Mdouble getTime () const
Returns the current simulation time.
Mdouble getNextTime () const
Returns the current simulation time.
unsigned int getNumberOfTimeSteps () const
Returns the current counter of time-steps, i.e. the number of time-steps that the simulation has undergone so far.
void setTime (Mdouble time)
Sets a new value for the current simulation time.
void setTimeMax (Mdouble newTMax)
Sets a new value for the maximum simulation duration.
Mdouble getTimeMax () const
Returns the maximum simulation duration.
void setLogarithmicSaveCount (Mdouble logarithmicSaveCountBase)
Sets File::logarithmicSaveCount_ for all files (ene, data, fstat, restart, stat)
void setNToWrite (int nToWrite)
set the number of elements to write to the screen
int getNToWrite () const
get the number of elements to write to the
void setRotation (bool rotation)
Sets whether particle rotation is enabled or disabled.
bool getRotation () const
Indicates whether particle rotation is enabled or disabled.
MERCURYDPM_DEPRECATED void setWallsWriteVTK (FileType writeWallsVTK)
Sets whether walls are written into a VTK file.
MERCURYDPM_DEPRECATED void setWallsWriteVTK (bool)
Sets whether walls are written into a VTK file.
MERCURYDPM_DEPRECATED void setInteractionsWriteVTK (bool)
Sets whether interactions are written into a VTK file.
void setParticlesWriteVTK (bool writeParticlesVTK)
Sets whether particles are written in a VTK file.
void setSuperquadricParticlesWriteVTK (bool writeSuperquadricParticlesVTK)
MERCURYDPM_DEPRECATED FileType getWallsWriteVTK () const
Returns whether walls are written in a VTK file.
bool getParticlesWriteVTK () const
Returns whether particles are written in a VTK file.
bool getSuperquadricParticlesWriteVTK () const
Mdouble getXMin () const
If the length of the problem domain in x-direction is XMax - XMin, then getXMin() returns XMin.
Mdouble getXMax () const
If the length of the problem domain in x-direction is XMax - XMin, then getXMax() returns XMax.
Mdouble getYMin () const
If the length of the problem domain in y-direction is YMax - YMin, then getYMin() returns YMin.
Mdouble getYMax () const
If the length of the problem domain in y-direction is YMax - YMin, then getYMax() returns XMax.
Mdouble getZMin () const
If the length of the problem domain in z-direction is ZMax - ZMin, then getZMin() returns ZMin.
Mdouble getZMax () const
If the length of the problem domain in z-direction is ZMax - ZMin, then getZMax() returns ZMax.
Mdouble getXCenter () const
Mdouble getYCenter () const
Mdouble getZCenter () const
Vec3D getCenter () const
get center of domain
Vec3D getMin () const
Returns the minimum coordinates of the problem domain.
Vec3D getMax () const
Returns the maximum coordinates of the problem domain.
void setXMin (Mdouble newXMin)
Sets the value of XMin, the lower bound of the problem domain in the x-direction.
void setYMin (Mdouble newYMin)
Sets the value of YMin, the lower bound of the problem domain in the y-direction.
void setZMin (Mdouble newZMin)
Sets the value of ZMin, the lower bound of the problem domain in the z-direction.
void setXMax (Mdouble newXMax)
Sets the value of XMax, the upper bound of the problem domain in the x-direction.
void setYMax (Mdouble newYMax)
Sets the value of YMax, the upper bound of the problem domain in the y-direction.
void setZMax (Mdouble newZMax)
Sets the value of ZMax, the upper bound of the problem domain in the z-direction.
void setMax (const Vec3D &max)
Sets the maximum coordinates of the problem domain.
void setMax (Mdouble, Mdouble, Mdouble)
Sets the maximum coordinates of the problem domain.
void setDomain (const Vec3D &min, const Vec3D &max)
Sets the minimum coordinates of the problem domain.
void setMin (const Vec3D &min)
Sets the minimum coordinates of the problem domain.
void setMin (Mdouble, Mdouble, Mdouble)
Sets the minimum coordinates of the problem domain.
void setTimeStep (Mdouble newDt)
Sets a new value for the simulation time step.
Mdouble getTimeStep () const
Returns the simulation time step.
void setNumberOfOMPThreads (int numberOfOMPThreads)
Sets the number of omp threads.
int getNumberOfOMPThreads () const
Returns the number of omp threads.
void setXBallsColourMode (int newCMode)
Set the xballs output mode.
int getXBallsColourMode () const
Get the xballs colour mode (CMode).
void setXBallsVectorScale (double newVScale)
Set the scale of vectors in xballs.
double getXBallsVectorScale () const
Returns the scale of vectors used in xballs.
void setXBallsAdditionalArguments (std::string newXBArgs)
Set the additional arguments for xballs.
std::string getXBallsAdditionalArguments () const
Returns the additional arguments for xballs.
void setXBallsScale (Mdouble newScale)
Sets the scale of the view (either normal, zoom in or zoom out) to display in xballs. The default is fit to screen.
double getXBallsScale () const
Returns the scale of the view in xballs.
void setGravity (Vec3D newGravity)
Sets a new value for the gravitational acceleration.
Vec3D getGravity () const
Returns the gravitational acceleration.
void setBackgroundDrag (Mdouble backgroundDrag)
Simple access function to turn on a background drag. The force of particleVelocity*drag is applied (note, it allowed to be negative i.e. create energy)
const Mdouble getBackgroundDrag () const
Return the background drag.
void setDimension (unsigned int newDim)
Sets both the system dimensions and the particle dimensionality.
void setSystemDimensions (unsigned int newDim)
Sets the system dimensionality.
unsigned int getSystemDimensions () const
Returns the system dimensionality.
void setParticleDimensions (unsigned int particleDimensions)
Sets the particle dimensionality.
unsigned int getParticleDimensions () const
Returns the particle dimensionality.
std::string getRestartVersion () const
This is to take into account for different Mercury versions. Returns the version of the restart file.
void setRestartVersion (std::string newRV)
Sets restart_version.
bool getRestarted () const
Returns the flag denoting if the simulation was restarted or not.
void setRestarted (bool newRestartedFlag)
Allows to set the flag stating if the simulation is to be restarted or not.
bool getAppend () const
Returns whether the "append" option is on or off.
void setAppend (bool newAppendFlag)
Sets whether the "append" option is on or off.
Mdouble getElasticEnergy () const
Returns the global elastic energy within the system.
Mdouble getKineticEnergy () const
Returns the global kinetic energy stored in the system.
Mdouble getGravitationalEnergy (Vec3D origin={0, 0, 0}) const
Returns the global gravitational potential energy stored relative to a user-defined origin in the system. Note, if no origin is specified the real origin i.e. (0,0,0) is taken.
Mdouble getRotationalEnergy () const
Returns the global rotational energy stored in the system.
Mdouble getTotalEnergy () const
Mdouble getTotalMass () const
JMFT: Return the total mass of the system, excluding fixed particles.
Vec3D getCentreOfMass () const
JMFT: Return the centre of mass of the system, excluding fixed particles.
Vec3D getTotalMomentum () const
JMFT: Return the total momentum of the system, excluding fixed particles.
double getCPUTime ()
double getWallTime ()
virtual void hGridInsertParticle (BaseParticle *obj UNUSED)
virtual void hGridUpdateParticle (BaseParticle *obj UNUSED)
virtual void hGridRemoveParticle (BaseParticle *obj UNUSED)
virtual void hGridUpdateMove (BaseParticle *, Mdouble)
bool mpiIsInCommunicationZone (BaseParticle *particle)
Checks if the position of the particle is in an mpi communication zone or not.
bool mpiInsertParticleCheck (BaseParticle *P)
Function that checks if the mpi particle should really be inserted by the current domain.
void insertGhostParticle (BaseParticle *P)
This function inserts a particle in the mpi communication boundaries.
void updateGhostGrid (BaseParticle *P)
Checks if the Domain/periodic interaction distance needs to be updated and updates it accordingly.
virtual void gatherContactStatistics (unsigned int index1, int index2, Vec3D Contact, Mdouble delta, Mdouble ctheta, Mdouble fdotn, Mdouble fdott, Vec3D P1_P2_normal_, Vec3D P1_P2_tangential)
//Not unsigned index because of possible wall collisions.
void setNumberOfDomains (std::vector< unsigned > direction)
Sets the number of domains in x-,y- and z-direction. Required for parallel computations.
void splitDomain (DomainSplit domainSplit)
std::vector< unsigned > getNumberOfDomains ()
returns the number of domains
Domain * getCurrentDomain ()
Function that returns a pointer to the domain corresponding to the processor.
void removeOldFiles () const
virtual void hGridGetInteractingParticleList (BaseParticle *obj, std::vector< BaseParticle * > &list)
Creates a list of neighbour particles obtained from the hgrid.
virtual void computeWallForces (BaseWall *w)
virtual bool getHGridUpdateEachTimeStep () const
void setMeanVelocity (Vec3D V_mean_goal)
This function will help you set a fixed kinetic energy and mean velocity in your system.
void setMeanVelocityAndKineticEnergy (Vec3D V_mean_goal, Mdouble Ek_goal)
This function will help you set a fixed kinetic energy and mean velocity in your system.
Mdouble getTotalVolume () const
Get the total volume of the cuboid system.
Matrix3D getKineticStress () const
Calculate the kinetic stress tensor in the system averaged over the whole volume.
Matrix3D getStaticStress () const
Calculate the static stress tensor in the system averaged over the whole volume.
Matrix3D getTotalStress () const
Calculate the total stress tensor in the system averaged over the whole volume.
virtual void handleParticleRemoval (unsigned int id)
Handles the removal of particles from the particleHandler.
virtual void handleParticleAddition (unsigned int id, BaseParticle *p)
Handles the addition of particles to the particleHandler.
void writePythonFileForVTKVisualisation () const
writes .py file for ParaView
void setWritePythonFileForVTKVisualisation (bool forceWritePythonFileForVTKVisualisation)
bool getWritePythonFileForVTKVisualisation () const
WallVTKWriter & getWallVTKWriter ()
Static Public Member Functions
static void incrementRunNumberInFile ()
Increment the run Number (counter value) stored in the file_counter (COUNTER_DONOTDEL) by 1 and store the new value in the counter file.
static int readRunNumberFromFile ()
Read the run number or the counter from the counter file (COUNTER_DONOTDEL)
static bool areInContact (const BaseParticle *pI, const BaseParticle *pJ)
Checks if two particle are in contact or is there any positive overlap.
Public Attributes
SpeciesHandler speciesHandler
A handler to that stores the species type i.e. LinearViscoelasticSpecies, etc.
RNG random
This is a random generator, often used for setting up the initial conditions etc...
ParticleHandler particleHandler
An object of the class ParticleHandler, contains the pointers to all the particles created.
ParticleHandler paoloParticleHandler
Fake particleHandler created by Paolo needed temporary by just Paolo.
WallHandler wallHandler
An object of the class WallHandler. Contains pointers to all the walls created.
BoundaryHandler boundaryHandler
An object of the class BoundaryHandler which concerns insertion and deletion of particles into or from regions.
PeriodicBoundaryHandler periodicBoundaryHandler
Internal handler that deals with periodic boundaries, especially in a parallel build.
DomainHandler domainHandler
An object of the class DomainHandler which deals with parallel code.
InteractionHandler interactionHandler
An object of the class InteractionHandler.
CGHandler cgHandler
Object of the class cgHandler.
File dataFile
An instance of class File to handle in- and output into a .data file.
File fStatFile
An instance of class File to handle in- and output into a .fstat file.
File eneFile
An instance of class File to handle in- and output into a .ene file.
File restartFile
An instance of class File to handle in- and output into a .restart file.
File statFile
An instance of class File to handle in- and output into a .stat file.
File interactionFile
File class to handle in- and output into .interactions file. This file hold information about interactions.
Time clock_
record when the simulation started
Protected Member Functions
virtual void computeAllForces ()
Computes all the forces acting on the particles using the BaseInteractable::setForce() and BaseInteractable::setTorque()
virtual void computeInternalForces (BaseParticle *)
Computes the internal forces on particle i (internal in the sense that the sum over all these forces is zero i.e. fully modelled forces)
virtual void computeInternalForce (BaseParticle *, BaseParticle *)
Computes the forces between two particles (internal in the sense that the sum over all these forces is zero i.e. fully modelled forces)
virtual void computeExternalForces (BaseParticle *)
Computes the external forces, such as gravity, acting on particles.
virtual void computeForcesDueToWalls (BaseParticle *, BaseWall *)
Computes the forces on the particles due to the walls (normals are outward normals)
virtual void actionsOnRestart ()
A virtual function where the users can add extra code which is executed only when the code is restarted.
virtual void actionsBeforeTimeLoop ()
A virtual function. Allows one to carry out any operations before the start of the time loop.
virtual void hGridActionsBeforeTimeLoop ()
A virtual function that allows one to carry out hGrid operations before the start of the time loop.
virtual void hGridActionsBeforeTimeStep ()
A virtual function that allows one to set or execute hGrid parameters or operations before every simulation time step.
virtual void actionsBeforeTimeStep ()
A virtual function which allows to define operations to be executed before the new time step.
virtual void computeAdditionalForces ()
A virtual function which allows to define operations to be executed prior to the OMP force collect.
virtual void actionsAfterSolve ()
A virtual function which allows to define operations to be executed after the solve().
virtual void actionsAfterTimeStep ()
A virtual function which allows to define operations to be executed after time step.
void writeVTKFiles () const
virtual void outputXBallsData (std::ostream &os) const
This function writes the location of the walls and particles in a format the XBalls program can read. For more information on the XBalls program, see Visualising data in xballs.
virtual void outputXBallsDataParticle (unsigned int i, unsigned int format, std::ostream &os) const
This function writes out the particle locations into an output stream in a format the XBalls program can read. For more information on the XBalls program, see Visualising data in xballs.
virtual void writeEneHeader (std::ostream &os) const
Writes a header with a certain format for ENE file.
virtual void writeFstatHeader (std::ostream &os) const
Writes a header with a certain format for FStat file.
virtual void writeEneTimeStep (std::ostream &os) const
Write the global kinetic, potential energy, etc. in the system.
virtual void initialiseStatistics ()
virtual void outputStatistics ()
void gatherContactStatistics ()
virtual void processStatistics (bool)
virtual void finishStatistics ()
virtual void integrateBeforeForceComputation ()
Update particles' and walls' positions and velocities before force computation.
virtual void integrateAfterForceComputation ()
Update particles' and walls' positions and velocities after force computation.
virtual void checkInteractionWithBoundaries ()
There are a range of boundaries one could implement depending on ones' problem. This methods checks for interactions between particles and such range of boundaries. See BaseBoundary.h and all the boundaries in the Boundaries folder.
virtual void hGridActionsBeforeIntegration ()
This function has to be called before integrateBeforeForceComputation.
virtual void hGridActionsAfterIntegration ()
This function has to be called after integrateBeforeForceComputation.
void setFixedParticles (unsigned int n)
Sets a number, n, of particles in the particleHandler as "fixed particles".
virtual void printTime () const
Displays the current simulation time and the maximum simulation duration.
virtual bool continueSolve () const
A virtual function for deciding whether to continue the simulation, based on a user-specified criterion.
void outputInteractionDetails () const
Displays the interaction details corresponding to the pointer objects in the interaction handler.
bool isTimeEqualTo (Mdouble time) const
Checks whether the input variable "time" is the current time in the simulation.
void removeDuplicatePeriodicParticles ()
Removes periodic duplicate Particles.
void checkAndDuplicatePeriodicParticles ()
For simulations using periodic boundaries, checks and adds particles when necessary into the particle handler. See DPMBase.cc and PeriodicBoundary.cc for more details.
void performGhostParticleUpdate ()
When the Verlet scheme updates the positions and velocities of particles, ghost particles will need an update as wel. Their status will also be updated accordingly.
void deleteGhostParticles (std::set< BaseParticle * > &particlesToBeDeleted)
void synchroniseParticle (BaseParticle *, unsigned fromProcessor=0)
void performGhostVelocityUpdate ()
updates the final time-step velocity of the ghost particles
void disableSoftStop ()
This prevents the initialisation of the soft stop feature.
void discontinueSolve ()
This discontinues the solve loop after the current time step is finished.
Private Member Functions
void setSoftStop ()
function for setting sigaction constructor.
void initialiseVTK () const
Generates the python file for vtk visualisation. Creates vtk output directories if needed.
Static Private Member Functions
static void signalHandler (int signal)
signal handler function.
Private Attributes
bool disableSoftStop_ = false
int numberOfOMPThreads_
unsigned int systemDimensions_
The dimensions of the simulation i.e. 2D or 3D.
unsigned int particleDimensions_
determines if 2D or 3D particle volume is used for mass calculations
Vec3D gravity_
Gravity vector.
Mdouble backgroundDrag_
This is a global background drag to help retard particles, or to do a simple fluid drag. The force particleVeclocity*backgroundDrag is applied.
std::vector< unsigned > numberOfDomains_
Vector containing the number of domains in x-,y- and z-direction, required for parallel computations.
Vec3D min_
These vectors are used for the XBalls domain, and occasionally people use it to add walls.
Vec3D max_
Mdouble time_
Stores the current simulation time.
unsigned int numberOfTimeSteps_
Stores the number of time steps.
Mdouble timeStep_
Stores the simulation time step.
Mdouble timeMax_
Stores the duration of the simulation.
std::string restartVersion_
Previous versions of MercuryDPM had a different restart file format, the below member variable allows one to specify the version in order to choose between the available version support.
bool restarted_
A bool to check if the simulation was restarted or not, ie. if setupInitialConditionsShould be run and the fileCounters reset.
bool append_
A flag to determine if the file has to be appended or not. See DPMBase::Solve() for example.
bool rotation_
A flag to turn on/off particle rotation. true will enable particle rotation. false will disable particle rotation.
bool writeParticlesVTK_
A flag to turn on/off the vtk writer for particles.
bool writeSuperquadricParticlesVTK_
ParticleVtkWriter * vtkWriter_
WallVTKWriter wallVTKWriter_
InteractionVTKWriter interactionVTKWriter_
BoundaryVTKWriter boundaryVTKWriter_
WallDetailsVTKWriter wallDetailsVTKWriter_
int xBallsColourMode_
XBalls is a package to view the particle data. As an alternative MercuryDPM also supports ParaView. The below variable is used to set the argument cmode in xballs script (see XBalls/xballs.txt)
Mdouble xBallsVectorScale_
sets the xballs argument vscale (see XBalls/xballs.txt)
Mdouble xBallsScale_
sets the xballs argument scale (see XBalls/xballs.txt)
std::string xBallsAdditionalArguments_
A string of additional arguments for xballs can be specified (see XBalls/xballs.txt). e.g. "-solidf -v0".
int runNumber_
This stores the run number for saving.
std::string name_
the name of the problem, used, e.g., for the output files
bool readSpeciesFromDataFile_
Determines if the last column of the data file is interpreted as the info parameter during restart.
int nToWrite_
number of elements to write to a screen
bool forceWritePythonFileForVTKVisualisation_ { true }
Static Private Attributes
static volatile sig_atomic_t continueFlag_ = true
Detailed Description
The DPMBase header includes quite a few header files, defining all the handlers, which are essential. Moreover, it defines and solves a DPM problem. It is inherited from FilesAndRunNumber (public).
Bug:
When restarting the first time step is not saved, therefore there is a missing time step after a restart
Member Enumeration Documentation
DomainSplit
enum DPMBase::DomainSplit strong
Enumerator
X
Y
Z
XY
XZ
YZ
XYZ
 {X, Y, Z, XY, XZ, YZ, XYZ};
ReadOptions
enum DPMBase::ReadOptions : int strong
Enumerator
ReadAll
ReadNoInteractions
ReadNoParticlesAndInteractions
                            : int {
         ReadAll,
         ReadNoInteractions,
         ReadNoParticlesAndInteractions
     };
Constructor & Destructor Documentation
DPMBase() [1/2]
DPMBase::DPMBase ()
Constructor that calls the "void constructor()".
Constructor for the DPMBase class. Initialises a set of default parameters allowing a simulation to be created 'off the shelf'. For full details of the parameters initialised and their assigned values, see constructor()
                  : wallVTKWriter_(wallHandler), interactionVTKWriter_(interactionHandler), boundaryVTKWriter_(boundaryHandler),
                      wallDetailsVTKWriter_(wallHandler)
 {
 constructor();
 }
References constructor().
DPMBase() [2/2]
DPMBase::DPMBase (const DPMBase & other)
Copy constructor type-2.
A copy constructor which takes a "DPMBase"-type object and creates a "copy" - i.e. creates a new instance of a class possessing the same properties as the original.
The argument "other" is the "original", i.e. the instance to be copied from.
The first set of actions performed, which follow the general form:
[variable] = other.[variable])
simply copy the relevant variables (i.e. information such as particle details, system details, simulation details...) from the original ("other").
The various handlers belonging to the original instance, however, are not directly copied, as this may cause problems (i.e. the handlers would still "point" to the original object, not the copy).
Rather, new handlers are created (e.g. boundaryHandler.setDPMBase(this);), and the contents of the handlers is then passed over (e.g. boundaryHandler = other.boundaryHandler;). For each handler class, the assignment operator = has been overridden to copy the contents, not just the pointer.
Parameters
[in] other
                                      : wallVTKWriter_(other.wallVTKWriter_),
                                          interactionVTKWriter_(other.interactionVTKWriter_),
                                          boundaryVTKWriter_(other.boundaryVTKWriter_),
                                          wallDetailsVTKWriter_(other.wallDetailsVTKWriter_)
 {
     setName(other.getName());
     runNumber_ = other.runNumber_;
     systemDimensions_ = other.systemDimensions_;
     particleDimensions_ = other.particleDimensions_;
     gravity_ = other.gravity_;
     backgroundDrag_=other.backgroundDrag_;
 /*    xMin_ = other.xMin_;
     xMax_ = other.xMax_;
     yMin_ = other.yMin_;
     yMax_ = other.yMax_;
     zMin_ = other.zMin_;
     zMax_ = other.zMax_;*/
     min_ = other.min_;
     max_ = other.max_;
     numberOfDomains_ = other.numberOfDomains_;
     time_ = other.time_;
     timeStep_ = other.timeStep_;
     numberOfTimeSteps_ = other.numberOfTimeSteps_;
     timeMax_ = other.timeMax_;
     restartVersion_ = other.restartVersion_; //to read new and old restart data
     restarted_ = other.restarted_; //to see if it was restarted or not
     append_ = other.append_;
     rotation_ = other.rotation_;
     xBallsColourMode_ = other.xBallsColourMode_; // sets the xballs argument cmode (see xballs.txt)
     xBallsVectorScale_ = other.xBallsVectorScale_; // sets the xballs argument vscale (see xballs.txt)
     xBallsScale_ = other.xBallsScale_; // sets the xballs argument scale (see xballs.txt)
     xBallsAdditionalArguments_ = other.xBallsAdditionalArguments_; // std::string where additional xballs argument can be specified (see xballs.txt)
     writeParticlesVTK_ = other.writeParticlesVTK_;
     readSpeciesFromDataFile_ = other.readSpeciesFromDataFile_;
 //effectively saying "if there exists a CONTACT_LIST_HGRID, copy it, if not, ignore."
 #ifdef CONTACT_LIST_HGRID
 possibleContactList=other.possibleContactList;
 #endif
     random = other.random;
     boundaryHandler.setDPMBase(this);
     particleHandler.setDPMBase(this);
     interactionHandler.setDPMBase(this);
     speciesHandler.setDPMBase(this);
     wallHandler.setDPMBase(this);
     domainHandler.setDPMBase(this);
     periodicBoundaryHandler.setDPMBase(this);
     //Initialise the handlers
     domainHandler.initialise();
     periodicBoundaryHandler.initialise();
     //setting contents equal to the other handlers!
     speciesHandler = other.speciesHandler;
     particleHandler = other.particleHandler;
     cgHandler = other.cgHandler;
     //cgHandler = other.cgHandler.copy(); //\todo
     //cgHandler.setDPMBase(this);
     wallHandler = other.wallHandler;
     boundaryHandler = other.boundaryHandler;
     interactionHandler = other.interactionHandler;
     vtkWriter_ = other.vtkWriter_;
     writeSuperquadricParticlesVTK_ = other.writeSuperquadricParticlesVTK_;
     writeParticlesVTK_ = other.writeParticlesVTK_;
     numberOfOMPThreads_ = other.numberOfOMPThreads_;
 }
References append_, backgroundDrag_, boundaryHandler, cgHandler, domainHandler, getName(), gravity_, DomainHandler::initialise(), PeriodicBoundaryHandler::initialise(), interactionHandler, max_, min_, numberOfDomains_, numberOfOMPThreads_, numberOfTimeSteps_, particleDimensions_, particleHandler, periodicBoundaryHandler, random, readSpeciesFromDataFile_, restarted_, restartVersion_, rotation_, runNumber_, BaseHandler< T >::setDPMBase(), setName(), speciesHandler, systemDimensions_, time_, timeMax_, timeStep_, vtkWriter_, wallHandler, writeParticlesVTK_, writeSuperquadricParticlesVTK_, xBallsAdditionalArguments_, xBallsColourMode_, xBallsScale_, and xBallsVectorScale_.
~DPMBase()
DPMBase::~DPMBase () virtual
virtual destructor
A simple destructor for "DPMBase"-type objects, used to free-up memory when an object is no longer necessary.
 {
 delete vtkWriter_;
 }
References vtkWriter_.
Member Function Documentation
actionsAfterSolve()
void DPMBase::actionsAfterSolve () protected virtual
A virtual function which allows to define operations to be executed after the solve().
no implementation but can be overridden in its derived classes.
Reimplemented in BaseCluster, SpeciesTest, VisualisationTest, SphericalSuperQuadricCollision, EllipticalSuperQuadricCollision, EllipticalSuperQuadricCollision, EllipsoidsBouncingOnWallDemo, Contact, HertzianBSHPInteractionTwoParticleElasticCollision, PSDManualInsertionSelfTest, ParameterStudy3DDemo, ParameterStudy2DDemo, ParameterStudy1DDemo, MaserRepeatedOutInMPI2Test, ForceLawsMPI2Test, DPM, and ShearStage.
 {
 }
Referenced by finaliseSolve(), and Mercury3DRestart::writeOutputFiles().
actionsAfterTimeStep()
void DPMBase::actionsAfterTimeStep () protected virtual
A virtual function which allows to define operations to be executed after time step.
no implementation but can be overridden in its derived classes.
Reimplemented in BaseCluster, MpiPeriodicBoundaryUnitTest, DrivenParticleClass, Tutorial11, protectiveWall, MercuryProblem, ContactDetectionRotatedSpheresTest, ContactDetectionNormalSpheresTest, SphericalSuperQuadricCollision, SlidingSpheresUnitTest, GranularCollapse, EllipticalSuperQuadricCollision, EllipsoidsBouncingOnWallDemo, BouncingSuperQuadric, SphericalIndenter, DPM, DPM, PolydisperseInsertionBoundarySelfTest, NozzleSelfTest, FluxBoundarySelfTest, FluxAndPeriodicBoundarySelfTest, BoundariesSelfTest, SingleParticleSegregation, Chutebelt, RotatingDrumBidisperseInitialise, OneParticleCoolingSelfTest, OneParticleHeatingSelfTest, vibratedBed, TimeDependentPeriodicBoundaryTest, TimeDependentPeriodicBoundary3DSelfTest, ShiftingMaserBoundarySelfTest, ShiftingConstantMassFlowMaserBoundarySelfTest, PrintWallTimeMixinDemo, MinimalExampleDrum, MarbleRun, LeesEdwardsDemo, HourGlass, HourGlass2D, HourGlass2D, FreeCoolingDemoProblem, FreeCooling3DinWallsDemo, FreeCooling3DDemoProblem, FreeCooling2DinWallsDemo, CubicCell, TwoByTwoMPIDomainMPI4Test, MaserRepeatedOutInMPI2Test, NozzleDemo, RotatingDrumWet, NozzleDemo, HorizontalMixer, CFDDEMCoupleTest, ChangingTOIParticle, ChangingTOIParticle, ChangingTOIParticle, ChangingTOIParticle, ChangingTOIParticle, ChangingTOIParticle, ClosedCSCWalls, ClosedCSCRun, ClosedCSCRestart, ShearStage, GranuHeap, T_protectiveWall, Vreman, Vreman, and Vreman.
 {
 }
Referenced by ChangingTOIParticle::actionsAfterTimeStep(), and computeOneTimeStep().
actionsBeforeTimeLoop()
void DPMBase::actionsBeforeTimeLoop () protected virtual
A virtual function. Allows one to carry out any operations before the start of the time loop.
no implementation but can be overridden in its derived classes.
Reimplemented in SphericalIndenter, Slide, statistics_while_running< T >, ParameterStudy3DDemo, ParameterStudy2DDemo, ParameterStudy1DDemo, GranularJet, and GranularJet.
 {
 }
Referenced by initialiseSolve().
actionsBeforeTimeStep()
void DPMBase::actionsBeforeTimeStep () protected virtual
A virtual function which allows to define operations to be executed before the new time step.
no implementation but can be overridden in its derived classes.
Reimplemented in ChuteBottom, Chute, SaveCountUnitTest, PeriodicWallsWithSlidingFrictionUnitTest, QuaternionWallUnitTest, SphericalIndenter, RotatingDrum, DrumRot, CoilSelfTest, ConstantRestitutionSelfTest, Chutebelt, SegregationPeriodic, SegregationPeriodic, SegregationPeriodic, RotatingDrum, RotatingDrum, Slide, Slide, SegregationPeriodic, ThermalConductionSelfTest, MeltableForceLawSelfTest, MeltableForceLaw2SelfTest, statistics_while_running< T >, SilbertPeriodic, Mercury3DRestart, statistics_while_running< T >, statistics_while_running< T >, statistics_while_running< T >, SilbertPeriodic, CLiveStatistics< T >, inflowFromPeriodic, SilbertPeriodic, Restart, CLiveStatistics< T >, SilbertHstop, SilbertPeriodic, SilbertPeriodic, AngleOfRepose, statistics_while_running< T >, statistics_while_running< T >, Cstatic3D, Cstatic2d, Cstatic2d, ChutePeriodic, ForceLawsMPI2Test, Mercury3DRestart, Binary, ChuteWithPeriodicInflow, restart, free_cooling, SmoothChute, SmoothChute, DPM, AxisymmetricHopper, VariableBottom, ChutePeriodic, SegregationPeriodic, ChuteRestart, VariableBottom, ChutePeriodic, ChutePeriodic, ChutePeriodic, ChutePeriodic, LawinenBox, LawinenBox, LawinenBox, and AngleOfRepose.
 {
 }
Referenced by computeOneTimeStep(), loadingTest(), normalAndTangentialLoadingTest(), and objectivenessTest().
actionsOnRestart()
void DPMBase::actionsOnRestart () protected virtual
A virtual function where the users can add extra code which is executed only when the code is restarted.
no implementation but can be overridden in its derived classes.
Reimplemented in BaseCluster, FreeFall, DrumRot, Chutebelt, ChuteRestartDemo, and AirySavageHutter.
 {
 }
Referenced by initialiseSolve().
areInContact()
bool DPMBase::areInContact (const BaseParticle * pI, const BaseParticle * pJ) static
Checks if two particle are in contact or is there any positive overlap.
Determines whether two particles are distinct and in contact by comparing the separation of their centres to their (interaction) radii.
Firstly, checks if the two particles are different (if pI == pJ, the result is "false"). Secondly, if the two particles are distinct, finds the distance between the two particles' centres (getDistanceSquared(pI->getPosition(), pJ->getPosition()))) and tests whether the separation of the particles is less than the sum of their radii (pI->getInteractionRadius() + pJ->getInteractionRadius()). If so, the bool returns "true", i.e. the particles are in contact.
Parameters
[in] pI A pointer to a particle
[in] pJ A pointer to a second particle
Returns
bool (True or False) - lets the user know whether two particles are in contact
 {
     return (pI != pJ && pI->isInContactWith(pJ));
 }
References BaseParticle::isInContactWith().
Referenced by Mercury2D::hGridFindParticleContacts(), Mercury3D::hGridFindParticleContacts(), Mercury3D::hGridHasContactsInTargetCell(), and Mercury2D::hGridHasContactsInTargetCell().
autoNumber()
void DPMBase::autoNumber ()
The autoNumber() function calls three functions: setRunNumber(), readRunNumberFromFile() and incrementRunNumberInFile().
Using the three functions named above, the autoNumber() function acts to:
1) Use the readRunNumberFromFile() function to read the current run number from the file COUNTER_DONOTDEL created by any script which utilises auto-numbering.
2) Set the runNumber_ counter to the value obtained from the above using the setRunNumber() function.
3) Increment the value stored in the COUNTER_DONOTDEL file by one once the current value has been read using the incrementRunNumberInFile() function.
 {
 setRunNumber(readRunNumberFromFile());
 if (!getRestarted())
 {
 incrementRunNumberInFile();
 }
 }
References getRestarted(), incrementRunNumberInFile(), readRunNumberFromFile(), and setRunNumber().
Referenced by readNextArgument(), and ChutePeriodic::setup().
checkAndDuplicatePeriodicParticles()
void DPMBase::checkAndDuplicatePeriodicParticles () protected
For simulations using periodic boundaries, checks and adds particles when necessary into the particle handler. See DPMBase.cc and PeriodicBoundary.cc for more details.
For all particles in the system, checks their proximity to all periodic boundaries. If a particle is found to be near a periodic boundary, creates and adds a periodic ("ghost") particle.
 {
     //Looping over all boundaries in the boundaryHandler
     for (BaseBoundary* boundary : boundaryHandler)
     {
         //Calls the createPeriodicParticles() function which checks if a particle is adequately
         //close to a periodic particle that a periodic (ghost) particle should be created and,
         //if so, creates one and adds it to the system (hence the necessity to keep "N" variable).
         //
         // (The loop is over all boundaries, but if a boundary is not a PeriodicBoundary, then
         // this does nothing.)
         boundary->createPeriodicParticles(particleHandler);
     }
     // OMP parallelism
     /*#pragma omp parallel for num_threads(getNumberOfOMPThreads()) //schedule(dynamic)
     for (int k = 0; k < boundaryHandler.getNumberOfObjects(); k++)
     {
         //Calls the createPeriodicParticles() function which checks if a particle is adequately
         //close to a periodic particle that a periodic (ghost) particle should be created and,
         //if so, creates one and adds it to the system (hence the necessity to keep "N" variable).
         //
         // (The loop is over all boundaries, but if a boundary is not a PeriodicBoundary, then
         // this does nothing.)
         BaseBoundary* boundary = boundaryHandler.getObject(k);
         #pragma omp critical
         boundary->createPeriodicParticles(particleHandler);
     }*/
 }
References boundaryHandler, and particleHandler.
Referenced by SilbertPeriodic::add_flow_particles(), computeOneTimeStep(), and initialiseSolve().
checkInteractionWithBoundaries()
void DPMBase::checkInteractionWithBoundaries () protected virtual
There are a range of boundaries one could implement depending on ones' problem. This methods checks for interactions between particles and such range of boundaries. See BaseBoundary.h and all the boundaries in the Boundaries folder.
For each boundary, checks whether each particle in the system has "passed" it and performs an action according to the type of boundary involved.
For instance, if the boundary is a periodic boundary, the periodic boundary version of "checkBoundaryAfterParticleMoved" will be called (PeriodicBoundary::checkBoundaryAfterParticleMoved()) and in turn apply the shiftPosition() function to the particle. If the boundary is a deletion boundary (DeletionBoundary::checkBoundaryAfterParticleMoved ()), any particle passing the boundary will be deleted. Further details can be seen in the in-code comments below.
 {
     //Cycling over all boundaries within the system...
     for (BaseBoundary* b : boundaryHandler)
     {
         //check all boundaries...
         b->checkBoundaryAfterParticlesMove(particleHandler);
 #ifdef MERCURYDPM_USE_MPI
         //When ghost particles are deleted by deletion boundaries they need to be removed
         //from their communication lists to avoid segfaults
         if (NUMBER_OF_PROCESSORS > 1)
         {
             //Flush deleted particles from mpi communication zones
             getCurrentDomain()->flushParticles(b->getParticlesToBeDeleted());
             getCurrentDomain()->cleanCommunicationLists();
             periodicBoundaryHandler.flushParticles(b->getParticlesToBeDeleted());
             periodicBoundaryHandler.cleanCommunicationLists();
         }
         //Delete particles that were in communication zone
         for (auto p_it = b->getParticlesToBeDeleted().begin(); p_it != b->getParticlesToBeDeleted().end(); p_it++)
         {
             particleHandler.removeGhostObject((*p_it)->getIndex());
         }
 #endif
     }
 }
References b, boundaryHandler, Domain::cleanCommunicationLists(), PeriodicBoundaryHandler::cleanCommunicationLists(), PeriodicBoundaryHandler::flushParticles(), Domain::flushParticles(), getCurrentDomain(), NUMBER_OF_PROCESSORS, particleHandler, periodicBoundaryHandler, and ParticleHandler::removeGhostObject().
Referenced by computeOneTimeStep().
checkParticleForInteraction()
bool DPMBase::checkParticleForInteraction (const BaseParticle & p) virtual
Checks whether a particle P has any interaction with walls or other particles.
A very useful feature. For example, when one wants to have an initial condition with particles free of interactions with other particles or walls, one could use this to see if a particle about to be inserted would have interactions. If yes, then the particle would not be considered for insertion.
However can prove expensive if the number of particles is large.
Parameters
[in] p The particle for which one wants to detect collisions (or the lack thereof).
Returns
true if and only if there are no interactions with other particles or walls.
Reimplemented in MercuryBase.
 {
 #ifdef MERCURYDPM_USE_MPI
     if (NUMBER_OF_PROCESSORS == 1)
     {
         return checkParticleForInteractionLocalPeriodic(p);
     }
     int localInteraction = checkParticleForInteractionLocal(p);
     //The root gathers all values and computes the global value
     int *interactionList = nullptr;
     if (PROCESSOR_ID == 0)
     {
         interactionList = new int [NUMBER_OF_PROCESSORS];
     }
     //Gather all local values
     MPIContainer::Instance().gather(localInteraction,interactionList);
     //Compute the global value
     int globalInteraction = 1;
     if (PROCESSOR_ID == 0)
     {
         for (int i = 0; i < NUMBER_OF_PROCESSORS; i++)
         {
             if (interactionList[i] == 0)
             {
                 globalInteraction = 0;
                 break;
             }
         }
     }
     //The root now tells the other processors what the global value for the interaction is
     MPIContainer::Instance().broadcast(globalInteraction);
     //Convert the result back to bool
     bool interaction = globalInteraction;
 #else
     bool interaction = checkParticleForInteractionLocalPeriodic(p);
 #endif
     return interaction;
 }
References MPIContainer::broadcast(), checkParticleForInteractionLocal(), checkParticleForInteractionLocalPeriodic(), MPIContainer::gather(), i, MPIContainer::Instance(), NUMBER_OF_PROCESSORS, p, and PROCESSOR_ID.
checkParticleForInteractionLocal()
bool DPMBase::checkParticleForInteractionLocal (const BaseParticle & p) virtual
Checks if a particle P has any interaction with walls or other particles in the local domain.
A very useful feature. For example, when one wants to have an initial condition with particles free of interactions with other particles or walls, one could use this method and whether particles are interacting. If yes, then it would not consider this particle for insertion and continue onto the next particle. However can prove expensive if the number of particles is large.
Returns true if and only if there are no interactions with other particles in the local domain or walls.
Parameters
[in] p The particle for which one wants to detect collisions (or the lack thereof).
Returns
bool - true if particle P has no interactions, false if P has one or more interactions with other particles or walls.
Todo:
tw check against periodic copies (see ShearCell3DInitialConditions.cpp)
Reimplemented in MercuryBase.
 {
     Mdouble distance;
     Vec3D normal;
     //Check if it has no collision with walls
     for (BaseWall* w : wallHandler)
     {
         //returns false if the function getDistanceAndNormal returns true,
         //i.e. if there exists an interaction between wall and particle
         // \todo TW getDistanceAndNormal(p,distance,normal) should ideally be replaced by a inContact(p) function, as it doesn't require distance and normal for anything (and walls now can have multiple contacts, soon particles can have it too.)
         if (w->getDistanceAndNormal(p, distance, normal))
         {
             //std::cout<<"failure: Collision with wall: "<<**it<<std::endl;
             return false;
         }
         else
         {
             //std::cout<<"No collision with wall: "<<**it<<std::endl;
         }
     }
     //Check if it has no collision with other particles
     for (BaseParticle* q : particleHandler)
     {
         //returns false if the particle separation is less than the relevant sum of interaction radii
         //(i.e. another particle is in contact with P)
         if (Vec3D::getDistanceSquared(q->getPosition(), p.getPosition())
             < mathsFunc::square(p.getSumOfInteractionRadii(q)))
         {
             //std::cout<<"failure: Collision with particle "<<**it<<std::endl;
             return false;
         }
         else
         {
             //std::cout<<"No collision with particle "<<**it<<std::endl;
         }
     }
     return true;
 }
References Vec3D::getDistanceSquared(), WallFunction::normal(), p, particleHandler, Eigen::numext::q, mathsFunc::square(), w, and wallHandler.
Referenced by checkParticleForInteraction(), and checkParticleForInteractionLocalPeriodic().
checkParticleForInteractionLocalPeriodic()
bool DPMBase::checkParticleForInteractionLocalPeriodic (const BaseParticle & p)
Extends the capability of detecting intersecting particles to periodic systems
Todo:
TW the implementation of this function is not very efficient and should be improved
Parameters
p
Returns
 {
     //A vector of ghost particles of the particle that is to be inserted (empty if no periodic boundaries are present)
     std::vector<Vec3D> pPeriodic;
     for (BaseBoundary* b : boundaryHandler)
     {
         PeriodicBoundary* pb = dynamic_cast<PeriodicBoundary*>(b);
         if (pb && particleHandler.getNumberOfObjects() > 0 )
         {
             const Mdouble maxDistance = p.getMaxInteractionRadius() + particleHandler.getLargestParticle()->getMaxInteractionRadius();
             for (int i = pPeriodic.size() - 1; i >= 0; --i)
             {
                 if (pb->getDistance(pPeriodic[i]) < maxDistance)
                 {
                     pPeriodic.push_back(pPeriodic[i]);
                     pb->shiftPosition(pPeriodic.back());
                 }
             }
             if (pb->getDistance(p) < maxDistance)
             {
                 pPeriodic.push_back(p.getPosition());
                 pb->shiftPosition(pPeriodic.back());
             }
         }
     }
     //check the particle AND the ghost particles for intersection problems
     bool insertable = checkParticleForInteractionLocal(p);
     if (!pPeriodic.empty()) {
         BaseParticle* q = p.copy();
         for (const Vec3D& pos : pPeriodic) {
             q->setPosition(pos);
             insertable &= checkParticleForInteractionLocal(*q);
         }
         delete q;
     }
     return insertable;
 }
References b, boundaryHandler, checkParticleForInteractionLocal(), ParticleHandler::getLargestParticle(), BaseParticle::getMaxInteractionRadius(), ParticleHandler::getNumberOfObjects(), i, p, particleHandler, pb, and Eigen::numext::q.
Referenced by checkParticleForInteraction(), and MercuryBase::checkParticleForInteraction().
checkSettings()
void DPMBase::checkSettings ()
Checks if the essentials are set properly to go ahead with solving the problem.
Checks if at least one species exists in the SpeciesHandler.
Checks if the time step is set or not.
If any of the above checks fail, gives an error message to the user and terminates the program.
 {
     //check if name is set
     logger.assert_always(getName() != "",
                          "File name not set: use setName()");
     //check if time step is set
     logger.assert_always(getTimeStep() != 0,
                          "Time step undefined: use setTimeStep()");
     //check if domain is set
     logger.assert_always(getXMax() > getXMin(),
                          "Domain size not set: use setXMin() and setXMax()");
     logger.assert_always(getYMax() > getYMin(),
                          "Domain size not set: use setYMin() and setYMax()");
     logger.assert_always(systemDimensions_ == 3 ? (getZMax() > getZMin()) : (getZMax() >= getZMin()),
                          "Domain size not set: use setZMin() and setZMax()", systemDimensions_);
     //check for species parameters
     logger.assert_always(speciesHandler.getNumberOfObjects() > 0,
                          "No species defined: use speciesHandler.copyAndAddObject()");
     for (BaseParticle* p : particleHandler)
     {
         logger.assert_always(p->getSpecies() != nullptr, "particle % has no species", p->getId());
     }
     for (BaseWall* w : wallHandler)
     {
         logger.assert_always(w->getSpecies() != nullptr, "% with index % has no species", w->getName(), w->getId());
     }
 }
References getName(), BaseHandler< T >::getNumberOfObjects(), getTimeStep(), getXMax(), getXMin(), getYMax(), getYMin(), getZMax(), getZMin(), logger, p, particleHandler, speciesHandler, systemDimensions_, w, and wallHandler.
Referenced by initialiseSolve().
closeFiles()
void DPMBase::closeFiles ()
Closes all files (ene, data, fstat, restart, stat) that were opened to read or write.
 {
 dataFile.close();
 fStatFile.close();
 restartFile.close();
 statFile.close();
 eneFile.close();
 interactionFile.close();
 }
References File::close(), dataFile, eneFile, fStatFile, interactionFile, restartFile, and statFile.
Referenced by finaliseSolve(), and Mercury3DRestart::writeOutputFiles().
computeAdditionalForces()
virtual void DPMBase::computeAdditionalForces () inline protected virtual
A virtual function which allows to define operations to be executed prior to the OMP force collect.
no implementation but can be overridden in its derived classes. This function is called by DPMBase::computeAllForces. It may be used to add additional user defined forces to any MercuryObject. Within this function, OMP parallelization may be used, as it is called prior to sumForceTorqueOMP.
Reimplemented in MembraneSelfTest, SingleParticleSegregation, and MembraneDemo.
 {}
Referenced by computeAllForces().
computeAllForces()
void DPMBase::computeAllForces () protected virtual
Computes all the forces acting on the particles using the BaseInteractable::setForce() and BaseInteractable::setTorque()
Initially, resets all forces to zero for all particles and all walls. For each particle in turn, the function searches for particle interactions, and computes the relevant internal forces, followed by the relevant external forces (e.g. gravity).
Now loop over all particles contacts computing force contributions
Reimplemented in DPM, and Mercury3Dclump.
 {
     //Resetting all forces on both particles and walls to zero
     #pragma omp parallel num_threads(getNumberOfOMPThreads())
     {
         #pragma omp for
         for (int k = 0; k < particleHandler.getSize(); ++k) {
             particleHandler.getObject(k)->resetForceTorque(getNumberOfOMPThreads());
         }
         #pragma omp for
         for (int k = 0; k < wallHandler.getSize(); k++) {
             wallHandler.getObject(k)->resetForceTorque(getNumberOfOMPThreads());
         }
     }
     logger(DEBUG,"All forces set to zero");
     // for omp simulations, reset the newObjects_ variable (used for reduction)
     interactionHandler.resetNewObjectsOMP();
     // compute all internal and external forces; for omp simulations, this can be done in parallel
     #pragma omp parallel num_threads(getNumberOfOMPThreads())
     {
         //logger(INFO, "Number of omp threads = %", getNumberOfOMPThreads());
         #pragma omp for schedule(dynamic)
         for (int k = 0; k < particleHandler.getSize(); ++k) {
             BaseParticle *p = particleHandler.getObject(k);
             //computing both internal forces (e.g. due to collisions)
             //and external forces (e.g. gravity)
             //(compute internal forces compares the current particle p
             //with all others in the handler!)
             computeInternalForces(p);
             // body forces
             computeExternalForces(p);
         }
         // wall-forces
         #pragma omp for schedule(dynamic)
         for (int k = 0; k < wallHandler.getSize(); k++) {
             BaseWall *w = wallHandler.getObject(k);
             computeWallForces(w);
             w->computeWear();
         }
     }
     #ifdef MERCURYDPM_TRIANGLE_WALL_CORRECTION
     // This statement deals with interactions of a particle with a group of walls:
     // If there are multiple contact forces between the particle and the group of walls, we assume that these contacts share a concave edge or a vertex. Thus, we multiply each force by a weight $w_{\alpha\gamma}=|\vec{f}_{\alpha\gamma}^{\text{w}}|/\sum_\gamma|\vec{f}_{\alpha\gamma}^{\text{w}}|$. Note that these weights add up to 1, thus, the total contact force between the particle and the group of walls will be a weighted average of the individual contact forces.
     // A second modification is done in #BaseWall::getInteractionWith
     for (BaseParticle *p : particleHandler) {
         // find all current interactions between this particle and a TriangleWall
         std::vector<BaseInteraction *> wallInters;
         double overlapSum = 0.0;
         for (const auto i : p->getInteractions()) {
             if (i->getI()->getName() == "TriangleWall" && i->getTimeStamp() > getNumberOfTimeSteps()) {
                 wallInters.push_back(i);
                 overlapSum += i->getOverlap();
             }
         }
         // if more than one interactions are detected, we have a concave wall interaction problem.
         if (wallInters.size() > 1) {
             // get the multiple contact points to define the new contact plane, normal, and overlap
             for (BaseInteraction *i : wallInters) {
                 auto q = i->getI();
                 // undo the force/torque computation from multiple TriangleWalls
                 p->addForce(-i->getForce());
                 q->addForce(i->getForce());
                 if (getRotation()) {
                     p->addTorque(-i->getTorque() + Vec3D::cross(p->getPosition() - i->getContactPoint(), i->getForce()));
                     q->addTorque( i->getTorque() - Vec3D::cross(q->getPosition() - i->getContactPoint(), i->getForce()));
                 }
                 // reset the forces
                 double w = i->getOverlap() / overlapSum;
                 i->setContactPoint(p->getPosition() - (p->getRadius() - 0.5 * i->getOverlap()) * w * i->getNormal());
                 i->setForce(i->getForce() * w);
                 i->setTorque(i->getTorque() * w);
                 // applies the reset forces to the particle and the wall
                 p->addForce(i->getForce());
                 q->addForce(-i->getForce());
                 if (getRotation()) {
                     p->addTorque( i->getTorque() - Vec3D::cross(p->getPosition() - i->getContactPoint(), i->getForce()));
                     q->addTorque(-i->getTorque() + Vec3D::cross(q->getPosition() - i->getContactPoint(), i->getForce()));
                 }
             }
         }
     }
     #endif
 #ifdef CONTACT_LIST_HGRID
     PossibleContact* Curr=possibleContactList.getFirstPossibleContact();
     while(Curr)
     {
         computeInternalForces(Curr->getP1(),Curr->getP2());
         Curr=Curr->getNext();
     }
 #endif
     // Check wall forces
     #pragma omp for schedule(dynamic)
     for (int k = 0; k < wallHandler.getNumberOfObjects(); k++) {
         BaseWall *w = wallHandler.getObject(k);
         w->checkInteractions(&interactionHandler, getNumberOfTimeSteps() + 1);
     }
     computeAdditionalForces();
     // for omp simulations, sum up all forces and add all newObjects_ (needed since both are using reduction)
     #ifdef MERCURYDPM_USE_OMP
     if (getNumberOfOMPThreads()>1) {
         interactionHandler.addNewObjectsOMP();
     }
     //Resetting all forces on both particles and walls to zero
     #pragma omp parallel num_threads(getNumberOfOMPThreads())
     {
         #pragma omp for
         for (int k = 0; k < particleHandler.getSize(); k++) {
             particleHandler.getObject(k)->sumForceTorqueOMP();
         }
         #pragma omp for
         for (int k = 0; k < wallHandler.getSize(); k++) {
             wallHandler.getObject(k)->sumForceTorqueOMP();
         } //end reset forces loop
     }
     #endif
     //end outer loop over contacts.
 }
References InteractionHandler::addNewObjectsOMP(), computeAdditionalForces(), computeExternalForces(), computeInternalForces(), computeWallForces(), Vec3D::cross(), DEBUG, PossibleContact::getNext(), BaseHandler< T >::getNumberOfObjects(), getNumberOfOMPThreads(), getNumberOfTimeSteps(), BaseHandler< T >::getObject(), PossibleContact::getP1(), PossibleContact::getP2(), getRotation(), BaseHandler< T >::getSize(), i, interactionHandler, k, logger, p, particleHandler, Eigen::numext::q, BaseInteractable::resetForceTorque(), InteractionHandler::resetNewObjectsOMP(), BaseInteractable::sumForceTorqueOMP(), w, and wallHandler.
Referenced by Mercury3Dclump::computeAllForces(), DPM::computeAllForces(), computeOneTimeStep(), initialiseSolve(), and ExtremeOverlapVolumeUnitTest::setupInitialConditions().
computeExternalForces()
void DPMBase::computeExternalForces (BaseParticle * CI) protected virtual
Computes the external forces, such as gravity, acting on particles.
By default we have gravity and background drag as the external forces
Parameters
[in] CI The BaseParticle object to which the relevant external forces are applied.
Reimplemented in ScaleCoupling< Mercury3D, SolidProblem< ScaleCoupledElement< ELEMENT > > >, AngledPeriodicBoundarySecondUnitTest, SphericalIndenter, CFDDEMCoupleTest, my_problem, my_problem, PeriodicWalls, and Contact.
 {
     //Checks that the current particle is not "fixed"
     //and hence infinitely massive!
     if ((!CI->isFixed()) && (!CI->isPebble()))
     {
         // Applying the force due to gravity (F = m.g) Do not apply gravity to slave particles
         CI->addForce(getGravity() * CI->getMass()-getBackgroundDrag()*CI->getVelocity());
         // Still calls this in compute External Forces.
         // computeForcesDueToWalls(CI);
     }
 }
References BaseInteractable::addForce(), getBackgroundDrag(), getGravity(), BaseParticle::getMass(), BaseInteractable::getVelocity(), BaseParticle::isFixed(), and BaseParticle::isPebble().
Referenced by computeAllForces(), DPM::computeAllForcesNoHGrid(), Contact::computeExternalForces(), CFDDEMCoupleTest::computeExternalForces(), and SphericalIndenter::computeExternalForces().
computeForcesDueToWalls()
void DPMBase::computeForcesDueToWalls (BaseParticle * pI, BaseWall * w) protected virtual
Computes the forces on the particles due to the walls (normals are outward normals)
Checks if a particle pI is currently in contact - i.e. interacting - with any of the walls within the system using the BaseParticle::getInteractionWith() function. If an interaction is detected, computes the force acting between particle and wall and applies the relevant torques and forces to both particle and wall(s).
Parameters
[in] pI The BaseParticle object to which the wall forces are applied.
Todo:
TW: I think this torque has the wrong sign
Reimplemented in Mercury3Dclump.
 {
     //No need to compute interactions between periodic particle images and walls
     if (pI->getPeriodicFromParticle() != nullptr)
         return;
     //Checks if the particle is interacting with the current wall
     BaseInteraction* i = w->getInteractionWith(pI, getNumberOfTimeSteps() + 1,
                                                &interactionHandler);
     if (i!=nullptr) {
         //...calculates the forces between the two objects...
         i->computeForce();
         //...and applies them to each of the two objects (wall and particle).
         pI->addForce(i->getForce());
         w->addForce(-i->getForce());
         //If the rotation flag is on, also applies the relevant torques
         //(getRotation() returns a boolean).
         if (getRotation()) // getRotation() returns a boolean.
         {
             pI->addTorque(i->getTorque() - Vec3D::cross(pI->getPosition() - i->getContactPoint(), i->getForce()));
             w->addTorque(-i->getTorque() + Vec3D::cross(w->getPosition() - i->getContactPoint(), i->getForce()));
         }
     }
 }
References BaseInteractable::addForce(), BaseInteractable::addTorque(), Vec3D::cross(), getNumberOfTimeSteps(), BaseParticle::getPeriodicFromParticle(), BaseInteractable::getPosition(), getRotation(), i, interactionHandler, and w.
Referenced by DPM::computeAllForcesNoHGrid(), Mercury3Dclump::computeForcesDueToWalls(), computeWallForces(), Mercury3D::computeWallForces(), and ArcWallUnitTest::setupInitialConditions().
computeInternalForce()
void DPMBase::computeInternalForce (BaseParticle * P1, BaseParticle * P2) protected virtual
Computes the forces between two particles (internal in the sense that the sum over all these forces is zero i.e. fully modelled forces)
Firstly, checks the types of particles involved in order to ensure that only viable interactions are counted.
Secondly, if the particle combination is viable, checks if the particles are interacting.
Finally, if the particles are found to be interacting, calculates the relevant forces (as well as torques, if the "rotation" flag is turned "on") acting between the particles, and applies them to each particle.
Parameters
[in] P1
[in] P2
Reimplemented in Mercury3Dclump.
 {
     //Does not compute forces if particles are fixed
     //this is necessary because the rough bottom allows overlapping fixed particles
     if (P1->isFixed() && P2->isFixed())
     {
         return;
     }
 //Ensures that interactions between the "ghost" particles used to implement periodic behaviour
     //are not included in calculations
     //i.e. ends the function if both particles are "ghosts".
     if ((P1->getPeriodicFromParticle() != nullptr) && (P2->getPeriodicFromParticle() != nullptr))
     {
         return;
     }
 //if statement below ensures that the PI has the lower id than PJ
     BaseParticle* PI, * PJ;
     if (P1->getId() > P2->getId())
     {
         PI = P2;
         PJ = P1;
     }
     else
     {
         PI = P1;
         PJ = P2;
     }
     //checks if the two particles are interacting
     //("getInteractionWith" returns the relevant pointer if PI and PJ are interacting,
     //zero if not)
     //if statement above ensures that the PI has the lower id than PJ
     BaseInteraction* i = PJ->getInteractionWith(PI, getNumberOfTimeSteps() + 1,
                                                 &interactionHandler);
     if (i!= nullptr) {
         //calculates the force corresponding to the interaction
         i->computeForce();
         //Applies the relevant calculated forces to PI and PJ
         PI->addForce(i->getForce());
         PJ->addForce(-i->getForce());
         //checks if particle rotation is turned on...
         if (getRotation()) {
             //...and, if so, performs equivalent calculations for the torque as were
             //performed for the force.
             PI->addTorque(i->getTorque() - Vec3D::cross(PI->getPosition() - i->getContactPoint(), i->getForce()));
             PJ->addTorque(-i->getTorque() + Vec3D::cross(PJ->getPosition() - i->getContactPoint(), i->getForce()));
         }
     }
 }
References BaseInteractable::addForce(), BaseInteractable::addTorque(), Vec3D::cross(), BaseObject::getId(), BaseParticle::getInteractionWith(), getNumberOfTimeSteps(), BaseParticle::getPeriodicFromParticle(), BaseInteractable::getPosition(), getRotation(), i, interactionHandler, and BaseParticle::isFixed().
Referenced by DPM::computeAllForcesNoHGrid(), SphericalIndenter::computeExternalForces(), Mercury3Dclump::computeInternalForce(), computeInternalForces(), Mercury3D::hGridFindContactsWithinTargetCell(), Mercury2D::hGridFindContactsWithinTargetCell(), Mercury3D::hGridFindContactsWithTargetCell(), and Mercury2D::hGridFindContactsWithTargetCell().
computeInternalForces()
void DPMBase::computeInternalForces (BaseParticle * i) protected virtual
Computes the internal forces on particle i (internal in the sense that the sum over all these forces is zero i.e. fully modelled forces)
Taking a single BaseParticle object as an argument, passes it to the broadPhase() function which then loops over all other particles in the particleHandler and computes the relevant forces for any particle pairing found to be in contact.
Parameters
[in] i A BaseParticle object for which we want to calculate the internal forces.
Reimplemented in Mercury3D, Mercury2D, my_problem_HGRID, and my_problem.
 {
     for (auto it = particleHandler.begin(); (*it) != i; ++it)
     {
         computeInternalForce(i, *it);
     }
 }
References BaseHandler< T >::begin(), computeInternalForce(), i, and particleHandler.
Referenced by computeAllForces().
computeOneTimeStep()
void DPMBase::computeOneTimeStep () virtual
Performs everything needed for one time step, used in the time-loop of solve().
Todo:
IFCD @AT, TW: please check what should be in here, and whether it should be virtual or not.
Performs one time step in the time loop, including updating the time. It is made public, since this makes coupling multiple DPM simulations easier in the future.
Todo:
MX: this is not true anymore. all boundaries are handled here. particles have received a position update, so here the deletion boundary deletes particles
Todo:
add particles need a periodic check
Bug:
{In chute particles are added in actions_before_time_set(), however they are not written to the xballs data yet, but can have a collision and be written to the fstat data}
 {
     logger(DEBUG, "starting computeOneTimeStep()");
     logger(DEBUG, "about to call writeOutputFiles()");
     writeOutputFiles(); //everything is written at the beginning of the time step!
     logger(DEBUG, "about to call hGridActionsBeforeIntegration()");
     hGridActionsBeforeIntegration();
     //Computes the half-time step velocity and full time step position and updates the particles accordingly
     logger(DEBUG, "about to call integrateBeforeForceComputation()");
     integrateBeforeForceComputation();
     //New positions require the MPI and parallel periodic boundaries to do things
     logger(DEBUG, "about to call performGhostParticleUpdate()");
     performGhostParticleUpdate();
     // Some walls need to be aware of the new positions
     wallHandler.actionsAfterParticleGhostUpdate();
     logger(DEBUG, "about to call checkInteractionWithBoundaries()");
     checkInteractionWithBoundaries(); // INSERTION boundaries handled
     logger(DEBUG, "about to call hGridActionsAfterIntegration()");
     hGridActionsAfterIntegration();
     // Compute forces
     // INSERTION/DELETION boundary flag change
     for (BaseBoundary* b : boundaryHandler)
     {
         b->checkBoundaryBeforeTimeStep(this);
     }
     logger(DEBUG, "about to call actionsBeforeTimeStep()");
     actionsBeforeTimeStep();
     particleHandler.actionsBeforeTimeStep();
     //interactionHandler.actionsBeforeTimeStep();
     logger(DEBUG, "about to call checkAndDuplicatePeriodicParticles()");
     checkAndDuplicatePeriodicParticles();
     logger(DEBUG, "about to call hGridActionsBeforeTimeStep()");
     hGridActionsBeforeTimeStep();
     //Creates and updates interactions and computes forces based on these
     logger(DEBUG, "about to call computeAllForces()");
     computeAllForces();
     logger(DEBUG, "about to call removeDuplicatePeriodicParticles()");
     removeDuplicatePeriodicParticles();
     logger(DEBUG, "about to call actionsAfterTimeStep()");
     actionsAfterTimeStep();
     //Computes new velocities and updates the particles accordingly
     logger(DEBUG, "about to call integrateAfterForceComputation()");
     integrateAfterForceComputation();
     //erase interactions that have not been used during the last time step
     //logger(DEBUG, "about to call interactionHandler.eraseOldInteractions(getNumberOfTimeSteps())");
     interactionHandler.eraseOldInteractions(getNumberOfTimeSteps());
     logger(DEBUG, "about to call interactionHandler.actionsAfterTimeStep()");
     interactionHandler.actionsAfterTimeStep();
     particleHandler.actionsAfterTimeStep();
     time_ += timeStep_;
     numberOfTimeSteps_++;
     logger(DEBUG, "finished computeOneTimeStep()");
 }
References WallHandler::actionsAfterParticleGhostUpdate(), actionsAfterTimeStep(), InteractionHandler::actionsAfterTimeStep(), ParticleHandler::actionsAfterTimeStep(), actionsBeforeTimeStep(), ParticleHandler::actionsBeforeTimeStep(), b, boundaryHandler, checkAndDuplicatePeriodicParticles(), checkInteractionWithBoundaries(), computeAllForces(), DEBUG, InteractionHandler::eraseOldInteractions(), getNumberOfTimeSteps(), hGridActionsAfterIntegration(), hGridActionsBeforeIntegration(), hGridActionsBeforeTimeStep(), integrateAfterForceComputation(), integrateBeforeForceComputation(), interactionHandler, logger, numberOfTimeSteps_, particleHandler, performGhostParticleUpdate(), removeDuplicatePeriodicParticles(), time_, timeStep_, wallHandler, and writeOutputFiles().
Referenced by solve().
computeWallForces()
void DPMBase::computeWallForces (BaseWall * w) virtual
Reimplemented in Mercury3D.
 {
     //compute forces for all particles that are neither fixed nor ghosts
     for (auto p : particleHandler)
     {
         if (!p->isFixed() && p->getPeriodicFromParticle() == nullptr)
         {
             //w->computeForces(p);
             computeForcesDueToWalls(p, w);
         }
     }
 }
References computeForcesDueToWalls(), p, particleHandler, and w.
Referenced by computeAllForces(), and Mercury3D::computeWallForces().
constructor()
void DPMBase::constructor ()
A function which initialises the member variables to default values, so that the problem can be solved off the shelf; sets up a basic two dimensional problem which can be solved off the shelf. It is called in the constructor DPMBase().
A simple vector of vectors for collecting and ordering interactions in the OpenMP parallel environment
Provides all the necessary default values for the DPMBase() constructor. When called, will initialise a two-dimensional simulation (setSystemDimensions(2), setParticleDimensions(2)) with "normal" vertical gravity (gravity_ = Vec3D(0.0, -9.8, 0.0);) as well as defining an arbitrary length (1s) and XBalls viewing domain (0.01 x 0.01) and other relevant viewing parameters (e.g. colourscheme, scale...). The first block of text creates the necessary handlers and sets their content according to the current ("this") instance of the DPMBase superclass.
 {
     //constructor();
     dataFile.getFstream().precision(10);
     fStatFile.getFstream().precision(10);
     eneFile.getFstream().precision(10);
     restartFile.getFstream().precision(
             std::numeric_limits<double>::digits10); //highly accurate, so the overlap is accurate
     statFile.getFstream().precision(10);
     statFile.getFstream().setf(std::ios::left);
     interactionFile.getFstream().precision(10);
     name_ = ""; // needs to be user-specified, otherwise checkSettings throws error
     //by default, the fileType of all files is ONE_FILE. However, by default we don't want an interaction file since it
     // is very large.
     interactionFile.setFileType(FileType::NO_FILE);
     runNumber_ = 0;
     //Decomposition direction for MPI
     numberOfDomains_ = {1, 1, 1};
     //Check if MPI is already initialised
     initialiseMPI();
     //This sets the maximum number of particles
     boundaryHandler.setDPMBase(this);
     periodicBoundaryHandler.setDPMBase(this);
     speciesHandler.setDPMBase(this);
     particleHandler.setDPMBase(this);
     cgHandler.setDPMBase(this);
     interactionHandler.setDPMBase(this);
     wallHandler.setDPMBase(this);
     interactionHandler.setDPMBase(this);
     domainHandler.setDPMBase(this);
     domainHandler.initialise();
     periodicBoundaryHandler.setDPMBase(this);
     periodicBoundaryHandler.initialise();
     //set defaults for DPMBase parameters
     setSystemDimensions(3);
     setParticleDimensions(3);
     setRestarted(false);
     setGravity(Vec3D(0, 0, 0));
     setBackgroundDrag(0.0);
     //This is the parameter of the numerical part
     setTime(0);
     numberOfTimeSteps_ = 0;
     setTimeMax(0);
     timeStep_ = 0; // needs to be user-specified, otherwise checkSettings throws error
     setSaveCount(20);
     //This sets the default xballs domain
     min_ = Vec3D(0, 0, 0);
     max_ = Vec3D(0, 0, 0); // needs to be user-specified, otherwise checkSettings throws error
     //sets the default write particles data in VTK format flag to false
     writeParticlesVTK_ = false;
     writeSuperquadricParticlesVTK_ = false;
     vtkWriter_ = nullptr;
     setName(""); // needs to be user-specified, otherwise checkSettings throws error
     //Default mode is energy with no scale of the vectors
     xBallsColourMode_ = 0;
     xBallsVectorScale_ = -1;
     xBallsScale_ = -1;
     xBallsAdditionalArguments_ = "";
     setAppend(false);
     //The default random seed is 0
     random.setRandomSeed(0);
     logger(DEBUG, "DPMBase problem constructor finished");
     readSpeciesFromDataFile_ = false;
     numberOfOMPThreads_ = 1;
     //Set number of elements to write to the screen if a user wants to output write information to the terminal
     nToWrite_ = 4;
 }
References boundaryHandler, cgHandler, dataFile, DEBUG, domainHandler, eneFile, fStatFile, File::getFstream(), DomainHandler::initialise(), PeriodicBoundaryHandler::initialise(), initialiseMPI(), interactionFile, interactionHandler, logger, max_, min_, name_, NO_FILE, nToWrite_, numberOfDomains_, numberOfOMPThreads_, numberOfTimeSteps_, particleHandler, periodicBoundaryHandler, random, readSpeciesFromDataFile_, restartFile, runNumber_, setAppend(), setBackgroundDrag(), BaseHandler< T >::setDPMBase(), File::setFileType(), setGravity(), setName(), setParticleDimensions(), RNG::setRandomSeed(), setRestarted(), setSaveCount(), setSystemDimensions(), setTime(), setTimeMax(), speciesHandler, statFile, timeStep_, vtkWriter_, wallHandler, writeParticlesVTK_, writeSuperquadricParticlesVTK_, xBallsAdditionalArguments_, xBallsColourMode_, xBallsScale_, and xBallsVectorScale_.
Referenced by DPMBase().
continueSolve()
bool DPMBase::continueSolve () const protected virtual
A virtual function for deciding whether to continue the simulation, based on a user-specified criterion.
Alternatively, the discontinueSolve function can be used as well, which can be called directly from any place in the code.
Used within the main loop of the 'solve()' routine to let the code know whether or not the time step should continue to be advanced, i.e. whether the simulation should be continued. By default this is always true but the user may redefine it to return false under certain desired circumstances.
Returns
bool (True or False)
Reimplemented in protectiveWall, ScalingTestInitialConditionsRelax, ScalingTestInitialConditionsRelax, DPM, InitialConditions< SpeciesType >, RotatingDrumBidisperseInitialise, InitialBed, SilbertHstop, SilbertHstop, SilbertHstop, SilbertHstop, SilbertHstop, CSCWalls, CSCInit, ClosedCSCWalls, and T_protectiveWall.
 {
     return true;
 }
Referenced by solve().
decompose()
void DPMBase::decompose () virtual
Sends particles from processorId to the root processor.
Decomposes the simulation domain in a structured cube mesh of domains for parallel processing
This function takes the simulation domain boundaries and decomposes it into sub domains ready for parallel computations
 {
 #ifdef MERCURYDPM_USE_MPI
     //If running in parallel build, but just running with one core - no domain decomposition required
     int numberOfRequiredProcessors = numberOfDomains_[Direction::XAXIS]*
                                      numberOfDomains_[Direction::YAXIS]*
                                      numberOfDomains_[Direction::ZAXIS];
     if (NUMBER_OF_PROCESSORS != numberOfRequiredProcessors)
     {
         logger(ERROR,"The domain decompositions expects % processors, but only % are requested.\n"
                      "Either run your process using \"mpirun -np % [executable]\", "
                      "or change the domain decomposition to e.g. setNumberOfDomains({%,1,1}).", numberOfRequiredProcessors, NUMBER_OF_PROCESSORS, numberOfRequiredProcessors, NUMBER_OF_PROCESSORS);
     }
     if (NUMBER_OF_PROCESSORS == 1) {return;}
     //Check if the simulation domain has been set
     logger.assert_always(getXMax() - getXMin() > 0,"Please set your simulation domain (setXMax(),setXmin()) before calling solve()");
     logger.assert_always(getYMax() - getYMin() > 0,"Please set your simulation domain (setYMax(),setYmin()) before calling solve()");
     logger.assert_always(getZMax() - getZMin() > 0,"Please set your simulation domain (setZMax(),setZmin()) before calling solve()");
     //Grab simulation domains
     std::vector<Mdouble> simulationMin{getXMin(), getYMin(), getZMin()};
     std::vector<Mdouble> simulationMax{getXMax(), getYMax(), getZMax()};
     //Check if the user input decomposition is correct
     logger.assert_always(numberOfDomains_[Direction::XAXIS] > 0,"Number of domain in x-direction incorrect: %",numberOfDomains_[Direction::XAXIS]);
     logger.assert_always(numberOfDomains_[Direction::YAXIS] > 0,"Number of domain in y-direction incorrect: %",numberOfDomains_[Direction::YAXIS]);
     logger.assert_always(numberOfDomains_[Direction::ZAXIS] > 0,"Number of domain in z-direction incorrect: %",numberOfDomains_[Direction::ZAXIS]);
     //Open domain decomposition, closed is not implemented
     bool open = true;
     //Check if the number of domains is equal to the number of processors
     logger.assert_always(numberOfDomains_[Direction::XAXIS]*numberOfDomains_[Direction::YAXIS]*numberOfDomains_[Direction::ZAXIS] == NUMBER_OF_PROCESSORS,
              "Number of Processors is not equal to number of domains.    Processors %, domains, %",
              NUMBER_OF_PROCESSORS,
              numberOfDomains_[Direction::XAXIS]*numberOfDomains_[Direction::YAXIS]*numberOfDomains_[Direction::ZAXIS]);
     //Create all processor domains
     domainHandler.setDPMBase(this);
     domainHandler.createMesh(simulationMin, simulationMax, numberOfDomains_, open);
     logger(VERBOSE,"Number of domains: % | Number of processors: %",domainHandler.getNumberOfObjects(), NUMBER_OF_PROCESSORS);
     //logger.assert_always(domainHandler.getNumberOfObjects() == numberOfProcessors, "Invalid decomposition: Number of domains and processors are different");
     //Tell the current processor to which domain it belongs
     for (Domain* domain : domainHandler)
     {
         if (domain->getRank() == PROCESSOR_ID)
         {
             logger(VERBOSE,"processor: %, domain index: %",PROCESSOR_ID, domain->getIndex());
             domainHandler.setCurrentDomainIndex(domain->getIndex());
         }
     }
     //Define the mpi transfer types, which requires a definition of the species already
     logger.assert_always(speciesHandler.getNumberOfObjects() > 0, "Please create a particle species before calling solve()");
     MPIContainer::Instance().initialiseMercuryMPITypes(speciesHandler);
     //Make sure all processors are done with decomposition before proceeding
     logger(VERBOSE,"processor %: #real particles: %, #total particles: %", PROCESSOR_ID, particleHandler.getNumberOfRealObjects(), particleHandler.getSize());
     MPIContainer::Instance().sync();
 #endif
 }
References DomainHandler::createMesh(), domain, domainHandler, ERROR, BaseHandler< T >::getNumberOfObjects(), ParticleHandler::getNumberOfRealObjects(), BaseHandler< T >::getSize(), getXMax(), getXMin(), getYMax(), getYMin(), getZMax(), getZMin(), MPIContainer::initialiseMercuryMPITypes(), MPIContainer::Instance(), logger, NUMBER_OF_PROCESSORS, numberOfDomains_, particleHandler, PROCESSOR_ID, DomainHandler::setCurrentDomainIndex(), BaseHandler< T >::setDPMBase(), speciesHandler, MPIContainer::sync(), VERBOSE, XAXIS, YAXIS, and ZAXIS.
Referenced by initialiseSolve(), and read().
deleteGhostParticles()
void DPMBase::deleteGhostParticles (std::set< BaseParticle * > & particlesToBeDeleted) protected
Todo:
: doc
 {
     //Flush mixed particles from lists (MP particles are located in both structures)
     if (periodicBoundaryHandler.getSize() > 0)
     {
         //Flush particles from boundaries
         domainHandler.getCurrentDomain()->flushParticles(particlesToBeDeleted);
         periodicBoundaryHandler.flushParticles(particlesToBeDeleted);
     }
     //Clean communication lists
     domainHandler.getCurrentDomain()->cleanCommunicationLists();
     periodicBoundaryHandler.cleanCommunicationLists();
     //Delete the particles
     for (auto particle_it : particlesToBeDeleted)
     {
         particleHandler.removeGhostObject(particle_it->getIndex());
     }
 }
References Domain::cleanCommunicationLists(), PeriodicBoundaryHandler::cleanCommunicationLists(), domainHandler, PeriodicBoundaryHandler::flushParticles(), Domain::flushParticles(), DomainHandler::getCurrentDomain(), BaseHandler< T >::getSize(), particleHandler, periodicBoundaryHandler, and ParticleHandler::removeGhostObject().
Referenced by performGhostParticleUpdate().
disableSoftStop()
void DPMBase::disableSoftStop () inline protected
This prevents the initialisation of the soft stop feature.
 { disableSoftStop_ = true; }
References disableSoftStop_.
discontinueSolve()
void DPMBase::discontinueSolve () inline protected
This discontinues the solve loop after the current time step is finished.
Use this to gracefully exit the simulation early, i.e. write the output files etc., by calling it from any place in the code. It is an alternative to overriding the continueSolve function.
 { continueFlag_ = false; }
References continueFlag_.
fillDomainWithParticles()
void DPMBase::fillDomainWithParticles (unsigned N = 50)
Inserts particles in the whole domain. THis is useful if you want to check whether the wall visualisation or wall computation is correct: First insert the walls, then the particles, then check in paraview if the walls and particles overlap
Parameters
N
{
     logger.assert_always(speciesHandler.getSize()>0,"There needs to be at least one species");
     ParticleSpecies* s = speciesHandler.getLastObject();
     SphericalParticle p(s);
     CubeInsertionBoundary b;
     b.set(p, 100, getMin(), getMax(), {0, 0, 0}, {0, 0, 0});
     b.insertParticles(this);
     logger(INFO,"Inserted % particles",particleHandler.getSize());
 }
References b, BaseHandler< T >::getLastObject(), getMax(), getMin(), BaseHandler< T >::getSize(), INFO, logger, p, particleHandler, s, and speciesHandler.
finaliseSolve()
void DPMBase::finaliseSolve ()
End of the solve routine, after time stepping.
{
     //force writing of the last time step
     forceWriteOutputFiles();
     //end loop over interaction count
     actionsAfterSolve();
     //To make sure getTime gets the correct time for outputting statistics
     finishStatistics();
     closeFiles();
 }
References actionsAfterSolve(), closeFiles(), finishStatistics(), and forceWriteOutputFiles().
Referenced by solve().
findNextExistingDataFile()
bool DPMBase::findNextExistingDataFile (Mdouble tMin, bool verbose = true)
Finds and opens the next data file, if such a file exists.
First, checks to see if the file type is MULTIPLE_FILES or MULTIPLE_FILES_PADDED and, if so, whether the file contains data (ending the function if not). Then, checks if the time corresponding to the current file exceeds the minimum value entered (tMin). If not, keeps looking through subsequent data files. When a data file that satisfies t > tMin is found and successfully opened, the function returns true.
Useful when fileType is chosen as MULTIPLE_FILES or MULTIPLE_FILES_PADDED, which write data corresponding to each time step as a separate, consecutively numbered file (see FileType).
Parameters
[in] tMin Compared with the t value belonging to the file being checked to see if it is viable.
[in] verbose Allows the function to give output to the screen if desired.
Returns
bool - true if the next file is found, false if not.
 {
     if (dataFile.getFileType() == FileType::MULTIPLE_FILES || dataFile.getFileType() == FileType::MULTIPLE_FILES_PADDED)
     {
         while (true)// This true corresponds to the if s
         {
             dataFile.open();
             //check if file exists and contains data
             int N;
             dataFile.getFstream() >> N;
             if (dataFile.getFstream().eof() || dataFile.getFstream().peek() == -1)
             {
                 logger(WARN, "file % not found", dataFile.getName());
                 return false;
             }
             //check if tmin condition is satisfied
             Mdouble t;
             dataFile.getFstream() >> t;
             if (t > tMin)
             {
                 //set_file_counter(get_file_counter()-1);
                 return true;
             }
             if (verbose)
                 logger(VERBOSE, "Jumping file counter: %", dataFile.getCounter());
         }
     }
     return true;
 }
References dataFile, File::getCounter(), File::getFileType(), File::getFstream(), File::getName(), logger, MULTIPLE_FILES, MULTIPLE_FILES_PADDED, N, File::open(), plotPSD::t, verbose, VERBOSE, and WARN.
finishStatistics()
void DPMBase::finishStatistics () protected virtual
This function is overridden by StatisticsVector
Reimplemented in statistics_while_running< T >, StatisticsVector< T >, StatisticsVector< O >, StatisticsVector< XZ >, and statistics_while_running< T >.
 {
     cgHandler.finish();
 }
References cgHandler, and CGHandler::finish().
Referenced by finaliseSolve(), and Mercury3DRestart::writeOutputFiles().
forceWriteOutputFiles()
void DPMBase::forceWriteOutputFiles ()
Writes output files immediately, even if the current time step was not meant to be written. Also resets the last saved time step.
 {
     setLastSavedTimeStep(NEVER);
     writeOutputFiles();
 }
References NEVER, setLastSavedTimeStep(), and writeOutputFiles().
Referenced by finaliseSolve(), main(), and FileReader::read().
gatherContactStatistics() [1/2]
void DPMBase::gatherContactStatistics () protected
 {
     for (BaseInteraction* c : interactionHandler)
     {
         c->gatherContactStatistics();
     }
 }
References calibrate::c, and interactionHandler.
Referenced by ChuteWithPeriodicInflow::computeInternalForces().
gatherContactStatistics() [2/2]
void DPMBase::gatherContactStatistics (unsigned int index1 UNUSED, int index2 UNUSED, Vec3D Contact UNUSED, Mdouble delta UNUSED, Mdouble ctheta UNUSED, Mdouble fdotn UNUSED, Mdouble fdott UNUSED, Vec3D P1_P2_normal_ UNUSED, Vec3D P1_P2_tangential UNUSED) virtual
//Not unsigned index because of possible wall collisions.
no implementation but can be overridden in its derived classes.
Reimplemented in StatisticsVector< T >, StatisticsVector< O >, and StatisticsVector< XZ >.
 {
 }
Referenced by BaseInteraction::gatherContactStatistics().
get1DParametersFromRunNumber()
std::vector< int > DPMBase::get1DParametersFromRunNumber (int sizeX) const
This turns a counter into 1 index, which is a useful feature for performing 1D parameter study. The index run from 1:size_x, while the study number starts at 0 (initially the counter=1 in COUNTER_DONOTDEL)
Let's say sizeX = 5, counter stored in COUNTER_DONOTDEL = 1. Substituting these values into the algorithm below implies that studyNum = 0 or 1. Everytime the code is executed the counter gets incremented and the values of studyNum and i are updated, which is returned as std::vector<int>
Parameters
[in] sizeX The (integer) number of values to be tested in 1D parameter space.
Returns
std::vector<int> The current study numbers.
 {
 // Declare a vector of integers capable of storing 2 values
 std::vector<int> temp(2);
 // Declare and initialise for the current simulation run number
 int counter = getRunNumber();
 // Give studyNum value 0 if study is incomplete, otherwise value > 0
 int studyNum = (counter-1)/sizeX;
 counter = counter - sizeX*studyNum;
 int i = ((counter - 1) % sizeX) + 1;
 logger(INFO,"StudyNum: % \t Counter: % \t i: %", studyNum, counter, i);
 temp[0] = studyNum;
 temp[1] = i;
 return temp;
 }
References getRunNumber(), i, INFO, and logger.
Referenced by ParameterStudy1DDemo::getCurrentStudyNum().
get2DParametersFromRunNumber()
std::vector< int > DPMBase::get2DParametersFromRunNumber (int sizeX, int sizeY) const
This turns a counter into 2 indices which is a very useful feature for performing a 2D study. The indices run from 1:size_x and 1:size_y, while the study number starts at 0 (initially the counter=1 in COUNTER_DONOTDEL)
Let's say sizeX = 2 and sizeY = 5, counter stored in COUNTER_DONOTDEL =1. The studySize = 10. Substituting these values into the below algorithm implies that studyNum = 0 or 1, everytime the code is executed the counter gets incremented and hence determined the values of studyNum, i and j which is returned as a std::vector<int>
Parameters
[in] sizeX The (integer) number of values to be tested for one of the 2 parameters forming the 2D parameter space.
[in] sizeY The (integer) number of values to be tested for the other of the 2 parameters forming the 2D parameter space.
Returns
std::vector<int>
 {
 //declares a vector of integers capable of storing 3 values,
 std::vector<int> temp(3);
 //declares and initialises an integer variable named "counter"
 //with the current counter number, runNumber_
 int counter = getRunNumber();
 //calculates the total size of the study, i.e. the number of points
 //in the 2D parameter space explored
 int studySize = sizeX * sizeY;
 //(counter - 1) / studySize gives a fraction comparing the number of runs conducted so far
 //to the total size of the study, i.e. the total number of runs that need to be performed.
 //since studyNum is an integer, will declare zero until an adequate number of runs has been performed,
 //at which point it will equal 1
 int studyNum = (counter - 1) / studySize;
 counter = counter - studySize * studyNum;
 int i = ((counter - 1) % sizeX) + 1;
 int j = ((counter - i) / sizeX) + 1;
 logger(INFO,"StudyNum: % \t Counter: % \t i: % \t j: %", studyNum, counter, i, j);
 temp[0] = studyNum;
 temp[1] = i;
 temp[2] = j;
 return (temp);
 }
References getRunNumber(), i, INFO, j, and logger.
Referenced by ParameterStudy2DDemo::getCurrentStudyNum().
get3DParametersFromRunNumber()
std::vector< int > DPMBase::get3DParametersFromRunNumber (int sizeX, int sizeY, int sizeZ) const
This turns a counter into 3 indices, which is a useful feature for performing a 3D parameter study. The indices run from 1:size_x, 1:size_y and 1:size_z, while the study number starts at 0 (initially the counter=1 in COUNTER_DONOTDEL)
Let's say sizeX = 2, sizeY = 5 and sizeZ = 3, counter stored in COUNTER_DONOTDEL =1. The studySize = 30. Substituting these values into the below algorithm implies that studyNum = 0 or 1, everytime the code is executed the counter gets incremented and hence determined the values of studyNum, i,j and k which is returned as a std::vector<int>
Parameters
[in] sizeX The (integer) number of values to be tested for one of the 3 parameters forming the 3D parameter space.
[in] sizeY The (integer) number of values to be tested for one of the 3 parameters forming the 3D parameter space.
[in] sizeZ The (integer) number of values to be tested for one of the 3 parameters forming the 3D parameter space.
Returns
std::vector<int>
 {
 //declares a vector of integers capable of storing 4 values,
 std::vector<int> temp(4);
 //declares and initialises an integer variable named "counter"
 //with the current counter number, runNumber_
 int counter = getRunNumber();
 //calculates the total size of the study, i.e. the number of points
 //in the 3D parameter space explored
 int studySize = sizeX * sizeY * sizeZ;
 //(counter - 1) / studySize gives a fraction comparing the number of runs conducted so far
 //to the total size of the study, i.e. the total number of runs that need to be performed.
 //since studyNum is an integer, will declare zero until an adequate number of runs has been performed,
 //at which point it will equal 1
 int studyNum = (counter - 1) / studySize;
 counter = counter - studySize * studyNum;
 int i = ((counter-1) % sizeX) + 1;
 int j = static_cast<int>(std::floor((counter-1)/sizeX)) % sizeY + 1;
 int k = static_cast<int>(std::floor((counter-1)/(sizeX*sizeY))) % sizeZ + 1;
 logger(INFO,"StudyNum: % \t Counter: % \t i: % \t j: % \t k: %", studyNum, counter, i, j, k);
 temp[0] = studyNum;
 temp[1] = i;
 temp[2] = j;
 temp[3] = k;
 return (temp);
 }
References Eigen::bfloat16_impl::floor(), getRunNumber(), i, INFO, j, k, and logger.
Referenced by ParameterStudy3DDemo::getCurrentStudyNum().
getAppend()
bool DPMBase::getAppend () const
Returns whether the "append" option is on or off.
Returns
true if the "append" option is on; false if the "append" option is off.
 {
     return append_;
 }
References append_.
Referenced by initialiseSolve(), and writeEneHeader().
getBackgroundDrag()
const Mdouble DPMBase::getBackgroundDrag () const inline
Return the background drag.
Returns
double which is the background drag. Positive number removes energy, negative gains.
 {return backgroundDrag_;}
References backgroundDrag_.
Referenced by RotatingDrumBidisperseInitialise::actionsAfterTimeStep(), computeExternalForces(), and write().
getCenter()
Vec3D DPMBase::getCenter () const inline
get center of domain
     { return {getXCenter(), getYCenter(), getZCenter()}; }
References getXCenter(), getYCenter(), and getZCenter().
getCentreOfMass()
Vec3D DPMBase::getCentreOfMass () const
JMFT: Return the centre of mass of the system, excluding fixed particles.
Returns the centre of mass of particles, excluding fixed particles.
 {
     return particleHandler.getCentreOfMass();
 }
References ParticleHandler::getCentreOfMass(), and particleHandler.
Referenced by GranuHeap::actionsAfterTimeStep(), GranuDrum::printTime(), GranuHeap::printTime(), VerticalMixer::printTime(), InitialBed::printTime(), LaserOnLayer::printTime(), RotatingDrumBidisperse::printTime(), GranuDrum::writeResults(), and RotatingDrumBidisperse::writeResults().
getCPUTime()
double DPMBase::getCPUTime () inline
 { return clock_.getCPUTime(); }
References clock_, and Time::getCPUTime().
getCurrentDomain()
Domain * DPMBase::getCurrentDomain ()
Function that returns a pointer to the domain corresponding to the processor.
Function that returns a pointer to the domain correseponding to the processor.
Returns
Pointer to a domain corresponding to the processor
 {
     return domainHandler.getCurrentDomain();
 }
References domainHandler, and DomainHandler::getCurrentDomain().
Referenced by checkInteractionWithBoundaries(), and PeriodicBoundaryHandler::clearCommunicationLists().
getDataFile() [1/2]
File & DPMBase::getDataFile ()
The non const version. Allows one to edit the File::dataFile.
Deprecated:
dataFile is now protected, so it can be used by all applications. Please don't use getDataFile() anymore.
Returns
File& (A reference of object type File i.e. File& dataFile)
 {
 return dataFile;
 }
References dataFile.
getDataFile() [2/2]
const File & DPMBase::getDataFile () const
The const version. Does not allow for any editing of the File::dataFile.
Deprecated:
dataFile is now protected, so it can be used by all applications. Please don't use getDataFile() anymore.
Returns
const File& (A const reference of object type File i.e. const File& dataFile)
 {
 return dataFile;
 }
References dataFile.
getElasticEnergy()
Mdouble DPMBase::getElasticEnergy () const
Returns the global elastic energy within the system.
Returns
elasticEnergy The total elastic energy of all current particle interactions.
 {
     Mdouble elasticEnergy = 0.0;
     // JMFT: Note that we do count the elastic energy of fixed particles here.
     for (const BaseInteraction* c : interactionHandler)
     {
         elasticEnergy += c->getElasticEnergy();
     }
     return elasticEnergy;
 }
References calibrate::c, and interactionHandler.
Referenced by SilbertHstop::actionAfterTimeStep(), BaseCluster::actionsAfterSolve(), GranuHeap::actionsAfterTimeStep(), ShearStage::actionsAfterTimeStep(), RotatingDrumBidisperseInitialise::actionsAfterTimeStep(), BaseCluster::actionsAfterTimeStep(), T_protectiveWall::continueSolve(), ClosedCSCWalls::continueSolve(), CSCInit::continueSolve(), CSCWalls::continueSolve(), RotatingDrumBidisperseInitialise::continueSolve(), InitialConditions< SpeciesType >::continueSolve(), DPM::continueSolve(), protectiveWall::continueSolve(), getTotalEnergy(), main(), GranuHeap::printTime(), ShearStage::printTime(), ClosedCSCRestart::printTime(), ClosedCSCRun::printTime(), ClosedCSCStats::printTime(), ClosedCSCWalls::printTime(), CSCInit::printTime(), CSCRestart::printTime(), CSCRun::printTime(), CSCStats::printTime(), CSCWalls::printTime(), HorizontalMixer::printTime(), VerticalMixer::printTime(), ParticleInclusion::printTime(), vibratedBed::printTime(), RotatingDrumBidisperseInitialise::printTime(), SingleParticleSegregation::printTime(), InitialConditions< SpeciesType >::printTime(), SphericalIndenter::printTime(), DPM::printTime(), regimeForceUnitTest::printTime(), TangentialSpringEnergyConservationUnitTest::printTime(), BaseCluster::printTime(), writeEneTimeStep(), LawinenBox::writeEneTimeStep(), and BaseCluster::writeToCdatFile().
getEneFile() [1/2]
File & DPMBase::getEneFile ()
The non const version. Allows to edit the File::eneFile.
Deprecated:
eneFile is now protected, so it can be used by all applications. Please don't use getEneFile() anymore.
Returns
File& (A reference of object type File i.e. File& eneFile)
 {
 return eneFile;
 }
References eneFile.
getEneFile() [2/2]
const File & DPMBase::getEneFile () const
The const version. Does not allow for any editing of the File::eneFile.
Deprecated:
eneFile is now protected, so it can be used by all applications. Please don't use getEneFile() anymore.
Returns
const File& (A const reference of object type File i.e. const File& eneFile)
 {
 return eneFile;
 }
References eneFile.
getFStatFile() [1/2]
File & DPMBase::getFStatFile ()
The non const version. Allows to edit the File::fStatFile.
Deprecated:
fStatFile is now protected, so it can be used by all applications. Please don't use getFStatFile() anymore.
Returns
File& (A reference of object type File i.e. File& fStatFile)
 {
 return fStatFile;
 }
References fStatFile.
getFStatFile() [2/2]
const File & DPMBase::getFStatFile () const
The const version. Does not allow for any editing of the File::fStatFile.
Deprecated:
fStatFile is now protected, so it can be used by all applications. Please don't use getFStatFile() anymore.
Returns
const File& (A const reference of object type File i.e. const File& fStatFile)
 {
 return fStatFile;
 }
References fStatFile.
getGravitationalEnergy()
Mdouble DPMBase::getGravitationalEnergy (Vec3D origin = {0,0,0}) const
Returns the global gravitational potential energy stored relative to a user-defined origin in the system. Note, if no origin is specified the real origin i.e. (0,0,0) is taken.
Returns
gravitationalEnergy The total gravitational potential energy of all particles (relative to user-specified origin. If no origin is specified the real origin (0,0,0) is taken.
 {
     Mdouble gravitationalEnergy = 0;
     for (const BaseParticle* const p : particleHandler)
     {
         // Don't consider fixed particles. 'Fixed' particles aren't necessarily
         // stationary; it just means their position is prescribed.
         if (!(p->isFixed()))
         {
             gravitationalEnergy += p->getMass() * Vec3D::dot((-getGravity()), p->getPosition()-origin);
         }
     }
     return gravitationalEnergy;
 }
References Vec3D::dot(), getGravity(), p, and particleHandler.
Referenced by InitialBed::continueSolve(), getTotalEnergy(), InitialBed::printTime(), and LaserOnLayer::printTime().
getGravity()
Vec3D DPMBase::getGravity () const
Returns the gravitational acceleration.
Returns
Vec3D gravity_ The desired new value of the gravitational acceleration as a Vec3D vector.
 {
     return gravity_;
 }
References gravity_.
Referenced by MarbleRun::actionsAfterTimeStep(), computeExternalForces(), getGravitationalEnergy(), ChuteWithHopper::getMaximumVelocityInducedByGravity(), GranuDrum::GranuDrum(), RotatingDrumBidisperse::RotatingDrumBidisperse(), RotatingDrumBidisperseInitialise::RotatingDrumBidisperseInitialise(), save(), SingleParticle< SpeciesType >::scaleMass(), InitialConditions< SpeciesType >::scaleMass(), Chute::setChuteAngle(), Binary::setupInitialConditions(), MarbleRun::setupInitialConditions(), CGHandlerSelfTest::setupInitialConditions(), RollingOverTriangleWalls::setupInitialConditions(), InitialConditions< SpeciesType >::setupInitialConditions(), MercuryProblem::setupInitialConditions(), SingleParticle< SpeciesType >::SingleParticle(), write(), writeEneTimeStep(), and LawinenBox::writeEneTimeStep().
getHGridUpdateEachTimeStep()
bool DPMBase::getHGridUpdateEachTimeStep () const virtual
Returns
bool (True or False)
Reimplemented in MercuryBase.
 {
     return true;
 }
Referenced by BaseParticle::integrateBeforeForceComputation(), and ClumpParticle::integrateBeforeForceComputation().
getInfo()
Mdouble DPMBase::getInfo (const BaseParticle & p) const virtual
A virtual function that returns some user-specified information about a particle.
Returns
double
Reimplemented in WallSpecies, SegregationPeriodic, SegregationPeriodic, SegregationPeriodic, and ChuteWithPeriodicInflow.
 {
 //    return p.getSpecies()->getId(); // was getIndex()
     return p.getInfo();
 }
References p.
getInteractionFile() [1/2]
File & DPMBase::getInteractionFile ()
Return a reference to the file InteractionsFile.
Returns
A reference of object type File i.e. File* interactionFile_
 {
 return interactionFile;
 }
References interactionFile.
Referenced by initialiseSolve(), main(), setName(), and BaseInteraction::~BaseInteraction().
getInteractionFile() [2/2]
const File & DPMBase::getInteractionFile () const
Returns a constant reference to an Interactions file.
Returns
const File& (A const reference of object type std::string i.e. const std::string& name_)
Bug:
The InteractionFile does not work across multifiles.
 {
 return interactionFile;
 }
References interactionFile.
getKineticEnergy()
Mdouble DPMBase::getKineticEnergy () const
Returns the global kinetic energy stored in the system.
Returns
kineticEnergy The total kinetic energy of all particles.
 {
     Mdouble kineticEnergy = 0;
     for (const BaseParticle* const p : particleHandler)
     {
         if (!(p->isFixed()))
         {
             kineticEnergy += .5 * p->getMass() * p->getVelocity().getLengthSquared();
         }
     }
     return kineticEnergy;
 }
References p, and particleHandler.
Referenced by SilbertHstop::actionAfterTimeStep(), BaseCluster::actionsAfterSolve(), GranuHeap::actionsAfterTimeStep(), ShearStage::actionsAfterTimeStep(), RotatingDrumBidisperseInitialise::actionsAfterTimeStep(), BaseCluster::actionsAfterTimeStep(), DrumRot::actionsBeforeTimeStep(), RotatingDrum::actionsBeforeTimeStep(), T_protectiveWall::continueSolve(), ClosedCSCWalls::continueSolve(), CSCInit::continueSolve(), CSCWalls::continueSolve(), InitialBed::continueSolve(), RotatingDrumBidisperseInitialise::continueSolve(), InitialConditions< SpeciesType >::continueSolve(), DPM::continueSolve(), protectiveWall::continueSolve(), getTotalEnergy(), main(), GranuHeap::printTime(), ShearStage::printTime(), ClosedCSCRestart::printTime(), ClosedCSCRun::printTime(), ClosedCSCStats::printTime(), ClosedCSCWalls::printTime(), CSCInit::printTime(), CSCRestart::printTime(), CSCRun::printTime(), CSCStats::printTime(), CSCWalls::printTime(), HorizontalMixer::printTime(), VerticalMixer::printTime(), ParticleInclusion::printTime(), vibratedBed::printTime(), InitialBed::printTime(), LaserOnLayer::printTime(), RotatingDrumBidisperseInitialise::printTime(), SingleParticleSegregation::printTime(), InitialConditions< SpeciesType >::printTime(), SphericalIndenter::printTime(), DPM::printTime(), regimeForceUnitTest::printTime(), BaseCluster::printTime(), setMeanVelocityAndKineticEnergy(), and BaseCluster::writeToCdatFile().
getKineticStress()
Matrix3D DPMBase::getKineticStress () const
Calculate the kinetic stress tensor in the system averaged over the whole volume.
The function calculate the kinetic stress tensor based on particle fluctuation velocity.
Returns
The kinetic stress of the whole system (all particles).
 {
     Matrix3D F; //set the kinetic energy tensor, this is in terms of Sum(m*v^2)
     Vec3D J; //set the momentum tensor
     //calculate stress for kinetic part
     for (const auto& p : particleHandler)
     {
         F += Matrix3D::dyadic(p->getVelocity(), p->getVelocity()) * p->getMass();
         J += p->getVelocity() * p->getMass();
     }
     Matrix3D stressKinetic = F - Matrix3D::dyadic(J, J) / getTotalMass();
     stressKinetic /= getTotalVolume();
     return stressKinetic;
 }
References Matrix3D::dyadic(), oomph::OcTreeNames::F, getTotalMass(), getTotalVolume(), J, p, and particleHandler.
Referenced by getTotalStress().
getMax()
Vec3D DPMBase::getMax () const inline
Returns the maximum coordinates of the problem domain.
     { return max_; }
References max_.
Referenced by BaseWall::addParticlesAtWall(), ClosedCSCWalls::ClosedCSCWalls(), commandLineCG(), InfiniteWall::createVTK(), CSCWalls::CSCWalls(), SubcriticalMaserBoundaryTEST::extendBottom(), fillDomainWithParticles(), MembraneDemo::fixMembraneEdges(), MembraneSelfTest::fixMembraneEdges(), CGExactOverlapUnitTest::getVolume(), GranuDrum::GranuDrum(), GranuHeap::GranuHeap(), main(), FileReader::read(), RotatingDrumBidisperseInitialise::RotatingDrumBidisperseInitialise(), Slide::set_Walls(), Domain::setBounds(), Domain::setRange(), ClosedCSCWalls::setupInitialConditions(), Drum::setupInitialConditions(), RotatingDrumWet::setupInitialConditions(), VerticalMixer::setupInitialConditions(), Binary::setupInitialConditions(), my_problem::setupInitialConditions(), FreeCooling2DinWalls::setupInitialConditions(), StressStrainControl::setupInitialConditions(), Cstatic2d::setupInitialConditions(), InitialBed::setupInitialConditions(), Penetration::setupInitialConditions(), DistributionSelfTest::setupInitialConditions(), DistributionToPSDSelfTest::setupInitialConditions(), InsertionBoundarySelfTest::setupInitialConditions(), MultiplePSDSelfTest::setupInitialConditions(), PolydisperseInsertionBoundarySelfTest::setupInitialConditions(), PSDManualInsertionSelfTest::setupInitialConditions(), PSDSelfTest::setupInitialConditions(), DPM::setupInitialConditions(), TwoParticleElasticCollisionInteraction::setupInitialConditions(), TriangulatedWallSelfTest::setupInitialConditions(), Packing::setupInitialConditions(), Packing::test(), TwoByTwoMPIDomainMPI4Test::TwoByTwoMPIDomainMPI4Test(), AxisymmetricIntersectionOfWalls::writeVTK(), HorizontalBaseScrew::writeVTK(), IntersectionOfWalls::writeVTK(), ScrewsymmetricIntersectionOfWalls::writeVTK(), and WallHandler::writeWallDetailsVTKBoundingBox().
getMin()
Vec3D DPMBase::getMin () const inline
Returns the minimum coordinates of the problem domain.
     { return min_; }
References min_.
Referenced by BaseWall::addParticlesAtWall(), ClosedCSCWalls::ClosedCSCWalls(), commandLineCG(), InfiniteWall::createVTK(), CSCWalls::CSCWalls(), SubcriticalMaserBoundaryTEST::extendBottom(), fillDomainWithParticles(), MembraneDemo::fixMembraneEdges(), MembraneSelfTest::fixMembraneEdges(), CGExactOverlapUnitTest::getVolume(), GranuDrum::GranuDrum(), GranuHeap::GranuHeap(), main(), FileReader::read(), RotatingDrumBidisperseInitialise::RotatingDrumBidisperseInitialise(), Domain::setBounds(), Domain::setRange(), Drum::setupInitialConditions(), RotatingDrumWet::setupInitialConditions(), VerticalMixer::setupInitialConditions(), Binary::setupInitialConditions(), my_problem::setupInitialConditions(), InsertionBoundaryMPI2Test::setupInitialConditions(), FreeCooling2DinWalls::setupInitialConditions(), StressStrainControl::setupInitialConditions(), Cstatic2d::setupInitialConditions(), InitialBed::setupInitialConditions(), Penetration::setupInitialConditions(), DistributionSelfTest::setupInitialConditions(), DistributionToPSDSelfTest::setupInitialConditions(), InsertionBoundarySelfTest::setupInitialConditions(), MultiplePSDSelfTest::setupInitialConditions(), PolydisperseInsertionBoundarySelfTest::setupInitialConditions(), PSDManualInsertionSelfTest::setupInitialConditions(), PSDSelfTest::setupInitialConditions(), FreeFallInteractionSelfTest::setupInitialConditions(), TwoParticleElasticCollisionInteraction::setupInitialConditions(), TriangulatedWallSelfTest::setupInitialConditions(), Packing::setupInitialConditions(), Packing::test(), AxisymmetricIntersectionOfWalls::writeVTK(), HorizontalBaseScrew::writeVTK(), IntersectionOfWalls::writeVTK(), ScrewsymmetricIntersectionOfWalls::writeVTK(), and WallHandler::writeWallDetailsVTKBoundingBox().
getName()
const std::string & DPMBase::getName () const
Returns the name of the file. Does not allow to change it though.
 {
 return name_;
 }
References name_.
Referenced by ShearStage::actionsAfterSolve(), OneParticleHeatingSelfTest::actionsAfterTimeStep(), OneParticleCoolingSelfTest::actionsAfterTimeStep(), SingleParticleSegregation::actionsAfterTimeStep(), ThermalConductionSelfTest::actionsBeforeTimeStep(), BaseCluster::actionsOnRestart(), checkSettings(), commandLineCG(), DPMBase(), statistics_while_running< T >::finishStatistics(), WallDetailsVTKWriter::generateFileName(), GranuDrum::GranuDrum(), GranuHeap::GranuHeap(), initialiseSolve(), LaserOnLayer::LaserOnLayer(), main(), BaseCluster::makeAmatFile(), BaseCluster::makeCdatFile(), BaseCluster::makeGnuplotFile(), BaseCluster::makeIntenalStructureFile(), BaseCluster::makeOverlFile(), readNextArgument(), Mercury3DRestart::readNextArgument(), removeOldFiles(), FlowRule::run(), statistics_while_running< T >::run(), AngleOfRepose::run(), vibratedBed::run(), save(), SaveCountUnitTest::SaveCountUnitTest(), ClosedCSCStats::setupInitialConditions(), CSCStats::setupInitialConditions(), AirySavageHutter::setupInitialConditions(), CFDDEMCoupleTest::setupInitialConditions(), MeltableForceLaw2SelfTest::setupInitialConditions(), MeltableForceLawSelfTest::setupInitialConditions(), OneParticleCoolingSelfTest::setupInitialConditions(), SingleParticle< SpeciesType >::setupInitialConditions(), MovingWalls::setupInitialConditions(), Chute::setupInitialConditions(), ShearStage::ShearStage(), statistics_while_running< T >::statistics_while_running(), Mercury3DRestart::writeOutputFiles(), Calibration::writePSDToFile(), writePythonFileForVTKVisualisation(), GranuDrum::writeResults(), GranuHeap::writeResults(), RotatingDrumBidisperse::writeResults(), HorizontalMixer::writeScript(), ChutePeriodic::writeToLocalFolder(), and ChuteWithPeriodicInflow::writeXBallsScript().
getNextTime()
Mdouble DPMBase::getNextTime () const
Returns the current simulation time.
Returns
time_
 {
 return time_ + timeStep_;
 }
References time_, and timeStep_.
getNToWrite()
int DPMBase::getNToWrite () const
get the number of elements to write to the
Gets nToWrite. If a user wants to output e.g. particle information to the screen we limit the number of outputs to nToWrite elements to not get an overflow of information in the terminal.
Parameters
[out] nToWrite_ Number of elements to write to the screen
 {
 return nToWrite_;
 }
References nToWrite_.
Referenced by write().
getNumberOfDomains()
std::vector< unsigned > DPMBase::getNumberOfDomains ()
returns the number of domains
number of domains in parallel code in terms of domains in x,y,z direction
Returns
Returns the number of domains in cartesian coordinates of the parallel mesh
 {
     return numberOfDomains_;
 }
References numberOfDomains_.
Referenced by CGHandler::evaluateDataFiles(), CGHandler::evaluateRestartFiles(), and DomainHandler::getParticleDomainGlobalIndex().
getNumberOfOMPThreads()
int DPMBase::getNumberOfOMPThreads () const
Returns the number of omp threads.
 {
     //logger.assert_debug(numberOfOMPThreads_,"You need to set the number of OMP threads");
     return numberOfOMPThreads_;
 }
References numberOfOMPThreads_.
Referenced by SphericalIndenter::actionsBeforeTimeStep(), computeAllForces(), setNumberOfOMPThreads(), and write().
getNumberOfTimeSteps()
unsigned int DPMBase::getNumberOfTimeSteps () const
Returns the current counter of time-steps, i.e. the number of time-steps that the simulation has undergone so far.
Returns
numberOfTimeSteps_
 {
 return numberOfTimeSteps_;
 }
References numberOfTimeSteps_.
Referenced by ShearStage::actionsAfterTimeStep(), ChangingTOIParticle::actionsAfterTimeStep(), RotatingDrumWet::actionsAfterTimeStep(), TwoByTwoMPIDomainMPI4Test::actionsAfterTimeStep(), OneParticleHeatingSelfTest::actionsAfterTimeStep(), OneParticleCoolingSelfTest::actionsAfterTimeStep(), ForceLawsMPI2Test::actionsBeforeTimeStep(), MeltableForceLaw2SelfTest::actionsBeforeTimeStep(), MeltableForceLawSelfTest::actionsBeforeTimeStep(), ThermalConductionSelfTest::actionsBeforeTimeStep(), SaveCountUnitTest::actionsBeforeTimeStep(), computeAllForces(), computeForcesDueToWalls(), computeInternalForce(), computeOneTimeStep(), DPM::continueSolve(), importParticlesAs(), GranuHeap::printTime(), ShearStage::printTime(), LiquidMigrationMPI2Test::printTime(), LiquidMigrationPeriodicBoundaryInteraction::printTime(), readNextFStatFile(), writeDataFile(), writeEneFile(), writeFStatFile(), and writeRestartFile().
getParticleDimensions()
unsigned int DPMBase::getParticleDimensions () const
Returns the particle dimensionality.
Returns
particleDimensions_ The dimensionality of the particles. (Note that the system may possess a different dimensionality).
 {
     return particleDimensions_;
 }
References particleDimensions_.
Referenced by BaseParticle::getParticleDimensions(), ParticleSpecies::getVolumeFromRadius(), and write().
getParticlesWriteVTK()
bool DPMBase::getParticlesWriteVTK () const
Returns whether particles are written in a VTK file.
The VTK format is used for visualisation in ParaView.
Todo:
Move this (and the set) to ParticleHandler.
Returns
bool
 {
 return writeParticlesVTK_;
 }
References writeParticlesVTK_.
Referenced by initialiseVTK(), writePythonFileForVTKVisualisation(), and writeVTKFiles().
getRestarted()
bool DPMBase::getRestarted () const
Returns the flag denoting if the simulation was restarted or not.
Returns
restarted_
 {
     return restarted_;
 }
References restarted_.
Referenced by autoNumber(), initialiseSolve(), and writeOutputFiles().
getRestartFile() [1/2]
File & DPMBase::getRestartFile ()
The non const version. Allows to edit the File::restartFile.
Deprecated:
restartFile is now protected, so it can be used by all applications. Please don't use getRestartFile() anymore.
Returns
File& (A reference of object type File i.e. File& restartFile)
 {
 return restartFile;
 }
References restartFile.
getRestartFile() [2/2]
const File & DPMBase::getRestartFile () const
The const version. Does not allow for any editing of the File::restartFile.
Deprecated:
restartFile is now protected, so it can be used by all applications. Please don't use getRestartFile() anymore.
Returns
const File& (A const reference of object type File i.e. const File& restartFile)
 {
 return restartFile;
 }
References restartFile.
getRestartVersion()
std::string DPMBase::getRestartVersion () const
This is to take into account for different Mercury versions. Returns the version of the restart file.
Returns
restartVersion_
 {
     return restartVersion_;
 }
References restartVersion_.
Referenced by Chute::read().
getRotation()
bool DPMBase::getRotation () const inline
Indicates whether particle rotation is enabled or disabled.
Returns
true if particle rotation is enabled; false if particle rotation is disabled.
     { return rotation_; }
References rotation_.
Referenced by computeAllForces(), computeForcesDueToWalls(), computeInternalForce(), BaseParticle::integrateBeforeForceComputation(), and SphericalParticleVtkWriter::writeVTKAngularVelocity().
getRotationalEnergy()
Mdouble DPMBase::getRotationalEnergy () const
Returns the global rotational energy stored in the system.
 {
     Mdouble kineticEnergy = 0;
     for (const BaseParticle* const p : particleHandler)
     {
         if (!(p->isFixed()))
         {
             kineticEnergy += .5 * Vec3D::dot(p->getAngularVelocity(), p->getInertia() * p->getAngularVelocity());
         }
     }
     return kineticEnergy;
 }
References Vec3D::dot(), p, and particleHandler.
Referenced by getTotalEnergy(), and TangentialSpringEnergyConservationUnitTest::printTime().
getRunNumber()
int DPMBase::getRunNumber () const
This returns the current value of the counter (runNumber_)
A simple "get function" which allows the user to retrieve the current value corresponding to the run number counter, runNumber_
Returns
runNumber_ - the stored value of the current run number, i.e. the number of files corresponding to a given Mercury script that have been produced in a given directory.
 {
 return runNumber_;
 }
References runNumber_.
Referenced by get1DParametersFromRunNumber(), get2DParametersFromRunNumber(), get3DParametersFromRunNumber(), and initialiseSolve().
getStatFile() [1/2]
File & DPMBase::getStatFile ()
The non const version. Allows to edit the File::statFile.
Deprecated:
statFile is now protected, so it can be used by all applications. Please don't use getStatFile() anymore.
Returns
File& (A reference of object type File i.e. File& statFile)
 {
 return statFile;
 }
References statFile.
getStatFile() [2/2]
const File & DPMBase::getStatFile () const
The const version. Does not allow for any editing of the File::statFile.
Deprecated:
statFile is now protected, so it can be used by all applications. Please don't use getStatFile() anymore.
Returns
const File& (A const reference of object type File i.e. const File& statFile)
 {
 return statFile;
 }
References statFile.
getStaticStress()
Matrix3D DPMBase::getStaticStress () const
Calculate the static stress tensor in the system averaged over the whole volume.
The function calculate the static stress tensor based on particle contact force and contact normal branch vector.
Returns
The static stress of the whole system (all interactions).
 {
     //stress components calculation variables
     Matrix3D stressStatic;
     //calculate the static stress tensor based on all the interactions
     for (const auto i : interactionHandler)
     {
         stressStatic += Matrix3D::dyadic(i->getForce(), i->getNormal()) * i->getDistance();
     }
     stressStatic /= getTotalVolume();
     return stressStatic;
 }
References Matrix3D::dyadic(), getTotalVolume(), i, and interactionHandler.
Referenced by getTotalStress(), and DPM::printTime().
getSuperquadricParticlesWriteVTK()
bool DPMBase::getSuperquadricParticlesWriteVTK () const
Returns
bool
 {
 return writeSuperquadricParticlesVTK_;
 }
References writeSuperquadricParticlesVTK_.
Referenced by initialiseVTK(), and writeVTKFiles().
getSystemDimensions()
unsigned int DPMBase::getSystemDimensions () const
Returns the system dimensionality.
Returns
systemDimensions_ The dimensionality of the system. (Note that particles may possess a different dimensionality.)
 {
     return systemDimensions_;
 }
References systemDimensions_.
Referenced by outputXBallsData(), readNextDataFile(), StatisticsVector< T >::setNZ(), write(), inflowFromPeriodic::writeXBallsScript(), and ChuteWithPeriodicInflow::writeXBallsScript().
getTime()
Mdouble DPMBase::getTime () const
Returns the current simulation time.
Returns
time_
 {
 return time_;
 }
References time_.
Referenced by SilbertHstop::actionAfterTimeStep(), GranuHeap::actionsAfterTimeStep(), ShearStage::actionsAfterTimeStep(), ChangingTOIParticle::actionsAfterTimeStep(), MaserRepeatedOutInMPI2Test::actionsAfterTimeStep(), FreeCooling2DinWallsDemo::actionsAfterTimeStep(), FreeCooling3DDemoProblem::actionsAfterTimeStep(), FreeCooling3DinWallsDemo::actionsAfterTimeStep(), FreeCoolingDemoProblem::actionsAfterTimeStep(), HourGlass::actionsAfterTimeStep(), MinimalExampleDrum::actionsAfterTimeStep(), OneParticleHeatingSelfTest::actionsAfterTimeStep(), OneParticleCoolingSelfTest::actionsAfterTimeStep(), Chutebelt::actionsAfterTimeStep(), SingleParticleSegregation::actionsAfterTimeStep(), BoundariesSelfTest::actionsAfterTimeStep(), FluxAndPeriodicBoundarySelfTest::actionsAfterTimeStep(), FluxBoundarySelfTest::actionsAfterTimeStep(), DPM::actionsAfterTimeStep(), SphericalIndenter::actionsAfterTimeStep(), BouncingSuperQuadric::actionsAfterTimeStep(), GranularCollapse::actionsAfterTimeStep(), SphericalSuperQuadricCollision::actionsAfterTimeStep(), ContactDetectionNormalSpheresTest::actionsAfterTimeStep(), ContactDetectionRotatedSpheresTest::actionsAfterTimeStep(), Tutorial11::actionsAfterTimeStep(), BaseCluster::actionsAfterTimeStep(), LawinenBox::actionsBeforeTimeStep(), DPM::actionsBeforeTimeStep(), SmoothChute::actionsBeforeTimeStep(), Binary::actionsBeforeTimeStep(), AngleOfRepose::actionsBeforeTimeStep(), MeltableForceLaw2SelfTest::actionsBeforeTimeStep(), MeltableForceLawSelfTest::actionsBeforeTimeStep(), ThermalConductionSelfTest::actionsBeforeTimeStep(), Slide::actionsBeforeTimeStep(), Chutebelt::actionsBeforeTimeStep(), ConstantRestitutionSelfTest::actionsBeforeTimeStep(), CoilSelfTest::actionsBeforeTimeStep(), DrumRot::actionsBeforeTimeStep(), RotatingDrum::actionsBeforeTimeStep(), QuaternionWallUnitTest::actionsBeforeTimeStep(), PeriodicWallsWithSlidingFrictionUnitTest::actionsBeforeTimeStep(), SaveCountUnitTest::actionsBeforeTimeStep(), AirySavageHutter::actionsOnRestart(), StatisticsVector< T >::check_current_time_for_statistics(), TimeDependentPeriodicBoundary::checkBoundaryAfterParticlesMove(), ClosedCSCStats::ClosedCSCStats(), commandLineCG(), ChuteWithPeriodicInflow::computeInternalForces(), SilbertHstop::continueSolve(), TimeDependentPeriodicBoundary::createGhostParticle(), CSCStats::CSCStats(), PrintWallTimeMixin::deadReckoningEstimateRemainingWallTime(), BaseCluster::decreaseForce(), PrintWallTimeMixin::estimateRemainingWallTime(), CGHandler::evaluateDataFiles(), CGHandler::evaluateRestartFiles(), LeesEdwardsBoundary::getCurrentShift(), LeesEdwardsBoundary::getCurrentVelocity(), HorizontalBaseScrew::getDistanceAndNormal(), vibratedBed::getPrescribedVelocity(), BaseCluster::increaseForce(), integrateAfterForceComputation(), integrateBeforeForceComputation(), isTimeEqualTo(), loadingTest(), main(), normalAndTangentialLoadingTest(), objectivenessTest(), outputXBallsData(), LiquidMigrationMPI2Test::outputXBallsData(), LiquidMigrationSelfTest::outputXBallsData(), SphericalIndenter::outputXBallsData(), inflowFromPeriodic::printTime(), printTime(), T_protectiveWall::printTime(), LawinenBox::printTime(), GranuDrum::printTime(), ShearStage::printTime(), ClosedCSCRestart::printTime(), ClosedCSCRun::printTime(), ClosedCSCStats::printTime(), ClosedCSCWalls::printTime(), CSCInit::printTime(), CSCRestart::printTime(), CSCRun::printTime(), CSCStats::printTime(), CSCWalls::printTime(), ChuteWithPeriodicInflow::printTime(), CFDDEMCoupleTest::printTime(), HorizontalMixer::printTime(), NozzleDemo::printTime(), Drum::printTime(), RotatingDrumWet::printTime(), VerticalMixer::printTime(), ForceLawsMPI2Test::printTime(), ParticleInclusion::printTime(), ParticleBeam::printTime(), SilbertPeriodic::printTime(), CLiveStatistics< T >::printTime(), statistics_while_running< T >::printTime(), vibratedBed::printTime(), InitialBed::printTime(), LaserOnLayer::printTime(), MeltableForceLaw2SelfTest::printTime(), MeltableForceLawSelfTest::printTime(), OneParticleHeatingSelfTest::printTime(), OneParticleCoolingSelfTest::printTime(), ThermalConductionSelfTest::printTime(), RotatingDrumBidisperseInitialise::printTime(), RotatingDrumBidisperse::printTime(), SingleParticleSegregation::printTime(), ConstantMassFlowMaserBoundaryMixedSpeciesSelfTest::printTime(), ConstantMassFlowMaserSelfTest::printTime(), CubeDeletionBoundarySelfTest::printTime(), DeletionBoundarySelfTest::printTime(), DistributionPhiNormalSelfTest::printTime(), DistributionSelfTest::printTime(), DistributionToPSDSelfTest::printTime(), InsertionBoundarySelfTest::printTime(), MultiplePSDSelfTest::printTime(), NozzleSelfTest::printTime(), PolydisperseInsertionBoundarySelfTest::printTime(), PSDManualInsertionSelfTest::printTime(), LiquidMigrationSelfTest::printTime(), TwoParticleCollisionInteraction::printTime(), TwoParticleElasticCollisionInteraction::printTime(), InitialConditions< SpeciesType >::printTime(), SinterPair::printTime(), SphericalIndenter::printTime(), DPM::printTime(), protectiveWall::printTime(), PSDSelfTest::printTime(), EvaporationAndHeatTest::printTime(), RandomClusterInsertionBoundarySelfTest::printTime(), HeatTransferUnitTest::printTime(), viscoElasticUnitTest::printTime(), MultiParticlesInsertion::printTime(), regimeForceUnitTest::printTime(), SetDistributionPhiNormalSelfTest::printTime(), BaseCluster::printTime(), Chute::printTime(), PrintWallTimeMixin::printTime(), PrintWallTimeMixin::PrintWallTimeMixin(), FileReader::read(), readNextDataFile(), readNextFStatFile(), BaseWall::renderWall(), CGHandler::restart(), statistics_while_running< T >::run(), CGFields::DisplacementField::setFields(), CGHandler::setPreviousEvaluationTimeToCurrentTime(), NozzleDemo::setupInitialConditions(), Binary::setupInitialConditions(), my_problem::setupInitialConditions(), NozzleSelfTest::setupInitialConditions(), DrumRot::setupInitialConditions(), RotatingDrum::setupInitialConditions(), BaseCluster::setupInitialConditions(), ShearBoxBoundary::shiftHorizontalPosition(), LeesEdwardsBoundary::shiftVerticalPosition(), solve(), statistics_while_running< T >::statistics_while_running(), Domain::updateParticles(), LeesEdwardsBoundary::write(), write(), writeEneTimeStep(), LawinenBox::writeEneTimeStep(), Drum::writeEneTimeStep(), Penetration::writeEneTimeStep(), Silo::writeEneTimeStep(), SingleParticle< SpeciesType >::writeEneTimeStep(), Sintering::writeEneTimeStep(), SphericalIndenter::writeEneTimeStep(), SlidingFrictionUnitTest::writeEneTimeStep(), writeFstatHeader(), protectiveWall::writeFstatHeader(), BaseInteraction::writeInteraction(), ClosedCSCRestart::writeOutputFiles(), CSCRestart::writeOutputFiles(), BaseCluster::writeToCdatFile(), BaseCluster::writeToOverlFile(), and HorizontalBaseScrew::writeVTK().
getTimeMax()
Mdouble DPMBase::getTimeMax () const
Returns the maximum simulation duration.
Returns
timeMax_
 {
 return timeMax_;
 }
References timeMax_.
Referenced by AngleOfRepose::actionsBeforeTimeStep(), Slide::actionsBeforeTimeStep(), AirySavageHutter::actionsOnRestart(), ChutePeriodicDemo::ChutePeriodicDemo(), PrintWallTimeMixin::deadReckoningEstimateRemainingWallTime(), PrintWallTimeMixin::estimateRemainingWallTime(), ForceLawsMPI2Test::ForceLawsMPI2Test(), StatisticsVector< T >::getTimeMaxStat(), GranuDrum::GranuDrum(), LaserOnLayer::LaserOnLayer(), loadingTest(), main(), normalAndTangentialLoadingTest(), objectivenessTest(), ParticleBeam::ParticleBeam(), printTime(), T_protectiveWall::printTime(), LawinenBox::printTime(), GranuDrum::printTime(), HorizontalMixer::printTime(), NozzleDemo::printTime(), Drum::printTime(), RotatingDrumWet::printTime(), ParticleBeam::printTime(), SilbertPeriodic::printTime(), CLiveStatistics< T >::printTime(), statistics_while_running< T >::printTime(), vibratedBed::printTime(), InitialBed::printTime(), LaserOnLayer::printTime(), RotatingDrumBidisperse::printTime(), ConstantMassFlowMaserBoundaryMixedSpeciesSelfTest::printTime(), ConstantMassFlowMaserSelfTest::printTime(), DistributionSelfTest::printTime(), DistributionToPSDSelfTest::printTime(), InsertionBoundarySelfTest::printTime(), MultiplePSDSelfTest::printTime(), NozzleSelfTest::printTime(), PolydisperseInsertionBoundarySelfTest::printTime(), PSDManualInsertionSelfTest::printTime(), SinterPair::printTime(), protectiveWall::printTime(), PSDSelfTest::printTime(), RandomClusterInsertionBoundarySelfTest::printTime(), MultiParticlesInsertion::printTime(), regimeForceUnitTest::printTime(), Chute::printTime(), PrintWallTimeMixin::printTime(), readNextArgument(), Mercury3DRestart::readNextArgument(), regimeForceUnitTest::regimeForceUnitTest(), RotatingDrumBidisperse::RotatingDrumBidisperse(), save(), ChutePeriodic::setup(), ClosedCSCStats::setupInitialConditions(), CSCRun::setupInitialConditions(), CSCStats::setupInitialConditions(), MarbleRun::setupInitialConditions(), OneParticleCoolingSelfTest::setupInitialConditions(), Drum::setupInitialConditions(), Penetration::setupInitialConditions(), Silo::setupInitialConditions(), UnionOfWalls::setupInitialConditions(), SingleParticle< SpeciesType >::setupInitialConditions(), EvaporationAndHeatTest::setupInitialConditions(), HeatTransferUnitTest::setupInitialConditions(), MovingIntersectionOfWallsUnitTest_Basic::setupInitialConditions(), MovingWall::setupInitialConditions(), SeparateFilesSelfTest::setupInitialConditions(), MercuryProblem::setupMercuryProblem(), Siegen::Siegen(), Slide::Slide(), solve(), write(), and protectiveWall::writeFstatHeader().
getTimeStep()
Mdouble DPMBase::getTimeStep () const
Returns the simulation time step.
Returns
timeStep_ The current (Mdouble) value of the simulation time step.
 {
 return timeStep_;
 }
References timeStep_.
Referenced by ClosedCSCRestart::actionsAfterTimeStep(), ClosedCSCRun::actionsAfterTimeStep(), ClosedCSCWalls::actionsAfterTimeStep(), CFDDEMCoupleTest::actionsAfterTimeStep(), HorizontalMixer::actionsAfterTimeStep(), CubicCell::actionsAfterTimeStep(), FreeCooling2DinWallsDemo::actionsAfterTimeStep(), FreeCooling3DDemoProblem::actionsAfterTimeStep(), FreeCooling3DinWallsDemo::actionsAfterTimeStep(), FreeCoolingDemoProblem::actionsAfterTimeStep(), HourGlass::actionsAfterTimeStep(), MarbleRun::actionsAfterTimeStep(), SphericalIndenter::actionsAfterTimeStep(), GranularCollapse::actionsAfterTimeStep(), SlidingSpheresUnitTest::actionsAfterTimeStep(), SphericalSuperQuadricCollision::actionsAfterTimeStep(), ContactDetectionNormalSpheresTest::actionsAfterTimeStep(), ContactDetectionRotatedSpheresTest::actionsAfterTimeStep(), Tutorial11::actionsAfterTimeStep(), BaseCluster::actionsAfterTimeStep(), MeltableInteraction::actionsAfterTimeStep(), HeatFluidCoupledSpecies< NormalForceSpecies >::actionsAfterTimeStep(), LawinenBox::actionsBeforeTimeStep(), DPM::actionsBeforeTimeStep(), SmoothChute::actionsBeforeTimeStep(), Slide::actionsBeforeTimeStep(), Chutebelt::actionsBeforeTimeStep(), CoilSelfTest::actionsBeforeTimeStep(), BaseCluster::actionsOnRestart(), StressStrainControlBoundary::activateStrainRateControl(), NautaMixer::addSpeciesAndSetTimeStepAndSaveCount(), BaseCluster::calculateTimeStep(), StatisticsVector< T >::check_current_time_for_statistics(), HeaterBoundary::checkBoundaryAfterParticleMoved(), checkSettings(), ChutePeriodicDemo::ChutePeriodicDemo(), ClosedCSCRun::ClosedCSCRun(), ClosedCSCWalls::ClosedCSCWalls(), FrictionInteraction::computeFrictionForce(), MindlinInteraction::computeFrictionForce(), MindlinRollingTorsionInteraction::computeFrictionForce(), ChuteWithPeriodicInflow::computeInternalForces(), SinterInteraction::computeNormalForce(), SinterLinInteraction::computeNormalForce(), HertzianSinterInteraction::computeSinterForce(), SlidingFrictionInteraction::computeSlidingSpring(), StressStrainControlBoundary::computeStrainRate(), WearableNurbsWall::computeWear(), WearableTriangleMeshWall::computeWear(), WearableTriangulatedWall::computeWear(), SilbertHstop::continueSolve(), CSCWalls::CSCWalls(), StressStrainControlBoundary::determineStressControlledShearBoundaries(), ForceLawsMPI2Test::ForceLawsMPI2Test(), ChuteWithHopper::getTimeStepRatio(), GranuDrum::GranuDrum(), integrateAfterForceComputation(), ChuteWithPeriodicInflow::integrateBeforeForceComputation(), integrateBeforeForceComputation(), inflowFromPeriodic::integrateBeforeForceComputation(), isTimeEqualTo(), LaserOnLayer::LaserOnLayer(), LeesEdwardsDemo::LeesEdwardsDemo(), main(), ChuteBottom::makeRoughBottom(), ParticleBeam::ParticleBeam(), ParticleCreation::ParticleCreation(), readNextArgument(), readParAndIniFiles(), regimeForceUnitTest::regimeForceUnitTest(), BaseWall::renderWall(), Screw::rotate(), RotatingDrumBidisperse::RotatingDrumBidisperse(), save(), Cstatic2d::set_particle_properties(), Cstatic3D::set_particle_properties(), SilbertPeriodic::set_study(), Calibration::setSpecies(), Material::setSpecies(), ChutePeriodic::setup(), ChuteWithContraction::setup_particles_initial_conditions(), CSCRun::setupInitialConditions(), CFDDEMCoupleTest::setupInitialConditions(), RotatingDrumWet::setupInitialConditions(), MarbleRun::setupInitialConditions(), ShiftingConstantMassFlowMaserBoundarySelfTest::setupInitialConditions(), ShiftingMaserBoundarySelfTest::setupInitialConditions(), ChutePeriodic::setupInitialConditions(), OneParticleCoolingSelfTest::setupInitialConditions(), GetDistanceAndNormalForIntersectionOfWalls::setupInitialConditions(), GetDistanceAndNormalForScrew::setupInitialConditions(), GetDistanceAndNormalForTriangleWall::setupInitialConditions(), Drum::setupInitialConditions(), Penetration::setupInitialConditions(), Silo::setupInitialConditions(), DistributionSelfTest::setupInitialConditions(), TwoParticleCollisionInteraction::setupInitialConditions(), ContactDetectionIntersectionOfWallsTest::setupInitialConditions(), GetDistanceAndNormalForTriangleWalls::setupInitialConditions(), UnionOfWalls::setupInitialConditions(), SingleParticle< SpeciesType >::setupInitialConditions(), InitialConditions< SpeciesType >::setupInitialConditions(), EllipticalSuperQuadricCollision::setupInitialConditions(), ParticleParticleInteraction::setupInitialConditions(), ParticleParticleInteractionWithPlasticForces::setupInitialConditions(), ParticleWallInteraction::setupInitialConditions(), Packing::setupInitialConditions(), CreateDataAndFStatFiles::setupInitialConditions(), EvaporationAndHeatTest::setupInitialConditions(), HeatTransferUnitTest::setupInitialConditions(), HertzianSinterForceUnitTest::setupInitialConditions(), MovingIntersectionOfWallsUnitTest_Basic::setupInitialConditions(), MovingWall::setupInitialConditions(), PlasticForceUnitTest::setupInitialConditions(), SeparateFilesSelfTest::setupInitialConditions(), BaseCluster::setupInitialConditions(), MercuryProblem::setupMercuryProblem(), Siegen::Siegen(), SilbertHstop::SilbertHstop(), SingleParticleSegregation::SingleParticleSegregation(), Slide::Slide(), TangentialSpringEnergyConservationUnitTest::TangentialSpringEnergyConservationUnitTest(), TimeDependentPeriodicBoundary3DSelfTest::TimeDependentPeriodicBoundary3DSelfTest(), TimeDependentPeriodicBoundaryTest::TimeDependentPeriodicBoundaryTest(), TriangulatedScrewSelfTest::TriangulatedScrewSelfTest(), TriangulatedStepSelfTest::TriangulatedStepSelfTest(), TriangulatedStepWallSelfTest::TriangulatedStepWallSelfTest(), TriangulatedWallSelfTest::TriangulatedWallSelfTest(), StressStrainControlBoundary::updateDomainSize(), and write().
getTotalEnergy()
Mdouble DPMBase::getTotalEnergy () const
{
     return getElasticEnergy()+getKineticEnergy()+getGravitationalEnergy()+getRotationalEnergy();
 }
References getElasticEnergy(), getGravitationalEnergy(), getKineticEnergy(), and getRotationalEnergy().
getTotalMass()
Mdouble DPMBase::getTotalMass () const
JMFT: Return the total mass of the system, excluding fixed particles.
Returns
double
 {
     /*
     double mass_sum = 0;
     for (std::vector<BaseParticle*>::const_iterator it = particleHandler.begin(); it != particleHandler.end(); ++it)
         if (!(*it)->isFixed())
             mass_sum += (*it)->getMass();
     return mass_sum;
     */
     return particleHandler.getMass();
 }
References ParticleHandler::getMass(), and particleHandler.
Referenced by ShearStage::actionsAfterTimeStep(), getKineticStress(), ShearStage::printTime(), setMeanVelocity(), and setMeanVelocityAndKineticEnergy().
getTotalMomentum()
Vec3D DPMBase::getTotalMomentum () const
JMFT: Return the total momentum of the system, excluding fixed particles.
Returns the total momentum in the system, excluding fixed particles (which will usually, but not always, have velocity 0)
Returns
Vec3D
 {
     return particleHandler.getMomentum();
     /*
     Vec3D total_momentum = Vec3D(0,0,0);
     for (std::vector<BaseParticle*>::const_iterator it = particleHandler.begin(); it != particleHandler.end(); ++it)
         if (!(*it)->isFixed())
             total_momentum += (*it)->getMass() * (*it)->getVelocity();
     return total_momentum;
     */
 }
References ParticleHandler::getMomentum(), and particleHandler.
Referenced by setMeanVelocity(), and setMeanVelocityAndKineticEnergy().
getTotalStress()
Matrix3D DPMBase::getTotalStress () const
Calculate the total stress tensor in the system averaged over the whole volume.
The function calculate the total stress tensor which is the sum of kinetic and static stress tensors.
Returns
The total stress of the whole system (all particles and all interactions).
 {
     return getKineticStress() + getStaticStress();
 }
References getKineticStress(), and getStaticStress().
Referenced by ShearStage::actionsAfterTimeStep(), StressStrainControlBoundary::computeStrainRate(), StressStrainControlBoundary::computeStressError(), and ShearStage::printTime().
getTotalVolume()
Mdouble DPMBase::getTotalVolume () const
Get the total volume of the cuboid system.
Returns
The total volume of the domain.
 {
     return (getXMax() - getXMin()) * (getYMax() - getYMin()) * (getZMax() - getZMin());
 }
References getXMax(), getXMin(), getYMax(), getYMin(), getZMax(), and getZMin().
Referenced by ShearStage::actionsAfterTimeStep(), getKineticStress(), getStaticStress(), GranuHeap::GranuHeap(), ShearStage::printTime(), and InitialBed::setupInitialConditions().
getVtkWriter()
ParticleVtkWriter * DPMBase::getVtkWriter () const
 {
     return vtkWriter_;
 }
References vtkWriter_.
getWallsWriteVTK()
FileType DPMBase::getWallsWriteVTK () const
Returns whether walls are written in a VTK file.
Deprecated:
Use wallHandler.getWriteVTK() instead (since 21-07-2021)
The VTK file is used for visualisation in Paraview.
Todo:
Move this (and the set) to WallHandler.
Returns
bool
 {
     logger(WARN, "DPMBase.getWallsWriteVTK() is deprecated! Use wallHandler.getWriteVTK() instead.");
     return wallHandler.getWriteVTK();
 }
References WallHandler::getWriteVTK(), logger, wallHandler, and WARN.
getWallTime()
double DPMBase::getWallTime () inline
 { return clock_.getWallTime(); }
References clock_, and Time::getWallTime().
getWallVTKWriter()
WallVTKWriter & DPMBase::getWallVTKWriter ()
 {
     return wallVTKWriter_;
 }
References wallVTKWriter_.
Referenced by WallHandler::getWriteWallSurfaceAreaVTK(), and WallHandler::setWriteWallSurfaceAreaVTK().
getWritePythonFileForVTKVisualisation()
bool DPMBase::getWritePythonFileForVTKVisualisation () const
 {
     return forceWritePythonFileForVTKVisualisation_;
 }
References forceWritePythonFileForVTKVisualisation_.
getXBallsAdditionalArguments()
std::string DPMBase::getXBallsAdditionalArguments () const
Returns the additional arguments for xballs.
Returns
xBallsAdditionalArguments_
 {
     return xBallsAdditionalArguments_;
 }
References xBallsAdditionalArguments_.
Referenced by write(), inflowFromPeriodic::writeXBallsScript(), and ChuteWithPeriodicInflow::writeXBallsScript().
getXBallsColourMode()
int DPMBase::getXBallsColourMode () const
Get the xballs colour mode (CMode).
Returns the integer value corresponding to the colour scheme used by the XBalls visualisation software. See also setXBallsColourMode and the Visualising data in xballs
Returns
int xBallsColourMode_ The integer value corresponding to the colour scheme used by the XBalls visualisation software.
 {
     return xBallsColourMode_;
 }
References xBallsColourMode_.
Referenced by inflowFromPeriodic::writeXBallsScript(), and ChuteWithPeriodicInflow::writeXBallsScript().
getXBallsScale()
double DPMBase::getXBallsScale () const
Returns the scale of the view in xballs.
Returns
double xBallsScale_ The scaling or "zoom" - corresponds tol the XBalls "-s" flag. Values > 1 mean a "zoomed out" view, values < 1 give a "zoomed in" view.
 {
     return xBallsScale_;
 }
References xBallsScale_.
Referenced by inflowFromPeriodic::writeXBallsScript(), and ChuteWithPeriodicInflow::writeXBallsScript().
getXBallsVectorScale()
double DPMBase::getXBallsVectorScale () const
Returns the scale of vectors used in xballs.
Returns the length of the vectors which represent particle velocities in XBalls visualisations (see also setXBallsVectorScale and the Visualising data in xballs).
Returns
double xBallsVectorScale_ The value of the vector length used in XBalls visualisations. A value of 100 sets the length to 1 particle radius, 1000 sets it to 10 particle radii etc.
 {
     return xBallsVectorScale_;
 }
References xBallsVectorScale_.
Referenced by inflowFromPeriodic::writeXBallsScript(), and ChuteWithPeriodicInflow::writeXBallsScript().
getXCenter()
Mdouble DPMBase::getXCenter () const inline
     { return 0.5*(max_.X+min_.X); }
References max_, min_, and Vec3D::X.
Referenced by getCenter().
getXMax()
Mdouble DPMBase::getXMax () const inline
If the length of the problem domain in x-direction is XMax - XMin, then getXMax() returns XMax.
     { return max_.x(); }
References max_, and Vec3D::x().
Referenced by LeesEdwardsDemo::actionsAfterTimeStep(), TimeDependentPeriodicBoundary3DSelfTest::actionsAfterTimeStep(), TimeDependentPeriodicBoundaryTest::actionsAfterTimeStep(), Chutebelt::actionsAfterTimeStep(), Chutebelt::actionsBeforeTimeStep(), Chutebelt::actionsOnRestart(), StressStrainControlBoundary::activateStrainRateControl(), ChuteWithPeriodicInflow::AddContinuingBottom(), NautaMixer::addParticles(), NautaMixer::addParticlesAtWall(), CFDDEMCoupleTest::CalcPhiPAndFz(), Funnel::check_funnel(), checkSettings(), ChutePeriodicDemo::ChutePeriodicDemo(), ChuteWithContraction::ChuteWithContraction(), ChuteWithPeriodicInflowAndContinuingBottom::ChuteWithPeriodicInflowAndContinuingBottom(), ChuteWithPeriodicInflowAndContraction::ChuteWithPeriodicInflowAndContraction(), ChuteWithPeriodicInflowAndVariableBottom::ChuteWithPeriodicInflowAndVariableBottom(), ChuteWithPeriodicInflow::cleanChute(), ChuteWithContraction::cleanChute(), Chute::cleanChute(), ClosedCSCRestart::ClosedCSCRestart(), ClosedCSCRun::ClosedCSCRun(), ClosedCSCWalls::ClosedCSCWalls(), ContractionWithPeriodicInflow::ContractionWithPeriodicInflow(), LawinenBox::create_inflow_particle(), ChutePeriodic::create_inflow_particle(), FlowRule::create_inflow_particle(), SilbertPeriodic::create_inflow_particle(), Chute::createBottom(), Chute::createFlowParticle(), CSCWalls::CSCWalls(), decompose(), StressStrainControlBoundary::determineStressControlledShearBoundaries(), Chute::getChuteLength(), ChuteWithHopper::getChuteLength(), ChuteWithHopper::getMaximumVelocityInducedByGravity(), DomainHandler::getParticleDomainGlobalIndex(), getTotalVolume(), StatisticsVector< T >::getXMaxStat(), MarbleRun::includeInDomain(), Indenter::Indenter(), inflowFromPeriodic::inflowFromPeriodic(), InitialConditions< SpeciesType >::InitialConditions(), HorizontalMixer::introduceParticlesAtWall(), ContactDetectionIntersectionOfWallsTest::introduceParticlesAtWall(), HorizontalMixer::introduceParticlesInDomain(), LaserOnLayer::LaserOnLayer(), LawinenBox::LawinenBox(), LeesEdwardsSelfTest::LeesEdwardsSelfTest(), ChuteWithPeriodicInflow::loadPeriodicBox(), main(), MercuryCGSelfTest::MercuryCGSelfTest(), outputXBallsData(), LiquidMigrationMPI2Test::outputXBallsData(), LiquidMigrationSelfTest::outputXBallsData(), SphericalIndenter::outputXBallsData(), ParticleCreation::ParticleCreation(), protectiveWall::protectiveWall(), readParAndIniFiles(), regimeForceUnitTest::regimeForceUnitTest(), RotatingDrumBidisperse::RotatingDrumBidisperse(), save(), ClosedCSCWalls::saveWalls(), CSCWalls::saveWalls(), StressStrainControlBoundary::set(), CGFields::DisplacementField::setFields(), ChuteWithHopper::setHopperShift(), SphericalIndenter::setIndenterHeight(), T_protectiveWall::setupInitialConditions(), LawinenBox::setupInitialConditions(), ClosedCSCWalls::setupInitialConditions(), CSCInit::setupInitialConditions(), CSCWalls::setupInitialConditions(), ChutePeriodic::setupInitialConditions(), MercuryLogo::setupInitialConditions(), ChangingTOIParticle::setupInitialConditions(), CFDDEMCoupleTest::setupInitialConditions(), Binary::setupInitialConditions(), my_problem::setupInitialConditions(), LiquidMigrationMPI2Test::setupInitialConditions(), CubicCell::setupInitialConditions(), FreeCooling2DinWalls::setupInitialConditions(), FreeCooling2DinWallsDemo::setupInitialConditions(), FreeCooling3DDemoProblem::setupInitialConditions(), FreeCooling3DinWallsDemo::setupInitialConditions(), FreeCoolingDemoProblem::setupInitialConditions(), HeaterBoundaryTest::setupInitialConditions(), HourGlass2D::setupInitialConditions(), HourGlass::setupInitialConditions(), LeesEdwardsDemo::setupInitialConditions(), MarbleRun::setupInitialConditions(), TimeDependentPeriodicBoundary3DSelfTest::setupInitialConditions(), TimeDependentPeriodicBoundaryTest::setupInitialConditions(), Cstatic2d::setupInitialConditions(), AngleOfRepose::setupInitialConditions(), SilbertPeriodic::setupInitialConditions(), statistics_while_running< T >::setupInitialConditions(), InitialBed::setupInitialConditions(), GetDistanceAndNormalForIntersectionOfWalls::setupInitialConditions(), GetDistanceAndNormalForScrew::setupInitialConditions(), GetDistanceAndNormalForTriangleWall::setupInitialConditions(), RotatingDrum::setupInitialConditions(), Chutebelt::setupInitialConditions(), SingleParticleSegregation::setupInitialConditions(), DistributionPhiNormalSelfTest::setupInitialConditions(), clumpTest::setupInitialConditions(), PolydisperseInsertionBoundarySelfTest::setupInitialConditions(), CGHandlerSelfTest::setupInitialConditions(), NewtonsCradleSelftest::setupInitialConditions(), SquarePacking::setupInitialConditions(), ParticleCreation::setupInitialConditions(), ChargedBondedParticleUnitTest::setupInitialConditions(), my_problem_HGRID::setupInitialConditions(), FreeFallInteractionSelfTest::setupInitialConditions(), FreeFallSelfTest::setupInitialConditions(), LiquidMigrationSelfTest::setupInitialConditions(), TwoBondedParticleElasticCollision::setupInitialConditions(), TwoParticleBagheriCollision::setupInitialConditions(), TwoParticleClassicalWilletCollision::setupInitialConditions(), TwoParticleCollisionInteraction::setupInitialConditions(), TwoParticleElasticCollision::setupInitialConditions(), CoilSelfTest::setupInitialConditions(), GetDistanceAndNormalForTriangleWalls::setupInitialConditions(), TriangulatedScrewSelfTest::setupInitialConditions(), TriangulatedStepWallSelfTest::setupInitialConditions(), TriangulatedWallSelfTest::setupInitialConditions(), DrumRot::setupInitialConditions(), SingleParticle< SpeciesType >::setupInitialConditions(), ScalingTestInitialConditionsRelax::setupInitialConditions(), ScalingTestRun::setupInitialConditions(), Contact::setupInitialConditions(), GranularCollapse::setupInitialConditions(), EllipticalSuperQuadricCollision::setupInitialConditions(), MercuryProblem::setupInitialConditions(), protectiveWall::setupInitialConditions(), Tutorial11::setupInitialConditions(), Tutorial12::setupInitialConditions(), Tutorial2::setupInitialConditions(), Tutorial3::setupInitialConditions(), Tutorial4::setupInitialConditions(), Tutorial5::setupInitialConditions(), Tutorial6::setupInitialConditions(), Tutorial7::setupInitialConditions(), Tutorial8::setupInitialConditions(), Tutorial9::setupInitialConditions(), PSDSelfTest::setupInitialConditions(), ExtremeOverlapWithWallsUnitTest::setupInitialConditions(), MD_demo::setupInitialConditions(), InclinedPlane::setupInitialConditions(), MultiParticlesInsertion::setupInitialConditions(), MpiPeriodicBoundaryUnitTest::setupInitialConditions(), PeriodicWalls::setupInitialConditions(), PeriodicWallsWithSlidingFrictionUnitTest::setupInitialConditions(), SetDistributionPhiNormalSelfTest::setupInitialConditions(), SinterForceUnitTest::setupInitialConditions(), Chute::setupInitialConditions(), ChuteBottom::setupInitialConditions(), setXMin(), Siegen::Siegen(), FlowFrontChute::stretch(), T_protectiveWall::T_protectiveWall(), StressStrainControlBoundary::updateDomainSize(), viscoElasticUnitTest::viscoElasticUnitTest(), write(), writeFstatHeader(), RotatingDrumBidisperse::writeResults(), inflowFromPeriodic::writeXBallsScript(), and ChuteWithPeriodicInflow::writeXBallsScript().
getXMin()
Mdouble DPMBase::getXMin () const inline
If the length of the problem domain in x-direction is XMax - XMin, then getXMin() returns XMin.
     { return min_.x(); }
References min_, and Vec3D::x().
Referenced by LeesEdwardsDemo::actionsAfterTimeStep(), TimeDependentPeriodicBoundary3DSelfTest::actionsAfterTimeStep(), TimeDependentPeriodicBoundaryTest::actionsAfterTimeStep(), Chutebelt::actionsAfterTimeStep(), Chutebelt::actionsBeforeTimeStep(), Chutebelt::actionsOnRestart(), StressStrainControlBoundary::activateStrainRateControl(), NautaMixer::addParticles(), NautaMixer::addParticlesAtWall(), CFDDEMCoupleTest::CalcPhiPAndFz(), Funnel::check_funnel(), checkSettings(), ChutePeriodicDemo::ChutePeriodicDemo(), Chute::cleanChute(), ClosedCSCRestart::ClosedCSCRestart(), ClosedCSCRun::ClosedCSCRun(), ClosedCSCWalls::ClosedCSCWalls(), MercuryLogo::constructTextAsParticles(), LawinenBox::create_inflow_particle(), ChutePeriodic::create_inflow_particle(), ChuteWithContraction::create_inflow_particle(), ChuteWithVerticalHopper::create_inflow_particle(), FlowRule::create_inflow_particle(), SilbertPeriodic::create_inflow_particle(), Chute::createBottom(), Chute::createFlowParticle(), CSCWalls::CSCWalls(), decompose(), StressStrainControlBoundary::determineStressControlledShearBoundaries(), DomainHandler::getParticleDomainGlobalIndex(), getTotalVolume(), StatisticsVector< T >::getXMinStat(), MarbleRun::includeInDomain(), Indenter::Indenter(), InitialConditions< SpeciesType >::InitialConditions(), HorizontalMixer::introduceParticlesAtWall(), ContactDetectionIntersectionOfWallsTest::introduceParticlesAtWall(), HorizontalMixer::introduceParticlesInDomain(), LeesEdwardsSelfTest::LeesEdwardsSelfTest(), main(), MercuryCGSelfTest::MercuryCGSelfTest(), outputXBallsData(), LiquidMigrationMPI2Test::outputXBallsData(), LiquidMigrationSelfTest::outputXBallsData(), SphericalIndenter::outputXBallsData(), ParticleCreation::ParticleCreation(), protectiveWall::protectiveWall(), readParAndIniFiles(), RotatingDrumBidisperseInitialise::RotatingDrumBidisperseInitialise(), save(), ClosedCSCWalls::saveWalls(), CSCWalls::saveWalls(), StressStrainControlBoundary::set(), CGFields::DisplacementField::setFields(), SphericalIndenter::setIndenterHeight(), T_protectiveWall::setupInitialConditions(), LawinenBox::setupInitialConditions(), ClosedCSCWalls::setupInitialConditions(), CSCInit::setupInitialConditions(), CSCWalls::setupInitialConditions(), ChutePeriodic::setupInitialConditions(), MercuryLogo::setupInitialConditions(), ChangingTOIParticle::setupInitialConditions(), my_problem::setupInitialConditions(), Binary::setupInitialConditions(), ForceLawsMPI2Test::setupInitialConditions(), LiquidMigrationMPI2Test::setupInitialConditions(), CubicCell::setupInitialConditions(), FreeCooling2DinWalls::setupInitialConditions(), FreeCooling2DinWallsDemo::setupInitialConditions(), FreeCooling3DDemoProblem::setupInitialConditions(), FreeCooling3DinWallsDemo::setupInitialConditions(), FreeCoolingDemoProblem::setupInitialConditions(), HeaterBoundaryTest::setupInitialConditions(), HourGlass2D::setupInitialConditions(), HourGlass::setupInitialConditions(), LeesEdwardsDemo::setupInitialConditions(), MarbleRun::setupInitialConditions(), TimeDependentPeriodicBoundary3DSelfTest::setupInitialConditions(), TimeDependentPeriodicBoundaryTest::setupInitialConditions(), Cstatic2d::setupInitialConditions(), SilbertPeriodic::setupInitialConditions(), statistics_while_running< T >::setupInitialConditions(), InitialBed::setupInitialConditions(), GetDistanceAndNormalForIntersectionOfWalls::setupInitialConditions(), GetDistanceAndNormalForScrew::setupInitialConditions(), GetDistanceAndNormalForTriangleWall::setupInitialConditions(), RotatingDrum::setupInitialConditions(), Chutebelt::setupInitialConditions(), SingleParticleSegregation::setupInitialConditions(), ConstantMassFlowMaserSelfTest::setupInitialConditions(), DistributionPhiNormalSelfTest::setupInitialConditions(), clumpTest::setupInitialConditions(), PolydisperseInsertionBoundarySelfTest::setupInitialConditions(), CGHandlerSelfTest::setupInitialConditions(), NewtonsCradleSelftest::setupInitialConditions(), SquarePacking::setupInitialConditions(), ParticleCreation::setupInitialConditions(), ChargedBondedParticleUnitTest::setupInitialConditions(), my_problem_HGRID::setupInitialConditions(), LiquidMigrationSelfTest::setupInitialConditions(), ObliqueImpactSelfTest::setupInitialConditions(), TwoBondedParticleElasticCollision::setupInitialConditions(), TwoParticleBagheriCollision::setupInitialConditions(), TwoParticleClassicalWilletCollision::setupInitialConditions(), TwoParticleElasticCollision::setupInitialConditions(), CoilSelfTest::setupInitialConditions(), GetDistanceAndNormalForTriangleWalls::setupInitialConditions(), TriangulatedScrewSelfTest::setupInitialConditions(), TriangulatedStepWallSelfTest::setupInitialConditions(), TriangulatedWallSelfTest::setupInitialConditions(), DrumRot::setupInitialConditions(), ScalingTestInitialConditionsRelax::setupInitialConditions(), GranularCollapse::setupInitialConditions(), EllipticalSuperQuadricCollision::setupInitialConditions(), MercuryProblem::setupInitialConditions(), protectiveWall::setupInitialConditions(), Tutorial11::setupInitialConditions(), Tutorial12::setupInitialConditions(), Tutorial6::setupInitialConditions(), Tutorial7::setupInitialConditions(), Tutorial8::setupInitialConditions(), ParticleWallInteraction::setupInitialConditions(), PSDSelfTest::setupInitialConditions(), MD_demo::setupInitialConditions(), InclinedPlane::setupInitialConditions(), MpiPeriodicBoundaryUnitTest::setupInitialConditions(), PeriodicWalls::setupInitialConditions(), PeriodicWallsWithSlidingFrictionUnitTest::setupInitialConditions(), SetDistributionPhiNormalSelfTest::setupInitialConditions(), Chute::setupInitialConditions(), ChuteBottom::setupInitialConditions(), setXMax(), FlowFrontChute::stretch(), T_protectiveWall::T_protectiveWall(), StressStrainControlBoundary::updateDomainSize(), write(), writeFstatHeader(), inflowFromPeriodic::writeXBallsScript(), and ChuteWithPeriodicInflow::writeXBallsScript().
getYCenter()
Mdouble DPMBase::getYCenter () const inline
     { return 0.5*(max_.Y+min_.Y); }
References max_, min_, and Vec3D::Y.
Referenced by getCenter().
getYMax()
Mdouble DPMBase::getYMax () const inline
If the length of the problem domain in y-direction is YMax - YMin, then getYMax() returns XMax.
     { return max_.y(); }
References max_, and Vec3D::y().
Referenced by T_protectiveWall::actionsAfterTimeStep(), LeesEdwardsDemo::actionsAfterTimeStep(), TimeDependentPeriodicBoundary3DSelfTest::actionsAfterTimeStep(), TimeDependentPeriodicBoundaryTest::actionsAfterTimeStep(), GranularCollapse::actionsAfterTimeStep(), protectiveWall::actionsAfterTimeStep(), SmoothChute::actionsBeforeTimeStep(), Chutebelt::actionsOnRestart(), StressStrainControlBoundary::activateStrainRateControl(), ChuteWithHopper::addHopper(), NautaMixer::addParticles(), NautaMixer::addParticlesAtWall(), CFDDEMCoupleTest::CalcPhiPAndFz(), Funnel::check_funnel(), checkSettings(), ChuteWithContraction::ChuteWithContraction(), ChuteWithPeriodicInflowAndContraction::ChuteWithPeriodicInflowAndContraction(), ClosedCSCRestart::ClosedCSCRestart(), ClosedCSCRun::ClosedCSCRun(), ClosedCSCWalls::ClosedCSCWalls(), MercuryLogo::constructTextAsParticles(), ContractionWithPeriodicInflow::ContractionWithPeriodicInflow(), LawinenBox::create_inflow_particle(), ChutePeriodic::create_inflow_particle(), ChuteWithContraction::create_inflow_particle(), ChuteWithVerticalHopper::create_inflow_particle(), FlowRule::create_inflow_particle(), SilbertPeriodic::create_inflow_particle(), SegregationWithHopper::create_inflow_particle(), Funnel::create_walls(), Chute::createBottom(), Chute::createFlowParticle(), CSCWalls::CSCWalls(), decompose(), StressStrainControlBoundary::determineStressControlledShearBoundaries(), ChuteWithPeriodicInflow::ExtendInWidth(), Chute::getChuteWidth(), DomainHandler::getParticleDomainGlobalIndex(), getTotalVolume(), StatisticsVector< T >::getYMaxStat(), MarbleRun::includeInDomain(), Indenter::Indenter(), InitialConditions< SpeciesType >::InitialConditions(), HorizontalMixer::introduceParticlesAtWall(), HorizontalMixer::introduceParticlesInDomain(), LawinenBox::LawinenBox(), LeesEdwardsSelfTest::LeesEdwardsSelfTest(), main(), MercuryCGSelfTest::MercuryCGSelfTest(), outputXBallsData(), LiquidMigrationMPI2Test::outputXBallsData(), LiquidMigrationSelfTest::outputXBallsData(), SphericalIndenter::outputXBallsData(), ParticleCreation::ParticleCreation(), protectiveWall::protectiveWall(), readParAndIniFiles(), regimeForceUnitTest::regimeForceUnitTest(), save(), ClosedCSCWalls::saveWalls(), CSCWalls::saveWalls(), StressStrainControlBoundary::set(), CGFields::DisplacementField::setFields(), SphericalIndenter::setIndenterHeight(), T_protectiveWall::setupInitialConditions(), LawinenBox::setupInitialConditions(), ClosedCSCWalls::setupInitialConditions(), CSCInit::setupInitialConditions(), CSCWalls::setupInitialConditions(), ChutePeriodic::setupInitialConditions(), MercuryLogo::setupInitialConditions(), SmoothChute::setupInitialConditions(), ChangingTOIParticle::setupInitialConditions(), CFDDEMCoupleTest::setupInitialConditions(), HorizontalMixer::setupInitialConditions(), RotatingDrumWet::setupInitialConditions(), Binary::setupInitialConditions(), my_problem::setupInitialConditions(), CubicCell::setupInitialConditions(), FreeCooling2DinWalls::setupInitialConditions(), FreeCooling2DinWallsDemo::setupInitialConditions(), FreeCooling3DDemoProblem::setupInitialConditions(), FreeCooling3DinWallsDemo::setupInitialConditions(), FreeCoolingDemoProblem::setupInitialConditions(), HeaterBoundaryTest::setupInitialConditions(), HourGlass::setupInitialConditions(), LeesEdwardsDemo::setupInitialConditions(), MarbleRun::setupInitialConditions(), MinimalExampleDrum::setupInitialConditions(), TimeDependentPeriodicBoundary3DSelfTest::setupInitialConditions(), TimeDependentPeriodicBoundaryTest::setupInitialConditions(), AngleOfRepose::setupInitialConditions(), SilbertPeriodic::setupInitialConditions(), statistics_while_running< T >::setupInitialConditions(), InitialBed::setupInitialConditions(), Chutebelt::setupInitialConditions(), ConstantMassFlowMaserSelfTest::setupInitialConditions(), DistributionPhiNormalSelfTest::setupInitialConditions(), clumpTest::setupInitialConditions(), PolydisperseInsertionBoundarySelfTest::setupInitialConditions(), CGHandlerSelfTest::setupInitialConditions(), NewtonsCradleSelftest::setupInitialConditions(), SquarePacking::setupInitialConditions(), ParticleCreation::setupInitialConditions(), ChargedBondedParticleUnitTest::setupInitialConditions(), my_problem_HGRID::setupInitialConditions(), FreeFallInteractionSelfTest::setupInitialConditions(), FreeFallSelfTest::setupInitialConditions(), LiquidMigrationSelfTest::setupInitialConditions(), TwoBondedParticleElasticCollision::setupInitialConditions(), TwoParticleBagheriCollision::setupInitialConditions(), TwoParticleClassicalWilletCollision::setupInitialConditions(), TwoParticleCollisionInteraction::setupInitialConditions(), TwoParticleElasticCollision::setupInitialConditions(), CoilSelfTest::setupInitialConditions(), TriangulatedScrewSelfTest::setupInitialConditions(), TriangulatedWallSelfTest::setupInitialConditions(), DrumRot::setupInitialConditions(), RotatingDrum::setupInitialConditions(), ScalingTestInitialConditionsRelax::setupInitialConditions(), ScalingTestRun::setupInitialConditions(), Contact::setupInitialConditions(), GranularCollapse::setupInitialConditions(), EllipticalSuperQuadricCollision::setupInitialConditions(), MercuryProblem::setupInitialConditions(), protectiveWall::setupInitialConditions(), Tutorial11::setupInitialConditions(), Tutorial12::setupInitialConditions(), Tutorial2::setupInitialConditions(), Tutorial3::setupInitialConditions(), Tutorial4::setupInitialConditions(), Tutorial5::setupInitialConditions(), Tutorial6::setupInitialConditions(), Tutorial7::setupInitialConditions(), Tutorial8::setupInitialConditions(), Tutorial9::setupInitialConditions(), MD_demo::setupInitialConditions(), MultiParticlesInsertion::setupInitialConditions(), MpiPeriodicBoundaryUnitTest::setupInitialConditions(), PeriodicWalls::setupInitialConditions(), PeriodicWallsWithSlidingFrictionUnitTest::setupInitialConditions(), SetDistributionPhiNormalSelfTest::setupInitialConditions(), SinterForceUnitTest::setupInitialConditions(), Chute::setupInitialConditions(), ChuteBottom::setupInitialConditions(), ChuteWithHopper::setupInitialConditions(), Chute::setupSideWalls(), setYMin(), T_protectiveWall::T_protectiveWall(), StressStrainControlBoundary::updateDomainSize(), viscoElasticUnitTest::viscoElasticUnitTest(), write(), writeFstatHeader(), inflowFromPeriodic::writeXBallsScript(), and ChuteWithPeriodicInflow::writeXBallsScript().
getYMin()
Mdouble DPMBase::getYMin () const inline
If the length of the problem domain in y-direction is YMax - YMin, then getYMin() returns YMin.
     { return min_.y(); }
References min_, and Vec3D::y().
Referenced by LeesEdwardsDemo::actionsAfterTimeStep(), TimeDependentPeriodicBoundary3DSelfTest::actionsAfterTimeStep(), TimeDependentPeriodicBoundaryTest::actionsAfterTimeStep(), SmoothChute::actionsBeforeTimeStep(), Chutebelt::actionsOnRestart(), StressStrainControlBoundary::activateStrainRateControl(), ChuteWithHopper::addHopper(), NautaMixer::addParticles(), NautaMixer::addParticlesAtWall(), CFDDEMCoupleTest::CalcPhiPAndFz(), Funnel::check_funnel(), checkSettings(), ChuteWithContraction::ChuteWithContraction(), ChuteWithPeriodicInflowAndContraction::ChuteWithPeriodicInflowAndContraction(), ClosedCSCRestart::ClosedCSCRestart(), ClosedCSCRun::ClosedCSCRun(), ClosedCSCWalls::ClosedCSCWalls(), ContractionWithPeriodicInflow::ContractionWithPeriodicInflow(), LawinenBox::create_inflow_particle(), ChutePeriodic::create_inflow_particle(), ChuteWithContraction::create_inflow_particle(), ChuteWithVerticalHopper::create_inflow_particle(), FlowRule::create_inflow_particle(), SilbertPeriodic::create_inflow_particle(), SegregationWithHopper::create_inflow_particle(), Funnel::create_walls(), Chute::createBottom(), Chute::createFlowParticle(), CSCWalls::CSCWalls(), decompose(), StressStrainControlBoundary::determineStressControlledShearBoundaries(), ChuteWithPeriodicInflow::ExtendInWidth(), DomainHandler::getParticleDomainGlobalIndex(), getTotalVolume(), StatisticsVector< T >::getYMinStat(), MarbleRun::includeInDomain(), Indenter::Indenter(), InitialConditions< SpeciesType >::InitialConditions(), HorizontalMixer::introduceParticlesAtWall(), HorizontalMixer::introduceParticlesInDomain(), LeesEdwardsSelfTest::LeesEdwardsSelfTest(), main(), MercuryCGSelfTest::MercuryCGSelfTest(), outputXBallsData(), LiquidMigrationMPI2Test::outputXBallsData(), LiquidMigrationSelfTest::outputXBallsData(), SphericalIndenter::outputXBallsData(), ParticleCreation::ParticleCreation(), readParAndIniFiles(), RotatingDrumBidisperseInitialise::RotatingDrumBidisperseInitialise(), save(), ClosedCSCWalls::saveWalls(), CSCWalls::saveWalls(), StressStrainControlBoundary::set(), CGFields::DisplacementField::setFields(), SphericalIndenter::setIndenterHeight(), T_protectiveWall::setupInitialConditions(), LawinenBox::setupInitialConditions(), ClosedCSCWalls::setupInitialConditions(), CSCInit::setupInitialConditions(), CSCWalls::setupInitialConditions(), ChutePeriodic::setupInitialConditions(), MercuryLogo::setupInitialConditions(), SmoothChute::setupInitialConditions(), ChangingTOIParticle::setupInitialConditions(), my_problem::setupInitialConditions(), RotatingDrumWet::setupInitialConditions(), Binary::setupInitialConditions(), CubicCell::setupInitialConditions(), FreeCooling2DinWalls::setupInitialConditions(), FreeCooling2DinWallsDemo::setupInitialConditions(), FreeCooling3DDemoProblem::setupInitialConditions(), FreeCooling3DinWallsDemo::setupInitialConditions(), FreeCoolingDemoProblem::setupInitialConditions(), HeaterBoundaryTest::setupInitialConditions(), HourGlass::setupInitialConditions(), LeesEdwardsDemo::setupInitialConditions(), MarbleRun::setupInitialConditions(), MinimalExampleDrum::setupInitialConditions(), TimeDependentPeriodicBoundary3DSelfTest::setupInitialConditions(), TimeDependentPeriodicBoundaryTest::setupInitialConditions(), SilbertPeriodic::setupInitialConditions(), statistics_while_running< T >::setupInitialConditions(), InitialBed::setupInitialConditions(), Chutebelt::setupInitialConditions(), ConstantMassFlowMaserSelfTest::setupInitialConditions(), DistributionPhiNormalSelfTest::setupInitialConditions(), clumpTest::setupInitialConditions(), PolydisperseInsertionBoundarySelfTest::setupInitialConditions(), CGHandlerSelfTest::setupInitialConditions(), NewtonsCradleSelftest::setupInitialConditions(), SquarePacking::setupInitialConditions(), ParticleCreation::setupInitialConditions(), ChargedBondedParticleUnitTest::setupInitialConditions(), my_problem_HGRID::setupInitialConditions(), FreeFallSelfTest::setupInitialConditions(), LiquidMigrationSelfTest::setupInitialConditions(), ObliqueImpactSelfTest::setupInitialConditions(), TwoBondedParticleElasticCollision::setupInitialConditions(), TwoParticleBagheriCollision::setupInitialConditions(), TwoParticleClassicalWilletCollision::setupInitialConditions(), TwoParticleElasticCollision::setupInitialConditions(), CoilSelfTest::setupInitialConditions(), TriangulatedScrewSelfTest::setupInitialConditions(), TriangulatedWallSelfTest::setupInitialConditions(), DrumRot::setupInitialConditions(), RotatingDrum::setupInitialConditions(), ScalingTestInitialConditionsRelax::setupInitialConditions(), GranularCollapse::setupInitialConditions(), EllipticalSuperQuadricCollision::setupInitialConditions(), MercuryProblem::setupInitialConditions(), protectiveWall::setupInitialConditions(), Tutorial11::setupInitialConditions(), Tutorial12::setupInitialConditions(), Tutorial7::setupInitialConditions(), Tutorial8::setupInitialConditions(), FreeFallHertzMindlinUnitTest::setupInitialConditions(), MD_demo::setupInitialConditions(), InclinedPlane::setupInitialConditions(), MpiPeriodicBoundaryUnitTest::setupInitialConditions(), PeriodicWalls::setupInitialConditions(), PeriodicWallsWithSlidingFrictionUnitTest::setupInitialConditions(), SetDistributionPhiNormalSelfTest::setupInitialConditions(), Chute::setupInitialConditions(), ChuteBottom::setupInitialConditions(), ChuteWithHopper::setupInitialConditions(), Chute::setupSideWalls(), setYMax(), StressStrainControlBoundary::updateDomainSize(), write(), writeFstatHeader(), inflowFromPeriodic::writeXBallsScript(), and ChuteWithPeriodicInflow::writeXBallsScript().
getZCenter()
Mdouble DPMBase::getZCenter () const inline
     { return 0.5*(max_.Z+min_.Z); }
References max_, min_, and Vec3D::Z.
Referenced by getCenter().
getZMax()
Mdouble DPMBase::getZMax () const inline
If the length of the problem domain in z-direction is ZMax - ZMin, then getZMax() returns ZMax.
     { return max_.z(); }
References max_, and Vec3D::z().
Referenced by SmoothChute::actionsBeforeTimeStep(), Chutebelt::actionsOnRestart(), StressStrainControlBoundary::activateStrainRateControl(), NautaMixer::addParticles(), NautaMixer::addParticlesAtWall(), CFDDEMCoupleTest::CalcPhiPAndFz(), checkSettings(), ClosedCSCWalls::ClosedCSCWalls(), MercuryLogo::constructTextAsParticles(), Funnel::create_funnel(), LawinenBox::create_inflow_particle(), ChuteWithContraction::create_inflow_particle(), ChuteWithVerticalHopper::create_inflow_particle(), CSCWalls::CSCWalls(), decompose(), StressStrainControlBoundary::determineStressControlledShearBoundaries(), DomainHandler::getParticleDomainGlobalIndex(), getTotalVolume(), StatisticsVector< T >::getZMaxStat(), MarbleRun::includeInDomain(), ContactDetectionIntersectionOfWallsTest::introduceParticlesAtWall(), LaserOnLayer::LaserOnLayer(), LawinenBox::LawinenBox(), main(), MercuryCGSelfTest::MercuryCGSelfTest(), outputXBallsData(), LiquidMigrationMPI2Test::outputXBallsData(), LiquidMigrationSelfTest::outputXBallsData(), SphericalIndenter::outputXBallsData(), ParticleCreation::ParticleCreation(), protectiveWall::protectiveWall(), readParAndIniFiles(), regimeForceUnitTest::regimeForceUnitTest(), save(), ClosedCSCWalls::saveWalls(), CSCWalls::saveWalls(), StressStrainControlBoundary::set(), CGFields::DisplacementField::setFields(), T_protectiveWall::setupInitialConditions(), LawinenBox::setupInitialConditions(), ClosedCSCWalls::setupInitialConditions(), CSCInit::setupInitialConditions(), CSCWalls::setupInitialConditions(), MercuryLogo::setupInitialConditions(), SmoothChute::setupInitialConditions(), ChangingTOIParticle::setupInitialConditions(), CFDDEMCoupleTest::setupInitialConditions(), NozzleDemo::setupInitialConditions(), Binary::setupInitialConditions(), MpiPeriodicBoundaryUnitTest::setupInitialConditions(), CubicCell::setupInitialConditions(), FreeCooling3DDemoProblem::setupInitialConditions(), FreeCooling3DinWallsDemo::setupInitialConditions(), HeaterBoundaryTest::setupInitialConditions(), HourGlass2D::setupInitialConditions(), HourGlass::setupInitialConditions(), MarbleRun::setupInitialConditions(), TimeDependentPeriodicBoundary3DSelfTest::setupInitialConditions(), AngleOfRepose::setupInitialConditions(), SilbertPeriodic::setupInitialConditions(), GetDistanceAndNormalForIntersectionOfWalls::setupInitialConditions(), GetDistanceAndNormalForScrew::setupInitialConditions(), GetDistanceAndNormalForTriangleWall::setupInitialConditions(), RotatingDrum::setupInitialConditions(), Chutebelt::setupInitialConditions(), ConstantMassFlowMaserSelfTest::setupInitialConditions(), DistributionPhiNormalSelfTest::setupInitialConditions(), NozzleSelfTest::setupInitialConditions(), clumpTest::setupInitialConditions(), CGHandlerSelfTest::setupInitialConditions(), NewtonsCradleSelftest::setupInitialConditions(), ParticleCreation::setupInitialConditions(), ChargedBondedParticleUnitTest::setupInitialConditions(), DPM::setupInitialConditions(), TwoParticleCollisionInteraction::setupInitialConditions(), CoilSelfTest::setupInitialConditions(), GetDistanceAndNormalForTriangleWalls::setupInitialConditions(), TriangulatedScrewSelfTest::setupInitialConditions(), TriangulatedStepWallSelfTest::setupInitialConditions(), TriangulatedWallSelfTest::setupInitialConditions(), DrumRot::setupInitialConditions(), ScalingTestInitialConditionsRelax::setupInitialConditions(), ScalingTestRun::setupInitialConditions(), Contact::setupInitialConditions(), EllipticalSuperQuadricCollision::setupInitialConditions(), protectiveWall::setupInitialConditions(), Tutorial11::setupInitialConditions(), Tutorial2::setupInitialConditions(), Tutorial3::setupInitialConditions(), Tutorial4::setupInitialConditions(), Tutorial5::setupInitialConditions(), Tutorial6::setupInitialConditions(), PSDSelfTest::setupInitialConditions(), FreeFall::setupInitialConditions(), MD_demo::setupInitialConditions(), MultiParticlesInsertion::setupInitialConditions(), SetDistributionPhiNormalSelfTest::setupInitialConditions(), SinterForceUnitTest::setupInitialConditions(), Chute::setupInitialConditions(), ChuteBottom::setupInitialConditions(), setZMin(), Siegen::Siegen(), SilbertHstop::solve_analytic(), T_protectiveWall::T_protectiveWall(), StressStrainControlBoundary::updateDomainSize(), viscoElasticUnitTest::viscoElasticUnitTest(), write(), writeFstatHeader(), inflowFromPeriodic::writeXBallsScript(), and ChuteWithPeriodicInflow::writeXBallsScript().
getZMin()
Mdouble DPMBase::getZMin () const inline
If the length of the problem domain in z-direction is ZMax - ZMin, then getZMin() returns ZMin.
     { return min_.z(); }
References min_, and Vec3D::z().
Referenced by HourGlass2D::actionsAfterTimeStep(), HourGlass::actionsAfterTimeStep(), Tutorial11::actionsAfterTimeStep(), SmoothChute::actionsBeforeTimeStep(), Chutebelt::actionsOnRestart(), StressStrainControlBoundary::activateStrainRateControl(), SilbertPeriodic::add_flow_particles(), NautaMixer::addParticles(), NautaMixer::addParticlesAtWall(), checkSettings(), Funnel::cleanChute(), inflowFromPeriodic::cleanChute(), ClosedCSCWalls::ClosedCSCWalls(), LawinenBox::create_inflow_particle(), ChutePeriodic::create_inflow_particle(), ChuteWithContraction::create_inflow_particle(), ChuteWithVerticalHopper::create_inflow_particle(), FlowRule::create_inflow_particle(), SilbertPeriodic::create_inflow_particle(), Chute::createBottom(), Chute::createFlowParticle(), CSCWalls::CSCWalls(), decompose(), StressStrainControlBoundary::determineStressControlledShearBoundaries(), SphericalIndenter::getBedHeight(), DomainHandler::getParticleDomainGlobalIndex(), getTotalVolume(), StatisticsVector< T >::getZMinStat(), MarbleRun::includeInDomain(), InitialConditions< SpeciesType >::InitialConditions(), HorizontalMixer::introduceParticlesAtWall(), ContactDetectionIntersectionOfWallsTest::introduceParticlesAtWall(), HorizontalMixer::introduceParticlesInDomain(), main(), MercuryCGSelfTest::MercuryCGSelfTest(), outputXBallsData(), LiquidMigrationMPI2Test::outputXBallsData(), LiquidMigrationSelfTest::outputXBallsData(), SphericalIndenter::outputXBallsData(), ParticleCreation::ParticleCreation(), readParAndIniFiles(), save(), ClosedCSCWalls::saveWalls(), CSCWalls::saveWalls(), StressStrainControlBoundary::set(), CGFields::DisplacementField::setFields(), HorizontalMixer::setOuterWalls(), T_protectiveWall::setupInitialConditions(), LawinenBox::setupInitialConditions(), ClosedCSCWalls::setupInitialConditions(), CSCInit::setupInitialConditions(), CSCWalls::setupInitialConditions(), MercuryLogo::setupInitialConditions(), SmoothChute::setupInitialConditions(), ChangingTOIParticle::setupInitialConditions(), CFDDEMCoupleTest::setupInitialConditions(), NozzleDemo::setupInitialConditions(), Binary::setupInitialConditions(), my_problem::setupInitialConditions(), Chain::setupInitialConditions(), MpiPeriodicBoundaryUnitTest::setupInitialConditions(), CubicCell::setupInitialConditions(), FreeCooling3DDemoProblem::setupInitialConditions(), FreeCooling3DinWallsDemo::setupInitialConditions(), HeaterBoundaryTest::setupInitialConditions(), HourGlass2D::setupInitialConditions(), HourGlass::setupInitialConditions(), MarbleRun::setupInitialConditions(), TimeDependentPeriodicBoundary3DSelfTest::setupInitialConditions(), AngleOfRepose::setupInitialConditions(), InitialBed::setupInitialConditions(), GetDistanceAndNormalForIntersectionOfWalls::setupInitialConditions(), GetDistanceAndNormalForScrew::setupInitialConditions(), GetDistanceAndNormalForTriangleWall::setupInitialConditions(), RotatingDrum::setupInitialConditions(), Chutebelt::setupInitialConditions(), ConstantMassFlowMaserSelfTest::setupInitialConditions(), DistributionPhiNormalSelfTest::setupInitialConditions(), NozzleSelfTest::setupInitialConditions(), clumpTest::setupInitialConditions(), PolydisperseInsertionBoundarySelfTest::setupInitialConditions(), CGHandlerSelfTest::setupInitialConditions(), NewtonsCradleSelftest::setupInitialConditions(), NewtonsCradleSelfTest::setupInitialConditions(), ParticleCreation::setupInitialConditions(), ChargedBondedParticleUnitTest::setupInitialConditions(), DPM::setupInitialConditions(), TwoParticleCollisionInteraction::setupInitialConditions(), CoilSelfTest::setupInitialConditions(), GetDistanceAndNormalForTriangleWalls::setupInitialConditions(), TriangulatedScrewSelfTest::setupInitialConditions(), TriangulatedStepWallSelfTest::setupInitialConditions(), DrumRot::setupInitialConditions(), ScalingTestInitialConditionsRelax::setupInitialConditions(), GranularCollapse::setupInitialConditions(), EllipticalSuperQuadricCollision::setupInitialConditions(), protectiveWall::setupInitialConditions(), Tutorial11::setupInitialConditions(), Tutorial3::setupInitialConditions(), Tutorial4::setupInitialConditions(), Tutorial9::setupInitialConditions(), PSDSelfTest::setupInitialConditions(), MD_demo::setupInitialConditions(), MultiParticlesInsertion::setupInitialConditions(), SetDistributionPhiNormalSelfTest::setupInitialConditions(), WallSpecies::setupInitialConditions(), Chute::setupInitialConditions(), ChuteBottom::setupInitialConditions(), setZMax(), StressStrainControlBoundary::updateDomainSize(), write(), writeFstatHeader(), inflowFromPeriodic::writeXBallsScript(), and ChuteWithPeriodicInflow::writeXBallsScript().
handleParticleAddition()
void DPMBase::handleParticleAddition (unsigned int id, BaseParticle * p) virtual
Handles the addition of particles to the particleHandler.
This function is called by ParticleHandler::addObject and ParticleHandler::addGhostObject to broadcast the addition of a particle from the handler. It passes the information on to the walls in the wallHandler.
Parameters
[in] id The id of the removed particle.
[in] p A pointer to the particle.
 {
     for (auto w: wallHandler)
     {
         w->handleParticleAddition(id, p);
     }
 }
References p, w, and wallHandler.
Referenced by ParticleHandler::addGhostObject(), and ParticleHandler::addObject().
handleParticleRemoval()
void DPMBase::handleParticleRemoval (unsigned int id) virtual
Handles the removal of particles from the particleHandler.
This function is called by ParticleHandler::removeObject and ParticleHandler::removeGhostObject to broadcast the removal of a particle from the handler. It passes the information on to the walls in the wallHandler.
Parameters
[in] id The id of the removed particle.
 {
     for (auto w: wallHandler)
     {
         w->handleParticleRemoval(id);
     }
 }
References w, and wallHandler.
Referenced by ParticleHandler::clear(), ParticleHandler::removeGhostObject(), ParticleHandler::removeLastObject(), and ParticleHandler::removeObject().
hGridActionsAfterIntegration()
void DPMBase::hGridActionsAfterIntegration () protected virtual
This function has to be called after integrateBeforeForceComputation.
no implementation but can be overridden in its derived classes.
Reimplemented in MercuryBase.
 {
 }
Referenced by computeOneTimeStep().
hGridActionsBeforeIntegration()
void DPMBase::hGridActionsBeforeIntegration () protected virtual
This function has to be called before integrateBeforeForceComputation.
no implementation but can be overridden in its derived classes.
Reimplemented in MercuryBase.
 {
 }
Referenced by computeOneTimeStep().
hGridActionsBeforeTimeLoop()
void DPMBase::hGridActionsBeforeTimeLoop () protected virtual
A virtual function that allows one to carry out hGrid operations before the start of the time loop.
no implementation but can be overridden in its derived classes.
Reimplemented in MercuryBase.
 {
 }
Referenced by initialiseSolve().
hGridActionsBeforeTimeStep()
void DPMBase::hGridActionsBeforeTimeStep () protected virtual
A virtual function that allows one to set or execute hGrid parameters or operations before every simulation time step.
no implementation but can be overridden in its derived classes.
Reimplemented in MercuryBase.
 {
 }
Referenced by computeOneTimeStep(), and initialiseSolve().
hGridGetInteractingParticleList()
virtual void DPMBase::hGridGetInteractingParticleList (BaseParticle * obj, std::vector< BaseParticle * > & list) inline virtual
Creates a list of neighbour particles obtained from the hgrid.
Reimplemented in Mercury3D, and Mercury2D.
     {};
Referenced by PeriodicBoundaryHandler::processLocalInteractionData(), PeriodicBoundaryHandler::processReceivedInteractionData(), and Domain::processReceivedInteractionData().
hGridInsertParticle()
void DPMBase::hGridInsertParticle (BaseParticle *obj UNUSED) virtual
Bug:
Why are the hGRID actions public, this seems wrong. Someone please comment [Ant].
no implementation but can be overridden in its derived classes.
 {
 }
Referenced by ParticleHandler::addExistingObject(), ParticleHandler::addGhostObject(), and ParticleHandler::addObject().
hGridRemoveParticle()
void DPMBase::hGridRemoveParticle (BaseParticle *obj UNUSED) virtual
no implementation but can be overridden in its derived classes.
 {
 }
Referenced by ParticleHandler::removeGhostObject(), ParticleHandler::removeLastObject(), and ParticleHandler::removeObject().
hGridUpdateMove()
void DPMBase::hGridUpdateMove (BaseParticle * , Mdouble) virtual
no implementation but can be overridden in its derived classes.
Reimplemented in MercuryBase.
 {
 }
Referenced by PeriodicBoundary::checkBoundaryAfterParticlesMove(), BaseParticle::integrateBeforeForceComputation(), ClumpParticle::integrateBeforeForceComputation(), Domain::updateParticlePosition(), and PeriodicBoundaryHandler::updateParticles().
hGridUpdateParticle()
void DPMBase::hGridUpdateParticle (BaseParticle *obj UNUSED) virtual
no implementation but can be overridden in its derived classes.
 {
 }
Referenced by ParticleHandler::addExistingObject(), ParticleHandler::addGhostObject(), ParticleHandler::addObject(), MercuryBase::hGridActionsBeforeTimeStep(), and MercuryBase::hGridRebuild().
importParticlesAs()
void DPMBase::importParticlesAs (ParticleHandler & particleH, InteractionHandler & interactionH, const ParticleSpecies * species)
Copies particles, interactions assigning species from a local simulation to a global one. Useful for the creation of a cluster.
Copies particles, interactions assigning species from a local simulation to a global one; useful for the creation of a cluster.
Parameters
[in] particleH the particle handler from wich particles are copied,
[in] particleH the interaction handler from wich interactions are copied,
[in] species the species that will be assigned to the particle.
 {
     size_t nParticlesPreviouslyIn = particleHandler.getSize();
     for (auto k = particleH.begin(); k != particleH.end(); ++k) {
         auto p = particleHandler.copyAndAddObject( *k );
         p->setSpecies(species);
     }
     for (std::vector<BaseInteraction*>::const_iterator i = interactionH.begin(); i != interactionH.end(); ++i) {
         if ( (*i)->getP()->getInvMass() != 0.0 && (*i)->getI()->getInvMass() != 0.0 ) {
             auto j = interactionHandler.copyAndAddObject(*i);
             j->importP(particleHandler.getObject(nParticlesPreviouslyIn + j->getP()->getIndex()));
             j->importI(particleHandler.getObject(nParticlesPreviouslyIn + j->getI()->getIndex()));
             j->setTimeStamp(getNumberOfTimeSteps());
         }
     }
 }
References BaseHandler< T >::begin(), BaseHandler< T >::copyAndAddObject(), BaseHandler< T >::end(), getNumberOfTimeSteps(), BaseHandler< T >::getObject(), BaseHandler< T >::getSize(), i, interactionHandler, j, k, p, and particleHandler.
incrementRunNumberInFile()
void DPMBase::incrementRunNumberInFile () static
Increment the run Number (counter value) stored in the file_counter (COUNTER_DONOTDEL) by 1 and store the new value in the counter file.
In order to increment the counter stored in COUNTER_DONOTDEL, we initialise two fstream objects counter_file, counter_file2 and an integer type temp_counter. First we open the file COUNTER_DONOTDEL, check if everything went fine with the opening. If yes, we extract the runNumber (counter) into the temp_counter. Increment the temp_counter and then write it into COUNTER_DONOTDEL. This is how we increment the counter in the file.
 {
 //opening two filestreams - counter_file and counter_file2
 std::fstream counter_file, counter_file2;
 //declares an integer, temp_counter
 int temp_counter;
 //attempts to open the COUNTER_DONOTDEL text file
 counter_file.open("COUNTER_DONOTDEL", std::ios::in);
 //gives error message if file could not be successfully opened and ends the program
 if (counter_file.fail())
 {
 fprintf(stderr, "\n\n\tERROR :: Counter File NOT found, please re-create\n\n");
 counter_file.close();
 exit(0);
 }
 // if opened successfully, reads in the counter corresponding to the current run number
 //and stored it in the "temp_counter" variable
 counter_file >> temp_counter;
 counter_file.close();
 //Increments the temp_counter
 temp_counter++;
 //opens an output stream to the COUNTER_DONOTDEL file
 counter_file2.open("COUNTER_DONOTDEL", std::ios::out);
 if (counter_file2.fail())
 {
 fprintf(stderr, "\n\n\tERROR :: Counter File NOT found, please re-create2\n\n");
 counter_file2.close();
 exit(0);
 }
 //writes the new value of the counter to COUNTER_DONOTDEL
 counter_file2 << temp_counter;
 counter_file2.close();
 }
References out().
Referenced by autoNumber().
initialiseSolve()
void DPMBase::initialiseSolve ()
Beginning of the solve routine, before time stepping.
Initialises the time, sets up the initial conditions for the simulation by calling the setupInitialConditions() and resets the counter using setNExtSavedTimeStep().
HGrid operations which is the contact detection algorithm.
Checks if the basic essentials are set for carrying out the simulations using checkSettings()
And many more vital operations.
Further details are included in the body of the code, below.
Todo:
Is it necessary to reset initial conditions here and in setTimeStepByParticle (i.e. should it be in constructor) Thomas: I agree, setTimeStepByParticle should be rewritten to work without calling setupInitialConditions
Initialise the time and sets up the initial conditions for the simulation
Todo:
Is it necessary to reset initial conditions here and in setTimeStepByParticle (i.e. should it be in constructor)? Thomas: I agree, setTimeStepByParticle should be rewritten to work without calling setupInitialConditions
Todo:
MX: Why does the mass get computed here? if a particle is assigned a radius, it automatically also computes its mass. IFCD: commenting out this line does not make any test fail on my system.
{
     logger(DEBUG, "Entered solve");
 #ifdef CONTACT_LIST_HGRID
     logger(INFO,"Using CONTACT_LIST_HGRID");
 #endif
     if (!getRestarted()) {
         // If the simulation is "new" (i.e. not restarted):
         // - set time, nTimeSteps to zero
         // - reset the file counter etc.
         // - decompose the domain based on XMin, XMax, ....
         // - run user-defined setupInitialConditions
         numberOfTimeSteps_ = 0;
         setTime(0.0);
         resetFileCounter();
         decompose();
         // \todo tw there was a function combining the next two lines, why is it back to the old version?
         //setLastSavedTimeStep(NEVER); //reset the counter
         //this is to ensure that the interaction time stamps agree with the resetting of the time value
         for (auto &i: interactionHandler)
             i->setTimeStamp(0);
         setupInitialConditions();
         logger(DEBUG, "Have created the particles initial conditions");
     } else {
         // If the simulation is "restarted" (i.e. not restarted):
         // - run wall-defined actionsOnRestart
         for (auto w: wallHandler) {
             w->actionsOnRestart();
         }
         // - run user-defined actionsOnRestart
         actionsOnRestart();
     }
     // Check that the code has been correctly set up,
     // i.e. system dimensions, particles and time steps are sensibly implemented
     checkSettings();
     // If the simulation is "new" and the runNumber is used, append the run number to the problem name
     if (getRunNumber() > 0 && !getRestarted()) {
         std::stringstream name;
         name << getName() << "." << getRunNumber();
         setName(name.str());
     }
     //If append is true, files are appended, not overwritten
     if (getAppend()) {
         setOpenMode(std::fstream::out | std::fstream::app);
         //Restart files should always be overwritten.
         restartFile.setOpenMode(std::fstream::out);
     } else {
         setOpenMode(std::fstream::out);
     }
     initialiseVTK();
     //sets the hgrid, writes headers to the .stat output file
     initialiseStatistics();
     if (getInteractionFile().getFileType() == FileType::ONE_FILE) {
         logger(WARN, "Warning: interaction file will take up a lot of disk space!");
         getInteractionFile().open();
     }
     // Sets the mass of all particle.
     particleHandler.computeAllMasses();
     // Other initialisations
     //max_radius = getLargestParticle()->getRadius();
     actionsBeforeTimeLoop();
     boundaryHandler.boundaryActionsBeforeTimeLoop();
     hGridActionsBeforeTimeLoop();
     if (!getRestarted())
     {
         // Performs a first force computation
         checkAndDuplicatePeriodicParticles();
         logger(DEBUG, "about to call performGhostParticleUpdate()");
         performGhostParticleUpdate();
         hGridActionsBeforeTimeStep();
         computeAllForces();
         removeDuplicatePeriodicParticles();
         interactionHandler.actionsAfterTimeStep();
         logger(DEBUG, "Have computed the initial values for the forces ");
     }
 }
References InteractionHandler::actionsAfterTimeStep(), actionsBeforeTimeLoop(), actionsOnRestart(), BoundaryHandler::boundaryActionsBeforeTimeLoop(), boundaryHandler, checkAndDuplicatePeriodicParticles(), checkSettings(), computeAllForces(), ParticleHandler::computeAllMasses(), DEBUG, decompose(), getAppend(), getInteractionFile(), getName(), getRestarted(), getRunNumber(), hGridActionsBeforeTimeLoop(), hGridActionsBeforeTimeStep(), i, INFO, initialiseStatistics(), initialiseVTK(), interactionHandler, logger, plotDoE::name, numberOfTimeSteps_, ONE_FILE, File::open(), out(), particleHandler, performGhostParticleUpdate(), removeDuplicatePeriodicParticles(), resetFileCounter(), restartFile, setName(), setOpenMode(), File::setOpenMode(), setTime(), setupInitialConditions(), w, wallHandler, and WARN.
Referenced by solve().
initialiseStatistics()
void DPMBase::initialiseStatistics () protected virtual
This function is overridden by StatisticsVector
Reimplemented in statistics_while_running< T >, StatisticsVector< T >, StatisticsVector< O >, StatisticsVector< XZ >, and statistics_while_running< T >.
 {
     cgHandler.initialise();
 }
References cgHandler, and CGHandler::initialise().
Referenced by initialiseSolve().
initialiseVTK()
void DPMBase::initialiseVTK () const private
Generates the python file for vtk visualisation. Creates vtk output directories if needed.
 {
     bool writePythonScript = false;
     if (wallHandler.getWriteVTK() != FileType::NO_FILE) {
         helpers::createDirectory(wallVTKWriter_.getOutputDirectory(), true);
         writePythonScript = true;
     }
     if (vtkWriter_ && (getParticlesWriteVTK() || getSuperquadricParticlesWriteVTK())) {
         helpers::createDirectory(vtkWriter_->getOutputDirectory(), true);
         writePythonScript = true;
     }
     if (interactionHandler.getWriteVTK() != FileType::NO_FILE) {
         helpers::createDirectory(interactionVTKWriter_.getOutputDirectory(), true);
         writePythonScript = true;
     }
     if (boundaryHandler.getWriteVTK()) {
         helpers::createDirectory(boundaryVTKWriter_.getOutputDirectory(), true);
         writePythonScript = true;
     }
     if (wallHandler.getWriteDetailsVTKAny()) {
         helpers::createDirectory(wallDetailsVTKWriter_.getOutputDirectory(), true);
         writePythonScript = true;
     }
     if (writePythonScript && forceWritePythonFileForVTKVisualisation_)
     {
         writePythonFileForVTKVisualisation();
     }
 }
References boundaryHandler, boundaryVTKWriter_, helpers::createDirectory(), forceWritePythonFileForVTKVisualisation_, BaseVTKWriter< H >::getOutputDirectory(), getParticlesWriteVTK(), getSuperquadricParticlesWriteVTK(), WallHandler::getWriteDetailsVTKAny(), BoundaryHandler::getWriteVTK(), InteractionHandler::getWriteVTK(), WallHandler::getWriteVTK(), interactionHandler, interactionVTKWriter_, NO_FILE, vtkWriter_, wallDetailsVTKWriter_, wallHandler, wallVTKWriter_, and writePythonFileForVTKVisualisation().
Referenced by initialiseSolve().
insertGhostParticle()
void DPMBase::insertGhostParticle (BaseParticle * particle)
This function inserts a particle in the mpi communication boundaries.
Parameters
[in] particle Pointer to a base particle that needs to be inserted in the communication boundaries
 {
 #ifdef MERCURYDPM_USE_MPI
     //mpi particles only exist when there is more than one domain
     if (domainHandler.getSize() > 0)
     {
         //Add the particle to the mpi domain
         domainHandler.getCurrentDomain()->addParticle(particle);
     }
     //If periodic boundaries are present..
     if (periodicBoundaryHandler.getSize() > 0)
     {
         periodicBoundaryHandler.addNewParticle(particle);
     }
 #endif
 }
References PeriodicBoundaryHandler::addNewParticle(), Domain::addParticle(), domainHandler, DomainHandler::getCurrentDomain(), BaseHandler< T >::getSize(), and periodicBoundaryHandler.
Referenced by ParticleHandler::addObject().
integrateAfterForceComputation()
void DPMBase::integrateAfterForceComputation () protected virtual
Update particles' and walls' positions and velocities after force computation.
Performs integration - i.e. updating particle's positions, velocities and accelerations - for all particles and walls within the system (i.e. in the particleHandler and wallHandler). Integration is performed using the BaseParticle::integrateBeforeForceComputation() function.
The velocity Verlet algorithm requires us to integrate twice each time step: both before and after the force computation. This method is therefore used in conjunction with DPMBase::integrateAfterForceComputation(). See http://en.wikipedia.org/wiki/Verlet_integration#Velocity_Verlet for details.
 {
     //cycling through all particles, p, in the particleHandler
     //for_each(particleHandler.begin(), particleHandler.end(), [this](BaseParticle* p){
     #pragma omp parallel for num_threads(getNumberOfOMPThreads()) //schedule(dynamic)
     for (int k = 0; k < particleHandler.getSize(); ++k) {
         BaseParticle *p = particleHandler.getObject(k);
 #ifdef MERCURYDPM_USE_MPI
         //MPI particles do not require integration - they are updated by the communication step
         if (!(p->isMPIParticle() || p->isPeriodicGhostParticle()))
         {
             p->integrateAfterForceComputation(getTime(), getTimeStep());
         }
 #else
         //using the particle p's internal "integrateAfterForceComputation" function
         //to update the relevant parameters concerning the particle's position and motion
         p->integrateAfterForceComputation(getTime(), getTimeStep());
 #endif
     }
     //});
     //cycling through all walls, w, in the wallHandler
     //for_each(wallHandler.begin(), wallHandler.end(), [this](BaseWall* w){
     #pragma omp parallel for num_threads(getNumberOfOMPThreads()) //schedule(dynamic)
     for (int k = 0; k < wallHandler.getSize(); k++) {
         BaseWall *w = wallHandler.getObject(k);
         //using the wall's internal "integrateAfterForceComputation" function
         //to update the relevant parameters concerning its position and motion
         w->integrateAfterForceComputation(getTime(), getTimeStep());
     }
     //});
 }
References BaseHandler< T >::getObject(), BaseHandler< T >::getSize(), getTime(), getTimeStep(), k, p, particleHandler, w, and wallHandler.
Referenced by computeOneTimeStep().
integrateBeforeForceComputation()
void DPMBase::integrateBeforeForceComputation () protected virtual
Update particles' and walls' positions and velocities before force computation.
This is where the integration is done, at the moment it is velocity Verlet integration and is done before the forces are computed. See http://en.wikipedia.org/wiki/Verlet_integration#Velocity_Verlet
Performs integration - i.e. updating particle's positions, velocities and accelerations - for all particles and walls within the system (i.e. in the particleHandler and wallHandler). Integration is performed using the BaseParticle::integrateBeforeForceComputation() function.
The velocity Verlet algorithm requires us to integrate twice each time step: both before and after the force computation. This method is therefore used in conjunction with DPMBase::integrateAfterForceComputation(). See http://en.wikipedia.org/wiki/Verlet_integration#Velocity_Verlet for details.
Reimplemented in ChuteWithPeriodicInflow.
 {
     //cycling through all particles, p, in the particleHandler
     //for_each(particleHandler.begin(), particleHandler.end(), [this](BaseParticle* p)
     //for (BaseParticle* p : particleHandler) {
     #pragma omp parallel for num_threads(getNumberOfOMPThreads()) //schedule(dynamic)
     for (int k = 0; k < particleHandler.getSize(); ++k) {
         BaseParticle *p = particleHandler.getObject(k);
 #ifdef MERCURYDPM_USE_MPI
         //MPI particles are not integrated, they are purely ghost particles and get their new velocity and position from an MPI update
         if (!(p->isMPIParticle() || p->isPeriodicGhostParticle()))
         {
             p->integrateBeforeForceComputation(getTime(), getTimeStep());
         }
 #else
         //using the particle p's internal "integrateBeforeForceComputation" function
         //to update the relevant parameters concerning the particle's position and motion
         p->integrateBeforeForceComputation(getTime(), getTimeStep());
 #endif
     }
     //});
     //cycling through all walls, w, in the wallHandler
     //for_each(wallHandler.begin(), wallHandler.end(), [this](BaseWall* w)
     //for (BaseWall* w : wallHandler) {
     #pragma omp parallel for num_threads(getNumberOfOMPThreads()) //schedule(dynamic)
     for (int k = 0; k < wallHandler.getSize(); k++) {
         BaseWall *w = wallHandler.getObject(k);
         //using the wall's internal "integrateBeforeForceComputation" function
         //to update the relevant parameters concerning its position and motion
         w->integrateBeforeForceComputation(getTime(), getTimeStep());
     }
     //});
 }
References BaseHandler< T >::getObject(), BaseHandler< T >::getSize(), getTime(), getTimeStep(), k, p, particleHandler, w, and wallHandler.
Referenced by computeOneTimeStep().
isTimeEqualTo()
bool DPMBase::isTimeEqualTo (Mdouble time) const protected
Checks whether the input variable "time" is the current time in the simulation.
Returns true if and only if the "time" argument passed to the function is equal to the current simulation time i.e. if "time" is either exactly equal to the current simulation time (getTime()) or at least lies between this time step and the next increment (this nicely avoids rounding errors!)
Returns
true if "time" and getTime() are equal, otherwise false.
 {
     return getTime() <= time && getTime() + getTimeStep() > time;
 }
References getTime(), and getTimeStep().
launchNewRun()
int DPMBase::launchNewRun (const char * name, bool quick UNUSED = false)
This launches a code from within this code. Please pass the name of the code to run.
Reads in the name of the command (code) to be launched. This name is then converted to a string stream and appended with " &" (such that command is run in the background), before being converted back to a C string and then fed to the system() command which will execute the named code from within the running Mercury program.
Parameters
[in] name The name of the code to be launched
[in] quick
Returns
int
 {
 //defines an (empty) stringstream named "com"
 std::stringstream com("");
 //adds the name of the code to run (fed in as an argument)
 //to the "com" string and appends the string with " &"
 com << name << " &";
 //converts the stringstream "com" to a standard string, and then
 //converts this string to a C string
 //the string is then fed to the "system" function, which will run the named command
 return system(com.str().c_str());
 }
References plotDoE::name.
Referenced by ParameterStudy1DDemo::actionsAfterSolve(), ParameterStudy2DDemo::actionsAfterSolve(), ParameterStudy3DDemo::actionsAfterSolve(), ParameterStudy1DDemo::actionsBeforeTimeLoop(), ParameterStudy2DDemo::actionsBeforeTimeLoop(), ParameterStudy3DDemo::actionsBeforeTimeLoop(), and FlowRule::launch().
mpiInsertParticleCheck()
bool DPMBase::mpiInsertParticleCheck (BaseParticle * P)
Function that checks if the mpi particle should really be inserted by the current domain.
When adding a particle, all domains "add" the particle to enable communication between processors However not very domain should add the particle, only the domain that actually contains the particle There is one exception, if an MPI Particle is added (which is not physically in the current domain), this has already been approved by the domain and hence it should return true.
Parameters
[in] P Pointer to a baseParticle that requires an insertion check
Returns
Returns if the baseParticle should be inserted or not
 {
 #ifdef MERCURYDPM_USE_MPI
     //If only one core is used (i.e. domainHandler is empty) then the result is always true
     if (domainHandler.getSize() == 0)
     {
         return true;
     }
     //Get the current domain
     Domain* domain = domainHandler.getCurrentDomain();
     //Check if the particle is in the current domain
     if(domain->containsParticle(P))
     {
         //When adding a particle inside the domain, this should always be true
         return true;
     }
     else
     {
         //MPI particles that are inserted in the communication zone should still be inserted
         return (P->isMPIParticle());
     }
 #else
     return false;
 #endif
 }
References domain, domainHandler, DomainHandler::getCurrentDomain(), BaseHandler< T >::getSize(), and Global_Physical_Variables::P.
Referenced by ParticleHandler::addObject().
mpiIsInCommunicationZone()
bool DPMBase::mpiIsInCommunicationZone (BaseParticle * particle)
Checks if the position of the particle is in an mpi communication zone or not.
Parameters
[in] particle Pointer to a base particle
Returns
Returns if the particle is in the communication zone (true) or not (false)
 {
     bool insideCommunicationZone = false;
 #ifdef MERCURYDPM_USE_MPI
     MPIContainer& communicator = MPIContainer::Instance();
     //Check for the current domain if the particle is within the communication domain
     int val = domainHandler.getCurrentDomain()->isInCommunicationZone(particle);
     //The root gathers all results
     int *list = nullptr;
     if (PROCESSOR_ID == 0)
     {
         list = new int [NUMBER_OF_PROCESSORS];
     }
     communicator.gather(val,list);
     //Compute the global value
     //if on any processor the val is true, we have to do the communcation step
     int result = 0;
     if (PROCESSOR_ID == 0)
     {
         for (int i = 0; i< NUMBER_OF_PROCESSORS; i++)
         {
             if (list[i] == 1)
             {
                 result = 1;
                 break;
             }
         }
     }
     //The root now tells the other processors what the global value for the interaction is
     communicator.broadcast(result);
     //Convert the result back to bool
     insideCommunicationZone = result;
 #endif
     return insideCommunicationZone;
 }
References MPIContainer::broadcast(), domainHandler, MPIContainer::gather(), DomainHandler::getCurrentDomain(), i, MPIContainer::Instance(), Domain::isInCommunicationZone(), NUMBER_OF_PROCESSORS, PROCESSOR_ID, and calibrate::val.
outputInteractionDetails()
void DPMBase::outputInteractionDetails () const protected
Displays the interaction details corresponding to the pointer objects in the interaction handler.
Skims through all the object pointers of type BaseInteraction in the interaction handler. Outputs the type of interaction between two particles P and I.
 {
     logger(INFO, "Interactions currently in the handler:\n", Flusher::NO_FLUSH);
     //looping over all individual objects in the interactionHandler
     for (BaseInteraction* p : interactionHandler)
     {
         p->write(std::cout);
         logger(INFO, "\nInteraction % % between % and %",
                p->getName(), p->getId(), p->getP()->getId(), p->getI()->getId());
     }
 }
References INFO, interactionHandler, logger, NO_FLUSH, and p.
outputStatistics()
void DPMBase::outputStatistics () protected virtual
This function is overridden by StatisticsVector
Reimplemented in StatisticsVector< T >, StatisticsVector< O >, and StatisticsVector< XZ >.
 {
     //cgHandler.evaluate();
 }
outputXBallsData()
void DPMBase::outputXBallsData (std::ostream & os) const protected virtual
This function writes the location of the walls and particles in a format the XBalls program can read. For more information on the XBalls program, see Visualising data in xballs.
Parameters
[in] os
Reimplemented in SphericalIndenter, LiquidMigrationSelfTest, and LiquidMigrationMPI2Test.
 {
     //Set the correct formation based of dimension if the formation is not specified by the user
     unsigned int format=0;
     switch (getSystemDimensions())
     {
         case 2:
             format = 8;
             break;
         case 3:
             format = 14;
             break;
         default:
             logger(ERROR, "Unknown system dimension");
     }
     unsigned int numberOfParticles = particleHandler.getNumberOfRealObjectsLocal();
     // This outputs the location of walls and how many particles there are to file this is required by the xballs plotting
     if (format != 14) // dim = 1 or 2
     {
         os << numberOfParticles
            << " " << getTime()
            << " " << getXMin()
            << " " << getYMin()
            << " " << getXMax()
            << " " << getYMax()
            << " " << std::endl;
     }
     else
     {
         //dim==3
         os << numberOfParticles
            << " " << getTime()
            << " " << getXMin()
            << " " << getYMin()
            << " " << getZMin()
            << " " << getXMax()
            << " " << getYMax()
            << " " << getZMax()
            << " " << std::endl;
     }
     // This outputs the particle data
     for (unsigned int i = 0; i < particleHandler.getSize(); i++)
     {
 #ifdef MERCURYDPM_USE_MPI
         if (!particleHandler.getObject(i)->isPeriodicGhostParticle() && !particleHandler.getObject(i)->isMPIParticle())
         {
             outputXBallsDataParticle(i, format, os);
         }
 #else
         outputXBallsDataParticle(i, format, os);
 #endif
     }
 #ifdef DEBUG_OUTPUT
     logger(DEBUG, "Have output the properties of the problem to disk ");
 #endif
 }
References DEBUG, ERROR, format(), ParticleHandler::getNumberOfRealObjectsLocal(), BaseHandler< T >::getObject(), BaseHandler< T >::getSize(), getSystemDimensions(), getTime(), getXMax(), getXMin(), getYMax(), getYMin(), getZMax(), getZMin(), i, BaseParticle::isMPIParticle(), BaseParticle::isPeriodicGhostParticle(), logger, outputXBallsDataParticle(), and particleHandler.
Referenced by CSCInit::save(), RotatingDrumBidisperseInitialise::save(), ClosedCSCWalls::saveWalls(), CSCWalls::saveWalls(), and writeDataFile().
outputXBallsDataParticle()
virtual void DPMBase::outputXBallsDataParticle (unsigned int i, unsigned int format, std::ostream & os) const protected virtual
This function writes out the particle locations into an output stream in a format the XBalls program can read. For more information on the XBalls program, see Visualising data in xballs.
Referenced by outputXBallsData(), LiquidMigrationMPI2Test::outputXBallsData(), LiquidMigrationSelfTest::outputXBallsData(), and SphericalIndenter::outputXBallsData().
performGhostParticleUpdate()
void DPMBase::performGhostParticleUpdate () protected
When the Verlet scheme updates the positions and velocities of particles, ghost particles will need an update as wel. Their status will also be updated accordingly.
Todo:
MX: Under construction
 {
 #ifdef MERCURYDPM_USE_MPI
     //MPIContainer& communicator = MPIContainer::Instance();
     if (NUMBER_OF_PROCESSORS == 1) {return;}
     //Update the postion and velocity data of ghosts and perform some bookkeeping
     std::set<BaseParticle*> particlesToBeDeleted;
     domainHandler.updateStatus(particlesToBeDeleted);
     periodicBoundaryHandler.updateStatus(particlesToBeDeleted);
     //Delete particles
     deleteGhostParticles(particlesToBeDeleted);
     //Add new particles
     domainHandler.addNewParticles();
     periodicBoundaryHandler.addNewParticles();
 #endif
 }
References DomainHandler::addNewParticles(), PeriodicBoundaryHandler::addNewParticles(), deleteGhostParticles(), domainHandler, NUMBER_OF_PROCESSORS, periodicBoundaryHandler, PeriodicBoundaryHandler::updateStatus(), and DomainHandler::updateStatus().
Referenced by computeOneTimeStep(), and initialiseSolve().
performGhostVelocityUpdate()
void DPMBase::performGhostVelocityUpdate () protected
updates the final time-step velocity of the ghost particles
 {
 #ifdef MERCURYDPM_USE_MPI
     if (NUMBER_OF_PROCESSORS == 1) {return;}
     // \todo If required, I can implement this for periodic particles, first discuss with Thomas if it is actually requiredf
     //periodicDomainHandler.updateVelocity()
     //domainHandler.updateVelocity();
 #endif
 }
References NUMBER_OF_PROCESSORS.
printTime()
void DPMBase::printTime () const protected virtual
Displays the current simulation time and the maximum simulation duration.
Gets and prints the current simulation time (getTime()) and the currently set maximum simulation time (getTimeMax()) .
Reimplemented in PrintWallTimeMixin, Chute, BaseCluster, TangentialSpringEnergyConservationUnitTest, PSDSelfTest, SpeciesTest, SetDistributionPhiNormalSelfTest, regimeForceUnitTest, RandomClusterInsertionBoundarySelfTest, PeriodicWallsWithSlidingFrictionUnitTest, MultiParticlesInsertion, LiquidMigrationPeriodicBoundaryInteraction, viscoElasticUnitTest, LongHertzianSinterForceUnitTest, HeatTransferUnitTest, RandomClusterInsertionBoundarySelfTest, EvaporationAndHeatTest, PSDSelfTest, protectiveWall, DPM, SphericalIndenter, SinterPair, Sintering, InitialConditions< SpeciesType >, SingleParticle< SpeciesType >, TwoParticleElasticCollisionInteraction, TwoParticleCollisionInteraction, LiquidMigrationSelfTest, PSDSelfTest, PSDManualInsertionSelfTest, PolydisperseInsertionBoundarySelfTest, NozzleSelfTest, MultiplePSDSelfTest, InsertionBoundarySelfTest, DistributionToPSDSelfTest, DistributionSelfTest, DistributionPhiNormalSelfTest, DeletionBoundarySelfTest, CubeDeletionBoundarySelfTest, ConstantMassFlowMaserSelfTest, ConstantMassFlowMaserBoundaryMixedSpeciesSelfTest, SingleParticleSegregation, RotatingDrumBidisperse, RotatingDrumBidisperseInitialise, Silo, Penetration, Drum, ThermalConductionSelfTest, OneParticleCoolingSelfTest, OneParticleHeatingSelfTest, MeltableForceLawSelfTest, MeltableForceLaw2SelfTest, LaserOnLayer, InitialBed, vibratedBed, statistics_while_running< T >, SilbertPeriodic, CLiveStatistics< T >, SilbertPeriodic, SilbertPeriodic, statistics_while_running< T >, statistics_while_running< T >, ParticleBeam, ParticleInclusion, LiquidMigrationMPI2Test, ForceLawsMPI2Test, VerticalMixer, NozzleDemo, RotatingDrumWet, Drum, NozzleDemo, HorizontalMixer, CFDDEMCoupleTest, ChuteWithPeriodicInflow, RandomClusterInsertionBoundarySelfTest, Vreman, Vreman, Vreman, VariableBottom, ChutePeriodic, VariableBottom, ChutePeriodic, CSCWalls, CSCStats, CSCRun, CSCRestart, CSCInit, ClosedCSCWalls, ClosedCSCStats, ClosedCSCRun, ClosedCSCRestart, ShearStage, GranuHeap, GranuDrum, LawinenBox, LawinenBox, LawinenBox, and T_protectiveWall.
 {
 #ifdef MERCURYDPM_USE_MPI
     MPIContainer& communicator = MPIContainer::Instance();
     if (communicator.getProcessorID() != 0)
     {
         return;
     }
 #endif
   logger(INFO, "t=%3.6, tmax=%3.6", getTime(), getTimeMax());
 }
References MPIContainer::getProcessorID(), getTime(), getTimeMax(), INFO, MPIContainer::Instance(), and logger.
Referenced by LongHertzianSinterForceUnitTest::printTime(), TangentialSpringEnergyConservationUnitTest::printTime(), Mercury3DRestart::readNextArgument(), and writeOutputFiles().
processStatistics()
void DPMBase::processStatistics (bool) protected virtual
This function is overridden by StatisticsVector
Reimplemented in StatisticsVector< T >, StatisticsVector< O >, and StatisticsVector< XZ >.
 {
 }
read()
void DPMBase::read (std::istream & is, ReadOptions opt = ReadOptions::ReadAll) virtual
Reads all data from a restart file, e.g. domain data and particle data.
Todo:
warning: hides non-virtual function from the class 'Files'.
Reads in an existing .restart file line-by-line and passes all relevant parameters to the current instance of DPMBase. The data stream corresponding to the desired input file is passed as an argument.
Parameters
[in] is The data stream from which the particle data will be read.
Todo:
: Bound checking
Todo:
: Same order as other file format, please?
Todo:
{Do we want to calculate the mass?}
Reimplemented in MercuryBase, ChuteWithHopper, Chute, BaseCluster, Funnel, MembraneSelfTest, and MembraneDemo.
 {
 #ifdef MERCURYDPM_USE_MPI
     int previousNumberOfProcessors;
 #endif
     //Declares...
     std::string dummy;
     //...and reads in a dummy variable from the start of the stream "is"
     is >> dummy;
     //compare the string read in to the phrase "restart_version" to see if the stream corresponds
     //to a restart file (all restart files begin with this phrase)
     //if both strings match, strcmp(dummy.c_str(), "restart_version") returns 0 (here read as "false")
     if (dummy != "restart_version" && dummy != "MercuryDPM")
     {
         //If the strings do not match, if statement is fulfilled  and the error logged
         //Note: only very old files did not have a restart_version
         logger(FATAL, "Error in DPMBase::read(is): this is not a valid restart file");
     }
     else
     {
         //reads in the restart version (earlier versions of Mercury possess different file formats!)
         is >> restartVersion_;
         //checking which version the current data file corresponds to, and reads the data in
         //accordingly
         if (restartVersion_ == "1.0" || restartVersion_ == "0.14")
         {
             //reads in and saves the relevant values from the data file to the current instance of DPMBase
             std::stringstream line;
             // Store path (if restart file is nonlocal)
             auto slash = restartFile.getName().rfind('/');
             std::string path;
             if (slash != std::string::npos)
             {
                 path = restartFile.getName().substr(0, slash + 1);
             }
             if (!path.empty())
             {
                 logger(INFO, "Adding path information (%) to file names", path);
             }
             //line 1
             helpers::getLineFromStringStream(is, line);
             //discards the whitespace (ws) at the start of the stream
             line >> std::ws;
             //uses the "peek" function to access the stream's first
             //non-whitespace character, and check if it is an "r"
             if (line.peek() == 'r')
                 //if so, reads in the current run number
                 line >> dummy >> runNumber_;
             //In either case, then uses the "Files" version of the read function
             //to read in the rest of the relevant information.
             line >> dummy >> name_;
             setName(name_);
             //Read line 2-7 (definition of i/o files)
             helpers::getLineFromStringStream(is, line);
             line >> dummy >> dataFile;
             helpers::getLineFromStringStream(is, line);
             line >> dummy >> fStatFile;
             helpers::getLineFromStringStream(is, line);
             line >> dummy >> eneFile;
             helpers::getLineFromStringStream(is, line);
             line >> dummy >> restartFile;
             helpers::getLineFromStringStream(is, line);
             line >> dummy >> statFile;
             // Add the file path from the restart file to the file names
             dataFile.setName(path + dataFile.getName());
             fStatFile.setName(path + fStatFile.getName());
             eneFile.setName(path + eneFile.getName());
             restartFile.setName(path + restartFile.getName());
             statFile.setName(path + statFile.getName());
             // Get current position
             //check if the next line starts with 'interactionFile'; otherwise, skip interaction
             if (helpers::isNext(is, "interactionFile"))
             {
                 helpers::getLineFromStringStream(is, line);
                 line >> interactionFile;
                 interactionFile.setName(path + interactionFile.getName());
             }
             helpers::getLineFromStringStream(is, line);
             line >> dummy >> min_.x()
                  >> dummy >> max_.x()
                  >> dummy >> min_.y()
                  >> dummy >> max_.y()
                  >> dummy >> min_.z()
                  >> dummy >> max_.z();
             helpers::getLineFromStringStream(is, line);
             line >> dummy >> timeStep_
                  >> dummy >> time_
                  >> dummy >> numberOfTimeSteps_
                  >> dummy >> timeMax_;
             helpers::getLineFromStringStream(is, line);
             line >> dummy >> systemDimensions_
                  >> dummy >> particleDimensions_
                  >> dummy >> gravity_
                  >> dummy >> backgroundDrag_;
             line >> dummy;
             if (!dummy.compare("writeVTK"))
             {
                 FileType writeInteractionsVTK = FileType::NO_FILE, writeWallsVTK;
                 unsigned particlesCounter, wallCounter, interactionCounter, boundaryCounter;
                 bool writeBoundaryVTK, writeParticlesVTK;
                 line >> writeParticlesVTK >> writeWallsVTK >> writeInteractionsVTK >> writeBoundaryVTK >> particlesCounter >> wallCounter >> interactionCounter >> boundaryCounter;
                 line.clear();//because the number of arguments  in writeVTK has changed
                 line >> dummy;
                 setParticlesWriteVTK(writeParticlesVTK);
                 wallHandler.setWriteVTK(writeWallsVTK);
                 interactionHandler.setWriteVTK(writeInteractionsVTK);
                 boundaryHandler.setWriteVTK(writeBoundaryVTK);
                 vtkWriter_->setFileCounter(particlesCounter);
                 wallVTKWriter_.setFileCounter(wallCounter);
                 interactionVTKWriter_.setFileCounter(interactionCounter);
                 boundaryVTKWriter_.setFileCounter(boundaryCounter);
             }
             if (!dummy.compare("writeWallDetailsVTK"))
             {
                 // Example input: writeWallDetailsVTK 3 4 NO_FILE 12 ONE_FILE 25 MULTIPLE_FILES 101
                 // Number of options is 3, each option having an enum value and file type (4 NO_FILE), (12 ONE_FILE) and
                 // (25 MULTIPLE_FILES). At the end the file counter (101).
                 unsigned numberOfOptions, fileCounter, enumType;
                 FileType fileType;
                 line >> numberOfOptions;
                 for (unsigned  i = 0; i < numberOfOptions; i++)
                 {
                     line >> enumType >> fileType;
                     wallHandler.setWriteDetailsVTK(static_cast<WallHandler::DetailsVTKOptions>(enumType), fileType);
                 }
                 line >> fileCounter;
                 wallDetailsVTKWriter_.setFileCounter(fileCounter);
                 line.clear();
                 line >> dummy;
             }
             if (!dummy.compare("vtkOutDir")){
                 std::string particlesDir, wallsDir, interactionsDir, boundariesDir, wallDetailsDir;
                 line >> particlesDir >> wallsDir >> interactionsDir >> boundariesDir >> wallDetailsDir;
                 if (vtkWriter_) vtkWriter_->setOutputDirectory(particlesDir);
                 wallVTKWriter_.setOutputDirectory(wallsDir);
                 interactionVTKWriter_.setOutputDirectory(interactionsDir);
                 boundaryVTKWriter_.setOutputDirectory(boundariesDir);
                 wallDetailsVTKWriter_.setOutputDirectory(wallDetailsDir);
                 line >> dummy;
             }
             if (!dummy.compare("random"))
             {
                 random.read(line);
                 line >> dummy;
             }
 #ifdef MERCURYDPM_USE_OMP
             //Read the number of OMP threads
             if (!dummy.compare("numberOfOMPThreads")) {
                 int numberOfOMPThreads;
                 line >> numberOfOMPThreads;
                 setNumberOfOMPThreads(numberOfOMPThreads);
                 //logger(INFO," Check the number of OMP threads = % ", getNumberOfOMPThreads());
             }
 #endif
 #ifdef MERCURYDPM_USE_MPI
             if (!dummy.compare("numberOfProcessors"))
             {
                 line  >> previousNumberOfProcessors
                     >> dummy >> numberOfDomains_[Direction::XAXIS]
                     >> numberOfDomains_[Direction::YAXIS]
                     >> numberOfDomains_[Direction::ZAXIS];
             }
             else
             {
                 logger(INFO,"Reading a serial restart file");
                 //numberOfDomains_ = {1,1,1};
             }
 #endif
             if (!dummy.compare("xBallsArguments")) {
                 helpers::getLineFromStringStream(line, line);
                 setXBallsAdditionalArguments(line.str());
             }
             speciesHandler.read(is);
 #ifdef MERCURYDPM_USE_MPI
             //Initialise MPI structures and perform domain decomposition
             decompose();
 #endif
             //reading in the various relevant handlers
             unsigned int N;
             is >> dummy >> N;
             if (dummy.compare("Walls"))
                 logger(ERROR, "DPMBase::read(is): Error during restart: 'Walls' argument could not be found.");
             wallHandler.clear();
             wallHandler.setStorageCapacity(N);
             helpers::getLineFromStringStream(is, line);
             for (unsigned int i = 0; i < N; i++)
             {
                 helpers::getLineFromStringStream(is, line);
                 wallHandler.readAndAddObject(line);
             }
             is >> dummy >> N;
             boundaryHandler.clear();
             boundaryHandler.setStorageCapacity(N);
             if (dummy.compare("Boundaries"))
                 logger(ERROR, "DPMBase::read(is): Error during restart: 'Boundaries' argument could not be found.");
             helpers::getLineFromStringStream(is, line);
             for (unsigned int i = 0; i < N; i++)
             {
                 helpers::getLineFromStringStream(is, line);
                 boundaryHandler.readAndAddObject(line);
             }
             if (opt==ReadOptions::ReadNoParticlesAndInteractions) return;
             is >> dummy >> N;
             is.ignore(std::numeric_limits<std::streamsize>::max(), '\n');
             //display a message if a large amount o fparticles is read
             if (N>2.5e5) logger(INFO, "Reading % particles (may take a while)",N);
             logger.assert_always(dummy.compare("Particles")==0, "DPMBase::read(is): Error during restart: 'Particles' argument could not be found. %",dummy);
             particleHandler.clear();
             particleHandler.setStorageCapacity(N);
             for (unsigned int i = 0; i < N; i++)
             {
                 //ParticleHandler::readAndCreateObject reads line-by-line
                 particleHandler.readAndAddObject(is);
                 //skip the remaining data in line
                 is.ignore(std::numeric_limits<std::streamsize>::max(), '\n');
                 //particleHandler.getLastObject()->computeMass();
             }
 #ifdef MERCURYDPM_USE_MPI
             //Interaction distances of the domainHandler and periodicBoundaryHandler need to be set
             Mdouble interactionRadius = particleHandler.getLargestInteractionRadius();
             domainHandler.setInteractionDistance(2.0*interactionRadius);
             periodicBoundaryHandler.setInteractionDistance(2.0*interactionRadius);
             if (NUMBER_OF_PROCESSORS > 1)
             {
                 //Create ghost particles
                 domainHandler.addNewParticles();
                 periodicBoundaryHandler.addNewParticles();
             }
 #endif
             //Add interactions to particles and ghost particles
             if (opt==ReadOptions::ReadNoInteractions) return;
             interactionHandler.read(is);
         }
             //reading in for older versions of the Mercury restart file.
         else if (!restartVersion_.compare("3"))
         {
             logger(INFO, "DPMBase::read(is): restarting from an old restart file (restart_version %).",
                    restartVersion_);
             readOld(is);
         }
             //returning an error if there is no restart file to read in due to the use of outdated files.
         else
         {
             //only very old files did not have a restart_version
             logger(FATAL,
                    "Error in DPMBase::read(is): restart_version % cannot be read; use an older version of Mercury to upgrade the file",
                    restartVersion_);
         }
     }
 }
References DomainHandler::addNewParticles(), PeriodicBoundaryHandler::addNewParticles(), backgroundDrag_, boundaryHandler, boundaryVTKWriter_, BaseHandler< T >::clear(), ParticleHandler::clear(), dataFile, decompose(), domainHandler, eneFile, ERROR, FATAL, fStatFile, ParticleHandler::getLargestInteractionRadius(), helpers::getLineFromStringStream(), File::getName(), gravity_, i, INFO, interactionFile, interactionHandler, interactionVTKWriter_, helpers::isNext(), calibrate::line, logger, max, max_, min_, N, name_, NO_FILE, NUMBER_OF_PROCESSORS, numberOfDomains_, numberOfTimeSteps_, particleDimensions_, particleHandler, periodicBoundaryHandler, random, BaseHandler< T >::read(), InteractionHandler::read(), RNG::read(), BoundaryHandler::readAndAddObject(), WallHandler::readAndAddObject(), ParticleHandler::readAndAddObject(), ReadNoInteractions, ReadNoParticlesAndInteractions, readOld(), restartFile, restartVersion_, runNumber_, BaseVTKWriter< H >::setFileCounter(), DomainHandler::setInteractionDistance(), PeriodicBoundaryHandler::setInteractionDistance(), setName(), File::setName(), setNumberOfOMPThreads(), BaseVTKWriter< H >::setOutputDirectory(), setParticlesWriteVTK(), BaseHandler< T >::setStorageCapacity(), WallHandler::setWriteDetailsVTK(), BoundaryHandler::setWriteVTK(), InteractionHandler::setWriteVTK(), WallHandler::setWriteVTK(), setXBallsAdditionalArguments(), speciesHandler, statFile, oomph::Global_string_for_annotation::string(), systemDimensions_, time_, timeMax_, timeStep_, vtkWriter_, wallDetailsVTKWriter_, wallHandler, wallVTKWriter_, Vec3D::x(), XAXIS, Vec3D::y(), YAXIS, Vec3D::z(), and ZAXIS.
Referenced by MercuryBase::read(), readRestartFile(), and readSpeciesFromDataFile().
readArguments()
bool DPMBase::readArguments (int argc, char * argv[])
Can interpret main function input arguments that are passed by the driver codes.
Interprets commands passed in the command line (e.g. -tmin 0 -tmax 100 ...).
argc gives the number of commands passed, while argv stores the commands themselves (as strings).
Outputs the name and value of each flag passed, then calls the readNextArgument() function to actually interpret and implement the relevant arguments. Will raise an error if an unknown flag is passed.
Parameters
[in] argc "Argument count" - number of individual elements that argv will possess
[in] *argv[] An array of length argc - specifically an array of strings (or, in C terminology, a character array)
 {
     bool isRead = true;
     // Cycles over every second element. (Most flags will contain both name labels and actual data.
     // Those that don't will have to do i--; some examples in readNextArgument.)
     for (int i = 1; i < argc; i += 2)
     {
         logger(INFO, "interpreting input argument %\n", argv[i], Flusher::NO_FLUSH);
         for (int j = i + 1; j < argc; j++)
         {
             //looks for the next string that starts with a minus sign
             //i.e. the next flag, as each flag may take 0, 1 , 2, 3... arguments
             //and we need to make sure all are read in!
             if (argv[j][0] == '-')
                 break;
             logger(INFO, " %\n", argv[j], Flusher::NO_FLUSH);
         }
         logger(INFO, "");
         //if "isRead" is true and "readNextArgument" is also true...
         //(i.e. checking if any argument is false)
         isRead &= readNextArgument(i, argc, argv);
         // If the read was unsuccessful, raise an error and quit. (JMFT: Used to just be a warning.)
         if (!isRead)
         {
             logger(ERROR, "Warning: not all arguments read correctly!");
         }
     }
     return isRead;
 }
References ERROR, i, INFO, j, logger, NO_FLUSH, and readNextArgument().
Referenced by FlowRule::run(), vibratedBed::run(), and solve().
readDataFile()
bool DPMBase::readDataFile (std::string fileName = "", unsigned int format = 0)
This allows particle data to be reloaded from data files.
This function reads a .data file, which contains info about each particle's position, velocity, angular velocity, radius ...info. See also MD::readRestartFile For XBalls: Can read in format_ 14 - 8 or format_ 7 data format. This code saves in format_ 8 for 2D and format_ 14 for 3D. So if no extra parameters are specified it will assume many parameters, like density cannot be set using the data file. use of string instead of string& b/c this function is often used with a string literal
Parameters
[in] fileName
[in] format (format for specifying if its for 2D or 3D data)
Returns
bool (True or False)
 {
     //default value: dataFile.getFullName()
     if (!fileName.compare(""))
         fileName = dataFile.getFullName();
     std::string oldFileName = dataFile.getName();
     unsigned oldCounter = dataFile.getCounter();
     //Updates the name of the data file to the user-input from the argument.
     dataFile.setName(fileName);
     //opens a filestream of the input type
     dataFile.open(std::fstream::in);
     //Checks if the file has been successfully opened...
     if (!dataFile.getFstream().is_open() || dataFile.getFstream().bad())
     {
         //...and if not, ends the function and returns "false"
         logger(WARN, "Loading data file % failed.", fileName);
         return false;
     }
     //retrieves and saves the "FileType" of the file
     FileType fileTypeData = dataFile.getFileType();
     dataFile.setFileType(FileType::ONE_FILE);
     readNextDataFile(format);
     dataFile.setFileType(fileTypeData);
     dataFile.close();
     dataFile.setName(oldFileName);
     dataFile.setCounter(oldCounter);
     return true;
 }
References File::close(), dataFile, UniformPSDSelfTest::fileName, format(), File::getCounter(), File::getFileType(), File::getFstream(), File::getFullName(), File::getName(), logger, ONE_FILE, File::open(), readNextDataFile(), File::setCounter(), File::setFileType(), File::setName(), oomph::Global_string_for_annotation::string(), and WARN.
Referenced by VariableBottom::add_particles(), VariableBottom::createBottom(), LawinenBox::LawinenBox(), main(), readNextArgument(), my_problem::setupInitialConditions(), free_cooling::setupInitialConditions(), restart::setupInitialConditions(), and DPM::setupInitialConditions().
readNextArgument()
bool DPMBase::readNextArgument (int & i, int argc, char * argv[]) virtual
Interprets the i^th command-line argument.
Reads, recognises and applies all valid flags passed when starting or restarting a Mercury simulation.
For all of the N = argc (argument count) command line arguments passed when starting/restarting a code (e.g. -tmax, -tmin ...), compares them to the "known" arguments understood by Mercury (note that further recognised arguments can be added in derived classes). If a match is found, the relevant parameter is set to the corresponding value(s) following the flag and true is returned. Otherwise, false is returned.
For instance, if the flag -xmin 0 is passed, the code's second if statement will recognise the flag, convert the subsequent string in argv to a double, and then call the setXMin() function to implement the new value (0) of XMin.
For developers: note the use of strcmp here. This cannot be replaced with a simpler ==, as we are comparing c-style strings (char*), instead of std::string. Thus, == would return equality of the pointers instead of the contents of the string. strcmp returns 0 if the strings are the same, and another number if they are different. This is then implicitly cast to a bool, where 0->false and other numbers will give true. Finally, the !-operator makes sure that the expression in the if-statements are true if the strings are the same, and false otherwise.
Parameters
[in] i the position of the element that will be read, note that the count starts at 1, as element 0 is the name of the executable
[in] argc number of arguments the user has given
[in] *argv[] the command-line arguments the user has given when calling the executable
Returns
true if the argument is successfully read, and false otherwise.
-gravity_ requires three arguments
-restart or -r loads a restart file. By default, it loads <name>.restart. If an argument "arg" is given it loads the file "arg", or "arg".restart (if the ending is not given).
Reimplemented in MercuryBase, Mercury3DRestart, ChuteWithHopper, Chute, SilbertPeriodic, SilbertPeriodic, FlowRule, Funnel, GranularJet, and AxisymmetricHopper.
 {
     // The argument argv[i] identifies the label of the flag, and subsequent arguments (usually 1)
     // contain the content.
     //
     // For example...
     // Checks if the "-name" flag has been passed
     // The strcmp returns 0 if "argv[i]" is "-name" (i.e. !strcmp(argv[i], "-name") --> 1)
     // In this case, the setName function is run with the relevant input (i.e. the value which
     // immediately follows the "-name" flag
     if (!strcmp(argv[i], "-name"))
     {
         setName(argv[i + 1]);
     }
         // The above process is repeated for all viable flags.
     else if (!strcmp(argv[i], "-xmin"))
     {
         setXMin(atof(argv[i + 1]));
     }
     else if (!strcmp(argv[i], "-ymin"))
     {
         setYMin(atof(argv[i + 1]));
     }
     else if (!strcmp(argv[i], "-zmin"))
     {
         setZMin(atof(argv[i + 1]));
     }
     else if (!strcmp(argv[i], "-xmax"))
     {
         setXMax(atof(argv[i + 1]));
     }
     else if (!strcmp(argv[i], "-ymax"))
     {
         setYMax(atof(argv[i + 1]));
     }
     else if (!strcmp(argv[i], "-zmax"))
     {
         setZMax(atof(argv[i + 1]));
         //} else if (!strcmp(argv[i],"-svn")) {
         //  std::cout << "svn version " << SVN_VERSION << std::endl;
         //  i--;
     }
     else if (!strcmp(argv[i], "-dt"))
     {
         Mdouble old = getTimeStep();
         setTimeStep(atof(argv[i + 1]));
         logger(INFO, "  reset dt from % to %", old, getTimeStep());
     }
 //    else if (!strcmp(argv[i], "-Hertz"))
 //    {
 //        speciesHandler.getObject(0)->setForceType(ForceType::HERTZ);
 //        i--;
 //    }
     else if (!strcmp(argv[i], "-tmax"))
     {
         Mdouble old = getTimeMax();
         setTimeMax(atof(argv[i + 1]));
         logger(INFO, "  reset timeMax from % to %", old, getTimeMax());
     }
     else if (!strcmp(argv[i], "-saveCount"))
     {
         Mdouble old = dataFile.getSaveCount();
         setSaveCount(static_cast<unsigned int>(atoi(argv[i + 1])));
         logger(INFO, "  reset saveCount from & to %", old, dataFile.getSaveCount());
     }
     else if (!strcmp(argv[i], "-saveCountData"))
     {
         dataFile.setSaveCount(static_cast<unsigned int>(atoi(argv[i + 1])));
     }
     else if (!strcmp(argv[i], "-saveCountFStat"))
     {
         fStatFile.setSaveCount(static_cast<unsigned int>(atoi(argv[i + 1])));
     }
     else if (!strcmp(argv[i], "-saveCountStat"))
     {
         statFile.setSaveCount(static_cast<unsigned int>(atoi(argv[i + 1])));
     }
     else if (!strcmp(argv[i], "-saveCountEne"))
     {
         eneFile.setSaveCount(static_cast<unsigned int>(atoi(argv[i + 1])));
     }
     else if (!strcmp(argv[i], "-saveCountRestart"))
     {
         restartFile.setSaveCount(static_cast<unsigned int>(atoi(argv[i + 1])));
     }
     else if (!strcmp(argv[i], "-dim"))
     {
         setSystemDimensions(static_cast<unsigned int>(atoi(argv[i + 1])));
     }
     else if (!strcmp(argv[i], "-gravity"))
     {
         setGravity(Vec3D(atof(argv[i + 1]), atof(argv[i + 2]), atof(argv[i + 3])));
         i += 2;
     }
     else if (!strcmp(argv[i], "-fileType"))
     { //uses int input
         setFileType(static_cast<FileType>(atoi(argv[i + 1])));
     }
     else if (!strcmp(argv[i], "-fileTypeFStat"))
     { //uses int input
         fStatFile.setFileType(static_cast<FileType>(atoi(argv[i + 1])));
     }
     else if (!strcmp(argv[i], "-fileTypeRestart"))
     {
         restartFile.setFileType(static_cast<FileType>(atoi(argv[i + 1])));
     }
     else if (!strcmp(argv[i], "-fileTypeData"))
     {
         dataFile.setFileType(static_cast<FileType>(atoi(argv[i + 1])));
     }
     else if (!strcmp(argv[i], "-fileTypeStat"))
     {
         statFile.setFileType(static_cast<FileType>(atoi(argv[i + 1])));
     }
     else if (!strcmp(argv[i], "-fileTypeEne"))
     {
         eneFile.setFileType(static_cast<FileType>(atoi(argv[i + 1])));
     }
     else if (!strcmp(argv[i], "-auto_number"))
     {
         autoNumber();
         i--;
     }
 //    else if (!strcmp(argv[i], "-number_of_saves"))
 //    {
 //        set_number_of_saves_all(atof(argv[i + 1]));
 //    }
     else if (!strcmp(argv[i], "-restart") || !strcmp(argv[i], "-r"))
     {
         std::string filename;
         //use default filename if no argument is given
         if (i + 1 >= argc || argv[i + 1][0] == '-')
         {
             i--;
             filename = getName();
             logger(INFO, "%", getName());
         }
         else
         {
             filename = argv[i + 1];
         }
         //add ".restart" if necessary
         if (filename.find(".restart") == std::string::npos)
         {
             filename = filename + ".restart";
         }
         readRestartFile(filename);
     }
     else if (!strcmp(argv[i], "-clean") || !strcmp(argv[i], "-c"))
     {
         logger(INFO, "Remove old %.* files", getName());
         removeOldFiles();
         i--;
     }
     else if (!strcmp(argv[i], "-data"))
     {
         std::string filename = argv[i + 1];
         readDataFile(filename);
     }
     else if (!strcmp(argv[i], "-readSpeciesFromDataFile"))
     {
         readSpeciesFromDataFile_ = true;
         i--;
         logger(INFO, "Last column of data file will be interpreted as species index");
     }
 //    else if (!strcmp(argv[i], "-k"))
 //    {
 //        Mdouble old = getSpecies(0)->getStiffness();
 //        getSpecies(0)->setStiffness(atof(argv[i + 1]));
 //        std::cout << "  reset k from " << old << " to " << getSpecies(0)->getStiffness() << std::endl;
 //    }
 //    else if (!strcmp(argv[i], "-dissipation") || !strcmp(argv[i], "-disp"))
 //    {
 //        Mdouble old = getSpecies(0)->getDissipation();
 //        getSpecies(0)->setDissipation(atof(argv[i + 1]));
 //        std::cout << "  reset getDissipation() from " << old << " to " << getSpecies(0)->getDissipation() << std::endl;
 //    }
 //    else if (!strcmp(argv[i], "-kt"))
 //    {
 //        Mdouble old = getSpecies(0)->getSlidingStiffness();
 //        getSpecies(0)->setSlidingStiffness(atof(argv[i + 1]));
 //        std::cout << "  reset kt from " << old << " to " << getSpecies(0)->getSlidingStiffness() << std::endl;
 //    }
 //    else if (!strcmp(argv[i], "-dispt"))
 //    {
 //        Mdouble old = getSpecies(0)->getSlidingDissipation();
 //        getSpecies(0)->setSlidingDissipation(atof(argv[i + 1]));
 //        std::cout << "  reset dispt from " << old << " to " << getSpecies(0)->getSlidingDissipation() << std::endl;
 //    }
 //    else if (!strcmp(argv[i], "-krolling"))
 //    {
 //        Mdouble old = getSpecies(0)->getRollingStiffness();
 //        getSpecies(0)->setRollingStiffness(atof(argv[i + 1]));
 //        std::cout << "  reset krolling from " << old << " to " << getSpecies(0)->getRollingStiffness() << std::endl;
 //    }
 //    else if (!strcmp(argv[i], "-disprolling"))
 //    {
 //        Mdouble old = getSpecies(0)->getRollingDissipation();
 //        getSpecies(0)->setRollingDissipation(atof(argv[i + 1]));
 //        std::cout << "  reset disprolling from " << old << " to " << getSpecies(0)->getRollingDissipation() << std::endl;
 //    }
 //    else if (!strcmp(argv[i], "-mu"))
 //    {
 //        Mdouble old = getSpecies(0)->getSlidingFrictionCoefficient();
 //        getSpecies(0)->setSlidingFrictionCoefficient(atof(argv[i + 1]));
 //        std::cout << "  reset mu from " << old << " to " << getSpecies(0)->getSlidingFrictionCoefficient() << std::endl;
 //    }
 //    else if (!strcmp(argv[i], "-murolling"))
 //    {
 //        Mdouble old = getSpecies(0)->getRollingFrictionCoefficient();
 //        getSpecies(0)->setRollingFrictionCoefficient(atof(argv[i + 1]));
 //        std::cout << "  reset murolling from " << old << " to " << getSpecies(0)->getRollingFrictionCoefficient() << std::endl;
 //    }
     else if (!strcmp(argv[i], "-randomise") || !strcmp(argv[i], "-randomize"))
     {
         random.randomise();
         i--;
     }
 //    else if (!strcmp(argv[i], "-k0"))
 //    {
 //        Mdouble old = speciesHandler.getObject(0)->getAdhesionStiffness();
 //        speciesHandler.getObject(0)->setAdhesionStiffness(atof(argv[i + 1]));
 //        std::cout << "  reset k0 from " << old << " to " << speciesHandler.getObject(0)->getAdhesionStiffness() << std::endl;
 //    }
 //    else if (!strcmp(argv[i], "-f0"))
 //    {
 //        Mdouble old = speciesHandler.getObject(0)->getBondForceMax();
 //        speciesHandler.getObject(0)->setBondForceMax(atof(argv[i + 1]));
 //        std::cout << "  reset f0 from " << old << " to " << speciesHandler.getObject(0)->getBondForceMax() << std::endl;
 //    }
 //    else if (!strcmp(argv[i], "-AdhesionForceType"))
 //    {
 //        AdhesionForceType old = speciesHandler.getObject(0)->getAdhesionForceType();
 //        speciesHandler.getObject(0)->setAdhesionForceType(argv[i + 1]);
 //        std::cout << "  reset AdhesionForceType from "
 //                << static_cast<signed char>(old) << " to "
 //                << static_cast<signed char>(speciesHandler.getObject(0)->getAdhesionForceType()) << std::endl;
 //    }
     else if (!strcmp(argv[i], "-append"))
     {
         setAppend(true);
         i--;
     }
     else if (!strcmp(argv[i], "-fixedParticles"))
     {
         setFixedParticles(static_cast<unsigned int>(atoi(argv[i + 1])));
     }
 //    else if (!strcmp(argv[i], "-rho"))
 //    {
 //        Mdouble old = speciesHandler.getObject(0)->getDensity();
 //        speciesHandler.getObject(0)->setDensity(atof(argv[i + 1]));
 //        std::cout << "  reset rho from " << old << " to " << speciesHandler.getObject(0)->getDensity() << std::endl;
 //    }
 //    else if (!strcmp(argv[i], "-dim_particle"))
 //    {
 //        setParticleDimensions(atoi(argv[i + 1]));
 //    }
     else if (!strcmp(argv[i], "-counter"))
     {
         setRunNumber(atoi(argv[i + 1]));
     }
     else
     {
         //returns false if the flag passed does not match any of the currently used flags.
         return false;
     }
     //returns true if argv is found
     return true;
 }
References autoNumber(), dataFile, eneFile, MergeRestartFiles::filename, fStatFile, getName(), File::getSaveCount(), getTimeMax(), getTimeStep(), i, INFO, logger, random, RNG::randomise(), readDataFile(), readRestartFile(), readSpeciesFromDataFile_, removeOldFiles(), restartFile, setAppend(), setFileType(), File::setFileType(), setFixedParticles(), setGravity(), setName(), setRunNumber(), setSaveCount(), File::setSaveCount(), setSystemDimensions(), setTimeMax(), setTimeStep(), setXMax(), setXMin(), setYMax(), setYMin(), setZMax(), setZMin(), statFile, and oomph::Global_string_for_annotation::string().
Referenced by readArguments(), and MercuryBase::readNextArgument().
readNextDataFile()
bool DPMBase::readNextDataFile (unsigned int format = 0)
Reads the next data file with default format=0. However, one can modify the format based on whether the particle data corresponds to 3D or 2D data- see Visualising data in xballs.
Used to load data from existing .data files (particle positions, velocities, sizes etc.) when restarting a simulation. The 'format' to choose depends on the formatting of the data files to be read in which varies, for instance, if the code is 2D (format 8) or 3D (format 14).
Parameters
[in] format
Todo:
make systemDimensions enum (2 or 3)
 {
     logger(VERBOSE, "Read data file %, t=%, Np=%, Nc=%", dataFile.getFullName(), getTime(), particleHandler.getSize(), interactionHandler.getNumberOfObjects());
     dataFile.open(std::fstream::in);
     //logger(INFO,"Reading %",dataFile.getFullName());
     //fStatFile.open();
     //Set the correct format based of dimension if the format is not explicitly specified by the user
     if (format == 0)
     {
         //checking the dimensionality of the system
         switch (getSystemDimensions())
         {
             case 1:
                 //if 2D, sets format 8 (data file has 8 columns for 2D)
             case 2:
                 format = 8;
                 break;
             case 3:
                 //if 3D, sets format 14 (data file has 14 columns for 3D)
                 format = 14;
                 break;
         }
         //end case
     }
     //end if
     // read in the particle number (as a double)
     double doubleN = -1;
     dataFile.getFstream() >> doubleN;
     // If N cannot be read, we reached the end of the file
     if (doubleN == -1) return false;
     // converting N to an integer; skipping the line if there is a problem (this happens when there is a corrupt data file)
     unsigned N = doubleN;
     while (doubleN != N) {
         std::string dummy;
         getline(dataFile.getFstream(),dummy,'\n');
         logger(WARN,"Skipping bad line in data file: % %",doubleN, dummy);
         dataFile.getFstream() >> doubleN;
         N = doubleN;
     }
     //store the parameters you want to preserve:
     const size_t nHistory = std::min(N,particleHandler.getSize());
     std::vector<const ParticleSpecies*> species(nHistory);
     std::vector<bool> fix(nHistory);
     std::vector<Vec3D> positionHistory(nHistory);
     for (size_t i=0; i<nHistory; ++i) {
         const BaseParticle *p = particleHandler.getObject(i);
         species[i] = p->getSpecies();
         fix[i] = p->isFixed();
         positionHistory[i] = p->getPosition();
         //store from reading the restart file which particles are fixed and which species each particle has
     }
     BaseParticle* p;
     if (particleHandler.getSize() == 0) {
         logger.assert_always(speciesHandler.getSize()>0,"readData: species needs to be set first");
         p = new SphericalParticle(speciesHandler.getObject(0));
         p->unfix();
     } else {
         p = particleHandler.getObject(0)->copy();
     }
     //empty the particle handler
     particleHandler.clear();
     particleHandler.setStorageCapacity(N);
     //now fill it again with the read-in particles
     std::stringstream line;
     helpers::getLineFromStringStream(dataFile.getFstream(), line);
     Mdouble radius;
     Vec3D position, velocity, angle, angularVelocity;
     size_t indSpecies;
     //read all other data available for the time step
     if (format==7) {
         line >> time_ >> min_.x() >> min_.y() >> min_.z() >> max_.x() >> max_.y() >> max_.z();
         for (size_t i = 0; i < N; ++i) {
             helpers::getLineFromStringStream(dataFile.getFstream(), line);
             line >> position.X >> position.Z >> position.Y >> velocity.X >> velocity.Z
                  >> velocity.Y >> radius
                  >> indSpecies;
             p->setPosition(position);
             p->setVelocity(velocity);
             p->setOrientation({1, 0, 0, 0});
             p->setAngularVelocity({0.0, 0.0, 0.0});
             p->setRadius(radius);
             if (readSpeciesFromDataFile_)
                 p->setSpecies(speciesHandler.getObject(indSpecies));
             else if (i < nHistory)
                 p->setSpecies(species[i]);
             if (i < nHistory && fix[i])
                 p->fixParticle();
             if (i < nHistory)
                 p->setPreviousPosition(positionHistory[i]);
             else
                 p->setPreviousPosition(p->getPosition());
             particleHandler.copyAndAddObject(*p);
             p->unfix();
         }
     } else if (format==8) {
         line >> time_ >> min_.x() >> min_.y() >> max_.x() >> max_.y();
         min_.z() = 0.0; max_.z() = 0.0;//For 2d functions we define Z to be of no interest
         for (size_t i = 0; i < N; ++i) {
             helpers::getLineFromStringStream(dataFile.getFstream(), line);
             line >> position.X >> position.Y >> velocity.X >> velocity.Y >> radius >> angle.Z >> angularVelocity.Z >> indSpecies;
             Quaternion q;
             q.setAngleZ(angle.Z);
             p->setPosition(position);
             p->setVelocity(velocity);
             p->setOrientation(q);
             p->setAngularVelocity(-angularVelocity);
             p->setRadius(radius);
             if (readSpeciesFromDataFile_) p->setSpecies(speciesHandler.getObject(indSpecies));
             else if (i < nHistory) p->setSpecies(species[i]);
             if (i < nHistory && fix[i]) p->fixParticle();
             if (i < nHistory) p->setPreviousPosition(positionHistory[i]);
             else p->setPreviousPosition(p->getPosition());
             particleHandler.copyAndAddObject(*p);
             p->unfix();
         } //end for all particles
     } else if (format==14) {
         //This is a 3D format_
         // \todo : Check bounds or get rid of this function
         line >> time_ >> min_.x() >> min_.y() >> min_.z() >> max_.x() >> max_.y() >> max_.z();
         for (size_t i = 0; i < N; ++i) {
             helpers::getLineFromStringStream(dataFile.getFstream(), line);
             line >> position >> velocity >> radius >> angle >> angularVelocity >> indSpecies;
 #ifdef MERCURYDPM_USE_MPI
             //This is required for the CG tool. When reading the data file it is neseccary to know if a particle is an MPIParticle or not
             bool isMPIParticle = false;
             bool isPeriodicGhostParticle = false;
             if (NUMBER_OF_PROCESSORS > 1)
             {
                 line >> isMPIParticle >> isPeriodicGhostParticle;
             }
 #endif
             p->setPosition(position);
             p->setVelocity(velocity);
             p->setOrientationViaEuler(angle);
             p->setAngularVelocity(angularVelocity);
             p->setRadius(radius);
             if (readSpeciesFromDataFile_) {
                 if (indSpecies<speciesHandler.getSize()) {
                     p->setSpecies(speciesHandler.getObject(indSpecies));
                 } else {
                     logger(WARN, "Read in bad species data; species is not set");
                 }
             } else if (i < nHistory)
                 p->setSpecies(species[i]);
             if (i < nHistory && fix[i])
                 p->fixParticle();
             if (i < nHistory) p->setPreviousPosition(positionHistory[i]);
             else p->setPreviousPosition(p->getPosition());
 #ifdef MERCURYDPM_USE_MPI
             if (NUMBER_OF_PROCESSORS)
             {
                 p->setMPIParticle(isMPIParticle);
                 p->setPeriodicGhostParticle(isPeriodicGhostParticle);
             }
 #endif
             particleHandler.copyAndAddObject(*p);
             p->unfix();
         } //end read into existing particles logger(INFO, "read % particles", particleHandler.getNumberOfObjects());
     } else if (format==15) {
         line >> time_ >> min_.x() >> min_.y() >> min_.z() >> max_.z() >> max_.y() >> max_.z();
         for (size_t i = 0; i < N; ++i) {
             helpers::getLineFromStringStream(dataFile.getFstream(), line);
             line >> position >> velocity >> radius >> angle >> angularVelocity >> indSpecies >> indSpecies;
             Quaternion q;
             q.setEuler(angle);
             p->setPosition(position);
             p->setVelocity(velocity);
             p->setOrientation(q);
             p->setAngularVelocity(angularVelocity);
             p->setRadius(radius);
             if (readSpeciesFromDataFile_) p->setSpecies(speciesHandler.getObject(indSpecies));
             else if (i < nHistory) p->setSpecies(species[i]);
             if (i < nHistory && fix[i]) p->fixParticle();
             if (i < nHistory) p->setPreviousPosition(positionHistory[i]);
             else p->setPreviousPosition(p->getPosition());
             particleHandler.copyAndAddObject(*p);
         } //end for all particles
     } //end if format
     particleHandler.computeAllMasses();
     return true;
 }
References Jeffery_Solution::angle(), ParticleHandler::clear(), ParticleHandler::computeAllMasses(), BaseParticle::copy(), BaseHandler< T >::copyAndAddObject(), dataFile, Eigen::fix, format(), File::getFstream(), File::getFullName(), helpers::getLineFromStringStream(), BaseHandler< T >::getNumberOfObjects(), BaseHandler< T >::getObject(), BaseHandler< T >::getSize(), getSystemDimensions(), getTime(), i, interactionHandler, calibrate::line, logger, max_, min, min_, N, NUMBER_OF_PROCESSORS, File::open(), p, particleHandler, Eigen::numext::q, UniformPSDSelfTest::radius, readSpeciesFromDataFile_, BaseHandler< T >::setStorageCapacity(), speciesHandler, oomph::Global_string_for_annotation::string(), time_, Jeffery_Solution::velocity(), VERBOSE, WARN, Vec3D::X, Vec3D::x(), Vec3D::Y, Vec3D::y(), Vec3D::Z, and Vec3D::z().
Referenced by CGHandler::evaluateDataFiles(), and readDataFile().
readNextFStatFile()
void DPMBase::readNextFStatFile ()
Reads the next fstat file.
 {
     logger(VERBOSE, "Read fstat file %, t=%, Np=%, Nc=%", fStatFile.getFullName(), getTime(), particleHandler.getSize(), interactionHandler.getNumberOfObjects());
     fStatFile.open(std::fstream::in);
     std::string line;
     std::fstream& in = fStatFile.getFstream();
     // read the first three lines
     getline(in, line);
     getline(in, line);
     getline(in, line);
     Mdouble time;
     unsigned int indexP;
     int indexI; //could be negative
     interactionHandler.clear();
     while ((in.peek() != -1) && (in.peek() != '#'))
     {
         /* # 1: time
          # 2: particle Number i
          # 3: contact partner j (particles >= 0, walls < 0)
          # 4: x-position \
          # 5: y-position  > of the contact point (I hope)
          # 6: z-position /
          # 7: delta = overlap at the contact
          # 8: ctheta = length of the tangential spring
          # 9: P1_P2_normal force |f^n|
          # 10: remaining (tangential) force |f^t|=|f-f^n|
          # 11-13: P1_P2_normal unit vector nx, ny, nz
          # 14-16: tangential unit vector tx, ty, tz
          */
         in >> time >> indexP >> indexI;
         logger(VERBOSE, "Read fstat line: t=% i=%, p=%", time, indexP, indexI);
         BaseParticle* P = particleHandler.getObject(indexP);
         BaseInteraction* C;
         if (indexI >= 0)
         {
             BaseParticle* I = particleHandler.getObject(static_cast<const unsigned int>(indexI));
             //read only one of the two fstat lines reported
             if (indexI >= indexP or I->isFixed())
             {
                 // particle pair contact
                 C = interactionHandler.addInteraction(P, I, getNumberOfTimeSteps() + 1);
                 C->setFStatData(in, P, I);
                 // skip next line
                 //in.ignore(256, '\n');
             } else logger(VERBOSE, "line ignored because indexI=% >= indexP=%", indexP, indexI);
         }
         else
         {
             // wall-particle contact
             while (wallHandler.getNumberOfObjects() <= -indexI - 1)
             {
                 wallHandler.copyAndAddObject(InfiniteWall(speciesHandler.getLastObject()));
                 logger(WARN, "Added new wall because .fstat file indicates contact with wall % that doesn't exist",
                        -indexI - 1);
             }
             BaseWall* I = wallHandler.getObject(static_cast<const unsigned int>(-indexI - 1));
             C = interactionHandler.addInteraction(P, I, getNumberOfTimeSteps() + 1);
             C->setFStatData(in, P, I);
         }
         //skip the rest of the line, to allow additional output and to ignore the second time a particle-particle contact is printed
         in.ignore(std::numeric_limits<std::streamsize>::max(), '\n');
     }
     //logger(INFO,"read % contacts at t = % (N=%)",counter,timeStamp,interactionHandler.getNumberOfObjects());
     //interactionHandler.write(std::cout);
     //logger(INFO,"normal % %",interactionHandler.getObject(0)->getNormal(),interactionHandler.getObject(0)->getContactPoint());
     //logger(INFO,"normal % %",interactionHandler.getLastObject()->getNormal(),interactionHandler.getLastObject()->getContactPoint());
 }
References InteractionHandler::addInteraction(), BaseHandler< T >::clear(), BaseHandler< T >::copyAndAddObject(), fStatFile, File::getFstream(), File::getFullName(), BaseHandler< T >::getLastObject(), BaseHandler< T >::getNumberOfObjects(), getNumberOfTimeSteps(), BaseHandler< T >::getObject(), BaseHandler< T >::getSize(), getTime(), I, interactionHandler, calibrate::line, logger, max, File::open(), Global_Physical_Variables::P, particleHandler, speciesHandler, oomph::Global_string_for_annotation::string(), VERBOSE, wallHandler, and WARN.
Referenced by CGHandler::evaluateDataFiles().
readOld()
void DPMBase::readOld (std::istream & is) virtual
Reads all data from a restart file, e.g. domain data and particle data; old version.
Deprecated:
Use read or the new magic driver instead
Parameters
[in] is
 {
     std::string dummy;
     is >> dummy >> dummy;
     setName(dummy);
     unsigned int saveCountData, saveCountEne, saveCountStat, saveCountFStat;
     unsigned int fileTypeFstat, fileTypeData, fileTypeEne, fileTypeRestart;
     is >> dummy >> min_.x()
        >> dummy >> max_.x()
        >> dummy >> min_.y()
        >> dummy >> max_.y()
        >> dummy >> min_.z()
        >> dummy >> max_.z()
        >> dummy >> timeStep_
        >> dummy >> time_
        >> dummy >> timeMax_
        >> dummy >> saveCountData
        >> dummy >> saveCountEne
        >> dummy >> saveCountStat
        >> dummy >> saveCountFStat
        >> dummy >> systemDimensions_
        >> dummy >> gravity_
        >> dummy >> fileTypeFstat
        >> dummy >> fileTypeData
        >> dummy >> fileTypeEne;
     dataFile.setSaveCount(saveCountData);
     eneFile.setSaveCount(saveCountEne);
     statFile.setSaveCount(saveCountStat);
     fStatFile.setSaveCount(saveCountFStat);
     fStatFile.setFileType(static_cast<FileType>(fileTypeFstat));
     dataFile.setFileType(static_cast<FileType>(fileTypeData));
     eneFile.setFileType(static_cast<FileType>(fileTypeEne));
     //this is optional to allow restart files with and without restartFile.getFileType()
     is >> dummy;
     if (!strcmp(dummy.c_str(), "options_restart"))
     {
         is >> fileTypeRestart;
         restartFile.setFileType(static_cast<FileType>(fileTypeRestart));
     }
     speciesHandler.read(is);
     wallHandler.read(is);
     boundaryHandler.read(is);
     particleHandler.read(is);
     setRestarted(true);
 }
References boundaryHandler, dataFile, eneFile, fStatFile, gravity_, max_, min_, particleHandler, BaseHandler< T >::read(), restartFile, File::setFileType(), setName(), setRestarted(), File::setSaveCount(), speciesHandler, statFile, oomph::Global_string_for_annotation::string(), systemDimensions_, time_, timeMax_, timeStep_, wallHandler, Vec3D::x(), Vec3D::y(), and Vec3D::z().
Referenced by read().
readParAndIniFiles()
bool DPMBase::readParAndIniFiles (std::string fileName)
Allows the user to read par.ini files (useful to read files produced by the MDCLR simulation code - external to MercuryDPM)
use of string instead of string& b/c this function is often used with a string literal
Parameters
[in] fileName
Returns
bool (True or False)
 {
     //Opens the par.ini file
     std::fstream file;
     file.open(fileName, std::fstream::in);
     if (!file.is_open() || file.bad())
     {
         //std::cout << "Loading par.ini file " << filename << " failed" << std::endl;
         return false;
     }
     Mdouble doubleValue;
     int integerValue;
     // inputfile par.ini
     // line 1 =============================================================
     // Example: 1 1 0
     //   1: integer (0|1) switches from non-periodic to periodic
     //      integer (5|6) does 2D integration only (y-coordinates fixed)
     //                    and switches from non-periodic to periodic
     //      integer (11) uses a quarter system with circular b.c.
     file >> integerValue;
     //~ std::cout << "11" << integerValue << std::endl;
     if (integerValue == 0)
     {
         InfiniteWall w0;
         w0.setSpecies(speciesHandler.getObject(0));
         w0.set(Vec3D(-1, 0, 0), Vec3D(getXMin(), 0, 0));
         wallHandler.copyAndAddObject(w0);
         w0.set(Vec3D(1, 0, 0), Vec3D(getXMax(), 0, 0));
         wallHandler.copyAndAddObject(w0);
         w0.set(Vec3D(0, -1, 0), Vec3D(0, getYMin(), 0));
         wallHandler.copyAndAddObject(w0);
         w0.set(Vec3D(0, 1, 0), Vec3D(0, getYMax(), 0));
         wallHandler.copyAndAddObject(w0);
         w0.set(Vec3D(0, 0, -1), Vec3D(0, 0, getZMin()));
         wallHandler.copyAndAddObject(w0);
         w0.set(Vec3D(0, 0, 1), Vec3D(0, 0, getZMax()));
         wallHandler.copyAndAddObject(w0);
     }
     else if (integerValue == 1)
     {
         PeriodicBoundary b0;
         b0.set(Vec3D(1, 0, 0), getXMin(), getXMax());
         boundaryHandler.copyAndAddObject(b0);
         b0.set(Vec3D(0, 1, 0), getYMin(), getYMax());
         boundaryHandler.copyAndAddObject(b0);
         b0.set(Vec3D(0, 0, 1), getZMin(), getZMax());
         boundaryHandler.copyAndAddObject(b0);
     }
     else if (integerValue == 5)
     {
         InfiniteWall w0;
         w0.setSpecies(speciesHandler.getObject(0));
         w0.set(Vec3D(-1, 0, 0), Vec3D(-getXMin(), 0, 0));
         wallHandler.copyAndAddObject(w0);
         w0.set(Vec3D(1, 0, 0), Vec3D(getXMax(), 0, 0));
         wallHandler.copyAndAddObject(w0);
         w0.set(Vec3D(0, -1, 0), Vec3D(0, -getYMin(), 0));
         wallHandler.copyAndAddObject(w0);
         w0.set(Vec3D(0, 1, 0), Vec3D(0, getYMax(), 0));
         wallHandler.copyAndAddObject(w0);
     }
     else if (integerValue == 6)
     {
         PeriodicBoundary b0;
         b0.set(Vec3D(1, 0, 0), getXMin(), getXMax());
         boundaryHandler.copyAndAddObject(b0);
         b0.set(Vec3D(0, 1, 0), getYMin(), getYMax());
         boundaryHandler.copyAndAddObject(b0);
         b0.set(Vec3D(0, 0, 1), getZMin(), getZMax());
         boundaryHandler.copyAndAddObject(b0);
     }
     else
     {
         logger(ERROR, "Error in par.ini: line 1, value 1 is %", integerValue);
     }
     //   2: integer (0|1) dont use | use the search pattern for linked cells
     file >> integerValue; //ignore
     //   3: real - gravity in z direction: positive points upwards
     file >> doubleValue;
     setGravity(Vec3D(0.0, 0.0, doubleValue));
     // line 2 =============================================================
     // Example: -10000 .5e-2
     //   1: time end of simulation - (negative resets start time to zero
     //                                and uses -time as end-time)
     file >> doubleValue;
     if (doubleValue < 0)
         setTime(0);
     setTimeMax(fabs(doubleValue));
     //   2: time-step of simulation
     file >> doubleValue;
     setTimeStep(doubleValue);
     // line 3 =============================================================
     // Example: 1e-1 100
     file >> doubleValue;
     if (doubleValue >= 0)
     {
         //   1: time-step for output on time-series protocol file  -> "ene"
         unsigned int savecount = static_cast<unsigned int>(round(doubleValue / getTimeStep()));
         setSaveCount(savecount);
         //   2: time-step for output on film (coordinate) file      -> "c3d"
         //      (fstat-output is coupled to c3d-output time-step)
         file >> doubleValue;
         savecount = static_cast<unsigned int>(round(doubleValue / getTimeStep()));
         dataFile.setSaveCount(savecount);
         fStatFile.setSaveCount(savecount);
     }
     else
     {
         //  or: ---------------------------------------------------------------
         //   1: negative number is multiplied to the previous log-output-time
         //   2: requires initial log-output time
         //   3: negative number is multiplied to the previous film-output-time
         //   4: requires initial film-output time
         logger(ERROR, "Error in par.ini: line 3, value 1 is %", doubleValue);
     }
     // line 4 =============================================================
     // Example: 2000 1e5 1e3 1e2
     //   1: particle density (mass=4/3*constants::pi*density*rad^3)
     file >> doubleValue;
     //clear species handler
     speciesHandler.clear();
     auto S = new LinearViscoelasticSlidingFrictionSpecies;
     speciesHandler.addObject(S);
     setParticleDimensions(3);
     S->setDensity(doubleValue);
     //   2: linear spring constant
     file >> doubleValue;
     S->setStiffness(doubleValue);
     //   3: linear dashpot constant
     file >> doubleValue;
     S->setDissipation(doubleValue);
     //   4: background damping dashpot constant
     file >> doubleValue;
     if (doubleValue != 0.0)
         logger(WARN, "Warning in par.ini: ignored background damping %", doubleValue);
     // line 5 =============================================================
     // Example: 0 0
     //   1: growth rate:  d(radius) = xgrow * dt
     file >> doubleValue;
     if (doubleValue != 0.0)
         logger(WARN, "Warning in par.ini: ignored growth rate %", doubleValue);
     //   2: target volume_fraction
     file >> doubleValue;
     if (doubleValue != 0.0)
         logger(WARN, "Warning in par.ini: ignored target volume_fraction %", doubleValue);
     file.close();
     //std::cout << "Loaded par.ini file " << filename << std::endl;
     return true;
 }
References SpeciesHandler::addObject(), boundaryHandler, SpeciesHandler::clear(), BaseHandler< T >::copyAndAddObject(), dataFile, ERROR, boost::multiprecision::fabs(), UniformPSDSelfTest::fileName, fStatFile, BaseHandler< T >::getObject(), getTimeStep(), getXMax(), getXMin(), getYMax(), getYMin(), getZMax(), getZMin(), logger, Eigen::bfloat16_impl::round(), oomph::QuadTreeNames::S, PeriodicBoundary::set(), InfiniteWall::set(), setGravity(), setParticleDimensions(), setSaveCount(), File::setSaveCount(), BaseWall::setSpecies(), setTime(), setTimeMax(), setTimeStep(), speciesHandler, wallHandler, and WARN.
readRestartFile() [1/2]
bool DPMBase::readRestartFile (ReadOptions opt = ReadOptions::ReadAll)
Reads all the particle data corresponding to a given, existing . restart file (for more details regarding restart files, refer to the training materials on the MercuryDPM website).Returns true if it is successful, false otherwise.
Opens a file input stream corresponding to the restart file to be opened. If the file can be successfully opened, uses the read() function to extract all data from the restart file. Once the read-in has been successfully completed, sets the "restarted_" flag to true such that, where necessary, other functions will know that the file has been restarted.
Returns
int
 {
     //Assuming a filename corresponding to "restartFile" has already been established,
     //opens an input filestream to the relevant file
     if (restartFile.open(std::fstream::in))
     {
         // store the name of the file that will be read (because restarting can change the file name)
         std::string fileName = restartFile.getFullName();
         //reads the input stream line-by-line
         read(restartFile.getFstream(), opt);
         logger(INFO, "Loaded restart file %", fileName);
         restartFile.close();
         //sets the flag such that other functions can tell that the file has been restarted
         //e.g. does not run "setUpInitialConditions" or add headers to the .ene files etc.
         setRestarted(true);
         return true;
     }
     else /* if the file could not be opened */
     {
         logger(INFO, "% could not be loaded.", restartFile.getFullName());
         return false;
     }
 }
References File::close(), UniformPSDSelfTest::fileName, File::getFstream(), File::getFullName(), INFO, logger, File::open(), read(), restartFile, setRestarted(), and oomph::Global_string_for_annotation::string().
Referenced by BaseCluster::actionsOnRestart(), ChuteWithPeriodicInflowAndVariableBottom::ChuteWithPeriodicInflowAndVariableBottom(), ClosedCSCRestart::ClosedCSCRestart(), ClosedCSCRun::ClosedCSCRun(), ClosedCSCStats::ClosedCSCStats(), CSCInit::CSCInit(), CSCRestart::CSCRestart(), CSCStats::CSCStats(), CGHandler::evaluateRestartFiles(), CLiveStatistics< T >::getLiveStatistics(), Indenter::Indenter(), LaserOnLayer::LaserOnLayer(), LawinenBox::LawinenBox(), ChuteWithPeriodicInflow::loadPeriodicBox(), ChuteWithContraction::loadPeriodicBox(), main(), readNextArgument(), Mercury3DRestart::readNextArgument(), readRestartFile(), CGHandler::restart(), RotatingDrumBidisperse::RotatingDrumBidisperse(), statistics_while_running< T >::run(), CSCRun::setupInitialConditions(), CFDDEMCoupleTest::setupInitialConditions(), Cstatic3D::setupInitialConditions(), OneParticleCoolingSelfTest::setupInitialConditions(), ShearStage::ShearStage(), SingleParticleIndenter::SingleParticleIndenter(), Sintering::Sintering(), statistics_while_running< T >::statistics_while_running(), and StressStrainControl::StressStrainControl().
readRestartFile() [2/2]
int DPMBase::readRestartFile (std::string fileName, ReadOptions opt = ReadOptions::ReadAll)
The same as readRestartFile(bool), but also reads all the particle data corresponding to the current saved time step.
Reads in the name of a (.restart) file and then opens and reads in the data corresponding to this file using the argument-less readRestartFile() function. Note that this function should be called before setupInitialConditions().
Parameters
[in] fileName The name of the (.restart) file to be read in.
Returns
int
 {
     //add ".restart" if necessary
     if (fileName.find(".restart") == std::string::npos)
     {
         fileName.append(".restart");
     }
     //If padded or numbered files are used, we need to extract the counter and remove it from the filename
     //First find the last point in the restart name
     unsigned int pos = fileName.find('.');
     while (fileName.find('.', pos + 1) != std::string::npos)
     {
         pos = fileName.find('.', pos + 1);
     }
     //If the next char after the last . is a digit we are using numbered files
     std::string counter;
     if (isdigit(fileName[pos + 1]))
     {
         for (int i = pos + 1; i < fileName.length(); i++)
         {
             counter.push_back(fileName[i]);
         }
         //Set counter in restart file
         restartFile.setCounter(std::stoi(counter));
         logger(INFO, "Counter: %", std::stoi(counter));
     }
 #ifdef MERCURYDPM_USE_MPI
     //Correct for the processor number
     if (NUMBER_OF_PROCESSORS > 1 && !helpers::fileExists(fileName))
     {
         //Modify file name
         const unsigned int length = fileName.length();
         if (isdigit(fileName[pos + 1]))
         {
             for (int i = pos + 1; i < length + 1; i++)
             {
                 fileName.pop_back();
             }
         }
         fileName.append(std::to_string(PROCESSOR_ID));
         if (counter.size() > 0)
         {
             fileName.append(".");
             fileName.append(counter);
         }
     }
 #endif
     restartFile.setName(fileName);
     logger(INFO, "Restarting from %", fileName);
     return readRestartFile(opt);
 }
References helpers::fileExists(), UniformPSDSelfTest::fileName, i, INFO, logger, NUMBER_OF_PROCESSORS, PROCESSOR_ID, readRestartFile(), restartFile, File::setCounter(), File::setName(), oomph::Global_string_for_annotation::string(), and oomph::StringConversion::to_string().
readRunNumberFromFile()
int DPMBase::readRunNumberFromFile () static
Read the run number or the counter from the counter file (COUNTER_DONOTDEL)
Reads in the current counter in from the COUNTER_DONOTDEL file stored on the disk. If a COUNTER_DONOTDEL file does not already exist, creates one and initialises it with a value "1"
 {
 int counter;
 FILE* counter_file;
 //checking if there exists already a file named "COUNTER_DONOTDEL" which can be opened for
 //input and output (returns "true" if no such file exists).
 if ((counter_file = fopen("COUNTER_DONOTDEL", "r+")) == nullptr)
 {
 //if a file does not already exist, checks whether a new file can be created
 //returns "true" if a new file CANNOT be created
 if ((counter_file = fopen("COUNTER_DONOTDEL", "w")) == nullptr)
 {
     //If true, outputs an error message and ends the program
     fprintf(stderr, "\n\n\tERROR :: Counter File NOT found, please re-create\n\n");
     //fclose(counter_file);
     exit(-1);
 }
     //alternatively, if a new file CAN be created...
 else
 {
     //starts the new counter file, writing to it the value "1"
     fprintf(counter_file, "1");
     fprintf(stderr, "Counter File created\n");
     fclose(counter_file);
     return 1;
 }
 }
 //alternatively, if a counter file DOES already exist...
 else
 {
 //...checks if there exists only 1 value in the file (as would be expected from a COUNTER_DONOTDEL file...)
 if (fscanf(counter_file, "%d", &counter) != 1)
 {
     //...and if not, returns an error.
     fprintf(stderr, "\n\n\tERROR :: Counter File found, but something went wrong with reading it\n\n");
     fclose(counter_file);
     exit(-1);
 }
 else
 {
     //...otherwise, if all has been successful, returns the current value of the file!
     fclose(counter_file);
     return counter;
 }
 }
 }
Referenced by autoNumber().
readSpeciesFromDataFile()
void DPMBase::readSpeciesFromDataFile (bool read = true) inline
 {readSpeciesFromDataFile_=read;}
References read(), and readSpeciesFromDataFile_.
Referenced by commandLineCG().
readUserDefinedWall()
virtual BaseWall* DPMBase::readUserDefinedWall (const std::string & type) const inline virtual
Allows you to read in a wall defined in a Driver directory; see USER/Luca/ScrewFiller.
     { return nullptr; }
Referenced by WallHandler::readAndCreateObject().
removeDuplicatePeriodicParticles()
void DPMBase::removeDuplicatePeriodicParticles () protected
Removes periodic duplicate Particles.
Removes particles created by checkAndDuplicatePeriodicParticles().
Loops (from back to front) through the particle handler, removing particles marked as 'periodic' (i.e. BaseParticle::getPeriodicFromParticle() returns a real value, as opposed to a null pointer).
Since the duplicated particles will be stored at the 'back' of the particle handler, the function ceases when the first non-duplicated particle is found.
Note that between these two functions it is not allowed to create additional functions.
 {
 #ifdef MERCURYDPM_USE_MPI
     if (NUMBER_OF_PROCESSORS == 1)
     {
 #endif
     //Looping from the *back* of the particle handler, where all the periodic or "ghost" particles are stored.
     //The loop ends when there exist no more periodic particles (i.e. "getPeriodicFromParticle()" returns a null pointer)
     for (unsigned int i = particleHandler.getSize();
          i >= 1 && particleHandler.getObject(i - 1)->getPeriodicFromParticle() != nullptr; i--)
     {
         while (!particleHandler.getObject(i - 1)->getInteractions().empty())
         {
             interactionHandler.removeObjectKeepingPeriodics(
                     particleHandler.getObject(i - 1)->getInteractions().front()->getIndex());
         }
         particleHandler.removeObject(i - 1);
     }
     // OMP parallelism
     /*#pragma omp parallel for num_threads(getNumberOfOMPThreads()) //schedule(dynamic)
     for (unsigned int i = particleHandler.getSize(); i >= 1 ; i--)
     {
         if (particleHandler.getObject(i - 1)->getPeriodicFromParticle() != nullptr) {
             while (!particleHandler.getObject(i - 1)->getInteractions().empty()) {
                 interactionHandler.removeObjectKeepingPeriodics(
                         particleHandler.getObject(i - 1)->getInteractions().front()->getIndex());
             }
             particleHandler.removeObject(i - 1);
         }
     }*/
 #ifdef MERCURYDPM_USE_MPI
     }
 #endif
 }
References BaseInteractable::getInteractions(), BaseHandler< T >::getObject(), BaseParticle::getPeriodicFromParticle(), BaseHandler< T >::getSize(), i, interactionHandler, NUMBER_OF_PROCESSORS, particleHandler, ParticleHandler::removeObject(), and InteractionHandler::removeObjectKeepingPeriodics().
Referenced by computeOneTimeStep(), and initialiseSolve().
removeOldFiles()
void DPMBase::removeOldFiles () const
Note
If setVTKOutputDirectory() is used this function must be called after it.
 {
     //logger(INFO,"ID %",PROCESSOR_ID);
     //if (PROCESSOR_ID!=0) return;
     logger(INFO,"Removing old files named %.*",getName());
     std::ostringstream filename;
     // add processor id to file extension for mpi jobs
     std::string p = (NUMBER_OF_PROCESSORS > 1)?std::to_string(PROCESSOR_ID):"";
     // all the file extensions that should be deleted
     std::vector<std::string> ext{".restart"+p, ".stat"+p, ".fstat"+p, ".data"+p, ".ene"+p, ".xballs", ".py"};
     for (const auto& j : ext)
     {
         // remove files with given extension for FileType::ONE_FILE
         filename.str("");
         filename << getName() << j;
         if (!remove(filename.str().c_str()))
         {
             logger(INFO,"  File % successfully deleted",filename.str());
         }
         // remove files with given extension for FileType::MULTIPLE_FILES
         unsigned k = 0;
         filename.str("");
         filename << getName() << j << '.' << k;
         while (!remove(filename.str().c_str()))
         {
             if (k<3) logger(INFO,"  File % successfully deleted",filename.str());
             filename.clear();
             filename.str("");
             filename << getName() << j << '.' << ++k;
         }
         // remove files with given extension for FileType::MULTIPLE_FILES_PADDED
         k = 0;
         filename.str("");
         filename << getName() << j << '.' << to_string_padded(k);
         while (!remove(filename.str().c_str()))
         {
             if (k<3) logger(INFO,"  File % successfully deleted",filename.str());
             filename.clear();
             filename.str("");
             filename << getName() << j << '.' << to_string_padded(++k);
         }
     }
     // remove vtk files
     // add processor id to file extension for mpi jobs
     std::string q = (NUMBER_OF_PROCESSORS > 1)?("Processor_"+std::to_string(PROCESSOR_ID)+"_"):"";
     // all the file extensions that should be deleted
     ext = {"Wall_", q+"Particle_", q+"Interaction_", q+"Boundary_"};
     // List of VTK output directories, in same order as given extensions!
     std::vector<std::string> dirs{ wallVTKWriter_.getOutputDirectory(),
                                    (vtkWriter_ ? vtkWriter_->getOutputDirectory() : "."),
                                    interactionVTKWriter_.getOutputDirectory(),
                                    boundaryVTKWriter_.getOutputDirectory() };
     for (int i = 0; i < ext.size(); i++)
     {
         const std::string j = ext[i];
         const std::string VTKDir = dirs[i];
         // remove files with given extension for FileType::ONE_FILE
         filename.str("");
         filename << VTKDir << "/" << getName() << j << ".vtu";
         if (!remove(filename.str().c_str()))
         {
             logger(INFO,"  File % successfully deleted",filename.str());
         }
         // remove files with given extension for FileType::MULTIPLE_FILES
         unsigned k = 0;
         filename.str("");
         filename << VTKDir << "/" << getName() << j << k << ".vtu";
         while (!remove(filename.str().c_str()))
         {
             if (k<3) logger(INFO,"  File % successfully deleted",filename.str());
             filename.str("");
             filename << VTKDir << "/" << getName() << j << ++k << ".vtu";
         }
         //std::cout << "  File " << filename.str() << " not found" << std::endl;
     }
 }
References boundaryVTKWriter_, MergeRestartFiles::filename, getName(), BaseVTKWriter< H >::getOutputDirectory(), i, INFO, interactionVTKWriter_, j, k, logger, NUMBER_OF_PROCESSORS, p, PROCESSOR_ID, Eigen::numext::q, oomph::Global_string_for_annotation::string(), oomph::StringConversion::to_string(), to_string_padded(), vtkWriter_, and wallVTKWriter_.
Referenced by GranuDrum::GranuDrum(), LaserOnLayer::LaserOnLayer(), main(), readNextArgument(), RotatingDrumBidisperse::RotatingDrumBidisperse(), RotatingDrumBidisperseInitialise::RotatingDrumBidisperseInitialise(), NozzleDemo::setupInitialConditions(), RotatingDrumWet::setupInitialConditions(), MarbleRun::setupInitialConditions(), InitialBed::setupInitialConditions(), MeltableForceLaw2SelfTest::setupInitialConditions(), Drum::setupInitialConditions(), Penetration::setupInitialConditions(), Silo::setupInitialConditions(), SingleParticleSegregation::setupInitialConditions(), NozzleSelfTest::setupInitialConditions(), RollingOverTriangleWalls::setupInitialConditions(), and AreaVTK::setupInitialConditions().
resetFileCounter()
void DPMBase::resetFileCounter ()
Resets the file counter for each file i.e. for ene, data, fstat, restart, stat)
This implicitly calls the setCounter() function defined in File.h
 {
     dataFile.setCounter(0);
     fStatFile.setCounter(0);
     restartFile.setCounter(0);
     statFile.setCounter(0);
     eneFile.setCounter(0);
     interactionFile.setCounter(0);
     setLastSavedTimeStep(NEVER);
     if (vtkWriter_) vtkWriter_->setFileCounter(0);
     boundaryVTKWriter_.setFileCounter(0);
     interactionVTKWriter_.setFileCounter(0);
     wallVTKWriter_.setFileCounter(0);
     wallDetailsVTKWriter_.setFileCounter(0);
 }
References boundaryVTKWriter_, dataFile, eneFile, fStatFile, interactionFile, interactionVTKWriter_, NEVER, restartFile, File::setCounter(), BaseVTKWriter< H >::setFileCounter(), setLastSavedTimeStep(), statFile, vtkWriter_, wallDetailsVTKWriter_, and wallVTKWriter_.
Referenced by initialiseSolve().
setAppend()
void DPMBase::setAppend (bool newAppendFlag)
Sets whether the "append" option is on or off.
Used when a code is restarted. If set to true, existing files (other than restart files, which are always overwritten) will be appended, rather than new files being created and/or old files being overwritten. If false, files will simply be overwritten.
Parameters
[in] newAppendFlag
 {
     append_ = newAppendFlag;
 }
References append_.
Referenced by ClosedCSCRestart::ClosedCSCRestart(), commandLineCG(), constructor(), CSCRestart::CSCRestart(), LawinenBox::LawinenBox(), readNextArgument(), and Mercury3DRestart::readNextArgument().
setBackgroundDrag()
void DPMBase::setBackgroundDrag (Mdouble backgroundDrag) inline
Simple access function to turn on a background drag. The force of particleVelocity*drag is applied (note, it allowed to be negative i.e. create energy)
 {backgroundDrag_=backgroundDrag;}
References backgroundDrag_.
Referenced by RotatingDrumBidisperseInitialise::actionsAfterTimeStep(), and constructor().
setDimension()
void DPMBase::setDimension (unsigned int newDim)
Sets both the system dimensions and the particle dimensionality.
Note: In MercuryDPM, it is possible to simulate, for example, 3D particles in a 2D system by setting "setSystemDimensions(newDim)" and "setParticleDimensions(newDim)" individually.
The relevant sanity checks exist within the "setSystemDimensions(newDim)" and "setParticleDimensions(newDim)" functions.
Parameters
[in] newDim The desired dimensionality of the system and the particles: 1 → 1D, 2 → 2D, 3 → 3D.
 {
     setSystemDimensions(newDim);
     setParticleDimensions(newDim);
 }
References setParticleDimensions(), and setSystemDimensions().
Referenced by main(), Contact::setupInitialConditions(), and EnergyUnitTest::setupInitialConditions().
setDomain()
void DPMBase::setDomain (const Vec3D & min, const Vec3D & max)
Sets the minimum coordinates of the problem domain.
 {
 logger.assert_debug(min.X <= max.X, "lower x-bound (%) is larger than upper x-bound (%)", min.X, max.X);
 logger.assert_debug(min.Y <= max.Y, "lower x-bound (%) is larger than upper x-bound (%)", min.Y, max.Y);
 logger.assert_debug(min.Z <= max.Z, "lower x-bound (%) is larger than upper x-bound (%)", min.Z, max.Z);
 min_ = min;
 max_ = max;
 }
References logger, max, max_, min, and min_.
Referenced by AxisymmetricWallSelfTest::AxisymmetricWallSelfTest(), RandomClusterInsertionBoundary::checkBoundaryBeforeTimeStep(), DPM::DPM(), Hertzian2DUnitTest::Hertzian2DUnitTest(), main(), ParticleBeam::ParticleBeam(), CGHandler::restart(), BaseCluster::setDomainLimits(), NautaMixer::setupInitialConditions(), MarbleRun::setupInitialConditions(), InitialBed::setupInitialConditions(), MeltableForceLaw2SelfTest::setupInitialConditions(), MeltableForceLawSelfTest::setupInitialConditions(), OneParticleHeatingSelfTest::setupInitialConditions(), ThermalConductionSelfTest::setupInitialConditions(), CubeDeletionBoundarySelfTest::setupInitialConditions(), DeletionBoundarySelfTest::setupInitialConditions(), PSDSelfTest::setupInitialConditions(), SquarePacking::setupInitialConditions(), Wall::setupInitialConditions(), Packing::setupInitialConditions(), and SaveCountUnitTest::setupInitialConditions().
setFileType()
void DPMBase::setFileType (FileType fileType)
Sets File::fileType_ for all files (ene, data, fstat, restart, stat)
Calls the setFileType() function from the File.h, which basically sets the File::fileType_. Note, this does not affect the interactionFile.
Parameters
[in] fileType (an object of enum class FileType)
 {
 dataFile.setFileType(fileType);
 fStatFile.setFileType(fileType);
 restartFile.setFileType(fileType);
 statFile.setFileType(fileType);
 eneFile.setFileType(fileType);
 }
References dataFile, eneFile, fStatFile, restartFile, File::setFileType(), and statFile.
Referenced by ClosedCSCRun::ClosedCSCRun(), ClosedCSCStats::ClosedCSCStats(), Contact::Contact(), CSCStats::CSCStats(), loadingTest(), main(), normalAndTangentialLoadingTest(), objectivenessTest(), readNextArgument(), regimeForceUnitTest::regimeForceUnitTest(), Calibration::setOutput(), CSCRun::setupInitialConditions(), CFDDEMCoupleTest::setupInitialConditions(), GetDistanceAndNormalForIntersectionOfWalls::setupInitialConditions(), GetDistanceAndNormalForScrew::setupInitialConditions(), GetDistanceAndNormalForTriangleWall::setupInitialConditions(), Drum::setupInitialConditions(), Penetration::setupInitialConditions(), Silo::setupInitialConditions(), ContactDetectionIntersectionOfWallsTest::setupInitialConditions(), GetDistanceAndNormalForTriangleWalls::setupInitialConditions(), RollingOverTriangleWalls::setupInitialConditions(), ParticleParticleInteraction::setupInitialConditions(), ParticleParticleInteractionWithPlasticForces::setupInitialConditions(), ParticleWallInteraction::setupInitialConditions(), EnergyUnitTest::setupInitialConditions(), HertzianSinterForceUnitTest::setupInitialConditions(), PeriodicWallsWithSlidingFrictionUnitTest::setupInitialConditions(), PlasticForceUnitTest::setupInitialConditions(), AreaVTK::setupInitialConditions(), Tutorial11::Tutorial11(), viscoElasticUnitTest::viscoElasticUnitTest(), and Wall::Wall().
setFixedParticles()
void DPMBase::setFixedParticles (unsigned int n) protected
Sets a number, n, of particles in the particleHandler as "fixed particles".
That is to say that the first n particles in the handler will have their masses and inertiae set to infinity and their velocities set to zero, making them effectively immobile and immovable (see also BaseParticle::fixParticle()). If n exceeds the number of particles in the handler, then all particles will be "fixed".
Parameters
[in] n The number of particles to "fix".
Todo:
Question: can this function be called during the run of the program? i.e. can particles be made to suddenly "become fixed"?
 {
     for (unsigned int i = 0; i < std::min(particleHandler.getSize(), n); i++)
         particleHandler.getObject(i)->fixParticle();
 }
References BaseParticle::fixParticle(), BaseHandler< T >::getObject(), BaseHandler< T >::getSize(), i, min, n, and particleHandler.
Referenced by readNextArgument().
setGravity()
void DPMBase::setGravity (Vec3D newGravity)
Sets a new value for the gravitational acceleration.
Allows the user to set the value of the gravitational acceleration (g) to which their simulated system is exposed. The gravity is passed to the function as a (Vec3D) vector value, thus providing all three components of g and hence allowing both its direction and strength to be altered.
Parameters
[in] newGravity The desired new value of the gravitational acceleration as a Vec3D vector.
 {
     gravity_ = newGravity;
 }
References gravity_.
Referenced by BoundariesSelfTest::BoundariesSelfTest(), CGBasicSelfTest::CGBasicSelfTest(), CGForceDensityUnitTest::CGForceDensityUnitTest(), ChangingTOIParticle::ChangingTOIParticle(), ClosedCSCWalls::ClosedCSCWalls(), clumpTest::clumpTest(), constructor(), CSCWalls::CSCWalls(), FluxAndPeriodicBoundarySelfTest::FluxAndPeriodicBoundarySelfTest(), FluxBoundarySelfTest::FluxBoundarySelfTest(), GranuDrum::GranuDrum(), GranuHeap::GranuHeap(), InitialConditions< SpeciesType >::InitialConditions(), LawinenBox::LawinenBox(), LeesEdwardsDemo::LeesEdwardsDemo(), LeesEdwardsSelfTest::LeesEdwardsSelfTest(), load(), main(), MaserRepeatedOutInMPI2Test::MaserRepeatedOutInMPI2Test(), MercuryCGSelfTest::MercuryCGSelfTest(), MinimalExampleDrum::MinimalExampleDrum(), MultiParticlesInsertion::MultiParticlesInsertion(), ParticleCreation::ParticleCreation(), ParticleInclusion::ParticleInclusion(), ParticleParticleCollision::ParticleParticleCollision(), protectiveWall::protectiveWall(), readNextArgument(), readParAndIniFiles(), regimeForceUnitTest::regimeForceUnitTest(), RotatingDrumBidisperseInitialise::RotatingDrumBidisperseInitialise(), SingleParticle< SpeciesType >::scaleMass(), InitialConditions< SpeciesType >::scaleMass(), Cstatic2d::set_particle_properties(), Cstatic3D::set_particle_properties(), Chute::setChuteAngleAndMagnitudeOfGravity(), CurvyChute::setChuteAngleAndMagnitudeOfGravity(), ExtremeOverlapUnitTest::setupInitialConditions(), HorizontalMixer::setupInitialConditions(), NautaMixer::setupInitialConditions(), NozzleDemo::setupInitialConditions(), RotatingDrumWet::setupInitialConditions(), VerticalMixer::setupInitialConditions(), Binary::setupInitialConditions(), my_problem::setupInitialConditions(), Chain::setupInitialConditions(), StressStrainControl::setupInitialConditions(), ShiftingConstantMassFlowMaserBoundarySelfTest::setupInitialConditions(), ShiftingMaserBoundarySelfTest::setupInitialConditions(), FiveParticles::setupInitialConditions(), InitialBed::setupInitialConditions(), Drum::setupInitialConditions(), MindlinSelfTest::setupInitialConditions(), Penetration::setupInitialConditions(), Silo::setupInitialConditions(), ConstantMassFlowMaserBoundaryMixedSpeciesSelfTest::setupInitialConditions(), ConstantMassFlowMaserSelfTest::setupInitialConditions(), CubeDeletionBoundarySelfTest::setupInitialConditions(), DeletionBoundarySelfTest::setupInitialConditions(), DistributionToPSDSelfTest::setupInitialConditions(), InsertionBoundarySelfTest::setupInitialConditions(), MultiplePSDSelfTest::setupInitialConditions(), NozzleSelfTest::setupInitialConditions(), PolydisperseInsertionBoundarySelfTest::setupInitialConditions(), PSDManualInsertionSelfTest::setupInitialConditions(), SubcriticalMaserBoundarySelfTest::setupInitialConditions(), CGHandlerSelfTest::setupInitialConditions(), CGStaticBalanceSelfTest::setupInitialConditions(), FreeFallSelfTest::setupInitialConditions(), HertzianBSHPInteractionTwoParticleElasticCollision::setupInitialConditions(), LiquidMigrationSelfTest::setupInitialConditions(), DPM::setupInitialConditions(), TwoParticleBagheriCollision::setupInitialConditions(), TwoParticleClassicalWilletCollision::setupInitialConditions(), TwoParticleElasticCollisionInteraction::setupInitialConditions(), TwoParticleElasticCollision::setupInitialConditions(), RollingOverTriangleWalls::setupInitialConditions(), SimpleOpt::setupInitialConditions(), InitialConditions< SpeciesType >::setupInitialConditions(), BouncingSuperQuadric::setupInitialConditions(), EllipsoidsBouncingOnWallDemo::setupInitialConditions(), GranularCollapse::setupInitialConditions(), EllipticalSuperQuadricCollision::setupInitialConditions(), ParticleParticleInteraction::setupInitialConditions(), ParticleParticleInteractionWithPlasticForces::setupInitialConditions(), ParticleWallInteraction::setupInitialConditions(), ArcWallUnitTest::setupInitialConditions(), CreateDataAndFStatFiles::setupInitialConditions(), PSDSelfTest::setupInitialConditions(), EnergyUnitTest::setupInitialConditions(), EvaporationAndHeatTest::setupInitialConditions(), ExtremeOverlapWithWallsUnitTest::setupInitialConditions(), RandomClusterInsertionBoundarySelfTest::setupInitialConditions(), FreeFall::setupInitialConditions(), HertzianSinterForceUnitTest::setupInitialConditions(), MovingIntersectionOfWallsUnitTest_Basic::setupInitialConditions(), MovingWall::setupInitialConditions(), MovingWallTangential::setupInitialConditions(), PeriodicWalls::setupInitialConditions(), PeriodicWallsWithSlidingFrictionUnitTest::setupInitialConditions(), PlasticForceUnitTest::setupInitialConditions(), SeparateFilesSelfTest::setupInitialConditions(), SinterForceUnitTest::setupInitialConditions(), SpeciesTest::setupInitialConditions(), WallSpecies::setupInitialConditions(), MercuryProblem::setupMercuryProblem(), Siegen::Siegen(), SingleParticle< SpeciesType >::SingleParticle(), SingleParticleSegregation::SingleParticleSegregation(), SinterPair::SinterPair(), Slide::Slide(), SubcriticalMaserBoundaryTESTMPI2Test::SubcriticalMaserBoundaryTESTMPI2Test(), T_protectiveWall::T_protectiveWall(), TimeDependentPeriodicBoundary3DSelfTest::TimeDependentPeriodicBoundary3DSelfTest(), TimeDependentPeriodicBoundaryTest::TimeDependentPeriodicBoundaryTest(), TriangulatedScrewSelfTest::TriangulatedScrewSelfTest(), TriangulatedStepSelfTest::TriangulatedStepSelfTest(), TriangulatedStepWallSelfTest::TriangulatedStepWallSelfTest(), TriangulatedWallSelfTest::TriangulatedWallSelfTest(), Tutorial11::Tutorial11(), and viscoElasticUnitTest::viscoElasticUnitTest().
setInteractionsWriteVTK()
void DPMBase::setInteractionsWriteVTK (bool writeVTK)
Sets whether interactions are written into a VTK file.
Deprecated:
Use interactionHandler.setWriteVTK(bool) instead (since 21-07-2021)
 {
     logger(WARN, "DPMBase.setInteractionsWriteVTK(bool) is deprecated! Use interactionHandler.setWriteVTK(bool) instead.");
     interactionHandler.setWriteVTK(writeVTK);
 }
References interactionHandler, logger, InteractionHandler::setWriteVTK(), and WARN.
setLastSavedTimeStep()
void DPMBase::setLastSavedTimeStep (unsigned int nextSavedTimeStep)
Sets the next time step for all the files (ene, data, fstat, restart, stat) at which the data is to be written or saved.
Sets the time step when the files will next be saved, except for the interaction file. Note, that the interaction file is independent of time steps, and just writes when an interaction starts or ends.
Parameters
[in] nextSavedTimeStep
 {
 dataFile.setLastSavedTimeStep(nextSavedTimeStep);
 fStatFile.setLastSavedTimeStep(nextSavedTimeStep);
 restartFile.setLastSavedTimeStep(nextSavedTimeStep);
 //statFile.setLastSavedTimeStep(nextSavedTimeStep); //this one is not force-written
 eneFile.setLastSavedTimeStep(nextSavedTimeStep);
 }
References dataFile, eneFile, fStatFile, restartFile, and File::setLastSavedTimeStep().
Referenced by forceWriteOutputFiles(), main(), and resetFileCounter().
setLogarithmicSaveCount()
void DPMBase::setLogarithmicSaveCount (Mdouble logarithmicSaveCountBase)
Sets File::logarithmicSaveCount_ for all files (ene, data, fstat, restart, stat)
sets the number of time steps skipped between each save for ALL data files, except for the interaction file. And the increment of this number of time steps is based on a user input logarithmicSaveCountBase, e.g. if you put 10 as your input, the saving point will be at 10, 10^1, 10^2, 10^3, which results equal distance on a log scale. Note, that the interaction file is independent of time steps, and just writes when an interaction starts or ends.
Parameters
[in] logarithmicSaveCountBase
 {
     dataFile.setlogarithmicSaveCount(logarithmicSaveCountBase);
     fStatFile.setlogarithmicSaveCount(logarithmicSaveCountBase);
     restartFile.setlogarithmicSaveCount(logarithmicSaveCountBase);
     statFile.setlogarithmicSaveCount(logarithmicSaveCountBase);
     eneFile.setlogarithmicSaveCount(logarithmicSaveCountBase);
 }
References dataFile, eneFile, fStatFile, restartFile, File::setlogarithmicSaveCount(), and statFile.
setMax() [1/2]
void DPMBase::setMax (const Vec3D & newMax)
Sets the maximum coordinates of the problem domain.
This specifies one corner of the problem's cuboidal bounding box. These bounds are used for display, plotting and statistics purposes. They do not affect the dynamics.
A sanity check is performed to verify that each of the maximum coordinates are greater than the corresponding minimum coordinates. It raises a (logged) warning if not.
Parameters
[in] newMax
 {
 if (min_.x() > newMax.x() ||
 min_.y() > newMax.y() ||
 min_.z() > newMax.z())
 {
 logger(WARN, "Warning in setMax: upper bound is smaller"
          " than lower bound. (%,%,%) > (%,%,%)",
        min_.x(), min_.y(), min_.z(), newMax.x(), newMax.y(), newMax.z());
 }
 else
 {
 max_ = newMax;
 }
 }
References logger, max_, min_, WARN, Vec3D::x(), Vec3D::y(), and Vec3D::z().
Referenced by ChangingTOIParticle::ChangingTOIParticle(), ForceLawsMPI2Test::ForceLawsMPI2Test(), GranuDrum::GranuDrum(), GranuHeap::GranuHeap(), InsertionBoundaryMPI2Test::InsertionBoundaryMPI2Test(), InsertionBoundarySelfTest::InsertionBoundarySelfTest(), LawinenBox::LawinenBox(), LeesEdwardsDemo::LeesEdwardsDemo(), LeesEdwardsSelfTest::LeesEdwardsSelfTest(), LiquidMigrationMPI2Test::LiquidMigrationMPI2Test(), loadingTest(), main(), MaserRepeatedOutInMPI2Test::MaserRepeatedOutInMPI2Test(), MercuryCGSelfTest::MercuryCGSelfTest(), MinimalExampleDrum::MinimalExampleDrum(), MultiParticlesInsertion::MultiParticlesInsertion(), normalAndTangentialLoadingTest(), objectivenessTest(), ParticleInclusion::ParticleInclusion(), FileReader::read(), RotatingDrumBidisperseInitialise::RotatingDrumBidisperseInitialise(), runFreeFall(), setMax(), NozzleDemo::setupInitialConditions(), RotatingDrumWet::setupInitialConditions(), VerticalMixer::setupInitialConditions(), ShiftingConstantMassFlowMaserBoundarySelfTest::setupInitialConditions(), ShiftingMaserBoundarySelfTest::setupInitialConditions(), GetDistanceAndNormalForIntersectionOfWalls::setupInitialConditions(), GetDistanceAndNormalForScrew::setupInitialConditions(), GetDistanceAndNormalForTriangleWall::setupInitialConditions(), Drum::setupInitialConditions(), HertzSelfTest::setupInitialConditions(), MindlinSelfTest::setupInitialConditions(), Penetration::setupInitialConditions(), Silo::setupInitialConditions(), DistributionSelfTest::setupInitialConditions(), DistributionToPSDSelfTest::setupInitialConditions(), InsertionBoundarySelfTest::setupInitialConditions(), MultiplePSDSelfTest::setupInitialConditions(), NozzleSelfTest::setupInitialConditions(), PSDManualInsertionSelfTest::setupInitialConditions(), SubcriticalMaserBoundarySelfTest::setupInitialConditions(), CGHandlerSelfTest::setupInitialConditions(), DPM::setupInitialConditions(), ChargedBondedInteractionSelfTest::setupInitialConditions(), FreeFallSelfTest::setupInitialConditions(), HertzianBSHPInteractionTwoParticleElasticCollision::setupInitialConditions(), LiquidMigrationSelfTest::setupInitialConditions(), ObliqueImpactSelfTest::setupInitialConditions(), TwoBondedParticleElasticCollision::setupInitialConditions(), TwoParticleBagheriCollision::setupInitialConditions(), TwoParticleClassicalWilletCollision::setupInitialConditions(), TwoParticleElasticCollisionInteraction::setupInitialConditions(), TwoParticleElasticCollision::setupInitialConditions(), ContactDetectionIntersectionOfWallsTest::setupInitialConditions(), GetDistanceAndNormalForTriangleWalls::setupInitialConditions(), RollingOverTriangleWalls::setupInitialConditions(), UnionOfWalls::setupInitialConditions(), BouncingSuperQuadric::setupInitialConditions(), EllipsoidsBouncingOnWallDemo::setupInitialConditions(), EllipticalSuperQuadricCollision::setupInitialConditions(), SlidingSpheresUnitTest::setupInitialConditions(), SphericalSuperQuadricCollision::setupInitialConditions(), ContactDetectionNormalSpheresTest::setupInitialConditions(), ContactDetectionRotatedSpheresTest::setupInitialConditions(), ShapesDemo::setupInitialConditions(), VisualisationTest::setupInitialConditions(), ArcWallUnitTest::setupInitialConditions(), Packing::setupInitialConditions(), CGDisplacementFieldUnitTest::setupInitialConditions(), CGExactOverlapUnitTest::setupInitialConditions(), CGForceDensityUnitTest::setupInitialConditions(), CreateDataAndFStatFiles::setupInitialConditions(), PSDSelfTest::setupInitialConditions(), EvaporationAndHeatTest::setupInitialConditions(), RandomClusterInsertionBoundarySelfTest::setupInitialConditions(), FluxBoundaryPrescribedDistanceUnitTest::setupInitialConditions(), FluxBoundaryUnitTest::setupInitialConditions(), FreeFallHertzMindlinUnitTest::setupInitialConditions(), HeatTransferUnitTest::setupInitialConditions(), HertzContactRestitutionUnitTest::setupInitialConditions(), MovingWalls::setupInitialConditions(), PeriodicWalls::setupInitialConditions(), AreaVTK::setupInitialConditions(), SinterPair::SinterPair(), StressStrainControl::StressStrainControl(), SubcriticalMaserBoundaryTESTMPI2Test::SubcriticalMaserBoundaryTESTMPI2Test(), TangentialSpringEnergyConservationUnitTest::TangentialSpringEnergyConservationUnitTest(), TimeDependentPeriodicBoundary3DSelfTest::TimeDependentPeriodicBoundary3DSelfTest(), TimeDependentPeriodicBoundaryTest::TimeDependentPeriodicBoundaryTest(), TriangulatedScrewSelfTest::TriangulatedScrewSelfTest(), TriangulatedStepSelfTest::TriangulatedStepSelfTest(), TriangulatedStepWallSelfTest::TriangulatedStepWallSelfTest(), TriangulatedWallSelfTest::TriangulatedWallSelfTest(), and TwoByTwoMPIDomainMPI4Test::TwoByTwoMPIDomainMPI4Test().
setMax() [2/2]
void DPMBase::setMax (Mdouble xMax, Mdouble yMax, Mdouble zMax)
Sets the maximum coordinates of the problem domain.
As in setMax but the coordinates are passed as three Mdouble, not a Vec3D.
 {
 setMax(Vec3D(xMax, yMax, zMax));
 }
References setMax().
setMeanVelocity()
void DPMBase::setMeanVelocity (Vec3D V_mean_goal)
This function will help you set a fixed kinetic energy and mean velocity in your system.
The function first generates random velocities for every particle in the system and then injects the desired kinetic energy and sets the desired mean velocity in the system.
Parameters
[in] V_mean_goal The mean velocity you want to set after injecting energy
[in] Ek_goal The kinetic energy you want to inject into the system
 {
     Vec3D meanVelocity = getTotalMomentum() / getTotalMass();
     //correct the mean velocity to zero
     for (auto& p : particleHandler)
     {
         p->addVelocity(-meanVelocity);
     }
 }
References getTotalMass(), getTotalMomentum(), p, and particleHandler.
Referenced by FreeCooling2DinWalls::setupInitialConditions().
setMeanVelocityAndKineticEnergy()
void DPMBase::setMeanVelocityAndKineticEnergy (Vec3D V_mean_goal, Mdouble Ek_goal)
This function will help you set a fixed kinetic energy and mean velocity in your system.
The function first generates random velocities for every particle in the system and then injects the desired kinetic energy and sets the desired mean velocity in the system.
Parameters
[in] V_mean_goal The mean velocity you want to set after injecting energy
[in] Ek_goal The kinetic energy you want to inject into the system
 {
     Vec3D V_mean;
     Mdouble Ek_mean_goal = 0, Ek_fluct_factor = 0;
     RNG rng;
     //assign random velocity to each particle
     for (auto& p : particleHandler)
     {
         p->setVelocity(Vec3D(rng.getRandomNumber(-1, 1), rng.getRandomNumber(-1, 1), rng.getRandomNumber(-1, 1)));
     }
     //calculate the mean velocity in the system now
     Ek_mean_goal = 0.5 * getTotalMass() * V_mean_goal.getLengthSquared();
     V_mean = getTotalMomentum() / getTotalMass();
     //check if the user input mean kinetic energy is larger than the total kinetic energy input, then return error
     logger.assert_always(0.5 * getTotalMass() * V_mean_goal.getLengthSquared() < Ek_goal,
                          "Too large mean velocity input, Kinetic energy from mean velocity part is larger than the "
                                  "total kinetic energy you want to set");
     //correct the mean velocity to zero
     for (auto& p : particleHandler)
     {
         p->addVelocity(-V_mean);
     }
     //set the new fluctuating velocity based on the goal fluctuating kinetic energy
     Ek_fluct_factor = std::sqrt((Ek_goal - Ek_mean_goal) / getKineticEnergy());
     for (auto& p : particleHandler)
     {
         p->setVelocity(Ek_fluct_factor * p->getVelocity());
     }
     //correct the mean velocity finally to the user set values
     V_mean = getTotalMomentum() / getTotalMass();
     for (auto& p : particleHandler)
     {
         p->addVelocity(V_mean_goal - V_mean);
     }
     //check the final mean velocity and kinetic energy
     logger(INFO, "In DPMBase::setMeanVelocityAndKineticEnergy,\nV_mean_final %\n Ek_final %",
            getTotalMomentum() / getTotalMass(), getKineticEnergy());
 }
References getKineticEnergy(), Vec3D::getLengthSquared(), RNG::getRandomNumber(), getTotalMass(), getTotalMomentum(), INFO, logger, p, particleHandler, and sqrt().
setMin() [1/2]
void DPMBase::setMin (const Vec3D & newMin)
Sets the minimum coordinates of the problem domain.
This specifies one corner of the problem's cuboidal bounding box. These bounds are used for display, plotting and statistics purposes. They do not affect the dynamics.
A sanity check is performed to verify that each of the minimum coordinates are greater than the corresponding maximum coordinates. It raises a (logged) warning if not.
Parameters
[in] newMin
 {
 if (max_.x() < newMin.x() ||
 max_.y() < newMin.y() ||
 max_.z() < newMin.z())
 {
 logger(WARN, "Warning in setMin: lower bound is larger"
          " than upper bound. (%,%,%) < (%,%,%)",
        max_.x(), max_.y(), max_.z(), newMin.x(), newMin.y(), newMin.z());
 }
 else
 {
 min_ = newMin;
 }
 }
References logger, max_, min_, WARN, Vec3D::x(), Vec3D::y(), and Vec3D::z().
Referenced by ChangingTOIParticle::ChangingTOIParticle(), ForceLawsMPI2Test::ForceLawsMPI2Test(), GranuDrum::GranuDrum(), GranuHeap::GranuHeap(), InsertionBoundaryMPI2Test::InsertionBoundaryMPI2Test(), InsertionBoundarySelfTest::InsertionBoundarySelfTest(), LeesEdwardsDemo::LeesEdwardsDemo(), LeesEdwardsSelfTest::LeesEdwardsSelfTest(), LiquidMigrationMPI2Test::LiquidMigrationMPI2Test(), loadingTest(), main(), MaserRepeatedOutInMPI2Test::MaserRepeatedOutInMPI2Test(), MercuryCGSelfTest::MercuryCGSelfTest(), MinimalExampleDrum::MinimalExampleDrum(), MultiParticlesInsertion::MultiParticlesInsertion(), normalAndTangentialLoadingTest(), objectivenessTest(), ParticleInclusion::ParticleInclusion(), FileReader::read(), RotatingDrumBidisperseInitialise::RotatingDrumBidisperseInitialise(), setMin(), NozzleDemo::setupInitialConditions(), RotatingDrumWet::setupInitialConditions(), VerticalMixer::setupInitialConditions(), ShiftingConstantMassFlowMaserBoundarySelfTest::setupInitialConditions(), ShiftingMaserBoundarySelfTest::setupInitialConditions(), GetDistanceAndNormalForIntersectionOfWalls::setupInitialConditions(), GetDistanceAndNormalForScrew::setupInitialConditions(), GetDistanceAndNormalForTriangleWall::setupInitialConditions(), Drum::setupInitialConditions(), HertzSelfTest::setupInitialConditions(), MindlinSelfTest::setupInitialConditions(), Penetration::setupInitialConditions(), Silo::setupInitialConditions(), DistributionSelfTest::setupInitialConditions(), DistributionToPSDSelfTest::setupInitialConditions(), InsertionBoundarySelfTest::setupInitialConditions(), MultiplePSDSelfTest::setupInitialConditions(), NozzleSelfTest::setupInitialConditions(), PSDManualInsertionSelfTest::setupInitialConditions(), SubcriticalMaserBoundarySelfTest::setupInitialConditions(), CGHandlerSelfTest::setupInitialConditions(), DPM::setupInitialConditions(), ChargedBondedInteractionSelfTest::setupInitialConditions(), HertzianBSHPInteractionTwoParticleElasticCollision::setupInitialConditions(), ObliqueImpactSelfTest::setupInitialConditions(), TwoBondedParticleElasticCollision::setupInitialConditions(), ContactDetectionIntersectionOfWallsTest::setupInitialConditions(), GetDistanceAndNormalForTriangleWalls::setupInitialConditions(), RollingOverTriangleWalls::setupInitialConditions(), UnionOfWalls::setupInitialConditions(), BouncingSuperQuadric::setupInitialConditions(), EllipsoidsBouncingOnWallDemo::setupInitialConditions(), EllipticalSuperQuadricCollision::setupInitialConditions(), SlidingSpheresUnitTest::setupInitialConditions(), SphericalSuperQuadricCollision::setupInitialConditions(), ContactDetectionNormalSpheresTest::setupInitialConditions(), ContactDetectionRotatedSpheresTest::setupInitialConditions(), ShapesDemo::setupInitialConditions(), VisualisationTest::setupInitialConditions(), ArcWallUnitTest::setupInitialConditions(), Packing::setupInitialConditions(), CGDisplacementFieldUnitTest::setupInitialConditions(), CGExactOverlapUnitTest::setupInitialConditions(), CGForceDensityUnitTest::setupInitialConditions(), CreateDataAndFStatFiles::setupInitialConditions(), PSDSelfTest::setupInitialConditions(), EvaporationAndHeatTest::setupInitialConditions(), RandomClusterInsertionBoundarySelfTest::setupInitialConditions(), FluxBoundaryPrescribedDistanceUnitTest::setupInitialConditions(), FluxBoundaryUnitTest::setupInitialConditions(), FreeFallHertzMindlinUnitTest::setupInitialConditions(), HeatTransferUnitTest::setupInitialConditions(), HertzContactRestitutionUnitTest::setupInitialConditions(), MovingWalls::setupInitialConditions(), AreaVTK::setupInitialConditions(), SinterPair::SinterPair(), StressStrainControl::StressStrainControl(), SubcriticalMaserBoundaryTESTMPI2Test::SubcriticalMaserBoundaryTESTMPI2Test(), TangentialSpringEnergyConservationUnitTest::TangentialSpringEnergyConservationUnitTest(), TimeDependentPeriodicBoundary3DSelfTest::TimeDependentPeriodicBoundary3DSelfTest(), TimeDependentPeriodicBoundaryTest::TimeDependentPeriodicBoundaryTest(), TriangulatedScrewSelfTest::TriangulatedScrewSelfTest(), TriangulatedStepSelfTest::TriangulatedStepSelfTest(), TriangulatedStepWallSelfTest::TriangulatedStepWallSelfTest(), TriangulatedWallSelfTest::TriangulatedWallSelfTest(), and TwoByTwoMPIDomainMPI4Test::TwoByTwoMPIDomainMPI4Test().
setMin() [2/2]
void DPMBase::setMin (Mdouble xMin, Mdouble yMin, Mdouble zMin)
Sets the minimum coordinates of the problem domain.
As in setMin but the coordinates are passed as three Mdouble, not a Vec3D.
 {
 setMin(Vec3D(xMin, yMin, zMin));
 }
References setMin().
setName() [1/2]
void DPMBase::setName (const char * name)
Calls setName(std::string)
Parameters
[in] name
 {
 setName(std::string(name));
 }
References plotDoE::name, setName(), and oomph::Global_string_for_annotation::string().
setName() [2/2]
void DPMBase::setName (const std::string & name)
Allows to set the name of all the files (ene, data, fstat, restart, stat)
Parameters
[in] name
 {
 if (NUMBER_OF_PROCESSORS > 1)
 {
 name_ = name; // was before this->name_ = name
 dataFile.setName(name_ + ".data" + std::to_string(PROCESSOR_ID));
 fStatFile.setName(name_ + ".fstat" + std::to_string(PROCESSOR_ID));
 restartFile.setName(name_ + ".restart" + std::to_string(PROCESSOR_ID));
 statFile.setName(name_ + ".stat" + std::to_string(PROCESSOR_ID));
 eneFile.setName(name_ + ".ene" + std::to_string(PROCESSOR_ID));
 getInteractionFile().setName(name_ + ".interaction" + std::to_string(PROCESSOR_ID));
 }
 else
 {
 name_ = name; // was before this->name_ = name
 dataFile.setName(name_ + ".data");
 fStatFile.setName(name_ + ".fstat");
 restartFile.setName(name_ + ".restart");
 statFile.setName(name_ + ".stat");
 eneFile.setName(name_ + ".ene");
 interactionFile.setName(name_ + ".interaction");
 }
 }
References dataFile, eneFile, fStatFile, getInteractionFile(), interactionFile, plotDoE::name, name_, NUMBER_OF_PROCESSORS, PROCESSOR_ID, restartFile, File::setName(), statFile, and oomph::StringConversion::to_string().
Referenced by ChuteRestartDemo::actionsOnRestart(), AngleOfRepose::AngleOfRepose(), AxisymmetricWallSelfTest::AxisymmetricWallSelfTest(), CGBasicSelfTest::CGBasicSelfTest(), CGDisplacementFieldUnitTest::CGDisplacementFieldUnitTest(), CGExactOverlapUnitTest::CGExactOverlapUnitTest(), CGForceDensityUnitTest::CGForceDensityUnitTest(), ChangingTOIParticle::ChangingTOIParticle(), ChutePeriodicDemo::ChutePeriodicDemo(), ChuteWithContraction::ChuteWithContraction(), ChuteWithPeriodicInflowAndContinuingBottom::ChuteWithPeriodicInflowAndContinuingBottom(), ChuteWithPeriodicInflowAndContraction::ChuteWithPeriodicInflowAndContraction(), ChuteWithPeriodicInflowAndVariableBottom::ChuteWithPeriodicInflowAndVariableBottom(), ClosedCSCRestart::ClosedCSCRestart(), ClosedCSCRun::ClosedCSCRun(), ClosedCSCStats::ClosedCSCStats(), ClosedCSCWalls::ClosedCSCWalls(), clumpTest::clumpTest(), ChuteBottom::constructor(), constructor(), Contact::Contact(), ContractionWithPeriodicInflow::ContractionWithPeriodicInflow(), Slide::create_rough_wall(), CSCInit::CSCInit(), CSCRestart::CSCRestart(), CSCStats::CSCStats(), CSCWalls::CSCWalls(), DPM::DPM(), DPMBase(), FileReader::FileReader(), FluxBoundaryPrescribedDistanceUnitTest::FluxBoundaryPrescribedDistanceUnitTest(), FluxBoundaryUnitTest::FluxBoundaryUnitTest(), ForceLawsMPI2Test::ForceLawsMPI2Test(), GranuDrum::GranuDrum(), GranuHeap::GranuHeap(), Hertzian2DUnitTest::Hertzian2DUnitTest(), Indenter::Indenter(), inflowFromPeriodic::inflowFromPeriodic(), InitialConditions< SpeciesType >::InitialConditions(), initialiseSolve(), InsertionBoundaryMPI2Test::InsertionBoundaryMPI2Test(), LaserOnLayer::LaserOnLayer(), LawinenBox::LawinenBox(), LeesEdwardsDemo::LeesEdwardsDemo(), LeesEdwardsSelfTest::LeesEdwardsSelfTest(), LiquidMigrationMPI2Test::LiquidMigrationMPI2Test(), load(), ChuteWithPeriodicInflow::loadPeriodicBox(), ChuteWithContraction::loadPeriodicBox(), main(), MaserRepeatedOutInMPI2Test::MaserRepeatedOutInMPI2Test(), MercuryCGSelfTest::MercuryCGSelfTest(), MovingWalls::MovingWalls(), MultiParticlesInsertion::MultiParticlesInsertion(), ParticleBeam::ParticleBeam(), ParticleInclusion::ParticleInclusion(), read(), readNextArgument(), Mercury3DRestart::readNextArgument(), readOld(), regimeForceUnitTest::regimeForceUnitTest(), CGHandler::restart(), RotatingDrumBidisperse::RotatingDrumBidisperse(), RotatingDrumBidisperseInitialise::RotatingDrumBidisperseInitialise(), statistics_while_running< T >::run(), AngleOfRepose::run(), vibratedBed::run(), runFreeFall(), SaveCountUnitTest::SaveCountUnitTest(), SilbertPeriodic::set_study(), setName(), Funnel::setName_(), ChutePeriodic::setup(), ClosedCSCStats::setupInitialConditions(), CSCRun::setupInitialConditions(), CSCStats::setupInitialConditions(), CFDDEMCoupleTest::setupInitialConditions(), NozzleDemo::setupInitialConditions(), RotatingDrumWet::setupInitialConditions(), Chain::setupInitialConditions(), ShiftingConstantMassFlowMaserBoundarySelfTest::setupInitialConditions(), ShiftingMaserBoundarySelfTest::setupInitialConditions(), Cstatic3D::setupInitialConditions(), InitialBed::setupInitialConditions(), MeltableForceLaw2SelfTest::setupInitialConditions(), MeltableForceLawSelfTest::setupInitialConditions(), OneParticleHeatingSelfTest::setupInitialConditions(), OneParticleCoolingSelfTest::setupInitialConditions(), ThermalConductionSelfTest::setupInitialConditions(), GetDistanceAndNormalForIntersectionOfWalls::setupInitialConditions(), GetDistanceAndNormalForScrew::setupInitialConditions(), GetDistanceAndNormalForTriangleWall::setupInitialConditions(), Drum::setupInitialConditions(), HertzSelfTest::setupInitialConditions(), MindlinSelfTest::setupInitialConditions(), Penetration::setupInitialConditions(), Silo::setupInitialConditions(), ConstantMassFlowMaserBoundaryMixedSpeciesSelfTest::setupInitialConditions(), ConstantMassFlowMaserSelfTest::setupInitialConditions(), CubeDeletionBoundarySelfTest::setupInitialConditions(), DeletionBoundarySelfTest::setupInitialConditions(), DistributionSelfTest::setupInitialConditions(), DistributionToPSDSelfTest::setupInitialConditions(), InsertionBoundarySelfTest::setupInitialConditions(), MultiplePSDSelfTest::setupInitialConditions(), NozzleSelfTest::setupInitialConditions(), PolydisperseInsertionBoundarySelfTest::setupInitialConditions(), PSDManualInsertionSelfTest::setupInitialConditions(), SubcriticalMaserBoundarySelfTest::setupInitialConditions(), CGHandlerSelfTest::setupInitialConditions(), DPM::setupInitialConditions(), ChargedBondedInteractionSelfTest::setupInitialConditions(), ContactDetectionIntersectionOfWallsTest::setupInitialConditions(), GetDistanceAndNormalForTriangleWalls::setupInitialConditions(), RollingOverTriangleWalls::setupInitialConditions(), UnionOfWalls::setupInitialConditions(), SimpleOpt::setupInitialConditions(), ParticleParticleInteraction::setupInitialConditions(), ParticleParticleInteractionWithPlasticForces::setupInitialConditions(), ParticleWallInteraction::setupInitialConditions(), CreateDataAndFStatFiles::setupInitialConditions(), PSDSelfTest::setupInitialConditions(), EvaporationAndHeatTest::setupInitialConditions(), RandomClusterInsertionBoundarySelfTest::setupInitialConditions(), HeatTransferUnitTest::setupInitialConditions(), AreaVTK::setupInitialConditions(), BaseCluster::setupInitialConditions(), MercuryProblem::setupMercuryProblem(), ShearStage::ShearStage(), Siegen::Siegen(), SilbertPeriodic::SilbertPeriodic(), SingleParticle< SpeciesType >::SingleParticle(), SingleParticleIndenter::SingleParticleIndenter(), SingleParticleSegregation::SingleParticleSegregation(), Sintering::Sintering(), SinterPair::SinterPair(), Slide::Slide(), statistics_while_running< T >::statistics_while_running(), StressStrainControl::StressStrainControl(), SubcriticalMaserBoundaryTESTMPI2Test::SubcriticalMaserBoundaryTESTMPI2Test(), T_protectiveWall::T_protectiveWall(), TangentialSpringEnergyConservationUnitTest::TangentialSpringEnergyConservationUnitTest(), BouncingSuperQuadric::test(), SlidingSpheresUnitTest::test(), ContactDetectionNormalSpheresTest::test(), ContactDetectionRotatedSpheresTest::test(), Packing::test(), HertzContactRestitutionUnitTest::test(), TimeDependentPeriodicBoundary3DSelfTest::TimeDependentPeriodicBoundary3DSelfTest(), TimeDependentPeriodicBoundaryTest::TimeDependentPeriodicBoundaryTest(), TriangulatedScrewSelfTest::TriangulatedScrewSelfTest(), TriangulatedStepSelfTest::TriangulatedStepSelfTest(), TriangulatedStepWallSelfTest::TriangulatedStepWallSelfTest(), TriangulatedWallSelfTest::TriangulatedWallSelfTest(), Tutorial11::Tutorial11(), TwoByTwoMPIDomainMPI4Test::TwoByTwoMPIDomainMPI4Test(), viscoElasticUnitTest::viscoElasticUnitTest(), Wall::Wall(), and ChutePeriodic::writeToLocalFolder().
setNToWrite()
void DPMBase::setNToWrite (int nToWrite)
set the number of elements to write to the screen
sets nToWrite_. If a user wants to output e.g. particle information to the screen we limit the number of outputs to nToWrite elements to not get an overflow of information in the terminal.
Parameters
[in] nToWrite Number of elements to write to the screen
 {
 nToWrite_ = nToWrite;
 }
References nToWrite_.
setNumberOfDomains()
void DPMBase::setNumberOfDomains (std::vector< unsigned > numberOfDomains)
Sets the number of domains in x-,y- and z-direction. Required for parallel computations.
Sets the number of domains in DPMbase.
The parallel code decomposes the domain according to these values
Parameters
[in] numberOfDomains
 {
 #ifdef MERCURYDPM_USE_MPI
     numberOfDomains_ = numberOfDomains;
     logger(INFO, "Split domain into a %x%x% grid",numberOfDomains[0],numberOfDomains[1],numberOfDomains[2]);
 #else
     logger(WARN, "Setting number of domains, but code is not compiled with MPI on");
 #endif
 }
References INFO, logger, numberOfDomains_, and WARN.
Referenced by RandomClusterInsertionBoundary::checkBoundaryBeforeTimeStep(), ForceLawsMPI2Test::ForceLawsMPI2Test(), InsertionBoundaryMPI2Test::InsertionBoundaryMPI2Test(), LiquidMigrationMPI2Test::LiquidMigrationMPI2Test(), main(), splitDomain(), SubcriticalMaserBoundaryTESTMPI2Test::SubcriticalMaserBoundaryTESTMPI2Test(), and TwoByTwoMPIDomainMPI4Test::TwoByTwoMPIDomainMPI4Test().
setNumberOfOMPThreads()
void DPMBase::setNumberOfOMPThreads (int numberOfOMPThreads)
Sets the number of omp threads.
 {
 logger.assert_always(numberOfOMPThreads > 0, "Number of OMP threads must be positive");
 numberOfOMPThreads_ = numberOfOMPThreads;
 #ifdef MERCURYDPM_USE_OMP
 if(numberOfOMPThreads > omp_get_max_threads()) {
 logger(INFO, "Number of omp threads set to the maximum number of threads allowed: %",
        omp_get_max_threads());
 numberOfOMPThreads_ = numberOfOMPThreads = omp_get_max_threads();
 }
 #pragma omp parallel num_threads(getNumberOfOMPThreads())
 {
 if (omp_get_thread_num()==0)
     logger(INFO, "Using % of % omp threads; testing thread",
        omp_get_num_threads(), omp_get_max_threads(), Flusher::NO_FLUSH);
 }
 #pragma omp parallel num_threads(getNumberOfOMPThreads())
 {
         logger(INFO, " %", std::to_string(omp_get_thread_num()), Flusher::NO_FLUSH);
     }
     logger(INFO,"");
 #else
     logger(WARN, "You are setting the number of omp threads to %, but OMP is not turned on", getNumberOfOMPThreads());
 #endif
 }
References getNumberOfOMPThreads(), INFO, logger, NO_FLUSH, numberOfOMPThreads_, oomph::StringConversion::to_string(), and WARN.
Referenced by main(), and read().
setOpenMode()
void DPMBase::setOpenMode (std::fstream::openmode openMode)
Sets File::openMode_ for all files (ene, data, fstat, restart, stat)
Parameters
[in] openmode
 {
 dataFile.setOpenMode(openMode);
 fStatFile.setOpenMode(openMode);
 restartFile.setOpenMode(openMode);
 statFile.setOpenMode(openMode);
 eneFile.setOpenMode(openMode);
 interactionFile.setOpenMode(openMode);
 }
References dataFile, eneFile, fStatFile, interactionFile, restartFile, File::setOpenMode(), and statFile.
Referenced by initialiseSolve().
setParticleDimensions()
void DPMBase::setParticleDimensions (unsigned int particleDimensions)
Sets the particle dimensionality.
Sets the dimensionality of the particles. This affects whether particles are treated as rods, discs or spheres. This is used e.g. for calculating masses and moments of inertia.
Note that the system may possess a different dimensionality.
The particles can be chosen to be one- two- or three-dimensional by passing, respectively, arguments equal to 1, 2 or 3. The code also performs a sanity check to ensure that the dimensionality cannot be higher than three or lower than one. If an unphysical dimensionality is chosen, the particle dimension is set to be equal to the system dimension. Note, that we cannot throw an error here, since in some old restart files the "particleDimensions_" are 0.
Parameters
[in] particleDimensions An integer value representing the desired dimensionality of the particles: 1 → 1D, 2 → 2D, 3 → 3D.
 {
     if (particleDimensions >= 1 && particleDimensions <= 3)
     {
         particleDimensions_ = particleDimensions;
         particleHandler.computeAllMasses();
     }
     else
     {
         logger(WARN, "Error in setParticleDimensions; particleDimensions % is not 1, 2 or 3, setting it to "
                      "systemDimension now (%)", particleDimensions, systemDimensions_);
         particleDimensions_ = systemDimensions_;
     }
 }
References ParticleHandler::computeAllMasses(), logger, particleDimensions_, particleHandler, systemDimensions_, and WARN.
Referenced by constructor(), Mercury2D::constructor(), Mercury3D::constructor(), loadingTest(), main(), normalAndTangentialLoadingTest(), objectivenessTest(), SpeciesHandler::readOldObject(), readParAndIniFiles(), setDimension(), ParticleParticleCollision::setupInitialConditions(), WallParticleCollision::setupInitialConditions(), ParticleParticleInteraction::setupInitialConditions(), ParticleParticleInteractionWithPlasticForces::setupInitialConditions(), ParticleWallInteraction::setupInitialConditions(), ChargedBondedParticleUnitTest::setupInitialConditions(), MovingIntersectionOfWallsUnitTest_Basic::setupInitialConditions(), MovingWall::setupInitialConditions(), SeparateFilesSelfTest::setupInitialConditions(), TangentialSpringUnitTest::setupInitialConditions(), WallSpecies::setupInitialConditions(), and Siegen::Siegen().
setParticlesWriteVTK()
void DPMBase::setParticlesWriteVTK (bool writeParticlesVTK)
Sets whether particles are written in a VTK file.
The VTK format is used for visualisation in Paraview.
Todo:
Move this (and the get) to ParticleHandler.
Parameters
[in] writeParticlesVTK
 {
 writeParticlesVTK_ = writeParticlesVTK;
 if (writeParticlesVTK_)
 {
 writeSuperquadricParticlesVTK_ = false;
 }
 delete vtkWriter_;
 vtkWriter_ = new SphericalParticleVtkWriter(particleHandler);
 }
References particleHandler, vtkWriter_, writeParticlesVTK_, and writeSuperquadricParticlesVTK_.
Referenced by Chutebelt::actionsAfterTimeStep(), BaseCluster::actionsOnRestart(), AxisymmetricWallSelfTest::AxisymmetricWallSelfTest(), HorizontalMixer::HorizontalMixer(), LaserOnLayer::LaserOnLayer(), main(), MaserRepeatedOutInMPI2Test::MaserRepeatedOutInMPI2Test(), ParticleBeam::ParticleBeam(), protectiveWall::protectiveWall(), read(), RotatingDrumBidisperse::RotatingDrumBidisperse(), ChutePeriodicDemo::setupInitialConditions(), ChangingTOIParticle::setupInitialConditions(), NautaMixer::setupInitialConditions(), NozzleDemo::setupInitialConditions(), RotatingDrumWet::setupInitialConditions(), MarbleRun::setupInitialConditions(), InitialBed::setupInitialConditions(), MeltableForceLaw2SelfTest::setupInitialConditions(), MeltableForceLawSelfTest::setupInitialConditions(), ThermalConductionSelfTest::setupInitialConditions(), Drum::setupInitialConditions(), Penetration::setupInitialConditions(), Silo::setupInitialConditions(), SingleParticleSegregation::setupInitialConditions(), NozzleSelfTest::setupInitialConditions(), SubcriticalMaserBoundarySelfTest::setupInitialConditions(), TwoParticleBagheriCollision::setupInitialConditions(), TwoParticleClassicalWilletCollision::setupInitialConditions(), RollingOverTriangleWalls::setupInitialConditions(), PSDSelfTest::setupInitialConditions(), MovingWalls::setupInitialConditions(), AreaVTK::setupInitialConditions(), BaseCluster::setupInitialConditions(), MercuryProblem::setupMercuryProblem(), SinterPair::SinterPair(), SubcriticalMaserBoundaryTESTMPI2Test::SubcriticalMaserBoundaryTESTMPI2Test(), T_protectiveWall::T_protectiveWall(), TangentialSpringEnergyConservationUnitTest::TangentialSpringEnergyConservationUnitTest(), and Tutorial11::Tutorial11().
setRestarted()
void DPMBase::setRestarted (bool newRestartedFlag)
Allows to set the flag stating if the simulation is to be restarted or not.
Parameters
[in] newRestartedFlag
 {
     restarted_ = newRestartedFlag;
     //setAppend(new_);
 }
References restarted_.
Referenced by ClosedCSCRun::ClosedCSCRun(), ClosedCSCStats::ClosedCSCStats(), constructor(), CSCInit::CSCInit(), CSCStats::CSCStats(), Indenter::Indenter(), inflowFromPeriodic::inflowFromPeriodic(), LaserOnLayer::LaserOnLayer(), ChuteWithPeriodicInflow::loadPeriodicBox(), ChuteWithContraction::loadPeriodicBox(), main(), readOld(), readRestartFile(), RotatingDrumBidisperse::RotatingDrumBidisperse(), CSCRun::setupInitialConditions(), CFDDEMCoupleTest::setupInitialConditions(), ShearStage::ShearStage(), SingleParticleIndenter::SingleParticleIndenter(), Sintering::Sintering(), and StressStrainControl::StressStrainControl().
setRestartVersion()
void DPMBase::setRestartVersion (std::string newRV)
Sets restart_version.
Parameters
[in] newRV
 {
     restartVersion_ = newRV;
 }
References restartVersion_.
setRotation()
void DPMBase::setRotation (bool rotation) inline
Sets whether particle rotation is enabled or disabled.
Todo:
Passing true will enable particle rotation. Passing false will disable particle rotation.
Parameters
[in] newRotFlag
     { rotation_ = rotation; }
References rotation_.
Referenced by ParticleHandler::addObject(), SpeciesHandler::addObject(), SpeciesHandler::removeObject(), MembraneDemo::setupInitialConditions(), and MembraneSelfTest::setupInitialConditions().
setRunNumber()
void DPMBase::setRunNumber (int runNumber)
This sets the counter/Run number, overriding the defaults.
A simple "set function" which allows the user to simply overwrite the current run number to any valid new value.
Parameters
[in] runNumber - the value to which we want to (re)set the internally stored run number parameter, runNumber_
 {
 runNumber_ = runNumber;
 }
References runNumber_.
Referenced by autoNumber(), and readNextArgument().
setSaveCount()
void DPMBase::setSaveCount (unsigned int saveCount)
Sets File::saveCount_ for all files (ene, data, fstat, restart, stat)
sets the number of time steps skipped between each save for ALL data files, except for the interaction file. Note, that the interaction file is independent of time steps, and just writes when an interaction starts or ends.
 {
 dataFile.setSaveCount(saveCount);
 fStatFile.setSaveCount(saveCount);
 restartFile.setSaveCount(saveCount);
 statFile.setSaveCount(saveCount);
 eneFile.setSaveCount(saveCount);
 for (auto cg : cgHandler)
 cg->statFile.setSaveCount(saveCount);
 }
References cgHandler, dataFile, eneFile, fStatFile, restartFile, File::setSaveCount(), and statFile.
Referenced by BaseCluster::actionsAfterTimeStep(), DrumRot::actionsBeforeTimeStep(), SaveCountUnitTest::actionsBeforeTimeStep(), ChuteRestartDemo::actionsOnRestart(), DrumRot::actionsOnRestart(), BaseCluster::actionsOnRestart(), NautaMixer::addSpeciesAndSetTimeStepAndSaveCount(), AngleOfRepose::AngleOfRepose(), BoundariesSelfTest::BoundariesSelfTest(), CGBasicSelfTest::CGBasicSelfTest(), ChutePeriodicDemo::ChutePeriodicDemo(), ClosedCSCRun::ClosedCSCRun(), ClosedCSCStats::ClosedCSCStats(), ClosedCSCWalls::ClosedCSCWalls(), constructor(), CSCStats::CSCStats(), CSCWalls::CSCWalls(), DPM::DPM(), FluxAndPeriodicBoundarySelfTest::FluxAndPeriodicBoundarySelfTest(), FluxBoundarySelfTest::FluxBoundarySelfTest(), ForceLawsMPI2Test::ForceLawsMPI2Test(), CLiveStatistics< T >::getLiveStatistics(), GranuDrum::GranuDrum(), Hertzian2DUnitTest::Hertzian2DUnitTest(), InitialConditions< SpeciesType >::InitialConditions(), LaserOnLayer::LaserOnLayer(), LeesEdwardsDemo::LeesEdwardsDemo(), LeesEdwardsSelfTest::LeesEdwardsSelfTest(), LiquidMigrationMPI2Test::LiquidMigrationMPI2Test(), loadingTest(), main(), ChuteBottom::makeRoughBottom(), MaserRepeatedOutInMPI2Test::MaserRepeatedOutInMPI2Test(), MercuryCGSelfTest::MercuryCGSelfTest(), MinimalExampleDrum::MinimalExampleDrum(), normalAndTangentialLoadingTest(), objectivenessTest(), ParticleBeam::ParticleBeam(), readNextArgument(), readParAndIniFiles(), regimeForceUnitTest::regimeForceUnitTest(), RotatingDrumBidisperse::RotatingDrumBidisperse(), RotatingDrumBidisperseInitialise::RotatingDrumBidisperseInitialise(), FlowRule::run(), statistics_while_running< T >::run(), AngleOfRepose::run(), runFreeFall(), Calibration::setOutput(), ChutePeriodic::setup(), CSCRun::setupInitialConditions(), CFDDEMCoupleTest::setupInitialConditions(), NozzleDemo::setupInitialConditions(), RotatingDrumWet::setupInitialConditions(), VerticalMixer::setupInitialConditions(), Chain::setupInitialConditions(), MarbleRun::setupInitialConditions(), ShiftingConstantMassFlowMaserBoundarySelfTest::setupInitialConditions(), ShiftingMaserBoundarySelfTest::setupInitialConditions(), InitialBed::setupInitialConditions(), MeltableForceLaw2SelfTest::setupInitialConditions(), MeltableForceLawSelfTest::setupInitialConditions(), OneParticleHeatingSelfTest::setupInitialConditions(), OneParticleCoolingSelfTest::setupInitialConditions(), ThermalConductionSelfTest::setupInitialConditions(), Drum::setupInitialConditions(), HertzSelfTest::setupInitialConditions(), MindlinSelfTest::setupInitialConditions(), Penetration::setupInitialConditions(), Silo::setupInitialConditions(), ConstantMassFlowMaserBoundaryMixedSpeciesSelfTest::setupInitialConditions(), ConstantMassFlowMaserSelfTest::setupInitialConditions(), CubeDeletionBoundarySelfTest::setupInitialConditions(), DeletionBoundarySelfTest::setupInitialConditions(), DistributionPhiNormalSelfTest::setupInitialConditions(), NozzleSelfTest::setupInitialConditions(), SubcriticalMaserBoundarySelfTest::setupInitialConditions(), CGStaticBalanceSelfTest::setupInitialConditions(), ChargedBondedInteractionSelfTest::setupInitialConditions(), ParticleParticleCollision::setupInitialConditions(), WallParticleCollision::setupInitialConditions(), DPM::setupInitialConditions(), TwoParticleCollisionInteraction::setupInitialConditions(), RollingOverTriangleWalls::setupInitialConditions(), UnionOfWalls::setupInitialConditions(), Contact::setupInitialConditions(), Wall::setupInitialConditions(), ParticleParticleInteraction::setupInitialConditions(), ParticleParticleInteractionWithPlasticForces::setupInitialConditions(), ParticleWallInteraction::setupInitialConditions(), Packing::setupInitialConditions(), CreateDataAndFStatFiles::setupInitialConditions(), EvaporationAndHeatTest::setupInitialConditions(), HeatTransferUnitTest::setupInitialConditions(), HertzianSinterForceUnitTest::setupInitialConditions(), LongHertzianSinterForceUnitTest::setupInitialConditions(), MovingIntersectionOfWallsUnitTest_Basic::setupInitialConditions(), MovingWalls::setupInitialConditions(), MovingWall::setupInitialConditions(), PlasticForceUnitTest::setupInitialConditions(), SaveCountUnitTest::setupInitialConditions(), SeparateFilesSelfTest::setupInitialConditions(), SetDistributionPhiNormalSelfTest::setupInitialConditions(), SpeciesTest::setupInitialConditions(), WallSpecies::setupInitialConditions(), AreaVTK::setupInitialConditions(), BaseCluster::setupInitialConditions(), MercuryProblem::setupMercuryProblem(), SilbertHstop::SilbertHstop(), SilbertPeriodic::SilbertPeriodic(), SingleParticleSegregation::SingleParticleSegregation(), SinterPair::SinterPair(), Slide::Slide(), statistics_while_running< T >::statistics_while_running(), SubcriticalMaserBoundaryTESTMPI2Test::SubcriticalMaserBoundaryTESTMPI2Test(), T_protectiveWall::T_protectiveWall(), TangentialSpringEnergyConservationUnitTest::TangentialSpringEnergyConservationUnitTest(), BouncingSuperQuadric::test(), SlidingSpheresUnitTest::test(), ContactDetectionNormalSpheresTest::test(), ContactDetectionRotatedSpheresTest::test(), HertzContactRestitutionUnitTest::test(), TimeDependentPeriodicBoundary3DSelfTest::TimeDependentPeriodicBoundary3DSelfTest(), TimeDependentPeriodicBoundaryTest::TimeDependentPeriodicBoundaryTest(), TriangulatedScrewSelfTest::TriangulatedScrewSelfTest(), TriangulatedStepSelfTest::TriangulatedStepSelfTest(), TriangulatedStepWallSelfTest::TriangulatedStepWallSelfTest(), TriangulatedWallSelfTest::TriangulatedWallSelfTest(), TwoByTwoMPIDomainMPI4Test::TwoByTwoMPIDomainMPI4Test(), and viscoElasticUnitTest::viscoElasticUnitTest().
setSoftStop()
void DPMBase::setSoftStop () private
function for setting sigaction constructor.
 {
     if (disableSoftStop_)
     {
         logger(INFO, "Soft stop disabled.");
         return;
     }
     struct sigaction act{};
     memset(&act, 0, sizeof(act));
     act.sa_handler = &signalHandler;
     sigaction(SIGINT, &act, nullptr);
     sigaction(SIGTERM, &act, nullptr);
     logger(VERBOSE, "Soft stop enabled.");
 }
References disableSoftStop_, INFO, logger, signalHandler(), and VERBOSE.
Referenced by solve().
setSuperquadricParticlesWriteVTK()
void DPMBase::setSuperquadricParticlesWriteVTK (bool writeParticlesVTK)
Parameters
[in] writeParticlesVTK
 {
 writeSuperquadricParticlesVTK_ = writeParticlesVTK;
 if (writeSuperquadricParticlesVTK_)
 {
 writeParticlesVTK_ = false;
 }
 delete vtkWriter_;
 vtkWriter_ = new SuperQuadricParticleVtkWriter(particleHandler);
 }
References particleHandler, vtkWriter_, writeParticlesVTK_, and writeSuperquadricParticlesVTK_.
Referenced by BouncingSuperQuadric::test().
setSystemDimensions()
void DPMBase::setSystemDimensions (unsigned int newDim)
Sets the system dimensionality.
Sets the dimensionality of the system. (Note that particles
may possess a different dimensionality.)
A sanity check is performed to ensure that the dimensionality is 1, 2 or 3. If not, an error message is logged and the simulation terminates.
Parameters
[in] newDim The desired dimensionality of the system: 1 → 1D, 2 → 2D, 3 → 3D.
 {
     if (newDim >= 1 && newDim <= 3)
         systemDimensions_ = newDim;
     else
     {
         logger(ERROR, "Error in setSystemDimensions; newDim % is not 1, 2 or 3", newDim);
     }
 }
References ERROR, logger, and systemDimensions_.
Referenced by constructor(), Mercury2D::constructor(), Mercury3D::constructor(), loadingTest(), main(), normalAndTangentialLoadingTest(), objectivenessTest(), readNextArgument(), setDimension(), StressStrainControl::setupInitialConditions(), DistributionToPSDSelfTest::setupInitialConditions(), InsertionBoundarySelfTest::setupInitialConditions(), MultiplePSDSelfTest::setupInitialConditions(), PolydisperseInsertionBoundarySelfTest::setupInitialConditions(), PSDManualInsertionSelfTest::setupInitialConditions(), ParticleParticleCollision::setupInitialConditions(), WallParticleCollision::setupInitialConditions(), DPM::setupInitialConditions(), SimpleOpt::setupInitialConditions(), GranularCollapse::setupInitialConditions(), ParticleParticleInteraction::setupInitialConditions(), ParticleParticleInteractionWithPlasticForces::setupInitialConditions(), ParticleWallInteraction::setupInitialConditions(), ChargedBondedParticleUnitTest::setupInitialConditions(), PSDSelfTest::setupInitialConditions(), RandomClusterInsertionBoundarySelfTest::setupInitialConditions(), MovingIntersectionOfWallsUnitTest_Basic::setupInitialConditions(), MovingWall::setupInitialConditions(), SeparateFilesSelfTest::setupInitialConditions(), TangentialSpringUnitTest::setupInitialConditions(), WallSpecies::setupInitialConditions(), MercuryProblem::setupMercuryProblem(), Siegen::Siegen(), and T_protectiveWall::T_protectiveWall().
setTime()
void DPMBase::setTime (Mdouble time)
Sets a new value for the current simulation time.
This may be useful in codes where some initial set-up is required e.g. if a system of particles is first prepared and then exposed to excitation. In this situation, getNumberOfTimeSteps() may be used to reset the time to zero at the point at which excitation begins to be applied.
Parameters
[in] time
 {
 Mdouble diff = time_ - time;
 time_ = time;
 //this sets the interaction timestamp, so each interaction has the right time
 for (auto i: interactionHandler)
 {
 i->setTimeStamp(i->getTimeStamp() - diff);
 }
 }
References i, interactionHandler, and time_.
Referenced by Chutebelt::actionsAfterTimeStep(), DrumRot::actionsBeforeTimeStep(), constructor(), initialiseSolve(), main(), FileReader::read(), readParAndIniFiles(), RotatingDrumBidisperse::RotatingDrumBidisperse(), ClosedCSCStats::setupInitialConditions(), CSCRun::setupInitialConditions(), CSCStats::setupInitialConditions(), ChutePeriodic::setupInitialConditions(), Cstatic3D::setupInitialConditions(), OneParticleCoolingSelfTest::setupInitialConditions(), and SingleParticleIndenter::SingleParticleIndenter().
setTimeMax()
void DPMBase::setTimeMax (Mdouble newTMax)
Sets a new value for the maximum simulation duration.
A sanity check is performed to ensure that the new maximum simulation duration is nonnegative.
Parameters
[in] newTMmax
 {
 if (newTMax >= 0)
 {
 timeMax_ = newTMax;
 }
 else
 {
 logger(ERROR, "Error in setTimeMax, new timeMax=% is not positive", newTMax);
 }
 }
References ERROR, logger, and timeMax_.
Referenced by GranuHeap::actionsAfterTimeStep(), ShearStage::actionsAfterTimeStep(), SphericalIndenter::actionsAfterTimeStep(), BaseCluster::actionsAfterTimeStep(), LawinenBox::actionsBeforeTimeStep(), ChuteRestartDemo::actionsOnRestart(), AngleOfRepose::AngleOfRepose(), AxisymmetricWallSelfTest::AxisymmetricWallSelfTest(), BoundariesSelfTest::BoundariesSelfTest(), ChutePeriodicDemo::ChutePeriodicDemo(), ClosedCSCStats::ClosedCSCStats(), ClosedCSCWalls::ClosedCSCWalls(), commandLineCG(), constructor(), Contact::Contact(), CSCStats::CSCStats(), CSCWalls::CSCWalls(), DPM::DPM(), FluxAndPeriodicBoundarySelfTest::FluxAndPeriodicBoundarySelfTest(), FluxBoundarySelfTest::FluxBoundarySelfTest(), ForceLawsMPI2Test::ForceLawsMPI2Test(), GranuDrum::GranuDrum(), GranuHeap::GranuHeap(), Hertzian2DUnitTest::Hertzian2DUnitTest(), InitialConditions< SpeciesType >::InitialConditions(), InsertionBoundaryMPI2Test::InsertionBoundaryMPI2Test(), LaserOnLayer::LaserOnLayer(), LeesEdwardsDemo::LeesEdwardsDemo(), LeesEdwardsSelfTest::LeesEdwardsSelfTest(), LiquidMigrationMPI2Test::LiquidMigrationMPI2Test(), load(), loadingTest(), main(), ChuteBottom::makeRoughBottom(), MaserRepeatedOutInMPI2Test::MaserRepeatedOutInMPI2Test(), MercuryCGSelfTest::MercuryCGSelfTest(), MinimalExampleDrum::MinimalExampleDrum(), normalAndTangentialLoadingTest(), objectivenessTest(), ParticleBeam::ParticleBeam(), ParticleCreation::ParticleCreation(), ParticleInclusion::ParticleInclusion(), readNextArgument(), readParAndIniFiles(), regimeForceUnitTest::regimeForceUnitTest(), RotatingDrumBidisperse::RotatingDrumBidisperse(), RotatingDrumBidisperseInitialise::RotatingDrumBidisperseInitialise(), FlowRule::run(), statistics_while_running< T >::run(), runFreeFall(), ChutePeriodic::setup(), ChuteWithContraction::setup_particles_initial_conditions(), ClosedCSCStats::setupInitialConditions(), CSCRun::setupInitialConditions(), CSCStats::setupInitialConditions(), CFDDEMCoupleTest::setupInitialConditions(), NozzleDemo::setupInitialConditions(), RotatingDrumWet::setupInitialConditions(), Chain::setupInitialConditions(), ShiftingConstantMassFlowMaserBoundarySelfTest::setupInitialConditions(), ShiftingMaserBoundarySelfTest::setupInitialConditions(), ChutePeriodic::setupInitialConditions(), Cstatic3D::setupInitialConditions(), InitialBed::setupInitialConditions(), MeltableForceLaw2SelfTest::setupInitialConditions(), MeltableForceLawSelfTest::setupInitialConditions(), OneParticleHeatingSelfTest::setupInitialConditions(), OneParticleCoolingSelfTest::setupInitialConditions(), ThermalConductionSelfTest::setupInitialConditions(), GetDistanceAndNormalForIntersectionOfWalls::setupInitialConditions(), GetDistanceAndNormalForScrew::setupInitialConditions(), GetDistanceAndNormalForTriangleWall::setupInitialConditions(), Drum::setupInitialConditions(), HertzSelfTest::setupInitialConditions(), MindlinSelfTest::setupInitialConditions(), Penetration::setupInitialConditions(), Silo::setupInitialConditions(), ConstantMassFlowMaserBoundaryMixedSpeciesSelfTest::setupInitialConditions(), ConstantMassFlowMaserSelfTest::setupInitialConditions(), CubeDeletionBoundarySelfTest::setupInitialConditions(), DeletionBoundarySelfTest::setupInitialConditions(), DistributionPhiNormalSelfTest::setupInitialConditions(), DistributionSelfTest::setupInitialConditions(), DistributionToPSDSelfTest::setupInitialConditions(), InsertionBoundarySelfTest::setupInitialConditions(), MultiplePSDSelfTest::setupInitialConditions(), NozzleSelfTest::setupInitialConditions(), PolydisperseInsertionBoundarySelfTest::setupInitialConditions(), PSDManualInsertionSelfTest::setupInitialConditions(), SubcriticalMaserBoundarySelfTest::setupInitialConditions(), CGStaticBalanceSelfTest::setupInitialConditions(), ChargedBondedInteractionSelfTest::setupInitialConditions(), ParticleParticleCollision::setupInitialConditions(), WallParticleCollision::setupInitialConditions(), FreeFallSelfTest::setupInitialConditions(), DPM::setupInitialConditions(), ObliqueImpactSelfTest::setupInitialConditions(), TwoParticleCollisionInteraction::setupInitialConditions(), ContactDetectionIntersectionOfWallsTest::setupInitialConditions(), GetDistanceAndNormalForTriangleWalls::setupInitialConditions(), RollingOverTriangleWalls::setupInitialConditions(), UnionOfWalls::setupInitialConditions(), SimpleOpt::setupInitialConditions(), SingleParticle< SpeciesType >::setupInitialConditions(), BouncingSuperQuadric::setupInitialConditions(), EllipsoidsBouncingOnWallDemo::setupInitialConditions(), EllipticalSuperQuadricCollision::setupInitialConditions(), SlidingSpheresUnitTest::setupInitialConditions(), SphericalSuperQuadricCollision::setupInitialConditions(), ContactDetectionNormalSpheresTest::setupInitialConditions(), ContactDetectionRotatedSpheresTest::setupInitialConditions(), ShapesDemo::setupInitialConditions(), VisualisationTest::setupInitialConditions(), ParticleParticleInteraction::setupInitialConditions(), ParticleParticleInteractionWithPlasticForces::setupInitialConditions(), ParticleWallInteraction::setupInitialConditions(), ArcWallUnitTest::setupInitialConditions(), Packing::setupInitialConditions(), CreateDataAndFStatFiles::setupInitialConditions(), PSDSelfTest::setupInitialConditions(), DrivenParticleClass::setupInitialConditions(), EvaporationAndHeatTest::setupInitialConditions(), RandomClusterInsertionBoundarySelfTest::setupInitialConditions(), HeatTransferUnitTest::setupInitialConditions(), HertzContactRestitutionUnitTest::setupInitialConditions(), HertzianSinterForceUnitTest::setupInitialConditions(), LongHertzianSinterForceUnitTest::setupInitialConditions(), MovingIntersectionOfWallsUnitTest_Basic::setupInitialConditions(), MovingWalls::setupInitialConditions(), MovingWall::setupInitialConditions(), PeriodicWallsWithSlidingFrictionUnitTest::setupInitialConditions(), PlasticForceUnitTest::setupInitialConditions(), SaveCountUnitTest::setupInitialConditions(), SeparateFilesSelfTest::setupInitialConditions(), SetDistributionPhiNormalSelfTest::setupInitialConditions(), SpeciesTest::setupInitialConditions(), WallSpecies::setupInitialConditions(), AreaVTK::setupInitialConditions(), BaseCluster::setupInitialConditions(), MercuryProblem::setupMercuryProblem(), SilbertHstop::SilbertHstop(), SilbertPeriodic::SilbertPeriodic(), SingleParticle< SpeciesType >::SingleParticle(), SingleParticleSegregation::SingleParticleSegregation(), SinterPair::SinterPair(), Slide::Slide(), SilbertHstop::solve_analytic(), statistics_while_running< T >::statistics_while_running(), SubcriticalMaserBoundaryTESTMPI2Test::SubcriticalMaserBoundaryTESTMPI2Test(), TangentialSpringEnergyConservationUnitTest::TangentialSpringEnergyConservationUnitTest(), TimeDependentPeriodicBoundary3DSelfTest::TimeDependentPeriodicBoundary3DSelfTest(), TimeDependentPeriodicBoundaryTest::TimeDependentPeriodicBoundaryTest(), TriangulatedScrewSelfTest::TriangulatedScrewSelfTest(), TriangulatedStepSelfTest::TriangulatedStepSelfTest(), TriangulatedStepWallSelfTest::TriangulatedStepWallSelfTest(), TriangulatedWallSelfTest::TriangulatedWallSelfTest(), TwoByTwoMPIDomainMPI4Test::TwoByTwoMPIDomainMPI4Test(), viscoElasticUnitTest::viscoElasticUnitTest(), Wall::Wall(), ClosedCSCRestart::writeOutputFiles(), and CSCRestart::writeOutputFiles().
setTimeStep()
void DPMBase::setTimeStep (Mdouble timeStep)
Sets a new value for the simulation time step.
A sanity check is performed to ensure that the time step must be positive.
Parameters
[in] timeStep The (Mdouble) value of the desired new time step
 {
 if (timeStep > 0.0)
 {
 timeStep_ = timeStep;
 }
 else
 {
 logger(ERROR, "Error in setTimeStep: new timeStep % is not positive", timeStep);
 }
 }
References ERROR, logger, and timeStep_.
Referenced by RotatingDrumBidisperseInitialise::actionsAfterTimeStep(), NautaMixer::addSpeciesAndSetTimeStepAndSaveCount(), AngledPeriodicBoundarySecondUnitTest::AngledPeriodicBoundarySecondUnitTest(), AngledPeriodicBoundaryUnitTest::AngledPeriodicBoundaryUnitTest(), AngleOfRepose::AngleOfRepose(), BouncingSuperQuadric::BouncingSuperQuadric(), BoundariesSelfTest::BoundariesSelfTest(), BaseCluster::calculateTimeStep(), CGBasicSelfTest::CGBasicSelfTest(), ChutePeriodicDemo::ChutePeriodicDemo(), ClosedCSCWalls::ClosedCSCWalls(), Contact::Contact(), CSCWalls::CSCWalls(), DPM::DPM(), FluxAndPeriodicBoundarySelfTest::FluxAndPeriodicBoundarySelfTest(), FluxBoundarySelfTest::FluxBoundarySelfTest(), ForceLawsMPI2Test::ForceLawsMPI2Test(), Hertzian2DUnitTest::Hertzian2DUnitTest(), InsertionBoundaryMPI2Test::InsertionBoundaryMPI2Test(), LawinenBox::LawinenBox(), LeesEdwardsDemo::LeesEdwardsDemo(), LeesEdwardsSelfTest::LeesEdwardsSelfTest(), LiquidMigrationMPI2Test::LiquidMigrationMPI2Test(), load(), loadingTest(), main(), ChuteBottom::makeRoughBottom(), MaserRepeatedOutInMPI2Test::MaserRepeatedOutInMPI2Test(), MercuryCGSelfTest::MercuryCGSelfTest(), MinimalExampleDrum::MinimalExampleDrum(), normalAndTangentialLoadingTest(), objectivenessTest(), ParticleBeam::ParticleBeam(), ParticleCreation::ParticleCreation(), ParticleInclusion::ParticleInclusion(), readNextArgument(), readParAndIniFiles(), regimeForceUnitTest::regimeForceUnitTest(), RotatingDrumBidisperseInitialise::RotatingDrumBidisperseInitialise(), runFreeFall(), Cstatic2d::set_particle_properties(), Cstatic3D::set_particle_properties(), Calibration::setSpecies(), Material::setSpecies(), AxisymmetricWallSelfTest::setSpeciesAndTimeStep(), MercuryProblem::setSpeciesProperties(), ChutePeriodic::setup(), CFDDEMCoupleTest::setupInitialConditions(), NozzleDemo::setupInitialConditions(), RotatingDrumWet::setupInitialConditions(), Chain::setupInitialConditions(), MarbleRun::setupInitialConditions(), StressStrainControl::setupInitialConditions(), ShiftingConstantMassFlowMaserBoundarySelfTest::setupInitialConditions(), ShiftingMaserBoundarySelfTest::setupInitialConditions(), FiveParticles::setupInitialConditions(), InitialBed::setupInitialConditions(), MeltableForceLaw2SelfTest::setupInitialConditions(), MeltableForceLawSelfTest::setupInitialConditions(), OneParticleHeatingSelfTest::setupInitialConditions(), ThermalConductionSelfTest::setupInitialConditions(), GetDistanceAndNormalForIntersectionOfWalls::setupInitialConditions(), GetDistanceAndNormalForScrew::setupInitialConditions(), GetDistanceAndNormalForTriangleWall::setupInitialConditions(), Drum::setupInitialConditions(), HertzSelfTest::setupInitialConditions(), MindlinSelfTest::setupInitialConditions(), Penetration::setupInitialConditions(), Silo::setupInitialConditions(), ConstantMassFlowMaserBoundaryMixedSpeciesSelfTest::setupInitialConditions(), ConstantMassFlowMaserSelfTest::setupInitialConditions(), CubeDeletionBoundarySelfTest::setupInitialConditions(), DeletionBoundarySelfTest::setupInitialConditions(), DistributionPhiNormalSelfTest::setupInitialConditions(), DistributionSelfTest::setupInitialConditions(), DistributionToPSDSelfTest::setupInitialConditions(), InsertionBoundarySelfTest::setupInitialConditions(), MultiplePSDSelfTest::setupInitialConditions(), NozzleSelfTest::setupInitialConditions(), PolydisperseInsertionBoundarySelfTest::setupInitialConditions(), PSDManualInsertionSelfTest::setupInitialConditions(), SubcriticalMaserBoundarySelfTest::setupInitialConditions(), CGHandlerSelfTest::setupInitialConditions(), CGStaticBalanceSelfTest::setupInitialConditions(), DPM::setupInitialConditions(), ChargedBondedInteractionSelfTest::setupInitialConditions(), ParticleParticleCollision::setupInitialConditions(), WallParticleCollision::setupInitialConditions(), TwoParticleCollisionInteraction::setupInitialConditions(), ContactDetectionIntersectionOfWallsTest::setupInitialConditions(), GetDistanceAndNormalForTriangleWalls::setupInitialConditions(), RollingOverTriangleWalls::setupInitialConditions(), UnionOfWalls::setupInitialConditions(), SingleParticle< SpeciesType >::setupInitialConditions(), InitialConditions< SpeciesType >::setupInitialConditions(), EllipsoidsBouncingOnWallDemo::setupInitialConditions(), EllipticalSuperQuadricCollision::setupInitialConditions(), SlidingSpheresUnitTest::setupInitialConditions(), SphericalSuperQuadricCollision::setupInitialConditions(), ContactDetectionNormalSpheresTest::setupInitialConditions(), ContactDetectionRotatedSpheresTest::setupInitialConditions(), ShapesDemo::setupInitialConditions(), VisualisationTest::setupInitialConditions(), ParticleParticleInteraction::setupInitialConditions(), ParticleParticleInteractionWithPlasticForces::setupInitialConditions(), ParticleWallInteraction::setupInitialConditions(), ArcWallUnitTest::setupInitialConditions(), Packing::setupInitialConditions(), CreateDataAndFStatFiles::setupInitialConditions(), PSDSelfTest::setupInitialConditions(), DrivenParticleClass::setupInitialConditions(), EvaporationAndHeatTest::setupInitialConditions(), RandomClusterInsertionBoundarySelfTest::setupInitialConditions(), HeatTransferUnitTest::setupInitialConditions(), HertzContactRestitutionUnitTest::setupInitialConditions(), HertzianSinterForceUnitTest::setupInitialConditions(), MovingIntersectionOfWallsUnitTest_Basic::setupInitialConditions(), MovingWalls::setupInitialConditions(), MovingWall::setupInitialConditions(), PeriodicWallsWithSlidingFrictionUnitTest::setupInitialConditions(), PlasticForceUnitTest::setupInitialConditions(), SaveCountUnitTest::setupInitialConditions(), SeparateFilesSelfTest::setupInitialConditions(), SetDistributionPhiNormalSelfTest::setupInitialConditions(), SpeciesTest::setupInitialConditions(), WallSpecies::setupInitialConditions(), AreaVTK::setupInitialConditions(), Siegen::Siegen(), SilbertPeriodic::SilbertPeriodic(), SingleParticleSegregation::SingleParticleSegregation(), SinterPair::SinterPair(), SubcriticalMaserBoundaryTESTMPI2Test::SubcriticalMaserBoundaryTESTMPI2Test(), T_protectiveWall::T_protectiveWall(), TangentialSpringEnergyConservationUnitTest::TangentialSpringEnergyConservationUnitTest(), TimeDependentPeriodicBoundary3DSelfTest::TimeDependentPeriodicBoundary3DSelfTest(), TimeDependentPeriodicBoundaryTest::TimeDependentPeriodicBoundaryTest(), TriangulatedScrewSelfTest::TriangulatedScrewSelfTest(), TriangulatedStepSelfTest::TriangulatedStepSelfTest(), TriangulatedStepWallSelfTest::TriangulatedStepWallSelfTest(), TriangulatedWallSelfTest::TriangulatedWallSelfTest(), TwoByTwoMPIDomainMPI4Test::TwoByTwoMPIDomainMPI4Test(), viscoElasticUnitTest::viscoElasticUnitTest(), and Wall::Wall().
setupInitialConditions()
void DPMBase::setupInitialConditions () virtual
This function allows to set the initial conditions for our problem to be solved, by default particle locations are randomly set. Remember particle properties must also be defined here.
A virtual function with no implementation but can be overridden.
Todo:
I (Anthony) wants to change this to be an external function. This has a lot of advantages especially when using copy-constructors. This is a major change and will break other codes, so therefore has to be done carefully.
This sets up the particles initial conditions it is as you expect the user to override this. By default the particles are randomly distributed
Reimplemented in ChuteWithHopper, ChuteBottom, Chute, BaseCluster, AreaVTK, WallSpecies, TangentialSpringUnitTest, TangentialSpringEnergyConservationUnitTest, PSDSelfTest, SpeciesTest, SinterForceUnitTest, SetDistributionPhiNormalSelfTest, SeparateFilesSelfTest, SaveCountUnitTest, my_problem_HGRID, my_problem, RandomClusterInsertionBoundarySelfTest, PlasticForceUnitTest, PeriodicWallsWithSlidingFrictionUnitTest, PeriodicWalls, MpiPeriodicBoundaryUnitTest, MpiPeriodicBoundaryUnitTest, MpiPeriodicBoundaryUnitTest, MultiParticlesInsertion, MovingWallTangentialPrescribedPositionPrescribedVelocity, MovingWallTangentialPrescribedVelocity, MovingWallTangentialPrescribedPosition, MovingWallTangentialSimpleIntegration, MovingWallTangentialReference, MovingWallTangential, MovingWallPrescribedPositionPrescribedVelocity, MovingWallPrescribedVelocity, MovingWallPrescribedPosition, MovingWallSimpleIntegration, MovingWallReference, MovingWall, MovingWalls, MovingIntersectionOfWallsUnitTest_MovingReferenceFrame, MovingIntersectionOfWallsUnitTest_Basic, MpiMaserChuteTest, InclinedPlane, MD_demo, LongHertzianSinterForceUnitTest, HertzianSinterForceUnitTest, HertzContactRestitutionUnitTest, HeatTransferUnitTest, my_problem, FullRestartTest, FreeFall, FreeFall, FreeFallHertzMindlinUnitTest, FluxBoundaryUnitTest, FluxBoundaryPrescribedDistanceUnitTest, RandomClusterInsertionBoundarySelfTest, ExtremeOverlapWithWallsUnitTest, EvaporationAndHeatTest, EnergyUnitTest, DrivenParticleClass, PSDSelfTest, ConsistencyInitialParticleWallOverlapUnitTest, ChargedBondedParticleUnitTest, CreateDataAndFStatFiles, ParticleWall, TwoParticles, Packing, TwoParticles, CGForceDensityUnitTest, CGExactOverlapUnitTest, CGDisplacementFieldUnitTest, Packing, ArcWallUnitTest, AngledPeriodicBoundaryUnitTest, AngledPeriodicBoundarySecondUnitTest, ParticleWallInteraction, ParticleParticleInteractionWithPlasticForces, ParticleParticleInteraction, Tutorial9, Tutorial8, Tutorial7, Tutorial6, Tutorial5, Tutorial4, Tutorial3, Tutorial2, Tutorial1, Tutorial12, Tutorial11, DPM, protectiveWall, MercuryProblem, MyProblem, VisualisationTest, ShapesDemo, ContactDetectionRotatedSpheresTest, ContactDetectionNormalSpheresTest, SphericalSuperQuadricCollision, SlidingSpheresUnitTest, EllipticalSuperQuadricCollision, GranularCollapse, EllipticalSuperQuadricCollision, EllipsoidsBouncingOnWallDemo, BouncingSuperQuadric, Wall, Contact, ScalingTestRun, ScalingTestInitialConditionsRelax, ScalingTestRun, ScalingTestInitialConditionsRelax, SphericalIndenter, InitialConditions< SpeciesType >, SingleParticle< SpeciesType >, SimpleOpt, RotatingDrum, DrumRot, UnionOfWalls, TriangulatedWallSelfTest, TriangulatedStepWallSelfTest, TriangulatedStepSelfTest, TriangulatedScrewSelfTest, RollingOverTriangleWalls, MembraneSelfTest, GetDistanceAndNormalForTriangleWalls, ContactDetectionIntersectionOfWallsTest, CoilSelfTest, AxisymmetricWallSelfTest, TwoParticleElasticCollision, TwoParticleElasticCollisionInteraction, TwoParticleElasticCollisionInteraction, TwoParticleCollisionInteraction, TwoParticleClassicalWilletCollision, TwoParticleBagheriCollision, TwoBondedParticleElasticCollision, ObliqueImpactSelfTest, DPM, LiquidMigrationSelfTest, HertzianBSHPInteractionTwoParticleElasticCollision, FreeFallSelfTest, FreeFallInteractionSelfTest, my_problem_HGRID, WallParticleCollision, ParticleParticleCollision, ChargedBondedParticleUnitTest, ChargedBondedInteractionSelfTest, ParticleCreation, DPM, SquarePacking, NewtonsCradleSelfTest, NewtonsCradleSelftest, CGStaticBalanceSelfTest, CGHandlerSelfTest, CGHandlerSelfTest, CGHandlerSelfTest, CGBasicSelfTest, PSDSelfTest, PSDSelfTest, SubcriticalMaserBoundarySelfTest, StressStrainControl, PSDSelfTest, PSDManualInsertionSelfTest, PolydisperseInsertionBoundarySelfTest, clumpTest, NozzleSelfTest, MultiplePSDSelfTest, InsertionBoundarySelfTest, InsertionBoundarySelfTest, DistributionToPSDSelfTest, DistributionSelfTest, DistributionPhiNormalSelfTest, DeletionBoundarySelfTest, CubeDeletionBoundarySelfTest, ConstantMassFlowMaserSelfTest, ConstantMassFlowMaserBoundaryMixedSpeciesSelfTest, SingleParticleSegregation, Chutebelt, SegregationPeriodic, SegregationPeriodic, SegregationPeriodic, RotatingDrum, RotatingDrum, Siegen, SegregationPeriodic, Silo, Penetration, MindlinSelfTest, HertzSelfTest, Drum, Silo, Polygon, Nurbs, MyCoil, GetDistanceAndNormalForTriangleWall, GetDistanceAndNormalForScrew, GetDistanceAndNormalForIntersectionOfWalls, ThermalConductionSelfTest, OneParticleCoolingSelfTest, OneParticleHeatingSelfTest, MeltableForceLawSelfTest, MeltableForceLaw2SelfTest, InitialBed, statistics_while_running< T >, SilbertPeriodic, Mercury3DRestart, statistics_while_running< T >, statistics_while_running< T >, statistics_while_running< T >, SilbertPeriodic, CLiveStatistics< T >, inflowFromPeriodic, SilbertPeriodic, Restart, AngleOfRepose, CLiveStatistics< T >, SilbertPeriodic, SilbertPeriodic, AngleOfRepose, statistics_while_running< T >, statistics_while_running< T >, Cstatic3D, Cstatic2d, Cstatic2d, ChutePeriodic, FiveParticles, TimeDependentPeriodicBoundaryTest, TimeDependentPeriodicBoundary3DSelfTest, ShiftingMaserBoundarySelfTest, ShiftingConstantMassFlowMaserBoundarySelfTest, StressStrainControl, StressStrainControl, StressStrainControl, ParameterStudy3DDemo, ParameterStudy2DDemo, ParameterStudy1DDemo, MinimalExampleDrum, MarbleRun, MarbleRun, LeesEdwardsDemo, HourGlass, HourGlass2D, HourGlass2D, HeaterBoundaryTest, FreeCoolingDemoProblem, FreeCooling3DinWallsDemo, FreeCooling3DDemoProblem, FreeCooling2DinWallsDemo, FreeCooling2DinWalls, CubicCell, TwoByTwoMPIDomainMPI4Test, SubcriticalMaserBoundaryTESTMPI2Test, PeriodicBounaryEnteringMPIDomainTest, MpiPeriodicBoundaryUnitTest, MaserRepeatedOutInMPI2Test, LiquidMigrationMPI2Test, InsertionBoundaryMPI2Test, ForceLawsMPI2Test, Mercury3DRestart, Chain, Chain, my_problem, my_problem, my_problem, Binary, Funnel, ChuteWithVerticalHopper, MembraneDemo, VerticalMixer, NozzleDemo, RotatingDrumWet, Drum, NozzleDemo, NautaMixer, HorizontalMixerWalls, HorizontalMixer, CFDDEMCoupleTest, ChuteWithPeriodicInflow, restart, free_cooling, my_problem, my_problem, RandomClusterInsertionBoundarySelfTest, ChangingTOIParticle, ChangingTOIParticle, ChangingTOIParticle, ChangingTOIParticle, ChangingTOIParticle, ChangingTOIParticle, ChangingTOIParticle, ChangingTOIParticle, SmoothChute, SmoothChute, MercuryLogo, ChuteWithWedge, ChutePeriodicDemo, AxisymmetricHopper, AirySavageHutter, Vreman, Vreman, Vreman, VariableBottom, VariableBottom, ChutePeriodic, SegregationPeriodic, ChuteRestart, VariableBottom, ChutePeriodic, ChutePeriodic, ChutePeriodic, ChutePeriodic, CSCWalls, CSCStats, CSCRun, CSCInit, ClosedCSCWalls, ClosedCSCStats, ClosedCSCRun, LawinenBox, LawinenBox, LawinenBox, T_protectiveWall, ExtremeOverlapVolumeUnitTest, and ExtremeOverlapUnitTest.
 {
 }
Referenced by initialiseSolve(), loadingTest(), normalAndTangentialLoadingTest(), and objectivenessTest().
setVTKOutputDirectory()
void DPMBase::setVTKOutputDirectory (const std::string & dir)
Sets the output directory of the VTK files.
 {
     if (vtkWriter_)
         vtkWriter_->setOutputDirectory(dir);
     else
         logger(WARN, "Failed to set VTK output directory for particles. Make sure to set particle VTK writing to true, "
                      "before setting the output directory.");
     boundaryVTKWriter_.setOutputDirectory(dir);
     interactionVTKWriter_.setOutputDirectory(dir);
     wallVTKWriter_.setOutputDirectory(dir);
     wallDetailsVTKWriter_.setOutputDirectory(dir);
 }
References boundaryVTKWriter_, interactionVTKWriter_, logger, BaseVTKWriter< H >::setOutputDirectory(), vtkWriter_, wallDetailsVTKWriter_, wallVTKWriter_, and WARN.
setWallsWriteVTK() [1/2]
void DPMBase::setWallsWriteVTK (bool writeVTK)
Sets whether walls are written into a VTK file.
Deprecated:
Use wallHandler.setWriteVTK(bool) instead (since 21-07-2021)
The VTK file is used for visualisation in Paraview.
Todo:
Move this (and the get) to WallHandler.
Parameters
[in] writeWallsVTK
 {
     FileType writeVTKFileType = writeVTK?FileType::MULTIPLE_FILES:FileType::NO_FILE;
     logger(WARN, "DPMBase.setWallsWriteVTK(bool) is deprecated! Use wallHandler.setWriteVTK(bool) instead.");
     wallHandler.setWriteVTK(writeVTKFileType);
 }
References logger, MULTIPLE_FILES, NO_FILE, WallHandler::setWriteVTK(), wallHandler, and WARN.
setWallsWriteVTK() [2/2]
void DPMBase::setWallsWriteVTK (FileType writeWallsVTK)
Sets whether walls are written into a VTK file.
Deprecated:
Use wallHandler.setWriteVTK(FileType) instead (since 21-07-2021)
Uses the preprocessor directive ifdef to check if there exists a CONTACT_LIST_HGRID, before any code is compiled. If CONTACT_LIST_HGRID does exist, this function can be used to return the "possibleContactsList" - but not to alter it.
The VTK file is used for visualisation in Paraview.
Todo:
Move this (and the get) to WallHandler.
Parameters
[in] writeWallsVTK
 {
     logger(WARN, "DPMBase.setWallsWriteVTK(FileType) is deprecated! Use wallHandler.setWriteVTK(FileType) instead.");
     wallHandler.setWriteVTK(writeWallsVTK);
 }
References logger, WallHandler::setWriteVTK(), wallHandler, and WARN.
setWritePythonFileForVTKVisualisation()
void DPMBase::setWritePythonFileForVTKVisualisation (bool forceWritePythonFileForVTKVisualisation)
Todo:
When restarting the indexMax should be reset
Enables/disables the writePythonFileForVTKVisualisation() function.
Parameters
[in] forceWritePythonFileForVTKVisualisation
 {
     forceWritePythonFileForVTKVisualisation_ = forceWritePythonFileForVTKVisualisation;
 }
References forceWritePythonFileForVTKVisualisation_.
Referenced by AreaVTK::setupInitialConditions().
setXBallsAdditionalArguments()
void DPMBase::setXBallsAdditionalArguments (std::string xBallsAdditionalArguments)
Set the additional arguments for xballs.
Used to set, from the driver code itself, arguments to control the visualisation of the simulation run using xballs. All arguments can be passed as a single string, for example:
setXBallsAdditionalArguments("-cmode 8 -solidf");
will set the colour mode (cmode) to 8 (colour dependent on species) and draw particles with solid lines (solidf)
Parameters
[in] newXBArgs
 {
     xBallsAdditionalArguments_ = xBallsAdditionalArguments;
 }
References xBallsAdditionalArguments_.
Referenced by BaseCluster::actionsOnRestart(), BoundariesSelfTest::BoundariesSelfTest(), ChangingTOIParticle::ChangingTOIParticle(), ClosedCSCRun::ClosedCSCRun(), ClosedCSCWalls::ClosedCSCWalls(), clumpTest::clumpTest(), CSCInit::CSCInit(), CSCWalls::CSCWalls(), DPM::DPM(), FluxAndPeriodicBoundarySelfTest::FluxAndPeriodicBoundarySelfTest(), FluxBoundarySelfTest::FluxBoundarySelfTest(), ForceLawsMPI2Test::ForceLawsMPI2Test(), InitialConditions< SpeciesType >::InitialConditions(), LawinenBox::LawinenBox(), LiquidMigrationMPI2Test::LiquidMigrationMPI2Test(), main(), MultiParticlesInsertion::MultiParticlesInsertion(), read(), RotatingDrumBidisperse::RotatingDrumBidisperse(), Calibration::setOutput(), CSCRun::setupInitialConditions(), GetDistanceAndNormalForIntersectionOfWalls::setupInitialConditions(), GetDistanceAndNormalForScrew::setupInitialConditions(), GetDistanceAndNormalForTriangleWall::setupInitialConditions(), DPM::setupInitialConditions(), ContactDetectionIntersectionOfWallsTest::setupInitialConditions(), GetDistanceAndNormalForTriangleWalls::setupInitialConditions(), UnionOfWalls::setupInitialConditions(), RandomClusterInsertionBoundarySelfTest::setupInitialConditions(), BaseCluster::setupInitialConditions(), ShearStage::ShearStage(), SingleParticle< SpeciesType >::SingleParticle(), TriangulatedScrewSelfTest::TriangulatedScrewSelfTest(), TriangulatedStepSelfTest::TriangulatedStepSelfTest(), TriangulatedStepWallSelfTest::TriangulatedStepWallSelfTest(), TriangulatedWallSelfTest::TriangulatedWallSelfTest(), Tutorial11::Tutorial11(), and TwoByTwoMPIDomainMPI4Test::TwoByTwoMPIDomainMPI4Test().
setXBallsColourMode()
void DPMBase::setXBallsColourMode (int newCMode)
Set the xballs output mode.
Allows the user to change the default "cmode" (colour mode) variable in MercuryDPM's built-in visualiser, "XBalls". cmode takes an integer value between 1 and 27 (1 and 14 for 2D problems); to each integer is assigned a different colour mode, which can be used to assign colours to individual particles based on a parameter such as the particles radius, velocity, rotational energy etc. etc. For further details, refer to the Visualising data in xballs
Parameters
[in] newCMode The numerical value corresponding to the colour mode (see Visualising data in xballs) you want to use when visually reconstructing Mercury simulations.
 {
     xBallsColourMode_ = newCMode;
 }
References xBallsColourMode_.
Referenced by ChutePeriodic::setup().
setXBallsScale()
void DPMBase::setXBallsScale (Mdouble newScale)
Sets the scale of the view (either normal, zoom in or zoom out) to display in xballs. The default is fit to screen.
Parameters
[in] newScale The desired new scaling or "zoom". Values > 1 act to "zoom out", values < 1 act to "zoom in".
 {
     xBallsScale_ = newScale;
 }
References xBallsScale_.
setXBallsVectorScale()
void DPMBase::setXBallsVectorScale (double newVScale)
Set the scale of vectors in xballs.
Allows the user to choose the default vector scaling, i.e. the length of the vectors representing particle velocities in the XBalls visualisation software. Further details may be found in the Visualising data in xballs
Parameters
[in] newVScale The value of the desired vector length - a value of 100 sets the length to 1 particle radius, 1000 sets it to 10 particle radii etc.
 {
     xBallsVectorScale_ = newVScale;
 }
References xBallsVectorScale_.
Referenced by ChutePeriodic::setup().
setXMax()
void DPMBase::setXMax (Mdouble newXMax)
Sets the value of XMax, the upper bound of the problem domain in the x-direction.
Deprecated:
An access function which allows the user to alter the value of the (private) x value of the "Vec3D" object "max_", thus setting the maximum x-value corresponding to the system, i.e. the upper limit of the domain in the x-direction.
These bounds are used for display, plotting and statistics purposes. They do not affect the dynamics.
The function also performs a sanity check to stop the user defining an upper bound that is lower than the corresponding lower bound (XMin), giving a (logged) warning if the user attempts to do so.
Parameters
[in] newXMax
 {
 if (newXMax >= getXMin())
 {
 max_.x() = newXMax;
 }
 else
 {
 logger(WARN, "Warning in setXMax(%): xMax=%", newXMax, getXMin());
 }
 }
References getXMin(), logger, max_, WARN, and Vec3D::x().
Referenced by ChuteWithPeriodicInflow::AddContinuingBottom(), statistics_while_running< T >::auto_set_domain(), BoundariesSelfTest::BoundariesSelfTest(), ChangingTOIParticle::ChangingTOIParticle(), Funnel::check_funnel(), ChuteWithContraction::ChuteWithContraction(), ChuteWithPeriodicInflowAndContinuingBottom::ChuteWithPeriodicInflowAndContinuingBottom(), ChuteWithPeriodicInflowAndContraction::ChuteWithPeriodicInflowAndContraction(), ChuteWithPeriodicInflowAndVariableBottom::ChuteWithPeriodicInflowAndVariableBottom(), ClosedCSCWalls::ClosedCSCWalls(), clumpTest::clumpTest(), ContractionWithPeriodicInflow::ContractionWithPeriodicInflow(), CSCWalls::CSCWalls(), FluxAndPeriodicBoundarySelfTest::FluxAndPeriodicBoundarySelfTest(), FluxBoundarySelfTest::FluxBoundarySelfTest(), MarbleRun::includeInDomain(), inflowFromPeriodic::inflowFromPeriodic(), InitialConditions< SpeciesType >::InitialConditions(), LawinenBox::LawinenBox(), load(), main(), ParticleCreation::ParticleCreation(), protectiveWall::protectiveWall(), readNextArgument(), regimeForceUnitTest::regimeForceUnitTest(), Chute::setChuteLength(), ChuteWithHopper::setChuteLength(), ChuteWithHopper::setHopperShift(), ExtremeOverlapUnitTest::setupInitialConditions(), ExtremeOverlapVolumeUnitTest::setupInitialConditions(), SmoothChute::setupInitialConditions(), HorizontalMixer::setupInitialConditions(), MembraneDemo::setupInitialConditions(), Chain::setupInitialConditions(), FiveParticles::setupInitialConditions(), Cstatic2d::setupInitialConditions(), Cstatic3D::setupInitialConditions(), statistics_while_running< T >::setupInitialConditions(), ConstantMassFlowMaserBoundaryMixedSpeciesSelfTest::setupInitialConditions(), ConstantMassFlowMaserSelfTest::setupInitialConditions(), PolydisperseInsertionBoundarySelfTest::setupInitialConditions(), CGBasicSelfTest::setupInitialConditions(), CGHandlerSelfTest::setupInitialConditions(), CGStaticBalanceSelfTest::setupInitialConditions(), NewtonsCradleSelftest::setupInitialConditions(), NewtonsCradleSelfTest::setupInitialConditions(), ParticleParticleCollision::setupInitialConditions(), WallParticleCollision::setupInitialConditions(), TwoParticleElasticCollisionInteraction::setupInitialConditions(), MembraneSelfTest::setupInitialConditions(), SimpleOpt::setupInitialConditions(), ScalingTestInitialConditionsRelax::setupInitialConditions(), ScalingTestRun::setupInitialConditions(), Contact::setupInitialConditions(), GranularCollapse::setupInitialConditions(), ParticleParticleInteraction::setupInitialConditions(), ParticleParticleInteractionWithPlasticForces::setupInitialConditions(), ParticleWallInteraction::setupInitialConditions(), AngledPeriodicBoundarySecondUnitTest::setupInitialConditions(), ChargedBondedParticleUnitTest::setupInitialConditions(), DrivenParticleClass::setupInitialConditions(), EnergyUnitTest::setupInitialConditions(), ExtremeOverlapWithWallsUnitTest::setupInitialConditions(), HertzianSinterForceUnitTest::setupInitialConditions(), MD_demo::setupInitialConditions(), MovingIntersectionOfWallsUnitTest_Basic::setupInitialConditions(), MovingWall::setupInitialConditions(), PeriodicWallsWithSlidingFrictionUnitTest::setupInitialConditions(), PlasticForceUnitTest::setupInitialConditions(), SeparateFilesSelfTest::setupInitialConditions(), SinterForceUnitTest::setupInitialConditions(), SpeciesTest::setupInitialConditions(), TangentialSpringUnitTest::setupInitialConditions(), WallSpecies::setupInitialConditions(), MercuryProblem::setupMercuryProblem(), Siegen::Siegen(), SingleParticle< SpeciesType >::SingleParticle(), FlowFrontChute::stretch(), T_protectiveWall::T_protectiveWall(), Tutorial11::Tutorial11(), StressStrainControlBoundary::updateDomainSize(), and viscoElasticUnitTest::viscoElasticUnitTest().
setXMin()
void DPMBase::setXMin (Mdouble newXMin)
Sets the value of XMin, the lower bound of the problem domain in the x-direction.
Deprecated:
An access function which allows the user to alter the value of the (private) x value of the "Vec3D" object "min_", thus setting the minimum x-value corresponding to the system, i.e. the lower limit of the domain in the x-direction.
These bounds are used for display, plotting and statistics purposes. They do not affect the dynamics.
The function also performs a sanity check to stop the user defining a lower bound that is higher than the corresponding upper bound (XMax), giving a (logged) warning if the user attempts to do so.
Parameters
[in] newXMin
 {
 if (newXMin <= getXMax())
 {
 min_.x() = newXMin;
 }
 else
 {
 logger(WARN, "Warning in setXMin(%): xMax=%", newXMin, getXMax());
 }
 }
References getXMax(), logger, min_, WARN, and Vec3D::x().
Referenced by statistics_while_running< T >::auto_set_domain(), BoundariesSelfTest::BoundariesSelfTest(), ChangingTOIParticle::ChangingTOIParticle(), Funnel::check_funnel(), ClosedCSCWalls::ClosedCSCWalls(), clumpTest::clumpTest(), CSCWalls::CSCWalls(), FluxAndPeriodicBoundarySelfTest::FluxAndPeriodicBoundarySelfTest(), FluxBoundarySelfTest::FluxBoundarySelfTest(), MarbleRun::includeInDomain(), InitialConditions< SpeciesType >::InitialConditions(), load(), main(), ParticleCreation::ParticleCreation(), readNextArgument(), regimeForceUnitTest::regimeForceUnitTest(), ChuteWithHopper::setChuteLength(), ExtremeOverlapUnitTest::setupInitialConditions(), ExtremeOverlapVolumeUnitTest::setupInitialConditions(), SmoothChute::setupInitialConditions(), HorizontalMixer::setupInitialConditions(), MembraneDemo::setupInitialConditions(), Chain::setupInitialConditions(), FiveParticles::setupInitialConditions(), ConstantMassFlowMaserBoundaryMixedSpeciesSelfTest::setupInitialConditions(), ConstantMassFlowMaserSelfTest::setupInitialConditions(), PolydisperseInsertionBoundarySelfTest::setupInitialConditions(), CGBasicSelfTest::setupInitialConditions(), CGHandlerSelfTest::setupInitialConditions(), CGStaticBalanceSelfTest::setupInitialConditions(), NewtonsCradleSelftest::setupInitialConditions(), NewtonsCradleSelfTest::setupInitialConditions(), ChargedBondedParticleUnitTest::setupInitialConditions(), MembraneSelfTest::setupInitialConditions(), SimpleOpt::setupInitialConditions(), ScalingTestInitialConditionsRelax::setupInitialConditions(), Contact::setupInitialConditions(), GranularCollapse::setupInitialConditions(), ParticleParticleInteraction::setupInitialConditions(), ParticleParticleInteractionWithPlasticForces::setupInitialConditions(), ParticleWallInteraction::setupInitialConditions(), AngledPeriodicBoundarySecondUnitTest::setupInitialConditions(), EnergyUnitTest::setupInitialConditions(), ExtremeOverlapWithWallsUnitTest::setupInitialConditions(), MD_demo::setupInitialConditions(), MovingIntersectionOfWallsUnitTest_Basic::setupInitialConditions(), PeriodicWallsWithSlidingFrictionUnitTest::setupInitialConditions(), SinterForceUnitTest::setupInitialConditions(), MercuryProblem::setupMercuryProblem(), Siegen::Siegen(), SingleParticle< SpeciesType >::SingleParticle(), Tutorial11::Tutorial11(), StressStrainControlBoundary::updateDomainSize(), and viscoElasticUnitTest::viscoElasticUnitTest().
setYMax()
void DPMBase::setYMax (Mdouble newYMax)
Sets the value of YMax, the upper bound of the problem domain in the y-direction.
Deprecated:
An access function which allows the user to alter the value of the (private) y value of the "Vec3D" object "max_", thus setting the maximum y-value corresponding to the system, i.e. the upper limit of the domain in the y-direction.
These bounds are used for display, plotting and statistics purposes. They do not affect the dynamics.
The function also performs a sanity check to stop the user defining an upper bound that is lower than the corresponding lower bound (YMin), giving a (logged) warning if the user attempts to do so.
Parameters
[in] newYMax
 {
 if (newYMax >= getYMin())
 {
 max_.y() = newYMax;
 }
 else
 {
 logger(WARN, "Warning in setYMax(%): yMax=%", newYMax, getYMin());
 }
 }
References getYMin(), logger, max_, WARN, and Vec3D::y().
Referenced by statistics_while_running< T >::auto_set_domain(), BoundariesSelfTest::BoundariesSelfTest(), ChangingTOIParticle::ChangingTOIParticle(), Funnel::check_funnel(), ChuteWithContraction::ChuteWithContraction(), ChuteWithPeriodicInflowAndContraction::ChuteWithPeriodicInflowAndContraction(), ClosedCSCWalls::ClosedCSCWalls(), clumpTest::clumpTest(), ContractionWithPeriodicInflow::ContractionWithPeriodicInflow(), CSCWalls::CSCWalls(), ChuteWithPeriodicInflow::ExtendInWidth(), FluxAndPeriodicBoundarySelfTest::FluxAndPeriodicBoundarySelfTest(), FluxBoundarySelfTest::FluxBoundarySelfTest(), MarbleRun::includeInDomain(), InitialConditions< SpeciesType >::InitialConditions(), LawinenBox::LawinenBox(), load(), main(), ParticleCreation::ParticleCreation(), protectiveWall::protectiveWall(), readNextArgument(), regimeForceUnitTest::regimeForceUnitTest(), Slide::set_Walls(), Chute::setChuteWidth(), ExtremeOverlapUnitTest::setupInitialConditions(), ExtremeOverlapVolumeUnitTest::setupInitialConditions(), SmoothChute::setupInitialConditions(), HorizontalMixer::setupInitialConditions(), MembraneDemo::setupInitialConditions(), Chain::setupInitialConditions(), FiveParticles::setupInitialConditions(), Cstatic2d::setupInitialConditions(), Cstatic3D::setupInitialConditions(), statistics_while_running< T >::setupInitialConditions(), ConstantMassFlowMaserBoundaryMixedSpeciesSelfTest::setupInitialConditions(), ConstantMassFlowMaserSelfTest::setupInitialConditions(), PolydisperseInsertionBoundarySelfTest::setupInitialConditions(), CGBasicSelfTest::setupInitialConditions(), CGHandlerSelfTest::setupInitialConditions(), CGStaticBalanceSelfTest::setupInitialConditions(), NewtonsCradleSelftest::setupInitialConditions(), NewtonsCradleSelfTest::setupInitialConditions(), ParticleParticleCollision::setupInitialConditions(), WallParticleCollision::setupInitialConditions(), TwoParticleElasticCollisionInteraction::setupInitialConditions(), MembraneSelfTest::setupInitialConditions(), SimpleOpt::setupInitialConditions(), ScalingTestInitialConditionsRelax::setupInitialConditions(), ScalingTestRun::setupInitialConditions(), Contact::setupInitialConditions(), GranularCollapse::setupInitialConditions(), ParticleParticleInteraction::setupInitialConditions(), ParticleParticleInteractionWithPlasticForces::setupInitialConditions(), ParticleWallInteraction::setupInitialConditions(), AngledPeriodicBoundarySecondUnitTest::setupInitialConditions(), ChargedBondedParticleUnitTest::setupInitialConditions(), DrivenParticleClass::setupInitialConditions(), EnergyUnitTest::setupInitialConditions(), ExtremeOverlapWithWallsUnitTest::setupInitialConditions(), HertzianSinterForceUnitTest::setupInitialConditions(), MD_demo::setupInitialConditions(), MovingIntersectionOfWallsUnitTest_Basic::setupInitialConditions(), MovingWall::setupInitialConditions(), PeriodicWallsWithSlidingFrictionUnitTest::setupInitialConditions(), PlasticForceUnitTest::setupInitialConditions(), SeparateFilesSelfTest::setupInitialConditions(), SinterForceUnitTest::setupInitialConditions(), SpeciesTest::setupInitialConditions(), TangentialSpringUnitTest::setupInitialConditions(), WallSpecies::setupInitialConditions(), MercuryProblem::setupMercuryProblem(), Siegen::Siegen(), SingleParticle< SpeciesType >::SingleParticle(), T_protectiveWall::T_protectiveWall(), Tutorial11::Tutorial11(), StressStrainControlBoundary::updateDomainSize(), and viscoElasticUnitTest::viscoElasticUnitTest().
setYMin()
void DPMBase::setYMin (Mdouble newYMin)
Sets the value of YMin, the lower bound of the problem domain in the y-direction.
Deprecated:
An access function which allows the user to alter the value of the (private) y value of the "Vec3D" object "min_", thus setting the minimum y-value corresponding to the system, i.e. the lower limit of the domain in the y-direction.
These bounds are used for display, plotting and statistics purposes. They do not affect the dynamics.
The function also performs a sanity check to stop the user defining a lower bound that is higher than the corresponding upper bound (YMax), giving a (logged) warning if the user attempts to do so.
Parameters
[in] newYMin
 {
 if (newYMin <= getYMax())
 {
 min_.y() = newYMin;
 }
 else
 {
 logger(WARN, "Warning in setYMin(%): yMax=%", newYMin, getYMax());
 }
 }
References getYMax(), logger, min_, WARN, and Vec3D::y().
Referenced by statistics_while_running< T >::auto_set_domain(), BoundariesSelfTest::BoundariesSelfTest(), ChangingTOIParticle::ChangingTOIParticle(), Funnel::check_funnel(), ClosedCSCWalls::ClosedCSCWalls(), clumpTest::clumpTest(), CSCWalls::CSCWalls(), FluxAndPeriodicBoundarySelfTest::FluxAndPeriodicBoundarySelfTest(), FluxBoundarySelfTest::FluxBoundarySelfTest(), MarbleRun::includeInDomain(), InitialConditions< SpeciesType >::InitialConditions(), load(), main(), ParticleCreation::ParticleCreation(), readNextArgument(), regimeForceUnitTest::regimeForceUnitTest(), Slide::set_Walls(), ExtremeOverlapUnitTest::setupInitialConditions(), ExtremeOverlapVolumeUnitTest::setupInitialConditions(), SmoothChute::setupInitialConditions(), HorizontalMixer::setupInitialConditions(), MembraneDemo::setupInitialConditions(), Chain::setupInitialConditions(), FiveParticles::setupInitialConditions(), ConstantMassFlowMaserBoundaryMixedSpeciesSelfTest::setupInitialConditions(), ConstantMassFlowMaserSelfTest::setupInitialConditions(), PolydisperseInsertionBoundarySelfTest::setupInitialConditions(), CGBasicSelfTest::setupInitialConditions(), CGHandlerSelfTest::setupInitialConditions(), CGStaticBalanceSelfTest::setupInitialConditions(), NewtonsCradleSelftest::setupInitialConditions(), NewtonsCradleSelfTest::setupInitialConditions(), ChargedBondedParticleUnitTest::setupInitialConditions(), MembraneSelfTest::setupInitialConditions(), SimpleOpt::setupInitialConditions(), ScalingTestInitialConditionsRelax::setupInitialConditions(), Contact::setupInitialConditions(), GranularCollapse::setupInitialConditions(), ParticleParticleInteraction::setupInitialConditions(), ParticleParticleInteractionWithPlasticForces::setupInitialConditions(), ParticleWallInteraction::setupInitialConditions(), AngledPeriodicBoundarySecondUnitTest::setupInitialConditions(), EnergyUnitTest::setupInitialConditions(), ExtremeOverlapWithWallsUnitTest::setupInitialConditions(), MD_demo::setupInitialConditions(), MovingIntersectionOfWallsUnitTest_Basic::setupInitialConditions(), PeriodicWallsWithSlidingFrictionUnitTest::setupInitialConditions(), SinterForceUnitTest::setupInitialConditions(), MercuryProblem::setupMercuryProblem(), Siegen::Siegen(), SingleParticle< SpeciesType >::SingleParticle(), Tutorial11::Tutorial11(), StressStrainControlBoundary::updateDomainSize(), and viscoElasticUnitTest::viscoElasticUnitTest().
setZMax()
void DPMBase::setZMax (Mdouble newZMax)
Sets the value of ZMax, the upper bound of the problem domain in the z-direction.
Deprecated:
An access function which allows the user to alter the value of the (private) z value of the "Vec3D" object "max_", thus setting the maximum z-value corresponding to the system, i.e. the upper limit of the domain in the z-direction.
These bounds are used for display, plotting and statistics purposes. They do not affect the dynamics.
The function also performs a sanity check to stop the user defining an upper bound that is lower than the corresponding lower bound (ZMin), giving a (logged) warning if the user attempts to do so.
Parameters
[in] newZMax
 {
 if (newZMax >= getZMin())
 {
 max_.z() = newZMax;
 }
 else
 {
 logger(WARN, "Warning in setZMax(%): zMax=%", newZMax, getZMin());
 }
 }
References getZMin(), logger, max_, WARN, and Vec3D::z().
Referenced by Chutebelt::actionsAfterTimeStep(), ChutePeriodic::add_flow_particles(), SilbertPeriodic::add_flow_particles(), Chute::addFlowParticlesCompactly(), ChuteWithHopper::addHopper(), statistics_while_running< T >::auto_set_domain(), statistics_while_running< T >::auto_set_z(), BoundariesSelfTest::BoundariesSelfTest(), ChangingTOIParticle::ChangingTOIParticle(), ClosedCSCWalls::ClosedCSCWalls(), clumpTest::clumpTest(), CSCWalls::CSCWalls(), FluxAndPeriodicBoundarySelfTest::FluxAndPeriodicBoundarySelfTest(), FluxBoundarySelfTest::FluxBoundarySelfTest(), MarbleRun::includeInDomain(), InitialConditions< SpeciesType >::InitialConditions(), load(), main(), ParticleCreation::ParticleCreation(), protectiveWall::protectiveWall(), readNextArgument(), Chute::readNextArgument(), regimeForceUnitTest::regimeForceUnitTest(), ClosedCSCWalls::saveWalls(), AngleOfRepose::set_H(), SilbertPeriodic::set_H(), Slide::set_Walls(), Chute::setInflowHeight(), ChutePeriodic::setup(), ExtremeOverlapUnitTest::setupInitialConditions(), ExtremeOverlapVolumeUnitTest::setupInitialConditions(), LawinenBox::setupInitialConditions(), SmoothChute::setupInitialConditions(), CFDDEMCoupleTest::setupInitialConditions(), HorizontalMixer::setupInitialConditions(), MembraneDemo::setupInitialConditions(), Chain::setupInitialConditions(), FiveParticles::setupInitialConditions(), Cstatic2d::setupInitialConditions(), Cstatic3D::setupInitialConditions(), statistics_while_running< T >::setupInitialConditions(), Chutebelt::setupInitialConditions(), ConstantMassFlowMaserBoundaryMixedSpeciesSelfTest::setupInitialConditions(), ConstantMassFlowMaserSelfTest::setupInitialConditions(), PolydisperseInsertionBoundarySelfTest::setupInitialConditions(), CGBasicSelfTest::setupInitialConditions(), CGHandlerSelfTest::setupInitialConditions(), CGStaticBalanceSelfTest::setupInitialConditions(), NewtonsCradleSelftest::setupInitialConditions(), NewtonsCradleSelfTest::setupInitialConditions(), ParticleParticleCollision::setupInitialConditions(), WallParticleCollision::setupInitialConditions(), TwoParticleElasticCollisionInteraction::setupInitialConditions(), MembraneSelfTest::setupInitialConditions(), SimpleOpt::setupInitialConditions(), ScalingTestInitialConditionsRelax::setupInitialConditions(), ScalingTestRun::setupInitialConditions(), Contact::setupInitialConditions(), GranularCollapse::setupInitialConditions(), ParticleParticleInteraction::setupInitialConditions(), ParticleParticleInteractionWithPlasticForces::setupInitialConditions(), ParticleWallInteraction::setupInitialConditions(), AngledPeriodicBoundarySecondUnitTest::setupInitialConditions(), ChargedBondedParticleUnitTest::setupInitialConditions(), DrivenParticleClass::setupInitialConditions(), EnergyUnitTest::setupInitialConditions(), ExtremeOverlapWithWallsUnitTest::setupInitialConditions(), HertzianSinterForceUnitTest::setupInitialConditions(), MD_demo::setupInitialConditions(), MovingWall::setupInitialConditions(), PlasticForceUnitTest::setupInitialConditions(), SeparateFilesSelfTest::setupInitialConditions(), SinterForceUnitTest::setupInitialConditions(), SpeciesTest::setupInitialConditions(), TangentialSpringUnitTest::setupInitialConditions(), WallSpecies::setupInitialConditions(), MercuryProblem::setupMercuryProblem(), Siegen::Siegen(), SingleParticle< SpeciesType >::SingleParticle(), T_protectiveWall::T_protectiveWall(), Tutorial11::Tutorial11(), StressStrainControlBoundary::updateDomainSize(), and viscoElasticUnitTest::viscoElasticUnitTest().
setZMin()
void DPMBase::setZMin (Mdouble newZMin)
Sets the value of ZMin, the lower bound of the problem domain in the z-direction.
Deprecated:
An access function which allows the user to alter the value of the (private) z value of the "Vec3D" object "min_", thus setting the minimum z-value corresponding to the system, i.e. the lower limit of the domain in the z-direction.
These bounds are used for display, plotting and statistics purposes. They do not affect the dynamics.
The function also performs a sanity check to stop the user defining a lower bound that is higher than the corresponding upper bound (ZMax), giving a (logged) warning if the user attempts to do so.
Parameters
[in] newZMin
 {
 if (newZMin <= getZMax())
 {
 min_.z() = newZMin;
 }
 else
 {
 logger(WARN, "Warning in setZMin(%): zMax=%", newZMin, getZMax());
 }
 }
References getZMax(), logger, min_, WARN, and Vec3D::z().
Referenced by statistics_while_running< T >::auto_set_domain(), statistics_while_running< T >::auto_set_z(), BoundariesSelfTest::BoundariesSelfTest(), ChangingTOIParticle::ChangingTOIParticle(), ClosedCSCWalls::ClosedCSCWalls(), clumpTest::clumpTest(), CSCWalls::CSCWalls(), FluxAndPeriodicBoundarySelfTest::FluxAndPeriodicBoundarySelfTest(), FluxBoundarySelfTest::FluxBoundarySelfTest(), MarbleRun::includeInDomain(), InitialConditions< SpeciesType >::InitialConditions(), load(), main(), ParticleCreation::ParticleCreation(), readNextArgument(), regimeForceUnitTest::regimeForceUnitTest(), Slide::set_Walls(), ExtremeOverlapUnitTest::setupInitialConditions(), ExtremeOverlapVolumeUnitTest::setupInitialConditions(), SmoothChute::setupInitialConditions(), HorizontalMixer::setupInitialConditions(), MembraneDemo::setupInitialConditions(), Chain::setupInitialConditions(), FiveParticles::setupInitialConditions(), ConstantMassFlowMaserBoundaryMixedSpeciesSelfTest::setupInitialConditions(), ConstantMassFlowMaserSelfTest::setupInitialConditions(), PolydisperseInsertionBoundarySelfTest::setupInitialConditions(), CGBasicSelfTest::setupInitialConditions(), CGHandlerSelfTest::setupInitialConditions(), CGStaticBalanceSelfTest::setupInitialConditions(), NewtonsCradleSelftest::setupInitialConditions(), NewtonsCradleSelfTest::setupInitialConditions(), ChargedBondedParticleUnitTest::setupInitialConditions(), MembraneSelfTest::setupInitialConditions(), SimpleOpt::setupInitialConditions(), ScalingTestInitialConditionsRelax::setupInitialConditions(), Contact::setupInitialConditions(), GranularCollapse::setupInitialConditions(), ParticleParticleInteraction::setupInitialConditions(), ParticleParticleInteractionWithPlasticForces::setupInitialConditions(), ParticleWallInteraction::setupInitialConditions(), AngledPeriodicBoundarySecondUnitTest::setupInitialConditions(), EnergyUnitTest::setupInitialConditions(), ExtremeOverlapWithWallsUnitTest::setupInitialConditions(), MD_demo::setupInitialConditions(), SinterForceUnitTest::setupInitialConditions(), SpeciesTest::setupInitialConditions(), MercuryProblem::setupMercuryProblem(), Siegen::Siegen(), SingleParticle< SpeciesType >::SingleParticle(), Tutorial11::Tutorial11(), StressStrainControlBoundary::updateDomainSize(), and viscoElasticUnitTest::viscoElasticUnitTest().
signalHandler()
void DPMBase::signalHandler (int signal) static private
signal handler function.
 {
     switch (signal)
     {
         case SIGINT:
             if (!continueFlag_)
             {
                 logger(INFO, "SIGINT has been captured for the second time!\nMercuryDPM will forcefully exit!");
                 std::exit(SIGINT);
             }
             logger(INFO, "SIGINT has been captured!\nMercuryDPM will finish the current time step, then it will stop!\nHit Ctrl+C again to forcefully exit.");
             continueFlag_ = false;
             return;
         case SIGTERM:
             logger(INFO, "\nSIGTERM has been captured!\nMercuryDPM will finish the current time step, then it will stop!");
             continueFlag_ = false;
             return;
         default:
             logger(INFO, "No Signal to Capture!");
     }
 }
References continueFlag_, INFO, and logger.
Referenced by setSoftStop().
solve() [1/2]
void DPMBase::solve ()
The work horse of the code.
Todo:
IFCD AT, TW: Consider moving some things before the time loop to actionsBeforeTimeLoop
 {
     initialiseSolve();
     setSoftStop();
     // Can be used to measure simulation time
     clock_.tic();
     // This is the main loop over advancing time
     while (getTime() < getTimeMax() && continueSolve() && continueFlag_)
     {
         computeOneTimeStep();
     }
     // Can be used to measure simulation time
     clock_.toc();
     finaliseSolve();
 }
References clock_, computeOneTimeStep(), continueFlag_, continueSolve(), finaliseSolve(), getTime(), getTimeMax(), initialiseSolve(), setSoftStop(), Time::tic(), and Time::toc().
Referenced by FixedClusterInsertionBoundary::checkBoundaryBeforeTimeStep(), RandomClusterInsertionBoundary::checkBoundaryBeforeTimeStep(), commandLineCG(), ClusterGenerator::create(), CLiveStatistics< T >::getLiveStatistics(), main(), ChuteBottom::makeRoughBottom(), MeltableForceLaw2SelfTest::MeltableForceLaw2SelfTest(), MeltableForceLawSelfTest::MeltableForceLawSelfTest(), MovingWalls::MovingWalls(), RotatingDrumBidisperse::RotatingDrumBidisperse(), FlowRule::run(), statistics_while_running< T >::run(), AngleOfRepose::run(), vibratedBed::run(), runFreeFall(), SaveCountUnitTest::SaveCountUnitTest(), solve(), SilbertHstop::solve_analytic(), statistics_while_running< T >::statistics_while_running(), ContactDetectionIntersectionOfWallsTest::test(), BouncingSuperQuadric::test(), SlidingSpheresUnitTest::test(), ContactDetectionNormalSpheresTest::test(), ContactDetectionRotatedSpheresTest::test(), Packing::test(), and HertzContactRestitutionUnitTest::test().
solve() [2/2]
void DPMBase::solve (int argc, char * argv[])
The work horse of the code. Can handle flags from the command line.
This method allows flags to be passed to Mercury from driver codes, such that variables can be altered without needing to alter the driver files - for example, if the user wishes to give specific commands for the manner in which the system will be displayed in xballs.
After reading in the arguments provided, the normal 'solve()' routine is called. For full details see the documentation of the solve() function (linked).
Parameters
[in] argc
[in] argv
 {
 readArguments(argc, argv);
 solve();
 }
References readArguments(), and solve().
splitDomain()
void DPMBase::splitDomain (DomainSplit domainSplit)
Splits domain as neatly as possible. e.g. splitDomain(XY) splits domain into a 6x5x1 grid for 30 processors, a 6x6x1 grid for 36 processors
Todo:
the function needs improvement: for non-cubic domains (with different domain length in x,y,z), having a equal number of grid cell is not the best choice.
{
     //one-d problems
     if (domainSplit == DomainSplit::X) {
         setNumberOfDomains({NUMBER_OF_PROCESSORS,1,1});
         return;
     } else if (domainSplit == DomainSplit::Y) {
         setNumberOfDomains({1,NUMBER_OF_PROCESSORS,1});
         return;
     } else if (domainSplit == DomainSplit::Z) {
         setNumberOfDomains({1,1,NUMBER_OF_PROCESSORS});
         return;
     }
     //two-d problems
     // split into axb grid with a the largest integer that divides NUMBER_OF_PROCESSORS and is smaller than sqrt(NUMBER_OF_PROCESSORS)
     unsigned a;
     for (unsigned n = floor(sqrt(NUMBER_OF_PROCESSORS));n>0; n--) {
         if (NUMBER_OF_PROCESSORS % n == 0) {
             a = n;
             break;
         }
     }
     if (domainSplit == DomainSplit::XY) {
         setNumberOfDomains({NUMBER_OF_PROCESSORS/a,a,1});
         return;
     } else if (domainSplit == DomainSplit::XZ) {
         setNumberOfDomains({NUMBER_OF_PROCESSORS/a,1,a});
         return;
     } else if (domainSplit == DomainSplit::YZ) {
         setNumberOfDomains({1,NUMBER_OF_PROCESSORS/a,a});
         return;
     }
     //three-d problems
     // split into axbxc grid with
     //  - a the largest integer that divides NUMBER_OF_PROCESSORS and is smaller than cbrt(NUMBER_OF_PROCESSORS)
     //  - b the largest integer that divides NUMBER_OF_PROCESSORS/a and is smaller than sqrt(NUMBER_OF_PROCESSORS/a)
     unsigned b;
     for (unsigned n = floor(cbrt(NUMBER_OF_PROCESSORS));n>0; n--) {
         if (NUMBER_OF_PROCESSORS % n == 0) {
             a = n;
             break;
         }
     }
     for (unsigned n = floor(sqrt(NUMBER_OF_PROCESSORS/a));n>0; n--) {
         if (NUMBER_OF_PROCESSORS % (n*a) == 0) {
             b = n;
             break;
         }
     }
     setNumberOfDomains({NUMBER_OF_PROCESSORS/a/b,a,b});
 }
References a, b, Eigen::numext::cbrt(), Eigen::bfloat16_impl::floor(), n, NUMBER_OF_PROCESSORS, setNumberOfDomains(), sqrt(), X, XY, XZ, Y, YZ, and Z.
synchroniseParticle()
void DPMBase::synchroniseParticle (BaseParticle * p, unsigned fromProcessor = 0) protected
 {
 #ifdef MERCURYDPM_USE_MPI
     MPIContainer& communicator = MPIContainer::Instance();
     //The processor that contains the particle that needs to be copied needs to identify the target, and communicate this
     MPIParticle pInfo;
     if (communicator.getProcessorID() == fromProcessor)
     {
         pInfo.copyDataFromParticleToMPIParticle(p);
     }
     //Broadcast from processor i
     communicator.broadcast(&pInfo,MercuryMPIType::PARTICLE,fromProcessor);
     copyDataFromMPIParticleToParticle(&pInfo, p, &particleHandler);
 #endif
 }
References MPIContainer::broadcast(), copyDataFromMPIParticleToParticle(), MPISphericalParticle::copyDataFromParticleToMPIParticle(), MPIContainer::getProcessorID(), MPIContainer::Instance(), p, PARTICLE, and particleHandler.
updateGhostGrid()
void DPMBase::updateGhostGrid (BaseParticle * P)
Checks if the Domain/periodic interaction distance needs to be updated and updates it accordingly.
Checks if the domain and periodicBoundaryHandler need to update the interaction distance. If this is the case it will update the ghost particles as well.
When adding a new particle with a larger interaction radius than all previous particles, the domain needs to update the interactionDistance and initialise all particles that are now also included in the communication zones. All other domains are updated as well.
Parameters
[in] P Pointer to a baseParticle that recently has been added to the simulation
 {
 #ifdef MERCURYDPM_USE_MPI
     if (NUMBER_OF_PROCESSORS == 1) { return; }
     //Check if the interactionRadius of the BaseParticle is larger than given in the domain
     Domain* domain = domainHandler.getCurrentDomain();
     if(2.0*P->getMaxInteractionRadius() > domainHandler.getInteractionDistance())
     {
         logger(VERBOSE,"Processor % | Updating mpi grid. Old interactionDistance: %, new interactionDistance %.",
             PROCESSOR_ID,domainHandler.getInteractionDistance(),2.0*P->getMaxInteractionRadius());
         //Update the interactionDistance in the domain and periodicBoundaryHandler
         domainHandler.setInteractionDistance(2.0*P->getMaxInteractionRadius());
         periodicBoundaryHandler.setInteractionDistance(2.0*P->getMaxInteractionRadius());
         //Find new ghost particless
         domainHandler.addNewParticles();
         periodicBoundaryHandler.addNewParticles();
     }
 #endif
 }
References DomainHandler::addNewParticles(), PeriodicBoundaryHandler::addNewParticles(), domain, domainHandler, DomainHandler::getCurrentDomain(), DomainHandler::getInteractionDistance(), logger, NUMBER_OF_PROCESSORS, Global_Physical_Variables::P, periodicBoundaryHandler, PROCESSOR_ID, DomainHandler::setInteractionDistance(), PeriodicBoundaryHandler::setInteractionDistance(), and VERBOSE.
Referenced by ParticleHandler::addObject().
write()
void DPMBase::write (std::ostream & os, bool writeAllParticles = true) const virtual
     \brief Loads all MD data and plots statistics for all time steps in the .data file
    &zwj;/
void statisticsFromRestartData(const char *name); /
Todo:
what to do with statisticsFromRestartData?
/*!
   \brief Writes all data into a restart file
Writes out all relevant information - e.g. system dimensions, run duration, particle information - for a .restart file to the chosen output stream, os. More detailed comments may be seen in the body of the code.
Parameters
[in] writeAllParticles A boolean which decides whether or not all particle information is written to the output file. (Otherwise, only a small number of particles are printed.)
[in] nToWrite
Reimplemented in MercuryBase, ChuteWithHopper, Chute, Funnel, BaseCluster, MembraneSelfTest, MembraneDemo, SegregationPeriodic, SegregationPeriodic, and SegregationPeriodic.
 {
     os << "MercuryDPM " << getVersion();
     //which outputs basic information regarding the various files  (.data, .fstat etc. etc.)
     //only writes the run number if it is different from 0
     if (runNumber_ != 0)
         os << " runNumber " << runNumber_;
     os << " name " << name_;
     os << " revision " << getRevision();
     os << " repository " << getRepositoryURL() << '\n';
     os << "dataFile    " << dataFile << '\n';
     os << "fStatFile   " << fStatFile << '\n';
     os << "eneFile     " << eneFile << '\n';
     os << "restartFile " << restartFile << '\n';
     os << "statFile    " << statFile << '\n';
     os << "interactionFile " << interactionFile << '\n';
     //Outputs the "domain" corresponding to the system for
     //use with XBalls, as well as other information regarding the system as a whole
     os << "xMin " << getXMin()
        << " xMax " << getXMax()
        << " yMin " << getYMin()
        << " yMax " << getYMax()
        << " zMin " << getZMin()
        << " zMax " << getZMax() << '\n'
        << "timeStep " << getTimeStep()
        << " time " << getTime()
        << " ntimeSteps " << numberOfTimeSteps_
        << " timeMax " << getTimeMax() << '\n'
        << "systemDimensions " << getSystemDimensions()
        << " particleDimensions " << getParticleDimensions()
        << " gravity " << getGravity()
        << " backgroundDrag " <<getBackgroundDrag();
     os << " writeVTK " << writeParticlesVTK_
         << " " << wallHandler.getWriteVTK()
         << " " << interactionHandler.getWriteVTK()
         << " " << boundaryHandler.getWriteVTK()
         << " " << (vtkWriter_?vtkWriter_->getFileCounter():0)
         << " " << wallVTKWriter_.getFileCounter()
         << " " << interactionVTKWriter_.getFileCounter()
         << " " << boundaryVTKWriter_.getFileCounter();
     // Outputting the wall details vtk enum values and file types.
     // For example, we have three wall details options with enum values 4, 12 and 25, and three corresponding filetypes
     // NO_FILE, ONE_FILE and MULTIPLE_FILES. Let's also say the file counter is at 101.
     // The output will be: writeWallDetailsVTK 3 4 NO_FILE 12 ONE_FILE 25 MULTIPLE_FILES 101
     // Only write when any of them have something other than NO_FILE. In this way the selftests restart files all keep working.
     if (wallHandler.getWriteDetailsVTKAny())
     {
         std::unordered_map<WallHandler::DetailsVTKOptions, FileType> writeWallDetailsVTK = wallHandler.getWriteWallDetailsVTKAll();
         os << " writeWallDetailsVTK " << writeWallDetailsVTK.size();
         for (const auto& p : writeWallDetailsVTK)
             os << " " << static_cast<int>(p.first) << " " << p.second;
         os << " " << wallDetailsVTKWriter_.getFileCounter();
     }
     // Only write vtk output directories if any of them are different then the default directory.
     if ((vtkWriter_ && vtkWriter_->getOutputDirectory() != ".") ||
         wallVTKWriter_.getOutputDirectory() != "." ||
         interactionVTKWriter_.getOutputDirectory() != "." ||
         boundaryVTKWriter_.getOutputDirectory() != "." ||
         wallDetailsVTKWriter_.getOutputDirectory() != ".")
     {
         os << " vtkOutDir " << (vtkWriter_ ? vtkWriter_->getOutputDirectory() : ".")
             << " " << wallVTKWriter_.getOutputDirectory()
             << " " << interactionVTKWriter_.getOutputDirectory()
             << " " << boundaryVTKWriter_.getOutputDirectory()
             << " " << wallDetailsVTKWriter_.getOutputDirectory();
     }
 vtk_out_dir_done:
     os << " random ";
     random.write(os);
 #ifdef MERCURYDPM_USE_OMP
     //Write number of OMP threads
     if(getNumberOfOMPThreads() > 1) {
         os << " numberOfOMPThreads " << getNumberOfOMPThreads();
     }
 #endif
 #ifdef MERCURYDPM_USE_MPI
     //Check if we are dealing with multiple cores
     if (NUMBER_OF_PROCESSORS > 1 )
     {
         os << " numberOfProcessors " << NUMBER_OF_PROCESSORS
             << " numberOfDomains " << numberOfDomains_[Direction::XAXIS] << " " << numberOfDomains_[Direction::YAXIS] << " " << numberOfDomains_[Direction::ZAXIS];
     }
 #endif
     //only write xBallsArguments if they are nonzero
     if (getXBallsAdditionalArguments().compare(""))
         os << " xBallsArguments " << getXBallsAdditionalArguments();
     os << '\n';
     //writes all species (including mixed species) to an output stream
     speciesHandler.write(os);
     //outputs the number of walls in the system
     os << "Walls " << wallHandler.getNumberOfObjects() << std::endl;
     if (writeAllParticles || wallHandler.getSize() < 9) {
         for (BaseWall* w : wallHandler)
             os << (*w) << std::endl;
     } else {
         for (int i=0; i<2; ++i)
             os << *wallHandler.getObject(i) << std::endl;
         os << "...\n";
     }
     //outputs the number of boundaries in the system
     os << "Boundaries " << boundaryHandler.getNumberOfObjects() << std::endl;
     if (writeAllParticles || boundaryHandler.getSize() < 9)
     {
         for (BaseBoundary* b: boundaryHandler)
             os << (*b) << std::endl;
     }
     else
     {
         for (int i = 0; i < 2; ++i)
             os << *boundaryHandler.getObject(i) << std::endl;
         os << "...\n";
     }
     if (writeAllParticles || particleHandler.getSize() < getNToWrite())
     {
         //if the "writeAllParticles" bool == true, or there are fewer than 4 particles
         //calls the particleHandler version of the "write" function and also
         //outputs to file all relevant particle information for all particles in the system
         particleHandler.write(os);
     }
     else
     {
         //otherwise, only prints out limited information
         os << "Particles " << particleHandler.getSize() << '\n';
         for (unsigned int i = 0; i < getNToWrite(); i++)
             os << *(particleHandler.getObject(i)) << '\n';
         os << "..." << '\n';
     }
     // Similarly, print out interaction details (all of them, or up to nToWrite of them)
     if (writeAllParticles || interactionHandler.getNumberOfObjects() < getNToWrite())
     {
         interactionHandler.write(os);
     }
     else
     {
         os << "Interactions " << interactionHandler.getNumberOfObjects() << '\n';
         for (unsigned int i = 0; i < getNToWrite(); i++)
             os << *(interactionHandler.getObject(i)) << '\n';
         os << "..." << '\n';
     }
 }
References b, boundaryHandler, boundaryVTKWriter_, compare(), dataFile, eneFile, fStatFile, getBackgroundDrag(), BaseVTKWriter< H >::getFileCounter(), getGravity(), getNToWrite(), BaseHandler< T >::getNumberOfObjects(), getNumberOfOMPThreads(), BaseHandler< T >::getObject(), BaseVTKWriter< H >::getOutputDirectory(), getParticleDimensions(), getRepositoryURL(), getRevision(), BaseHandler< T >::getSize(), getSystemDimensions(), getTime(), getTimeMax(), getTimeStep(), getVersion(), WallHandler::getWriteDetailsVTKAny(), BoundaryHandler::getWriteVTK(), InteractionHandler::getWriteVTK(), WallHandler::getWriteVTK(), WallHandler::getWriteWallDetailsVTKAll(), getXBallsAdditionalArguments(), getXMax(), getXMin(), getYMax(), getYMin(), getZMax(), getZMin(), i, interactionFile, interactionHandler, interactionVTKWriter_, name_, NUMBER_OF_PROCESSORS, numberOfDomains_, numberOfTimeSteps_, p, particleHandler, random, restartFile, runNumber_, speciesHandler, statFile, vtkWriter_, w, wallDetailsVTKWriter_, wallHandler, wallVTKWriter_, InteractionHandler::write(), RNG::write(), ParticleHandler::write(), SpeciesHandler::write(), writeParticlesVTK_, XAXIS, YAXIS, and ZAXIS.
Referenced by statistics_while_running< T >::actionsBeforeTimeLoop(), CLiveStatistics< T >::setupInitialConditions(), statistics_while_running< T >::setupInitialConditions(), Slide::Slide(), MercuryBase::write(), and writeRestartFile().
writeDataFile()
void DPMBase::writeDataFile ()
 {
     if (dataFile.openWrite(getNumberOfTimeSteps()))
     {
         outputXBallsData(dataFile.getFstream());
         dataFile.close();
     }
 }
References File::close(), dataFile, File::getFstream(), getNumberOfTimeSteps(), File::openWrite(), and outputXBallsData().
Referenced by writeOutputFiles().
writeEneFile()
void DPMBase::writeEneFile ()
 {
     if (eneFile.openWrite(getNumberOfTimeSteps()))
     {
         //If the file type is "multiple files", writes a header for each individual files. If not, only writes for the first time step
         writeEneTimeStep(eneFile.getFstream());
         eneFile.close();
     }
 }
References File::close(), eneFile, File::getFstream(), getNumberOfTimeSteps(), File::openWrite(), and writeEneTimeStep().
Referenced by writeOutputFiles().
writeEneHeader()
void DPMBase::writeEneHeader (std::ostream & os) const protected virtual
Writes a header with a certain format for ENE file.
If the "append" flag is off (false) - i.e. the file has not been restarted - creates a header for the output ".ene" file. The headers simply give titles to each of the columns output to this file.
If the "append" flag is on (true), i.e. if the file has restarted, simply ends the function without writing a header - otherwise restarted files will have a random header at the point of restart, making data processing more difficult...
The function takes as an argument an output stream, "os", which tells the compiler where to output the headers, if they are required.
Parameters
[in] os The output stream to the file in which the header should be written.
Todo:
JMFT: Get rid of aligned columns. They make things too wide. (changed back)
Todo:
{Why is there a +6 here? TW: to get the numbers and title aligned}
Todo:
Add number of particles to this file (change from Jonny to be added later)
Reimplemented in BaseCoupling< Mercury3D, SolidProblem< SCoupledElement< ELEMENT > > >, BaseCoupling< Mercury3D, SolidProblem< ScaleCoupledElement< ELEMENT > > >, SlidingFrictionUnitTest, SphericalIndenter, Sintering, and SingleParticle< SpeciesType >.
 {
     //only write if we don't restart
     if (getAppend())
         return;
     long width = os.precision() + 6;
     os << std::setw(width)
        << "time " << std::setw(width)
        << "gravitEnergy " << std::setw(width) //gravitational potential energy
        << "traKineticEnergy " << std::setw(width) //translational kinetic energy
        << "rotKineticEnergy " << std::setw(width) //rotational kE
        << "elasticEnergy " << std::setw(width)
        << "centerOfMassX " << std::setw(width)
        << "centerOfMassY " << std::setw(width)
        << "centerOfMassZ\n";
 }
References getAppend().
Referenced by writeEneTimeStep().
writeEneTimeStep()
void DPMBase::writeEneTimeStep (std::ostream & os) const protected virtual
Write the global kinetic, potential energy, etc. in the system.
The function cycles over all particles within the system (or rather, the particleHandler), creating sums of the relevant energies and "mass lengths" (m.x, m.y, m.z) from which the system's centre of mass can also be calculated. The summed energy values and calculated centre of mass values are then output to the file corresponding to "os" alongside the current time step.
A check is performed - if (!p->isFixed()) - to ensure that calculations are not performed on fixed particles, as these are assigned an effectively infinite mass and would hence cause compiler issues.
Parameters
[in] os The output stream to which the data will be written
Reimplemented in BaseCoupling< Mercury3D, SolidProblem< SCoupledElement< ELEMENT > > >, BaseCoupling< Mercury3D, SolidProblem< ScaleCoupledElement< ELEMENT > > >, SlidingFrictionUnitTest, SphericalIndenter, Sintering, SingleParticle< SpeciesType >, Slide, Slide, Silo, Penetration, Drum, LawinenBox, LawinenBox, and LawinenBox.
 {
     if (eneFile.getCounter() == 1 || eneFile.getFileType() == FileType::MULTIPLE_FILES ||
         eneFile.getFileType() == FileType::MULTIPLE_FILES_PADDED)
         writeEneHeader(os);
     const Mdouble m = particleHandler.getMass();
     const Vec3D com = particleHandler.getMassTimesPosition();
     //Ensure the numbers fit into a constant width column: for this we need the precision given by the operating system,
     //plus a few extra characters for characters like a minus and scientific notation.
     const static int width = os.precision() + 6;
     os << std::setw(width) << getTime()
        << " " << std::setw(width) << -Vec3D::dot(getGravity(), com)
        << " " << std::setw(width) << particleHandler.getKineticEnergy()
        << " " << std::setw(width) << particleHandler.getRotationalEnergy()
        << " " << std::setw(width) << getElasticEnergy()
        // we need to write x, y and z coordinates separately, otherwise the width of the columns is incorrect
        << " " << std::setw(width)
        << (m == 0 ? constants::NaN : com.X / m) //set to nan because 0/0 implementation in gcc and clang differs
        << " " << std::setw(width) << (m == 0 ? constants::NaN : com.Y / m)
        << " " << std::setw(width) << (m == 0 ? constants::NaN : com.Z / m)
        << std::endl;
 }
References Vec3D::dot(), eneFile, File::getCounter(), getElasticEnergy(), File::getFileType(), getGravity(), ParticleHandler::getKineticEnergy(), ParticleHandler::getMass(), ParticleHandler::getMassTimesPosition(), ParticleHandler::getRotationalEnergy(), getTime(), m, MULTIPLE_FILES, MULTIPLE_FILES_PADDED, constants::NaN, particleHandler, writeEneHeader(), Vec3D::X, Vec3D::Y, and Vec3D::Z.
Referenced by writeEneFile().
writeFStatFile()
void DPMBase::writeFStatFile ()
 {
     if (fStatFile.openWrite(getNumberOfTimeSteps()))
     {
         writeFstatHeader(fStatFile.getFstream());
         //fStatFile.getFstream().ignore(2000,'\t');
         fStatFile.close();
     }
 }
References File::close(), fStatFile, File::getFstream(), getNumberOfTimeSteps(), File::openWrite(), and writeFstatHeader().
Referenced by writeOutputFiles().
writeFstatHeader()
void DPMBase::writeFstatHeader (std::ostream & os) const protected virtual
Writes a header with a certain format for FStat file.
The function takes as an argument an output stream and, to the corresponding file, outputs the relevant header and data for the ".fstat"-type output files. For more information regarding the fstat file format, please refer to the user guide on the Mercury website
Parameters
[in] os The output stream (e.g. a file stream or cout)
Reimplemented in protectiveWall.
 {
     // line #1: time, volume fraction
     // line #2: wall box: wx0, wy0, wz0, wx1, wy1, wz1
     // line #3: radii-min-max & moments: rad_min, rad_max, r1, r2, r3, r4
     os << "#"
        << " " << getTime()
        << " " << 1 //marker that these are fstat files with contact point instead of center point
        << '\n';
     os << "#"
        << " " << getXMin()
        << " " << getYMin()
        << " " << getZMin()
        << " " << getXMax()
        << " " << getYMax()
        << " " << getZMax()
        << '\n';
     os << "#"
        << " ";
     if (!(particleHandler.getSmallestParticleLocal() == nullptr))
     {
         os << particleHandler.getSmallestParticleLocal()->getRadius();
     }
     else
     {
         os << std::numeric_limits<double>::quiet_NaN();
     }
     os << " ";
     if (!(particleHandler.getLargestParticleLocal() == nullptr))
     {
         os << particleHandler.getLargestParticleLocal()->getRadius();
     }
     else
     {
         os << std::numeric_limits<double>::quiet_NaN();
     }
     os << " " << 0
        << " " << 0
        << " " << 0
        << " " << 0
        << '\n';
     //B: write data
     for (BaseInteraction* c : interactionHandler)
     {
         c->writeToFStat(os, getTime());
     }
     //os << std::flush;
 }
References calibrate::c, ParticleHandler::getLargestParticleLocal(), BaseParticle::getRadius(), ParticleHandler::getSmallestParticleLocal(), getTime(), getXMax(), getXMin(), getYMax(), getYMin(), getZMax(), getZMin(), interactionHandler, and particleHandler.
Referenced by writeFStatFile().
writeOutputFiles()
void DPMBase::writeOutputFiles () virtual
Writes simulation data to all the main Mercury files: .data, .ene, .fstat, .xballs and .restart (see the Mercury website for more details regarding these files).
Writes headers and all relevant information to the relevant output files. Note that the writeFstatHeader() actually contains within it the functionality to write the full fstat data, whereas for .ene files the functions to write the headers and main data are separate. Note that the interaction file is not written here: it is written with the start and end of each interaction.
The function [X].saveCurrentTimeStep(numberOfTimeSteps_) returns true if:
a) The current time step is greater than or equal to the time step at which the next write or read operation is supposed to happen.
b) The FileType is not "NO_FILE".
c) The file is open.
Reimplemented in Mercury3DRestart, Mercury3DRestarter, CSCRestart, ClosedCSCRestart, StatisticsVector< T >, StatisticsVector< O >, and StatisticsVector< XZ >.
 {
     //writing fstat data if .saveCurrentTimeStep(numberOfTimeSteps_) is true
     if (fStatFile.saveCurrentTimeStep(numberOfTimeSteps_))
     {
         writeFStatFile();
     }
     //writing .ene data if .saveCurrentTimeStep(numberOfTimeSteps_) is true
     if (eneFile.saveCurrentTimeStep(numberOfTimeSteps_))
     {
         writeEneFile();
     }
     //writing .data data if .saveCurrentTimeStep(numberOfTimeSteps_) is true
     if (dataFile.saveCurrentTimeStepNoFileTypeCheck(numberOfTimeSteps_))
     {
         if (dataFile.getFileType() != FileType::NO_FILE) {
             if (getRestarted() || dataFile.getCounter() == 0)
                 writeXBallsScript();
             writeDataFile();
         } else {
             dataFile.setLastSavedTimeStep(numberOfTimeSteps_);
         }
         printTime();
         writeVTKFiles();
     }
     cgHandler.evaluate();
     //write restart file last, otherwise the output counters are wrong
     if (restartFile.saveCurrentTimeStep(numberOfTimeSteps_))
     {
         writeRestartFile();
     }
 }
References cgHandler, dataFile, eneFile, CGHandler::evaluate(), fStatFile, File::getCounter(), File::getFileType(), getRestarted(), NO_FILE, numberOfTimeSteps_, printTime(), restartFile, File::saveCurrentTimeStep(), File::saveCurrentTimeStepNoFileTypeCheck(), File::setLastSavedTimeStep(), writeDataFile(), writeEneFile(), writeFStatFile(), writeRestartFile(), writeVTKFiles(), and writeXBallsScript().
Referenced by computeOneTimeStep(), forceWriteOutputFiles(), ClosedCSCRestart::writeOutputFiles(), CSCRestart::writeOutputFiles(), Mercury3DRestarter::writeOutputFiles(), and Mercury3DRestart::writeOutputFiles().
writePythonFileForVTKVisualisation()
void DPMBase::writePythonFileForVTKVisualisation () const
writes .py file for ParaView
The function generates .py file with the same name as the simulation
 {
 #ifdef MERCURYDPM_USE_MPI
     if (PROCESSOR_ID == 0)
     {
 #endif
     logger(INFO, "Writing python script for paraview visualisation");
     std::string script = "#script to visualise the output of data2pvd of MercuryDPM in paraview.\n"
                          "#usage: change the path below to your own path, open paraview\n"
                          "#Tools->Python Shell->Run Script->VisualisationScript.py\n"
                          "#or run paraview --script=VisualisationScript.py \n"
                          "\n"
                          "from paraview.simple import *\n"
                          "import os\n"
                          "import glob\n"
                          "import re # for natural sorting\n\n"
                          "# Path to directory containing vtu files\n"
                          "# Hardcoded (for windows you might need to change start of path, for example: from /mnt/c/MyFolder to c:/MyFolder)\n"
                          "dirPath = '" + helpers::getPath() + "'\n"
                          "# Or directory containing this script\n"
                          "#dirPath = os.path.dirname(os.path.realpath(__file__))\n"
                          "# Change to directory\n"
                          "os.chdir(dirPath)\n\n";
     script += "# Some functions to achieve natural sorting for the numbering of the files (regardless of them being padded or not etc.)\n"
               "# See https://stackoverflow.com/questions/5967500/how-to-correctly-sort-a-string-with-a-number-inside for more info\n"
               "def atoi(text):\n"
               "\treturn int(text) if text.isdigit() else text\n"
               "\n"
               "def natural_keys(text):\n"
               "\treturn [ atoi(c) for c in re.split(r'(\\d+)', text) ]\n\n";
     script += "simName = '" + getName() + "' # name of the simulation\n\n";
     if (getParticlesWriteVTK())
     {
         const std::string dir = (vtkWriter_ ? vtkWriter_->getOutputDirectory() : ".");
 #ifdef MERCURYDPM_USE_MPI
         if (NUMBER_OF_PROCESSORS > 1)
         {
             script += "# PARTICLES ##########################################################\n"
                       "for processorNumber in range(0, " + std::to_string(NUMBER_OF_PROCESSORS) + "):\n"
                       "\t# Load data in any order and sort it\n"
                       "\tDataParticles = glob.glob('" + dir + "/' + simName + 'Processor_' + str(processorNumber) + '_Particle_*.vtu')\n"
                       "\tDataParticles.sort(key = natural_keys)"
                       "\t# Load the data and visualise it in paraview\n"
                       "\tparticles = XMLUnstructuredGridReader(FileName = DataParticles, registrationName = simName + 'Processor_' + str(processorNumber) + '_Particle_*')\n"
                       "\tglyphP = Glyph(particles, registrationName = 'Glyph Particle')\n" // From here on no differences with (non-)MPI
                       "\tglyphP.GlyphType = 'Sphere'\n"
                       "\tglyphP.ScaleArray = 'Radius'\n"
                       "\tglyphP.ScaleFactor = 2\n"
                       "\tglyphP.GlyphMode = 'All Points'\n"
                       "\tparticlesDisplay = Show(glyphP)\n"
                       "\t#ColorBy(particlesDisplay, ('POINTS', 'Velocity', 'Magnitude'))\n"
                       "\t#particlesDisplay.Opacity = 0.5\n"
                       "\n\n";
         }
         else
         {
 #endif
         script += "# PARTICLES ##########################################################\n"
                   "# Load data in any order and sort it\n"
                   "DataParticles = glob.glob('" + dir + "/' + simName + 'Particle_*.vtu')\n"
                   "DataParticles.sort(key = natural_keys)"
                   "# Load the data and visualise it in paraview\n"
                   "particles = XMLUnstructuredGridReader(FileName = DataParticles, registrationName = simName + 'Particle_*')\n"
                   "glyphP = Glyph(particles, registrationName = 'Glyph Particle')\n" // From here on no differences with (non-)MPI
                   "glyphP.GlyphType = 'Sphere'\n"
                   "glyphP.ScaleArray = 'Radius'\n"
                   "glyphP.ScaleFactor = 2\n"
                   "glyphP.GlyphMode = 'All Points'\n"
                   "particlesDisplay = Show(glyphP)\n"
                   "#ColorBy(particlesDisplay, ('POINTS', 'Velocity', 'Magnitude'))\n"
                   "#particlesDisplay.Opacity = 0.5\n"
                   "\n\n";
 #ifdef MERCURYDPM_USE_MPI
         }
 #endif
     }
     if (wallHandler.getWriteVTK() != FileType::NO_FILE)
     {
         const std::string dir = wallVTKWriter_.getOutputDirectory();
         script += "# WALLS ##############################################################\n"
                   "# Load data in any order and sort it\n"
                   "DataWalls = glob.glob('" + dir + "/' + simName + 'Wall_*.vtu')\n"
                   "DataWalls.sort(key = natural_keys)"
                   "# Load the data and visualise it in paraview\n"
                   "walls = XMLUnstructuredGridReader(FileName = DataWalls, registrationName = simName + 'Wall_*')\n"
                   "wallsDisplay = Show(walls)\n"
                   "#wallsDisplay.Opacity = 0.5\n"
                   "\n\n";
     }
     if (interactionHandler.getWriteVTK() != FileType::NO_FILE)
     {
         const std::string dir = interactionVTKWriter_.getOutputDirectory();
 #ifdef MERCURYDPM_USE_MPI
         if (NUMBER_OF_PROCESSORS > 1)
         {
             script += "# INTERACTIONS #######################################################\n"
                       "for processorNumber in range(0, " + std::to_string(NUMBER_OF_PROCESSORS) + "):\n"
                       "\t# Load data in any order and sort it\n"
                       "\tDataInteractions = glob.glob('" + dir + "/' + simName + 'Processor_' + str(processorNumber) + '_Interaction_*.vtu')\n"
                       "\tDataInteractions.sort(key = natural_keys)"
                       "\t# Load the data and visualise it in paraview\n"
                       "\tinteractions = XMLUnstructuredGridReader(FileName = DataInteractions, registrationName = simName + 'Processor_' + str(processorNumber) + '_Interaction_*')\n"
                       "\tglyphI = Glyph(interactions, registrationName = 'Glyph Interaction')\n" // From here on no differences with (non-)MPI
                       "\tglyphI.GlyphType = 'Arrow'\n"
                       "\tglyphI.OrientationArray = 'Normal'\n"
                       "\tglyphI.ScaleArray = 'Force'\n"
                       "\tglyphI.ScaleFactor = 0.01\n"
                       "\tglyphI.GlyphMode = 'All Points'\n"
                       "\tinteractionsDisplay = Show(glyphI)\n"
                       "\t#ColorBy(interactionsDisplay, ('POINTS', 'Force'))\n"
                       "\t#interactionsDisplay.Opacity = 0.5\n"
                       "\n\n";
         }
         else
         {
 #endif
         script += "# INTERACTIONS #######################################################\n"
                   "# Load data in any order and sort it\n"
                   "DataInteractions = glob.glob('" + dir + "/' + simName + 'Interaction_*.vtu')\n"
                   "DataInteractions.sort(key = natural_keys)"
                   "# Load the data and visualise it in paraview\n"
                   "interactions = XMLUnstructuredGridReader(FileName = DataInteractions, registrationName = simName + 'Interaction_*')\n"
                   "glyphI = Glyph(interactions, registrationName = 'Glyph Interaction')\n" // From here on no differences with (non-)MPI
                   "glyphI.GlyphType = 'Arrow'\n"
                   "glyphI.OrientationArray = 'Normal'\n"
                   "glyphI.ScaleArray = 'Force'\n"
                   "glyphI.ScaleFactor = 0.01\n"
                   "glyphI.GlyphMode = 'All Points'\n"
                   "interactionsDisplay = Show(glyphI)\n"
                   "#ColorBy(interactionsDisplay, ('POINTS', 'Force'))\n"
                   "#interactionsDisplay.Opacity = 0.5\n"
                   "\n\n";
 #ifdef MERCURYDPM_USE_MPI
         }
 #endif
     }
     if (wallHandler.getWriteDetailsVTK(WallHandler::DetailsVTKOptions::BOUNDINGBOX) != FileType::NO_FILE)
     {
         const std::string dir = wallDetailsVTKWriter_.getOutputDirectory();
         script += "# WALL DETAILS - BOUNDING BOX ########################################\n"
                   "# Load data in any order and sort it\n"
                   "DataWDBoundingBox = glob.glob('" + dir + "/' + simName + 'WallDetailsBoundingBox_*.vtu')\n"
                   "DataWDBoundingBox.sort(key = natural_keys)"
                   "# Load the data and visualise it in paraview\n"
                   "wdBoundingBox = XMLUnstructuredGridReader(FileName = DataWDBoundingBox, registrationName = simName + 'WallDetailsBoundingBox_*')\n"
                   "wdBoundingBoxDisplay = Show(wdBoundingBox)\n"
                   "wdBoundingBoxDisplay.Representation = 'Wireframe'\n"
                   "\n\n";
     }
     if (wallHandler.getWriteDetailsVTK(WallHandler::DetailsVTKOptions::NURBSWALL) != FileType::NO_FILE)
     {
         const std::string dir = wallDetailsVTKWriter_.getOutputDirectory();
         script += "# WALL DETAILS - NURBS WALL ##########################################\n"
                   "# Load data in any order and sort it\n"
                   "DataWDNurbsWall = glob.glob('" + dir + "/' + simName + 'WallDetailsNurbsWall_*.vtu')\n"
                   "DataWDNurbsWall.sort(key = natural_keys)"
                   "# Load the data and visualise it in paraview\n"
                   "wdNurbsWall = XMLUnstructuredGridReader(FileName = DataWDNurbsWall, registrationName = simName + 'WallDetailsNurbsWall_*')\n"
                   "wdNurbsWallDisplay = Show(wdNurbsWall)\n"
                   "wdNurbsWallDisplay.Representation = 'Wireframe'\n"
                   "ColorBy(wdNurbsWallDisplay, ('POINTS', 'ID'))\n"
                   "glyphWDNW = Glyph(wdNurbsWall, registrationName='Glyph NURBS Control Point')\n"
                   "glyphWDNW.GlyphType = 'Sphere'\n"
                   "glyphWDNW.ScaleArray = 'Weight'\n"
                   "glyphWDNW.ScaleFactor = 0.05\n"
                   "glyphWDNW.GlyphMode = 'All Points'\n"
                   "glyphWDNWDisplay = Show(glyphWDNW)\n"
                   "ColorBy(glyphWDNWDisplay, ('POINTS', 'ID'))\n"
                   "\n\n";
     }
     script += "GetAnimationScene().PlayMode = 'Snap To TimeSteps'\n"
               "Render()\n"
               "ResetCamera()\n";
     helpers::writeToFile(getName() + ".py", script);
 #ifdef MERCURYDPM_USE_MPI
     } // end of communicator is root statement
 #endif
 }
References WallHandler::BOUNDINGBOX, getName(), BaseVTKWriter< H >::getOutputDirectory(), getParticlesWriteVTK(), helpers::getPath(), WallHandler::getWriteDetailsVTK(), InteractionHandler::getWriteVTK(), WallHandler::getWriteVTK(), INFO, interactionHandler, interactionVTKWriter_, logger, NO_FILE, NUMBER_OF_PROCESSORS, WallHandler::NURBSWALL, PROCESSOR_ID, oomph::Global_string_for_annotation::string(), oomph::StringConversion::to_string(), vtkWriter_, wallDetailsVTKWriter_, wallHandler, wallVTKWriter_, and helpers::writeToFile().
Referenced by initialiseVTK().
writeRestartFile()
void DPMBase::writeRestartFile () virtual
Stores all the particle data for current save time step to a "restart" file, which is a file simply intended to store all the information necessary to "restart" a simulation from a given time step (see also MercuryDPM.org for more information on restart files).
Calls the write() function in order to output all relevant data (particle positions and velocities, system dimensions, positions of walls and boundaries...) to a restart file.
See also readRestartFile
Reimplemented in FlowRule, FlowRule, FlowRule, FlowRule, and FlowRule.
 {
     if (restartFile.openWriteNoAppend(getNumberOfTimeSteps()))
     {
         //logger(DEBUG, "Writing restart file %th time step",getNumberOfTimeSteps());
         write(restartFile.getFstream());
         restartFile.close();
     }
 }
References File::close(), File::getFstream(), getNumberOfTimeSteps(), File::openWriteNoAppend(), restartFile, and write().
Referenced by ParameterStudy1DDemo::actionsAfterSolve(), ParameterStudy2DDemo::actionsAfterSolve(), ParameterStudy3DDemo::actionsAfterSolve(), ChutePeriodic::add_flow_particles(), SilbertPeriodic::add_flow_particles(), main(), AngleOfRepose::run(), vibratedBed::run(), CSCInit::save(), RotatingDrumBidisperseInitialise::save(), ClosedCSCWalls::saveWalls(), CSCWalls::saveWalls(), statistics_while_running< T >::statistics_while_running(), writeOutputFiles(), and FlowRule::writeRestartFile().
writeVTKFiles()
void DPMBase::writeVTKFiles () const protected
 {
     if (wallHandler.getWriteVTK() == FileType::ONE_FILE && wallVTKWriter_.getFileCounter() == 0)
     {
         wallVTKWriter_.writeVTK();
     } else if (wallHandler.getWriteVTK() == FileType::MULTIPLE_FILES
         || wallHandler.getWriteVTK() == FileType::MULTIPLE_FILES_PADDED) {
         wallVTKWriter_.writeVTK();
     } // else do nothing
     if (getParticlesWriteVTK() || getSuperquadricParticlesWriteVTK())
     {
         vtkWriter_->writeVTK();
     }  // else do nothing
     if (interactionHandler.getWriteVTK() != FileType::NO_FILE)
     {
         interactionVTKWriter_.writeVTK();
     }
     if (boundaryHandler.getWriteVTK())
     {
         boundaryVTKWriter_.writeVTK();
     }
     if (wallHandler.getWriteDetailsVTKAny())
     {
         wallDetailsVTKWriter_.writeVTK();
     }
 }
References boundaryHandler, boundaryVTKWriter_, BaseVTKWriter< H >::getFileCounter(), getParticlesWriteVTK(), getSuperquadricParticlesWriteVTK(), WallHandler::getWriteDetailsVTKAny(), BoundaryHandler::getWriteVTK(), InteractionHandler::getWriteVTK(), WallHandler::getWriteVTK(), interactionHandler, interactionVTKWriter_, MULTIPLE_FILES, MULTIPLE_FILES_PADDED, NO_FILE, ONE_FILE, vtkWriter_, wallDetailsVTKWriter_, wallHandler, wallVTKWriter_, BaseVTKWriter< H >::writeVTK(), BoundaryVTKWriter::writeVTK(), InteractionVTKWriter::writeVTK(), WallDetailsVTKWriter::writeVTK(), and WallVTKWriter::writeVTK().
Referenced by GetDistanceAndNormalForScrew::setupInitialConditions(), GetDistanceAndNormalForTriangleWall::setupInitialConditions(), MyCoil::setupInitialConditions(), Nurbs::setupInitialConditions(), Polygon::setupInitialConditions(), Silo::setupInitialConditions(), GetDistanceAndNormalForTriangleWalls::setupInitialConditions(), and writeOutputFiles().
writeXBallsScript()
virtual void DPMBase::writeXBallsScript () const virtual
This writes a script which can be used to load the xballs problem to display the data just generated.
Todo:
Implement or make pure virtual
Reimplemented in ChuteWithPeriodicInflow.
Referenced by ClosedCSCRun::ClosedCSCRun(), CSCInit::CSCInit(), RotatingDrumBidisperse::RotatingDrumBidisperse(), CSCRun::setupInitialConditions(), and writeOutputFiles().
Member Data Documentation
append_
bool DPMBase::append_ private
A flag to determine if the file has to be appended or not. See DPMBase::Solve() for example.
Referenced by DPMBase(), getAppend(), and setAppend().
backgroundDrag_
Mdouble DPMBase::backgroundDrag_ private
This is a global background drag to help retard particles, or to do a simple fluid drag. The force particleVeclocity*backgroundDrag is applied.
Referenced by DPMBase(), getBackgroundDrag(), read(), and setBackgroundDrag().
boundaryHandler
BoundaryHandler DPMBase::boundaryHandler
An object of the class BoundaryHandler which concerns insertion and deletion of particles into or from regions.
Referenced by T_protectiveWall::actionsAfterTimeStep(), GranuHeap::actionsAfterTimeStep(), LeesEdwardsDemo::actionsAfterTimeStep(), ShiftingConstantMassFlowMaserBoundarySelfTest::actionsAfterTimeStep(), ShiftingMaserBoundarySelfTest::actionsAfterTimeStep(), TimeDependentPeriodicBoundary3DSelfTest::actionsAfterTimeStep(), TimeDependentPeriodicBoundaryTest::actionsAfterTimeStep(), Chutebelt::actionsAfterTimeStep(), BoundariesSelfTest::actionsAfterTimeStep(), PolydisperseInsertionBoundarySelfTest::actionsAfterTimeStep(), GranularCollapse::actionsAfterTimeStep(), protectiveWall::actionsAfterTimeStep(), SilbertPeriodic::add_flow_particles(), AngledPeriodicBoundarySecondUnitTest::AngledPeriodicBoundarySecondUnitTest(), AngledPeriodicBoundaryUnitTest::AngledPeriodicBoundaryUnitTest(), BoundariesSelfTest::BoundariesSelfTest(), ChuteWithPeriodicInflow::Check_and_Duplicate_Periodic_Particle(), checkAndDuplicatePeriodicParticles(), Mercury3Dclump::checkClumpForInteractionPeriodic(), checkInteractionWithBoundaries(), checkParticleForInteractionLocalPeriodic(), ChutePeriodicDemo::ChutePeriodicDemo(), ChuteWithContraction::ChuteWithContraction(), ChuteWithPeriodicInflowAndContraction::ChuteWithPeriodicInflowAndContraction(), ClosedCSCWalls::ClosedCSCWalls(), Mercury3Dclump::computeAllForces(), computeOneTimeStep(), constructor(), ContractionWithPeriodicInflow::ContractionWithPeriodicInflow(), Funnel::create_walls(), CSCWalls::CSCWalls(), DPMBase(), ChuteWithPeriodicInflow::ExtendInWidth(), FluxAndPeriodicBoundarySelfTest::FluxAndPeriodicBoundarySelfTest(), FluxBoundarySelfTest::FluxBoundarySelfTest(), GranuDrum::GranuDrum(), InitialConditions< SpeciesType >::InitialConditions(), initialiseSolve(), initialiseVTK(), ChuteWithPeriodicInflow::integrateBeforeForceComputation(), LeesEdwardsSelfTest::LeesEdwardsSelfTest(), main(), protectiveWall::protectiveWall(), read(), readOld(), readParAndIniFiles(), RotatingDrumBidisperseInitialise::RotatingDrumBidisperseInitialise(), ChutePeriodic::setupInitialConditions(), MercuryLogo::setupInitialConditions(), ChangingTOIParticle::setupInitialConditions(), RandomClusterInsertionBoundarySelfTest::setupInitialConditions(), my_problem::setupInitialConditions(), NozzleDemo::setupInitialConditions(), Drum::setupInitialConditions(), RotatingDrumWet::setupInitialConditions(), VerticalMixer::setupInitialConditions(), InsertionBoundaryMPI2Test::setupInitialConditions(), MaserRepeatedOutInMPI2Test::setupInitialConditions(), MpiPeriodicBoundaryUnitTest::setupInitialConditions(), PeriodicBounaryEnteringMPIDomainTest::setupInitialConditions(), SubcriticalMaserBoundaryTESTMPI2Test::setupInitialConditions(), CubicCell::setupInitialConditions(), FreeCooling2DinWalls::setupInitialConditions(), FreeCooling3DDemoProblem::setupInitialConditions(), FreeCoolingDemoProblem::setupInitialConditions(), HeaterBoundaryTest::setupInitialConditions(), LeesEdwardsDemo::setupInitialConditions(), MinimalExampleDrum::setupInitialConditions(), StressStrainControl::setupInitialConditions(), ShiftingConstantMassFlowMaserBoundarySelfTest::setupInitialConditions(), ShiftingMaserBoundarySelfTest::setupInitialConditions(), TimeDependentPeriodicBoundary3DSelfTest::setupInitialConditions(), TimeDependentPeriodicBoundaryTest::setupInitialConditions(), Cstatic2d::setupInitialConditions(), SilbertPeriodic::setupInitialConditions(), Silo::setupInitialConditions(), Chutebelt::setupInitialConditions(), SingleParticleSegregation::setupInitialConditions(), ConstantMassFlowMaserBoundaryMixedSpeciesSelfTest::setupInitialConditions(), ConstantMassFlowMaserSelfTest::setupInitialConditions(), CubeDeletionBoundarySelfTest::setupInitialConditions(), DeletionBoundarySelfTest::setupInitialConditions(), DistributionPhiNormalSelfTest::setupInitialConditions(), DistributionSelfTest::setupInitialConditions(), DistributionToPSDSelfTest::setupInitialConditions(), InsertionBoundarySelfTest::setupInitialConditions(), MultiplePSDSelfTest::setupInitialConditions(), NozzleSelfTest::setupInitialConditions(), clumpTest::setupInitialConditions(), PolydisperseInsertionBoundarySelfTest::setupInitialConditions(), PSDManualInsertionSelfTest::setupInitialConditions(), SubcriticalMaserBoundarySelfTest::setupInitialConditions(), TriangulatedScrewSelfTest::setupInitialConditions(), ScalingTestInitialConditionsRelax::setupInitialConditions(), ScalingTestRun::setupInitialConditions(), Tutorial6::setupInitialConditions(), Packing::setupInitialConditions(), PSDSelfTest::setupInitialConditions(), FluxBoundaryPrescribedDistanceUnitTest::setupInitialConditions(), FluxBoundaryUnitTest::setupInitialConditions(), FullRestartTest::setupInitialConditions(), MD_demo::setupInitialConditions(), MpiMaserChuteTest::setupInitialConditions(), PeriodicWalls::setupInitialConditions(), PeriodicWallsWithSlidingFrictionUnitTest::setupInitialConditions(), SetDistributionPhiNormalSelfTest::setupInitialConditions(), Chute::setupInitialConditions(), ChuteBottom::setupInitialConditions(), ChuteWithHopper::setupInitialConditions(), Chute::setupSideWalls(), ShearStage::ShearStage(), T_protectiveWall::T_protectiveWall(), write(), and writeVTKFiles().
boundaryVTKWriter_
BoundaryVTKWriter DPMBase::boundaryVTKWriter_ private
Referenced by initialiseVTK(), read(), removeOldFiles(), resetFileCounter(), setVTKOutputDirectory(), write(), and writeVTKFiles().
cgHandler
CGHandler DPMBase::cgHandler
Object of the class cgHandler.
Referenced by CGExactOverlapUnitTest::clear(), commandLineCG(), constructor(), DPMBase(), finishStatistics(), initialiseStatistics(), main(), setSaveCount(), Packing::test(), and writeOutputFiles().
clock_
Time DPMBase::clock_
record when the simulation started
Referenced by getCPUTime(), getWallTime(), and solve().
continueFlag_
volatile sig_atomic_t DPMBase::continueFlag_ = true static private
Stores whether code should continue solving, see discontinueSolve.
Referenced by discontinueSolve(), signalHandler(), and solve().
dataFile
File DPMBase::dataFile
An instance of class File to handle in- and output into a .data file.
Referenced by RotatingDrumWet::actionsAfterTimeStep(), OneParticleCoolingSelfTest::actionsAfterTimeStep(), ParameterStudy1DDemo::actionsBeforeTimeLoop(), ParameterStudy2DDemo::actionsBeforeTimeLoop(), ParameterStudy3DDemo::actionsBeforeTimeLoop(), ThermalConductionSelfTest::actionsBeforeTimeStep(), BaseCluster::actionsOnRestart(), NautaMixer::addSpeciesAndSetTimeStepAndSaveCount(), BoundariesSelfTest::BoundariesSelfTest(), ClosedCSCRun::ClosedCSCRun(), closeFiles(), commandLineCG(), ChuteBottom::constructor(), constructor(), InitialBed::continueSolve(), CGHandler::evaluateDataFiles(), CGHandler::evaluateRestartFiles(), findNextExistingDataFile(), FluxAndPeriodicBoundarySelfTest::FluxAndPeriodicBoundarySelfTest(), FluxBoundarySelfTest::FluxBoundarySelfTest(), getDataFile(), CLiveStatistics< T >::getLiveStatistics(), ChuteWithPeriodicInflow::integrateBeforeForceComputation(), LeesEdwardsDemo::LeesEdwardsDemo(), LeesEdwardsSelfTest::LeesEdwardsSelfTest(), main(), MultiParticlesInsertion::MultiParticlesInsertion(), read(), readDataFile(), readNextArgument(), readNextDataFile(), readOld(), readParAndIniFiles(), BaseWall::renderWall(), resetFileCounter(), CGHandler::restart(), FlowRule::run(), statistics_while_running< T >::run(), AngleOfRepose::run(), CSCInit::save(), RotatingDrumBidisperseInitialise::save(), SaveCountUnitTest::SaveCountUnitTest(), ClosedCSCWalls::saveWalls(), CSCWalls::saveWalls(), AngleOfRepose::set_study(), SilbertPeriodic::set_study(), setFileType(), setLastSavedTimeStep(), setLogarithmicSaveCount(), FlowRule::setName(), setName(), setOpenMode(), Calibration::setOutput(), setSaveCount(), ChutePeriodic::setup(), ShiftingConstantMassFlowMaserBoundarySelfTest::setupInitialConditions(), ShiftingMaserBoundarySelfTest::setupInitialConditions(), ChutePeriodic::setupInitialConditions(), Cstatic3D::setupInitialConditions(), GetDistanceAndNormalForIntersectionOfWalls::setupInitialConditions(), GetDistanceAndNormalForScrew::setupInitialConditions(), GetDistanceAndNormalForTriangleWall::setupInitialConditions(), DistributionToPSDSelfTest::setupInitialConditions(), InsertionBoundarySelfTest::setupInitialConditions(), MultiplePSDSelfTest::setupInitialConditions(), PolydisperseInsertionBoundarySelfTest::setupInitialConditions(), PSDManualInsertionSelfTest::setupInitialConditions(), ContactDetectionIntersectionOfWallsTest::setupInitialConditions(), GetDistanceAndNormalForTriangleWalls::setupInitialConditions(), RollingOverTriangleWalls::setupInitialConditions(), Packing::setupInitialConditions(), PSDSelfTest::setupInitialConditions(), RandomClusterInsertionBoundarySelfTest::setupInitialConditions(), HertzianSinterForceUnitTest::setupInitialConditions(), BaseCluster::setupInitialConditions(), SilbertHstop::SilbertHstop(), SilbertPeriodic::SilbertPeriodic(), statistics_while_running< T >::statistics_while_running(), TimeDependentPeriodicBoundary3DSelfTest::TimeDependentPeriodicBoundary3DSelfTest(), TimeDependentPeriodicBoundaryTest::TimeDependentPeriodicBoundaryTest(), write(), writeDataFile(), writeOutputFiles(), and ChuteWithPeriodicInflow::writeXBallsScript().
disableSoftStop_
bool DPMBase::disableSoftStop_ = false private
Stores whether the soft stop should not be initialised.
Referenced by disableSoftStop(), and setSoftStop().
domainHandler
DomainHandler DPMBase::domainHandler
An object of the class DomainHandler which deals with parallel code.
Referenced by constructor(), SubcriticalMaserBoundaryTEST::copyExtraParticles(), decompose(), deleteGhostParticles(), DPMBase(), SubcriticalMaserBoundaryTEST::extendBottom(), PeriodicBoundaryHandler::findTargetProcessor(), getCurrentDomain(), PeriodicBoundaryHandler::getMPIFlags(), ParticleHandler::getNumberOfRealObjectsLocal(), insertGhostParticle(), mpiInsertParticleCheck(), mpiIsInCommunicationZone(), performGhostParticleUpdate(), ForceLawsMPI2Test::printTime(), read(), and updateGhostGrid().
eneFile
File DPMBase::eneFile
An instance of class File to handle in- and output into a .ene file.
Referenced by BaseCluster::actionsOnRestart(), closeFiles(), ChuteWithPeriodicInflow::computeInternalForces(), ChuteBottom::constructor(), constructor(), ForceLawsMPI2Test::ForceLawsMPI2Test(), getEneFile(), LiquidMigrationMPI2Test::LiquidMigrationMPI2Test(), main(), read(), readNextArgument(), readOld(), resetFileCounter(), FlowRule::run(), statistics_while_running< T >::run(), AngleOfRepose::run(), setFileType(), setLastSavedTimeStep(), setLogarithmicSaveCount(), setName(), setOpenMode(), Calibration::setOutput(), setSaveCount(), RandomClusterInsertionBoundarySelfTest::setupInitialConditions(), ChutePeriodic::setupInitialConditions(), Cstatic3D::setupInitialConditions(), Drum::setupInitialConditions(), Penetration::setupInitialConditions(), Silo::setupInitialConditions(), CubeDeletionBoundarySelfTest::setupInitialConditions(), DeletionBoundarySelfTest::setupInitialConditions(), BaseCluster::setupInitialConditions(), SilbertPeriodic::SilbertPeriodic(), statistics_while_running< T >::statistics_while_running(), Tutorial11::Tutorial11(), TwoByTwoMPIDomainMPI4Test::TwoByTwoMPIDomainMPI4Test(), write(), writeEneFile(), writeEneTimeStep(), Drum::writeEneTimeStep(), Penetration::writeEneTimeStep(), Silo::writeEneTimeStep(), and writeOutputFiles().
forceWritePythonFileForVTKVisualisation_
bool DPMBase::forceWritePythonFileForVTKVisualisation_ { true } private
Referenced by getWritePythonFileForVTKVisualisation(), initialiseVTK(), and setWritePythonFileForVTKVisualisation().
fStatFile
File DPMBase::fStatFile
An instance of class File to handle in- and output into a .fstat file.
Referenced by ChuteRestartDemo::actionsOnRestart(), BaseCluster::actionsOnRestart(), AxisymmetricWallSelfTest::AxisymmetricWallSelfTest(), BoundariesSelfTest::BoundariesSelfTest(), closeFiles(), ChuteWithPeriodicInflow::computeInternalForces(), ChuteBottom::constructor(), constructor(), CGHandler::evaluateDataFiles(), FluxAndPeriodicBoundarySelfTest::FluxAndPeriodicBoundarySelfTest(), FluxBoundarySelfTest::FluxBoundarySelfTest(), ForceLawsMPI2Test::ForceLawsMPI2Test(), getFStatFile(), CLiveStatistics< T >::getLiveStatistics(), HorizontalMixer::HorizontalMixer(), InitialConditions< SpeciesType >::InitialConditions(), LeesEdwardsDemo::LeesEdwardsDemo(), LeesEdwardsSelfTest::LeesEdwardsSelfTest(), LiquidMigrationMPI2Test::LiquidMigrationMPI2Test(), main(), ParticleParticleCollision::ParticleParticleCollision(), read(), readNextArgument(), readNextFStatFile(), readOld(), readParAndIniFiles(), resetFileCounter(), FlowRule::run(), statistics_while_running< T >::run(), AngleOfRepose::run(), setFileType(), setLastSavedTimeStep(), setLogarithmicSaveCount(), setName(), setOpenMode(), setSaveCount(), ChutePeriodic::setup(), RandomClusterInsertionBoundarySelfTest::setupInitialConditions(), MarbleRun::setupInitialConditions(), ChutePeriodic::setupInitialConditions(), Cstatic3D::setupInitialConditions(), Drum::setupInitialConditions(), HertzSelfTest::setupInitialConditions(), Penetration::setupInitialConditions(), Silo::setupInitialConditions(), CubeDeletionBoundarySelfTest::setupInitialConditions(), DeletionBoundarySelfTest::setupInitialConditions(), RollingOverTriangleWalls::setupInitialConditions(), UnionOfWalls::setupInitialConditions(), SingleParticle< SpeciesType >::setupInitialConditions(), Packing::setupInitialConditions(), MovingWalls::setupInitialConditions(), BaseCluster::setupInitialConditions(), SilbertHstop::SilbertHstop(), SilbertPeriodic::SilbertPeriodic(), statistics_while_running< T >::statistics_while_running(), TimeDependentPeriodicBoundary3DSelfTest::TimeDependentPeriodicBoundary3DSelfTest(), TimeDependentPeriodicBoundaryTest::TimeDependentPeriodicBoundaryTest(), TriangulatedScrewSelfTest::TriangulatedScrewSelfTest(), TriangulatedStepWallSelfTest::TriangulatedStepWallSelfTest(), TriangulatedWallSelfTest::TriangulatedWallSelfTest(), Tutorial11::Tutorial11(), TwoByTwoMPIDomainMPI4Test::TwoByTwoMPIDomainMPI4Test(), write(), writeFStatFile(), and writeOutputFiles().
gravity_
Vec3D DPMBase::gravity_ private
Gravity vector.
Referenced by DPMBase(), getGravity(), read(), readOld(), and setGravity().
interactionFile
File DPMBase::interactionFile
File class to handle in- and output into .interactions file. This file hold information about interactions.
Referenced by closeFiles(), ChuteBottom::constructor(), constructor(), getInteractionFile(), read(), resetFileCounter(), setName(), setOpenMode(), and write().
interactionHandler
InteractionHandler DPMBase::interactionHandler
An object of the class InteractionHandler.
Referenced by ForceLawsMPI2Test::actionsAfterSolve(), Contact::actionsAfterSolve(), TwoByTwoMPIDomainMPI4Test::actionsAfterTimeStep(), SlidingSpheresUnitTest::actionsAfterTimeStep(), SphericalSuperQuadricCollision::actionsAfterTimeStep(), ContactDetectionNormalSpheresTest::actionsAfterTimeStep(), ContactDetectionRotatedSpheresTest::actionsAfterTimeStep(), MercuryProblem::actionsAfterTimeStep(), ForceLawsMPI2Test::actionsBeforeTimeStep(), MeltableForceLaw2SelfTest::actionsBeforeTimeStep(), MeltableForceLawSelfTest::actionsBeforeTimeStep(), ThermalConductionSelfTest::actionsBeforeTimeStep(), ConstantRestitutionSelfTest::actionsBeforeTimeStep(), QuaternionWallUnitTest::actionsBeforeTimeStep(), PeriodicWallsWithSlidingFrictionUnitTest::actionsBeforeTimeStep(), SilbertPeriodic::add_flow_particles(), FixedClusterInsertionBoundary::checkBoundaryBeforeTimeStep(), RandomClusterInsertionBoundary::checkBoundaryBeforeTimeStep(), PeriodicBoundaryHandler::collectInteractionData(), computeAllForces(), DPM::computeAllForcesNoHGrid(), computeForcesDueToWalls(), computeInternalForce(), computeOneTimeStep(), constructor(), BaseCluster::createAdjacencyMatrix(), DPMBase(), CGHandler::evaluateDataFiles(), CGHandler::evaluateRestartFiles(), Domain::finaliseBoundaryDataTransmission(), gatherContactStatistics(), getElasticEnergy(), LiquidMigrationPeriodicBoundaryInteraction::getLiquidBridgeVolume(), Sintering::getMeanPlasticOverlap(), InitialConditions< SpeciesType >::getMeanRelativeContactRadius(), Sintering::getMeanRelativeContactRadius(), regimeForceUnitTest::getMeanRelativeContactRadius(), getStaticStress(), importParticlesAs(), initialiseSolve(), initialiseVTK(), main(), BaseCluster::makeDataAnalysis(), BaseCluster::makeGnuplotFile(), outputInteractionDetails(), LiquidMigrationMPI2Test::outputXBallsData(), LiquidMigrationSelfTest::outputXBallsData(), Domain::performBoundaryDataTransmission(), PeriodicBoundaryHandler::performNewParticleTransmission(), GranuDrum::printTime(), Drum::printTime(), RotatingDrumWet::printTime(), ForceLawsMPI2Test::printTime(), LiquidMigrationMPI2Test::printTime(), ParticleInclusion::printTime(), MeltableForceLaw2SelfTest::printTime(), MeltableForceLawSelfTest::printTime(), ThermalConductionSelfTest::printTime(), RotatingDrumBidisperse::printTime(), LiquidMigrationSelfTest::printTime(), TwoParticleElasticCollisionInteraction::printTime(), EvaporationAndHeatTest::printTime(), PeriodicBoundaryHandler::processLocalInteractionData(), PeriodicBoundaryHandler::processReceivedInteractionData(), Domain::processReceivedInteractionData(), FileReader::read(), read(), readNextDataFile(), readNextFStatFile(), removeDuplicatePeriodicParticles(), CGHandler::restart(), CSCWalls::saveWalls(), setInteractionsWriteVTK(), setTime(), ExtremeOverlapVolumeUnitTest::setupInitialConditions(), RotatingDrumWet::setupInitialConditions(), MeltableForceLawSelfTest::setupInitialConditions(), ThermalConductionSelfTest::setupInitialConditions(), ChargedBondedInteractionSelfTest::setupInitialConditions(), TwoBondedParticleElasticCollision::setupInitialConditions(), GetDistanceAndNormalForTriangleWalls::setupInitialConditions(), UnionOfWalls::setupInitialConditions(), ArcWallUnitTest::setupInitialConditions(), ChargedBondedParticleUnitTest::setupInitialConditions(), MovingWalls::setupInitialConditions(), MultiParticlesInsertion::setupInitialConditions(), ContactDetectionTester::testEllipsoidsContact(), ContactDetectionWithWallTester::testEllipsoidsContact(), ContactDetectionTester::testSpheresContact(), ContactDetectionWithWallTester::testSpheresContact(), write(), BaseCluster::writeAmatFile(), SingleParticle< SpeciesType >::writeEneTimeStep(), SlidingFrictionUnitTest::writeEneTimeStep(), writeFstatHeader(), writePythonFileForVTKVisualisation(), BaseCluster::writeToOverlFile(), and writeVTKFiles().
interactionVTKWriter_
InteractionVTKWriter DPMBase::interactionVTKWriter_ private
Referenced by initialiseVTK(), read(), removeOldFiles(), resetFileCounter(), setVTKOutputDirectory(), write(), writePythonFileForVTKVisualisation(), and writeVTKFiles().
max_
Vec3D DPMBase::max_ private
Referenced by constructor(), DPMBase(), getMax(), getXCenter(), getXMax(), getYCenter(), getYMax(), getZCenter(), getZMax(), read(), readNextDataFile(), readOld(), setDomain(), setMax(), setMin(), setXMax(), setYMax(), and setZMax().
min_
Vec3D DPMBase::min_ private
These vectors are used for the XBalls domain, and occasionally people use it to add walls.
Referenced by constructor(), DPMBase(), getMin(), getXCenter(), getXMin(), getYCenter(), getYMin(), getZCenter(), getZMin(), read(), readNextDataFile(), readOld(), setDomain(), setMax(), setMin(), setXMin(), setYMin(), and setZMin().
name_
std::string DPMBase::name_ private
the name of the problem, used, e.g., for the output files
Referenced by constructor(), getName(), read(), setName(), and write().
nToWrite_
int DPMBase::nToWrite_ private
number of elements to write to a screen
Referenced by constructor(), getNToWrite(), and setNToWrite().
numberOfDomains_
std::vector<unsigned> DPMBase::numberOfDomains_ private
Vector containing the number of domains in x-,y- and z-direction, required for parallel computations.
Referenced by constructor(), decompose(), DPMBase(), getNumberOfDomains(), read(), setNumberOfDomains(), and write().
numberOfOMPThreads_
int DPMBase::numberOfOMPThreads_ private
Referenced by constructor(), DPMBase(), getNumberOfOMPThreads(), and setNumberOfOMPThreads().
numberOfTimeSteps_
unsigned int DPMBase::numberOfTimeSteps_ private
Stores the number of time steps.
Referenced by computeOneTimeStep(), constructor(), DPMBase(), getNumberOfTimeSteps(), initialiseSolve(), read(), write(), and writeOutputFiles().
paoloParticleHandler
ParticleHandler DPMBase::paoloParticleHandler
Fake particleHandler created by Paolo needed temporary by just Paolo.
particleDimensions_
unsigned int DPMBase::particleDimensions_ private
determines if 2D or 3D particle volume is used for mass calculations
Referenced by DPMBase(), getParticleDimensions(), read(), and setParticleDimensions().
particleHandler
ParticleHandler DPMBase::particleHandler
An object of the class ParticleHandler, contains the pointers to all the particles created.
Referenced by DPM::actionsAfterSolve(), MaserRepeatedOutInMPI2Test::actionsAfterSolve(), PSDManualInsertionSelfTest::actionsAfterSolve(), HertzianBSHPInteractionTwoParticleElasticCollision::actionsAfterSolve(), Contact::actionsAfterSolve(), EllipsoidsBouncingOnWallDemo::actionsAfterSolve(), EllipticalSuperQuadricCollision::actionsAfterSolve(), SphericalSuperQuadricCollision::actionsAfterSolve(), VisualisationTest::actionsAfterSolve(), SpeciesTest::actionsAfterSolve(), BaseCluster::actionsAfterSolve(), ShearStage::actionsAfterTimeStep(), ClosedCSCRestart::actionsAfterTimeStep(), ClosedCSCRun::actionsAfterTimeStep(), ChangingTOIParticle::actionsAfterTimeStep(), RotatingDrumWet::actionsAfterTimeStep(), TwoByTwoMPIDomainMPI4Test::actionsAfterTimeStep(), CubicCell::actionsAfterTimeStep(), LeesEdwardsDemo::actionsAfterTimeStep(), ShiftingConstantMassFlowMaserBoundarySelfTest::actionsAfterTimeStep(), ShiftingMaserBoundarySelfTest::actionsAfterTimeStep(), TimeDependentPeriodicBoundary3DSelfTest::actionsAfterTimeStep(), TimeDependentPeriodicBoundaryTest::actionsAfterTimeStep(), vibratedBed::actionsAfterTimeStep(), OneParticleHeatingSelfTest::actionsAfterTimeStep(), OneParticleCoolingSelfTest::actionsAfterTimeStep(), RotatingDrumBidisperseInitialise::actionsAfterTimeStep(), SingleParticleSegregation::actionsAfterTimeStep(), BoundariesSelfTest::actionsAfterTimeStep(), FluxAndPeriodicBoundarySelfTest::actionsAfterTimeStep(), FluxBoundarySelfTest::actionsAfterTimeStep(), PolydisperseInsertionBoundarySelfTest::actionsAfterTimeStep(), DPM::actionsAfterTimeStep(), BouncingSuperQuadric::actionsAfterTimeStep(), GranularCollapse::actionsAfterTimeStep(), SlidingSpheresUnitTest::actionsAfterTimeStep(), SphericalSuperQuadricCollision::actionsAfterTimeStep(), ContactDetectionNormalSpheresTest::actionsAfterTimeStep(), ContactDetectionRotatedSpheresTest::actionsAfterTimeStep(), MercuryProblem::actionsAfterTimeStep(), DrivenParticleClass::actionsAfterTimeStep(), Slide::actionsBeforeTimeLoop(), LawinenBox::actionsBeforeTimeStep(), DPM::actionsBeforeTimeStep(), SmoothChute::actionsBeforeTimeStep(), AngleOfRepose::actionsBeforeTimeStep(), MeltableForceLaw2SelfTest::actionsBeforeTimeStep(), MeltableForceLawSelfTest::actionsBeforeTimeStep(), ThermalConductionSelfTest::actionsBeforeTimeStep(), Slide::actionsBeforeTimeStep(), Chutebelt::actionsBeforeTimeStep(), PeriodicWallsWithSlidingFrictionUnitTest::actionsBeforeTimeStep(), Chutebelt::actionsOnRestart(), ConstantMassFlowMaserBoundary::activateMaser(), SubcriticalMaserBoundary::activateMaser(), SubcriticalMaserBoundaryTEST::activateMaser(), ChutePeriodic::add_flow_particles(), SilbertPeriodic::add_flow_particles(), ChuteWithPeriodicInflow::AddContinuingBottom(), Chute::addFlowParticlesCompactly(), ChuteWithHopper::addHopper(), SingleParticleSegregation::addIntruderParticle(), SpeciesHandler::addObject(), NautaMixer::addParticles(), NautaMixer::addParticlesAtWall(), BaseWall::addParticlesAtWall(), BaseCluster::applyCentralForce(), statistics_while_running< T >::auto_set_domain(), statistics_while_running< T >::auto_set_z(), Membrane::buildMesh(), CFDDEMCoupleTest::CalcPhiPAndFz(), ChuteWithPeriodicInflow::Check_and_Duplicate_Periodic_Particle(), checkAndDuplicatePeriodicParticles(), FixedClusterInsertionBoundary::checkBoundaryBeforeTimeStep(), RandomClusterInsertionBoundary::checkBoundaryBeforeTimeStep(), Mercury3Dclump::checkClumpForInteraction(), Mercury3Dclump::checkClumpForInteractionPeriodic(), checkInteractionWithBoundaries(), checkParticleForInteractionLocal(), checkParticleForInteractionLocalPeriodic(), checkSettings(), ChuteWithContraction::ChuteWithContraction(), ChuteWithPeriodicInflowAndContinuingBottom::ChuteWithPeriodicInflowAndContinuingBottom(), ChuteWithPeriodicInflowAndContraction::ChuteWithPeriodicInflowAndContraction(), ChuteWithPeriodicInflowAndVariableBottom::ChuteWithPeriodicInflowAndVariableBottom(), ChuteWithPeriodicInflow::cleanChute(), ChuteWithContraction::cleanChute(), Funnel::cleanChute(), Chute::cleanChute(), ContactDetectionTester::cleanup(), CGExactOverlapUnitTest::clear(), PeriodicBoundaryHandler::clearCommunicationLists(), ClosedCSCRestart::ClosedCSCRestart(), ClosedCSCRun::ClosedCSCRun(), computeAllForces(), Mercury3Dclump::computeAllForces(), DPM::computeAllForcesNoHGrid(), computeInternalForces(), ChuteWithPeriodicInflow::computeInternalForces(), DPM::computeLocalVolumeFraction(), computeOneTimeStep(), computeWallForces(), constructor(), MercuryLogo::constructTextAsParticles(), ScalingTestInitialConditionsRelax::continueSolve(), ContractionWithPeriodicInflow::ContractionWithPeriodicInflow(), SubcriticalMaserBoundaryTEST::copyExtraParticles(), Funnel::create_funnel(), Slide::create_rough_wall(), BaseCluster::createAdjacencyMatrix(), AngleOfRepose::createBaseSpecies(), SilbertPeriodic::createBaseSpecies(), Chute::createBottom(), CurvyChute::createBottom(), PeriodicBoundary::createGhostParticle(), TimeDependentPeriodicBoundary::createGhostParticle(), Membrane::createVertexParticles(), CSCInit::CSCInit(), BaseCluster::dampVelocities(), decompose(), deleteGhostParticles(), DPM::DPM(), DPMBase(), CGHandler::evaluateDataFiles(), CGHandler::evaluateRestartFiles(), SubcriticalMaserBoundaryTEST::extendBottom(), ChuteWithPeriodicInflow::ExtendInWidth(), fillDomainWithParticles(), FluxAndPeriodicBoundarySelfTest::FluxAndPeriodicBoundarySelfTest(), SphericalIndenter::getBedHeight(), getCentreOfMass(), getGravitationalEnergy(), MercuryBase::getHGridTargetMaxInteractionRadius(), MercuryBase::getHGridTargetMinInteractionRadius(), MercuryBase::getHGridTargetNumberOfBuckets(), getKineticEnergy(), getKineticStress(), LiquidMigrationPeriodicBoundaryInteraction::getLiquidFilmVolume(), InitialConditions< SpeciesType >::getMeanRelativeContactRadius(), Sintering::getMeanRelativeContactRadius(), regimeForceUnitTest::getMeanRelativeContactRadius(), ParticleParticleCollision::getRelativeVelocity(), WallParticleCollision::getRelativeVelocity(), getRotationalEnergy(), getTotalMass(), getTotalMomentum(), GranuHeap::GranuHeap(), Hertzian2DUnitTest::Hertzian2DUnitTest(), MercuryBase::hGridActionsBeforeTimeStep(), MercuryBase::hGridNeedsRebuilding(), MercuryBase::hGridRebuild(), importParticlesAs(), Indenter::Indenter(), InitialConditions< SpeciesType >::InitialConditions(), initialiseSolve(), Membrane::initializeEdgeBendingQuantities(), integrateAfterForceComputation(), ChuteWithPeriodicInflow::integrateBeforeForceComputation(), integrateBeforeForceComputation(), HorizontalMixer::introduceParticlesAtWall(), ContactDetectionIntersectionOfWallsTest::introduceParticlesAtWall(), HorizontalMixer::introduceParticlesInDomain(), HorizontalMixer::introduceSingleParticle(), LaserOnLayer::LaserOnLayer(), LawinenBox::LawinenBox(), LeesEdwardsSelfTest::LeesEdwardsSelfTest(), load(), main(), BaseCluster::makeDataAnalysis(), ChuteBottom::makeRoughBottom(), MarbleRun::MarbleRun(), MercuryCGSelfTest::MercuryCGSelfTest(), MovingWall::MovingWall(), outputXBallsData(), LiquidMigrationMPI2Test::outputXBallsData(), LiquidMigrationSelfTest::outputXBallsData(), SphericalIndenter::outputXBallsData(), ChuteWithPeriodicInflow::outputXBallsDataParticlee(), ParticleBeam::ParticleBeam(), ParticleInclusion::ParticleInclusion(), BaseCluster::particleInsertionSuccessful(), LawinenBox::printTime(), GranuDrum::printTime(), GranuHeap::printTime(), ChuteWithPeriodicInflow::printTime(), NozzleDemo::printTime(), Drum::printTime(), RotatingDrumWet::printTime(), VerticalMixer::printTime(), LiquidMigrationMPI2Test::printTime(), ParticleBeam::printTime(), SilbertPeriodic::printTime(), vibratedBed::printTime(), InitialBed::printTime(), LaserOnLayer::printTime(), MeltableForceLaw2SelfTest::printTime(), MeltableForceLawSelfTest::printTime(), OneParticleHeatingSelfTest::printTime(), OneParticleCoolingSelfTest::printTime(), ThermalConductionSelfTest::printTime(), RotatingDrumBidisperse::printTime(), SingleParticleSegregation::printTime(), CubeDeletionBoundarySelfTest::printTime(), DeletionBoundarySelfTest::printTime(), DistributionSelfTest::printTime(), DistributionToPSDSelfTest::printTime(), InsertionBoundarySelfTest::printTime(), MultiplePSDSelfTest::printTime(), NozzleSelfTest::printTime(), PolydisperseInsertionBoundarySelfTest::printTime(), PSDManualInsertionSelfTest::printTime(), LiquidMigrationSelfTest::printTime(), SinterPair::printTime(), PSDSelfTest::printTime(), EvaporationAndHeatTest::printTime(), RandomClusterInsertionBoundarySelfTest::printTime(), HeatTransferUnitTest::printTime(), MultiParticlesInsertion::printTime(), regimeForceUnitTest::printTime(), BaseCluster::printTime(), Chute::printTime(), PeriodicBoundaryHandler::processLocalGhostParticles(), Domain::processReceivedBoundaryParticleData(), PeriodicBoundaryHandler::processReceivedGhostParticleData(), FileReader::read(), InsertionBoundary::read(), Membrane::read(), read(), InteractionHandler::readAndAddObject(), readNextDataFile(), readNextFStatFile(), readOld(), CurvyChute::recreateBottom(), regimeForceUnitTest::regimeForceUnitTest(), removeDuplicatePeriodicParticles(), CGHandler::restart(), MeshTriangle::retrieveVertexParticles(), RotatingDrumBidisperse::RotatingDrumBidisperse(), CSCInit::save(), RotatingDrumBidisperseInitialise::save(), save(), Membrane::saveVertexPositions(), ClosedCSCWalls::saveWalls(), CSCWalls::saveWalls(), Slide::set_Walls(), ParticleSpecies::setDensity(), setFixedParticles(), MeshTriangle::setHandler(), setMeanVelocity(), setMeanVelocityAndKineticEnergy(), setParticleDimensions(), setParticlesWriteVTK(), BaseParticle::setSpecies(), setSuperquadricParticlesWriteVTK(), ExtremeOverlapUnitTest::setupInitialConditions(), ExtremeOverlapVolumeUnitTest::setupInitialConditions(), LawinenBox::setupInitialConditions(), ClosedCSCWalls::setupInitialConditions(), CSCInit::setupInitialConditions(), CSCRun::setupInitialConditions(), CSCWalls::setupInitialConditions(), MercuryLogo::setupInitialConditions(), SmoothChute::setupInitialConditions(), ChangingTOIParticle::setupInitialConditions(), free_cooling::setupInitialConditions(), restart::setupInitialConditions(), CFDDEMCoupleTest::setupInitialConditions(), HorizontalMixerWalls::setupInitialConditions(), MembraneDemo::setupInitialConditions(), Binary::setupInitialConditions(), my_problem::setupInitialConditions(), Chain::setupInitialConditions(), ForceLawsMPI2Test::setupInitialConditions(), LiquidMigrationMPI2Test::setupInitialConditions(), MaserRepeatedOutInMPI2Test::setupInitialConditions(), PeriodicBounaryEnteringMPIDomainTest::setupInitialConditions(), SubcriticalMaserBoundaryTESTMPI2Test::setupInitialConditions(), TwoByTwoMPIDomainMPI4Test::setupInitialConditions(), CubicCell::setupInitialConditions(), FreeCooling2DinWalls::setupInitialConditions(), FreeCooling2DinWallsDemo::setupInitialConditions(), FreeCooling3DDemoProblem::setupInitialConditions(), FreeCooling3DinWallsDemo::setupInitialConditions(), FreeCoolingDemoProblem::setupInitialConditions(), HeaterBoundaryTest::setupInitialConditions(), HourGlass2D::setupInitialConditions(), HourGlass::setupInitialConditions(), MinimalExampleDrum::setupInitialConditions(), ParameterStudy1DDemo::setupInitialConditions(), ParameterStudy2DDemo::setupInitialConditions(), ParameterStudy3DDemo::setupInitialConditions(), StressStrainControl::setupInitialConditions(), TimeDependentPeriodicBoundary3DSelfTest::setupInitialConditions(), FiveParticles::setupInitialConditions(), Cstatic2d::setupInitialConditions(), Cstatic3D::setupInitialConditions(), AngleOfRepose::setupInitialConditions(), SilbertPeriodic::setupInitialConditions(), statistics_while_running< T >::setupInitialConditions(), InitialBed::setupInitialConditions(), MeltableForceLaw2SelfTest::setupInitialConditions(), MeltableForceLawSelfTest::setupInitialConditions(), OneParticleHeatingSelfTest::setupInitialConditions(), ThermalConductionSelfTest::setupInitialConditions(), GetDistanceAndNormalForIntersectionOfWalls::setupInitialConditions(), GetDistanceAndNormalForScrew::setupInitialConditions(), GetDistanceAndNormalForTriangleWall::setupInitialConditions(), Drum::setupInitialConditions(), HertzSelfTest::setupInitialConditions(), MindlinSelfTest::setupInitialConditions(), Penetration::setupInitialConditions(), Silo::setupInitialConditions(), Chutebelt::setupInitialConditions(), ConstantMassFlowMaserBoundaryMixedSpeciesSelfTest::setupInitialConditions(), CubeDeletionBoundarySelfTest::setupInitialConditions(), DeletionBoundarySelfTest::setupInitialConditions(), clumpTest::setupInitialConditions(), SubcriticalMaserBoundarySelfTest::setupInitialConditions(), PSDSelfTest::setupInitialConditions(), CGBasicSelfTest::setupInitialConditions(), CGHandlerSelfTest::setupInitialConditions(), CGStaticBalanceSelfTest::setupInitialConditions(), NewtonsCradleSelftest::setupInitialConditions(), NewtonsCradleSelfTest::setupInitialConditions(), SquarePacking::setupInitialConditions(), DPM::setupInitialConditions(), ParticleCreation::setupInitialConditions(), ChargedBondedInteractionSelfTest::setupInitialConditions(), ParticleParticleCollision::setupInitialConditions(), WallParticleCollision::setupInitialConditions(), my_problem_HGRID::setupInitialConditions(), FreeFallInteractionSelfTest::setupInitialConditions(), FreeFallSelfTest::setupInitialConditions(), HertzianBSHPInteractionTwoParticleElasticCollision::setupInitialConditions(), LiquidMigrationSelfTest::setupInitialConditions(), ObliqueImpactSelfTest::setupInitialConditions(), TwoBondedParticleElasticCollision::setupInitialConditions(), TwoParticleBagheriCollision::setupInitialConditions(), TwoParticleClassicalWilletCollision::setupInitialConditions(), TwoParticleCollisionInteraction::setupInitialConditions(), TwoParticleElasticCollisionInteraction::setupInitialConditions(), TwoParticleElasticCollision::setupInitialConditions(), CoilSelfTest::setupInitialConditions(), GetDistanceAndNormalForTriangleWalls::setupInitialConditions(), MembraneSelfTest::setupInitialConditions(), RollingOverTriangleWalls::setupInitialConditions(), TriangulatedScrewSelfTest::setupInitialConditions(), TriangulatedStepSelfTest::setupInitialConditions(), TriangulatedStepWallSelfTest::setupInitialConditions(), TriangulatedWallSelfTest::setupInitialConditions(), UnionOfWalls::setupInitialConditions(), DrumRot::setupInitialConditions(), RotatingDrum::setupInitialConditions(), SphericalIndenter::setupInitialConditions(), ScalingTestInitialConditionsRelax::setupInitialConditions(), ScalingTestRun::setupInitialConditions(), Contact::setupInitialConditions(), Wall::setupInitialConditions(), BouncingSuperQuadric::setupInitialConditions(), EllipsoidsBouncingOnWallDemo::setupInitialConditions(), EllipticalSuperQuadricCollision::setupInitialConditions(), GranularCollapse::setupInitialConditions(), SlidingSpheresUnitTest::setupInitialConditions(), SphericalSuperQuadricCollision::setupInitialConditions(), ContactDetectionNormalSpheresTest::setupInitialConditions(), ContactDetectionRotatedSpheresTest::setupInitialConditions(), ShapesDemo::setupInitialConditions(), VisualisationTest::setupInitialConditions(), MercuryProblem::setupInitialConditions(), Tutorial11::setupInitialConditions(), Tutorial12::setupInitialConditions(), Tutorial1::setupInitialConditions(), Tutorial2::setupInitialConditions(), Tutorial3::setupInitialConditions(), Tutorial4::setupInitialConditions(), Tutorial5::setupInitialConditions(), Tutorial6::setupInitialConditions(), Tutorial7::setupInitialConditions(), Tutorial8::setupInitialConditions(), Tutorial9::setupInitialConditions(), ParticleParticleInteraction::setupInitialConditions(), ParticleParticleInteractionWithPlasticForces::setupInitialConditions(), ParticleWallInteraction::setupInitialConditions(), AngledPeriodicBoundarySecondUnitTest::setupInitialConditions(), AngledPeriodicBoundaryUnitTest::setupInitialConditions(), Packing::setupInitialConditions(), CGDisplacementFieldUnitTest::setupInitialConditions(), CGExactOverlapUnitTest::setupInitialConditions(), CGForceDensityUnitTest::setupInitialConditions(), CreateDataAndFStatFiles::setupInitialConditions(), ChargedBondedParticleUnitTest::setupInitialConditions(), ConsistencyInitialParticleWallOverlapUnitTest::setupInitialConditions(), DrivenParticleClass::setupInitialConditions(), EnergyUnitTest::setupInitialConditions(), EvaporationAndHeatTest::setupInitialConditions(), ExtremeOverlapWithWallsUnitTest::setupInitialConditions(), FluxBoundaryPrescribedDistanceUnitTest::setupInitialConditions(), FluxBoundaryUnitTest::setupInitialConditions(), FreeFallHertzMindlinUnitTest::setupInitialConditions(), FreeFall::setupInitialConditions(), FullRestartTest::setupInitialConditions(), HeatTransferUnitTest::setupInitialConditions(), HertzContactRestitutionUnitTest::setupInitialConditions(), HertzianSinterForceUnitTest::setupInitialConditions(), MD_demo::setupInitialConditions(), InclinedPlane::setupInitialConditions(), MpiMaserChuteTest::setupInitialConditions(), MovingIntersectionOfWallsUnitTest_Basic::setupInitialConditions(), MovingWalls::setupInitialConditions(), MovingWallTangential::setupInitialConditions(), MultiParticlesInsertion::setupInitialConditions(), MpiPeriodicBoundaryUnitTest::setupInitialConditions(), PeriodicWalls::setupInitialConditions(), PeriodicWallsWithSlidingFrictionUnitTest::setupInitialConditions(), PlasticForceUnitTest::setupInitialConditions(), SeparateFilesSelfTest::setupInitialConditions(), SinterForceUnitTest::setupInitialConditions(), SpeciesTest::setupInitialConditions(), TangentialSpringEnergyConservationUnitTest::setupInitialConditions(), TangentialSpringUnitTest::setupInitialConditions(), WallSpecies::setupInitialConditions(), BaseCluster::setupInitialConditions(), ChuteBottom::setupInitialConditions(), ContactDetectionWithWallTester::setupParticleAndWall(), ContactDetectionTester::setupParticles(), Siegen::Siegen(), SingleParticle< SpeciesType >::SingleParticle(), SingleParticleIndenter::SingleParticleIndenter(), SinterPair::SinterPair(), Slide::Slide(), statistics_while_running< T >::statistics_while_running(), StressStrainControl::StressStrainControl(), FlowFrontChute::stretch(), synchroniseParticle(), ContactDetectionNormalSpheresTest::test(), InertiaTensorTester::test(), VolumeTest::test(), HertzContactRestitutionUnitTest::test(), PeriodicBoundaryHandler::updateMaserParticle(), PeriodicBoundaryHandler::updateParticleStatus(), viscoElasticUnitTest::viscoElasticUnitTest(), write(), BaseCluster::writeAmatFile(), WallVTKWriter::writeCGFields(), writeEneTimeStep(), LawinenBox::writeEneTimeStep(), Drum::writeEneTimeStep(), Penetration::writeEneTimeStep(), Silo::writeEneTimeStep(), Slide::writeEneTimeStep(), SingleParticle< SpeciesType >::writeEneTimeStep(), writeFstatHeader(), Calibration::writePSDToFile(), and BaseCluster::writeToOverlFile().
periodicBoundaryHandler
PeriodicBoundaryHandler DPMBase::periodicBoundaryHandler
Internal handler that deals with periodic boundaries, especially in a parallel build.
Referenced by BoundaryHandler::addObject(), checkInteractionWithBoundaries(), constructor(), deleteGhostParticles(), DPMBase(), ParticleHandler::getNumberOfRealObjectsLocal(), BaseParticle::getPeriodicComplexity(), insertGhostParticle(), performGhostParticleUpdate(), read(), BaseParticle::setPeriodicComplexity(), and updateGhostGrid().
random
RNG DPMBase::random
This is a random generator, often used for setting up the initial conditions etc...
Referenced by SmoothChute::actionsBeforeTimeStep(), Chutebelt::actionsOnRestart(), NautaMixer::addParticles(), HeaterBoundary::checkBoundaryAfterParticleMoved(), FixedClusterInsertionBoundary::checkBoundaryBeforeTimeStep(), RandomClusterInsertionBoundary::checkBoundaryBeforeTimeStep(), BaseCluster::computeInternalStructure(), constructor(), LawinenBox::create_inflow_particle(), ChutePeriodic::create_inflow_particle(), ChuteWithContraction::create_inflow_particle(), ChuteWithVerticalHopper::create_inflow_particle(), Funnel::create_inflow_particle(), AngleOfRepose::create_inflow_particle(), FlowRule::create_inflow_particle(), SilbertPeriodic::create_inflow_particle(), SegregationWithHopper::create_inflow_particle(), Slide::create_rough_wall(), Chute::createBottom(), CurvyChute::createBottom(), Chute::createFlowParticle(), DPMBase(), InitialConditions< SpeciesType >::InitialConditions(), HorizontalMixer::introduceParticlesInDomain(), LawinenBox::LawinenBox(), LeesEdwardsSelfTest::LeesEdwardsSelfTest(), main(), BaseCluster::particleInsertionSuccessful(), MD_demo::RandomRadius(), read(), readNextArgument(), RotatingDrumBidisperse::RotatingDrumBidisperse(), BaseCluster::setRadii(), ClosedCSCWalls::setupInitialConditions(), CSCInit::setupInitialConditions(), CSCWalls::setupInitialConditions(), MercuryLogo::setupInitialConditions(), SmoothChute::setupInitialConditions(), NozzleDemo::setupInitialConditions(), Binary::setupInitialConditions(), CubicCell::setupInitialConditions(), FreeCooling2DinWallsDemo::setupInitialConditions(), FreeCooling3DDemoProblem::setupInitialConditions(), FreeCooling3DinWallsDemo::setupInitialConditions(), FreeCoolingDemoProblem::setupInitialConditions(), HourGlass2D::setupInitialConditions(), HourGlass::setupInitialConditions(), MinimalExampleDrum::setupInitialConditions(), TimeDependentPeriodicBoundary3DSelfTest::setupInitialConditions(), FiveParticles::setupInitialConditions(), Cstatic2d::setupInitialConditions(), InitialBed::setupInitialConditions(), NozzleSelfTest::setupInitialConditions(), ParticleCreation::setupInitialConditions(), ParticleParticleCollision::setupInitialConditions(), WallParticleCollision::setupInitialConditions(), my_problem_HGRID::setupInitialConditions(), TriangulatedScrewSelfTest::setupInitialConditions(), TriangulatedWallSelfTest::setupInitialConditions(), DrumRot::setupInitialConditions(), RotatingDrum::setupInitialConditions(), ScalingTestInitialConditionsRelax::setupInitialConditions(), Contact::setupInitialConditions(), GranularCollapse::setupInitialConditions(), EllipticalSuperQuadricCollision::setupInitialConditions(), Tutorial11::setupInitialConditions(), MD_demo::setupInitialConditions(), MpiMaserChuteTest::setupInitialConditions(), MpiPeriodicBoundaryUnitTest::setupInitialConditions(), ChuteBottom::setupInitialConditions(), and write().
readSpeciesFromDataFile_
bool DPMBase::readSpeciesFromDataFile_ private
Determines if the last column of the data file is interpreted as the info parameter during restart.
Referenced by constructor(), DPMBase(), readNextArgument(), readNextDataFile(), and readSpeciesFromDataFile().
restarted_
bool DPMBase::restarted_ private
A bool to check if the simulation was restarted or not, ie. if setupInitialConditionsShould be run and the fileCounters reset.
Referenced by DPMBase(), getRestarted(), and setRestarted().
restartFile
File DPMBase::restartFile
An instance of class File to handle in- and output into a .restart file.
Referenced by BaseCluster::actionsOnRestart(), BoundariesSelfTest::BoundariesSelfTest(), ClosedCSCRestart::ClosedCSCRestart(), ClosedCSCStats::ClosedCSCStats(), closeFiles(), commandLineCG(), ChuteBottom::constructor(), constructor(), CSCRestart::CSCRestart(), CSCStats::CSCStats(), CGHandler::evaluateRestartFiles(), FluxAndPeriodicBoundarySelfTest::FluxAndPeriodicBoundarySelfTest(), FluxBoundarySelfTest::FluxBoundarySelfTest(), ForceLawsMPI2Test::ForceLawsMPI2Test(), CLiveStatistics< T >::getLiveStatistics(), getRestartFile(), Indenter::Indenter(), InitialConditions< SpeciesType >::InitialConditions(), initialiseSolve(), LiquidMigrationMPI2Test::LiquidMigrationMPI2Test(), main(), read(), readNextArgument(), Mercury3DRestart::readNextArgument(), readOld(), readRestartFile(), resetFileCounter(), CGHandler::restart(), RotatingDrumBidisperse::RotatingDrumBidisperse(), FlowRule::run(), statistics_while_running< T >::run(), AngleOfRepose::run(), CSCInit::save(), RotatingDrumBidisperseInitialise::save(), ClosedCSCWalls::saveWalls(), CSCWalls::saveWalls(), setFileType(), setLastSavedTimeStep(), setLogarithmicSaveCount(), setName(), setOpenMode(), Calibration::setOutput(), setSaveCount(), ClosedCSCStats::setupInitialConditions(), CSCRun::setupInitialConditions(), CSCStats::setupInitialConditions(), MarbleRun::setupInitialConditions(), ChutePeriodic::setupInitialConditions(), Cstatic3D::setupInitialConditions(), Drum::setupInitialConditions(), HertzSelfTest::setupInitialConditions(), MindlinSelfTest::setupInitialConditions(), Penetration::setupInitialConditions(), Silo::setupInitialConditions(), CubeDeletionBoundarySelfTest::setupInitialConditions(), DeletionBoundarySelfTest::setupInitialConditions(), UnionOfWalls::setupInitialConditions(), HertzianSinterForceUnitTest::setupInitialConditions(), BaseCluster::setupInitialConditions(), SilbertPeriodic::SilbertPeriodic(), SingleParticle< SpeciesType >::SingleParticle(), statistics_while_running< T >::statistics_while_running(), TriangulatedScrewSelfTest::TriangulatedScrewSelfTest(), TriangulatedStepSelfTest::TriangulatedStepSelfTest(), TriangulatedWallSelfTest::TriangulatedWallSelfTest(), Tutorial11::Tutorial11(), TwoByTwoMPIDomainMPI4Test::TwoByTwoMPIDomainMPI4Test(), write(), writeOutputFiles(), and writeRestartFile().
restartVersion_
std::string DPMBase::restartVersion_ private
Previous versions of MercuryDPM had a different restart file format, the below member variable allows one to specify the version in order to choose between the available version support.
Referenced by DPMBase(), getRestartVersion(), read(), and setRestartVersion().
rotation_
bool DPMBase::rotation_ private
A flag to turn on/off particle rotation. true will enable particle rotation. false will disable particle rotation.
Referenced by DPMBase(), getRotation(), and setRotation().
runNumber_
int DPMBase::runNumber_ private
This stores the run number for saving.
Referenced by constructor(), DPMBase(), getRunNumber(), read(), setRunNumber(), and write().
speciesHandler
SpeciesHandler DPMBase::speciesHandler
A handler to that stores the species type i.e. LinearViscoelasticSpecies, etc.
Referenced by ShiftingConstantMassFlowMaserBoundarySelfTest::actionsAfterTimeStep(), ShiftingMaserBoundarySelfTest::actionsAfterTimeStep(), DropletBoundary::actionsBeforeTimeLoop(), SmoothChute::actionsBeforeTimeStep(), Chutebelt::actionsOnRestart(), NautaMixer::addBaseWall(), NautaMixer::addConeWall(), ChuteWithPeriodicInflow::AddContinuingBottom(), ChuteWithHopper::addHopper(), InteractionHandler::addInteraction(), SingleParticleSegregation::addIntruderParticle(), NautaMixer::addParticles(), NautaMixer::addParticlesAtWall(), BaseWall::addParticlesAtWall(), ConstantMassFlowMaserBoundary::addParticleToMaser(), SubcriticalMaserBoundary::addParticleToMaser(), NautaMixer::addScrew(), NautaMixer::addSpeciesAndSetTimeStepAndSaveCount(), NautaMixer::addTopWall(), AngledPeriodicBoundarySecondUnitTest::AngledPeriodicBoundarySecondUnitTest(), AngledPeriodicBoundaryUnitTest::AngledPeriodicBoundaryUnitTest(), AngleOfRepose::AngleOfRepose(), AreaVTK::AreaVTK(), BouncingSuperQuadric::BouncingSuperQuadric(), BoundariesSelfTest::BoundariesSelfTest(), BaseCluster::calculateTimeStep(), CGBasicSelfTest::CGBasicSelfTest(), CGDisplacementFieldUnitTest::CGDisplacementFieldUnitTest(), CGExactOverlapUnitTest::CGExactOverlapUnitTest(), CGForceDensityUnitTest::CGForceDensityUnitTest(), RandomClusterInsertionBoundary::checkBoundaryBeforeTimeStep(), checkSettings(), ChutePeriodicDemo::ChutePeriodicDemo(), ChuteWithPeriodicInflowAndContinuingBottom::ChuteWithPeriodicInflowAndContinuingBottom(), ChuteWithPeriodicInflowAndContraction::ChuteWithPeriodicInflowAndContraction(), ChuteWithPeriodicInflowAndVariableBottom::ChuteWithPeriodicInflowAndVariableBottom(), ClosedCSCWalls::ClosedCSCWalls(), ChuteWithPeriodicInflow::computeInternalForces(), BaseCluster::computeInternalStructure(), constructor(), Contact::Contact(), ContractionWithPeriodicInflow::ContractionWithPeriodicInflow(), ChutePeriodic::create_inflow_particle(), FlowRule::create_inflow_particle(), SilbertPeriodic::create_inflow_particle(), AngleOfRepose::createBaseSpecies(), SilbertPeriodic::createBaseSpecies(), Chute::createBottom(), CurvyChute::createBottom(), InteractionHandler::createEmptyInteraction(), Chute::createFlowParticle(), ParameterStudy1DDemo::createSpecies(), ParameterStudy2DDemo::createSpecies(), ParameterStudy3DDemo::createSpecies(), MercuryProblem::createTriangleWall(), CSCInit::CSCInit(), CSCWalls::CSCWalls(), decompose(), InteractionHandler::deleteEmptyInteraction(), DPM::DPM(), DPMBase(), fillDomainWithParticles(), FluxAndPeriodicBoundarySelfTest::FluxAndPeriodicBoundarySelfTest(), FluxBoundaryPrescribedDistanceUnitTest::FluxBoundaryPrescribedDistanceUnitTest(), FluxBoundarySelfTest::FluxBoundarySelfTest(), FluxBoundaryUnitTest::FluxBoundaryUnitTest(), ForceLawsMPI2Test::ForceLawsMPI2Test(), FlowRule::getDensityVariation(), NurbsWall::getDistanceAndNormal(), Screw::getDistanceAndNormal(), IntersectionOfWalls::getDistanceAndNormal(), InteractionHandler::getInteraction(), GranuDrum::GranuDrum(), GranuHeap::GranuHeap(), GranularCollapse::GranularCollapse(), Hertzian2DUnitTest::Hertzian2DUnitTest(), HertzianSinterForceUnitTest::HertzianSinterForceUnitTest(), Indenter::Indenter(), inflowFromPeriodic::inflowFromPeriodic(), InitialConditions< SpeciesType >::InitialConditions(), MembraneDemo::initializeSpecies(), MembraneSelfTest::initializeSpecies(), InsertionBoundaryMPI2Test::InsertionBoundaryMPI2Test(), InsertionBoundarySelfTest::InsertionBoundarySelfTest(), ChuteWithPeriodicInflow::integrateBeforeForceComputation(), inflowFromPeriodic::integrateBeforeForceComputation(), HorizontalMixer::introduceParticlesAtWall(), ContactDetectionIntersectionOfWallsTest::introduceParticlesAtWall(), HorizontalMixer::introduceParticlesInDomain(), HorizontalMixer::introduceSingleParticle(), LaserOnLayer::LaserOnLayer(), LawinenBox::LawinenBox(), LeesEdwardsDemo::LeesEdwardsDemo(), LeesEdwardsSelfTest::LeesEdwardsSelfTest(), LiquidMigrationMPI2Test::LiquidMigrationMPI2Test(), MarbleRun::loadBigSeesaw(), ChuteWithPeriodicInflow::loadPeriodicBox(), MarbleRun::loadSmallSeesaw(), MarbleRun::loadSTLFile(), main(), ChuteBottom::makeRoughBottom(), MarbleRun::MarbleRun(), MaserRepeatedOutInMPI2Test::MaserRepeatedOutInMPI2Test(), MD_demo::MD_demo(), MercuryCGSelfTest::MercuryCGSelfTest(), MinimalExampleDrum::MinimalExampleDrum(), MovingIntersectionOfWallsUnitTest_Basic::MovingIntersectionOfWallsUnitTest_Basic(), MovingWall::MovingWall(), MultiParticlesInsertion::MultiParticlesInsertion(), ParticleBeam::ParticleBeam(), ParticleCreation::ParticleCreation(), ParticleInclusion::ParticleInclusion(), BaseCluster::particleInsertionSuccessful(), ParticleParticleCollision::ParticleParticleCollision(), ParticleParticleInteraction::ParticleParticleInteraction(), ParticleParticleInteractionWithPlasticForces::ParticleParticleInteractionWithPlasticForces(), ParticleWallInteraction::ParticleWallInteraction(), PlasticForceUnitTest::PlasticForceUnitTest(), ShearStage::printTime(), protectiveWall::protectiveWall(), FileReader::read(), ConstantMassFlowMaserBoundary::read(), SubcriticalMaserBoundary::read(), Membrane::read(), MembraneDemo::read(), MembraneSelfTest::read(), read(), readNextDataFile(), readNextFStatFile(), readOld(), readParAndIniFiles(), CurvyChute::recreateBottom(), regimeForceUnitTest::regimeForceUnitTest(), CGHandler::restart(), RotatingDrumBidisperse::RotatingDrumBidisperse(), RotatingDrumBidisperseInitialise::RotatingDrumBidisperseInitialise(), runFreeFall(), Cstatic2d::set_particle_properties(), Cstatic3D::set_particle_properties(), FlowRule::setDensityVariation(), AxisymmetricWallSelfTest::setGeometry(), BaseParticle::setIndSpecies(), MercuryOS::setMaterialProperties(), BaseCluster::setSpecies(), Calibration::setSpecies(), Material::setSpecies(), AxisymmetricWallSelfTest::setSpeciesAndTimeStep(), MercuryProblem::setSpeciesProperties(), ChutePeriodic::setup(), ExtremeOverlapUnitTest::setupInitialConditions(), ExtremeOverlapVolumeUnitTest::setupInitialConditions(), LawinenBox::setupInitialConditions(), MercuryLogo::setupInitialConditions(), SmoothChute::setupInitialConditions(), ChangingTOIParticle::setupInitialConditions(), free_cooling::setupInitialConditions(), restart::setupInitialConditions(), CFDDEMCoupleTest::setupInitialConditions(), HorizontalMixer::setupInitialConditions(), NozzleDemo::setupInitialConditions(), Drum::setupInitialConditions(), RotatingDrumWet::setupInitialConditions(), Binary::setupInitialConditions(), my_problem::setupInitialConditions(), Chain::setupInitialConditions(), ForceLawsMPI2Test::setupInitialConditions(), InsertionBoundaryMPI2Test::setupInitialConditions(), LiquidMigrationMPI2Test::setupInitialConditions(), MaserRepeatedOutInMPI2Test::setupInitialConditions(), PeriodicBounaryEnteringMPIDomainTest::setupInitialConditions(), SubcriticalMaserBoundaryTESTMPI2Test::setupInitialConditions(), TwoByTwoMPIDomainMPI4Test::setupInitialConditions(), CubicCell::setupInitialConditions(), FreeCooling2DinWalls::setupInitialConditions(), FreeCooling2DinWallsDemo::setupInitialConditions(), FreeCooling3DDemoProblem::setupInitialConditions(), FreeCooling3DinWallsDemo::setupInitialConditions(), FreeCoolingDemoProblem::setupInitialConditions(), HeaterBoundaryTest::setupInitialConditions(), HourGlass2D::setupInitialConditions(), HourGlass::setupInitialConditions(), LeesEdwardsDemo::setupInitialConditions(), MinimalExampleDrum::setupInitialConditions(), ParameterStudy1DDemo::setupInitialConditions(), ParameterStudy2DDemo::setupInitialConditions(), ParameterStudy3DDemo::setupInitialConditions(), StressStrainControl::setupInitialConditions(), ShiftingConstantMassFlowMaserBoundarySelfTest::setupInitialConditions(), ShiftingMaserBoundarySelfTest::setupInitialConditions(), TimeDependentPeriodicBoundary3DSelfTest::setupInitialConditions(), TimeDependentPeriodicBoundaryTest::setupInitialConditions(), FiveParticles::setupInitialConditions(), SilbertPeriodic::setupInitialConditions(), InitialBed::setupInitialConditions(), MeltableForceLaw2SelfTest::setupInitialConditions(), MeltableForceLawSelfTest::setupInitialConditions(), OneParticleHeatingSelfTest::setupInitialConditions(), OneParticleCoolingSelfTest::setupInitialConditions(), ThermalConductionSelfTest::setupInitialConditions(), GetDistanceAndNormalForIntersectionOfWalls::setupInitialConditions(), GetDistanceAndNormalForScrew::setupInitialConditions(), GetDistanceAndNormalForTriangleWall::setupInitialConditions(), MyCoil::setupInitialConditions(), Nurbs::setupInitialConditions(), Polygon::setupInitialConditions(), Silo::setupInitialConditions(), Chutebelt::setupInitialConditions(), ConstantMassFlowMaserBoundaryMixedSpeciesSelfTest::setupInitialConditions(), ConstantMassFlowMaserSelfTest::setupInitialConditions(), CubeDeletionBoundarySelfTest::setupInitialConditions(), DeletionBoundarySelfTest::setupInitialConditions(), DistributionPhiNormalSelfTest::setupInitialConditions(), DistributionSelfTest::setupInitialConditions(), DistributionToPSDSelfTest::setupInitialConditions(), InsertionBoundarySelfTest::setupInitialConditions(), MultiplePSDSelfTest::setupInitialConditions(), NozzleSelfTest::setupInitialConditions(), clumpTest::setupInitialConditions(), PolydisperseInsertionBoundarySelfTest::setupInitialConditions(), PSDManualInsertionSelfTest::setupInitialConditions(), SubcriticalMaserBoundarySelfTest::setupInitialConditions(), CGBasicSelfTest::setupInitialConditions(), CGHandlerSelfTest::setupInitialConditions(), CGStaticBalanceSelfTest::setupInitialConditions(), NewtonsCradleSelftest::setupInitialConditions(), NewtonsCradleSelfTest::setupInitialConditions(), SquarePacking::setupInitialConditions(), DPM::setupInitialConditions(), ChargedBondedInteractionSelfTest::setupInitialConditions(), ParticleParticleCollision::setupInitialConditions(), WallParticleCollision::setupInitialConditions(), my_problem_HGRID::setupInitialConditions(), FreeFallInteractionSelfTest::setupInitialConditions(), FreeFallSelfTest::setupInitialConditions(), HertzianBSHPInteractionTwoParticleElasticCollision::setupInitialConditions(), LiquidMigrationSelfTest::setupInitialConditions(), ObliqueImpactSelfTest::setupInitialConditions(), TwoBondedParticleElasticCollision::setupInitialConditions(), TwoParticleBagheriCollision::setupInitialConditions(), TwoParticleClassicalWilletCollision::setupInitialConditions(), TwoParticleCollisionInteraction::setupInitialConditions(), TwoParticleElasticCollisionInteraction::setupInitialConditions(), TwoParticleElasticCollision::setupInitialConditions(), CoilSelfTest::setupInitialConditions(), ContactDetectionIntersectionOfWallsTest::setupInitialConditions(), GetDistanceAndNormalForTriangleWalls::setupInitialConditions(), RollingOverTriangleWalls::setupInitialConditions(), TriangulatedScrewSelfTest::setupInitialConditions(), TriangulatedStepSelfTest::setupInitialConditions(), TriangulatedStepWallSelfTest::setupInitialConditions(), TriangulatedWallSelfTest::setupInitialConditions(), UnionOfWalls::setupInitialConditions(), DrumRot::setupInitialConditions(), RotatingDrum::setupInitialConditions(), SphericalIndenter::setupInitialConditions(), Contact::setupInitialConditions(), Wall::setupInitialConditions(), BouncingSuperQuadric::setupInitialConditions(), EllipsoidsBouncingOnWallDemo::setupInitialConditions(), EllipticalSuperQuadricCollision::setupInitialConditions(), SlidingSpheresUnitTest::setupInitialConditions(), SphericalSuperQuadricCollision::setupInitialConditions(), ContactDetectionNormalSpheresTest::setupInitialConditions(), ContactDetectionRotatedSpheresTest::setupInitialConditions(), ShapesDemo::setupInitialConditions(), VisualisationTest::setupInitialConditions(), MercuryProblem::setupInitialConditions(), Tutorial11::setupInitialConditions(), Tutorial12::setupInitialConditions(), Tutorial1::setupInitialConditions(), Tutorial2::setupInitialConditions(), Tutorial3::setupInitialConditions(), Tutorial4::setupInitialConditions(), Tutorial5::setupInitialConditions(), Tutorial6::setupInitialConditions(), Tutorial7::setupInitialConditions(), Tutorial8::setupInitialConditions(), Tutorial9::setupInitialConditions(), ParticleParticleInteraction::setupInitialConditions(), ParticleParticleInteractionWithPlasticForces::setupInitialConditions(), ParticleWallInteraction::setupInitialConditions(), AngledPeriodicBoundarySecondUnitTest::setupInitialConditions(), AngledPeriodicBoundaryUnitTest::setupInitialConditions(), ArcWallUnitTest::setupInitialConditions(), Packing::setupInitialConditions(), CGDisplacementFieldUnitTest::setupInitialConditions(), CGExactOverlapUnitTest::setupInitialConditions(), CGForceDensityUnitTest::setupInitialConditions(), CreateDataAndFStatFiles::setupInitialConditions(), ChargedBondedParticleUnitTest::setupInitialConditions(), ConsistencyInitialParticleWallOverlapUnitTest::setupInitialConditions(), PSDSelfTest::setupInitialConditions(), DrivenParticleClass::setupInitialConditions(), EnergyUnitTest::setupInitialConditions(), EvaporationAndHeatTest::setupInitialConditions(), ExtremeOverlapWithWallsUnitTest::setupInitialConditions(), RandomClusterInsertionBoundarySelfTest::setupInitialConditions(), FluxBoundaryPrescribedDistanceUnitTest::setupInitialConditions(), FluxBoundaryUnitTest::setupInitialConditions(), FreeFallHertzMindlinUnitTest::setupInitialConditions(), FreeFall::setupInitialConditions(), FullRestartTest::setupInitialConditions(), HeatTransferUnitTest::setupInitialConditions(), HertzContactRestitutionUnitTest::setupInitialConditions(), HertzianSinterForceUnitTest::setupInitialConditions(), MD_demo::setupInitialConditions(), InclinedPlane::setupInitialConditions(), MpiMaserChuteTest::setupInitialConditions(), MovingIntersectionOfWallsUnitTest_Basic::setupInitialConditions(), MovingWalls::setupInitialConditions(), MultiParticlesInsertion::setupInitialConditions(), MpiPeriodicBoundaryUnitTest::setupInitialConditions(), PeriodicWalls::setupInitialConditions(), PeriodicWallsWithSlidingFrictionUnitTest::setupInitialConditions(), PlasticForceUnitTest::setupInitialConditions(), SaveCountUnitTest::setupInitialConditions(), SeparateFilesSelfTest::setupInitialConditions(), SetDistributionPhiNormalSelfTest::setupInitialConditions(), SinterForceUnitTest::setupInitialConditions(), SpeciesTest::setupInitialConditions(), TangentialSpringEnergyConservationUnitTest::setupInitialConditions(), TangentialSpringUnitTest::setupInitialConditions(), WallSpecies::setupInitialConditions(), BaseCluster::setupInitialConditions(), Chute::setupInitialConditions(), ChuteBottom::setupInitialConditions(), ChuteWithHopper::setupInitialConditions(), ContactDetectionWithWallTester::setupParticleAndWall(), ContactDetectionTester::setupParticles(), Chute::setupSideWalls(), Siegen::Siegen(), SilbertPeriodic::SilbertPeriodic(), SingleParticle< SpeciesType >::SingleParticle(), SingleParticleSegregation::SingleParticleSegregation(), Sintering::Sintering(), SinterPair::SinterPair(), StressStrainControl::StressStrainControl(), SubcriticalMaserBoundaryTESTMPI2Test::SubcriticalMaserBoundaryTESTMPI2Test(), T_protectiveWall::T_protectiveWall(), TangentialSpringEnergyConservationUnitTest::TangentialSpringEnergyConservationUnitTest(), BoundingRadiusTester::test(), InertiaTensorTester::test(), VolumeTest::test(), ShapeGradientHessianTester::testCushion(), ShapeGradientHessianTester::testEllipsoid(), ShapeGradientHessianTester::testRoundedBeam(), ShapeGradientHessianTester::testSphere(), TimeDependentPeriodicBoundary3DSelfTest::TimeDependentPeriodicBoundary3DSelfTest(), TimeDependentPeriodicBoundaryTest::TimeDependentPeriodicBoundaryTest(), TriangulatedScrewSelfTest::TriangulatedScrewSelfTest(), TriangulatedStepSelfTest::TriangulatedStepSelfTest(), TriangulatedWallSelfTest::TriangulatedWallSelfTest(), TwoByTwoMPIDomainMPI4Test::TwoByTwoMPIDomainMPI4Test(), viscoElasticUnitTest::viscoElasticUnitTest(), Wall::Wall(), and write().
statFile
File DPMBase::statFile
An instance of class File to handle in- and output into a .stat file.
Referenced by ClosedCSCStats::ClosedCSCStats(), closeFiles(), ChuteWithPeriodicInflow::computeInternalForces(), constructor(), CSCStats::CSCStats(), getStatFile(), main(), read(), readNextArgument(), readOld(), resetFileCounter(), setFileType(), setLogarithmicSaveCount(), setName(), setOpenMode(), setSaveCount(), and write().
systemDimensions_
unsigned int DPMBase::systemDimensions_ private
The dimensions of the simulation i.e. 2D or 3D.
Referenced by checkSettings(), DPMBase(), getSystemDimensions(), read(), readOld(), setParticleDimensions(), and setSystemDimensions().
time_
Mdouble DPMBase::time_ private
Stores the current simulation time.
Referenced by computeOneTimeStep(), DPMBase(), getNextTime(), getTime(), read(), readNextDataFile(), readOld(), Binary::setSwitchPlateAmplitude(), and setTime().
timeMax_
Mdouble DPMBase::timeMax_ private
Stores the duration of the simulation.
Referenced by DPMBase(), getTimeMax(), read(), readOld(), and setTimeMax().
timeStep_
Mdouble DPMBase::timeStep_ private
Stores the simulation time step.
Referenced by computeOneTimeStep(), constructor(), DPMBase(), getNextTime(), getTimeStep(), read(), readOld(), and setTimeStep().
vtkWriter_
ParticleVtkWriter* DPMBase::vtkWriter_ private
Referenced by constructor(), DPMBase(), getVtkWriter(), initialiseVTK(), read(), removeOldFiles(), resetFileCounter(), setParticlesWriteVTK(), setSuperquadricParticlesWriteVTK(), setVTKOutputDirectory(), write(), writePythonFileForVTKVisualisation(), writeVTKFiles(), and ~DPMBase().
wallDetailsVTKWriter_
WallDetailsVTKWriter DPMBase::wallDetailsVTKWriter_ private
Referenced by initialiseVTK(), read(), resetFileCounter(), setVTKOutputDirectory(), write(), writePythonFileForVTKVisualisation(), and writeVTKFiles().
wallHandler
WallHandler DPMBase::wallHandler
An object of the class WallHandler. Contains pointers to all the walls created.
Referenced by T_protectiveWall::actionsAfterTimeStep(), GranuHeap::actionsAfterTimeStep(), ChangingTOIParticle::actionsAfterTimeStep(), NozzleDemo::actionsAfterTimeStep(), MaserRepeatedOutInMPI2Test::actionsAfterTimeStep(), HourGlass2D::actionsAfterTimeStep(), HourGlass::actionsAfterTimeStep(), MarbleRun::actionsAfterTimeStep(), MinimalExampleDrum::actionsAfterTimeStep(), ShiftingConstantMassFlowMaserBoundarySelfTest::actionsAfterTimeStep(), ShiftingMaserBoundarySelfTest::actionsAfterTimeStep(), vibratedBed::actionsAfterTimeStep(), Chutebelt::actionsAfterTimeStep(), NozzleSelfTest::actionsAfterTimeStep(), GranularCollapse::actionsAfterTimeStep(), MercuryProblem::actionsAfterTimeStep(), protectiveWall::actionsAfterTimeStep(), Tutorial11::actionsAfterTimeStep(), LawinenBox::actionsBeforeTimeStep(), Slide::actionsBeforeTimeStep(), DrumRot::actionsBeforeTimeStep(), RotatingDrum::actionsBeforeTimeStep(), DrumRot::actionsOnRestart(), NautaMixer::addBaseWall(), VerticalMixerStraightBlades::addBlades(), VerticalMixerAngledBlades::addBlades(), NautaMixer::addConeWall(), ChuteWithHopper::addHopper(), NautaMixer::addParticles(), NautaMixer::addParticlesAtWall(), VerticalMixerAngledBlades::addPrettyBlades(), NautaMixer::addScrew(), NautaMixer::addTopWall(), AxisymmetricWallSelfTest::AxisymmetricWallSelfTest(), checkParticleForInteractionLocal(), MercuryBase::checkParticleForInteractionLocal(), checkSettings(), ChuteWithContraction::ChuteWithContraction(), ChuteWithPeriodicInflowAndContraction::ChuteWithPeriodicInflowAndContraction(), ClosedCSCRestart::ClosedCSCRestart(), ClosedCSCRun::ClosedCSCRun(), ClosedCSCWalls::ClosedCSCWalls(), computeAllForces(), DPM::computeAllForcesNoHGrid(), computeOneTimeStep(), constructor(), ContractionWithPeriodicInflow::ContractionWithPeriodicInflow(), Slide::create_rough_wall(), Funnel::create_walls(), Chute::createBottom(), MercuryProblem::createTriangleWall(), CSCWalls::CSCWalls(), DPMBase(), CGHandler::evaluateRestartFiles(), getWallsWriteVTK(), GranuDrum::GranuDrum(), GranuHeap::GranuHeap(), handleParticleAddition(), handleParticleRemoval(), HorizontalMixer::HorizontalMixer(), InitialConditions< SpeciesType >::InitialConditions(), initialiseSolve(), initialiseVTK(), integrateAfterForceComputation(), integrateBeforeForceComputation(), HorizontalMixer::introduceParticlesAtWall(), ContactDetectionIntersectionOfWallsTest::introduceParticlesAtWall(), HorizontalMixer::introduceParticlesInDomain(), LaserOnLayer::LaserOnLayer(), load(), MarbleRun::loadBigSeesaw(), MarbleRun::loadSmallSeesaw(), MarbleRun::loadSTLFile(), main(), MaserRepeatedOutInMPI2Test::MaserRepeatedOutInMPI2Test(), MercuryCGSelfTest::MercuryCGSelfTest(), MovingWall::MovingWall(), MovingWalls::MovingWalls(), ParticleCreation::ParticleCreation(), PeriodicBoundaryHandler::processLocalInteractionData(), PeriodicBoundaryHandler::processReceivedInteractionData(), Domain::processReceivedInteractionData(), protectiveWall::protectiveWall(), FileReader::read(), Membrane::read(), read(), Funnel::read(), readNextFStatFile(), readOld(), readParAndIniFiles(), RotatingDrumBidisperse::RotatingDrumBidisperse(), RotatingDrumBidisperseInitialise::RotatingDrumBidisperseInitialise(), save(), ContractionWithPeriodicInflow::set_symmetric_contraction(), ChuteWithPeriodicInflowAndContraction::set_symmetric_contraction(), ChuteWithContraction::set_symmetric_contraction(), Slide::set_Walls(), AxisymmetricWallSelfTest::setGeometry(), HorizontalMixer::setOuterWalls(), HorizontalMixerWalls::setOuterWalls(), Calibration::setOutput(), HorizontalMixer::setScrewCore(), HorizontalMixerWalls::setScrewCore(), HorizontalMixer::setScrewWalls(), BaseWall::setSpecies(), T_protectiveWall::setupInitialConditions(), LawinenBox::setupInitialConditions(), ClosedCSCWalls::setupInitialConditions(), MercuryLogo::setupInitialConditions(), SmoothChute::setupInitialConditions(), ChangingTOIParticle::setupInitialConditions(), NautaMixer::setupInitialConditions(), NozzleDemo::setupInitialConditions(), RotatingDrumWet::setupInitialConditions(), VerticalMixer::setupInitialConditions(), Binary::setupInitialConditions(), my_problem::setupInitialConditions(), Chain::setupInitialConditions(), MaserRepeatedOutInMPI2Test::setupInitialConditions(), PeriodicBounaryEnteringMPIDomainTest::setupInitialConditions(), FreeCooling2DinWallsDemo::setupInitialConditions(), FreeCooling3DinWallsDemo::setupInitialConditions(), HeaterBoundaryTest::setupInitialConditions(), HourGlass2D::setupInitialConditions(), HourGlass::setupInitialConditions(), MarbleRun::setupInitialConditions(), MinimalExampleDrum::setupInitialConditions(), ShiftingConstantMassFlowMaserBoundarySelfTest::setupInitialConditions(), ShiftingMaserBoundarySelfTest::setupInitialConditions(), Cstatic2d::setupInitialConditions(), AngleOfRepose::setupInitialConditions(), SilbertPeriodic::setupInitialConditions(), statistics_while_running< T >::setupInitialConditions(), InitialBed::setupInitialConditions(), MeltableForceLaw2SelfTest::setupInitialConditions(), MeltableForceLawSelfTest::setupInitialConditions(), ThermalConductionSelfTest::setupInitialConditions(), GetDistanceAndNormalForIntersectionOfWalls::setupInitialConditions(), GetDistanceAndNormalForScrew::setupInitialConditions(), GetDistanceAndNormalForTriangleWall::setupInitialConditions(), MyCoil::setupInitialConditions(), Nurbs::setupInitialConditions(), Polygon::setupInitialConditions(), Drum::setupInitialConditions(), HertzSelfTest::setupInitialConditions(), MindlinSelfTest::setupInitialConditions(), Penetration::setupInitialConditions(), Silo::setupInitialConditions(), Chutebelt::setupInitialConditions(), ConstantMassFlowMaserBoundaryMixedSpeciesSelfTest::setupInitialConditions(), ConstantMassFlowMaserSelfTest::setupInitialConditions(), DistributionPhiNormalSelfTest::setupInitialConditions(), InsertionBoundarySelfTest::setupInitialConditions(), NozzleSelfTest::setupInitialConditions(), PolydisperseInsertionBoundarySelfTest::setupInitialConditions(), CGHandlerSelfTest::setupInitialConditions(), NewtonsCradleSelftest::setupInitialConditions(), NewtonsCradleSelfTest::setupInitialConditions(), SquarePacking::setupInitialConditions(), ChargedBondedParticleUnitTest::setupInitialConditions(), WallParticleCollision::setupInitialConditions(), my_problem_HGRID::setupInitialConditions(), FreeFallInteractionSelfTest::setupInitialConditions(), FreeFallSelfTest::setupInitialConditions(), HertzianBSHPInteractionTwoParticleElasticCollision::setupInitialConditions(), LiquidMigrationSelfTest::setupInitialConditions(), DPM::setupInitialConditions(), ObliqueImpactSelfTest::setupInitialConditions(), TwoBondedParticleElasticCollision::setupInitialConditions(), TwoParticleBagheriCollision::setupInitialConditions(), TwoParticleClassicalWilletCollision::setupInitialConditions(), TwoParticleCollisionInteraction::setupInitialConditions(), TwoParticleElasticCollisionInteraction::setupInitialConditions(), TwoParticleElasticCollision::setupInitialConditions(), AxisymmetricWallSelfTest::setupInitialConditions(), CoilSelfTest::setupInitialConditions(), ContactDetectionIntersectionOfWallsTest::setupInitialConditions(), GetDistanceAndNormalForTriangleWalls::setupInitialConditions(), RollingOverTriangleWalls::setupInitialConditions(), TriangulatedScrewSelfTest::setupInitialConditions(), TriangulatedStepSelfTest::setupInitialConditions(), TriangulatedStepWallSelfTest::setupInitialConditions(), TriangulatedWallSelfTest::setupInitialConditions(), UnionOfWalls::setupInitialConditions(), DrumRot::setupInitialConditions(), RotatingDrum::setupInitialConditions(), Wall::setupInitialConditions(), BouncingSuperQuadric::setupInitialConditions(), EllipsoidsBouncingOnWallDemo::setupInitialConditions(), GranularCollapse::setupInitialConditions(), EllipticalSuperQuadricCollision::setupInitialConditions(), protectiveWall::setupInitialConditions(), Tutorial11::setupInitialConditions(), Tutorial12::setupInitialConditions(), Tutorial3::setupInitialConditions(), Tutorial4::setupInitialConditions(), Tutorial7::setupInitialConditions(), Tutorial8::setupInitialConditions(), Tutorial9::setupInitialConditions(), ParticleWallInteraction::setupInitialConditions(), ArcWallUnitTest::setupInitialConditions(), ConsistencyInitialParticleWallOverlapUnitTest::setupInitialConditions(), EvaporationAndHeatTest::setupInitialConditions(), ExtremeOverlapWithWallsUnitTest::setupInitialConditions(), FreeFallHertzMindlinUnitTest::setupInitialConditions(), FreeFall::setupInitialConditions(), FullRestartTest::setupInitialConditions(), InclinedPlane::setupInitialConditions(), MpiMaserChuteTest::setupInitialConditions(), MovingIntersectionOfWallsUnitTest_Basic::setupInitialConditions(), MovingWalls::setupInitialConditions(), MultiParticlesInsertion::setupInitialConditions(), MpiPeriodicBoundaryUnitTest::setupInitialConditions(), SetDistributionPhiNormalSelfTest::setupInitialConditions(), WallSpecies::setupInitialConditions(), AreaVTK::setupInitialConditions(), ChuteBottom::setupInitialConditions(), MercuryProblem::setupMercuryProblem(), ContactDetectionWithWallTester::setupParticleAndWall(), Chute::setupSideWalls(), setWallsWriteVTK(), Slide::Slide(), FlowFrontChute::stretch(), T_protectiveWall::T_protectiveWall(), TangentialSpringEnergyConservationUnitTest::TangentialSpringEnergyConservationUnitTest(), Tutorial11::Tutorial11(), write(), LawinenBox::writeEneTimeStep(), Slide::writeEneTimeStep(), writePythonFileForVTKVisualisation(), and writeVTKFiles().
wallVTKWriter_
WallVTKWriter DPMBase::wallVTKWriter_ private
Referenced by getWallVTKWriter(), initialiseVTK(), read(), removeOldFiles(), resetFileCounter(), setVTKOutputDirectory(), write(), writePythonFileForVTKVisualisation(), and writeVTKFiles().
writeParticlesVTK_
bool DPMBase::writeParticlesVTK_ private
A flag to turn on/off the vtk writer for particles.
Referenced by constructor(), DPMBase(), getParticlesWriteVTK(), setParticlesWriteVTK(), setSuperquadricParticlesWriteVTK(), and write().
writeSuperquadricParticlesVTK_
bool DPMBase::writeSuperquadricParticlesVTK_ private
Referenced by constructor(), DPMBase(), getSuperquadricParticlesWriteVTK(), setParticlesWriteVTK(), and setSuperquadricParticlesWriteVTK().
xBallsAdditionalArguments_
std::string DPMBase::xBallsAdditionalArguments_ private
A string of additional arguments for xballs can be specified (see XBalls/xballs.txt). e.g. "-solidf -v0".
Referenced by constructor(), DPMBase(), getXBallsAdditionalArguments(), and setXBallsAdditionalArguments().
xBallsColourMode_
int DPMBase::xBallsColourMode_ private
XBalls is a package to view the particle data. As an alternative MercuryDPM also supports ParaView. The below variable is used to set the argument cmode in xballs script (see XBalls/xballs.txt)
Referenced by constructor(), DPMBase(), getXBallsColourMode(), and setXBallsColourMode().
xBallsScale_
Mdouble DPMBase::xBallsScale_ private
sets the xballs argument scale (see XBalls/xballs.txt)
Referenced by constructor(), DPMBase(), getXBallsScale(), and setXBallsScale().
xBallsVectorScale_
Mdouble DPMBase::xBallsVectorScale_ private
sets the xballs argument vscale (see XBalls/xballs.txt)
Referenced by constructor(), DPMBase(), getXBallsVectorScale(), and setXBallsVectorScale().
The documentation for this class was generated from the following files:
DPMBase.h
DPMBase.cc