MercuryDPM: Eigen::internal::generic_i0< T, ScalarType > Struct Template Reference
Eigen::internal::generic_i0< T, ScalarType > Struct Template Reference
#include <BesselFunctionsImpl.h>
Static Public Member Functions
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE T run (const T &x)
Member Function Documentation
run()
template<typename T , typename ScalarType = typename unpacket_traits<T>::type> static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE T Eigen::internal::generic_i0< T, ScalarType >::run (const T & x) inline static
{
     return pmul(pexp(pabs(x)), generic_i0e<T, ScalarType>::run(x));
   }
References Eigen::internal::pabs(), Eigen::internal::pexp(), Eigen::internal::pmul(), and plotDoE::x.
Referenced by Eigen::internal::bessel_i0_impl< T >::run().
The documentation for this struct was generated from the following file:
BesselFunctionsImpl.h