MercuryDPM: Eigen::TensorEvaluator< const TensorIndexPairOp< ArgType >, Device > Struct Template Reference
Eigen::TensorEvaluator< const TensorIndexPairOp< ArgType >, Device > Struct Template Reference
#include <TensorArgMax.h>
Public Types
enum {
IsAligned = false , PacketAccess = false , BlockAccess = false , PreferBlockAccess = TensorEvaluator<ArgType, Device>::PreferBlockAccess ,
CoordAccess = false , RawAccess = false
}
typedef TensorIndexPairOp< ArgType > XprType
typedef XprType::Index Index
typedef XprType::Scalar Scalar
typedef XprType::CoeffReturnType CoeffReturnType
typedef TensorEvaluator< ArgType, Device >::Dimensions Dimensions
typedef StorageMemory< CoeffReturnType, Device > Storage
typedef Storage::Type EvaluatorPointerType
typedef internal::TensorBlockNotImplemented TensorBlock
Public Member Functions
EIGEN_STRONG_INLINE TensorEvaluator (const XprType &op, const Device &device)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Dimensions & dimensions () const
EIGEN_STRONG_INLINE bool evalSubExprsIfNeeded (EvaluatorPointerType)
EIGEN_STRONG_INLINE void cleanup ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType coeff (Index index) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorOpCost costPerCoeff (bool vectorized) const
EIGEN_DEVICE_FUNC EvaluatorPointerType data () const
Static Public Attributes
static constexpr int NumDims = internal::array_size<Dimensions>::value
static constexpr int Layout = TensorEvaluator<ArgType, Device>::Layout
Protected Attributes
TensorEvaluator< ArgType, Device > m_impl
Member Typedef Documentation
CoeffReturnType
template<typename ArgType , typename Device > typedef XprType::CoeffReturnType Eigen::TensorEvaluator< const TensorIndexPairOp< ArgType >, Device >::CoeffReturnType
Dimensions
template<typename ArgType , typename Device > typedef TensorEvaluator<ArgType, Device>::Dimensions Eigen::TensorEvaluator< const TensorIndexPairOp< ArgType >, Device >::Dimensions
EvaluatorPointerType
template<typename ArgType , typename Device > typedef Storage::Type Eigen::TensorEvaluator< const TensorIndexPairOp< ArgType >, Device >::EvaluatorPointerType
Index
template<typename ArgType , typename Device > typedef XprType::Index Eigen::TensorEvaluator< const TensorIndexPairOp< ArgType >, Device >::Index
Scalar
template<typename ArgType , typename Device > typedef XprType::Scalar Eigen::TensorEvaluator< const TensorIndexPairOp< ArgType >, Device >::Scalar
Storage
template<typename ArgType , typename Device > typedef StorageMemory<CoeffReturnType, Device> Eigen::TensorEvaluator< const TensorIndexPairOp< ArgType >, Device >::Storage
TensorBlock
template<typename ArgType , typename Device > typedef internal::TensorBlockNotImplemented Eigen::TensorEvaluator< const TensorIndexPairOp< ArgType >, Device >::TensorBlock
XprType
template<typename ArgType , typename Device > typedef TensorIndexPairOp<ArgType> Eigen::TensorEvaluator< const TensorIndexPairOp< ArgType >, Device >::XprType
Member Enumeration Documentation
anonymous enum
template<typename ArgType , typename Device > anonymous enum
Enumerator
IsAligned
PacketAccess
BlockAccess
PreferBlockAccess
CoordAccess
RawAccess
        {
     IsAligned = /*TensorEvaluator<ArgType, Device>::IsAligned*/ false,
     PacketAccess = /*TensorEvaluator<ArgType, Device>::PacketAccess*/ false,
     BlockAccess = false,
     PreferBlockAccess = TensorEvaluator<ArgType, Device>::PreferBlockAccess,
     CoordAccess = false,  // to be implemented
     RawAccess = false
   };
Constructor & Destructor Documentation
TensorEvaluator()
template<typename ArgType , typename Device > EIGEN_STRONG_INLINE Eigen::TensorEvaluator< const TensorIndexPairOp< ArgType >, Device >::TensorEvaluator (const XprType & op, const Device & device) inline
 : m_impl(op.expression(), device) {}
Member Function Documentation
cleanup()
template<typename ArgType , typename Device > EIGEN_STRONG_INLINE void Eigen::TensorEvaluator< const TensorIndexPairOp< ArgType >, Device >::cleanup () inline
 { m_impl.cleanup(); }
Referenced by framework.Frame::__init__().
coeff()
template<typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType Eigen::TensorEvaluator< const TensorIndexPairOp< ArgType >, Device >::coeff (Index index) const inline
{
     return CoeffReturnType(index, m_impl.coeff(index));
   }
costPerCoeff()
template<typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorOpCost Eigen::TensorEvaluator< const TensorIndexPairOp< ArgType >, Device >::costPerCoeff (bool vectorized) const inline
{
     return m_impl.costPerCoeff(vectorized) + TensorOpCost(0, 0, 1);
   }
data()
template<typename ArgType , typename Device > EIGEN_DEVICE_FUNC EvaluatorPointerType Eigen::TensorEvaluator< const TensorIndexPairOp< ArgType >, Device >::data () const inline
 { return NULL; }
Referenced by gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenQuaternionPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), gdb.printers.EigenSparseMatrixPrinter::to_string(), and gdb.printers.EigenQuaternionPrinter::to_string().
dimensions()
template<typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Dimensions& Eigen::TensorEvaluator< const TensorIndexPairOp< ArgType >, Device >::dimensions () const inline
 { return m_impl.dimensions(); }
evalSubExprsIfNeeded()
template<typename ArgType , typename Device > EIGEN_STRONG_INLINE bool Eigen::TensorEvaluator< const TensorIndexPairOp< ArgType >, Device >::evalSubExprsIfNeeded (EvaluatorPointerType) inline
{
     m_impl.evalSubExprsIfNeeded(NULL);
     return true;
   }
Member Data Documentation
Layout
template<typename ArgType , typename Device > constexpr int Eigen::TensorEvaluator< const TensorIndexPairOp< ArgType >, Device >::Layout = TensorEvaluator<ArgType, Device>::Layout static constexpr
m_impl
template<typename ArgType , typename Device > TensorEvaluator<ArgType, Device> Eigen::TensorEvaluator< const TensorIndexPairOp< ArgType >, Device >::m_impl protected
NumDims
template<typename ArgType , typename Device > constexpr int Eigen::TensorEvaluator< const TensorIndexPairOp< ArgType >, Device >::NumDims = internal::array_size<Dimensions>::value static constexpr
The documentation for this struct was generated from the following file:
TensorArgMax.h