MercuryDPM: Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::BlockInnerIterator Class Reference
Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::BlockInnerIterator Class Reference
#include <BlockSparseMatrix.h>
Public Member Functions
BlockInnerIterator (const BlockSparseMatrix &mat, const Index outer)
BlockInnerIterator & operator++ ()
const Map< const BlockScalar > value () const
Map< BlockScalar > valueRef ()
Index index () const
Index outer () const
Index row () const
Index col () const
Index rows () const
Index cols () const
operator bool () const
Protected Attributes
const BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex > & m_mat
const Index m_outer
Index m_id
Index m_end
Constructor & Destructor Documentation
BlockInnerIterator()
template<typename Scalar_ , int _BlockAtCompileTime, int Options_, typename StorageIndex_ > Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::BlockInnerIterator::BlockInnerIterator (const BlockSparseMatrix & mat, const Index outer) inline
       : m_mat(mat), m_outer(outer), m_id(mat.m_outerIndex[outer]), m_end(mat.m_outerIndex[outer + 1]) {}
Member Function Documentation
col()
template<typename Scalar_ , int _BlockAtCompileTime, int Options_, typename StorageIndex_ > Index Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::BlockInnerIterator::col () const inline
 { return outer(); }
cols()
template<typename Scalar_ , int _BlockAtCompileTime, int Options_, typename StorageIndex_ > Index Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::BlockInnerIterator::cols () const inline
{
     return (m_mat.m_blockSize == Dynamic) ? (m_mat.m_outerOffset[m_outer + 1] - m_mat.m_outerOffset[m_outer])
                                           : m_mat.m_blockSize;
   }
References Eigen::Dynamic.
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
index()
template<typename Scalar_ , int _BlockAtCompileTime, int Options_, typename StorageIndex_ > Index Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::BlockInnerIterator::index () const inline
 { return m_mat.m_indices[m_id]; }
operator bool()
template<typename Scalar_ , int _BlockAtCompileTime, int Options_, typename StorageIndex_ > Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::BlockInnerIterator::operator bool () const inline
 { return (m_id < m_end); }
operator++()
template<typename Scalar_ , int _BlockAtCompileTime, int Options_, typename StorageIndex_ > BlockInnerIterator& Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::BlockInnerIterator::operator++ () inline
{
     m_id++;
     return *this;
   }
outer()
template<typename Scalar_ , int _BlockAtCompileTime, int Options_, typename StorageIndex_ > Index Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::BlockInnerIterator::outer () const inline
 { return m_outer; }
row()
template<typename Scalar_ , int _BlockAtCompileTime, int Options_, typename StorageIndex_ > Index Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::BlockInnerIterator::row () const inline
 { return index(); }
rows()
template<typename Scalar_ , int _BlockAtCompileTime, int Options_, typename StorageIndex_ > Index Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::BlockInnerIterator::rows () const inline
{
     return (m_mat.m_blockSize == Dynamic) ? (m_mat.m_innerOffset[index() + 1] - m_mat.m_innerOffset[index()])
                                           : m_mat.m_blockSize;
   }
References Eigen::Dynamic.
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
value()
template<typename Scalar_ , int _BlockAtCompileTime, int Options_, typename StorageIndex_ > const Map<const BlockScalar> Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::BlockInnerIterator::value () const inline
{
     return Map<const BlockScalar>(&(m_mat.m_values[m_mat.blockPtr(m_id)]), rows(), cols());
   }
References Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::cols(), and Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::rows().
valueRef()
template<typename Scalar_ , int _BlockAtCompileTime, int Options_, typename StorageIndex_ > Map<BlockScalar> Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::BlockInnerIterator::valueRef () inline
{
     return Map<BlockScalar>(&(m_mat.m_values[m_mat.blockPtr(m_id)]), rows(), cols());
   }
References Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::cols(), and Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::rows().
Member Data Documentation
m_end
template<typename Scalar_ , int _BlockAtCompileTime, int Options_, typename StorageIndex_ > Index Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::BlockInnerIterator::m_end protected
m_id
template<typename Scalar_ , int _BlockAtCompileTime, int Options_, typename StorageIndex_ > Index Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::BlockInnerIterator::m_id protected
m_mat
template<typename Scalar_ , int _BlockAtCompileTime, int Options_, typename StorageIndex_ > const BlockSparseMatrix<Scalar_, _BlockAtCompileTime, Options_, StorageIndex>& Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::BlockInnerIterator::m_mat protected
m_outer
template<typename Scalar_ , int _BlockAtCompileTime, int Options_, typename StorageIndex_ > const Index Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::BlockInnerIterator::m_outer protected
The documentation for this class was generated from the following file:
BlockSparseMatrix.h