MercuryDPM: oomph::Hankel_functions_for_helmholtz_problem Namespace Reference
oomph::Hankel_functions_for_helmholtz_problem Namespace Reference
Functions
void Hankel_first (const unsigned &n, const double &x, Vector< std::complex< double >> &h, Vector< std::complex< double >> &hp)
void CHankel_first (const unsigned &n, const std::complex< double > &x, Vector< std::complex< double >> &h, Vector< std::complex< double >> &hp)
Detailed Description
//////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////// Namespace to provide Hankel function of the first kind and various orders – needed for Helmholtz computations.
Function Documentation
CHankel_first()
void oomph::Hankel_functions_for_helmholtz_problem::CHankel_first (const unsigned & n, const std::complex< double > & x, Vector< std::complex< double >> & h, Vector< std::complex< double >> & hp)
Compute Hankel function of the first kind of orders 0...n and its derivates at coordinate x. The function returns the vector then its derivative (complex version). This functionality is only required in the computation of the solution for the complex- shifted Laplacian preconditioner.
     {
       // Set the highest order actually calculated
       int n_actual = 0;
       // Create a vector for the Bessel function of the 1st kind
       Vector<std::complex<double>> jn(n + 1);
       // Create a vector for the Bessel function of the 2nd kind
       Vector<std::complex<double>> yn(n + 1);
       // Create a vector for the Bessel function (1st kind) derivative
       Vector<std::complex<double>> jnp(n + 1);
       // Create a vector for the Bessel function (2nd kind) derivative
       Vector<std::complex<double>> ynp(n + 1);
       // Call the (complex) Bessel function to calculate the solution
       CRBond_Bessel::cbessjyna(
         int(n), x, n_actual, &jn[0], &yn[0], &jnp[0], &ynp[0]);
 #ifdef PARANOID
       // Tell the user if they tried to calculate higher order terms
       if (n_actual != int(n))
       {
         // Create an output stream
         std::ostringstream error_message_stream;
         // Create the error message
         error_message_stream << "CRBond_Bessel::cbessjyna() only computed "
                              << n_actual << " rather than " << n
                              << " Bessel functions.\n";
         // Throw the error message
         throw OomphLibError(error_message_stream.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
 #endif
       // Loop over the number of terms requested (only the first entry
       // has *actually* been calculated)
       for (unsigned i = 0; i < n; i++)
       {
         // Set the entries in the Hankel function vector
         h[i] = std::complex<double>(jn[i].real() - yn[i].imag(),
                                     jn[i].imag() + yn[i].real());
         // Set the entries in the Hankel function derivative vector
         hp[i] = std::complex<double>(jnp[i].real() - ynp[i].imag(),
                                      jnp[i].imag() + ynp[i].real());
       }
     } // End of Hankel_first
References CRBond_Bessel::cbessjyna(), i, imag(), n, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and plotDoE::x.
Hankel_first()
void oomph::Hankel_functions_for_helmholtz_problem::Hankel_first (const unsigned & n, const double & x, Vector< std::complex< double >> & h, Vector< std::complex< double >> & hp)
Compute Hankel function of the first kind of orders 0...n and its derivates at coordinate x. The function returns the vector then its derivative.
     {
       int n_actual = 0;
       Vector<double> jn(n + 1), yn(n + 1), jnp(n + 1), ynp(n + 1);
       CRBond_Bessel::bessjyna(
         int(n), x, n_actual, &jn[0], &yn[0], &jnp[0], &ynp[0]);
 #ifdef PARANOID
       if (n_actual != int(n))
       {
         std::ostringstream error_stream;
         error_stream << "CRBond_Bessel::bessjyna() only computed " << n_actual
                      << " rather than " << n << " Bessel functions.\n";
         throw OomphLibError(
           error_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
       }
 #endif
       for (unsigned i = 0; i < n; i++)
       {
         h[i] = std::complex<double>(jn[i], yn[i]);
         hp[i] = std::complex<double>(jnp[i], ynp[i]);
       }
     } // End of Hankel_first
References CRBond_Bessel::bessjyna(), i, n, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and plotDoE::x.
Referenced by GlobalParameters::get_exact_u(), GlobalParameters::get_exact_u_bessel(), and oomph::HelmholtzDtNMesh< ELEMENT >::setup_gamma().