MercuryDPM: FreeFallRestartUnitTest.cpp File Reference
FreeFallRestartUnitTest.cpp File Reference
#include "Mercury2D.h"
#include "Walls/InfiniteWall.h"
#include <iostream>
#include <Species/LinearViscoelasticSpecies.h>
#include <Logger.h>
Classes
class FreeFall
This code is a example on how to write a restartable mercury code.
Functions
void runFreeFall (int argc, char *argv[])
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc , char * argv[])
 {
     //If code is being called with no arguments (e.g. as a selftest), it enters here and call the code again 3 times with different arguments.
     if (argc == 1)
     {
         logger(INFO, "Case 1: simple run");
         if (system("./FreeFallRestartUnitTest -name FreeFallRestart0"))
             logger(FATAL, "code did not run");
         logger(INFO, "Case 2: restart in the middle");
         //restarted at t=0.2
         if (system("./FreeFallRestartUnitTest -tmax 1.05 -name FreeFallRestart1"))
             logger(FATAL, "code did not run");
         if (system("./FreeFallRestartUnitTest -r FreeFallRestart1 -tmax 2.1"))
             logger(FATAL, "code did not run");
         logger(INFO, "Case 3: restart in the middle, using separate data files");
         if (system("./FreeFallRestartUnitTest -tmax 1.05 -name FreeFallRestart2 -fileTypeData 2"))
             logger(FATAL, "code did not run");
         if (system("./FreeFallRestartUnitTest -r FreeFallRestart2 -tmax 2.1"))
             logger(FATAL, "code did not run");
     }
     else
     {
         runFreeFall(argc, argv);
         return 0;
     }
     //To compare the code using gnuplot follow the instructions below.
     //gnuplot> plot 'free_fall_restart/free_fall_restart.ene' u 1:3 w l, 'free_fall_restart/free_fall_no_restart.ene' u 1:3 w l
     //../sc/fpdiff.py ./free_fall_restart.fstat ./free_fall_no_restart.fstat
     //Final stage now we check what we get.
     logger(INFO, "Finished running, now comparing");
     FreeFall dpm0;
     FreeFall dpm1;
     FreeFall dpm2;
     dpm0.readRestartFile("FreeFallRestart0.restart");
     dpm1.readRestartFile("FreeFallRestart1.restart");
     dpm2.readRestartFile("FreeFallRestart2.restart");
     auto p1 = dpm1.particleHandler.begin();
     auto p2 = dpm2.particleHandler.begin();
     for (auto p0 = dpm0.particleHandler.begin(); p0 != dpm0.particleHandler.end(); ++p0)
     {
         if (!(*p0)->getPosition().isEqualTo((*p1)->getPosition(),1e-6))
         {
             logger(FATAL, "Particles is not in the same place after restart. Before it was % and now it is %.",
                    (*p0)->getPosition(), (*p1)->getPosition());
         }
         if (!(*p0)->getPosition().isEqualTo((*p2)->getPosition(),1e-10))
         {
             logger(FATAL, "Particles velocities are not the same place. Before it was % and now it is %.",
                    (*p0)->getVelocity(), (*p1)->getVelocity());
         }
         ++p1;
         ++p2;
     }
     return 0;
 }
References BaseHandler< T >::begin(), e(), BaseHandler< T >::end(), FATAL, INFO, logger, p0, p1, DPMBase::particleHandler, DPMBase::readRestartFile(), and runFreeFall().
runFreeFall()
void runFreeFall (int argc, char * argv[])
Start off my solving the default problem
 {
     FreeFall dpm;
     dpm.setName("FreeFallRestart");
     dpm.setMax({1.0,1.5,0.0});
     auto species = dpm.speciesHandler.copyAndAddObject(LinearViscoelasticSpecies());
     species->setDensity(4.0/constants::pi);
     species->setCollisionTimeAndRestitutionCoefficient(0.1,1,species->getMassFromRadius(0.5));
     dpm.setTimeStep(0.002);
     dpm.setTimeMax(2.1);
     dpm.setSaveCount(100);
     dpm.solve(argc, argv);
 }
References BaseHandler< T >::copyAndAddObject(), constants::pi, DPMBase::setMax(), DPMBase::setName(), DPMBase::setSaveCount(), DPMBase::setTimeMax(), DPMBase::setTimeStep(), DPMBase::solve(), and DPMBase::speciesHandler.
Referenced by main().