MercuryDPM: Eigen::internal::random_default_impl< Scalar, false, false > Struct Template Reference
Eigen::internal::random_default_impl< Scalar, false, false > Struct Template Reference
#include <RandomImpl.h>
Public Types
using Impl = random_float_impl< Scalar >
Static Public Member Functions
static EIGEN_DEVICE_FUNC Scalar run (const Scalar &x, const Scalar &y, int numRandomBits)
static EIGEN_DEVICE_FUNC Scalar run (const Scalar &x, const Scalar &y)
static EIGEN_DEVICE_FUNC Scalar run (int numRandomBits)
static EIGEN_DEVICE_FUNC Scalar run ()
Member Typedef Documentation
Impl
template<typename Scalar > using Eigen::internal::random_default_impl< Scalar, false, false >::Impl = random_float_impl<Scalar>
Member Function Documentation
run() [1/4]
template<typename Scalar > static EIGEN_DEVICE_FUNC Scalar Eigen::internal::random_default_impl< Scalar, false, false >::run () inline static
 { return run(Impl::mantissaBits()); }
References run().
Referenced by run().
run() [2/4]
template<typename Scalar > static EIGEN_DEVICE_FUNC Scalar Eigen::internal::random_default_impl< Scalar, false, false >::run (const Scalar & x, const Scalar & y) inline static
{
     return run(x, y, Impl::mantissaBits());
   }
References Eigen::run(), plotDoE::x, and Eigen::internal::y.
run() [3/4]
template<typename Scalar > static EIGEN_DEVICE_FUNC Scalar Eigen::internal::random_default_impl< Scalar, false, false >::run (const Scalar & x, const Scalar & y, int numRandomBits) inline static
{
     Scalar half_x = Scalar(0.5) * x;
     Scalar half_y = Scalar(0.5) * y;
     Scalar result = (half_x + half_y) + (half_y - half_x) * run(numRandomBits);
     // result is in the half-open interval [x, y) -- provided that x < y
     return result;
   }
References Eigen::run(), plotDoE::x, and Eigen::internal::y.
run() [4/4]
template<typename Scalar > static EIGEN_DEVICE_FUNC Scalar Eigen::internal::random_default_impl< Scalar, false, false >::run (int numRandomBits) inline static
 { return Impl::run(numRandomBits); }
References run().
The documentation for this struct was generated from the following file:
RandomImpl.h