MercuryDPM: Eigen::internal::variable_if_dynamicindex< T, Value > Class Template Reference
Eigen::internal::variable_if_dynamicindex< T, Value > Class Template Reference
#include <XprHelper.h>
Public Member Functions
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE variable_if_dynamicindex (T v)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void setValue (T)
Static Public Member Functions
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE EIGEN_CONSTEXPR T value ()
Detailed Description
template<typename T, int Value>
class Eigen::internal::variable_if_dynamicindex< T, Value >
like variable_if_dynamic but for DynamicIndex
Constructor & Destructor Documentation
variable_if_dynamicindex()
template<typename T , int Value> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Eigen::internal::variable_if_dynamicindex< T, Value >::variable_if_dynamicindex (T v) inline explicit
{
     EIGEN_ONLY_USED_FOR_DEBUG(v);
     eigen_assert(v == T(Value));
   }
References eigen_assert, EIGEN_ONLY_USED_FOR_DEBUG, and v.
Member Function Documentation
setValue()
template<typename T , int Value> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::internal::variable_if_dynamicindex< T, Value >::setValue (T) inline
 {}
value()
template<typename T , int Value> static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE EIGEN_CONSTEXPR T Eigen::internal::variable_if_dynamicindex< T, Value >::value () inline static
 { return T(Value); }
Referenced by Eigen::Diagonal< MatrixType, DiagIndex_ >::absDiagIndex(), Eigen::internal::evaluator< Diagonal< ArgType, DiagIndex > >::colOffset(), Eigen::Diagonal< MatrixType, DiagIndex_ >::colOffset(), Eigen::internal::ArithmeticSequenceRange< FirstAtCompileTime_, SizeAtCompileTime_, IncrAtCompileTime_ >::first(), Eigen::internal::SingleRange< ValueAtCompileTime >::first(), Eigen::internal::ArithmeticSequenceRange< FirstAtCompileTime_, SizeAtCompileTime_, IncrAtCompileTime_ >::incr(), Eigen::internal::evaluator< Diagonal< ArgType, DiagIndex > >::rowOffset(), Eigen::Diagonal< MatrixType, DiagIndex_ >::rowOffset(), and Eigen::internal::variable_if_dynamicindex< T, DynamicIndex >::setValue().
The documentation for this class was generated from the following file:
XprHelper.h