MercuryDPM: StatisticsVector< T > Class Template Reference
StatisticsVector< T > Class Template Reference
This class is used to extract statistical data from MD simulations.
#include <StatisticsVector.h>
Public Member Functions
void constructor ()
this is the actual constructor, sets up all basic things
void constructor (std::string name)
StatisticsVector ()
Basic constructor only calls constructor()
StatisticsVector (std::string name)
StatisticsVector (StatisticsVector &other)
Copy constructor.
StatisticsVector (int argc, char *argv[])
Advanced constructor that accepts arguments from the command line.
void readStatArguments (int argc, char *argv[])
std::string printStat ()
Outputs member variable values to a std::string.
void set_statType ()
void writeOutputFiles ()
Writes simulation data to all the main Mercury files: .data, .ene, .fstat, .xballs and .restart (see the Mercury website for more details regarding these files).
void print_help ()
void setNX (int new_)
void set_hx (Mdouble hx)
void setNY (int new_)
void set_hy (Mdouble hy)
void setNZ (int new_)
void set_hz (Mdouble hz)
void setN (int n)
void set_h (Mdouble h)
int getNX ()
int getNY ()
int getNZ ()
void setCGTimeMin (Mdouble t)
void setTimeMaxStat (Mdouble t)
void setCGTimeAveragingInterval (Mdouble t)
Mdouble getCGTimeMin ()
Mdouble getTimeMaxStat ()
Mdouble getCGTimeAveragingInterval ()
bool check_current_time_for_statistics ()
void setCGShape (const char *new_)
void setCGShape (CG_TYPE new_)
CG_TYPE getCGShape ()
void setN (int nx_, int ny_, int nz_)
void getN (int &nx_, int &ny_, int &nz_)
void setCGWidth (Mdouble w)
Set CG variables w2 and CG_invvolume.
void setCGWidth2 (Mdouble new_)
Set CG variables w2 and CG_invvolume.
Mdouble getCGWidth ()
Mdouble getCGWidthSquared ()
Mdouble getCutoff ()
Mdouble getCutoff2 ()
std::string print_CG ()
Output coarse graining variables.
StatisticsPoint< T > average (std::vector< StatisticsPoint< T > > &P)
Output average of statistical variables.
virtual void reset_statistics ()
Set all statistical variables to zero.
void statistics_from_fstat_and_data ()
get StatisticsPoint
void statistics_from_p3 ()
void jump_p3c ()
void setDoTimeAverage (bool new_)
bool getDoTimeAverage ()
void setStressTypeForFixedParticles (int new_)
int getStressTypeForFixedParticles ()
void set_infiniteStressForFixedParticles (bool new_)
void setMirrorAtDomainBoundary (Mdouble new_)
Mdouble getMirrorAtDomainBoundary ()
void setDoVariance (bool new_)
bool getDoVariance ()
void setDoGradient (bool new_)
bool getDoGradient ()
void setSuperExact (bool new_)
bool getSuperExact ()
void setDoIgnoreFixedParticles (bool new_)
bool getDoIgnoreFixedParticles ()
void verbose ()
void setVerbosityLevel (int new_)
int getVerbosityLevel () const
void setCGWidthalls (bool new_)
bool getCGWidthalls ()
void setDoPeriodicWalls (bool new_)
bool getDoPeriodicWalls ()
void setCGWidth_over_rmax (Mdouble new_)
Mdouble getCGWidth_over_rmax ()
void setPositions ()
Set position of StatisticsPoint points and set variables to 0.
bool readNextDataFile (unsigned int format)
void gather_force_statistics_from_fstat_and_data ()
void gather_force_statistics_from_p3c (int version)
void gather_force_statistics_from_p3w (int version, std::vector< int > &index)
void evaluate_force_statistics (int wp=0)
void evaluate_wall_force_statistics (Vec3D P, int wp=0)
void jump_fstat ()
void initialiseStatistics ()
Initializes statistics, i.e. setting w2, setting the grid and writing the header lines in the .stat file.
void outputStatistics ()
Calculates statistics for Particles (i.e. not collisions)
void gatherContactStatistics (unsigned int index1, int index2, Vec3D Contact, Mdouble delta, Mdouble ctheta, Mdouble fdotn, Mdouble fdott, Vec3D P1_P2_normal_, Vec3D P1_P2_tangential)
Calculates statistics for one collision (can be any kind of collision)
void processStatistics (bool usethese)
Processes all gathered statistics and resets them afterwards. (Processing means either calculating time averages or writing out statistics)
void finishStatistics ()
Finish all statistics (i.e. write out final data)
void write_statistics ()
Writes regular statistics.
void write_time_average_statistics ()
Writes out time averaged statistics.
void evaluate_particle_statistics (std::vector< BaseParticle * >::iterator P, int wp=0)
Calculates statistics for a single Particle.
std::vector< StatisticsPoint< T > > getCGPoints ()
Mdouble getXMinStat ()
Functions to acces and change the domain of statistics.
Mdouble getYMinStat ()
Mdouble getZMinStat ()
Mdouble getXMaxStat ()
Mdouble getYMaxStat ()
Mdouble getZMaxStat ()
void setXMinStat (Mdouble xMinStat_)
void setYMinStat (Mdouble yMinStat_)
void setZMinStat (Mdouble zMinStat_)
void setXMaxStat (Mdouble xMaxStat_)
void setYMaxStat (Mdouble yMaxStat_)
void setZMaxStat (Mdouble zMaxStat_)
int getNTimeAverage ()
Mdouble setInfinitelyLongDistance ()
void set_Polynomial (std::vector< Mdouble > new_coefficients, unsigned int new_dim)
void set_Polynomial (Mdouble *new_coefficients, unsigned int num_coeff, unsigned int new_dim)
void setPolynomialName (const char *new_name)
std::string getPolynomialName ()
void setDoDoublePoints (bool new_)
bool getDoDoublePoints ()
void setNTimeAverageReset (int new_)
bool getNTimeAverageReset ()
void set_rmin (Mdouble new_)
void set_rmax (Mdouble new_)
void set_hmax (Mdouble new_)
Mdouble evaluatePolynomial (Mdouble r)
Mdouble evaluatePolynomialGradient (Mdouble r)
Mdouble evaluateIntegral (Mdouble n1, Mdouble n2, Mdouble t)
unsigned int getStepSize () const
void setStepSize (unsigned int stepSize)
void setIndSpecies (unsigned int indSpecies)
Public Member Functions inherited from DPMBase
void constructor ()
A function which initialises the member variables to default values, so that the problem can be solved off the shelf; sets up a basic two dimensional problem which can be solved off the shelf. It is called in the constructor DPMBase().
DPMBase ()
Constructor that calls the "void constructor()".
DPMBase (const DPMBase &other)
Copy constructor type-2.
virtual ~DPMBase ()
virtual destructor
void autoNumber ()
The autoNumber() function calls three functions: setRunNumber(), readRunNumberFromFile() and incrementRunNumberInFile().
std::vector< int > get1DParametersFromRunNumber (int size_x) const
This turns a counter into 1 index, which is a useful feature for performing 1D parameter study. The index run from 1:size_x, while the study number starts at 0 (initially the counter=1 in COUNTER_DONOTDEL)
std::vector< int > get2DParametersFromRunNumber (int size_x, int size_y) const
This turns a counter into 2 indices which is a very useful feature for performing a 2D study. The indices run from 1:size_x and 1:size_y, while the study number starts at 0 (initially the counter=1 in COUNTER_DONOTDEL)
std::vector< int > get3DParametersFromRunNumber (int size_x, int size_y, int size_z) const
This turns a counter into 3 indices, which is a useful feature for performing a 3D parameter study. The indices run from 1:size_x, 1:size_y and 1:size_z, while the study number starts at 0 (initially the counter=1 in COUNTER_DONOTDEL)
int launchNewRun (const char *name, bool quick=false)
This launches a code from within this code. Please pass the name of the code to run.
void setRunNumber (int runNumber)
This sets the counter/Run number, overriding the defaults.
int getRunNumber () const
This returns the current value of the counter (runNumber_)
virtual void decompose ()
Sends particles from processorId to the root processor.
void solve ()
The work horse of the code.
void initialiseSolve ()
Beginning of the solve routine, before time stepping.
void finaliseSolve ()
End of the solve routine, after time stepping.
virtual void computeOneTimeStep ()
Performs everything needed for one time step, used in the time-loop of solve().
void checkSettings ()
Checks if the essentials are set properly to go ahead with solving the problem.
void forceWriteOutputFiles ()
Writes output files immediately, even if the current time step was not meant to be written. Also resets the last saved time step.
void solve (int argc, char *argv[])
The work horse of the code. Can handle flags from the command line.
virtual void setupInitialConditions ()
This function allows to set the initial conditions for our problem to be solved, by default particle locations are randomly set. Remember particle properties must also be defined here.
virtual void writeXBallsScript () const
This writes a script which can be used to load the xballs problem to display the data just generated.
virtual Mdouble getInfo (const BaseParticle &P) const
A virtual function that returns some user-specified information about a particle.
ParticleVtkWriter * getVtkWriter () const
virtual void writeRestartFile ()
Stores all the particle data for current save time step to a "restart" file, which is a file simply intended to store all the information necessary to "restart" a simulation from a given time step (see also MercuryDPM.org for more information on restart files).
void writeDataFile ()
void writeEneFile ()
void writeFStatFile ()
void fillDomainWithParticles (unsigned N=50)
bool readRestartFile (ReadOptions opt=ReadOptions::ReadAll)
Reads all the particle data corresponding to a given, existing . restart file (for more details regarding restart files, refer to the training materials on the MercuryDPM website).Returns true if it is successful, false otherwise.
int readRestartFile (std::string fileName, ReadOptions opt=ReadOptions::ReadAll)
The same as readRestartFile(bool), but also reads all the particle data corresponding to the current saved time step.
virtual void write (std::ostream &os, bool writeAllParticles=true) const
virtual void read (std::istream &is, ReadOptions opt=ReadOptions::ReadAll)
Reads all data from a restart file, e.g. domain data and particle data.
virtual BaseWall * readUserDefinedWall (const std::string &type) const
Allows you to read in a wall defined in a Driver directory; see USER/Luca/ScrewFiller.
virtual void readOld (std::istream &is)
Reads all data from a restart file, e.g. domain data and particle data; old version.
bool readDataFile (std::string fileName="", unsigned int format=0)
This allows particle data to be reloaded from data files.
bool readParAndIniFiles (std::string fileName)
Allows the user to read par.ini files (useful to read files produced by the MDCLR simulation code - external to MercuryDPM)
bool readNextDataFile (unsigned int format=0)
Reads the next data file with default format=0. However, one can modify the format based on whether the particle data corresponds to 3D or 2D data- see Visualising data in xballs.
void readNextFStatFile ()
Reads the next fstat file.
bool findNextExistingDataFile (Mdouble tMin, bool verbose=true)
Finds and opens the next data file, if such a file exists.
bool readArguments (int argc, char *argv[])
Can interpret main function input arguments that are passed by the driver codes.
virtual bool readNextArgument (int &i, int argc, char *argv[])
Interprets the i^th command-line argument.
virtual bool checkParticleForInteraction (const BaseParticle &P)
Checks whether a particle P has any interaction with walls or other particles.
virtual bool checkParticleForInteractionLocal (const BaseParticle &P)
Checks if a particle P has any interaction with walls or other particles in the local domain.
bool checkParticleForInteractionLocalPeriodic (const BaseParticle &P)
void readSpeciesFromDataFile (bool read=true)
void importParticlesAs (ParticleHandler &particleHandler, InteractionHandler &interactionHandler, const ParticleSpecies *species)
Copies particles, interactions assigning species from a local simulation to a global one. Useful for the creation of a cluster.
MERCURYDPM_DEPRECATED File & getDataFile ()
The non const version. Allows one to edit the File::dataFile.
MERCURYDPM_DEPRECATED File & getEneFile ()
The non const version. Allows to edit the File::eneFile.
MERCURYDPM_DEPRECATED File & getFStatFile ()
The non const version. Allows to edit the File::fStatFile.
MERCURYDPM_DEPRECATED File & getRestartFile ()
The non const version. Allows to edit the File::restartFile.
MERCURYDPM_DEPRECATED File & getStatFile ()
The non const version. Allows to edit the File::statFile.
File & getInteractionFile ()
Return a reference to the file InteractionsFile.
MERCURYDPM_DEPRECATED const File & getDataFile () const
The const version. Does not allow for any editing of the File::dataFile.
MERCURYDPM_DEPRECATED const File & getEneFile () const
The const version. Does not allow for any editing of the File::eneFile.
MERCURYDPM_DEPRECATED const File & getFStatFile () const
The const version. Does not allow for any editing of the File::fStatFile.
MERCURYDPM_DEPRECATED const File & getRestartFile () const
The const version. Does not allow for any editing of the File::restartFile.
MERCURYDPM_DEPRECATED const File & getStatFile () const
The const version. Does not allow for any editing of the File::statFile.
const File & getInteractionFile () const
Returns a constant reference to an Interactions file.
const std::string & getName () const
Returns the name of the file. Does not allow to change it though.
void setName (const std::string &name)
Allows to set the name of all the files (ene, data, fstat, restart, stat)
void setName (const char *name)
Calls setName(std::string)
void setSaveCount (unsigned int saveCount)
Sets File::saveCount_ for all files (ene, data, fstat, restart, stat)
void setFileType (FileType fileType)
Sets File::fileType_ for all files (ene, data, fstat, restart, stat)
void setOpenMode (std::fstream::openmode openMode)
Sets File::openMode_ for all files (ene, data, fstat, restart, stat)
void resetFileCounter ()
Resets the file counter for each file i.e. for ene, data, fstat, restart, stat)
void closeFiles ()
Closes all files (ene, data, fstat, restart, stat) that were opened to read or write.
void setVTKOutputDirectory (const std::string &dir)
Sets the output directory of the VTK files.
void setLastSavedTimeStep (unsigned int nextSavedTimeStep)
Sets the next time step for all the files (ene, data, fstat, restart, stat) at which the data is to be written or saved.
Mdouble getTime () const
Returns the current simulation time.
Mdouble getNextTime () const
Returns the current simulation time.
unsigned int getNumberOfTimeSteps () const
Returns the current counter of time-steps, i.e. the number of time-steps that the simulation has undergone so far.
void setTime (Mdouble time)
Sets a new value for the current simulation time.
void setTimeMax (Mdouble newTMax)
Sets a new value for the maximum simulation duration.
Mdouble getTimeMax () const
Returns the maximum simulation duration.
void setLogarithmicSaveCount (Mdouble logarithmicSaveCountBase)
Sets File::logarithmicSaveCount_ for all files (ene, data, fstat, restart, stat)
void setNToWrite (int nToWrite)
set the number of elements to write to the screen
int getNToWrite () const
get the number of elements to write to the
void setRotation (bool rotation)
Sets whether particle rotation is enabled or disabled.
bool getRotation () const
Indicates whether particle rotation is enabled or disabled.
MERCURYDPM_DEPRECATED void setWallsWriteVTK (FileType writeWallsVTK)
Sets whether walls are written into a VTK file.
MERCURYDPM_DEPRECATED void setWallsWriteVTK (bool)
Sets whether walls are written into a VTK file.
MERCURYDPM_DEPRECATED void setInteractionsWriteVTK (bool)
Sets whether interactions are written into a VTK file.
void setParticlesWriteVTK (bool writeParticlesVTK)
Sets whether particles are written in a VTK file.
void setSuperquadricParticlesWriteVTK (bool writeSuperquadricParticlesVTK)
MERCURYDPM_DEPRECATED FileType getWallsWriteVTK () const
Returns whether walls are written in a VTK file.
bool getParticlesWriteVTK () const
Returns whether particles are written in a VTK file.
bool getSuperquadricParticlesWriteVTK () const
Mdouble getXMin () const
If the length of the problem domain in x-direction is XMax - XMin, then getXMin() returns XMin.
Mdouble getXMax () const
If the length of the problem domain in x-direction is XMax - XMin, then getXMax() returns XMax.
Mdouble getYMin () const
If the length of the problem domain in y-direction is YMax - YMin, then getYMin() returns YMin.
Mdouble getYMax () const
If the length of the problem domain in y-direction is YMax - YMin, then getYMax() returns XMax.
Mdouble getZMin () const
If the length of the problem domain in z-direction is ZMax - ZMin, then getZMin() returns ZMin.
Mdouble getZMax () const
If the length of the problem domain in z-direction is ZMax - ZMin, then getZMax() returns ZMax.
Mdouble getXCenter () const
Mdouble getYCenter () const
Mdouble getZCenter () const
Vec3D getCenter () const
get center of domain
Vec3D getMin () const
Returns the minimum coordinates of the problem domain.
Vec3D getMax () const
Returns the maximum coordinates of the problem domain.
void setXMin (Mdouble newXMin)
Sets the value of XMin, the lower bound of the problem domain in the x-direction.
void setYMin (Mdouble newYMin)
Sets the value of YMin, the lower bound of the problem domain in the y-direction.
void setZMin (Mdouble newZMin)
Sets the value of ZMin, the lower bound of the problem domain in the z-direction.
void setXMax (Mdouble newXMax)
Sets the value of XMax, the upper bound of the problem domain in the x-direction.
void setYMax (Mdouble newYMax)
Sets the value of YMax, the upper bound of the problem domain in the y-direction.
void setZMax (Mdouble newZMax)
Sets the value of ZMax, the upper bound of the problem domain in the z-direction.
void setMax (const Vec3D &max)
Sets the maximum coordinates of the problem domain.
void setMax (Mdouble, Mdouble, Mdouble)
Sets the maximum coordinates of the problem domain.
void setDomain (const Vec3D &min, const Vec3D &max)
Sets the minimum coordinates of the problem domain.
void setMin (const Vec3D &min)
Sets the minimum coordinates of the problem domain.
void setMin (Mdouble, Mdouble, Mdouble)
Sets the minimum coordinates of the problem domain.
void setTimeStep (Mdouble newDt)
Sets a new value for the simulation time step.
Mdouble getTimeStep () const
Returns the simulation time step.
void setNumberOfOMPThreads (int numberOfOMPThreads)
Sets the number of omp threads.
int getNumberOfOMPThreads () const
Returns the number of omp threads.
void setXBallsColourMode (int newCMode)
Set the xballs output mode.
int getXBallsColourMode () const
Get the xballs colour mode (CMode).
void setXBallsVectorScale (double newVScale)
Set the scale of vectors in xballs.
double getXBallsVectorScale () const
Returns the scale of vectors used in xballs.
void setXBallsAdditionalArguments (std::string newXBArgs)
Set the additional arguments for xballs.
std::string getXBallsAdditionalArguments () const
Returns the additional arguments for xballs.
void setXBallsScale (Mdouble newScale)
Sets the scale of the view (either normal, zoom in or zoom out) to display in xballs. The default is fit to screen.
double getXBallsScale () const
Returns the scale of the view in xballs.
void setGravity (Vec3D newGravity)
Sets a new value for the gravitational acceleration.
Vec3D getGravity () const
Returns the gravitational acceleration.
void setBackgroundDrag (Mdouble backgroundDrag)
Simple access function to turn on a background drag. The force of particleVelocity*drag is applied (note, it allowed to be negative i.e. create energy)
const Mdouble getBackgroundDrag () const
Return the background drag.
void setDimension (unsigned int newDim)
Sets both the system dimensions and the particle dimensionality.
void setSystemDimensions (unsigned int newDim)
Sets the system dimensionality.
unsigned int getSystemDimensions () const
Returns the system dimensionality.
void setParticleDimensions (unsigned int particleDimensions)
Sets the particle dimensionality.
unsigned int getParticleDimensions () const
Returns the particle dimensionality.
std::string getRestartVersion () const
This is to take into account for different Mercury versions. Returns the version of the restart file.
void setRestartVersion (std::string newRV)
Sets restart_version.
bool getRestarted () const
Returns the flag denoting if the simulation was restarted or not.
void setRestarted (bool newRestartedFlag)
Allows to set the flag stating if the simulation is to be restarted or not.
bool getAppend () const
Returns whether the "append" option is on or off.
void setAppend (bool newAppendFlag)
Sets whether the "append" option is on or off.
Mdouble getElasticEnergy () const
Returns the global elastic energy within the system.
Mdouble getKineticEnergy () const
Returns the global kinetic energy stored in the system.
Mdouble getGravitationalEnergy (Vec3D origin={0, 0, 0}) const
Returns the global gravitational potential energy stored relative to a user-defined origin in the system. Note, if no origin is specified the real origin i.e. (0,0,0) is taken.
Mdouble getRotationalEnergy () const
Returns the global rotational energy stored in the system.
Mdouble getTotalEnergy () const
Mdouble getTotalMass () const
JMFT: Return the total mass of the system, excluding fixed particles.
Vec3D getCentreOfMass () const
JMFT: Return the centre of mass of the system, excluding fixed particles.
Vec3D getTotalMomentum () const
JMFT: Return the total momentum of the system, excluding fixed particles.
double getCPUTime ()
double getWallTime ()
virtual void hGridInsertParticle (BaseParticle *obj UNUSED)
virtual void hGridUpdateParticle (BaseParticle *obj UNUSED)
virtual void hGridRemoveParticle (BaseParticle *obj UNUSED)
virtual void hGridUpdateMove (BaseParticle *, Mdouble)
bool mpiIsInCommunicationZone (BaseParticle *particle)
Checks if the position of the particle is in an mpi communication zone or not.
bool mpiInsertParticleCheck (BaseParticle *P)
Function that checks if the mpi particle should really be inserted by the current domain.
void insertGhostParticle (BaseParticle *P)
This function inserts a particle in the mpi communication boundaries.
void updateGhostGrid (BaseParticle *P)
Checks if the Domain/periodic interaction distance needs to be updated and updates it accordingly.
void setNumberOfDomains (std::vector< unsigned > direction)
Sets the number of domains in x-,y- and z-direction. Required for parallel computations.
void splitDomain (DomainSplit domainSplit)
std::vector< unsigned > getNumberOfDomains ()
returns the number of domains
Domain * getCurrentDomain ()
Function that returns a pointer to the domain corresponding to the processor.
void removeOldFiles () const
virtual void hGridGetInteractingParticleList (BaseParticle *obj, std::vector< BaseParticle * > &list)
Creates a list of neighbour particles obtained from the hgrid.
virtual void computeWallForces (BaseWall *w)
virtual bool getHGridUpdateEachTimeStep () const
void setMeanVelocity (Vec3D V_mean_goal)
This function will help you set a fixed kinetic energy and mean velocity in your system.
void setMeanVelocityAndKineticEnergy (Vec3D V_mean_goal, Mdouble Ek_goal)
This function will help you set a fixed kinetic energy and mean velocity in your system.
Mdouble getTotalVolume () const
Get the total volume of the cuboid system.
Matrix3D getKineticStress () const
Calculate the kinetic stress tensor in the system averaged over the whole volume.
Matrix3D getStaticStress () const
Calculate the static stress tensor in the system averaged over the whole volume.
Matrix3D getTotalStress () const
Calculate the total stress tensor in the system averaged over the whole volume.
virtual void handleParticleRemoval (unsigned int id)
Handles the removal of particles from the particleHandler.
virtual void handleParticleAddition (unsigned int id, BaseParticle *p)
Handles the addition of particles to the particleHandler.
void writePythonFileForVTKVisualisation () const
writes .py file for ParaView
void setWritePythonFileForVTKVisualisation (bool forceWritePythonFileForVTKVisualisation)
bool getWritePythonFileForVTKVisualisation () const
WallVTKWriter & getWallVTKWriter ()
Protected Member Functions
bool satisfiesInclusionCriteria (BaseParticle *P)
bool loadVelocityProfile (const char *filename)
bool loadPositions (const char *filename)
Vec3D getVelocityProfile (Vec3D Position)
bool read_next_from_p3p_file ()
void autoSetSystemDimensions ()
Protected Member Functions inherited from DPMBase
virtual void computeAllForces ()
Computes all the forces acting on the particles using the BaseInteractable::setForce() and BaseInteractable::setTorque()
virtual void computeInternalForces (BaseParticle *)
Computes the internal forces on particle i (internal in the sense that the sum over all these forces is zero i.e. fully modelled forces)
virtual void computeInternalForce (BaseParticle *, BaseParticle *)
Computes the forces between two particles (internal in the sense that the sum over all these forces is zero i.e. fully modelled forces)
virtual void computeExternalForces (BaseParticle *)
Computes the external forces, such as gravity, acting on particles.
virtual void computeForcesDueToWalls (BaseParticle *, BaseWall *)
Computes the forces on the particles due to the walls (normals are outward normals)
virtual void actionsOnRestart ()
A virtual function where the users can add extra code which is executed only when the code is restarted.
virtual void actionsBeforeTimeLoop ()
A virtual function. Allows one to carry out any operations before the start of the time loop.
virtual void hGridActionsBeforeTimeLoop ()
A virtual function that allows one to carry out hGrid operations before the start of the time loop.
virtual void hGridActionsBeforeTimeStep ()
A virtual function that allows one to set or execute hGrid parameters or operations before every simulation time step.
virtual void actionsBeforeTimeStep ()
A virtual function which allows to define operations to be executed before the new time step.
virtual void computeAdditionalForces ()
A virtual function which allows to define operations to be executed prior to the OMP force collect.
virtual void actionsAfterSolve ()
A virtual function which allows to define operations to be executed after the solve().
virtual void actionsAfterTimeStep ()
A virtual function which allows to define operations to be executed after time step.
void writeVTKFiles () const
virtual void outputXBallsData (std::ostream &os) const
This function writes the location of the walls and particles in a format the XBalls program can read. For more information on the XBalls program, see Visualising data in xballs.
virtual void outputXBallsDataParticle (unsigned int i, unsigned int format, std::ostream &os) const
This function writes out the particle locations into an output stream in a format the XBalls program can read. For more information on the XBalls program, see Visualising data in xballs.
virtual void writeEneHeader (std::ostream &os) const
Writes a header with a certain format for ENE file.
virtual void writeFstatHeader (std::ostream &os) const
Writes a header with a certain format for FStat file.
virtual void writeEneTimeStep (std::ostream &os) const
Write the global kinetic, potential energy, etc. in the system.
void gatherContactStatistics ()
virtual void integrateBeforeForceComputation ()
Update particles' and walls' positions and velocities before force computation.
virtual void integrateAfterForceComputation ()
Update particles' and walls' positions and velocities after force computation.
virtual void checkInteractionWithBoundaries ()
There are a range of boundaries one could implement depending on ones' problem. This methods checks for interactions between particles and such range of boundaries. See BaseBoundary.h and all the boundaries in the Boundaries folder.
virtual void hGridActionsBeforeIntegration ()
This function has to be called before integrateBeforeForceComputation.
virtual void hGridActionsAfterIntegration ()
This function has to be called after integrateBeforeForceComputation.
void setFixedParticles (unsigned int n)
Sets a number, n, of particles in the particleHandler as "fixed particles".
virtual void printTime () const
Displays the current simulation time and the maximum simulation duration.
virtual bool continueSolve () const
A virtual function for deciding whether to continue the simulation, based on a user-specified criterion.
void outputInteractionDetails () const
Displays the interaction details corresponding to the pointer objects in the interaction handler.
bool isTimeEqualTo (Mdouble time) const
Checks whether the input variable "time" is the current time in the simulation.
void removeDuplicatePeriodicParticles ()
Removes periodic duplicate Particles.
void checkAndDuplicatePeriodicParticles ()
For simulations using periodic boundaries, checks and adds particles when necessary into the particle handler. See DPMBase.cc and PeriodicBoundary.cc for more details.
void performGhostParticleUpdate ()
When the Verlet scheme updates the positions and velocities of particles, ghost particles will need an update as wel. Their status will also be updated accordingly.
void deleteGhostParticles (std::set< BaseParticle * > &particlesToBeDeleted)
void synchroniseParticle (BaseParticle *, unsigned fromProcessor=0)
void performGhostVelocityUpdate ()
updates the final time-step velocity of the ghost particles
void disableSoftStop ()
This prevents the initialisation of the soft stop feature.
void discontinueSolve ()
This discontinues the solve loop after the current time step is finished.
Protected Attributes
StatType statType
Possible values X,Y,Z,XY,XZ,YZ,XYZ,RAZ,RA,RZ,AZ,R,A are used to determine if the statistics are averaged; f.e. StatType X is averaged over y and z.
int nx
Grid size nx,ny,nz (by default the points of evaluation are placed in an grid on the domain [xMinStat,xMaxStat]x[yMinStat,yMaxStat]x[zMinStat,zMaxStat].
int ny
see nx
int nz
see nx
Mdouble xMinStat
By default the domain is set to the domain of the MD problem (indicated by setting the stat-domain values to nan), but can be resized.
Mdouble xMaxStat
Mdouble yMinStat
Mdouble yMaxStat
Mdouble zMinStat
Mdouble zMaxStat
int nxMirrored
extension of grid size from mirrored points
int nyMirrored
int nzMirrored
std::vector< StatisticsPoint< T > > Points
A vector that stores the values of the statistical variables at a given position.
std::vector< StatisticsPoint< T > > dx
A vector that stores the gradient in x of all statistical variables at a given position.
std::vector< StatisticsPoint< T > > dy
A vector that stores the gradient in y of all statistical variables at a given position.
std::vector< StatisticsPoint< T > > dz
A vector that stores the gradient in z of all statistical variables at a given position.
std::vector< StatisticsPoint< T > > timeAverage
A vector used to sum up all statistical values in Points for time-averaging.
std::vector< StatisticsPoint< T > > timeVariance
a vector used to sum up the variance in time of all statistical values
std::vector< StatisticsPoint< T > > dxTimeAverage
a vector used to sum up all statistical gradients in dx for time-averaging
std::vector< StatisticsPoint< T > > dyTimeAverage
a vector used to sum up all statistical gradients in dy for time-averaging
std::vector< StatisticsPoint< T > > dzTimeAverage
a vector used to sum up all statistical gradients in dz for time-averaging
bool doTimeAverage
Determines if output is averaged over time.
int nTimeAverageReset
Determines after how many time steps the time average is reset.
bool doVariance
Determines if variance is outputted.
bool doGradient
Determines if gradient is outputted.
int nTimeAverage
A counter needed to average over time.
CG_TYPE CG_type
coarse graining type (Gaussian, Heaviside, Polynomial)
NORMALIZED_POLYNOMIAL< T > CGPolynomial
Stores the Polynomial, if the cg function is an axisymmetric function Polynomial in r.
Mdouble w2
coarse graining width squared; for HeavisideSphere and Gaussian
Mdouble cutoff
The distance from the origin at which the cg function vanishes; cutoff=w for HeavisideSphere or Polynomial, 3*w for Gaussian.
Mdouble cutoff2
Mdouble w_over_rmax
if w is not set manually then w will be set by multiplying this value by the largest particle radius at t=0
Mdouble tMinStat
Statistical output will only be created if t>tMinStat.
Mdouble tMaxStat
Statistical output will only be created if t<tMaxStat.
Mdouble tIntStat
Statistical output will only be created if tMaxStat-tIntStat< t< tMaxStat.
Mdouble indSpecies
defines the species for which statistics are extracted (-1 for all species)
Mdouble rmin
defines the minimum radius of the particles for which statistics are extracted
Mdouble rmax
defines the maximum radius of the particles for which statistics are extracted
Mdouble hmax
defines the maximum height of the particles for which statistics are extracted
bool walls
Turns off walls before evaluation.
bool periodicWalls
Turns off periodic walls before evaluation (needed for averaging, because we do not yet check if particle is in domain)
bool ignoreFixedParticles
Determines if fixed particles contribute to particle statistics (density, ...)
int StressTypeForFixedParticles
Stress type for fixed particles.
int verbosity
Determines how much is outputted to the terminal.
int format
format of the data input file
Mdouble mirrorAtDomainBoundary
0: Statistics near the wall are equal to statistics away from the wall; 1: Statistics are mirrored at the domain boundaries; up to a maximum depth specified by this number
bool isMDCLR
bool superexact
If true, cutoff radius for Gaussian is set to 5*w (from 3*w)
bool doDoublePoints
Vec3D P1
Position of first contact point.
Vec3D P2
Position of second contact point.
Vec3D P1_P2_normal
Direction of contact.
Mdouble P1_P2_distance
Length of contact line.
Matrix3D P1_P2_NormalStress
Contact stress from normal forces along the line of contact.
Matrix3D P1_P2_ContactCoupleStress
Vec3D P1_P2_Contact
Matrix3D P1_P2_TangentialStress
Contact stress from tangential forces along the line of contact.
Vec3D P1_P2_NormalTraction
Traction from normal forces at contact of flow with fixed particles or walls.
Vec3D P1_P2_TangentialTraction
Traction from tangential forces at contact of flow with fixed particles or walls.
MatrixSymmetric3D P1_P2_Fabric
Fabric.
Vec3D P1_P2_CollisionalHeatFlux
not yet working
Mdouble P1_P2_Dissipation
not yet working
Mdouble P1_P2_Potential
not yet working
std::vector< Vec3D > VelocityProfile
Vec3D VelocityProfile_Min
Vec3D VelocityProfile_D
std::fstream p3p_file
std::fstream p3c_file
std::fstream p3w_file
bool p3Format = true
unsigned int stepSize_
std::vector< Vec3D > positions_
bool centerPointInFStat_ = true
Additional Inherited Members
Public Types inherited from DPMBase
enum class ReadOptions : int { ReadAll , ReadNoInteractions , ReadNoParticlesAndInteractions }
enum class DomainSplit {
X , Y , Z , XY ,
XZ , YZ , XYZ
}
Static Public Member Functions inherited from DPMBase
static void incrementRunNumberInFile ()
Increment the run Number (counter value) stored in the file_counter (COUNTER_DONOTDEL) by 1 and store the new value in the counter file.
static int readRunNumberFromFile ()
Read the run number or the counter from the counter file (COUNTER_DONOTDEL)
static bool areInContact (const BaseParticle *pI, const BaseParticle *pJ)
Checks if two particle are in contact or is there any positive overlap.
Public Attributes inherited from DPMBase
SpeciesHandler speciesHandler
A handler to that stores the species type i.e. LinearViscoelasticSpecies, etc.
RNG random
This is a random generator, often used for setting up the initial conditions etc...
ParticleHandler particleHandler
An object of the class ParticleHandler, contains the pointers to all the particles created.
ParticleHandler paoloParticleHandler
Fake particleHandler created by Paolo needed temporary by just Paolo.
WallHandler wallHandler
An object of the class WallHandler. Contains pointers to all the walls created.
BoundaryHandler boundaryHandler
An object of the class BoundaryHandler which concerns insertion and deletion of particles into or from regions.
PeriodicBoundaryHandler periodicBoundaryHandler
Internal handler that deals with periodic boundaries, especially in a parallel build.
DomainHandler domainHandler
An object of the class DomainHandler which deals with parallel code.
InteractionHandler interactionHandler
An object of the class InteractionHandler.
CGHandler cgHandler
Object of the class cgHandler.
File dataFile
An instance of class File to handle in- and output into a .data file.
File fStatFile
An instance of class File to handle in- and output into a .fstat file.
File eneFile
An instance of class File to handle in- and output into a .ene file.
File restartFile
An instance of class File to handle in- and output into a .restart file.
File statFile
An instance of class File to handle in- and output into a .stat file.
File interactionFile
File class to handle in- and output into .interactions file. This file hold information about interactions.
Time clock_
record when the simulation started
Detailed Description
template<StatType T>
class StatisticsVector< T >
This class is used to extract statistical data from MD simulations.
When calling statistics_from_fstat_and_data(), statistical data (such as density, pressure, ...) will be extracted at various points in the domain, aligned in a nx*ny*nz grid.
Set functions can be used to define the dimensions of the grid (default: nx=ny=nz=1) and the type and width of the coarse graining function (default: Gaussian, width w=r_max).
Constructor & Destructor Documentation
StatisticsVector() [1/4]
template<StatType T> StatisticsVector< T >::StatisticsVector () inline
Basic constructor only calls constructor()
     {
         constructor();
     }
References StatisticsVector< T >::constructor().
StatisticsVector() [2/4]
template<StatType T> StatisticsVector< T >::StatisticsVector (std::string name) inline
     {
         constructor(name);
     }
References StatisticsVector< T >::constructor(), and plotDoE::name.
StatisticsVector() [3/4]
template<StatType T> StatisticsVector< T >::StatisticsVector (StatisticsVector< T > & other)
Copy constructor.
StatisticsVector() [4/4]
template<StatType T> StatisticsVector< T >::StatisticsVector (int argc, char * argv[])
Advanced constructor that accepts arguments from the command line.
Member Function Documentation
autoSetSystemDimensions()
template<StatType T> void StatisticsVector< T >::autoSetSystemDimensions () protected
average()
template<StatType T> StatisticsPoint<T> StatisticsVector< T >::average (std::vector< StatisticsPoint< T > > & P)
Output average of statistical variables.
check_current_time_for_statistics()
template<StatType T> bool StatisticsVector< T >::check_current_time_for_statistics () inline
     {
         return (getTime() >= getCGTimeMin() && getTime() <= getTimeMaxStat() + getTimeStep());
     }
References StatisticsVector< T >::getCGTimeMin(), DPMBase::getTime(), StatisticsVector< T >::getTimeMaxStat(), and DPMBase::getTimeStep().
constructor() [1/2]
template<StatType T> void StatisticsVector< T >::constructor ()
this is the actual constructor, sets up all basic things
Referenced by StatisticsVector< T >::StatisticsVector().
constructor() [2/2]
template<StatType T> void StatisticsVector< T >::constructor (std::string name)
evaluate_force_statistics()
template<StatType T> void StatisticsVector< T >::evaluate_force_statistics (int wp = 0)
evaluate_particle_statistics()
template<StatType T> void StatisticsVector< T >::evaluate_particle_statistics (std::vector< BaseParticle * >::iterator P, int wp = 0)
Calculates statistics for a single Particle.
evaluate_wall_force_statistics()
template<StatType T> void StatisticsVector< T >::evaluate_wall_force_statistics (Vec3D P, int wp = 0)
evaluateIntegral()
template<StatType T> Mdouble StatisticsVector< T >::evaluateIntegral (Mdouble n1, Mdouble n2, Mdouble t) inline
     {
         return CGPolynomial.evaluateIntegral(n1, n2, t);
     }
References StatisticsVector< T >::CGPolynomial, and plotPSD::t.
evaluatePolynomial()
template<StatType T> Mdouble StatisticsVector< T >::evaluatePolynomial (Mdouble r) inline
     {
         return CGPolynomial.evaluate(r);
     }
References StatisticsVector< T >::CGPolynomial, and UniformPSDSelfTest::r.
evaluatePolynomialGradient()
template<StatType T> Mdouble StatisticsVector< T >::evaluatePolynomialGradient (Mdouble r) inline
     {
         return CGPolynomial.evaluateGradient(r);
     }
References StatisticsVector< T >::CGPolynomial, and UniformPSDSelfTest::r.
finishStatistics()
template<StatType T> void StatisticsVector< T >::finishStatistics () virtual
Finish all statistics (i.e. write out final data)
Reimplemented from DPMBase.
Referenced by statistics_while_running< T >::finishStatistics().
gather_force_statistics_from_fstat_and_data()
template<StatType T> void StatisticsVector< T >::gather_force_statistics_from_fstat_and_data ()
gather_force_statistics_from_p3c()
template<StatType T> void StatisticsVector< T >::gather_force_statistics_from_p3c (int version)
gather_force_statistics_from_p3w()
template<StatType T> void StatisticsVector< T >::gather_force_statistics_from_p3w (int version, std::vector< int > & index)
gatherContactStatistics()
template<StatType T> void StatisticsVector< T >::gatherContactStatistics (unsigned int index1, int index2, Vec3D Contact, Mdouble delta, Mdouble ctheta, Mdouble fdotn, Mdouble fdott, Vec3D P1_P2_normal_, Vec3D P1_P2_tangential) virtual
Calculates statistics for one collision (can be any kind of collision)
Reimplemented from DPMBase.
getCGPoints()
template<StatType T> std::vector<StatisticsPoint<T> > StatisticsVector< T >::getCGPoints () inline
     {
         return Points;
     }
References StatisticsVector< T >::Points.
getCGShape()
template<StatType T> CG_TYPE StatisticsVector< T >::getCGShape () inline
     {
         return CG_type;
     }
References StatisticsVector< T >::CG_type.
getCGTimeAveragingInterval()
template<StatType T> Mdouble StatisticsVector< T >::getCGTimeAveragingInterval () inline
     {
         return tIntStat;
     }
References StatisticsVector< T >::tIntStat.
getCGTimeMin()
template<StatType T> Mdouble StatisticsVector< T >::getCGTimeMin () inline
     {
         return tMinStat;
     }
References StatisticsVector< T >::tMinStat.
Referenced by StatisticsVector< T >::check_current_time_for_statistics().
getCGWidth()
template<StatType T> Mdouble StatisticsVector< T >::getCGWidth () inline
     {
         return std::sqrt(w2);
     }
References sqrt(), and StatisticsVector< T >::w2.
Referenced by statistics_while_running< T >::run().
getCGWidth_over_rmax()
template<StatType T> Mdouble StatisticsVector< T >::getCGWidth_over_rmax () inline
     {
         return w_over_rmax;
     }
References StatisticsVector< T >::w_over_rmax.
getCGWidthalls()
template<StatType T> bool StatisticsVector< T >::getCGWidthalls () inline
     {
         return walls;
     }
References StatisticsVector< T >::walls.
getCGWidthSquared()
template<StatType T> Mdouble StatisticsVector< T >::getCGWidthSquared () inline
     {
         return w2;
     }
References StatisticsVector< T >::w2.
getCutoff()
template<StatType T> Mdouble StatisticsVector< T >::getCutoff () inline
     {
         return cutoff;
     }
References StatisticsVector< T >::cutoff.
getCutoff2()
template<StatType T> Mdouble StatisticsVector< T >::getCutoff2 () inline
     {
         return mathsFunc::square(cutoff);
     }
References StatisticsVector< T >::cutoff, and mathsFunc::square().
getDoDoublePoints()
template<StatType T> bool StatisticsVector< T >::getDoDoublePoints () inline
     {
         return doDoublePoints;
     }
References StatisticsVector< T >::doDoublePoints.
getDoGradient()
template<StatType T> bool StatisticsVector< T >::getDoGradient () inline
     {
         return doGradient;
     }
References StatisticsVector< T >::doGradient.
getDoIgnoreFixedParticles()
template<StatType T> bool StatisticsVector< T >::getDoIgnoreFixedParticles () inline
     {
         return ignoreFixedParticles;
     }
References StatisticsVector< T >::ignoreFixedParticles.
getDoPeriodicWalls()
template<StatType T> bool StatisticsVector< T >::getDoPeriodicWalls () inline
     {
         return periodicWalls;
     }
References StatisticsVector< T >::periodicWalls.
getDoTimeAverage()
template<StatType T> bool StatisticsVector< T >::getDoTimeAverage () inline
     {
         return doTimeAverage;
     }
References StatisticsVector< T >::doTimeAverage.
getDoVariance()
template<StatType T> bool StatisticsVector< T >::getDoVariance () inline
     {
         return doVariance;
     }
References StatisticsVector< T >::doVariance.
getMirrorAtDomainBoundary()
template<StatType T> Mdouble StatisticsVector< T >::getMirrorAtDomainBoundary () inline
     {
         return mirrorAtDomainBoundary;
     }
References StatisticsVector< T >::mirrorAtDomainBoundary.
getN()
template<StatType T> void StatisticsVector< T >::getN (int & nx_, int & ny_, int & nz_) inline
     {
         nx_ = nx;
         ny_ = ny;
         nz_ = nz;
     }
References StatisticsVector< T >::nx, StatisticsVector< T >::ny, and StatisticsVector< T >::nz.
getNTimeAverage()
template<StatType T> int StatisticsVector< T >::getNTimeAverage () inline
     {
         return nTimeAverage;
     }
References StatisticsVector< T >::nTimeAverage.
getNTimeAverageReset()
template<StatType T> bool StatisticsVector< T >::getNTimeAverageReset () inline
     {
         return nTimeAverageReset;
     }
References StatisticsVector< T >::nTimeAverageReset.
getNX()
template<StatType T> int StatisticsVector< T >::getNX () inline
     {
         return nx;
     }
References StatisticsVector< T >::nx.
getNY()
template<StatType T> int StatisticsVector< T >::getNY () inline
     {
         return ny;
     }
References StatisticsVector< T >::ny.
getNZ()
template<StatType T> int StatisticsVector< T >::getNZ () inline
     {
         return nz;
     }
References StatisticsVector< T >::nz.
getPolynomialName()
template<StatType T> std::string StatisticsVector< T >::getPolynomialName () inline
     {
         return CGPolynomial.getName();
     }
References StatisticsVector< T >::CGPolynomial.
getStepSize()
template<StatType T> unsigned int StatisticsVector< T >::getStepSize () const inline
     {
         return stepSize_;
     }
References StatisticsVector< T >::stepSize_.
getStressTypeForFixedParticles()
template<StatType T> int StatisticsVector< T >::getStressTypeForFixedParticles () inline
     {
         return StressTypeForFixedParticles;
     }
References StatisticsVector< T >::StressTypeForFixedParticles.
getSuperExact()
template<StatType T> bool StatisticsVector< T >::getSuperExact () inline
     {
         return superexact;
     }
References StatisticsVector< T >::superexact.
getTimeMaxStat()
template<StatType T> Mdouble StatisticsVector< T >::getTimeMaxStat () inline
     {
         if (std::isnan(tMaxStat))
             return getTimeMax();
         else
             return tMaxStat;
     }
References DPMBase::getTimeMax(), isnan, and StatisticsVector< T >::tMaxStat.
Referenced by StatisticsVector< T >::check_current_time_for_statistics().
getVelocityProfile()
template<StatType T> Vec3D StatisticsVector< T >::getVelocityProfile (Vec3D Position) protected
getVerbosityLevel()
template<StatType T> int StatisticsVector< T >::getVerbosityLevel () const inline
     {
         return verbosity;
     }
References StatisticsVector< T >::verbosity.
Referenced by statistics_while_running< T >::printTime().
getXMaxStat()
template<StatType T> Mdouble StatisticsVector< T >::getXMaxStat () inline
     {
         if (std::isnan(xMaxStat))
             return getXMax();
         else
             return xMaxStat;
     }
References DPMBase::getXMax(), isnan, and StatisticsVector< T >::xMaxStat.
Referenced by StatisticsVector< T >::set_hx().
getXMinStat()
template<StatType T> Mdouble StatisticsVector< T >::getXMinStat () inline
Functions to acces and change the domain of statistics.
     {
         if (std::isnan(xMinStat))
             return getXMin();
         else
             return xMinStat;
     }
References DPMBase::getXMin(), isnan, and StatisticsVector< T >::xMinStat.
Referenced by StatisticsVector< T >::set_hx().
getYMaxStat()
template<StatType T> Mdouble StatisticsVector< T >::getYMaxStat () inline
     {
         if (std::isnan(yMaxStat))
             return getYMax();
         else
             return yMaxStat;
     }
References DPMBase::getYMax(), isnan, and StatisticsVector< T >::yMaxStat.
Referenced by StatisticsVector< T >::set_hy().
getYMinStat()
template<StatType T> Mdouble StatisticsVector< T >::getYMinStat () inline
     {
         if (std::isnan(yMinStat))
             return getYMin();
         else
             return yMinStat;
     }
References DPMBase::getYMin(), isnan, and StatisticsVector< T >::yMinStat.
Referenced by StatisticsVector< T >::set_hy().
getZMaxStat()
template<StatType T> Mdouble StatisticsVector< T >::getZMaxStat () inline
     {
         if (std::isnan(zMaxStat))
             return getZMax();
         else
             return zMaxStat;
     }
References DPMBase::getZMax(), isnan, and StatisticsVector< T >::zMaxStat.
Referenced by StatisticsVector< T >::set_hz().
getZMinStat()
template<StatType T> Mdouble StatisticsVector< T >::getZMinStat () inline
     {
         if (std::isnan(zMinStat))
             return getZMin();
         else
             return zMinStat;
     }
References DPMBase::getZMin(), isnan, and StatisticsVector< T >::zMinStat.
Referenced by StatisticsVector< T >::set_hz().
initialiseStatistics()
template<StatType T> void StatisticsVector< T >::initialiseStatistics () virtual
Initializes statistics, i.e. setting w2, setting the grid and writing the header lines in the .stat file.
Reimplemented from DPMBase.
Referenced by statistics_while_running< T >::initialiseStatistics().
jump_fstat()
template<StatType T> void StatisticsVector< T >::jump_fstat ()
jump_p3c()
template<StatType T> void StatisticsVector< T >::jump_p3c ()
loadPositions()
template<StatType T> bool StatisticsVector< T >::loadPositions (const char * filename) protected
loadVelocityProfile()
template<StatType T> bool StatisticsVector< T >::loadVelocityProfile (const char * filename) protected
outputStatistics()
template<StatType T> void StatisticsVector< T >::outputStatistics () virtual
Calculates statistics for Particles (i.e. not collisions)
Reimplemented from DPMBase.
print_CG()
template<StatType T> std::string StatisticsVector< T >::print_CG ()
Output coarse graining variables.
print_help()
template<StatType T> void StatisticsVector< T >::print_help ()
printStat()
template<StatType T> std::string StatisticsVector< T >::printStat ()
Outputs member variable values to a std::string.
Referenced by CLiveStatistics< T >::setupInitialConditions(), and statistics_while_running< T >::setupInitialConditions().
processStatistics()
template<StatType T> void StatisticsVector< T >::processStatistics (bool usethese) virtual
Processes all gathered statistics and resets them afterwards. (Processing means either calculating time averages or writing out statistics)
Reimplemented from DPMBase.
Referenced by statistics_while_running< T >::processStatistics().
read_next_from_p3p_file()
template<StatType T> bool StatisticsVector< T >::read_next_from_p3p_file () protected
readNextDataFile()
template<StatType T> bool StatisticsVector< T >::readNextDataFile (unsigned int format)
readStatArguments()
template<StatType T> void StatisticsVector< T >::readStatArguments (int argc, char * argv[])
Referenced by main(), statistics_while_running< T >::run(), and statistics_while_running< T >::statistics_while_running().
reset_statistics()
template<StatType T> virtual void StatisticsVector< T >::reset_statistics () virtual
Set all statistical variables to zero.
satisfiesInclusionCriteria()
template<StatType T> bool StatisticsVector< T >::satisfiesInclusionCriteria (BaseParticle * P) protected
set_h()
template<StatType T> void StatisticsVector< T >::set_h (Mdouble h) inline
     {
         set_hx(h);
         set_hy(h);
         set_hz(h);
     }
References StatisticsVector< T >::set_hx(), StatisticsVector< T >::set_hy(), and StatisticsVector< T >::set_hz().
Referenced by main().
set_hmax()
template<StatType T> void StatisticsVector< T >::set_hmax (Mdouble new_) inline
     {
         hmax = new_;
     }
References StatisticsVector< T >::hmax.
set_hx()
template<StatType T> void StatisticsVector< T >::set_hx (Mdouble hx) inline
     {
         setNX(static_cast<int>(std::ceil((getXMaxStat() - getXMinStat()) / hx)));
     }
References Eigen::bfloat16_impl::ceil(), StatisticsVector< T >::getXMaxStat(), StatisticsVector< T >::getXMinStat(), and StatisticsVector< T >::setNX().
Referenced by StatisticsVector< T >::set_h().
set_hy()
template<StatType T> void StatisticsVector< T >::set_hy (Mdouble hy) inline
     {
         setNY(static_cast<int>(std::ceil((getYMaxStat() - getYMinStat()) / hy)));
     }
References Eigen::bfloat16_impl::ceil(), StatisticsVector< T >::getYMaxStat(), StatisticsVector< T >::getYMinStat(), and StatisticsVector< T >::setNY().
Referenced by StatisticsVector< T >::set_h().
set_hz()
template<StatType T> void StatisticsVector< T >::set_hz (Mdouble hz) inline
     {
         setNZ(static_cast<int>(std::ceil((getZMaxStat() - getZMinStat()) / hz)));
     }
References Eigen::bfloat16_impl::ceil(), StatisticsVector< T >::getZMaxStat(), StatisticsVector< T >::getZMinStat(), and StatisticsVector< T >::setNZ().
Referenced by StatisticsVector< T >::set_h().
set_infiniteStressForFixedParticles()
template<StatType T> void StatisticsVector< T >::set_infiniteStressForFixedParticles (bool new_) inline
     {
         StressTypeForFixedParticles = 2 + new_;
     }
References StatisticsVector< T >::StressTypeForFixedParticles.
Referenced by main().
set_Polynomial() [1/2]
template<StatType T> void StatisticsVector< T >::set_Polynomial (Mdouble * new_coefficients, unsigned int num_coeff, unsigned int new_dim) inline
     {
         CGPolynomial.set_polynomial(new_coefficients, num_coeff, new_dim);
     }
References StatisticsVector< T >::CGPolynomial.
set_Polynomial() [2/2]
template<StatType T> void StatisticsVector< T >::set_Polynomial (std::vector< Mdouble > new_coefficients, unsigned int new_dim) inline
     {
         CGPolynomial.set_polynomial(new_coefficients, new_dim);
     }
References StatisticsVector< T >::CGPolynomial.
set_rmax()
template<StatType T> void StatisticsVector< T >::set_rmax (Mdouble new_) inline
     {
         rmax = new_;
     }
References StatisticsVector< T >::rmax.
set_rmin()
template<StatType T> void StatisticsVector< T >::set_rmin (Mdouble new_) inline
     {
         rmin = new_;
     }
References StatisticsVector< T >::rmin.
set_statType()
template<StatType T> void StatisticsVector< T >::set_statType ()
setCGShape() [1/2]
template<StatType T> void StatisticsVector< T >::setCGShape (CG_TYPE new_)
setCGShape() [2/2]
template<StatType T> void StatisticsVector< T >::setCGShape (const char * new_)
Referenced by main().
setCGTimeAveragingInterval()
template<StatType T> void StatisticsVector< T >::setCGTimeAveragingInterval (Mdouble t) inline
     {
         tIntStat = t;
     }
References plotPSD::t, and StatisticsVector< T >::tIntStat.
setCGTimeMin()
template<StatType T> void StatisticsVector< T >::setCGTimeMin (Mdouble t) inline
     {
         tMinStat = t;
     }
References plotPSD::t, and StatisticsVector< T >::tMinStat.
Referenced by main(), statistics_while_running< T >::run(), and statistics_while_running< T >::statistics_while_running().
setCGWidth()
template<StatType T> void StatisticsVector< T >::setCGWidth (Mdouble w) inline
Set CG variables w2 and CG_invvolume.
     {
         setCGWidth2(mathsFunc::square(w));
     }
References StatisticsVector< T >::setCGWidth2(), mathsFunc::square(), and w.
Referenced by main(), statistics_while_running< T >::run(), and statistics_while_running< T >::statistics_while_running().
setCGWidth2()
template<StatType T> void StatisticsVector< T >::setCGWidth2 (Mdouble new_)
Set CG variables w2 and CG_invvolume.
Referenced by StatisticsVector< T >::setCGWidth().
setCGWidth_over_rmax()
template<StatType T> void StatisticsVector< T >::setCGWidth_over_rmax (Mdouble new_) inline
     {
         w_over_rmax = new_;
     }
References StatisticsVector< T >::w_over_rmax.
setCGWidthalls()
template<StatType T> void StatisticsVector< T >::setCGWidthalls (bool new_) inline
     {
         walls = new_;
     }
References StatisticsVector< T >::walls.
setDoDoublePoints()
template<StatType T> void StatisticsVector< T >::setDoDoublePoints (bool new_) inline
     {
         doDoublePoints = new_;
     }
References StatisticsVector< T >::doDoublePoints.
setDoGradient()
template<StatType T> void StatisticsVector< T >::setDoGradient (bool new_) inline
     {
         doGradient = new_;
     }
References StatisticsVector< T >::doGradient.
setDoIgnoreFixedParticles()
template<StatType T> void StatisticsVector< T >::setDoIgnoreFixedParticles (bool new_) inline
     {
         ignoreFixedParticles = new_;
     }
References StatisticsVector< T >::ignoreFixedParticles.
setDoPeriodicWalls()
template<StatType T> void StatisticsVector< T >::setDoPeriodicWalls (bool new_) inline
     {
         periodicWalls = new_;
     }
References StatisticsVector< T >::periodicWalls.
Referenced by CLiveStatistics< T >::CLiveStatistics(), main(), statistics_while_running< T >::run(), Statistics(), and statistics_while_running< T >::statistics_while_running().
setDoTimeAverage()
template<StatType T> void StatisticsVector< T >::setDoTimeAverage (bool new_) inline
     {
         doTimeAverage = new_;
     }
References StatisticsVector< T >::doTimeAverage.
setDoVariance()
template<StatType T> void StatisticsVector< T >::setDoVariance (bool new_) inline
     {
         doVariance = new_;
     }
References StatisticsVector< T >::doVariance.
setIndSpecies()
template<StatType T> void StatisticsVector< T >::setIndSpecies (unsigned int indSpecies) inline
     {
         this->indSpecies = indSpecies;
     }
References StatisticsVector< T >::indSpecies.
setInfinitelyLongDistance()
template<StatType T> Mdouble StatisticsVector< T >::setInfinitelyLongDistance ()
setMirrorAtDomainBoundary()
template<StatType T> void StatisticsVector< T >::setMirrorAtDomainBoundary (Mdouble new_) inline
     {
         mirrorAtDomainBoundary = new_;
     }
References StatisticsVector< T >::mirrorAtDomainBoundary.
setN() [1/2]
template<StatType T> void StatisticsVector< T >::setN (int n) inline
     {
         setNX(n);
         setNY(n);
         setNZ(n);
     }
References n, StatisticsVector< T >::setNX(), StatisticsVector< T >::setNY(), and StatisticsVector< T >::setNZ().
Referenced by main(), statistics_while_running< T >::run(), and statistics_while_running< T >::statistics_while_running().
setN() [2/2]
template<StatType T> void StatisticsVector< T >::setN (int nx_, int ny_, int nz_) inline
     {
         nx = nx_;
         ny = ny_;
         nz = nz_;
     }
References StatisticsVector< T >::nx, StatisticsVector< T >::ny, and StatisticsVector< T >::nz.
setNTimeAverageReset()
template<StatType T> void StatisticsVector< T >::setNTimeAverageReset (int new_) inline
     {
         nTimeAverageReset = new_;
     }
References StatisticsVector< T >::nTimeAverageReset.
setNX()
template<StatType T> void StatisticsVector< T >::setNX (int new_) inline
     {
         nx = new_;
     }
References StatisticsVector< T >::nx.
Referenced by main(), StatisticsVector< T >::set_hx(), and StatisticsVector< T >::setN().
setNY()
template<StatType T> void StatisticsVector< T >::setNY (int new_) inline
     {
         ny = new_;
     }
References StatisticsVector< T >::ny.
Referenced by main(), StatisticsVector< T >::set_hy(), and StatisticsVector< T >::setN().
setNZ()
template<StatType T> void StatisticsVector< T >::setNZ (int new_) inline
     {
         nz = new_;
         if (getSystemDimensions() < 3)
         {
             logger(WARN, "Warning in set_nz: dimension less than 3");
         }
     }
References DPMBase::getSystemDimensions(), logger, StatisticsVector< T >::nz, and WARN.
Referenced by main(), StatisticsVector< T >::set_hz(), and StatisticsVector< T >::setN().
setPolynomialName()
template<StatType T> void StatisticsVector< T >::setPolynomialName (const char * new_name) inline
     {
         CGPolynomial.setName(new_name);
     }
References StatisticsVector< T >::CGPolynomial.
setPositions()
template<StatType T> void StatisticsVector< T >::setPositions ()
Set position of StatisticsPoint points and set variables to 0.
setStepSize()
template<StatType T> void StatisticsVector< T >::setStepSize (unsigned int stepSize) inline
     {
         stepSize_ = stepSize;
     }
References StatisticsVector< T >::stepSize_.
setStressTypeForFixedParticles()
template<StatType T> void StatisticsVector< T >::setStressTypeForFixedParticles (int new_) inline
     {
         StressTypeForFixedParticles = new_;
     }
References StatisticsVector< T >::StressTypeForFixedParticles.
Referenced by statistics_while_running< T >::statistics_while_running().
setSuperExact()
template<StatType T> void StatisticsVector< T >::setSuperExact (bool new_) inline
     {
         superexact = new_;
     }
References StatisticsVector< T >::superexact.
Referenced by main().
setTimeMaxStat()
template<StatType T> void StatisticsVector< T >::setTimeMaxStat (Mdouble t) inline
     {
         tMaxStat = t;
     }
References plotPSD::t, and StatisticsVector< T >::tMaxStat.
Referenced by main().
setVerbosityLevel()
template<StatType T> void StatisticsVector< T >::setVerbosityLevel (int new_) inline
     {
         verbosity = new_;
     }
References StatisticsVector< T >::verbosity.
Referenced by main().
setXMaxStat()
template<StatType T> void StatisticsVector< T >::setXMaxStat (Mdouble xMaxStat_) inline
     {
         xMaxStat = xMaxStat_;
     }
References StatisticsVector< T >::xMaxStat.
setXMinStat()
template<StatType T> void StatisticsVector< T >::setXMinStat (Mdouble xMinStat_) inline
     {
         xMinStat = xMinStat_;
     }
References StatisticsVector< T >::xMinStat.
setYMaxStat()
template<StatType T> void StatisticsVector< T >::setYMaxStat (Mdouble yMaxStat_) inline
     {
         yMaxStat = yMaxStat_;
     }
References StatisticsVector< T >::yMaxStat.
setYMinStat()
template<StatType T> void StatisticsVector< T >::setYMinStat (Mdouble yMinStat_) inline
     {
         yMinStat = yMinStat_;
     }
References StatisticsVector< T >::yMinStat.
setZMaxStat()
template<StatType T> void StatisticsVector< T >::setZMaxStat (Mdouble zMaxStat_) inline
     {
         zMaxStat = zMaxStat_;
     }
References StatisticsVector< T >::zMaxStat.
Referenced by main().
setZMinStat()
template<StatType T> void StatisticsVector< T >::setZMinStat (Mdouble zMinStat_) inline
     {
         zMinStat = zMinStat_;
     }
References StatisticsVector< T >::zMinStat.
Referenced by main().
statistics_from_fstat_and_data()
template<StatType T> void StatisticsVector< T >::statistics_from_fstat_and_data ()
get StatisticsPoint
Referenced by main(), and Statistics().
statistics_from_p3()
template<StatType T> void StatisticsVector< T >::statistics_from_p3 ()
Referenced by main().
verbose()
template<StatType T> void StatisticsVector< T >::verbose () inline
     {
         verbosity = 2;
     }
References StatisticsVector< T >::verbosity.
Referenced by smc.smc::getDPMData(), smc.smc::getInitParams(), smc.smc::getObsDataFromFile(), smc.smc::getParamsFromTable(), smc.smc::initialize(), main(), smc.smc::resampleParams(), smc.smc::run(), and statistics_while_running< T >::setupInitialConditions().
write_statistics()
template<StatType T> void StatisticsVector< T >::write_statistics ()
Writes regular statistics.
write_time_average_statistics()
template<StatType T> void StatisticsVector< T >::write_time_average_statistics ()
Writes out time averaged statistics.
writeOutputFiles()
template<StatType T> void StatisticsVector< T >::writeOutputFiles () virtual
Writes simulation data to all the main Mercury files: .data, .ene, .fstat, .xballs and .restart (see the Mercury website for more details regarding these files).
Writes headers and all relevant information to the relevant output files. Note that the writeFstatHeader() actually contains within it the functionality to write the full fstat data, whereas for .ene files the functions to write the headers and main data are separate. Note that the interaction file is not written here: it is written with the start and end of each interaction.
The function [X].saveCurrentTimeStep(numberOfTimeSteps_) returns true if:
a) The current time step is greater than or equal to the time step at which the next write or read operation is supposed to happen.
b) The FileType is not "NO_FILE".
c) The file is open.
Reimplemented from DPMBase.
Member Data Documentation
centerPointInFStat_
template<StatType T> bool StatisticsVector< T >::centerPointInFStat_ = true protected
CG_type
template<StatType T> CG_TYPE StatisticsVector< T >::CG_type protected
coarse graining type (Gaussian, Heaviside, Polynomial)
Referenced by StatisticsVector< T >::getCGShape().
CGPolynomial
template<StatType T> NORMALIZED_POLYNOMIAL<T> StatisticsVector< T >::CGPolynomial protected
Stores the Polynomial, if the cg function is an axisymmetric function Polynomial in r.
Referenced by StatisticsVector< T >::evaluateIntegral(), StatisticsVector< T >::evaluatePolynomial(), StatisticsVector< T >::evaluatePolynomialGradient(), StatisticsVector< T >::getPolynomialName(), StatisticsVector< T >::set_Polynomial(), and StatisticsVector< T >::setPolynomialName().
cutoff
template<StatType T> Mdouble StatisticsVector< T >::cutoff protected
The distance from the origin at which the cg function vanishes; cutoff=w for HeavisideSphere or Polynomial, 3*w for Gaussian.
Referenced by StatisticsVector< T >::getCutoff(), and StatisticsVector< T >::getCutoff2().
cutoff2
template<StatType T> Mdouble StatisticsVector< T >::cutoff2 protected
doDoublePoints
template<StatType T> bool StatisticsVector< T >::doDoublePoints protected
Referenced by StatisticsVector< T >::getDoDoublePoints(), and StatisticsVector< T >::setDoDoublePoints().
doGradient
template<StatType T> bool StatisticsVector< T >::doGradient protected
Determines if gradient is outputted.
Referenced by StatisticsVector< T >::getDoGradient(), and StatisticsVector< T >::setDoGradient().
doTimeAverage
template<StatType T> bool StatisticsVector< T >::doTimeAverage protected
Determines if output is averaged over time.
Referenced by StatisticsVector< T >::getDoTimeAverage(), main(), and StatisticsVector< T >::setDoTimeAverage().
doVariance
template<StatType T> bool StatisticsVector< T >::doVariance protected
Determines if variance is outputted.
Referenced by StatisticsVector< T >::getDoVariance(), and StatisticsVector< T >::setDoVariance().
dx
template<StatType T> std::vector<StatisticsPoint<T> > StatisticsVector< T >::dx protected
A vector that stores the gradient in x of all statistical variables at a given position.
dxTimeAverage
template<StatType T> std::vector<StatisticsPoint<T> > StatisticsVector< T >::dxTimeAverage protected
a vector used to sum up all statistical gradients in dx for time-averaging
dy
template<StatType T> std::vector<StatisticsPoint<T> > StatisticsVector< T >::dy protected
A vector that stores the gradient in y of all statistical variables at a given position.
dyTimeAverage
template<StatType T> std::vector<StatisticsPoint<T> > StatisticsVector< T >::dyTimeAverage protected
a vector used to sum up all statistical gradients in dy for time-averaging
dz
template<StatType T> std::vector<StatisticsPoint<T> > StatisticsVector< T >::dz protected
A vector that stores the gradient in z of all statistical variables at a given position.
dzTimeAverage
template<StatType T> std::vector<StatisticsPoint<T> > StatisticsVector< T >::dzTimeAverage protected
a vector used to sum up all statistical gradients in dz for time-averaging
format
template<StatType T> int StatisticsVector< T >::format protected
format of the data input file
hmax
template<StatType T> Mdouble StatisticsVector< T >::hmax protected
defines the maximum height of the particles for which statistics are extracted
Referenced by StatisticsVector< T >::set_hmax().
ignoreFixedParticles
template<StatType T> bool StatisticsVector< T >::ignoreFixedParticles protected
Determines if fixed particles contribute to particle statistics (density, ...)
Referenced by StatisticsVector< T >::getDoIgnoreFixedParticles(), and StatisticsVector< T >::setDoIgnoreFixedParticles().
indSpecies
template<StatType T> Mdouble StatisticsVector< T >::indSpecies protected
defines the species for which statistics are extracted (-1 for all species)
Referenced by StatisticsVector< T >::setIndSpecies().
isMDCLR
template<StatType T> bool StatisticsVector< T >::isMDCLR protected
mirrorAtDomainBoundary
template<StatType T> Mdouble StatisticsVector< T >::mirrorAtDomainBoundary protected
0: Statistics near the wall are equal to statistics away from the wall; 1: Statistics are mirrored at the domain boundaries; up to a maximum depth specified by this number
Referenced by StatisticsVector< T >::getMirrorAtDomainBoundary(), and StatisticsVector< T >::setMirrorAtDomainBoundary().
nTimeAverage
template<StatType T> int StatisticsVector< T >::nTimeAverage protected
A counter needed to average over time.
Referenced by StatisticsVector< T >::getNTimeAverage().
nTimeAverageReset
template<StatType T> int StatisticsVector< T >::nTimeAverageReset protected
Determines after how many time steps the time average is reset.
Referenced by StatisticsVector< T >::getNTimeAverageReset(), and StatisticsVector< T >::setNTimeAverageReset().
nx
template<StatType T> int StatisticsVector< T >::nx protected
Grid size nx,ny,nz (by default the points of evaluation are placed in an grid on the domain [xMinStat,xMaxStat]x[yMinStat,yMaxStat]x[zMinStat,zMaxStat].
Referenced by StatisticsVector< T >::getN(), StatisticsVector< T >::getNX(), StatisticsVector< T >::setN(), and StatisticsVector< T >::setNX().
nxMirrored
template<StatType T> int StatisticsVector< T >::nxMirrored protected
extension of grid size from mirrored points
ny
template<StatType T> int StatisticsVector< T >::ny protected
see nx
Referenced by StatisticsVector< T >::getN(), StatisticsVector< T >::getNY(), StatisticsVector< T >::setN(), and StatisticsVector< T >::setNY().
nyMirrored
template<StatType T> int StatisticsVector< T >::nyMirrored protected
nz
template<StatType T> int StatisticsVector< T >::nz protected
see nx
Referenced by StatisticsVector< T >::getN(), StatisticsVector< T >::getNZ(), StatisticsVector< T >::setN(), and StatisticsVector< T >::setNZ().
nzMirrored
template<StatType T> int StatisticsVector< T >::nzMirrored protected
P1
template<StatType T> Vec3D StatisticsVector< T >::P1 protected
Position of first contact point.
P1_P2_CollisionalHeatFlux
template<StatType T> Vec3D StatisticsVector< T >::P1_P2_CollisionalHeatFlux protected
not yet working
P1_P2_Contact
template<StatType T> Vec3D StatisticsVector< T >::P1_P2_Contact protected
P1_P2_ContactCoupleStress
template<StatType T> Matrix3D StatisticsVector< T >::P1_P2_ContactCoupleStress protected
P1_P2_Dissipation
template<StatType T> Mdouble StatisticsVector< T >::P1_P2_Dissipation protected
not yet working
P1_P2_distance
template<StatType T> Mdouble StatisticsVector< T >::P1_P2_distance protected
Length of contact line.
P1_P2_Fabric
template<StatType T> MatrixSymmetric3D StatisticsVector< T >::P1_P2_Fabric protected
Fabric.
P1_P2_normal
template<StatType T> Vec3D StatisticsVector< T >::P1_P2_normal protected
Direction of contact.
P1_P2_NormalStress
template<StatType T> Matrix3D StatisticsVector< T >::P1_P2_NormalStress protected
Contact stress from normal forces along the line of contact.
P1_P2_NormalTraction
template<StatType T> Vec3D StatisticsVector< T >::P1_P2_NormalTraction protected
Traction from normal forces at contact of flow with fixed particles or walls.
P1_P2_Potential
template<StatType T> Mdouble StatisticsVector< T >::P1_P2_Potential protected
not yet working
P1_P2_TangentialStress
template<StatType T> Matrix3D StatisticsVector< T >::P1_P2_TangentialStress protected
Contact stress from tangential forces along the line of contact.
P1_P2_TangentialTraction
template<StatType T> Vec3D StatisticsVector< T >::P1_P2_TangentialTraction protected
Traction from tangential forces at contact of flow with fixed particles or walls.
P2
template<StatType T> Vec3D StatisticsVector< T >::P2 protected
Position of second contact point.
p3c_file
template<StatType T> std::fstream StatisticsVector< T >::p3c_file protected
p3Format
template<StatType T> bool StatisticsVector< T >::p3Format = true protected
p3p_file
template<StatType T> std::fstream StatisticsVector< T >::p3p_file protected
p3w_file
template<StatType T> std::fstream StatisticsVector< T >::p3w_file protected
periodicWalls
template<StatType T> bool StatisticsVector< T >::periodicWalls protected
Turns off periodic walls before evaluation (needed for averaging, because we do not yet check if particle is in domain)
Todo:
{Thomas: the case periodicWalls=true seems to mess up some statistics. Needs to be checked or removed}
Referenced by StatisticsVector< T >::getDoPeriodicWalls(), and StatisticsVector< T >::setDoPeriodicWalls().
Points
template<StatType T> std::vector<StatisticsPoint<T> > StatisticsVector< T >::Points protected
A vector that stores the values of the statistical variables at a given position.
Referenced by StatisticsVector< T >::getCGPoints().
positions_
template<StatType T> std::vector<Vec3D> StatisticsVector< T >::positions_ protected
rmax
template<StatType T> Mdouble StatisticsVector< T >::rmax protected
defines the maximum radius of the particles for which statistics are extracted
Referenced by StatisticsVector< T >::set_rmax().
rmin
template<StatType T> Mdouble StatisticsVector< T >::rmin protected
defines the minimum radius of the particles for which statistics are extracted
Todo:
Thomas: maybe this fixed condition should be replaced by a condition function, bool include_statistics_if()
Referenced by StatisticsVector< T >::set_rmin().
statType
template<StatType T> StatType StatisticsVector< T >::statType protected
Possible values X,Y,Z,XY,XZ,YZ,XYZ,RAZ,RA,RZ,AZ,R,A are used to determine if the statistics are averaged; f.e. StatType X is averaged over y and z.
stepSize_
template<StatType T> unsigned int StatisticsVector< T >::stepSize_ protected
Referenced by StatisticsVector< T >::getStepSize(), and StatisticsVector< T >::setStepSize().
StressTypeForFixedParticles
template<StatType T> int StatisticsVector< T >::StressTypeForFixedParticles protected
Stress type for fixed particles.
0 no Stress from fixed particles
1 Stress from fixed particles distributed between Contact and flowing Particle COM (default)
2 Stress from fixed particles distributed between fixed and flowing Particle COM
3 Stress from fixed particles extends from flowing particle to infinity
Referenced by StatisticsVector< T >::getStressTypeForFixedParticles(), StatisticsVector< T >::set_infiniteStressForFixedParticles(), and StatisticsVector< T >::setStressTypeForFixedParticles().
superexact
template<StatType T> bool StatisticsVector< T >::superexact protected
If true, cutoff radius for Gaussian is set to 5*w (from 3*w)
Referenced by StatisticsVector< T >::getSuperExact(), and StatisticsVector< T >::setSuperExact().
timeAverage
template<StatType T> std::vector<StatisticsPoint<T> > StatisticsVector< T >::timeAverage protected
A vector used to sum up all statistical values in Points for time-averaging.
timeVariance
template<StatType T> std::vector<StatisticsPoint<T> > StatisticsVector< T >::timeVariance protected
a vector used to sum up the variance in time of all statistical values
tIntStat
template<StatType T> Mdouble StatisticsVector< T >::tIntStat protected
Statistical output will only be created if tMaxStat-tIntStat< t< tMaxStat.
Referenced by StatisticsVector< T >::getCGTimeAveragingInterval(), and StatisticsVector< T >::setCGTimeAveragingInterval().
tMaxStat
template<StatType T> Mdouble StatisticsVector< T >::tMaxStat protected
Statistical output will only be created if t<tMaxStat.
Referenced by StatisticsVector< T >::getTimeMaxStat(), and StatisticsVector< T >::setTimeMaxStat().
tMinStat
template<StatType T> Mdouble StatisticsVector< T >::tMinStat protected
Statistical output will only be created if t>tMinStat.
Referenced by StatisticsVector< T >::getCGTimeMin(), and StatisticsVector< T >::setCGTimeMin().
VelocityProfile
template<StatType T> std::vector<Vec3D> StatisticsVector< T >::VelocityProfile protected
VelocityProfile_D
template<StatType T> Vec3D StatisticsVector< T >::VelocityProfile_D protected
VelocityProfile_Min
template<StatType T> Vec3D StatisticsVector< T >::VelocityProfile_Min protected
verbosity
template<StatType T> int StatisticsVector< T >::verbosity protected
Determines how much is outputted to the terminal.
0 no output
1 basic output (time steps)
2 full output (number of forces and particles, md and stat parameters)
Referenced by StatisticsVector< T >::getVerbosityLevel(), StatisticsVector< T >::setVerbosityLevel(), and StatisticsVector< T >::verbose().
w2
template<StatType T> Mdouble StatisticsVector< T >::w2 protected
coarse graining width squared; for HeavisideSphere and Gaussian
Referenced by StatisticsVector< T >::getCGWidth(), and StatisticsVector< T >::getCGWidthSquared().
w_over_rmax
template<StatType T> Mdouble StatisticsVector< T >::w_over_rmax protected
if w is not set manually then w will be set by multiplying this value by the largest particle radius at t=0
Referenced by StatisticsVector< T >::getCGWidth_over_rmax(), and StatisticsVector< T >::setCGWidth_over_rmax().
walls
template<StatType T> bool StatisticsVector< T >::walls protected
Turns off walls before evaluation.
Referenced by StatisticsVector< T >::getCGWidthalls(), and StatisticsVector< T >::setCGWidthalls().
xMaxStat
template<StatType T> Mdouble StatisticsVector< T >::xMaxStat protected
Referenced by StatisticsVector< T >::getXMaxStat(), and StatisticsVector< T >::setXMaxStat().
xMinStat
template<StatType T> Mdouble StatisticsVector< T >::xMinStat protected
By default the domain is set to the domain of the MD problem (indicated by setting the stat-domain values to nan), but can be resized.
Referenced by StatisticsVector< T >::getXMinStat(), and StatisticsVector< T >::setXMinStat().
yMaxStat
template<StatType T> Mdouble StatisticsVector< T >::yMaxStat protected
Referenced by StatisticsVector< T >::getYMaxStat(), and StatisticsVector< T >::setYMaxStat().
yMinStat
template<StatType T> Mdouble StatisticsVector< T >::yMinStat protected
Referenced by StatisticsVector< T >::getYMinStat(), and StatisticsVector< T >::setYMinStat().
zMaxStat
template<StatType T> Mdouble StatisticsVector< T >::zMaxStat protected
Referenced by StatisticsVector< T >::getZMaxStat(), and StatisticsVector< T >::setZMaxStat().
zMinStat
template<StatType T> Mdouble StatisticsVector< T >::zMinStat protected
Referenced by StatisticsVector< T >::getZMinStat(), and StatisticsVector< T >::setZMinStat().
The documentation for this class was generated from the following files:
StatisticsPoint.h
StatisticsVector.h