MercuryDPM: MercuryLogo.cpp File Reference
MercuryLogo.cpp File Reference
#include <iostream>
#include "Mercury3D.h"
#include <Species/LinearViscoelasticFrictionSpecies.h>
#include <Walls/InfiniteWall.h>
#include <Boundaries/PeriodicBoundary.h>
Classes
class MercuryLogo
Functions
int main ()
Function Documentation
main()
int main ()
 {
     MercuryLogo logo;
     logo.numberOfParticlesToBeInserted = 600;
     logo.setName("MercuryLogo");
     logo.setZMax(45.0);
     logo.setYMax(5.0);
     logo.setXMax(20.0);
     logo.setSystemDimensions(3);
     logo.setTimeStep(logo.tc * 0.02);
     logo.setTimeMax(1.0);
     logo.setGravity(Vec3D(0.0, 0.0, 0.0));
     logo.setSaveCount(100);
     logo.setFileType(FileType::ONE_FILE);
     logo.setXBallsAdditionalArguments("-solidf -v0");
     logo.solve();
     return 0;
 }
References MercuryLogo::numberOfParticlesToBeInserted, ONE_FILE, DPMBase::setFileType(), DPMBase::setGravity(), DPMBase::setName(), DPMBase::setSaveCount(), DPMBase::setSystemDimensions(), DPMBase::setTimeMax(), DPMBase::setTimeStep(), DPMBase::setXBallsAdditionalArguments(), DPMBase::setXMax(), DPMBase::setYMax(), DPMBase::setZMax(), DPMBase::solve(), and MercuryLogo::tc.