MercuryDPM: TwoBondedParticleElasticCollisionSelfTest.cpp File Reference
TwoBondedParticleElasticCollisionSelfTest.cpp File Reference
#include "Mercury3D.h"
#include "Walls/InfiniteWall.h"
#include <iostream>
#include "Species/Species.h"
#include "Species/LinearViscoelasticSlidingFrictionBondedSpecies.h"
Classes
class TwoBondedParticleElasticCollision
Functions
int main (int argc UNUSED, char *argv[] UNUSED)
Function Documentation
main()
int main (int argc UNUSED, char *argv[] UNUSED)
 {
     //create an instance of the DPM class
     TwoBondedParticleElasticCollision twoParticleElasticCollisionProblem;
     twoParticleElasticCollisionProblem.setName("TwoBondedParticleElasticCollisionSelfTest");
     //set species properties
     auto species = new LinearViscoelasticSlidingFrictionBondedSpecies;
     twoParticleElasticCollisionProblem.speciesHandler.addObject(species);
     species->setDensity(2000);
     Mdouble radius = 0.0005;
     Mdouble mass = species->getMassFromRadius(radius);
     Mdouble tc = 1e-3;
     Mdouble restitution = 0.8;
     species->setCollisionTimeAndNormalAndTangentialRestitutionCoefficient(tc,restitution,restitution,mass);
     species->setSlidingFrictionCoefficient(0.05);
     //set bond strength such that particles have 0.5r overlap under equilibrium conditions (no external forces)
     species->setBondForceMax(species->getStiffness()*radius*0.5);
     //set global DPM properties
     twoParticleElasticCollisionProblem.setTimeMax(0.3);
     twoParticleElasticCollisionProblem.setSaveCount(20);
     twoParticleElasticCollisionProblem.setTimeStep(0.02*tc);
     twoParticleElasticCollisionProblem.fStatFile.setFileType(FileType::NO_FILE);
     twoParticleElasticCollisionProblem.setXBallsAdditionalArguments("-cmode 7 -v0 -solid -3dturn 1");
     twoParticleElasticCollisionProblem.solve();
 }
References SpeciesHandler::addObject(), e(), DPMBase::fStatFile, NO_FILE, UniformPSDSelfTest::radius, File::setFileType(), DPMBase::setName(), DPMBase::setSaveCount(), DPMBase::setTimeMax(), DPMBase::setTimeStep(), DPMBase::setXBallsAdditionalArguments(), DPMBase::solve(), and DPMBase::speciesHandler.