MercuryDPM: CMakeDefinitions.h File Reference
Configuration/CMakeDefinitions.h File Reference
#include <string>
Functions
const std::string getMercuryDPMSourceDir ()
This file is used for generating definitions that give access to CMakeVariables from within a cpp file (definitions.
const std::string getMercuryDPMBuildDir ()
const std::string getRevision ()
const std::string getRepositoryURL ()
const std::string getVersion ()
Function Documentation
getMercuryDPMBuildDir()
const std::string getMercuryDPMBuildDir ()
 {
     return "@MercuryDPM_BINARY_DIR@";
 }
Referenced by LoadFinalOrient(), LoadInitOrient(), LoadIProfiles(), and main().
getMercuryDPMSourceDir()
const std::string getMercuryDPMSourceDir ()
This file is used for generating definitions that give access to CMakeVariables from within a cpp file (definitions.
PLEASE DO NOT EDIT THE FILE IN THE KERNEL - only in Configuration
This file is used for generating defitions that give access to CMakeVaribles from within a cpp file (defintions have only been added as required PLEASE DO NOT EDIT THE FILE IN THE KERNEL - only in Configuration
 {
     return "@MercuryDPM_SOURCE_DIR@";
 }
Referenced by LoadConf(), main(), ChangingTOIParticle::setupInitialConditions(), MultiplePSDSelfTest::setupInitialConditions(), PSDManualInsertionSelfTest::setupInitialConditions(), PSDSelfTest::setupInitialConditions(), MembraneSelfTest::setUpMembrane(), and StressStrainControl::StressStrainControl().
getRepositoryURL()
const std::string getRepositoryURL ()
 {
     return "@REPOSITORY_URL@";
 }
Referenced by DPMBase::write().
getRevision()
const std::string getRevision ()
 {
     return "@REVISION@";
 }
Referenced by DPMBase::write().
getVersion()
const std::string getVersion ()
 {
     return "@MercuryDPM_VERSION_MAJOR@.@MercuryDPM_VERSION_MINOR@";
 }
Referenced by DPMBase::write().