MercuryDPM: prescribed_displ_lagr_mult_precond.cc File Reference
prescribed_displ_lagr_mult_precond.cc File Reference
#include "generic.h"
#include "solid.h"
#include "constitutive.h"
#include "meshes/rectangular_quadmesh.h"
#include "multi_physics/pseudo_elastic_preconditioner.h"
Classes
class oomph::PseudoElasticBulkElement< ELEMENT >
class oomph::FaceGeometry< PseudoElasticBulkElement< ELEMENT > >
FaceGeometry of wrapped element is the same as the underlying element.
class FiniteElementComp
class WarpedLine
Warped line in 2D space.
class PrescribedBoundaryDisplacementProblem< ELEMENT >
Namespaces
oomph
DRAIG: Change all instances of (SPATIAL_DIM) to (DIM-1).
DiagonalPreconditionerHelper
Global_Physical_Variables
Global variables.
Functions
Preconditioner * DiagonalPreconditionerHelper::get_diagonal_preconditioner ()
int main (int argc, char *argv[])
Driver code.
Variables
WarpedLine Global_Physical_Variables::Boundary_geom_object (0.0)
GeomObject specifying the shape of the boundary: Initially it's flat.
Function Documentation
main()
int main (int argc , char * argv[])
Driver code.
 {
 #ifdef OOMPH_HAS_MPI
  // Start up mpi if oomph-lib has been compiled with parallel support
  // because parallel versions of trilinos and hypre which are then called
  // by default) need it.
  MPI_Helpers::init(argc,argv,false);
 #endif
  // Store command line arguments
  CommandLineArgs::setup(argc,argv);
  // Define possible command line arguments and parse the ones that
  // were actually specified
  // Number of elements along axes
  unsigned nel_1d=5;
  CommandLineArgs::specify_command_line_flag("--nel_1d",&nel_1d);
  // Suppress adaptation (for study of iteration count vs uniform mesh
  // refinement, say)
  CommandLineArgs::specify_command_line_flag("--no_adapt");
  // Use block upper triangular preconditioner for elasticity block
  CommandLineArgs::specify_command_line_flag("--block_upper_for_elastic_block");
  // Use Hypre as subsidiary preconditioner (inexact solver) for
  // linear (sub-)systems to be solved in the elastic block?
  CommandLineArgs::specify_command_line_flag("--hypre_for_elastic_blocks");
  // Use Trilinos CG as subsidiary preconditioner (inexact solver) for
  // linear (sub-)systems to be solved in the Lagrange multiplier block?
  CommandLineArgs::specify_command_line_flag
   ("--trilinos_cg_for_lagrange_multiplier_blocks");
  // Use diagonal scaling as subsidiary preconditioner (inexact solver) for
  // linear (sub-)systems to be solved in the elastic block?
  // [only used for exercise]
  CommandLineArgs::specify_command_line_flag
   ("--diagonal_scaling_for_elastic_blocks");
  // Parse command line
  CommandLineArgs::parse_and_assign();
  // Doc what has actually been specified on the command line
  CommandLineArgs::doc_specified_flags();
  //Set up the problem with specified number of elements along axes.
  PrescribedBoundaryDisplacementProblem<
   PseudoElasticBulkElement<RefineableQPVDElement<2,3> > > problem(nel_1d);
  // Doc initial domain shape
  problem.doc_solution();
  // Max. number of adaptations per solve
  unsigned max_adapt=1;
  if (CommandLineArgs::command_line_flag_has_been_set("--no_adapt"))
   {
    max_adapt=0;
   }
  //Parameter incrementation
  unsigned nstep=2;
  for(unsigned i=0;i<nstep;i++)
   {
    // Increment imposed boundary displacement
    Global_Physical_Variables::Boundary_geom_object.ampl()+=0.1;
    // Solve the problem with Newton's method, allowing
    // up to max_adapt mesh adaptations after every solve.
    problem.newton_solve(max_adapt);
    // Doc solution
    problem.doc_solution();
    // For maximum stability: Reset the current nodal positions to be
    // the "stress-free" ones -- this assignment means that the
    // parameter study no longer corresponds to a physical experiment
    // but is what we'd do if we wanted to use the solid solve
    // to update a fluid mesh in an FSI problem, say.
    problem.solid_mesh_pt()->set_lagrangian_nodal_coordinates();
   }
 } //end of main
References WarpedLine::ampl(), Global_Physical_Variables::Boundary_geom_object, oomph::CommandLineArgs::command_line_flag_has_been_set(), oomph::CommandLineArgs::doc_specified_flags(), i, oomph::CommandLineArgs::parse_and_assign(), problem, Flag_definition::setup(), and oomph::CommandLineArgs::specify_command_line_flag().