MercuryDPM: oomph::SimpleCircle Class Reference
oomph::SimpleCircle Class Reference
#include <circle.h>
Public Member Functions
SimpleCircle (const double &x_c, const double &y_c, const double &r)
Constructor: Pass x and y-coords of centre and radius.
void position (const Vector< double > &zeta, Vector< double > &r) const
Position Vector at Lagrangian coordinate zeta.
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
Public Member Functions inherited from oomph::GeomObject
GeomObject ()
Default constructor.
GeomObject (const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim, TimeStepper *time_stepper_pt)
GeomObject (const GeomObject &dummy)=delete
Broken copy constructor.
void operator= (const GeomObject &)=delete
Broken assignment operator.
virtual ~GeomObject ()
(Empty) destructor
unsigned nlagrangian () const
Access function to # of Lagrangian coordinates.
unsigned ndim () const
Access function to # of Eulerian coordinates.
void set_nlagrangian_and_ndim (const unsigned &n_lagrangian, const unsigned &n_dim)
Set # of Lagrangian and Eulerian coordinates.
TimeStepper *& time_stepper_pt ()
TimeStepper * time_stepper_pt () const
virtual unsigned ngeom_data () const
virtual Data * geom_data_pt (const unsigned &j)
virtual void position (const double &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void dposition_dt (const Vector< double > &zeta, const unsigned &j, Vector< double > &drdt)
virtual void dposition (const Vector< double > &zeta, DenseMatrix< double > &drdzeta) const
virtual void d2position (const Vector< double > &zeta, RankThreeTensor< double > &ddrdzeta) const
virtual void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
virtual void locate_zeta (const Vector< double > &zeta, GeomObject *&sub_geom_object_pt, Vector< double > &s, const bool &use_coordinate_as_initial_guess=false)
virtual void interpolated_zeta (const Vector< double > &s, Vector< double > &zeta) const
Protected Attributes
double X_c
X-coordinate of centre.
double Y_c
Y-coordinate of centre.
double R
Radius.
Protected Attributes inherited from oomph::GeomObject
unsigned NLagrangian
Number of Lagrangian (intrinsic) coordinates.
unsigned Ndim
Number of Eulerian coordinates.
TimeStepper * Geom_object_time_stepper_pt
Detailed Description
Simple circle in 2D space.
\[ x = X_c + R \cos(\zeta) \]
\[ y = Y_c + R \sin(\zeta) \]
Constructor & Destructor Documentation
SimpleCircle()
oomph::SimpleCircle::SimpleCircle (const double & x_c, const double & y_c, const double & r) inline
Constructor: Pass x and y-coords of centre and radius.
                                 : GeomObject(1,2), X_c(x_c), Y_c(y_c), R(r)
   {}
Member Function Documentation
position() [1/2]
void oomph::SimpleCircle::position (const unsigned & t, const Vector< double > & zeta, Vector< double > & r) const inline virtual
Position Vector at Lagrangian coordinate zeta at time level t (t=0: present; t>0: previous level). Steady object, so we simply forward the call to the steady version.
Reimplemented from oomph::GeomObject.
   {position(zeta,r);}
References position(), UniformPSDSelfTest::r, and Eigen::zeta().
position() [2/2]
void oomph::SimpleCircle::position (const Vector< double > & zeta, Vector< double > & r) const inline virtual
Position Vector at Lagrangian coordinate zeta.
Implements oomph::GeomObject.
   {
    // Position vector
    r[0] = X_c+R*cos(zeta[0]);
    r[1] = Y_c+R*sin(zeta[0]);
   }
References cos(), UniformPSDSelfTest::r, R, sin(), X_c, Y_c, and Eigen::zeta().
Referenced by position().
Member Data Documentation
R
double oomph::SimpleCircle::R protected
Radius.
Referenced by position().
X_c
double oomph::SimpleCircle::X_c protected
X-coordinate of centre.
Referenced by position().
Y_c
double oomph::SimpleCircle::Y_c protected
Y-coordinate of centre.
Referenced by position().
The documentation for this class was generated from the following file:
circle.h