MercuryDPM: Eigen::internal::eigen_zero_impl< Xpr, true > Struct Template Reference
Eigen::internal::eigen_zero_impl< Xpr, true > Struct Template Reference
#include <Fill.h>
Public Types
using Scalar = typename Xpr::Scalar
Static Public Member Functions
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void run (Xpr &dst)
template<typename SrcXpr >
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void run (Xpr &dst, const SrcXpr &src)
Static Public Attributes
static constexpr size_t max_bytes = (std::numeric_limits<std::ptrdiff_t>::max)()
Member Typedef Documentation
Scalar
template<typename Xpr > using Eigen::internal::eigen_zero_impl< Xpr, true >::Scalar = typename Xpr::Scalar
Member Function Documentation
run() [1/2]
template<typename Xpr > static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::internal::eigen_zero_impl< Xpr, true >::run (Xpr & dst) inline static
{
     const size_t num_bytes = dst.size() * sizeof(Scalar);
     if (num_bytes == 0) return;
     void* dst_ptr = static_cast<void*>(dst.data());
 #ifndef EIGEN_NO_DEBUG
     if (num_bytes > max_bytes) throw_std_bad_alloc();
     eigen_assert((dst_ptr != nullptr) && "null pointer dereference error!");
 #endif
     EIGEN_USING_STD(memset);
     memset(dst_ptr, 0, num_bytes);
   }
References eigen_assert, EIGEN_USING_STD, and Eigen::internal::throw_std_bad_alloc().
run() [2/2]
template<typename Xpr > template<typename SrcXpr > static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::internal::eigen_zero_impl< Xpr, true >::run (Xpr & dst, const SrcXpr & src) inline static
{
     resize_if_allowed(dst, src, assign_op<Scalar, Scalar>());
     run(dst);
   }
References Eigen::internal::resize_if_allowed(), and Eigen::run().
Member Data Documentation
max_bytes
template<typename Xpr > constexpr size_t Eigen::internal::eigen_zero_impl< Xpr, true >::max_bytes = (std::numeric_limits<std::ptrdiff_t>::max)() static constexpr
The documentation for this struct was generated from the following file:
Fill.h