MercuryDPM: oomph::PVDEquationsWithPressure< DIM > Class Template Reference
oomph::PVDEquationsWithPressure< DIM > Class Template Reference abstract
#include <solid_elements.h>
Public Member Functions
PVDEquationsWithPressure ()
Constructor, by default the element is NOT incompressible.
void get_stress (const Vector< double > &s, DenseMatrix< double > &sigma)
bool is_incompressible () const
Return whether the material is incompressible.
void set_incompressible ()
Set the material to be incompressible.
void set_compressible ()
Set the material to be compressible.
virtual double solid_p (const unsigned &l)=0
Return the lth solid pressure.
virtual void set_solid_p (const unsigned &l, const double &p_value)=0
Set the lth solid pressure to p_value.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Fill in the residuals.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
double interpolated_solid_p (const Vector< double > &s)
Return the interpolated_solid_pressure.
void output (std::ostream &outfile)
Output: x,y,[z],xi0,xi1,[xi2],p,gamma.
void output (std::ostream &outfile, const unsigned &n_plot)
Output: x,y,[z],xi0,xi1,[xi2],p,gamma.
void output (FILE *file_pt)
C-style output: x,y,[z],xi0,xi1,[xi2],p,gamma.
void output (FILE *file_pt, const unsigned &n_plot)
C-style output: x,y,[z],xi0,xi1,[xi2],p,gamma.
void extended_output (std::ostream &outfile, const unsigned &n_plot)
Output: x,y,[z],xi0,xi1,[xi2],gamma strain and stress components.
void get_mass_matrix_diagonal (Vector< double > &mass_diag)
unsigned ndof_types () const
void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned >> &dof_lookup_list) const
Public Member Functions inherited from oomph::PVDEquationsBase< DIM >
PVDEquationsBase ()
ConstitutiveLaw *& constitutive_law_pt ()
Return the constitutive law pointer.
const double & lambda_sq () const
Access function for timescale ratio (nondim density)
double *& lambda_sq_pt ()
Access function for pointer to timescale ratio (nondim density)
IsotropicGrowthFctPt & isotropic_growth_fct_pt ()
Access function: Pointer to isotropic growth function.
PrestressFctPt & prestress_fct_pt ()
Access function: Pointer to pre-stress function.
IsotropicGrowthFctPt isotropic_growth_fct_pt () const
Access function: Pointer to isotropic growth function (const version)
BodyForceFctPt & body_force_fct_pt ()
Access function: Pointer to body force function.
BodyForceFctPt body_force_fct_pt () const
Access function: Pointer to body force function (const version)
void enable_inertia ()
Switch on solid inertia.
void disable_inertia ()
Switch off solid inertia.
bool is_inertia_enabled () const
Access function to flag that switches inertia on/off (const version)
virtual unsigned npres_solid () const
virtual int solid_p_local_eqn (const unsigned &i) const
virtual int solid_p_nodal_index () const
virtual void unpin_elemental_solid_pressure_dofs ()=0
Unpin all solid pressure dofs in the element.
virtual void pin_elemental_redundant_nodal_solid_pressures ()
Pin the element's redundant solid pressures (needed for refinement)
void get_strain (const Vector< double > &s, DenseMatrix< double > &strain) const
Return the strain tensor.
void get_energy (double &pot_en, double &kin_en)
Get potential (strain) and kinetic energy.
void get_deformed_covariant_basis_vectors (const Vector< double > &s, DenseMatrix< double > &def_covariant_basis)
void get_principal_stress (const Vector< double > &s, DenseMatrix< double > &principal_stress_vector, Vector< double > &principal_stress)
virtual void get_isotropic_growth (const unsigned &ipt, const Vector< double > &s, const Vector< double > &xi, double &gamma) const
void body_force (const Vector< double > &xi, Vector< double > &b) const
void enable_evaluate_jacobian_by_fd ()
Set Jacobian to be evaluated by FD? Else: Analytically.
void disable_evaluate_jacobian_by_fd ()
Set Jacobian to be evaluated analytically Else: by FD.
bool is_jacobian_evaluated_by_fd () const
Return the flag indicating whether the jacobian is evaluated by fd.
double prestress (const unsigned &i, const unsigned &j, const Vector< double > xi)
Public Member Functions inherited from oomph::SolidFiniteElement
void set_lagrangian_dimension (const unsigned &lagrangian_dimension)
virtual bool has_internal_solid_data ()
SolidFiniteElement ()
Constructor: Set defaults.
virtual ~SolidFiniteElement ()
Destructor to clean up any allocated memory.
SolidFiniteElement (const SolidFiniteElement &)=delete
Broken copy constructor.
unsigned ngeom_data () const
Broken assignment operator.
Data * geom_data_pt (const unsigned &j)
void identify_geometric_data (std::set< Data * > &geometric_data_pt)
double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
virtual void get_x_and_xi (const Vector< double > &s, Vector< double > &x_fe, Vector< double > &x, Vector< double > &xi_fe, Vector< double > &xi) const
virtual void set_macro_elem_pt (MacroElement *macro_elem_pt)
virtual void set_macro_elem_pt (MacroElement *macro_elem_pt, MacroElement *undeformed_macro_elem_pt)
void set_undeformed_macro_elem_pt (MacroElement *undeformed_macro_elem_pt)
MacroElement * undeformed_macro_elem_pt ()
Access function to pointer to "undeformed" macro element.
double dshape_lagrangian (const Vector< double > &s, Shape &psi, DShape &dpsidxi) const
virtual double dshape_lagrangian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidxi) const
double d2shape_lagrangian (const Vector< double > &s, Shape &psi, DShape &dpsidxi, DShape &d2psidxi) const
virtual double d2shape_lagrangian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidxi, DShape &d2psidxi) const
unsigned lagrangian_dimension () const
unsigned nnodal_lagrangian_type () const
Node * construct_node (const unsigned &n)
Construct the local node n and return a pointer to it.
Node * construct_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
Node * construct_boundary_node (const unsigned &n)
Node * construct_boundary_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
virtual void assign_all_generic_local_eqn_numbers (const bool &store_local_dof_pt)
void describe_local_dofs (std::ostream &out, const std::string &current_string) const
double raw_lagrangian_position (const unsigned &n, const unsigned &i) const
double raw_lagrangian_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double lagrangian_position (const unsigned &n, const unsigned &i) const
Return i-th Lagrangian coordinate at local node n.
double lagrangian_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
virtual double interpolated_xi (const Vector< double > &s, const unsigned &i) const
virtual void interpolated_xi (const Vector< double > &s, Vector< double > &xi) const
virtual void interpolated_dxids (const Vector< double > &s, DenseMatrix< double > &dxids) const
virtual void J_lagrangian (const Vector< double > &s) const
virtual double J_lagrangian_at_knot (const unsigned &ipt) const
SolidInitialCondition *& solid_ic_pt ()
Pointer to object that describes the initial condition.
void enable_solve_for_consistent_newmark_accel ()
void disable_solve_for_consistent_newmark_accel ()
Set to reset the problem being solved to be the standard problem.
MultiplierFctPt & multiplier_fct_pt ()
MultiplierFctPt multiplier_fct_pt () const
virtual void get_residuals_for_solid_ic (Vector< double > &residuals)
void fill_in_residuals_for_solid_ic (Vector< double > &residuals)
void fill_in_jacobian_for_solid_ic (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_jacobian_for_newmark_accel (DenseMatrix< double > &jacobian)
void compute_norm (double &el_norm)
int position_local_eqn (const unsigned &n, const unsigned &k, const unsigned &j) const
Public Member Functions inherited from oomph::FiniteElement
void set_dimension (const unsigned &dim)
void set_nodal_dimension (const unsigned &nodal_dim)
void set_nnodal_position_type (const unsigned &nposition_type)
Set the number of types required to interpolate the coordinate.
void set_n_node (const unsigned &n)
int nodal_local_eqn (const unsigned &n, const unsigned &i) const
double dJ_eulerian_at_knot (const unsigned &ipt, Shape &psi, DenseMatrix< double > &djacobian_dX) const
FiniteElement ()
Constructor.
virtual ~FiniteElement ()
FiniteElement (const FiniteElement &)=delete
Broken copy constructor.
virtual bool local_coord_is_valid (const Vector< double > &s)
Broken assignment operator.
virtual void move_local_coord_back_into_element (Vector< double > &s) const
void get_centre_of_gravity_and_max_radius_in_terms_of_zeta (Vector< double > &cog, double &max_radius) const
virtual void local_coordinate_of_node (const unsigned &j, Vector< double > &s) const
virtual void local_fraction_of_node (const unsigned &j, Vector< double > &s_fraction)
virtual double local_one_d_fraction_of_node (const unsigned &n1d, const unsigned &i)
MacroElement * macro_elem_pt ()
Access function to pointer to macro element.
void get_x (const Vector< double > &s, Vector< double > &x) const
void get_x (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void get_x_from_macro_element (const Vector< double > &s, Vector< double > &x) const
virtual void get_x_from_macro_element (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void set_integration_scheme (Integral *const &integral_pt)
Set the spatial integration scheme.
Integral *const & integral_pt () const
Return the pointer to the integration scheme (const version)
virtual void shape (const Vector< double > &s, Shape &psi) const =0
virtual void shape_at_knot (const unsigned &ipt, Shape &psi) const
virtual void dshape_local (const Vector< double > &s, Shape &psi, DShape &dpsids) const
virtual void dshape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids) const
virtual void d2shape_local (const Vector< double > &s, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual void d2shape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual double J_eulerian (const Vector< double > &s) const
virtual double J_eulerian_at_knot (const unsigned &ipt) const
void check_J_eulerian_at_knots (bool &passed) const
void check_jacobian (const double &jacobian) const
double dshape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsi, DenseMatrix< double > &djacobian_dX, RankFourTensor< double > &d_dpsidx_dX) const
double d2shape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual double d2shape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual void assign_nodal_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void describe_nodal_local_dofs (std::ostream &out, const std::string &current_string) const
Node *& node_pt (const unsigned &n)
Return a pointer to the local node n.
Node *const & node_pt (const unsigned &n) const
Return a pointer to the local node n (const version)
unsigned nnode () const
Return the number of nodes.
virtual unsigned nnode_1d () const
double raw_nodal_position (const unsigned &n, const unsigned &i) const
double raw_nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position (const unsigned &n, const unsigned &i) const
double nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double dnodal_position_dt (const unsigned &n, const unsigned &i) const
Return the i-th component of nodal velocity: dx/dt at local node n.
double dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
virtual void get_dresidual_dnodal_coordinates (RankThreeTensor< double > &dresidual_dnodal_coordinates)
virtual void disable_ALE ()
virtual void enable_ALE ()
virtual unsigned required_nvalue (const unsigned &n) const
unsigned nnodal_position_type () const
bool has_hanging_nodes () const
unsigned nodal_dimension () const
Return the required Eulerian dimension of the nodes in this element.
virtual unsigned nvertex_node () const
virtual Node * vertex_node_pt (const unsigned &j) const
int get_node_number (Node *const &node_pt) const
virtual Node * get_node_at_local_coordinate (const Vector< double > &s) const
double raw_nodal_value (const unsigned &n, const unsigned &i) const
double raw_nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
unsigned dim () const
virtual ElementGeometry::ElementGeometry element_geometry () const
Return the geometry type of the element (either Q or T usually).
virtual double interpolated_x (const Vector< double > &s, const unsigned &i) const
Return FE interpolated coordinate x[i] at local coordinate s.
virtual double interpolated_x (const unsigned &t, const Vector< double > &s, const unsigned &i) const
virtual void interpolated_x (const Vector< double > &s, Vector< double > &x) const
Return FE interpolated position x[] at local coordinate s as Vector.
virtual void interpolated_x (const unsigned &t, const Vector< double > &s, Vector< double > &x) const
virtual double interpolated_dxdt (const Vector< double > &s, const unsigned &i, const unsigned &t)
virtual void interpolated_dxdt (const Vector< double > &s, const unsigned &t, Vector< double > &dxdt)
void position (const Vector< double > &zeta, Vector< double > &r) const
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
void dposition_dt (const Vector< double > &zeta, const unsigned &t, Vector< double > &drdt)
void interpolated_zeta (const Vector< double > &s, Vector< double > &zeta) const
void locate_zeta (const Vector< double > &zeta, GeomObject *&geom_object_pt, Vector< double > &s, const bool &use_coordinate_as_initial_guess=false)
virtual void node_update ()
virtual void identify_field_data_for_interactions (std::set< std::pair< Data *, unsigned >> &paired_field_data)
virtual double s_min () const
Min value of local coordinate.
virtual double s_max () const
Max. value of local coordinate.
double size () const
virtual double compute_physical_size () const
virtual void point_output_data (const Vector< double > &s, Vector< double > &data)
void point_output (std::ostream &outfile, const Vector< double > &s)
virtual unsigned nplot_points_paraview (const unsigned &nplot) const
virtual unsigned nsub_elements_paraview (const unsigned &nplot) const
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_output_offset_information (std::ofstream &file_out, const unsigned &nplot, unsigned &counter) const
virtual void write_paraview_type (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_offsets (std::ofstream &file_out, const unsigned &nplot, unsigned &offset_sum) const
virtual unsigned nscalar_paraview () const
virtual void scalar_value_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
virtual std::string scalar_name_paraview (const unsigned &i) const
virtual void output (const unsigned &t, std::ostream &outfile, const unsigned &n_plot) const
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output an exact solution over the element.
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output a time-dependent exact solution over the element.
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, const SolutionFunctorBase &exact_soln) const
Output a time-dependent exact solution over the element.
virtual void get_s_plot (const unsigned &i, const unsigned &nplot, Vector< double > &s, const bool &shifted_to_interior=false) const
virtual std::string tecplot_zone_string (const unsigned &nplot) const
virtual void write_tecplot_zone_footer (std::ostream &outfile, const unsigned &nplot) const
virtual void write_tecplot_zone_footer (FILE *file_pt, const unsigned &nplot) const
virtual unsigned nplot_points (const unsigned &nplot) const
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_abs_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error)
void integrate_fct (FiniteElement::SteadyExactSolutionFctPt integrand_fct_pt, Vector< double > &integral)
Integrate Vector-valued function over element.
void integrate_fct (FiniteElement::UnsteadyExactSolutionFctPt integrand_fct_pt, const double &time, Vector< double > &integral)
Integrate Vector-valued time-dep function over element.
virtual void build_face_element (const int &face_index, FaceElement *face_element_pt)
virtual unsigned self_test ()
virtual unsigned get_bulk_node_number (const int &face_index, const unsigned &i) const
virtual int face_outer_unit_normal_sign (const int &face_index) const
Get the sign of the outer unit normal on the face given by face_index.
virtual unsigned nnode_on_face () const
void face_node_number_error_check (const unsigned &i) const
Range check for face node numbers.
virtual CoordinateMappingFctPt face_to_bulk_coordinate_fct_pt (const int &face_index) const
virtual BulkCoordinateDerivativesFctPt bulk_coordinate_derivatives_fct_pt (const int &face_index) const
Public Member Functions inherited from oomph::GeneralisedElement
GeneralisedElement ()
Constructor: Initialise all pointers and all values to zero.
virtual ~GeneralisedElement ()
Virtual destructor to clean up any memory allocated by the object.
GeneralisedElement (const GeneralisedElement &)=delete
Broken copy constructor.
void operator= (const GeneralisedElement &)=delete
Broken assignment operator.
Data *& internal_data_pt (const unsigned &i)
Return a pointer to i-th internal data object.
Data *const & internal_data_pt (const unsigned &i) const
Return a pointer to i-th internal data object (const version)
Data *& external_data_pt (const unsigned &i)
Return a pointer to i-th external data object.
Data *const & external_data_pt (const unsigned &i) const
Return a pointer to i-th external data object (const version)
unsigned long eqn_number (const unsigned &ieqn_local) const
int local_eqn_number (const unsigned long &ieqn_global) const
unsigned add_external_data (Data *const &data_pt, const bool &fd=true)
bool external_data_fd (const unsigned &i) const
void exclude_external_data_fd (const unsigned &i)
void include_external_data_fd (const unsigned &i)
void flush_external_data ()
Flush all external data.
void flush_external_data (Data *const &data_pt)
Flush the object addressed by data_pt from the external data array.
unsigned ninternal_data () const
Return the number of internal data objects.
unsigned nexternal_data () const
Return the number of external data objects.
unsigned ndof () const
Return the number of equations/dofs in the element.
void dof_vector (const unsigned &t, Vector< double > &dof)
Return the vector of dof values at time level t.
void dof_pt_vector (Vector< double * > &dof_pt)
Return the vector of pointers to dof values.
void set_internal_data_time_stepper (const unsigned &i, TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void assign_internal_eqn_numbers (unsigned long &global_number, Vector< double * > &Dof_pt)
void describe_dofs (std::ostream &out, const std::string &current_string) const
void add_internal_value_pt_to_map (std::map< unsigned, double * > &map_of_value_pt)
virtual void assign_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void complete_setup_of_dependencies ()
virtual void get_residuals (Vector< double > &residuals)
virtual void get_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
virtual void get_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void get_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void get_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void get_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void get_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void get_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void get_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void get_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
virtual void compute_norm (Vector< double > &norm)
Public Member Functions inherited from oomph::GeomObject
GeomObject ()
Default constructor.
GeomObject (const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim, TimeStepper *time_stepper_pt)
GeomObject (const GeomObject &dummy)=delete
Broken copy constructor.
void operator= (const GeomObject &)=delete
Broken assignment operator.
virtual ~GeomObject ()
(Empty) destructor
unsigned nlagrangian () const
Access function to # of Lagrangian coordinates.
unsigned ndim () const
Access function to # of Eulerian coordinates.
void set_nlagrangian_and_ndim (const unsigned &n_lagrangian, const unsigned &n_dim)
Set # of Lagrangian and Eulerian coordinates.
TimeStepper *& time_stepper_pt ()
TimeStepper * time_stepper_pt () const
virtual void position (const double &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void dposition (const Vector< double > &zeta, DenseMatrix< double > &drdzeta) const
virtual void d2position (const Vector< double > &zeta, RankThreeTensor< double > &ddrdzeta) const
virtual void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
Public Member Functions inherited from oomph::SolidElementWithDiagonalMassMatrix
SolidElementWithDiagonalMassMatrix ()
Empty constructor.
virtual ~SolidElementWithDiagonalMassMatrix ()
Virtual destructor.
SolidElementWithDiagonalMassMatrix (const SolidElementWithDiagonalMassMatrix &)=delete
Broken copy constructor.
void operator= (const SolidElementWithDiagonalMassMatrix &)=delete
Broken assignment operator.
Protected Member Functions
void get_stress (const DenseMatrix< double > &g, const DenseMatrix< double > &G, DenseMatrix< double > &sigma_dev, DenseMatrix< double > &Gcontra, double &gen_dil, double &inv_kappa)
void get_d_stress_dG_upper (const DenseMatrix< double > &g, const DenseMatrix< double > &G, const DenseMatrix< double > &sigma, const double &gen_dil, const double &inv_kappa, const double &interpolated_solid_p, RankFourTensor< double > &d_sigma_dG, DenseMatrix< double > &d_gen_dil_dG)
virtual void solid_pshape (const Vector< double > &s, Shape &psi) const =0
Return the solid pressure shape functions.
void solid_pshape_at_knot (const unsigned &ipt, Shape &psi) const
Return the stored solid shape functions at the knots.
virtual void fill_in_generic_residual_contribution_pvd_with_pressure (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix, const unsigned &flag)
void get_stress (const DenseMatrix< double > &g, const DenseMatrix< double > &G, DenseMatrix< double > &sigma_dev, DenseMatrix< double > &Gcontra, double &detG)
void get_d_stress_dG_upper (const DenseMatrix< double > &g, const DenseMatrix< double > &G, const DenseMatrix< double > &sigma, const double &detG, const double &interpolated_solid_p, RankFourTensor< double > &d_sigma_dG, DenseMatrix< double > &d_detG_dG)
Protected Member Functions inherited from oomph::SolidFiniteElement
void fill_in_generic_jacobian_for_solid_ic (Vector< double > &residuals, DenseMatrix< double > &jacobian, const unsigned &flag)
void set_nnodal_lagrangian_type (const unsigned &nlagrangian_type)
virtual double local_to_lagrangian_mapping (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
double local_to_lagrangian_mapping (const DShape &dpsids, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_lagrangian_mapping_diagonal (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual void assign_solid_local_eqn_numbers (const bool &store_local_dof)
Assign local equation numbers for the solid equations in the element.
void describe_solid_local_dofs (std::ostream &out, const std::string &current_string) const
Classifies dofs locally for solid specific aspects.
virtual void fill_in_jacobian_from_solid_position_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_jacobian_from_solid_position_by_fd (DenseMatrix< double > &jacobian)
virtual void update_before_solid_position_fd ()
virtual void reset_after_solid_position_fd ()
virtual void update_in_solid_position_fd (const unsigned &i)
virtual void reset_in_solid_position_fd (const unsigned &i)
Protected Member Functions inherited from oomph::FiniteElement
virtual void assemble_local_to_eulerian_jacobian (const DShape &dpsids, DenseMatrix< double > &jacobian) const
virtual void assemble_local_to_eulerian_jacobian2 (const DShape &d2psids, DenseMatrix< double > &jacobian2) const
virtual void assemble_eulerian_base_vectors (const DShape &dpsids, DenseMatrix< double > &interpolated_G) const
template<unsigned DIM>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double invert_jacobian_mapping (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping_diagonal (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual void dJ_eulerian_dnodal_coordinates (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<unsigned DIM>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
virtual void d_dshape_eulerian_dnodal_coordinates (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<unsigned DIM>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
virtual void transform_derivatives (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
void transform_derivatives_diagonal (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
virtual void transform_second_derivatives (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
virtual void fill_in_jacobian_from_nodal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_jacobian_from_nodal_by_fd (DenseMatrix< double > &jacobian)
virtual void update_before_nodal_fd ()
virtual void reset_after_nodal_fd ()
virtual void update_in_nodal_fd (const unsigned &i)
virtual void reset_in_nodal_fd (const unsigned &i)
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Zero-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
One-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Two-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
Protected Member Functions inherited from oomph::GeneralisedElement
unsigned add_internal_data (Data *const &data_pt, const bool &fd=true)
bool internal_data_fd (const unsigned &i) const
void exclude_internal_data_fd (const unsigned &i)
void include_internal_data_fd (const unsigned &i)
void clear_global_eqn_numbers ()
void add_global_eqn_numbers (std::deque< unsigned long > const &global_eqn_numbers, std::deque< double * > const &global_dof_pt)
virtual void assign_internal_and_external_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void assign_additional_local_eqn_numbers ()
int internal_local_eqn (const unsigned &i, const unsigned &j) const
int external_local_eqn (const unsigned &i, const unsigned &j)
void fill_in_jacobian_from_internal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_internal_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
virtual void update_before_internal_fd ()
virtual void reset_after_internal_fd ()
virtual void update_in_internal_fd (const unsigned &i)
virtual void reset_in_internal_fd (const unsigned &i)
virtual void update_before_external_fd ()
virtual void reset_after_external_fd ()
virtual void update_in_external_fd (const unsigned &i)
virtual void reset_in_external_fd (const unsigned &i)
virtual void fill_in_contribution_to_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void fill_in_contribution_to_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void fill_in_contribution_to_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void fill_in_contribution_to_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void fill_in_contribution_to_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
Protected Attributes
bool Incompressible
Boolean to determine whether the solid is incompressible or not.
Protected Attributes inherited from oomph::PVDEquationsBase< DIM >
IsotropicGrowthFctPt Isotropic_growth_fct_pt
Pointer to isotropic growth function.
PrestressFctPt Prestress_fct_pt
Pointer to prestress function.
ConstitutiveLaw * Constitutive_law_pt
Pointer to the constitutive law.
double * Lambda_sq_pt
Timescale ratio (non-dim. density)
bool Unsteady
Flag that switches inertia on/off.
BodyForceFctPt Body_force_fct_pt
Pointer to body force function.
bool Evaluate_jacobian_by_fd
Use FD to evaluate Jacobian.
Protected Attributes inherited from oomph::SolidFiniteElement
MacroElement * Undeformed_macro_elem_pt
Pointer to the element's "undeformed" macro element (NULL by default)
SolidInitialCondition * Solid_ic_pt
Pointer to object that specifies the initial condition.
bool Solve_for_consistent_newmark_accel_flag
Protected Attributes inherited from oomph::FiniteElement
MacroElement * Macro_elem_pt
Pointer to the element's macro element (NULL by default)
Protected Attributes inherited from oomph::GeomObject
unsigned NLagrangian
Number of Lagrangian (intrinsic) coordinates.
unsigned Ndim
Number of Eulerian coordinates.
TimeStepper * Geom_object_time_stepper_pt
Additional Inherited Members
Public Types inherited from oomph::PVDEquationsBase< DIM >
typedef void(* IsotropicGrowthFctPt) (const Vector< double > &xi, double &gamma)
typedef double(* PrestressFctPt) (const unsigned &i, const unsigned &j, const Vector< double > &xi)
typedef void(* BodyForceFctPt) (const double &t, const Vector< double > &xi, Vector< double > &b)
Public Types inherited from oomph::SolidFiniteElement
typedef double(* MultiplierFctPt) (const Vector< double > &xi)
Public Types inherited from oomph::FiniteElement
typedef void(* SteadyExactSolutionFctPt) (const Vector< double > &, Vector< double > &)
typedef void(* UnsteadyExactSolutionFctPt) (const double &, const Vector< double > &, Vector< double > &)
Static Public Member Functions inherited from oomph::PVDEquationsBase< DIM >
static void pin_redundant_nodal_solid_pressures (const Vector< GeneralisedElement * > &element_pt)
static void unpin_all_solid_pressure_dofs (const Vector< GeneralisedElement * > &element_pt)
Unpin all pressure dofs in elements listed in vector.
Static Public Attributes inherited from oomph::FiniteElement
static double Tolerance_for_singular_jacobian = 1.0e-16
Tolerance below which the jacobian is considered singular.
static bool Accept_negative_jacobian = false
static bool Suppress_output_while_checking_for_inverted_elements
Static Public Attributes inherited from oomph::GeneralisedElement
static bool Suppress_warning_about_repeated_internal_data
static bool Suppress_warning_about_repeated_external_data = true
static double Default_fd_jacobian_step = 1.0e-8
Static Protected Attributes inherited from oomph::PVDEquationsBase< DIM >
static double Default_lambda_sq_value = 1.0
Static default value for timescale ratio (1.0 – for natural scaling)
Static Protected Attributes inherited from oomph::FiniteElement
static const unsigned Default_Initial_Nvalue = 0
Default value for the number of values at a node.
static const double Node_location_tolerance = 1.0e-14
static const unsigned N2deriv [] = {0, 1, 3, 6}
Static Protected Attributes inherited from oomph::GeneralisedElement
static DenseMatrix< double > Dummy_matrix
static std::deque< double * > Dof_pt_deque
Detailed Description
template<unsigned DIM>
class oomph::PVDEquationsWithPressure< DIM >
//////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////// A class for elements that solve the equations of solid mechanics, based on the principle of virtual displacements, with a contitutive equation that involves a pressure. This formulation is required in the case of incompressible materials, in which the additional constraint that volume must be conserved is applied. In this case, the Incompressible flag must be set to true. If the Incompressible flag is not set to true, we use the nearly-incompressible formulation of the constitutive equations.
Constructor & Destructor Documentation
PVDEquationsWithPressure()
template<unsigned DIM> oomph::PVDEquationsWithPressure< DIM >::PVDEquationsWithPressure () inline
Constructor, by default the element is NOT incompressible.
                                : PVDEquationsBase<DIM>(), Incompressible(false)
     {
     }
Member Function Documentation
extended_output()
template<unsigned DIM> void oomph::PVDEquationsWithPressure< DIM >::extended_output (std::ostream & outfile, const unsigned & n_plot)
Output: x,y,[z],xi0,xi1,[xi2],gamma strain and stress components.
Output: x,y,[z],xi0,xi1,[xi2],gamma and the strain and stress components
   {
     Vector<double> x(DIM);
     Vector<double> xi(DIM);
     Vector<double> s(DIM);
     DenseMatrix<double> stress_or_strain(DIM, DIM);
     // Tecplot header info
     outfile << this->tecplot_zone_string(n_plot);
     // Loop over plot points
     unsigned num_plot_points = this->nplot_points(n_plot);
     for (unsigned iplot = 0; iplot < num_plot_points; iplot++)
     {
       // Get local coordinates of plot point
       this->get_s_plot(iplot, n_plot, s);
       // Get Eulerian and Lagrangian coordinates
       this->interpolated_x(s, x);
       this->interpolated_xi(s, xi);
       // Get isotropic growth
       double gamma;
       // Dummy integration point
       unsigned ipt = 0;
       this->get_isotropic_growth(ipt, s, xi, gamma);
       // Output the x,y,..
       for (unsigned i = 0; i < DIM; i++)
       {
         outfile << x[i] << " ";
       }
       // Output xi0,xi1,..
       for (unsigned i = 0; i < DIM; i++)
       {
         outfile << xi[i] << " ";
       }
       // Output growth
       outfile << gamma << " ";
       // Output pressure
       outfile << interpolated_solid_p(s) << " ";
       // get the strain
       this->get_strain(s, stress_or_strain);
       for (unsigned i = 0; i < DIM; i++)
       {
         for (unsigned j = 0; j <= i; j++)
         {
           outfile << stress_or_strain(j, i) << " ";
         }
       }
       // get the stress
       this->get_stress(s, stress_or_strain);
       for (unsigned i = 0; i < DIM; i++)
       {
         for (unsigned j = 0; j <= i; j++)
         {
           outfile << stress_or_strain(j, i) << " ";
         }
       }
       outfile << std::endl;
     }
     // Write tecplot footer (e.g. FE connectivity lists)
     this->write_tecplot_zone_footer(outfile, n_plot);
     outfile << std::endl;
   }
References DIM, mathsFunc::gamma(), i, j, s, and plotDoE::x.
fill_in_contribution_to_jacobian()
template<unsigned DIM> void oomph::PVDEquationsWithPressure< DIM >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) inline virtual
Fill in contribution to Jacobian (either by FD or analytically, for the positional variables; control this via evaluate_jacobian_by_fd(). Note: Jacobian entries arising from derivatives w.r.t. pressure terms are always computed analytically.
Reimplemented from oomph::SolidFiniteElement.
     {
       // Solve for the consistent acceleration in the Newmark scheme
       // Note that this replaces solid entries only
       if ((this->Solve_for_consistent_newmark_accel_flag) ||
           (this->Solid_ic_pt != 0))
       {
         std::string error_message = "Can't assign consistent Newmark history\n";
         error_message += " values for solid element with pressure dofs\n";
         throw OomphLibError(
           error_message, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
       }
       // FD
       if (this->Evaluate_jacobian_by_fd)
       {
         // Call the generic routine with the flag set to 2: Computes residuals
         // and derivatives w.r.t. to pressure variables
         fill_in_generic_residual_contribution_pvd_with_pressure(
           residuals, jacobian, GeneralisedElement::Dummy_matrix, 2);
         // Call the finite difference routine for the deriatives w.r.t.
         // the positional variables
         this->fill_in_jacobian_from_solid_position_by_fd(jacobian);
       }
       // Do it fully analytically
       else
       {
         // Call the generic routine with the flag set to 1: Get residual
         // and fully analytical Jacobian
         fill_in_generic_residual_contribution_pvd_with_pressure(
           residuals, jacobian, GeneralisedElement::Dummy_matrix, 1);
       }
     }
References oomph::GeneralisedElement::Dummy_matrix, oomph::PVDEquationsBase< DIM >::Evaluate_jacobian_by_fd, oomph::PVDEquationsWithPressure< DIM >::fill_in_generic_residual_contribution_pvd_with_pressure(), oomph::SolidFiniteElement::fill_in_jacobian_from_solid_position_by_fd(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::SolidFiniteElement::Solid_ic_pt, oomph::SolidFiniteElement::Solve_for_consistent_newmark_accel_flag, and oomph::Global_string_for_annotation::string().
fill_in_contribution_to_jacobian_and_mass_matrix()
template<unsigned DIM> void oomph::PVDEquationsWithPressure< DIM >::fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > & residuals, DenseMatrix< double > & jacobian, DenseMatrix< double > & mass_matrix) inline virtual
Fill in contribution to Mass matrix and Jacobian (either by FD or analytically, for the positional variables; control this via evaluate_jacobian_by_fd(). Note: Jacobian entries arising from derivatives w.r.t. pressure terms are always computed analytically. Note that the Jacobian is multiplied by minus one to ensure that the mass matrix is positive semi-definite.
Reimplemented from oomph::GeneralisedElement.
     {
       // Solve for the consistent acceleration in the Newmark scheme
       // Note that this replaces solid entries only
       if ((this->Solve_for_consistent_newmark_accel_flag) ||
           (this->Solid_ic_pt != 0))
       {
         std::string error_message = "Can't assign consistent Newmark history\n";
         error_message += " values for solid element with pressure dofs\n";
         throw OomphLibError(
           error_message, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
       }
       // FD
       if (this->Evaluate_jacobian_by_fd)
       {
         // Call the generic routine with the flag set to 4: Computes residuals
         // and derivatives w.r.t. to pressure variables
         // and the mass matrix
         fill_in_generic_residual_contribution_pvd_with_pressure(
           residuals, jacobian, mass_matrix, 4);
         // Call the finite difference routine for the deriatives w.r.t.
         // the positional variables
         this->fill_in_jacobian_from_solid_position_by_fd(jacobian);
       }
       // Do it fully analytically
       else
       {
         // Call the generic routine with the flag set to 3: Get residual
         // and fully analytical Jacobian
         fill_in_generic_residual_contribution_pvd_with_pressure(
           residuals, jacobian, mass_matrix, 3);
       }
       // Multiply the residuals and jacobian by minus one
       const unsigned n_dof = this->ndof();
       for (unsigned i = 0; i < n_dof; i++)
       {
         residuals[i] *= -1.0;
         for (unsigned j = 0; j < n_dof; j++)
         {
           jacobian(i, j) *= -1.0;
         }
       }
     }
References oomph::PVDEquationsBase< DIM >::Evaluate_jacobian_by_fd, oomph::PVDEquationsWithPressure< DIM >::fill_in_generic_residual_contribution_pvd_with_pressure(), oomph::SolidFiniteElement::fill_in_jacobian_from_solid_position_by_fd(), i, j, oomph::GeneralisedElement::ndof(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::SolidFiniteElement::Solid_ic_pt, oomph::SolidFiniteElement::Solve_for_consistent_newmark_accel_flag, and oomph::Global_string_for_annotation::string().
fill_in_contribution_to_residuals()
template<unsigned DIM> void oomph::PVDEquationsWithPressure< DIM >::fill_in_contribution_to_residuals (Vector< double > & residuals) inline virtual
Fill in the residuals.
Reimplemented from oomph::GeneralisedElement.
     {
       // Call the generic residuals function with flag set to 0
       // using a dummy matrix argument
       fill_in_generic_residual_contribution_pvd_with_pressure(
         residuals,
         GeneralisedElement::Dummy_matrix,
         GeneralisedElement::Dummy_matrix,
         0);
     }
References oomph::GeneralisedElement::Dummy_matrix, and oomph::PVDEquationsWithPressure< DIM >::fill_in_generic_residual_contribution_pvd_with_pressure().
fill_in_generic_residual_contribution_pvd_with_pressure()
template<unsigned DIM> void oomph::PVDEquationsWithPressure< DIM >::fill_in_generic_residual_contribution_pvd_with_pressure (Vector< double > & residuals, DenseMatrix< double > & jacobian, DenseMatrix< double > & mass_matrix, const unsigned & flag) protected virtual
Returns the residuals for the discretised principle of virtual displacements, formulated in the incompressible/ near-incompressible case.
If flag==0, compute only the residual vector.
If flag==1, compute residual vector and fully analytical Jacobian
If flag==2, also compute the pressure-related entries in the Jacobian (all others need to be done by finite differencing.
Fill in element's contribution to the elemental residual vector and/or Jacobian matrix. flag=0: compute only residual vector flag=1: compute both, fully analytically flag=2: compute both, using FD for the derivatives w.r.t. to the discrete displacment dofs. flag=3: compute residuals, jacobian (full analytic) and mass matrix flag=4: compute residuals, jacobian (FD for derivatives w.r.t. displacements) and mass matrix
Reimplemented in oomph::RefineablePVDEquationsWithPressure< DIM >.
   {
 #ifdef PARANOID
     // Check if the constitutive equation requires the explicit imposition of an
     // incompressibility constraint
     if (this->Constitutive_law_pt->requires_incompressibility_constraint() &&
         (!Incompressible))
     {
       throw OomphLibError("The constitutive law requires the use of the "
                           "incompressible formulation by setting the element's "
                           "member function set_incompressible()",
                           OOMPH_CURRENT_FUNCTION,
                           OOMPH_EXCEPTION_LOCATION);
     }
 #endif
     // Simply set up initial condition?
     if (this->Solid_ic_pt != 0)
     {
       this->get_residuals_for_solid_ic(residuals);
       return;
     }
     // Find out how many nodes there are
     const unsigned n_node = this->nnode();
     // Find out how many position types of dof there are
     const unsigned n_position_type = this->nnodal_position_type();
     // Find out how many pressure dofs there are
     const unsigned n_solid_pres = this->npres_solid();
     // Set up memory for the shape functions
     Shape psi(n_node, n_position_type);
     DShape dpsidxi(n_node, n_position_type, DIM);
     // Set up memory for the pressure shape functions
     Shape psisp(n_solid_pres);
     // Set the value of n_intpt
     const unsigned n_intpt = this->integral_pt()->nweight();
     // Set the vector to hold the local coordinates in the element
     Vector<double> s(DIM);
     // Timescale ratio (non-dim density)
     double lambda_sq = this->lambda_sq();
     // Time factor
     double time_factor = 0.0;
     if (lambda_sq > 0)
     {
       time_factor = this->node_pt(0)->position_time_stepper_pt()->weight(2, 0);
     }
     // Integers to hold the local equation and unknown numbers
     int local_eqn = 0, local_unknown = 0;
     // Loop over the integration points
     for (unsigned ipt = 0; ipt < n_intpt; ipt++)
     {
       // Assign the values of s
       for (unsigned i = 0; i < DIM; ++i)
       {
         s[i] = this->integral_pt()->knot(ipt, i);
       }
       // Get the integral weight
       double w = this->integral_pt()->weight(ipt);
       // Call the derivatives of the shape functions
       double J = this->dshape_lagrangian_at_knot(ipt, psi, dpsidxi);
       // Call the pressure shape functions
       solid_pshape_at_knot(ipt, psisp);
       // Storage for Lagrangian coordinates (initialised to zero)
       Vector<double> interpolated_xi(DIM, 0.0);
       // Deformed tangent vectors
       DenseMatrix<double> interpolated_G(DIM);
       // Setup memory for accelerations
       Vector<double> accel(DIM);
       // Initialise to zero
       for (unsigned i = 0; i < DIM; i++)
       {
         // Initialise acclerations
         accel[i] = 0.0;
         for (unsigned j = 0; j < DIM; j++)
         {
           interpolated_G(i, j) = 0.0;
         }
       }
       // Calculate displacements and derivatives and lagrangian coordinates
       for (unsigned l = 0; l < n_node; l++)
       {
         // Loop over positional dofs
         for (unsigned k = 0; k < n_position_type; k++)
         {
           // Loop over displacement components (deformed position)
           for (unsigned i = 0; i < DIM; i++)
           {
             // Calculate the lagrangian coordinates and the accelerations
             interpolated_xi[i] +=
               this->lagrangian_position_gen(l, k, i) * psi(l, k);
             // Only compute accelerations if inertia is switched on
             // otherwise the timestepper might not be able to
             // work out dx_gen_dt(2,...)
             if ((lambda_sq > 0.0) && (this->Unsteady))
             {
               accel[i] += this->dnodal_position_gen_dt(2, l, k, i) * psi(l, k);
             }
             // Loop over derivative directions
             for (unsigned j = 0; j < DIM; j++)
             {
               interpolated_G(j, i) +=
                 this->nodal_position_gen(l, k, i) * dpsidxi(l, k, j);
             }
           }
         }
       }
       // Get isotropic growth factor
       double gamma = 1.0;
       this->get_isotropic_growth(ipt, s, interpolated_xi, gamma);
       // Get body force at current time
       Vector<double> b(DIM);
       this->body_force(interpolated_xi, b);
       // We use Cartesian coordinates as the reference coordinate
       // system. In this case the undeformed metric tensor is always
       // the identity matrix -- stretched by the isotropic growth
       double diag_entry = pow(gamma, 2.0 / double(DIM));
       DenseMatrix<double> g(DIM);
       for (unsigned i = 0; i < DIM; i++)
       {
         for (unsigned j = 0; j < DIM; j++)
         {
           if (i == j)
           {
             g(i, j) = diag_entry;
           }
           else
           {
             g(i, j) = 0.0;
           }
         }
       }
       // Premultiply the undeformed volume ratio (from the isotropic
       // growth), the weights and the Jacobian
       double W = gamma * w * J;
       // Calculate the interpolated solid pressure
       double interpolated_solid_p = 0.0;
       for (unsigned l = 0; l < n_solid_pres; l++)
       {
         interpolated_solid_p += solid_p(l) * psisp[l];
       }
       // Declare and calculate the deformed metric tensor
       DenseMatrix<double> G(DIM);
       // Assign values of G
       for (unsigned i = 0; i < DIM; i++)
       {
         // Do upper half of matrix
         for (unsigned j = i; j < DIM; j++)
         {
           // Initialise G(i,j) to zero
           G(i, j) = 0.0;
           // Now calculate the dot product
           for (unsigned k = 0; k < DIM; k++)
           {
             G(i, j) += interpolated_G(i, k) * interpolated_G(j, k);
           }
         }
         // Matrix is symmetric so just copy lower half
         for (unsigned j = 0; j < i; j++)
         {
           G(i, j) = G(j, i);
         }
       }
       // Now calculate the deviatoric stress and all pressure-related
       // quantitites
       DenseMatrix<double> sigma(DIM, DIM), sigma_dev(DIM, DIM), Gup(DIM, DIM);
       double detG = 0.0;
       double gen_dil = 0.0;
       double inv_kappa = 0.0;
       // Get stress derivative by FD only needed for Jacobian
       // Stress etc derivatives
       RankFourTensor<double> d_stress_dG(DIM, DIM, DIM, DIM, 0.0);
       DenseMatrix<double> d_detG_dG(DIM, DIM, 0.0);
       DenseMatrix<double> d_gen_dil_dG(DIM, DIM, 0.0);
       // Derivative of metric tensor w.r.t. to nodal coords
       RankFiveTensor<double> d_G_dX(
         n_node, n_position_type, DIM, DIM, DIM, 0.0);
       // Get Jacobian too?
       if ((flag == 1) || (flag == 3))
       {
         // Derivative of metric tensor w.r.t. to discrete positional dofs
         // NOTE: Since G is symmetric we only compute the upper triangle
         //       and DO NOT copy the entries across. Subsequent computations
         //       must (and, in fact, do) therefore only operate with upper
         //       triangular entries
         for (unsigned ll = 0; ll < n_node; ll++)
         {
           for (unsigned kk = 0; kk < n_position_type; kk++)
           {
             for (unsigned ii = 0; ii < DIM; ii++)
             {
               for (unsigned aa = 0; aa < DIM; aa++)
               {
                 for (unsigned bb = aa; bb < DIM; bb++)
                 {
                   d_G_dX(ll, kk, ii, aa, bb) =
                     interpolated_G(aa, ii) * dpsidxi(ll, kk, bb) +
                     interpolated_G(bb, ii) * dpsidxi(ll, kk, aa);
                 }
               }
             }
           }
         }
       }
       // Incompressible: Compute the deviatoric part of the stress tensor, the
       // contravariant deformed metric tensor and the determinant
       // of the deformed covariant metric tensor.
       if (Incompressible)
       {
         get_stress(g, G, sigma_dev, Gup, detG);
         // Get full stress
         for (unsigned a = 0; a < DIM; a++)
         {
           for (unsigned b = 0; b < DIM; b++)
           {
             sigma(a, b) = sigma_dev(a, b) - interpolated_solid_p * Gup(a, b);
           }
         }
         // Get Jacobian too?
         if ((flag == 1) || (flag == 3))
         {
           // Get the "upper triangular" entries of the derivatives of the stress
           // tensor with respect to G
           this->get_d_stress_dG_upper(
             g, G, sigma, detG, interpolated_solid_p, d_stress_dG, d_detG_dG);
         }
       }
       // Nearly incompressible: Compute the deviatoric part of the
       // stress tensor, the contravariant deformed metric tensor,
       // the generalised dilatation and the inverse bulk modulus.
       else
       {
         get_stress(g, G, sigma_dev, Gup, gen_dil, inv_kappa);
         // Get full stress
         for (unsigned a = 0; a < DIM; a++)
         {
           for (unsigned b = 0; b < DIM; b++)
           {
             sigma(a, b) = sigma_dev(a, b) - interpolated_solid_p * Gup(a, b);
           }
         }
         // Get Jacobian too?
         if ((flag == 1) || (flag == 3))
         {
           // Get the "upper triangular" entries of the derivatives of the stress
           // tensor with respect to G
           this->get_d_stress_dG_upper(g,
                                       G,
                                       sigma,
                                       gen_dil,
                                       inv_kappa,
                                       interpolated_solid_p,
                                       d_stress_dG,
                                       d_gen_dil_dG);
         }
       }
       // Add pre-stress
       for (unsigned i = 0; i < DIM; i++)
       {
         for (unsigned j = 0; j < DIM; j++)
         {
           sigma(i, j) += this->prestress(i, j, interpolated_xi);
         }
       }
       //=====EQUATIONS OF ELASTICITY FROM PRINCIPLE OF VIRTUAL
       // DISPLACEMENTS========
       // Loop over the test functions, nodes of the element
       for (unsigned l = 0; l < n_node; l++)
       {
         // Loop over the types of dof
         for (unsigned k = 0; k < n_position_type; k++)
         {
           // Offset for faster access
           const unsigned offset5 = dpsidxi.offset(l, k);
           // Loop over the displacement components
           for (unsigned i = 0; i < DIM; i++)
           {
             // Get the equation number
             local_eqn = this->position_local_eqn(l, k, i);
             /*IF it's not a boundary condition*/
             if (local_eqn >= 0)
             {
               // Initialise the contribution
               double sum = 0.0;
               // Acceleration and body force
               sum += (lambda_sq * accel[i] - b[i]) * psi(l, k);
               // Stress term
               for (unsigned a = 0; a < DIM; a++)
               {
                 unsigned count = offset5;
                 for (unsigned b = 0; b < DIM; b++)
                 {
                   // Add the stress terms to the residuals
                   sum += sigma(a, b) * interpolated_G(a, i) *
                          dpsidxi.raw_direct_access(count);
                   ++count;
                 }
               }
               residuals[local_eqn] += W * sum;
               // Add in the mass matrix terms
               if (flag > 2)
               {
                 // Loop over the nodes of the element again
                 for (unsigned ll = 0; ll < n_node; ll++)
                 {
                   // Loop of types of dofs again
                   for (unsigned kk = 0; kk < n_position_type; kk++)
                   {
                     // Get the number of the unknown
                     int local_unknown = this->position_local_eqn(ll, kk, i);
                     /*IF it's not a boundary condition*/
                     if (local_unknown >= 0)
                     {
                       mass_matrix(local_eqn, local_unknown) +=
                         lambda_sq * psi(l, k) * psi(ll, kk) * W;
                     }
                   }
                 }
               }
               // Add in the jacobian terms
               if ((flag == 1) || (flag == 3))
               {
                 // Offset for faster access in general stress loop
                 const unsigned offset1 = d_G_dX.offset(l, k, i);
                 // Loop over the nodes of the element again
                 for (unsigned ll = 0; ll < n_node; ll++)
                 {
                   // Loop of types of dofs again
                   for (unsigned kk = 0; kk < n_position_type; kk++)
                   {
                     // Loop over the displacement components again
                     for (unsigned ii = 0; ii < DIM; ii++)
                     {
                       // Get the number of the unknown
                       int local_unknown = this->position_local_eqn(ll, kk, ii);
                       /*IF it's not a boundary condition*/
                       if (local_unknown >= 0)
                       {
                         // Offset for faster access in general stress loop
                         const unsigned offset2 = d_G_dX.offset(ll, kk, ii);
                         const unsigned offset4 = dpsidxi.offset(ll, kk);
                         // General stress term
                         //--------------------
                         double sum = 0.0;
                         unsigned count1 = offset1;
                         for (unsigned a = 0; a < DIM; a++)
{
                           // Bump up direct access because we're only
                           // accessing upper triangle
                           count1 += a;
                           for (unsigned b = a; b < DIM; b++)
{
                             double factor = d_G_dX.raw_direct_access(count1);
                             if (a == b) factor *= 0.5;
                             // Offset for faster access
                             unsigned offset3 = d_stress_dG.offset(a, b);
                             unsigned count2 = offset2;
                             unsigned count3 = offset3;
                             for (unsigned aa = 0; aa < DIM; aa++)
{
                               // Bump up direct access because we're only
                               // accessing upper triangle
                               count2 += aa;
                               count3 += aa;
                               // Only upper half of derivatives w.r.t. symm
                               // tensor
                               for (unsigned bb = aa; bb < DIM; bb++)
{
                                 sum += factor *
                                        d_stress_dG.raw_direct_access(count3) *
                                        d_G_dX.raw_direct_access(count2);
                                 ++count2;
                                 ++count3;
                               }
                             }
                             ++count1;
                           }
                         }
                         // Multiply by weight and add contribution
                         // (Add directly because this bit is nonsymmetric)
                         jacobian(local_eqn, local_unknown) += sum * W;
                         // Only upper triangle (no separate test for bc as
                         // local_eqn is already nonnegative)
                         if ((i == ii) && (local_unknown >= local_eqn))
{
                           // Initialise the contribution
                           double sum = 0.0;
                           // Inertia term
                           sum +=
                             lambda_sq * time_factor * psi(ll, kk) * psi(l, k);
                           // Stress term
                           unsigned count4 = offset4;
                           for (unsigned a = 0; a < DIM; a++)
{
                             // Cache term
                             const double factor =
                               dpsidxi.raw_direct_access(count4); // ll ,kk
                             ++count4;
                             unsigned count5 = offset5;
                             for (unsigned b = 0; b < DIM; b++)
{
                               sum += sigma(a, b) * factor *
                                      dpsidxi.raw_direct_access(count5); // l  ,k
                               ++count5;
                             }
                           }
                           // Add to jacobian
                           jacobian(local_eqn, local_unknown) += sum * W;
                           // Add to lower triangular parts
                           if (local_eqn != local_unknown)
{
                             jacobian(local_unknown, local_eqn) += sum * W;
                           }
                         }
                       } // End of if not boundary condition
                     }
                   }
                 }
               }
               // Derivatives w.r.t. pressure dofs
               if (flag > 0)
               {
                 // Loop over the pressure dofs for unknowns
                 for (unsigned l2 = 0; l2 < n_solid_pres; l2++)
                 {
                   local_unknown = this->solid_p_local_eqn(l2);
                   // If it's not a boundary condition
                   if (local_unknown >= 0)
                   {
                     // Add the pressure terms to the jacobian
                     for (unsigned a = 0; a < DIM; a++)
                     {
                       for (unsigned b = 0; b < DIM; b++)
                       {
                         jacobian(local_eqn, local_unknown) -=
                           psisp[l2] * Gup(a, b) * interpolated_G(a, i) *
                           dpsidxi(l, k, b) * W;
                       }
                     }
                   }
                 }
               } // End of Jacobian terms
             } // End of if not boundary condition
           } // End of loop over coordinate directions
         } // End of loop over types of dof
       } // End of loop over shape functions
       //==============CONSTRAINT EQUATIONS FOR PRESSURE=====================
       // Now loop over the pressure degrees of freedom
       for (unsigned l = 0; l < n_solid_pres; l++)
       {
         local_eqn = this->solid_p_local_eqn(l);
         // Pinned (unlikely, actually) or real dof?
         if (local_eqn >= 0)
         {
           // For true incompressibility we need to conserve volume
           // so the determinant of the deformed metric tensor
           // needs to be equal to that of the undeformed one, which
           // is equal to the volumetric growth factor
           if (Incompressible)
           {
             residuals[local_eqn] += (detG - gamma) * psisp[l] * W;
             // Get Jacobian too?
             if ((flag == 1) || (flag == 3))
             {
               // Loop over the nodes of the element again
               for (unsigned ll = 0; ll < n_node; ll++)
               {
                 // Loop of types of dofs again
                 for (unsigned kk = 0; kk < n_position_type; kk++)
                 {
                   // Loop over the displacement components again
                   for (unsigned ii = 0; ii < DIM; ii++)
                   {
                     // Get the number of the unknown
                     int local_unknown = this->position_local_eqn(ll, kk, ii);
                     /*IF it's not a boundary condition*/
                     if (local_unknown >= 0)
                     {
                       // Offset for faster access
                       const unsigned offset = d_G_dX.offset(ll, kk, ii);
                       // General stress term
                       double sum = 0.0;
                       unsigned count = offset;
                       for (unsigned aa = 0; aa < DIM; aa++)
                       {
                         // Bump up direct access because we're only
                         // accessing upper triangle
                         count += aa;
                         // Only upper half
                         for (unsigned bb = aa; bb < DIM; bb++)
{
                           sum += d_detG_dG(aa, bb) *
                                  d_G_dX.raw_direct_access(count) * psisp(l);
                           ++count;
                         }
                       }
                       jacobian(local_eqn, local_unknown) += sum * W;
                     }
                   }
                 }
               }
               // No Jacobian terms due to pressure since it does not feature
               // in the incompressibility constraint
             }
           }
           // Nearly incompressible: (Neg.) pressure given by product of
           // bulk modulus and generalised dilatation
           else
           {
             residuals[local_eqn] +=
               (inv_kappa * interpolated_solid_p + gen_dil) * psisp[l] * W;
             // Add in the jacobian terms
             if ((flag == 1) || (flag == 3))
             {
               // Loop over the nodes of the element again
               for (unsigned ll = 0; ll < n_node; ll++)
               {
                 // Loop of types of dofs again
                 for (unsigned kk = 0; kk < n_position_type; kk++)
                 {
                   // Loop over the displacement components again
                   for (unsigned ii = 0; ii < DIM; ii++)
                   {
                     // Get the number of the unknown
                     int local_unknown = this->position_local_eqn(ll, kk, ii);
                     /*IF it's not a boundary condition*/
                     if (local_unknown >= 0)
                     {
                       // Offset for faster access
                       const unsigned offset = d_G_dX.offset(ll, kk, ii);
                       // General stress term
                       double sum = 0.0;
                       unsigned count = offset;
                       for (unsigned aa = 0; aa < DIM; aa++)
                       {
                         // Bump up direct access because we're only
                         // accessing upper triangle
                         count += aa;
                         // Only upper half
                         for (unsigned bb = aa; bb < DIM; bb++)
{
                           sum += d_gen_dil_dG(aa, bb) *
                                  d_G_dX.raw_direct_access(count) * psisp(l);
                           ++count;
                         }
                       }
                       jacobian(local_eqn, local_unknown) += sum * W;
                     }
                   }
                 }
               }
             }
             // Derivatives w.r.t. pressure dofs
             if (flag > 0)
             {
               // Loop over the pressure nodes again
               for (unsigned l2 = 0; l2 < n_solid_pres; l2++)
               {
                 local_unknown = this->solid_p_local_eqn(l2);
                 // If not pinnned
                 if (local_unknown >= 0)
                 {
                   jacobian(local_eqn, local_unknown) +=
                     inv_kappa * psisp[l2] * psisp[l] * W;
                 }
               }
             } // End of jacobian terms
           } // End of else
         } // End of if not boundary condition
       }
     } // End of loop over integration points
   }
References a, b, Global_Parameters::body_force(), Constitutive::Constitutive_law_pt, DIM, G, mathsFunc::gamma(), i, J, j, k, oomph::RankFourTensor< T >::offset(), oomph::DShape::offset(), oomph::RankFiveTensor< T >::offset(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, Eigen::bfloat16_impl::pow(), oomph::RankFourTensor< T >::raw_direct_access(), oomph::RankFiveTensor< T >::raw_direct_access(), oomph::DShape::raw_direct_access(), oomph::ConstitutiveLaw::requires_incompressibility_constraint(), s, calibrate::sigma, w, and oomph::QuadTreeNames::W.
Referenced by oomph::PVDEquationsWithPressure< DIM >::fill_in_contribution_to_jacobian(), oomph::PVDEquationsWithPressure< DIM >::fill_in_contribution_to_jacobian_and_mass_matrix(), and oomph::PVDEquationsWithPressure< DIM >::fill_in_contribution_to_residuals().
get_d_stress_dG_upper() [1/2]
template<unsigned DIM> void oomph::PVDEquationsWithPressure< DIM >::get_d_stress_dG_upper (const DenseMatrix< double > & g, const DenseMatrix< double > & G, const DenseMatrix< double > & sigma, const double & detG, const double & interpolated_solid_p, RankFourTensor< double > & d_sigma_dG, DenseMatrix< double > & d_detG_dG) inline protected
Return the derivative of the 2nd Piola Kirchhoff stress tensor, as calculated from the constitutive law in the incompresible formulation. Also return derivative of the determinant of the deformed covariant metric tensor (likely to be needed in the incompressibility constraint)
     {
 #ifdef PARANOID
       // If the pointer to the constitutive law hasn't been set, issue an error
       if (this->Constitutive_law_pt == 0)
       {
         // Write an error message
         std::string error_message =
           "Elements derived from PVDEquationsWithPressure \n";
         error_message += "must have a constitutive law:\n";
         error_message +=
           "set one using the constitutive_law_pt() member function";
         // Throw the error
         throw OomphLibError(
           error_message, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
       }
 #endif
       // Only bother with the symmetric part by passing false as last entry
       this->Constitutive_law_pt->calculate_d_second_piola_kirchhoff_stress_dG(
         g, G, sigma, detG, interpolated_solid_p, d_sigma_dG, d_detG_dG, false);
     }
References oomph::ConstitutiveLaw::calculate_d_second_piola_kirchhoff_stress_dG(), oomph::PVDEquationsBase< DIM >::Constitutive_law_pt, G, oomph::PVDEquationsWithPressure< DIM >::interpolated_solid_p(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, calibrate::sigma, and oomph::Global_string_for_annotation::string().
get_d_stress_dG_upper() [2/2]
template<unsigned DIM> void oomph::PVDEquationsWithPressure< DIM >::get_d_stress_dG_upper (const DenseMatrix< double > & g, const DenseMatrix< double > & G, const DenseMatrix< double > & sigma, const double & gen_dil, const double & inv_kappa, const double & interpolated_solid_p, RankFourTensor< double > & d_sigma_dG, DenseMatrix< double > & d_gen_dil_dG) inline protected
Return the derivative of the deviatoric part of the 2nd Piola Kirchhoff stress tensor, as calculated from the constitutive law in the nearly incompresible formulation. Also return the derivative of the generalised dilatation.
     {
 #ifdef PARANOID
       // If the pointer to the constitutive law hasn't been set, issue an error
       if (this->Constitutive_law_pt == 0)
       {
         // Write an error message
         std::string error_message =
           "Elements derived from PVDEquationsWithPressure \n";
         error_message += "must have a constitutive law:\n";
         error_message +=
           "set one using the constitutive_law_pt() member function";
         // Throw the error
         throw OomphLibError(
           error_message, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
       }
 #endif
       // Only bother with the symmetric part by passing false as last entry
       this->Constitutive_law_pt->calculate_d_second_piola_kirchhoff_stress_dG(
         g,
         G,
         sigma,
         gen_dil,
         inv_kappa,
         interpolated_solid_p,
         d_sigma_dG,
         d_gen_dil_dG,
         false);
     }
References oomph::ConstitutiveLaw::calculate_d_second_piola_kirchhoff_stress_dG(), oomph::PVDEquationsBase< DIM >::Constitutive_law_pt, G, oomph::PVDEquationsWithPressure< DIM >::interpolated_solid_p(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, calibrate::sigma, and oomph::Global_string_for_annotation::string().
get_dof_numbers_for_unknowns()
template<unsigned DIM> void oomph::PVDEquationsWithPressure< DIM >::get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned >> & dof_lookup_list) const inline virtual
Create a list of pairs for all unknowns in this element, so that the first entry in each pair contains the global equation number of the unknown, while the second one contains the number of the "DOF" that this unknown is associated with. (Function can obviously only be called if the equation numbering scheme has been set up.) There are DIM+1 types of DOF: displacement compnents and pressure
Reimplemented from oomph::PVDEquationsBase< DIM >.
     {
       // temporary pair (used to store dof lookup prior to being added to list
       std::pair<unsigned, unsigned> dof_lookup;
       // number of nodes
       const unsigned n_node = this->nnode();
       // Get the number of position dofs and dimensions at the node
       const unsigned n_position_type = this->nnodal_position_type();
       const unsigned nodal_dim = this->nodal_dimension();
       // Integer storage for local unknown
       int local_unknown = 0;
       // Loop over the nodes
       for (unsigned n = 0; n < n_node; n++)
       {
         // Loop over position dofs
         for (unsigned k = 0; k < n_position_type; k++)
         {
           // Loop over dimension
           for (unsigned i = 0; i < nodal_dim; i++)
           {
             // If the variable is free
             local_unknown = this->position_local_eqn(n, k, i);
             // ignore pinned values
             if (local_unknown >= 0)
             {
               // store dof lookup in temporary pair: First entry in pair
               // is global equation number; second entry is dof type
               dof_lookup.first = this->eqn_number(local_unknown);
               dof_lookup.second = i;
               // add to list
               dof_lookup_list.push_front(dof_lookup);
             }
           }
         }
       }
       // Do solid pressure degrees of freedom
       unsigned np = this->npres_solid();
       for (unsigned j = 0; j < np; j++)
       {
         int local_unknown = this->solid_p_local_eqn(j);
         // ignore pinned values
         if (local_unknown >= 0)
         {
           // store dof lookup in temporary pair: First entry in pair
           // is global equation number; second entry is dof type
           dof_lookup.first = this->eqn_number(local_unknown);
           dof_lookup.second = DIM;
           // add to list
           dof_lookup_list.push_front(dof_lookup);
         }
       }
     }
References DIM, oomph::GeneralisedElement::eqn_number(), i, j, k, n, oomph::FiniteElement::nnodal_position_type(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_dimension(), oomph::PVDEquationsBase< DIM >::npres_solid(), oomph::SolidFiniteElement::position_local_eqn(), and oomph::PVDEquationsBase< DIM >::solid_p_local_eqn().
get_mass_matrix_diagonal()
template<unsigned DIM> void oomph::PVDEquationsWithPressure< DIM >::get_mass_matrix_diagonal (Vector< double > & mass_diag) virtual
Compute the diagonal of the displacement mass matrix for LSC preconditioner
Compute the diagonal of the velocity mass matrix for LSC preconditioner.
Implements oomph::SolidElementWithDiagonalMassMatrix.
   {
     // Resize and initialise
     mass_diag.assign(this->ndof(), 0.0);
     // find out how many nodes there are
     unsigned n_node = this->nnode();
     // Find out how many position types of dof there are
     const unsigned n_position_type = this->nnodal_position_type();
     // Set up memory for the shape functions
     Shape psi(n_node, n_position_type);
     DShape dpsidxi(n_node, n_position_type, DIM);
     // Number of integration points
     unsigned n_intpt = this->integral_pt()->nweight();
     // Integer to store the local equations no
     int local_eqn = 0;
     // Loop over the integration points
     for (unsigned ipt = 0; ipt < n_intpt; ipt++)
     {
       // Get the integral weight
       double w = this->integral_pt()->weight(ipt);
       // Call the derivatives of the shape functions
       double J = this->dshape_lagrangian_at_knot(ipt, psi, dpsidxi);
       // Premultiply weights and Jacobian
       double W = w * J;
       // Loop over the nodes
       for (unsigned l = 0; l < n_node; l++)
       {
         // Loop over the types of dof
         for (unsigned k = 0; k < n_position_type; k++)
         {
           // Loop over the directions
           for (unsigned i = 0; i < DIM; i++)
           {
             // Get the equation number
             local_eqn = this->position_local_eqn(l, k, i);
             // If not a boundary condition
             if (local_eqn >= 0)
             {
               // Add the contribution
               mass_diag[local_eqn] += pow(psi(l, k), 2) * W;
             } // End of if not boundary condition statement
           } // End of loop over dimension
         } // End of dof type
       } // End of loop over basis functions
     }
   }
References DIM, i, J, k, Eigen::bfloat16_impl::pow(), w, and oomph::QuadTreeNames::W.
get_stress() [1/3]
template<unsigned DIM> void oomph::PVDEquationsWithPressure< DIM >::get_stress (const DenseMatrix< double > & g, const DenseMatrix< double > & G, DenseMatrix< double > & sigma_dev, DenseMatrix< double > & Gcontra, double & detG) inline protected
Return the deviatoric part of the 2nd Piola Kirchhoff stress tensor, as calculated from the constitutive law in the incompresible formulation. Also return the contravariant deformed metric tensor, and the determinant of the deformed covariant metric tensor (likely to be needed in the incompressibility constraint)
     {
 #ifdef PARANOID
       // If the pointer to the constitutive law hasn't been set, issue an error
       if (this->Constitutive_law_pt == 0)
       {
         // Write an error message
         std::string error_message =
           "Elements derived from PVDEquationsWithPressure \n";
         error_message += "must have a constitutive law:\n";
         error_message +=
           "set one using the constitutive_law_pt() member function";
         // Throw the error
         throw OomphLibError(
           error_message, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
       }
 #endif
       this->Constitutive_law_pt->calculate_second_piola_kirchhoff_stress(
         g, G, sigma_dev, Gcontra, detG);
     }
References oomph::ConstitutiveLaw::calculate_second_piola_kirchhoff_stress(), oomph::PVDEquationsBase< DIM >::Constitutive_law_pt, G, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and oomph::Global_string_for_annotation::string().
get_stress() [2/3]
template<unsigned DIM> void oomph::PVDEquationsWithPressure< DIM >::get_stress (const DenseMatrix< double > & g, const DenseMatrix< double > & G, DenseMatrix< double > & sigma_dev, DenseMatrix< double > & Gcontra, double & gen_dil, double & inv_kappa) inline protected
Return the deviatoric part of the 2nd Piola Kirchhoff stress tensor, as calculated from the constitutive law in the nearly incompresible formulation. Also return the contravariant deformed metric tensor, the generalised dilatation, and the inverse of the bulk modulus.
     {
 #ifdef PARANOID
       // If the pointer to the constitutive law hasn't been set, issue an error
       if (this->Constitutive_law_pt == 0)
       {
         // Write an error message
         std::string error_message =
           "Elements derived from PVDEquationsWithPressure \n";
         error_message += "must have a constitutive law:\n";
         error_message +=
           "set one using the constitutive_law_pt() member function";
         // Throw the error
         throw OomphLibError(
           error_message, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
       }
 #endif
       this->Constitutive_law_pt->calculate_second_piola_kirchhoff_stress(
         g, G, sigma_dev, Gcontra, gen_dil, inv_kappa);
     }
References oomph::ConstitutiveLaw::calculate_second_piola_kirchhoff_stress(), oomph::PVDEquationsBase< DIM >::Constitutive_law_pt, G, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and oomph::Global_string_for_annotation::string().
get_stress() [3/3]
template<unsigned DIM> void oomph::PVDEquationsWithPressure< DIM >::get_stress (const Vector< double > & s, DenseMatrix< double > & sigma) virtual
Return the 2nd Piola Kirchoff stress tensor, as calculated from the constitutive law at specified local coordinate
Compute the contravariant second Piola Kirchoff stress at a given local coordinate. Note: this replicates a lot of code that is already coontained in get_residuals() but without sacrificing efficiency (re-computing the shape functions several times) or creating helper functions with horrendous interfaces (to pass all the functions which shouldn't be recomputed) about this is unavoidable.
Implements oomph::PVDEquationsBase< DIM >.
   {
     // Find out how many nodes there are
     unsigned n_node = this->nnode();
     // Find out how many positional dofs there are
     unsigned n_position_type = this->nnodal_position_type();
     // Find out how many pressure dofs there are
     unsigned n_solid_pres = this->npres_solid();
     // Set up memory for the shape functions
     Shape psi(n_node, n_position_type);
     DShape dpsidxi(n_node, n_position_type, DIM);
     // Set up memory for the pressure shape functions
     Shape psisp(n_solid_pres);
     // Find values of shape function
     solid_pshape(s, psisp);
     // Call the derivatives of the shape functions (ignore Jacobian)
     (void)this->dshape_lagrangian(s, psi, dpsidxi);
     // Lagrangian coordinates
     Vector<double> xi(DIM);
     this->interpolated_xi(s, xi);
     // Get isotropic growth factor
     double gamma;
     // Dummy integration point
     unsigned ipt = 0;
     this->get_isotropic_growth(ipt, s, xi, gamma);
     // We use Cartesian coordinates as the reference coordinate
     // system. In this case the undeformed metric tensor is always
     // the identity matrix -- stretched by the isotropic growth
     double diag_entry = pow(gamma, 2.0 / double(DIM));
     DenseMatrix<double> g(DIM);
     for (unsigned i = 0; i < DIM; i++)
     {
       for (unsigned j = 0; j < DIM; j++)
       {
         if (i == j)
         {
           g(i, j) = diag_entry;
         }
         else
         {
           g(i, j) = 0.0;
         }
       }
     }
     // Calculate interpolated values of the derivative of global position
     // wrt lagrangian coordinates
     DenseMatrix<double> interpolated_G(DIM);
     // Initialise to zero
     for (unsigned i = 0; i < DIM; i++)
     {
       for (unsigned j = 0; j < DIM; j++)
       {
         interpolated_G(i, j) = 0.0;
       }
     }
     // Calculate displacements and derivatives
     for (unsigned l = 0; l < n_node; l++)
     {
       // Loop over positional dofs
       for (unsigned k = 0; k < n_position_type; k++)
       {
         // Loop over displacement components (deformed position)
         for (unsigned i = 0; i < DIM; i++)
         {
           // Loop over derivative directions
           for (unsigned j = 0; j < DIM; j++)
           {
             interpolated_G(j, i) +=
               this->nodal_position_gen(l, k, i) * dpsidxi(l, k, j);
           }
         }
       }
     }
     // Declare and calculate the deformed metric tensor
     DenseMatrix<double> G(DIM);
     // Assign values of G
     for (unsigned i = 0; i < DIM; i++)
     {
       // Do upper half of matrix
       // Note that j must be signed here for the comparison test to work
       // Also i must be cast to an int
       for (int j = (DIM - 1); j >= static_cast<int>(i); j--)
       {
         // Initialise G(i,j) to zero
         G(i, j) = 0.0;
         // Now calculate the dot product
         for (unsigned k = 0; k < DIM; k++)
         {
           G(i, j) += interpolated_G(i, k) * interpolated_G(j, k);
         }
       }
       // Matrix is symmetric so just copy lower half
       for (int j = (i - 1); j >= 0; j--)
       {
         G(i, j) = G(j, i);
       }
     }
     // Calculate the interpolated solid pressure
     double interpolated_solid_p = 0.0;
     for (unsigned l = 0; l < n_solid_pres; l++)
     {
       interpolated_solid_p += solid_p(l) * psisp[l];
     }
     // Now calculate the deviatoric stress and all pressure-related
     // quantitites
     DenseMatrix<double> sigma_dev(DIM), Gup(DIM);
     double detG = 0.0;
     double gen_dil = 0.0;
     double inv_kappa = 0.0;
     // Incompressible: Compute the deviatoric part of the stress tensor, the
     // contravariant deformed metric tensor and the determinant
     // of the deformed covariant metric tensor.
     if (Incompressible)
     {
       get_stress(g, G, sigma_dev, Gup, detG);
     }
     // Nearly incompressible: Compute the deviatoric part of the
     // stress tensor, the contravariant deformed metric tensor,
     // the generalised dilatation and the inverse bulk modulus.
     else
     {
       get_stress(g, G, sigma_dev, Gup, gen_dil, inv_kappa);
     }
     // Get complete stress
     for (unsigned i = 0; i < DIM; i++)
     {
       for (unsigned j = 0; j < DIM; j++)
       {
         sigma(i, j) = -interpolated_solid_p * Gup(i, j) + sigma_dev(i, j);
       }
     }
   }
References DIM, G, mathsFunc::gamma(), i, j, k, Eigen::bfloat16_impl::pow(), s, and calibrate::sigma.
interpolated_solid_p()
template<unsigned DIM> double oomph::PVDEquationsWithPressure< DIM >::interpolated_solid_p (const Vector< double > & s) inline
Return the interpolated_solid_pressure.
     {
       // Find number of nodes
       unsigned n_solid_pres = this->npres_solid();
       // Local shape function
       Shape psisp(n_solid_pres);
       // Find values of shape function
       solid_pshape(s, psisp);
       // Initialise value of solid_p
       double interpolated_solid_p = 0.0;
       // Loop over the local nodes and sum
       for (unsigned l = 0; l < n_solid_pres; l++)
       {
         interpolated_solid_p += solid_p(l) * psisp[l];
       }
       return (interpolated_solid_p);
     }
References oomph::PVDEquationsBase< DIM >::npres_solid(), s, oomph::PVDEquationsWithPressure< DIM >::solid_p(), and oomph::PVDEquationsWithPressure< DIM >::solid_pshape().
Referenced by oomph::RefineableQPVDElementWithPressure< DIM >::further_build(), oomph::PVDEquationsWithPressure< DIM >::get_d_stress_dG_upper(), and oomph::RefineableQPVDElementWithContinuousPressure< DIM >::get_interpolated_values().
is_incompressible()
template<unsigned DIM> bool oomph::PVDEquationsWithPressure< DIM >::is_incompressible () const inline
Return whether the material is incompressible.
     {
       return Incompressible;
     }
References oomph::PVDEquationsWithPressure< DIM >::Incompressible.
Referenced by oomph::RefineablePVDEquationsWithPressure< DIM >::further_build().
ndof_types()
template<unsigned DIM> unsigned oomph::PVDEquationsWithPressure< DIM >::ndof_types () const inline virtual
returns the number of DOF types associated with this element: displacement components and pressure
Reimplemented from oomph::PVDEquationsBase< DIM >.
     {
       return DIM + 1;
     }
References DIM.
output() [1/4]
template<unsigned DIM> void oomph::PVDEquationsWithPressure< DIM >::output (FILE * file_pt) inline virtual
C-style output: x,y,[z],xi0,xi1,[xi2],p,gamma.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::TPVDElementWithContinuousPressure< DIM >, oomph::QPVDElementWithContinuousPressure< DIM >, and oomph::QPVDElementWithPressure< DIM >.
     {
       unsigned n_plot = 5;
       output(file_pt, n_plot);
     }
References oomph::PVDEquationsWithPressure< DIM >::output().
output() [2/4]
template<unsigned DIM> void oomph::PVDEquationsWithPressure< DIM >::output (FILE * file_pt, const unsigned & n_plot) virtual
C-style output: x,y,[z],xi0,xi1,[xi2],p,gamma.
C-stsyle output: x,y,[z],xi0,xi1,[xi2],p,gamma.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::TPVDElementWithContinuousPressure< DIM >, oomph::QPVDElementWithContinuousPressure< DIM >, and oomph::QPVDElementWithPressure< DIM >.
   {
     // Set output Vector
     Vector<double> s(DIM);
     Vector<double> x(DIM);
     Vector<double> xi(DIM);
     switch (DIM)
     {
       case 2:
         // Tecplot header info
         // outfile << "ZONE I=" << n_plot << ", J=" << n_plot << std::endl;
         fprintf(file_pt, "ZONE I=%i, J=%i\n", n_plot, n_plot);
         // Loop over element nodes
         for (unsigned l2 = 0; l2 < n_plot; l2++)
         {
           s[1] = -1.0 + l2 * 2.0 / (n_plot - 1);
           for (unsigned l1 = 0; l1 < n_plot; l1++)
           {
             s[0] = -1.0 + l1 * 2.0 / (n_plot - 1);
             // Get Eulerian and Lagrangian coordinates
             this->interpolated_x(s, x);
             this->interpolated_xi(s, xi);
             // Get isotropic growth
             double gamma;
             // Dummy integration point
             unsigned ipt = 0;
             this->get_isotropic_growth(ipt, s, xi, gamma);
             // Output the x,y,..
             for (unsigned i = 0; i < DIM; i++)
             {
               // outfile << x[i] << " ";
               fprintf(file_pt, "%g ", x[i]);
             }
             // Output xi0,xi1,..
             for (unsigned i = 0; i < DIM; i++)
             {
               // outfile << xi[i] << " ";
               fprintf(file_pt, "%g ", xi[i]);
             }
             // Output growth
             // outfile << gamma << " ";
             fprintf(file_pt, "%g ", gamma);
             // Output pressure
             // outfile << interpolated_solid_p(s) << " ";
             // outfile << std::endl;
             fprintf(file_pt, "%g \n", interpolated_solid_p(s));
           }
         }
         break;
       case 3:
         // Tecplot header info
         // outfile << "ZONE I=" << n_plot
         //        << ", J=" << n_plot
         //        << ", K=" << n_plot << std::endl;
         fprintf(file_pt, "ZONE I=%i, J=%i, K=%i \n", n_plot, n_plot, n_plot);
         // Loop over element nodes
         for (unsigned l3 = 0; l3 < n_plot; l3++)
         {
           s[2] = -1.0 + l3 * 2.0 / (n_plot - 1);
           for (unsigned l2 = 0; l2 < n_plot; l2++)
           {
             s[1] = -1.0 + l2 * 2.0 / (n_plot - 1);
             for (unsigned l1 = 0; l1 < n_plot; l1++)
             {
               s[0] = -1.0 + l1 * 2.0 / (n_plot - 1);
               // Get Eulerian and Lagrangian coordinates
               this->interpolated_x(s, x);
               this->interpolated_xi(s, xi);
               // Get isotropic growth
               double gamma;
               // Dummy integration point
               unsigned ipt = 0;
               this->get_isotropic_growth(ipt, s, xi, gamma);
               // Output the x,y,..
               for (unsigned i = 0; i < DIM; i++)
               {
                 // outfile << x[i] << " ";
                 fprintf(file_pt, "%g ", x[i]);
               }
               // Output xi0,xi1,..
               for (unsigned i = 0; i < DIM; i++)
               {
                 // outfile << xi[i] << " ";
                 fprintf(file_pt, "%g ", xi[i]);
               }
               // Output growth
               // outfile << gamma << " ";
               fprintf(file_pt, "%g ", gamma);
               // Output pressure
               // outfile << interpolated_solid_p(s) << " ";
               // outfile << std::endl;
               fprintf(file_pt, "%g \n", interpolated_solid_p(s));
             }
           }
         }
         break;
       default:
         std::ostringstream error_message;
         error_message << "No output routine for PVDEquationsWithPressure<"
                       << DIM << "> elements. Write it yourself!" << std::endl;
         throw OomphLibError(error_message.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
     }
   }
References DIM, mathsFunc::gamma(), i, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, s, and plotDoE::x.
output() [3/4]
template<unsigned DIM> void oomph::PVDEquationsWithPressure< DIM >::output (std::ostream & outfile) inline virtual
Output: x,y,[z],xi0,xi1,[xi2],p,gamma.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::TPVDElementWithContinuousPressure< DIM >, oomph::QPVDElementWithContinuousPressure< DIM >, and oomph::QPVDElementWithPressure< DIM >.
     {
       unsigned n_plot = 5;
       output(outfile, n_plot);
     }
Referenced by oomph::PVDEquationsWithPressure< DIM >::output(), oomph::QPVDElementWithPressure< DIM >::output(), oomph::QPVDElementWithContinuousPressure< DIM >::output(), and oomph::TPVDElementWithContinuousPressure< DIM >::output().
output() [4/4]
template<unsigned DIM> void oomph::PVDEquationsWithPressure< DIM >::output (std::ostream & outfile, const unsigned & n_plot) virtual
Output: x,y,[z],xi0,xi1,[xi2],p,gamma.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::TPVDElementWithContinuousPressure< DIM >, oomph::QPVDElementWithContinuousPressure< DIM >, and oomph::QPVDElementWithPressure< DIM >.
   {
     // Set output Vector
     Vector<double> s(DIM);
     Vector<double> x(DIM);
     Vector<double> xi(DIM);
     // Tecplot header info
     outfile << this->tecplot_zone_string(n_plot);
     // Loop over plot points
     unsigned num_plot_points = this->nplot_points(n_plot);
     for (unsigned iplot = 0; iplot < num_plot_points; iplot++)
     {
       // Get local coordinates of plot point
       this->get_s_plot(iplot, n_plot, s);
       // Get Eulerian and Lagrangian coordinates
       this->interpolated_x(s, x);
       this->interpolated_xi(s, xi);
       // Get isotropic growth
       double gamma;
       // Dummy integration point
       unsigned ipt = 0;
       this->get_isotropic_growth(ipt, s, xi, gamma);
       // Output the x,y,..
       for (unsigned i = 0; i < DIM; i++)
       {
         outfile << x[i] << " ";
       }
       // Output xi0,xi1,..
       for (unsigned i = 0; i < DIM; i++)
       {
         outfile << xi[i] << " ";
       }
       // Output growth
       outfile << gamma << " ";
       // Output pressure
       outfile << interpolated_solid_p(s) << " ";
       outfile << "\n";
     }
     // Write tecplot footer (e.g. FE connectivity lists)
     this->write_tecplot_zone_footer(outfile, n_plot);
   }
References DIM, mathsFunc::gamma(), i, s, and plotDoE::x.
set_compressible()
template<unsigned DIM> void oomph::PVDEquationsWithPressure< DIM >::set_compressible () inline
Set the material to be compressible.
     {
       Incompressible = false;
     }
References oomph::PVDEquationsWithPressure< DIM >::Incompressible.
Referenced by CompressedSquareProblem< ELEMENT >::CompressedSquareProblem(), CantileverProblem< ELEMENT >::run_tests(), and SimpleShearProblem< ELEMENT >::set_incompressible().
set_incompressible()
template<unsigned DIM> void oomph::PVDEquationsWithPressure< DIM >::set_incompressible () inline
Set the material to be incompressible.
     {
       Incompressible = true;
     }
References oomph::PVDEquationsWithPressure< DIM >::Incompressible.
Referenced by CantileverProblem< ELEMENT >::CantileverProblem(), CompressedSquareProblem< ELEMENT >::CompressedSquareProblem(), main(), and SimpleShearProblem< ELEMENT >::set_incompressible().
set_solid_p()
template<unsigned DIM> virtual void oomph::PVDEquationsWithPressure< DIM >::set_solid_p (const unsigned & l, const double & p_value) pure virtual
Set the lth solid pressure to p_value.
Implemented in oomph::TPVDElementWithContinuousPressure< DIM >, oomph::QPVDElementWithContinuousPressure< DIM >, and oomph::QPVDElementWithPressure< DIM >.
solid_p()
template<unsigned DIM> virtual double oomph::PVDEquationsWithPressure< DIM >::solid_p (const unsigned & l) pure virtual
Return the lth solid pressure.
Implemented in oomph::TPVDElementWithContinuousPressure< DIM >, oomph::QPVDElementWithContinuousPressure< DIM >, and oomph::QPVDElementWithPressure< DIM >.
Referenced by oomph::PVDEquationsWithPressure< DIM >::interpolated_solid_p().
solid_pshape()
template<unsigned DIM> virtual void oomph::PVDEquationsWithPressure< DIM >::solid_pshape (const Vector< double > & s, Shape & psi) const protected pure virtual
Return the solid pressure shape functions.
Implemented in oomph::TPVDElementWithContinuousPressure< DIM >, oomph::TPVDElementWithContinuousPressure< DIM >, oomph::TPVDElementWithContinuousPressure< DIM >, oomph::QPVDElementWithContinuousPressure< DIM >, oomph::QPVDElementWithContinuousPressure< DIM >, oomph::QPVDElementWithContinuousPressure< DIM >, oomph::QPVDElementWithPressure< DIM >, oomph::QPVDElementWithPressure< DIM >, and oomph::QPVDElementWithPressure< DIM >.
Referenced by oomph::PVDEquationsWithPressure< DIM >::interpolated_solid_p(), and oomph::PVDEquationsWithPressure< DIM >::solid_pshape_at_knot().
solid_pshape_at_knot()
template<unsigned DIM> void oomph::PVDEquationsWithPressure< DIM >::solid_pshape_at_knot (const unsigned & ipt, Shape & psi) const inline protected
Return the stored solid shape functions at the knots.
     {
       // Find the dimension of the element
       unsigned Dim = this->dim();
       // Storage for local coordinates of the integration point
       Vector<double> s(Dim);
       // Set the local coordinates
       for (unsigned i = 0; i < Dim; i++)
       {
         s[i] = this->integral_pt()->knot(ipt, i);
       }
       // Get the shape function
       solid_pshape(s, psi);
     }
References Global_Variables::Dim, oomph::FiniteElement::dim(), i, oomph::FiniteElement::integral_pt(), oomph::Integral::knot(), s, and oomph::PVDEquationsWithPressure< DIM >::solid_pshape().
Member Data Documentation
Incompressible
template<unsigned DIM> bool oomph::PVDEquationsWithPressure< DIM >::Incompressible protected
Boolean to determine whether the solid is incompressible or not.
Referenced by oomph::RefineablePVDEquationsWithPressure< DIM >::further_build(), oomph::PVDEquationsWithPressure< DIM >::is_incompressible(), oomph::PVDEquationsWithPressure< DIM >::set_compressible(), and oomph::PVDEquationsWithPressure< DIM >::set_incompressible().
The documentation for this class was generated from the following files:
solid_elements.h
solid_elements.cc