MercuryDPM: BoundaryHandler Class Reference
BoundaryHandler Class Reference final
Container to store pointers to all BaseBoundary objects.
#include <BoundaryHandler.h>
Public Member Functions
BoundaryHandler ()
Default constructor, it creates an empty BoundaryHandler.
BoundaryHandler (const BoundaryHandler &BH)
Constructor that copies all BaseBoundary it contains and sets the other variables to 0/nullptr.
BoundaryHandler & operator= (const BoundaryHandler &rhs)
Assignment operator, copies only the vector of BaseBoundary and sets the other variables to 0/nullptr.
~BoundaryHandler () final
Destructor, it destructs the BoundaryHandler and all BaseBoundary it contains.
void addObject (BaseBoundary *P) final
Adds a BaseBoundary to the BoundaryHandler.
void readAndAddObject (std::istream &is) final
Reads BaseBoundary into the BoundaryHandler from restart data.
void readOldObject (std::istream &is)
Reads a periodic boundary from old-style restart data.
std::string getName () const final
Returns the name of the handler, namely the string "BoundaryHandler".
void boundaryActionsBeforeTimeLoop ()
void setWriteVTK (bool writeVTK)
bool getWriteVTK () const
Public Member Functions inherited from BaseHandler< BaseBoundary >
BaseHandler ()
Default BaseHandler constructor, it creates an empty BaseHandler and assigns DPMBase_ to a null pointer.
BaseHandler (const BaseHandler< BaseBoundary > &BH)
Constructor that copies the objects of the given handler into itself and sets other variables to 0/nullptr.
virtual ~BaseHandler ()
Destructor, it destructs the BaseHandler and all Object it contains.
void copyContentsFromOtherHandler (const BaseHandler< BaseBoundary > &BH)
Function that copies the contents (vector of pointers, maxObject_, nextId_, DPMBase_) from one handler (container) to the other.
std::enable_if<!std::is_pointer< U >::value, U * >::type copyAndAddObject (const U &object)
Creates a copy of a Object and adds it to the BaseHandler.
std::enable_if< std::is_pointer< U >::value, U >::type copyAndAddObject (const U object)
Creates a copy of a Object and adds it to the BaseHandler.
std::enable_if<!std::is_pointer< U >::value, U * >::type copyAndAddGhostObject (const U &object)
Creates a copy of a Object and adds it to the BaseHandler. This is one locally for inserting mpi particles, they avoid the global check if the particle can actually be inserted, because the mpi domain already knows that is the case.
std::enable_if< std::is_pointer< U >::value, U >::type copyAndAddGhostObject (const U object)
Creates a copy of a Object and adds it to the BaseHandler. This is one locally for inserting mpi particles, they avoid the global check if the particle can actually be inserted, because the mpi domain already knows that is the case.
virtual void addExistingObject (BaseBoundary *O)
Adds an existing object to the BaseHandler without changing the id of the object.
virtual void addObject (BaseBoundary *object)
Adds a new Object to the BaseHandler.
virtual void addGhostObject (BaseBoundary *O)
Adds a new Object to the BaseHandler. called by the to avoid increasing the id.
void removeIf (const std::function< bool(BaseBoundary *)> cond)
virtual void removeObject (unsigned const int index)
Removes an Object from the BaseHandler.
virtual void removeObjects (std::vector< unsigned int > indices)
void removeLastObject ()
Removes the last Object from the BaseHandler.
virtual void clear ()
Empties the whole BaseHandler by removing all Objects and setting all other variables to 0.
void read (std::istream &is)
Reads all objects from restart data.
BaseBoundary * getObjectById (const unsigned int id)
Gets a pointer to the Object at the specified index in the BaseHandler.
std::vector< BaseBoundary * > getObjectsById (const unsigned int id)
Gets a vector of pointers to the objects with the specific id.
BaseBoundary * getObject (const unsigned int id)
Gets a pointer to the Object at the specified index in the BaseHandler.
const BaseBoundary * getObject (const unsigned int id) const
Gets a constant pointer to the Object at the specified index in the BaseHandler.
BaseBoundary * getLastObject ()
Gets a pointer to the last Object in this BaseHandler.
const BaseBoundary * getLastObject () const
Gets a constant pointer to the last Object in this BaseHandler.
virtual unsigned int getNumberOfObjects () const
Gets the number of real Object in this BaseHandler. (i.e. no mpi or periodic particles)
unsigned int getSize () const
Gets the size of the particleHandler (including mpi and periodic particles)
unsigned int getStorageCapacity () const
Gets the storage capacity of this BaseHandler.
void setStorageCapacity (const unsigned int N)
Sets the storage capacity of this BaseHandler.
void resize (const unsigned int N, const BaseBoundary &obj)
Resizes the container to contain N elements.
const std::vector< BaseBoundary * >::const_iterator begin () const
Gets the begin of the const_iterator over all Object in this BaseHandler.
const std::vector< BaseBoundary * >::iterator begin ()
Gets the begin of the iterator over all BaseBoundary in this BaseHandler.
const std::vector< BaseBoundary * >::const_iterator end () const
Gets the end of the const_iterator over all BaseBoundary in this BaseHandler.
const std::vector< BaseBoundary * >::iterator end ()
Gets the end of the iterator over all BaseBoundary in this BaseHandler.
void setDPMBase (DPMBase *DPMBase)
Sets the problem that is solved using this handler.
void setId (BaseBoundary *object, unsigned int id)
void increaseId ()
unsigned int getNextId ()
void setNextId (unsigned int id)
DPMBase * getDPMBase ()
Gets the problem that is solved using this handler.
DPMBase * getDPMBase () const
Gets the problem that is solved using this handler and does not change the class.
virtual void writeVTK () const
now empty function for writing VTK files.
unsigned getNextGroupId ()
Should be called each time you assign a groupId. Returns the value of nextGroupId_ and increases nextGroupId_ by one.
Static Public Member Functions
static BaseBoundary * createObject (const std::string &type)
Private Attributes
bool writeVTK_
Additional Inherited Members
Protected Attributes inherited from BaseHandler< BaseBoundary >
std::vector< BaseBoundary * > objects_
The actual list of Object pointers.
Detailed Description
Container to store pointers to all BaseBoundary objects.
The BoundaryHandler is a container to store all BaseBoundary. It is implemented by a vector of pointers to BaseBoundary.
Constructor & Destructor Documentation
BoundaryHandler() [1/2]
BoundaryHandler::BoundaryHandler ()
Default constructor, it creates an empty BoundaryHandler.
Constructor of the BoundaryHandler class. It creates and empty BoundaryHandler.
 {
     writeVTK_ = false;
     logger(DEBUG, "BoundaryHandler::BoundaryHandler() finished");
 }
References DEBUG, logger, and writeVTK_.
BoundaryHandler() [2/2]
BoundaryHandler::BoundaryHandler (const BoundaryHandler & BH)
Constructor that copies all BaseBoundary it contains and sets the other variables to 0/nullptr.
Parameters
[in] BH The BoundaryHandler that has to be copied.
This is not a copy constructor! It just copies all BaseBoundary from the other handler into this handler, and clears all other variables.
         : BaseHandler<BaseBoundary>()
 {
     writeVTK_ = BH.writeVTK_;
     copyContentsFromOtherHandler(BH);
     logger(DEBUG, "BoundaryHandler::BoundaryHandler(const BoundaryHandler &BH) finished");
 }
References BaseHandler< BaseBoundary >::copyContentsFromOtherHandler(), DEBUG, logger, and writeVTK_.
~BoundaryHandler()
BoundaryHandler::~BoundaryHandler () final
Destructor, it destructs the BoundaryHandler and all BaseBoundary it contains.
Default destructor. Note that the delete for all boundaries is done in the BaseHandler.
 {
     logger(DEBUG, "BoundaryHandler::~BoundaryHandler() finished");
 }
References DEBUG, and logger.
Member Function Documentation
addObject()
void BoundaryHandler::addObject (BaseBoundary * P) final
Adds a BaseBoundary to the BoundaryHandler.
Parameters
[in] P A pointer to the BaseBoundary (or derived class) that has to be added. Add the object and tell the object that this is his handler.
 {
     //Puts the boundary in the Boundary list
     BaseHandler<BaseBoundary>::addObject(P);
     //set the handler pointer
     P->setHandler(this);
 #ifdef MERCURYDPM_USE_MPI
     //Different manner of treating periodic boundaries in MPI: hence there is a periodicBoundaryHandler
     BasePeriodicBoundary* upcast = dynamic_cast<BasePeriodicBoundary*>(P);
     if (upcast != nullptr)
     {
         getDPMBase()->periodicBoundaryHandler.addObject(upcast);
     }
 #endif
 }
References PeriodicBoundaryHandler::addObject(), BaseHandler< T >::addObject(), BaseHandler< BaseBoundary >::getDPMBase(), Global_Physical_Variables::P, and DPMBase::periodicBoundaryHandler.
Referenced by readAndAddObject(), Chutebelt::setupInitialConditions(), and InsertionBoundarySelfTest::setupInitialConditions().
boundaryActionsBeforeTimeLoop()
void BoundaryHandler::boundaryActionsBeforeTimeLoop ()
 {
     for (BaseBoundary* b : objects_)
     {
         b->actionsBeforeTimeLoop();
     }
 }
References b, and BaseHandler< BaseBoundary >::objects_.
Referenced by DPMBase::initialiseSolve().
createObject()
BaseBoundary * BoundaryHandler::createObject (const std::string & type) static
 {
     //Note that compare returns 0 if the strings are the same.
     if (type == "AngledPeriodicBoundary")
     {
         return new AngledPeriodicBoundary;
     }
     else if (type == "ChuteInsertionBoundary")
     {
         return new ChuteInsertionBoundary;
     }
     else if (type == "CubeInsertionBoundary")
     {
         return new CubeInsertionBoundary;
     }
     else if (type == "CubeDeletionBoundary")
     {
         return new CubeDeletionBoundary;
     }
     else if (type == "CircularPeriodicBoundary")
     {
         return new CircularPeriodicBoundary;
     }
     else if (type == "DeletionBoundary")
     {
         return new DeletionBoundary;
     }
     else if (type == "HopperInsertionBoundary")
     {
         return new HopperInsertionBoundary;
     }
     else if (type == "PeriodicBoundary")
     {
         return new PeriodicBoundary;
     }
     else if (type == "ConstantMassFlowMaserBoundary" || type == "MaserBoundary")
     {
         return new ConstantMassFlowMaserBoundary;
     }
     else if (type == "SubcriticalMaserBoundary")
     {
         return new SubcriticalMaserBoundary;
     }
     else if (type == "SubcriticalMaserBoundaryTEST")
     {
         return new SubcriticalMaserBoundaryTEST;
     }
     else if (type == "LeesEdwardsBoundary")
     {
         return new LeesEdwardsBoundary;
     }
     else if (type == "MPIDomainBoundary")
     {
         return new PeriodicBoundary;
     }
     else if (type == "FluxBoundary")
     {
         return new FluxBoundary;
     }
     else if (type == "HeaterBoundary")
     {
         return new HeaterBoundary;
     }
     else if (type == "StressStrainControlBoundary")
     {
         return new StressStrainControlBoundary;
     }
     else if (type == "BaseClusterInsertionBoundary")
     {
         return new BaseClusterInsertionBoundary;
     }
     else if (type == "RandomClusterInsertionBoundary")
     {
         return new RandomClusterInsertionBoundary;
     }
     else if (type == "FixedClusterInsertionBoundary")
     {
         return new FixedClusterInsertionBoundary;
     }
     else if (type == "DropletBoundary")
     {
         return new DropletBoundary;
     }
     else if (type == "normal") //for backward compatibility (before svnversion ~2360)
     {
         return new PeriodicBoundary;
     }
     else
     {
         logger(WARN, "Boundary type: % not understood in restart file.", type);
         return nullptr;
     }
 }
References logger, compute_granudrum_aor::type, and WARN.
Referenced by readAndAddObject().
getName()
std::string BoundaryHandler::getName () const final virtual
Returns the name of the handler, namely the string "BoundaryHandler".
Returns
The string "BoundaryHandler"
Implements BaseHandler< BaseBoundary >.
 {
     return "BoundaryHandler";
 }
getWriteVTK()
bool BoundaryHandler::getWriteVTK () const inline
 { return writeVTK_; }
References writeVTK_.
Referenced by DPMBase::initialiseVTK(), DPMBase::write(), and DPMBase::writeVTKFiles().
operator=()
BoundaryHandler & BoundaryHandler::operator= (const BoundaryHandler & rhs)
Assignment operator, copies only the vector of BaseBoundary and sets the other variables to 0/nullptr.
Parameters
[in] rhs The BoundaryHandler on the right hand side of the assignment.
This is not a copy assignment operator! It just copies all BaseBoundary from the other handler into this handler, and clears all other variables.
 {
     if (this != &rhs)
     {
         clear();
         copyContentsFromOtherHandler(rhs);
     }
     logger(DEBUG, "BoundaryHandler BoundaryHandler::operator =(const BoundaryHandler& rhs)");
     return *this;
 }
References BaseHandler< BaseBoundary >::clear(), BaseHandler< BaseBoundary >::copyContentsFromOtherHandler(), DEBUG, and logger.
readAndAddObject()
void BoundaryHandler::readAndAddObject (std::istream & is) final virtual
Reads BaseBoundary into the BoundaryHandler from restart data.
Parameters
[in] is The input stream from which the information is read. First read the type of boundary, then compare the type to all existing types. When the correct type is found, read it with the >> operator, copy it and add it to the handler.
Implements BaseHandler< BaseBoundary >.
 {
     //Note that compare returns 0 if the strings are the same.
     std::string type;
     is >> type;
     logger(VERBOSE, "BoundaryHandler::readAndAddObject(is): restarting a boundary of type %.", type);
     if (type == "normal")
     {
         readOldObject(is);
     }
     else
     {
         BaseBoundary* boundary = createObject(type);
         if (boundary == nullptr)
         {
             std::string line;
             getline(is, line);
             logger(WARN, "This boundary could not be read and is ignored:\n%%", type, line);
             return;
         }
         boundary->setHandler(this);
         is >> *boundary;
         addObject(boundary);
     }
 }
References addObject(), createObject(), calibrate::line, logger, readOldObject(), BaseBoundary::setHandler(), oomph::Global_string_for_annotation::string(), compute_granudrum_aor::type, VERBOSE, and WARN.
Referenced by DPMBase::read().
readOldObject()
void BoundaryHandler::readOldObject (std::istream & is)
Reads a periodic boundary from old-style restart data.
Parameters
[in] is The input stream from which the information is read. Get the normal, position left and position right for a periodic boundary from the stream is, and construct a new periodic boundary from it. The boundaries that are written like that are outdated, this function is there for backward compatability.
 {
     //read in next line
     std::stringstream line;
     helpers::getLineFromStringStream(is, line);
     std::string dummy;
     Vec3D normal;
     Mdouble positionLeft, positionRight;
     PeriodicBoundary periodicBoundary;
     line >> normal >> dummy >> positionLeft >> dummy >> positionRight;
     periodicBoundary.set(normal, positionLeft, positionRight);
     copyAndAddObject(periodicBoundary);
 }
References BaseHandler< BaseBoundary >::copyAndAddObject(), helpers::getLineFromStringStream(), calibrate::line, WallFunction::normal(), PeriodicBoundary::set(), and oomph::Global_string_for_annotation::string().
Referenced by readAndAddObject().
setWriteVTK()
void BoundaryHandler::setWriteVTK (bool writeVTK) inline
 { writeVTK_ = writeVTK; }
References BaseHandler< BaseBoundary >::writeVTK(), and writeVTK_.
Referenced by main(), DPMBase::read(), NozzleDemo::setupInitialConditions(), and NozzleSelfTest::setupInitialConditions().
Member Data Documentation
writeVTK_
bool BoundaryHandler::writeVTK_ private
Referenced by BoundaryHandler(), getWriteVTK(), and setWriteVTK().
The documentation for this class was generated from the following files:
BoundaryHandler.h
BoundaryHandler.cc