MercuryDPM: oomph::AlgebraicRefineableQuarterTubeMesh< ELEMENT > Class Template Reference
oomph::AlgebraicRefineableQuarterTubeMesh< ELEMENT > Class Template Reference
AlgebraicMesh version of RefineableQuarterTubeMesh.
#include <quarter_tube_mesh.template.h>
Public Member Functions
AlgebraicRefineableQuarterTubeMesh (GeomObject *wall_pt, const Vector< double > &xi_lo, const double &fract_mid, const Vector< double > &xi_hi, const unsigned &nlayer, const double centre_box_size=1.0, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
unsigned self_test ()
Run self-test for algebraic mesh – return 0/1 for OK/failure.
QuarterTubeDomain::AxialSpacingFctPt & axial_spacing_fct_pt ()
void node_update (const bool &update_all_solid_nodes=false)
void algebraic_node_update (const unsigned &t, AlgebraicNode *&node_pt)
void update_node_update (AlgebraicNode *&node_pt)
Public Member Functions inherited from oomph::AlgebraicMesh
AlgebraicMesh ()
AlgebraicMesh (const AlgebraicMesh &)=delete
Broken copy constructor.
~AlgebraicMesh ()
Broken assignment operator.
AlgebraicNode * node_pt (const unsigned long &n)
Return a pointer to the n-th global AlgebraicNode.
unsigned self_test ()
Self test: check consistentency of multiple node updates.
void add_geom_object_list_pt (GeomObject *geom_object_pt)
unsigned ngeom_object_list_pt ()
Return number of geometric objects associated with AlgebraicMesh.
GeomObject * geom_object_list_pt (const unsigned &i)
Access function to the ith GeomObject.
Public Member Functions inherited from oomph::Mesh
Mesh ()
Default constructor.
Mesh (const Vector< Mesh * > &sub_mesh_pt)
void merge_meshes (const Vector< Mesh * > &sub_mesh_pt)
virtual void reset_boundary_element_info (Vector< unsigned > &ntmp_boundary_elements, Vector< Vector< unsigned >> &ntmp_boundary_elements_in_region, Vector< FiniteElement * > &deleted_elements)
Virtual function to perform the reset boundary elements info rutines.
template<class BULK_ELEMENT >
void doc_boundary_coordinates (const unsigned &b, std::ofstream &the_file)
virtual void scale_mesh (const double &factor)
Mesh (const Mesh &dummy)=delete
Broken copy constructor.
void operator= (const Mesh &)=delete
Broken assignment operator.
virtual ~Mesh ()
Virtual Destructor to clean up all memory.
void flush_element_and_node_storage ()
void flush_element_storage ()
void flush_node_storage ()
Node *& node_pt (const unsigned long &n)
Return pointer to global node n.
Node * node_pt (const unsigned long &n) const
Return pointer to global node n (const version)
GeneralisedElement *& element_pt (const unsigned long &e)
Return pointer to element e.
GeneralisedElement * element_pt (const unsigned long &e) const
Return pointer to element e (const version)
const Vector< GeneralisedElement * > & element_pt () const
Return reference to the Vector of elements.
Vector< GeneralisedElement * > & element_pt ()
Return reference to the Vector of elements.
FiniteElement * finite_element_pt (const unsigned &e) const
Node *& boundary_node_pt (const unsigned &b, const unsigned &n)
Return pointer to node n on boundary b.
Node * boundary_node_pt (const unsigned &b, const unsigned &n) const
Return pointer to node n on boundary b.
void set_nboundary (const unsigned &nbound)
Set the number of boundaries in the mesh.
void remove_boundary_nodes ()
Clear all pointers to boundary nodes.
void remove_boundary_nodes (const unsigned &b)
void remove_boundary_node (const unsigned &b, Node *const &node_pt)
Remove a node from the boundary b.
void add_boundary_node (const unsigned &b, Node *const &node_pt)
Add a (pointer to) a node to the b-th boundary.
void copy_boundary_node_data_from_nodes ()
bool boundary_coordinate_exists (const unsigned &i) const
Indicate whether the i-th boundary has an intrinsic coordinate.
unsigned long nelement () const
Return number of elements in the mesh.
unsigned long nnode () const
Return number of nodes in the mesh.
unsigned ndof_types () const
Return number of dof types in mesh.
unsigned elemental_dimension () const
Return number of elemental dimension in mesh.
unsigned nodal_dimension () const
Return number of nodal dimension in mesh.
void add_node_pt (Node *const &node_pt)
Add a (pointer to a) node to the mesh.
void add_element_pt (GeneralisedElement *const &element_pt)
Add a (pointer to) an element to the mesh.
virtual void reorder_nodes (const bool &use_old_ordering=true)
virtual void get_node_reordering (Vector< Node * > &reordering, const bool &use_old_ordering=true) const
template<class BULK_ELEMENT , template< class > class FACE_ELEMENT>
void build_face_mesh (const unsigned &b, Mesh *const &face_mesh_pt)
unsigned self_test ()
Self-test: Check elements and nodes. Return 0 for OK.
void max_and_min_element_size (double &max_size, double &min_size)
double total_size ()
void check_inverted_elements (bool &mesh_has_inverted_elements, std::ofstream &inverted_element_file)
void check_inverted_elements (bool &mesh_has_inverted_elements)
unsigned check_for_repeated_nodes (const double &epsilon=1.0e-12)
Vector< Node * > prune_dead_nodes ()
unsigned nboundary () const
Return number of boundaries.
unsigned long nboundary_node (const unsigned &ibound) const
Return number of nodes on a particular boundary.
FiniteElement * boundary_element_pt (const unsigned &b, const unsigned &e) const
Return pointer to e-th finite element on boundary b.
Node * get_some_non_boundary_node () const
unsigned nboundary_element (const unsigned &b) const
Return number of finite elements that are adjacent to boundary b.
int face_index_at_boundary (const unsigned &b, const unsigned &e) const
virtual void dump (std::ofstream &dump_file, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
void dump (const std::string &dump_file_name, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
virtual void read (std::ifstream &restart_file)
Read solution from restart file.
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
void output (std::ostream &outfile)
Output for all elements.
void output (std::ostream &outfile, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output (FILE *file_pt)
Output for all elements (C-style output)
void output (FILE *file_pt, const unsigned &nplot)
Output at f(n_plot) points in each element (C-style output)
void output (const std::string &output_filename)
Output for all elements.
void output (const std::string &output_filename, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt)
Output a given Vector function at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt)
void output_boundaries (std::ostream &outfile)
Output the nodes on the boundaries (into separate tecplot zones)
void output_boundaries (const std::string &output_filename)
void assign_initial_values_impulsive ()
Assign initial values for an impulsive start.
void shift_time_values ()
void calculate_predictions ()
void set_nodal_and_elemental_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
virtual void set_mesh_level_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void set_consistent_pinned_values_for_continuation (ContinuationStorageScheme *const &continuation_stepper_pt)
Set consistent values for pinned data in continuation.
bool does_pointer_correspond_to_mesh_data (double *const &parameter_pt)
Does the double pointer correspond to any mesh data.
void set_nodal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
Set the timestepper associated with the nodal data in the mesh.
void set_elemental_internal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
virtual void compute_norm (double &norm)
virtual void compute_norm (Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Returns the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
bool is_mesh_distributed () const
Boolean to indicate if Mesh has been distributed.
OomphCommunicator * communicator_pt () const
void delete_all_external_storage ()
Wipe the storage for all externally-based elements.
Public Member Functions inherited from oomph::RefineableQuarterTubeMesh< ELEMENT >
RefineableQuarterTubeMesh (GeomObject *wall_pt, const Vector< double > &xi_lo, const double &fract_mid, const Vector< double > &xi_hi, const unsigned &nlayer, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
virtual ~RefineableQuarterTubeMesh ()
Destructor: empty.
Public Member Functions inherited from oomph::QuarterTubeMesh< ELEMENT >
QuarterTubeMesh (GeomObject *wall_pt, const Vector< double > &xi_lo, const double &fract_mid, const Vector< double > &xi_hi, const unsigned &nlayer, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
virtual ~QuarterTubeMesh ()
Destructor: empty.
GeomObject *& wall_pt ()
Access function to GeomObject representing wall.
QuarterTubeDomain * domain_pt ()
Access function to domain.
QuarterTubeDomain::BLSquashFctPt & bl_squash_fct_pt ()
QuarterTubeDomain * domain_pt () const
Access function to underlying domain.
Public Member Functions inherited from oomph::BrickMeshBase
BrickMeshBase ()
Constructor (empty)
BrickMeshBase (const BrickMeshBase &)=delete
Broken copy constructor.
virtual ~BrickMeshBase ()
Broken assignment operator.
void setup_boundary_element_info ()
void setup_boundary_element_info (std::ostream &outfile)
Public Member Functions inherited from oomph::RefineableBrickMesh< ELEMENT >
RefineableBrickMesh ()
Constructor: Setup static octree data.
RefineableBrickMesh (const RefineableBrickMesh &dummy)=delete
Broken copy constructor.
void operator= (const RefineableBrickMesh &)=delete
Broken assignment operator.
virtual ~RefineableBrickMesh ()
Destructor:
virtual void setup_tree_forest ()
void setup_octree_forest ()
Do what it says...
Public Member Functions inherited from oomph::TreeBasedRefineableMesh< ELEMENT >
TreeBasedRefineableMesh ()
Constructor, call the constructor of the base class.
TreeBasedRefineableMesh (const TreeBasedRefineableMesh &dummy)=delete
Broken copy constructor.
virtual ~TreeBasedRefineableMesh ()
Empty virtual destructor.
Public Member Functions inherited from oomph::TreeBasedRefineableMeshBase
TreeBasedRefineableMeshBase ()
Constructor.
TreeBasedRefineableMeshBase (const TreeBasedRefineableMeshBase &dummy)=delete
Broken copy constructor.
void operator= (const TreeBasedRefineableMeshBase &)=delete
Broken assignment operator.
virtual ~TreeBasedRefineableMeshBase ()
Empty Destructor:
void adapt (const Vector< double > &elemental_error)
void p_adapt (const Vector< double > &elemental_error)
void refine_uniformly (DocInfo &doc_info)
Refine mesh uniformly and doc process.
void refine_uniformly ()
Refine mesh uniformly.
void p_refine_uniformly (DocInfo &doc_info)
p-refine mesh uniformly and doc process
void p_refine_uniformly ()
p-refine mesh uniformly
unsigned unrefine_uniformly ()
void p_unrefine_uniformly (DocInfo &doc_info)
p-unrefine mesh uniformly
TreeForest * forest_pt ()
Return pointer to the Forest represenation of the mesh.
void doc_adaptivity_targets (std::ostream &outfile)
Doc the targets for mesh adaptation.
unsigned & max_refinement_level ()
Access fct for max. permissible refinement level (relative to base mesh)
unsigned & min_refinement_level ()
Access fct for min. permissible refinement level (relative to base mesh)
unsigned & max_p_refinement_level ()
unsigned & min_p_refinement_level ()
virtual void adapt_mesh (DocInfo &doc_info)
virtual void adapt_mesh ()
void p_adapt_mesh (DocInfo &doc_info)
void p_adapt_mesh ()
virtual void refine_selected_elements (const Vector< unsigned > &elements_to_be_refined)
virtual void refine_selected_elements (const Vector< RefineableElement * > &elements_to_be_refined)
void p_refine_selected_elements (const Vector< unsigned > &elements_to_be_refined)
p-refine mesh by refining the elements identified by their numbers.
void p_refine_selected_elements (const Vector< PRefineableElement * > &elements_to_be_refined_pt)
p-refine mesh by refining the elements identified by their pointers.
virtual void refine_base_mesh_as_in_reference_mesh (TreeBasedRefineableMeshBase *const &ref_mesh_pt)
Refine to same degree as the reference mesh.
virtual bool refine_base_mesh_as_in_reference_mesh_minus_one (TreeBasedRefineableMeshBase *const &ref_mesh_pt)
virtual void refine_as_in_reference_mesh (TreeBasedRefineableMeshBase *const &ref_mesh_pt)
virtual void get_refinement_levels (unsigned &min_refinement_level, unsigned &max_refinement_level)
Get max/min refinement levels in mesh.
virtual void get_elements_at_refinement_level (unsigned &refinement_level, Vector< RefineableElement * > &level_elements)
virtual void get_refinement_pattern (Vector< Vector< unsigned >> &to_be_refined)
void refine_base_mesh (Vector< Vector< unsigned >> &to_be_refined)
Refine base mesh according to specified refinement pattern.
virtual void refine (std::ifstream &restart_file)
Refine mesh according to refinement pattern in restart file.
virtual void dump_refinement (std::ostream &outfile)
Dump refinement pattern to allow for rebuild.
virtual void read_refinement (std::ifstream &restart_file, Vector< Vector< unsigned >> &to_be_refined)
Read refinement pattern to allow for rebuild.
unsigned uniform_refinement_level_when_pruned () const
unsigned & uniform_refinement_level_when_pruned ()
Level to which the mesh was uniformly refined when it was pruned.
Public Member Functions inherited from oomph::RefineableMeshBase
bool adapt_flag ()
RefineableMeshBase ()
RefineableMeshBase (const RefineableMeshBase &dummy)=delete
Broken copy constructor.
void operator= (const RefineableMeshBase &)=delete
Broken assignment operator.
virtual ~RefineableMeshBase ()
Empty Destructor:
unsigned nrefined ()
Access fct for number of elements that were refined.
unsigned nunrefined ()
Access fct for number of elements that were unrefined.
unsigned & nrefinement_overruled ()
unsigned & max_keep_unrefined ()
ErrorEstimator *& spatial_error_estimator_pt ()
Access to spatial error estimator.
ErrorEstimator * spatial_error_estimator_pt () const
Access to spatial error estimator (const version.
double & min_permitted_error ()
double & max_permitted_error ()
double & min_error ()
double & max_error ()
DocInfo *& doc_info_pt ()
Access fct for pointer to DocInfo.
void enable_adaptation ()
Enable adaptation.
void disable_adaptation ()
Disable adaptation.
void enable_p_adaptation ()
Enable adaptation.
void disable_p_adaptation ()
Disable adaptation.
void enable_additional_synchronisation_of_hanging_nodes ()
Enable additional synchronisation of hanging nodes.
void disable_additional_synchronisation_of_hanging_nodes ()
Disable additional synchronisation of hanging nodes.
bool is_adaptation_enabled () const
Return whether the mesh is to be adapted.
bool is_p_adaptation_enabled () const
Return whether the mesh is to be adapted.
bool is_additional_synchronisation_of_hanging_nodes_disabled () const
Return whether additional synchronisation is enabled.
DocInfo doc_info ()
Access fct for DocInfo.
void p_unrefine_uniformly (DocInfo &doc_info)
p-unrefine mesh uniformly
Private Types
enum { Central_region , Lower_right_region , Upper_left_region }
Remesh function ids.
Private Member Functions
void node_update_central_region (const unsigned &t, AlgebraicNode *&node_pt)
void node_update_lower_right_region (const unsigned &t, AlgebraicNode *&node_pt)
void node_update_upper_left_region (const unsigned &t, AlgebraicNode *&node_pt)
void setup_algebraic_node_update ()
Setup algebraic update operation for all nodes.
void update_node_update_in_region (AlgebraicNode *&node_pt, int &region_id)
Private Attributes
double Centre_box_size
Size of centre box.
double Lambda_x
Fractional width of central region.
double Lambda_y
Fractional height of central region.
Additional Inherited Members
Public Types inherited from oomph::Mesh
typedef void(FiniteElement::* SteadyExactSolutionFctPt) (const Vector< double > &x, Vector< double > &soln)
typedef void(FiniteElement::* UnsteadyExactSolutionFctPt) (const double &time, const Vector< double > &x, Vector< double > &soln)
Static Public Attributes inherited from oomph::Mesh
static Steady< 0 > Default_TimeStepper
The Steady Timestepper.
static bool Suppress_warning_about_empty_mesh_level_time_stepper_function
Static boolean flag to control warning about mesh level timesteppers.
Protected Member Functions inherited from oomph::Mesh
unsigned long assign_global_eqn_numbers (Vector< double * > &Dof_pt)
Assign (global) equation numbers to the nodes.
void describe_dofs (std::ostream &out, const std::string &current_string) const
void describe_local_dofs (std::ostream &out, const std::string &current_string) const
void assign_local_eqn_numbers (const bool &store_local_dof_pt)
Assign local equation numbers in all elements.
void convert_to_boundary_node (Node *&node_pt, const Vector< FiniteElement * > &finite_element_pt)
void convert_to_boundary_node (Node *&node_pt)
Protected Member Functions inherited from oomph::TreeBasedRefineableMeshBase
void complete_hanging_nodes (const int &ncont_interpolated_values)
Complete the hanging node scheme recursively.
void complete_hanging_nodes_recursively (Node *&nod_pt, Vector< Node * > &master_nodes, Vector< double > &hang_weights, const int &ival)
Auxiliary routine for recursive hanging node completion.
Protected Attributes inherited from oomph::Mesh
Vector< Vector< Node * > > Boundary_node_pt
bool Lookup_for_elements_next_boundary_is_setup
Vector< Vector< FiniteElement * > > Boundary_element_pt
Vector< Vector< int > > Face_index_at_boundary
Vector< Node * > Node_pt
Vector of pointers to nodes.
Vector< GeneralisedElement * > Element_pt
Vector of pointers to generalised elements.
std::vector< bool > Boundary_coordinate_exists
Protected Attributes inherited from oomph::QuarterTubeMesh< ELEMENT >
QuarterTubeDomain * Domain_pt
Pointer to domain.
GeomObject * Wall_pt
Pointer to the geometric object that represents the curved wall.
Vector< double > Xi_lo
Lower limits for the coordinates along the wall.
double Fract_mid
Fraction along wall where outer ring is to be divided.
Vector< double > Xi_hi
Upper limits for the coordinates along the wall.
Protected Attributes inherited from oomph::TreeBasedRefineableMeshBase
unsigned Uniform_refinement_level_when_pruned
Level to which the mesh was uniformly refined when it was pruned.
unsigned Max_refinement_level
Max. permissible refinement level (relative to base mesh)
unsigned Min_refinement_level
Min. permissible refinement level (relative to base mesh)
unsigned Max_p_refinement_level
Max. permissible p-refinement level (relative to base mesh)
unsigned Min_p_refinement_level
Min. permissible p-refinement level (relative to base mesh)
TreeForest * Forest_pt
Forest representation of the mesh.
Protected Attributes inherited from oomph::RefineableMeshBase
ErrorEstimator * Spatial_error_estimator_pt
Pointer to spatial error estimator.
double Max_permitted_error
Max. error (i.e. split elements if their error is larger)
double Min_permitted_error
Min. error (i.e. (try to) merge elements if their error is smaller)
double Min_error
Min.actual error.
double Max_error
Max. actual error.
unsigned Nrefined
Stats: Number of elements that were refined.
unsigned Nunrefined
Stats: Number of elements that were unrefined.
bool Adapt_flag
Flag that requests adaptation.
bool P_adapt_flag
Flag that requests p-adaptation.
bool Additional_synchronisation_of_hanging_nodes_not_required
Flag that disables additional synchronisation of hanging nodes.
DocInfo * Doc_info_pt
Pointer to DocInfo.
unsigned Max_keep_unrefined
unsigned Nrefinement_overruled
Detailed Description
template<class ELEMENT>
class oomph::AlgebraicRefineableQuarterTubeMesh< ELEMENT >
AlgebraicMesh version of RefineableQuarterTubeMesh.
Algebraic 3D quarter tube mesh class.
The mesh boundaries are numbered as follows:
Boundary 0: "Inflow" cross section; located along the line parametrised by \(\xi_0 = \xi_0^{lo} \) on the geometric object that specifies the wall.
Boundary 1: Plane x=0
Boundary 2: Plane y=0
Boundary 3: The curved wall - specified by the GeomObject passed to the mesh constructor.
Boundary 4: "Outflow" cross section; located along the line parametrised by \(\xi_0 = \xi_0^{hi} \) on the geometric object that specifies the wall. Algebraic version of RefineableQuarterTubeMesh
Cross section through mesh looking along tube.........
                 ---___
                |      ---____
                |              -   BOUNDARY 3
                |                /
                |  [Region 2]   /  |
                |              /     |
                | N           /        |
                | |_ E       /          |
  BOUNDARY 1    |------------            |
                |            |            |
                | [Region 0] | [Region 1] |  ^
                |            |            | / \  direction of
                | N          |    N       |  |   2nd Lagrangian
                | |_ E       |    |_ E    |  |   coordinate
                |____________|____________|  |   along wall GeomObject
                      BOUNDARY 2
The Domain is built of slices each consisting of three MacroElements as sketched. The local coordinates are such that the (E)astern direction coincides with the positive s_0 direction, while the (N)orther direction coincides with the positive s_1 direction. The positive s_2 direction points down the tube.
Elements need to be derived from AlgebraicElementBase. In addition to the refinement procedures available for the RefineableQuarterTubeMesh which forms the basis for this mesh, three algebraic node update functions are implemented for the nodes in the three regions defined by the Domain MacroElements. Note: it is assumed the cross section down the tube is uniform when setup_algebraic_node_update() is called.
Member Enumeration Documentation
anonymous enum
template<class ELEMENT > anonymous enum private
Remesh function ids.
Enumerator
Central_region
Lower_right_region
Upper_left_region
     {
       Central_region,
       Lower_right_region,
       Upper_left_region
     };
Constructor & Destructor Documentation
AlgebraicRefineableQuarterTubeMesh()
template<class ELEMENT > oomph::AlgebraicRefineableQuarterTubeMesh< ELEMENT >::AlgebraicRefineableQuarterTubeMesh (GeomObject * wall_pt, const Vector< double > & xi_lo, const double & fract_mid, const Vector< double > & xi_hi, const unsigned & nlayer, const double centre_box_size = 1.0, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper) inline
Constructor: Pass pointer to geometric object, start and end coordinates of the geometric object and the fraction along the 2nd Lagrangian coordinate at which the dividing line between region 1 and region 2 is to be placed, and timestepper (defaults to (Steady) default timestepper defined in Mesh). Sets up the refineable mesh (by calling the constructor for the underlying RefineableQuarterTubeMesh).
       : QuarterTubeMesh<ELEMENT>(
           wall_pt, xi_lo, fract_mid, xi_hi, nlayer, time_stepper_pt),
         RefineableQuarterTubeMesh<ELEMENT>(
           wall_pt, xi_lo, fract_mid, xi_hi, nlayer, time_stepper_pt),
         Centre_box_size(centre_box_size)
     {
 #ifdef PARANOID
       ELEMENT* el_pt = new ELEMENT;
       if (dynamic_cast<AlgebraicElementBase*>(el_pt) == 0)
       {
         std::ostringstream error_message;
         error_message << "Base class for ELEMENT in "
                       << "AlgebraicRefineableQuarterTubeMesh needs"
                       << "to be of type AlgebraicElement!\n";
         error_message << "Whereas it is: typeid(el_pt).name()"
                       << typeid(el_pt).name() << std::endl;
         std::string function_name = " AlgebraicRefineableQuarterTubeMesh::\n";
         function_name += "AlgebraicRefineableQuarterTubeMesh()";
         throw OomphLibError(error_message.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
       delete el_pt;
 #endif
       // Add the geometric object to the list associated with this AlgebraicMesh
       AlgebraicMesh::add_geom_object_list_pt(wall_pt);
       // Setup algebraic node update operations
       setup_algebraic_node_update();
       // Ensure nodes are in their default position
       node_update();
     }
References oomph::AlgebraicMesh::add_geom_object_list_pt(), plotDoE::name, oomph::AlgebraicRefineableQuarterTubeMesh< ELEMENT >::node_update(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::AlgebraicRefineableQuarterTubeMesh< ELEMENT >::setup_algebraic_node_update(), oomph::Global_string_for_annotation::string(), and oomph::QuarterTubeMesh< ELEMENT >::wall_pt().
Member Function Documentation
algebraic_node_update()
template<class ELEMENT > void oomph::AlgebraicRefineableQuarterTubeMesh< ELEMENT >::algebraic_node_update (const unsigned & t, AlgebraicNode *& node_pt) inline virtual
Implement the algebraic node update function for a node at time level t (t=0: present; t>0: previous): Update with the node's first (default) update function.
Implements oomph::AlgebraicMesh.
     {
       // Update with the update function for the node's first (default)
       // node update fct
       unsigned id = node_pt->node_update_fct_id();
       switch (id)
       {
         case Central_region:
           // Central region
           node_update_central_region(t, node_pt);
           break;
         case Lower_right_region:
           // Lower right region
           node_update_lower_right_region(t, node_pt);
           break;
         case Upper_left_region:
           // Upper left region
           node_update_upper_left_region(t, node_pt);
           break;
         default:
           std::ostringstream error_message;
           error_message << "The node update fct id is " << id
                         << ", but it should only be one of " << Central_region
                         << ", " << Lower_right_region << " or "
                         << Upper_left_region << std::endl;
           std::string function_name = " AlgebraicRefineableQuarterTubeMesh::";
           function_name += "algebraic_node_update()";
           throw OomphLibError(error_message.str(),
                               OOMPH_CURRENT_FUNCTION,
                               OOMPH_EXCEPTION_LOCATION);
       }
     }
References oomph::AlgebraicRefineableQuarterTubeMesh< ELEMENT >::Central_region, oomph::AlgebraicRefineableQuarterTubeMesh< ELEMENT >::Lower_right_region, oomph::AlgebraicMesh::node_pt(), oomph::AlgebraicRefineableQuarterTubeMesh< ELEMENT >::node_update_central_region(), oomph::AlgebraicNode::node_update_fct_id(), oomph::AlgebraicRefineableQuarterTubeMesh< ELEMENT >::node_update_lower_right_region(), oomph::AlgebraicRefineableQuarterTubeMesh< ELEMENT >::node_update_upper_left_region(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::Global_string_for_annotation::string(), plotPSD::t, and oomph::AlgebraicRefineableQuarterTubeMesh< ELEMENT >::Upper_left_region.
axial_spacing_fct_pt()
template<class ELEMENT > QuarterTubeDomain::AxialSpacingFctPt& oomph::AlgebraicRefineableQuarterTubeMesh< ELEMENT >::axial_spacing_fct_pt () inline virtual
Broken version of the QuarterTubeDomain function Function is broken because axial spacing isn't implemented yet for the Algebraic version of the RefineableQuarterTubeMesh. Note: this function must be used BEFORE algebraic_node_update(...) is called.
Reimplemented from oomph::QuarterTubeMesh< ELEMENT >.
     {
       std::ostringstream error_message;
       error_message << "AxialSpacingFctPt has not been implemented "
                     << "for the AlgebraicRefineableQuarterTubeMesh\n";
       std::string function_name =
         " AlgebraicRefineableQuarterTubeMesh::AxialSpacingFctPt()";
       throw OomphLibError(
         error_message.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
       return this->Domain_pt->axial_spacing_fct_pt();
     }
References oomph::QuarterTubeDomain::axial_spacing_fct_pt(), oomph::QuarterTubeMesh< ELEMENT >::Domain_pt, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and oomph::Global_string_for_annotation::string().
node_update()
template<class ELEMENT > void oomph::AlgebraicRefineableQuarterTubeMesh< ELEMENT >::node_update (const bool & update_all_solid_nodes = false) inline virtual
Resolve mesh update: Update current nodal positions via algebraic node update. [Doesn't make sense to use this mesh with SolidElements anyway, so we buffer the case if update_all_solid_nodes is set to true.]
Reimplemented from oomph::AlgebraicMesh.
     {
 #ifdef PARANOID
       if (update_all_solid_nodes)
       {
         std::string error_message =
           "Doesn't make sense to use an AlgebraicMesh with\n";
         error_message +=
           "SolidElements so specifying update_all_solid_nodes=true\n";
         error_message += "doesn't make sense either\n";
         std::string function_name = " AlgebraicRefineableQuarterTubeMesh::";
         function_name += "node_update()";
         throw OomphLibError(
           error_message, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
       }
 #endif
       AlgebraicMesh::node_update();
     }
References oomph::AlgebraicMesh::node_update(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and oomph::Global_string_for_annotation::string().
Referenced by oomph::AlgebraicRefineableQuarterTubeMesh< ELEMENT >::AlgebraicRefineableQuarterTubeMesh().
node_update_central_region()
template<class ELEMENT > void oomph::AlgebraicRefineableQuarterTubeMesh< ELEMENT >::node_update_central_region (const unsigned & t, AlgebraicNode *& node_pt) private
Algebraic update function for a node that is located in the central region
Algebraic update function: Update in central region according to wall shape at time level t (t=0: present; t>0: previous)
   {
 #ifdef PARANOID
     // We're updating the nodal positions (!) at time level t
     // and determine them by evaluating the wall GeomObject's
     // position at that time level. I believe this only makes sense
     // if the t-th history value in the positional timestepper
     // actually represents previous values (rather than some
     // generalised quantity). Hence if this function is called with
     // t>nprev_values(), we issue a warning and terminate the execution.
     // It *might* be possible that the code still works correctly
     // even if this condition is violated (e.g. if the GeomObject's
     // position() function returns the appropriate "generalised"
     // position value that is required by the timestepping scheme but it's
     // probably worth flagging this up and forcing the user to manually switch
     // off this warning if he/she is 100% sure that this is kosher.
     if (t > node_pt->position_time_stepper_pt()->nprev_values())
     {
       std::string error_message =
         "Trying to update the nodal position at a time level\n";
       error_message += "beyond the number of previous values in the nodes'\n";
       error_message += "position timestepper. This seems highly suspect!\n";
       error_message += "If you're sure the code behaves correctly\n";
       error_message += "in your application, remove this warning \n";
       error_message += "or recompile with PARNOID switched off.\n";
       std::string function_name = "AlgebraicRefineableQuarterTubeMesh::";
       function_name += "node_update_central_region()",
         throw OomphLibError(
           error_message, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
 #endif
     // Extract references for update in central region by copy construction
     Vector<double> ref_value(node_pt->vector_ref_value(Central_region));
     // Extract geometric objects for update in central region by copy
     // construction
     Vector<GeomObject*> geom_object_pt(
       node_pt->vector_geom_object_pt(Central_region));
     // First reference value: fractional x-position of node inside region
     double rho_x = ref_value[0];
     // Second reference value: fractional y-position of node inside region
     double rho_y = ref_value[1];
     // Wall position in bottom right corner:
     // Pointer to GeomObject
     GeomObject* obj_br_pt = geom_object_pt[0];
     // Local coordinate at bottom-right reference point:
     Vector<double> s_br(2);
     s_br[0] = ref_value[3];
     s_br[1] = ref_value[4];
     // Get wall position
     unsigned n_dim = obj_br_pt->ndim();
     Vector<double> r_br(n_dim);
     obj_br_pt->position(t, s_br, r_br);
     // Wall position in top left corner:
     // Pointer to GeomObject
     GeomObject* obj_tl_pt = geom_object_pt[1];
     // Local coordinate:
     Vector<double> s_tl(2);
     s_tl[0] = ref_value[5];
     s_tl[1] = ref_value[6];
     // Get wall position
     Vector<double> r_tl(n_dim);
     obj_tl_pt->position(t, s_tl, r_tl);
     // Assign new nodal coordinate
     node_pt->x(t, 0) = r_br[0] * Lambda_x * rho_x;
     node_pt->x(t, 1) = r_tl[1] * Lambda_y * rho_y;
     node_pt->x(t, 2) = (r_br[2] + r_tl[2]) * 0.5;
   }
References oomph::GeomObject::ndim(), oomph::TimeStepper::nprev_values(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::GeomObject::position(), oomph::Node::position_time_stepper_pt(), oomph::Global_string_for_annotation::string(), plotPSD::t, oomph::AlgebraicNode::vector_geom_object_pt(), oomph::AlgebraicNode::vector_ref_value(), and oomph::Node::x().
Referenced by oomph::AlgebraicRefineableQuarterTubeMesh< ELEMENT >::algebraic_node_update().
node_update_lower_right_region()
template<class ELEMENT > void oomph::AlgebraicRefineableQuarterTubeMesh< ELEMENT >::node_update_lower_right_region (const unsigned & t, AlgebraicNode *& node_pt) private
Algebraic update function for a node that is located in the lower-right region
Algebraic update function: Update in lower-right region according to wall shape at time level t (t=0: present; t>0: previous)
   {
 #ifdef PARANOID
     // We're updating the nodal positions (!) at time level t
     // and determine them by evaluating the wall GeomObject's
     // position at that gime level. I believe this only makes sense
     // if the t-th history value in the positional timestepper
     // actually represents previous values (rather than some
     // generalised quantity). Hence if this function is called with
     // t>nprev_values(), we issue a warning and terminate the execution.
     // It *might* be possible that the code still works correctly
     // even if this condition is violated (e.g. if the GeomObject's
     // position() function returns the appropriate "generalised"
     // position value that is required by the timestepping scheme but it's
     // probably worth flagging this up and forcing the user to manually switch
     // off this warning if he/she is 100% sure that this is kosher.
     if (t > node_pt->position_time_stepper_pt()->nprev_values())
     {
       std::string error_message =
         "Trying to update the nodal position at a time level";
       error_message += "beyond the number of previous values in the nodes'";
       error_message += "position timestepper. This seems highly suspect!";
       error_message += "If you're sure the code behaves correctly";
       error_message += "in your application, remove this warning ";
       error_message += "or recompile with PARNOID switched off.";
       std::string function_name = "AlgebraicRefineableQuarterTubeSectorMesh::";
       function_name += "node_update_lower_right_region()",
         throw OomphLibError(
           error_message, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
 #endif
     // Extract references for update in lower-right region by copy construction
     Vector<double> ref_value(node_pt->vector_ref_value(Lower_right_region));
     // Extract geometric objects for update in lower-right region
     // by copy construction
     Vector<GeomObject*> geom_object_pt(
       node_pt->vector_geom_object_pt(Lower_right_region));
     // First reference value: fractional s0-position of node inside region
     double rho_0 = ref_value[0];
     // Use s_squashed to modify fractional s0 position
     rho_0 = this->Domain_pt->s_squashed(rho_0);
     // Second reference value: fractional s1-position of node inside region
     double rho_1 = ref_value[1];
     // Wall position in bottom right corner:
     // Pointer to GeomObject
     GeomObject* obj_br_pt = geom_object_pt[0];
     // Local coordinate
     Vector<double> s_br(2);
     s_br[0] = ref_value[3];
     s_br[1] = ref_value[4];
     // Eulerian dimension
     unsigned n_dim = obj_br_pt->ndim();
     // Get wall position
     Vector<double> r_br(n_dim);
     obj_br_pt->position(t, s_br, r_br);
     // Wall position in top left corner:
     // Pointer to GeomObject
     GeomObject* obj_tl_pt = geom_object_pt[1];
     // Local coordinate
     Vector<double> s_tl(2);
     s_tl[0] = ref_value[5];
     s_tl[1] = ref_value[6];
     Vector<double> r_tl(n_dim);
     obj_tl_pt->position(t, s_tl, r_tl);
     // Wall position at reference point:
     // Pointer to GeomObject
     GeomObject* obj_wall_pt = geom_object_pt[2];
     // Local coordinate
     Vector<double> s_wall(2);
     s_wall[0] = ref_value[7];
     s_wall[1] = ref_value[8];
     Vector<double> r_wall(n_dim);
     obj_wall_pt->position(t, s_wall, r_wall);
     // Position Vector to corner of the central region
     Vector<double> r_corner(n_dim);
     r_corner[0] = Lambda_x * r_br[0];
     r_corner[1] = Lambda_y * r_tl[1];
     r_corner[2] = (r_br[2] + r_tl[2]) * 0.5;
     // Position Vector to left edge of region
     Vector<double> r_left(n_dim);
     r_left[0] = r_corner[0];
     r_left[1] = rho_1 * r_corner[1];
     r_left[2] = r_corner[2];
     // Assign new nodal coordinate
     node_pt->x(t, 0) = r_left[0] + rho_0 * (r_wall[0] - r_left[0]);
     node_pt->x(t, 1) = r_left[1] + rho_0 * (r_wall[1] - r_left[1]);
     node_pt->x(t, 2) = r_left[2] + rho_0 * (r_wall[2] - r_left[2]);
   }
References oomph::GeomObject::ndim(), oomph::TimeStepper::nprev_values(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::GeomObject::position(), oomph::Node::position_time_stepper_pt(), oomph::Global_string_for_annotation::string(), plotPSD::t, oomph::AlgebraicNode::vector_geom_object_pt(), oomph::AlgebraicNode::vector_ref_value(), and oomph::Node::x().
Referenced by oomph::AlgebraicRefineableQuarterTubeMesh< ELEMENT >::algebraic_node_update().
node_update_upper_left_region()
template<class ELEMENT > void oomph::AlgebraicRefineableQuarterTubeMesh< ELEMENT >::node_update_upper_left_region (const unsigned & t, AlgebraicNode *& node_pt) private
Algebraic update function for a node that is located in the upper-left region
Algebraic update function: Update in upper left region according to wall shape at time level t (t=0: present; t>0: previous)
   {
 #ifdef PARANOID
     // We're updating the nodal positions (!) at time level t
     // and determine them by evaluating the wall GeomObject's
     // position at that gime level. I believe this only makes sense
     // if the t-th history value in the positional timestepper
     // actually represents previous values (rather than some
     // generalised quantity). Hence if this function is called with
     // t>nprev_values(), we issue a warning and terminate the execution.
     // It *might* be possible that the code still works correctly
     // even if this condition is violated (e.g. if the GeomObject's
     // position() function returns the appropriate "generalised"
     // position value that is required by the timestepping scheme but it's
     // probably worth flagging this up and forcing the user to manually switch
     // off this warning if he/she is 100% sure that this is kosher.
     if (t > node_pt->position_time_stepper_pt()->nprev_values())
     {
       std::string error_message =
         "Trying to update the nodal position at a time level";
       error_message += "beyond the number of previous values in the nodes'";
       error_message += "position timestepper. This seems highly suspect!";
       error_message += "If you're sure the code behaves correctly";
       error_message += "in your application, remove this warning ";
       error_message += "or recompile with PARNOID switched off.";
       std::string function_name = "AlgebraicRefineableQuarterTubeMesh::";
       function_name += "node_update_upper_left_region()";
       throw OomphLibError(
         error_message, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
 #endif
     // Extract references for update in upper-left region by copy construction
     Vector<double> ref_value(node_pt->vector_ref_value(Upper_left_region));
     // Extract geometric objects for update in upper-left region
     // by copy construction
     Vector<GeomObject*> geom_object_pt(
       node_pt->vector_geom_object_pt(Upper_left_region));
     // First reference value: fractional s0-position of node inside region
     double rho_0 = ref_value[0];
     // Second  reference value: fractional s1-position of node inside region
     double rho_1 = ref_value[1];
     // Use s_squashed to modify fractional s1 position
     rho_1 = this->Domain_pt->s_squashed(rho_1);
     // Wall position in bottom right corner:
     // Pointer to GeomObject
     GeomObject* obj_br_pt = geom_object_pt[0];
     // Eulerian dimension
     unsigned n_dim = obj_br_pt->ndim();
     // Local coordinate
     Vector<double> s_br(2);
     s_br[0] = ref_value[3];
     s_br[1] = ref_value[4];
     // Get wall position
     Vector<double> r_br(n_dim);
     obj_br_pt->position(t, s_br, r_br);
     // Wall position in top left corner:
     // Pointer to GeomObject
     GeomObject* obj_tl_pt = node_pt->geom_object_pt(1);
     // Local coordinate
     Vector<double> s_tl(2);
     s_tl[0] = ref_value[5];
     s_tl[1] = ref_value[6];
     Vector<double> r_tl(n_dim);
     obj_tl_pt->position(t, s_tl, r_tl);
     // Wall position at reference point:
     // Pointer to GeomObject
     GeomObject* obj_wall_pt = node_pt->geom_object_pt(2);
     // Local coordinate
     Vector<double> s_wall(2);
     s_wall[0] = ref_value[7];
     s_wall[1] = ref_value[8];
     Vector<double> r_wall(n_dim);
     obj_wall_pt->position(t, s_wall, r_wall);
     // Position vector to corner of the central region
     Vector<double> r_corner(n_dim);
     r_corner[0] = Lambda_x * r_br[0];
     r_corner[1] = Lambda_y * r_tl[1];
     r_corner[2] = (r_br[2] + r_tl[2]) * 0.5;
     // Position Vector to top face of central region
     Vector<double> r_top(n_dim);
     r_top[0] = rho_0 * r_corner[0];
     r_top[1] = r_corner[1];
     r_top[2] = r_corner[2];
     // Assign new nodal coordinate
     node_pt->x(t, 0) = r_top[0] + rho_1 * (r_wall[0] - r_top[0]);
     node_pt->x(t, 1) = r_top[1] + rho_1 * (r_wall[1] - r_top[1]);
     node_pt->x(t, 2) = r_top[2] + rho_1 * (r_wall[2] - r_top[2]);
   }
References oomph::AlgebraicNode::geom_object_pt(), oomph::GeomObject::ndim(), oomph::TimeStepper::nprev_values(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::GeomObject::position(), oomph::Node::position_time_stepper_pt(), oomph::Global_string_for_annotation::string(), plotPSD::t, oomph::AlgebraicNode::vector_geom_object_pt(), oomph::AlgebraicNode::vector_ref_value(), and oomph::Node::x().
Referenced by oomph::AlgebraicRefineableQuarterTubeMesh< ELEMENT >::algebraic_node_update().
self_test()
template<class ELEMENT > unsigned oomph::AlgebraicRefineableQuarterTubeMesh< ELEMENT >::self_test () inline
Run self-test for algebraic mesh – return 0/1 for OK/failure.
     {
       return AlgebraicMesh::self_test();
     }
References oomph::AlgebraicMesh::self_test().
setup_algebraic_node_update()
template<class ELEMENT > void oomph::AlgebraicRefineableQuarterTubeMesh< ELEMENT >::setup_algebraic_node_update private
Setup algebraic update operation for all nodes.
//////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////// Setup algebraic node update data, based on 3 regions, each undergoing a different node update strategy. These regions are defined by the three MacroElements in each of the nlayer slices of the QuarterTubeDomain used to build the mesh. The Mesh is suspended from the ‘wall’ GeomObject pointed to by wall_pt. The lower right edge of the mesh is located at the wall's coordinate xi[1]==xi_lo[1], the upper left edge at xi[1]=xi_hi[1], i.e. a view looking down the tube length. The dividing line between the two outer regions is located at the fraction fract_mid between these two coordinates. Node updating strategy:
the starting cross sectional shape along the tube length is assumed to be uniform
the cross sectional shape of the central region remains rectangular; the position of its top right corner is located at a fixed fraction of the starting width and height of the domain measured at xi[1]==xi_lo[1] and xi[1]==xi_hi[1] respectively. Nodes in this region are located at fixed horizontal and vertical fractions of the region.
Nodes in the two outer regions (bottom right and top left) are located on straight lines running from the edges of the central region to the outer wall.
   {
 #ifdef PARANOID
     AlgebraicElementBase* algebraic_element_pt =
       dynamic_cast<AlgebraicElementBase*>(Mesh::element_pt(0));
     if (algebraic_element_pt == 0)
     {
       std::ostringstream error_message;
       error_message
         << "Element in AlgebraicRefineableQuarterTubeMesh must be\n ";
       error_message << "derived from AlgebraicElementBase\n";
       error_message << "but it is of type:  "
                     << typeid(Mesh::element_pt(0)).name() << std::endl;
       std::string function_name = "AlgebraicRefineableQuarterTubeMesh::";
       function_name += "setup_algebraic_node_update()";
       throw OomphLibError(
         error_message.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
 #endif
     // Find number of nodes in an element from the zeroth element
     unsigned nnodes_3d = Mesh::finite_element_pt(0)->nnode();
     // also find number of nodes in 1d line and 2d slice
     unsigned nnodes_1d = Mesh::finite_element_pt(0)->nnode_1d();
     unsigned nnodes_2d = nnodes_1d * nnodes_1d;
     // find node number of a top-left and a bottom-right node in an element
     // (orientation: looking down tube)
     unsigned tl_node = nnodes_2d - nnodes_1d;
     unsigned br_node = nnodes_1d - 1;
     // find x & y distances to top-right node in element 0 - this is the same
     // node as the top-left node of element 1
     double x_c_element = Mesh::finite_element_pt(1)->node_pt(tl_node)->x(0);
     double y_c_element = Mesh::finite_element_pt(1)->node_pt(tl_node)->x(1);
     // Get x-distance to bottom-right edge of wall, i.e. coord of node
     // at bottom-right of bottom-right of element 1
     double x_wall = Mesh::finite_element_pt(1)->node_pt(br_node)->x(0);
     // Get y-distance to top-left edge of wall, i.e. coord of node
     // at top-left of element 2
     double y_wall = Mesh::finite_element_pt(2)->node_pt(tl_node)->x(1);
     // Establish fractional widths in central region
     Lambda_x = Centre_box_size * x_c_element / x_wall;
     Lambda_y = Centre_box_size * y_c_element / y_wall;
     // how many elements are there?
     unsigned nelements = Mesh::nelement();
     // loop through the elements
     for (unsigned e = 0; e < nelements; e++)
     {
       // get pointer to element
       FiniteElement* el_pt = Mesh::finite_element_pt(e);
       // set region id
       unsigned region_id = e % 3;
       // find the first node for which to set up node update info - must
       // bypass the first nnodes_2d nodes after the first 3 elements
       unsigned nstart = nnodes_2d;
       if (e < 3)
       {
         nstart = 0;
       }
       // loop through the nodes,
       for (unsigned n = nstart; n < nnodes_3d; n++)
       {
         // find z coordinate of node
         // NOTE: to implement axial spacing replace z by z_spaced where
         // z_spaced=axial_spacing_fct(z) when finding the GeomObjects
         // and local coords below
         // BUT store z as the third reference value since this is the value
         // required by update_node_update()
         double z = el_pt->node_pt(n)->x(2);
         // Find wall GeomObject and the GeomObject local coordinates
         // at bottom-right edge of wall
         Vector<double> xi(2);
         xi[0] = z;
         xi[1] = QuarterTubeMesh<ELEMENT>::Xi_lo[1];
         GeomObject* obj_br_pt;
         Vector<double> s_br(2);
         this->Wall_pt->locate_zeta(xi, obj_br_pt, s_br);
         // Find wall GeomObject/local coordinate
         // at top-left edge of wall
         xi[1] = QuarterTubeMesh<ELEMENT>::Xi_hi[1];
         GeomObject* obj_tl_pt;
         Vector<double> s_tl(2);
         this->Wall_pt->locate_zeta(xi, obj_tl_pt, s_tl);
         // Element 0: central region
         //--------------------------
         if (region_id == 0)
         {
           // Nodal coordinates in x and y direction
           double x = el_pt->node_pt(n)->x(0);
           double y = el_pt->node_pt(n)->x(1);
           // The update function requires two geometric objects
           Vector<GeomObject*> geom_object_pt(2);
           // Wall GeomObject at bottom right end of wall mesh:
           geom_object_pt[0] = obj_br_pt;
           // Wall GeomObject at top left end of wall mesh:
           geom_object_pt[1] = obj_tl_pt;
           // The update function requires seven parameters:
           Vector<double> ref_value(7);
           // First reference value: fractional x-position inside region
           ref_value[0] = x / x_c_element;
           // Second cfractional y-position inside region
           ref_value[1] = y / y_c_element;
           // Third reference value: initial z coordinate of node
           ref_value[2] = z;
           // Fourth and fifth reference values:
           // local coordinate in GeomObject at bottom-right of wall.
           // Note: must recompute this reference for new nodes
           // since values interpolated from parent nodes will
           // be wrong (this is true for all local coordinates
           // within GeomObjects)
           ref_value[3] = s_br[0];
           ref_value[4] = s_br[1];
           // Sixth and seventh reference values:
           // local coordinate in GeomObject at top-left of wall.
           ref_value[5] = s_tl[0];
           ref_value[6] = s_tl[1];
           // Setup algebraic update for node: Pass update information
           static_cast<AlgebraicNode*>(el_pt->node_pt(n))
             ->add_node_update_info(Central_region, // enumerated ID
                                    this, // mesh
                                    geom_object_pt, // vector of geom objects
                                    ref_value); // vector of ref. values
         }
         // Element 1: Bottom right region
         //-------------------------------
         else if (region_id == 1)
         {
           // Fractional distance between nodes
           double fract = 1.0 / double(nnodes_1d - 1);
           // Fraction in the s_0-direction
           double rho_0 = fract * double(n % nnodes_1d);
           // Fraction in the s_1-direction
           double rho_1 = fract * double((n / nnodes_1d) % nnodes_1d);
           // Find coord of reference point on wall
           xi[1] = QuarterTubeMesh<ELEMENT>::Xi_lo[1] +
                   rho_1 * QuarterTubeMesh<ELEMENT>::Fract_mid *
                     (QuarterTubeMesh<ELEMENT>::Xi_hi[1] -
                      QuarterTubeMesh<ELEMENT>::Xi_lo[1]);
           // Identify wall GeomObject and local coordinate of
           // reference point in GeomObject
           GeomObject* obj_wall_pt;
           Vector<double> s_wall(2);
           this->Wall_pt->locate_zeta(xi, obj_wall_pt, s_wall);
           // The update function requires three geometric objects
           Vector<GeomObject*> geom_object_pt(3);
           // Wall element at bottom-right end of wall mesh:
           geom_object_pt[0] = obj_br_pt;
           // Wall element at top left end of wall mesh:
           geom_object_pt[1] = obj_tl_pt;
           // Wall element at that contians reference point:
           geom_object_pt[2] = obj_wall_pt;
           // The update function requires nine parameters:
           Vector<double> ref_value(9);
           // First reference value: fractional s0-position inside region
           ref_value[0] = rho_0;
           // Second reference value: fractional s1-position inside region
           ref_value[1] = rho_1;
           // Thrid reference value: initial z coord of node
           ref_value[2] = z;
           // Fourth and fifth reference values:
           //   local coordinates at bottom-right of wall.
           ref_value[3] = s_br[0];
           ref_value[4] = s_br[1];
           // Sixth and seventh reference values:
           //   local coordinates at top-left of wall.
           ref_value[5] = s_tl[0];
           ref_value[6] = s_tl[1];
           // Eighth and ninth reference values:
           //   local coordinate of reference point.
           ref_value[7] = s_wall[0];
           ref_value[8] = s_wall[1];
           // Setup algebraic update for node: Pass update information
           static_cast<AlgebraicNode*>(el_pt->node_pt(n))
             ->add_node_update_info(Lower_right_region, // enumerated ID
                                    this, // mesh
                                    geom_object_pt, // vector of geom objects
                                    ref_value); // vector of ref. vals
         }
         // Element 2: Top left region
         //---------------------------
         else if (region_id == 2)
         {
           // Fractional distance between nodes
           double fract = 1.0 / double(nnodes_1d - 1);
           // Fraction in the s_0-direction
           double rho_0 = fract * double(n % nnodes_1d);
           // Fraction in the s_1-direction
           double rho_1 = fract * double((n / nnodes_1d) % nnodes_1d);
           // Find coord of reference point on wall
           xi[1] = QuarterTubeMesh<ELEMENT>::Xi_hi[1] +
                   rho_0 * (1.0 - QuarterTubeMesh<ELEMENT>::Fract_mid) *
                     (QuarterTubeMesh<ELEMENT>::Xi_lo[1] -
                      QuarterTubeMesh<ELEMENT>::Xi_hi[1]);
           // Identify GeomObject and local coordinate at
           // reference point on wall
           GeomObject* obj_wall_pt;
           Vector<double> s_wall(2);
           this->Wall_pt->locate_zeta(xi, obj_wall_pt, s_wall);
           // The update function requires three geometric objects
           Vector<GeomObject*> geom_object_pt(3);
           // Wall element at bottom-right of wall mesh:
           geom_object_pt[0] = obj_br_pt;
           // Wall element at top-left of wall mesh:
           geom_object_pt[1] = obj_tl_pt;
           // Wall element contianing reference point:
           geom_object_pt[2] = obj_wall_pt;
           // The update function requires nine parameters:
           Vector<double> ref_value(9);
           // First reference value: fractional s0-position inside region
           ref_value[0] = rho_0;
           // Second reference value: fractional s1-position inside region
           ref_value[1] = rho_1;
           // Third reference value: initial z coord
           ref_value[2] = z;
           // Fourth and fifth reference values:
           //   local coordinates in bottom-right GeomObject
           ref_value[3] = s_br[0];
           ref_value[4] = s_br[1];
           // Sixth and seventh reference values:
           //   local coordinates in top-left GeomObject
           ref_value[5] = s_tl[0];
           ref_value[6] = s_tl[1];
           // Eighth and ninth reference values:
           //   local coordinates at reference point
           ref_value[7] = s_wall[0];
           ref_value[8] = s_wall[1];
           // Setup algebraic update for node: Pass update information
           static_cast<AlgebraicNode*>(el_pt->node_pt(n))
             ->add_node_update_info(Upper_left_region, // Enumerated ID
                                    this, // mesh
                                    geom_object_pt, // vector of geom objects
                                    ref_value); // vector of ref. vals
         }
       }
     }
   }
References e(), oomph::Mesh::element_pt(), oomph::Mesh::finite_element_pt(), n, plotDoE::name, oomph::Mesh::nelement(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nnode_1d(), oomph::FiniteElement::node_pt(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::Global_string_for_annotation::string(), plotDoE::x, oomph::Node::x(), and y.
Referenced by oomph::AlgebraicRefineableQuarterTubeMesh< ELEMENT >::AlgebraicRefineableQuarterTubeMesh().
update_node_update()
template<class ELEMENT > void oomph::AlgebraicRefineableQuarterTubeMesh< ELEMENT >::update_node_update (AlgebraicNode *& node_pt) inline virtual
Update the node update info for specified algebraic node following any spatial mesh adaptation.
Implements oomph::AlgebraicMesh.
     {
       // Get all node update fct for this node (resizes internally)
       Vector<int> id;
       node_pt->node_update_fct_id(id);
       // Loop over all update fcts
       unsigned n_update = id.size();
       for (unsigned i = 0; i < n_update; i++)
       {
         update_node_update_in_region(node_pt, id[i]);
       }
     }
References i, oomph::AlgebraicMesh::node_pt(), oomph::AlgebraicNode::node_update_fct_id(), and oomph::AlgebraicRefineableQuarterTubeMesh< ELEMENT >::update_node_update_in_region().
update_node_update_in_region()
template<class ELEMENT > void oomph::AlgebraicRefineableQuarterTubeMesh< ELEMENT >::update_node_update_in_region (AlgebraicNode *& node_pt, int & region_id) private
Update algebraic node update function for nodes in the region defined by region_id
Update algebraic update function for nodes in region defined by region_id.
   {
     // Extract references by copy construction
     Vector<double> ref_value(node_pt->vector_ref_value(region_id));
     // Extract geometric objects for update by copy construction
     Vector<GeomObject*> geom_object_pt(
       node_pt->vector_geom_object_pt(region_id));
     // Now remove the update info to allow overwriting below
     node_pt->kill_node_update_info(region_id);
     // Fixed reference value: Start coordinate on wall
     double xi_lo = QuarterTubeMesh<ELEMENT>::Xi_lo[1];
     // Fixed reference value: Fractional position of dividing line
     double fract_mid = QuarterTubeMesh<ELEMENT>::Fract_mid;
     // Fixed reference value: End coordinate on wall
     double xi_hi = QuarterTubeMesh<ELEMENT>::Xi_hi[1];
     // get initial z-coordinate of node
     // NOTE: use modified z found using axial_spacing_fct()
     // to implement axial spacing
     double z = ref_value[2];
     // Update reference to wall point in bottom right corner
     //------------------------------------------------------
     // Wall position in bottom right corner:
     Vector<double> xi(2);
     xi[0] = z;
     xi[1] = xi_lo;
     // Find corresponding wall element/local coordinate
     GeomObject* obj_br_pt;
     Vector<double> s_br(2);
     this->Wall_pt->locate_zeta(xi, obj_br_pt, s_br);
     // Wall element at bottom right end of wall mesh:
     geom_object_pt[0] = obj_br_pt;
     // Local coordinate in this wall element.
     ref_value[3] = s_br[0];
     ref_value[4] = s_br[1];
     // Update reference to wall point in upper left corner
     //----------------------------------------------------
     // Wall position in top left corner
     xi[1] = xi_hi;
     // Find corresponding wall element/local coordinate
     GeomObject* obj_tl_pt;
     Vector<double> s_tl(2);
     this->Wall_pt->locate_zeta(xi, obj_tl_pt, s_tl);
     // Wall element at top left end of wall mesh:
     geom_object_pt[1] = obj_tl_pt;
     // Local coordinate in this wall element.
     ref_value[5] = s_tl[0];
     ref_value[6] = s_tl[1];
     if (region_id != Central_region)
     {
       // Update reference to reference point on wall
       //--------------------------------------------
       // Reference point on wall
       if (region_id == Lower_right_region)
       {
         // Second reference value: fractional s1-position of node inside region
         double rho_1 = ref_value[1];
         // position of reference point
         xi[1] = xi_lo + rho_1 * fract_mid * (xi_hi - xi_lo);
       }
       else // case of Upper_left region
       {
         // First reference value: fractional s0-position of node inside region
         double rho_0 = ref_value[0];
         // position of reference point
         xi[1] = xi_hi - rho_0 * (1.0 - fract_mid) * (xi_hi - xi_lo);
       }
       // Identify wall element number and local coordinate of
       // reference point on wall
       GeomObject* obj_wall_pt;
       Vector<double> s_wall(2);
       this->Wall_pt->locate_zeta(xi, obj_wall_pt, s_wall);
       // Wall element at that contians reference point:
       geom_object_pt[2] = obj_wall_pt;
       // Local coordinate in this wall element.
       ref_value[7] = s_wall[0];
       ref_value[8] = s_wall[1];
     }
     // Setup algebraic update for node: Pass update information
     node_pt->add_node_update_info(region_id, // Enumerated ID
                                   this, // mesh
                                   geom_object_pt, // vector of geom objects
                                   ref_value); // vector of ref. vals
   }
References oomph::AlgebraicNode::add_node_update_info(), oomph::AlgebraicNode::kill_node_update_info(), oomph::AlgebraicNode::vector_geom_object_pt(), and oomph::AlgebraicNode::vector_ref_value().
Referenced by oomph::AlgebraicRefineableQuarterTubeMesh< ELEMENT >::update_node_update().
Member Data Documentation
Centre_box_size
template<class ELEMENT > double oomph::AlgebraicRefineableQuarterTubeMesh< ELEMENT >::Centre_box_size private
Size of centre box.
Lambda_x
template<class ELEMENT > double oomph::AlgebraicRefineableQuarterTubeMesh< ELEMENT >::Lambda_x private
Fractional width of central region.
Lambda_y
template<class ELEMENT > double oomph::AlgebraicRefineableQuarterTubeMesh< ELEMENT >::Lambda_y private
Fractional height of central region.
The documentation for this class was generated from the following files:
quarter_tube_mesh.template.h
quarter_tube_mesh.template.cc