MercuryDPM: FreeCooling3DDemo.cpp File Reference
FreeCooling3DDemo.cpp File Reference
#include <iostream>
#include <Species/LinearViscoelasticSpecies.h>
#include <Boundaries/PeriodicBoundary.h>
#include "Mercury3D.h"
#include "MercuryTime.h"
Classes
class FreeCooling3DDemoProblem
[FCD_3D:headers]
Functions
int main (int argc UNUSED, char *argv[] UNUSED)
[FCD_3D:class]
Function Documentation
main()
int main (int argc UNUSED, char *argv[] UNUSED)
[FCD_3D:class]
[FCD_3D:main]
[FCD_3D:species]
[FCD_3D:species] [FCD_3DproblemSetup]
[FCD_3DproblemSetup] [FCD_3D:solve]
[FCD_3D:solve]
 {
     // Problem setup
     FreeCooling3DDemoProblem problem;
     LinearViscoelasticSpecies species;
     species.setDensity(2e3);
     species.setDissipation(0.0);
     species.setStiffness(1e3);
     problem.FC3D_Species = species;
     problem.speciesHandler.copyAndAddObject(species);
     problem.N = 1000;
     problem.setName("FreeCooling3DDemo");
     problem.setGravity(Vec3D(0.0, 0.0, 0.0));
     problem.setTimeStep(5e-5);
     problem.setSaveCount(4000);
     problem.setTimeMax(50.0);
     problem.setMax(0.064,0.064,0.064);
     problem.setHGridMaxLevels(1);
     problem.setHGridCellOverSizeRatio(1.2);
     problem.setHGridUpdateEachTimeStep(false);
     problem.setFileType(FileType::ONE_FILE);
     problem.setParticlesWriteVTK(true);
     problem.solve();
 }
References e(), ONE_FILE, problem, ParticleSpecies::setDensity(), LinearViscoelasticNormalSpecies::setDissipation(), and LinearViscoelasticNormalSpecies::setStiffness().