MercuryDPM: ElementCmp Class Reference
ElementCmp Class Reference
Function-type-object to perform comparison of elements.
Public Member Functions
bool operator() (GeneralisedElement *const &x, GeneralisedElement *const &y) const
Comparison. Are the values identical or not?
bool operator() (GeneralisedElement *const &x, GeneralisedElement *const &y) const
Comparison. Are the values identical or not?
bool operator() (GeneralisedElement *const &x, GeneralisedElement *const &y) const
Comparison. Are the values identical or not?
bool operator() (GeneralisedElement *const &x, GeneralisedElement *const &y) const
Comparison. Are the values identical or not?
bool operator() (GeneralisedElement *const &x, GeneralisedElement *const &y) const
Comparison. Are the values identical or not?
Detailed Description
Function-type-object to perform comparison of elements.
Function-type-object to perform comparison of elements in y-direction.
////////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////////
Member Function Documentation
operator()() [1/5]
bool ElementCmp::operator() (GeneralisedElement *const & x, GeneralisedElement *const & y) const inline
Comparison. Are the values identical or not?
   {
    FiniteElement* cast_x = dynamic_cast<FiniteElement*>(x);
    FiniteElement* cast_y = dynamic_cast<FiniteElement*>(y);
    if((cast_x ==0) || (cast_y==0)) {return 0;}
    else
     {return cast_x->node_pt(0)->x(0) < cast_y->node_pt(0)->x(0);}
   }
References oomph::FiniteElement::node_pt(), plotDoE::x, oomph::Node::x(), and y.
operator()() [2/5]
bool ElementCmp::operator() (GeneralisedElement *const & x, GeneralisedElement *const & y) const inline
Comparison. Are the values identical or not?
   {
    FiniteElement* cast_x = dynamic_cast<FiniteElement*>(x);
    FiniteElement* cast_y = dynamic_cast<FiniteElement*>(y);
    // Orders elements vertically, starting from the bottom of each spine
    if((cast_x==0) || (cast_y==0)) { return 0; }
    else
     {
      return ((cast_x->node_pt(0)->x(0) + 1.0e-8*cast_x->node_pt(0)->x(1))
              < (cast_y->node_pt(0)->x(0) + 1.0e-8*cast_y->node_pt(0)->x(1)));
     }
   }
References oomph::FiniteElement::node_pt(), plotDoE::x, oomph::Node::x(), and y.
operator()() [3/5]
bool ElementCmp::operator() (GeneralisedElement *const & x, GeneralisedElement *const & y) const inline
Comparison. Are the values identical or not?
   {
    FiniteElement* cast_x = dynamic_cast<FiniteElement*>(x);
    FiniteElement* cast_y = dynamic_cast<FiniteElement*>(y);
    if((cast_x ==0) || (cast_y==0)) {return 0;}
    else
     {return cast_x->node_pt(0)->x(2) < cast_y->node_pt(0)->x(2);}
   }
References oomph::FiniteElement::node_pt(), plotDoE::x, oomph::Node::x(), and y.
operator()() [4/5]
bool ElementCmp::operator() (GeneralisedElement *const & x, GeneralisedElement *const & y) const inline
Comparison. Are the values identical or not?
   {
    FiniteElement* cast_x = dynamic_cast<FiniteElement*>(x);
    FiniteElement* cast_y = dynamic_cast<FiniteElement*>(y);
    if((cast_x ==0) || (cast_y==0)) {return 0;}
    else
     {return cast_x->node_pt(0)->x(2) < cast_y->node_pt(0)->x(2);}
   }
References oomph::FiniteElement::node_pt(), plotDoE::x, oomph::Node::x(), and y.
operator()() [5/5]
bool ElementCmp::operator() (GeneralisedElement *const & x, GeneralisedElement *const & y) const inline
Comparison. Are the values identical or not?
   {
    FiniteElement* cast_x = dynamic_cast<FiniteElement*>(x);
    FiniteElement* cast_y = dynamic_cast<FiniteElement*>(y);
    if((cast_x ==0) || (cast_y==0)) {return 0;}
    else
     {return (cast_x->node_pt(0)->x(1)< cast_y->node_pt(0)->x(1));}
   }
References oomph::FiniteElement::node_pt(), plotDoE::x, oomph::Node::x(), and y.
The documentation for this class was generated from the following files:
elastic_bretherton.cc
two_layer_interface_nonaxisym_perturbations.cc
3d_multimesh_ref_b_convect.cc
3d_ref_b_convect.cc
3d_rayleigh_instability_surfactant.cc