MercuryDPM: Eigen::PartialReduxExpr< MatrixType, MemberOp, Direction > Class Template Reference
Eigen::PartialReduxExpr< MatrixType, MemberOp, Direction > Class Template Reference
Dense matrix and array manipulation » Reference » Core_Module
Generic expression of a partially reduxed matrix.
#include <VectorwiseOp.h>
Public Types
typedef internal::dense_xpr_base< PartialReduxExpr >::type Base
Public Member Functions
EIGEN_DEVICE_FUNC PartialReduxExpr (const MatrixType &mat, const MemberOp &func=MemberOp())
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index rows () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index cols () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC MatrixType::Nested nestedExpression () const
EIGEN_DEVICE_FUNC const MemberOp & functor () const
Protected Attributes
MatrixType::Nested m_matrix
const MemberOp m_functor
Detailed Description
template<typename MatrixType, typename MemberOp, int Direction>
class Eigen::PartialReduxExpr< MatrixType, MemberOp, Direction >
Generic expression of a partially reduxed matrix.
Template Parameters
MatrixType the type of the matrix we are applying the redux operation
MemberOp type of the member functor
Direction indicates the direction of the redux (Vertical or Horizontal)
This class represents an expression of a partial redux operator of a matrix. It is the return type of some VectorwiseOp functions, and most of the time this is the only way it is used.
See also
class VectorwiseOp
Member Typedef Documentation
Base
template<typename MatrixType , typename MemberOp , int Direction> typedef internal::dense_xpr_base<PartialReduxExpr>::type Eigen::PartialReduxExpr< MatrixType, MemberOp, Direction >::Base
Constructor & Destructor Documentation
PartialReduxExpr()
template<typename MatrixType , typename MemberOp , int Direction> EIGEN_DEVICE_FUNC Eigen::PartialReduxExpr< MatrixType, MemberOp, Direction >::PartialReduxExpr (const MatrixType & mat, const MemberOp & func = MemberOp()) inline explicit
       : m_matrix(mat), m_functor(func) {}
Member Function Documentation
cols()
template<typename MatrixType , typename MemberOp , int Direction> EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index Eigen::PartialReduxExpr< MatrixType, MemberOp, Direction >::cols () const inline
{
     return (Direction == Horizontal ? 1 : m_matrix.cols());
   }
References Eigen::Horizontal, and Eigen::PartialReduxExpr< MatrixType, MemberOp, Direction >::m_matrix.
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
functor()
template<typename MatrixType , typename MemberOp , int Direction> EIGEN_DEVICE_FUNC const MemberOp& Eigen::PartialReduxExpr< MatrixType, MemberOp, Direction >::functor () const inline
 { return m_functor; }
References Eigen::PartialReduxExpr< MatrixType, MemberOp, Direction >::m_functor.
nestedExpression()
template<typename MatrixType , typename MemberOp , int Direction> EIGEN_DEVICE_FUNC MatrixType::Nested Eigen::PartialReduxExpr< MatrixType, MemberOp, Direction >::nestedExpression () const inline
 { return m_matrix; }
References Eigen::PartialReduxExpr< MatrixType, MemberOp, Direction >::m_matrix.
rows()
template<typename MatrixType , typename MemberOp , int Direction> EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index Eigen::PartialReduxExpr< MatrixType, MemberOp, Direction >::rows () const inline
{
     return (Direction == Vertical ? 1 : m_matrix.rows());
   }
References Eigen::PartialReduxExpr< MatrixType, MemberOp, Direction >::m_matrix, and Eigen::Vertical.
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
Member Data Documentation
m_functor
template<typename MatrixType , typename MemberOp , int Direction> const MemberOp Eigen::PartialReduxExpr< MatrixType, MemberOp, Direction >::m_functor protected
Referenced by Eigen::PartialReduxExpr< MatrixType, MemberOp, Direction >::functor().
m_matrix
template<typename MatrixType , typename MemberOp , int Direction> MatrixType::Nested Eigen::PartialReduxExpr< MatrixType, MemberOp, Direction >::m_matrix protected
Referenced by Eigen::PartialReduxExpr< MatrixType, MemberOp, Direction >::cols(), Eigen::PartialReduxExpr< MatrixType, MemberOp, Direction >::nestedExpression(), and Eigen::PartialReduxExpr< MatrixType, MemberOp, Direction >::rows().
The documentation for this class was generated from the following files:
ForwardDeclarations.h
VectorwiseOp.h