MercuryDPM: oomph::IsotropicElasticityTensor Class Reference
oomph::IsotropicElasticityTensor Class Reference
#include <elasticity_tensor.h>
Public Member Functions
IsotropicElasticityTensor (const double &nu, const double &E)
IsotropicElasticityTensor (const double &nu)
IsotropicElasticityTensor (const Vector< double > &lame)
void update_constitutive_parameters (const double &nu, const double &E=1.0)
double independent_component (const unsigned &i) const
Overload the independent coefficient function.
IsotropicElasticityTensor (const double &nu, const double &E)
IsotropicElasticityTensor (const double &nu)
IsotropicElasticityTensor (const Vector< double > &lame)
double independent_component (const unsigned &i) const
Overload the independent coefficient function.
Public Member Functions inherited from oomph::ElasticityTensor
virtual ~ElasticityTensor ()
Empty virtual Destructor.
double operator() (const unsigned &i, const unsigned &j, const unsigned &k, const unsigned &l) const
virtual void set_value (const unsigned &i, const unsigned &j, const unsigned &k, const unsigned &l, const double &value)
virtual ~ElasticityTensor ()
Empty virtual Destructor.
double operator() (const unsigned &i, const unsigned &j, const unsigned &k, const unsigned &l) const
Private Member Functions
void set_lame_coefficients (const double &lambda, const double &mu)
void set_lame_coefficients (const double &lambda, const double &mu)
Private Attributes
double C [4]
Static Private Attributes
static const unsigned StaticIndex [21]
Translation scheme for the isotropic elasticity tensor.
Additional Inherited Members
Protected Member Functions inherited from oomph::ElasticityTensor
void range_check (const unsigned &i, const unsigned &j, const unsigned &k, const unsigned &l) const
ElasticityTensor ()
Empty Constructor.
void range_check (const unsigned &i, const unsigned &j, const unsigned &k, const unsigned &l) const
ElasticityTensor ()
Empty Constructor.
Static Protected Attributes inherited from oomph::ElasticityTensor
static const unsigned Index [3][3][3][3]
Detailed Description
An isotropic elasticity tensor defined in terms of Young's modulus and Poisson's ratio. The elasticity tensor is assumed to be non-dimensionalised on some reference value for Young's modulus so the value provided to the constructor (if any) is to be interpreted as the ratio of the actual Young's modulus to the Young's modulus used to non-dimensionalise the stresses/tractions in the governing equations.
Constructor & Destructor Documentation
IsotropicElasticityTensor() [1/6]
oomph::IsotropicElasticityTensor::IsotropicElasticityTensor (const double & nu, const double & E) inline
Constructor. Passing in the values of the Poisson's ratio and Young's modulus (interpreted as the ratio of the actual Young's modulus to the Young's modulus (or other reference stiffness) used to non-dimensionalise stresses and tractions in the governing equations).
       : ElasticityTensor()
     {
       // Set the three indepdent components
       C[0] = 0.0;
       double lambda = E * nu / ((1.0 + nu) * (1.0 - 2.0 * nu));
       double mu = E / (2.0 * (1.0 + nu));
       this->set_lame_coefficients(lambda, mu);
     }
References Global_Physical_Variables::E, lambda, Global_Parameters::mu, and set_lame_coefficients().
IsotropicElasticityTensor() [2/6]
oomph::IsotropicElasticityTensor::IsotropicElasticityTensor (const double & nu) inline
Constructor. Passing in the value of the Poisson's ratio. Stresses and tractions in the governing equations are assumed to have been non-dimensionalised on Young's modulus.
                                                 : ElasticityTensor()
     {
       // Set the three indepdent components
       C[0] = 0.0;
       // reference value
       double E = 1.0;
       double lambda = E * nu / ((1.0 + nu) * (1.0 - 2.0 * nu));
       double mu = E / (2.0 * (1.0 + nu));
       this->set_lame_coefficients(lambda, mu);
     }
References Global_Physical_Variables::E, lambda, Global_Parameters::mu, and set_lame_coefficients().
IsotropicElasticityTensor() [3/6]
oomph::IsotropicElasticityTensor::IsotropicElasticityTensor (const Vector< double > & lame) inline
Constructur. Passing in the values of the two lame coefficients directly (interpreted as the ratios of these quantities to a reference stiffness used to non-dimensionalised
     {
       // Set the three independent componens
       C[0] = 0.0;
       this->set_lame_coefficients(lame[0], lame[1]);
     }
References set_lame_coefficients().
IsotropicElasticityTensor() [4/6]
oomph::IsotropicElasticityTensor::IsotropicElasticityTensor (const double & nu, const double & E) inline
Constructor. Passing in the values of the Poisson's ratio and Young's modulus (interpreted as the ratio of the actual Young's modulus to the Young's modulus (or other reference stiffness) used to non-dimensionalise stresses and tractions in the governing equations).
       : ElasticityTensor()
     {
       // Set the three independent components
       C[0] = 0.0;
       double lambda = E * nu / ((1.0 + nu) * (1.0 - 2.0 * nu));
       double mu = E / (2.0 * (1.0 + nu));
       this->set_lame_coefficients(lambda, mu);
     }
References Global_Physical_Variables::E, lambda, Global_Parameters::mu, and set_lame_coefficients().
IsotropicElasticityTensor() [5/6]
oomph::IsotropicElasticityTensor::IsotropicElasticityTensor (const double & nu) inline
Constructor. Passing in the value of the Poisson's ratio. Stresses and tractions in the governing equations are assumed to have been non-dimensionalised on Young's modulus.
                                                 : ElasticityTensor()
     {
       // Set the three independent components
       C[0] = 0.0;
       // reference value
       double E = 1.0;
       double lambda = E * nu / ((1.0 + nu) * (1.0 - 2.0 * nu));
       double mu = E / (2.0 * (1.0 + nu));
       this->set_lame_coefficients(lambda, mu);
     }
References Global_Physical_Variables::E, lambda, Global_Parameters::mu, and set_lame_coefficients().
IsotropicElasticityTensor() [6/6]
oomph::IsotropicElasticityTensor::IsotropicElasticityTensor (const Vector< double > & lame) inline
Constructur. Passing in the values of the two lame coefficients directly (interpreted as the ratios of these quantities to a reference stiffness used to non-dimensionalised
     {
       // Set the three independent components
       C[0] = 0.0;
       this->set_lame_coefficients(lame[0], lame[1]);
     }
References set_lame_coefficients().
Member Function Documentation
independent_component() [1/2]
double oomph::IsotropicElasticityTensor::independent_component (const unsigned & i) const inline virtual
Overload the independent coefficient function.
Reimplemented from oomph::ElasticityTensor.
     {
       return C[StaticIndex[i]];
     }
References i, and StaticIndex.
independent_component() [2/2]
double oomph::IsotropicElasticityTensor::independent_component (const unsigned & i) const inline virtual
Overload the independent coefficient function.
Reimplemented from oomph::ElasticityTensor.
     {
       return C[StaticIndex[i]];
     }
References i, and StaticIndex.
set_lame_coefficients() [1/2]
void oomph::IsotropicElasticityTensor::set_lame_coefficients (const double & lambda, const double & mu) inline private
     {
       C[1] = lambda + 2.0 * mu;
       C[2] = lambda;
       C[3] = mu;
     }
References lambda, and Global_Parameters::mu.
Referenced by IsotropicElasticityTensor(), and update_constitutive_parameters().
set_lame_coefficients() [2/2]
void oomph::IsotropicElasticityTensor::set_lame_coefficients (const double & lambda, const double & mu) inline private
     {
       C[1] = lambda + 2.0 * mu;
       C[2] = lambda;
       C[3] = mu;
     }
References lambda, and Global_Parameters::mu.
update_constitutive_parameters()
void oomph::IsotropicElasticityTensor::update_constitutive_parameters (const double & nu, const double & E = 1.0) inline
Update parameters: Specify values of the Poisson's ratio and (optionally) Young's modulus (interpreted as the ratio of the actual Young's modulus to the Young's modulus (or other reference stiffness) used to non-dimensionalise stresses and tractions in the governing equations).
     {
       // Set the three indepdent components
       C[0] = 0.0;
       double lambda = E * nu / ((1.0 + nu) * (1.0 - 2.0 * nu));
       double mu = E / (2.0 * (1.0 + nu));
       this->set_lame_coefficients(lambda, mu);
     }
References Global_Physical_Variables::E, lambda, Global_Parameters::mu, and set_lame_coefficients().
Member Data Documentation
C
double oomph::IsotropicElasticityTensor::C private
StaticIndex
static const unsigned oomph::IsotropicElasticityTensor::StaticIndex static private
Initial value:
= {
    1, 0, 2, 3, 0, 1, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 0, 2, 3, 0, 1}
Translation scheme for the isotropic elasticity tensor.
Referenced by independent_component().
The documentation for this class was generated from the following files:
linear_elasticity/elasticity_tensor.h
linear_elasticity/elasticity_tensor.cc