MercuryDPM: DeletionBoundary Class Reference
DeletionBoundary Class Reference
Used for removing particles from the problem. Inherits from BaseBoundary. By default, a plane that deletes everything past it, but there are derived classes such as CubeDeletionBoundary.
#include <DeletionBoundary.h>
Public Member Functions
DeletionBoundary ()
default constructor
DeletionBoundary (DeletionBoundary const &d)
default copy constructor
~DeletionBoundary () override
destructor
DeletionBoundary * copy () const override
Copy method; creates copy on the heap and returns a pointer to it.
void set (const Vec3D &normal, Mdouble distance)
Sets boundary position based on a normal and distance.
void move (Mdouble position)
Sets the boundary's distance property to the given one.
virtual Mdouble getDistance (const Vec3D &position) const
Returns a negative value if and only if the particle is inside the boundary (and therefore to be deleted).
bool checkBoundaryAfterParticleMoved (BaseParticle *p, ParticleHandler &pH)
Checks if particle is inside the boundary, and deletes the particle if so.
void checkBoundaryAfterParticlesMove (ParticleHandler &pH) override
unsigned int getNumberOfParticlesDeleted () const
Gets the number of particles deleted by the boundary.
double getMassOfParticlesDeleted () const
double getVolumeOfParticlesDeleted () const
void reset ()
void activate ()
Turns on the DeletionBoundary.
void deactivate ()
Turns off the DeletionBoundary.
void trackOutflow (bool trackOutflow=true)
Turns on the outflow tracker.
void setTrackerCustom (std::function< void(std::ofstream &, BaseParticle *)> trackerCustom)
Sets a custom function for tracking the outflow.
void read (std::istream &is) override
Reads some boundary properties from an std::istream.
MERCURYDPM_DEPRECATED void oldRead (std::istream &is)
Deprecated read method. use DeletionBoundary::read() instead.
void write (std::ostream &os) const override
Writes the boundary properties to an std::ostream.
std::string getName () const override
Returns the name of the object.
Public Member Functions inherited from BaseBoundary
BaseBoundary ()
default constructor.
BaseBoundary (const BaseBoundary &b)
copy constructor
~BaseBoundary () override
destructor
virtual void createPeriodicParticle (BaseParticle *p UNUSED, ParticleHandler &pH UNUSED)
Creates a periodic particle in case of periodic boundaries in serial build.
virtual void createPeriodicParticles (ParticleHandler &pH UNUSED)
Creates periodic copies of given particle in case of periodic boundaries.
virtual void checkBoundaryBeforeTimeStep (DPMBase *md)
Virtual function that does things before each time step.
virtual void actionsBeforeTimeLoop ()
Virtual function that does something after DPMBase::setupInitialConditions but before the first time step.
virtual void modifyGhostAfterCreation (BaseParticle *particle, int i)
virtual void writeVTK (std::fstream &file)
void setHandler (BoundaryHandler *handler)
Sets the boundary's BoundaryHandler.
BoundaryHandler * getHandler () const
Returns the boundary's BoundaryHandler.
Public Member Functions inherited from BaseObject
BaseObject ()=default
Default constructor.
BaseObject (const BaseObject &p)=default
Copy constructor, copies all the objects BaseObject contains.
virtual ~BaseObject ()=default
virtual destructor
virtual void moveInHandler (unsigned int index)
Except that it is virtual, it does the same thing as setIndex() does.
void setIndex (unsigned int index)
Allows one to assign an index to an object in the handler/container.
void setId (unsigned long id)
Assigns a unique identifier to each object in the handler (container) which remains constant even after the object is deleted from the container/handler.
unsigned int getIndex () const
Returns the index of the object in the handler.
unsigned int getId () const
Returns the unique identifier of any particular object.
void setGroupId (unsigned groupId)
unsigned getGroupId () const
Private Attributes
Vec3D normal_
outward unit normal vector
Mdouble scaleFactor_
This is the factor to rescale the given normal vector to a unit vectors.
Mdouble distance_
The boundary's distance from the origin.
unsigned int numberOfParticlesDeleted_
Number of particles that have been deleted by this boundary.
double massDeleted_
double trackMassDeleted_
double volumeDeleted_
bool isActivated_
The DeletionBoundary is activated by default. If the DeletionBoundary is deactivated, then it deletes no particles.
bool trackOutflow_
std::ofstream tracker
std::function< void(std::ofstream &, BaseParticle *)> trackerCustom_ = [] (std::ofstream&, BaseParticle*) {}
Detailed Description
Used for removing particles from the problem. Inherits from BaseBoundary. By default, a plane that deletes everything past it, but there are derived classes such as CubeDeletionBoundary.
Constructor & Destructor Documentation
DeletionBoundary() [1/2]
DeletionBoundary::DeletionBoundary ()
default constructor
Default constructor (calls the parent-constructor of BaseBoundary as well)
         : BaseBoundary()
 {
     distance_ = std::numeric_limits<double>::quiet_NaN();
     scaleFactor_ = std::numeric_limits<double>::quiet_NaN();
     isActivated_ = true;
     trackOutflow_ = false;
     numberOfParticlesDeleted_ = 0;
     massDeleted_ = 0;
     volumeDeleted_ = 0;
     logger(DEBUG, "DeletionBoundary::DeletionBoundary() finished", true);
 }
References DEBUG, distance_, isActivated_, logger, massDeleted_, numberOfParticlesDeleted_, scaleFactor_, trackOutflow_, and volumeDeleted_.
Referenced by copy().
DeletionBoundary() [2/2]
DeletionBoundary::DeletionBoundary (DeletionBoundary const & d) inline
default copy constructor
         : normal_(d.normal_), scaleFactor_(d.scaleFactor_), distance_(d.distance_),
           numberOfParticlesDeleted_(d.numberOfParticlesDeleted_), massDeleted_(d.massDeleted_),
           volumeDeleted_(d.volumeDeleted_), isActivated_(d.isActivated_), trackOutflow_(d.trackOutflow_),
           trackerCustom_(d.trackerCustom_) {}
~DeletionBoundary()
DeletionBoundary::~DeletionBoundary () override
destructor
Destructor
 {
     tracker.close();
     logger(DEBUG, "DeletionBoundary::~DeletionBoundary() finished", true);
 }
References DEBUG, logger, and tracker.
Member Function Documentation
activate()
void DeletionBoundary::activate ()
Turns on the DeletionBoundary.
 {
     isActivated_ = true;
 }
References isActivated_.
checkBoundaryAfterParticleMoved()
bool DeletionBoundary::checkBoundaryAfterParticleMoved (BaseParticle * p, ParticleHandler & pH)
Checks if particle is inside the boundary, and deletes the particle if so.
Todo:
: MX: update the above comment
Checks if particle has passed the boundary, and if so, deletes the particle.
Parameters
[in] p pointer to the particle which is to be checked
[out] pH the particle's ParticleHandler, from which the particle is removed in case it has passed the boundary.
Returns
TRUE if the particle has actually passed the boundary and is thus deleted.
Todo:
JMFT: The mass and volume counters need to be updated in the MPI code.
 {
     if (getDistance(p->getPosition()) < 0)
     {
         if (trackOutflow_) {
             auto dpm = getHandler()->getDPMBase();
             trackMassDeleted_ += p->getMass();
             if (!tracker.is_open()) {
                 std::string name  = dpm->getName()
                         + helpers::toString(getIndex())
                         + ".out" + (NUMBER_OF_PROCESSORS==1?"":std::to_string(PROCESSOR_ID));
                 logger(INFO, "Open file %", name);
                 tracker.open(name);
                 tracker << std::setw(13) << "Time "
                         << std::setw(8) << "Species "
                         << std::setw(8) << "ID "
                         << std::setw(13) << "Position_x "
                         << std::setw(13) << "Position_y "
                         << std::setw(13) << "Position_z "
                         << std::setw(13) << "Velocity_x "
                         << std::setw(13) << "Velocity_y "
                         << std::setw(13) << "Velocity_z "
                         << std::setw(13) << "Radius "
                         << std::setw(13) << "AnVelocity_x "
                         << std::setw(13) << "AnVelocity_y "
                         << std::setw(13) << "AnVelocity_z "
                         << std::setw(13) << "Mass "
                         << std::setw(13) << "TotalMass"
                         << '\n';
             }
             tracker << std::setw(12) << dpm->getTime() << ' '
                     << std::setw(8) << p->getIndSpecies() << ' '
                     << std::setw(8) << p->getId() << ' '
                     << std::setw(12) << p->getPosition().X << ' '
                     << std::setw(12) << p->getPosition().Y << ' '
                     << std::setw(12) << p->getPosition().Z << ' '
                     << std::setw(12) << p->getVelocity().X << ' '
                     << std::setw(12) << p->getVelocity().Y << ' '
                     << std::setw(12) << p->getVelocity().Z << ' '
                     << std::setw(12) << p->getRadius() << ' '
                     << std::setw(12) << p->getAngularVelocity().X << ' '
                     << std::setw(12) << p->getAngularVelocity().Y << ' '
                     << std::setw(12) << p->getAngularVelocity().Z << ' '
                     << std::setw(12) << p->getMass() << ' '
                     << std::setw(12) << trackMassDeleted_ << '\n';
         }
         else
             trackerCustom_(tracker, p);
         #ifdef MERCURYDPM_USE_MPI
             //Check if the particle is in the mpi communication zone
             if(p->isInMPIDomain())
             {
                 //Add the particle to a list so we can flush it later on
                 //The particles are not deleted yet. This is done in dpmBase after this function is called
                 particlesToBeDeleted_.insert(p);
                 return false;
             }
             else
             {
                 pH.removeGhostObject(p->getIndex());
                 return true;
             }
         #else
             numberOfParticlesDeleted_++;
             massDeleted_ += p->getMass();
             volumeDeleted_ += p->getVolume();
             pH.removeObject(p->getIndex());
             pH.computeLargestParticle();
             pH.computeSmallestParticle();
             return true;
         #endif
     }
     else
     {
         return false;
     }
 }
References ParticleHandler::computeLargestParticle(), ParticleHandler::computeSmallestParticle(), getDistance(), BaseHandler< T >::getDPMBase(), BaseBoundary::getHandler(), BaseObject::getIndex(), INFO, logger, massDeleted_, plotDoE::name, NUMBER_OF_PROCESSORS, numberOfParticlesDeleted_, p, PROCESSOR_ID, ParticleHandler::removeGhostObject(), ParticleHandler::removeObject(), oomph::Global_string_for_annotation::string(), oomph::StringConversion::to_string(), helpers::toString(), tracker, trackerCustom_, trackMassDeleted_, trackOutflow_, and volumeDeleted_.
Referenced by checkBoundaryAfterParticlesMove().
checkBoundaryAfterParticlesMove()
void DeletionBoundary::checkBoundaryAfterParticlesMove (ParticleHandler & pH) override virtual
Todo:
MX: I changed the syntax to a more mpi compatible (and neater) code. Need to update the comments of the checkBoundaryAfterParticleMoved function
Reimplemented from BaseBoundary.
 {
     if (!isActivated_)
         return;
 #ifdef MERCURYDPM_USE_MPI
     particlesToBeDeleted_.clear();
 #endif
     for (unsigned int i = 0; i < pH.getSize(); i++)
     {
         //If the particle is deleted, change the iterator
         if (checkBoundaryAfterParticleMoved(pH.getObject(i), pH))
         {
             i--;
         }
     }
 }
References checkBoundaryAfterParticleMoved(), BaseHandler< T >::getObject(), BaseHandler< T >::getSize(), i, and isActivated_.
copy()
DeletionBoundary * DeletionBoundary::copy () const override virtual
Copy method; creates copy on the heap and returns a pointer to it.
Copy function, which creates a copy and returns a pointer to that copy (on the heap)
Returns
pointer to the copy
Implements BaseBoundary.
 {
     return new DeletionBoundary(*this);
 }
References DeletionBoundary().
deactivate()
void DeletionBoundary::deactivate ()
Turns off the DeletionBoundary.
 {
     isActivated_ = false;
 }
References isActivated_.
getDistance()
Mdouble DeletionBoundary::getDistance (const Vec3D & position) const virtual
Returns a negative value if and only if the particle is inside the boundary (and therefore to be deleted).
The default DeletionBoundary is a half-space (specified by a plane) but the geometry can be overridden (e.g. by CubeDeletionBoundary). Calculates the shortest distance between the wall and given position.
Parameters
[in] position the position of which the distance should be calculated.
Reimplemented in CubeDeletionBoundary.
 {
     return distance_ - Vec3D::dot(position, normal_);
 }
References distance_, Vec3D::dot(), and normal_.
Referenced by checkBoundaryAfterParticleMoved().
getMassOfParticlesDeleted()
double DeletionBoundary::getMassOfParticlesDeleted () const
 {
     return massDeleted_;
 }
References massDeleted_.
Referenced by BoundariesSelfTest::actionsAfterTimeStep().
getName()
std::string DeletionBoundary::getName () const override virtual
Returns the name of the object.
Returns the object's class name (i.e. 'DeletionBoundary').
Returns
the object's class name
Implements BaseObject.
 {
     return "DeletionBoundary";
 }
getNumberOfParticlesDeleted()
unsigned int DeletionBoundary::getNumberOfParticlesDeleted () const
Gets the number of particles deleted by the boundary.
Returns the number of particles deleted by this boundary. TODO For some reason, this causes a segfault — DO NOT USE. valgrind complains that 'numberOfParticlesDeleted_' is not initialised.
 {
     return numberOfParticlesDeleted_;
 }
References numberOfParticlesDeleted_.
Referenced by T_protectiveWall::actionsAfterTimeStep(), BoundariesSelfTest::actionsAfterTimeStep(), and protectiveWall::actionsAfterTimeStep().
getVolumeOfParticlesDeleted()
double DeletionBoundary::getVolumeOfParticlesDeleted () const
 {
     return volumeDeleted_;
 }
References volumeDeleted_.
Referenced by BoundariesSelfTest::actionsAfterTimeStep().
move()
void DeletionBoundary::move (Mdouble distance)
Sets the boundary's distance property to the given one.
Resets the boundary's 'distance' from the origin to be the one given.
Parameters
[in] distance the new 'distance' between boundary and origin. see also comments of DeletionBoundary::set().
 {
     distance_ = distance * scaleFactor_;
 }
References distance_, and scaleFactor_.
oldRead()
void DeletionBoundary::oldRead (std::istream & is)
Deprecated read method. use DeletionBoundary::read() instead.
the deprecated version of the read-method. Should not be used by new users!
Deprecated:
Should be gone by Mercury 2.0. Use DeletionBoundary::read() instead.
 {
     std::string dummy;
     is >> dummy >> normal_ >> dummy >> scaleFactor_ >> dummy >> distance_;
 }
References distance_, normal_, scaleFactor_, and oomph::Global_string_for_annotation::string().
read()
void DeletionBoundary::read (std::istream & is) override virtual
Reads some boundary properties from an std::istream.
Reads a number of boundary properties from the given std::istream.
Parameters
[in,out] is the istream
Implements BaseBoundary.
 {
     BaseBoundary::read(is);
     std::string dummy;
     is >> dummy >> normal_
        >> dummy >> scaleFactor_
        >> dummy >> distance_
        >> dummy >> numberOfParticlesDeleted_
        >> dummy >> massDeleted_
        >> dummy >> volumeDeleted_
        >> dummy >> isActivated_
        >> dummy >> trackOutflow_;
 }
References distance_, isActivated_, massDeleted_, normal_, numberOfParticlesDeleted_, BaseBoundary::read(), scaleFactor_, oomph::Global_string_for_annotation::string(), trackOutflow_, and volumeDeleted_.
Referenced by CubeDeletionBoundary::read().
reset()
void DeletionBoundary::reset ()
 {
     numberOfParticlesDeleted_ = 0;
     massDeleted_ = 0;
     volumeDeleted_ = 0;
 }
References massDeleted_, numberOfParticlesDeleted_, and volumeDeleted_.
set()
void DeletionBoundary::set (const Vec3D & normal, Mdouble distance)
Sets boundary position based on a normal and distance.
Defines the placing of the (2D) boundary based on the given normal and distance.
Parameters
[in] normal boundary normal vector
[in] distance 'distance' between the origin and the boundary, such that the following relation is satisfied:
\[ \mathbf{r} \cdot \mathbf{\hat{n}} = d \]
in which \(\mathbf{\hat{n}} \) and \(d \) are the given normal vector and distance, respectively. NB: If the distance is the ACTUAL distance from the origin, the normal vector must be of UNIT LENGTH for the placing of the boundary to be done correctly.
 {
     scaleFactor_ = 1. / std::sqrt(Vec3D::dot(normal, normal));
     normal_ = normal * scaleFactor_;
     distance_ = distance * scaleFactor_;
 }
References distance_, Vec3D::dot(), WallFunction::normal(), normal_, scaleFactor_, and sqrt().
Referenced by GranuHeap::actionsAfterTimeStep(), BoundariesSelfTest::BoundariesSelfTest(), FluxBoundarySelfTest::FluxBoundarySelfTest(), protectiveWall::protectiveWall(), Silo::setupInitialConditions(), FullRestartTest::setupInitialConditions(), and T_protectiveWall::T_protectiveWall().
setTrackerCustom()
void DeletionBoundary::setTrackerCustom (std::function< void(std::ofstream &, BaseParticle *)> trackerCustom) inline
Sets a custom function for tracking the outflow.
Parameters
trackerCustom The function to which the tracker ofstream and a pointer to the BaseParticle is passed.
     {
         trackOutflow_ = false;
         trackerCustom_ = trackerCustom;
     }
References trackerCustom_, and trackOutflow_.
trackOutflow()
void DeletionBoundary::trackOutflow (bool trackOutflow = true) inline
Turns on the outflow tracker.
 {trackOutflow_ = trackOutflow;}
References trackOutflow(), and trackOutflow_.
Referenced by trackOutflow().
write()
void DeletionBoundary::write (std::ostream & os) const override virtual
Writes the boundary properties to an std::ostream.
Writes the boundary properties to an std::ostream.
Parameters
[out] os the ostream the properties are to be written to.
Implements BaseBoundary.
 {
     BaseBoundary::write(os);
     os << " normal " << normal_
        << " scaleFactor " << scaleFactor_
        << " distance " << distance_
        << " numberOfParticlesDeleted " << numberOfParticlesDeleted_
        << " massDeleted " << massDeleted_
        << " volumeDeleted " << volumeDeleted_
        << " isActivated " << isActivated_
        << " trackOutflow " << trackOutflow_;
 }
References distance_, isActivated_, massDeleted_, normal_, numberOfParticlesDeleted_, scaleFactor_, trackOutflow_, volumeDeleted_, and BaseBoundary::write().
Referenced by CubeDeletionBoundary::write().
Member Data Documentation
distance_
Mdouble DeletionBoundary::distance_ private
The boundary's distance from the origin.
Referenced by DeletionBoundary(), getDistance(), move(), oldRead(), read(), set(), and write().
isActivated_
bool DeletionBoundary::isActivated_ private
The DeletionBoundary is activated by default. If the DeletionBoundary is deactivated, then it deletes no particles.
Referenced by activate(), checkBoundaryAfterParticlesMove(), deactivate(), DeletionBoundary(), read(), and write().
massDeleted_
double DeletionBoundary::massDeleted_ private
Referenced by checkBoundaryAfterParticleMoved(), DeletionBoundary(), getMassOfParticlesDeleted(), read(), reset(), and write().
normal_
Vec3D DeletionBoundary::normal_ private
outward unit normal vector
Referenced by getDistance(), oldRead(), read(), set(), and write().
numberOfParticlesDeleted_
unsigned int DeletionBoundary::numberOfParticlesDeleted_ private
Number of particles that have been deleted by this boundary.
Referenced by checkBoundaryAfterParticleMoved(), DeletionBoundary(), getNumberOfParticlesDeleted(), read(), reset(), and write().
scaleFactor_
Mdouble DeletionBoundary::scaleFactor_ private
This is the factor to rescale the given normal vector to a unit vectors.
NB: Not only the normal vector is rescaled by this factor, also the 'distance' from the origin of the boundary is scaled by this factor! Also, once the boundary position is set with DeletionBoundary::set(), the arguments of any reset of the distance_ property (i.e. usage of DeletionBoundary::move()) will be rescaled by the same factor!
Referenced by DeletionBoundary(), move(), oldRead(), read(), set(), and write().
tracker
std::ofstream DeletionBoundary::tracker private
Referenced by checkBoundaryAfterParticleMoved(), and ~DeletionBoundary().
trackerCustom_
std::function<void(std::ofstream&, BaseParticle*)> DeletionBoundary::trackerCustom_ = [] (std::ofstream&, BaseParticle*) {} private
Referenced by checkBoundaryAfterParticleMoved(), and setTrackerCustom().
trackMassDeleted_
double DeletionBoundary::trackMassDeleted_ private
Referenced by checkBoundaryAfterParticleMoved().
trackOutflow_
bool DeletionBoundary::trackOutflow_ private
Referenced by checkBoundaryAfterParticleMoved(), DeletionBoundary(), read(), setTrackerCustom(), trackOutflow(), and write().
volumeDeleted_
double DeletionBoundary::volumeDeleted_ private
Referenced by checkBoundaryAfterParticleMoved(), DeletionBoundary(), getVolumeOfParticlesDeleted(), read(), reset(), and write().
The documentation for this class was generated from the following files:
DeletionBoundary.h
DeletionBoundary.cc