MercuryDPM: Eigen::TransposeImpl< MatrixType, Dense > Class Template Reference
Eigen::TransposeImpl< MatrixType, Dense > Class Template Reference
#include <Transpose.h>
Public Types
typedef internal::TransposeImpl_base< MatrixType >::type Base
typedef std::conditional_t< internal::is_lvalue< MatrixType >::value, Scalar, const Scalar > ScalarWithConstIfNotLvalue
Public Member Functions
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index innerStride () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index outerStride () const
EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE ScalarWithConstIfNotLvalue * data ()
EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE const Scalar * data () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Scalar & coeffRef (Index rowId, Index colId) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Scalar & coeffRef (Index index) const
Member Typedef Documentation
Base
template<typename MatrixType > typedef internal::TransposeImpl_base<MatrixType>::type Eigen::TransposeImpl< MatrixType, Dense >::Base
ScalarWithConstIfNotLvalue
template<typename MatrixType > typedef std::conditional_t<internal::is_lvalue<MatrixType>::value, Scalar, const Scalar> Eigen::TransposeImpl< MatrixType, Dense >::ScalarWithConstIfNotLvalue
Member Function Documentation
coeffRef() [1/2]
template<typename MatrixType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Scalar& Eigen::TransposeImpl< MatrixType, Dense >::coeffRef (Index index) const inline
{
     return derived().nestedExpression().coeffRef(index);
   }
coeffRef() [2/2]
template<typename MatrixType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Scalar& Eigen::TransposeImpl< MatrixType, Dense >::coeffRef (Index rowId, Index colId) const inline
{
     return derived().nestedExpression().coeffRef(colId, rowId);
   }
data() [1/2]
template<typename MatrixType > EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE ScalarWithConstIfNotLvalue* Eigen::TransposeImpl< MatrixType, Dense >::data () inline constexpr
{
     return derived().nestedExpression().data();
   }
Referenced by gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenQuaternionPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), gdb.printers.EigenSparseMatrixPrinter::to_string(), and gdb.printers.EigenQuaternionPrinter::to_string().
data() [2/2]
template<typename MatrixType > EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE const Scalar* Eigen::TransposeImpl< MatrixType, Dense >::data () const inline constexpr
{
     return derived().nestedExpression().data();
   }
Referenced by gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenQuaternionPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), gdb.printers.EigenSparseMatrixPrinter::to_string(), and gdb.printers.EigenQuaternionPrinter::to_string().
innerStride()
template<typename MatrixType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index Eigen::TransposeImpl< MatrixType, Dense >::innerStride () const inline
 { return derived().nestedExpression().innerStride(); }
outerStride()
template<typename MatrixType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index Eigen::TransposeImpl< MatrixType, Dense >::outerStride () const inline
 { return derived().nestedExpression().outerStride(); }
The documentation for this class was generated from the following file:
Transpose.h