MercuryDPM: Eigen::internal::TensorUnaryExprBlock< BlockFactory, ArgTensorBlock > Class Template Reference
Eigen::internal::TensorUnaryExprBlock< BlockFactory, ArgTensorBlock > Class Template Reference
#include <TensorBlock.h>
Public Types
typedef std::conditional_t< NoArgBlockAccess, void, typename BlockFactory::template XprType< ArgXprType >::type > XprType
typedef XprScalar< XprType >::type Scalar
Public Member Functions
TensorUnaryExprBlock (const ArgTensorBlock &arg_block, const BlockFactory &factory)
TensorBlockKind kind () const
XprType expr () const
const Scalar * data () const
void cleanup ()
Private Types
typedef ArgTensorBlock::XprType ArgXprType
Private Attributes
ArgTensorBlock m_arg_block
BlockFactory m_factory
Static Private Attributes
static constexpr bool NoArgBlockAccess = internal::is_void<ArgXprType>::value
Member Typedef Documentation
ArgXprType
template<typename BlockFactory , typename ArgTensorBlock > typedef ArgTensorBlock::XprType Eigen::internal::TensorUnaryExprBlock< BlockFactory, ArgTensorBlock >::ArgXprType private
Scalar
template<typename BlockFactory , typename ArgTensorBlock > typedef XprScalar<XprType>::type Eigen::internal::TensorUnaryExprBlock< BlockFactory, ArgTensorBlock >::Scalar
XprType
template<typename BlockFactory , typename ArgTensorBlock > typedef std::conditional_t<NoArgBlockAccess, void, typename BlockFactory::template XprType<ArgXprType>::type> Eigen::internal::TensorUnaryExprBlock< BlockFactory, ArgTensorBlock >::XprType
Constructor & Destructor Documentation
TensorUnaryExprBlock()
template<typename BlockFactory , typename ArgTensorBlock > Eigen::internal::TensorUnaryExprBlock< BlockFactory, ArgTensorBlock >::TensorUnaryExprBlock (const ArgTensorBlock & arg_block, const BlockFactory & factory) inline
       : m_arg_block(arg_block), m_factory(factory) {}
Member Function Documentation
cleanup()
template<typename BlockFactory , typename ArgTensorBlock > void Eigen::internal::TensorUnaryExprBlock< BlockFactory, ArgTensorBlock >::cleanup () inline
 { m_arg_block.cleanup(); }
References Eigen::internal::TensorUnaryExprBlock< BlockFactory, ArgTensorBlock >::m_arg_block.
Referenced by framework.Frame::__init__().
data()
template<typename BlockFactory , typename ArgTensorBlock > const Scalar* Eigen::internal::TensorUnaryExprBlock< BlockFactory, ArgTensorBlock >::data () const inline
 { return NULL; }
Referenced by gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenQuaternionPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), gdb.printers.EigenSparseMatrixPrinter::to_string(), and gdb.printers.EigenQuaternionPrinter::to_string().
expr()
template<typename BlockFactory , typename ArgTensorBlock > XprType Eigen::internal::TensorUnaryExprBlock< BlockFactory, ArgTensorBlock >::expr () const inline
 { return m_factory.expr(m_arg_block.expr()); }
References Eigen::internal::TensorUnaryExprBlock< BlockFactory, ArgTensorBlock >::m_arg_block, and Eigen::internal::TensorUnaryExprBlock< BlockFactory, ArgTensorBlock >::m_factory.
kind()
template<typename BlockFactory , typename ArgTensorBlock > TensorBlockKind Eigen::internal::TensorUnaryExprBlock< BlockFactory, ArgTensorBlock >::kind () const inline
 { return internal::TensorBlockKind::kExpr; }
References Eigen::internal::kExpr.
Member Data Documentation
m_arg_block
template<typename BlockFactory , typename ArgTensorBlock > ArgTensorBlock Eigen::internal::TensorUnaryExprBlock< BlockFactory, ArgTensorBlock >::m_arg_block private
Referenced by Eigen::internal::TensorUnaryExprBlock< BlockFactory, ArgTensorBlock >::cleanup(), and Eigen::internal::TensorUnaryExprBlock< BlockFactory, ArgTensorBlock >::expr().
m_factory
template<typename BlockFactory , typename ArgTensorBlock > BlockFactory Eigen::internal::TensorUnaryExprBlock< BlockFactory, ArgTensorBlock >::m_factory private
Referenced by Eigen::internal::TensorUnaryExprBlock< BlockFactory, ArgTensorBlock >::expr().
NoArgBlockAccess
template<typename BlockFactory , typename ArgTensorBlock > constexpr bool Eigen::internal::TensorUnaryExprBlock< BlockFactory, ArgTensorBlock >::NoArgBlockAccess = internal::is_void<ArgXprType>::value static constexpr private
The documentation for this class was generated from the following file:
TensorBlock.h