MercuryDPM: fsi_channel_with_leaflet.cc File Reference
mpi/multi_domain/fsi_channel_with_leaflet/fsi_channel_with_leaflet.cc File Reference
#include "generic.h"
#include "beam.h"
#include "navier_stokes.h"
#include "multi_physics.h"
#include "meshes/channel_with_leaflet_mesh.h"
#include "meshes/one_d_lagrangian_mesh.h"
Classes
class UndeformedLeaflet
GeomObject: Undeformed straight, vertical leaflet.
class FSIChannelWithLeafletProblem< ELEMENT >
FSI leaflet in channel.
Namespaces
Global_Physical_Variables
Global variables.
Functions
double Global_Physical_Variables::flux (const double &t)
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc , char * argv[])
Driver code – pass a command line argument if you want to run the code in validation mode where it only performs a few steps
 {
 #ifdef OOMPH_HAS_MPI
  MPI_Helpers::init(argc,argv);
 #endif
   // Switch off output modifier
  oomph_info.output_modifier_pt() = &default_output_modifier;
  // Define processor-labeled output file for all on-screen stuff
  std::ofstream output_stream;
  char filename[1000];
  sprintf(filename,"OUTPUT.%i",
          MPI_Helpers::communicator_pt()->my_rank());
  output_stream.open(filename);
  oomph_info.stream_pt() = &output_stream;
  OomphLibWarning::set_stream_pt(&output_stream);
  OomphLibError::set_stream_pt(&output_stream);
  // Store command line arguments
  CommandLineArgs::setup(argc,argv);
  //Parameters for the leaflet: x-position of root and height
  double x_0 = 1.0;
  double hleaflet=0.5;
  // Number of elements in various regions of mesh
  unsigned nleft=6;
  unsigned nright=18;
  unsigned ny1=3;
  unsigned ny2=3;
  // Dimensions of fluid mesh: length to the left and right of leaflet
  // and total height
  double lleft =1.0;
  double lright=3.0;
  double htot=1.0;
  //Build the problem
  FSIChannelWithLeafletProblem<
   AlgebraicElement<RefineableQTaylorHoodElement<2> > >
   problem(lleft,lright,hleaflet,
           htot,nleft,nright,ny1,ny2,x_0);
  // Set up doc info
  DocInfo doc_info;
  doc_info.set_directory("RESLT_FSI_LEAF");
  // Trace file (only on processor zero)
  ofstream trace;
  if (problem.communicator_pt()->my_rank()==0)
   {
    sprintf(filename,"%s/trace.dat",doc_info.directory().c_str());
    trace.open(filename);
   }
  // Number of timesteps (reduced for validation)
  unsigned nstep=200;
  if (CommandLineArgs::Argc>1)
   {
    nstep=2;
   }
  //Timestep:
  double dt=0.05;
  // Initialise timestep
  problem.initialise_dt(dt);
  // Doc initial guess for steady solve
  problem.doc_solution(doc_info,trace);
  doc_info.number()++;
 #ifdef OOMPH_HAS_MPI
  // Distribute the problem (output info to screen)
  bool report_stats=true;
  if (CommandLineArgs::Argc==1)
   {
    // Distribute problem using METIS to determine the partitioning
    problem.distribute(report_stats);
   }
  else
   {
    // Command line arguments, read in partition vector (2-processor job)
    std::ifstream input_file;
    // All meshes are partitioned
    unsigned n_partition=problem.mesh_pt()->nelement();
    Vector<unsigned> in_element_partition(n_partition,0);
    // Get partition from file
    sprintf(filename,"fsi_channel_with_leaflet_partition.dat");
    input_file.open(filename);
    std::string input_string;
    for (unsigned e=0;e<n_partition;e++)
     {
      getline(input_file,input_string,'\n');
      in_element_partition[e]=atoi(input_string.c_str());
     }
    // Now distribute the (still uniformly refined) problem
    problem.distribute(in_element_partition,report_stats);
   }
 #endif
  problem.doc_solution(doc_info,trace);
  // Initial loop to increment the Reynolds number in sequence of steady solves
  //---------------------------------------------------------------------------
  unsigned n_increment=4;
  // Just do one step for validation run
  if (CommandLineArgs::Argc>1)
   {
    n_increment=1;
   }
  // Set max. number of adaptations
  unsigned max_adapt=3;
  // Just do one adaptation for validation run
  if (CommandLineArgs::Argc>1)
   {
    max_adapt=1;
   }
  Global_Physical_Variables::Re=0.0;
  for (unsigned i=0;i<n_increment;i++)
   {
    // Increase Re and ReSt (for St=1)
    Global_Physical_Variables::Re+=50.0;
    Global_Physical_Variables::ReSt=Global_Physical_Variables::Re;
    // Solve the steady problem
    std::cout << "Computing a steady solution for Re="
              <<  Global_Physical_Variables::Re << std::endl;
    problem.steady_newton_solve(max_adapt);
    problem.doc_solution(doc_info,trace);
    doc_info.number()++;
   } // reached final Reynolds number
  // Proper time-dependent run
  //--------------------------
  // Limit the number of adaptations during unsteady run to one per timestep
  max_adapt=1;
  // Don't re-set the initial conditions when adapting the mesh
  bool first = false;
  // Timestepping loop
  for (unsigned istep=0;istep<nstep;istep++)
   {
    // Solve the problem
    problem.unsteady_newton_solve(dt,max_adapt,first);
    // Output the solution
    problem.doc_solution(doc_info,trace);
    // Step number
    doc_info.number()++;
   }
 #ifdef OOMPH_HAS_MPI
  MPI_Helpers::finalize();
 #endif
 }//end of main
References oomph::CommandLineArgs::Argc, oomph::default_output_modifier, oomph::DocInfo::directory(), e(), MergeRestartFiles::filename, i, oomph::DocInfo::number(), oomph::oomph_info, oomph::OomphInfo::output_modifier_pt(), problem, Global_Physical_Variables::Re, Global_Physical_Variables::ReSt, oomph::DocInfo::set_directory(), Flag_definition::setup(), oomph::OomphInfo::stream_pt(), and oomph::Global_string_for_annotation::string().