MercuryDPM: fsi_collapsible_channel_adapt.cc File Reference
mpi/multi_domain/fsi_collapsible_channel/fsi_collapsible_channel_adapt.cc File Reference
#include <iostream>
#include "generic.h"
#include "navier_stokes.h"
#include "beam.h"
#include "meshes/one_d_lagrangian_mesh.h"
#include "meshes/collapsible_channel_mesh.h"
#include <fenv.h>
Classes
class UndeformedWall
class FSICollapsibleChannelProblem< ELEMENT >
Problem class.
Namespaces
BL_Squash
Global_Physical_Variables
Global variables.
Functions
double BL_Squash::squash_fct (const double &s)
void Global_Physical_Variables::prescribed_traction (const double &t, const Vector< double > &x, const Vector< double > &n, Vector< double > &traction)
Traction applied on the fluid at the left (inflow) boundary.
void Global_Physical_Variables::load (const Vector< double > &xi, const Vector< double > &x, const Vector< double > &N, Vector< double > &load)
Load function: Apply a constant external pressure to the beam.
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc , char * argv[])
Driver code for a collapsible channel problem with FSI. Presence of command line arguments indicates validation run with coarse resolution and small number of timesteps.
 {
 // feenableexcept(FE_INVALID | FE_DIVBYZERO | FE_OVERFLOW | FE_UNDERFLOW);
 #ifdef OOMPH_HAS_MPI
  MPI_Helpers::init(argc,argv);
 #endif
  // Store command line arguments
  CommandLineArgs::setup(argc,argv);
  // Reduction in resolution for validation run
  unsigned coarsening_factor=4;
  if (CommandLineArgs::Argc>1)
   {
    coarsening_factor=4;
   }
   // Switch off output modifier
  oomph_info.output_modifier_pt() = &default_output_modifier;
  // Define processor-labeled output file for all on-screen stuff
  std::ofstream output_stream;
  char filename[100];
  sprintf(filename,"OUTPUT.%i",MPI_Helpers::communicator_pt()->my_rank());
  output_stream.open(filename);
  oomph_info.stream_pt() = &output_stream;
  OomphLibWarning::set_stream_pt(&output_stream);
  OomphLibError::set_stream_pt(&output_stream);
  // Number of elements in the domain
  unsigned nup=20/coarsening_factor;
  unsigned ncollapsible=40/coarsening_factor;
  unsigned ndown=40/coarsening_factor;
  unsigned ny=16/coarsening_factor;
  // Length of the domain
  double lup=5.0;
  double lcollapsible=10.0;
  double ldown=10.0;
  double ly=1.0;
  // Set external pressure (on the wall stiffness scale).
  Global_Physical_Variables::P_ext = 1.0e-1;
  // Pressure on the left boundary: This is consistent with steady
  // Poiseuille flow
  Global_Physical_Variables::P_up=12.0*(lup+lcollapsible+ldown);
 #ifdef MACRO_ELEMENT_NODE_UPDATE
 #ifdef TAYLOR_HOOD
  // Build the problem with QTaylorHoodElements
  FSICollapsibleChannelProblem
   <MacroElementNodeUpdateElement<RefineableQTaylorHoodElement<2> > >
   problem(nup, ncollapsible, ndown, ny,
           lup, lcollapsible, ldown, ly);
 #else
  // Build the problem with QCrouzeixRaviartElements
  FSICollapsibleChannelProblem
   <MacroElementNodeUpdateElement<RefineableQCrouzeixRaviartElement<2> > >
   problem(nup, ncollapsible, ndown, ny,
           lup, lcollapsible, ldown, ly);
 #endif
 #else
 #ifdef TAYLOR_HOOD
  // Build the problem with QTaylorHoodElements
  FSICollapsibleChannelProblem
   <AlgebraicElement<RefineableQTaylorHoodElement<2> > >
   problem(nup, ncollapsible, ndown, ny,
           lup, lcollapsible, ldown, ly);
 #else
  // Build the problem with QCrouzeixRaviartElements
  FSICollapsibleChannelProblem
   <AlgebraicElement<RefineableQCrouzeixRaviartElement<2> > >
   problem(nup, ncollapsible, ndown, ny,
           lup, lcollapsible, ldown, ly);
 #endif
 #endif
  // Timestep. Note: Preliminary runs indicate that the period of
  // the oscillation is about 1 so this gives us 40 steps per period.
  double dt=1.0/40.0;
  // Initial time for the simulation
  double t_min=0.0;
  // Maximum time for simulation
  double t_max=3.5;
  // Initialise timestep
  problem.time_pt()->time()=t_min;
  problem.initialise_dt(dt);
  // Apply initial condition
  problem.set_initial_condition();
  //Set output directory
  DocInfo doc_info;
 #ifdef MACRO_ELEMENT_NODE_UPDATE
  doc_info.set_directory("RESLT");
 #else
  doc_info.set_directory("RESLT_ALG");
 #endif
  // Open a trace file
  ofstream trace_file;
  sprintf(filename,"%s/trace.dat",doc_info.directory().c_str());
  trace_file.open(filename);
  // Output the initial condition
  problem.doc_solution(doc_info, trace_file);
  // Increment step number
  doc_info.number()++;
  // Find number of timesteps (reduced for validation)
  unsigned nstep = unsigned((t_max-t_min)/dt);
 // unsigned nstep=10;
  if (CommandLineArgs::Argc>1)
   {
    nstep=3;
   }
  // Set targets for spatial adaptivity
  problem.bulk_mesh_pt()->max_permitted_error()=1.0e-3;
  problem.bulk_mesh_pt()->min_permitted_error()=1.0e-5;
 #ifdef OOMPH_HAS_MPI
  // Distribute the problem
  std::ifstream input_file;
  unsigned n_partition=problem.mesh_pt()->nelement();
  // Get partition from file
  Vector<unsigned> element_partition(n_partition,0);
  sprintf(filename,"fsi_collapsible_channel_partition.dat");
  input_file.open(filename);
  std::string input_string;
  for (unsigned e=0;e<n_partition;e++)
   {
    getline(input_file,input_string,'\n');
    element_partition[e]=atoi(input_string.c_str());
   }
  bool report_stats=false;
  DocInfo mesh_doc_info;
  mesh_doc_info.disable_doc();
  problem.distribute(element_partition,mesh_doc_info,report_stats);
  // Check halo schemes (on submeshes)
  problem.check_halo_schemes();
 #endif
  // When performing the first timestep, we can adapt the mesh as many times
  // as we want because the initial condition can be re-set
  unsigned max_adapt=3; // 1
  bool first=true;
  // Timestepping loop
  for (unsigned istep=0;istep<nstep;istep++)
   {
    // Solve the problem
    problem.unsteady_newton_solve(dt,max_adapt,first);
    // Outpt the solution
    problem.doc_solution(doc_info, trace_file);
    // Step number
    doc_info.number()++;
    // We've done the first step
    first=false;
    max_adapt=1;
   }
  // Close trace file.
  trace_file.close();
 #ifdef OOMPH_HAS_MPI
  MPI_Helpers::finalize();
 #endif
 }//end of main
References oomph::CommandLineArgs::Argc, oomph::default_output_modifier, oomph::DocInfo::directory(), oomph::DocInfo::disable_doc(), e(), MergeRestartFiles::filename, Mesh_Parameters::ly, oomph::DocInfo::number(), Mesh_Parameters::ny, oomph::oomph_info, oomph::OomphInfo::output_modifier_pt(), Global_Physical_Variables::P_ext, Global_Physical_Variables::P_up, problem, oomph::DocInfo::set_directory(), Flag_definition::setup(), oomph::OomphInfo::stream_pt(), and oomph::Global_string_for_annotation::string().