MercuryDPM: oomph::FSIWallElement Class Reference
oomph::FSIWallElement Class Reference
#include <fsi.h>
Public Member Functions
void describe_local_dofs (std::ostream &out, const std::string &current_string) const
FSIWallElement ()
FSIWallElement (const FSIWallElement &)=delete
Broken copy constructor.
void operator= (const FSIWallElement &)=delete
Broken assignment operator.
virtual ~FSIWallElement ()
Empty virtual destructor for safety.
void setup_fsi_wall_element (const unsigned &nlagr_solid, const unsigned &ndim_fluid)
const double & q () const
double *& q_pt ()
void enable_fluid_loading_on_both_sides ()
bool only_front_is_loaded_by_fluid () const
void exclude_external_load_data ()
void include_external_load_data ()
void disable_shear_stress_in_jacobian ()
void enable_shear_stress_in_jacobian ()
void node_update_adjacent_fluid_elements ()
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Public Member Functions inherited from oomph::SolidFiniteElement
void set_lagrangian_dimension (const unsigned &lagrangian_dimension)
virtual bool has_internal_solid_data ()
SolidFiniteElement ()
Constructor: Set defaults.
virtual ~SolidFiniteElement ()
Destructor to clean up any allocated memory.
SolidFiniteElement (const SolidFiniteElement &)=delete
Broken copy constructor.
unsigned ngeom_data () const
Broken assignment operator.
Data * geom_data_pt (const unsigned &j)
void identify_geometric_data (std::set< Data * > &geometric_data_pt)
double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
virtual void get_x_and_xi (const Vector< double > &s, Vector< double > &x_fe, Vector< double > &x, Vector< double > &xi_fe, Vector< double > &xi) const
virtual void set_macro_elem_pt (MacroElement *macro_elem_pt)
virtual void set_macro_elem_pt (MacroElement *macro_elem_pt, MacroElement *undeformed_macro_elem_pt)
void set_undeformed_macro_elem_pt (MacroElement *undeformed_macro_elem_pt)
MacroElement * undeformed_macro_elem_pt ()
Access function to pointer to "undeformed" macro element.
double dshape_lagrangian (const Vector< double > &s, Shape &psi, DShape &dpsidxi) const
virtual double dshape_lagrangian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidxi) const
double d2shape_lagrangian (const Vector< double > &s, Shape &psi, DShape &dpsidxi, DShape &d2psidxi) const
virtual double d2shape_lagrangian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidxi, DShape &d2psidxi) const
unsigned lagrangian_dimension () const
unsigned nnodal_lagrangian_type () const
Node * construct_node (const unsigned &n)
Construct the local node n and return a pointer to it.
Node * construct_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
Node * construct_boundary_node (const unsigned &n)
Node * construct_boundary_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
virtual void assign_all_generic_local_eqn_numbers (const bool &store_local_dof_pt)
double raw_lagrangian_position (const unsigned &n, const unsigned &i) const
double raw_lagrangian_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double lagrangian_position (const unsigned &n, const unsigned &i) const
Return i-th Lagrangian coordinate at local node n.
double lagrangian_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
virtual double interpolated_xi (const Vector< double > &s, const unsigned &i) const
virtual void interpolated_xi (const Vector< double > &s, Vector< double > &xi) const
virtual void interpolated_dxids (const Vector< double > &s, DenseMatrix< double > &dxids) const
virtual void J_lagrangian (const Vector< double > &s) const
virtual double J_lagrangian_at_knot (const unsigned &ipt) const
SolidInitialCondition *& solid_ic_pt ()
Pointer to object that describes the initial condition.
void enable_solve_for_consistent_newmark_accel ()
void disable_solve_for_consistent_newmark_accel ()
Set to reset the problem being solved to be the standard problem.
MultiplierFctPt & multiplier_fct_pt ()
MultiplierFctPt multiplier_fct_pt () const
virtual void get_residuals_for_solid_ic (Vector< double > &residuals)
void fill_in_residuals_for_solid_ic (Vector< double > &residuals)
void fill_in_jacobian_for_solid_ic (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_jacobian_for_newmark_accel (DenseMatrix< double > &jacobian)
void compute_norm (double &el_norm)
int position_local_eqn (const unsigned &n, const unsigned &k, const unsigned &j) const
Public Member Functions inherited from oomph::FiniteElement
void set_dimension (const unsigned &dim)
void set_nodal_dimension (const unsigned &nodal_dim)
void set_nnodal_position_type (const unsigned &nposition_type)
Set the number of types required to interpolate the coordinate.
void set_n_node (const unsigned &n)
int nodal_local_eqn (const unsigned &n, const unsigned &i) const
double dJ_eulerian_at_knot (const unsigned &ipt, Shape &psi, DenseMatrix< double > &djacobian_dX) const
FiniteElement ()
Constructor.
virtual ~FiniteElement ()
FiniteElement (const FiniteElement &)=delete
Broken copy constructor.
virtual bool local_coord_is_valid (const Vector< double > &s)
Broken assignment operator.
virtual void move_local_coord_back_into_element (Vector< double > &s) const
void get_centre_of_gravity_and_max_radius_in_terms_of_zeta (Vector< double > &cog, double &max_radius) const
virtual void local_coordinate_of_node (const unsigned &j, Vector< double > &s) const
virtual void local_fraction_of_node (const unsigned &j, Vector< double > &s_fraction)
virtual double local_one_d_fraction_of_node (const unsigned &n1d, const unsigned &i)
MacroElement * macro_elem_pt ()
Access function to pointer to macro element.
void get_x (const Vector< double > &s, Vector< double > &x) const
void get_x (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void get_x_from_macro_element (const Vector< double > &s, Vector< double > &x) const
virtual void get_x_from_macro_element (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void set_integration_scheme (Integral *const &integral_pt)
Set the spatial integration scheme.
Integral *const & integral_pt () const
Return the pointer to the integration scheme (const version)
virtual void shape (const Vector< double > &s, Shape &psi) const =0
virtual void shape_at_knot (const unsigned &ipt, Shape &psi) const
virtual void dshape_local (const Vector< double > &s, Shape &psi, DShape &dpsids) const
virtual void dshape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids) const
virtual void d2shape_local (const Vector< double > &s, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual void d2shape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual double J_eulerian (const Vector< double > &s) const
virtual double J_eulerian_at_knot (const unsigned &ipt) const
void check_J_eulerian_at_knots (bool &passed) const
void check_jacobian (const double &jacobian) const
double dshape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsi, DenseMatrix< double > &djacobian_dX, RankFourTensor< double > &d_dpsidx_dX) const
double d2shape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual double d2shape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual void assign_nodal_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void describe_nodal_local_dofs (std::ostream &out, const std::string &current_string) const
Node *& node_pt (const unsigned &n)
Return a pointer to the local node n.
Node *const & node_pt (const unsigned &n) const
Return a pointer to the local node n (const version)
unsigned nnode () const
Return the number of nodes.
virtual unsigned nnode_1d () const
double raw_nodal_position (const unsigned &n, const unsigned &i) const
double raw_nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position (const unsigned &n, const unsigned &i) const
double nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double dnodal_position_dt (const unsigned &n, const unsigned &i) const
Return the i-th component of nodal velocity: dx/dt at local node n.
double dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
virtual void get_dresidual_dnodal_coordinates (RankThreeTensor< double > &dresidual_dnodal_coordinates)
virtual void disable_ALE ()
virtual void enable_ALE ()
virtual unsigned required_nvalue (const unsigned &n) const
unsigned nnodal_position_type () const
bool has_hanging_nodes () const
unsigned nodal_dimension () const
Return the required Eulerian dimension of the nodes in this element.
virtual unsigned nvertex_node () const
virtual Node * vertex_node_pt (const unsigned &j) const
int get_node_number (Node *const &node_pt) const
virtual Node * get_node_at_local_coordinate (const Vector< double > &s) const
double raw_nodal_value (const unsigned &n, const unsigned &i) const
double raw_nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
unsigned dim () const
virtual ElementGeometry::ElementGeometry element_geometry () const
Return the geometry type of the element (either Q or T usually).
virtual double interpolated_x (const Vector< double > &s, const unsigned &i) const
Return FE interpolated coordinate x[i] at local coordinate s.
virtual double interpolated_x (const unsigned &t, const Vector< double > &s, const unsigned &i) const
virtual void interpolated_x (const Vector< double > &s, Vector< double > &x) const
Return FE interpolated position x[] at local coordinate s as Vector.
virtual void interpolated_x (const unsigned &t, const Vector< double > &s, Vector< double > &x) const
virtual double interpolated_dxdt (const Vector< double > &s, const unsigned &i, const unsigned &t)
virtual void interpolated_dxdt (const Vector< double > &s, const unsigned &t, Vector< double > &dxdt)
void position (const Vector< double > &zeta, Vector< double > &r) const
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
void dposition_dt (const Vector< double > &zeta, const unsigned &t, Vector< double > &drdt)
void interpolated_zeta (const Vector< double > &s, Vector< double > &zeta) const
void locate_zeta (const Vector< double > &zeta, GeomObject *&geom_object_pt, Vector< double > &s, const bool &use_coordinate_as_initial_guess=false)
virtual void node_update ()
virtual void identify_field_data_for_interactions (std::set< std::pair< Data *, unsigned >> &paired_field_data)
virtual double s_min () const
Min value of local coordinate.
virtual double s_max () const
Max. value of local coordinate.
double size () const
virtual double compute_physical_size () const
virtual void point_output_data (const Vector< double > &s, Vector< double > &data)
void point_output (std::ostream &outfile, const Vector< double > &s)
virtual unsigned nplot_points_paraview (const unsigned &nplot) const
virtual unsigned nsub_elements_paraview (const unsigned &nplot) const
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_output_offset_information (std::ofstream &file_out, const unsigned &nplot, unsigned &counter) const
virtual void write_paraview_type (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_offsets (std::ofstream &file_out, const unsigned &nplot, unsigned &offset_sum) const
virtual unsigned nscalar_paraview () const
virtual void scalar_value_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
virtual std::string scalar_name_paraview (const unsigned &i) const
virtual void output (std::ostream &outfile)
virtual void output (std::ostream &outfile, const unsigned &n_plot)
virtual void output (const unsigned &t, std::ostream &outfile, const unsigned &n_plot) const
virtual void output (FILE *file_pt)
virtual void output (FILE *file_pt, const unsigned &n_plot)
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output an exact solution over the element.
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output a time-dependent exact solution over the element.
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, const SolutionFunctorBase &exact_soln) const
Output a time-dependent exact solution over the element.
virtual void get_s_plot (const unsigned &i, const unsigned &nplot, Vector< double > &s, const bool &shifted_to_interior=false) const
virtual std::string tecplot_zone_string (const unsigned &nplot) const
virtual void write_tecplot_zone_footer (std::ostream &outfile, const unsigned &nplot) const
virtual void write_tecplot_zone_footer (FILE *file_pt, const unsigned &nplot) const
virtual unsigned nplot_points (const unsigned &nplot) const
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_abs_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error)
void integrate_fct (FiniteElement::SteadyExactSolutionFctPt integrand_fct_pt, Vector< double > &integral)
Integrate Vector-valued function over element.
void integrate_fct (FiniteElement::UnsteadyExactSolutionFctPt integrand_fct_pt, const double &time, Vector< double > &integral)
Integrate Vector-valued time-dep function over element.
virtual void build_face_element (const int &face_index, FaceElement *face_element_pt)
virtual unsigned self_test ()
virtual unsigned get_bulk_node_number (const int &face_index, const unsigned &i) const
virtual int face_outer_unit_normal_sign (const int &face_index) const
Get the sign of the outer unit normal on the face given by face_index.
virtual unsigned nnode_on_face () const
void face_node_number_error_check (const unsigned &i) const
Range check for face node numbers.
virtual CoordinateMappingFctPt face_to_bulk_coordinate_fct_pt (const int &face_index) const
virtual BulkCoordinateDerivativesFctPt bulk_coordinate_derivatives_fct_pt (const int &face_index) const
Public Member Functions inherited from oomph::GeneralisedElement
GeneralisedElement ()
Constructor: Initialise all pointers and all values to zero.
virtual ~GeneralisedElement ()
Virtual destructor to clean up any memory allocated by the object.
GeneralisedElement (const GeneralisedElement &)=delete
Broken copy constructor.
void operator= (const GeneralisedElement &)=delete
Broken assignment operator.
Data *& internal_data_pt (const unsigned &i)
Return a pointer to i-th internal data object.
Data *const & internal_data_pt (const unsigned &i) const
Return a pointer to i-th internal data object (const version)
Data *& external_data_pt (const unsigned &i)
Return a pointer to i-th external data object.
Data *const & external_data_pt (const unsigned &i) const
Return a pointer to i-th external data object (const version)
unsigned long eqn_number (const unsigned &ieqn_local) const
int local_eqn_number (const unsigned long &ieqn_global) const
unsigned add_external_data (Data *const &data_pt, const bool &fd=true)
bool external_data_fd (const unsigned &i) const
void exclude_external_data_fd (const unsigned &i)
void include_external_data_fd (const unsigned &i)
void flush_external_data ()
Flush all external data.
void flush_external_data (Data *const &data_pt)
Flush the object addressed by data_pt from the external data array.
unsigned ninternal_data () const
Return the number of internal data objects.
unsigned nexternal_data () const
Return the number of external data objects.
unsigned ndof () const
Return the number of equations/dofs in the element.
void dof_vector (const unsigned &t, Vector< double > &dof)
Return the vector of dof values at time level t.
void dof_pt_vector (Vector< double * > &dof_pt)
Return the vector of pointers to dof values.
void set_internal_data_time_stepper (const unsigned &i, TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void assign_internal_eqn_numbers (unsigned long &global_number, Vector< double * > &Dof_pt)
void describe_dofs (std::ostream &out, const std::string &current_string) const
void add_internal_value_pt_to_map (std::map< unsigned, double * > &map_of_value_pt)
virtual void assign_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void complete_setup_of_dependencies ()
virtual void get_residuals (Vector< double > &residuals)
virtual void get_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
virtual void get_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void get_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void get_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void get_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void get_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void get_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void get_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void get_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
virtual void compute_norm (Vector< double > &norm)
virtual unsigned ndof_types () const
virtual void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned >> &dof_lookup_list) const
Public Member Functions inherited from oomph::GeomObject
GeomObject ()
Default constructor.
GeomObject (const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim, TimeStepper *time_stepper_pt)
GeomObject (const GeomObject &dummy)=delete
Broken copy constructor.
void operator= (const GeomObject &)=delete
Broken assignment operator.
virtual ~GeomObject ()
(Empty) destructor
unsigned nlagrangian () const
Access function to # of Lagrangian coordinates.
unsigned ndim () const
Access function to # of Eulerian coordinates.
void set_nlagrangian_and_ndim (const unsigned &n_lagrangian, const unsigned &n_dim)
Set # of Lagrangian and Eulerian coordinates.
TimeStepper *& time_stepper_pt ()
TimeStepper * time_stepper_pt () const
virtual void position (const double &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void dposition (const Vector< double > &zeta, DenseMatrix< double > &drdzeta) const
virtual void d2position (const Vector< double > &zeta, RankThreeTensor< double > &ddrdzeta) const
virtual void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
Public Member Functions inherited from oomph::ElementWithExternalElement
ElementWithExternalElement ()
virtual ~ElementWithExternalElement ()
The destructor, clean up any allocated memory.
ElementWithExternalElement (const ElementWithExternalElement &)=delete
Broken copy constructor.
void operator= (const ElementWithExternalElement &)=delete
Broken assignment operator.
bool storage_has_been_allocated () const
Helper function to check if storage has actually been allocated.
FiniteElement *& external_element_pt (const unsigned &interaction_index, const unsigned &ipt)
FiniteElement *const & external_element_pt (const unsigned &interaction_index, const unsigned &ipt) const
Access function to source element, const version.
Vector< double > & external_element_local_coord (const unsigned &interaction_index, const unsigned &ipt)
Vector< double > const & external_element_local_coord (const unsigned &interaction_index, const unsigned &ipt) const
Access function to get source element's coords, const version.
void output_external_elements (std::ostream &outfile, const unsigned &interaction_index)
void initialise_external_element_storage ()
void flush_all_external_element_storage ()
Flush the storage for external elements.
void set_ninteraction (const unsigned &n_interaction)
unsigned ninteraction () const
Return the number of interactions in the element.
unsigned nexternal_interaction_field_data () const
Vector< Data * > external_interaction_field_data_pt () const
unsigned nexternal_interaction_geometric_data () const
bool add_external_geometric_data ()
Are we including external geometric data in the element's Jacobian.
bool add_external_interaction_data ()
Are we including external data in the element's Jacobian.
Vector< Data * > external_interaction_geometric_data_pt () const
void ignore_external_geometric_data ()
void ignore_external_interaction_data ()
void include_external_geometric_data ()
void include_external_interaction_data ()
bool external_geometric_data_is_included () const
Static Public Attributes
static bool Dont_warn_about_missing_adjacent_fluid_elements = false
Static flag that allows the suppression of warning messages.
Static Public Attributes inherited from oomph::FiniteElement
static double Tolerance_for_singular_jacobian = 1.0e-16
Tolerance below which the jacobian is considered singular.
static bool Accept_negative_jacobian = false
static bool Suppress_output_while_checking_for_inverted_elements
Static Public Attributes inherited from oomph::GeneralisedElement
static bool Suppress_warning_about_repeated_internal_data
static bool Suppress_warning_about_repeated_external_data = true
static double Default_fd_jacobian_step = 1.0e-8
Protected Member Functions
void update_in_internal_fd (const unsigned &i)
After an internal data change, update the nodal positions.
void reset_in_internal_fd (const unsigned &i)
void reset_after_internal_fd ()
void update_in_external_fd (const unsigned &i)
After an external data change, update the nodal positions.
void reset_in_external_fd (const unsigned &i)
void reset_after_external_fd ()
void update_in_nodal_fd (const unsigned &i)
After a nodal data change, update the nodal positions.
void reset_in_nodal_fd (const unsigned &i)
void reset_after_nodal_fd ()
void update_in_external_interaction_field_fd (const unsigned &i)
After an external field data change, update the nodal positions.
void reset_in_external_interaction_field_fd (const unsigned &i)
void reset_after_external_interaction_field_fd ()
void update_in_external_interaction_geometric_fd (const unsigned &i)
void reset_in_external_interaction_geometric_fd (const unsigned &i)
void reset_after_external_interaction_geometric_fd ()
void update_in_solid_position_fd (const unsigned &i)
After an internal data change, update the nodal positions.
void reset_in_solid_position_fd (const unsigned &i)
void reset_after_solid_position_fd ()
void fluid_load_vector (const unsigned &intpt, const Vector< double > &N, Vector< double > &load)
Protected Member Functions inherited from oomph::SolidFiniteElement
void fill_in_generic_jacobian_for_solid_ic (Vector< double > &residuals, DenseMatrix< double > &jacobian, const unsigned &flag)
void set_nnodal_lagrangian_type (const unsigned &nlagrangian_type)
virtual double local_to_lagrangian_mapping (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
double local_to_lagrangian_mapping (const DShape &dpsids, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_lagrangian_mapping_diagonal (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual void assign_solid_local_eqn_numbers (const bool &store_local_dof)
Assign local equation numbers for the solid equations in the element.
void describe_solid_local_dofs (std::ostream &out, const std::string &current_string) const
Classifies dofs locally for solid specific aspects.
virtual void fill_in_jacobian_from_solid_position_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_jacobian_from_solid_position_by_fd (DenseMatrix< double > &jacobian)
virtual void update_before_solid_position_fd ()
Protected Member Functions inherited from oomph::FiniteElement
virtual void assemble_local_to_eulerian_jacobian (const DShape &dpsids, DenseMatrix< double > &jacobian) const
virtual void assemble_local_to_eulerian_jacobian2 (const DShape &d2psids, DenseMatrix< double > &jacobian2) const
virtual void assemble_eulerian_base_vectors (const DShape &dpsids, DenseMatrix< double > &interpolated_G) const
template<unsigned DIM>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double invert_jacobian_mapping (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping_diagonal (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual void dJ_eulerian_dnodal_coordinates (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<unsigned DIM>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
virtual void d_dshape_eulerian_dnodal_coordinates (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<unsigned DIM>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
virtual void transform_derivatives (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
void transform_derivatives_diagonal (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
virtual void transform_second_derivatives (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
virtual void fill_in_jacobian_from_nodal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_jacobian_from_nodal_by_fd (DenseMatrix< double > &jacobian)
virtual void update_before_nodal_fd ()
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Zero-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
One-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Two-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
Protected Member Functions inherited from oomph::GeneralisedElement
unsigned add_internal_data (Data *const &data_pt, const bool &fd=true)
bool internal_data_fd (const unsigned &i) const
void exclude_internal_data_fd (const unsigned &i)
void include_internal_data_fd (const unsigned &i)
void clear_global_eqn_numbers ()
void add_global_eqn_numbers (std::deque< unsigned long > const &global_eqn_numbers, std::deque< double * > const &global_dof_pt)
virtual void assign_additional_local_eqn_numbers ()
int internal_local_eqn (const unsigned &i, const unsigned &j) const
int external_local_eqn (const unsigned &i, const unsigned &j)
virtual void fill_in_contribution_to_residuals (Vector< double > &residuals)
void fill_in_jacobian_from_internal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_internal_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
virtual void update_before_internal_fd ()
virtual void update_before_external_fd ()
virtual void fill_in_contribution_to_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void fill_in_contribution_to_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void fill_in_contribution_to_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void fill_in_contribution_to_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void fill_in_contribution_to_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
Protected Member Functions inherited from oomph::ElementWithExternalElement
void assign_internal_and_external_local_eqn_numbers (const bool &store_local_dof_pt)
void assign_external_interaction_data_local_eqn_numbers (const bool &store_local_dof_pt)
void fill_in_jacobian_from_external_interaction_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_jacobian_from_external_interaction_by_fd (DenseMatrix< double > &jacobian)
void fill_in_jacobian_from_external_interaction_field_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_jacobian_from_external_interaction_field_by_fd (DenseMatrix< double > &jacobian)
void fill_in_jacobian_from_external_interaction_geometric_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_jacobian_from_external_interaction_geometric_by_fd (DenseMatrix< double > &jacobian)
virtual void update_before_external_interaction_field_fd ()
virtual void update_before_external_interaction_geometric_fd ()
Private Member Functions
void identify_all_field_data_for_external_interaction (Vector< std::set< FiniteElement * >> const &external_elements_pt, std::set< std::pair< Data *, unsigned >> &paired_iteraction_data)
void identify_all_geometric_data_for_external_interaction (Vector< std::set< FiniteElement * >> const &external_elements_pt, std::set< Data * > &external_geometric_data_pt)
Private Attributes
bool Only_front_is_loaded_by_fluid
double * Q_pt
bool Ignore_shear_stress_in_jacobian
Static Private Attributes
static double Default_Q_Value = 1.0
Additional Inherited Members
Public Types inherited from oomph::SolidFiniteElement
typedef double(* MultiplierFctPt) (const Vector< double > &xi)
Public Types inherited from oomph::FiniteElement
typedef void(* SteadyExactSolutionFctPt) (const Vector< double > &, Vector< double > &)
typedef void(* UnsteadyExactSolutionFctPt) (const double &, const Vector< double > &, Vector< double > &)
Protected Attributes inherited from oomph::SolidFiniteElement
MacroElement * Undeformed_macro_elem_pt
Pointer to the element's "undeformed" macro element (NULL by default)
SolidInitialCondition * Solid_ic_pt
Pointer to object that specifies the initial condition.
bool Solve_for_consistent_newmark_accel_flag
Protected Attributes inherited from oomph::FiniteElement
MacroElement * Macro_elem_pt
Pointer to the element's macro element (NULL by default)
Protected Attributes inherited from oomph::GeomObject
unsigned NLagrangian
Number of Lagrangian (intrinsic) coordinates.
unsigned Ndim
Number of Eulerian coordinates.
TimeStepper * Geom_object_time_stepper_pt
Protected Attributes inherited from oomph::ElementWithExternalElement
bool Add_external_interaction_data
Boolean flag to indicate whether to include the external data.
bool Add_external_geometric_data
Boolean flag to indicate whether to include the external geometric data.
Data ** External_interaction_field_data_pt
Data ** External_interaction_geometric_data_pt
Static Protected Attributes inherited from oomph::FiniteElement
static const unsigned Default_Initial_Nvalue = 0
Default value for the number of values at a node.
static const double Node_location_tolerance = 1.0e-14
static const unsigned N2deriv [] = {0, 1, 3, 6}
Static Protected Attributes inherited from oomph::GeneralisedElement
static DenseMatrix< double > Dummy_matrix
static std::deque< double * > Dof_pt_deque
Detailed Description
////////////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////////// This is a base class for all SolidFiniteElements that participate in FSI computations. These elements provide interfaces and generic funcionality for the two additional roles that SolidFiniteElements play in FSI problems:
They parameterise the domain boundary for the fluid domain. To allow them to play this role, FSIWallElements are derived from the SolidFiniteElement and the GeomObject class, indicating that the every specific FSIWallElement must implement the pure virtual function GeomObject::position(...) which should compute the position vector to a point in the SolidFiniteElement, parametrised by its local coordinates.
In FSI problems fluid exerts a traction onto the wall and this traction must be added to any other load terms (such as an external pressure acting on an elastic pipe) that are already applied to the SolidFiniteElements by other means.
The fluid-traction on the SolidFiniteElements depends on the fluid variables (velocities and pressures) in those fluid elements that are adjacent to the SolidFiniteElements' Gauss points. In an FSI problem these velocities and pressures are unknowns in the overall problem and the dependency of the SolidFiniteElement's residual vector on these unknowns must be taken into account when computing the element's Jacobian matrix.
For each Gauss point in the FSIWallElement, we therefore store:
[a] pointer[s] to the FSIFluidElement[s] that is [are] "adjacent" to the Gauss point in the FSIWallElement.
the vector[s] of the local coordinates (in the fluid element[s]) that identify the point in the fluid element that is (deemed to be) "opposite" that Gauss point. (Note that we do not require the discretisations of the fluid and solid domains to match exactly, therefore, small "gaps" may occur between fluid and solid elements.)
By default, each FSIWallElement is assumed to be exposed to fluid loading only on one of its faces. For elements that are immersed into fluid, so that a fluid traction is "exerted from both sides", the element can store pointers to multiple adjacent fluid elements (and local coordindates in these). This capability must be enabled by a call to FSIWallElement::enable_fluid_loading_on_both_sides().
Since the fluid traction can involve derivatives of the velocity (think of Newtonian fluids), the traction is also affected by changes in the nodal positions of the adjacent fluid elements. Since fluid and solid discretisations are not required to match, the nodal positions in an adjacent fluid element can be affected by the positional variables in another FSIWallElement. To capture this influence, we provide the function FSIWallElement::node_update_adjacent_fluid_elements() which does exactly what it says....
Finally, since oomph-lib's fluid and solid elements tend to employ different non-dimensionalisations for the stresses, the fluid traction (computed by the adjacent fluid element, on the fluid stress-scale) may have to be scaled by the ratio \(Q \) of the stresses used to non-dimensionalise the two sets of stresses. For instance, for a fluid stress non-dimensionalisation based on the viscous scale \(\mu U / L\) (as in oomph-lib's Navier-Stokes elements) and a non-dimensionalisation of the solid mechanics stresses, based on a Young's modulus \(E \), as in oomph-lib's KirchhoffLoveBeamElements, the stress ratio is given by
\[ Q=\frac{\mu U}{LE} \]
For other wall/fluid element combinations the definition of \(Q \) will differ – check the documentation and/or implementation to see which parameters are used to non-dimensionalise the stresses in the respective elements!
The function FSIWallElement::fluid_load_vector(...) computes the fluid traction on the wall on the wall stress-scale. This function may be called in the get_load (say) function of a specific FSIWallElement to add the fluid load to the other tractions that may already be applied to the element by other means. By default a stress-ratio of \(Q = 1 \) is used but this may be overwritten with the access function FSIWallElement::q_pt().
Constructor & Destructor Documentation
FSIWallElement() [1/2]
oomph::FSIWallElement::FSIWallElement () inline
Constructor. Note that element is not fully-functional until its setup_fsi_wall_element() function has been called!
       : Only_front_is_loaded_by_fluid(true),
         Q_pt(&Default_Q_Value),
         Ignore_shear_stress_in_jacobian(false)
     {
     }
FSIWallElement() [2/2]
oomph::FSIWallElement::FSIWallElement (const FSIWallElement &) delete
Broken copy constructor.
~FSIWallElement()
virtual oomph::FSIWallElement::~FSIWallElement () inline virtual
Empty virtual destructor for safety.
 {}
Member Function Documentation
describe_local_dofs()
void oomph::FSIWallElement::describe_local_dofs (std::ostream & out, const std::string & current_string) const virtual
Function to describe the local dofs of the element. The ostream specifies the output stream to which the description is written; the string stores the currently assembled output that is ultimately written to the output stream by Data::describe_dofs(...); it is typically built up incrementally as we descend through the call hierarchy of this function when called from Problem::describe_dofs(...)
Reimplemented from oomph::ElementWithExternalElement.
   {
     // Call the standard finite element classification.
     FiniteElement::describe_local_dofs(out, current_string);
     describe_solid_local_dofs(out, current_string);
     // Find the number of external field data
     const unsigned n_external_field_data = nexternal_interaction_field_data();
     // Now loop over the field data again to assign local equation numbers
     for (unsigned i = 0; i < n_external_field_data; i++)
     {
       std::stringstream conversion;
       conversion << " of External Interaction Field Data " << i
                  << current_string;
       std::string in(conversion.str());
       External_interaction_field_data_pt[i]->describe_dofs(out, in);
     }
     // Find the number of external geometric data
     unsigned n_external_geom_data = nexternal_interaction_geometric_data();
     // Now loop over the field data again assign local equation numbers
     for (unsigned i = 0; i < n_external_geom_data; i++)
     {
       std::stringstream conversion;
       conversion << " of External Interaction Geometric Data " << i
                  << current_string;
       std::string in(conversion.str());
       External_interaction_geometric_data_pt[i]->describe_dofs(out, in);
     }
   }
References oomph::Data::describe_dofs(), oomph::FiniteElement::describe_local_dofs(), oomph::SolidFiniteElement::describe_solid_local_dofs(), oomph::ElementWithExternalElement::External_interaction_field_data_pt, oomph::ElementWithExternalElement::External_interaction_geometric_data_pt, i, oomph::ElementWithExternalElement::nexternal_interaction_field_data(), oomph::ElementWithExternalElement::nexternal_interaction_geometric_data(), out(), and oomph::Global_string_for_annotation::string().
disable_shear_stress_in_jacobian()
void oomph::FSIWallElement::disable_shear_stress_in_jacobian () inline
Call this function to ignore shear stress component of load when calculating the Jacobian, i.e. to ignore fluid velocity Data in the FSIFluidElement and "far away" geometric Data that affects nodal positions in the FSIFluidElement, also to bypass node updates in the FSIFluidElement. This functionality is provided to allow the user to deem the coupling to the shear stress component of the fluid equations to be irrelevant.
     {
       Ignore_shear_stress_in_jacobian = true;
     }
References Ignore_shear_stress_in_jacobian.
Referenced by FSICollapsibleChannelProblem< ELEMENT >::FSICollapsibleChannelProblem().
enable_fluid_loading_on_both_sides()
void oomph::FSIWallElement::enable_fluid_loading_on_both_sides ()
Allow element to be loaded by fluid on both sides. (Resizes containers for lookup schemes and initialises data associated with elements at the "back" of the FSIWallElement to NULL.
   {
     // Both faces are loaded
     Only_front_is_loaded_by_fluid = false;
     // Set source element storage - two interactions
     this->set_ninteraction(2);
   }
References Only_front_is_loaded_by_fluid, and oomph::ElementWithExternalElement::set_ninteraction().
Referenced by FSIChannelWithLeafletProblem< ELEMENT >::FSIChannelWithLeafletProblem().
enable_shear_stress_in_jacobian()
void oomph::FSIWallElement::enable_shear_stress_in_jacobian () inline
Call thi function to re-enable calculation of the shear stress componnent of load when calculating the Jacobian (the default)
     {
       Ignore_shear_stress_in_jacobian = false;
     }
References Ignore_shear_stress_in_jacobian.
Referenced by FSICollapsibleChannelProblem< ELEMENT >::FSICollapsibleChannelProblem().
exclude_external_load_data()
void oomph::FSIWallElement::exclude_external_load_data () inline
Do not include any external data that affects the load in the computation of element's Jacobian matrix. This functionality is provided to allow the "user" to deem the coupling to the fluid equations to be irrelevant and to facilitate the solution of a auxiliary solids-only problems, e.g. during the assignment of initial conditions for a time-dependent FSI problem.
     {
       Add_external_interaction_data = false;
     }
References oomph::ElementWithExternalElement::Add_external_interaction_data.
fill_in_contribution_to_jacobian()
void oomph::FSIWallElement::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) inline virtual
Fill in the element's contribution to the Jacobian matrix and the residual vector: Done by finite differencing the residual vector w.r.t. all nodal, internal, external and load Data.
Reimplemented from oomph::ElementWithExternalElement.
Reimplemented in oomph::RefineableFSISolidTractionElement< ELEMENT, DIM >, oomph::FSISolidTractionElement< ELEMENT, DIM >, and oomph::FSIDiagHermiteShellElement.
     {
       // Add the contribution to the residuals
       fill_in_contribution_to_residuals(residuals);
       // Solve for the consistent acceleraction in the Newmark scheme
       if (Solve_for_consistent_newmark_accel_flag)
       {
         fill_in_jacobian_for_newmark_accel(jacobian);
         return;
       }
       // Allocate storage for the full residuals (residuals of the entire
       // element)
       Vector<double> full_residuals(this->ndof());
       // Get the residuals for the entire element
       get_residuals(full_residuals);
       // Add the internal and external by finite differences
       fill_in_jacobian_from_internal_by_fd(full_residuals, jacobian);
       fill_in_jacobian_from_external_by_fd(full_residuals, jacobian);
       fill_in_jacobian_from_nodal_by_fd(full_residuals, jacobian);
       fill_in_jacobian_from_solid_position_by_fd(jacobian);
       fill_in_jacobian_from_external_interaction_by_fd(full_residuals,
                                                        jacobian);
     }
References oomph::GeneralisedElement::fill_in_contribution_to_residuals(), oomph::SolidFiniteElement::fill_in_jacobian_for_newmark_accel(), oomph::GeneralisedElement::fill_in_jacobian_from_external_by_fd(), oomph::ElementWithExternalElement::fill_in_jacobian_from_external_interaction_by_fd(), oomph::GeneralisedElement::fill_in_jacobian_from_internal_by_fd(), oomph::FiniteElement::fill_in_jacobian_from_nodal_by_fd(), oomph::SolidFiniteElement::fill_in_jacobian_from_solid_position_by_fd(), oomph::GeneralisedElement::get_residuals(), oomph::GeneralisedElement::ndof(), and oomph::SolidFiniteElement::Solve_for_consistent_newmark_accel_flag.
fluid_load_vector()
void oomph::FSIWallElement::fluid_load_vector (const unsigned & intpt, const Vector< double > & N, Vector< double > & load) protected
Get FE Jacobian by systematic finite differencing w.r.t. nodal positition Data, internal and external Data and any load Data that is not included in the previous categories. This is a re-implementation of the generic FD routines with they key difference being that any updates of values are followed by a node update in the adjacent fluid elements since their position (and hence the shear stresses they exert onto the solid) may be indirectly affected by these. For greater efficiency this may be overloaded in derived classes, e.g. if it is known that for a specific FSIWallElement, the internal Data does not affect the nodal positions in adjacent fluid elements. Get the contribution to the load vector provided by the adjacent fluid element: Pass number of integration point in solid element, and the unit normal vector (pointing into the fluid!) and return the load vector. Note that the load is non-dimensionalised on the wall-stress scale, i.e. it is obtained by computing the traction (on the fluid stress-scale) from the adjacent fluid element and then multiplying it by the stress-scale-ratio \(Q. \).
Get the contribution to the load vector provided by the adjacent fluid element: Pass number of integration point in solid element, and the unit normal vector (pointing into the fluid on the "front" of the FSIWallElement) and return the load vector. Note that the load is non-dimensionalised on the wall-stress scale, i.e. it is obtained by computing the traction (on the fluid stress-scale) from the adjacent fluid element and then multiplying it by the stress-scale-ratio \(Q. \). If element is loaded on both sides, the fluid load computed from the reverse element is subtracted, because it's computed with the same normal vector.
   {
     // Size of load vector
     unsigned n_load = load.size();
     // Initialise
     for (unsigned i = 0; i < n_load; i++) load[i] = 0.0;
     // Create vector for fluid load
     Vector<double> fluid_load(n_load);
     // Loop over front and back if required: Get number of fluid-loaded faces
     unsigned n_loaded_face = 2;
     if (Only_front_is_loaded_by_fluid) n_loaded_face = 1;
     for (unsigned face = 0; face < n_loaded_face; face++)
     {
       // Get the local coordinate in the fluid element (copy
       // operation for Vector)
       Vector<double> s_adjacent(external_element_local_coord(face, intpt));
       // Call the load function for adjacent element
       FSIFluidElement* el_f_pt =
         dynamic_cast<FSIFluidElement*>(external_element_pt(face, intpt));
       if (el_f_pt != 0)
       {
         el_f_pt->get_load(s_adjacent, N, fluid_load);
       }
       else
       {
 #ifdef PARANOID
         if (!Dont_warn_about_missing_adjacent_fluid_elements)
         {
           std::ostringstream warning_stream;
           warning_stream
             << "Info: No adjacent element set in FSIWallElement.\n\n"
             << "Note: you can disable this message by setting \n      "
             << "FSIWallElement::Dont_warn_about_missing_adjacent_fluid_elements"
             << "\n      to true or recompiling without PARANOID.\n";
           OomphLibWarning(warning_stream.str(),
                           "FSIWallElement::fluid_load_vector()",
                           OOMPH_EXCEPTION_LOCATION);
         }
 #endif
       }
       // Adjust sign of fluid traction. If normal on the front
       // points into the fluid, the normal at the back points away
       // from it.
       double sign = 1.0;
       if (face == 1) sign = -1.0;
       // The load is scaled by the stress-scale ratio Q
       for (unsigned i = 0; i < n_load; i++)
       {
         load[i] += fluid_load[i] * sign * q();
       }
     } // end of loop over faces
   }
References Dont_warn_about_missing_adjacent_fluid_elements, oomph::ElementWithExternalElement::external_element_local_coord(), oomph::ElementWithExternalElement::external_element_pt(), oomph::FSIFluidElement::get_load(), i, load(), N, Only_front_is_loaded_by_fluid, OOMPH_EXCEPTION_LOCATION, q(), and SYCL::sign().
Referenced by oomph::FSISolidTractionElement< ELEMENT, DIM >::get_traction(), oomph::FSIHermiteBeamElement::load_vector(), oomph::FSIDiagHermiteShellElement::load_vector(), and oomph::FSIDiagHermiteShellElement::load_vector_for_rate_of_work_computation().
identify_all_field_data_for_external_interaction()
void oomph::FSIWallElement::identify_all_field_data_for_external_interaction (Vector< std::set< FiniteElement * >> const & external_elements_pt, std::set< std::pair< Data *, unsigned >> & paired_interaction_data) private virtual
Overload the function that must return all field data involved in the interactions from the external (fluid) element. It allows the velocity degrees of freedom to be ignored if we want to ignore the shear stresses when computing the Jacobian.
Reimplemented from oomph::ElementWithExternalElement.
   {
     // Loop over each inteaction
     const unsigned n_interaction = this->ninteraction();
     for (unsigned i = 0; i < n_interaction; i++)
     {
       // Loop over each element in the set
       for (std::set<FiniteElement*>::const_iterator it =
              external_elements_pt[i].begin();
            it != external_elements_pt[i].end();
            it++)
       {
         // Cast the element  the specific fluid element
         FSIFluidElement* external_fluid_el_pt =
           dynamic_cast<FSIFluidElement*>(*it);
         // Only add pressure load if so desired
         if (Ignore_shear_stress_in_jacobian)
         {
           // Add the "pressure" load data
           external_fluid_el_pt->identify_pressure_data(paired_interaction_data);
         }
         else
         {
           // Add the "direct" load data (usually velocities and pressures)
           // to the set
           external_fluid_el_pt->identify_load_data(paired_interaction_data);
         }
       }
     } // End of loop over interactions
   }
References i, oomph::FSIFluidElement::identify_load_data(), oomph::FSIFluidElement::identify_pressure_data(), Ignore_shear_stress_in_jacobian, and oomph::ElementWithExternalElement::ninteraction().
identify_all_geometric_data_for_external_interaction()
void oomph::FSIWallElement::identify_all_geometric_data_for_external_interaction (Vector< std::set< FiniteElement * >> const & external_elements_pt, std::set< Data * > & external_geometric_data_pt) private virtual
Function that must return all geometric data involved in the desired interactions from the external element
Reimplemented from oomph::ElementWithExternalElement.
   {
     // If we are ignoring the shear stress, then we can ignore all
     // external geometric data
     if (Ignore_shear_stress_in_jacobian)
     {
       return;
     }
     else
     {
       // Loop over each inteaction
       const unsigned n_interaction = this->ninteraction();
       for (unsigned i = 0; i < n_interaction; i++)
       {
         // Loop over each element in the set
         for (std::set<FiniteElement*>::const_iterator it =
                external_elements_pt[i].begin();
              it != external_elements_pt[i].end();
              it++)
         {
           (*it)->identify_geometric_data(external_geometric_data_pt);
         }
       }
     }
   }
References i, Ignore_shear_stress_in_jacobian, and oomph::ElementWithExternalElement::ninteraction().
include_external_load_data()
void oomph::FSIWallElement::include_external_load_data () inline
Include all external fluid data that affects the load in the computation of the element's Jacobian matrix
     {
       Add_external_interaction_data = true;
       Ignore_shear_stress_in_jacobian = false;
     }
References oomph::ElementWithExternalElement::Add_external_interaction_data, and Ignore_shear_stress_in_jacobian.
node_update_adjacent_fluid_elements()
void oomph::FSIWallElement::node_update_adjacent_fluid_elements ()
Update the nodal positions in all fluid elements that affect the traction on this FSIWallElement
   {
     // Don't update elements repeatedly
     std::map<FSIFluidElement*, bool> done;
     // Number of integration points
     unsigned n_intpt = integral_pt()->nweight();
     // Loop over front and back if required: Get number of fluid-loaded faces
     unsigned n_loaded_face = 2;
     if (Only_front_is_loaded_by_fluid) n_loaded_face = 1;
     for (unsigned face = 0; face < n_loaded_face; face++)
     {
       // Loop over all integration points in wall element
       for (unsigned iint = 0; iint < n_intpt; iint++)
       {
         // Get fluid element that affects this integration point
         FSIFluidElement* el_f_pt =
           dynamic_cast<FSIFluidElement*>(external_element_pt(face, iint));
         // Is there an adjacent fluid element?
         if (el_f_pt != 0)
         {
           // Have we updated its positions yet?
           if (!done[el_f_pt])
           {
             // Update nodal positions
             el_f_pt->node_update();
             done[el_f_pt] = true;
           }
         }
       }
     }
   }
References oomph::ElementWithExternalElement::external_element_pt(), oomph::FiniteElement::integral_pt(), oomph::FiniteElement::node_update(), oomph::Integral::nweight(), and Only_front_is_loaded_by_fluid.
Referenced by reset_after_external_fd(), reset_after_external_interaction_field_fd(), reset_after_external_interaction_geometric_fd(), reset_after_internal_fd(), reset_after_nodal_fd(), reset_after_solid_position_fd(), update_in_external_fd(), update_in_external_interaction_field_fd(), update_in_external_interaction_geometric_fd(), update_in_internal_fd(), update_in_nodal_fd(), and update_in_solid_position_fd().
only_front_is_loaded_by_fluid()
bool oomph::FSIWallElement::only_front_is_loaded_by_fluid () const inline
Is the element exposed to (and hence loaded by) fluid only on its "front"? True by default. This flag is set to false if the FSIWallElement is immersed in fluid in which case each integration point is loaded by two adjacent fluid elements, one at the "front" and one at the "back". This is a read-only function – the ability have loading from both sides must be enabled by a call to FSIWallElement::enable_fluid_loading_on_both_sides();
     {
       return Only_front_is_loaded_by_fluid;
     }
References Only_front_is_loaded_by_fluid.
Referenced by oomph::FSI_functions::doc_fsi().
operator=()
void oomph::FSIWallElement::operator= (const FSIWallElement &) delete
Broken assignment operator.
q()
const double& oomph::FSIWallElement::q () const inline
Return the ratio of the stress scales used to non-dimensionalise the fluid and solid equations. E.g. \(Q = \mu U/(LE) \) if the fluid mechanics stresses (pressures) are scaled on the viscous scale \(\mu U / L\) and the solid mechanics stresses on the solid's Young's modulus \(E \).
     {
       return *Q_pt;
     }
References Q_pt.
Referenced by fluid_load_vector().
q_pt()
double*& oomph::FSIWallElement::q_pt () inline
Return a pointer the ratio of stress scales used to non-dimensionalise the fluid and solid equations.
     {
       return Q_pt;
     }
References Q_pt.
Referenced by TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::actions_after_distribute(), AirwayReopeningProblem< ELEMENT >::AirwayReopeningProblem(), TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::build_mesh(), PseudoElasticCollapsibleChannelProblem< FLUID_ELEMENT, SOLID_ELEMENT >::create_fsi_traction_elements(), UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::create_fsi_traction_elements(), FSIChannelWithLeafletProblem< ELEMENT >::FSIChannelWithLeafletProblem(), FSICollapsibleChannelProblem< ELEMENT >::FSICollapsibleChannelProblem(), FSIDrivenCavityProblem< ELEMENT >::FSIDrivenCavityProblem(), FSIRingProblem::FSIRingProblem(), TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::generic_actions_after(), and TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::TurekProblem().
reset_after_external_fd()
void oomph::FSIWallElement::reset_after_external_fd () inline protected virtual
Function that is call after the finite differencing of the external data. This may be overloaded to reset any dependent variables that may have changed during the finite differencing.
Reimplemented from oomph::GeneralisedElement.
     {
       if (!Ignore_shear_stress_in_jacobian)
       {
         node_update_adjacent_fluid_elements();
       }
     }
References Ignore_shear_stress_in_jacobian, and node_update_adjacent_fluid_elements().
reset_after_external_interaction_field_fd()
void oomph::FSIWallElement::reset_after_external_interaction_field_fd () inline protected virtual
Function that is call after the finite differencing of the external interaction data associated with external fields This may be overloaded to reset any dependent variables that may have changed during the finite differencing.
Reimplemented from oomph::ElementWithExternalElement.
     {
       if (!Ignore_shear_stress_in_jacobian)
       {
         node_update_adjacent_fluid_elements();
       }
     }
References Ignore_shear_stress_in_jacobian, and node_update_adjacent_fluid_elements().
reset_after_external_interaction_geometric_fd()
void oomph::FSIWallElement::reset_after_external_interaction_geometric_fd () inline protected virtual
Function that is call after the finite differencing of the external interaction data associated with external geometry. This may be overloaded to reset any dependent variables that may have changed during the finite differencing.
Reimplemented from oomph::ElementWithExternalElement.
     {
       if (!Ignore_shear_stress_in_jacobian)
       {
         node_update_adjacent_fluid_elements();
       }
     }
References Ignore_shear_stress_in_jacobian, and node_update_adjacent_fluid_elements().
reset_after_internal_fd()
void oomph::FSIWallElement::reset_after_internal_fd () inline protected virtual
Function that is call after the finite differencing of the internal data. This may be overloaded to reset any dependent variables that may have changed during the finite differencing.
Reimplemented from oomph::GeneralisedElement.
     {
       if (!Ignore_shear_stress_in_jacobian)
       {
         node_update_adjacent_fluid_elements();
       }
     }
References Ignore_shear_stress_in_jacobian, and node_update_adjacent_fluid_elements().
reset_after_nodal_fd()
void oomph::FSIWallElement::reset_after_nodal_fd () inline protected virtual
Function that is call after the finite differencing of the nodal data. This may be overloaded to reset any dependent variables that may have changed during the finite differencing.
Reimplemented from oomph::FiniteElement.
     {
       if (!Ignore_shear_stress_in_jacobian)
       {
         node_update_adjacent_fluid_elements();
       }
     }
References Ignore_shear_stress_in_jacobian, and node_update_adjacent_fluid_elements().
reset_after_solid_position_fd()
void oomph::FSIWallElement::reset_after_solid_position_fd () inline protected virtual
Function that is call after the finite differencing of the solid position data. This may be overloaded to reset any dependent variables that may have changed during the finite differencing.
Reimplemented from oomph::SolidFiniteElement.
     {
       if (!Ignore_shear_stress_in_jacobian)
       {
         node_update_adjacent_fluid_elements();
       }
     }
References Ignore_shear_stress_in_jacobian, and node_update_adjacent_fluid_elements().
reset_in_external_fd()
void oomph::FSIWallElement::reset_in_external_fd (const unsigned & i) inline protected virtual
Function called within the finite difference loop for external data after the values in the i-th external data object are reset. The default behaviour is to call the update function.
Reimplemented from oomph::GeneralisedElement.
 {}
reset_in_external_interaction_field_fd()
void oomph::FSIWallElement::reset_in_external_interaction_field_fd (const unsigned & i) inline protected virtual
Function called within the finite difference loop for external interaction data after the values in the i-th external interaction data object associated with external fields are reset. The default behaviour is to call the update function.
Reimplemented from oomph::ElementWithExternalElement.
 {}
reset_in_external_interaction_geometric_fd()
void oomph::FSIWallElement::reset_in_external_interaction_geometric_fd (const unsigned & i) inline protected virtual
Function called within the finite difference loop for external interaction data after the values in the i-th external interaction data object associated with external geometry are reset. The default behaviour is to call the update function.
Reimplemented from oomph::ElementWithExternalElement.
 {}
reset_in_internal_fd()
void oomph::FSIWallElement::reset_in_internal_fd (const unsigned & i) inline protected virtual
Function called within the finite difference loop for internal data after the values in the i-th external data object are reset. The default behaviour is to call the update function.
Reimplemented from oomph::GeneralisedElement.
 {}
reset_in_nodal_fd()
void oomph::FSIWallElement::reset_in_nodal_fd (const unsigned & i) inline protected virtual
Function called within the finite difference loop for nodal data after the i-th nodal values is reset. The default behaviour is to call the update function.
Reimplemented from oomph::FiniteElement.
 {}
reset_in_solid_position_fd()
void oomph::FSIWallElement::reset_in_solid_position_fd (const unsigned & i) inline protected virtual
Function called within the finite difference loop for solid position data after the values in the i-th node are reset. The default behaviour is to call the update function.
Reimplemented from oomph::SolidFiniteElement.
 {}
setup_fsi_wall_element()
void oomph::FSIWallElement::setup_fsi_wall_element (const unsigned & nlagr_solid, const unsigned & ndim_fluid)
Setup: Assign storage – pass the Eulerian dimension of the "adjacent" fluid elements and the number of local coordinates required to parametrise the wall element. E.g. for a FSIKirchhoffLoveBeam, bounding a 2D fluid domain ndim_fluid=2 and nlagr_solid=1
Compete build of element: Assign storage – pass the Eulerian dimension of the "adjacent" fluid elements and the number of local coordinates required to parametrise the wall element. E.g. for a FSIKirchhoffLoveBeam, bounding a 2D fluid domain ndim_fluid=2 and nlagr_solid=1. Note that, by default, we're only providing storage for fluid loading on the "front" of the element. Call FSIWallElement::enable_fluid_loading_on_both_sides() to enable fluid loading on the back, too.
   {
     // Set storage for underlying GeomObject
     set_nlagrangian_and_ndim(nlagr_solid, ndim_fluid);
     // Set source element storage - one interaction
     this->set_ninteraction(1);
   }
References oomph::ElementWithExternalElement::set_ninteraction(), and oomph::GeomObject::set_nlagrangian_and_ndim().
Referenced by oomph::FSIDiagHermiteShellElement::FSIDiagHermiteShellElement(), oomph::FSIHermiteBeamElement::FSIHermiteBeamElement(), and oomph::FSISolidTractionElement< ELEMENT, DIM >::FSISolidTractionElement().
update_in_external_fd()
void oomph::FSIWallElement::update_in_external_fd (const unsigned & i) inline protected virtual
After an external data change, update the nodal positions.
Reimplemented from oomph::GeneralisedElement.
     {
       if (!Ignore_shear_stress_in_jacobian)
       {
         node_update_adjacent_fluid_elements();
       }
     }
References Ignore_shear_stress_in_jacobian, and node_update_adjacent_fluid_elements().
update_in_external_interaction_field_fd()
void oomph::FSIWallElement::update_in_external_interaction_field_fd (const unsigned & i) inline protected virtual
After an external field data change, update the nodal positions.
Reimplemented from oomph::ElementWithExternalElement.
     {
       if (!Ignore_shear_stress_in_jacobian)
       {
         node_update_adjacent_fluid_elements();
       }
     }
References Ignore_shear_stress_in_jacobian, and node_update_adjacent_fluid_elements().
update_in_external_interaction_geometric_fd()
void oomph::FSIWallElement::update_in_external_interaction_geometric_fd (const unsigned & i) inline protected virtual
After an external geometric data change, update the nodal positions
Reimplemented from oomph::ElementWithExternalElement.
     {
       if (!Ignore_shear_stress_in_jacobian)
       {
         node_update_adjacent_fluid_elements();
       }
     }
References Ignore_shear_stress_in_jacobian, and node_update_adjacent_fluid_elements().
update_in_internal_fd()
void oomph::FSIWallElement::update_in_internal_fd (const unsigned & i) inline protected virtual
After an internal data change, update the nodal positions.
Reimplemented from oomph::GeneralisedElement.
     {
       if (!Ignore_shear_stress_in_jacobian)
       {
         node_update_adjacent_fluid_elements();
       }
     }
References Ignore_shear_stress_in_jacobian, and node_update_adjacent_fluid_elements().
update_in_nodal_fd()
void oomph::FSIWallElement::update_in_nodal_fd (const unsigned & i) inline protected virtual
After a nodal data change, update the nodal positions.
Reimplemented from oomph::FiniteElement.
     {
       if (!Ignore_shear_stress_in_jacobian)
       {
         node_update_adjacent_fluid_elements();
       }
     }
References Ignore_shear_stress_in_jacobian, and node_update_adjacent_fluid_elements().
update_in_solid_position_fd()
void oomph::FSIWallElement::update_in_solid_position_fd (const unsigned & i) inline protected virtual
After an internal data change, update the nodal positions.
Reimplemented from oomph::SolidFiniteElement.
     {
       if (!Ignore_shear_stress_in_jacobian)
       {
         node_update_adjacent_fluid_elements();
       }
     }
References Ignore_shear_stress_in_jacobian, and node_update_adjacent_fluid_elements().
Member Data Documentation
Default_Q_Value
double oomph::FSIWallElement::Default_Q_Value = 1.0 static private
Static default value for the ratio of stress scales used in the fluid and solid equations (default is 1.0)
Dont_warn_about_missing_adjacent_fluid_elements
bool oomph::FSIWallElement::Dont_warn_about_missing_adjacent_fluid_elements = false static
Static flag that allows the suppression of warning messages.
Flag that allows the suppression of warning messages.
Referenced by fluid_load_vector().
Ignore_shear_stress_in_jacobian
bool oomph::FSIWallElement::Ignore_shear_stress_in_jacobian private
Set this flag to true to ignore shear stress component of load when calculating the Jacobian, i.e. to ignore fluid velocity Data in the FSIFluidElement and "far away" geometric Data that affects nodal positions in the FSIFluidElement, also to bypass node updates in the FSIFluidElement.
Referenced by disable_shear_stress_in_jacobian(), enable_shear_stress_in_jacobian(), identify_all_field_data_for_external_interaction(), identify_all_geometric_data_for_external_interaction(), include_external_load_data(), reset_after_external_fd(), reset_after_external_interaction_field_fd(), reset_after_external_interaction_geometric_fd(), reset_after_internal_fd(), reset_after_nodal_fd(), reset_after_solid_position_fd(), update_in_external_fd(), update_in_external_interaction_field_fd(), update_in_external_interaction_geometric_fd(), update_in_internal_fd(), update_in_nodal_fd(), and update_in_solid_position_fd().
Only_front_is_loaded_by_fluid
bool oomph::FSIWallElement::Only_front_is_loaded_by_fluid private
Is the element exposed to (and hence loaded by) fluid only on its "front"? True by default. This flag is set to false if the FSIWallElement is immersed in fluid in which case each integration point is loaded by two adjacent fluid elements, one at the "front" and one at the "back".
Referenced by enable_fluid_loading_on_both_sides(), fluid_load_vector(), node_update_adjacent_fluid_elements(), and only_front_is_loaded_by_fluid().
Q_pt
double* oomph::FSIWallElement::Q_pt private
Pointer to the ratio, \(Q \) , of the stress used to non-dimensionalise the fluid stresses to the stress used to non-dimensionalise the solid stresses.
Referenced by q(), and q_pt().
The documentation for this class was generated from the following files:
fsi.h
fsi.cc