MercuryDPM: Eigen::internal::gemm_pack_lhs< Scalar, Index, DataMapper, Pack1, Pack2, Packet, RowMajor, Conjugate, PanelMode > Struct Template Reference
Eigen::internal::gemm_pack_lhs< Scalar, Index, DataMapper, Pack1, Pack2, Packet, RowMajor, Conjugate, PanelMode > Struct Template Reference
#include <GeneralBlockPanelKernel.h>
Public Types
typedef DataMapper::LinearMapper LinearMapper
Public Member Functions
EIGEN_DONT_INLINE void operator() (Scalar *blockA, const DataMapper &lhs, Index depth, Index rows, Index stride=0, Index offset=0)
Member Typedef Documentation
LinearMapper
template<typename Scalar , typename Index , typename DataMapper , int Pack1, int Pack2, typename Packet , bool Conjugate, bool PanelMode> typedef DataMapper::LinearMapper Eigen::internal::gemm_pack_lhs< Scalar, Index, DataMapper, Pack1, Pack2, Packet, RowMajor, Conjugate, PanelMode >::LinearMapper
Member Function Documentation
operator()()
template<typename Scalar , typename Index , typename DataMapper , int Pack1, int Pack2, typename Packet , bool Conjugate, bool PanelMode> EIGEN_DONT_INLINE void Eigen::internal::gemm_pack_lhs< Scalar, Index, DataMapper, Pack1, Pack2, Packet, RowMajor, Conjugate, PanelMode >::operator() (Scalar * blockA, const DataMapper & lhs, Index depth, Index rows, Index stride = 0, Index offset = 0)
{
   typedef typename unpacket_traits<Packet>::half HalfPacket;
   typedef typename unpacket_traits<typename unpacket_traits<Packet>::half>::half QuarterPacket;
   enum {
     PacketSize = unpacket_traits<Packet>::size,
     HalfPacketSize = unpacket_traits<HalfPacket>::size,
     QuarterPacketSize = unpacket_traits<QuarterPacket>::size,
     HasHalf = (int)HalfPacketSize < (int)PacketSize,
     HasQuarter = (int)QuarterPacketSize < (int)HalfPacketSize
   };
   EIGEN_ASM_COMMENT("EIGEN PRODUCT PACK LHS");
   EIGEN_UNUSED_VARIABLE(stride);
   EIGEN_UNUSED_VARIABLE(offset);
   eigen_assert(((!PanelMode) && stride == 0 && offset == 0) || (PanelMode && stride >= depth && offset <= stride));
   conj_if<NumTraits<Scalar>::IsComplex && Conjugate> cj;
   Index count = 0;
   bool gone_half = false, gone_quarter = false, gone_last = false;
   Index i = 0;
   Index pack = Pack1;
   Index psize = PacketSize;
   while (pack > 0) {
     Index remaining_rows = rows - i;
     Index peeled_mc = gone_last ? Pack2 > 1 ? (rows / pack) * pack : 0 : i + (remaining_rows / pack) * pack;
     Index starting_pos = i;
     for (; i < peeled_mc; i += pack) {
       if (PanelMode) count += pack * offset;
       Index k = 0;
       if (pack >= psize && psize >= QuarterPacketSize) {
         const Index peeled_k = (depth / psize) * psize;
         for (; k < peeled_k; k += psize) {
           for (Index m = 0; m < pack; m += psize) {
             if (psize == PacketSize) {
               PacketBlock<Packet> kernel;
               for (Index p = 0; p < psize; ++p) kernel.packet[p] = lhs.template loadPacket<Packet>(i + p + m, k);
               ptranspose(kernel);
               for (Index p = 0; p < psize; ++p) pstore(blockA + count + m + (pack)*p, cj.pconj(kernel.packet[p]));
             } else if (HasHalf && psize == HalfPacketSize) {
               gone_half = true;
               PacketBlock<HalfPacket> kernel_half;
               for (Index p = 0; p < psize; ++p)
                 kernel_half.packet[p] = lhs.template loadPacket<HalfPacket>(i + p + m, k);
               ptranspose(kernel_half);
               for (Index p = 0; p < psize; ++p) pstore(blockA + count + m + (pack)*p, cj.pconj(kernel_half.packet[p]));
             } else if (HasQuarter && psize == QuarterPacketSize) {
               gone_quarter = true;
               PacketBlock<QuarterPacket> kernel_quarter;
               for (Index p = 0; p < psize; ++p)
                 kernel_quarter.packet[p] = lhs.template loadPacket<QuarterPacket>(i + p + m, k);
               ptranspose(kernel_quarter);
               for (Index p = 0; p < psize; ++p)
                 pstore(blockA + count + m + (pack)*p, cj.pconj(kernel_quarter.packet[p]));
             }
           }
           count += psize * pack;
         }
       }
       for (; k < depth; k++) {
         Index w = 0;
         for (; w < pack - 3; w += 4) {
           Scalar a(cj(lhs(i + w + 0, k))), b(cj(lhs(i + w + 1, k))), c(cj(lhs(i + w + 2, k))), d(cj(lhs(i + w + 3, k)));
           blockA[count++] = a;
           blockA[count++] = b;
           blockA[count++] = c;
           blockA[count++] = d;
         }
         if (pack % 4)
           for (; w < pack; ++w) blockA[count++] = cj(lhs(i + w, k));
       }
       if (PanelMode) count += pack * (stride - offset - depth);
     }
     pack -= psize;
     Index left = rows - i;
     if (pack <= 0) {
       if (!gone_last && (starting_pos == i || left >= psize / 2 || left >= psize / 4) &&
           ((psize / 2 == HalfPacketSize && HasHalf && !gone_half) ||
            (psize / 2 == QuarterPacketSize && HasQuarter && !gone_quarter))) {
         psize /= 2;
         pack = psize;
         continue;
       }
       // Pack2 may be *smaller* than PacketSize—that happens for
       // products like real * complex, where we have to go half the
       // progress on the lhs in order to duplicate those operands to
       // address both real & imaginary parts on the rhs. This portion will
       // pack those half ones until they match the number expected on the
       // last peeling loop at this point (for the rhs).
       if (Pack2 < PacketSize && !gone_last) {
         gone_last = true;
         psize = pack = left & ~1;
       }
     }
   }
   for (; i < rows; i++) {
     if (PanelMode) count += offset;
     for (Index k = 0; k < depth; k++) blockA[count++] = cj(lhs(i, k));
     if (PanelMode) count += (stride - offset - depth);
   }
 }
References a, b, calibrate::c, EIGEN_ASM_COMMENT, eigen_assert, EIGEN_UNUSED_VARIABLE, i, int(), k, m, p, Eigen::internal::PacketBlock< Packet, N >::packet, Eigen::internal::pstore(), Eigen::internal::ptranspose(), rows, and w.
The documentation for this struct was generated from the following file:
products/GeneralBlockPanelKernel.h