MercuryDPM: Eigen::TensorEvaluator< const TensorRollOp< RollDimensions, ArgType >, Device > Struct Template Reference
Eigen::TensorEvaluator< const TensorRollOp< RollDimensions, ArgType >, Device > Struct Template Reference
#include <TensorRoll.h>
Classes
struct BlockIteratorState
Public Types
enum { IsAligned = false , PacketAccess = TensorEvaluator<ArgType, Device>::PacketAccess }
typedef TensorRollOp< RollDimensions, ArgType > XprType
typedef XprType::Index Index
typedef DSizes< Index, NumDims > Dimensions
typedef XprType::Scalar Scalar
typedef XprType::CoeffReturnType CoeffReturnType
typedef PacketType< CoeffReturnType, Device >::type PacketReturnType
typedef StorageMemory< CoeffReturnType, Device > Storage
typedef Storage::Type EvaluatorPointerType
typedef internal::TensorIntDivisor< Index > IndexDivisor
using TensorBlockDesc = internal::TensorBlockDescriptor< NumDims, Index >
using TensorBlockScratch = internal::TensorBlockScratchAllocator< Device >
using ArgTensorBlock = typename TensorEvaluator< const ArgType, Device >::TensorBlock
using TensorBlock = typename internal::TensorMaterializedBlock< CoeffReturnType, NumDims, Layout, Index >
Public Member Functions
EIGEN_STRONG_INLINE TensorEvaluator (const XprType &op, const Device &device)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Dimensions & dimensions () const
EIGEN_STRONG_INLINE bool evalSubExprsIfNeeded (EvaluatorPointerType)
EIGEN_STRONG_INLINE void cleanup ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index roll (Index const i, Index const r, Index const n) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE array< Index, NumDims > rollCoords (array< Index, NumDims > const &coords) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index rollIndex (Index index) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType coeff (Index index) const
template<int LoadMode>
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketReturnType packet (Index index) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE internal::TensorBlockResourceRequirements getResourceRequirements () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorBlock block (TensorBlockDesc &desc, TensorBlockScratch &scratch, bool=false) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorOpCost costPerCoeff (bool vectorized) const
EIGEN_DEVICE_FUNC Storage::Type data () const
Static Public Attributes
static constexpr int NumDims = internal::array_size<RollDimensions>::value
static constexpr int PacketSize = PacketType<CoeffReturnType, Device>::size
static constexpr int Layout = TensorEvaluator<ArgType, Device>::Layout
Protected Member Functions
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void extract_coordinates (Index index, array< Index, NumDims > &coords) const
Protected Attributes
Dimensions m_dimensions
array< Index, NumDims > m_strides
array< IndexDivisor, NumDims > m_fast_strides
TensorEvaluator< ArgType, Device > m_impl
RollDimensions m_rolls
const Device EIGEN_DEVICE_REF m_device
Member Typedef Documentation
ArgTensorBlock
template<typename RollDimensions , typename ArgType , typename Device > using Eigen::TensorEvaluator< const TensorRollOp< RollDimensions, ArgType >, Device >::ArgTensorBlock = typename TensorEvaluator<const ArgType, Device>::TensorBlock
CoeffReturnType
template<typename RollDimensions , typename ArgType , typename Device > typedef XprType::CoeffReturnType Eigen::TensorEvaluator< const TensorRollOp< RollDimensions, ArgType >, Device >::CoeffReturnType
Dimensions
template<typename RollDimensions , typename ArgType , typename Device > typedef DSizes<Index, NumDims> Eigen::TensorEvaluator< const TensorRollOp< RollDimensions, ArgType >, Device >::Dimensions
EvaluatorPointerType
template<typename RollDimensions , typename ArgType , typename Device > typedef Storage::Type Eigen::TensorEvaluator< const TensorRollOp< RollDimensions, ArgType >, Device >::EvaluatorPointerType
Index
template<typename RollDimensions , typename ArgType , typename Device > typedef XprType::Index Eigen::TensorEvaluator< const TensorRollOp< RollDimensions, ArgType >, Device >::Index
IndexDivisor
template<typename RollDimensions , typename ArgType , typename Device > typedef internal::TensorIntDivisor<Index> Eigen::TensorEvaluator< const TensorRollOp< RollDimensions, ArgType >, Device >::IndexDivisor
PacketReturnType
template<typename RollDimensions , typename ArgType , typename Device > typedef PacketType<CoeffReturnType, Device>::type Eigen::TensorEvaluator< const TensorRollOp< RollDimensions, ArgType >, Device >::PacketReturnType
Scalar
template<typename RollDimensions , typename ArgType , typename Device > typedef XprType::Scalar Eigen::TensorEvaluator< const TensorRollOp< RollDimensions, ArgType >, Device >::Scalar
Storage
template<typename RollDimensions , typename ArgType , typename Device > typedef StorageMemory<CoeffReturnType, Device> Eigen::TensorEvaluator< const TensorRollOp< RollDimensions, ArgType >, Device >::Storage
TensorBlock
template<typename RollDimensions , typename ArgType , typename Device > using Eigen::TensorEvaluator< const TensorRollOp< RollDimensions, ArgType >, Device >::TensorBlock = typename internal::TensorMaterializedBlock<CoeffReturnType, NumDims, Layout, Index>
TensorBlockDesc
template<typename RollDimensions , typename ArgType , typename Device > using Eigen::TensorEvaluator< const TensorRollOp< RollDimensions, ArgType >, Device >::TensorBlockDesc = internal::TensorBlockDescriptor<NumDims, Index>
TensorBlockScratch
template<typename RollDimensions , typename ArgType , typename Device > using Eigen::TensorEvaluator< const TensorRollOp< RollDimensions, ArgType >, Device >::TensorBlockScratch = internal::TensorBlockScratchAllocator<Device>
XprType
template<typename RollDimensions , typename ArgType , typename Device > typedef TensorRollOp<RollDimensions, ArgType> Eigen::TensorEvaluator< const TensorRollOp< RollDimensions, ArgType >, Device >::XprType
Member Enumeration Documentation
anonymous enum
template<typename RollDimensions , typename ArgType , typename Device > anonymous enum
Enumerator
IsAligned
PacketAccess
        {
     IsAligned = false,
     PacketAccess = TensorEvaluator<ArgType, Device>::PacketAccess,
     BlockAccess = NumDims > 0,
     PreferBlockAccess = true,
     CoordAccess = false,  // to be implemented
     RawAccess = false
   };
Constructor & Destructor Documentation
TensorEvaluator()
template<typename RollDimensions , typename ArgType , typename Device > EIGEN_STRONG_INLINE Eigen::TensorEvaluator< const TensorRollOp< RollDimensions, ArgType >, Device >::TensorEvaluator (const XprType & op, const Device & device) inline
       : m_impl(op.expression(), device), m_rolls(op.roll()), m_device(device) {
     EIGEN_STATIC_ASSERT((NumDims > 0), Must_Have_At_Least_One_Dimension_To_Roll);
     // Compute strides
     m_dimensions = m_impl.dimensions();
     if (static_cast<int>(Layout) == static_cast<int>(ColMajor)) {
       m_strides[0] = 1;
       for (int i = 1; i < NumDims; ++i) {
         m_strides[i] = m_strides[i - 1] * m_dimensions[i - 1];
         if (m_strides[i] > 0) m_fast_strides[i] = IndexDivisor(m_strides[i]);
       }
     } else {
       m_strides[NumDims - 1] = 1;
       for (int i = NumDims - 2; i >= 0; --i) {
         m_strides[i] = m_strides[i + 1] * m_dimensions[i + 1];
         if (m_strides[i] > 0) m_fast_strides[i] = IndexDivisor(m_strides[i]);
       }
     }
   }
References Eigen::ColMajor, EIGEN_STATIC_ASSERT, i, and Eigen::TensorEvaluator< Derived, Device >::Layout.
Member Function Documentation
block()
template<typename RollDimensions , typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorBlock Eigen::TensorEvaluator< const TensorRollOp< RollDimensions, ArgType >, Device >::block (TensorBlockDesc & desc, TensorBlockScratch & scratch, bool = false) const inline
{
     static const bool is_col_major = static_cast<int>(Layout) == static_cast<int>(ColMajor);
     // Compute spatial coordinates for the first block element.
     array<Index, NumDims> coords;
     extract_coordinates(desc.offset(), coords);
     array<Index, NumDims> initial_coords = coords;
     Index offset = 0;  // Offset in the output block buffer.
     // Initialize output block iterator state. Dimension in this array are
     // always in inner_most -> outer_most order (col major layout).
     array<BlockIteratorState, NumDims> it;
     for (int i = 0; i < NumDims; ++i) {
       const int dim = is_col_major ? i : NumDims - 1 - i;
       it[i].size = desc.dimension(dim);
       it[i].stride = i == 0 ? 1 : (it[i - 1].size * it[i - 1].stride);
       it[i].span = it[i].stride * (it[i].size - 1);
       it[i].count = 0;
     }
     eigen_assert(it[0].stride == 1);
     // Prepare storage for the materialized generator result.
     const typename TensorBlock::Storage block_storage = TensorBlock::prepareStorage(desc, scratch);
     CoeffReturnType* block_buffer = block_storage.data();
     static const int inner_dim = is_col_major ? 0 : NumDims - 1;
     const Index inner_dim_size = it[0].size;
     while (it[NumDims - 1].count < it[NumDims - 1].size) {
       Index i = 0;
       for (; i < inner_dim_size; ++i) {
         auto const rolled = rollCoords(coords);
         auto const index = is_col_major ? m_dimensions.IndexOfColMajor(rolled) : m_dimensions.IndexOfRowMajor(rolled);
         *(block_buffer + offset + i) = m_impl.coeff(index);
         coords[inner_dim]++;
       }
       coords[inner_dim] = initial_coords[inner_dim];
       if (NumDims == 1) break;  // For the 1d tensor we need to generate only one inner-most dimension.
       // Update offset.
       for (i = 1; i < NumDims; ++i) {
         if (++it[i].count < it[i].size) {
           offset += it[i].stride;
           coords[is_col_major ? i : NumDims - 1 - i]++;
           break;
         }
         if (i != NumDims - 1) it[i].count = 0;
         coords[is_col_major ? i : NumDims - 1 - i] = initial_coords[is_col_major ? i : NumDims - 1 - i];
         offset -= it[i].span;
       }
     }
     return block_storage.AsTensorMaterializedBlock();
   }
References Eigen::ColMajor, Eigen::internal::TensorBlockDescriptor< NumDims, IndexType >::dimension(), eigen_assert, i, Eigen::TensorEvaluator< Derived, Device >::Layout, Eigen::internal::TensorBlockDescriptor< NumDims, IndexType >::offset(), Eigen::internal::TensorMaterializedBlock< Scalar, NumDims, Layout, IndexType >::prepareStorage(), and size.
cleanup()
template<typename RollDimensions , typename ArgType , typename Device > EIGEN_STRONG_INLINE void Eigen::TensorEvaluator< const TensorRollOp< RollDimensions, ArgType >, Device >::cleanup () inline
 { m_impl.cleanup(); }
Referenced by framework.Frame::__init__().
coeff()
template<typename RollDimensions , typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType Eigen::TensorEvaluator< const TensorRollOp< RollDimensions, ArgType >, Device >::coeff (Index index) const inline
{
     return m_impl.coeff(rollIndex(index));
   }
costPerCoeff()
template<typename RollDimensions , typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorOpCost Eigen::TensorEvaluator< const TensorRollOp< RollDimensions, ArgType >, Device >::costPerCoeff (bool vectorized) const inline
{
     double compute_cost = NumDims * (2 * TensorOpCost::AddCost<Index>() + 2 * TensorOpCost::MulCost<Index>() +
                                      TensorOpCost::DivCost<Index>());
     for (int i = 0; i < NumDims; ++i) {
       compute_cost += 2 * TensorOpCost::AddCost<Index>();
     }
     return m_impl.costPerCoeff(vectorized) + TensorOpCost(0, 0, compute_cost, false /* vectorized */, PacketSize);
   }
References i, and Eigen::TensorEvaluator< Derived, Device >::PacketSize.
data()
template<typename RollDimensions , typename ArgType , typename Device > EIGEN_DEVICE_FUNC Storage::Type Eigen::TensorEvaluator< const TensorRollOp< RollDimensions, ArgType >, Device >::data () const inline
 { return nullptr; }
Referenced by gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenQuaternionPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), gdb.printers.EigenSparseMatrixPrinter::to_string(), and gdb.printers.EigenQuaternionPrinter::to_string().
dimensions()
template<typename RollDimensions , typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Dimensions& Eigen::TensorEvaluator< const TensorRollOp< RollDimensions, ArgType >, Device >::dimensions () const inline
 { return m_dimensions; }
evalSubExprsIfNeeded()
template<typename RollDimensions , typename ArgType , typename Device > EIGEN_STRONG_INLINE bool Eigen::TensorEvaluator< const TensorRollOp< RollDimensions, ArgType >, Device >::evalSubExprsIfNeeded (EvaluatorPointerType) inline
{
     m_impl.evalSubExprsIfNeeded(nullptr);
     return true;
   }
extract_coordinates()
template<typename RollDimensions , typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::TensorEvaluator< const TensorRollOp< RollDimensions, ArgType >, Device >::extract_coordinates (Index index, array< Index, NumDims > & coords) const inline protected
{
     if (static_cast<int>(Layout) == static_cast<int>(ColMajor)) {
       for (int i = NumDims - 1; i > 0; --i) {
         const Index idx = index / m_fast_strides[i];
         index -= idx * m_strides[i];
         coords[i] = idx;
       }
       coords[0] = index;
     } else {
       for (int i = 0; i < NumDims - 1; ++i) {
         const Index idx = index / m_fast_strides[i];
         index -= idx * m_strides[i];
         coords[i] = idx;
       }
       coords[NumDims - 1] = index;
     }
   }
References Eigen::ColMajor, i, and Eigen::TensorEvaluator< Derived, Device >::Layout.
getResourceRequirements()
template<typename RollDimensions , typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE internal::TensorBlockResourceRequirements Eigen::TensorEvaluator< const TensorRollOp< RollDimensions, ArgType >, Device >::getResourceRequirements () const inline
{
     const size_t target_size = m_device.lastLevelCacheSize();
     return internal::TensorBlockResourceRequirements::skewed<Scalar>(target_size).addCostPerCoeff({0, 0, 24});
   }
References Eigen::TensorEvaluator< Derived, Device >::m_device.
packet()
template<typename RollDimensions , typename ArgType , typename Device > template<int LoadMode> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketReturnType Eigen::TensorEvaluator< const TensorRollOp< RollDimensions, ArgType >, Device >::packet (Index index) const inline
{
     eigen_assert(index + PacketSize - 1 < dimensions().TotalSize());
     EIGEN_ALIGN_MAX std::remove_const_t<CoeffReturnType> values[PacketSize];
     EIGEN_UNROLL_LOOP
     for (int i = 0; i < PacketSize; ++i) {
       values[i] = coeff(index + i);
     }
     PacketReturnType rslt = internal::pload<PacketReturnType>(values);
     return rslt;
   }
References Eigen::TensorEvaluator< Derived, Device >::coeff(), Eigen::TensorEvaluator< Derived, Device >::dimensions(), EIGEN_ALIGN_MAX, eigen_assert, EIGEN_UNROLL_LOOP, i, and Eigen::TensorEvaluator< Derived, Device >::PacketSize.
roll()
template<typename RollDimensions , typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index Eigen::TensorEvaluator< const TensorRollOp< RollDimensions, ArgType >, Device >::roll (Index const i, Index const r, Index const n) const inline
{
     auto const tmp = (i + r) % n;
     if (tmp < 0) {
       return tmp + n;
     } else {
       return tmp;
     }
   }
References i, n, UniformPSDSelfTest::r, and tmp.
rollCoords()
template<typename RollDimensions , typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE array<Index, NumDims> Eigen::TensorEvaluator< const TensorRollOp< RollDimensions, ArgType >, Device >::rollCoords (array< Index, NumDims > const & coords) const inline
{
     array<Index, NumDims> rolledCoords;
     for (int id = 0; id < NumDims; id++) {
       eigen_assert(coords[id] < m_dimensions[id]);
       rolledCoords[id] = roll(coords[id], m_rolls[id], m_dimensions[id]);
     }
     return rolledCoords;
   }
References eigen_assert.
rollIndex()
template<typename RollDimensions , typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index Eigen::TensorEvaluator< const TensorRollOp< RollDimensions, ArgType >, Device >::rollIndex (Index index) const inline
{
     eigen_assert(index < dimensions().TotalSize());
     Index rolledIndex = 0;
     if (static_cast<int>(Layout) == static_cast<int>(ColMajor)) {
       EIGEN_UNROLL_LOOP
       for (int i = NumDims - 1; i > 0; --i) {
         Index idx = index / m_fast_strides[i];
         index -= idx * m_strides[i];
         rolledIndex += roll(idx, m_rolls[i], m_dimensions[i]) * m_strides[i];
       }
       rolledIndex += roll(index, m_rolls[0], m_dimensions[0]);
     } else {
       EIGEN_UNROLL_LOOP
       for (int i = 0; i < NumDims - 1; ++i) {
         Index idx = index / m_fast_strides[i];
         index -= idx * m_strides[i];
         rolledIndex += roll(idx, m_rolls[i], m_dimensions[i]) * m_strides[i];
       }
       rolledIndex += roll(index, m_rolls[NumDims - 1], m_dimensions[NumDims - 1]);
     }
     return rolledIndex;
   }
References Eigen::ColMajor, Eigen::TensorEvaluator< Derived, Device >::dimensions(), eigen_assert, EIGEN_UNROLL_LOOP, i, and Eigen::TensorEvaluator< Derived, Device >::Layout.
Member Data Documentation
Layout
template<typename RollDimensions , typename ArgType , typename Device > constexpr int Eigen::TensorEvaluator< const TensorRollOp< RollDimensions, ArgType >, Device >::Layout = TensorEvaluator<ArgType, Device>::Layout static constexpr
m_device
template<typename RollDimensions , typename ArgType , typename Device > const Device EIGEN_DEVICE_REF Eigen::TensorEvaluator< const TensorRollOp< RollDimensions, ArgType >, Device >::m_device protected
m_dimensions
template<typename RollDimensions , typename ArgType , typename Device > Dimensions Eigen::TensorEvaluator< const TensorRollOp< RollDimensions, ArgType >, Device >::m_dimensions protected
m_fast_strides
template<typename RollDimensions , typename ArgType , typename Device > array<IndexDivisor, NumDims> Eigen::TensorEvaluator< const TensorRollOp< RollDimensions, ArgType >, Device >::m_fast_strides protected
m_impl
template<typename RollDimensions , typename ArgType , typename Device > TensorEvaluator<ArgType, Device> Eigen::TensorEvaluator< const TensorRollOp< RollDimensions, ArgType >, Device >::m_impl protected
m_rolls
template<typename RollDimensions , typename ArgType , typename Device > RollDimensions Eigen::TensorEvaluator< const TensorRollOp< RollDimensions, ArgType >, Device >::m_rolls protected
m_strides
template<typename RollDimensions , typename ArgType , typename Device > array<Index, NumDims> Eigen::TensorEvaluator< const TensorRollOp< RollDimensions, ArgType >, Device >::m_strides protected
NumDims
template<typename RollDimensions , typename ArgType , typename Device > constexpr int Eigen::TensorEvaluator< const TensorRollOp< RollDimensions, ArgType >, Device >::NumDims = internal::array_size<RollDimensions>::value static constexpr
PacketSize
template<typename RollDimensions , typename ArgType , typename Device > constexpr int Eigen::TensorEvaluator< const TensorRollOp< RollDimensions, ArgType >, Device >::PacketSize = PacketType<CoeffReturnType, Device>::size static constexpr
The documentation for this struct was generated from the following file:
TensorRoll.h