MercuryDPM: oomph::RankFiveTensor< T > Class Template Reference
oomph::RankFiveTensor< T > Class Template Reference
A Rank 5 Tensor class.
#include <matrices.h>
Public Member Functions
RankFiveTensor ()
Empty constructor.
RankFiveTensor (const RankFiveTensor &source_tensor)
Copy constructor: Deep copy.
RankFiveTensor & operator= (const RankFiveTensor &source_tensor)
Copy assignement.
RankFiveTensor (const unsigned long &n)
One parameter constructor produces a nxnxnxnxn tensor.
RankFiveTensor (const unsigned long &n_index1, const unsigned long &n_index2, const unsigned long &n_index3, const unsigned long &n_index4, const unsigned long &n_index5)
Four parameter constructor, general non-square tensor.
RankFiveTensor (const unsigned long &n_index1, const unsigned long &n_index2, const unsigned long &n_index3, const unsigned long &n_index4, const unsigned long &n_index5, const T &initial_val)
Four parameter constructor, general non-square tensor.
virtual ~RankFiveTensor ()
Destructor: delete the pointers.
void resize (const unsigned long &n)
Resize to a square nxnxnxn tensor.
void resize (const unsigned long &n_index1, const unsigned long &n_index2, const unsigned long &n_index3, const unsigned long &n_index4, const unsigned long &n_index5)
Resize to a general tensor.
void resize (const unsigned long &n_index1, const unsigned long &n_index2, const unsigned long &n_index3, const unsigned long &n_index4, const unsigned long &n_index5, const T &initial_value)
Resize to a general tensor.
void initialise (const T &val)
Initialise all values in the tensor to val.
unsigned long nindex1 () const
Return the range of index 1 of the tensor.
unsigned long nindex2 () const
Return the range of index 2 of the tensor.
unsigned long nindex3 () const
Return the range of index 3 of the tensor.
unsigned long nindex4 () const
Return the range of index 4 of the tensor.
unsigned long nindex5 () const
Return the range of index 5 of the tensor.
T & operator() (const unsigned long &i, const unsigned long &j, const unsigned long &k, const unsigned long &l, const unsigned long &m)
Overload the round brackets to give access as a(i,j,k,l,m)
T operator() (const unsigned long &i, const unsigned long &j, const unsigned long &k, const unsigned long &l, const unsigned long &m) const
Overload a const version for read-only access as a(i,j,k,l,m)
T & raw_direct_access (const unsigned long &i)
const T & raw_direct_access (const unsigned long &i) const
unsigned offset (const unsigned long &i, const unsigned long &j, const unsigned long &k) const
Private Member Functions
void range_check (const unsigned long &i, const unsigned long &j, const unsigned long &k, const unsigned long &l, const unsigned long &m) const
Private Attributes
T * Tensordata
Private internal representation as pointer to data.
unsigned N
1st Tensor dimension
unsigned M
2nd Tensor dimension
unsigned P
3rd Tensor dimension
unsigned Q
4th Tensor dimension
unsigned R
5th Tensor dimension
Detailed Description
template<class T>
class oomph::RankFiveTensor< T >
A Rank 5 Tensor class.
/////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////
Constructor & Destructor Documentation
RankFiveTensor() [1/5]
template<class T > oomph::RankFiveTensor< T >::RankFiveTensor () inline
Empty constructor.
 : Tensordata(0), N(0), M(0), P(0), Q(0), R(0) {}
RankFiveTensor() [2/5]
template<class T > oomph::RankFiveTensor< T >::RankFiveTensor (const RankFiveTensor< T > & source_tensor) inline
Copy constructor: Deep copy.
     {
       // Set row and column lengths
       N = source_tensor.nindex1();
       M = source_tensor.nindex2();
       P = source_tensor.nindex3();
       Q = source_tensor.nindex4();
       R = source_tensor.nindex5();
       // Assign space for the data
       Tensordata = new T[N * M * P * Q * R];
       // Copy the data across from the other matrix
       for (unsigned i = 0; i < N; i++)
       {
         for (unsigned j = 0; j < M; j++)
         {
           for (unsigned k = 0; k < P; k++)
           {
             for (unsigned l = 0; l < Q; l++)
             {
               for (unsigned m = 0; m < R; m++)
               {
                 Tensordata[R * (Q * (P * (M * i + j) + k) + l) + m] =
                   source_tensor(i, j, k, l, m);
               }
             }
           }
         }
       }
     }
References i, j, k, m, oomph::RankFiveTensor< T >::M, oomph::RankFiveTensor< T >::N, oomph::RankFiveTensor< T >::nindex1(), oomph::RankFiveTensor< T >::nindex2(), oomph::RankFiveTensor< T >::nindex3(), oomph::RankFiveTensor< T >::nindex4(), oomph::RankFiveTensor< T >::nindex5(), oomph::RankFiveTensor< T >::P, oomph::RankFiveTensor< T >::Q, oomph::RankFiveTensor< T >::R, and oomph::RankFiveTensor< T >::Tensordata.
RankFiveTensor() [3/5]
template<class T > oomph::RankFiveTensor< T >::RankFiveTensor (const unsigned long & n) inline
One parameter constructor produces a nxnxnxnxn tensor.
     {
       // Set row and column lengths
       N = n;
       M = n;
       P = n;
       Q = n;
       R = n;
       // Assign space for the n rows
       Tensordata = new T[N * M * P * Q * R];
       // Initialise to zero if required
 #ifdef OOMPH_INITIALISE_DENSE_MATRICES
       initialise(T(0));
 #endif
     }
References oomph::RankFiveTensor< T >::initialise(), n, oomph::RankFiveTensor< T >::N, oomph::RankFiveTensor< T >::P, oomph::RankFiveTensor< T >::Q, oomph::RankFiveTensor< T >::R, and oomph::RankFiveTensor< T >::Tensordata.
RankFiveTensor() [4/5]
template<class T > oomph::RankFiveTensor< T >::RankFiveTensor (const unsigned long & n_index1, const unsigned long & n_index2, const unsigned long & n_index3, const unsigned long & n_index4, const unsigned long & n_index5) inline
Four parameter constructor, general non-square tensor.
     {
       // Set row and column lengths
       N = n_index1;
       M = n_index2;
       P = n_index3;
       Q = n_index4;
       R = n_index5;
       // Assign space for the n rows
       Tensordata = new T[N * M * P * Q * R];
       // Initialise to zero if required
 #ifdef OOMPH_INITIALISE_DENSE_MATRICES
       initialise(T(0));
 #endif
     }
References oomph::RankFiveTensor< T >::initialise(), oomph::RankFiveTensor< T >::N, oomph::RankFiveTensor< T >::P, oomph::RankFiveTensor< T >::Q, oomph::RankFiveTensor< T >::R, and oomph::RankFiveTensor< T >::Tensordata.
RankFiveTensor() [5/5]
template<class T > oomph::RankFiveTensor< T >::RankFiveTensor (const unsigned long & n_index1, const unsigned long & n_index2, const unsigned long & n_index3, const unsigned long & n_index4, const unsigned long & n_index5, const T & initial_val) inline
Four parameter constructor, general non-square tensor.
     {
       // Set row and column lengths
       N = n_index1;
       M = n_index2;
       P = n_index3;
       Q = n_index4;
       R = n_index5;
       // Assign space for the n rows
       Tensordata = new T[N * M * P * Q * R];
       // Initialise to the initial value
       initialise(initial_val);
     }
References oomph::RankFiveTensor< T >::initialise(), oomph::RankFiveTensor< T >::N, oomph::RankFiveTensor< T >::P, oomph::RankFiveTensor< T >::Q, oomph::RankFiveTensor< T >::R, and oomph::RankFiveTensor< T >::Tensordata.
~RankFiveTensor()
template<class T > virtual oomph::RankFiveTensor< T >::~RankFiveTensor () inline virtual
Destructor: delete the pointers.
     {
       delete[] Tensordata;
       Tensordata = 0;
     }
References oomph::RankFiveTensor< T >::Tensordata.
Member Function Documentation
initialise()
template<class T > void oomph::RankFiveTensor< T >::initialise (const T & val) inline
Initialise all values in the tensor to val.
     {
       for (unsigned long i = 0; i < (N * M * P * Q * R); ++i)
       {
         Tensordata[i] = val;
       }
     }
References i, oomph::RankFiveTensor< T >::N, oomph::RankFiveTensor< T >::P, oomph::RankFiveTensor< T >::Q, oomph::RankFiveTensor< T >::R, oomph::RankFiveTensor< T >::Tensordata, and calibrate::val.
Referenced by oomph::RankFiveTensor< T >::RankFiveTensor(), and oomph::RankFiveTensor< T >::resize().
nindex1()
template<class T > unsigned long oomph::RankFiveTensor< T >::nindex1 () const inline
Return the range of index 1 of the tensor.
     {
       return N;
     }
References oomph::RankFiveTensor< T >::N.
Referenced by oomph::RankFiveTensor< T >::operator=(), and oomph::RankFiveTensor< T >::RankFiveTensor().
nindex2()
template<class T > unsigned long oomph::RankFiveTensor< T >::nindex2 () const inline
Return the range of index 2 of the tensor.
     {
       return M;
     }
References oomph::RankFiveTensor< T >::M.
Referenced by oomph::RankFiveTensor< T >::operator=(), and oomph::RankFiveTensor< T >::RankFiveTensor().
nindex3()
template<class T > unsigned long oomph::RankFiveTensor< T >::nindex3 () const inline
Return the range of index 3 of the tensor.
     {
       return P;
     }
References oomph::RankFiveTensor< T >::P.
Referenced by oomph::RankFiveTensor< T >::operator=(), and oomph::RankFiveTensor< T >::RankFiveTensor().
nindex4()
template<class T > unsigned long oomph::RankFiveTensor< T >::nindex4 () const inline
Return the range of index 4 of the tensor.
     {
       return Q;
     }
References oomph::RankFiveTensor< T >::Q.
Referenced by oomph::RankFiveTensor< T >::operator=(), and oomph::RankFiveTensor< T >::RankFiveTensor().
nindex5()
template<class T > unsigned long oomph::RankFiveTensor< T >::nindex5 () const inline
Return the range of index 5 of the tensor.
     {
       return R;
     }
References oomph::RankFiveTensor< T >::R.
Referenced by oomph::RankFiveTensor< T >::operator=(), and oomph::RankFiveTensor< T >::RankFiveTensor().
offset()
template<class T > unsigned oomph::RankFiveTensor< T >::offset (const unsigned long & i, const unsigned long & j, const unsigned long & k) const inline
Caculate the offset in flat-packed Cy-style, column-major format, required for a given i,j,k. WARNING: Only for experienced users. Only use this if raw speed is of the essence, as in the solid mechanics problems.
     {
       return (R * (Q * (P * (M * i + j) + k) + 0) + 0);
     }
References i, j, k, oomph::RankFiveTensor< T >::P, oomph::RankFiveTensor< T >::Q, and oomph::RankFiveTensor< T >::R.
Referenced by oomph::RefineableQDPVDElement< DIM, NNODE_1D >::fill_in_generic_contribution_to_residuals_pvd(), oomph::RefineablePVDEquations< DIM >::fill_in_generic_contribution_to_residuals_pvd(), oomph::PVDEquations< DIM >::fill_in_generic_contribution_to_residuals_pvd(), oomph::ScaleCoupledElement< ELEMENT >::fill_in_generic_contribution_to_residuals_pvd(), oomph::VolumeCoupledElement< ELEMENT >::fill_in_generic_contribution_to_residuals_pvd(), oomph::RefineablePVDEquationsWithPressure< DIM >::fill_in_generic_residual_contribution_pvd_with_pressure(), and oomph::PVDEquationsWithPressure< DIM >::fill_in_generic_residual_contribution_pvd_with_pressure().
operator()() [1/2]
template<class T > T& oomph::RankFiveTensor< T >::operator() (const unsigned long & i, const unsigned long & j, const unsigned long & k, const unsigned long & l, const unsigned long & m) inline
Overload the round brackets to give access as a(i,j,k,l,m)
     {
 #ifdef RANGE_CHECKING
       this->range_check(i, j, k, l, m);
 #endif
       return Tensordata[R * (Q * (P * (M * i + j) + k) + l) + m];
     }
References i, j, k, m, oomph::RankFiveTensor< T >::P, oomph::RankFiveTensor< T >::Q, oomph::RankFiveTensor< T >::R, oomph::RankFiveTensor< T >::range_check(), and oomph::RankFiveTensor< T >::Tensordata.
operator()() [2/2]
template<class T > T oomph::RankFiveTensor< T >::operator() (const unsigned long & i, const unsigned long & j, const unsigned long & k, const unsigned long & l, const unsigned long & m) const inline
Overload a const version for read-only access as a(i,j,k,l,m)
     {
 #ifdef RANGE_CHECKING
       this->range_check(i, j, k, l, m);
 #endif
       return Tensordata[R * (Q * (P * (M * i + j) + k) + l) + m];
     }
References i, j, k, m, oomph::RankFiveTensor< T >::P, oomph::RankFiveTensor< T >::Q, oomph::RankFiveTensor< T >::R, oomph::RankFiveTensor< T >::range_check(), and oomph::RankFiveTensor< T >::Tensordata.
operator=()
template<class T > RankFiveTensor& oomph::RankFiveTensor< T >::operator= (const RankFiveTensor< T > & source_tensor) inline
Copy assignement.
     {
       // Don't create a new matrix if the assignement is the identity
       if (this != &source_tensor)
       {
         // Check row and column length
         unsigned long n = source_tensor.nindex1();
         unsigned long m = source_tensor.nindex2();
         unsigned long p = source_tensor.nindex3();
         unsigned long q = source_tensor.nindex4();
         unsigned long r = source_tensor.nindex5();
         // Resize the tensor to be the same size as the old tensor
         if ((N != n) || (M != m) || (P != p) || (Q != q) || (R != r))
         {
           resize(n, m, p, q, r);
         }
         // Copy entries across from the other matrix
         for (unsigned long i = 0; i < N; i++)
         {
           for (unsigned long j = 0; j < M; j++)
           {
             for (unsigned long k = 0; k < P; k++)
             {
               for (unsigned long l = 0; l < Q; l++)
               {
                 for (unsigned long m = 0; m < R; m++)
                 {
                   (*this)(i, j, k, l, m) = source_tensor(i, j, k, l, m);
                 }
               }
             }
           }
         }
       }
       // Return reference to object itself (i.e. de-reference this pointer)
       return *this;
     }
References i, j, k, m, oomph::RankFiveTensor< T >::M, n, oomph::RankFiveTensor< T >::N, oomph::RankFiveTensor< T >::nindex1(), oomph::RankFiveTensor< T >::nindex2(), oomph::RankFiveTensor< T >::nindex3(), oomph::RankFiveTensor< T >::nindex4(), oomph::RankFiveTensor< T >::nindex5(), p, oomph::RankFiveTensor< T >::P, Eigen::numext::q, oomph::RankFiveTensor< T >::Q, UniformPSDSelfTest::r, oomph::RankFiveTensor< T >::R, and oomph::RankFiveTensor< T >::resize().
range_check()
template<class T > void oomph::RankFiveTensor< T >::range_check (const unsigned long & i, const unsigned long & j, const unsigned long & k, const unsigned long & l, const unsigned long & m) const inline private
Range check to catch when an index is out of bounds, if so, it issues a warning message and dies by throwing an OomphLibError
     {
       if (i >= N)
       {
         std::ostringstream error_message;
         error_message << "Range Error: i=" << i << " is not in the range (0,"
                       << N - 1 << ")." << std::endl;
         throw OomphLibError(error_message.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
       else if (j >= M)
       {
         std::ostringstream error_message;
         error_message << "Range Error: j=" << j << " is not in the range (0,"
                       << M - 1 << ")." << std::endl;
         throw OomphLibError(error_message.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
       else if (k >= P)
       {
         std::ostringstream error_message;
         error_message << "Range Error: k=" << k << " is not in the range (0,"
                       << P - 1 << ")." << std::endl;
         throw OomphLibError(error_message.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
       else if (l >= Q)
       {
         std::ostringstream error_message;
         error_message << "Range Error: l=" << l << " is not in the range (0,"
                       << Q - 1 << ")." << std::endl;
         throw OomphLibError(error_message.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
       else if (m >= R)
       {
         std::ostringstream error_message;
         error_message << "Range Error: m=" << m << " is not in the range (0,"
                       << R - 1 << ")." << std::endl;
         throw OomphLibError(error_message.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
     }
References i, j, k, m, oomph::RankFiveTensor< T >::N, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::RankFiveTensor< T >::P, oomph::RankFiveTensor< T >::Q, and oomph::RankFiveTensor< T >::R.
Referenced by oomph::RankFiveTensor< T >::operator()().
raw_direct_access() [1/2]
template<class T > T& oomph::RankFiveTensor< T >::raw_direct_access (const unsigned long & i) inline
Direct access to internal storage of data in flat-packed C-style column-major format. WARNING: Only for experienced users. Only use this if raw speed is of the essence, as in the solid mechanics problems.
     {
       return Tensordata[i];
     }
References i, and oomph::RankFiveTensor< T >::Tensordata.
Referenced by oomph::RefineableQDPVDElement< DIM, NNODE_1D >::fill_in_generic_contribution_to_residuals_pvd(), oomph::RefineablePVDEquations< DIM >::fill_in_generic_contribution_to_residuals_pvd(), oomph::PVDEquations< DIM >::fill_in_generic_contribution_to_residuals_pvd(), oomph::ScaleCoupledElement< ELEMENT >::fill_in_generic_contribution_to_residuals_pvd(), oomph::VolumeCoupledElement< ELEMENT >::fill_in_generic_contribution_to_residuals_pvd(), oomph::RefineablePVDEquationsWithPressure< DIM >::fill_in_generic_residual_contribution_pvd_with_pressure(), and oomph::PVDEquationsWithPressure< DIM >::fill_in_generic_residual_contribution_pvd_with_pressure().
raw_direct_access() [2/2]
template<class T > const T& oomph::RankFiveTensor< T >::raw_direct_access (const unsigned long & i) const inline
Direct access to internal storage of data in flat-packed C-style column-major format. WARNING: Only for experienced users. Only use this if raw speed is of the essence, as in the solid mechanics problems.
     {
       return Tensordata[i];
     }
References i, and oomph::RankFiveTensor< T >::Tensordata.
resize() [1/3]
template<class T > void oomph::RankFiveTensor< T >::resize (const unsigned long & n) inline
Resize to a square nxnxnxn tensor.
     {
       resize(n, n, n, n, n);
     }
References n.
Referenced by oomph::RankFiveTensor< T >::operator=().
resize() [2/3]
template<class T > void oomph::RankFiveTensor< T >::resize (const unsigned long & n_index1, const unsigned long & n_index2, const unsigned long & n_index3, const unsigned long & n_index4, const unsigned long & n_index5) inline
Resize to a general tensor.
     {
       // If the sizes have not changed do nothing
       if ((n_index1 == N) && (n_index2 == M) && (n_index3 == P) &&
           (n_index4 == Q) && (n_index5 == R))
       {
         return;
       }
       // Store old sizes
       unsigned long n_old = N, m_old = M, p_old = P, q_old = Q, r_old = R;
       // Reassign the sizes
       N = n_index1;
       M = n_index2;
       P = n_index3;
       Q = n_index4;
       R = n_index5;
       // Store pointer to old matrix data
       T* temp_tensor = Tensordata;
       // Re-create Tensordata in new size
       Tensordata = new T[N * M * P * Q * R];
 #ifdef OOMPH_INITIALISE_DENSE_MATRICES
       initialise(T(0));
 #endif
       // Transfer values
       unsigned long n_copy, m_copy, p_copy, q_copy, r_copy;
       n_copy = std::min(n_old, n_index1);
       m_copy = std::min(m_old, n_index2);
       p_copy = std::min(p_old, n_index3);
       q_copy = std::min(q_old, n_index4);
       r_copy = std::min(r_old, n_index5);
       // If matrix has values, transfer them to new matrix
       // Loop over rows
       for (unsigned long i = 0; i < n_copy; i++)
       {
         // Loop over columns
         for (unsigned long j = 0; j < m_copy; j++)
         {
           // Loop over columns
           for (unsigned long k = 0; k < p_copy; k++)
           {
             // Loop over columns
             for (unsigned long l = 0; l < q_copy; l++)
             {
               // Loop over columns
               for (unsigned long m = 0; m < r_copy; m++)
               {
                 // Transfer values from temp_tensor
                 Tensordata[R * (Q * (M * P * i + P * j + k) + l) + m] =
                   temp_tensor[r_old *
                                 (q_old * (m_old * p_old * i + p_old * j + k) +
                                  l) +
                               m];
               }
             }
           }
         }
       }
       // Now kill storage for old tensor
       delete[] temp_tensor;
     }
References i, oomph::RankFiveTensor< T >::initialise(), j, k, m, oomph::RankFiveTensor< T >::M, min, oomph::RankFiveTensor< T >::N, oomph::RankFiveTensor< T >::P, oomph::RankFiveTensor< T >::Q, oomph::RankFiveTensor< T >::R, and oomph::RankFiveTensor< T >::Tensordata.
resize() [3/3]
template<class T > void oomph::RankFiveTensor< T >::resize (const unsigned long & n_index1, const unsigned long & n_index2, const unsigned long & n_index3, const unsigned long & n_index4, const unsigned long & n_index5, const T & initial_value) inline
Resize to a general tensor.
     {
       // If the sizes have not changed do nothing
       if ((n_index1 == N) && (n_index2 == M) && (n_index3 == P) &&
           (n_index4 == Q) && (n_index5 == R))
       {
         return;
       }
       // Store old sizes
       unsigned long n_old = N, m_old = M, p_old = P, q_old = Q, r_old = R;
       // Reassign the sizes
       N = n_index1;
       M = n_index2;
       P = n_index3;
       Q = n_index4;
       R = n_index5;
       // Store triple pointer to old matrix data
       T* temp_tensor = Tensordata;
       // Re-create Tensordata in new size
       Tensordata = new T[N * M * P * Q * R];
       // Initialise the newly allocated storage
       initialise(initial_value);
       // Transfer values
       unsigned long n_copy, m_copy, p_copy, q_copy, r_copy;
       n_copy = std::min(n_old, n_index1);
       m_copy = std::min(m_old, n_index2);
       p_copy = std::min(p_old, n_index3);
       q_copy = std::min(q_old, n_index4);
       r_copy = std::min(r_old, n_index5);
       // If matrix has values, transfer them to new matrix
       // Loop over rows
       for (unsigned long i = 0; i < n_copy; i++)
       {
         // Loop over columns
         for (unsigned long j = 0; j < m_copy; j++)
         {
           // Loop over columns
           for (unsigned long k = 0; k < p_copy; k++)
           {
             // Loop over columns
             for (unsigned long l = 0; l < q_copy; l++)
             {
               // Loop over columns
               for (unsigned long m = 0; m < r_copy; m++)
               {
                 // Transfer values from temp_tensor
                 Tensordata[R * (Q * (M * P * i + P * j + k) + l) + m] =
                   temp_tensor[r_old *
                                 (q_old * (m_old * p_old * i + p_old * j + k) +
                                  l) +
                               m];
               }
             }
           }
         }
       }
       // Now kill storage for old tensor
       delete[] temp_tensor;
     }
References i, oomph::RankFiveTensor< T >::initialise(), j, k, m, oomph::RankFiveTensor< T >::M, min, oomph::RankFiveTensor< T >::N, oomph::RankFiveTensor< T >::P, oomph::RankFiveTensor< T >::Q, oomph::RankFiveTensor< T >::R, and oomph::RankFiveTensor< T >::Tensordata.
Member Data Documentation
M
template<class T > unsigned oomph::RankFiveTensor< T >::M private
2nd Tensor dimension
Referenced by oomph::RankFiveTensor< T >::nindex2(), oomph::RankFiveTensor< T >::operator=(), oomph::RankFiveTensor< T >::RankFiveTensor(), and oomph::RankFiveTensor< T >::resize().
N
template<class T > unsigned oomph::RankFiveTensor< T >::N private
1st Tensor dimension
Referenced by oomph::RankFiveTensor< T >::initialise(), oomph::RankFiveTensor< T >::nindex1(), oomph::RankFiveTensor< T >::operator=(), oomph::RankFiveTensor< T >::range_check(), oomph::RankFiveTensor< T >::RankFiveTensor(), and oomph::RankFiveTensor< T >::resize().
P
template<class T > unsigned oomph::RankFiveTensor< T >::P private
3rd Tensor dimension
Referenced by oomph::RankFiveTensor< T >::initialise(), oomph::RankFiveTensor< T >::nindex3(), oomph::RankFiveTensor< T >::offset(), oomph::RankFiveTensor< T >::operator()(), oomph::RankFiveTensor< T >::operator=(), oomph::RankFiveTensor< T >::range_check(), oomph::RankFiveTensor< T >::RankFiveTensor(), and oomph::RankFiveTensor< T >::resize().
Q
template<class T > unsigned oomph::RankFiveTensor< T >::Q private
4th Tensor dimension
Referenced by oomph::RankFiveTensor< T >::initialise(), oomph::RankFiveTensor< T >::nindex4(), oomph::RankFiveTensor< T >::offset(), oomph::RankFiveTensor< T >::operator()(), oomph::RankFiveTensor< T >::operator=(), oomph::RankFiveTensor< T >::range_check(), oomph::RankFiveTensor< T >::RankFiveTensor(), and oomph::RankFiveTensor< T >::resize().
R
template<class T > unsigned oomph::RankFiveTensor< T >::R private
5th Tensor dimension
Referenced by oomph::RankFiveTensor< T >::initialise(), oomph::RankFiveTensor< T >::nindex5(), oomph::RankFiveTensor< T >::offset(), oomph::RankFiveTensor< T >::operator()(), oomph::RankFiveTensor< T >::operator=(), oomph::RankFiveTensor< T >::range_check(), oomph::RankFiveTensor< T >::RankFiveTensor(), and oomph::RankFiveTensor< T >::resize().
Tensordata
template<class T > T* oomph::RankFiveTensor< T >::Tensordata private
Private internal representation as pointer to data.
Referenced by oomph::RankFiveTensor< T >::initialise(), oomph::RankFiveTensor< T >::operator()(), oomph::RankFiveTensor< T >::RankFiveTensor(), oomph::RankFiveTensor< T >::raw_direct_access(), oomph::RankFiveTensor< T >::resize(), and oomph::RankFiveTensor< T >::~RankFiveTensor().
The documentation for this class was generated from the following file:
matrices.h