MercuryDPM: Eigen::internal::transposition_matrix_product< ExpressionType, Side, Transposed, ExpressionShape > Class Template Reference
Eigen::internal::transposition_matrix_product< ExpressionType, Side, Transposed, ExpressionShape > Class Template Reference
#include <ProductEvaluators.h>
Public Types
typedef nested_eval< ExpressionType, 1 >::type MatrixType
typedef remove_all_t< MatrixType > MatrixTypeCleaned
Static Public Member Functions
template<typename Dest , typename TranspositionType >
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void run (Dest &dst, const TranspositionType &tr, const ExpressionType &xpr)
Detailed Description
template<typename ExpressionType, int Side, bool Transposed, typename ExpressionShape>
class Eigen::internal::transposition_matrix_product< ExpressionType, Side, Transposed, ExpressionShape >
Internal helper class implementing the product between a permutation matrix and a matrix.
Member Typedef Documentation
MatrixType
template<typename ExpressionType , int Side, bool Transposed, typename ExpressionShape > typedef nested_eval<ExpressionType, 1>::type Eigen::internal::transposition_matrix_product< ExpressionType, Side, Transposed, ExpressionShape >::MatrixType
MatrixTypeCleaned
template<typename ExpressionType , int Side, bool Transposed, typename ExpressionShape > typedef remove_all_t<MatrixType> Eigen::internal::transposition_matrix_product< ExpressionType, Side, Transposed, ExpressionShape >::MatrixTypeCleaned
Member Function Documentation
run()
template<typename ExpressionType , int Side, bool Transposed, typename ExpressionShape > template<typename Dest , typename TranspositionType > static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::internal::transposition_matrix_product< ExpressionType, Side, Transposed, ExpressionShape >::run (Dest & dst, const TranspositionType & tr, const ExpressionType & xpr) inline static
{
     MatrixType mat(xpr);
     typedef typename TranspositionType::StorageIndex StorageIndex;
     const Index size = tr.size();
     StorageIndex j = 0;
     if (!is_same_dense(dst, mat)) dst = mat;
     for (Index k = (Transposed ? size - 1 : 0); Transposed ? k >= 0 : k < size; Transposed ? --k : ++k)
       if (Index(j = tr.coeff(k)) != k) {
         if (Side == OnTheLeft)
           dst.row(k).swap(dst.row(j));
         else if (Side == OnTheRight)
           dst.col(k).swap(dst.col(j));
       }
   }
References Eigen::internal::is_same_dense(), j, k, Eigen::OnTheLeft, Eigen::OnTheRight, size, and Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::swap().
Referenced by Eigen::internal::generic_product_impl< Lhs, Rhs, TranspositionsShape, MatrixShape, ProductTag >::evalTo(), Eigen::internal::generic_product_impl< Lhs, Rhs, MatrixShape, TranspositionsShape, ProductTag >::evalTo(), Eigen::internal::generic_product_impl< Lhs, Transpose< Rhs >, MatrixShape, TranspositionsShape, ProductTag >::evalTo(), and Eigen::internal::generic_product_impl< Transpose< Lhs >, Rhs, TranspositionsShape, MatrixShape, ProductTag >::evalTo().
The documentation for this class was generated from the following file:
ProductEvaluators.h