MercuryDPM: SinterLinInteraction Class Reference
SinterLinInteraction Class Reference
#include <SinterLinInteraction.h>
Public Types
typedef SinterLinNormalSpecies SpeciesType
An alias for the corresponding species.
Public Member Functions
SinterLinInteraction (BaseInteractable *P, BaseInteractable *I, unsigned timeStamp)
Constructor.
SinterLinInteraction (const SinterLinInteraction &p)
Copy constructor.
SinterLinInteraction ()
~SinterLinInteraction () override
Destructor.
void computeNormalForce ()
Creates a copy of an object of this class. (Deep copy)
void read (std::istream &is) override
Interaction read function, which accepts an std::istream as input.
void write (std::ostream &os) const override
Interaction write function, which accepts an std::ostream as input.
virtual std::string getBaseName () const
Returns the name of the interaction.
Mdouble getElasticEnergy () const override
Computes and returns the amount of elastic energy stored in the spring.
Mdouble getMaxOverlap () const
Mdouble getPlasticOverlap () const
void setMaxOverlap (Mdouble maxOverlap)
void setPlasticOverlap (Mdouble plasticOverlap)
Mdouble getUnloadingStiffness () const
const SinterLinNormalSpecies * getSpecies () const
Returns a const pointer of type LinearViscoelasticNormalSpecies*.
Public Member Functions inherited from BaseInteraction
BaseInteraction (BaseInteractable *P, BaseInteractable *I, unsigned timeStamp)
A constructor takes the BaseInteractable objects which are interacting (come into contact) and time the interaction starts.
BaseInteraction ()
BaseInteraction (const BaseInteraction &p)
Copy constructor.
~BaseInteraction () override
The destructor. It removes this interactions from the objects that were interacting, and writes the time to a file when needed.
virtual void actionsOnErase ()
If an interaction needs to do something before it gets erased, add it here. E.g. Liquid bridges rupture at the end of their lifetime, and the liquid bridge volume has to be redistributed. The reason this action is not done in the destructor is that this action should not be taken when erasing ghost interactions.
virtual void computeForce ()
Virtual function that contains the force law between the two objects interacting.
void writeToFStat (std::ostream &os, Mdouble time) const
Writes forces data to the FStat file.
std::string getName () const override
Virtual function which allows interactions to be named.
void setDistance (Mdouble distance)
Sets the interaction distance between the two interacting objects.
void setNormal (Vec3D normal)
Sets the normal vector between the two interacting objects.
void setOverlap (Mdouble overlap)
Set the overlap between the two interacting object.
void setContactPoint (Vec3D contactPoint)
Set the location of the contact point between the two interacting objects.
void setTimeStamp (unsigned timeStamp)
Updates the time step of the interacting. Note, time steps used to find completed interactions.
void setSpecies (const BaseSpecies *species)
Set the Species of the interaction; note this can either be a Species or MixedSpecies.
void setP (BaseInteractable *P)
Sets the first object involved in the interaction (normally a particle).
void setI (BaseInteractable *I)
Sets the second object involved in the interaction (often particle or wall).
void importP (BaseInteractable *P)
Sets the first object involved in the interaction (normally a particle).
void importI (BaseInteractable *I)
Sets the second object involved in the interaction (often particle or wall).
Vec3D getIP () const
Vec3D getIC () const
Vec3D getCP () const
void setLagrangeMultiplier (Mdouble multiplier)
Mdouble getLagrangeMultiplier ()
void setHandler (InteractionHandler *handler)
Sets the pointer to the interaction hander which is storing this interaction.
InteractionHandler * getHandler () const
Gets a point to the interaction handlers to which this interaction belongs.
const Vec3D & getForce () const
Gets the current force (vector) between the two interacting objects.
const Vec3D & getTorque () const
Gets the current torque (vector) between the two interacting objects.
const Vec3D & getNormal () const
Gets the normal vector between the two interacting objects.
const Vec3D & getContactPoint () const
Gets constant reference to contact point (vector).
Mdouble getOverlap () const
Returns a Mdouble with the current overlap between the two interacting objects.
Mdouble getOverlapVolume () const
Returns the overlap volume between two interacting objects.
Mdouble getContactRadius () const
Returns a Mdouble with the current contact between the two interacting objects.
void removeFromHandler ()
Removes this interaction from its interaction hander.
void copySwitchPointer (const BaseInteractable *original, BaseInteractable *ghost) const
This copies the interactions of the original particle and replaces the original with the ghost copy.
void gatherContactStatistics ()
BaseInteractable * getP ()
Returns a pointer to first object involved in the interaction (normally a particle).
BaseInteractable * getI ()
Returns a pointer to the second object involved in the interaction (often a wall or a particle).
const BaseInteractable * getP () const
Returns a constant pointer to the first object involved in the interaction.
const BaseInteractable * getI () const
Returns a constant pointer to the second object involved in the interaction.
Mdouble getTimeStamp () const
Returns an Mdouble which is the time stamp of the interaction.
virtual void integrate (Mdouble timeStep)
integrates variables of the interaction which need to be integrate e.g. the tangential overlap.
virtual Mdouble getTangentialOverlap () const
get the length of the current tangential overlap
Mdouble getDistance () const
Returns an Mdouble which is the norm (length) of distance vector.
const Vec3D & getRelativeVelocity () const
Returns a constant reference to a vector of relative velocity.
Mdouble getNormalRelativeVelocity () const
Returns a double which is the norm (length) of the relative velocity vector.
Mdouble getAbsoluteNormalForce () const
Returns the absolute value of the norm (length) of the Normal force vector.
virtual BaseInteraction * copy () const =0
Makes a copy of the interaction and returns a pointer to the copy.
void setFStatData (std::fstream &fstat, BaseParticle *P, BaseWall *I)
void setFStatData (std::fstream &fstat, BaseParticle *P, BaseParticle *I)
unsigned int getMultiContactIdentifier () const
void setMultiContactIdentifier (unsigned int multiContactIdentifier_)
virtual void rotateHistory (Matrix3D &rotationMatrix)
When periodic particles are used, some interactions need certain history properties rotated (e.g. tangential springs). This is the function for that.
virtual void actionsAfterTimeStep ()
virtual unsigned getNumberOfFieldsVTK () const
virtual std::string getTypeVTK (unsigned i) const
virtual std::string getNameVTK (unsigned i) const
virtual std::vector< Mdouble > getFieldVTK (unsigned i) const
void addForce (Vec3D force)
add an force increment to the total force.
void addTorque (Vec3D torque)
add a torque increment to the total torque.
void setForce (Vec3D force)
set total force (this is used by the normal force, tangential forces are added use addForce)
void setTorque (Vec3D torque)
set the total force (this is used by the normal force, tangential torques are added use addTorque)
const BaseSpecies * getBaseSpecies () const
Return a constant point to BaseSpecies of the interaction.
virtual void createMPIType ()
virtual void * createMPIInteractionDataArray (unsigned int numberOfInteractions) const
virtual void deleteMPIInteractionDataArray (void *dataArray)
virtual void getMPIInteraction (void *historyDataArray, unsigned int index) const
copies the history interactions into the data array
virtual void getInteractionDetails (void *interactionDataArray, unsigned int index, unsigned int &identificationP, unsigned int &identificationI, bool &isWallInteraction, unsigned &timeStamp)
virtual void setMPIInteraction (void *interactionDataArray, unsigned int index, bool resetPointers)
void setBasicMPIInteractionValues (int P, int I, unsigned timeStamp, Vec3D force, Vec3D torque, bool isWallInteraction, bool resetPointers)
void setIdentificationP (unsigned int identification)
void setIdentificationI (int identification)
void setWallInteraction (bool flag)
unsigned int getIdentificationP ()
int getIdentificationI ()
bool isWallInteraction ()
virtual bool isBonded () const
Public Member Functions inherited from BaseObject
BaseObject ()=default
Default constructor.
BaseObject (const BaseObject &p)=default
Copy constructor, copies all the objects BaseObject contains.
virtual ~BaseObject ()=default
virtual destructor
virtual void moveInHandler (unsigned int index)
Except that it is virtual, it does the same thing as setIndex() does.
void setIndex (unsigned int index)
Allows one to assign an index to an object in the handler/container.
void setId (unsigned long id)
Assigns a unique identifier to each object in the handler (container) which remains constant even after the object is deleted from the container/handler.
unsigned int getIndex () const
Returns the index of the object in the handler.
unsigned int getId () const
Returns the unique identifier of any particular object.
void setGroupId (unsigned groupId)
unsigned getGroupId () const
Private Attributes
Mdouble maxOverlap_
Mdouble plasticOverlap_
Additional Inherited Members
Protected Member Functions inherited from BaseInteraction
virtual const Vec3D getTangentialForce () const
Mdouble getEffectiveRadius () const
Returns a Mdouble to the effective radius of the interaction. (Not corrected for the overlap)
Mdouble getEffectiveMass () const
Returns a Mdouble to the effective radius of the interaction. (Not corrected for the overlap)
void setRelativeVelocity (Vec3D relativeVelocity)
set the relative velocity of the current of the interactions.
void setNormalRelativeVelocity (Mdouble normalRelativeVelocit)
set the normal component of the relative velocity.
void setAbsoluteNormalForce (Mdouble absoluteNormalForce)
the absolute values of the norm (length) of the normal force
virtual Mdouble getElasticEnergyAtEquilibrium (Mdouble adhesiveForce) const
virtual void reverseHistory ()
When periodic particles some interaction need certain history properties reversing. This is the function for that.
void writeInteraction (std::ostream &os, bool created) const
Writes information about a interaction to the interaction file.
Member Typedef Documentation
SpeciesType
typedef SinterLinNormalSpecies SinterLinInteraction::SpeciesType
An alias for the corresponding species.
Constructor & Destructor Documentation
SinterLinInteraction() [1/3]
SinterLinInteraction::SinterLinInteraction (BaseInteractable * P, BaseInteractable * I, unsigned timeStamp)
Constructor.
Parameters
[in] P
[in] I
[in] timeStamp
         : BaseInteraction(P, I, timeStamp)
 {
     plasticOverlap_ = 0;
 #ifdef DEBUG_CONSTRUCTOR
     std::cout<<"LinearPlasticViscoelasticInteraction::LinearPlasticViscoelasticInteraction() finished"<<std::endl;
 #endif
 }
References plasticOverlap_.
SinterLinInteraction() [2/3]
SinterLinInteraction::SinterLinInteraction (const SinterLinInteraction & p)
Copy constructor.
Parameters
[in] p
         : BaseInteraction(p)
 {
     plasticOverlap_ = p.plasticOverlap_;
 #ifdef DEBUG_CONSTRUCTOR
     std::cout<<"LinearPlasticViscoelasticInteraction::LinearPlasticViscoelasticInteraction(const LinearPlasticViscoelasticInteraction &p finished"<<std::endl;
 #endif
 }
References p, and plasticOverlap_.
SinterLinInteraction() [3/3]
SinterLinInteraction::SinterLinInteraction ()
Todo:
: MX add to MPI
         : BaseInteraction()
 {
     plasticOverlap_ = 0;
 #ifdef DEBUG_CONSTRUCTOR
     std::cout<<"LinearPlasticViscoelasticInteraction::LinearPlasticViscoelasticInteraction() finished"<<std::endl;
 #endif
 }
References plasticOverlap_.
~SinterLinInteraction()
SinterLinInteraction::~SinterLinInteraction () override
Destructor.
 {
 #ifdef DEBUG_DESTRUCTOR
     std::cout<<"SinterLinInteraction::~SinterLinInteraction() finished"<<std::endl;
 #endif
 }
Member Function Documentation
computeNormalForce()
void SinterLinInteraction::computeNormalForce ()
Creates a copy of an object of this class. (Deep copy)
Computes the normal forces due to linear plastic visco elastic interaction.
 {
     // Compute the relative velocity vector of particle P w.r.t. I
     setRelativeVelocity(
             getP()->getVelocityAtContact(getContactPoint()) - getI()->getVelocityAtContact(getContactPoint()));
     // Compute the projection of vrel onto the normal (can be negative)
     setNormalRelativeVelocity(Vec3D::dot(getRelativeVelocity(), getNormal()));
     if (getOverlap() > 0) //if contact forces
     {
         const SinterLinNormalSpecies* species = getSpecies();
         // calculate the effective diameter, equal to the radius for two equal-sized particles
         const Mdouble effectiveDiameter = 2.0 * getEffectiveRadius();
         //[1] Compute  delta fluid of equilibrium. In this model, it is the same than delta*
         const Mdouble d_fluid_0 = (species->getUnloadingStiffnessMax()
                                    / (species->getUnloadingStiffnessMax() - species->getLoadingStiffness()))
                                   * species->getPenetrationDepthMax() * effectiveDiameter;
         //[2] Compute the rate d(k2/k1)/d(delta0). To obtain this parameter, the linear relationship
         //between unloading stiffness and maximum overlap is used.
         const Mdouble dk = (species->getUnloadingStiffnessMax()/species->getLoadingStiffness() - 1.0)*(1.0/d_fluid_0);
         //Increase max overlap if necessary
         //Here, two relationships are used. The linear relationship between unloadingstiffness max and
         // the equilibrium overlap based on the unloading stiffness.
         //k2 = k1*(1+dk*d), k1*d = k2*(d-d0)
         //k1*d = k1*(1 + dk*d)*(d-d0)
         //d = d - d0 +dk*d^2 -dk*d*d0
         //dk*d^2 = dk *d * d0 + d0
         //dk*d^2 = (dk*d + 1)*d0
         //dkd^2/(dk*d + 1) = d0
         //d0 = d/(1 + 1/(dk*d))
         //[3] Compute the equilibirum overlap is:
         const Mdouble d0 = getOverlap()/(1.0 + 1.0/(dk*getOverlap()));
         const Mdouble minPlasticOverlap = std::min(d0,d_fluid_0);
         //[4] Determine the plastic overlap
         plasticOverlap_ = std::max(minPlasticOverlap,plasticOverlap_);
         //[5] Compute the unloading Stiffness \hat{k2}.
         const Mdouble unloadingStiffness = species->getLoadingStiffness() * (1.0 + dk * plasticOverlap_);
         //[6] Compute the elastic force
         Mdouble normalForce = unloadingStiffness * (getOverlap() - plasticOverlap_);
         //[7] Add cohesive force (distinct from sinteirng)
         //Decrease plastic overlap if necessary
         Mdouble nonSinterAdhesiveForce = -species->getCohesionStiffness() * getOverlap();
         if (normalForce < nonSinterAdhesiveForce)
         {
             plasticOverlap_ = (1.0 + species->getCohesionStiffness() / unloadingStiffness) * getOverlap();
             normalForce = nonSinterAdhesiveForce;
         }
         //[[8] Add dissipative force
         normalForce -= species->getDissipation() * getNormalRelativeVelocity();
         //[9] Sintering effect as adhesive force:
         Mdouble adhesiveForce = species->getSinterAdhesion() * effectiveDiameter;
 //        Mdouble adhesiveForce = species->getSinterAdhesion();
         //[10] now set the interaction force equal to this normal force (friction and adhesive forces will be added later)
         setForce(getNormal() * ((normalForce - adhesiveForce)));
         setTorque(Vec3D(0.0, 0.0, 0.0));
         //used for tangential force calculations; don't add adhesive force components
         setAbsoluteNormalForce(std::abs(normalForce));
         //[11] Checking the overlap to change sintering model
         //Before this point, the material is unrelaxed, and the contact radious is given by the JKR theory.
         //Ref: The role of viscoelastic adhesive contact in the sintering of polymeric particles
         //Author: Y.Y Lin et al.
         const Mdouble baseNum = (9.0/2.0)*pi*species->getComplianceZero()*species->getSurfTension()/(getEffectiveRadius());
         const Mdouble a0_R = std::pow(2.0*baseNum,1.0/3.0);
         //const Mdouble realOverlap = std::sqrt(getOverlap()/effectiveDiameter);
         DPMBase* dpmBase = getHandler()->getDPMBase();
         Mdouble rateOverlap;
         Mdouble rateOverlap2;
         if (species->getSinterType() == SINTER_APPROACH::FRENKEL)
         {
             rateOverlap = 2.0*normalForce * species->getSinterRate() / species->getSinterAdhesion();
         }
         else if (species->getSinterType() == SINTER_APPROACH::VISCOELASTIC_CONTACT)
         {
             if ((getContactRadius())/getEffectiveRadius() < a0_R)
             {
                 rateOverlap = 0.0; //normalForce / species->getSinterAdhesion();
                 //ToDo: Measure the evolution of the creep compliance: Art.Contact creep compliance of viscoelastic material via nanoindentation
             } else {
                 const Mdouble C1 = std::pow((63 * pow(pi, 3.0) / 16.0), 2.0 / 7.0);
                 const Mdouble C2 = pow((species->getSeparationDis()/ getEffectiveRadius()), 2.0 / 7.0);
                 const Mdouble C3 = species->getFluidity()* species->getSurfTension()/getEffectiveRadius();
                 Mdouble time_s = std::pow(8.0*getOverlap()/(getEffectiveRadius()*C1*C2*std::pow(C3,2.0/7.0)),7.0/2.0);
                 rateOverlap = getEffectiveRadius()*C1*C2*((2.0*std::pow(C3,2.0/7.0))/(7.0*std::pow(time_s,5.0/7.0))) * (normalForce / species->getSinterAdhesion());
                 const Mdouble aVisc_R = std::pow(63.0 * std::pow(pi, 3.0), 1.0 / 5.0) *
                                         std::pow((1.0/8.0)*(species->getSeparationDis())/ (0.5*getEffectiveRadius()), 2.0 / 5.0);
                 if (getContactRadius()/getEffectiveRadius() > aVisc_R)
                 {
                     Mdouble t  = (getOverlap())*(1.0/(4.0* species->getFluidity()* species->getSurfTension()));
                     Mdouble theta = atan(std::pow((8.0* species->getFluidity()* species->getSurfTension()*t)/getEffectiveRadius(),0.5));
                     Mdouble dtheta = (8.0* species->getFluidity()* species->getSurfTension()/getEffectiveRadius());
                     dtheta *= (std::pow(2.0,-5.0/3.0))*cos(theta)*sin(theta);
                     Mdouble K1 = tan(theta)/2.0 - (sin(theta)/6.0)*((2.0*(2.0-cos(theta))+(1.0+cos(theta)))/((1.0+cos(theta)))*(2.0-cos(theta)));
                     dtheta /= std::pow(K1,2.0);
                     dtheta /= (std::pow(2.0-cos(theta),5.0/3.0))*(std::pow(1.0+cos(theta),4.0/3.0));
                     //++++++
                     rateOverlap2 = 2.0*getEffectiveRadius()*std::pow(4.0/(std::pow(1.0+cos(theta),2.0)*(2.0-cos(theta))),2.0/3.0);
                     rateOverlap2 *= sin(theta)*cos(theta)* dtheta;
                     Mdouble term1 = 4.0*std::pow(2.0,1.0/3.0)*std::pow(sin(theta),3.0)*dtheta*(cos(theta)-1.0);
                     Mdouble term2 = std::pow(cos(theta)+1.0,7.0/3.0)*std::pow(-cos(theta)+2.0,5.0/3.0);
                     rateOverlap2 -= term1/term2;
                     rateOverlap2 *= 2.0*getEffectiveRadius()*(normalForce/species->getSinterAdhesion());
                     rateOverlap = rateOverlap2;
                 }
             }
         }
         else{
             rateOverlap = 0.0;
         }
         //[12] Increase plastic overlap due to sintering
         plasticOverlap_ = std::max(0.0, std::min(d_fluid_0, plasticOverlap_ + rateOverlap * dpmBase->getTimeStep()));
     }
     else
     {
         setAbsoluteNormalForce(0.0);
         setForce(Vec3D(0.0, 0.0, 0.0));
         setTorque(Vec3D(0.0, 0.0, 0.0));
     }
 }
References abs(), Eigen::bfloat16_impl::atan(), Global_Physical_Variables::C1, Global_Physical_Variables::C2, cos(), Vec3D::dot(), FRENKEL, SinterLinNormalSpecies::getCohesionStiffness(), SinterLinNormalSpecies::getComplianceZero(), BaseInteraction::getContactPoint(), BaseInteraction::getContactRadius(), SinterLinNormalSpecies::getDissipation(), BaseHandler< T >::getDPMBase(), BaseInteraction::getEffectiveRadius(), SinterLinNormalSpecies::getFluidity(), BaseInteraction::getHandler(), BaseInteraction::getI(), SinterLinNormalSpecies::getLoadingStiffness(), BaseInteraction::getNormal(), BaseInteraction::getNormalRelativeVelocity(), BaseInteraction::getOverlap(), BaseInteraction::getP(), SinterLinNormalSpecies::getPenetrationDepthMax(), BaseInteraction::getRelativeVelocity(), SinterLinNormalSpecies::getSeparationDis(), SinterLinNormalSpecies::getSinterAdhesion(), SinterLinNormalSpecies::getSinterRate(), SinterLinNormalSpecies::getSinterType(), getSpecies(), SinterLinNormalSpecies::getSurfTension(), DPMBase::getTimeStep(), SinterLinNormalSpecies::getUnloadingStiffnessMax(), max, min, constants::pi, plasticOverlap_, Eigen::bfloat16_impl::pow(), BaseInteraction::setAbsoluteNormalForce(), BaseInteraction::setForce(), BaseInteraction::setNormalRelativeVelocity(), BaseInteraction::setRelativeVelocity(), BaseInteraction::setTorque(), sin(), plotPSD::t, Eigen::bfloat16_impl::tan(), BiharmonicTestFunctions2::theta, and VISCOELASTIC_CONTACT.
getBaseName()
std::string SinterLinInteraction::getBaseName () const virtual
Returns the name of the interaction.
Returns
std::string
 {
     return "Sinter";
 }
getElasticEnergy()
Mdouble SinterLinInteraction::getElasticEnergy () const override virtual
Computes and returns the amount of elastic energy stored in the spring.
Returns
Mdouble
Todo:
TW this is not correct; we should count the return energy
Reimplemented from BaseInteraction.
 {
     Mdouble energy = getOverlap() > 0 ? 0.5 * (getSpecies()->getLoadingStiffness() * mathsFunc::square(getOverlap())) : 0.0;
     if (getSpecies()->getConstantRestitution()) energy *= 2.0*getEffectiveMass();
     return energy;
 }
References BaseNormalForce::getConstantRestitution(), BaseInteraction::getEffectiveMass(), SinterLinNormalSpecies::getLoadingStiffness(), BaseInteraction::getOverlap(), getSpecies(), and mathsFunc::square().
getMaxOverlap()
Mdouble SinterLinInteraction::getMaxOverlap () const
Returns
Mdouble plasticOverlap_
 {
     return maxOverlap_;
 }
References maxOverlap_.
Referenced by getUnloadingStiffness().
getPlasticOverlap()
Mdouble SinterLinInteraction::getPlasticOverlap () const
Returns
Mdouble plasticOverlap_
 {
     return plasticOverlap_;
 }
References plasticOverlap_.
getSpecies()
const SinterLinNormalSpecies * SinterLinInteraction::getSpecies () const
Returns a const pointer of type LinearViscoelasticNormalSpecies*.
Returns
const SinterLinNormalSpecies*
 {
     return dynamic_cast<const SinterLinNormalSpecies*>(getBaseSpecies());
 }
References BaseInteraction::getBaseSpecies().
Referenced by computeNormalForce(), getElasticEnergy(), and getUnloadingStiffness().
getUnloadingStiffness()
Mdouble SinterLinInteraction::getUnloadingStiffness () const
Returns
Mdouble
 {
     const SinterLinNormalSpecies* species = getSpecies();
     const Mdouble effectiveDiameter = 2.0 * getEffectiveRadius();
     Mdouble d_max_fluid = (species->getUnloadingStiffnessMax() / (species->getUnloadingStiffnessMax()
                                                                   - species->getLoadingStiffness()))* species->getPenetrationDepthMax() *
                           effectiveDiameter;
     if (getOverlap() > d_max_fluid)
         return species->getUnloadingStiffnessMax();
     else
         return species->getLoadingStiffness() +
                (species->getUnloadingStiffnessMax() - species->getLoadingStiffness()) * getMaxOverlap() / d_max_fluid;
 }
References BaseInteraction::getEffectiveRadius(), SinterLinNormalSpecies::getLoadingStiffness(), getMaxOverlap(), BaseInteraction::getOverlap(), SinterLinNormalSpecies::getPenetrationDepthMax(), getSpecies(), and SinterLinNormalSpecies::getUnloadingStiffnessMax().
read()
void SinterLinInteraction::read (std::istream & is) override virtual
Interaction read function, which accepts an std::istream as input.
Calls the read function of BaseInteraction().
Parameters
[in,out] is
Reimplemented from BaseInteraction.
 {
     BaseInteraction::read(is);
     std::string dummy;
     is >> dummy >> plasticOverlap_;
     //helpers::readOptionalVariable<Mdouble>(is, "maxOverlap", maxOverlap_);
 }
References plasticOverlap_, BaseInteraction::read(), and oomph::Global_string_for_annotation::string().
setMaxOverlap()
void SinterLinInteraction::setMaxOverlap (Mdouble maxOverlap)
Parameters
[in] maxOverlap
 {
     maxOverlap_ = maxOverlap;
 }
References maxOverlap_.
setPlasticOverlap()
void SinterLinInteraction::setPlasticOverlap (Mdouble plasticOverlap)
Parameters
[in] maxOverlap
 {
     plasticOverlap_ = plasticOverlap;
 }
References plasticOverlap_.
write()
void SinterLinInteraction::write (std::ostream & os) const override virtual
Interaction write function, which accepts an std::ostream as input.
Calls the write function of BaseInteraction().
Parameters
[in,out] os
Reimplemented from BaseInteraction.
 {
     BaseInteraction::write(os);
     os << " plasticOverlap " << plasticOverlap_;
 }
References plasticOverlap_, and BaseInteraction::write().
Member Data Documentation
maxOverlap_
Mdouble SinterLinInteraction::maxOverlap_ private
Referenced by getMaxOverlap(), and setMaxOverlap().
plasticOverlap_
Mdouble SinterLinInteraction::plasticOverlap_ private
Referenced by computeNormalForce(), getPlasticOverlap(), read(), setPlasticOverlap(), SinterLinInteraction(), and write().
The documentation for this class was generated from the following files:
SinterLinInteraction.h
SinterLinInteraction.cc